### ISSUE TITLE
s3.createPresignedPost support doesn't exist in v3

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#1001]
**Is your feature request related to a problem? Please describe.**
* s3.createPresignedPost support doesn't exist in v3
* for v2, it was added in PR https://github.com/aws/aws-sdk-js/pull/1350

**Describe the solution you'd like**
Support for createPresignedPost in v3

**Describe alternatives you've considered**
Manually writing createPresignedPost function

**Comment by AllanFly120** [comment]
Duplicated with #395
