### ISSUE TITLE
Feature request: Fetch HTTP Handler `keepalive` or `navigator.sendBeacon()` support

### ISSUE THREAD

**Issue by roborourke** [aws/aws-sdk-js-v3#1003]
Hi, first of all feel free to close this issue as it's probably not the right place, although it is specifically javascript related.

First I'll describe my specific use-case which is the Pinpoint Client. In web browsers we ideally want to log the `_session.stop` event when the page is unloaded, however any standard async HTTP request will most likely be dropped if triggered on `unload` or even `beforeunload` before it is completed. This makes it hard to gather accurate metrics for time on page, active sessions etc...

Most browsers have support for the `navigator.sendBeacon()` function that allows for sending asynchronous data to a URL without blocking or slowing down the page's unload event.

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon

The issue here is that `sendBeacon()` is limited in the following ways:

- can only make a `POST` request
- data must be sent using a `FormData` object or similar so you can't just send a JSON payload

The current workaround is to use a proxy eg, the server or a lambda function to receive the simple request from `sendBeacon()` and use the AWS SDK to call `putEvents()` but this isn't ideal - it adds to running costs for one and for an analytics service would be great to support this natively.

The second option I looked into was using the `Request` object's `keepalive` property. Current the `fetch-http-handler` package doesn't let you set this, even using middleware. I was hoping I could use URL pre-signing to authenticate the `putEvents` request with `keepalive` set to true but I haven't been successful, I'm not sure if it's even possible with Pinpoint. `keepalive` only works when you can [make a simple request without preflight as detailed here](https://blog.morethancode.dev/killing-cors-preflight-requests-on-a-react-spa/)

So I'm aware this feature request isn't straightforward at all, as it may involve changes to the service itself. I'm hoping it's something that's at least achievable using middleware and could just be documented.

Thanks for your time!

**Comment by AllanFly120** [comment]
We will investigate using `keepAlive` option. Currently the option is set in Node http handler but missed in [Fetch http handler](https://github.com/aws/aws-sdk-js-v3/blob/a239010d8946b2ac1cc1d74b40085fe4343b16be/packages/fetch-http-handler/src/fetch-http-handler.ts#L35).

**Comment by trivikr** [comment]
keepAlive was set to true in node-http-handler in https://github.com/aws/aws-sdk-js-v3/pull/307

**Comment by roborourke** [comment]
Thanks @AllanFly120. It's not surprising - using `keepAlive` with Fetch is not straightforward. I'm not sure if all AWS API endpoints can receive simple requests using query string authentication.

**Comment by anishd19** [comment]
+1

**Comment by FinestV** [comment]
+1 Need Beacon support for the Evidently client. For any client capturing analytics this is a must have.

**Comment by kuhe** [comment]
keepAlive is now an option in the `@smithy/fetch-http-handler`@2.2.3

```js
import { FetchHttpHandler } from '@smithy/fetch-http-handler';
import { S3Client } from '@aws-sdk/client-s3'; 

new S3Client({
  requestHandler: new FetchHttpHandler({ keepAlive: true }) // same interface for any JSv3 client
});
```

**Comment by roborourke** [comment]
Thank you @kuhe!
