### ISSUE TITLE
AWS.Polly.Presigner class with getSynthesizeSpeechUrl method

### ISSUE THREAD

**Issue by gyandeeps** [aws/aws-sdk-js-v3#1005]
**Is your feature request related to a problem? Please describe.**

I am trying to get an url for the audio based on polly. I know i can do that using the api but was not able to find that api here.

**Describe the solution you'd like**

Design `AWS.Polly.Presigner` class as designed in `aws-sdk`.

Link: https://github.com/aws/aws-sdk-js/blob/cc29728c1c4178969ebabe3bbe6b6f3159436394/lib/polly/presigner.js

**Describe alternatives you've considered**
n/a

**Additional context**

https://github.com/aws/aws-sdk-js/blob/cc29728c1c4178969ebabe3bbe6b6f3159436394/lib/polly/presigner.js

Is their a plan to do this in the future?

**Comment by AllanFly120** [comment]
@gyandeeps 
Thank you for bringing this up. I will add this to our GA tasks.

**Comment by alexforsyth** [comment]
Addressing this with https://github.com/aws/aws-sdk-js-v3/pull/1612
