### ISSUE TITLE
[signature-v4] change signature apiName from sign to sign<T> for <T>Signer

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#1010]
**Is your feature request related to a problem? Please describe.**
* The overloaded sign function in signature-v4 is difficult to understand https://github.com/aws/aws-sdk-js-v3/blob/22900d4f888b1f853b1fa38bd095b6a75385a905/packages/signature-v4/src/SignatureV4.ts#L192-L234
* It was added in PR https://github.com/aws/aws-sdk-js-v3/pull/80

**Describe the solution you'd like**
* change apiName from `sign` to `signRequest` for `RequestSigner` https://github.com/aws/aws-sdk-js-v3/blob/22900d4f888b1f853b1fa38bd095b6a75385a905/packages/types/src/signature.ts#L65-L73
* change apiName from `sign` to `signString` for `StringSigner` https://github.com/aws/aws-sdk-js-v3/blob/22900d4f888b1f853b1fa38bd095b6a75385a905/packages/types/src/signature.ts#L75-L81

**Additional context**
* The sign api for `RequestPresigner` is `presignRequest` https://github.com/aws/aws-sdk-js-v3/blob/22900d4f888b1f853b1fa38bd095b6a75385a905/packages/types/src/signature.ts#L42-L59
* The sign api for `EventSigner` is `signEvent` https://github.com/aws/aws-sdk-js-v3/blob/22900d4f888b1f853b1fa38bd095b6a75385a905/packages/types/src/signature.ts#L87-L95

**Comment by AllanFly120** [comment]
I don’t think it’s a good idea:
1. Why repeat the typename in method name, it’s very redundant. https://csharpcodingguidelines.com/naming-guidelines/#AV1710 This is C# coding guideline but you get the idea. Generally it's not a good practice
2. Method overloading is very commen in V3 SDK, I don’t think it’s complicated. We use it also in service clients.
3. ’sign’ with overloading can reduce the interfaces surface area, make the interface cleaner. I prefer no matter what RequestSigner/StringSigner/EventSigner, they only need to implement a 'sign()'. I should have change signEvent to sign too.

**Comment by trivikr** [comment]
Some findings about Method overloading:
* Method overloading in TypeScript Handbook https://www.typescriptlang.org/docs/handbook/functions.html#overloads
* Although async is supported in TypeScript method overloading, it doesn't plan to throw compile time errors if async modified is not mentioned https://github.com/microsoft/TypeScript/issues/34698#issuecomment-548073160

Tested the following function in TypeScript playground: https://tiny.amazon.com/yd2bse5
```typescript
async function checkType(param: number): Promise<number>;
async function checkType(param: string): Promise<string>;
async function checkType(param: any): Promise<any> {
  if (typeof param === "number") {
    return "number";
  } else if (typeof param === "string") {
    return "string";
  }
  return "error";
}

(async () => {
  console.log(await checkType(5));
  console.log(await checkType("five"));
  console.log(await checkType({}));
})();

```

**Comment by trivikr** [comment]
Superseded by:
* https://github.com/aws/aws-sdk-js-v3/issues/1011
* https://github.com/aws/aws-sdk-js-v3/issues/1012
