### ISSUE TITLE
IAM service uses invalid region.

### ISSUE THREAD

**Issue by Soni96pl** [aws/aws-sdk-js-v3#1024]
**Describe the bug**
IAM backend outside of GovCloud requires credentials to be scoped to `us-east-1` however IAM service scopes them to default region set in the profile causing them to fail with:
```
index.js:1 SignatureDoesNotMatch: Credential should be scoped to a valid region, not 'ap-southeast-1'.
    at QueryParser.exports.queryErrorUnmarshaller [as parseServiceException] (/Volumes/Data/Projects/spq-tools/aws-refresh-token/node_modules/@aws-sdk/query-error-unmarshaller/build/index.js:46:58)
    at /Volumes/Data/Projects/spq-tools/aws-refresh-token/node_modules/@aws-sdk/protocol-query/build/QueryParser.js:18:29
```
Adding `region: us-east-1` to `IAM` constructor fixes the issue.

**SDK version number**

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`

**To Reproduce (observed behavior)**
* Configure AWS with a different region than `us-east-1` using `aws configure` (in my case it's `ap-southeast-1`)
```
const { IAM } = require('@aws-sdk/client-iam-node');
const iam = new IAM({ region: 'us-east-1', endpoint: 'https://iam.amazonaws.com' });
iam.listMFADevices({}).then(console.log).catch(console.error);
```

**Expected behavior**
`IAM` uses the correct region, matching backend.

**Additional context**
To actually initialize and interact with IAM we need to set both region and endpoint:
```
const iam = new IAM({ region: 'us-east-1', endpoint: 'https://iam.amazonaws.com' });
```

Related issue: #373

**Comment by AllanFly120** [comment]
Hi, 

This issue has been fixed in our newest beta clients. Please refer to #944 for more information. Please let me know if this issue needs to be reopened.
