### ISSUE TITLE
Use ts-jest so that test files can be run without transpiling

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#1032]
**Is your feature request related to a problem? Please describe.**
The test files `*.spec.ts` are currently transpiled to JavaScript before being run

**Describe the solution you'd like**
Use ts-jest so that `*.spec.ts` files can be run without transpiling

**Describe alternatives you've considered**
Continue transpiling files before running tests

**Comment by trivikr** [comment]
compilerOptions.paths needs to be set up in order to use ts-jest:
* Documentation: https://kulshekhar.github.io/ts-jest/user/config/#paths-mapping
* Related: https://github.com/aws/aws-sdk-js-v3/issues/1026

**Comment by Syy0n** [comment]
https://jestjs.io/blog/2019/01/25/jest-24-refreshing-polished-typescript-friendly
jest v24+ already has native support for typescript.

**Comment by trivikr** [comment]
> One caveat to the default TypeScript support, similar to Flow, is that Babel will only strip out the type annotations to make your code valid JavaScript. It will not typecheck your code. 
> If you want to run typechecks while you test, you should use ts-jest

The native support for TypeScript in Jest 24+ won't typecheck the code.
