### ISSUE TITLE
Rename expiration (number) to expireTime (date) in Credentials

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#1037]
**Is your feature request related to a problem? Please describe.**
The expireTime (Date) in v2 is changed to expiration (number) in v3
* v2:
  * [docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Credentials.html#expireTime-property)
  * [code](https://github.com/aws/aws-sdk-js/blob/2f5261f46eb95a33ddb72ba27a6f7304e4f9ded9/lib/credentials.d.ts#L57-L61)
* v3: 
  * [code](https://github.com/aws/aws-sdk-js-v3/blob/845e25f61818e38030900c072dab510f2104507c/packages/types/src/credentials.ts#L23-L27)

**Describe the solution you'd like**
Rename expiration (number) to expireTime (date) in Credentials

**Comment by trivikr** [comment]
In v3, credentials had expiration from the beginning (added in https://github.com/aws/aws-sdk-js-v3/pull/4)

**Comment by trivikr** [comment]
botocore (used in AWS CLI and python SDK) uses `expiry_time` which is a string in ISO format ([code](https://github.com/boto/botocore/blob/07f09132df5104bcc5fca6c5772fab02d6c4cd2a/botocore/credentials.py#L202-L207))

**Comment by trivikr** [comment]
AWS SDK for Java v2 uses param `staleTime` of type `java.time.Instant` ([code](https://github.com/aws/aws-sdk-java-v2/search?q=staleTime&type=))

**Comment by trivikr** [comment]
STS [GetSessionToken API](https://docs.aws.amazon.com/STS/latest/APIReference/API_GetSessionToken.html) returns expiration time in `Expiration` key which is of type `Date` in JavaScript SDK ([docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/STS.html#getSessionToken-property))

**Comment by AllanFly120** [comment]
I don't think users will by any chance touch the interface manually. What's the benefit of this change?

**Comment by trivikr** [comment]
> What's the benefit of this change?

* The name `expireTime`, `expiryTime` or `expirationTime` is more accurate of the value in param, than name `expiration`
* If the type is `Date`, it'll need less type conversions
  * in credential-provider-cognito-identity fromCognitoIdentity.ts https://github.com/aws/aws-sdk-js-v3/blob/97ebfda87ac4e484e9f389a8d1e3bff3c17cef6b/packages/credential-provider-cognito-identity/src/fromCognitoIdentity.ts#L38-L40
  * in credential-provider-env fromEnv.ts https://github.com/aws/aws-sdk-js-v3/blob/97ebfda87ac4e484e9f389a8d1e3bff3c17cef6b/packages/credential-provider-env/src/index.ts#L24
  * in credential-provider-imds ImdsCredentials.ts https://github.com/aws/aws-sdk-js-v3/blob/97ebfda87ac4e484e9f389a8d1e3bff3c17cef6b/packages/credential-provider-imds/src/remoteProvider/ImdsCredentials.ts#L26
