### ISSUE TITLE
Comprehend client is not working: ValidationException

### ISSUE THREAD

**Issue by maxgr0** [aws/aws-sdk-js-v3#1061]
**Describe the bug**
The Comprehend client throws a `ValidationException` on each request. The same request run with the v2 client is working as expected.

**SDK version number**
1.0.0-alpha.1

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
13.4.0

**To Reproduce (observed behavior)**
Created a gist which includes the code and error messages:
https://gist.github.com/maxgr0/9ad39d6daba60cdf62d50013b71883f5

**Expected behavior**
The v3 client should work without any exception.

**Comment by trivikr** [comment]
Thank you @maxgr0 for the report.
Is this issue reproducible with `@aws-sdk/client-comprehend@beta`?

**Comment by maxgr0** [comment]
> Thank you @maxgr0 for the report.
> Is this issue reproducible with `@aws-sdk/client-comprehend@beta`?

works!
