### ISSUE TITLE
s3-request-presigner example does not work as written

### ISSUE THREAD

**Issue by gavinpc-mindgrub** [aws/aws-sdk-js-v3#1063]
The [s3-request-presigner](https://github.com/aws/aws-sdk-js-v3/tree/master/packages/s3-request-presigner) has one example, which does not work as intended.  The TypeScript version is copied here for reference (with one annotation):

```typescript
import { S3RequestPresigner } from "@aws-sdk/s3-request-presigner";
import { Sha256 as browserSha256 } from "@aws-crypto/sha256-browser";
import { Hash as nodeSha256 } from "@aws-sdk/hash-node";
const signer = new S3RequestPresigner({
  region: regionProvider,
  credentials: credentialsProvider,
  sha256: nodeSha256 //if the signer is used in browser, use `browserSha256` then
  // ^ this passes the TypeScript compiler, but fails to sign
});
const url = await signer.presign(request);
```

As written, the `presign` call will yield an error like this:

```
Error: Digest method not supported
      at new Hash (internal/crypto/hash.js:48:19)
```

which traces to this:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "algorithm" argument must be of type string. Received undefined
```

The `Hash` class exported by `@aws-sdk/hash-node` can't be used as the `sha256` property of the signer because its constructor expects an algorithm identifier as its first argument, as seen [here](https://github.com/aws/aws-sdk-js-v3/blob/master/packages/hash-node/src/index.ts#L9):

```typescript
export class Hash implements IHash {
  private readonly hash: NodeHash | Hmac;

  constructor(algorithmIdentifier: string, secret?: SourceData) {
    this.hash = secret
      ? createHmac(algorithmIdentifier, castSourceData(secret))
      : createHash(algorithmIdentifier);
  }
```

Whereas, the signer's `sha256` expects a `HashConstructor` interface that takes an optional secret as its only constructor argument.

Based on these findings, I found that the example worked as intended when using the following shim

```typescript
class Sha256 extends Hash {
  constructor(secret?: string | ArrayBuffer | ArrayBufferView) {
    super("sha256", secret);
  }
}
```

as the `sha256` option to the `S3RequestPresigner` constructor, rather than taking `Hash` directly from `@aws-sdk/node-hash`.

**Comment by gavinpc-mindgrub** [comment]
Regarding a mitigation, I would be happy to PR an update to the README, but it's not clear that the mismatch in interfaces is intentional here.  Can someone confirm that `Hash` is not expected to implement `HashConstructor`?

**Comment by AllanZhengYP** [comment]
@gavinpc-mindgrub Thanks a lot for pointing this out. I will update the readme.

**Comment by gavinpc-mindgrub** [comment]
Thanks, y'all!
