### ISSUE TITLE
[Prod] Configuration option "tls" is not honored in http handlers

### ISSUE THREAD

**Issue by Amplifiyer** [aws/aws-sdk-js-v3#1084]
**Describe the bug**
Providing a custom `endpoint` and a `tls: false` configuration options to clients still result in "https" protocol to be used in the[ fetch-http-handler](https://github.com/aws/aws-sdk-js-v3/blob/v1.0.0-beta.3/packages/fetch-http-handler/src/fetch-http-handler.ts#L57-L60).

This is causing issues while setting localhost server as mock servers for S3 since local mock server is only running on http protocol. Related issue: https://github.com/aws-amplify/amplify-js/issues/5320

**SDK version number** 
Beta.3

**Is the issue in the browser/Node.js?**
Browser

**To Reproduce (observed behavior)**
Pass the following configuration options to any client and check the request made in the network tab has https protocol

```
endpoint: "http:localhost:8080",
tls: false,
forcePathStyle: true
```

**Expected behavior**
http-handler (fetch or a custom provided one) should use the right http protocol based on tls flag or from the endpoint value (aws-sdk V2).

**Comment by sammartinez** [comment]
@AllanFly120 Any update on this ticket? Just wanted to understand where it was at

**Comment by AllanFly120** [comment]
I have confirmed a root cause: https://github.com/awslabs/smithy-typescript/issues/158. I will be working on a fix

**Comment by Amplifiyer** [comment]
@AllanFly120, has this been released?
