### ISSUE TITLE
Enable getting OIDC token from Auth module without using cognito hosted UI

### ISSUE THREAD

**Issue by zedsinn** [aws/aws-sdk-js-v3#1090]
**Is your feature request related to a problem? Please describe.**
It was previously not possible in amplify 2 to get an OIDC token when using the Vue authenticator which has a far nicer UI than then hosted UI.

**Describe the solution you'd like**
A way of getting an OIDC enabled token by calling the Auth component of amplify without having to use the cognito hosted UI.

**Describe alternatives you've considered**
An alternative would be to enable more customization of the cognito hosted UI, and/or allowing it to be hosted in an iframe or a lightbox, as currently it's very limited.

**Additional context**
I'm looking to get an OIDC token in my Vue-based front end, so that I can use it to log in an oauth2 enabled appclient running in an iframe.

**Comment by zedsinn** [comment]
Something along the lines of what is being asked for here, but with the js implementation of amplify: https://github.com/aws-amplify/aws-sdk-android/issues/684

**Comment by zsid** [comment]
I really need this feature as well
