### ISSUE TITLE
Eventstream-serde-browser package not compiling modules to commonjs like all other packages

### ISSUE THREAD

**Issue by juniorclarke** [aws/aws-sdk-js-v3#1099]
All packages set their compilerOptions.module to "commonjs" except "eventstream-serde-browser".

https://github.com/aws/aws-sdk-js-v3/blob/3dfb40f7371d0c0c4199c4dbb5b62e74bd45a3d8/packages/eventstream-serde-browser/tsconfig.json#L4

This causes the build file to export non standard import statements that is not the same across all packages. Please keep all packages standard by setting compilerOptions.module to "commonjs" in "eventstream-serde-browser"

Here are a few examples:
https://github.com/aws/aws-sdk-js-v3/blob/3dfb40f7371d0c0c4199c4dbb5b62e74bd45a3d8/packages/eventstream-serde-config-resolver/tsconfig.json#L4

https://github.com/aws/aws-sdk-js-v3/blob/3dfb40f7371d0c0c4199c4dbb5b62e74bd45a3d8/packages/s3-request-presigner/tsconfig.json#L4

https://github.com/aws/aws-sdk-js-v3/blob/3dfb40f7371d0c0c4199c4dbb5b62e74bd45a3d8/packages/types/tsconfig.json#L3

@AllanFly120 @jeskew @trivikr

**Comment by Amplifiyer** [comment]
@AllanFly120 This is root cause of two other Amplify issues https://github.com/aws-amplify/amplify-js/issues/5582 and https://github.com/aws-amplify/amplify-js/issues/5405
