### ISSUE TITLE
DynamoDB Converter

### ISSUE THREAD

**Issue by fishcharlie** [aws/aws-sdk-js-v3#1102]
**Is your feature request related to a problem? Please describe.**

`AWS.DynamoDB.Converter` from v2 doesn't seem to exist.

**Describe the solution you'd like**

`AWS.DynamoDB.Converter` should be added to v3.

**Describe alternatives you've considered**

None

**Additional context**

NA

**Comment by AllanFly120** [comment]
Hi @fishcharlie 

Thank you for the feedback! The is a valid feature request. Currently, we are working on porting some useful features in V2 SDK to the V3. This is undoubtedly our goal before releasing `1.0`. I will keep this issue and will provide more updates when we start implementing it.

**Comment by AaronHarris** [comment]
With that said, one of the big uses of converter was marshalling/unmarshalling between DynamoDB types and native JavaScript types outside of the Document Client. One gap in this was the *Number Set*, *String Set*, and *Binary Set* types, which required manually calling the createSet() function. Can we also add support for correct handling of **Map** and **Set** objects, which are now native in all ES implementations.

**Comment by fishcharlie** [comment]
@AaronHarris So just to provide more context. I help maintain [dynamoose](https://dynamoosejs.com). So for things like converting keys to use in `getItem`, converting objects for `putItem`, etc, we use `DynamoDB.Converter` (https://github.com/dynamoose/dynamoose/blob/master/lib/aws/converter.ts).

Now. I haven't looked into Document Client very much yet. But that looks like a **massive** rewrite for what we are doing. Almost all of our operations will need to be converted to Document Client. It's not just a matter of changing the function we call. The parameters and everything are different.

Now we have gotten comments about DAX (https://github.com/dynamoose/dynamoose/issues/764). But I'm a bit lost here. The documentation regarding DAX is very unclear. Is migrating to Document Client all you need to do to support DAX? Is there anyway to support DAX without Document Client? Gotta look into these questions more in the future. But I have higher things on my priority list.

So I disagree that it's just a simple transition. For a project like this one, migrating to Document Client would be a massive undertaking from what I've seen. If AWS is still supporting the existing methods (outside of Document Client), they should support Converter. If it was a simple transition I'd happily accept no Converter, and migrate to Document Client. But that isn't the reality of the situation here.

> Can we also add support for correct handling of Map and Set objects, which are now native in all ES implementations?

Sounds like potentially a different issue 😛

**Comment by fishcharlie** [comment]
@AllanZhengYP It looks like the release candidate has been released (https://aws.amazon.com/blogs/developer/modular-aws-sdk-for-javascript-release-candidate/). You mentioned the goal was to get this done before `1.0`.

Is that still the goal? Any chance you could update us on the roadmap in regards to this?

**Comment by trivikr** [comment]
@fishcharlie @AaronHarris 

In v3, we have exposed utility functions to operate with JavaScript objects in [@aws-sdk/util-dynamodb](https://www.npmjs.com/package/@aws-sdk/util-dynamodb). You can refer our [Developer Guide on using DynamoDB utilities](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/dynamodb-example-dynamodb-utilities.html).
