### ISSUE TITLE
Instantiating a CognitoIdentityClient with credentials

### ISSUE THREAD

**Issue by JohnWelle** [aws/aws-sdk-js-v3#1114]
**Describe the issue with documentation**
I'm having trouble instantiating a `CognitoIdentityClient` with credentials. If I understand v3 correctly, this is needed so that in subsequent operations (for instance fetching a list of S3 buckets) the client can be passed in via `fromCognitoIdentityPool`.

How is this done? I attempted to use `GetCredentialsForIdentityCommand` to generate credentials but the class does not match the type signature for the `credentials` parameter of the `CognitoIdentityClient` class.

**To Reproduce (observed behavior)**
```typescript
const credentials = new GetCredentialsForIdentityCommand({
  IdentityId: identityPool, // eu-west-1-....
  Logins: loginData, // { cognito-idp.eu-west-1.amazonaws.com/eu_west_1_...: id_token }
})
const client = new CognitoIdentityClient({ region, credentials }) // <-- this doesn't work...

const S3 = new S3Client({
  region,
  credentials: fromCognitoIdentityPool({
    client,
    identityPoolId: identityPool
  })
})

const response = await S3.send(new ListBucketsCommand({}))
```

**Expected behavior**
In v2 SDK, I can achieve the desired effect (set credentials, access services) by doing the following:

```typescript
import AWS_S3 from 'aws-sdk/clients/s3'
import * as AWS from 'aws-sdk/global'

const region = 'eu-west-1'
let identityPool = `${region}:...`
let cognitoIdp = `cognito-idp.${region}.amazonaws.com/${region}_...`
const idToken = getFromCookie(Paths.ID_TOKEN) // JWT token

const loginData = {
  [cognitoIdp]: idToken
}

AWS.config.region = region

AWS.config.credentials = new AWS.CognitoIdentityCredentials({
  IdentityPoolId: identityPool,
  Logins: loginData,
  LoginId: 'myemail@email.com'
})

await new Promise((resolve, reject) => {
  const s3 = new AWS_S3()
  s3.listBuckets((error?: Error, response?: any) => {
    if (error) {
      reject(error)
    } 
    console.log(response)
    resolve(response)
  })
})
```
How can I achieve the same using v3?

**Screenshots**
![image](https://user-images.githubusercontent.com/5860390/80386032-23d06f80-88a7-11ea-9250-dc81b28a65f8.png)

**Additional context**
Browser implementation.

**Comment by AllanFly120** [comment]
Hi @JohnWelle 

We are still working on the API reference so sorry for the confusions. Here's my (untested) example:

```javascript
    const region = 'eu-west-1'
    let identityPool = `${region}:...`
    const idToken = getFromCookie(Paths.ID_TOKEN) // JWT token
    const loginData = {
    [cognitoIdp]: idToken
    }
    const client = new S3Client({
        region,
        credentials: fromCognitoIdentityPool({
            client: new CognitoIdentityClient({region}),
            logins: loginData,
            identityPoolId: identityPool,
            userIdentifier: 'myemail@email.com' // equivalent to loginId
        })
    });
 ```

**Comment by JohnWelle** [comment]
Thanks for following up @AllanFly120.

With your example, I'm getting a compile error:

![image](https://user-images.githubusercontent.com/5860390/80585311-6adb7380-8a13-11ea-9a74-6e0bae44f8dc.png)

I'm not quite sure what is happening here, the error is a little cryptic, seems to be complaining about a dynamic import?

By adding a `@ts-ignore` comment, the code compiles, but I'm getting the following runtime error when trying to set up the client:

![image](https://user-images.githubusercontent.com/5860390/80585554-d6bddc00-8a13-11ea-88db-c74cc066c1b9.png)

Maybe I'm importing the client incorrectly?
```typescript
import { CognitoIdentityClient } from "@aws-sdk/client-cognito-identity"
```

package.json:
```json
"@aws-sdk/client-cognito-identity": "^1.0.0-beta.5"
```

**Comment by AllanFly120** [comment]
Hi @JohnWelle 

Can you check the version of `@aws-sdk/credential-provider-cognito-identity` package? From the stack trace, I can see you are sigining client from `@aws-sdk/client-cognito-identity` to parameters typed with client type from deprecated preview client `@aws-sdk/client-cognito-identity-browser`. 

Can you try updating all the dependencies from `@aws-sdk` org to newest beta version?

**Comment by JohnWelle** [comment]
@AllanFly120, thanks, that did indeed resolve the problem!
