### ISSUE TITLE
Interacting with Local DynamoDb fails

### ISSUE THREAD

**Issue by ignaciofuentes** [aws/aws-sdk-js-v3#1128]
**Describe the bug**
The new SDK (either DynamoDb or DynamoDbClient) fails to interact with a local DynamoDb installation

**SDK version number**
    "@aws-sdk/client-dynamodb": "^1.0.0-beta.5",

**Is the issue in the browser/Node.js?**
Node

**Details of the browser/Node.js version**
v10.16.3

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)
This does not work
```
app.get("/betasdk", async (req, res) => {
  //v3 sdk
  const client = new DynamoDBClient({
    region: "localhost",
    endpoint: "http://localhost:8000",
    credentials: {
      accessKeyId: "somelocalkeyid",
      secretAccessKey: "somelocalaccesskey",
    },
  });
  const command = new ListTablesCommand({});
  try {
    const results = await client.send(command);
    console.log(results.TableNames);
    res.send(results.TableNames);
  } catch (err) {
    console.error(err);
    res.send(err);
  }
});
```

The error is

> {"errno":"EPROTO","code":"EPROTO","syscall":"write","$metadata":{"retries":0,"totalRetryDelay":0}}

Using the v2 sdk works just fine
```
app.get("/", (req, res) => {
  //v2 sdk
  // Set the config
  AWS.config.update({
    region: "localhost",
    endpoint: "http://localhost:8000",
    credentials: {
      accessKeyId: "somelocalkeyid",
      secretAccessKey: "somelocalaccesskey",
    },
  });
  // Create the DynamoDB service object
  var client = new AWS.DynamoDB();
  client.listTables(function (err, data) {
    if (err) {
      console.error(err);
      res.send(err);
    } else {
      console.log(data);
      res.send(data.TableNames);
    }
  });
});
```

**Expected behavior**
A successful response.

**Comment by fboudra** [comment]
still broken on 1.0.0-gamma.2

**Comment by alexforsyth** [comment]
Looks like this is resolved on the most recent version of the SDK: https://github.com/aws/aws-sdk-js-v3/issues/1189
