### ISSUE TITLE
Add docs for suggested ways to mock AWS requests when testing with this package

### ISSUE THREAD

**Issue by mizzao** [aws/aws-sdk-js-v3#1156]
When using the AWS API in a project, it's important to be able to run tests without actually making S3 requests. For many HTTP requests these can be mocked, e.g. with [nock](https://github.com/nock/nock/). But it's complicated to intercept AWS requests at the HTTP level.

The [previous version of the SDK](https://github.com/aws/aws-sdk-js) has a pretty well-supported mocking library, [aws-sdk-mock](https://github.com/dwyl/aws-sdk-mock). Have you given any thought to how mocking would work for this SDK? Without being able to run tests easily, it'll be hard to switch over and start using this package.

Any documentation or suggestions on how to succinctly set up mocking using this v3 SDK would be great.

**Comment by monken** [comment]
We started using v3 and have come up with the following:

```ts
import 'mocha';
import { expect } from 'chai';
import sinon from 'sinon';

import { SESClient } from '@aws-sdk/client-ses';

describe('sendEmail', () => {
  let stub: any;
  before(() => {
      stub = sinon.stub(SESClient.prototype, 'send');
      after(() => stub.restore());
  });
  describe('send', () => {
      it('can send', async () => {
          await sendEmail(); // uses SESClient internally
          expect(stub.calledOnce).to.be.true;
      });
  });
});
```

**Comment by mizzao** [comment]
Cool. For reference, I was able to stub using nock this way, e.g. for a S3 `PutObject`, adapted from nock/nock#256

```ts
nock(`https://${bucket}.s3.${region}.amazonaws.com`)	
	.persist()
	.put(/SOME_KEY_REGEXP/)
	.reply(200)
```

This is intercepting at the HTTP level rather than the method level, but both are fine ways to do it. It would be nice to link to some examples of this when the SDK leaves beta.

**Comment by gugu** [comment]
I use this to stub it:

```javascript
describe('Domain registration', () => {
    let sandbox: sinon.SinonSandbox;
    beforeEach(() => {
        sandbox = sinon.createSandbox();
    })
    it('should check domain', async () => {
        sandbox.stub(Route53Domains.prototype, 'checkDomainAvailability').resolves({
            Availability: 'AVAILABLE',
        });
        ....
    });

    afterEach(() => sandbox.restore());
}
```

**Comment by paulswail** [comment]
For folks using Jest with the v3 SDK, here's how I mocked out the SES client:

```ts
import '@aws-sdk/client-ses';

const sendEmail = jest.fn().mockImplementation(() => {
  return Promise.resolve({ MessageId: uuid() })
});

jest.mock('@aws-sdk/client-ses', () => {
  return {
    SES: jest.fn().mockImplementation(() => {
      return { sendEmail };
    }),
  };
});

```

**Comment by dmattia** [comment]
The current solutions here work great if you're using the v2 compatible client functions, though they do not work with the recommended methods for the v3 sdk using the `send` method. Here's what I came up with to work with v3, using multiple commands:

```
import { S3Client, PutObjectCommand, GetObjectCommand } from '@aws-sdk/client-s3';
import sinon from 'sinon';

const s3 = new S3Client({})
sinon.stub(s3, 'send')
	.withArgs(sinon.match((param) => param.constructor.name === GetObjectCommand.name)
    .resolves({ VersionId: '1' })
	.withArgs(sinon.match((param) => param.constructor.name === PutObjectCommand.name)
	.resolves({ VersionId: '2' })
```

**Comment by monken** [comment]
you can use `param instanceof GetObjectCommand` instead of `param.constructor.name === GetObjectCommand.name`.

**Comment by allens** [comment]
I think _aws-mock-sdk_ could need a fairly significant rewrite to use with the new AWS JS SDK since the API is so different. It uses _sinon_ internally but I wanted a _Jest_ solution since that is what we use for most of our other tests.

Also I wanted to mock the `send` method rather than the v2 compatible functions.

The [_aws-doc-sdk-examples_](https://github.com/awsdocs/aws-doc-sdk-examples/blob/master/javascriptv3/example_code/tests/sqs/sqs_getqueueurl.test.js) repository has some example tests using Jest but they are of the simple `toHaveBeenCalled` variety rather than mocking the responses.

This is what I'm using for Jest:

```typescript
const mockSend = jest.fn();
jest.mock('@aws-sdk/client-sqs', () => {
    return {
        ...jest.requireActual('@aws-sdk/client-sqs'),
        SQSClient: function SQSClient(): void {
            this.send = mockSend;
        },
    };
});

describe('JobQueue', () => {
    beforeEach(() => {
        jest.clearAllMocks();
    });

    it('queueJob queues a specified job', async () => {
        
        let message = null;

        mockSend.mockImplementation((command) => {
            if (command instanceof GetQueueUrlCommand) {
                return Promise.resolve({ QueueUrl: 'sqs://queue' });
            } else if (command instanceof SendMessageCommand) {
                message = JSON.parse(command.input.MessageBody);
            }
        });

        // Class which uses SQSClient.send with GetQueueUrlCommand and SendMessageCommand 
        const queue = new JobQueue('queue');
        await queue.queueJob(job);

        expect(message.tenantId).toBe(job.tenantId);
        expect(message.bearerToken).toBe('token');
    });
});
```

You could probably use `jest.spyOn` to replace the implementation of `send` if you only need to mock it within the scope of the test file but I needed to mock the module in another class.

**Comment by m-radzikowski** [comment]
This over-typped looking function allows mocking Clients with type-checking for `instanceof` (for Jest):

```typescript
import {MetadataBearer} from '@aws-sdk/types';
import {Client, Command, SmithyResolvedConfiguration} from '@aws-sdk/smithy-client';

export const mockSend = <HandlerOptions,
    ClientInput extends object, // eslint-disable-line @typescript-eslint/ban-types
    ClientOutput extends MetadataBearer,
    ResolvedClientConfiguration extends SmithyResolvedConfiguration<HandlerOptions>,
    InputType extends ClientInput,
    OutputType extends ClientOutput>(
    client: new (config: never) => Client<HandlerOptions, ClientInput, ClientOutput, ResolvedClientConfiguration> // eslint-disable-line indent
): jest.Mock<unknown, [Command<InputType, OutputType, ResolvedClientConfiguration>]> => { // eslint-disable-line indent
    const mock = jest.fn<unknown, [Command<InputType, OutputType, ResolvedClientConfiguration>]>();
    (client as jest.Mock).mockImplementation(() => ({
        send: mock,
    }));
    return mock;
};
```

Usage:

```typescript
import {AssumeRoleCommand, STSClient} from '@aws-sdk/client-sts';

mockSend(STSClient).mockImplementation(command => {
    if (command instanceof AssumeRoleCommand) {
        const expiration = new Date();
        expiration.setHours(expiration.getHours() + 1);

        return {
            Credentials: {
                AccessKeyId: 'MOCK_ACCESS_KEY_ID',
                SecretAccessKey: 'MOCK_SECRET_ACCESS_KEY',
                SessionToken: 'MOCK_SESSION_TOKEN',
                Expiration: expiration,
            },
        };
    }
});
```

Usage in tests is simple and provides type-safe `instanceof` - you will get a warning if you check with a Command class that cannot be used with a given Client. `mockSend()` returns `jest.Mock`, so you can use all `mockImplementation`, `mockReturnValue`, `mockResolvedValue` etc.

It would be perfect if also a return type would be checked according to the used Client / Command type, but I don't know if that's even possible.

**Comment by m-radzikowski** [comment]
I've created an equivalent of [aws-sdk-mock](https://github.com/dwyl/aws-sdk-mock) for the v3 SDK: **[aws-sdk-client-mock](https://github.com/m-radzikowski/aws-sdk-client-mock)**

Does not depend on Jest or any other unit testing framework, uses Sinon.js under the hood for highly customizable mocks, fully typed, fluently declared mocks behaviors. Mocking is as simple as that:

```typescript
mockClient(SNSClient)
    .on(PublishCommand)
    .resolves({
        MessageId: '12345678-4444-5555-6666-111122223333',
    });
```

but can be further specified to give different responses based on the command input etc.

**Comment by allens** [comment]
@m-radzikowski  https://github.com/m-radzikowski/aws-sdk-client-mock looks really good. Thank you.

**Comment by tuscaonline** [comment]
@m-radzikowski very good work! Thank you.

**Comment by etiennenoel** [comment]
How would someone go about mocking the new waiters? For example:

```
    waitForTableExists,
    waitForTableNotExists,
```

**Comment by danobri** [comment]
Has anyone found a way to mock DynamoDBDocument or DynamoDBDocumentClient with just jest?  We are trying to upgrade from the v2 Dynamo library, but can't find a way to get the mocks working.  The main challenge is finding a way to mock the static "from" constructor.

**Comment by AllanZhengYP** [comment]
Hi,

We have posted a blog([Mocking modular AWS SDK for JavaScript (v3) in Unit Tests](https://aws.amazon.com/blogs/developer/mocking-modular-aws-sdk-for-javascript-v3-in-unit-tests/)) to show how to use the [aws-sdk-client-mock](https://github.com/m-radzikowski/aws-sdk-client-mock) to mock the JavaScript SDK v3. 

Please open a new issue if you have more questions regarding this topic.
