### ISSUE TITLE
`LambdaClient` references node types

### ISSUE THREAD

**Issue by aquark** [aws/aws-sdk-js-v3#1160]
**Describe the bug**
At least one client (`LambdaClient`) includes `/// <reference types="node" />` in its `.d.ts` files. This causes problems when the client is consumed in browser projects which define types that conflict with node. One example is using webpack hot module reloading, which requires a  declaration like the following:

```
  /**
   * Declare module interface for HMR.
   * https://webpack.js.org/api/hot-module-replacement/
   */
  declare var module: {
    hot?: {
      accept: () => void
      dispose: (callback: (data: HmrData) => void) => void
      data: HmrData
    }
  }
```

When a project with this declaration uses `LambdaClient`, the TypeScript compiler gives the following error:

```
node_modules/.pnpm/amazon.goshawk.aws.a2z.com/@types/node/12.12.37/node_modules/@types/node/globals.d.ts:235:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'module' must be of type '{ hot?: { accept: () => void; dispose: (callback: (data: HmrData) => void) => void; data: HmrData; } | undefined; }', but here has type 'NodeModule'.

235 declare var module: NodeModule;
                ~~~~~~

  packages/ui/src/global.d.ts:35:13
    35 declare var module: {
                   ~~~~~~
    'module' was also declared here.
```

This occurs just by importing `LambdaClient`, even though I have not imported the `InvokeAsyncRequest` type or anything which references it.

To work around this issue you can use the tsc `skipLibCheck` option.

**SDK version number** `1.0.0-beta.5`

**Is the issue in the browser/Node.js?** Browser

**Details of the browser/Node.js version** N/A

**To Reproduce (observed behavior)** See description

**Expected behavior** Generated clients should never reference `node` types except for features that are only supported in a `node` environment (and it should be possible to *not* include these features in a browser environment). E.g. if the `InvokeAsyncRequest` type cannot be defined in a cross-platform way, then it should be in a different module so that browser consumers can avoid importing it.

**Comment by AllanFly120** [comment]
Hi @aquark 

Can you share how do you bundle your project for browsers? It would be very helpful if you can share a reproduction repo with bundling guidance.

**Comment by ajredniwja** [comment]
@aquark is this still a persisting issue with the lates clients? 

Also reproduction code would be really helpful if it still an issue.
