### ISSUE TITLE
Support for Step Functions

### ISSUE THREAD

**Issue by seawatts** [aws/aws-sdk-js-v3#1162]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Support for Step Functions

**Comment by trivikr** [comment]
Step Functions discussed in Amplify https://github.com/aws-amplify/amplify-cli/issues/3222

**Comment by georgeionita** [comment]
is there a reason why this was left off?

**Comment by koweblomke** [comment]
I am looking for a way to trigger a startExecution on  stepfunctions from an Amplify application.
Is this going to be supported in de aws-sdk-js-v3 or in amplify?

What would be I good workaround until it is supported?

**Comment by koweblomke** [comment]
After some digging I probably discovered why StepFunctions is not supported.
the StepFunctions Service has no support for CORS, so you cannot call it from your browser.

https://forums.aws.amazon.com/thread.jspa?threadID=248225
and
https://github.com/aws/aws-sdk-js/issues/1334

So a workaround could be to implement a Lambda function which in turn invokes the StepFunctions Services.

**Comment by eikeon** [comment]
Was looking for it to startSyncExecution from a lambda to not have a mix of 2.x and 3.x

**Comment by NTonani** [comment]
@trivikr What's the status of v3 support for SFs?

**Comment by georgmao** [comment]
This should do it: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-sfn/index.html

**Comment by danielpater** [comment]
> This should do it: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-sfn/index.html

Thanks a lot for pointing out to this!

**Comment by smagch** [comment]
@seawatts Let's close this issue. As @georgmao mentioned above, AWS SDK v3 supports Step Functions client as `@aws-sdk/client-sfn`.

**Comment by brmur** [comment]
@seawatts There's a cross-service SDK example using Step Functions here - https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/serverless-step-functions-example.html

**Comment by pfried** [comment]
This issue can be closed since as @georgmao pointed out there is an implementation in aws sdk v3
