### ISSUE TITLE
Mode may not be implemented for `fetch` in some environments

### ISSUE THREAD

**Issue by blakeembrey** [aws/aws-sdk-js-v3#1165]
**Describe the bug**

When trying to use the new AWS clients on Cloudflare, it will error on:

```
The 'mode' field on 'RequestInitializerDict' is not implemented.
```

This is because `mode` is not implemented on Cloudflare. Thankfully, the default appears to be `cors` anyway so this could be deleted without loss of functionality: https://developer.mozilla.org/en-US/docs/Web/API/Request/mode.

**SDK version number** 1.0.0-alpha.1

**Is the issue in the browser/Node.js?**

Browser

**Details of the browser/Node.js version**

Cloudflare Workers.

**To Reproduce (observed behavior)**

```js
export const client = new DynamoDBClient({
  region: AWS_REGION,
  credentials: { accessKeyId: AWS_ACCESS_KEY, secretAccessKey: AWS_SECRET_KEY },
});

const result = await client.send(
  new GetItemCommand({
    TableName: DB_TABLE_NAME,
    Key: {
      PK: { S: "" },
    },
  })
);
```

**Expected behavior**

It should work.

**Comment by AllanFly120** [comment]
Hi @blakeembrey 

It sounds very bad that CloudFlare throws when `cors` is supplied. Even though it doesn't fully compatible with [Fetch standard](https://fetch.spec.whatwg.org/#concept-request-mode), it should not throw. Moreover, the default value for `cors` stated in the standard is not `cors`. 

Is there a way for SDK to detect if the runtime support `cors` feild?

**Comment by blakeembrey** [comment]
Oh, it says that on MDN:

> For example, when a Request object is created using the Request.Request constructor, the value of the mode property for that Request is set to cors.

In CloudFlare Workers, I'm not sure but I don't think so. The only documentation I'm aware of is https://developers.cloudflare.com/workers/reference/apis/request/.

**Comment by blakeembrey** [comment]
@AllanFly120 It's also documented behavior in the spec you just shared with me: https://fetch.spec.whatwg.org/#concept-request-request.

Specifically:

> Set fallbackMode to "cors".

And:

> Let mode be init["mode"] if it exists, and fallbackMode otherwise.

**Comment by blakeembrey** [comment]
I'm basing my original comment on this code by the way, in case we're discussing different things: https://github.com/aws/aws-sdk-js-v3/blob/5f820e6a06de21965db1ac4094b33b04d90533a3/packages/fetch-http-handler/src/fetch-http-handler.ts#L61-L73. In this context, I believe `cors` is the default regardless based on the specification.

**Comment by trivikr** [comment]
FYI: mode was set in original PR at https://github.com/aws/aws-sdk-js-v3/pull/57

**Comment by AllanFly120** [comment]
Removing the `mode` config makes sense to me. Also needs some input from @trivikr

**Comment by alexforsyth** [comment]
@blakeembrey thanks for opening this issue. Addressing it in https://github.com/aws/aws-sdk-js-v3/pull/1239

**Comment by trivikr** [comment]
@blakeembrey Can you verify if this is fixed in version `@aws-sdk/client-dynamodb@1.0.0-gamma.3`?

**Comment by blakeembrey** [comment]
@trivikr I'm unable to use the latest version because it depends on `fs` now. Looks like this is already logged in https://github.com/aws/aws-sdk-js-v3/issues/1352.

**Comment by trivikr** [comment]
@blakeembrey Can you verify if this is fixed in version `@aws-sdk/client-dynamodb@1.0.0-gamma.4`?

Release Notes: https://github.com/aws/aws-sdk-js-v3/releases/tag/v1.0.0-gamma.4

**Comment by blakeembrey** [comment]
I'm sorry, now I'm getting:

```
Blob is not defined
```

I believe this original issue is resolved though since I'm making it further along 😄 Right now I'm building my own wrappers for each of the AWS services I use so I'm excited to delete them.

**Comment by blakeembrey** [comment]
It appears to be coming from https://github.com/aws/aws-sdk-js-v3/blob/65a36581db0279a6044fd815201f91bcab4dcf90/packages/util-body-length-browser/src/index.ts#L3 and https://github.com/aws/aws-sdk-js-v3/blob/97efeeb7ca6dd1d7eb1f06ea0934284db1d45aa6/packages/fetch-http-handler/src/stream-collector.ts#L6. I've had luck using https://github.com/DylanPiercey/byte-length in other projects. Another thing I expect to run into is that workers don't expose a `.blob` implementation either: https://developers.cloudflare.com/workers/reference/apis/response/. However, it shouldn't run into that code path anyway.

**Comment by trivikr** [comment]
@blakeembrey Can you create a new issue for `Blob is not defined` error

So that this bug can be closed?

**Comment by blakeembrey** [comment]
Closing with https://github.com/aws/aws-sdk-js-v3/issues/1378.
