### ISSUE TITLE
Use npm-run-all to run the clients' build scripts

### ISSUE THREAD

**Issue by AllanZhengYP** [aws/aws-sdk-js-v3#1187]
**Is your feature request related to a problem? Please describe.**
[npm-run-all](https://github.com/mysticatea/npm-run-all/blob/master/README.md#%EF%B8%8F-motivation) enables user to write the npm scripts cleaner. We used to have `"build": "build:es && build:cjs"`, now it can be `"build": "npm-run-all build:*"`

**Comment by seebees** [comment]
Using `:` seems pretty common to me,
but I have found that `-` is a little more helpful.
Because it will tab complete.
