### ISSUE TITLE
tslib version in package.json seems to be incorrect

### ISSUE THREAD

**Issue by daku10** [aws/aws-sdk-js-v3#1188]
**Describe the bug**

`tslib` dependencies in package.json seems to be incorrect.
Packages declare that they use `Typescript@~3.8.3` and `tslib@^1.8.0`.
And some packages uses array spread operator, it is transpiled to code that uses `__spreadArrays` function of `tslib` by using `typescript@~3.8.3`.
But `__spreadArrays` function is instroduced `tslib@1.10.0`  [release note](https://github.com/microsoft/tslib/releases/tag/1.10.0)
Therefore build of the packages is failed in some enviroment.

**SDK version number**

`@aws-sdk/signature-v4@1.0.0-beta.4`

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`

`v12.16.0`

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

I cannot prepare minimal code to reproduce this issue, because this issue is related to environment.
So I create a [repository](https://github.com/daku10/aws-sdk-js-v3-issue) which contains this issue to use aws-amplify-react.
`yarn && yarn build` may produce this issue.

**Additional context**

I have encountered this issue when I introduced `ams-amplify-react` to some old project which lockfile uses tslib@1.9.3 as `tslib@^1.8.0`.
I think tslib version should be upgraded to match typescript version.
Should I create PR for this issue?

**Comment by trivikr** [comment]
tslib was bumped to 2.0.0 in https://github.com/aws/aws-sdk-js-v3/pull/1417
typescript was bumped to 4.0.2 in https://github.com/aws/aws-sdk-js-v3/pull/1456

Both updates are available in release [v1.0.0-gamma.7](https://github.com/aws/aws-sdk-js-v3/releases/tag/v1.0.0-gamma.7)
Is this issue still reproducible @daku10 ?

**Comment by daku10** [comment]
@trivikr 

In my environment, resolve this issue to update version.
Thanks!
