### ISSUE TITLE
Cannot connect to local dynamodb over HTTP

### ISSUE THREAD

**Issue by anvar** [aws/aws-sdk-js-v3#1189]
**Describe the bug**
The current client behaviour overrides any http-related configuration, such as when trying to connect to a local dynamodb instance.

**SDK version number**
1.0.0-beta.5

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
v12.16.3

**To Reproduce (observed behavior)**
Connect to a local dynamodb over http

**Expected behavior**
For it to succeed

**Screenshots**

**Additional context**
See https://github.com/aws/aws-sdk-js-v3/blob/c96f35f972c44706a391bb07e0a897e73b8d6dfe/clients/client-dynamodb/protocols/Aws_json1_0.ts#L11755 for more details where protocol is being overriden. I am happy to send a PR, but givent that it is a relatively low level part of the code, I am not sure if it was done on purpose.

**Comment by fboudra** [comment]
fwiw duplicate https://github.com/aws/aws-sdk-js-v3/issues/1128

**Comment by matej-prokop** [comment]
works for me, when I installed `1.0.0-gamma.2`

**Comment by fboudra** [comment]
@matej-prokop  do you mind pasting a sample code? I tried to pass tls/region/endpoint and didn't work:

```
const {
  DynamoDBClient,
  ListTablesCommand,
} = require('@aws-sdk/client-dynamodb');

(async () => {
  const client = new DynamoDBClient({
    tls: false,
    region: 'us-east-1',
    endpoint: 'http://localhost:8000',
  });
  const command = new ListTablesCommand({});
  try {
    const results = await client.send(command);
    console.log(results.TableNames.join('\n'));
  } catch (err) {
    console.error(err);
  }
})();
```

**Comment by fboudra** [comment]
@matej-prokop nevermind, thanks for the suggestion. For some reason, I was still running alpha.1

**Comment by matej-prokop** [comment]
@fboudra, provide also `credentials` to client configuration:

```js
  const client = new DynamoDBClient({
    region: "us-west-2",
    endpoint: "http://localhost:8000",
    credentials: {
      accessKeyId: "xxx",
      secretAccessKey: "yyy",
    },
  });
```

It doesn't make much sense for localhost and unfortunately it's missing in official examples (at least those I found) but without providing some credentials, it doesn't work.

**Comment by alexforsyth** [comment]
Looks like this is resolved. Closing
