### ISSUE TITLE
Empty blob decoding via base64 is causing issues in Chrome

### ISSUE THREAD

**Issue by Amplifiyer** [aws/aws-sdk-js-v3#1198]
**Describe the bug**
Empty blob decoding via base64 is causing issues in Chrome

**SDK version number**
Gamma.1

**Is the issue in the browser/Node.js?**
Browser: Chrome Version 81.0.4044.138

**To Reproduce (observed behavior)**
Make any service call that uses the stream collector and returns empty results. S3 PUT reproduces it easily. See https://github.com/aws-amplify/amplify-js/issues/5876 and https://github.com/aws-amplify/amplify-js/issues/5873

**Additional context**
The issue seems to be how browsers implement `FileReader.readAsDataURL()`. On firefox, for an empty blob (case for a successful S3 PUT request) I'm seeing `FileReader.readAsDataURL()` returns `data:application/octet-stream;base64,` while on chrome it returns `data:`. This causes issues with parsing the actual result [here](https://github.com/aws/aws-sdk-js-v3/blob/master/packages/fetch-http-handler/src/stream-collector.ts#L42-L48). On chrome when it doesn't find a `,` it leaves the input as is which later cannot be decoded since `:` is not a valid base64 character.

Both IE and edge seems to return `null` for empty blobs so it shouldn't create any issues.

Tested with the following code in the 4 browsers
```
var testBlob = new Blob([]) // and again with non empty Blob(["a"])
var fileReader = new FileReader();
fileReader.onloadend = () => { console.log(fileReader.result) }
fileReader.readAsDataURL(testBlob);
```
Resulted in following observations
Blob | Firefox(72.0.2) | Chrome (81) | Edge(44) | IE (11)
------------ | ------------ | -------------  | ------------ | -------------
Empty | data:application/octet-stream;base64, | data: | null | null
Non empty | data:application/octet-stream;base64,YQ== | data:application/octet-stream;base64,YQ== | data:;base64,YQ== | data:;base64,YQ==

**Comment by AllanFly120** [comment]
Hi @Amplifiyer 

I cannot reproduce it from default request handler on Firefox or Chrome. Looking at the code [`readToBase64()`](https://github.com/aws/aws-sdk-js-v3/blob/master/packages/fetch-http-handler/src/stream-collector.ts#L42-L48) is only executed in when response payload is `Blob` shape, and normally the body is not a Blob in browsers, except for very old ones. 

Given this only affects `Storage.put`, it's likely that the special [Axios handler](https://github.com/aws-amplify/amplify-js/blob/master/packages/storage/src/providers/axios-http-handler.ts) returns a `Blob` in browsers, so the `readToBase64()` is called in non-ReactNative runtime.

**Comment by Amplifiyer** [comment]
@AllanFly120 it was done because the stream collector was having issues with string return type(default axios return type) and was confirmed with aws-sdk that returning blobs in browsers is fine. I'm currently not sure what the path forward is given both strings and blobs are having issues in aws sdk. We need this fixed to work with blobs in browsers
