### ISSUE TITLE
Set default H2 session timeout

### ISSUE THREAD

**Issue by AllanZhengYP** [aws/aws-sdk-js-v3#1206]
**Is your feature request related to a problem? Please describe.**
If a service supports H2, the client will contain an H2 request handler by default (i.e. kinesis, but current released client-kinesis uses H1 request handler still). If user make a request, the process doesn't return after the request is completed, unless the request handler is explicitly destroyed.

This is because the H2 request [creates an H2 session everytime](https://github.com/aws/aws-sdk-js-v3/blob/4895ac7070cf6d845846e0c3b40aa4ee6ad94f82/packages/node-http-handler/src/node-http2-handler.ts#L113) it establish an H2 connection. Since the connection doesn't close even in idle, the process doesn't return either. 

It brings the problem that: 
1. If someone spawn a process calling a Kinesis API, the process will hang there indefinitely after the API call is completed. 
2. If an H1 service later release H2 support, SDK will use H2 http handler accross the service. It would be a breaking change if we ask users to destroy the handler later. 

**Describe the solution you'd like**
Nodejs provides a [setTimeout()](https://nodejs.org/api/http2.html#http2_http2session_settimeout_msecs_callback) config on H2 session object. It configs the session to be closed after a certain period of time if it's inactive. By default, there's no timeout.(It has 3 mins default timeout in reality because [NginX has default 3 mins idle time](https://nginx.org/en/docs/http/ngx_http_v2_module.html#http2_idle_timeout))

I suggest the default value to be shorter than 3 mins so it won't hang users process meaninglessly for too long. The defautl value should be longer than couple of seconds otherwise we are losing the benefit of H2.

/cc @trivikr @alexforsyth

**Comment by AllanFly120** [comment]
Nodejs introduced default timeout of 120 seconds on [H2 server timeout](https://nodejs.org/api/http2.html#http2_server_settimeout_msecs_callback) very early on but reverted in https://github.com/nodejs/node/pull/27558, because it introduced a lot surprice when it closes the connection unexpectedly.

**Comment by TysonAndre** [comment]
Another reason to add a session timeout is https://github.com/aws/aws-sdk-js-v3/issues/1525#issuecomment-841698915 - clients would get an unexpected error if a load balancer silently drops an inactive HTTP/2 connection without closing it.

It seems like many load balancers hosted by AWS services have a (configurable) default timeout of 300 seconds (after which many silently drop the connection), so my personal preference would be a value less than 300 seconds (such as 120 seconds)

**Comment by trivikr** [comment]
> Nodejs introduced default timeout of 120 seconds on [H2 server timeout](https://nodejs.org/api/http2.html#http2_server_settimeout_msecs_callback) very early on but reverted in [nodejs/node#27558](https://github.com/nodejs/node/pull/27558),

The revert in Node.js was done as it was surprising and problematic for users.
The behavior is not common in other language runtimes.

We should not add a default session time out as:
* It would be backward incompatible. The users on previous versions of 3.x SDK will see their Http2 sessions timing out.
* The users can always provide their own sessionTimeout as follows:
  ```js
  const client = new ClientUsingH2Handler({
    requestHandler: new NodeHttp2Handler({
      sessionTimeout: 120000
    }),
  });
  ```

> Another reason to add a session timeout is [#1525 (comment)](https://github.com/aws/aws-sdk-js-v3/issues/1525#issuecomment-841698915) - clients would get an unexpected error if a load balancer silently drops an inactive HTTP/2 connection without closing it.

Should this be handled by listening to [timeout](https://nodejs.org/api/http2.html#http2_event_timeout) event instead?
