### ISSUE TITLE
middleware-serde package not compiled to ES5 syntax, breaking IE

### ISSUE THREAD

**Issue by Amplifiyer** [aws/aws-sdk-js-v3#1208]
**Describe the bug**
Some packages are still compiled to ES2016 syntax and not ES5 breaking IE. See https://github.com/aws-amplify/amplify-js/issues/5582

This is a continuation of https://github.com/aws/aws-sdk-js-v3/issues/1099 which was fixed in https://github.com/aws/aws-sdk-js-v3/pull/1122 but missed the following package

https://github.com/aws/aws-sdk-js-v3/blob/910da6a07eb76f64738dce9374f1c197ebf228c1/packages/middleware-serde/tsconfig.json#L3

There might be more packages that are not compiled to ES5 syntax and need to be fixed.

**SDK version number** Gamma.2

**Is the issue in the browser/Node.js?**
Browser/IE

**Comment by jasonrose** [comment]
Is it possible to get a new gamma cut with this fix included?  It would help us confirm that we have addressed all of the IE11 issues.

**Comment by trivikr** [comment]
ES5 version of middleware-serde was released with v1.0.0-gamma.3
https://github.com/aws/aws-sdk-js-v3/releases/tag/v1.0.0-gamma.3
