### ISSUE TITLE
Use fixed versioning to manage the sub modules

### ISSUE THREAD

**Issue by AllanFly120** [aws/aws-sdk-js-v3#1248]
Reference: https://github.com/lerna/lerna#fixedlocked-mode-default
**Is your feature request related to a problem? Please describe.**

1. Currently the SDK create a new tag for each new version each subpackage. This results in having too many tags to maintain. As 06/05/2020 we have 10.5K tags. 

1. Using independent versioning also adds some unnecessary complexity over the release system.

1. Most popular monorepos use fixed versioning, like [Lerna](https://github.com/lerna/lerna/blob/master/lerna.json), [Babel](https://github.com/babel/babel/blob/master/lerna.json)

**Describe the solution you'd like**

Move the fixed versioning. Using fixed versioning [won't results in empty release of packages that not updated](https://github.com/lerna/lerna#fixedlocked-mode-default):
> When you run lerna publish, if a module has been updated since the last time a release was made, it will be updated to the new version you're releasing. This means that you only publish a new version of a package when you need to.

Fixed versions has a dropback that any major version change in any of the sub-package leads to a new major version to all sub-packages. But since we plan to do major version bumping only to all sub-packages anyway, this is not a problem for us.

**Describe alternatives you've considered**
I have attempt to stop publishing the excessive tags. But it results in issue with change log generation.

**Additional context**
This should be done in next prerelease id change, say `1.0.0-delta.0` or `1.0.0-rc.0`.

**Comment by trivikr** [comment]
Closing as we now use fixed versions from 1.0.0-rc.1 onwards.
Link: https://github.com/aws/aws-sdk-js-v3/releases/tag/v1.0.0-rc.1
