### ISSUE TITLE
Application stack trace being swallowed up

### ISSUE THREAD

**Issue by Bene-Graham** [aws/aws-sdk-js-v3#1287]
**Describe the bug**
In the v2 repo this bug: https://github.com/aws/aws-sdk-js/issues/3020 hinted at that in v3 there was going to be improvement around stack traces. So I decided to run some test wiht the v3 SDK to see if there is any improvements. Currently it does not show where the error was thrown within my application. This make it was hard to track down where the error is occurring.

**SDK version number**
@aws-sdk/client-s3: 1.0.0-gamma.2

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
v12.16.3

**To Reproduce (observed behavior)**
I created a simple application that should show the current behaviour.
https://github.com/Bene-Graham/AWS-SDK-StackTraceIssue

**Expected behavior**
I would expect that the stack trace should contain where in my application code the error was thrown. Currently it only show this:

```
NoSuchKey: NoSuchKey
    at deserializeAws_restXmlGetObjectCommandError (/Users/xyz/Documents/git/Other/AWS-SDK-StackTraceIssue/node_modules/@aws-sdk/client-s3/dist/cjs/protocols/Aws_restXml.js:4868:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 404,
    httpHeaders: {
      'x-amz-request-id': '',
      'x-amz-id-2': '',
      'content-type': 'application/xml',
      'transfer-encoding': 'chunked',
      date: 'Mon, 22 Jun 2020 19:50:40 GMT',
      server: 'AmazonS3'
    },
    requestId: undefined,
    retries: 0,
    totalRetryDelay: 0
  }
}
```

**Comment by AllanFly120** [comment]
Hi @Bene-Graham 

Thank you for reporting this. This is issue usually caused be async function throwing error inside a callback. I will need to take a closer look at it.

**Comment by simonbuchan** [comment]
A few notes:

Overly transpiling isn't helping, expanding every async/await frame into a set of `step()`, `next()`, `fulfilled()` regenerator runtime frames. To fix you would need to ship at least es2017. You *can* ship multiple, and ask users to use e.g. webpack `resolve.aliasFields = `["es2017", "module", "main"]`, but at this point many packages are simply targeting es2017 and asking people targeting platforms that don't support it (pretty much just IE) to retranspile.

Returning a promise breaks the async stack:

```
async function foo() { await 0; throw new Error() }
async function bar() { await foo() }
async function baz() { return bar() }
baz().catch(console.log)
Error: 
    at foo (<anonymous>:1:39)
    at async bar (<anonymous>:2:24)
```

```
async function foo() { await 0; throw new Error() }
async function bar() { return foo() }
async function baz() { await bar() }
baz().catch(console.log)
Error: 
    at foo (<anonymous>:1:39)
```

At least in 7.3, when async stack traces were enabled, only `await` and `Promise.all()` would reconstruct a stack frame, due to performance: https://v8.dev/docs/stack-trace-api#async-stack-traces

**Comment by AllanFly120** [comment]
Hi @simonbuchan @Bene-Graham,

Thank you for the insights. We have targeted all the Node.js packages to ES2018 in #1572. Here's how the stack trace will look like now:

```console
NoSuchKey: NoSuchKey
    at deserializeAws_restXmlGetObjectCommandError (Path/to/@aws-sdk/client-s3/dist/cjs/protocols/Aws_restXml.js:5311:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Path/to/@aws-sdk/middleware-serde/dist/cjs/deserializerMiddleware.js:12:20
    at async Path/to/@aws-sdk/middleware-signing/dist/cjs/middleware.js:12:24
    at async StandardRetryStrategy.retry (Path/to/@aws-sdk/middleware-retry/dist/cjs/defaultStrategy.js:55:46)
    at async Path/to/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22
    at async Path/to/test.js:29:18 {
  name: 'NoSuchKey',
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 404,
    httpHeaders: {
      'x-amz-request-id': '',
      'x-amz-id-2': '',
      'content-type': 'application/xml',
      'transfer-encoding': 'chunked',
      date: '',
      server: 'AmazonS3'
    },
    requestId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}
```

This fix will be released very soon.

**Comment by Bene-Graham** [comment]
Look forward to trying it out when the next package release happens 😄

**Comment by AllanFly120** [comment]
Hi @Bene-Graham, the new version is available. Please try the newest version `@aws-sdk/client-s3` (without `@gamma` dist tag!). I will resolve this issue now. Please let me know if the issue peresists.

**Comment by Bene-Graham** [comment]
That looks a lot better.

Thank You.
