### ISSUE TITLE
@aws-sdk/client-servicediscovery discoverInstances host is set to undefined

### ISSUE THREAD

**Issue by yokomizor** [aws/aws-sdk-js-v3#1290]
Simply calling `serviceDiscovery.discoverInstances({ ... })` throws `UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND data-undefined`.

**SDK version number**
```
"@aws-sdk/client-servicediscovery@^1.0.0-gamma.2":
  version "1.0.0-gamma.2"
  resolved "https://registry.yarnpkg.com/@aws-sdk/client-servicediscovery/-/client-servicediscovery-1.0.0-gamma.2.tgz#3c85d47b1ae1ea3074a62577468ac265c5109080"
  integrity sha512-tKRUMREcSm2dDxKmoklbyA7zb5S8mD2ISjikCIqNzdDBthW7jhuMWEWF+M9cInpzxJ69nNvnEf8jx/MFF/W8WA==
```

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
```
$ node -v
v12.18.0
```

**To Reproduce (observed behavior)**
Script:
```
(async () => {
    const { ServiceDiscovery } = require('@aws-sdk/client-servicediscovery')

    const  serviceDiscovery = new ServiceDiscovery({ apiVersion: '2017-03-14' });

    const users = await serviceDiscovery.discoverInstances({
        HealthStatus: 'HEALTHY', 
        MaxResults: 10,
        NamespaceName: 'demo', 
        ServiceName: 'demo',
    });
})();
```
Output:
```
(node:24384) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND data-undefined
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
(node:24384) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:24384) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Expected behavior**
`request.hostname` to be mapped from `servicediscovery.eu-west-1.amazonaws.com` to `data-servicediscovery.eu-west-1.amazonaws.com`.

**Additional context**
I have tested `serviceDiscovery.listNamespaces({})` and it works as expected.

It seems that `DiscoverInstances` is the only command using `"smithy.api#endpoint": {"hostPrefix": "data-" }`
https://github.com/aws/aws-sdk-js-v3/blob/e19fc4feea5268442370af97e266c982beef4210/codegen/sdk-codegen/aws-models/servicediscovery.2017-03-14.json#L547

I also found this patch that came after `1.0.0-gamma.2` release: #1224. I am not sure if it is related or not.

**Workaround I am using until it is fixed:**
```
serviceDiscovery.middlewareStack.add(
    (next) => args => {
        if (args.request.hostname === 'data-undefined') {
            args.request.hostname = `data-servicediscovery.${region}.amazonaws.com`;
            args.request.headers.host = `data-servicediscovery.${region}.amazonaws.com`;
        }

        return next(args);
    }, {
      step: "build"
    }
);
```

**Comment by AllanFly120** [comment]
Hi @yokomizor Thank you for reporting this issue. I don't think it has anything to do with the `hostPrefix` trait, since the host prefix is already populated. From the message here, I find the endpoint is resolved to `undefined`. We will look into why it happens.

**Comment by AllanZhengYP** [comment]
Hi @yokomizor, 

I cannot reproduce it in the latest SDK version. Are you able to reproduce it still? You can install it with the `latest` tag:

```console
yarn add @aws-sdk/client-servicediscovery
```
