### ISSUE TITLE
Development documentation - mention dependency on https://github.com/awslabs/smithy-typescript

### ISSUE THREAD

**Issue by PaulThompson** [aws/aws-sdk-js-v3#1291]
NB: Issue below 
Works successfully after following steps on https://github.com/awslabs/smithy-typescript#steps-to-build

**Describe the bug**
On fresh checkout of master, seeking to look into code gen tooling.
```
yarn run generate-clients
```

Results in error
```
> Task :smithy-aws-typescript-codegen:compileJava FAILED

stderr: 
FAILURE: Build failed with an exception.

* What went wrong:

stderr: Execution failed for task ':smithy-aws-typescript-codegen:compileJava'.
> Could not resolve all files for configuration ':smithy-aws-typescript-codegen:compileClasspath'.
   > Could not find software.amazon.smithy:smithy-typescript-codegen:0.2.0.
     Searched in the following locations:
       - file:/home/pault/.m2/repository/software/amazon/smithy/smithy-typescript-codegen/0.2.0/smithy-typescript-codegen-0.2.0.pom
       - file:/home/pault/.m2/repository/software/amazon/smithy/smithy-typescript-codegen/0.2.0/smithy-typescript-codegen-0.2.0.jar

stderr:        - https://repo.maven.apache.org/maven2/software/amazon/smithy/smithy-typescript-codegen/0.2.0/smithy-typescript-codegen-0.2.0.pom
       - https://repo.maven.apache.org/maven2/software/amazon/smithy/smithy-typescript-codegen/0.2.0/smithy-typescript-codegen-0.2.0.jar
     Required by:
stderr: 
         project :smithy-aws-typescript-codegen
```

**SDK version number**
git version from master 8f3fdc053 

**Is the issue in the browser/Node.js?**
In local development

**Comment by ajredniwja** [comment]
Hey @PaulThompson, thanks for opening the issue, it works successfully using the steps mentioned , what is the resolution that you suggest?

**Comment by paul-thompson-helix** [comment]
Resolution would be simply to mention the dependency, if it's still relevant.

**Comment by PaulThompson** [comment]
Resolution would be to mention the dependency on  https://github.com/awslabs/smithy-typescript#steps-to-build in this repo docs.

**Comment by RanVaknin** [comment]
@PaulThompson , Im grooming the backlog and see that this has been merged and fixed. I feel comfortable closing. If it persists, please open a new issue.

Thanks,
Ran~
