### ISSUE TITLE
Browser support fix for amplify

### ISSUE THREAD

**Issue by KwFung7** [aws/aws-sdk-js-v3#1319]
May I ask when will be the next release ?
I urgently need the "target ES5" fix (6243aac9) committed at 6/6/2020.
but its not included in latest v1.0.0-gamma.2 release yet.
Since aws-amplify also relay on aws sdk, my whole app clash in IE environments when there is arrow function inside aws sdk.

**Comment by trivikr** [comment]
@KwFung7 The "target ES5" fix (6243aac) was released with 1.0.0-gamma.3
https://github.com/aws/aws-sdk-js-v3/releases/tag/v1.0.0-gamma.3

**Comment by trivikr** [comment]
Reopening, and assigning "response-requested" to wait for verification from @KwFung7
