### ISSUE TITLE
Tsconfig ignores the build, not the dist

### ISSUE THREAD

**Issue by alexforsyth** [aws/aws-sdk-js-v3#1345]
**Describe the bug**
The tsconfig should ignore the package/dist and not the package/build

**SDK version number**

**Is the issue in the browser/Node.js/ReactNative?**
Browser/Node.js/ReactNative

**Details of the browser/Node.js/ReactNative version**
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by trivikr** [comment]
The related PR is closed https://github.com/aws/aws-sdk-js-v3/pull/1344
However, there was an observation that exclude can be removed altogether in https://github.com/aws/aws-sdk-js-v3/pull/1344#issuecomment-655623773

**Comment by alexforsyth** [comment]
Done. Closing as clean up
