### ISSUE TITLE
SNS, Where's the documentation?

### ISSUE THREAD

**Issue by vvo** [aws/aws-sdk-js-v3#1355]
**Describe the issue with documentation**
Hi there, I am trying to find the documentation for aws-sdk-js-v3 usage, for example on how to publish a message with the client-SNS package. Thanks!

**Comment by trivikr** [comment]
v3 API documentation is not deployed yet.

You can refer:
* Diffs given in workshop code https://github.com/aws-samples/aws-sdk-js-v3-workshop
* Examples given in v2 SDK API reference, but use v3 clients instead https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/

**Comment by brmur** [comment]
@vvo You can see examples of how to use the V3 of the AWS JS SDK with SNS here https://github.com/awsdocs/aws-doc-sdk-examples/tree/master/javascript/example_code_v3/sns
