### ISSUE TITLE
Client name in client-schemas is not capitalized

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#1361]
**Describe the bug**
Client name in client-schemas is not capitalized

**SDK version number**
```
$ yarn list aws-sdk
└─ aws-sdk@2.693.0
$ yarn list @aws-sdk/client-schemas
└─ @aws-sdk/client-schemas@1.0.0-gamma.3
```

**Is the issue in the browser/Node.js/ReactNative?**
N/A

**To Reproduce (observed behavior)**

<details>
<summary>Code</summary>

```js
const AWS = require("aws-sdk");
const { Schemas } = require("@aws-sdk/client-schemas");

(async () => {
  const region = "us-west-2";
  const v2Client = new AWS.Schemas({ region });
  const v3Client = new Schemas({ region });
})();
```

</details>

<details>
<summary>Output</summary>

```console
(node:38750) UnhandledPromiseRejectionWarning: TypeError: Schemas is not a constructor
    at /Users/trivikr/workspace/aws-sdk-js-tests/src/node/index.js:7:20
    at Object.<anonymous> (/Users/trivikr/workspace/aws-sdk-js-tests/src/node/index.js:8:3)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:38750) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:38750) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

</details>

**Expected behavior**
The client name should start with capital letter (i.e. Schemas)

**Additional context**
This issue was noticed while writing repro code for https://github.com/aws/aws-sdk-js-v3/issues/1360

**Comment by kstich** [comment]
This is caused by [the service's `@aws.api#service` trait specifying the `sdkId` as "schemas"](https://github.com/aws/aws-sdk-js-v3/blob/master/codegen/sdk-codegen/aws-models/schemas.2019-12-02.json#L2961). The [`AwsServiceIdIntegration` class does not manipulate the `sdkId` field and overrides the default strategy of capitalizing the service shape's name](https://github.com/aws/aws-sdk-js-v3/blob/master/codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsServiceIdIntegration.java#L30). You'll need to update this implementation to perform any additional manipulation.

**Comment by trivikr** [comment]
As per fix in https://github.com/aws/aws-sdk-js-v3/pull/1375, 12 services are affected.

To follow same client names as in v2, we'll have to run regular expression `name.replace(/Amazon|AWS|Beta|\(|\)|\s+|\/|\-/g, "")` is when name is `serviceAbbreviation` || `serviceFullName`

**Comment by trivikr** [comment]
In internal discussions, we decided to go ahead with solution proposed in https://github.com/aws/aws-sdk-js-v3/pull/1375, as serviceId should be used for client names during major version bumps.

I'll post a new PR after cleaning the commits.
