### ISSUE TITLE
Compiler error in v3 when using `util-create-request`

### ISSUE THREAD

**Issue by vecerek** [aws/aws-sdk-js-v3#1365]
**Describe the bug**
Hi 👋 I'm trying to use @trivikr's [example](https://github.com/aws/aws-sdk-js-v3/issues/456#issuecomment-607557895) from #456 in TypeScript but I keep getting the following compiler error:

```
Argument of type 'S3' is not assignable to parameter of type 'Client<any, ServiceInputTypes, MetadataBearer, any>'.
  Types of property 'middlewareStack' are incompatible.
    Type 'MiddlewareStack<ServiceInputTypes, ServiceOutputTypes>' is not assignable to type 'MiddlewareStack<ServiceInputTypes, MetadataBearer>'.
      Types have separate declarations of a private property 'absoluteEntries'.ts(2345)
```

I tried also following the examples in the [util-create-request package readme](https://github.com/aws/aws-sdk-js-v3/tree/master/packages/util-create-request#aws-sdkutil-create-request) but when I try to use an instance of a `S3Client` coming from `@aws-sdk/client-s3-node/S3Client`, I'm getting other issues with the interface. I noticed that there's no `gamma` release for the `client-s3-node` package and it can no longer be found in the mono-repo either. Thus, I'm under the impression that the README is out of date and `client-s3-node` was probably deprecated. Is there any other documentation I should be looking at? What is there current (`gamma.2`) way of satisfying the TypeScript compiler when using `@aws-sdk/util-create-request`?

**SDK version number**
1.0.0-gamma.2

**Is the issue in the browser/Node.js/ReactNative?**
Node.js

**Details of the browser/Node.js/ReactNative version**
Node v12.16.1

**To Reproduce (observed behavior)**
```ts
import { S3, PutObjectCommand } from "@aws-sdk/client-s3"; // 1.0.0-gamma.2
import { NodeHttpHandler } from "@aws-sdk/node-http-handler"; // 1.0.0-gamma.2
import { createRequest } from "@aws-sdk/util-create-request"; // 1.0.0-gamma.2
import { ServiceInputTypes, PutObjectCommandInput, PutObjectCommandOutput } from "@aws-sdk/client-s3/types"; // 1.0.0-gamma.2

const config = {
  credentials: {
    accessKeyId: "access_key",
    secretAccessKey: "secret_key",
  },
  encryption: "AES256",
  region: "us-east-1",
};

const client = new S3({
  ...config,
  requestHandler: new NodeHttpHandler(),
});

const Key = "some_key";
const Bucket = "my_bucket";
const request = await createRequest<ServiceInputTypes, PutObjectCommandInput, PutObjectCommandOutput>(
  client,
  new PutObjectCommand({ Key, Bucket }),
);
```

**Expected behavior**
I would expect not to get a compiler error and a better README of the `@aws-sdk/util-create-request` package.

**Screenshots**

**Additional context**
I've bumped into this issue when exploring the solutions on how to create pre-signed request URLs.

**Comment by AllanFly120** [comment]
Can you reinstall the dependencies in the newest `gamma` tag? As of 07/13 they are:

```console
    "@aws-sdk/client-s3": "1.0.0-gamma.4",
    "@aws-sdk/s3-request-presigner": "1.0.0-gamma.3",
    "@aws-sdk/util-format-url": "1.0.0-gamma.3"
```

The issue happens because the S3 client version does not peer with the S3 request presigner version. One of the solution is to add peer dependency to both of the package, but it's not ideal. We should get rid of private member variables from the middleware stack implementation.

This is not a bug strictly but definitely something to improve before this library goes GA. I will create a sparate feature request for this particular issue.

Let me know if you have more questions.

**Comment by vecerek** [comment]
@AllanFly120 thanks for the quick reply. Your suggestion worked but I also had to bump `@aws-sdk/util-create-request`. The compiler is happy with the below dependencies. Leaving them here in full for anyone who comes across this issue 🙂 Closing the issue as resolved, as well.

```json
"@aws-sdk/client-s3": "1.0.0-gamma.4",
"@aws-sdk/node-http-handler": "1.0.0-gamma.3",
"@aws-sdk/s3-request-presigner": "1.0.0-gamma.3",
"@aws-sdk/util-create-request": "1.0.0-gamma.3",
"@aws-sdk/util-format-url": "1.0.0-gamma.3"
```
