### ISSUE TITLE
Get rid of private members from MiddlewareStack class

### ISSUE THREAD

**Issue by AllanFly120** [aws/aws-sdk-js-v3#1377]
**Is your feature request related to a problem? Please describe.**
Because of the limitation of TS, 2 classes with the same signature but with private member variables are not assignable. In V3 SDK the situation happens a lot. For example, when users import `client-s3@1.0.0` that depends on `middleware-stack@1.0.0`, and `s3-request-presigner@1.0.0` that depends on `middleware-stack@2.0.0`, they import difference version of dependency `middleware-stack`. Then NPM will install to difference `MiddlewareStack` class. Because they both contain private members, middleware instantiated from each class are not assignable.

This will be a problem whenever 2 middleware stack need to interact, like merging. So user will see TS errors when presign an S3 request with incompatible S3 client and S3 presigner version. See #1365 

**Describe the solution you'd like**
Get rid of private variables/methods by:
1. make them `public`
2. convert the class implementation of `MiddlewareStack` to be pure functional.

**Comment by trivikr** [comment]
Fixed in #1398
Released in [v1.0.0-gamma.6](https://github.com/aws/aws-sdk-js-v3/releases/tag/v1.0.0-gamma.6)
