### ISSUE TITLE
Unable to pass a stream to s3.putObject

### ISSUE THREAD

**Issue by monken** [aws/aws-sdk-js-v3#1382]
**Describe the bug**
I'm trying to pass a stream to `s3.putObject`.

**SDK version number**
@aws-sdk/client-s3@1.0.0-gamma.4

**Is the issue in the browser/Node.js/ReactNative?**
Node.js

**To Reproduce (observed behavior)**

```js
import { PassThrough } from 'stream';

import { S3 } from '@aws-sdk/client-s3';

const s3 = new S3({
    region: 'us-east-1',
});

const pass = new PassThrough();

const put = s3.putObject({
    Bucket: 'bucket',
    Key: 'key.txt',
    Body: pass,
});

pass.end(Buffer.from('test'));

put.then((res) => console.log(res));
```

Throws with:

```
NotImplemented: A header you provided implies functionality that is not implemented
```

**Comment by monken** [comment]
Just realized that the old SDK hat a separate `s3.upload` function that accepted stream. So it's maybe a little confusing that the current implementation of `s3.putObject` also accepts streams even though it's not supported.

**Comment by AllanFly120** [comment]
Hi @monken 

`s3.putObject` does support stream body. However, the `size` of stream **must** be known. You can validate it by supplying `fs` stream, which has `size`. In V2 `s3.upload` works because it helps calculating the content length under the hood. 

The error message is not very clear here, because the `content-length` sent to S3 was `0`, so S3 maps the request to other APIs.

**Comment by monken** [comment]
Got it. Will there be an equivalent to s3.upload from V2? It's really useful to be able to stream a NodeJS Stream to S3 when you don't know the content length (e.g. if you are compressing a stream on the fly, etc.).

**Comment by AllanFly120** [comment]
Hi @monken 

Yes, there will be equivalent in V3. We will notify here when it's merged.

**Comment by farski** [comment]
@AllanZhengYP Also looking for info on the replacement for `s3.upload`. I looked around the various clients and utils and didn't see anything obvious that would contain that kind of functionality.

**Comment by trivikr** [comment]
@farski The replacement for `s3.upload` is `{ Upload }` from [`@aws-sdk/lib-storage`](https://www.npmjs.com/package/@aws-sdk/lib-storage)

We're going to write a blog post about this in Jan 2021.
