### ISSUE TITLE
@aws-sdk/client-sqs ReceiveMessageCommand sometimes returns Messages undefined

### ISSUE THREAD

**Issue by vecerek** [aws/aws-sdk-js-v3#1394]
**Describe the bug**
When I send a `ReceiveMessageCommand` via an `SQSClient`, the response only contains metadata and no `Messages`. However, if I call the `receive-message` command through `awslocal`, it always returns a messages array. I use the same credentials, and the same queue URL in both cases. I couldn't find documentation about when to expect `Messages: undefined`. So I'm wondering what the issue might be here. Am I missing some extra configuration somewhere?

**SDK version number**
1.0.0-gamma.4

**Is the issue in the browser/Node.js/ReactNative?**
Node.js

**Details of the browser/Node.js/ReactNative version**
v12.16.1

**To Reproduce (observed behavior)**
1. Setup `localstack` with an S3 bucket, an SQS queue and add notification configuration for the S3 bucket to send all `s3:ObjectCreated:*` events to the SQS queue.

2. `awslocal s3 cp some-file.txt s3://my-bucket`
3. Receive message via `awslocal`
```
awslocal sqs receive-message --queue-url http://localhost:4576/queue/my-sqs-queue --max-number-of-messages 1 --wait-time-seconds 10
```
Response:
```
{
    "Messages": [
        {
            "MessageId": "2531d06d-aac2-4dd7-8d10-52fc2b9867de",
            "ReceiptHandle": "2531d06d-aac2-4dd7-8d10-52fc2b9867de#2356b661-27b6-4dce-83d1-8c75ffdc526e",
            "MD5OfBody": "5d0d33b5898f05c1abcc3515b17b1171",
            "Body": "{\"Records\": [{\"eventVersion\": \"2.0\", \"eventSource\": \"aws:s3\", \"awsRegion\": \"us-east-1\", \"eventTime\": \"2020-07-21T15:33:09.995459Z\", \"eventName\": \"ObjectCreated:Put\", \"userIdentity\": {\"principalId\": \"AIDAJDPLRKLG7UEXAMPLE\"}, \"requestParameters\": {\"sourceIPAddress\": \"127.0.0.1\"}, \"responseElements\": {\"x-amz-request-id\": \"a2e829ec\", \"x-amz-id-2\": \"eftixk72aD6Ap51TnqcoF8eFidJG9Z/2\"}, \"s3\": {\"s3SchemaVersion\": \"1.0\", \"configurationId\": \"testConfigRule\", \"bucket\": {\"name\": \"my-bucket\", \"ownerIdentity\": {\"principalId\": \"A3NL1KOZZKExample\"}, \"arn\": \"arn:aws:s3:::my-bucket\"}, \"object\": {\"key\": \"some-file.txt\", \"size\": 86, \"eTag\": \"d41d8cd98f00b204e9800998ecf8427e\", \"versionId\": null, \"sequencer\": \"0055AED6DCD90281E5\"}}}]}"
        }
    ]
}
```

4. Receive a message in TS code:
```ts
import { SQSClient, ReceiveMessageCommand } from "@aws-sdk/client-sqs"; // "1.0.0-gamma.4"

const client = new SQSClient({
  credentials: { accessKeyId, secretAccessKey },
  endpoint,
  region,
});

const command = new ReceiveMessageCommand({
  QueueUrl: queueUrl,
  MaxNumberOfMessages: 1,
  WaitTimeSeconds: 10,
});

const res = await client.send(command);

logger.info({ command: "ReceiveMessageCommand", args: command.input, res });
```

and this results in:
```json
{
  "level": "info",
  "@timestamp": 1595346337028,
  "pid": 45,
  "hostname": "my-sqs-consumer",
  "command": "ReceiveMessageCommand",
  "args": {
    "QueueUrl": "http://localhost:4576/queue/my-sqs-queue",
    "MaxNumberOfMessages": 1,
    "WaitTimeSeconds": 10,
  },
  "res": {
    "$metadata": {
      "httpStatusCode": 200,
      "httpHeaders": {
        "server": "BaseHTTP/0.6 Python/3.8.2",
        "date": "Tue, 21 Jul 2020 15:45:36 GMT",
        "content-type": "text/plain; charset=UTF-8",
        "content-length": "348",
        "access-control-allow-origin": "*",
        "access-control-allow-methods": "HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH",
        "access-control-allow-headers": "authorization,content-type,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging",
        "access-control-expose-headers": "x-amz-version-id"
      },
      "attempts": 1,
      "totalRetryDelay": 0
    },
    "__type": "ReceiveMessageResult"
  },
  "v": 1
}
```

If I swap steps 3 and 4, the result is still the same. TS does not receive messages, `awslocal` does. I get the same result regardless of whether I use short polling or long polling.

**Expected behavior**
I expect to receive the same payload in TypeScript as I do with `awslocal`.

**Comment by vecerek** [comment]
If I swap steps 3 and 4, i.e. first attempt to receive a message via TS and the n via `awslocal` but also add the `--attribute-names "All"` option, I get the. following attributes back:
```json
"Attributes": {
  "SentTimestamp": "1595405717637",
  "ApproximateReceiveCount": "2",
  "ApproximateFirstReceiveTimestamp": "1595405761680",
  "SenderId": "127.0.0.1",
  "MessageDeduplicationId": "",
  "MessageGroupId": ""
}
```

Did SQS register that the consumer from TS asked for the message, it incremented the receive count but then didn't include the actual message in the response?

**Comment by vecerek** [comment]
I've also tried to set a `VisibilityTimeout: 15` param in my TS code, attempted to receive a message and then called the same receive-message action from `awslocal`. `awslocal` did not receive a message because the visibility timeout was still active. On a subsequent call (with awslocal), a message was received.

I'm very confused because some aspects of the TS client clearly work. Only the message can't be received which is kind of important 😅

**Comment by vecerek** [comment]
I'm also trying to implement the same functionality using a v2 client like so:
```ts
import SQS from 'aws-sdk/clients/sqs';

const clientV2 = new SQS({
  credentials: { accessKeyId, secretAccessKey },
  endpoint,
  region,
  httpOptions: { timeout: 25000 }
});

clientV2.receiveMessage({
  QueueUrl: queueUrl,
  MaxNumberOfMessages: 1,
  WaitTimeSeconds: 2,
  AttributeNames: ["All"],
}, (err, data) => {
  logger.info({ command: "ReceiveMessageCommand", args: command.input, err, data });
});
```

However, in that case the request fails with:
```json
{
  "type": "Error",
  "message": "connect ECONNREFUSED 127.0.0.1:4576",
  "stack": "Error: connect ECONNREFUSED 127.0.0.1:4576\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)",
  "errno": "ECONNREFUSED",
  "code": "NetworkingError",
  "syscall": "connect",
  "address": "127.0.0.1",
  "port": 4576,
  "region": "us-east-1",
  "hostname": "localhost",
  "retryable": true,
  "time": "2020-07-22T12:59:54.328Z"
}
```

At this point I'm no longer sure whether the bug is in the client or localstack.

**Comment by vecerek** [comment]
Another interesting observation:

I was curious if I could write any messages and maybe read my own writes. It turns out, that works. Or at least partially works.

```ts
import { ReceiveMessageCommand, SendMessageCommand } from "@aws-sdk/client-sqs";

const receiveCommand = new ReceiveMessageCommand({
  QueueUrl: queueUrl,
  MaxNumberOfMessages: maxNumberOfMessages,
  WaitTimeSeconds: 2,
  AttributeNames: ["All"],
});

const sendCommand = new SendMessageCommand({
  QueueUrl: queueUrl,
  MessageBody: "Sending SQS messages with a v3 client is so much fun",
});
await client.send(sendCommand);

const res = await client.send(receiveCommand);
logger.info({ command: "ReceiveMessageCommand", args: command.input, res });
```

If `maxNumberOfMessages === 1`, the receiveCommand will receive exactly one message. If `maxNumberOfMessages > 1`, the receiveCommand will result in no message being received.
To make it even more interesting, I then checked what's happening with:

```sh
awslocal sqs receive-message --queue-url http://localhost:4576/queue/my-sqs-queue --max-number-of-messages 10 --wait-time-seconds 5 --attribute-names "All" --visibility-timeout 0
```
and it receives 2 messages:
```json
{
    "Messages": [
        {
            "MessageId": "2923e149-c9b8-45e6-8aca-bc9160c39a57",
            "ReceiptHandle": "2923e149-c9b8-45e6-8aca-bc9160c39a57#d737c2f9-d748-4bd2-8c34-fed0ad2004fd",
            "MD5OfBody": "20b80cc143d77947a73acb211f6fa6ac",
            "Body": "Sending SQS messages with a v3 client is so much fun",
            "Attributes": {
                "SentTimestamp": "1595431625654",
                "ApproximateReceiveCount": "2",
                "ApproximateFirstReceiveTimestamp": "1595431625818",
                "SenderId": "127.0.0.1",
                "MessageDeduplicationId": "",
                "MessageGroupId": ""
            }
        },
        {
            "MessageId": "f41e78dc-45f6-4fbd-b521-92ffa9b6e721",
            "ReceiptHandle": "f41e78dc-45f6-4fbd-b521-92ffa9b6e721#ca0f1a4f-4f04-4c36-b4bf-dc019f8a0029",
            "MD5OfBody": "20b80cc143d77947a73acb211f6fa6ac",
            "Body": "Sending SQS messages with a v3 client is so much fun",
            "Attributes": {
                "SentTimestamp": "1595431625759",
                "ApproximateReceiveCount": "2",
                "ApproximateFirstReceiveTimestamp": "1595431625819",
                "SenderId": "127.0.0.1",
                "MessageDeduplicationId": "",
                "MessageGroupId": ""
            }
        }
    ]
}
```
So, somehow a single `SendMessageCommand` produced 2 messages in the queue. I'm getting more and more confused.

**Comment by wooque** [comment]
@vecerek Yeah, I'm observing 2 messages in queue also

**Comment by vecerek** [comment]
@AllanFly120 thanks for looking into this issue. I have some new development. I started implementing a fallback mechanism, to fetch the messages via the REST API, since neither v2, nor v3 of the SDK wasn't working for me in development. Because of the fallback mechanism, I had to explicitly send a `VisibilityTimeout: 0`, so that I don't have to wait before I could call the REST API.

After doing that, the v3 client suddenly started to successfully fetch S3-produced messages from the queue. So, now I removed the fallback mechanism and were able to narrow down the problem to:

```ts
const command = new ReceiveMessageCommand({
    MaxNumberOfMessages: 1,
    QueueUrl: queueUrl,
    VisibilityTimeout: 5, // this doesn't work
    WaitTimeSeconds: 2,
  });
```

```ts
const command = new ReceiveMessageCommand({
    MaxNumberOfMessages: 1,
    QueueUrl: queueUrl,
    VisibilityTimeout: 0, // this works (but, obviously, at a cost 🙁 )
    WaitTimeSeconds: 2,
  });
```

**Comment by theooos** [comment]
Just jumping on-board here to say I'm witnessing the same issue. Took a long time to track down why we might not see a message for a multiple of 30 seconds.
Setting `VisibilityTimeout` to 0 or 1 meant that messages are received almost immediately (my code is continually looping this ReceiveMessageCommand).
This seems to come with a disadvantage that there are many duplicate reads of the same item.

**Comment by bytenik** [comment]
This is a major problem for me as well. `VisibilityTimeout` of 0 or 1 fixes for me as well, but, that's not a tenable solution for my project.

**Comment by alexforsyth** [comment]
Hey all - checking in here. I'll be investigating this shortly. Thanks for opening the issue!

**Comment by alexforsyth** [comment]
Closing as this fix is out with rc.6
