### ISSUE TITLE
client-transcribe-streaming add VocabularyFiltering to model.

### ISSUE THREAD

**Issue by eggoynes** [aws/aws-sdk-js-v3#1405]
**Is your feature request related to a problem? Please describe.**
I have been using this client in the SDK. https://github.com/aws/aws-sdk-js-v3/tree/master/clients/client-transcribe-streaming

A couple months ago the feature VocabularyFiltering was released. I think it should work just like passing a VocabularyName into the client. I am not sure what has to be changed to allow a new parameter VocabularyFiltering. Here is the what's new blog post. https://aws.amazon.com/about-aws/whats-new/2020/05/amazon-transcribe-now-supports-vocabulary-filtering-for-real-time-transcription/

    const res = await client.send(new StartStreamTranscriptionCommand({
        LanguageCode: languageCode,
        MediaSampleRateHertz: MediaSampleRateHertz,
        MediaEncoding: 'pcm',
        VocabularyName: 'myvocab',
        AudioStream: transcribeInput()
    }));

**Describe the solution you'd like**
Adding VocabularyFiltering to this model should allow it to be passed in the client. Just like the VocabularyName I am not sure if it has to be added anywhere else. Thanks. 

https://github.com/aws/aws-sdk-js-v3/blob/master/clients/client-transcribe-streaming/models/index.ts

Here is the what's new blog post. 
https://aws.amazon.com/about-aws/whats-new/2020/05/amazon-transcribe-now-supports-vocabulary-filtering-for-real-time-transcription/

**Describe alternatives you've considered**
I have not see any alternatives. 

**Additional context**

This is the client I am using. 
https://github.com/aws/aws-sdk-js-v3/tree/master/clients/client-transcribe-streaming

**Comment by AllanFly120** [comment]
Hi @EddieGoynesAmazon 

The V3 SDK is currently in preview, the API model version is sometimes lagged behind. We will update all the API models in a batch soon.

**Comment by ajredniwja** [comment]
Hi @EddieGoynesAmazon looking at https://github.com/aws/aws-sdk-js-v3/blob/5d9bc5f32980f43a9b581b1f5101cdc7f2258173/clients/client-transcribe-streaming/models/models_0.ts#L801 it seems like it has been added. The comments indicate about possible values. With the documentation [here](https://docs.aws.amazon.com/transcribe/latest/dg/filter-unwanted-words.html) explaining the params.

**Comment by eggoynes** [comment]
Awesome! Thank you @ajredniwja!  

Trying it out. Thanks for the heads up.
