### ISSUE TITLE
CognitoIdentityProviderClient incorrectly requires credentials.

### ISSUE THREAD

**Issue by simonbuchan** [aws/aws-sdk-js-v3#1414]
**Describe the bug**
Runtime error when instantiating a `CognitoIdentityProviderClient` without `credentials` (e.g. to `InitiateAuth` without anonymous credentials)
Similar to #185 but for `@aws-sdk/client-cognito-identity-*provider*`, e.g. user pools not identity pools, and is a runtime error (only?) instead of being a typescript error.
This may actually be a service specification error, as I had to use the undocumented `Request#toUnauthenticated()` in v2, but i did for cognito-identity as well.

**SDK version number**
1.0.0-gamma.5

**Is the issue in the browser/Node.js/ReactNative?**
Browser

**Details of the browser/Node.js/ReactNative version**
Google Chrome 86.0.4214.3 (Official Build) dev (64-bit)

**To Reproduce (observed behavior)**
Something like:
```ts
import { CognitoIdentityProviderClient } from '@aws-sdk/client-cognito-identity-provider';
const client = new CognitoIdentityProviderClient({ region: "us-east-1" });

// presumably some `async function login(...) { ... }`, but the actual error happens above.
```

The actual error I get:
```
Error: Credential is missing
    at Object.credentialDefaultProvider (index.ts:2)
    at Object.resolveAwsAuthConfig (configurations.ts:45)
    at new CognitoIdentityProviderClient (CognitoIdentityProviderClient.ts:650)
    at createAuthProvider (auth.ts:23)
    at Module.login (auth.ts:143)
    at onLogin (index.tsx:64)
    at handleSubmit (components.tsx:44)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
```

To validate the actual call is not requiring credentials is a bit trickier due to the SRP auth flow, but a simple enough option is:

```ts
    const result = await cognitoUsers.send(new CognitoIdentityProvider.InitiateAuthCommand({
      ClientId: clientId,
      AuthFlow: 'REFRESH_TOKEN',
      AuthParameters: {
        REFRESH_TOKEN: refreshToken,
      },
    }));
```

using a `refreshToken` from an existing successful login response.

**Expected behavior**
Presumably, handle missing credentials as with `CognitoIdentityClient`, erroring only on using actions that require credentials.

At least `InitiateAuth`, `RespondToAuthChallenge` and `ForgotPassword` should not require any auth, and I assume in fact any action not starting with `Admin` uses the cognito auth tokens in the payload rather than credentials, but I haven't checked.

**Additional context**
A bit of a side-note, but I hit this integrating with my rewritten from scratch version of the Cognito SRP verifier (I only have a `bigint` and a separate Rust implementation that can compile to WASM, so no (good) IE version). You would probably need to be doing something similar in order to hit this problem, unless you're using admin username/password auth in a lambda or something.

**Comment by trivikr** [comment]
Finding: Whether an operation can be invoked without authentication is set by `optionalAuth` trait.
Smithy docs: https://awslabs.github.io/smithy/1.0/spec/core/auth-traits.html#optionalauth-trait

The `optionalAuth` trait is set up for InitiateAuth operation in smithy model.
Model: https://github.com/aws/aws-sdk-js-v3/blob/cbdec4285e95b0bc01e0698c976c99e6156ad357/codegen/sdk-codegen/aws-models/cognito-identity-provider.2016-04-18.json#L7360

The fix is to make authentication optional for operations which have `optionalAuth` enabled in codegen.

**Comment by SpencerDuball** [comment]
Can we reopen this issue? I am seeing the same error in `1.0.0-rc.7`. Also I am happy to create a new issue if that is the preferred way to approach this.

**Comment by trivikr** [comment]
@SpencerDuball Please create a new issue, as the current issue was fixed and verified in https://github.com/aws/aws-sdk-js-v3/pull/1622

**Comment by SpencerDuball** [comment]
New issue has been created, here is the reference: #1717
