### ISSUE TITLE
Open source the smithy models: What is the source of truth for model type codegen?

### ISSUE THREAD

**Issue by harrysolovay** [aws/aws-sdk-js-v3#1480]
What is the source of truth for these AWS API specs? I see html tags within the TSDoc-annotated model types. Are the types & documentation scraped from [the live AWS docs](https://docs.aws.amazon.com/index.html)?

Any info would be greatly appreciated. Thank you!

**Comment by trivikr** [comment]
The types and documentation are scrapped from AWS API models.

v3 repo currently has models in folder while under pre-release https://github.com/aws/aws-sdk-js-v3/tree/master/codegen/sdk-codegen/aws-models, but they would be removed in future after integration with internal release scripts in complete.
In v2, the models can be viewed in `apis` folder https://github.com/aws/aws-sdk-js/tree/master/apis

**Comment by harrysolovay** [comment]
@trivikr does this mean that––upon v3's stable release––its specs (wherever they end up generated to) should be used as the source of truth?

**Comment by trivikr** [comment]
> upon v3's stable release –– its models (wherever they end up generated to) should be used as the source of truth?

The v3 API Reference should be used as the source of truth.
Here is v2 API Reference for example https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/

The SDK user will usually not go through the smithy models used for code generation, the npm/gradle scripts or Java code used for code generation.

**Comment by harrysolovay** [comment]
@trivikr gotcha. I might sound like a broken record at this point, but from what source is https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/ generated? Or are those the lowest denominations of AWS's public-facing specs?

**Comment by trivikr** [comment]
> from what source is docs.aws.amazon.com/AWSJavaScriptSDK/latest generated?

The current latest docs are of stable version, i.e. v2
They're generated from v2 repo https://github.com/aws/aws-sdk-js

**Comment by harrysolovay** [comment]
@trivikr apologies I’m still not understanding. They aren’t generated from the backend source code of each service? From what source of truth are the SDK (v2 or v3, doesn’t matter) drawn?

**Comment by trivikr** [comment]
> They aren’t generated from the backend source code of each service? From what source of truth are the SDK (v2 or v3, doesn’t matter) drawn?

> v3 repo currently has models in folder while under pre-release https://github.com/aws/aws-sdk-js-v3/tree/master/codegen/sdk-codegen/aws-models

The models are provided by each service to generate clients

**Comment by harrysolovay** [comment]
Okay, so each service team submits a PR to the JS repo with the models as JSON files containing all types and documentation. Is this correct?

**Comment by trivikr** [comment]
> Okay, so each service team submits a PR to the JS repo with the models as JSON files containing all types and documentation.

Nope. Service teams provide models to internal release scripts which update them in all AWS SDK repositories.
Here is a release commit for `v2.742.0` for example https://github.com/aws/aws-sdk-js/commit/d3d35a4c95af4612d535842fb059efeae6887cdd

In future, v3 would also have releases updated daily by internal release scripts.

**Comment by harrysolovay** [comment]
@trivikr very interesting that it's repository-specific! I would have expected there to be a single endpoint for retrieving the most up-to-date service specs. Thank you for your help!

**Comment by trivikr** [comment]
> I would have expected there to be a single endpoint for retrieving the most up-to-date service specs.

There is a single endpoint for retrieving most up-to-date service models.
However, it's internal and not exposed to public.

Individual SDK repositories either put the models in some folder, or do not expose the models if it's CodeGen code.

**Comment by harrysolovay** [comment]
Reopening, as I believe exposing the single source of truth (the smithy models) to external customers should be a priority. I'd imagine this will take time. Maybe we should speak offline about how to go about seeking approval?

**Comment by alexforsyth** [comment]
@harrysolovay this will be addressed in the future once internal work has been completed. We're working on this and - for right now - the most up to date models will be exposed through our SDK.

Not making any promises, but long term we expect the models to be updated frequently and become a de facto source of (public) truth in a separate repo that all SDKs will pull from.

**Comment by harrysolovay** [comment]
Thank you @alexforsyth — very excited to hear that this is a long-term goal. Given that this is not a JS-SDK-specific issue, would you prefer I close it out? Or should it be left open for your tracking?

**Comment by alexforsyth** [comment]
Yes, I think this can be closed for now! Thanks for everythin
