### ISSUE TITLE
Remove $metadata from API response

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#1490]
**Is your feature request related to a problem? Please describe.**
The purpose of `$metadata` was to provide metadata related to Output. Since metadata is now available in logger.info, it can be removed from returned Output.

<details>
<summary>Code</summary>

```js
const { DynamoDB } = require("@aws-sdk/client-dynamodb");

(async () => {
  const client = new DynamoDB({ logger: { ...console, debug: undefined } });
  console.log(await client.listTables({ Limit: 5 }));
})();
```

</details>

<details>
<summary>Output</summary>

```console
{
  '$metadata': {
    httpStatusCode: 200,
    httpHeaders: {
      server: 'Server',
      date: 'Tue, 01 Sep 2020 22:42:10 GMT',
      'content-type': 'application/x-amz-json-1.0',
      'content-length': '167',
      connection: 'keep-alive',
      'x-amzn-requestid': 'D2V4MTLGN3KMM428QFEVDCG9KNVV4KQNSO5AEMVJF66Q9ASUAAJG',
      'x-amz-crc32': '251226023'
    },
    requestId: 'D2V4MTLGN3KMM428QFEVDCG9KNVV4KQNSO5AEMVJF66Q9ASUAAJG'
  },
  input: { Limit: 5 },
  output: {
    __type: 'ListTablesOutput',
    LastEvaluatedTableName: 'notes',
    TableNames: [
      'CUSTOMER_LIST',
      'MysfitsTable',
      'aws-js-sdk-workshop-notesAF81B09D-DVHP09NETDNE',
      'aws-sdk-js-integration-test',
      'notes'
    ]
  }
}
{
  '$metadata': {
    httpStatusCode: 200,
    httpHeaders: {
      server: 'Server',
      date: 'Tue, 01 Sep 2020 22:42:10 GMT',
      'content-type': 'application/x-amz-json-1.0',
      'content-length': '167',
      connection: 'keep-alive',
      'x-amzn-requestid': 'D2V4MTLGN3KMM428QFEVDCG9KNVV4KQNSO5AEMVJF66Q9ASUAAJG',
      'x-amz-crc32': '251226023'
    },
    requestId: 'D2V4MTLGN3KMM428QFEVDCG9KNVV4KQNSO5AEMVJF66Q9ASUAAJG',
    attempts: 1,
    totalRetryDelay: 0
  },
  __type: 'ListTablesOutput',
  LastEvaluatedTableName: 'notes',
  TableNames: [
    'CUSTOMER_LIST',
    'MysfitsTable',
    'aws-js-sdk-workshop-notesAF81B09D-DVHP09NETDNE',
    'aws-sdk-js-integration-test',
    'notes'
  ]
}
```

</details>

**Describe the solution you'd like**
Remove $metadata from response, as it can be accessed from logger info output

**Describe alternatives you've considered**
* Ignoring $metadata in response
* Using Output.$metadata for debugging, instead of explicitly passing logger

**Comment by AllanFly120** [comment]
The change makes sense. One the major usecase of `$metadata` today to to access request id programmably. Can you share an example of how people access the request id programmably?

**Comment by trivikr** [comment]
> Can you share an example of how people access the request id programmably?

The users would be able to get requestId from metadata logged in logger
The metadata will be logged by loggerMiddleware as a follow-up to PR https://github.com/aws/aws-sdk-js-v3/pull/1526/files#diff-fbf308f8310c0bdaa06094d6f1d5831b (PR adds ToDo comments)

Example:

<details>
<summary>Code</summary>

```js
const { DynamoDB } = require("@aws-sdk/client-dynamodb");

// We're using Pino, customer can pass any logger
const logger = require("pino")({
  level: process.env.LOG_LEVEL || "info",
  prettyPrint: true,
});

(async () => {
  const client = new DynamoDB({ logger });
  await client.listTables({ Limit: 1 });
})();
```

</details>

<details>
<summary>Output</summary>

```console
[1600118095663] INFO  (70609 on 186590ce2139):
    input: {
      "Limit": 1
    }
[1600118096387] INFO  (70609 on 186590ce2139):
    output: {
      "LastEvaluatedTableName": "CUSTOMER_LIST",
      "TableNames": [
        "CUSTOMER_LIST"
      ]
    }
[1600118096387] INFO  (70609 on 186590ce2139):
    retry: {
      "attempts": 1,
      "totalDelay": 0
    }
[1600118096387] INFO  (70609 on 186590ce2139):
    metadata: {
      "httpStatusCode": 200,
      "requestId": "0IG5NTHKJS423VET0CJVG8LF1NVV4KQNSO5AEMVJF66Q9ASUAAJG",
    }
```

</details>

In the above example:
* middleware-retry will `logger.info` retry parameters
* middleware-logger will `logger.info` metadata: httpStatusCode/requestId/extendedRequestId/cfId from response

**Comment by trivikr** [comment]
We plan to remove `$metadata` from the response using a middleware before general availability.
The removal from `$metadata` from SDK will be prioritized later, as it's used internally.
