### ISSUE TITLE
Align published package versions

### ISSUE THREAD

**Issue by rraziel** [aws/aws-sdk-js-v3#1499]
**Is your feature request related to a problem? Please describe.**
Published packages don't 100% have the same version number, e.g.:

- `@aws-sdk/client-*` are currently `1.0.0-gamma.8`
- `@aws-sdk/util-*` or `@aws-sdk/s3-request-presigner` are `1.0.0-gamma.7`
- `@aws-sdk/types` is `1.0.0-gamma.6`

Moreover, compatibility between those versions (even when using the latest available for each) is not always there.

**Describe the solution you'd like**
Having all packages published with the same version number, each time there is a release.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by rraziel** [comment]
And as an up-to-date follow-up, right now:

- `@aws-sdk/client-*` are `1.0.0-gamma.9`
- `@aws-sdk/util-create-request` is `1.0.0-gamma-8`
- `@aws-sdk/util-format-url` is `1.0.0.-gamma.7` (even even `util-*` is not on the same version)
- `@aws-sdk/types` is `1.0.0-gamma.6`

**Comment by rraziel** [comment]
It seems like with version `1.0.0-rc.7` all versions have been aligned 😃 
I think this issue can be closed, if they're going to remain aligned from now on.

**Comment by trivikr** [comment]
Yup, we switched to fixed versioning for RC prereleases in https://github.com/aws/aws-sdk-js-v3/pull/1577, starting with https://github.com/aws/aws-sdk-js-v3/releases/tag/v1.0.0-rc.1
