### ISSUE TITLE
Generate Errors using classes instead of Structures

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#1506]
**Is your feature request related to a problem? Please describe.**
We can't use `instanceof` check on Error shapes, and have to do equality check for string values in err.name
MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#Handling_a_specific_error
Refs: https://github.com/aws/aws-sdk-js-v3/pull/1502#issuecomment-689178056

**Describe the solution you'd like**
Enable `instanceof` check on Errors by using classes on Error shapes instead of Structures

**Describe alternatives you've considered**
Stick with string checks for Errors, i.e. `err.name === "ErrorName"`

**Comment by studds** [comment]
AFAIK it's a good practice to throw Errors and not other things, it'd be nice if this were changed.
