### ISSUE TITLE
IVS CreateChannelRequest/authorized not configurable

### ISSUE THREAD

**Issue by jokester** [aws/aws-sdk-js-v3#1508]
**Describe the bug**
When creating an IVS channel, an `authorized` property is supposed to configurable. This is true in SDK v2 but not in V3 yet.

**SDK version number**
`"@aws-sdk/client-ivs": "^1.0.0-gamma.1",`

**Is the issue in the browser/Node.js/ReactNative?**
Node.js

**Details of the browser/Node.js/ReactNative version**
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`
`node v12.18.2`

**To Reproduce (observed behavior)**

```ts
import * as IVS from '@aws-sdk/client-ivs';

const ivs = new IVS.IvsClient({
      region: 'us-east-1'
    });

async function doCreate() {
 const createdChannel = await this.ivs.send(
      new IVS.CreateChannelCommand({
        // Maximum length: 128 characters. May include numbers, letters, underscore (_), and hyphens (-).
        name: `new-channel-name`,
        latencyMode: 'LOW',
        type: 'STANDARD',
        // @ts-ignore
        authorized: true,
      }),
    );
}
```

would create a channel without `authorized` option. And it does not even type check without `@ts-ignore`.

**Expected behavior**

Create a private channel

**Comment by AllanFly120** [comment]
Hi @jokester 

The `authorized` option is introduced fairly new in v2, [v2.737.0](https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#27370). Currently the models for V3 is slightly lagged behind. The option will be available once the models are updated.
