### ISSUE TITLE
Provide support to serialize dates in util-dynamodb

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#1534]
**Is your feature request related to a problem? Please describe.**
util-dynamodb currently throws error when date is passed.
Refs: https://github.com/aws/aws-sdk-js-v3/pull/1531

**Describe the solution you'd like**
The problem is with JSON spec itself: there is no literal syntax for dates in JSON.
JSON spec: https://www.ietf.org/rfc/rfc4627.txt

Possible solution #1: Convert dates to ISO 8601 strings by default. Provide an option (say `convertDateToNumber`) which converts date to a string value. This option can be passed along with `convertEmptyValues`

Possible solution #2: Expose pre-marshall configuration allowing users to send their own convert functions, detailed in https://github.com/aws/aws-sdk-js-v3/issues/1533

**Describe alternatives you've considered**
Converting dates to String/Number or a different format before passing it to the converter.

**Additional context**
This request was raised in PR https://github.com/aws/aws-sdk-js-v3/pull/1531#issuecomment-695052731

**Comment by trivikr** [comment]
If we go ahead with using `JSON.stringify()` for serializing objects as suggested in https://github.com/aws/aws-sdk-js-v3/issues/1535, then date will be stored as a String in ISO 8601 format.

We still need to discuss adding `convertDateToNumber` (or similar) option, which converts date to number (output of `.getTime()`) instead of string.

**Comment by russell-dot-js** [comment]
I like the idea of ISO 8601 by default, especially considering nobody **wants** the current default behavior of serializing to `{}`. That being said, it's only OK if we allow a way out of it.

convertDateToNumber, just like convertEmptyValues, seems like a trap to me, as it could be a slippery slope:

- convertBufferToArray
- convertPromiseToAwaited
- convertArrayToSet
- convertBigIntToString
- convertGoToRust

**Comment by trivikr** [comment]
Update: we're exploring fixing this using premarshalling https://github.com/aws/aws-sdk-js-v3/issues/1533#issuecomment-702178924
