### ISSUE TITLE
Unit test "NodeHttpHandler › constructor › can set httpAgent and httpsAgent" intermittently fails

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#1539]
**Describe the bug**
Unit test "NodeHttpHandler › constructor › can set httpAgent and httpsAgent" intermittently fails with the following error:

```
FAIL packages/node-http-handler/dist/cjs/node-http-handler.spec.js
--
947 | ● NodeHttpHandler › constructor › can set httpAgent and httpsAgent
948 |  
949 | expect(received).toEqual(expected) // deep equality
950 |  
951 | Expected: 0
952 | Received: Infinity
953 |  
954 | 22 \|         httpsAgent: new https.Agent({ maxSockets }),
955 | 23 \|       });
956 | > 24 \|       expect((nodeHttpHandler as any).httpsAgent.maxSockets).toEqual(maxSockets);
957 | \|                                                              ^
958 | 25 \|     });
959 | 26 \|   });
960 | 27 \|   describe("http", () => {
961 |  
962 | at Object.<anonymous> (src/node-http-handler.spec.ts:24:62)
```

[Example run](https://us-west-2.console.aws.amazon.com/codesuite/codebuild/119327258862/projects/sdk-staging-test/build/sdk-staging-test%3A41343a87-64c7-48fa-a42e-1001e20775ec?region=us-west-2)

**SDK version number**
master

**To Reproduce (observed behavior)**
Intermittent failure

**Expected behavior**
The test succeeds every time it's run

**Comment by mhart** [comment]
I assume `maxSockets = 0` gets turned into `Infinity` – hence this failure. Should be fixed by #1660
