### ISSUE TITLE
Improve the README with list of available service packages

### ISSUE THREAD

**Issue by koiker** [aws/aws-sdk-js-v3#1546]
**Describe the issue with documentation**
For first time users (like me) when you get in the new aws-sdk-js-v3 package and read the documentation (README) you get the benefits of this new version and want to use this new version, but it's explicit described which services are available and the node/browser version syntax or even the alpha/beta/gamma/ga stage. I had to look into the issues list to find some hints on how the package is being structured.

**To Reproduce (observed behavior)**
Ask for new users of this package how they discovered which services are available and what is the syntax to import them into their projects. Probably most part of them spend time in slack/gitter channels or search on issues or stackoverflow.

**Expected behavior**
Include a list of available services in the README and the options available to install the packages. Ex:

`npm install @aws-sdk/<SERVICE>@<RELEASE>`
or 
`yarn install @aws-sdk/<SERVICE>@<RELEASE>`

RELEASE can be: `alpha`, `beta` or `gamma`. Bellow is a list of services and in which release they are available. (example)

| Service name                             | alpha | beta | gamma |
|------------------------------------------|-----|-----|-----|
| `client-accessanalyzer`                  | &check; | &check; | &check; |
| `client-acm`                             | &check; | &check; | &check; |
| `client-acm-pca`                         | &check; | &check; | &check; |
| `client-alexa-for-business`              | &check; | &check; | &check; |
| `client-amplify`                         | &check; | &check; | &check; |
| `client-api-gateway`                     | &check; | &check; | &check; |
| `client-apigatewaymanagementapi`         | &check; | &check; | &check; |
| `client-apigatewayv2`                    | &check; | &check; | &check; |
| `client-app-mesh`                        | &check; | &check; | &check; |
| `client-appconfig`                       | &check; | &check; | &check; |
| `client-application-auto-scaling`        | &check; | &check; | &check; |
| `client-application-discovery-service`   | &check; | &check; | &check; |
| `client-application-insights`            | &check; | &check; | &check; |
| `client-appstream`                       | &check; | &check; | &check; |
| `client-appsync`                         | &check; | &check; | &check; |
| `client-athena`                          | &check; | &check; | &check; |
| `client-auto-scaling`                    | &check; | &check; | &check; |
| `client-auto-scaling-plans`              | &check; | &check; | &check; |
| `client-backup`                          | &check; | &check; | &check; |
| `client-batch`                           | &check; | &check; | &check; |
| `client-braket`                          | &check; | &check; | &check; |
| `client-budgets`                         | &check; | &check; | &check; |
| `client-chime`                           | &check; | &check; | &check; |
| `client-cloud9`                          | &check; | &check; | &check; |
| `client-clouddirectory`                  | &check; | &check; | &check; |
| `client-cloudformation`                  | &check; | &check; | &check; |
| `client-cloudfront`                      | &check; | &check; | &check; |
| `client-cloudhsm`                        | &check; | &check; | &check; |
| `client-cloudhsm-v2`                     | &check; | &check; | &check; |
| `client-cloudsearch`                     | &check; | &check; | &check; |
| `client-cloudsearch-domain`              | &check; | &check; | &check; |
| `client-cloudtrail`                      | &check; | &check; | &check; |
| `client-cloudwatch`                      | &check; | &check; | &check; |
| `client-cloudwatch-events`               | &check; | &check; | &check; |
| `client-cloudwatch-logs`                 | &check; | &check; | &check; |
| `client-codeartifact`                    | &check; | &check; | &check; |
| `client-codebuild`                       | &check; | &check; | &check; |
| `client-codecommit`                      | &check; | &check; | &check; |
| `client-codedeploy`                      | &check; | &check; | &check; |
| `client-codeguru-reviewer`               | &check; | &check; | &check; |
| `client-codeguruprofiler`                | &check; | &check; | &check; |
| `client-codepipeline`                    | &check; | &check; | &check; |
| `client-codestar`                        | &check; | &check; | &check; |
| `client-codestar-connections`            | &check; | &check; | &check; |
| `client-codestar-notifications`          | &check; | &check; | &check; |
| `client-cognito-identity`                | &check; | &check; | &check; |
| `client-cognito-identity-provider`       | &check; | &check; | &check; |
| `client-cognito-sync`                    | &check; | &check; | &check; |
| `client-comprehend`                      | &check; | &check; | &check; |
| `client-comprehendmedical`               | &check; | &check; | &check; |
| `client-compute-optimizer`               | &check; | &check; | &check; |
| `client-config-service`                  | &check; | &check; | &check; |
| `client-connect`                         | &check; | &check; | &check; |
| `client-connectparticipant`              | &check; | &check; | &check; |
| `client-cost-and-usage-report-service`   | &check; | &check; | &check; |
| `client-cost-explorer`                   | &check; | &check; | &check; |
| `client-data-pipeline`                   | &check; | &check; | &check; |
| `client-database-migration-service`      | &check; | &check; | &check; |
| `client-dataexchange`                    | &check; | &check; | &check; |
| `client-datasync`                        | &check; | &check; | &check; |
| `client-dax`                             | &check; | &check; | &check; |
| `client-detective`                       | &check; | &check; | &check; |
| `client-device-farm`                     | &check; | &check; | &check; |
| `client-direct-connect`                  | &check; | &check; | &check; |
| `client-directory-service`               | &check; | &check; | &check; |
| `client-dlm`                             | &check; | &check; | &check; |
| `client-docdb`                           | &check; | &check; | &check; |
| `client-dynamodb`                        | &check; | &check; | &check; |
| `client-dynamodb-streams`                | &check; | &check; | &check; |
| `client-ebs`                             | &check; | &check; | &check; |
| `client-ec2`                             | &check; | &check; | &check; |
| `client-ec2-instance-connect`            | &check; | &check; | &check; |
| `client-ecr`                             | &check; | &check; | &check; |
| `client-ecs`                             | &check; | &check; | &check; |
| `client-efs`                             | &check; | &check; | &check; |
| `client-eks`                             | &check; | &check; | &check; |
| `client-elastic-beanstalk`               | &check; | &check; | &check; |
| `client-elastic-inference`               | &check; | &check; | &check; |
| `client-elastic-load-balancing`          | &check; | &check; | &check; |
| `client-elastic-load-balancing-v2`       | &check; | &check; | &check; |
| `client-elastic-transcoder`              | &check; | &check; | &check; |
| `client-elasticache`                     | &check; | &check; | &check; |
| `client-elasticsearch-service`           | &check; | &check; | &check; |
| `client-emr`                             | &check; | &check; | &check; |
| `client-eventbridge`                     | &check; | &check; | &check; |
| `client-firehose`                        | &check; | &check; | &check; |
| `client-fms`                             | &check; | &check; | &check; |
| `client-forecast`                        | &check; | &check; | &check; |
| `client-forecastquery`                   | &check; | &check; | &check; |
| `client-frauddetector`                   | &check; | &check; | &check; |
| `client-fsx`                             | &check; | &check; | &check; |
| `client-gamelift`                        | &check; | &check; | &check; |
| `client-glacier`                         | &check; | &check; | &check; |
| `client-global-accelerator`              | &check; | &check; | &check; |
| `client-glue`                            | &check; | &check; | &check; |
| `client-greengrass`                      | &check; | &check; | &check; |
| `client-groundstation`                   | &check; | &check; | &check; |
| `client-guardduty`                       | &check; | &check; | &check; |
| `client-health`                          | &check; | &check; | &check; |
| `client-honeycode`                       | &check; | &check; | &check; |
| `client-iam`                             | &check; | &check; | &check; |
| `client-imagebuilder`                    | &check; | &check; | &check; |
| `client-inspector`                       | &check; | &check; | &check; |
| `client-iot`                             | &check; | &check; | &check; |
| `client-iot-1click-devices-service`      | &check; | &check; | &check; |
| `client-iot-1click-projects`             | &check; | &check; | &check; |
| `client-iot-data-plane`                  | &check; | &check; | &check; |
| `client-iot-events`                      | &check; | &check; | &check; |
| `client-iot-events-data`                 | &check; | &check; | &check; |
| `client-iot-jobs-data-plane`             | &check; | &check; | &check; |
| `client-iotanalytics`                    | &check; | &check; | &check; |
| `client-iotsecuretunneling`              | &check; | &check; | &check; |
| `client-iotsitewise`                     | &check; | &check; | &check; |
| `client-iotthingsgraph`                  | &check; | &check; | &check; |
| `client-ivs`                             | &check; | &check; | &check; |
| `client-kafka`                           | &check; | &check; | &check; |
| `client-kendra`                          | &check; | &check; | &check; |
| `client-kinesis`                         | &check; | &check; | &check; |
| `client-kinesis-analytics`               | &check; | &check; | &check; |
| `client-kinesis-analytics-v2`            | &check; | &check; | &check; |
| `client-kinesis-video`                   | &check; | &check; | &check; |
| `client-kinesis-video-archived-media`    | &check; | &check; | &check; |
| `client-kinesis-video-media`             | &check; | &check; | &check; |
| `client-kinesis-video-signaling`         | &check; | &check; | &check; |
| `client-kms`                             | &check; | &check; | &check; |
| `client-lakeformation`                   | &check; | &check; | &check; |
| `client-lambda`                          | &check; | &check; | &check; |
| `client-lex-model-building-service`      | &check; | &check; | &check; |
| `client-lex-runtime-service`             | &check; | &check; | &check; |
| `client-license-manager`                 | &check; | &check; | &check; |
| `client-lightsail`                       | &check; | &check; | &check; |
| `client-machine-learning`                | &check; | &check; | &check; |
| `client-macie`                           | &check; | &check; | &check; |
| `client-macie2`                          | &check; | &check; | &check; |
| `client-managedblockchain`               | &check; | &check; | &check; |
| `client-marketplace-catalog`             | &check; | &check; | &check; |
| `client-marketplace-commerce-analytics`  | &check; | &check; | &check; |
| `client-marketplace-entitlement-service` | &check; | &check; | &check; |
| `client-marketplace-metering`            | &check; | &check; | &check; |
| `client-mediaconnect`                    | &check; | &check; | &check; |
| `client-mediaconvert`                    | &check; | &check; | &check; |
| `client-medialive`                       | &check; | &check; | &check; |
| `client-mediapackage`                    | &check; | &check; | &check; |
| `client-mediapackage-vod`                | &check; | &check; | &check; |
| `client-mediastore`                      | &check; | &check; | &check; |
| `client-mediastore-data`                 | &check; | &check; | &check; |
| `client-mediatailor`                     | &check; | &check; | &check; |
| `client-migration-hub`                   | &check; | &check; | &check; |
| `client-migrationhub-config`             | &check; | &check; | &check; |
| `client-mobile`                          | &check; | &check; | &check; |
| `client-mq`                              | &check; | &check; | &check; |
| `client-mturk`                           | &check; | &check; | &check; |
| `client-neptune`                         | &check; | &check; | &check; |
| `client-networkmanager`                  | &check; | &check; | &check; |
| `client-opsworks`                        | &check; | &check; | &check; |
| `client-opsworkscm`                      | &check; | &check; | &check; |
| `client-organizations`                   | &check; | &check; | &check; |
| `client-outposts`                        | &check; | &check; | &check; |
| `client-personalize`                     | &check; | &check; | &check; |
| `client-personalize-events`              | &check; | &check; | &check; |
| `client-personalize-runtime`             | &check; | &check; | &check; |
| `client-pi`                              | &check; | &check; | &check; |
| `client-pinpoint`                        | &check; | &check; | &check; |
| `client-pinpoint-email`                  | &check; | &check; | &check; |
| `client-pinpoint-sms-voice`              | &check; | &check; | &check; |
| `client-polly`                           | &check; | &check; | &check; |
| `client-pricing`                         | &check; | &check; | &check; |
| `client-qldb`                            | &check; | &check; | &check; |
| `client-qldb-session`                    | &check; | &check; | &check; |
| `client-quicksight`                      | &check; | &check; | &check; |
| `client-ram`                             | &check; | &check; | &check; |
| `client-rds`                             | &check; | &check; | &check; |
| `client-rds-data`                        | &check; | &check; | &check; |
| `client-redshift`                        | &check; | &check; | &check; |
| `client-rekognition`                     | &check; | &check; | &check; |
| `client-resource-groups`                 | &check; | &check; | &check; |
| `client-resource-groups-tagging-api`     | &check; | &check; | &check; |
| `client-robomaker`                       | &check; | &check; | &check; |
| `client-route-53`                        | &check; | &check; | &check; |
| `client-route-53-domains`                | &check; | &check; | &check; |
| `client-route53resolver`                 | &check; | &check; | &check; |
| `client-s3`                              | &check; | &check; | &check; |
| `client-s3-control`                      | &check; | &check; | &check; |
| `client-sagemaker`                       | &check; | &check; | &check; |
| `client-sagemaker-a2i-runtime`           | &check; | &check; | &check; |
| `client-sagemaker-runtime`               | &check; | &check; | &check; |
| `client-savingsplans`                    | &check; | &check; | &check; |
| `client-schemas`                         | &check; | &check; | &check; |
| `client-secrets-manager`                 | &check; | &check; | &check; |
| `client-securityhub`                     | &check; | &check; | &check; |
| `client-serverlessapplicationrepository` | &check; | &check; | &check; |
| `client-service-catalog`                 | &check; | &check; | &check; |
| `client-service-quotas`                  | &check; | &check; | &check; |
| `client-servicediscovery`                | &check; | &check; | &check; |
| `client-ses`                             | &check; | &check; | &check; |
| `client-sesv2`                           | &check; | &check; | &check; |
| `client-sfn`                             | &check; | &check; | &check; |
| `client-shield`                          | &check; | &check; | &check; |
| `client-signer`                          | &check; | &check; | &check; |
| `client-sms`                             | &check; | &check; | &check; |
| `client-snowball`                        | &check; | &check; | &check; |
| `client-sns`                             | &check; | &check; | &check; |
| `client-sqs`                             | &check; | &check; | &check; |
| `client-ssm`                             | &check; | &check; | &check; |
| `client-sso`                             | &check; | &check; | &check; |
| `client-sso-oidc`                        | &check; | &check; | &check; |
| `client-storage-gateway`                 | &check; | &check; | &check; |
| `client-sts`                             | &check; | &check; | &check; |
| `client-support`                         | &check; | &check; | &check; |
| `client-swf`                             | &check; | &check; | &check; |
| `client-synthetics`                      | &check; | &check; | &check; |
| `client-textract`                        | &check; | &check; | &check; |
| `client-transcribe`                      | &check; | &check; | &check; |
| `client-transcribe-streaming`            | &check; | &check; | &check; |
| `client-transfer`                        | &check; | &check; | &check; |
| `client-translate`                       | &check; | &check; | &check; |
| `client-waf`                             | &check; | &check; | &check; |
| `client-waf-regional`                    | &check; | &check; | &check; |
| `client-wafv2`                           | &check; | &check; | &check; |
| `client-workdocs`                        | &check; | &check; | &check; |
| `client-worklink`                        | &check; | &check; | &check; |
| `client-workmail`                        | &check; | &check; | &check; |
| `client-workmailmessageflow`             | &check; | &check; | &check; |
| `client-workspaces`                      | &check; | &check; | &check; |
| `client-xray`                            | &check; | &check; | &check; |

**Screenshots**

**Additional context**
I have to inspect the git repo to get the list of services, if a user find this package by npm he will not be able to see the list of services unless he spend some time searching for more info and get to the source code. Documentation will be very helpful in this development phase to get more users to test the new packages.
The table above is just an example on how users can use this v3, but I saw somewhere that there is the `node` and `browser` version of the package. How can we install one or another? What is the differences of each one? It's all those aspects of the package that will be good to include in the README or in the package description to make more easier to people to start using.

**Comment by trivikr** [comment]
We're using `latest` tag for Release Candidate versions, so yarn add or npm install would install the latest RC version.

The API Reference is being built, and will contain list of clients.
We'll provide a link to API reference from README once it's ready.
