### ISSUE TITLE
SQS sendMessage results in two identical messages in the queue

### ISSUE THREAD

**Issue by ddrinka** [aws/aws-sdk-js-v3#1556]
**Describe the bug**
Using SQS sendMessage in a typical way results in two identical messages being added to the destination queue.  Swapping the SDK to v2 resolves the issue.

**SDK version number**
`1.0.0-gamma.11`

**Is the issue in the browser/Node.js/ReactNative?**
Node.js

**Details of the browser/Node.js/ReactNative version**
`v12.19.0`

**To Reproduce (observed behavior)**
```
    async _enqueueResultAsync(attributes, buffer) {
        await this._ensureQueuesExistAsync();
        await this.#sqs.sendMessage({
            MessageBody: buffer.toString('base64'),
            QueueUrl: this.#outputQueueUrl,
            MessageAttributes: attributes.toApiMessageAttributes()
        });
    }
```

**Expected behavior**
A single message is added to the queue.

**Comment by alexforsyth** [comment]
@ddrinka Do you think you could provide a few more details? This seems to be working as intended. Here's the code i'm testing out and it seems to only add once to the queue. Currently using rc.3 

```
import { SQS } from "@aws-sdk/client-sqs"

(async () => {
    const sqsClient = new SQS({});

    const result = await sqsClient.sendMessage({
        MessageBody: "hello this is my message #1",
        MessageGroupId: "test-grouping-12345",
        MessageDeduplicationId: "de-duplication-id-123456",
        QueueUrl: "https://sqs.us-west-2.amazonaws.com/119327258862/test-sqs-client.fifo"
    });

    console.log(result);
})();
```

**Comment by ddrinka** [comment]
@alexforsyth I don't have a test environment set up for this any longer.  I wonder, however, if including the MessageDeduplicationId is masking any issue with the api called from your test case.

**Comment by alexforsyth** [comment]
@ddrinka yep. I included that flag explicitly as I assumed you have `ContentBasedDeduplication` disabled in your sqs queue.

If you don't include `MessageDeduplicationId ` you should get the following error:
```
(node:21840) UnhandledPromiseRejectionWarning: InvalidParameterValue: The queue should either have ContentBasedDeduplication enabled or MessageDeduplicationId provided explicitly
```

For the sake of completeness, i've tested this out with/without `MessageDeduplicationId ` and with/without `ContentBasedDeduplication` and i'm still not able to reproduce this issue. If you're still running into this problem could you provide a few more details to me reproduce the error?

**Comment by ddrinka** [comment]
@alexforsyth I reverted that code base to aws-sdk-js-v2 so I can't repro for you.  If it's working fine on your side feel free to close this.

**Comment by alexforsyth** [comment]
@ddrinka sounds good. If you do end up encountering this issue again please reopen or let us know!
