### ISSUE TITLE
IoTClient is incorrectly calculating the request signature

### ISSUE THREAD

**Issue by grahamford** [aws/aws-sdk-js-v3#1569]
**Describe the bug**
The IoTClient is incorrectly calculating the signature

**SDK version number**
@aws-sdk/client-iot 1.0.0-gamma.11

**Is the issue in the browser/Node.js/ReactNative?**
Node

**Details of the browser/Node.js/ReactNative version**
14.4.0

**To Reproduce (observed behavior)**
``` Typescript
import { IoTClient, GetIndexingConfigurationCommand } from '@aws-sdk/client-iot';
import { Credentials } from '@aws-sdk/types';

const credentials: Credentials = {
  accessKeyId: 'my-key',
  secretAccessKey: 'my-secret'
}

new IoTClient({region: 'us-east-1', credentials: credentials })
  .send(new GetIndexingConfigurationCommand({}))
  .then(() => console.log('Success'))
  .catch(err => console.log('Error:', err))
```

The output is
``` Console
InvalidSignatureException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
    at deserializeAws_restJson1GetIndexingConfigurationCommandError (/Users/work/Developer/iot-test/node_modules/@aws-sdk/client-iot/protocols/Aws_restJson1.ts:17164:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 403,
    httpHeaders: {
      date: 'Tue, 13 Oct 2020 15:01:08 GMT',
      'content-type': 'application/json',
      'content-length': '193',
      connection: 'close',
      'x-amzn-requestid': 'dd173bb2-3f2e-4587-b45c-dbba18efb610',
      'x-amzn-errortype': 'InvalidSignatureException',
      'x-amz-apigw-id': 'UWsgRHivoAMFQmQ=',
      'x-amzn-trace-id': 'Root=1-5f85c134-4d0b0e701ccf9903574008ff'
    },
    requestId: 'dd173bb2-3f2e-4587-b45c-dbba18efb610',
    attempts: 3,
    totalRetryDelay: 447
  }
}
```

**Expected behavior**
The result should be a json string when IoT services are available
eg
```
{
    "thingIndexingConfiguration": {
        "thingIndexingMode": "OFF",
        "thingConnectivityIndexingMode": "OFF"
    },
    "thingGroupIndexingConfiguration": {
        "thingGroupIndexingMode": "OFF"
    }
}
```

**Screenshots**

**Additional context**
This was working in the preview versions of the libraries

The equivalent CLI version is  `aws iot get-indexing-configuration --region=eu-west-1`

**Comment by alexforsyth** [comment]
@GrahamFord I unfortunately this error may require more investigation. IotClient is being uncooperative on my local machine, although I think thats due to other issues as Iot works just fine.

They both send the same request with the same headers under the hood.

```
(async () => {
    
    let iotclient = new IoT({});
    let result = iotclient.getIndexingConfiguration({});

    try{
        console.log(await result);    
    } catch(error) {
        console.log(error);
    }
    
})();
```

**Comment by simonbuchan** [comment]
Not sure if this is the same error or why it would matter, but in an electron renderer process (seems like it's using the node implementation, since requests don't show up in devtools network tab) with `@aws-sdk/client-iot@1.0.0-rc.6` I get `InvalidSignatureException: Credential should be scoped to correct service: 'execute-api'.`, when it worked with `1.0.0-gamma.6`. If I add `signingName: "execute-api"` to the config then it works.

Not sure why it would make any difference looking at the code, since `endpoints.ts` has had `signingService: "execute-api"` since it was added 10 months ago, and the client code that pulls it out hasn't changed since then either?

**Comment by GrahamFord** [comment]
Updating from the Gamma to the RC release gave me the same error about scoping the credentials @simonbuchan 

I added this to the code @alexforsyth suggested
``` javascript
(async () => {
    const { IoT } = require('@aws-sdk/client-iot');

    const credentials = {
      accessKeyId: 'my-key',
      secretAccessKey: 'my-secret',
    }
    let iotclient = new IoT({
      region: 'us-east-1',
      credentials: credentials,
      signingName: 'execute-api',
    });
    let result = iotclient.getIndexingConfiguration({});

    try{
        console.log(await result);
    } catch(error) {
        console.log(error);
    }
})();
```
but it's still throwing the error
> InvalidSignatureException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The biggest difference between my code and yours is that I'm passing in the credentials to the client as a parameter. Could this be the reason behind the error?

**Comment by simonbuchan** [comment]
Hmm, seems like I should probably break out my issue then, since it reproduces differently.

**Comment by ajredniwja** [comment]
Hi there, is this still an issue with the latest client? 

I wasn't able to reproduce this using similar code:

```JavaScript
const { IoTClient, GetIndexingConfigurationCommand } = require("@aws-sdk/client-iot");

(async () => {
    
    const client = new IoTClient({ region: "us-west-2" });

    var request = new GetIndexingConfigurationCommand();
    let result = client.send(request);

    try{
        console.log(await result);    
    } catch(error) {
        console.log(error);
    }
    
})();
```

**Comment by grahamford** [comment]
@ajredniwja your test code isn't passing in the credentials when creating the IoT client. That seemed to be the sticking point. See https://github.com/aws/aws-sdk-js-v3/issues/1569#issuecomment-730231394
