### ISSUE TITLE
TagSpecification parameter missed in CreateKeyPairInput object in client-ec2-node  module

### ISSUE THREAD

**Issue by Dataxelio** [aws/aws-sdk-js-v3#1581]
**Describe the bug**
TagSpecification parameter is missed in CreateKeyPairInput object used to instantiate the CreateKeyPairCommand

**SDK version number**
0.1.0-preview.2

**Is the issue in the browser/Node.js/ReactNative?**
Node.js

**To Reproduce (observed behavior)**
TagSpecification parameter missed in CreateKeyPairInput object. Note that this is available in v2

**Expected behavior**
TagSpecification parameter available in CreateKeyPairInput object. Note that this is available in v2

**Comment by AllanFly120** [comment]
Hi @Dataxelio 

The package version you are referring to was released over 1 year ago, can you try reproduce the issue with latest version?

**Comment by Dataxelio** [comment]
Hi @AllanFly120 

How can I get the latest version ?
I can only see 0.1.0-preview.2 version on npm

![image](https://user-images.githubusercontent.com/62846298/96521329-50bb7900-1271-11eb-9e24-f4990cc810ea.png)

Thanks for your help

**Comment by trivikr** [comment]
> How can I get the latest version ?

The client name is updated, and is now [@aws-sdk/client-ec2](https://www.npmjs.com/package/@aws-sdk/client-ec2)
You can refer our blog post for [Modular AWS SDK for JavaScript Release Candidate](https://aws.amazon.com/blogs/developer/modular-aws-sdk-for-javascript-release-candidate/).

**Comment by alexforsyth** [comment]
Closing
