### ISSUE TITLE
SQS receiveMessage makes 2 requests

### ISSUE THREAD

**Issue by zamu87** [aws/aws-sdk-js-v3#1582]
**Describe the bug**
Using SQS receiveMessage in a FIFO queue, 2 identical requests are generated causing a long delay in returning result because the second request wait for VisibilityTimeout. Swapping the SDK to v2 resolves the issue.

**SDK version number**
1.0.0-gamma.11

**Is the issue in the browser/Node.js/ReactNative?**
Node.js

**Details of the browser/Node.js/ReactNative version**
v14.14.0

**To Reproduce (observed behavior)**
```
const params = {
            AttributeNames: ["SentTimestamp"],
            MaxNumberOfMessages: 1, 
            MessageAttributeNames: ["All"],
            QueueUrl: queueUrl,
            VisibilityTimeout: 20,
            WaitTimeSeconds: 20,
        };
const response = await this.connection.receiveMessage(params);
```

**Expected behavior**
A single request should be done.

**Comment by ShogunPanda** [comment]
I can confirm this also happens in non FIFO queues.

**Comment by artur-ma** [comment]
Can confirm also

**Comment by rahulswarnkar** [comment]
Something similar on send side #1742?

**Comment by trivikr** [comment]
The issue with receiveMessage was fixed in rc.6 in PR https://github.com/aws/aws-sdk-js-v3/pull/1680
The fix for sendMessage is posted in https://github.com/aws/aws-sdk-js-v3/issues/1742, and will be published with rc.9
