### ISSUE TITLE
Step Function calls throw CORS errors

### ISSUE THREAD

**Issue by dschultz0** [aws/aws-sdk-js-v3#1588]
**Describe the bug**
Calls to Step Functions fail due to CORS errors when called from the browser

**SDK version number**
1.0.0-gamma.11

**Is the issue in the browser/Node.js/ReactNative?**
Browser

**Details of the browser/Node.js/ReactNative version**
Chrome v86

**To Reproduce (observed behavior)**
const sfn = new SFN({region: 'us-west-2', credentials: {accessKeyId: '<>', secretAccessKey: '<>'}})
sfn.listStateMachines({maxResults: 20, nextToken: null}).then(data => console.log(data)).catch(err => console.error(err))

Results in:
Access to fetch at 'https://states.us-west-2.amazonaws.com/' from origin 'http://localhost:59000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Expected behavior**
Request succeeds

**Additional context**
Most services don't require any special steps to handle CORS although S3 has a configuration option:
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/cors.html
That said, it appears this is a long running issue with Step Functions:
https://forums.aws.amazon.com/thread.jspa?messageID=770558

**Comment by alexforsyth** [comment]
Looks like this is an issue with the service team. I'll keep it in the backlog and we're having internal discussions on how we may be able to mitigate this in v3. 

@dschultz0 thanks for filing this. It would be very helpful if you can raise the issue with the service on the AWS forums as well. This will help visibility. https://forums.aws.amazon.com/forum.jspa?forumID=237&start=0. I'll create an internal ticket to the team as well.
