### ISSUE TITLE
[@aws-sdk/ssm-client] "Error: write EPIPE" during PutParameter operation in long-running NodeJS process

### ISSUE THREAD

**Issue by Obirah** [aws/aws-sdk-js-v3#1589]
**Describe the bug**
I am using the new SSM client in order to store SSM parameters in a small NodeJS/TypeScript CommanderJS CLI tool that I implemented for installing OpenShift 4 clusters on AWS.

During the first tests, I had no problems with the PutParameter operation. But now that the whole installation routine is implemented, I am getting the following error during a PutParameter operation (SecureString parameter in default tier):

```
Error: write EPIPE
     at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
     at writevGeneric (internal/stream_base_commons.js:134:26)
     at TLSSocket.Socket._writeGeneric (net.js:783:11)
     at TLSSocket.Socket._writev (net.js:792:8)
     at doWrite (_stream_writable.js:375:12)
     at clearBuffer (_stream_writable.js:521:5)
     at TLSSocket.Writable.uncork (_stream_writable.js:317:7)
     at ClientRequest._flushOutput (_http_outgoing.js:908:10)
     at ClientRequest._flush (_http_outgoing.js:877:22)
     at _http_client.js:325:47 {
   errno: -32,
   code: 'EPIPE',
   syscall: 'write',
   '$metadata': { attempts: 1, totalRetryDelay: 0 }
 }
```

At the point where the PutParameter operation is triggered the process has been running for around 45 minutes. It runs in a docker-based GitLab CI runner on AWS.

If I use exactly the same PutParameter code in short-running process (without installing OpenShift before and so on), it works without any problem.

My SDK v3 code looks like this (the returned promise, of course is awaited in another piece of code):
```
const command = new PutParameterCommand({
    Name: name,
    Type: ParameterType.SECURE_STRING,
    Overwrite: true,
    Value: value
});

return this.ssm.send(command).then(response =>
    console.log(response)
);
```

In order to verify that this is an issue with the SDK, I replaced the V3 code with the following V2 code:
```
return this.legacySsm.putParameter({
        Name: name,
        Overwrite: true,
        Type: 'SecureString',
        Value: value })
    .promise()
    .then(response => console.log(response));
```
With the V2 code I am not getting the error in my long-running installation routine.

**SDK version number**
V3 with the bug: 1.0.0-gamma.11
V2 without the bug: 2.774.0

**Is the issue in the browser/Node.js/ReactNative?**
NodeJS 14 (tried 10 as well, in order to verify that the problems occurs on multiple versions)
CentOS and Alpine (tried both in order to verify, it is not an OS problem)

**Details of the browser/Node.js/ReactNative version**
14.6.0

**To Reproduce (observed behavior)**
Not sure if this is reproducable, it looks like a classical Heisenbug.

**Expected behavior**
The PutParameter operation should be working with V3 as it does with V2.

**Comment by zxkane** [comment]
I met the same issue when using both `1.0.0.rc2` and `1.0.0.rc3`. The usage is quite simple to call ssm/sns API in lambda NODE 12.x runtime in region `cn-northwest-1`. 

It’s an intermittent issue, the error mostly happened when the lambda executed the first request.

**Comment by monken** [comment]
https://github.com/aws/aws-sdk-js-v3/issues/1196

**Comment by polovi** [comment]
> I met the same issue when using both `1.0.0.rc2` and `1.0.0.rc3`. The usage is quite simple to call ssm/sns API in lambda NODE 12.x runtime in region `cn-northwest-1`.
> 
> It’s an intermittent issue, the error mostly happened when the lambda executed the first request.

Its happen randomly across all clients in lambda runtime. Sometime in heavy load sometime in first cold start.

**Comment by trivikr** [comment]
This issue was fixed in https://github.com/aws/aws-sdk-js-v3/issues/1196, and the fix was verified in rc.7 https://github.com/aws/aws-sdk-js-v3/issues/1196#issuecomment-731297200

The NodeHttpHandler now retried `EPIPE` errors.
https://github.com/aws/aws-sdk-js-v3/blob/56c363955b5d278446d86736ebb4b2589fb8d261/packages/node-http-handler/src/constants.ts#L4
