### ISSUE TITLE
Connect Client fails with `CORS policy: Request header field amz-sdk-invocation-id is not allowed`

### ISSUE THREAD

**Issue by anantoghosh** [aws/aws-sdk-js-v3#1590]
**Describe the bug**
Using the v3 sdk connect client fails with 
> Access to fetch at 'https://connect.us-east-1.amazonaws.com/contact/attributes' from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field amz-sdk-invocation-id is not allowed by Access-Control-Allow-Headers in preflight response.

```
const params = {...}
const credentials = await Auth.currentUserCredentials();
const connectClient = new ConnectClient({
        region: this.region,
        credentials,
      });
await connectClient.send(new UpdateContactAttributesCommand(params));
```

**SDK version number**
`"@aws-sdk/client-connect": "1.0.0-rc.1"`

**Is the issue in the browser/Node.js/ReactNative?**
Browser

**Screenshots**
![image](https://user-images.githubusercontent.com/12339068/96712187-96e90900-1353-11eb-9b81-da9feabed1a5.png)

**Additional context**
The last version which worked was `1.0.0-gamma.2`
The options response indeed does not send `amz-sdk-invocation-id` in allowed headers which is being sent by the connect client.

**Comment by alexforsyth** [comment]
We're following up with the service team on this one. We'll keep you up to date on this one.

**Comment by trivikr** [comment]
Connect service now support retry CORS headers.

Tested using the curl command:
```
$ curl --insecure -i -X OPTIONS https://connect.us-east-1.amazonaws.com/routing-profiles/stringvalue/stringvalue/associate-queues -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36" -H "Origin: https://foo.example" -H "Access-Control-Request-Method: POST" -H "Access-Control-Request-Headers: Content-Type,user-agent,content-length,host,Authorization,amz-sdk-invocation-id,amz-sdk-request,x-amz-security-token" -H "host: connect.us-east-1.amazonaws.com"

HTTP/2 200 
date: Thu, 12 Nov 2020 16:27:29 GMT
content-type: application/json
content-length: 0
x-amzn-requestid: 56e74fd9-4937-44bb-995e-e1d72d9d0ce2
access-control-allow-origin: *
access-control-allow-headers: Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-Content-Sha256,X-Amz-User-Agent,amz-sdk-invocation-id,amz-sdk-request
x-amz-apigw-id: V5xR0GphoAMFhQw=
access-control-allow-methods: POST
x-amzn-trace-id: Root=1-5fad6271-6df71cb73a9eb5cd488e78e4
```

The Connect clients from all RC versions will no longer through CORS errors.
