### ISSUE TITLE
Add keywords in package.json for clients

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#1592]
**Is your feature request related to a problem? Please describe.**
Keywords are missing in clients packages. Example: https://github.com/aws/aws-sdk-js-v3/blob/master/clients/client-s3/package.json

Keywords help people discover package as listed in npm search: https://docs.npmjs.com/files/package.json#keywords

**Describe the solution you'd like**
Add keywords for clients packages.

**Describe alternatives you've considered**
N/A

**Comment by kuhe** [comment]
Closing this, if you have an implementation plan we can revisit it later. Currently I don't know how we'd get the keywords.
