### ISSUE TITLE
Error thrown from `s3.headObject` is missing `errorType`

### ISSUE THREAD

**Issue by vivmaha** [aws/aws-sdk-js-v3#1596]
**Describe the bug**
If you call `S3.headObject` for a `Key` that does not exist, the sdk throws an error in which `errorType` is an empty string. In the v2 sdk, `errorTYpe` used to be `"Forbidden"` (or `"NotFound"` if you had the right bucket permissions). 

**SDK version number**
1.0.0-rc.1

**Is the issue in the browser/Node.js/ReactNative?**
Node.js

**Details of the browser/Node.js/ReactNative version**
nodejs12.x

**To Reproduce (observed behavior)**
````
import { S3 } from "@aws-sdk/client-s3";
import { Handler } from "aws-lambda";

interface ParseFileEvent {
  s3Key: string;
}

export const parseFile: Handler<ParseFileEvent> = async (event) => {
  log(`parse() called with [${JSON.stringify(event)}].`);
  const s3 = new S3({});
  log(`Bucketname = ${parserUtils.getBucketName()}`);
  const headObject = await s3.headObject({
    Bucket: parserUtils.getBucketName(),
    Key: event.s3Key,
  });
````

Then, invoke the lambda with an s3Key that doesn't exist. 

**Expected behavior**
The error that is thrown should have `errorType` set to `Forbidden`.

**Screenshots**
Here is how it shows up in cloudwatch:
![image](https://user-images.githubusercontent.com/6677347/96898829-0c80d200-1445-11eb-8721-556ee1b31fd7.png)

**Additional context**
The `$metadata.httpStatusCode` is correctly 403, so that is nice, but the `errorType` is what we've been coding against. 

I discovered this while testing if the v3 sdk will solve the call stack issues I was running into related to https://github.com/aws/aws-sdk-js/issues/3093, and thankfully it did, so that is nice too.

**Comment by trivikr** [comment]
@vivmaha We're populating `"NotFound"` in error.name as shown in the code below:

<details>
<summary>Code</summary>

```js
const AWS = require("aws-sdk");
const { S3 } = require("@aws-sdk/client-s3");

(async () => {
  const region = "us-west-2";

  const v2Client = new AWS.S3({ region });
  const v3Client = new S3({ region });

  const Bucket = `test-bucket-${Math.ceil(Math.random() * 10 ** 10)}`;
  const Key = `non-existent-key`;
  await v3Client.createBucket({ Bucket });

  // Waiters are not available in v3.
  await v2Client.waitFor("bucketExists", { Bucket }).promise();

  try {
    await v3Client.headObject({ Bucket, Key });
  } catch (e) {
    console.log(JSON.stringify(e, null, 2));
  }

  await v3Client.deleteBucket({ Bucket });
})();

```

</details>

<details>
<summary>Output</summary>

```
{
  "name": "NotFound",
  "$fault": "client",
  "$metadata": {
    "httpStatusCode": 404,
    "httpHeaders": {
      "x-amz-request-id": "5E3E5F33392F5091",
      "x-amz-id-2": "W8Zsx6ORYaHyd1ZJ6Bib8G24Byze7c0sypGYer/lOOTsZbe7kIAXyGYqny4gTnzwWZPqxwQcy1Y=",
      "content-type": "application/xml",
      "transfer-encoding": "chunked",
      "date": "Thu, 22 Oct 2020 23:54:51 GMT",
      "server": "AmazonS3"
    },
    "attempts": 1,
    "totalRetryDelay": 0
  }
}
```

</details>

Where are you searching for errorType?

**Comment by vivmaha** [comment]
Hi @trivikr, it sure does look like it is doing the right thing for `NotFound`.

I was running into the `Forbidden` error (with an `httpStatusCode` of `403`). You get this when you do not have `list-objects` permission on the bucket I believe. 

Here is the cloudwatch log line that shows the empty `errorType`:

````
2020-10-22T15:42:01.375Z	e5db6ade-4522-4f78-9c03-e84ee5b8eced	ERROR	Invoke Error 	
{
    "errorType": "",
    "errorMessage": "",
    "name": "",
    "$fault": "client",
    "$metadata": {
        "httpStatusCode": 403,
        "httpHeaders": {
            "x-amz-request-id": "A3BEEE4917D4C6E5",
            "x-amz-id-2": "FUDZ0rqO1SSe85aE0BIUbMig0omKEsGHJfGx2JU+ZnOUKShEAH1IeCcBE1GMsRyu+PSd0aDI/HU=",
            "content-type": "application/xml",
            "transfer-encoding": "chunked",
            "date": "Thu, 22 Oct 2020 15:42:01 GMT",
            "server": "AmazonS3"
        },
        "attempts": 1,
        "totalRetryDelay": 0
    },
    "stack": [
        "",
        "    at deserializeAws_restXmlHeadObjectCommandError (/var/task/node_modules/@aws-sdk/client-s3/dist/cjs/protocols/Aws_restXml.js:5810:41)",
        "    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
        "    at async /var/task/node_modules/@aws-sdk/middleware-serde/dist/cjs/deserializerMiddleware.js:12:20",
        "    at async /var/task/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:12:24",
        "    at async StandardRetryStrategy.retry (/var/task/node_modules/@aws-sdk/middleware-retry/dist/cjs/defaultStrategy.js:55:46)",
        "    at async /var/task/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22",
        "    at async Runtime.exports.parseFile [as handler] (/var/task/src/handlers/parser/parse-file-lambda-aws.js:138:24)"
    ]
}
````

Hope this helps.

**Comment by eryon** [comment]
I will second this: with a `403 Forbidden` error, the `message` and `name` fields are missing and the actual reason is not obvious:
```
{
    "level": 50,
    "time": 1612573455574,
    "pid": 8,
    "hostname": "<snip>",
    "module": "/index.js",
    "err": {
        "type": "Error",
        "message": "",
        "stack": "\n    at deserializeAws_restXmlHeadObjectCommandError (/var/task/node_modules/@aws-sdk/client-s3/protocols/Aws_restXml.ts:7587:39)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at /var/task/node_modules/@aws-sdk/middleware-serde/src/deserializerMiddleware.ts:20:18\n    at /opt/nodejs/node_modules/@aws-sdk/middleware-signing/src/middleware.ts:26:22\n    at StandardRetryStrategy.retry (/opt/nodejs/node_modules/@aws-sdk/middleware-retry/src/defaultStrategy.ts:125:38)\n    at /opt/nodejs/node_modules/@aws-sdk/middleware-logger/src/loggerMiddleware.ts:21:20",
        "name": "",
        "$fault": "client",
        "$metadata": {
            "httpStatusCode": 403,
            "extendedRequestId": "3NLd7mAZD9wrxsmK0fjymYkDqTCcGOvXT4TNawbP/jw6+KYfxLn36coff72/BhT5tkNbqlgnGww=",
            "attempts": 1,
            "totalRetryDelay": 0
        }
    }
}
```

**Comment by cpcbell** [comment]
I believe this is the same/similar issue I am hitting in JS browser SDK ( aws-sdk@2.885.0 ) when a 404 is returned from S3 API:

Uncaught (in promise) NotFound: null.  s3.js?5101:698 

resp.error = AWS.util.error(new Error(), {
        code: codes[code],
        message: null,
        region: region
      });

This means I can't use headObject to test if an object exists. I tried wrapping it all in a try/catch but it crashes leading me to think it is a "syntax error"

Thank you!

**Comment by shadow-light** [comment]
I can confirm that in some situations the `name` property of the error is not set.

If the result of a `headBucket` request is a `301` or a `403` then `name` is `""`. But if the result is a `404` then `name` is `NotFound`.

Also I couldn't find any documentation for the changes to error handling from `v2` to `v3`...

**Comment by MickL** [comment]
I am on v3 and I also dont get "name", "code" or "message" in the error object when doing `HeadBucketCommand`:

```
INFO	
    at deserializeAws_restXmlHeadObjectCommandError (/var/task/node_modules/@aws-sdk/client-s3/dist/cjs/protocols/Aws_restXml.js:6793:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /var/task/node_modules/@aws-sdk/middleware-serde/dist/cjs/deserializerMiddleware.js:6:20
    at async /var/task/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:12:24
    at async StandardRetryStrategy.retry (/var/task/node_modules/@aws-sdk/middleware-retry/dist/cjs/StandardRetryStrategy.js:51:46)
    at async /var/task/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22
    at async FileService.exists (/var/task/index.js:1025:13)
    at async FileService.save (/var/task/dist/index.js:1063:13)
    at async FileController.upload (/var/task/index.js:1257:21) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 403,
    requestId: undefined,
    extendedRequestId: '.....',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}
```

**Comment by leematos** [comment]
I can confirm that this behavior is still present as of latest aws-sdk-js-v3 release (3.26.0)

https://github.com/aws/aws-sdk-js-v3/issues/1596#issuecomment-864910455 -- If you get a 301/400/403 your error XML will not be parsed, BUT if you use a pre-signed URL and make the same type of request, you can actually get the XML text and I can manually parse it with fast-xml-parser.

@trivikr -- Any idea where this falls in your triaging efforts? I'm resorting to sometimes using the SDK commands directly and other times generating presigned URLs and fetching myself depending on a guess as to how often I might get these errors...

**Comment by michaelfarrell76** [comment]
any timeline on whe this will be fixed???
