### ISSUE TITLE
How do I to share the same configuration across multiple clients?

### ISSUE THREAD

**Issue by gatsbyz** [aws/aws-sdk-js-v3#160]
I know that the global config is gone. Would it be through a configuration file?

**Comment by srchase** [comment]
@gatsbyz 

Thanks for opening this issue.

Can you give additional details on what you are trying to achieve?

**Comment by chrisradek** [comment]
@gatsbyz 
You should be able to store the configuration you would pass into a client in some variable, then pass that to multiple clients when you instantiate them. How you manage the configuration you've created will depend on your application/needs.

**Comment by gatsbyz** [comment]
@chrisradek Thanks so much! I guess my question was is it stored in a config file? Or.. literally in a variable.

**Comment by chrisradek** [comment]
@gatsbyz 
The SDK will now read from the shared configuration file (`~/.aws/config`) by default, where it can pull the region and configuration for assuming a role. Any client will be able to read those configuration settings by default (which you can override in the configuration object), but most of the configuration will be in memory.
