### ISSUE TITLE
STS functions (e.g. AssumeRoleWithWebIdentity) incorrectly require credentials

### ISSUE THREAD

**Issue by duarten** [aws/aws-sdk-js-v3#1602]
**Describe the bug**

[AssumeRoleWithWebIdentity](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithWebIdentity.html) doesn't require credentials, but not providing them when creating an STS object throws a "Credential not found" error.

**SDK version number**
1.0.0-rc.1

**Is the issue in the browser/Node.js/ReactNative?**

Browser

**Details of the browser/Node.js/ReactNative version**

Browsers:
    Brave Browser: 86.1.15.72
    Chrome: 86.0.4240.111
    Firefox: 76.0.1
    Safari: 14.0

**To Reproduce (observed behavior)**

Construct an STS object:

```ts
new STS({ region })
```

**Expected behavior**

No error should be thrown.

**Comment by mungojam** [comment]
is there any workaround in the meantime for this?

**Comment by duarten** [comment]
@mungojam There is, you can write it like this:

```ts
const client = new STS({
    region,
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    credentials: () => Promise.resolve({} as any),
})
```

**Comment by trivikr** [comment]
Reason for the issue: The customizations for disabling authentication for assumeRoleWithSAML/assumeRoleWithWebIdentity operations is missing in v3.

Equivalent code in v2: https://github.com/aws/aws-sdk-js/blob/534033a2edb638252d0030f27b9d6297283aa507/lib/services/sts.js#L43-L49

The authentication trait is updated by the service, but its release is being followed up internally.
In the meantime, a customization for assumeRoleWithSAML/assumeRoleWithWebIdentity operations needs to be added in v3 similar to how it was done for Cognito in https://github.com/aws/aws-sdk-js-v3/pull/853
