### ISSUE TITLE
Strategy for lambda deployments

### ISSUE THREAD

**Issue by rcoundon** [aws/aws-sdk-js-v3#1609]
**Describe the issue with documentation**

At present, the aws-sdk is automatically made available to lambdas without the need to bundle it. Is it possible to document the strategy about how/if AWS will migrate to automatically including this library instead? 

This will help developers with migration and could also encourage people to make a start using this library in early stage real projects to reduce friction later.

**Comment by jb4e** [comment]
+1 As it currently stands, using v3 on lambda results in a substantially larger bundle size since it can't be omitted. Can you confirm this will be supported in the near future now that v3 is GA?

**Comment by rcoundon** [comment]
This is still an 'issue' as we still don't know AWS's plan for including this in the lambda runtime

**Comment by RanVaknin** [comment]
Hi @rcoundon JS SDK v3 is now available on lambdaNode.js 18. : [official announcement](https://aws.amazon.com/blogs/compute/node-js-18-x-runtime-now-available-in-aws-lambda/)
