### ISSUE TITLE
Scheduled Release Date and Choice of Version to use

### ISSUE THREAD

**Issue by Ferido07** [aws/aws-sdk-js-v3#1620]
**Issue with documentation**
I have been trying to find the scheduled release date for this package but I couldn't find any. I'm about to start a new project and the features and improvements of this new version are valuable. Especially the typescript support and modularized package. In only use one service and hence I don't want to download an entire 58 MB of the previous version SDK. 

So please provide the release date so that if the release date is close I may use the new version. Alternatively I could use the new version without it being released but I don't seem to find how to easily install it as the package is not published on npm. So please provide some guidance regarding these issues.

**Comment by trivikr** [comment]
The AWS SDK for JavaScript (v3) was made [generally available](https://aws.amazon.com/blogs/developer/modular-aws-sdk-for-javascript-is-now-generally-available/) on December 15, 2020.

You can use versions `3.x.x`
