### ISSUE TITLE
ListBucketsCommand: Request with GET/HEAD method cannot have body

### ISSUE THREAD

**Issue by jzillmann** [aws/aws-sdk-js-v3#1633]
**Describe the bug**
Inside a browser app (inside an electron app as well), i tried:

```js
import { S3Client, ListBucketsCommand } from "@aws-sdk/client-s3";
const client = new S3Client({
  region: "eu-central-1",
  credentials: {
    accessKeyId: "xxx",
    secretAccessKey: "***",
  },
});
const result = client
  .send(new ListBucketsCommand({}))
  .catch((e) => console.log(e));

```

The error i'm getting is as follow:
```console
TypeError: Failed to construct 'Request': Request with GET/HEAD method cannot have body.
at FetchHttpHandler.handle (fetch-http-handler.js:41)
at ListBucketsCommand.js:29
at deserializerMiddleware.js:8
at step (tslib.es6.js:100)
at Object.next (tslib.es6.js:81)
at tslib.es6.js:74
at new Promise (<anonymous>)
at __awaiter$j (tslib.es6.js:70)
at deserializerMiddleware.js:2
at middleware.js:36
```

When debugging `fetch-http-handler.js:41` i can see the requestOptions object has `body: ""` set. 
Changing `""` to `undefined` solves the problem.

**SDK version number**
`@aws-sdk/client-s3 1.0.0-rc.2`

**Is the issue in the browser/Node.js/ReactNative?**
Browser/Node.js (Electron)

**Details of the browser/Node.js/ReactNative version**
- Chrome: 86.0.4240.111
- Electron: 10.1.5

**To Reproduce (observed behavior)**
not yet

**Expected behavior**
Executing commands like `ListBucketsCommand` should set the body.

**Screenshots**
not yet

**Additional context**
nothing

**Comment by AllanZhengYP** [comment]
Hi @jzillmann, 

I've post a PR removing empty string body fromt he GET/HEAD request. For your information, `listBuckets` won't work in browser even this fix. Because S3 doesn't support CORS for all bucket level operations(e.g. `listBuckets`). It may work in Electron.
