### ISSUE TITLE
DynamoDB - Pagination with Eager Loading

### ISSUE THREAD

**Issue by RossWilliams** [aws/aws-sdk-js-v3#1634]
**Is your feature request related to a problem? Please describe.**
I'd like to utilise my Lambdas efficiently and have network requests active while processing data. I don't want my Lambda to sit idle while fetching the next page of data to work from. 

I currently have a custom wrapper around the DynamoDB client to support pagination and eager loading. I'd like to retire my custom code and use the built-in pagination, but without eager loading my lambda performance will decrease.

Or, I'd like to see documentation for how to implement custom pagination with the new middleware.

**Describe the solution you'd like**

It would be nice if the pagination iterator fetched the next few pages of data (configurable) while working on the current set of data.

I'd also like pagination iterators to support map, reduce, and forEach operations. Having these methods defined will help with eager loading as it gives the library the control flow it might need to pause iteration and fetch the next page of results. To add one more layer of complexity, the iterator methods could handle and manage promises returned from the iterator lambda.

as an example, and how it can make code more readable:

```typescript
// user `bobby` needs all items updated to support the new gsi
exports.handler = async =>
   // second API call made before forEach starts processing
   // forEach itself returns a promise
  await dynamoClient.queryWithPaginator({
    TableName: 'x',
    IndexName: 'gsi1',
    KeyConditionExpression: 'pk = bobby'
  })
    /*  forEach yields buffered results, pauses on every (pageSize / 4) iteration
        to check the buffer size against its  capacity (bufferCapacity := pageSize * eagerness) 
        and decide to make another API request
    */
    .forEach((item, _index, client) =>
      // forEach manages the returned promises so that back-pressure and retries from the SDK continue to work
      client.update({
        TableName: 'x',
        Key: {pk: item.pk, sk: item.sk},
        UpdateExpression: `SET gsi2pk = ${item.data.val}`
    })
    .catch(failedUpdates => 
      failedUpdates.map(f =>
        console.error(`update failed, ${f.Request.Key.pk} ; ${f.Request.Key.sk}`, f)
      )
    )
  );
    
```

**Describe alternatives you've considered**
I have not found good documentation on how pagination works throughout the SDK and if there is a more general solution to this. It appears only ListTables currently supports pagination in Dynamo, and doesn't use middleware. 

The current code uses a simple yielding of a full page of data after it is fetched. A first start for eager loading would be to start fetching the next page of data before yielding the current page and manage a single extra page as a buffer.

**Additional context**

**Comment by zoellner** [comment]
Maybe you can integrate https://awslabs.github.io/dynamodb-data-mapper-js/packages/dynamodb-query-iterator/ into the sdk. With the tree shaking approach it won't bloat the code for those who don't need it.

**Comment by vivmaha** [comment]
@zoellner The linked docs don't mention any thinking looking like the eager loading that @RossWilliams is requesting. Do they actually perform eager loading?

**Comment by vivmaha** [comment]
I agree that having this built into the sdk would be nice. 

In case you're willing to roll your own, the following works for me.

Here's a function that converts any generator function into an eager generator function.

````
async function* eagerGenerator<T>(
  normalGenerator: AsyncGenerator<T>
): AsyncGenerator<T> {
  const preFetches: Promise<IteratorResult<T>>[] = [];

  const preFetch = (): void => {
    const next = normalGenerator.next();
    preFetches.push(
      (async () => {
        log("eagerGenerator prefetch");
        const nextResult = await next;
        if (!nextResult.done) {
          preFetch();
        }
        return nextResult;
      })()
    );
  };
  preFetch();

  while (preFetches.length > 0) {
    // eslint-disable-next-line no-await-in-loop
    const next = await preFetches.splice(0, 1)[0];
    if (!next.done) {
      yield next.value;
    }
  }
}
````

Note that this will eagerly fetch the entire underlying generator. In some cases you may need to limit this (eg. Only pre-fetch 10 values).

Here's a sample generator function for one of the DynamoDB calls (listObjects)

````
async function* listObjects(
  bucket: string,
  prefix: string
): AsyncGenerator<ListObjectsV2CommandOutput> {
  let continuationToken: string | undefined;
  do {
    // This is a paging API so we have to await inside it
    // eslint-disable-next-line no-await-in-loop
    const list = await createS3Client().send(
      new ListObjectsV2Command({
        Bucket: bucket,
        Delimiter: "/",
        Prefix: prefix,
        ContinuationToken: continuationToken,
      })
    );
    yield list;
    continuationToken = list.NextContinuationToken;
  } while (continuationToken !== undefined);
}
````

You combine both of the above to get an eager version of the DynamoDB call:

````
const eagerListObjects = (
  bucket: string,
  prefix: string
): AsyncGenerator<ListObjectsV2CommandOutput> =>
  eagerGenerator(listObjects(bucket, prefix));
````

And finally you can consume the API knowing that on you next iteration the data would most likely already be fetched:

````
    for await (const list of eagerListObjects(bucket, prefix)) {
      // your code
    }
````

**Comment by RossWilliams** [comment]
Thanks for the tip about query iterator, didn’t know about it.
