### ISSUE TITLE
DynamoDB: Buffer value not always accepted for binary (B) attributes

### ISSUE THREAD

**Issue by Manc** [aws/aws-sdk-js-v3#164]
A DynamoDB field attribute of type `B` (binary) is defined in `_AttributeValue` like this: `B?: ArrayBuffer | ArrayBufferView | string;`

Using `putItem` I can easily write a field attribute with a `Buffer` value, which is presumably later automatically converted to a Base64 representation for transmission over the network, but it looks like this is not always possible.

I tried applying a `Buffer` value to `ExpressionAttributeValues` in an `UpdateItemInput` object, but only Base64 encoded `string` works here. This doesn't throw an exception directly, but the condition will not be met, i.e. the resulting error is: `ConditionalCheckFailedException: The conditional request failed`.

Example:
```ts
const code = Buffer.from('aabbccddeeff', 'hex');

const args: UpdateItemInput = {
	TableName: 'myTableName',
	Key: {
		email: { S: 'xxx@xxx' },
	},
	ExpressionAttributeNames: {
		'#f': 'TestField',
	},
	ExpressionAttributeValues: {
		// ':c': { B: code }, // This should work, but doesn't
		// ':c': { B: code.buffer }, // This should work, but doesn't
		':c': { B: code.toString('base64') }, // Only Base64 representation works
	},
	ConditionExpression: '#f = :c',
	UpdateExpression: 'REMOVE #f',
};

client.updateItem(args);

```

Used SDK version: 0.1.0-preview.1

**Comment by AllanFly120** [comment]
Hey @Manc 

Thank you for reporting this. I did a test with the fix #169 and it works.
