### ISSUE TITLE
Export com.amazonaws.dynamodb#AttributeMap as separate type for DynamoDB Client

### ISSUE THREAD

**Issue by mwgamble** [aws/aws-sdk-js-v3#1644]
**Is your feature request related to a problem? Please describe.**

In my typescript code, if I want to type an individual item from a Scan command response (for example), I need to do this:

```
type Item = NonNullable<ScanCommandOutput["Items"]>[0];
```

This applies to any command that responds with an item or a list of items. It is essentially equivalent to `{ [key: string]: AttributeValue }`. Both options feel unnecessarily verbose and a bit brittle though.

**Describe the solution you'd like**

Having examined the codegen model file, I found that there is a separate type for "AttributeMap", which is essentially what `{ [key: string]: AttributeValue }` is. Ideally, instead of repeating this multiple times throughout the DynamoDB type definitions, this would just be stored in a standalone `AttributeMap` type that is also exported.

**Describe alternatives you've considered**

Right now I'm using the custom type definition above to ensure accuracy. It works, but it is unwieldy.

**Additional context**

The `AttributeMap` type could then be used in the type declarations for the `marshall()` and `unmarshall()` functions in the `util-dynamodb` package.

**Comment by AllanZhengYP** [comment]
Hi @mwgamble 

Thank you for the feature request. It's not a high priority for now since it's not blocking the SDK usage and you already have a workaround. I will keep it open and keep you posted.

**Comment by mwgamble** [comment]
:disappointed: This isn't stale, it's still an issue!

**Comment by mwgamble** [comment]
There was literally no warning that this was about to be closed for being stale.
