### ISSUE TITLE
@aws-sdk/types is a production dependency, but is full of empty JS files

### ISSUE THREAD

**Issue by mhart** [aws/aws-sdk-js-v3#1649]
**Describe the bug**

`@aws-sdk/types` is a production dependency of many modules in this project, but it is only made up of empty *.js files and has no use at runtime.

I believe it's only intended to provide type information – so a) there should be no *.js files and b) it should be in `devDependencies` instead of `dependencies`

This is something that should be fixed before GA so that ppl don't somehow rely on it being available without them installing it as a dev dep themselves (and also to save 500kb of production deps)

**Comment by alexforsyth** [comment]
@mhart Thanks for opening this. We're taking a look and we'll fix this soon

**Comment by mhart** [comment]
Glad to hear it, thanks @alexforsyth!

**Comment by alexforsyth** [comment]
This will be going out with the next release
