### ISSUE TITLE
Error TS2742 with the new client ec2 1.0.0-rc.3 on ClientSharedValues object

### ISSUE THREAD

**Issue by Dataxelio** [aws/aws-sdk-js-v3#1650]
**Describe the bug**
When transpiling, getting the below error TS2742

> node_modules/@aws-sdk/client-ec2/runtimeConfig.shared.ts:4:14 - error TS2742: The inferred type of 'ClientSharedValues' cannot be named without a reference to '@aws-sdk/client-ec2/node_modules/@aws-sdk/types'. This is likely not portable. A type annotation is necessary.

Below the content of runtimeConfig.shared.ts with the object ClientSharedValues causing the issue:
```typescript
export const ClientSharedValues = {
  apiVersion: "2016-11-15",
  disableHostPrefix: false,
  logger: {} as __Logger,
  regionInfoProvider: defaultRegionInfoProvider,
  signingName: "ec2",
};
```

**SDK version number**
1.0.0-rc.3

**Is the issue in the browser/Node.js/ReactNative?**
Node.js

**Details of the browser/Node.js/ReactNative version**
v12.16.2

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by alexforsyth** [comment]
Hey @dataxelio can you provide on information on the error you're getting? Here's some working code that's stubbed out all the type requirements without taking a direct dependency on @aws-sdk/types. Although it should still be find to take a dependency on that package.

```
import { EC2 } from "@aws-sdk/client-ec2";

(async () => {
    const client = new EC2({
        apiVersion: "2016-11-15",
        disableHostPrefix: false,
        logger: {
            debug: () => {},
            info: () => {},
            warn: () => {},
            error: () => {}
        },
        signingName: "ec2",
        regionInfoProvider: async (region: string ) => { return {
            region: "us-east-1",
            hostname: "some-host",
            partition: "some-partition"
        }}
    });

    console.log(client);
})();
```
