### ISSUE TITLE
Roadmap / timeline to production release

### ISSUE THREAD

**Issue by HaleTom** [aws/aws-sdk-js-v3#1659]
**Describe the issue with documentation**
I couldn't see a timeline as to planned release candidates, maturity/features and target release dates.

**Additional context**
I'm trying to select between SDK versions.  All I can see is that this SDK was announced in November 2018, but I've not seen a roadmap / timeline for other release candidates or final release.

**Comment by HaleTom** [comment]
Apologies if I missed this information in some documentation directory.

It would be very helpful to have it in the `README.md`.

**Comment by TysonAndre** [comment]
Can this be closed? it became generally available in December 2020 according to https://aws.amazon.com/blogs/developer/tag/aws-sdk-js-v3/
