### ISSUE TITLE
Paginator sends `...args` in command instead of send operation

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#1665]
**Describe the bug**
Paginator sends `...args` in command instead of send operation.

For example, in listTablesPaginator https://github.com/aws/aws-sdk-js-v3/blob/07ac6be17ddbd52f638f8ed4b92b093bf7c378d1/clients/client-dynamodb/pagination/ListTablesPaginator.ts#L13

The ListCommand constructor accepts only one parameter: https://github.com/aws/aws-sdk-js-v3/blob/07ac6be17ddbd52f638f8ed4b92b093bf7c378d1/clients/client-dynamodb/commands/ListTablesCommand.ts#L31-L35

The options object should be passed as second parameter of send operation, and not Command constructor: https://github.com/aws/aws-sdk-js-v3/blob/07ac6be17ddbd52f638f8ed4b92b093bf7c378d1/packages/smithy-client/src/client.ts#L22-L25

**SDK version number**
master

**Is the issue in the browser/Node.js/ReactNative?**
N/A

**Details of the browser/Node.js/ReactNative version**
N/A

**To Reproduce (observed behavior)**
Visit code https://github.com/aws/aws-sdk-js-v3/blob/07ac6be17ddbd52f638f8ed4b92b093bf7c378d1/clients/client-dynamodb/pagination/ListTablesPaginator.ts#L13

**Expected behavior**
The options object should be passed as second parameter of send operation, and not Command constructor.

**Comment by alexforsyth** [comment]
Taking a look here

**Comment by alexforsyth** [comment]
Yep, you're right. This should read 
```
return await client.send(new ListFunctionsCommand(input), ...args);
```

let me open a few PRs real quick

**Comment by alexforsyth** [comment]
Issues merged. Moving to done and closing
