### ISSUE TITLE
Support DynamoDB encreption client

### ISSUE THREAD

**Issue by AllanZhengYP** [aws/aws-sdk-js-v3#1671]
**Is your feature request related to a problem? Please describe.**
Port the [DynamoDB encryption client in Java and Python](https://docs.aws.amazon.com/dynamodb-encryption-client/latest/devguide/what-is-ddb-encrypt.html) into the v3 SDK.

**Additional context**
Feature request in v2: 
* https://github.com/aws/aws-sdk-js/issues/1164
* https://github.com/aws/aws-sdk-js/issues/2179

**Comment by trivikr** [comment]
The AWS SDK for JavaScript v3 uses HTTPS by default for all connections, so connection is encrypted.
What's the benefit of adding encryption client?
