### ISSUE TITLE
Support for DocumentClient

### ISSUE THREAD

**Issue by ghost** [aws/aws-sdk-js-v3#1677]
Will there be support for a DocumentClient like in v2?

At the moment no (future) support is documented here in the developer-guide:
https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/dynamodb-example-table-read-write.html

**Update:**
I guess the `marshall` and `unmarshall` functions in `@aws-sdk/util-dynamodb` are the corresponding replacements?

**Comment by jpbochi** [comment]
FWIW, there a `DynamoDBDocumentClient` in v3. See https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/classes/_aws_sdk_lib_dynamodb.dynamodbdocumentclient-1.html and https://github.com/aws/aws-sdk-js-v3/blob/main/lib/lib-dynamodb/src/DynamoDBDocumentClient.ts

I'm not sure if it's a proper replacement, though. That one only has a super generic `send` method.

**Comment by trivikr** [comment]
Yup, the support for DocumentClient was added in https://github.com/aws/aws-sdk-js-v3/pull/2097, and was released with `v3.8.0`

It's a better replacement as compared to v2, as it:
* It contains types for input/output.
* It supports BigInt.
* It is code generated. So it will support the latest operations from DynamoDB.

> That one only has a super generic `send` method.

The DocumentClient contains both bare-bones client which supports only `.send` as well as aggregated client which supports `.operationName` as documented under [Usage](https://www.npmjs.com/package/@aws-sdk/lib-dynamodb#user-content-usage)
