### ISSUE TITLE
[client-iot] (InvalidSignatureException) signs with wrong service name

### ISSUE THREAD

**Issue by simonbuchan** [aws/aws-sdk-js-v3#1704]
**Describe the bug**
Using `@aws-sdk/client-iot@1.0.0-rc.6` I get `InvalidSignatureException: Credential should be scoped to correct service: 'execute-api'.`, when it worked with at least `1.0.0-gamma.6`. If I add `signingName: "execute-api"` to the client configuration then it works.

Not sure why it would make any difference looking at the code, since `endpoints.ts` has had `signingService: "execute-api"` in all the entries since it was added 10 months ago, and the client code that pulls it out hasn't changed since then either? I'm using the `us-west-2` region if it matters.

**SDK version number**
1.0.0-rc.6

**Is the issue in the browser/Node.js/ReactNative?**
Only really tested in Node implementation running in an electron renderer process (by bundling with webpack with `resolve.aliasFields = ["module", "main"]`, which removes the default `"browser"`), and reproduced in node.

**Details of the browser/Node.js/ReactNative version**
```
yarn electron --version
yarn run v1.22.10
$ /Users/simon/code/admin-tool/node_modules/.bin/electron --version
v8.4.0
✨  Done in 0.69s.
```

According to [`electron/releases`](https://github.com/electron/releases/blob/75101bfc3c9c057978a48a917a3491d2824e5a74/lite.json#L5054-L5073) this is equivalent to node 12.13.0. (yes, it's very out of date)

Reproduced in node 15.2.1

**To Reproduce (observed behavior)**
```
% node
> const Iot = require("@aws-sdk/client-iot")
> const iot = new Iot.IoTClient(); // fix: new Iot.IoTClient({ signingName: "execute-api" });
> iot.send(new Iot.ListThingGroupsCommand({})).then(console.log, console.error);
InvalidSignatureException: Credential should be scoped to correct service: 'execute-api'. 
    at deserializeAws_restJson1ListThingGroupsCommandError (/Users/simon/code/admin-tool/node_modules/@aws-sdk/client-iot/dist/cjs/protocols/Aws_restJson1.js:19072:41)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async /Users/simon/code/admin-tool/node_modules/@aws-sdk/middleware-serde/dist/cjs/deserializerMiddleware.js:7:20
    at async /Users/simon/code/admin-tool/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:12:24
    at async StandardRetryStrategy.retry (/Users/simon/code/admin-tool/node_modules/@aws-sdk/middleware-retry/dist/cjs/defaultStrategy.js:55:46)
    at async /Users/simon/code/admin-tool/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:7:22 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 403,
    httpHeaders: {
      date: 'Thu, 19 Nov 2020 23:50:02 GMT',
      'content-type': 'application/json',
      'content-length': '77',
      connection: 'keep-alive',
      'x-amzn-requestid': '2c637bd0-1d8e-4ce5-994b-8db8e3ace40c',
      'x-amzn-errortype': 'InvalidSignatureException',
      'x-amz-apigw-id': 'WR2quE1SSwMFqIw='
    },
    requestId: '2c637bd0-1d8e-4ce5-994b-8db8e3ace40c',
    attempts: 3,
    totalRetryDelay: 506
  }
}

```

**Expected behavior**
Doesn't throw this error 😉

**Comment by AllanZhengYP** [comment]
Hi @simonbuchan 

I have confirmed that this is bug. The signingName from `endpoints.json` was incorrectly overwritten by [the default signingName](https://github.com/aws/aws-sdk-js-v3/blob/318ca36649b4134f95dcb66e801bb971c99bdc53/clients%2Fclient-iot%2FruntimeConfig.shared.ts#L12). I will put up a fix for it shortly.
