### ISSUE TITLE
More async iterator pagination support

### ISSUE THREAD

**Issue by farski** [aws/aws-sdk-js-v3#1712]
**Is your feature request related to a problem? Please describe.**
Based on this recent [blog post](https://aws.amazon.com/blogs/developer/pagination-using-async-iterators-in-modular-aws-sdk-for-javascript/), it sounded like pagination using async iterators was going to be available for all, or at least most, paginated operations in the SDK. Having spent a little bit of time with the DDB module, the two most common operations that would require pagination (`scan` and `query`) don't seem to offer native async iterator commands.

**Describe the solution you'd like**
It would be ideal if all operations that can produce paginated results supported async iterators.

**Comment by trivikr** [comment]
Hi @farski, thank you for creating the issue.

The APIs which receive pagination is decided by the Service team. In smithy interface definition language, it is defined by [paginated trait](https://awslabs.github.io/smithy/spec/core.html#paginated-trait).

The paginated trait is missing for `scan` and `query` commands in smithy models:
* Scan https://github.com/aws/aws-sdk-js-v3/blob/56c363955b5d278446d86736ebb4b2589fb8d261/codegen/sdk-codegen/aws-models/dynamodb.2012-08-10.json#L7043-L7071
* Query https://github.com/aws/aws-sdk-js-v3/blob/56c363955b5d278446d86736ebb4b2589fb8d261/codegen/sdk-codegen/aws-models/dynamodb.2012-08-10.json#L5766-L5794

The pagination is present in JS SDK v2 for DynamoDB scan and query commands https://github.com/aws/aws-sdk-js/blob/ffcad209c2b2459bb819a27a18bb7b9e83f7e276/apis/dynamodb-2012-08-10.paginators.json#L23-L34

We're tracking this issue internally to populate required pagination trait.
