### ISSUE TITLE
@aws-sdk/client-api-gateway: CreateApiKeyRequest.name disappeared in rc.4

### ISSUE THREAD

**Issue by mfogel** [aws/aws-sdk-js-v3#1714]
In fdd0ddf6e6400cf72dda521ddedc144436a6043c the optional field `name` was removed from the `CreateApiKeyRequest` interface for the api-gateway client (looking at `clients/client-api-gateway/models/models_0.ts`). I'm guessing this was unintentional, but if I'm missing something, please let me know.

Thanks for your work on this rebuild of the sdk, much appreciated!

**Comment by AllanZhengYP** [comment]
I can confirm the field is not removed by the service model, but it was removed in rc.7 release

**Comment by trivikr** [comment]
This is caused by `CreateApiKeyRequest.name` being removed from model using which client is built.
The issue is being internally tracked in SMITHY-198.

**Comment by trivikr** [comment]
The model for reference: https://github.com/aws/aws-sdk-js-v3/blob/56c363955b5d278446d86736ebb4b2589fb8d261/codegen/sdk-codegen/aws-models/api-gateway.2015-07-09.json#L1055-L1104
