### ISSUE TITLE
How to build packages for contributing?

### ISSUE THREAD

**Issue by zcei** [aws/aws-sdk-js-v3#172]
Hej folks,

I've seen https://github.com/aws/aws-sdk-js-v3/issues/153 while wondering about missing packages and found the answer explaining how to generate a package based on the provided models. 

So what I did was

```shell
$ npm install
$ npm run bootstrap
$ node ./packages/package-generator/build/cli.js client --m ../../models/s3/2006-03-01/service-2.json --r node --s ../../models/s3/2006-03-01/smoke.json
```

This command fails with

> Cannot find module '/Users/stephan/dev/github/aws-sdk-js-v3/packages/package-generator/build/cli.js'

as the `build` folder does not exist.

The package does not seem to have a specific build script and builds in `prepublishOnly`. 
I checked and `prepublish` lifecycle hook is called during `lerna bootstrap`:

```
npm run bootstrap

> aws-sdk-js-v3@0.0.1 bootstrap /Users/stephan/dev/github/aws-sdk-js-v3
> lerna bootstrap

lerna info version 2.11.0
lerna info versioning independent
lerna info Bootstrapping 117 packages
lerna info lifecycle preinstall
lerna WARN EHOIST_PKG_VERSION "@aws-sdk/credential-provider-cognito-identity" package depends on jest@^21, which differs from the hoisted jest@^20.0.4.
lerna info Installing external dependencies
lerna info hoist Installing hoisted dependencies into root
lerna info hoist Pruning hoisted dependencies
lerna info hoist Finished pruning hoisted dependencies
lerna info hoist Finished installing in root
lerna info Symlinking packages and binaries
lerna info lifecycle postinstall
lerna info lifecycle prepublish
lerna info lifecycle prepare
lerna success Bootstrapped 117 packages
```

Then I thought I'll just run `tsc` manually for this package:

```shell
$ lerna exec --scope @aws-sdk/package-generator -- tsc
```

This fails as the TypeScript compiler does not find `@aws-sdk/build-types` and others. So the symlinking step might not have been successful as well.

How do you all usually work with this repository? Am I missing something? (My monorepo experience is quite limited)

Looking forward to play around with the new shiny SDK!

**Comment by zcei** [comment]
No I did not, and I only now realized it has a `tsc` call on `pretest` lifecycle hook.

Is there a reason why this is the case? I wouldn't have expected to first run a ~3 minutes coverage run (on my machine) before being able to use it.

So it should be either mentioned in the [related `CONTRIBUTING.md`](https://github.com/aws/aws-sdk-js-v3/blob/master/CONTRIBUTING.md#generate-service-clients) section,
a) that an `npm test` is needed prior to executing the command mentioned there.
b) that there is a released version of this package you can install via `npm install @aws-sdk/package-generator` to then bootstrap the service clients (though it seems weird to install the "external" (released) version when you have the code in the repo either way.

Anyway, thanks for pointing me in the right direction!

**Comment by srchase** [comment]
@zcei 

Thanks for the feedback.  I've opened a PR to add a note for (a).

We'd be happy to take a PR if there is further clarification you'd like to add.

**Comment by srchase** [comment]
@zcei 

This change has been merged.

Closing this issue for now.  We're happy to re-open if you have additional concerns.
