### ISSUE TITLE
@aws-sdk/lib-storage: multipart copy

### ISSUE THREAD

**Issue by ljwagerfield** [aws/aws-sdk-js-v3#1720]
**Is your feature request related to a problem? Please describe.**

I'm trying to copy arbitrary-sized objects between buckets.

The objects could be between 0KB and 5TB in size.

**Describe the solution you'd like**

I would like the new `Upload` class in `@aws-sdk/lib-storage` to support [copy operations](https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPartCopy.html).

**Describe alternatives you've considered**

AFAIK the only alternatives with v3 are:

1. To manually write a lot of code to detect if the file is `< 5GB` and use `s3.copyObject` if so, or enter into a mutlipart copy operation if not, using `s3.uploadPartCopy` plus all of the other orchestration around it... which is a lot, when you consider error handling, etc.

2. To use the new `Upload` class, but with `s3.getObject().createReadStream()` as a `Body`. This would obviously involve all data having to go through my service, so will perform poorly.

**Comment by alexforsyth** [comment]
This is a great feature request. We'd be happy to consider a PR that addresses this. Otherwise if this issue get significant traction we'll look at prioritizing this.
