### ISSUE TITLE
Support for cloudformation package and deploy

### ISSUE THREAD

**Issue by nishant-dani** [aws/aws-sdk-js-v3#1721]
**Is your feature request related to a problem? Please describe.**
I am using javascript sdk for all my current deployments.  I would like to use it similarly for lambda deployments as well but I notice that support for aws cloudformation package CLI and aws cloudformation deploy CLI are missing from the javascript functions supported.

**Describe the solution you'd like**
Would be great the have these supported so that I don't have to mix in CLI with my deployment and can rely entirely on the Javascript SDK.

**Describe alternatives you've considered**
The alternative is use CLI for SAM or for CloudFormation to access the missing features.

**Additional context**

**Comment by AllanZhengYP** [comment]
Hi @nishant-dani 

Can you share the tool you are using? I'm not very familiar with the CLI you are referring to.

**Comment by nishant-dani** [comment]
@AllanZhengYP - 

I meant the AWS command line interface (CLI or cli)

The AWS CloudFormation Javascript API is at https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudFormation.html

The CLI for aws has the following functions package and deploy https://docs.aws.amazon.com/cli/latest/reference/cloudformation/package.html
https://docs.aws.amazon.com/cli/latest/reference/cloudformation/deploy/index.html

But I don't see support for those in the javascript API for cloudformation.  Ideally the javascript API should be complete in itself for all that is there in the CLI.

**Comment by AllanZhengYP** [comment]
Hey @nishant-dani 

This will be a helpful add-on the the SDK. We will keep this open. Currently this is not prioritized. But if we see more insterest in the feature, we can take it up. Thank you for bringing this up!
