### ISSUE TITLE
Browser doesn't support S3Client with custom credentials

### ISSUE THREAD

**Issue by tampler** [aws/aws-sdk-js-v3#1737]
**Describe the bug**
`Chromium` browser fails to create the `S3Client` from code below, yielding in `Error: Credential is missing`.
The same code works well in `NodeJs v.14.15.1`

```js
const cfg = {
  accessKeyId: process.env.KEY,
  secretAccessKey: process.env.SECRET,
  endpoint: process.env.HOST,
  s3ForcePathStyle: true,
  signatureVersion: "v4",
};

const s3 = new S3Client(cfg);
```
**SDK version number**
@aws-sdk/client-s3": "^1.0.0-rc.7"

**Comment by AllanZhengYP** [comment]
Hi @tampler 

V3's constructor is little different to what you shared. It should be

```javascript
const cfg = {
  credentials: {
    accessKeyId: process.env.KEY,
    secretAccessKey: process.env.SECRET,
  },
  endpoint: process.env.HOST,
  // s3ForcePathStyle is deprecated in v3, every endpoint is now virtual host style
  // signatureVersion is deprecated in v3, signature v4 for all the services
};

const s3 = new S3Client(cfg);
```

You can find more information in the S3 API reference: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/classes/s3client.html
