### ISSUE TITLE
Specify the minimum Node version

### ISSUE THREAD

**Issue by Mctalian** [aws/aws-sdk-js-v3#1744]
**Describe the issue with documentation**
Sub-libraries (e.g. client-s3) fail silently downstream (e.g. presigned URLs) if you are using an old version of Node (e.g. v10.17.0)

Please upgrade the documentation to call out whatever the minimum required version is (presigned URLs work as expected on Node v12.11.1)

Consider adding engine requirements to the package.json so when people attempt to install with an older version of node, it fails outright.

**To Reproduce (observed behavior)**
1. Install Node v10.17.0
1. Replicate the s3 presigned URL example
1. Note that the presigned URL output does not include `host` in the query string `X-Amz-SignedHeaders` of the resulting presigned URL.

**Expected behavior**
I expect requirements to be specified, or something needs to change in the library to support this version if it is expected.

**Screenshots**
Response of a presigned URL generated using Node V10.17.0:
`403 Forbidden`
Payload:
![image](https://user-images.githubusercontent.com/5081281/101201426-f873e700-3624-11eb-9b94-fda05ac6ac29.png)

Response of a presigned URL generated using Node V12.11.1:
`200 OK`

**Additional context**
If this documentation exists, let me know. Perhaps I overlooked it. I spent a good chunk of hours trying to troubleshoot the s3 presigned URL examples and it ended up being related to engine version.

**Comment by trivikr** [comment]
@Mctalian Please provide the presigned URL code which you used for reproduction.
Also, is this issue reproducible with `v3.1.0`?

**Comment by Mctalian** [comment]
I'll provide an example as soon as I can.

**Comment by Mctalian** [comment]
Apologies for the delay!

I followed something similar to the last example on this page: https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/s3-example-creating-buckets.html#s3-create-presigendurl

It does appear that the examples have changed since I followed them.

We are creating a presigned URL for a PutObjectCommand on a bucket.

Here's how we're generating the presigned URLs in our code today:

```
import { PutObjectCommand, S3 } from "@aws-sdk/client-s3";
import { S3RequestPresigner } from "@aws-sdk/s3-request-presigner";
import { createRequest } from "@aws-sdk/util-create-request";
import { formatUrl } from "@aws-sdk/util-format-url";

const someBucketName= "name-of-an-s3-bucket";
const s3Key = "some/path.txt";
const s3Client: S3 = new S3({});
const signer: S3RequestPresigner = new S3RequestPresigner({ ...s3Client.config });

const request = await createRequest(
  s3Client,
  new PutObjectCommand({ Key: s3Key, Bucket: `${someBucketName}` })
);
const url: string = formatUrl(await signer.presign(request, { expiresIn: FIVE_MINUTES_IN_SEC }));
```

When using Node v10.17.0, this code generates a URL, but when someone attempts to use it, they get the "headers not signed" error (similar to the screenshot I provided in the initial post).

Using Node v12.11.1 to generate the URL works as expected. The client is able to upload files using the URL without error.

**Comment by brmur** [comment]
@Mctalian I can confirm this example was updated on 1 Feb 2020 to conform to example [here ](https://github.com/aws/aws-sdk-js-v3/tree/master/packages/s3-request-presigner).

**Comment by Mctalian** [comment]
I will also try conforming to the updated example, but seeing the context for the examples, I still feel there is an undocumented incompatibility with Node v10 (unless of course this was fixed in a later version of the SDK, which I will try to figure out this week).

Thanks for the example @brmur - the code for my use case is certainly cleaner from your example link. I'll work on switching that out and test in both Node v10 and Node v12.

I got my examples from the AWS docs which don't explain the differences like your examples do. I got my examples circa early December 2020. Did you mean the examples were updated on 1 Feb 2021, by chance?

**Comment by ajredniwja** [comment]
Hey @Mctalian, apologies for a delayed response here, using the code mentioned [here](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/s3-example-creating-buckets.html#s3-create-presigendurl) I was not able to reproduce the above issue, I got similar results for both the versions of node. 

Can you please check if it is still an issue?
