### ISSUE TITLE
dynamo scan json unmarshalling error

### ISSUE THREAD

**Issue by chris--young** [aws/aws-sdk-js-v3#175]
seeing this when i try to do a dynamo scan

```
{ TypeError: Cannot read property 'type' of undefined
    at JsonParser.unmarshall (/Users/chrisyoung/Desktop/prod/node_modules/@aws-sdk/json-parser/build/index.js:13:19)
    at /Users/chrisyoung/Desktop/prod/node_modules/@aws-sdk/json-parser/build/index.js:41:37
    at Array.reduce (<anonymous>)
    at JsonParser.unmarshall (/Users/chrisyoung/Desktop/prod/node_modules/@aws-sdk/json-parser/build/index.js:40:18)
    at /Users/chrisyoung/Desktop/prod/node_modules/@aws-sdk/json-parser/build/index.js:22:48
    at Array.reduce (<anonymous>)
    at JsonParser.unmarshall (/Users/chrisyoung/Desktop/prod/node_modules/@aws-sdk/json-parser/build/index.js:18:18)
    at /Users/chrisyoung/Desktop/prod/node_modules/@aws-sdk/json-parser/build/index.js:41:37
    at Array.reduce (<anonymous>)
    at JsonParser.unmarshall (/Users/chrisyoung/Desktop/prod/node_modules/@aws-sdk/json-parser/build/index.js:40:18) '$metadata': { retries: 0, totalRetryDelay: 0 } }
```

this code reproduces the error

```
const { DynamoDB } = require('@aws-sdk/client-dynamodb-v2-node');

(async function main() {

  const db = new DynamoDB({ region: 'us-east-1' });

  try {
    const params = { TableName: 'foo' };
    const res = await db.scan(params);

    console.log(res);
  } catch (err) {
    console.error(err);
  }

})();

```

will try to take a deeper look into whats causing the issue tomorrow

**Comment by chris--young** [comment]
using node 10.10.0 btw

**Comment by srchase** [comment]
@chris--young 

Thanks for opening this issue.  From the stack, it looks like an issue with the parsing of the DynamoDB record.

If possible, could you share an example of your what the records in your table look like?

**Comment by chris--young** [comment]
I can't from the table I actually used to get this, but let me see if I can create a test table with an item that gives the same error.

**Comment by srchase** [comment]
It looks like you are using the DynamoDB client from NPM.  Is that correct?

There was a fix made on that client that has not yet been released.  It would be great if you had a chance to test against the client in this repository to confirm the unreleased change addresses the issue you're seeing.

**Comment by AllanFly120** [comment]
@chris--young  Hey the feature has been released. You can comment here if you still have issue with this.
