### ISSUE TITLE
Request: for Transcribe Javascript something equivalent to Java StartStreamTranscriptionResponseHandler.getResponseHandler().OnComplete

### ISSUE THREAD

**Issue by ted-consolidatedwonder** [aws/aws-sdk-js-v3#1754]
Thanks in advance.  Maybe I don't adequately understand the subtle differences between Java and Javascript ( regarding threading limitations ).
In java, when I use StreamTranscribe(), I establish an 'onComplete()' callback so I know when things are done.
I don't seem to know how to do the related activity in Javascript.

Specifically, in Java API ( see page 66 )
https://docs.aws.amazon.com/transcribe/latest/dg/transcribe-dg.pdf
Code like:
```
 private static StartStreamTranscriptionResponseHandler getResponseHandler() {
 return StartStreamTranscriptionResponseHandler.builder()
 .onResponse(r -> {
 System.out.println("Received Initial response");
 })
 .onError(e -> {
 System.out.println(e.getMessage());
 StringWriter sw = new StringWriter();
 e.printStackTrace(new PrintWriter(sw));
 System.out.println("Error Occurred: " + sw.toString());
 })
 .onComplete(() -> {
 System.out.println("=== All records stream successfully ===");
 })
 .subscriber(event -> {
 List<Result> results = ((TranscriptEvent)
 event).transcript().results();
 if (results.size() > 0) {
 if (!results.get(0).alternatives().get(0).transcript().isEmpty()) {

 System.out.println(results.get(0).alternatives().get(0).transcript());
 }
 }
 })
 .build();
 }
```

I'm trying to create a lambda using Node.js to do the following:
1. Pull down a .mp4 file.
2. Extract audio using local ffmpeg call
3. Stream audio to Transcribe & get results

Goal is to have this code run as quickly as possible.
We're using Node.js instead of Java because then we need to make a call to AWS AppSync and AWS AppSync doesn't seem to be Java-friendly.
We use AppSync in the lambda as we want this server-side process to push data to clients through AppSync Subcriptions.

Problem:  **Is your feature request related to a problem? Please describe.**
We need a way to quickly run Transcribe streams from Node.js Javascript & know when we are complete.

Solution: **Describe the solution you'd like**
_... A clear and concise description of what you want to happen._
We'd like to know when we're done.

Alternatives: **Describe alternatives you've considered**
_... A clear and concise description of any alternative solutions or features you've considered._
If we knew the count of results returned was guaranteed to be the same count as that which is sent, then we could stop.
Or if we got a termination flag
Or if we sent a specific 'done' flag

**Additional context**
_... Add any other context or screenshots about the feature request here._

We're using the code from:
[https://github.com/aws/aws-sdk-js-v3/tree/master/clients/client-transcribe-streaming]
We don't know how your example there works.

Thanks again for any support!
Ted

**Comment by AllanZhengYP** [comment]
Hi @ted-consolidatedwonder 

I'm sure you already read the [README](https://github.com/aws/aws-sdk-js-v3/tree/master/clients/client-transcribe-streaming#handling-text-stream). In JavaScript, with async-await, you can simply await for your `onComplete` async function after the async-for loop. You don't need an `onComplete` callback:

```javascript
const command = new StartStreamTranscriptionCommand({/* params */});
const response = await client.send(command);
for await (const event of response.TranscriptResultStream) {
  if (event.TranscriptEvent) {
    /* handle text stream */
  }
}
await onComplete(); // onComplete is an async function.
```
