### ISSUE TITLE
How-to: Set promise dependency for S3 Client

### ISSUE THREAD

**Issue by TechTeam12** [aws/aws-sdk-js-v3#1756]
**Describe the issue with documentation**
I can't find clear documentation in any of the client libraries, models, or packages on how we'd now set the promise dependency per client. 

In the previous version of the SDK for setting the promise dependency there was global configuration for that: `config.setPromisesDependency()`. With the migration of global configuration to individual clients, I can't find the set promise dependency function for the S3 client.

Questions:
How can I set the promise dependency for S3 Client, and other clients? 
Where can I find better documentation, or a migration guide?

**Comment by AllanZhengYP** [comment]
Hey @TechTeam12 

V3 only uses ECMAScript Promise from the runtime. In fact, the client ships ES5 for browsers, which have native promise implementation support.

Can you elaborate your usecase?

**Comment by TechTeam12** [comment]
Hey @AllanZhengYP 

I've been using [Bluebird](https://github.com/petkaantonov/bluebird) for their promise introspection abilities with [tap](http://bluebirdjs.com/docs/api/tap.html). It's come in handy when dealing with complex lambda functions and trying to debug states of that. I can proceed without tap and use native promises. 

Thanks for the link to the migration guide.

**Comment by ajredniwja** [comment]
I will close this issue if it is not an issue anymore.
