### ISSUE TITLE
ChainableTemporaryCredentials

### ISSUE THREAD

**Issue by tjunnone** [aws/aws-sdk-js-v3#1796]
**Is your feature request related to a problem? Please describe.**
We'd like to start adopting the AWS v3 SDK, but the current lack of ChainableTemporaryCredentials is a blocker.

Refresher on the difference wrt normal TemporaryCredentials:

> AWS.ChainableTemporaryCredentials differs from AWS.TemporaryCredentials in the way masterCredentials and refreshes are handled. AWS.ChainableTemporaryCredentials refreshes expired credentials using the masterCredentials passed by the user to support chaining of STS credentials. However, AWS.TemporaryCredentials recursively collapses the masterCredentials during instantiation, precluding the ability to refresh credentials which require intermediate, temporary credentials.

So if you have a server that has an IAM role assigned for the master credentials, and the process is using STS to assume other roles, you need to use ChainableTemporaryCredentials.

**Describe the solution you'd like**
Port of ChainableTemporaryCredentials from v2 to v3 SDK.

**Describe alternatives you've considered**
Work around lack of automatic credential refreshing, this gets pretty tricky.

**Additional context**
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ChainableTemporaryCredentials.html

**Comment by AllanZhengYP** [comment]
Hi @tjunnone 

Unfortunately, the equivalent of `ChainableTemporaryCredentials` in v3 is not yet implemented. I've added this feature request to our high-priority features. I will post here when we take it up. Thank you for reporting it!

**Comment by andcea** [comment]
Is there a workaround for this? The only way I managed to get a ddb client working with sts.assumeRole in v3 is pretty verbose.

```
interface Credentials {
  readonly accessKeyId: string
  readonly secretAccessKey: string
  readonly expiration: Date
  readonly sessionToken?: string
}

const stsClient = new STSClient({
  region: process.env.AWS_REGION,
})

const assumeRoleCommand = new AssumeRoleCommand({
  RoleArn: exampleRoleArn,
  RoleSessionName: 'example-session-name',
  DurationSeconds: 3600,
})

let credentials: Credentials

const ddbClient = new DynamoDBClient({
  region: process.env.AWS_REGION,
  credentials: async () => {
    if (!credentials || credentials.expiration.getTime() - Date.now() < 300000) {
      const assumeRoleOutput = await stsClient.send(assumeRoleCommand)
      const Credentials = assumeRoleOutput.Credentials!

      credentials = {
        accessKeyId: Credentials.AccessKeyId!,
        secretAccessKey: Credentials.SecretAccessKey!,
        expiration: Credentials.Expiration!,
        sessionToken: Credentials.SessionToken,
      }
    }

    return credentials
  },
})
```

If you're wondering why I defined a Credentials type and mapping: https://github.com/aws/aws-sdk-js-v3/issues/1685

**Comment by cprice404-aws** [comment]
This is a pretty big blocker for us too.

**Comment by cprice404-aws** [comment]
As days go by this proves more and more crippling :P

**Comment by nfantone** [comment]
Any updates here? It's disappointing to me that an SDK doesn't handle these kinds of things.

After several attempts and scavenging through the docs and the source code, this what we came up with using `@aws-sdk/client-s3`, `@aws-sdk/client-sts` and `@aws-sdk/credential-provider-node'`.

```js
const { S3 } = require('@aws-sdk/client-s3')
const { getDefaultRoleAssumer } = require('@aws-sdk/client-sts')
const { defaultProvider } = require('@aws-sdk/credential-provider-node')

const assumeRole = getDefaultRoleAssumer()
const getCredentials = defaultProvider()

const s3 = new S3({
  credentials: async () => {
    const credentials = await getCredentials()
    return assumeRole(credentials, {
      RoleArn: 'arn:aws:iam::44444444:role/some/name',
      RoleSessionName: 'some-random-name',
    })
  },
})
```

**Comment by AllanZhengYP** [comment]
@nfantone 's workaround it what I recommend. I will be working on provide an abstraction so users don't need to write these code anymore.
