### ISSUE TITLE
Use of vulnerable, deprecated, and unmaintained packages in @aws-sdk-middleware-retry

### ISSUE THREAD

**Issue by ebickle** [aws/aws-sdk-js-v3#1797]
**Describe the bug**

The `@aws-sdk-middleware-retry` library has multiple significant dependency issues, all related to the package `react-native-get-random-values@1.5.0`:
- `react-native-get-random-values@1.5.0`  depends on 9 other packages that are marked as deprecated in NPM.
- `react-native-get-random-values` depends on `react-native`. Having `react` and `react-native` as a core dependency of `@aws-sdk` is inappropriate - `react` is a client-side component and `react-native` is focused around native app development. In our case, we're using `@aws-sdk` entirely on the server side.
- `react-native-get-random-values` and `react-native` have extremely deep dependency trees, creating significant risk to applications that need to call AWS services. Installing `@aws-sdk` version 3.0.0 resulted in 753 new packages that weren't present in version 2.X.
- `react-native-get-random-values` depends on a library that contains a security vulnerability. In my case I installed `@aws-sdk/client-kms` and ended up with 10 security vulnerabilities.

Deprecated packages via `react-native-get-random-values` in `@aws-sdk-middleware-retry@3.0.0`:
- `urix@0.1.0`
- `resolve-url@0.2.1`
- `fsevents@1.2.13`
- `@hapi/topo@3.1.6`
- `@hapi/bourne@1.3.2`
- `@hapi/address@2.1.4`
- `@hapi/hoek@8.5.1`
- `@hapi/joi@15.1.1`
- `core-js@2.6.12`

Vulnerable packages via `react-native-get-random-values` in `@aws-sdk-middleware-retry@3.0.0`:
- `node-fetch@2.6.1` 

**SDK version number** 
> 3.0.0

**Is the issue in the browser/Node.js/ReactNative?**
N/A. Issue is during package installation via NPM.

**Details of the browser/Node.js/ReactNative version**
> node -v
> v14.15.1

**To Reproduce (observed behavior)**
1. `npm install @aws-sdk/client-kms`

**Expected behavior**
1. @aws-sdk should not install packages with known security vulnerabilities.
2. @aws-sdk should not depend on any deprecated packages.
3. @aws-sdk should not depend on react, react-native, or other UI-specific third-party packages.

**Console Log**
> npm install @aws-sdk/client-kms
> npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
> npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
> npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
> npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
> npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
> npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
> npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
> npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
> npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
> 
> added 753 packages, changed 3 packages, and audited 1064 packages in 1m
> 
> 10 low severity vulnerabilities

**Comment by brentjanderson** [comment]
A random build step bug in a backend serverless function led me to this issue. The error was `Cannot find module 'react-native'` which I found odd given that I'm not using react at all in that function.

+1 to using something other than `react-native-get-random-values` as it significantly complicates and needlessly bloats projects using AWS SDK v3.

**Comment by xeger** [comment]
I'm sure that getting random values is crucial to the middleware's operation, but there's _nothing wrong with copy-pasting_ whatever is being used into this package.

Causing people to pull in the entire React Native ecosystem as a peer dependency is completely nuts; it exposes every user of the AWS SDK to vulnerabilities and sets off auditing alarms like mad.
