### ISSUE TITLE
"Error: Credentialis missing" when CognitoIdentityClient is called in browser/ReactNative without credentials

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#1798]
**Describe the bug**
Error in browser console when is CognitoIdentityClient without credentials.

**SDK version number**
`3.0.0`

**Is the issue in the browser/Node.js/ReactNative?**
Browser/ReactNative

**Details of the browser/Node.js/ReactNative version**
N/A

**To Reproduce (observed behavior)**
* Run browser set up from https://github.com/aws-samples/aws-sdk-js-tests#browser
  * The error thrown in Browser console.
* Run React Native set up from https://github.com/aws-samples/aws-sdk-js-tests#react-native
  * The error is thrown in Metro console, and Output contains error "not implemented"

**Expected behavior**
CognitoIdentityClient should not throw error when credentials are not passed.

**Screenshots**

<details>
<summary>Browser console</summary>

![Screen Shot 2020-12-16 at 3 09 05 PM](https://user-images.githubusercontent.com/16024985/102417522-b9447f00-3fb0-11eb-9aca-7ffd7227dbfb.png)

</details>

<details>
<summary>React Native iOS</summary>

<img width="682" alt="Screen Shot 2020-12-16 at 3 11 10 PM" src="https://user-images.githubusercontent.com/16024985/102417666-fd378400-3fb0-11eb-8487-5c644cffcb5a.png">

</details>

**Comment by trivikr** [comment]
This issue was introduced in `1.0.0-rc.8` by PR https://github.com/aws/aws-sdk-js-v3/pull/1719
The issue is not reproducible in `1.0.0-rc.7` or earlier.

```
    "@aws-sdk/client-cognito-identity": "1.0.0-rc.7",
    "@aws-sdk/client-dynamodb": "1.0.0-rc.7",
    "@aws-sdk/credential-provider-cognito-identity": "1.0.0-rc.7",
```

**Comment by trivikr** [comment]
The PR https://github.com/aws/aws-sdk-js-v3/pull/1719 was posted to allow unauthenticated API calls for public APIs. The issue is with `invalidAsyncFunction` which rejects with an error as soon as it's called, and not when it's awaited.

invalidAsynsFunction is passed in `runtimeConfig.browser.ts`:
https://github.com/aws/aws-sdk-js-v3/blob/4f9e56f1b7fd1cd9374b2577786e4ab0f6602aaa/clients/client-cognito-identity/runtimeConfig.browser.ts#L24

And it's called in `resolveAwsAuthConfig`:
https://github.com/aws/aws-sdk-js-v3/blob/4f9e56f1b7fd1cd9374b2577786e4ab0f6602aaa/packages/middleware-signing/src/configurations.ts#L46

**Comment by trivikr** [comment]
This happens as rejecting Promise in `invalidAsyncFunction` throws before await is called on it.

**Comment by trivikr** [comment]
Proposed solution: Call `resolveAwsAuthConfig` only for commands which require authentication if a service client supports a public API.

For example, the following line in CreateIdentityPoolCommand: https://github.com/aws/aws-sdk-js-v3/blob/4f9e56f1b7fd1cd9374b2577786e4ab0f6602aaa/clients/client-cognito-identity/commands/CreateIdentityPoolCommand.ts#L76

Will be updated to:
```js
	this.middlewareStack.use(getAwsAuthPlugin(resolveAwsAuthConfig(configuration)));
```

And the call to `resolveAwsAuthConfig` will be removed from CognitoIdentityClient: https://github.com/aws/aws-sdk-js-v3/blob/4f9e56f1b7fd1cd9374b2577786e4ab0f6602aaa/clients/client-cognito-identity/CognitoIdentityClient.ts#L283

If this solution works, then invalidAsyncFunction can be removed in favor of invalidFunction, as both throw errors when called.

**Comment by trivikr** [comment]
Proposed solution 2: Go through all operations for a client and check if any of the operation has optional authentication.

This is similar to what is done for EventStream 
https://github.com/awslabs/smithy-typescript/blob/12548475eeff89528dd2ffd504289a08c3103d38/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddEventStreamDependency.java#L108-L114

This would throw credentials missing errors for clients which have at least one operation with optional authentication trait, and an operation which requires authentication is called without credentials.

**Comment by TheColorRed** [comment]
I don't know if I am doing something wrong, but even when I do pass credentials I am getting this error.

```
ERROR Error: Uncaught (in promise): Error: Credentialis missing
Error: Credentialis missing
```
This is what my code looks like:
```typescript
  private readonly s3 = new S3({
    region: environment.AWS.region,
    credentials: fromCognitoIdentityPool({
      client: new CognitoIdentityClient({ region: environment.AWS.region }),
      identityPoolId: environment.AWS.identityPoolId
    })
  })
```

**Comment by trivikr** [comment]
This issue happens because CognitoIdentityClient is expecting credentials even though they're not required.

A temporary fix is to pass fake credenitialProvider as follows:

```js
private readonly s3 = new S3({
    region: environment.AWS.region,
    credentials: fromCognitoIdentityPool({
      client: new CognitoIdentityClient({
        region: environment.AWS.region,
        credentials: () => Promise.resolve({} as any), // Temporary fix
      }),
      identityPoolId: environment.AWS.identityPoolId
    })
  })
credentials: () => Promise.resolve({} as any),`
``
