### ISSUE TITLE
SignatureDoesNotMatch while uploading an object to S3 with ContentType

### ISSUE THREAD

**Issue by Tietew** [aws/aws-sdk-js-v3#1800]
**Describe the bug**
SignatureDoesNotMatch occures while uploading an object to S3 with ContentType.

**SDK version number**
@aws-sdk/client-s3@3.0.0

**Is the issue in the browser/Node.js/ReactNative?**
Node.js

**Details of the browser/Node.js/ReactNative version**
```
$ node -v
v12.20.0
```

**To Reproduce (observed behavior)**

Run following script

``` js
import { S3 } from '@aws-sdk/client-s3';

const s3 = new S3({ region: 'ap-northeast-1' });
s3.putObject({
  Bucket: 'mybucketname',
  Key: 'blah.json',
  ContentType: 'application/json',
  Body: Buffer.from(JSON.stringify({ dead: 'beef' })),
}).then(console.log, console.error);
```

Got

```
SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

**Expected behavior**
An object `s3://mybucketname/blah.json` is created with its Content-Type is `application/json`.

**Additional context**
With no `ContentType`, object is successfully created but its Content-Type is `application/octet-stream`.

**Comment by joain946** [comment]
I just ran into this issue as well.
The problems seems to be that there are two content type headers being added. The one specified in PutObject ends up as "Content-Type" then the other header that is being added behind the scene is added as "content-type". 
The only workaround I have found so far is to create your own "signer" object when creating the S3 client and that class can then filter out the "content-type" header and then delegate to the "SignatureV4.ts" class. 

Here is what the headers for the signing looks like when getting into the SignatureV4.sign(...) method:
![image](https://user-images.githubusercontent.com/12528518/102481516-1b10f180-4062-11eb-8f89-b44accf8fb9b.png)

**Comment by AllanZhengYP** [comment]
Hi @Tietew @joain946 

I can confirm this is a bug. We will fix it soon. Thanks a lot for reporting and investigating in this.

**Comment by apostolos** [comment]
Adding `"content-type": true` in `ALWAYS_UNSIGNABLE_HEADERS` seems to fix the problem:
https://github.com/aws/aws-sdk-js-v3/blob/master/packages/signature-v4/src/constants.ts#L18-L34

**Comment by adamelmore** [comment]
> Hi @Tietew @joain946
> 
> I can confirm this is a bug. We will fix it soon. Thanks a lot for reporting and investigating in this.

Hi @AllanZhengYP, any chance you have an ETA on this fix? Or are there any known workarounds?

**Comment by adamelmore** [comment]
I'm actually working around it with middleware until this is fixed; in case this is helpful to anyone else:

```
  const s3 = new S3()

  s3.middlewareStack.add(
    (next) => async (args) => {
      delete args.request.headers['content-type']
      return next(args)
    },
    {step: 'build'},
  )

  await s3.putObject({
      Bucket: bucket,
      Key: key,
      Body: body,
      ContentType: contentType,
    })
```

**Comment by vokeio** [comment]
Maybe this is assumed but I wanted to add that this issue also plagues the v3 modular interface. Also @adamelmore middleware workaround gets past the issue for the modular interface.

**Comment by gswebspace** [comment]
Ran into this as well. Adding ContentType results in `SignatureDoesNotMatch`.
