### ISSUE TITLE
list all object when objects-count is over 1000

### ISSUE THREAD

**Issue by swellee** [aws/aws-sdk-js-v3#1801]
**Is your feature request related to a problem? Please describe.**
my s3 bucket contains much more than 1000 files, when I use client-s3, and call client.listObjects({MaxKeys: 5000}), it only return the first 1000 keys,so  how can I list all object-keys?

**Describe the solution you'd like**
it's better to provide a `client.count({xxFilter})` for the total number by given filter, and add options 'fromKey' or sth to client.listObjects() to get objects from given key

**Comment by AllanZhengYP** [comment]
Hi @swellee 

You can use the paginator feature in v3. The paginator will split the results in pages and you can read through them in consecutive request. [This blog post](https://aws.amazon.com/blogs/developer/pagination-using-async-iterators-in-modular-aws-sdk-for-javascript/) outlines the details you need for using the feature. 

For this one you can look into `paginateListObjectsV2` paginator.

**Comment by swellee** [comment]
great! thanks!

**Comment by swellee** [comment]
hmm, sorry, @AllanZhengYP ,
I tried the paginatelistObjectV2 function, seems not work, example code :
`let res = { done: false, list: [], ContinuationToken: '' }
            while (!res.done) {
                const objs = await paginateListObjectsV2(
                    {
                        client,
                        pageSize,
                    },
                    {
                        Bucket: AWS_BUCKET,
                        Prefix: folder,
                        ...(res.list.length ? { ContinuationToken: res.ContinuationToken, StartAfter: res.list[res.list.length - 1].Key } : {})
                    }).next()
                const pagelist = objs.value ? objs.value.Contents : []
                res.done = !pagelist.length
                res.list = res.list.concat(pagelist)
                res.ContinuationToken = objs.value.NextContinuationToken
                console.log(folder, 'get pagedata,', objs)
            }`
            even i set the `StartAfter` and `ContinuationToken` (or set one of them), it still return the first page's objects each loop.
            am I using it wrong way?

**Comment by AllanZhengYP** [comment]
Hi @swellee, are you following the v3 SDK code snippet? It's under the `Pagination using Async Iterators in JavaScript SDK v3` section of the [blog post](https://aws.amazon.com/blogs/developer/pagination-using-async-iterators-in-modular-aws-sdk-for-javascript/).

Here's what it would look like:

```javascript
const {
  S3Client,
  paginateListObjectsV2,
} = require("@aws-sdk/client-s3");

//...
const paginatorConfig = {
  client: new S3Client({}),
  pageSize: 30
};
const commandParams = { Bucket: "bucket" };
const paginator = paginateListObjectsV2(paginatorConfig, commandParams);

const objects = [];
for await (const page of paginator) {
  // page contains a single paginated output.
  objects.push(...page.Contents);
}
```

**Comment by swellee** [comment]
@AllanZhengYP Many thanks!
