### ISSUE TITLE
change client-dynamodb waitForTableExists/waitForTableNotExists default minDelay to 1 second or make configurable to caller

### ISSUE THREAD

**Issue by stang-tgs** [aws/aws-sdk-js-v3#1806]
**Is your feature request related to a problem? Please describe.**
The default `minDelay` in `waitForTableExists` and `waitForTableNotExists` is 20 seconds - this is somewhat annoying, especially when running tests that creates tables locally using mock AWS services (e.g. [localstack](https://github.com/localstack/localstack)) which can complete almost immediately

**Describe the solution you'd like**
Decrease the minDelay to 1 second or allow caller to configure.  Waiters will exponentially back off, so min delay of 1 second shouldn't be an issue?  Especially if one day, real DynamoDb does decide to complete the create/delete table in 1 second 😄, so we wouldn't need to wait the full 20 seconds. 

**Describe alternatives you've considered**
None

**Comment by alexforsyth** [comment]
We should be solving this in: https://github.com/aws/aws-sdk-js-v3/pull/1839. 

For the short term (and to unblock you immediately) you can pass minDelay like so:

```

import { DynamoDBClient, waitForTableExists } from "@aws-sdk/client-dynamodb"

(async () => {
    const TableName = "MY-TEST-TABLE-1";
  
    const maxWaitTime = 120;
    const client: DynamoDBClient = new DynamoDBClient({});
    let result = await waitForTableExists( { 
        client,
        minDelay: 20,
        maxWaitTime: 25 } as any, { TableName });
    console.log("Table exists", result);
  })();
  
  ```
  
Please note the "as any" to override typescript. This is NOT officially supported (yet)!
