### ISSUE TITLE
DynamoDB client does not parse request id from header

### ISSUE THREAD

**Issue by AllanFly120** [aws/aws-sdk-js-v3#181]
The response is suppose to have `requestId` value that contains the value from `x-amzn-requestid` header. We need to add another statement to extract request id from the header above other than `x-amz-requestid`. A small update [here](https://github.com/aws/aws-sdk-js-v3/blob/master/packages/response-metadata-extractor/src/index.ts#L23) may fix the issue.

**Comment by srchase** [comment]
Resolved in #184.
