### ISSUE TITLE
Some new services cannot resolve to correct endpoints

### ISSUE THREAD

**Issue by AllanZhengYP** [aws/aws-sdk-js-v3#1817]
**Describe the bug**
Several new service clients released recently during Re:Invent cannot resolve the endpoints correctly. To workaround, users need to supply the correct endpoint manually from client constructor. 

These services are:
* Contact Lens
* ECR Public
* Edge Sagemaker
* Sagemaker Runtime
* ServiceCatelog Application Registror

**SDK version number**
3.0.0

**Is the issue in the browser/Node.js/ReactNative?**
Browser & Node.js & ReactNative

**To Reproduce (observed behavior)**
Any call using mentioned clients will result in errors.

**Expected behavior**
The clients should work without errors.

**Additional context**
These new services models contains `endpoint-prefix` trait, which was only introduced in Smithy model very recently. Previously, the code generator maintains a map from serviceID to endpoint prefix manually. However, this map is not updated in time, and new Smithy trait `endpoint-prefix` is not supported.

**Comment by trivikr** [comment]
Related: https://github.com/AllanZhengYP/cors-test/issues/12
