### ISSUE TITLE
S3 - memory leak for Readable stream to lib-storage Upload

### ISSUE THREAD

**Issue by samsullivan** [aws/aws-sdk-js-v3#1828]
**Describe the bug**
When using the `Upload` function implemented in `lib-storage` (https://github.com/aws/aws-sdk-js-v3/pull/1547) on a large stream, memory is leaked because event handlers aren't cleaned up. I attempted to upgrade from v2 of the SDK for a use case where I stream data to S3 and I noticed the following error:

> MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [ReadStream]. Use emitter.setMaxListeners() to increase limit

**SDK version number**
v3.0.0

**Is the issue in the browser/Node.js/ReactNative?**
Node.js

**Details of the browser/Node.js/ReactNative version**
```
$ node -v
v12.16.2
```

**To Reproduce (observed behavior)**
You should be able to recreate this by using the example with a large file on a container with somewhat limited memory:
https://github.com/aws/aws-sdk-js-v3/blob/master/lib/storage/example-code/file-upload.ts

**Expected behavior**
Event listeners clean up after themselves so this isn't processing the same parts of a stream multiple times the longer the method runs. Large files get uploaded without exception.

**Comment by samsullivan** [comment]
I was able to fix this in #1829, although I'm still running into some issues with my production use case of streaming from a DB to S3. I think there may be something else going on, but I'll share in case it's related.

After a handful of chunks successfully uploaded I end up getting a TLS timeout error:
>  Client network socket disconnected before secure TLS connection was established

**Comment by AllanZhengYP** [comment]
Hey @samsullivan This issue is duplicated with https://github.com/aws/aws-sdk-js-v3/issues/1728. I see you have a PR up for that too. We will prioritize merging it.

**Comment by samsullivan** [comment]
Oops, my bad! It's been a whirlwind week trying to wrap up loose ends before the break and I'm actually trying out the v3 SDK because of an ECS Fargate IAM bug in v2, so I totally forgot to do a good search of this specific bug before creating this issue.

I'll let ya know if I find any other problems in lib-storage's upload from stream. Appreciate you looking at the PR whenever and let me know if I need to do anything else.

**Comment by thomassuckow** [comment]
The memory usage with Upload still appears to be be considerably higher than the v2 upload method in sdk 3.1.0.

You can see us maxing out a 256mb lambda trying to stream some data from another source to s3.
![image](https://user-images.githubusercontent.com/3100037/103712716-65a1d180-4f6f-11eb-89bf-c20e0b07f3c2.png)

As soon as we reverted the change to the v3 Upload it resolved. As far as I can tell the default chunk sizes are identical between the two versions.

**Comment by trivikr** [comment]
> The memory usage with Upload still appears to be be considerably higher than the v2 upload method in sdk 3.1.0.

@thomassuckow Please create a [separate GitHub issue](https://github.com/aws/aws-sdk-js-v3/issues/new?assignees=&labels=bug%2C+needs-triage&template=---bug-report.md&title=) as this is related to memory usage and not memory leak.

**Comment by samsullivan** [comment]
@thomassuckow I'd be curious if you could try with this branch: https://github.com/aws/aws-sdk-js-v3/pull/1841

Your benchmarking may be better than anything I did.
