### ISSUE TITLE
TypeScript Doesn't Work with DynamoDBClient Type

### ISSUE THREAD

**Issue by fishcharlie** [aws/aws-sdk-js-v3#1843]
**Describe the bug**

TypeScript doesn't work with DynamoDBClient Type. It seems to be using a lot of `any` types and not autocompleting as I expect it to be. (Will be more obvious once you run the MCVE attached).

**SDK version number**

3.1.0

**Is the issue in the browser/Node.js/ReactNative?**

Node.js

**Details of the browser/Node.js/ReactNative version**

v14.0.0

**To Reproduce (observed behavior)**

1. Create new folder and `cd` into it in Terminal
2. Run the following commands in Terminal:
    - `npm i @aws-sdk/client-dynamodb`
    - `npm i @types/node`
    - `touch index.ts`
    - `touch tsconfig.json`
3. Paste the code below into each of the files
4. Run `tsc` in Terminal

**tsconfig.json**

```
{
	"compilerOptions": {
		"module": "commonjs",
		"moduleResolution": "node",
		"lib": ["es2015"],
		"target": "es2017",
		"outDir": "dist",
		"sourceMap": true,
		"declaration": true,
		"noImplicitThis": true,
		"strict": false
	},
	"include": ["**/*"]
}
```

**index.ts**

```
const { DynamoDBClient, DynamoDB } = require("@aws-sdk/client-dynamodb");

function main(): DynamoDBClient {
	return new DynamoDBClient({
		"region": "us-west-2"
	});
}

function main2(): DynamoDB {
	return new DynamoDB({
		"region": "us-west-2"
	});
}
```

**Expected behavior**

There to be no errors. Or there to only be errors with either `main` or `main2`.

**Current behavior**

```
charliefish@Charlies-MBP tmp3 % tsc
index.ts:3:18 - error TS2749: 'DynamoDBClient' refers to a value, but is being used as a type here.

3 function main(): DynamoDBClient {
                   ~~~~~~~~~~~~~~

index.ts:3:18 - error TS4060: Return type of exported function has or is using private name 'DynamoDBClient'.

3 function main(): DynamoDBClient {
                   ~~~~~~~~~~~~~~

index.ts:9:19 - error TS2749: 'DynamoDB' refers to a value, but is being used as a type here.

9 function main2(): DynamoDB {
                    ~~~~~~~~

index.ts:9:19 - error TS4060: Return type of exported function has or is using private name 'DynamoDB'.

9 function main2(): DynamoDB {
                    ~~~~~~~~


Found 4 errors.
```

**Screenshots**

**Additional context**

- On [this link](https://aws.amazon.com/blogs/developer/first-class-typescript-support-in-modular-aws-sdk-for-javascript/) under the `IDE Support` section, the code snippet is almost exactly what I'm trying to do. I will note, when I try to enter that EXACT same code into my IDE, I don't get autocomplete or anything. And the type of `client` is `any`.
- This works if I change it from a `require` to an `import` statement. However, due to backwards compatibility issues, my project requires it to use `require` as opposed to `import`. It would break a lot of users code to switch it. There must be some solution since your post above uses `require`.

**Comment by alexforsyth** [comment]
@fishcharlie Thanks for opening an issue. From what I can see the code as it is written won't bring in types. But is instead referencing the DynamoDB value. Typescript rightfully complains that function definitions should return a type. 

You'll need to add a typeof to the function definiton. 
```
const { DynamoDBClient, DynamoDB } = require("@aws-sdk/client-dynamodb");

function main(): typeof DynamoDBClient {
...
}

function main2(): typeof DynamoDB {
...
}

```

However this wont really help you since you're still not bringing in types and this code is just saying that main returns the typeof the constructed object.

To bring in types with require syntax you'd need to do something like:
```
import dynamo = require("@aws-sdk/client-dynamodb");
function main() {
	return new dynamo.DynamoDBClient({
		"region": "us-west-2"
	});
}

function main2() {
	return new dynamo.DynamoDB({
		"region": "us-west-2"
	});
}
```
Note that specifying the return type of main and main2 is not needed any longer as it can be inferred. Vscode does this pretty well!
![Screen Shot 2021-01-04 at 11 29 08 AM](https://user-images.githubusercontent.com/8712303/103556904-71629a80-4e80-11eb-9a11-8b8c32ea88cc.png)


You should also be able to get full autocomplete and whatnot.
![Screen Shot 2021-01-04 at 11 34 02 AM](https://user-images.githubusercontent.com/8712303/103557172-c7cfd900-4e80-11eb-8d69-22fd974e9eb4.png)




Here's reading on how typescript handles models and exports. 
https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require

**Comment by fishcharlie** [comment]
@alexforsyth Ahhh got it. I think that solves my issue. Now I realize this is probably outside of the scope of this repo's support, so I **truly appreciate** you taking the time to help me out.

Might I suggest updating the screenshot on https://aws.amazon.com/blogs/developer/first-class-typescript-support-in-modular-aws-sdk-for-javascript/ under the IDE section to use `import dynamo = require("@aws-sdk/client-dynamodb");`?

I also feel like the documentation is a little bit spread out for v3. There doesn't seem to be a singular resource I can go to for information. In some instances I've found information on the repo README, in different AWS blog posts, sometimes on NPM's website, etc.

**Comment by alexforsyth** [comment]
@fishcharlie no worries - typescript generally really wants you to use imports. The code posted works with auto complete in .js files. @trivikr will be updating the blog posts for a bit of clarity around this.

**Comment by trivikr** [comment]
The blog post [First-class TypeScript support in modular AWS SDK for JavaScript](https://aws.amazon.com/blogs/developer/first-class-typescript-support-in-modular-aws-sdk-for-javascript/) was updated with screenshot of a TypeScript example which uses imports.
