### ISSUE TITLE
Using S3 client with custom endpoint without region throws "Region is missing"

### ISSUE THREAD

**Issue by ohana54** [aws/aws-sdk-js-v3#1845]
**Describe the bug**
When using the S3 client with a custom endpoint and without a region, an error "Region is missing" is thrown. This didn't happen with V2.
See the reproduction code below.

**SDK version number**
3.1.0

**Is the issue in the browser/Node.js/ReactNative?**
Node.js

**Details of the browser/Node.js/ReactNative version**
v12.18.2

**To Reproduce (observed behavior)**
The following code reproduces the error (there's no need for a running S3 server):
```javascript
const { S3 } = require('@aws-sdk/client-s3')

const s3 = new S3({
  endpoint: 'http://localhost:8000',
  credentials: { accessKeyId: 'local-s3', secretAccessKey: 'local-s3' },
})
s3.listBuckets({}).then(() => {
  console.log('done') // never gets here
})

```

**Expected behavior**
I expect no errors when not supplying a region given a custom endpoint is supplied.

**Comment by AllanZhengYP** [comment]
Hi @ohana54 

In v2 the SDK will use `us-east-1` as default region when S3 endpoint is global, like `bucket.s3.amazonaws.com`. However, in v3, we don't support global endpoint yet, here's the feature request: https://github.com/aws/aws-sdk-js-v3/issues/1807. To workaround it, you can explicitly set the region to `us-east-1`.

**Comment by ohana54** [comment]
Thanks @AllanZhengYP, appreciate the response. I'll add the workaround and wait for it to be implemented.

**Comment by thetutlage** [comment]
I use Digital ocean endpoint and no sure if region is applicable to Digital ocean
