### ISSUE TITLE
CognitoIdentityClient requires 'credentials' in its constructor

### ISSUE THREAD

**Issue by c4k9c0** [aws/aws-sdk-js-v3#185]
I am trying to construct a `CognitoIdentityClient` to get AWS Credentials for unauthenticated users.
Here is the code:

```
import { CognitoIdentityClient } from '@aws-sdk/client-cognito-identity-browser/CognitoIdentityClient'
const cognitoIdentityClient = new CognitoIdentityClient({
  region: 'us-wes'
})
```

TS throws a the compile error `Properties 'credentials' is missing in type...`
`credentials` should not be required to create a `CognitoIdentityClient` since it is the thing used to get credentials.

**Comment by tommedema** [comment]
@AllanFly120 this gives me an error `Type 'GetCredentialsForIdentityCommand' has no call signatures.ts(2349)`:

<img width="1077" alt="Screen Shot 2020-01-16 at 2 53 47 PM" src="https://user-images.githubusercontent.com/331833/72569785-12230900-3870-11ea-894e-f15254b111d5.png">

**Comment by trivikr** [comment]
Verified that credentials are no longer required to be passed in CognitoIdentityClient constructor in test repo in PR https://github.com/aws-samples/aws-sdk-js-tests/pull/4
