### ISSUE TITLE
S3 signed url deprecation?

### ISSUE THREAD

**Issue by kbrashears5** [aws/aws-sdk-js-v3#1851]
**Describe the bug**
S3 [getSignedUrl](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getSignedUrl-property) function was apparently deprecated in v3 with no notice?

**SDK version number**
3.1

**Is the issue in the browser/Node.js/ReactNative?**
Node.js

**Details of the browser/Node.js/ReactNative version**
N/A

**To Reproduce (observed behavior)**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Additional context**

**Comment by monken** [comment]
It's been moved to a dedicated package: https://github.com/aws/aws-sdk-js-v3/tree/master/packages/s3-request-presigner

**Comment by kbrashears5** [comment]
@monken that's what I needed, thanks!
