### ISSUE TITLE
SimpleDB missing

### ISSUE THREAD

**Issue by kaibo-ondruska** [aws/aws-sdk-js-v3#1854]
I cannot find client for SimpleDB in AWS SDK for JavaScript v3. Up until now I used v2 with SimpleDB and no problems.

**Comment by alexforsyth** [comment]
Simple DB does not scale and is largely deprecated. It's not available to new accounts at all, and not available in any region launched in the last 7 years (not even us-east-2). I would highly recommend not to use SimpleDB and/or phase out any code still relying on simpleDB - we do not support it in v3.

Take a look at DynamoDb and AppSync. They may be able to solve your issues a bit better.
