### ISSUE TITLE
Creating multiple signed URL promises fails with duplicate middleware error

### ISSUE THREAD

**Issue by olokobayusuf** [aws/aws-sdk-js-v3#1857]
I'm using the `@aws-sdk/client-s3` and `@aws-sdk/s3-request-presigner` packages to sign S3 object URL's in my GraphQL API. I've run into an issue where if there are multiple promises requesting a URL in one node tick, the following error occurs:
```
Duplicated middleware name 'presignInterceptMiddleware'
```

Doing some quick digging through the `s3-request-presigner` code, it looks like the implementation uses a naive stack placement without regard for multiple concurrent requests being a possibility:

https://github.com/aws/aws-sdk-js-v3/blob/314d3b37ac9d0d500e5762705be6188d9bd69625/packages/s3-request-presigner/src/getSignedUrl.ts#L43-L56

As such, the following code will fail:
```typescript
const getObjectCommands = [...];
await Promise.all(getObjectCommands.map(command => getSignedUrl(s3, command));
```

Whereas this won't:
```typescript
const getObjectCommands = [...];
for (const command of getObjectCommands)
    await getSignedUrl(s3, command);
```

I was able to partially workaround this by refactoring my code, but now I happen to be exposing URL pre-signing through a resolver managed by GraphQL. As such I can't refactor the code to avoid this bug; it can only be fixed upstream. I remember that a while ago, pre-signed URL's didn't need to make any actual request; it was entirely generated locally. Can this behaviour be imitated? And how quickly can this bug be fixed? It's a (very serious) blocker.

**SDK version number**
```
"@aws-sdk/client-s3": "^3.1.0",
"@aws-sdk/s3-request-presigner": "^3.1.0",
"@aws-sdk/types": "^3.1.0",
```

**Is the issue in the browser/Node.js/ReactNative?**
Node JS

**Details of the browser/Node.js/ReactNative version**
Node JS v12.4.0

**To Reproduce (observed behavior)**
See above.

**Expected behavior**
No middleware stack error should occur.

**Screenshots**
From GraphQL:
```
"errors": [
    {
      "message": "Duplicated middleware name 'presignInterceptMiddleware'",
      "locations": [
        {
          "line": 9,
          "column": 9
        }
      ],
      "path": [...],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
]
```

**Additional context**

**Comment by steventhanna** [comment]
Can confirm I am experiencing similar behavior when implemented in a REST API.

**Comment by steventhanna** [comment]
As a temporary work around until there is a patch, I switched to: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getSignedUrlPromise-property 

```js
let promise = s3.getSignedUrlPromise('getObject', params)
```

which has been working so far without incident.

**Comment by olokobayusuf** [comment]
> As a temporary work around until there is a patch, I switched to: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getSignedUrlPromise-property
> 
> ```js
> let promise = s3.getSignedUrlPromise('getObject', params)
> ```
> 
> which has been working so far without incident.

What package and version are you using? In `@aws-sdk/client-s3`, the `S3` class no longer contains the `getSignedUrlPromise` method.

**Comment by steventhanna** [comment]
@olokobayusuf I'm using the latest version of `aws-sdk` (2.824.0) which you can find [here](https://www.npmjs.com/package/aws-sdk)

**Comment by olokobayusuf** [comment]
> @olokobayusuf I'm using the latest version of `aws-sdk` (2.824.0) which you can find [here](https://www.npmjs.com/package/aws-sdk)

Thanks! I realized you probably weren't using the v3 SDK any longer. @AllanZhengYP I see you've moved this to `In progress`. Do you have an ETA?

**Comment by steventhanna** [comment]
Thanks @AllanZhengYP!!
