### ISSUE TITLE
util-dynamodb: allow marshalling of named objects/classes

### ISSUE THREAD

**Issue by stang-tgs** [aws/aws-sdk-js-v3#1865]
**Describe the bug**
named objects/classes cannot be marshalled

**SDK version number**
3.1.0 (and below)
**Is the issue in the browser/Node.js/ReactNative?**
Nodejs

**Details of the browser/Node.js/ReactNative version**
v14.9.0

**To Reproduce (observed behavior)**
try to marshall a named class.  See: https://github.com/aws/aws-sdk-js-v3/issues/1647#issuecomment-747173475 for example

**Expected behavior**
The class can be marshalled

**Screenshots**
See: https://github.com/aws/aws-sdk-js-v3/issues/1647#issuecomment-747173475

**Additional context**

**Comment by trivikr** [comment]
Changing to feature-request, as util-dynamodb was designed to be narrow to start with.
Prior discussion: https://github.com/aws/aws-sdk-js-v3/issues/1533

**Comment by elmarschulz** [comment]
It would be really great if this feature was implemented. Thanks.
