### ISSUE TITLE
"Error: not implemented" in React Native environment

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#1867]
**Describe the bug**
Aws SDK for JavaScript v3 throws "Error: not implemented" when run in React Native environment.

**SDK version number**
`3.1.0`

**Is the issue in the browser/Node.js/ReactNative?**
React Native

**Details of the browser/Node.js/ReactNative version**
`0.63.4`

**To Reproduce (observed behavior)**
Run React Native set up from https://github.com/aws-samples/aws-sdk-js-tests#react-native
The error is thrown in Emulator output.

**Expected behavior**
The output is displayed under JS SDK v3

**Screenshots**

<details>
<summary>Browser</summary>

![Screen Shot 2021-01-05 at 10 11 51 AM](https://user-images.githubusercontent.com/16024985/103683046-8bfb4900-4f3e-11eb-886d-c55d34fff837.png)

</details>

<details>
<summary>React Native</summary>

<img width="598" alt="Screen Shot 2021-01-05 at 9 45 38 AM" src="https://user-images.githubusercontent.com/16024985/103682428-bac4ef80-4f3d-11eb-8ffb-36edd1dcd6f1.png">

</details>

**Comment by AllanZhengYP** [comment]
It has something to do with the https://github.com/aws/aws-sdk-js-v3/pull/1766. The `URL.get()` from is [not supported in ReactNative](https://github.com/facebook/react-native/issues/16434). The SDK needs to fall back the JS implementation.
![Screen Shot 2021-01-12 at 12 38 16 AM](https://user-images.githubusercontent.com/7614947/104360122-6f728a00-54c5-11eb-9586-cad216b22e3e.png)

**Comment by trivikr** [comment]
Verified that this issue is fixed with `v3.3.0` in https://github.com/aws-samples/aws-sdk-js-tests/pull/66
