### ISSUE TITLE
Remove apiVersion from configuration

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#1869]
**Describe the bug**
The AWS SDK for JavaScript v3 is codegen and doesn't support multiple API versions for a client.
However, it accepts `apiVersion` in the configuration which can be confusing as discussed in https://github.com/aws/aws-sdk-js-v3/issues/1844

**SDK version number**
`3.1.0`

**Is the issue in the browser/Node.js/ReactNative?**
All

**Details of the browser/Node.js/ReactNative version**
N/A

**To Reproduce (observed behavior)**
```js
const { Lambda } = require("@aws-sdk/client-lambda")

const lambda = new Lambda({
  region: "ap-south-1",
  apiVersion: "2015-03-31"
});

```

**Expected behavior**
Do not allow apiVersion in client configuration.

**Comment by AllanZhengYP** [comment]
As removing this parameter will likely to break users, we will add a `@deprecation` to the doc instead.

**Comment by trivikr** [comment]
> we will add a `@internal` to the doc instead.

Verified that `@internal` marks the code as internal:
* Typedoc: https://typedoc.org/guides/doccomments/#%40internal
* TSdoc: https://tsdoc.org/pages/tags/internal/
