### ISSUE TITLE
Implement SourceFile and SaveAs parameters in S3 API

### ISSUE THREAD

**Issue by NobleUplift** [aws/aws-sdk-js-v3#187]
In the PHP SDK, [two parameters SourceFile and SaveAs](https://aws.amazon.com/blogs/developer/transferring-files-to-and-from-amazon-s3/) exist that do not exist in the JavaScript SDK. As the documentation states:

> The SDK also provides a shortcut for uploading directly from a file using the SourceFile parameter, instead of the Body parameter.

> The SourceFile and SaveAs parameters allow you to use the SDK to directly upload files to and download files from S3 very easily.

It's true that these two parameters make uploading and downloading files much easier. For API consistency across platforms, could we get SourceFile and SaveAs added into the JavaScript API please?

**Comment by srchase** [comment]
@NobleUplift 

Thanks for submitting this request.  Tracking as a Feature Request.
