### ISSUE TITLE
Remove *.d.ts in karma config

### ISSUE THREAD

**Issue by AllanFly120** [aws/aws-sdk-js-v3#188]
Per current karma config, smoke teset manages to find the *.ts files and preprocess them using karma-typescript. In some circumstances it will try to find *.d.ts that not yet generated. This may leads to 'resource cannot be found' error. We need to exclude these file in karma.config

**Comment by srchase** [comment]
Fixed in https://github.com/aws/aws-sdk-js-v3/pull/191
