### ISSUE TITLE
Need types for the paginator start token

### ISSUE THREAD

**Issue by AllanZhengYP** [aws/aws-sdk-js-v3#1882]
**Is your feature request related to a problem? Please describe.**
Currently the paginators start token is [`any` type](https://github.com/aws/aws-sdk-js-v3/blob/54e87151877dd5cf9a5f256698c088cc7a856225/packages/types/src/pagination.ts#L15). It can be more specific to individual paginators. For example in `paginateScan()`'s start token is the type of [`ExclusiveStartKey`](https://github.com/aws/aws-sdk-js-v3/blob/9296283623edecf95441e310200a17b61efe80e3/clients/client-dynamodb/models/models_0.ts#L8314). We can use generic to make the pagiator configuration interface include the start token type.

Without this type, users will be confused if they have an existing `ExclusiveStartKey`, where should they use. Take https://github.com/aws/aws-sdk-js-v3/issues/1864#issuecomment-755643903 for example.

**Describe the solution you'd like**
[`PaginationConfiguration` interface](https://github.com/aws/aws-sdk-js-v3/blob/54e87151877dd5cf9a5f256698c088cc7a856225/packages/types/src/pagination.ts#L12-L16) can contain a generic like:
```typescript
export interface PaginationConfiguration<StartToken> {
  client: Client<any, any, any>;
  pageSize?: number;
  startingToken?: StartToken;
}
```

In individual paginator, the function signature can be:
```typescript
export interface DynamoDBPaginationConfiguration<StartToken> extends PaginationConfiguration<StartToken> {
  client: DynamoDB | DynamoDBClient;
}
export async function* paginateScan(
  config: DynamoDBPaginationConfiguration<ExclusiveStartKey>,
  input: ScanCommandInput,
  ...additionalArguments: any
): Paginator<ScanCommandOutput>
```

**Describe alternatives you've considered**

**Additional context**

/cc @alexforsyth

**Comment by alexforsyth** [comment]
+1
