### ISSUE TITLE
Pinpoint sendMessages for voice returning resource not found

### ISSUE THREAD

**Issue by march93** [aws/aws-sdk-js-v3#1889]
**Describe the bug**
Attempting to send a voice call through AWS Pinpoint client using the `sendMessages` command. I have tested with `PinpointSMSVoice.sendVoiceMessage` and it works, but this client returns resource not found. Sending SMS works with this client works, just not voice. I'm currently in production mode and not sandbox mode.

**Result**: `{"DeliveryStatus":"PERMANENT_FAILURE","StatusCode":404,"StatusMessage":"Resource not found"}`

**SDK version number**
^2.799.0, v3 also reported to have same behaviour

**Is the issue in the browser/Node.js/ReactNative?**
Node.js

**Details of the browser/Node.js/ReactNative version**
v12.19.0 (node -v)

**To Reproduce (observed behavior)**
`Pinpoint.SendMessagesRequest` defined as

```js
const requestObj: Pinpoint.SendMessagesRequest = {
    ApplicationId: 'project-id,
      MessageRequest: {
        Addresses: {
           ['destination-number']: {
              ChannelType: 'VOICE'
           }
        },
        MessageConfiguration: {
          VoiceMessage: {
             LanguageCode: 'en-US',
             OriginationNumber: 'origination-number',
             Substitutions: {
                 // for template
              }
           }
        },
        TemplateConfiguration: {
           VoiceTemplate: {
               Name: 'voice-template'
           }
        }
    }
};
```

**Method called**
```js
new Pinpoint().sendMessages(
    requestObj,
    (err: AWSError, data: Pinpoint.SendMessagesResponse) => {
       if (err) {}
       else {  // returns resource not found here  }
   }
);
```

**Expected behavior**
Should expect a 200 and successful voice call.

**Comment by ajredniwja** [comment]
Hey @march93, I was not able to reproduce this issue, using the V2 of the SDK, I used the example mentioned [here](https://docs.aws.amazon.com/code-samples/latest/catalog/code-catalog-javascript-example_code-pinpoint-sms-voice.html), can you try using the latest version of the SDK and see if the issue still persists?
