### ISSUE TITLE
SignatureDoesNotMatch error when S3 key contains *

### ISSUE THREAD

**Issue by TsvetanMilanov** [aws/aws-sdk-js-v3#1896]
**Describe the bug**
When trying to get/put object with key which contains `*` (e.g. `te*st`) the S3 client throws `SignatureDoesNotMatch` error.

**SDK version number**
3.2.0

**Is the issue in the browser/Node.js/ReactNative?**
Node.js

**Details of the browser/Node.js/ReactNative version**
v12.16.1

**To Reproduce (observed behavior)**
```JavaScript
const { S3 } = require("@aws-sdk/client-s3");

const s3 = new S3({ region: "us-east-1" });
await s3.putObject({ Bucket: "test-signature-sdk-v3", Key: "test*", Body: "test" });
```

**Expected behavior**
Expecting the method invocation to succeed, but it throws `SignatureDoesNotMatch` error.

**Additional context**
There is a similar issue https://github.com/aws/aws-sdk-js-v3/issues/283 and a related fix https://github.com/aws/aws-sdk-js-v3/pull/284. The S3 client works with `:` (e.g. `te:st`) but not with `*`. The aws-sdk v2 works correctly with key `te*st`

**Comment by ajredniwja** [comment]
Hey @TsvetanMilanov I was able to reproduce this issue, it is currently in our high priority list, the issue will be updated once it has been fixed.

**Comment by dobrynin** [comment]
Bump, can the suggest change be implemented?

**Comment by live680g** [comment]
This error is being exist.

**Comment by dobrynin** [comment]
`myString.replace("*", "%2A");` fixed for me.

**Comment by yenfryherrerafeliz** [comment]
Hi @TsvetanMilanov, @Dids, @dobrynin, @live680g, this issue has been fixed. Please update to the latest version of the SDK you should have not issues.

If you folks have anything else that we can help with, please feel free of opening a new issue.

Thanks!
