### ISSUE TITLE
How to use in a Lambda function deployed with aws-cdk?

### ISSUE THREAD

**Issue by daviddelusenet** [aws/aws-sdk-js-v3#1901]
I've a Lambda function containing the following line of code:

```ts
import { DynamoDB, ScanCommandOutput } from '@aws-sdk/client-dynamodb'
```

When I deploy this using `aws-cdk` I get the following error in my CloudWatch logs:

```
Error: Cannot find module '@aws-sdk/client-dynamodb'
```

How can I fix this? Please let me know if you need any more information.

**Comment by daviddelusenet** [comment]
Managed to fix it by using the latest version of `@aws-sdk/client-dynamodb` and adding it as a layer by following [this guide](https://aws.amazon.com/premiumsupport/knowledge-center/lambda-layer-aws-sdk-latest-version/).

Shouldn't it be mentioned in the v3 documentation somewhere that at the moment you need to do this if you want to use `aws-sdk-v3` in combination with lambda?

**Comment by ajredniwja** [comment]
Hey @daviddelusenet, thanks for opening this issue, I am glad you were able to resolve the issue and you are right, this should be incorporated in the readme, we will be workin on getting this added.

**Comment by codingnuclei** [comment]
@ajredniwja Is there any plans to add v3 to node lambdas by default. Like v2?

**Comment by juuyan** [comment]
hey @ajredniwja 
As @codingnuclei said, instead of documentation, I think this should be included in the node_modules for lambda by default, just like v2.

**Comment by ajredniwja** [comment]
I think the same that it should be used in Lambda by default, while that may take time according to priority of the feature I have some kind of Documentation that people can use.  

https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/using-lambda-functions.html

**Comment by kogratte** [comment]
Hello guys!

I'm writing some code using the latest sdk, and I'm not able to run it, for the same reasons exposed here. Despite the layer guide, I'm stucked by the size of the layer. Just for SQS Client, we're talking about a zip file about 90Mo, who'll be around 160Mo once unzipped. That's far too much for the allowed limits of a lambda.

I'm also using the LambdaClient, wich add another 150Mo. It seems it is not actually possible to use this SDK, and, sadly, it shouldn't. Typescript is the main reason to use it, and we're many, many to wait for it.

Is there somewhere a shared layer with the latest sdk? Can we imagine to exclude sdk layers from total lambda size?

**Comment by chrisjaimes** [comment]
Hi @daviddelusenet ! How were you able to include `@aws-sdk/client-dynamodb` as a Lambda layer? I am trying to upload the layer with Serverless framework but the layer exceeds the maximum size. I also tried to upload the zip file manually but still, the `@aws-sdk/client-dynamodb` package.zip is greater than 50MB

**Comment by loicmagne** [comment]
Almost 1 year later why does aws lambda nodejs environnement still comes with the v2 and not the v3 ? 🤷‍♂️

**Comment by kogratte** [comment]
To provide my collaborators a reason to be stucked with vanilla instead of fresh TS -_-

**Comment by ShivamJoker** [comment]
Still @awstools you guys have not included this

**Comment by RanVaknin** [comment]
Resolving since now the JS SDK v3 is available on lambda Node.js 18. [Blogpost](https://aws.amazon.com/blogs/compute/node-js-18-x-runtime-now-available-in-aws-lambda/)

Thanks,
Ran~
