### ISSUE TITLE
`formatUrl` Implementation Error

### ISSUE THREAD

**Issue by jonioni** [aws/aws-sdk-js-v3#1906]
**Describe the bug**
The `formatUrl` in `@aws-sdk/util-format-url` failed to take into account the `body` field of a `GET` request. This results in partial query string when `body` is `Action=...&Version=...` for a `GET` request.

The current implementation is consistent with the HTTP definition. However it is inconsistent with the `botocore` python sdk where the building of the url takes into account the `body` field of a request object (`botocore/awsrequest.py`). 

**SDK version number**
3.1.0

**Is the issue in the browser/Node.js/ReactNative?**
All.

**Details of the browser/Node.js/ReactNative version**
Irrelevant but `node v12.20.1`.

**To Reproduce (observed behavior)**
1. Use `@aws-sdk/util-create-request`'s `createRequest` to build a POST `HttpRequest`, e.g. `GetCallerIdentityCommand`.
2. Manually update the `Method` field of the `HttpRequest` to `GET`. Note there is `body` field built in the `HttpRequest`.
3. Call `formatUrl` on the modified `HttpRequest`.

**Expected behavior**
It'd be better for `formatUrl` to accommodate to non-ideal `HttpRequest` cases.

**Additional Notes**
Not necessarily a "bug". Just want to make sure whether it's preferred to let user manually handle the `body` field of `GET` request or to have `formatUrl` handling such cases.

**Comment by ajredniwja** [comment]
Hey @jonioni thanks for opening this issue, you are right that botocore takes `body` in account as well. As for this SDK, as you mentioned this is not necessarily a bug but more of a usage issue, it will be helpful for `formatUrl` to handle it. I would mark it as a feature request and see if this can be prioritized if we have more customer ask for it.
