### ISSUE TITLE
ARN fails for Lambda.InvokeCommand.FunctionName.  FunctionName works

### ISSUE THREAD

**Issue by danbosnichill** [aws/aws-sdk-js-v3#1910]
**Describe the bug**
When I use the Lambda ARN as the FunctionName, it fails.  The docs say I can use the ARN.

**SDK version number**
@aws-sdk/client-lambda-node
0.1.0-preview.2

**Is the issue in the browser/Node.js/ReactNative?**
Node.js

**Details of the browser/Node.js/ReactNative version**
This is running in AWS Lambda as Node.js 12.x.

**To Reproduce (observed behavior)**
I gave example Lambda code below.  If I swap out FunctionName, I can get this to switch between working and not working.

When I use`FunctionName: 'my-api'`, it works.

When I use`FunctionName: 'arn:aws:lambda:us-east-1:123456789:function:my-api'`, it fails.

**Expected behavior**
I'd either expect the documentation to say using ARN is not supported or for this to work.

**Additional context**

I filed this with AWS Support.  It's case 7840527081.  They told me to file here.

```JavaScript
const { LambdaClient } = require('@aws-sdk/client-lambda-node/LambdaClient');
const { InvokeCommand } = require('@aws-sdk/client-lambda-node/commands/InvokeCommand');
exports.handler = () => {
  const lambda = new LambdaClient({
    region: process.env.AWS_REGION,
  });
  const params = {
    FunctionName: 'my-api',
  };
  const invokeCommand = new InvokeCommand(params);
  lambda.send(invokeCommand).then(data => {
    console.log('worked')
  }).catch(error => {
    console.log('didnt work', error)
  })
}
```

**Comment by ajredniwja** [comment]
Hey @danbosnichill thanks for opening this issue, I see you are using a [deprecated client](https://www.npmjs.com/package/@aws-sdk/client-lambda-node). Can you please use the [updated version](https://www.npmjs.com/package/@aws-sdk/client-lambda) of the client, that should solve the issue. 

Please reach out if the problem still persists.
