### ISSUE TITLE
Document in client README that only CORS supported services run in the browser

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#1913]
**Describe the issue with documentation**
There are several CORS issues reported on GitHub https://github.com/aws/aws-sdk-js-v3/search?q=cors+is%3Aissue&type=Issues
It would be awesome if we call out in client README about CORS support is managed by services.

**Additional context**
Refs: https://github.com/aws/aws-sdk-js-v3/pull/1907#discussion_r556783749

**Comment by techthumb** [comment]
Hi,

Checking to understand if there will always be a CORS limitation.

Are there any workarounds that the team is considering?


Thanks
