### ISSUE TITLE
Can not pass PassThrough stream to send object

### ISSUE THREAD

**Issue by cojack** [aws/aws-sdk-js-v3#1920]
**Describe the bug**

There is no possibility to pass stream as type `PassThrough` to the Body. 

**3.3.0**

**Is the issue in the browser/Node.js/ReactNative?**
Node.js

**Details of the browser/Node.js/ReactNative version**
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`

 node -v = v15.5.1

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

This is not working:

```typescript
        const stream1 = createReadStream(__dirname+'/test.json');
        const stream2 = new PassThrough();
        stream1.pipe(stream2);

        type PutObjectParams = ConstructorParameters<typeof PutObjectCommand>[0];
        const params: PutObjectParams = { Bucket: this.configAws.s3.mediaBucket, Key: filePath, Body: stream2, Expires: expiresAt };
        await this.s3.send(new PutObjectCommand(params));
```

But this is working:

```typescript
        const stream1 = createReadStream(__dirname+'/test.json');

        type PutObjectParams = ConstructorParameters<typeof PutObjectCommand>[0];
        const params: PutObjectParams = { Bucket: this.configAws.s3.mediaBucket, Key: filePath, Body: stream1, Expires: expiresAt };
        await this.s3.send(new PutObjectCommand(params));
```

**Expected behavior**
I should be able to pass the stream object fe Duplex, Transform or PassThrough 

**Screenshots**
None

**Additional context**

```
/home/cojack/Projects/foo/bar/node_modules/@aws-sdk/client-s3/protocols/Aws_restXml.ts:9275
  return Promise.reject(Object.assign(new Error(message), response));
                                      ^
NotImplemented: A header you provided implies functionality that is not implemented
    at deserializeAws_restXmlPutObjectCommandError (/home/cojack/Projects/foo/bar/node_modules/@aws-sdk/client-s3/protocols/Aws_restXml.ts:9275:39)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at /home/cojack/Projects/foo/bar/node_modules/@aws-sdk/middleware-serde/src/deserializerMiddleware.ts:20:18
    at /home/cojack/Projects/foo/bar/node_modules/@aws-sdk/middleware-signing/src/middleware.ts:26:22
    at StandardRetryStrategy.retry (/home/cojack/Projects/foo/bar/node_modules/@aws-sdk/middleware-retry/src/defaultStrategy.ts:125:38)
    at /home/cojack/Projects/foo/bar/node_modules/@aws-sdk/middleware-logger/src/loggerMiddleware.ts:21:20
    at GeneratePackHandler.upload2s3 (/home/cojack/Projects/foo/bar/src/aws-packer/cqrs/generate-pack/generate-pack.handler.ts:90:9)
    at GeneratePackHandler.execute (/home/cojack/Projects/foo/bar/src/aws-packer/cqrs/generate-pack/generate-pack.handler.ts:44:26)
    at ContentPacksService.generatePack (/home/cojack/Projects/foo/bar/src/aws-packer/aws-packer.service.ts:22:9)
npm ERR! code 1
npm ERR! path /home/cojack/Projects/foo/bar
npm ERR! command failed
npm ERR! command sh -c ts-node -P ./tsconfig.build.json src/main.ts

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cojack/.npm/_logs/2021-01-15T16_43_59_897Z-debug.log
```

**Comment by tekizian** [comment]
Not entirely sure why this works or how helpful this is, but if you specify the content length, it works.

**Comment by monken** [comment]
You can pass a stream using the `@aws-sdk/lib-storage` package.

```js
import { S3Client } from '@aws-sdk/client-s3';
import { Upload } from '@aws-sdk/lib-storage';

const upload = new Upload({
    client: new S3Client({}),
    params: {
        Bucket: bucket,
        Key: 'test.txt',
        Body: stream,
        ContentType: 'text/plain',
    },
});

upload.done();
```

**Comment by cojack** [comment]
@monken works, thanks!

**Comment by ajredniwja** [comment]
Hey @cojack, would like to close this issue now, please reach out if you have any other questions.

**Comment by cojack** [comment]
@ajredniwja I don't think that this issue should be closed, because this is not anyhow described in docs, and sdk allows to pass Readable interface where PassThrough implements.

**Comment by alchemycs** [comment]
Hi @monken - can you confirm that `ContentType` is being honoured when you use `upload`?

If I use the put object command and a string for the body then S3 is showing a metadata user definition with the content type honoured as expected

However when I use a stream with `upload` S3 is showing a metadata system definition with `binary/octet-stream`.

Would be great to see if I have an aberration or if this is a bug.

**Comment by monken** [comment]
#1891 its a known issue

**Comment by alchemycs** [comment]
Thanks @monken, appreciate the quick response!

**Comment by Leithal3** [comment]
Hi @monken,

Do you know if there is an equivalent to `Upload` for streaming large file downloads from S3?

I've been looking through as much documentation as I can, but I am struggling to find any references.

**Comment by monken** [comment]
The `GetObjectCommand` will now return a Readable stream instead of a Buffer (v2).

```js
const obj = s3.send(new GetObjectCommand({ Bucket: 'test', Key: 'test' }));

for await (const chunk of obj.Body) {
  console.log(chunk);
}

// or

obj.Body.pipe(process.stdout);
```

**Comment by Leithal3** [comment]
Thank you @monken, I appreciate the quick response

**Comment by mauricedoepke** [comment]
@ajredniwja

I think adding the bug label again would be appropriate.
The solution from monken might work, but feels like a hacky work around that does not solve the initial problem.

**Comment by warlockdn** [comment]
Any new development updates on this ?

**Comment by yousefamar** [comment]
FYI, in my case, the error "NotImplemented: A header you provided implies functionality that is not implemented" is referring to the header "Transfer-Encoding", as [apparently S3 doesn't support chunked](https://github.com/aws/aws-sdk-go/issues/3063#issuecomment-571279246)? So you need to know the Content-Length beforehand, which means you can't use streams?

**Comment by yousefamar** [comment]
Nevermind, it does work with @monken's approach after all, no extra headers needed except Content-Type!

**Comment by amitlevy21** [comment]
In my case, I cannot use @monken approach since I don't know the content type, it's dynamic at runtime. There is no way to know the content size from a stream as well (the whole purpose of streams).

Please fix this, it works for SDK v2, but not on v3

**Comment by RobvH** [comment]
I think there may be confusion here between ReadableStream (whatwg streams api) and NodeJS.ReadableStream.  These two, despite having the same names, are not interface compatible.

Oddly, the PutObjectRequest.Body typing says it's `Readable | ReadableStream | Blob`. `Readable` is an internal class that implements `NodeJS.ReadableStream` and the second type is `ReadableStream`, which without any qualifier is going to resolve (in Typescript) to the WHATWG api. I don't know if this is a mistake in `client-s3/dist-types` and it's intended to receive a NodeJS.ReadableStream, but it is not marked that way.

**Comment by kuhe** [comment]
At this point you can use `Upload` with `Passthrough` without specifying content length, so I think it could be helpful to add a warning if `putObject` is being used with a stream of unknown length to redirect there.  https://github.com/aws/aws-sdk-js-v3/pull/3571

Modifying the type description for `Readable | ReadalbeStream | Blob` is a larger matter, since that would affect all interfaces using the AWS Blob type.
