### ISSUE TITLE
Add support for Greengrass v2

### ISSUE THREAD

**Issue by jimfleming** [aws/aws-sdk-js-v3#1923]
**Is your feature request related to a problem? Please describe.**
The current `@aws-sdk/client-greengrass` only supports Greengrass v1 (it appears).

**Describe the solution you'd like**
Support for Greengrass v2, as in the v2 JS SDK, would be much appreciated: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/GreengrassV2.html

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by trivikr** [comment]
This happens as smithy models were last updated on 12/12/2020 in https://github.com/aws/aws-sdk-js-v3/pull/1774.

The updates haven't been regular in the past, as we're internally verifying our setup for models generation. We plan to verify and update regularly in future before switching to daily releases.

The client-greengrassv2 is added in new model update https://github.com/aws/aws-sdk-js-v3/pull/2258
