### ISSUE TITLE
issue passing credentials with accesskey and secretkey

### ISSUE THREAD

**Issue by jhylton** [aws/aws-sdk-js-v3#1927]
**Describe the bug**
Unable to pass accesskey and secretkey for the API:
var client = new EC2({ accessKeyId: "AKIA......", secretAccessKey: ".......", region: 'eu-west-1' });

if I have credentials saved in .aws/credentials file, the sdk continually tries to pull credentials from this file. If i remove this file, i get a time out error

**SDK version number**
3.3.0

**Is the issue in the browser/Node.js/ReactNative?**
Node.js

**Details of the browser/Node.js/ReactNative version**
node v12.16.1

**To Reproduce (observed behavior)**
try to pass credentials:
{ accessKeyId: "AKIA......", secretAccessKey: ".......", region: 'eu-west-1' }

**Expected behavior**
should work as it does in V2 of the SDK

**Screenshots**

**Additional context**

**Comment by ajredniwja** [comment]
Hey @jhylton thanks for opening this issue, the correct way to do this in V3 would be something like:

```JavaScript
const credentials = {
    accessKeyId: 'xyz', secretAccessKey: 'abc'
}
const client = new EC2Client({region: 'us-west-2', credentials : credentials});
```

Closing this issue now, please reach out if that doesn't work for you or if you have any other questions.
