### ISSUE TITLE
Usability with _AttributeValue type

### ISSUE THREAD

**Issue by timsuchanek** [aws/aws-sdk-js-v3#193]
In the old v2 api, I could do something like this:
```js
    client.get({ TableName, Key: { id } }, (err, data) => {
      if (err) {
        reject(err)
      } else {
        resolve(data.Item as any)
      }
    })
```

Now I have to do the following:
```js
    const get = new GetItemCommand({ TableName, Key: { id: {S: id} } })
    client.send(get, (err, data) => {
      if (err) {
        reject(err)
      } else {
        resolve(data.Item as any)
      }
    })
```

Is the `S: id` really necessary? That would mean I have to convert all my objects.
Am I incorrectly calling a too low level API?
This seems way more complicated than it should be.

I got it from here: https://github.com/aws/aws-sdk-js-v3/tree/master/packages/client-dynamodb-v2-node

**Comment by AllanFly120** [comment]
Hey @timsuchanek 

This is a very valid feature request! The [DDB client](https://github.com/aws/aws-sdk-js-v3/tree/master/packages/client-dynamodb-v2-node) you referred to is equivalent to the [low level client in v2](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html). The usage of the v2 SDK in your code snippet is from [DDB document client](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html), which wraps the low level DDB client and applies automatic convertion to your parameters. The equivalent to that class in V3 hasn't been rolled out yet but it's already on our road map. So stay tuned!

**Comment by lukehedger** [comment]
@AllanFly120 Has this feature been implemented now?

**Comment by farski** [comment]
@AllanZhengYP This will be a major blocker in moving to the new SDK for any existing DDB code. Given that this is no longer a high priority, and [hasn't made it](https://github.com/aws/aws-sdk-js-v3/issues/1102#issuecomment-620897771) into version 1, is the any guidance on the best way to handle the gap? Is it safe/advisable to use the v2 Converter?

**Comment by trivikr** [comment]
@farski @lukehedger In v3, we have exposed utility functions to operate with JavaScript objects in [@aws-sdk/util-dynamodb](https://www.npmjs.com/package/@aws-sdk/util-dynamodb). You can refer our [Developer Guide on using DynamoDB utilities](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/dynamodb-example-dynamodb-utilities.html).

**Comment by farski** [comment]
@trivikr Perfect, thank you!
