### ISSUE TITLE
[@aws-sdk/client-sqs] port and other endpoint attributes seem to be missing in V3

### ISSUE THREAD

**Issue by jennyEckstein** [aws/aws-sdk-js-v3#1930]
**Describe the bug**
My application uses endpoint property when creating SQSClient instance. When request reaches server, port seems to be stripped off the request.

**SDK version number**
Tested using: @aws-sdk/client-sqs 3.3.0

**Is the issue in the browser/Node.js/ReactNative?**
Tested in Node.js 14

**Details of the browser/Node.js/ReactNative version**
n/a

**To Reproduce (observed behavior)**
I build a small [repo](https://github.com/jennyEckstein/aws-sdk-v2-v3-test) to reproduce this issue.
1. Clone repo.
2. Run `npm ci`
3. Run `node v2.js` --> observe output in console --> kill server with Command/Ctrl +C
4. Run `node v3.js` --> observe output in console --> kill server with Command/Ctrl +C
Screenshot shows the result of the above experiment. As you can see, port is missing in V3. 

**Expected behavior**
Port should be available in the HTTP Request.

**Screenshots**
<img width="471" alt="Screen Shot 2021-01-19 at 4 58 48 PM" src="https://user-images.githubusercontent.com/7528575/105099549-da016800-5a79-11eb-97f0-6b20012ec5b5.png">

**Additional context**
This issue seems to be related to [this issue](https://github.com/aws/aws-sdk-js-v3/issues/1399)

**Comment by ajredniwja** [comment]
Hey @jennyEckstein thanks for opening this issue, I was able to reproduce the issue and I believe that investigation posted in https://github.com/aws/aws-sdk-js-v3/issues/1399 holds true for this case as well, the path is generated by the service model and to override it we would need to add a middelware, I see it is already in the TODO list, I can update here once that has been done which should resolve the issue.

**Comment by jennyEckstein** [comment]
> Hey @jennyEckstein thanks for opening this issue, I was able to reproduce the issue and I believe that investigation posted in #1399 holds true for this case as well, the path is generated by the service model and to override it we would need to add a middelware, I see it is already in the TODO list, I can update here once that has been done which should resolve the issue.
> 
> Something similar for the port, I mean.
