### ISSUE TITLE
Pre-signed URL is invalid briefly after generation

### ISSUE THREAD

**Issue by olokobayusuf** [aws/aws-sdk-js-v3#1946]
**Describe the bug**
I've stumbled upon a very weird error. After going through the motions on #1857, I'm running into an issue where a pre-signed URL generated by the SDK is invalid when it is generated. After a short period of time, it becomes valid. This is a blocker, because the amount of time before the URL becomes valid seems to be non-deterministic, and the links are being immediately sent to microservices so they are always invalid when they arrive.

I should note that the pre-signed URL is valid for 2 hours.

**SDK version number**
```json
{
  "@aws-sdk/client-s3": "^3.2.0",
  "@aws-sdk/s3-request-presigner": "^3.2.0",
}
```

**Is the issue in the browser/Node.js/ReactNative?**
Node JS

**Details of the browser/Node.js/ReactNative version**
v12.4.0

**To Reproduce (observed behavior)**
1. Generate pre-signed URL for an image on S3
2. Immediately try to open it in Python with Pillow:
```python
url = ...
image = Image.open(BytesIO(get(url).content))
```
3. OR: Simply open the link in your browser.
4. Observe the signature AWS Access Denied XML page:
```xml
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>CA8029A6C93C4CD5</RequestId>
  <HostId>j1EXY04v1UX9VMi87VBevOsfuLCcJMCIBbpbjt+/FOkm60eoMqS0HzVsssBE9XO1K7ya2nmd/9Y=</HostId>
</Error>
```
5. Wait up to a minute.
6. Retry step (2) or (3), observe that it now works.

**Expected behavior**
Pre-signed URL should work immediately after being generated.

**Screenshots**
None.

**Additional context**

**Comment by ajredniwja** [comment]
Hey @olokobayusuf thanks for opening this issue, unfortunately I wasn't able to reproduce the issue. I followed some steps found [here](https://aws.amazon.com/blogs/developer/generate-presigned-url-modular-aws-sdk-javascript/). 

Is there anything you might be doing differently?

**Comment by olokobayusuf** [comment]
Hey @ajredniwja , I haven't worked on this in quite a while, so I'll close this issue for now. If it comes up again, I'll open a new issue.
