### ISSUE TITLE
ChangeResourceRecordSetsCommand AliasTarget

### ISSUE THREAD

**Issue by vokeio** [aws/aws-sdk-js-v3#1957]
**Describe the issue with documentation**
Missing AliasTarget definitions. 

**To Reproduce (observed behavior)**
Original: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Route53.html#changeResourceRecordSets-property
New: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-route-53/modules/resourcerecordset.html#aliastarget

**Expected behavior**
Expected more info for the AliasTarget and the accepted properties.

**Additional context**
Its also not clear in the previous aws docs but when creating an Alias to cloudfront distribution you have to use the exact HostedZoneId `Z2FDTNDATAQYW2` making this more clear could help other.

**Comment by phuhl** [comment]
Same information for S3 hosted websites might be useful, especially this link: https://docs.aws.amazon.com/general/latest/gr/s3.html#s3_website_region_endpoints
