### ISSUE TITLE
Kinesis video signaling GetIceServerConfigCommand blocked by CORS policy

### ISSUE THREAD

**Issue by pdcarroll** [aws/aws-sdk-js-v3#1962]
**Describe the bug**
Kinesis video signaling client `GetIceServerConfigCommand` http request blocked by CORS policy

**SDK version number**
3.3.0

**Is the issue in the browser/Node.js/ReactNative?**
Browser

**Details of the browser/Node.js/ReactNative version**
"Request header field amz-sdk-invocation-id is not allowed by Access-Control-Allow-Headers in preflight response."

**To Reproduce (observed behavior)**
Send `GetIceServerConfigCommand` from `KinesisVideoSignalingClient` in Chrome browser.

**Expected behavior**
Request should succeed.

**Comment by atyshka** [comment]
Getting this issue as well, any fixes in the works? It looks like this was mentioned in #1376 but was never resolved.

**Comment by atyshka** [comment]
#1789 solved this for other services but KVS was not included. @AllanZhengYP I see KVS was mentioned in #1376 but was perhaps forgotten when implementing the fix

**Comment by pdcarroll** [comment]
@atyshka I opened a PR to address this: #1963

**Comment by trivikr** [comment]
Reopening as call to `get-ice-server-config` supports retry headers as per CORS URL in [cors-test](https://github.com/AllanZhengYP/cors-test/blob/master/output.md)

```console
$ curl --insecure -i -X OPTIONS https://kinesisvideo.us-east-1.amazonaws.com/v1/get-ice-server-config -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36" -H "Origin: https://foo.example" -H "Access-Control-Request-Method: POST" -H "Access-Control-Request-Headers: content-type,content-length,host,x-amz-user-agent,user-agent,Authorization,amz-sdk-invocation-id,amz-sdk-request,x-amz-security-token" -H "host: kinesisvideo.us-east-1.amazonaws.com"

HTTP/1.1 200 OK
x-amzn-RequestId: 1ccc9c64-9c4d-4077-823d-234a33c155b8
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: content-type,content-length,host,x-amz-user-agent,user-agent,Authorization,amz-sdk-invocation-id,amz-sdk-request,x-amz-security-token
Access-Control-Allow-Methods: POST
Access-Control-Expose-Headers: x-amzn-RequestId,x-amzn-ErrorType,x-amzn-ErrorMessage,Date
Access-Control-Max-Age: 172800
Content-Length: 0
Date: Tue, 16 Feb 2021 21:50:05 GMT
```

@pdcarroll Do you have a minimal repro code to reproduce this issue with `@aws-sdk/client-kinesis-video-signaling@3.5.0`?

**Comment by pdcarroll** [comment]
@trivikr Here's minimal code that should re-pro:

```javascript
import {
    GetIceServerConfigCommand,
    KinesisVideoSignalingClient
} from "@aws-sdk/client-kinesis-video-signaling";
  
const region = "us-west-2";
const channelARN = "<REPLACE>";
const endpoint = "<REPLACE>";
const credentials = {
    accessKeyId: "<REPLACE>",
    secretAccessKey: "<REPLACE>"
};

const kinesisVideoSignalingChannelsClient = new KinesisVideoSignalingClient({
  region,
  credentials,
  endpoint
});

const getIceServerConfigCommand = new GetIceServerConfigCommand({
  ChannelARN: channelARN
});

// This operation is blocked by CORS policy
const sigChannelResponse = kinesisVideoSignalingChannelsClient
  .send(getIceServerConfigCommand);
```
