### ISSUE TITLE
Cannot find module '@aws-sdk/config-resolver' ( using in lambda layer )

### ISSUE THREAD

**Issue by juuyan** [aws/aws-sdk-js-v3#1970]
## Describe the bug
Get error `Cannot find module '@aws-sdk/config-resolver' ` when using it in lambda layer

## Your environment
"@aws-sdk/client-sesv2": "^3.3.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
nodejs12.x

## Steps to reproduce
- Install `@aws-sdk/client-sesv2` locally
- Zip it and use it as the layer for any lambda function
- Let lambda call it
- Call the lambda through API gateway
- Check the response 

#### Observed behavior
```
{"error":"Cannot find module '@aws-sdk/config-resolver'\nRequire stack:\n- /opt/nodejs/node_modules/@aws-sdk/client-sesv2/dist/cjs/runtimeConfig.js\n- /opt/nodejs/node_modules/@aws-sdk/client-sesv2/dist/cjs/SESv2Client.js\n- /opt/nodejs/node_modules/@aws-sdk/client-sesv2/dist/cjs/index.js\n- /var/task/__index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js"}%    
```

#### Expected behavior
There should be no error.

#### Screenshots
File structure inside the zip:
![image](https://user-images.githubusercontent.com/48427014/106088576-33942180-6161-11eb-861a-421c8c221e83.png)

**Comment by juuyan** [comment]
Sorry it is not a bug.

**Comment by trivikr** [comment]
@juuyan What was the issue?

**Comment by juuyan** [comment]
@trivikr srr it was caused by a very stupid mistake in my code. 😅
