### ISSUE TITLE
Lex v2 updating with new APIs getting below error

### ISSUE THREAD

**Issue by vishalmarakana** [aws/aws-sdk-js-v3#1971]
## Describe the bug
I'm using the following SDK for lex v2, to send the message I'm using `recognizeText` but I'm receiving the fowling error:
{"Message":"User: arn:aws:sts::xxxxxxxxxx:assumed-role/Cognito_XXXXXChatbotPoolUnauth_Role/CognitoIdentityCredentials is not authorized to perform: lex:RecognizeText on resource: arn:aws:lex:us-east-1:xxxxxxxx:bot-alias/xxxxxxxxx/xxxxxxxx"}

I'm also trying to add new permissing role for `recognizeText` but i can't find it in actions list: 
<img width="891" alt="Screenshot 2021-01-28 at 12 04 12 PM" src="https://user-images.githubusercontent.com/38314221/106099723-28d98c80-6161-11eb-9bad-4e5320fe3d72.png">

#### SDK version number
`@aws-sdk@2.831.0`

#### Issue
{"Message":"User: arn:aws:sts::XXXXXXXX:assumed-role/Cognito_XXXXXChatbotPoolUnauth_Role/CognitoIdentityCredentials is not authorized to perform: lex:RecognizeText on resource: arn:aws:lex:us-east-1:XXXXXXXXX:bot-alias/XXXXXXXXX/TSTALIASID"}

Even I'm not able to find `recognizeText` action in the lex documentation(Service Authorization Reference
Feedback 
): https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonlex.html#amazonlex-actions-as-permissions

**Comment by trivikr** [comment]
@vishalmarakana what was the issue?

**Comment by vishalmarakana** [comment]
> @vishalmarakana what was the issue?

Thanks for your time.

Actually, the issue is for SDK v2: https://github.com/aws/aws-sdk-js/issues/3612
