### ISSUE TITLE
Upload constructor in @aws-sdk/lib-storage appears to be broken

### ISSUE THREAD

**Issue by ffxsam** [aws/aws-sdk-js-v3#1973]
## Describe the bug
Using `new Upload()` from `@aws-sdk/lib-storage` throws an error of "Invalid client type" when passed a valid S3 instance. This only happens when `@aws-sdk/client-s3` is also installed.

#### SDK version number
`@aws-sdk/lib-storage@3.4.0
`@aws-sdk/client-s3@3.4.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v12.20.1

## Steps to reproduce
```js
import { S3 } from '@aws-sdk/client-s3';

// ...

const upload = new Upload({
  client: new S3({}),
  params: {
    Bucket: process.env.STORAGE_BUCKET,
    Key: zipFileKey,
    Body: readableStream,
  },
});
```

#### Observed behavior
An error is thrown: "Invalid client type"

#### Expected behavior
I would expect it to not throw an error.

**Comment by ffxsam** [comment]
Ok, I discovered `@aws-sdk/lib-storage`. However, there's a bug. My code is below:

```js
    console.log('this is true:', s3 instanceof S3);
    const upload = new Upload({
      client: s3,
      params: {
        Bucket: process.env.DEST_BUCKET,
        Key: `${destPrefix}snippet.mp3`,
        Body: ffmpegProc.stdout,
      },
    });
```
So `s3` is definitely an instance of `S3`, and yet I get this error:
```
{
    "errorMessage": "Invalid client type"
}
```

**Comment by schantaraud** [comment]
You may want to uninstall your local version of `@aws-sdk/client-s3` and let `@aws-sdk/lib-storage` install it as a dependency.

**Comment by ffxsam** [comment]
VERY odd. It suddenly works, with no changes on my end. It's possible a package update fixed something.

**Comment by ffxsam** [comment]
I ran into this issue again. Uninstalling the `@aws-sdk/client-s3` package fixed it, but that's a weird solution. These packages shouldn't cause conflicts like that when they're both installed.

@trivikr @AllanZhengYP

**Comment by trivikr** [comment]
@ffxsan Please update the description of this issue with [bug report](https://github.com/aws/aws-sdk-js-v3/blob/master/.github/ISSUE_TEMPLATE/---bug-report.md) template so that it's easy to triage and debug.

**Comment by ffxsam** [comment]
@trivikr Done!

**Comment by alexforsyth** [comment]
This is not a great experience at all. This PR should fix this issue: https://github.com/aws/aws-sdk-js-v3/pull/2039

**Comment by ffxsam** [comment]
@alexforsyth Thanks, you rock! 🤘
