### ISSUE TITLE
Unmarshalling small numbers gives unexpected errors

### ISSUE THREAD

**Issue by leocurrie** [aws/aws-sdk-js-v3#1983]
## Describe the bug
When unmarshalling very small numbers like `0.0000001` from a DynamoDB table,  an unexpected Error is thrown.

#### SDK version number
`@aws-sdk/util-dynamodb@3.4.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Node.js version v12.20.1

## Steps to reproduce

- Start with an object containing javascript Number, e.g. `{score: 0.0000001}`
- Marshall this object using `util-dynamodb`, then store in a DynamoDB table using `client-dynamodb`
- Retrieve the record from the table and umarshall it

#### Observed behavior
When attempting to unmarshall the record, an Error is thrown with the following message:
`UnhandledPromiseRejectionWarning: Error: Value 0.0000001 is outside IEEE 754 Floating-Point Arithmetic. Set options.wrapNumbers to get string value.`

#### Expected behavior
The unmarshalling should complete without error.

#### Sample code
Hopefully this code illustrates the issue:

```typescript
import { DynamoDB } from '@aws-sdk/client-dynamodb';
import { marshall, unmarshall } from '@aws-sdk/util-dynamodb';

async function doTest(): Promise<void> {
  const tableName = 'my-table';
  const client = new DynamoDB({ region: 'eu-west-1' });
  const data = {
    Id: 'test-id',
    Timestamp: Date.now(),
    data: { score: 0.0000001 }
  };

  await client.putItem({
    TableName: tableName,
    Item: marshall(data)
  });

  const record = await client.query({
    TableName: tableName,
    KeyConditionExpression: 'Id = :id',
    ExpressionAttributeValues: marshall({
      ':id': 'test-id'
    })
  });

  unmarshall(record.Items[0]);
}

void doTest();
```

**Comment by trivikr** [comment]
This happens because DynamoDB stores [numbers as strings](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_AttributeValue.html#DDB-Type-AttributeValue-N), and the string numerical value of `"0.0000001"` is `1e-7`:
```console
$ node
Welcome to Node.js v12.20.1.
Type ".help" for more information.
> const numValue = 0.0000001;
undefined
> const strValue = numValue.toString();
undefined
> Number(strValue)
1e-7
```

Relevant code: https://github.com/aws/aws-sdk-js-v3/blob/cd50eeb5ddcfd69fe2d9586045e2078723fd9ea4/packages/util-dynamodb/src/convertToNative.ts#L57-L61

**Comment by trivikr** [comment]
I couldn't find any other easy way to detect string values for numbers which are outside IEEE 754 Floating-Point Arithmetic.

A third-party dependency like [big.js](https://github.com/MikeMcl/big.js) or [decimal.js](https://github.com/MikeMcl/decimal.js) will increase bundle size.
We would be removing the check for `num.toString() !== numString` to fix this bug.
