### ISSUE TITLE
apiVersion autocomplete info

### ISSUE THREAD

**Issue by ffxsam** [aws/aws-sdk-js-v3#1986]
### Is your feature request related to a problem? Please describe.
It's time-consuming to have to go look up the API version anytime I use one of the libraries.

### Describe the solution you'd like
It would be nice if the API versions were baked into the types file, as with the JS SDK v2:

<img width="584" alt="image" src="https://user-images.githubusercontent.com/12532733/106367966-0637a700-630c-11eb-9de7-1935e0f9e2d8.png">

**Comment by trivikr** [comment]
The API version is set internally by the SDK, and is not planned to be used by customer code.
Added documentation in https://github.com/aws/aws-sdk-js-v3/pull/2019

**Comment by ffxsam** [comment]
@trivikr I thought setting the API version was recommended, so that if the API changes, it doesn't introduce breaking changes into our apps.

**Comment by ffxsam** [comment]
In other words, breaking changes in the API will be reflected in the JS SDK via major version changes?

**Comment by trivikr** [comment]
Nope, the breaking changes in the API will be reflected in the JS SDK client on the day service would release new API, once we switch to daily releases. This happens across other language SDKs.

**Comment by ffxsam** [comment]
Ah - even better! Thank you. 😁
