### ISSUE TITLE
Migration guide

### ISSUE THREAD

**Issue by daveisfera** [aws/aws-sdk-js-v3#1989]
## Describe the issue with documentation
It would be very helpful to have Information on how to migrate from V2 module to this new V3 module. For example, simple uses like downloading or uploading a file from S3. With the V2 module, is was a simple call (like `upload()`), but appears to now be far more involved, so having examples on how to do this and a migration guide with example of V2 code and the corresponding V3 could would help users adopt this new module.

**Comment by brmur** [comment]
@daveisfera Thanks for you feedback. Have you seen these resources:
- [V3 examples of S3 basic operations](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/s3-example-creating-buckets.html)
- [Migration guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/migrating-to-v3.html)

**Comment by daveisfera** [comment]
The examples are probably what I'm looking for (even though it seems that use of the V3 module is a LOT more complex than the V2 one), but I'm not seeing what the migration guide is showing. Basically, I don't see examples of using the old V2 module to do actions like download or upload a file and then the corresponding code for the V3 module.

**Comment by mattvb91** [comment]
Have to agree with @daveisfera was looking to use v3 for the smaller lib size but it looks like its nowhere near as easy to quickly hook in as v2 if your planning on upgrading an existing project.

**Comment by brmur** [comment]
@daveisfera The [welcome.html](Welcome) page in the dev guide for V3 goes through the basics differences between writing basic functions for V2 and V3.

**Comment by daveisfera** [comment]
Yes, but the code in the `Comparing code size` section is a perfect example. How is someone supposed to know that the old call to `ddb.listTables` needs to be replaced by a call to `dbclient.send(new ListTablesCommand)` and then calling `results.Tables.forEach` on that result?
Basically, the V3 API appears to be quite a bit more complex and there doesn't appear to be a magic decoder ring anywhere to figure out how to use it.

**Comment by brmur** [comment]
@daveisfera Yes, there are some some significant changes in V3, and to reflect best practices the examples for V3 use the async/await pattern and the ```client.command(parameters) syntax```. But you can still take advantage of V3 modularity and use V2 coding style such as 
```
function run(){
         s3.createBucket(bucketParams, function(err, data) {
         if (err) {
         console.log("Error", err);
         } else {
         console.log("Success", data.Location);
         }
    })
```
See the ```Using V2 commands``` [V3 Dev. Guide Welcome page](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/welcome.html).

**Comment by daveisfera** [comment]
That sounds great, but `s3.upload()` fails because it's not a defined function, so how do users know what's valid for a "V2 coding style" and what's not?
