### ISSUE TITLE
Reduce size of install

### ISSUE THREAD

**Issue by jimfleming** [aws/aws-sdk-js-v3#1994]
### Is your feature request related to a problem? Please describe.
A clean install of just two v3 SDK dependencies generates a 200MB node_modules folder.
<img width="1440" alt="Screen Shot 2021-02-02 at 10 50 41 AM" src="https://user-images.githubusercontent.com/226553/106648000-81839d80-6544-11eb-87ee-d20255159f76.png">

Minimal package.json:

```
{
  "dependencies": {
    "@aws-sdk/client-dynamodb": "^3.4.1",
    "@aws-sdk/util-dynamodb": "^3.4.1"
  }
}
```

Run `npm install`.

### Describe the solution you'd like
Much smaller builds for lambdas. As is, we're just under the 250MB S3 upload limit for lambdas.

### Additional context
Screenshot attached of the size breakdown from `dust`. It looks like the bulk of the install is coming from react-native and android.

**Comment by willfarrell** [comment]
This is related to https://github.com/aws/aws-sdk-js-v3/issues/1536

**Comment by jimfleming** [comment]
As [this comment in #1536](1536#issuecomment-772088826) noted the issue appears to be cause by upgrading to npm@7.

To revert back to the npm@6 behavior we can use: `npm install --legacy-peer-deps`. This requires first deleting the package-lock.json and node_modules as it won't remove peer dependencies that were already installed.

Alternatively, we can explicitly omit peer dependencies: `npm install --omit peer` which will remove existing peer dependencies.

The long-term fix sounds like the peer dependencies should be marked as optional.

**Comment by trivikr** [comment]
Closing this issue, as the specific problem of react-native getting installed was fixed by asking customers to install react-native polyfills in https://github.com/aws/aws-sdk-js-v3/pull/2191

Reducing the install size further is being tracked in https://github.com/aws/aws-sdk-js-v3/issues/2132

**Comment by trivikr** [comment]
Tagging @jimfleming @willfarrell as you had pointed out about install size of v3 in the past.

The AWS SDK for JavaScript team is working on reducing the install size of v3 further.
Please test or create issues on our experimental repo if you have questions/suggestions https://github.com/trivikr/temp-client-s3
