### ISSUE TITLE
Why required region in IAM Client? 

### ISSUE THREAD

**Issue by Nevation** [aws/aws-sdk-js-v3#1995]
## Describe the bug

```javascript
async function iam_summary_test() {
    const iam = new IAMClient({ credentials: makeCredentials() })
    const command = new GetAccountAuthorizationDetailsCommand({});
    const data = await iam.send(command);

    return data
}
```

In aws-sdk v2, the IAM region was not required, but in v3, an error occurs "**Error: Region is missing**" if there is no region.

So I think it's a bug, and I ask for a fix.

## Your environment
@aws-sdk/client-iam@^3.4.1

#### Is the issue in the browser/Node.js/ReactNative?
Node.js 

#### Details of the browser/Node.js/ReactNative version
v12.18.2

#### Expected behavior
execute source code

#### Screenshots

![image](https://user-images.githubusercontent.com/52541784/106687248-1eab0880-660f-11eb-8604-2c1709255354.png)

**Comment by AllanZhengYP** [comment]
Hi @Nevation Thank you for bringing this up! You are right, region is not required for IAM service. Right now all services will throw [if region is not provided](https://github.com/aws/aws-sdk-js-v3/blob/d1c548ede2abe62adbdd11d207500a2eeb96dde0/packages/config-resolver/src/RegionConfig.ts#L10-L12). We will add another region provider specifically for global services like **IAM, Route53, ImportExport, WAF, Budgets, Chime, Cloudfront services**

**Comment by windy1** [comment]
Encountered this when trying to migrate from v2, bumping for visibility.
