### ISSUE TITLE
Improved accessibility to DynamoDB

### ISSUE THREAD

**Issue by monster-x-adventurer** [aws/aws-sdk-js-v3#1996]
Good morning. I am the author of the [@typemon/dynamon](https://www.npmjs.com/package/@typemon/dynamon) package, and I love the JavaScript ecosystem and AWS.

Many people using DynamoDB seem to be struggling with the lack of support for `DocumentClient` in version 3.

I want many people to have easy access to DynamoDB, and I developed the package with that in mind.

I suggest you mark the [@typemon/dynamon](https://www.npmjs.com/package/@typemon/dynamon) package as a recommended package in the README of the [@aws-sdk/client-dynamodb](https://www.npmjs.com/package/@aws-sdk/client-dynamodb) package.

> It was written using Google Translator, so please understand it even if the meaning is a bit strange.

**Comment by trivikr** [comment]
Thank you @monster-x-adventurer for creating `@typemon/dynamon`.
We do not add official recommendations for community supported packages, as they may not work in all use cases, may not have security reviewed and other reasons.

Would you like to add `@typemon/dynamon` under "Related repos" in community maintained awesome-aws list?
https://github.com/donnemartin/awesome-aws#javascript-sdk

**Comment by monster-x-adventurer** [comment]
Thank you. I'll do that.
