### ISSUE TITLE
Profile ############# requires a role to be assumed, but no role assumption callback was provided.

### ISSUE THREAD

**Issue by edpega** [aws/aws-sdk-js-v3#1998]
Confirm by changing [ ] to [x] below:
- [ X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

Profile selection causes error:
Error Error: Profile ############# requires a role to be assumed, but no role assumption callback was provided.

Code snippet:
const express = require('express')
const app = express()
const port = 8082
const exec = require("child_process").exec
const {
  AppStreamClient
} = require("@aws-sdk/client-appstream-node");
 
const {fromIni} = require("@aws-sdk/credential-provider-ini");
const appStream = new AppStreamClient({
   credentials: fromIni({profile: '#############'}),
   region: 'us-east-1'});
 
 
app.get('/test', (req,res) => {
   var params = { Names: ['as-stack-1']};
   const run = async() => {
      try {
         const data = await appStream.send(new describeStacksCommand(params));
         res.header("Content-Type","application/json");
         res.status(200).send(data);
      } catch (err) {
         console.log("Error", err);
      }
   }
   run();
 
});
 
app.listen(port, () => {
   console.log('Server running at http://127.0.0.1:' + port +'/');
})

**Comment by ajredniwja** [comment]
Hey @edpega thanks for opening this issue. Is it possible to to switch to the correct package i.e https://www.npmjs.com/package/@aws-sdk/client-appstream

**Comment by edpega** [comment]
Issue remains with new package:

npm install @aws-sdk/client-appstream


Code snippet:
const express = require('express')
const app = express()
const port = 8082
const exec = require("child_process").exec
const {
AppStreamClient
} = require("@aws-sdk/client-appstream");

const {fromIni} = require("@aws-sdk/credential-provider-ini");
const appStream = new AppStreamClient({
credentials: fromIni({profile: '#############'}),
region: 'us-east-1'});

app.get('/test', (req,res) => {
var params = { Names: ['as-stack-1']};
const run = async() => {
try {
const data = await appStream.send(new describeStacksCommand(params));
res.header("Content-Type","application/json");
res.status(200).send(data);
} catch (err) {
console.log("Error", err);
}
}
run();

});

app.listen(port, () => {
console.log('Server running at http://127.0.0.1:' + port +'/');
})




Error Error: Profile XXXXXXXXXXXX requires a role to be assumed, but no role assumption callback was provided.
    at new ProviderError (/scripts/appstream/node_modules/@aws-sdk/property-provider/build/ProviderError.js:17:28)
    at /scripts/appstream/node_modules/@aws-sdk/credential-provider-ini/build/index.js:58:31
    at step (/scripts/appstream/node_modules/tslib/tslib.js:141:27)
    at Object.next (/scripts/appstream/node_modules/tslib/tslib.js:122:57)
    at /scripts/appstream/node_modules/tslib/tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/scripts/appstream/node_modules/tslib/tslib.js:111:16)
    at resolveProfileData (/scripts/appstream/node_modules/@aws-sdk/credential-provider-ini/build/index.js:43:20)
    at /scripts/appstream/node_modules/@aws-sdk/credential-provider-ini/build/index.js:32:20
    at async SignatureV4.signRequest (/scripts/appstream/node_modules/@aws-sdk/middleware-signing/node_modules/@aws-sdk/signature-v4/dist/cjs/SignatureV4.js:84:29) {
  tryNextLink: false,
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}

**Comment by ivanbarlog** [comment]
@edpega I've got the same problem. Have you found any workaround?

**Comment by edpega** [comment]
I have not.

**Comment by cpitchford** [comment]
I believe I re-raised this issue here: https://github.com/aws/aws-sdk-js-v3/issues/2087 but have included a work around function
