### ISSUE TITLE
middleware-retry/defaultStrategy.js imports from 'uuid' package as ESM, but relies on CJS version

### ISSUE THREAD

**Issue by benjaminblack** [aws/aws-sdk-js-v3#2004]
## Describe the bug
The `middleware-retry` package depends on the `uuid` package at version `3.0.0`, which is a CJS package, but the `defaultStrategy.js` uses that package as ESM.

On line 4:

```
import { v4 } from "uuid";
```

This works with Webpack, which supports ESM imports from CJS packages in this manner, but it does not work with Rollup.

This is important because currently, even as of Webpack 5, Webpack does not support outputting ESM, while Rollup does. Outputting ESM is critical to target modern browsers which support it.

The version of `uuid` is very old. Bumping the version to the latest (^8.3) should fix the issue, since the latest versions of `uuid` are written as ESM, and both Webpack and Rollup can handle ESM packages and produce whatever bundle format is required.

#### SDK version number
`@aws-sdk/client-cognito-identity@^3.4.1`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
node v15.7.0

## Steps to reproduce
A very simple test file will demonstrate. Assuming the following dependencies in package.json:

```
    "@aws-sdk/client-cognito-identity": "^3.4.1",
    "@rollup/plugin-json": "^4.1.0",
    "@rollup/plugin-node-resolve": "^11.1.1",
    "rollup": "^2.38.5",
    "webpack": "^5.21.1",
    "webpack-cli": "^4.5.0"
```

test.js:

```
import { CognitoIdentityClient } from '@aws-sdk/client-cognito-identity';

const cognitoIdentityClient = new CognitoIdentityClient();
```

Bundling this test file with webpack works; attempting to bundle with Rollup to produce ESM output fails:

`npx webpack --entry "./test.js" --output-path "./dist"`

vs.

`npx rollup test.js --format es --file dist/main.js --plugin node-resolve --plugin json`

#### Observed behavior
Webpack produces a bundle, but Webpack 5 does not support outputting ESM. Rollup produces an error message:

`[!] Error: 'v4' is not exported by node_modules/uuid/index.js, imported by node_modules/@aws-sdk/middleware-retry/dist/es/defaultStrategy.js`

#### Expected behavior
The ESM import from the `uuid` package in `defaultStrategy.js` should not cause an error with Rollup.

**Comment by AllanZhengYP** [comment]
Hi @benjaminblack Thank you for bringing this to us! You are right, we need to bump up the uuid version. We used older uuid in #1322 because some issue in RN at the time. We need to make sure the updated uuid version works in all the runtime we support.

**Comment by ajredniwja** [comment]
Hey @benjaminblack https://github.com/aws/aws-sdk-js-v3/pull/1586 should have fixed the issue. 

Closing this now, please reach out if you have any other questions.
