### ISSUE TITLE
ApiGateway/ApiGatewayClient: PutRestApiRequest is missing "body" property

### ISSUE THREAD

**Issue by nprasovict** [aws/aws-sdk-js-v3#2006]
## Describe the bug
- A clear and concise description of what the bug is.

AWS-CLI provides a way to upload REST API definition via json, i.e.:
`aws apigateway put-rest-api --rest-api-id 'theApiId' --mode overwrite --body 'file://./openapi.json'`

One would expect equivalent functionality from AWS SDK `ApiGateway` client by using `putRestApi()` method, i.e.:
~~~
apiGateway.putRestApi({
    restApiId: 'theApiId',
    mode: PutMode.Overwrite,
    body: '[json api definition content here]'
})
~~~

However, there is no way (i.e. via the method parameters) to specify body content (API definition) to be sent with the request.

API Gateway API Reference specifies that the definition is to be sent in [the request body](https://docs.aws.amazon.com/apigateway/api-reference/link-relation/restapi-put/) and this is indeed possible either via a method parameter, as in [version 2 of aws-sdk-js](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/APIGateway.html#putRestApi-property) or, for example, via a method call on request parameter, as in [Java version](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/apigateway/model/PutRestApiRequest.html#setBody-java.nio.ByteBuffer-).

`aws-sdk-js-v3` `PutRestApiRequest` interface is [missing the `body` property](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-api-gateway/modules/putrestapirequest.html) and it is not clear from documentation how to specify it.

#### SDK version number
`@aws-sdk/client-api-gateway@3.4.1`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
- Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`

~~~
$ node -v
v12.20.1
~~~

## Steps to reproduce
- Please share code or minimal repo, and steps to reproduce the behavior.

TypeScript declaration of the `PutRestApiRequest` interface is missing `body` property.

Adding the property regardless, results in 400 HTTP status reponse, i.e.:

TypeScript code example:

(NOTE: `openapi.json` contains a **correct** json API definition, tested by successfuly uploading it by using AWS-CLI):
~~~
const param = {
    restApiId: 'theApiId',
    mode: PutMode.Overwrite,
    body: fs.readFileSync(`./openapi.json`).toString(),
};
await apiGateway.putRestApi( param );
~~~

and the relevant output in console is:

~~~
BadRequestException: Invalid OpenAPI input.
    at deserializeAws_restJson1PutRestApiCommandError .... loggerMiddleware.ts:21:20 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: '.......',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}

~~~

The response is the same no matter if `param` has `body` property in it or not, or if we force `body` property in `param` (like in the example code snippet above) as either a `string`, `Buffer` or `UInt8Array`.

#### Observed behavior
- A clear and concise description of what happens.

Exception is thrown when `putRestApi()` is called no matter what parameters are passed in.

#### Expected behavior
- A clear and concise description of what you were expecting to happen.

`putRestApi()` finishes with success.

#### Screenshots
- If applicable, add screenshots to help explain your problem.

## Additional context
- Add any other context about the problem here.

**Comment by AllanZhengYP** [comment]
Hi @nprasovict,

This seems to be an issue with the Smithy model we consume. The `body` [exists in JSON model of v2 SDK](https://github.com/aws/aws-sdk-js/blob/3aeaba4799cf3c9f9ccebbbd308c2cc2c05603ee/apis/apigateway-2015-07-09.normal.json#L7456) but [not in Smithy model of v3 SDK](https://github.com/aws/aws-sdk-js-v3/blob/d1c548ede2abe62adbdd11d207500a2eeb96dde0/codegen/sdk-codegen/aws-models/api-gateway.2015-07-09.json#L8535). I will reach out internally to have the model updated. I will keep you posted in the issue comments.

**Comment by nprasovict** [comment]
Any news on this?

**Comment by AllanZhengYP** [comment]
This issue has been fixed, please update your client to the latest: https://github.com/aws/aws-sdk-js-v3/blob/21568893bbd27c902e172f1cb96ebc60ac8791e0/codegen/sdk-codegen/aws-models/api-gateway.json#L8885-L8893
