### ISSUE TITLE
Util to generate dynamic UpdateItemInput for @aws-sdk/util-dynamodb

### ISSUE THREAD

**Issue by mattiLeBlanc** [aws/aws-sdk-js-v3#2009]
When doing an `updateItemCommand` with the new `dbClient`, it is handy to dynamically convert a map of key/values to an update statement.

I created a util function that does that:

```js
/**
 * Util function that creates updateItem input following AWS convention:
 * https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html
 */
export function createUpdateItemInput(data: any) {

  let updateExpression = `set`;
  const expressionAttributeValues: Dictionary<any> = {};
  const expressionAttributeNames: Dictionary<string> = {};

  // loop through data and create alias and update expression
  for(const [index, [key, value]] of Object.entries(Object.entries(data))) {
    const alias = getLetter(parseInt(index, 10));
    expressionAttributeValues[`:${alias}`] = value;
    expressionAttributeNames[`#${alias}`] = key;
    updateExpression = `${updateExpression} #${alias} = :${alias}, `;
  }
  // remove trailing comma
  updateExpression = updateExpression.replace(/,\s*$/, '');
  return {
    UpdateExpression: updateExpression,
    ExpressionAttributeValues: marshall(expressionAttributeValues),
    ExpressionAttributeNames: expressionAttributeNames,
    ReturnValues:'UPDATED_NEW'
  };
}
```

Maybe this is something to add to the dynamo utils and/or enhance?

I would use it  as:

```js
const key = {
  id: 1
};
const data = {
  name: 'foo',
  status: 'active'
};
const values = createUpdateItemInput(data);
const params = {
  TableName: 'TABLE NAME',
   Key: marshall(key),
   ...values
}
const command = new UpdateItemCommand({
  ...params
});
await this.dbClient.send(command);
```

**Comment by trivikr** [comment]
This is a great idea! 👍

Some suggestions:
* The input to the utility function needs to be typed, and not `any`.
* An options hash can be passed as a second parameter, in which user can optionally pass:
  * [UpdateExpression](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html#DDB-UpdateItem-request-UpdateExpression): type of `"SET"`, `"REMOVE"`, `"ADD"`, `"DELETE"` or string.
  * [ConditionExpression](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html#DDB-UpdateItem-request-ConditionExpression): type string, but open to come up with a configuration.
  * [ReturnConsumedCapacity](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html#DDB-UpdateItem-request-ReturnConsumedCapacity): type of [ReturnConsumeCapacity](https://github.com/aws/aws-sdk-js-v3/blob/a008d23fcd66f5d22ab00e14428309f7fc6f868a/clients/client-dynamodb/models/models_0.ts#L1024) or string.
  * [ReturnItemCollectionMetrics](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html#DDB-UpdateItem-request-ReturnItemCollectionMetrics): type of [ReturnItemCollectionMetrics](https://github.com/aws/aws-sdk-js-v3/blob/a008d23fcd66f5d22ab00e14428309f7fc6f868a/clients/client-dynamodb/models/models_0.ts#L1155) or string.
  * [ReturnValues](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html#DDB-UpdateItem-request-ReturnValues): type of [ReturnValue](https://github.com/aws/aws-sdk-js-v3/blob/a008d23fcd66f5d22ab00e14428309f7fc6f868a/clients/client-dynamodb/models/models_0.ts#L2944) or string.

Notes:
* The type `or string` is added for future compatibility. In case DynamoDB adds a new value for type in future, customer can still use it without upgrading their SDK version.
* The legacy parameters (like `AttributeValues`, `ConditionalOperator`) are not accepted.

@mattiLeBlanc Would you like to post a PR with this functionality?
A decision on utility function name can be arrived at a later stage.

**Comment by mattiLeBlanc** [comment]
@trivikr yes, I can extend it. This was a first version util function that I wrote just to solve one problem but I like your suggestions for extending it.
I will put it on my short term todo list.

**Comment by trivikr** [comment]
> By the way, wouldn't the Data Mapper lib already do most of what I did in my util via the `update` function. ([awslabs/dynamodb-data-mapper-js](https://github.com/awslabs/dynamodb-data-mapper-js)).

It will. But the data mapper library is not a priority of AWS SDK for JavaScript team right now.
A new data mapper library, when built on top of v3, would reuse the already written utilities wherever they seem fit.

**Comment by cadam11** [comment]
The data mapper library is also a bit of overkill for some use cases (thinking AWS Lambdas) and it would be nice to have a lightweight util for building update requests.

**Comment by mattiLeBlanc** [comment]
Okay, good to know I will contribute!
Maybe silly question, but do I just clone the whole `aws-sdk-js-v3` project for a PR on the dynamo util, or is there a separate repo?

**Comment by trivikr** [comment]
> Maybe silly question, but do I just clone the whole `aws-sdk-js-v3` project for a PR on the dynamo util, or is there a separate repo?

You'll need to clone the entire project, and build once to generate types for client-dynamodb.
You can run tests only for util-dynamodb during development, as the modular package is mostly independent of the rest of the codebase.

The code for `@aws-sdk/util-dynamodb` is in [packages/util-dynamodb](https://github.com/aws/aws-sdk-js-v3/tree/master/packages/util-dynamodb). To improve discoverability, we've provided this link under homepage field of package.json, and it appears on [npmjs landing page](https://www.npmjs.com/package/@aws-sdk/util-dynamodb).

Do let us know how contributor developer experience can be improved by [creating feature requests](https://github.com/aws/aws-sdk-js-v3/issues/new?assignees=&labels=feature-request&template=---feature-request.md&title=) while you play with the repo :+1:

**Comment by monster-x-adventurer** [comment]
The [@typemon/dynamon](https://www.npmjs.com/package/@typemon/dynamon) package is recommended. There are powerful features for expressions.
```typescript
dynamon.update({
    tableName: 'example',
    primaryKey: {
        foo: 'bar',
    },
    updateExpressionSpec: update(
        set(path, value),
        set(path, plus(path, value)),
        set(path, minus(path, value)),
        set(path, listAppend(path, value)),
        set(path, ifNotExists(path, value)),
        remove(path),
        add(path, value),
        del(path, value),
    ),
});
```

**Comment by donferi** [comment]
Is there any updates on this feature? This is IMO the only missing piece for an awesome DX and making dynamo a bit more accesible for newcomers.

**Comment by AllanZhengYP** [comment]
Hi @donferi @cadam11 @mattiLeBlanc 

This feature request is tracked by: https://github.com/aws/aws-sdk-js-v3/issues/3165 -- we are looking into building a DynamoDB expression builder in the SDK. In fact other AWS SDK already support it. 

The discussion is very helpful, please comment there for any other feature you want the expression builder to support!
