### ISSUE TITLE
AWS_PROFILE no longer works in v3

### ISSUE THREAD

**Issue by simov** [aws/aws-sdk-js-v3#2011]
## Describe the bug
Using `AWS_PROFILE` no longer works in aws-sdk v3 (might be related to this one https://github.com/aws/aws-sdk-js-v3/issues/1193).

I understand that in v3 the STS module is no longer part of the core SDK, but even after including `@aws-sdk/client-sts` in my project, using `AWS_PROFILE` still throws the following error:

```
(node:2519) UnhandledPromiseRejectionWarning: Error: Profile the-profile requires a role to be assumed, but no role assumption callback was provided.
    at resolveProfileData (/the-project/node_modules/@aws-sdk/credential-provider-ini/dist/cjs/index.js:49:19)
    at /the-project/node_modules/@aws-sdk/credential-provider-ini/dist/cjs/index.js:29:59
    at async SignatureV4.credentialProvider (/the-project/node_modules/@aws-sdk/property-provider/dist/cjs/memoize.js:26:26)
    at async SignatureV4.signRequest (/the-project/node_modules/@aws-sdk/signature-v4/dist/cjs/SignatureV4.js:84:29)
    at async /the-project/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:14:22
    at async StandardRetryStrategy.retry (/the-project/node_modules/@aws-sdk/middleware-retry/dist/cjs/defaultStrategy.js:56:46)
    at async /the-project/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22
```

Nothing else changed on my end besides updating the require statements in my project to use the v3 ones and remove `.promise()` on all API calls.

#### SDK version number
```
"@aws-sdk/client-kms": "^3.4.1",
"@aws-sdk/client-sts": "^3.4.1"
```

#### Is the issue in the browser/Node.js/ReactNative?
Node.js CLI script using AWS_PROFILE to assume a role

#### Details of the browser/Node.js/ReactNative version
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`

```
v10.23.1
v12.20.1
```

## Steps to reproduce
Please share code or minimal repo, and steps to reproduce the behavior.

You can probably have an empty file and it's still going to throw the above error because that happens before executing your actual code. I can share an example if needed.

#### Observed behavior
A clear and concise description of what happens.

The above error message.

#### Expected behavior
A clear and concise description of what you were expecting to happen.

The SDK should assume the role provided using AWS_PROFILE

**Comment by AllanZhengYP** [comment]
Hi @simov This is indeed duplicated with #1193. I will label this issue `duplicate` and I will post the latest progress on the other ticket. Please feel free to provide more comment on that issue too.
