### ISSUE TITLE
Use SDKv3 to make Sigv4-signed AppSync GraphQL requests 

### ISSUE THREAD

**Issue by AaronHarris** [aws/aws-sdk-js-v3#2016]
## Describe the issue with documentation

I would like to see if it is possible to leverage the `aws-sdk-js-v3 packages` to make a generic SigV4-signed GraphQL call to AWS AppSync endpoints. AWS AppSync supports IAM authentication using SigV4-signed HTTP requests. Relevant docs here: https://docs.aws.amazon.com/appsync/latest/devguide/security-authz.html#aws-iam-authorization This was previously possible in SDK v2 by creating a custom request and adding some middleware hooks. I know V3 has completely overhauled the middleware stack but I was looking for guidance on how one might make these requests without built-in Smithy documentation.

#### Observed behavior
This was how you could send the request in SDK v2 (rough approximation)

    const AWS = require('aws-sdk');
    // Configure credentials for the client
    let req = new AWS.HttpRequest('https://xxxxxxxxxxx.appsync-api.eu-central-1.amazonaws.com/graphql', 'eu-central-1');
    req.method = 'POST';
    req.headers.host = 'xxxxxxxxxxx.appsync-api.eu-central-1.amazonaws.com';
    req.headers['Content-Type'] = 'multipart/form-data';
    req.body = JSON.stringify({
        "query":"mutation ($input: UpdateUsersCamsInput!) { updateUsersCams(input: $input){ latestImage uid name } }",
        "variables": {
            "input": {
                "uid": owner,
                "name": thingName,
                "latestImage": key
            }
        }
    });

    let signer = new AWS.Signers.V4(req, 'appsync', true);
    signer.addAuthorization(AWS.config.credentials, AWS.util.date.getDate());

    client = new AWS.HttpClient();
    client.handleRequest(req, {}, httpResponse => console.log(httpResponse), err => console.error(err));

This was really handy as it offered built-in retries, connection keepalive (when the correct connection_reuse environment variable was set), connection timeout, and all the other benefits of the SDK.

#### Expected behavior
A way to call https://xxxxxxxxxxx.appsync-api.eu-central-1.amazonaws.com/graphql with IAM authentication using AWS SDK v3 libraries.

**Comment by bestickley** [comment]
These tests helped me figure it out: https://github.com/aws/aws-sdk-js-v3/blob/master/packages/signature-v4/src/SignatureV4.spec.ts
Key for me was using `@aws-crypto/sha256-js` package.

**Comment by bestickley** [comment]
Also made a gist [here](https://gist.github.com/bestickley/43ff142b14243a66d33b8f30c0e95443)

**Comment by ffxsam** [comment]
@AaronHarris Did you know you could do this, as well?

```js
const appSyncClient = new AWSAppSyncClient({
  url:
    'https://xx.appsync-api.us-east-1.amazonaws.com/graphql',
  region: 'us-east-1',
  auth: {
    type: 'AWS_IAM',
    credentials: AWS.config.credentials,
  },
  disableOffline: true,
});
let client: AWSAppSyncClient;

// ... snip

export async function updateThing(id, options) {
  const client = await appSyncClient.hydrated();
  const mutation = gql`
    mutation UpdateThing(
      // ...
  `;

  await client.mutate({
    mutation,
    variables: {
      id,
      options,
    },
  });
}
```

The only thing is, I'm not sure how to access `AWS.config.credentials` in this v3 SDK.

**Comment by ffxsam** [comment]
Figured it out for v3 SDK, leaving this here:

```js
import { defaultProvider } from '@aws-sdk/credential-provider-node';
import AWSAppSyncClient, { AUTH_TYPE } from 'aws-appsync';
import 'isomorphic-fetch';

// ...

  const appSyncClient = new AWSAppSyncClient({
    url:
      'https://xx.appsync-api.us-east-1.amazonaws.com/graphql',
    region: 'us-east-1',
    auth: {
      type: AUTH_TYPE.AWS_IAM,
      credentials: defaultProvider(),
    },
    disableOffline: true,
  });
```

**Comment by liveFreeOrCode** [comment]
@ffxsam I tried this within a nodejs lambda, and couldn't get it to work.  I kept getting 403, and tracing showed that it wasn't able to get the credentials.  I tried `AWS.config.credentails!` and `defaultProvider()`.  Do I need to use STS on the lambdas role arn to get credentials?  Or is there a way to get the embedded lambda runtime credentials?

**Comment by ffxsam** [comment]
@liveFreeOrCode Don't forget to add the proper permissions to the role your Lambda function is using:

```js
          {
            Effect: 'Allow',
            Action: 'appsync:GraphQL',
            Resource: [
              'arn:aws:appsync:*:*:apis/*',
              'arn:aws:appsync:*:*:apis/*/types/*/fields/*',
            ],
          },
```

**Comment by liveFreeOrCode** [comment]
Yeah, I have that as well.  Hmm

**Comment by ffxsam** [comment]
I don't have anything special beyond that. Off the top of my head, I'm not sure why you'd be getting a 403. If you figure it out, please post the answer here if you remember.

**Comment by liveFreeOrCode** [comment]
@ffxsam My issue was unrelated.  There was an API Gateway in front of AppSync in order to create a custom domain, and there was special auth mechanisms on the apigw.  Thanks again for your help.
