### ISSUE TITLE
Consider using alternatives to lerna for managing monorepo

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#2018]
### Is your feature request related to a problem? Please describe.
Lerna is largely unmaintained as discussed in https://github.com/lerna/lerna/issues/2703
An example issue which we'd cut was not responded to for three months https://github.com/lerna/lerna/issues/2668#issuecomment-708632441

### Describe the solution you'd like
Evaluate usage of lerna in v3, and explore replacements for lerna to manage monorepo if required:
* babel switched to [yarn 2 plugin](https://github.com/babel/babel/pull/12138) for managing releases on top of [yarn workspaces](https://classic.yarnpkg.com/en/docs/workspaces/).
* many TypeScript monorepos are switching to [rush stack](https://rushstack.io/) which is specifically designed for large scale TypeScript projects.
* some projects are also adopting [pnpm workspaces](https://pnpm.js.org/en/workspaces)
* npm 7 became [generally available](https://github.blog/2021-02-02-npm-7-is-now-generally-available/) in Feb 2021, and it also supports basic version of [workspaces](https://docs.npmjs.com/cli/v7/using-npm/workspaces).
* [Nx Dev Tools](https://github.com/nrwl/nx) for monorepos is another option.

### Describe alternatives you've considered
Stick with lerna if it's not causing any major issues with releases.

### Additional context
Noticed in responses to tweet https://twitter.com/matthewcp/status/1359234983618035717

**Comment by trivikr** [comment]
Bolt CLI was another tool which was built on top of yarn workspaces, but seems largely abandoned looking at the contribution graph https://github.com/boltpkg/bolt

**Comment by trivikr** [comment]
Revisiting this feature request:
* The AWS SDK for JavaScript team has successfully used Yarn 2+ since Feb 2021 in:
  * https://github.com/aws-samples/aws-sdk-js-tests
  * https://github.com/aws-samples/aws-sdk-js-notes-app
  * https://github.com/aws-samples/aws-sdk-js-v3-workshop
* Analysis on https://github.com/microsoft/fast/issues/4737 is tending towards NPM7.

**Comment by trivikr** [comment]
Revisiting in 2022: [Turborepo](https://turborepo.org/) is becoming monorepo build system of choice in 2022 especially after [acquisition by Vercel](https://vercel.com/blog/vercel-acquires-turborepo).
Nx also posted [it's comparison with Turborepo](https://nx.dev/guides/turbo-and-nx), and also hosted a new website called [Monorepo Explained](https://monorepo.tools/).

Reference: https://dev.to/swyx/why-turborepo-will-be-the-first-big-trend-of-2022-4gfj

**Comment by AllanZhengYP** [comment]
+1 for Turborepo, the Cloud caching the feature I like the most. Currently, the time for building this huge codebase is a pain. It's nice to stop building the same TS code repeatedly.

**Comment by trivikr** [comment]
Lerna is officially not actively maintained https://github.com/lerna/lerna/pull/3092

**Comment by trivikr** [comment]
Blog post evaluating options post lerna https://medium.com/autodesk-tlv/fc075cad51b0

**Comment by juristr** [comment]
Some news: https://github.com/lerna/lerna/issues/3121

**Comment by RanVaknin** [comment]
Close as not planned
