### ISSUE TITLE
LambdaClient InvokeCommand response is missing StatusCode

### ISSUE THREAD

**Issue by thekiwi** [aws/aws-sdk-js-v3#2021]
## Describe the bug
When executing the LambdaClient `send()` with an `InvokeCommand`, the response returned does not include the `StatusCode` field. The TypeScript definitions [suggest it should](https://github.com/aws/aws-sdk-js-v3/blob/master/clients/client-lambda/models/models_0.ts#L3138-L3143) (and SDK v2 did include it)

#### SDK version number
`@aws-sdk/client-lambda@3.4.1`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v12.13.1

## Steps to reproduce
Code snippet:
```JavaScript
const { LambdaClient, InvokeCommand } = require('@aws-sdk/client-lambda');

const credentials = { accessKeyId: process.env.AKID, secretAccessKey: process.env.SAK };

async function run() {
	const lambda = new LambdaClient({ credentials, region: 'eu-west-1' })

	const params = {
		InvocationType: 'Event',
		FunctionName: 'my_function',
		Payload: JSON.stringify({ foo: 'bar' })
	};
	const command = new InvokeCommand(params);
	const result = await lambda.send(command);
	console.log(JSON.stringify(result, null, 2));
}

run().catch(console.error);
```

#### Observed behavior
Here is the output of the above code:
```JSON
{
  "$metadata": {
    "httpStatusCode": 202,
    "requestId": "00000000-0000-0000-0000-000000000000",
    "attempts": 1,
    "totalRetryDelay": 0
  },
  "Payload": {}
}
```
You can see it has no `StatusCode` field at the root level. 

#### Expected behavior
According to [the TypeScript definition of InvocationResponse](https://github.com/aws/aws-sdk-js-v3/blob/master/clients/client-lambda/models/models_0.ts#L3138-L3143) and [the API documentation](https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html#API_Invoke_ResponseSyntax) I expect the response payload to include a `StatusCode` field containing the same as `$metadata.httpStatusCode`.

## Additional context
Tried with both the 'legacy' `Lambda` class and the newer `LambdaClient` class, both have the same result.

**Comment by razor-x** [comment]
Can confirm I just hit this and is still an issue with latest version of the sdk.

**Comment by ajredniwja** [comment]
Seems to be a deserialization issue
https://github.com/aws/aws-sdk-js-v3/blob/b9c1904b5b5a69952698ef6cc025e6893d34a6c8/clients/client-lambda/protocols/Aws_restJson1.ts#L5410,
 its under investigation already, I will discuss with the team for a possible fix to be made soon.

**Comment by AllanZhengYP** [comment]
Hey @thekiwi @ajredniwja this turns out to be an issue with the SDK generator. I pushed a fix in the linked PRs. Thank you a lot for bringing this up!
