### ISSUE TITLE
Support for Typescript Lambda@Edge Data Types

### ISSUE THREAD

**Issue by ronak2121** [aws/aws-sdk-js-v3#2029]
### Is your feature request related to a problem? Please describe.
We use the AWS JS SDK to write NodeJS Lambda@Edge functions. In v2, we used the Typescript Data Types from https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/aws-lambda/trigger. These types are missing from this SDK.

### Describe the solution you'd like
These missing data types added to the SDK so we can depend solely on the internal Typescript types.

### Describe alternatives you've considered
Depending on both the AWS JS SDK and these external Typescript types.

### Additional context
None

**Comment by trivikr** [comment]
The data types mentioned in [@types/aws-lambda](https://www.npmjs.com/package/@types/aws-lambda) are the type definitions for AWS Lambda functions, and should ideally be owned by AWS Lambda team.

The AWS SDK for JavaScript (v3) already contains type definitions for AWS Lambda operations in https://github.com/aws/aws-sdk-js-v3/blob/master/clients/client-lambda/models/models_0.ts

**Comment by ronak2121** [comment]
Right but it looks like you are missing type definitions:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/aws-lambda/trigger/cloudfront-request.d.ts
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/aws-lambda/trigger/cloudfront-response.d.ts

**Comment by trivikr** [comment]
> Right but it looks like you are missing type definitions:
> 
> [https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/aws-lambda/trigger/cloudfront-request.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/aws-lambda/trigger/cloudfront-request.d.ts?rgh-link-date=2021-02-15T18%3A51%3A54Z)
> [https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/aws-lambda/trigger/cloudfront-response.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/aws-lambda/trigger/cloudfront-response.d.ts?rgh-link-date=2021-02-15T18%3A51%3A54Z)

Which operation input/output in `@aws-sdk/client-lambda` are you expecting these type definitions?

**Comment by ronak2121** [comment]
These types are not used to call a Lambda or the Lambda API. These are types to use when defining a NodeJS Lambda. Therefore, these types would not be tagged to any operation from your SDK.

**Comment by trivikr** [comment]
> These types are not used to call a Lambda or the Lambda API. These are types to use when defining a NodeJS Lambda. Therefore, these types would not be tagged to any operation from your SDK.

The `@aws-sdk/client-dynamodb` should not have responsibility to emit types which are not used to call Lambda APIs. 

> The data types mentioned in [@types/aws-lambda](https://www.npmjs.com/package/@types/aws-lambda) are the type definitions for AWS Lambda functions, and should ideally be owned by AWS Lambda team.

These types must be ideally be owned by Lambda team, but looks like it's community supported and deployed on DefinitelyTyped.

You can create a PR to fix the type definitions in DefinitelyTyped by following guidelines in https://github.com/DefinitelyTyped/DefinitelyTyped#how-can-i-contribute
