### ISSUE TITLE
Provide service name and operation in context for middleware

### ISSUE THREAD

**Issue by workeitel** [aws/aws-sdk-js-v3#2030]
### Is your feature request related to a problem? Please describe.

For any client-side operational data collection it's important to know which operation is called on which service. One example use-case is the X-Ray integration: https://github.com/aws/aws-xray-sdk-node/pull/298/files but also custom monitoring code like we have handler to log latency/retry/success metrics for outgoing calls in lambda functions.

### Describe the solution you'd like

At the very minimal it would be good to get service name and operation. Right now only the class names are emitted: https://github.com/aws/aws-sdk-js-v3/blob/master/clients/client-dynamodb/commands/ScanCommand.ts#L74-L75

Example: `{ operation: "DescribeTableCommand", service: "DynamoDBClient" }`

The `Command` and `Client` are unnecessary suffix which need to be removed first (Example from X-Ray PR: `let operation: string = command.constructor.name.slice(0, -7);`)

In addition it would be great if `amz-sdk-invocation-id` is provided as well in the context. Similar for server-side timestamp to work around client-side time difference.

### Describe alternatives you've considered

Using the provided class names and stripping the suffix - which is ugly and brittle.

### Additional context

Example from java sdk: https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/generating-sdk-metrics.html https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/sdk-metrics.html and https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html

Bonus points for a built-in middleware which writes logs/metrics in EMF format right away: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Specification.html

**Comment by trivikr** [comment]
A solution discussed was to add the following in resolveMiddleware:
* `service` without `Client`
* `operation` without `Command` and switch to camelCase

https://github.com/aws/aws-sdk-js-v3/blob/6b4bde6f338720abf28b931f8a4506613bd64d3f/clients/client-dynamodb/commands/ScanCommand.ts#L69-L75

We decided to not go ahead with this for the following reasons:
* AWS SDK for JavaScript (v3) is GA, and we won't be breaking contract of clientName/commandName.
* These additional parameters will increase the bundle size of Command.
