### ISSUE TITLE
Upload constructor throws error & bypasses catch block

### ISSUE THREAD

**Issue by ffxsam** [aws/aws-sdk-js-v3#2036]
## Describe the bug
I'm not totally sure how this is happening, but `new Upload()` is raising an "Access Denied" error (due to IAM permissions) and bypassing my `catch` block somehow.

#### SDK version number
`@aws-sdk/lib-storage@3.4.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v12.20.1

## Steps to reproduce
```js
    try {
      const upload = new Upload({
        client: new S3({}),
        params: {
          Bucket: process.env.STORAGE_BUCKET,
          Key: zipFileKey,
          Body: readable,
        },
      });

      await upload.done();
    } catch (e) {
      // This block is NOT reached
      Sentry.captureException(e);
      await Sentry.flush(2000);

      return {
        error: FunctionError.S3_ERROR,
        errorMessage: 'Error saving ZIP to S3',
        rawError: e,
      };
```

#### Observed behavior
I see the error in my CloudWatch logs instead:
```
{
    "errorType": "AccessDenied",
    "errorMessage": "Access Denied",
    "code": "AccessDenied",
    "message": "Access Denied",
    // snip
}
```

#### Expected behavior
I expected my `catch` block to be reached so I can neatly handle the error.

**Comment by ffxsam** [comment]
Turns out this particular access denied was because the files were missing. So, the readable stream couldn't stream them from S3. Maybe when streams are involved, the exception isn't catchable for some reason?

**Comment by alexforsyth** [comment]
https://github.com/aws/aws-sdk-js-v3/pull/2039

**Comment by ffxsam** [comment]
I'll bookmark this for later and circle back when I have some time to test this again.
