### ISSUE TITLE
CORS requests now fail due to `amz-sdk-invocation-id` header

### ISSUE THREAD

**Issue by activiz** [aws/aws-sdk-js-v3#2038]
## Describe the bug
When attempting to describe a databrew dataset, I am encountering a CORS error

## SDK version number
`@aws-sdk/client-databrew@v3.5.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
`v10.19.0` 

## Steps to reproduce
```
cognitoIdentityClient = new CognitoIdentityClient({ region: 'eu-west-1' });
client = new DataBrewClient({
  region: 'eu-west-1',
  credentials: fromCognitoIdentityPool({
    client: this.cognitoIdentityClient,
    identityPoolId: 'eu-west-1:xxxxxx-7583-415b-xxxx-xxxxxx'
  })
});

constructor() { }

async ngOnInit() {
  try {
    const d: DescribeDatasetRequest = { Name: 'SalesDataset' };
    const command = new DescribeDatasetCommand(d);
    const data = await this.client.send(command);
    console.log(data);
  } catch (error) {
    console.log(error);
  }
}
```
#### Observed behavior
When executing the above code, I am getting the following error:
```
Access to fetch at 'https://databrew.eu-west-1.amazonaws.com/datasets/SalesDataset' from origin 'https://localhost:4200' has been blocked by CORS policy: Request header field amz-sdk-invocation-id is not allowed by Access-Control-Allow-Headers in preflight response.
```

#### Expected behavior
The data should return and show me a description of the dataset I requested.

**Comment by trivikr** [comment]
DataBrew doesn't support retry headers in CORS: https://github.com/AllanZhengYP/cors-test/blob/master/output.md

Fix:
* Short term: DataBrew service name needs to be added in [AddOmitRetryHeadersDependency](https://github.com/aws/aws-sdk-js-v3/blob/master/codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddOmitRetryHeadersDependency.java)
* Long term: Create a ticket with DataBrew service team to support retry headers.

**Comment by trivikr** [comment]
Other services which don't support retry headers in CORS, and are not in AddOmitRetryHeadersDependency:
* AppFlow
* AppIntegrations
* AuditManager
* Connect Contact Lens
* Customer Profiles
* DevOps Guru
* Service Catalog AppRegistry

**Comment by activiz** [comment]
Hi @trivikr, thank you for the new release.  The bug still exists in `"@aws-sdk/client-databrew": "^3.6.0"`.

**Comment by ahmedelhaw** [comment]
any update on "@aws-sdk/client-databrew" 
has been blocked by CORS policy: Request header field amz-sdk-invocation-id is not allowed by Access-Control-Allow-Headers in preflight respons
