### ISSUE TITLE
getBucketPolicy fails with TypeError: Cannot read property '#text' of undefined

### ISSUE THREAD

**Issue by abhinavkareer-nx** [aws/aws-sdk-js-v3#2040]
## Describe the bug
getBucketPolicy in the js sdk expects an XML response whereas the aws s3 api docs says it should be a json body
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getBucketPolicy-property

#### SDK version number
`@aws-sdk/aws-sdk-js-v3@3.30`
https://github.com/aws/aws-sdk-js-v3/tree/v3.3.0
#### Is the issue in the browser/Node.js/ReactNative?
No

#### Details of the browser/Node.js/ReactNative version
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`

## Steps to reproduce
Please share code or minimal repo, and steps to reproduce the behavior.
#### Observed behavior
getBucketPolicy fails with TypeError: Cannot read property '#text' of undefined

#### Expected behavior
getBucketPolicy should expect json input

## Additional context
this is similar to https://github.com/aws/aws-sdk-js-v3/issues/1349

**Comment by adcreare** [comment]
I can confirm this bug with latest 3.5.0 s3 sdk.

**Comment by trivikr** [comment]
I'm able to reproduce the big with the following code:

<details>
<summary>Code</summary>

```js
import { S3, waitForBucketExists } from "@aws-sdk/client-s3";
import { STS } from "@aws-sdk/client-sts";

const region = "us-west-2";
const client = new S3({ region });

const Bucket = `test-${Date.now()}`;
await client.createBucket({ Bucket });
await waitForBucketExists({ client }, { Bucket });

const stsClient = new STS({ region });
const { Account } = await stsClient.getCallerIdentity({});

const Policy = `{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "id",
      "Effect": "Allow",
      "Principal": {
        "AWS": "${Account}"
      },
      "Action": ["s3:*"],
      "Resource": "arn:aws:s3:::${Bucket}"
    }
  ]
}`;

await client.putBucketPolicy({ Bucket, Policy });
try {
  await client.getBucketPolicy({ Bucket });
} catch (error) {
  console.log(error);
}
await client.deleteBucketPolicy({ Bucket });

await client.deleteBucket({ Bucket });

```

</details>

<details>
<summary>Output</summary>

```console
TypeError: Cannot read property '#text' of undefined
    at /Users/trivikr/workspace/test/node_modules/@aws-sdk/client-s3/dist/cjs/protocols/Aws_restXml.js:12428:30
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Object.deserializeAws_restXmlGetBucketPolicyCommand (/Users/trivikr/workspace/test/node_modules/@aws-sdk/client-s3/dist/cjs/protocols/Aws_restXml.js:5590:18)
    at async /Users/trivikr/workspace/test/node_modules/@aws-sdk/middleware-serde/dist/cjs/deserializerMiddleware.js:6:20
    at async /Users/trivikr/workspace/test/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:12:24
    at async StandardRetryStrategy.retry (/Users/trivikr/workspace/test/node_modules/@aws-sdk/middleware-retry/dist/cjs/defaultStrategy.js:56:46)
    at async /Users/trivikr/workspace/test/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22
    at async file:///Users/trivikr/workspace/test/getBucketPolicy.mjs:31:3 {
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
```

</details>

**Comment by trivikr** [comment]
This happens as the the response returned is JSON and not XML, and the protocols generator runs xml-parse on it https://github.com/aws/aws-sdk-js-v3/blob/325d6b4958c0d53e9cf167fbfb54b1794bd29889/clients/client-s3/protocols/Aws_restXml.ts#L14316-L14321

The value in `encoded`: `{"Version":"2012-10-17","Statement":[{"Sid":"id","Effect":"Allow","Principal":{"AWS":"arn:aws:iam::REDACTED:root"},"Action":"s3:*","Resource":"arn:aws:s3:::REDACTED"}]}`
The value in `parsedObj`: undefined

**Comment by trivikr** [comment]
This issue doesn't happen in AWS SDK for JavaScript (v2), as it checks the type of the response output before calling parser.

Code: https://github.com/aws/aws-sdk-js/blob/e5c12fad7ebc87b4de447d777628030be4792945/lib/protocol/rest_xml.js#L77-L99

**Comment by JekaPolihovic** [comment]
Hello!!!
I faced the same problem, please tell me how it can be solved and whether it will be solved soon.

My example:
https://jmp.sh/CuJGaZ8
https://jmp.sh/02xwhq6

I would be grateful if you answer.

**Comment by trivikr** [comment]
The code is v2 is straightforward, as the variable `payload` contains `Policy`, and is populated in the response.
https://github.com/aws/aws-sdk-js/blob/e5c12fad7ebc87b4de447d777628030be4792945/lib/protocol/rest_xml.js#L92

In v3, I can avoid XML parsing in case of JSON as follows:
```js
      if (encoded.length) {
        if (encoded.startsWith('{')) {
            // Value is JSON, return as it is.
            return encoded;
        }
        const parsedObj = xmlParse(encoded, {
```

However, the deserialize function expects the object to be present in `Policy` key instead https://github.com/aws/aws-sdk-js-v3/blob/325d6b4958c0d53e9cf167fbfb54b1794bd29889/clients/client-s3/protocols/Aws_restXml.ts#L6482-L6485

I'll discuss this solution internally, and share my findings.

**Comment by JekaPolihovic** [comment]
> The code is v2 is straightforward, as the variable `payload` contains `Policy`, and is populated in the response.
> https://github.com/aws/aws-sdk-js/blob/e5c12fad7ebc87b4de447d777628030be4792945/lib/protocol/rest_xml.js#L92
> 
> In v3, I can avoid XML parsing in case of JSON as follows:
> 
> ```js
>       if (encoded.length) {
>         if (encoded.startsWith('{')) {
>             // Value is JSON, return as it is.
>             return encoded;
>         }
>         const parsedObj = xmlParse(encoded, {
> ```
> 
> However, the deserialize function expects the object to be present in `Policy` key instead
> 
> https://github.com/aws/aws-sdk-js-v3/blob/325d6b4958c0d53e9cf167fbfb54b1794bd29889/clients/client-s3/protocols/Aws_restXml.ts#L6482-L6485
> 
> I'll discuss this solution internally, and share my findings.

Thank you very much for your answer, we will wait for a solution!

**Comment by trivikr** [comment]
I was checking differences between models in v2 and v3.

Differences between models in v2:
* GetBucketPolicyOutput which returns output in JSON: https://github.com/aws/aws-sdk-js/blob/16905c13e61175878d30d5381ddfc2dc6ee75d3c/apis/s3-2006-03-01.normal.json#L4214-L4223
* GetObject which returns output in XML: https://github.com/aws/aws-sdk-js/blob/16905c13e61175878d30d5381ddfc2dc6ee75d3c/apis/s3-2006-03-01.normal.json#L4574

There's no information about the types at the models level.

Difference between models in v3:
* GetBucketPolicyOutput is missing httpPayload trait on Policy: https://github.com/aws/aws-sdk-js-v3/blob/7c5309410b71514255a1b098b0f016f68f31c939/codegen/sdk-codegen/aws-models/s3.2006-03-01.json#L4230-L4240
* GetObject contains empty httpPayload trait on Body: https://github.com/aws/aws-sdk-js-v3/blob/7c5309410b71514255a1b098b0f016f68f31c939/codegen/sdk-codegen/aws-models/s3.2006-03-01.json#L4807-L4816
