### ISSUE TITLE
[Benchmark] Add benchmark framework for this repository and integrate with CI

### ISSUE THREAD

**Issue by alexforsyth** [aws/aws-sdk-js-v3#2044]
### Is your feature request related to a problem? Please describe.
Feature request is created from comment https://github.com/aws/aws-sdk-js-v3/pull/2039#issuecomment-780881408 by user @monken

> it would be helpful to have [benchmarking] integrated in the build pipeline to ensure that performance doesn't regress. People will try and clean up or simplify the code without noticing that is serious performance implications.

example: https://github.com/aws/aws-sdk-js-v3/pull/2039#discussion_r577954106

### Describe the solution you'd like
Proper benchmarking as part of the CI in this repo. Should give stats on 
1. Performance
2. Bundle Size
3. Other stuff?

**Comment by trivikr** [comment]
We create size benchmark in https://github.com/aws/aws-sdk-js-v3/blob/main/benchmark/size/report.md
We also limit size increases in internal release automation scripts.
