### ISSUE TITLE
Add example of using @aws-sdk/client-transcribe-streaming with users microphpone

### ISSUE THREAD

**Issue by nhs-jamesallis** [aws/aws-sdk-js-v3#2046]
## Describe the issue with documentation
Is it possible to get some example code of using the users microphone with getUserMedia and the medical streaming transcription service in order to do real time transcription, thanks!

**Comment by trivikr** [comment]
The transcribe-streaming example is in repo https://github.com/aws-samples/aws-sdk-js-notes-app

<details>
<summary>Click to view video recording</summary>

  [![Screen recording](https://img.youtube.com/vi/fF9zd0YJn6A/0.jpg)](https://www.youtube.com/watch?v=fF9zd0YJn6A)

</details>

I've added link to notes-repo in README at https://github.com/aws/aws-sdk-js-v3/pull/2047
