### ISSUE TITLE
esm build targets es5

### ISSUE THREAD

**Issue by kyeotic** [aws/aws-sdk-js-v3#2056]
### Is your feature request related to a problem? Please describe.
Yes. Bundling this project results in poor performing code due to the `target: 'es5'` in the `tsconfig.es.json` transpiling async and generator functions.

The `tsconfig.json` used for the CommonJS build targets ES2018, resulting in native async and generator functions and significantly better performance.

This seems exactly backwards to me. The purpose of the es/ESM build is to support tree-shaking via tools like webpack and rollup that can statically analyze the _newer_ esm format and remove dead code. These same tools can handle tanspilation to ES5 _if needed_, but they cannot transpile from ES5 back up to ES2018/ESNEXT.

This forces you to choose between the CJS version, which performs the best but cannot be tree-shaken, or the ES version, that can be tree-shaken but performs terribly. This choice is unnecessary! If the ES build targeted ESNEXT (or ES2020 or even ES2018) then users could have _both_ the best performance and the best bundle size. Further, if they needed to target ES5 the same tools they are using for tree-shaking can transpile to that target.

By transpiling the ESM build to target ES5 you are removing this option.

### Describe the solution you'd like
Change the ESM build to target `ES2020` or `ESNEXT`

### Describe alternatives you've considered
There are none. This build configuration blocks the ability to tree-shake the version of code that has native async functions

### Additional context
None.

**Comment by aborayan1020** [comment]
https://aws.amazon.com/developer/language/javascript/?nc1=f_dr

**Comment by kyeotic** [comment]
@aborayan1020 I'm not really sure why you shared that link.

**Comment by monken** [comment]
Couldn't agree more. I'm using https://github.com/evanw/esbuild to bundle code for Lambda and I noticed that it doesn't tree-shake properly. The end result is a huge Lambda bundle.

@kyeotic out of curiosity, do you know how to force esbuild to us cjs files?

**Comment by kyeotic** [comment]
@monken Not exactly. [This setup](https://github.com/Nike-Inc/dynamo-arc/blob/v2/esbuild.js) seems to work reasonably well, but its still including some code I'd rather avoid.

**Comment by kb3eua** [comment]
To use the ES modules to get better tree-shaking w/ esbuild you can pass it the argument `--main-fields=module,main` (it uses `main,module` by default).

Also, instead of setting the "main fields" I've observed I can get even smaller bundles by instead adding the following `path` settings to my `tsconfig.json`:
```json
{
    "compilerOptions": {
        "paths": {
            "@aws-sdk/client-s3": ["./node_modules/@aws-sdk/client-s3/dist/es", "./node_modules/@aws-sdk/client-s3"]
        }
    }
}
```
... the obvious drawback to this is needing to specify each module you use form the AWS SDK.

**Comment by ataylorme** [comment]
I've been using [`@vercel/ncc`](https://github.com/vercel/ncc) to compile a JS file for use as an AWS Lambda. It works well with TypeScript so I get the advantages of writing modern code and typing while still having a small file to deploy to Lambda.

I have the Dynamo and Lambda client + my code and the compiled JS file is 2.8Mb. I'l using the full DynamoDB client as well, not the bare-bones version.

**Comment by simonbuchan** [comment]
Note that it's not just performance - transpiling async functions completely breaks the debuggability of requests as it breaks the default async stack support in runtimes, fixing this was a goal of v3 too.

It's pretty absurd that es modules are targeting es5 as to my knowledge [every environment](https://kangax.github.io/compat-table/es2016plus/) that supports modules supports everything (modulo Spectre / Meltdown mitigations) up to es2019 in their earliest supported versions, *including* Node v12. (Hermes may look like an exception here, but this is the react native opt-in optimized runtime that will already have everything run through babel transpilation in the react native bundler, Metro, by default anyway. iOS is also suspicious, but in detail the unsupported features are very niche, and don't look like they would be something that would affect any sensible library.)

As a possible alternative if you're feeling particularly nervous, you are not restricted to using the `module` and `main` fields: both webpack and rollup('s commonjs plugin) can be configured to respect arbitrary main fields, and there is the `exports` field that can configure for arbitrary conditions that is widely supported. You could expose a less or non-transpiled version in addition this way.

**Comment by paul-uz** [comment]
> Couldn't agree more. I'm using https://github.com/evanw/esbuild to bundle code for Lambda and I noticed that it doesn't tree-shake properly. The end result is a huge Lambda bundle.
> 
> @kyeotic out of curiosity, do you know how to force esbuild to use mjs files?

Could you explain how you use esbuild exactly? I'm interested to see if it could be useful for our lambda functions

**Comment by monken** [comment]
I use the following command:

```
esbuild --platform=node --target=node14 --bundle --main-fields=module,main --outdir=dist src/index.ts
```

The key is `--main-fields=module,main` which forces esbuild to use the mjs files bundled with the v3 SDK. This leads to a very small, tree-shaken bundle.

**Comment by suds-sky** [comment]
@here, I tried with `--main-fields=module,main` flag as suggested and it works great. Does anyone know how to set this in AWS CDK's NodejsFunction construct to get the same result

**Comment by AllanZhengYP** [comment]
Thank you for the input on the ECMA version for the ESM distribution. We already have a issue discussing the next step(https://github.com/aws/aws-sdk-js-v3/issues/2056), you can comment there if you have further quetsions.

**Comment by suds-sky** [comment]
@AllanZhengYP, Thanks for the update. Can you please share the issue you are referring to, so that we can follow on it.

**Comment by simonbuchan** [comment]
@AllanZhengYP to clarify, you posted this issue number :)

**Comment by simonbuchan** [comment]
I think it's #2889?

**Comment by suds-sky** [comment]
@AllanZhengYP Can you confirm is it (2889)[https://github.com/aws/aws-sdk-js-v3/issues/2889] you were referring to
