### ISSUE TITLE
aws-ses: SendTemplatedEmail uses unexpected IAM policy

### ISSUE THREAD

**Issue by ghost** [aws/aws-sdk-js-v3#2061]
Hey guys,

when using `SendTemplatedEmail` from `aws-ses` in the following way:

```
    // ...
    const request: ses.Types.SendTemplatedEmailRequest = {
      Source:       source,
      Destination:  { ToAddresses: ["test@gmail.com"] },
      Template:     template,
      TemplateData: JSON.stringify(data),
    };
    try {
      await this.client.sendTemplatedEmail(request).promise();
    } catch(e) {
      console.error("SES failed: %s", e);
      throw e;
    }
```
it expects my lambda to have the following policy/permissions:

```
arn:aws:sts::<accountId>:assumed-role/<serviceRole>/<lambda>' is not authorized to perform `ses:SendTemplatedEmail' on resource `arn:aws:ses:<region>:<accountId>:identity/test@gmail.com'
```

Is this a known bug? Or is there something wrong in my config?

The docs say, that I have to put my `source` mail-address into the resource-arn ...
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/sending-authorization-policy-examples.html

**Comment by ajredniwja** [comment]
Hi there, apologies for late reply, seems to be a permissions issue. You wanna make sure that IAM role has permissions to execute Lambda functions, find more about it [here](https://docs.aws.amazon.com/lambda/latest/dg/lambda-permissions.html).

To work with SES you can find example [here](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/ses-examples.html). 

Closing this issue now, please reach out if you have any additional questions.
