### ISSUE TITLE
property-provider memoize cache poisoned by uncaught exceptions

### ISSUE THREAD

**Issue by rlefebvre** [aws/aws-sdk-js-v3#2067]
## Describe the bug
Exceptions thrown by the provider will be cached, poisoning the cache forever. This problem is expressed in credential-provider-imds when there is an HTTP timeout, credentials are unobtainable after this has occurred once.

#### SDK version number
`@aws-sdk/property-provider@3.3.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v10.18.1

## Steps to reproduce
https://github.com/rlefebvre/timeout-aws

#### Observed behavior
If the provider to memoize throws an exception, there is no opportunity to retry (via isExpired for instance, since it is called after awaiting the cached promise - which throws)

#### Expected behavior
Interrupted execution of the provider should not be considered a final result. Or it should be parametrizable.

**Comment by trivikr** [comment]
This issue was fixed in https://github.com/aws/aws-sdk-js-v3/pull/2680, and will be released with `v3.27.0` on Friday 08/20.

**Comment by AllanZhengYP** [comment]
We notice some customers are getting intermittent failures while fetching credentials from STS. This issue became more prevalent in US-EAST-1 region using Amazon EKS managed AWS Identity and Access Management (IAM) OpenID Connect (OIDC) external identity provider (IdP).

If you have the similar issue, please refer to the comment below for guidance of debugging:
https://github.com/aws/aws-sdk-js-v3/pull/2680#issuecomment-986292595
