### ISSUE TITLE
TranscribeStreamingClient - bad transcription for StartStreamTranscriptionCommand

### ISSUE THREAD

**Issue by loretoparisi** [aws/aws-sdk-js-v3#2078]
## Describe the bug
The transcription of a short sample wav file is wrong and different from the results obtained by the AWS Transcribe Console.

#### SDK version number
```json
{
   "@aws-sdk/client-transcribe": "^3.6.1",
   "@aws-sdk/client-transcribe-streaming": "^3.6.1",
   "aws-sdk": "^2.850.0"
}
```

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
```
$ node --version
v12.16.1
```

## Steps to reproduce
Run the code example in the package [aws-transcribe-streaming-node-example](https://github.com/loretoparisi/aws-transcribe-streaming-node-example):

```
git clone https://github.com/loretoparisi/aws-transcribe-streaming-node-example
cd aws-transcribe-streaming-node-example
npm install
node streamingclient.js sample.wav
```

#### Observed behavior
Transcription results:

```
7.81: Closure.
13.9: Uh huh. For the man. You there? Yeah, sure. Sure.
```

#### Expected behavior
The transcription should at least match the results from the AWS Transcribe Console tool:

```
{
                "transcript": "Hi. My name is John McCollum. I'm a writer at large for The New York Times Magazine. And in 2016, I wrote a piece for the magazine about clouds. Yeah, it's a story about clouds. It doesn't sound very important, and I"
}
```

Full output is available [here](https://gist.github.com/loretoparisi/a00c95d851c111a311a5026d247df4eb).

#### Screenshots
-
## Additional context
-

**Comment by returnKitten** [comment]
Did you manage to solve this?

**Comment by returnKitten** [comment]
In the original code they mention they use a RAW PCM file, and you used a WAV, so I think the problem is likely there.

**Comment by loretoparisi** [comment]
@returnKitten sorry it should be PCM, my code for the audio is here, I'm using `pcm_s16le`

```javascript
function (fpath, opath, sampleRate) {
      var self = this;

      // defaults
      sampleRate = sampleRate || '44100';
      var loglevel = self.logger.isDebug() ? 'debug' : 'warning';
      return new Promise((resolve, reject) => {
        const args = [
          '-y',
          '-loglevel', loglevel,
          '-i', fpath,
          '-ar', sampleRate,
          '-acodec', 'pcm_s16le',
          opath
        ];
        const opts = {
          cwd: self._options.tempDir
        };
        cp.spawn('ffmpeg', args, opts)
          .on('message', msg => self.logger.info(msg))
          .on('error', reject)
          .on('close', resolve);
      });
    }
```

**Comment by ajredniwja** [comment]
Hey @loretoparisi thanks for opening this, unfortunately I am not able to reproduce this I used the code and example found here: https://github.com/ajredniwja/transcribe-example.

Is it possible for you to share code and the file?
