### ISSUE TITLE
CORS requests fail due to `amz-sdk-invocation-id` header in kinesis video service

### ISSUE THREAD

**Issue by Amplifiyer** [aws/aws-sdk-js-v3#2080]
## Describe the bug
Make a service call to kinesis-video and get the following error:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://xxxxx.kinesisvideo.us-west-2.amazonaws.com/v1/get-ice-server-config. (Reason: header ‘amz-sdk-invocation-id’ is not allowed according to header ‘Access-Control-Allow-Headers’ from CORS preflight response).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://xxxxx.kinesisvideo.us-west-2.amazonaws.com/v1/get-ice-server-config. (Reason: CORS request did not succeed).
```

#### SDK version number
    "@aws-sdk/client-kinesis": "1.0.0-rc.10",
    "@aws-sdk/client-kinesis-video": "1.0.0-rc.10",
    "@aws-sdk/client-kinesis-video-media": "1.0.0-rc.10",
    "@aws-sdk/client-kinesis-video-signaling": "1.0.0-rc.10",

I believe this is an issue since `1.0.0-gamma.3`

#### Is the issue in the browser/Node.js/ReactNative?
Browser

Originally mentioned here https://github.com/aws/aws-sdk-js-v3/issues/1376#issuecomment-693551866

**Comment by ajredniwja** [comment]
@Amplifiyer is this still an issue with the latest version? I see and open issue that needs discussion here: https://github.com/aws/aws-sdk-js-v3/issues/1962 and a PR that suggests it should be working in the latest version. https://github.com/aws/aws-sdk-js-v3/pull/1963
