### ISSUE TITLE
Update SSECustomerKey type from String to String | Buffer 

### ISSUE THREAD

**Issue by mrawdon** [aws/aws-sdk-js-v3#2081]
### Is your feature request related to a problem? Please describe.
Currently the type definition only accepts a String.  The actual code in middleware-ssec supports Strings or Buffers.  Passing in a buffer already works fine, but gets a TypeError.  The code below works, but requires the as any to avoid the typing issue.

```
const uploadParams: PutObjectRequest = {
      Bucket: bucket,
      Key: 'some-key',
      Body: fs.createReadStream('filename'),
      SSECustomerAlgorithm: "AES256",
      SSECustomerKey: (randomBytes(32) as any)
};

client.putObject(uploadParams);
```

### Describe the solution you'd like
Update the type definition of SSECustomerKey to include Buffer(or ArrayBuffer)  I wasn't sure if there was a best practice for Buffer types already defined for the project.

### Describe alternatives you've considered
Using `as any` to ignore the TypeScript error

### Additional context
I'd be willing to put together a PR, but wasn't sure of the correct type to use for the Buffer

**Comment by RanVaknin** [comment]
You should use `PutObjectCommandInput` instead of `PutObjectRequest` for the input type.
We can convert other input types to Strings and it is reflected with the `PutObjectCommandInput` type.

Thanks,
Ran~
