### ISSUE TITLE
@aborayan1020 I'm not really sure why you shared that link.

### ISSUE THREAD

**Issue by aborayan1020** [aws/aws-sdk-js-v3#2084]
@aborayan1020 I'm not really sure why you shared that link.

_Originally posted by @kyeotic in https://github.com/aws/aws-sdk-js-v3/issues/2056#issuecomment-784705087_

**Comment by kyeotic** [comment]
@trivikr This user has a habit of opening issues as responses to comments in other issues. I think it might be worth banning them.
