### ISSUE TITLE
waiters should fail immediately if it would be pointless to retry

### ISSUE THREAD

**Issue by otterley** [aws/aws-sdk-js-v3#2091]
## Describe the bug
I was trying to use a waiter, namely, `waitForVolumeInUse` from client-ec2, which never returned. (It might have had I continued to wait until the timeout exceeded.) It turned out that the excessive delay was caused by my role policy not granting access to `ec2:DescribeVolumes`. However, the wait function was swallowing the error and retrying, falsely assuming it was a temporary failure rather than a permanent one.

#### SDK version number
`@aws-sdk/client-ec2@3.7.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
14.15.4

**Comment by otterley** [comment]
Another instance I found where a waiter will retry until the timeout is when a validation error is returned, such as when calling ssm:GetCommandInvocation:

```
ValidationException: 1 validation error detected: Value null at 'commandId' failed to satisfy constraint: Member must not be null.
```

**Comment by alexforsyth** [comment]
Yeah, I agree this is a good point. The way these are codegen'd adds some complexity to doing this properly. We'll investigate the best path forward

**Comment by trivikr** [comment]
This should probably be implemented in new wrapper `waitUntilOperationName` discussed in https://github.com/aws/aws-sdk-js-v3/issues/1917#issuecomment-777061186

The `waitForOperationName` is planned to be deprecated in favor of `waitUntilOperationName`

**Comment by vudh1** [comment]
@otterley do you have a reproducible code that we can use?

**Comment by otterley** [comment]
An idle issue is still an issue.
