### ISSUE TITLE
Somtiems get duplicated items when use LastEvaluatedKey and ExclusiveStartKey

### ISSUE THREAD

**Issue by jthcast** [aws/aws-sdk-js-v3#2092]
## Describe the bug
Somtiems get duplicated items when use LastEvaluatedKey and ExclusiveStartKey.
It cause not specific item. 

#### SDK version number
@aws-sdk/client-dynamodb": "^3.2.0"

#### Is the issue in the browser/Node.js/ReactNative?
Browser/Node.js

#### Details of the browser/Node.js/ReactNative version
Chrome: 88.0.4324.190
Node.js v14.15.0

## Steps to reproduce
https://github.com/jthcast/techblogposts/blob/master/pages/api/posts.ts

#### Observed behavior
Response with include lastEvaluatedKey item, so I got duplicated data.

#### Expected behavior
Response with not include lastEvaluatedKey item

#### Screenshots
![dynamodb lastevaluatedkey](https://user-images.githubusercontent.com/49227119/109472135-167ea580-7ab5-11eb-85cf-40633ac0c1dc.jpg)

## Additional context
It cause not specific item. I guess.
It's different results when change limit value.

**Comment by ajredniwja** [comment]
Hi there, thanks for opening this issue, not able to go through the example that you mentioned. 

I am not sure if I understand your question. From what I understand is `LastEvaluatedKey` is the primary key of the item where the operation stopped. You believe that that is getting returned again in the next response when you use `exclusiveStartKey`? 

Is it possible for you to set up minimal repro code which causes the issue?

**Comment by jthcast** [comment]
Hi, thanks for reply. your understand is right. sorry for my poor English. 😭

Here are example repo and site.
github: https://github.com/jthcast/dynamo-test
site: https://dynamo-test.vercel.app/

Click 'load more' button then you can see last item is duplicated. but after button click, it works fine.
Data are unique. not duplicated.
