### ISSUE TITLE
Use consistent imports

### ISSUE THREAD

**Issue by christophgysin** [aws/aws-sdk-js-v3#2100]
### Is your feature request related to a problem? Please describe.
I'm maintaining a [fork of aws-sdk-js-v3](https://github.com/christophgysin/aws-sdk-js-v3) for [deno](https://deno.land). Since I'm trying to automatically convert the code, having consistent imports makes my work a lot easier.

Even besides that, using a consistent import style improves code readability IMO.

### Describe the solution you'd like
Use a consistent import style, e.g:
```
import { func } from 'module'
```

**Comment by alexforsyth** [comment]
Hey this is a sweet project! 

cc: @trivikr
