### ISSUE TITLE
Explore removing function overrides from aggregated clients

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#2104]
### Is your feature request related to a problem? Please describe.
As mentioned by @kyeotic about type guards when overloading functions in aggregated clients

> the same exact guard exists in every single command function, _as well as_ in the underlying function (`this.send`). The parameters are being checked twice on the way down at runtime.
> Since `this.send` is performing these checks it seems redundant to also perform the same check in every command method. It should be possible to write the underlying function type signature in such a way that that it accepts the various overload calls; that's kind of the point of overloading, to accept multiple kinds of input.

### Describe the solution you'd like
Explore removing function overrides from aggregated clients, which would reduce client size a little.

### Additional context
Refs: https://github.com/aws/aws-sdk-js-v3/pull/2097#discussion_r586719065

**Comment by kyeotic** [comment]
This is still an issue

**Comment by kyeotic** [comment]
This is still an issue

**Comment by RanVaknin** [comment]
Hi @kyeotic ,

Im closing this because this was addressed here https://github.com/aws/aws-sdk-js-v3/pull/4639

If you need anything else, let us know.
Thanks,
Ran~
