### ISSUE TITLE
DynamoDB - Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by antoineaws** [aws/aws-sdk-js-v3#2117]
## Describe the bug
The @aws-sdk/client-dynamodb is throwing an ambiguous error 'Cannot read property '0' of undefined' . I am using sdk v3.8.0. It was working great with the previous sdk using DocumentClient instead.

#### SDK version number
`@aws-sdk/client-dynamodb@3.8.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`
v14.15.4

## Steps to reproduce
Run the following command to start local debugging: 
`sam local start-api -d 9999`

Create a simple dynamo db table and a secondary index.
Create a lambda function with the following code:
```
const docClient = new DynamoDB({ region: 'ca-central-1' });
const { Items } = await docClient.query({
            TableName: 'MyTable',
            IndexName: 'MyColumnIndex',
            KeyConditionExpression: "MyColumn = :myColumn",
            ExpressionAttributeValues: {
                ":myColumn": parsedBody.myColumn
            },
        });
```
The table is already created and the index as well. The previous version of the sdk worked fine.

#### Observed behavior
A clear and concise description of what happens.
An ambiguous error is thrown. 
`
Invalid lambda response received: Invalid API Gateway Response Keys: {'errorType', 'trace', 'errorMessage'} in {'errorType': 'TypeError', 'errorMessage': "Cannot read property '0' of undefined", 'trace': ["TypeError: Cannot read property '0' of undefined", '    at Object.visit (/var/task/node_modules/@aws-sdk/client-dynamodb/dist/cjs/models/models_0.js:1101:40)', '    at serializeAws_json1_0AttributeValue (/var/task/node_modules/@aws-sdk/client-dynamodb/dist/cjs/protocols/Aws_json1_0.js:4612:38)', '    at /var/task/node_modules/@aws-sdk/client-dynamodb/dist/cjs/protocols/Aws_json1_0.js:5074:20', '    at Array.reduce (<anonymous>)', '    at serializeAws_json1_0ExpressionAttributeValueMap (/var/task/node_modules/@aws-sdk/client-dynamodb/dist/cjs/protocols/Aws_json1_0.js:5068:34)', '    at serializeAws_json1_0QueryInput (/var/task/node_modules/@aws-sdk/client-dynamodb/dist/cjs/protocols/Aws_json1_0.js:5544:40)', '    at Object.serializeAws_json1_0QueryCommand (/var/task/node_modules/@aws-sdk/client-dynamodb/dist/cjs/protocols/Aws_json1_0.js:354:27)', '    at serialize (/var/task/node_modules/@aws-sdk/client-dynamodb/dist/cjs/commands/QueryCommand.js:95:30)', '    at /var/task/node_modules/@aws-sdk/middleware-serde/dist/cjs/serializerMiddleware.js:5:27', '    at /var/task/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:28']}
`

#### Expected behavior
Expected the records to be returned. 

#### Screenshots
N/A

## Additional context
N/A

**Comment by antawad** [comment]
I figured it out, the query "ExpressionAttributeValues" were not formatted properly. Maybe we should adjust the typing in typescript to flag this as an error?

The correct way is: **note the { S: parsedBody.myColumn }**
```
const { Items } = await docClient.query({
            TableName: 'MyTable',
            IndexName: 'MyColumn',
            KeyConditionExpression: "MyColumn = :myColumn",
            ExpressionAttributeValues: {
                ":myColumn": { S: parsedBody.myColumn }
            },
        });
```

**Comment by ajredniwja** [comment]
Hey @antawad, thanks for opening this issue, I believe its more of a client side usage mistake as when using `DynamoDb DocumentClient` you dont have to mention the attribute type with `ExpressionAttributeValues`, while with the normal client you would. 

The `documentClient` has been implemented in this version of the SDK as well, see https://github.com/aws/aws-sdk-js-v3/pull/2097
