### ISSUE TITLE
S3RequestPresigner ignores the port part of the endpoint URL

### ISSUE THREAD

**Issue by egorFiNE** [aws/aws-sdk-js-v3#2121]
## Describe the bug
S3RequestPresigner ignores the non-standard port number in non-standard endpoints when calculating V4 signature.

## Your environment
node v15.10.0

#### SDK version number
`@aws-sdk/s3-request-presigner@3.8.0`

## Steps to reproduce
See https://github.com/minio/minio/issues/11743. This ticket contains the detailed description, steps to reproduce, a minimal testcase and the resulting fix for aws-sdk. 

#### Observed behavior
In the rare case the S3 endpoint is not standard with the port number specified, the `S3RequestPresigner.presign()` calculates signature based on host part only, disregarding the port part. This ends up calculating invalid signature for this endpoint. 

This is a regression over aws-sdk v2, as the V4 signature in aws-sdk v2 is calculated correctly (see testcase in the referenced ticket above). 

#### Expected behavior
Port number is included in signature calculation and the signature is valid. 

## Additional context
This has been discovered when I was trying to use aws-sdk v3 with [min.io](https://min.io), a storage server with S3-compatible API.

**Comment by ajredniwja** [comment]
https://github.com/aws/aws-sdk-js-v3/issues/1399 Duplicate

**Comment by egorFiNE** [comment]
@AllanZhengYP looks like `path` part of this issue has been fixed in #1399 but it seems that the `port` issue persists. 

Probably this ticket isn't a duplicate anymore?

**Comment by egorFiNE** [comment]
@elszczepano thank you very much for this trick! It's a life saver for us: due to it we were able to get rid of port forwarding today in our project!

**Comment by andreaspalsson** [comment]
It looks like presigner actually have support for adding the `port` to the `host` header but only does it if the `host` haven't been set before calling `presign`. 

```javascript
    if (!requestToSign.headers["host"]) {
      requestToSign.headers.host = requestToSign.hostname;
      if (requestToSign.port) {
        requestToSign.headers.host = `${requestToSign.headers.host}:${requestToSign.port}`;
      }
    }
    return this.signer.presign(requestToSign, {
``` 
https://github.com/aws/aws-sdk-js-v3/blob/main/packages/s3-request-presigner/src/presigner.ts#L44

However it seems, at least in my case using `import { S3Client } from '@aws-sdk/client-s3';` and no extra middleware, that something else sets the `host` header which doesn't adds the `port` before reaching the `presign` function so this code never gets used.

My workaround for now is to add a middleware before the `presignInterceptMiddleware` that delete the `host` header so it will be set by `presign`

```javascript
client.middlewareStack.addRelativeTo((next, _context) => async (args) => {
  // Remove host header to allow presign to set it.
  delete args.request.headers['host'];

  return next(args);
},{
  name: 'presignHostHeaderFixMiddleware',
  relation: 'before',
  toMiddleware: 'presignInterceptMiddleware',
  override: true,
});
```

**Comment by cforgeard** [comment]
Another workaround available on StackOverflow :[https://stackoverflow.com/a/72816365](https://stackoverflow.com/a/72816365)
