### ISSUE TITLE
GetObjectCommand returning empty Body

### ISSUE THREAD

**Issue by ash0x0** [aws/aws-sdk-js-v3#2122]
## Describe the bug
`@aws-sdk/client-s3` command `GetObjectCommand` returns a result with empty `Body` field. All other commands work fine on the target bucket and the access configuration for the bucket and the key pair used was verified. The only issue is with `GetObjectCommand` not having a `Body`

## Your environment
Windows 10 build 1909

#### SDK version number
` @aws-sdk/client-s3@3.8.0`

#### Is the issue in the browser/Node.js/ReactNative?
Browser/Node.js

#### Details of the browser/Node.js/ReactNative version
Node v14.15.4, Create React App with `react-scripts@4.0.3`

## Steps to reproduce
```js
const { GetObjectCommand } = require('@aws-sdk/client-s3');

const { S3Client } = require('@aws-sdk/client-s3');

const region = process.env.REACT_APP_AWS_REGION;
const accessKeyId = process.env.REACT_APP_AWS_ACCESS_KEY_ID;
const secretAccessKey = process.env.REACT_APP_AWS_SECRET_ACCESS_KEY;
const releaseBucket = process.env.REACT_APP_S3_RELEASE_BUCKET_NAME;

const clientConfig = {
  region,
  credentials: {
    accessKeyId,
    secretAccessKey,
  },
};

class AWSClient {
  constructor() {
    this.s3 = new S3Client(clientConfig);
    this.objectName = 'test.yml';
  }

  async getLatestVersion() {
    const result = await this.s3.send(
      new GetObjectCommand({
        Bucket: releaseBucket,
        Key: this.objectName,
      })
    );
    console.info(`Got result ${JSON.stringify(result)}`);
  }
}
```

#### Observed behavior
The console output of the command result is 
```
Got result {"$metadata":{"httpStatusCode":200,"attempts":1,"totalRetryDelay":0},"Body":{},"ContentType":"application//octet-stream","LastModified":"2021-03-09T21:12:22.000Z","Metadata":{}}
```

#### Expected behavior
Getting the object in the response `Body`

## Additional context
The target S3 bucket has the following CORS configuration:
```
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "HEAD",
            "GET",
            "POST"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": []
    }
]
```
Has public access turned on fully, for both ACLs and objects. The AWS access key pair used has complete access to the bucket and the account. The issue still persists that `GetObjectCommand` returns empty `Body`. Other commands such as `PutObject` and `ListObject` work fine.

**Comment by m-radzikowski** [comment]
The body is now a ReadableStream, not a string like previously. It's not printed after you stringify it. See how to handle it here: https://github.com/aws/aws-sdk-js-v3/issues/1096#issuecomment-620900466

**Comment by trivikr** [comment]
> The body is now a ReadableStream, not a string like previously. It's not printed after you stringify it. See how to handle it here: [#1096 (comment)](https://github.com/aws/aws-sdk-js-v3/issues/1096#issuecomment-620900466)

@ash0x0 Is body returned as a ReadableStream for you?

**Comment by ash0x0** [comment]
@trivikr @m-radzikowski thanks for the replies, apologies for not getting back. I was doing this in the midst of a crunch and I gave up on it and missed the replies. Going back to it now it does return a ReadableStream and https://github.com/aws/aws-sdk-js-v3/issues/1096#issuecomment-620900466 works so it was user error. 
This probably needs a doc update. I can't find the repo for it though, can someone point me to it?
