### ISSUE TITLE
Suggestion - Lambda - InvokeCommandInput should accept a json object

### ISSUE THREAD

**Issue by antoineaws** [aws/aws-sdk-js-v3#2123]
### Is your feature request related to a problem? Please describe.
The SDK v3 for Lambda javascript function "InvokeCommand" takes in an InvocationRequest as input.
The InvocationRequest takes in a couple input, specifically the payload property is a uint8array.
So clients using the sdk v3 will need to always convert the object to a uint8array, we should do that for them under the hood.

### Describe the solution you'd like
We should allow the payload to be a JSON object/string similar to the v2 sdk. 

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-lambda/modules/invocationrequest.html
https://github.com/aws/aws-sdk-js-v3/blob/49e2d61c80/clients/client-lambda/models/models_0.ts#L3122

### Describe alternatives you've considered
I have considered reverting back to v2. 

### Additional context
N/A

**Comment by fcwheat** [comment]
I'd also like to see this for the `client-iot-data-plane` `PublishRequest` interface.
https://github.com/aws/aws-sdk-js-v3/blob/1c47c181/clients/client-iot-data-plane/models/models_0.ts#L303
I'd imagine there are quite a few other `payload` fields that are behaving this way.

**Comment by antoineaws** [comment]
Team, we should keep this open until we hear back from the sdk team. (Adding this comment to flag request active)
