### ISSUE TITLE
No WebSocket support on client-api-gateway

### ISSUE THREAD

**Issue by jeanlescure** [aws/aws-sdk-js-v3#2124]
## Describe the bug
I have been successfully migrating many back-end projects to use aws-sdk-js-v3, yet I have encountered a blocker in migrating our WebSocket code-base since it uses the method:

```
AWS.ApiGatewayManagementApi().postToConnection(ConnectionId)
```

There is no equivalent method in `client-api-gateway` and furthermore, looking into the code, under the `protocols` directory there is only a definition for REST (HTTP):

https://github.com/aws/aws-sdk-js-v3/tree/main/clients/client-api-gateway/protocols

## Your environment

Not relevant.

#### Is the issue in the browser/Node.js/ReactNative?

Node.js

#### Details of the browser/Node.js/ReactNative version

Not relevant.

## Steps to reproduce

Simply try to use `@aws-sdk/client-api-gateway` to send a message to a client connected to a WebSocket API Gateway using said client's `ConnectionId`.

#### Observed behavior

There is no way to use `aws-sdk-js-v3` to send a message to a client connected to a WebSocket API Gateway using said client's `ConnectionId` (documented or otherwise).

#### Expected behavior

To have support for all features in the previous version of aws-sdk for javascript.

**Comment by jeanlescure** [comment]
I have found what I was looking for on `@aws-sdk/client-apigatewaymanagementapi` (specifically the `PostToConnectionCommand` class). Needless to say migrating to `aws-sdk-js-v3` is more of an archaeological feat. Are there any plans to have official AWS documentation updated to point developers/customers in the right direction when doing this sort of work?

**Comment by m-radzikowski** [comment]
The structure of the modules is the same for all AWS SDKs and CLI. Just like you had separate classes [AWS.APIGateway](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/APIGateway.html) and [ApiGatewayManagementApi](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ApiGatewayManagementApi.html) in v2, you now have [APIGatewayClient](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-api-gateway/index.html) and [ApiGatewayManagementApiClient](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-apigatewaymanagementapi/index.html). The same you will find in the [AWS CLI structure](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/index.html).

Although, with migration to v3, pay attention that sending messages to websocket is currently broken in v3: #1830

**Comment by jeanlescure** [comment]
Thanks @m-radzikowski . I had stumbled upon the error you mention and have been active on #1830

As you say, sending messages to websocket is currently broken in v3. Hope this gets fixed ASAP 🤞🏼 

Back to this issue, I shall close it since the original description was based on the wrong assumption that I had to use `@aws-sdk/client-api-gateway` to send messages to WebSocket API Gateway, but the reality was that I had to use `@aws-sdk/client-apigatewaymanagementapi`.

Cheers
