### ISSUE TITLE
util-dynamodb TypeScript Errors: Cannot find name 'Blob' Cannot find name 'File'

### ISSUE THREAD

**Issue by fishcharlie** [aws/aws-sdk-js-v3#2125]
## Describe the bug

I get the following TypeScript build errors when trying to use util-dynamodb:

```
node_modules/@aws-sdk/util-dynamodb/types/models.d.ts:19:59 - error TS2304: Cannot find name 'Blob'.

19 export declare type NativeAttributeBinary = ArrayBuffer | Blob | Buffer | DataView | File | Int8Array | Uint8Array | Uint8ClampedArray | Int16Array | Uint16Array | Int32Array | Uint32Array | Float32Array | Float64Array | BigInt64Array | BigUint64Array;
                                                             ~~~~

node_modules/@aws-sdk/util-dynamodb/types/models.d.ts:19:86 - error TS2304: Cannot find name 'File'.

19 export declare type NativeAttributeBinary = ArrayBuffer | Blob | Buffer | DataView | File | Int8Array | Uint8Array | Uint8ClampedArray | Int16Array | Uint16Array | Int32Array | Uint32Array | Float32Array | Float64Array | BigInt64Array | BigUint64Array;
                                                                                        ~~~~
```

You can also find an example of this at: https://github.com/dynamoose/dynamoose/tree/awssdkv3.

#### SDK version number
`@aws-sdk/util-dynamodb@3.8.0`

#### Is the issue in the browser/Node.js/ReactNative?

Node.js

#### Details of the browser/Node.js/ReactNative version

v15.8.0

#### TypeScript Version

v4.0.5

## Steps to reproduce

`import DynamoDBUtil = require("@aws-sdk/util-dynamodb");` within TypeScript project.

#### Observed behavior

See attached screenshot or error log in Summary.

#### Expected behavior

No errors.

#### Screenshots

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/860375/110730300-77a52800-81dd-11eb-8b8b-bd819ca5a3d5.png">

**Comment by fishcharlie** [comment]
I'd be happy to submit a PR for this (if it'd help get a fix out faster). But not sure what the fix should be. Should we just remove the `Blob` & `File` types from `NativeAttributeBinary`? Or what was the original intention here?

**Comment by G-Rath** [comment]
@fishcharlie the issue is because the sdks are designed to work in both Node and browsers, meaning its using types from the DOM lib without providing default interfaces.

You can either use the `dom` lib or define the missing interfaces:

```
// some @aws-sdk clients references these DOM lib interfaces,
// so we need them to exist to compile without having DOM.
declare global {
  /* eslint-disable @typescript-eslint/no-empty-interface */
  interface Blob {}
  interface File {}
  /* eslint-enable @typescript-eslint/no-empty-interface */
}
```

I'd only recommend using the `dom` lib if your project is meant to be used in the browser, since doing so will mean all the interfaces & globals defined for the DOM will be usable without error, which'll at best put your project in the same situation as aws-sdk-js-v3 is in now, or at worse introduce runtime bugs.
