### ISSUE TITLE
Kinesis `SubscribeToShardCommand` call does not resolve

### ISSUE THREAD

**Issue by stepanrx** [aws/aws-sdk-js-v3#2131]
## Describe the bug
Calling `SubscribeToShardCommand` on kinesis client never resolves.

#### SDK version number
`    "@aws-sdk/client-kinesis": "^3.8.1",`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
```
▶ node -v
v12.16.1
```

## Steps to reproduce
```
import { KinesisClient, SubscribeToShardCommand  } from '@aws-sdk/client-kinesis';

const client = new KinesisClient({ region: 'us-west-2' });
const params = {
  ConsumerARN: 'my-consumer-arn',
  ShardId: 'my-shard-id',
  StartingPosition: { Type: 'TRIM_HORIZON' },
};
const command = new SubscribeToShardCommand(params);
const data = await client.send(command); // <-- never resolves
```

**Comment by BKurzawa** [comment]
The same thing is happening to me with the exception that the promise does eventually resolve after 5 minutes with the following error 
> SyntaxError: Unexpected token in JSON at position 0
at JSON.parse (<anonymous>)
    at Aws_json1_1.ts:4020

**Comment by BKurzawa** [comment]
Same thing is happening to me except the promise resolves after 5 minutes with the following error:

```
SyntaxError:` Unexpected token in JSON at position 0
at JSON.parse (<anonymous>)
    at Aws_json1_1.ts:4020
```

**Comment by alexstar2008** [comment]
Have the same case as @BKurzawa

**Comment by alexstar2008** [comment]
@AllanZhengYP
@trivikr

**Comment by ajredniwja** [comment]
@alexstar2008 @stepanrx @BKurzawa  is this still and issue with latest version of the SDK?

**Comment by francescopace** [comment]
> @alexstar2008 @stepanrx @BKurzawa is this still and issue with latest version of the SDK?

same behavior with SDK verion 3.24.0

**Comment by vudh1** [comment]
@francescopace do you still have same issue with the latest version `3.41.0`? I am not able to reproduce, if you have updated to the latest version and still experience the same problem, please provide a sample reproducible code so we can help you better?

**Comment by francescopace** [comment]
> @francescopace do you still have same issue with the latest version `3.41.0`? I am not able to reproduce, if you have updated to the latest version and still experience the same problem, please provide a sample reproducible code so we can help you better?

I'm sorry but same as before.

here a sample code to reproduce the issue:
```

'use strict';

const { KinesisClient,
        PutRecordCommand,
        ListStreamConsumersCommand,
        RegisterStreamConsumerCommand,
        SubscribeToShardCommand  } = require("@aws-sdk/client-kinesis");

const StreamName = "mystream";
const region = "eu-central-1";
const accountId = "000000000000";
const ConsumerName = "myconsumer";
const PartitionKey = 'mypartitionkey';
const StreamARN = 'arn:aws:kinesis:'+region+':'+accountId+':stream/'+StreamName;

const client = new KinesisClient({region});

async function test(){

    //put some data
    const {ShardId, SequenceNumber} = await client.send(new PutRecordCommand({
        StreamName,
        PartitionKey,
        Data: Buffer.from('foo')
    }));

    //put some more data
    await client.send(new PutRecordCommand({
        StreamName,
        PartitionKey,
        Data: Buffer.from('bar')
    }));

    //recover a consumer or create a new one
    let { Consumers } = await client.send(new ListStreamConsumersCommand({StreamARN}));
    let consumer = Consumers.find((x) => x.ConsumerName == ConsumerName);
    if(!consumer){
        let {Consumer} = await client.send(new RegisterStreamConsumerCommand({StreamARN, ConsumerName}));
        consumer = Consumer;
    }

    //subscribe to shard
    const {EventStream} = await client.send(new SubscribeToShardCommand({ // <-- never resolves
        ConsumerARN: consumer.ConsumerARN,
        ShardId: ShardId,
        //StartingPosition: { Type: 'AT_SEQUENCE_NUMBER', SequenceNumber}
        StartingPosition: { Type: 'TRIM_HORIZON' },
    }));

    console.log('successfully subscribed'); // <-- never log

}

test();
```

**Comment by samlaycock** [comment]
I'm also seeing the same problem

**Comment by tribute2ro** [comment]
I'm experiencing the same problem as well. I'm using version `3.44.0`.

**Comment by vudh1** [comment]
Hi all, we are aware of this issue and in progress of fixing this.

**Comment by karkinkar** [comment]
Hello,
Any news on the matter? the issue is still there.

**Comment by wr-jramani** [comment]
@vudh1 Any updates on this, please?

**Comment by BDNilsson** [comment]
@vudh1 Any updates? 

I am a bit confused, I was under the impression kinesis had HTTP/2 support back in 2018? 

And nodejs also has http/2 support.

Why would the SDK take years to add http/2 support but release functions that don't work - that as far as i can see fail in the most basic of tests - what am i missing?

**Comment by tusharf5** [comment]
This is probably one of the most common features to be used by the kinesis fan-out consumer. Very disappointed that it doesn't work. What's the point of having it in the sdk. 👎🏻

**Comment by postsa** [comment]
I'm confused as well, I'm trying to understand this issue in the context of this document https://aws.amazon.com/blogs/aws/kds-enhanced-fanout/

which claims that 
> Enhanced fan-out and the new HTTP/2 SubscribeToShard API are both available now in all regions for new streams and existing streams

in August 2018. 

Similar to those above, my subscribe to shard requests succeed according to the monitoring available in the AWS console (`SubscribeToShard.Success` is incremented for the registered consumer) but the promise rejects after 5 minutes and I never get access to the underlying event stream or established Http2 connection. Are we sure this is a Kinesis issue and not an SDK issue? If it's Kinesis then that doc has been wrong for almost 4 years. I'm using version `3.67.0` of `client-kinesis`.

**Comment by tusharf5** [comment]
It's definitely not a kinesis issue. Aws node sdk doesn't support http/2 sessions which is the tech used by kinesis  fanout feature. 

I had to switch our consumer app to golang and it works perfectly fine with go aws sdk v2.
