### ISSUE TITLE
Module not found: Can't resolve 'fs' in 'node_modules/@aws-sdk/lib-storage/dist/es'

### ISSUE THREAD

**Issue by fedecastelli** [aws/aws-sdk-js-v3#2136]
## Describe the bug
Trying to upload a big file using multipart upload. From my React App, I'm using the method `Upload`  from the `@aws-sdk/lib-storage@3.8.1` but I'm getting this error:

```bash
node_modules/@aws-sdk/lib-storage/dist/es/bytelength.js
Module not found: Can't resolve 'fs' in '/node_modules/@aws-sdk/lib-storage/dist/es'
```

#### SDK version number
`@aws-sdk/client-s3@3.8.1`
`@aws-sdk/lib-storage@3.8.1`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Node Version: 12.16.3

## Steps to reproduce

```nodejs
let credentials = await Auth.currentCredentials();
let paralellUploadS3 = new Upload({
  client: new S3Client({
    apiVersion: '2012-08-10',
    credentials: Auth.essentialCredentials(credentials),
    region: "ca-cenral-1"
  }),
  params: {
    Bucket: 'example-bucket-s3',
    Key: 'key-file.zip',
    Body: myBody
  }
});
```

An issue was already open but it has been closed without fixing it. Reference to https://github.com/aws/aws-sdk-js-v3/issues/1688#issuecomment-786726628

**Comment by 70nyIT** [comment]
I can confirm, I'm having the same issue on a React App I was working on.

**Comment by 70nyIT** [comment]
Might reference to https://github.com/aws/aws-sdk-js-v3/issues/1688#issuecomment-786726628_

**Comment by kelvilee** [comment]
Running into the same issue on browser as well. I found downgrading to `@aws-sdk/lib-storage@3.7.0` generates a warning instead on missing `fs` module.

**Comment by alexforsyth** [comment]
Looking at this right now! I agree this is not ideal at all. We shouldn't even be generating that warning

**Comment by nighttiger1990** [comment]
same issue! error occurs instead of warning
SDK version number
`@aws-sdk/client-s3@3.8.1`
`@aws-sdk/lib-storage@3.8.1`
