### ISSUE TITLE
Incorrect XML payload is generated when issuing a "CompleteMultipartUpload" s3 api 

### ISSUE THREAD

**Issue by sn-satyendra** [aws/aws-sdk-js-v3#2139]
## Describe the bug
During the multipart uploads, when we try to complete the upload by using `CompleteMultipartUploadCommand`, the payload is generated incorrectly. The root xml node should have name as `CompleteMultipartUpload` but instead it has a name `CompletedMultipartUpload` (Additional `d`) as per the [api docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CompleteMultipartUpload.html). The issue seems to be in the generated [client](https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-s3/protocols/Aws_restXml.ts#L10219).

#### SDK version number
`@aws-sdk/client-s3@3.3.0`
The issue seems to be valid even for the recent versions. 

#### Is the issue in the browser/Node.js/ReactNative?
Browser/Node.js/ReactNative

#### Details of the browser/Node.js/ReactNative version
v10.17.0

## Steps to reproduce
1. Create a multipart upload request.
2. Once all the parts are uploaded successfully, initiate a completeMultipartUpload:
```
function completeUpload(UploadId, parts) {
  const { ETag } = await client.send(
    new CompleteMultipartUploadCommand({
      ...params,
      MultipartUpload: {
        Parts: parts.map((et, index) => ({
          ETag: et,
          PartNumber: index + 1,
        })),
      },
      UploadId,
    })
  );
}
```

#### Observed behavior
Step 2 above will generate an incorrect payload similar to below:
```
<?xml version="1.0" encoding="UTF-8"?>
<CompletedMultipartUpload xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <Part>
    <ETag>"3w456fc9258ed13efbd321bcff86e00a"</ETag>
    <PartNumber>1</PartNumber>
  </Part>
  <Part>
    <ETag>"b98e967c0b865fd3726d43f636eb9876"</ETag>
    <PartNumber>2</PartNumber>
  </Part>
</CompletedMultipartUpload>
```

#### Expected behavior
After step 2, payload should have been:
```
<?xml version="1.0" encoding="UTF-8"?>
<CompleteMultipartUpload xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <Part>
    <ETag>"3w456fc9258ed13efbd321bcff86e00a"</ETag>
    <PartNumber>1</PartNumber>
  </Part>
  <Part>
    <ETag>"b98e967c0b865fd3726d43f636eb9876"</ETag>
    <PartNumber>2</PartNumber>
  </Part>
</CompleteMultipartUpload>
```

**Comment by alexforsyth** [comment]
Hey this is an awesome catch! Let me escalate this internally

**Comment by trivikr** [comment]
Is this a bug?

The shape name for MultipartUpload is CompletedMultipartUpload even in v2 models: https://github.com/aws/aws-sdk-js/blob/17245a8c612ddd3cfe01b0c45e70cfbb557b62d1/apis/s3-2006-03-01.normal.json#L2055-L2062

I visited that issue while verifying models update in https://github.com/aws/aws-sdk-js-v3/pull/2258

**Comment by sn-satyendra** [comment]
@trivikr : This might be a bug with v2 as well (although I have not tested the payload generated with v2 sdk). The problem is that request payload is not complaint with what the s3 api [spec](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CompleteMultipartUpload.html#API_CompleteMultipartUpload_RequestSyntax) documents.
