### ISSUE TITLE
Incorrect XML payload is generated when issuing a "PutBucketLifecycleConfiguration" s3 api

### ISSUE THREAD

**Issue by sn-satyendra** [aws/aws-sdk-js-v3#2140]
## Describe the bug
When we try to update the bucket lifecycle rules by using `PutBucketLifecycleConfigurationCommand` it generates an incorrect root node in the xml payload. The root node is called as `BucketLifecycleConfiguration` instead of `LifecycleConfiguration` as mentioned in the [api docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/lifecycle-configuration-examples.html). The issue is in the generated [client](https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-s3/protocols/Aws_restXml.ts#L10195).

#### SDK version number
`@aws-sdk/client-s3@3.3.0`
The issue seems to be valid even for the recent versions.

#### Is the issue in the browser/Node.js/ReactNative?
Browser/Node.js/ReactNative

#### Details of the browser/Node.js/ReactNative version
v10.17.0

## Steps to reproduce
1. Use `PutBucketLifecycleConfigurationCommand` to save some lifecycle rules for a bucket:
```
async function saveRules(bucketName, rules = []) {
  const data = await client.send(new PutBucketLifecycleConfigurationCommand({
    Bucket: bucketName,
    LifecycleConfiguration: {
      Rules: rules
    }
  }));
  return data;
}
```

#### Observed behavior
The xml payload is generated incorrectly:
```
<?xml version="1.0" encoding="UTF-8"?>
<BucketLifecycleConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <Rule>
    <Expiration>
      <Days>34</Days>
    </Expiration>
    <ID>test-rule-1</ID>
    <Filter>
      <Prefix>p1/</Prefix>
    </Filter>
    <Status>Enabled</Status>
  </Rule>
</BucketLifecycleConfiguration>
```

#### Expected behavior
Payload should be:
```
<?xml version="1.0" encoding="UTF-8"?>
<LifecycleConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <Rule>
    <Expiration>
      <Days>34</Days>
    </Expiration>
    <ID>test-rule-1</ID>
    <Filter>
      <Prefix>p1/</Prefix>
    </Filter>
    <Status>Enabled</Status>
  </Rule>
</LifecycleConfiguration>
```

**Comment by alexforsyth** [comment]
This is being looked at internally. Thanks so much for the bug report. I'll keep these tickets updated as I get more information that I can share

**Comment by sgouache** [comment]
Submitted patch
#2162

**Comment by trivikr** [comment]
Should this be a bug?

The shape name for LifeCycleConfiguration is BucketLifeCycleConfiguration even in v2 https://github.com/aws/aws-sdk-js/blob/17245a8c612ddd3cfe01b0c45e70cfbb557b62d1/apis/s3-2006-03-01.normal.json#L7842-L7855

I visited this issue while analyzing model updates for clients in https://github.com/aws/aws-sdk-js-v3/pull/2258

**Comment by trivikr** [comment]
Verified that LifeCycleConfiguration is added in Bucket in both cases:
* When payload is `<LifecycleConfiguration>`
* When payload is `<BucketLifecycleConfiguration>`

Code changed in https://github.com/aws/aws-sdk-js-v3/blob/da2c0852df6bc64cbd397489f2a8d1aea5d88c6f/clients/client-s3/protocols/Aws_restXml.ts#L10193
The body tag console.log at https://github.com/aws/aws-sdk-js-v3/blob/da2c0852df6bc64cbd397489f2a8d1aea5d88c6f/clients/client-s3/protocols/Aws_restXml.ts#L3439

<details>
<summary>Code used for testing</summary>

```js
const { S3, waitForBucketExists } = require("@aws-sdk/client-s3");

(async () => {
  const region = "us-west-2";
  const client = new S3({ region });

  const Bucket = `test-bucket-${Date.now()}`;
  await client.createBucket({ Bucket });
  await waitForBucketExists({ client }, { Bucket });

  await client.putBucketLifecycleConfiguration({
    Bucket,
    LifecycleConfiguration: {
      Rules: [
        {
          Expiration: {
            Days: 7,
          },
          Filter: {
            Prefix: "",
          },
          Status: "Enabled",
        },
      ],
    },
  });
  console.log(await client.getBucketLifecycleConfiguration({ Bucket }));
  await client.deleteBucketLifecycle({ Bucket });

  await client.deleteBucket({ Bucket });
})();

```

</details>

<details>
<summary>console.log output for body</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?><BucketLifecycleConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Rule><Expiration><Days>7</Days></Expiration><Filter><Prefix></Prefix></Filter><Status>Enabled</Status></Rule></BucketLifecycleConfiguration>
```

```xml
<?xml version="1.0" encoding="UTF-8"?><LifecycleConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Rule><Expiration><Days>7</Days></Expiration><Filter><Prefix></Prefix></Filter><Status>Enabled</Status></Rule></LifecycleConfiguration>
```

</details>

**Comment by trivikr** [comment]
Verified that v2 sends `LifeCycleConfiguration` by console.log `req.httpRequest.body` in `populateBody` https://github.com/aws/aws-sdk-js/blob/17245a8c612ddd3cfe01b0c45e70cfbb557b62d1/lib/protocol/rest_xml.js#L26

<details>
<summary>Code</summary>

```js
const AWS = require("aws-sdk");

(async () => {
  const region = "us-west-2";
  const client = new AWS.S3({ region });

  const Bucket = `test-bucket-${Date.now()}`;
  await client.createBucket({ Bucket }).promise();
  await client.waitFor("bucketExists", { Bucket }).promise();

  await client
    .putBucketLifecycleConfiguration({
      Bucket,
      LifecycleConfiguration: {
        Rules: [
          {
            Expiration: {
              Days: 7,
            },
            Filter: {
              Prefix: "",
            },
            Status: "Enabled",
          },
        ],
      },
    })
    .promise();

  console.log(
    await client.getBucketLifecycleConfiguration({ Bucket }).promise()
  );

  await client.deleteBucket({ Bucket }).promise();
})();

```

</details>

<details>
<summary>Output</summary>

```console
<LifecycleConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Rule><Expiration><Days>7</Days></Expiration><Filter><Prefix></Prefix></Filter><Status>Enabled</Status></Rule></LifecycleConfiguration>
```

</details>

**Comment by trivikr** [comment]
The fix is to replace `nodeName` with `memberName` in XmlShapeSerVisitor https://github.com/aws/aws-sdk-js-v3/blob/da2c0852df6bc64cbd397489f2a8d1aea5d88c6f/codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlShapeSerVisitor.java#L195-L196

where
```java
String memberName = symbolProvider.toMemberName(documentBindings.get(0).getMember());
```

**Comment by trivikr** [comment]
The codegen is not able to read XmlTrait from shape while serializing structure https://github.com/aws/aws-sdk-js-v3/blob/da2c0852df6bc64cbd397489f2a8d1aea5d88c6f/codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlShapeSerVisitor.java#L190-L193

Confirmed that the xmlName trait is present on LifecycleConfiguration https://github.com/aws/aws-sdk-js-v3/blob/4f9f4a79b019c1c35530e05c4138fde88a6fb547/codegen/sdk-codegen/aws-models/s3.2006-03-01.json#L9558-L9566

Smithy documentation on xmlName trait https://awslabs.github.io/smithy/1.0/spec/core/xml-traits.html#xmlname-trait

**Comment by robcresswell** [comment]
@alexforsyth @ajredniwja Is this going to be fixed? Its still broken in the latest client and judging from the reports seems to have been broken for over 6 months?

**Comment by robcresswell** [comment]
What a great way to deal with bugs 😂 Wait long enough and pretend its not a problem any more.
