### ISSUE TITLE
Body Data is unsupported format, expected data to be one of: string | Uint8Array | Buffer | Readable | ReadableStream | Blob

### ISSUE THREAD

**Issue by kelvilee** [aws/aws-sdk-js-v3#2145]
## Describe the bug
Upgrading from `v2` and I'm running into an issue with using `Upload` from `@aws-sdk/lib-storage@3.8.1` to upload a file. Failing on Safari but works on both Chrome and Firefox. Getting this error:

`Body Data is unsupported format, expected data to be one of: string | Uint8Array | Buffer | Readable | ReadableStream | Blob`

#### SDK version number
`@aws-sdk/client-s3@3.8.1`
`@aws-sdk/lib-storage@3.8.1`
`@aws-sdk/credential-provider-cognito-identity@3.8.1`
`@aws-sdk/client-cognito-identity@3.8.1`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Browsers:
    Chrome: 89.0.4389.90
    Firefox: 84.0.2
    Safari: 14.0.3
Node:
    v12.18.4

## Steps to reproduce
```JavaScript
const options = {
  region: 'us-east-1',
  credentials: fromCognitoIdentityPool({
    client: new CognitoIdentityClient({
      region: 'us-east-1'
    }),
    identityPoolId: identityPoolId
  }),
  apiVersion: 'latest',
  maxRetries: 3,
  correctClockSkew: true,
  systemClockOffset: offset,
  useAccelerateEndpoint: true
};

const target = {
  Key: processingKey,
  Bucket: processingBucket,
  ContentType: file.type,
  Body: file
};

const upload = new Upload({
  client: new S3Client(options),
  params: target
});

upload.on('httpUploadProgress', evt => {
  console.log(evt);
});

const data = await upload.done()
```

#### Observed behavior
Upload failing on Safari due to error `Body Data is unsupported format, expected data to be one of: string | Uint8Array | Buffer | Readable | ReadableStream | Blob`

#### Expected behavior
Upload should be successful on Safari

**Comment by ajredniwja** [comment]
Hi @kelvilee thanks for opening this issue, can you share the full code example basically how you are pulling the image.

**Comment by ajredniwja** [comment]
I was able to reproduce this using the code I I mentioned in: https://github.com/aws/aws-sdk-js-v3/issues/2183

**Comment by kelvilee** [comment]
@ajredniwja did a little investigating and found that when trying to upload an image on safari `Blob.prototype.stream()` is missing and doesn't satisfy this [condition](https://github.com/aws/aws-sdk-js-v3/blob/89403aa78aca4078e2dda60250e88329ae085d26/lib/lib-storage/src/chunker.ts#L19) as it normally would. 

Not sure what kind of solution would be appropriate here.

**Comment by ajredniwja** [comment]
Hey @kelvilee, you are right, it happens because Safari didn't implement `Blob.prototype.stream` till `14.0`.

I have tried using the same code mentioned above and everything seems to work in Safari `14.1.1`. Would you be able to check as well?

**Comment by ludwighen** [comment]
I just tested my implementation that failed in earlier safari versions and I can confirm it works in 14.1.1.
First of all, thanks for sharing this. Second, is there any fallback or workaround for earlier safari versions?

**Comment by ajredniwja** [comment]
We are trying to get to a solution for it as reading entire file in memory is not ideal. More on that in this issue https://github.com/aws/aws-sdk-js-v3/issues/2365
I will keep the issue open and update you accordingly.

**Comment by kelvilee** [comment]
Thanks for the update @ajredniwja. I can confirm updating to Safari `14.1.1` fixes the issue but I won't be upgrading from v2 to v3 until this issue is resolved for previous versions of Safari. Looking forward to any updates you have on the fix!

**Comment by kelvilee** [comment]
Hi @ajredniwja! Just checking in if there are any updates on this bug? I've updated the packages to `3.21.0` but it's still running into the issue on Safari `13.1`

**Comment by mikkeldamsgaard** [comment]
Hi. Just if someone is still struggling with this, I found this workaround, that seems more streaming than converting to an in-mem array.
```
function safariStream(blob) {
  let position = 0;

  return new ReadableStream({
    pull: function (controller) {
      const chunk = blob.slice(position, Math.min(blob.size, position + Math.max(controller.desiredSize, 512*1024)));
      return chunk.arrayBuffer()
          .then(function (buffer) {
            const uint8array = new Uint8Array(buffer);
            const bytesRead = uint8array.byteLength;

            position += bytesRead;
            controller.enqueue(uint8array);

            if(position >= blob.size)
              controller.close();
          });
    }
  });
}
```

And I use it in the Upload function like this:
```
new Upload({
  ...
  params: { Bucket, Key,
    Body: Blob.prototype.stream?file:safariStream(file)
  }
}
```

**Comment by kelvilee** [comment]
@mikkeldamsgaard Thanks for the solution! It ended up working after a small tweak since `Blob.arrayBuffer() ` is only supported on versions after Safari 14. The solution creates a Response instance from the chunk and calls arrayBuffer on it.

Here is the working modified code
```
safariStream(blob) {
    let position = 0;

    return new ReadableStream({
      async pull(controller) {
        const chunk = blob.slice(
          position,
          Math.min(blob.size, position + Math.max(controller.desiredSize, 512 * 1024))
        );
        const buffer = await new Response(chunk).arrayBuffer();
        const uint8array = new Uint8Array(buffer);
        const bytesRead = uint8array.byteLength;

        position += bytesRead;
        controller.enqueue(uint8array);

        if (position >= blob.size) controller.close();
      }
    });
}
```

**Comment by AllanZhengYP** [comment]
The workaround is reasonable to me. Given the error only exists for Safari <= 14 and the usage will decrease([current market share](https://www.stetic.com/market-share/browser/)), we will NOT implement the fix in SDK. You can refer to the workaround above. 

If you strongly feel we need to add the support, please create a new issue.
