### ISSUE TITLE
@aws-sdk/client-s3 160mb?

### ISSUE THREAD

**Issue by lukasa1993** [aws/aws-sdk-js-v3#2150]
is there a way to import `@aws-sdk/client-s3` just for nodejs ? i don't want to carry 160mb to upload a file

![2021-03-18 16 16 43](https://user-images.githubusercontent.com/1499012/111624955-c1a59380-8805-11eb-8b8c-eb665004c649.jpg)
![2021-03-18 16 16 40](https://user-images.githubusercontent.com/1499012/111624969-c5d1b100-8805-11eb-96a5-b447fa53a874.jpg)

**Comment by G-Rath** [comment]
One of the big reasons for this is that `react-native` and its dependencies are being pulled in due to `npm` v7 installing peerDependencies by default.

See #1536, and the respective PR to resolve this: #2108

**Comment by lukasa1993** [comment]
`npm install --only=production --legacy-peer-deps` this seems to be a workaround

**Comment by ajredniwja** [comment]
Is this still an issue?  I see https://github.com/aws/aws-sdk-js-v3/pull/2191 was merged and react-native pollyfills were removed.
