### ISSUE TITLE
[util-dynamodb]: `marshall` types allow passing `undefined` at compile time, but always throws at runtime

### ISSUE THREAD

**Issue by G-Rath** [aws/aws-sdk-js-v3#2158]
## Describe the bug

When using `marshall`, it's considered valid at compile time to pass in `undefined` but this will always throw an error at runtime.

## Your environment

Ubuntu 18.04 via WSLv1

#### SDK version number
`@aws-sdk/util-dynamodb@3.8.1`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
14.16.0

## Steps to reproduce
```
import { marshall } from '@aws-sdk/util-dynamodb';

marshall(undefined);
```

#### Observed behavior
TypeScript does not give any compiler errors.
At runtime, code throws the following:

```
Error: Pass options.removeUndefinedValues=true to remove undefined values from map/array/set.
    at Object.convertToAttr (.../node_modules/@aws-sdk/util-dynamodb/dist/cjs/convertToAttr.js:13:15)
    at Object.marshall (.../node_modules/@aws-sdk/util-dynamodb/dist/cjs/marshall.js:11:53)
```

This behaviour occurs regardless of if `{ removeUndefinedValues: true }` is passed or not.

#### Expected behavior
TypeScript gives a compiler error, preventing `undefined` being passed to `marshall`.

## Additional context

The reason for this is because the `marshall` function takes a generic which is constrained to being an object whose keys are of itself, which collapses down into `{}` which in TypeScript is equivalent to `any`.

This should be fixable by just using [`K: string` instead of `K in keyof T` (playground link)](https://www.typescriptlang.org/play?#code/PTAEGEFcCdoUwHYBdRIJ4Ac6gMYHsEBnJaAQwEtkBYAKHSwgEYAeAFQD5QBeUAb1ADaAaVCVQAazho8AM1CsAugC5QpBGgDcoAL4baIUAAVoeDHkJwAJqkzZ8REhWp1bEAExtOPfsJXFolADmyqrqWrq0tHAAHmbQKJZwOAA2pPC4BMSgALZphAAWpMnJKmygMUiIloTunuwAFJakSKQqrACU3Jy8tKB9gpJofiRBIWqatBE0+mAAAkiEALQxWDhIy7B40LS50AVFyfXtejQG80srSetwm9s0u-vF9ZAIiTKUVsc7eYVPAgpfe4-A71XjaQEPX6HfiMFQAcgAbkVIHA4ToIcCnvw4Yw4fCkckUWjwSczgtlrErhsTHdISCfAg4AB3UAAZTQ2QARnhDnDonD2iFEcjUeiTnSnoyWay4Egjhi9lD6lLQABZUgYeUaIA).

**Comment by kennu** [comment]
I just ran into this problem when passing a complex object to DynamoDB PutCommand, where the object contains a few undefined values. The error message says I could use `options.removeUndefinedValues=true` to allow them, but I don't see a way to specify that option to PutCommand.

**Comment by petermorlion** [comment]
@kennu I got the same message and fixed it by adding the option in the constructor of my DynamoDBDocumentClient. Using TypeScript:

```
const dynamoClient = DynamoDBDocumentClient.from(new DynamoDBClient({
    apiVersion: "2012-08-10",
    region: process.env.AWS_REGION
}), {
    marshallOptions: {
        removeUndefinedValues: true
    }
});
```

**Comment by kennu** [comment]
Thanks @petermorlion! I was worried my code will forget to remove some of those undefined values (which appear in responses from another AWS API), so that should make it more reliable.

**Comment by pull-task** [comment]
With the removeUndefinedValues option, it is implied that we can decide whether to process the key-value pairs that have a value of undefined or whether to filter them out. The default is to process them, that is, removeUndefinedValues: false.

As a consequence of this bug, one must set removeUndefinedValues: true to avoid the error.

Although I suspect most code would behave the same whether myKey: undefined was present or absent from the data, not all code will behave the same. 

For example: Object.keys({a:1, b: undefined, c:3}) results in [ 'a', 'b', 'c' ], while Object.keys({a:1, c:3}) results in [ 'a',  'c' ].

**Comment by G-Rath** [comment]
Just to restate my original post: this is about the types incorrectly allowing you to pass the value `undefined` to this function.

It has nothing to do with the `removeUndefinedValues` option as this function is expected to always take an object as it's top-level parameter.

**Comment by yenfryherrerafeliz** [comment]
Hi @G-Rath, thanks for opening this issue. This behavior is due to that the marshall function allows the parameter "data" to be unknown [here](https://github.com/aws/aws-sdk-js-v3/blob/cc0fee3f6fd553b4ba7d17cd9782df014ecefe01/packages/util-dynamodb/src/marshall.ts#L45), which basically allows any type of data. 

I will mark this issue to be reviewed so we can further address it.

Thanks!
