### ISSUE TITLE
Pagination utils for DynamoDB DocumentClient

### ISSUE THREAD

**Issue by m-radzikowski** [aws/aws-sdk-js-v3#2159]
### Is your feature request related to a problem? Please describe.

All paginated commands have Async Iterator util functions, like `paginateQuery` in `@aws-sdk/client-dynamodb`. But there are none in`@aws-sdk/lib-dynamodb`. So when doing paginated queries, I need to either handle the pagination myself, or handle unmarshalling myself.

### Describe the solution you'd like

Add functions like `paginateQuery` to `@aws-sdk/lib-dynamodb`, that will work with`DynamoDBDocumentClient`.

**Comment by monster-x-adventurer** [comment]
Try using the [@typemon/dynamon](https://www.npmjs.com/package/@typemon/dynamon) package. Pagination can be easily handled.
```typescript
const paginator: Dynamon.Paginator<Item> = dynamon.query$({
    tableName: 'example',
    keyConditionExpressionSpec: equal('foo', 'bar'),
});

for await (const page of paginator) {
    ...
}
```

**Comment by bluepeter** [comment]
Ping on this issue.
