### ISSUE TITLE
LifecycleConfiguration incorrectly named BucketLifecycleConfiguration

### ISSUE THREAD

**Issue by sgouache** [aws/aws-sdk-js-v3#2162]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

When trying to set lifecycle management configuration (PutBucketLifecycleConfiguration), my request fails with an indication that the submitted XML is invalid. Having looked at the code generating the request, indeed the toplevel element is "BucketLifecycleConfiguration", while it should be "LifecycleConfiguration" according to https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketLifecycleConfiguration.html

The exact message is: 
MalformedXML: request xml does not include LifecycleConfiguration

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@aws-sdk/client-s3/dist/cjs/protocols/Aws_restXml.js b/node_modules/@aws-sdk/client-s3/dist/cjs/protocols/Aws_restXml.js
index 9290461..1b11c01 100644
--- a/node_modules/@aws-sdk/client-s3/dist/cjs/protocols/Aws_restXml.js
+++ b/node_modules/@aws-sdk/client-s3/dist/cjs/protocols/Aws_restXml.js
@@ -8806,7 +8806,7 @@ const serializeAws_restXmlAnalyticsS3BucketDestination = (input, context) => {
     return bodyNode;
 };
 const serializeAws_restXmlBucketLifecycleConfiguration = (input, context) => {
-    const bodyNode = new xml_builder_1.XmlNode("BucketLifecycleConfiguration");
+    const bodyNode = new xml_builder_1.XmlNode("LifecycleConfiguration");
     if (input.Rules !== undefined && input.Rules !== null) {
         const nodes = serializeAws_restXmlLifecycleRules(input.Rules, context);
         nodes.map((node) => {
```

**Comment by sgouache** [comment]
Example invocation triggering the error:

**Comment by sgouache** [comment]
Sample invocation that exhibits the problem:

`    try {
      // Create lifecycle params
      const bucketLifecycleConfiguration = {
        Rules: [
          {
            "Expiration": {"Days":30},
            "ID":"TempUploads",
            "Filter":{"Prefix":s3prefix},
            "Status":"Enabled"
          }
        ]
      }
      
      const lifecycleParams = {
        Bucket: s3bucket,
        LifecycleConfiguration: bucketLifecycleConfiguration
      };
      const data = await s3.send(new PutBucketLifecycleConfigurationCommand(lifecycleParams));
      console.log("Success setting S3 bucket lifecycle configuration", data);
    } catch (err) {
      console.log("Error setting S3 bucket lifecycle configuration", err);
    }`

**Comment by ajredniwja** [comment]
Hey @sgouache, thanks for opening this issue, can you share what version of the package you are using? 


I ran the code:

```JavaScript
(async () => {

  const { S3 , PutBucketLifecycleConfigurationCommand } = require("@aws-sdk/client-s3");
  const client = new S3({
    region: "us-west-2",
  });
  
  try {
    // Create lifecycle params
    const bucketLifecycleConfiguration = {
      Rules: [
        {
          "Expiration": {"Days":30},
          "ID":"TempUploads",
          "Filter":{"Prefix":"xyz"},
          "Status":"Enabled"
        }
      ]
  }
  
  const lifecycleParams = {
    Bucket: "testBucket",
    LifecycleConfiguration: bucketLifecycleConfiguration
  };

  const data = await client.send(new PutBucketLifecycleConfigurationCommand(lifecycleParams));
    console.log("Success setting S3 bucket lifecycle configuration", data);
  } catch (err) {
    console.log("Error setting S3 bucket lifecycle configuration", err);
  }
})
```
I get a 200 response. 

My package version: 
```
npm view @aws-sdk/client-s3 version                                                                                                                                                                                                                                                                                                                                                 ─╯
3.9.0
```

**Comment by sgouache** [comment]
Hey @ajredniwja, thanks for your response.
I confirm that I have 3.9.0 as well.
I should have mentioned that I am accessing a company-hosted S3 service, so if the request works for you, then most likely the issue the alignment of the aws-sdk with that particular service.

Nevertheless, the link I mentioned above [https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketLifecycleConfiguration.html](url) explicitly states that the XML toplevel element should be "LifecycleConfiguration", which led me to believe my server's implementation was right in rejecting the "BucketLifecycleConfiguration" element, and hence the client was wrong.

So if you believe the client and server implementations are correct, then it is the doc might need to be updated.

**Comment by turneand** [comment]
I had the same issue and raised as #2064 previously.

**Comment by yenfryherrerafeliz** [comment]
Hi @sgouache, @turneand, this issue has been fixed and can be confirmed in the serializer for PutBucketLifecycleConfigurationCommand [here](https://github.com/aws/aws-sdk-js-v3/blob/89f97b5cea8052510471cdad69acced9f5be60d1/clients/client-s3/src/protocols/Aws_restXml.ts#L2870C35-L2870C57).

If you have any other inquires that we can help with, please feel free in opening a new issue.

Thanks!
