### ISSUE TITLE
Use path mapping in jest so that jest tests can be run without TypeScript build

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#2164]
### Is your feature request related to a problem? Please describe.
The dependencies need to be built once before tests can be run.

### Describe the solution you'd like
Use [path mapping](https://medium.com/ah-technology/a-guide-through-the-wild-wild-west-of-setting-up-a-mono-repo-part-2-adding-jest-with-a-breeze-16e08596f0de#fdf5) in Jest, so that Jest tests can be run without TypeScript build required.

**Comment by RanVaknin** [comment]
@trivikr ,

This has been opened for 3 years now and p3. If we need to address this lets open a separate ticket and assign higher priority.

Closing.
