### ISSUE TITLE
CloudFormation waiters should match those in sdk v2 (e.g. `stackExists`)

### ISSUE THREAD

**Issue by troyready** [aws/aws-sdk-js-v3#2169]
The [old sdk](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudFormation.html#waitFor-property) shipped with waiters for `stackExists`, `stackCreateComplete`, etc.

It would be ideal if versions of these stack waiters were shipped in the new sdk version, to make for smoother upgrades to v3.

**Comment by trivikr** [comment]
Waiters are [available](https://aws.amazon.com/blogs/developer/waiters-in-modular-aws-sdk-for-javascript/) in AWS SDK for JavaScript (v3).
