### ISSUE TITLE
Support for Greengrass v2 APIs

### ISSUE THREAD

**Issue by massi-ang** [aws/aws-sdk-js-v3#2171]
### Is your feature request related to a problem? Please describe.
In order to use Greengrass v2 API we need support in the SDK

### Describe the solution you'd like
Support for Greengrass v2 APIs

### Describe alternatives you've considered
Use another SDK

### Additional context
Greengrass v2 went GA in December 2020, and its API are not implemented to date in this SDK, while on boto3 they were present at launch

**Comment by trivikr** [comment]
The `@aws-sdk/client-greengrass-v2` was added in https://github.com/aws/aws-sdk-js-v3/pull/2258, and was released with v3.13.0
