### ISSUE TITLE
INI file credential provider should call SSO, Process, WebIdentity credentials provider internally

### ISSUE THREAD

**Issue by AllanZhengYP** [aws/aws-sdk-js-v3#2176]
### Is your feature request related to a problem? Please describe.
Currently the File credential [`fromIni()`](https://github.com/aws/aws-sdk-js-v3/tree/main/packages/credential-provider-ini) only resolves static credentials or credentials that assume with static credentials. It fails to resolve the credentials file if the profile contains parameters indicating it's other type of credentials.

It fails at credentials like bellow:

```
[profile willFail]
sso_start_url = https://sso-endpoint/start
sso_region = us-west-2
sso_account_id =123456789012
sso_role_name = AdministratorAccess
[profile willFailToo]
credential_process = /usr/local/bin/awscreds dev
```

Instead users need to use the individual credential provider for different configurations: [`fromProcess()`](https://github.com/aws/aws-sdk-js-v3/tree/main/packages/credential-provider-process), [`fromSSO()`](https://github.com/aws/aws-sdk-js-v3/tree/main/packages/credential-provider-sso), or the [`defaultProvider()`](https://github.com/aws/aws-sdk-js-v3/tree/main/packages/credential-provider-node). However the [`defaultProvider()`](https://github.com/aws/aws-sdk-js-v3/tree/main/packages/credential-provider-node) may fallback to other providers that is not preferred. When a user specificies the [`fromIni()`](https://github.com/aws/aws-sdk-js-v3/tree/main/packages/credential-provider-ini), it should be able to resolve all the credential format that can exist in an AWS credential file.

Calling the individual credential provider from [`fromIni()`](https://github.com/aws/aws-sdk-js-v3/tree/main/packages/credential-provider-ini) can also simplify the logic a lot because each credential provider doesn't need to implement the logic of recursively resolving the profiles in the credential file anymore.

This issue arises when comparing with the implementation with the Java SDK([`ProfileCredentialsProvider`](https://github.com/aws/aws-sdk-java-v2/blob/master/core/auth/src/main/java/software/amazon/awssdk/auth/credentials/ProfileCredentialsProvider.java), [`DefaultCredentialProvider`](https://github.com/aws/aws-sdk-java-v2/blob/master/core/auth/src/main/java/software/amazon/awssdk/auth/credentials/DefaultCredentialsProvider.java) ) during reviewing https://github.com/aws/aws-sdk-js-v3/pull/2147#issuecomment-806203135

### Describe the solution you'd like
[`fromProcess()`](https://github.com/aws/aws-sdk-js-v3/tree/main/packages/credential-provider-process), [`fromSSO()`](https://github.com/aws/aws-sdk-js-v3/tree/main/packages/credential-provider-sso) should be integrated into [`fromIni()`](https://github.com/aws/aws-sdk-js-v3/tree/main/packages/credential-provider-ini) when the profile's format indicates these credential providers. At the same time, standalone provider [`fromProcess()`](https://github.com/aws/aws-sdk-js-v3/tree/main/packages/credential-provider-process) and [`fromSSO()`](https://github.com/aws/aws-sdk-js-v3/tree/main/packages/credential-provider-sso) must be added to default credential chain **before** `fromIni()`.

**Comment by john-aws** [comment]
Not clear to me that this should be categorized as a feature request, rather than a bug. It's a standard feature of the awscli to be able to [source credentials from an external process](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html).
