### ISSUE TITLE
@aws-sdk/client-transcribe-streaming Word level Confidence not available.

### ISSUE THREAD

**Issue by ArmandDu** [aws/aws-sdk-js-v3#2187]
## Describe the bug
The latest version of AWS Streaming Transcribe now has [word-level confidence score](https://aws.amazon.com/about-aws/whats-new/2021/03/amazon-transcribe-supports-word-level-confidence-scores-for-streaming-transcription/) but this feature is not available in `@aws-sdk/client-transcribe-streaming` <= 3.10.0

The issue seems to come from [clients/client-transcribe-streaming/protocols/Aws_restJson1.ts](https://github.com/aws/aws-sdk-js-v3/blob/62ea7873559130d075a3a01082a1addda8aac1bf/clients/client-transcribe-streaming/protocols/Aws_restJson1.ts#L728) file.

The method `deserializeAws_restJson1Item` doesn't return the `Confidence` value

```typescript
const deserializeAws_restJson1Item = (output: any, context: __SerdeContext): Item => {
  return {
   // Confidence:... is missing here
    Content: output.Content !== undefined && output.Content !== null ? output.Content : undefined,
    EndTime: output.EndTime !== undefined && output.EndTime !== null ? output.EndTime : undefined,
    Speaker: output.Speaker !== undefined && output.Speaker !== null ? output.Speaker : undefined,
    StartTime: output.StartTime !== undefined && output.StartTime !== null ? output.StartTime : undefined,
    Type: output.Type !== undefined && output.Type !== null ? output.Type : undefined,
    VocabularyFilterMatch:
      output.VocabularyFilterMatch !== undefined && output.VocabularyFilterMatch !== null
        ? output.VocabularyFilterMatch
        : undefined,
  } as any;
};
```

#### SDK version number
`@aws-sdk/client-transcribe-streaming@3.10.0`

#### Is the issue in the browser/Node.js/ReactNative?
Browser

#### Details of the browser/Node.js/ReactNative version
  Browsers:
    Firefox: 87.0

## Steps to reproduce
add `@aws-sdk/client-transcribe-streaming@3.10.0` as a dependency and use the `StartStreamTranscriptionCommand` Command either in the browsers or nodejs environment. and log each `StartStreamTranscriptionCommandOutput` events.

```typescript
function* audioStream() {
  //snip, stream audio data. for example from MediaRecorder or an audio file
}

const command = new StartStreamTranscriptionCommand({
  LanguageCode: "en-US",
  MediaEncoding: "pcm",
  MediaSampleRateHertz: inputSampleRate,
  AudioStream: audioStream(),
});
const response = await client.send(command);

for await (const event of response.TranscriptResultStream) {
  for (const result of event.TranscriptEvent?.Transcript?.Results || []) {
    if (result.IsPartial === false) {
      // Confidence will be missing here.
      console.log(result);
    }
  }
}
```

#### Observed behavior
The `StartStreamTranscriptionCommandOutput` will yield `TranscriptResultStream` that has been serialized by `client-transcribe-streaming/protocols/Aws_restJson1.ts` function. Omitting Confidence attribute.

The current observed response shape is 
```typescript
interface TranscriptEvent {
  Transcript?: Transcript;
}
interface Transcript {
 Results?: Result[];
}

interface Result {
  Alternatives?: Alternative[];
 IsPartial?: boolean;
//snip...
}
interface Alternative {
Transcript?: string;
Items?: Item[];
}

interface Item {
//Confidence is missing here!
Content?: string;
//snip...
}
```

#### Expected behavior
the `Item` interface should have an attribute `Confidence?: number` and the `Aws_restJson1.ts` should include the `Confidence` attribute.

**Comment by Skeird** [comment]
Hi @ArmandDu,

Could you please provide me with an example for the audioStream() function ? I am really struggling to get this working.
By the way, I couldn't help but notice that you were a fellow Epitech student. I'm currently in my 4th year at Epitech and I need to implement AWS Transcribe in my EIP project. So any help would be greatly appreciated.

Thanks

**Comment by ArmandDu** [comment]
Hey,

you can find some examples here : https://github.com/aws/aws-sdk-js-v3/tree/d8475f8d972d28fbc15cd7e23abfe18f9eab0644/clients/client-transcribe-streaming#acquire-speech-stream

I'm not sure why they were removed from the README.

**Comment by ajredniwja** [comment]
Hey @ArmandDu thanks for the wait, I believe initially it was because the models were not updated timely. 

I was able to test the client using the code below and it happens to work correctly with `Confidence` added to it. 

<details>
<summary>Code:</summary>

```javascript
const fs = require('fs');
const { TranscribeStreamingClient,  StartStreamTranscriptionCommand } = require('@aws-sdk/client-transcribe-streaming');

function wait(time) {
    return new Promise(resolve => {
        setTimeout(resolve, time);
    })
}

async function* audioSource() {
    const chunkSize = 10 * 1000;
    const fileBuf = fs.readFileSync('./testFile.wav');
    let index = 0;
    let i = 0;
    while(index < fileBuf.length) {
    // while(index < chunkSize * 60) {
        const chunk = fileBuf.slice(index, Math.min(index + chunkSize, fileBuf.byteLength));
        await wait(300);
        yield chunk;
        index += chunkSize;
    }
}

(async () => {
    console.log(`***start: [${new Date()}]`);
    async function * audioStream() {
        for await(const chunk of audioSource()) {
            yield {AudioEvent: {AudioChunk: chunk}}
        }
    }
    const client = new TranscribeStreamingClient({region: "us-west-2"});

    const command = new StartStreamTranscriptionCommand({
        LanguageCode: 'en-US',
        MediaSampleRateHertz: 16000,
        MediaEncoding: 'pcm',
        AudioStream: audioStream(),

    });
    try {
        const data = await client.send(command, {sessionTimeout: 2000});
        // console.log(data.TranscriptResultStream)

        for await (const event of data.TranscriptResultStream) {
            for (const result of event.TranscriptEvent?.Transcript?.Results || []) {
              if (result.IsPartial === false) {
                console.log(result.Alternatives[0].Items);
              }
            }
          }
        console.log('DONE', data);
        client.destroy();
    } catch(e) {
        console.log('ERROR: ', e);
        process.exit(1);
    }
})();
```
</details> 


<details>
<summary>Sample output:</summary>

```
  {
    Confidence: 1,
    Content: 'to',
    EndTime: 10.17,
    Speaker: undefined,
    Stable: undefined,
    StartTime: 10.06,
    Type: 'pronunciation',
    VocabularyFilterMatch: false
  },
  {
    Confidence: 1,
    Content: 'the',
    EndTime: 10.31,
    Speaker: undefined,
    Stable: undefined,
    StartTime: 10.18,
    Type: 'pronunciation',
    VocabularyFilterMatch: false
  },
  {
    Confidence: 1,
    Content: 'proposition',
    EndTime: 11.2,
    Speaker: undefined,
    Stable: undefined,
    StartTime: 10.32,
    Type: 'pronunciation',
    VocabularyFilterMatch: false
  },
  {
    Confidence: 1,
    Content: 'that',
    EndTime: 11.38,
    Speaker: undefined,
    Stable: undefined,
    StartTime: 11.22,
    Type: 'pronunciation',
    VocabularyFilterMatch: false
  },
  {
    Confidence: 1,
    Content: 'all',
    EndTime: 11.73,
    Speaker: undefined,
    Stable: undefined,
    StartTime: 11.39,
    Type: 'pronunciation',
    VocabularyFilterMatch: false
  },
  {
    Confidence: 1,
    Content: 'men',
    EndTime: 12.13,
    Speaker: undefined,
    Stable: undefined,
    StartTime: 11.74,
    Type: 'pronunciation',
    VocabularyFilterMatch: false
  },
  {
    Confidence: 1,
    Content: 'are',
    EndTime: 12.43,
    Speaker: undefined,
    Stable: undefined,
    StartTime: 12.15,
    Type: 'pronunciation',
    VocabularyFilterMatch: false
  },
  {
    Confidence: 1,
    Content: 'created',
    EndTime: 13.04,
    Speaker: undefined,
    Stable: undefined,
    StartTime: 12.45,
    Type: 'pronunciation',
    VocabularyFilterMatch: false
  }
```
</details> 

Using: `@aws-sdk/client-transcribe-streaming@3.17.0`

So I believe updating the client should work just fine. 

Closing this issue now. Please reach out if that doesn't work or you have any additional questions.

**Comment by ArmandDu** [comment]
Hey @ajredniwja, thanks for the update. It's good to know that it has been fixed in a later version.

Unfortunately since recently the confidence seems to always be 1. Which defeat the purpose of this field. But That's not an issue in the scope of the SDK.

**Comment by ajredniwja** [comment]
@ArmandDu You are right, thats something that the `transcribe` sends as a response. Feel free to raise this feature request at  https://github.com/aws/aws-sdk and I can reach out to the team involved for this.
