### ISSUE TITLE
High AWS Lambda Execution Duration with NodeJS AWS SDK v3 vs. v2

### ISSUE THREAD

**Issue by jenslauterbach** [aws/aws-sdk-js-v3#2190]
## Describe the bug

I am observing major Lambda execution duration differences between v2 and v3 of the SDK when getting an object from S3.

#### SDK version number
`@aws-sdk/client-s3@3.1.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version

* AWS Lambda NodeJS 14.x runtime
* 128MB memory

## Steps to reproduce

1. Create two Lambdas
2. NodeJS 14.x runtime
3. 128MB memory

Since v2 of the SDK is available in the runtime, I only had to deploy my `index.js`. For v3 I also have to deploy the `node_modules`, because v3 is not available in the runtime out of the box.

**Code with v2 SDK:**

```
const AWS = require("aws-sdk");
const s3 = new AWS.S3();

exports.handler = async (event, context, callback) => {
    const params = {Bucket: "<bucket>", Key: "test.txt"};
    const data = await s3.getObject(params).promise();

    return callback(null, data.ContentLength);
};
```

**Code with v3 SDK:**

```
const { S3Client, GetObjectCommand } = require("@aws-sdk/client-s3");
const client = new S3Client();

exports.handler = async (event, context, callback) => {
    const command = new GetObjectCommand({Bucket: "<bucket>", Key: "test.txt"});
    const data = await client.send(command);

    return callback(null, data.ContentLength);
};
```

#### Observed behavior

The Lambda with the v2 version of the SDK performs reasonably well in terms of execution duration, but the Lambda that uses v3 of the SDK takes ten times the time to do the same task.

Both Lambdas are "hot". The following times are from "hot" executions:

```
v2: ~50-80ms     (Duration:   69.80 ms  Billed Duration:   70 ms Memory Size: 128 MB Max Memory Used: 90 MB)
v3: ~5500-7000ms (Duration: 6096.98 ms  Billed Duration: 6097 ms Memory Size: 128 MB Max Memory Used: 97 MB)
```

I used X-Ray (see screenshot below) to check where the time is "lost" and it appears to be the "Overhead" phase. The [AWS documentation](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-tracing.html#nodejs-tracing-api) states:

> Represents the work done by the Lambda runtime to prepare to handle the next event.

I have no clue what that is supposed to mean, but it appears to be what takes so long. Since the performance degradation is so huge, I would suspect this a bug.

#### Expected behavior

I would expect that both Lambdas perform similar. 

#### Screenshots

<img width="1114" alt="nodejs-v3-xray" src="https://user-images.githubusercontent.com/1292368/112870031-0fe84b80-90be-11eb-832a-f4754c5d0a2a.png">

## Additional context

The object that is downloaded in both examples is just a simple text file with a size of `43` bytes.

**Comment by PatrykMilewski** [comment]
Did you tried to use the webpack to optimize the package size? Maybe the number of files/package size still affects the lambda performance, even for hot lambdas.

**Comment by jenslauterbach** [comment]
@PatrykMilewski I am not using webpack. I will try to use it and see if it makes any difference.

Not sure how NodeJS does work under the hood, but I would expect that the deployment package size does not have a lot if any influence on the "Overhead" phase of a requests life cycle. Even then, 6 seconds seems an awful lot.

**Comment by jenslauterbach** [comment]
I have re-visited this issue and used a bundler ([esbuild](https://esbuild.github.io)) to create a "bundle" of my super tiny app and the AWS SDK. I also tried the latest version (`3.13.0`).

Both did not affect the execution time at all. It is still way above 6 seconds.

I used the following command to create the bundle:

```
esbuild --bundle --platform=node --target=node14 --minify index.js
```

**Comment by Samrose-Ahmed** [comment]
I can reproduce this with your code. 

Your error is you are using `callback` inside an async handler. In an async handler, you should just return the value (or a Promise). See [the documentation](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-handler.html#nodejs-handler-async).

Changing your code to:

```javascript
const { S3Client, GetObjectCommand } = require("@aws-sdk/client-s3");
const client = new S3Client();

exports.handler = async (event, context) => {
    const command = new GetObjectCommand({Bucket: "<bucket>", Key: "test.txt"});
    const data = await client.send(command);

    return data.ContentLength;
};
```

Makes the execution time equivalent to the V2 version.

**Comment by jenslauterbach** [comment]
@Samrose-Ahmed Thank you _very much_ for your help 👍. I was not aware of this `async` behaviour. I changed the code accordingly and now it works as expected.

Therefore, I am closing the issue.
