### ISSUE TITLE
Error during the build in Netlify functions

### ISSUE THREAD

**Issue by felipecesr** [aws/aws-sdk-js-v3#2199]
## Describe the bug

I have a [Netlify Function](https://docs.netlify.com/functions/overview/) that connect to DynamoDB and everything works well in development, but when I deploy it, the following error occurs during the build.

<img width="446" alt="error" src="https://user-images.githubusercontent.com/10980841/113055806-64a0ca80-9181-11eb-82eb-3ff2b83d726f.png">

I'm not using React Native, it´s only a serverless function, but when `DynamoDBClient` is required, that error occurs.

#### SDK version number

`@aws-sdk/client-dynamodb@3.10.0`

#### Is the issue in the browser/Node.js/ReactNative?

Node.js

#### Details of the browser/Node.js/ReactNative version

v12.18.0

## Steps to reproduce

You can follow the [documentation](https://docs.netlify.com/functions/configure-and-deploy/) to create a Netlify function.

This is my code.

```javascript
require('dotenv').config()
const { DynamoDBClient } = require('@aws-sdk/client-dynamodb')
const { DynamoDBDocument } = require('@aws-sdk/lib-dynamodb')

const dbclient = new DynamoDBClient({
  region: process.env.MY_AWS_REGION,
  credentials: {
    accessKeyId: process.env.MY_AWS_ACCESS_KEY_ID,
    secretAccessKey: process.env.MY_AWS_SECRET_ACCESS_KEY
  }
})

const ddbDocClient = DynamoDBDocument.from(dbclient)

exports.handler = async () => {
  const params = {
    TableName: 'todos',
    KeyConditionExpression: 'pk = :userid and begins_with(sk, :todokey)',
    ExpressionAttributeValues: {
      ':userid': 'user#1',
      ':todokey': 'todo#'
    }
  }

  try {
    const response = await ddbDocClient.query(params)
    const items = response.Items.map(({ sk, data }) => ({
      _id: sk.replace('todo#', ''),
      ...data
    }))

    return {
      statusCode: 200,
      body: JSON.stringify(items)
    }
  } catch (error) {
    return {
      statusCode: 400,
      body: JSON.stringify(error)
    }
  }
}
```

**Comment by trivikr** [comment]
This will be fixed by https://github.com/aws/aws-sdk-js-v3/pull/2191
