### ISSUE TITLE
@aws-sdk/lib-storage httpUploadProgress Only get emitted after each part uploaded

### ISSUE THREAD

**Issue by vinithisonline** [aws/aws-sdk-js-v3#2206]
The httpUploadProgress event only gets triggered after each part uploaded completely. So if part size is cofigured as 100MB, there is no way to track if the upload is progressing until 100MB got fullly uploaded.

**Comment by ajredniwja** [comment]
@vinithisonline can you please follow the [issue template](https://github.com/aws/aws-sdk-js-v3/issues/new?assignees=&labels=bug%2C+needs-triage&template=---bug-report.md&title=)?
