### ISSUE TITLE
Use the same version of `tslib` *everywhere*

### ISSUE THREAD

**Issue by G-Rath** [aws/aws-sdk-js-v3#2207]
### Is your feature request related to a problem? Please describe.
It seems that some packages are using v1 of `tslib`, and others are using v2.

This instantly causes *massive* duplication in the dependency tree:

![image](https://user-images.githubusercontent.com/3151613/113348990-d81a2600-9393-11eb-903d-9133ba38ac31.png)

(This project is solely using `@aws-sdk/client-dynamodb` & `@aws-sdk/client-dynamodb`).

### Describe the solution you'd like
That all packages that specify `tslib` as a dependency use the same version.

### Describe alternatives you've considered
Being sad that there's so much duplication.

### Additional context
This should reduce the install size a little :)

(Related to #1536)

**Comment by AllanZhengYP** [comment]
Closing it as it should be fixed by https://github.com/aws/aws-sdk-js-v3/pull/2601. Please open a new issue if this request is not addressed.
