### ISSUE TITLE
Looking for LogoutCommand from cognito packages

### ISSUE THREAD

**Issue by Maev4l** [aws/aws-sdk-js-v3#2209]
According to the documentation, LogoutCommand is exported from @aws-sdk/client-cognito-identity or @aws-sdk/client-cognito-identity-provider packages

`import { LogoutCommand } from "@aws-sdk/client-cognito-identity";`
or 
`import { LogoutCommand } from "@aws-sdk/client-cognito-identity-provider";`

fail with the following error message:
`Named export 'LogoutCommand' not found.`

Would you mind please to update the documentation ? Or provide some guidance on how to perform a logout using the AWS JS SDK v3 ?

Thanks !

**Comment by RanVaknin** [comment]
Hi @Maev4l ,

Thanks for pointing this out.

> According to the documentation, 

Which documentation?

I see this is [documented](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-cognito-identity-provider/classes/logoutcommand.html) here under `cognito-identity-providers` but the import line states:
 `import { SSOClient, LogoutCommand } from "@aws-sdk/client-sso";` which is the correct import. 

Is this the doc you were referring to? 

Thanks,
Ran~

**Comment by Maev4l** [comment]
Hi @RanVaknin ,
My bad, I should have read the example more carefully.

Thanks again.
