### ISSUE TITLE
client-lambda-browser is missing

### ISSUE THREAD

**Issue by buildbreakdo** [aws/aws-sdk-js-v3#221]
Looks like the browser version of AWS Lambda is missing, here are AWS docs that talk about the use case:

https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/browser-invoke-lambda-function-example.html

**Comment by srchase** [comment]
@buildbreakdo 

Not all of the clients have been generated and released to NPM yet.

You can build clients from source following the instructions for [generating service clients](https://github.com/aws/aws-sdk-js-v3/blob/master/CONTRIBUTING.md#generating-service-clients).

After the other setup steps, you can run the following to generate the lambda browser client:
```
node ./packages/package-generator/build/cli.js client --model models/lambda/2015-03-31/service-2.json --runtime browser --smoke models/lambda/2015-03-31/smoke.json
```
