### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by alaley40** [aws/aws-sdk-js-v3#2213]
#### SDK version number
`@aws-sdk/package-name@version`

#### Is the issue in the browser/Node.js/ReactNative?
Browser/Node.js/ReactNative

#### Details of the browser/Node.js/ReactNative version
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`

## Steps to reproduce
Please share code or minimal repo, and steps to reproduce the behavior.

#### Observed behavior
A clear and concise description of what happens.

#### Expected behavior
A clear and concise description of what you were expecting to happen.

**Comment by ajredniwja** [comment]
Closing this issue as it has no information.
