### ISSUE TITLE
installing v3 packages pulls in a huge number of npm packages

### ISSUE THREAD

**Issue by lukemcgregor** [aws/aws-sdk-js-v3#2219]
## Describe the bug
Installing @aws-sdk/client-dynamodb (or actually most of the libraries in the v3 sdk) installs a monumental number of dependencies. The above is 200mb (which incidently is more than 3 times the size of the whole v2 api), including amongst other things react-native and jest. This makes my lambdas huge, adds seconds to the cold start time and as a result I'm going to have to downgrade to v2.

![image](https://user-images.githubusercontent.com/1284608/113957596-9f86ba80-9873-11eb-9515-9240e7e1b773.png)

#### SDK version number
`@aws-sdk/client-dynamodb@3.11.0`

## Steps to reproduce
```
mkdir whatever && cd whatever && npm init && npm i @aws-sdk/client-dynamodb
```
#### Observed behavior
Thousands of npm packages are installed

#### Expected behavior
a minimal set of npm packages should be installed 

## Additional context
npm why react-native

```
react-native@0.64.0 peer
node_modules/react-native
  peer react-native@">=0.56" from react-native-get-random-values@1.6.0
  node_modules/react-native-get-random-values
    react-native-get-random-values@"^1.4.0" from @aws-sdk/middleware-retry@3.10.0
    node_modules/@aws-sdk/middleware-retry
      @aws-sdk/middleware-retry@"3.10.0" from @aws-sdk/client-dynamodb@3.11.0
      node_modules/@aws-sdk/client-dynamodb
        @aws-sdk/client-dynamodb@"^3.11.0" from the root project
      @aws-sdk/middleware-retry@"3.10.0" from @aws-sdk/client-sso@3.11.0
      node_modules/@aws-sdk/client-sso
        @aws-sdk/client-sso@"3.11.0" from @aws-sdk/credential-provider-sso@3.11.0
        node_modules/@aws-sdk/credential-provider-sso
          @aws-sdk/credential-provider-sso@"3.11.0" from @aws-sdk/credential-provider-node@3.11.0
          node_modules/@aws-sdk/credential-provider-node
            @aws-sdk/credential-provider-node@"3.11.0" from @aws-sdk/client-dynamodb@3.11.0
            node_modules/@aws-sdk/client-dynamodb
              @aws-sdk/client-dynamodb@"^3.11.0" from the root project
  peer react-native@">=0.64.0-rc.0 || 0.0.0-*" from @react-native-community/cli@5.0.1-alpha.2
  node_modules/@react-native-community/cli
    @react-native-community/cli@"^5.0.1-alpha.0" from react-native@0.64.0
```

**Comment by trivikr** [comment]
This will be fixed by https://github.com/aws/aws-sdk-js-v3/pull/2191
