### ISSUE TITLE
fetch-http-handler handle fails due to missing import of Headers

### ISSUE THREAD

**Issue by frjtrifork** [aws/aws-sdk-js-v3#2225]
When invoking @aws-sdk/fetch-http-handler (version 3.10) `handle` method it fails at runtime with a 'Headers is not defined' error.

The runtime environment is Node 14.x in AWS Lambda. The application is written in typescript and compiled to es2020 target.

The handle request fails when trying to make a GET request to an API Gateway with an AWS Signature v4 signed request (made using @aws-sdk/signature-v4). 

Changing my handler to @aws-sdk/node-http-handler works for the same signed request.

The problem:
https://github.com/aws/aws-sdk-js-v3/blob/5ae46f645327216f5f06c5cddc48523ff0d9e19e/packages/fetch-http-handler/src/fetch-http-handler.ts#L56

Error message:

```
{
    "errorType": "ReferenceError",
    "errorMessage": "Headers is not defined",
    "stack": [
        "ReferenceError: Headers is not defined",
        "    at FetchHttpHandler.handle (/var/task/node_modules/@aws-sdk/fetch-http-handler/src/fetch-http-handler.ts:56:20)",
        "    at /var/task/src/webpack:/src/common/utils/lacApiClient.ts:148:38",
        "    at process.response (internal/process/task_queues.js:93:5)",
        "    at Runtime.S [as handler] (/var/task/src/webpack:/src/handler.ts:120:17)"
    ]
}
```

**Comment by ajredniwja** [comment]
Hey @frjtrifork thanks for reaching out, can you please provide some code to reproduce the problem?
