### ISSUE TITLE
@aws-sdk/client-sts/STSClient v3 doesn't use provided proxy setting

### ISSUE THREAD

**Issue by brandt-roberts** [aws/aws-sdk-js-v3#2228]
## Describe the bug
Can't connect with STSClient using proxy when running AWS SDK v3 locally, but can with v2.  Have verified STS IP addresses are reachable from local machine via proxy.

https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/node-configuring-proxies.html 

## Your environment
local

#### SDK version number
`@aws-sdk/client-sts@3.11.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v12.22.0

## Steps to reproduce
Fails on STSClient.send method:

`const awsStsClient = new STSClient({​ 
  requestHandler: new NodeHttpHandler({​
    httpsAgent: new Agent({​
      proxy: proxy('<proxy-url-redacted>')
    }​) 
  }​)
}​);`
`const assumeRoleCommand = new AssumeRoleWithSAMLCommand({​ 
  RoleArn: '<role-arn-redacted>',
  PrincipalArn: '<principal-arn-redacted>',
  SAMLAssertion: '<assertion-redacted>'
}​)`
`const stsReposnse = await awsStsClient.send(assumeRoleCommand);`

#### Observed behavior
Failure results in ETIMEDOUT

#### Expected behavior
Web service request from STSClient.send should connect via provided proxy and return (any) results instead of ETIMEDOUT. 

#### Screenshots
N/A

## Additional context
None

**Comment by ishener** [comment]
I have found that this documentation page is wrong and not helpful

This is in fact the way to configure proxy:

```
const client = new XXXXClient({
            region: "us-east-1", requestHandler: new NodeHttpHandler({
                httpsAgent: proxy("http://proxy-domain.com")
            }),
        });
```

**Comment by brandt-roberts** [comment]
> I have found that this documentation page is wrong and not helpful
> 
> This is in fact the way to configure proxy:
> 
> ```
> const client = new XXXXClient({
>             region: "us-east-1", requestHandler: new NodeHttpHandler({
>                 httpsAgent: proxy("http://proxy-domain.com")
>             }),
>         });
> ```

Thank you @ishener!! Using the configuration you provided worked immediately!
