### ISSUE TITLE
docs(clients) async/await example does not use async await

### ISSUE THREAD

**Issue by pratikpc** [aws/aws-sdk-js-v3#2231]
## Describe the issue with documentation
async/await example in client-ses does not sue async await

## Steps to reproduce
Present in [README.md at example here](https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-ses/README.md#v2-compatible-style)

**Comment by trivikr** [comment]
Thank you @pratikpc for finding this issue, and adding a PR to fix it.

This fix is required in codegen for all clients. I cherry-picked commit from your PR, and posted fix for all clients in https://github.com/aws/aws-sdk-js-v3/pull/2243

**Comment by pratikpc** [comment]
@trivikr thanks

I renamed the issue to now make it more clear that multiple projects are affected
