### ISSUE TITLE
client-ses: fails to send with 400 without any other indicaton

### ISSUE THREAD

**Issue by pkit** [aws/aws-sdk-js-v3#2238]
## Describe the bug
Exception does not contain any indication on what happened

#### SDK version number
`@aws-sdk/client-ses@3.12.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v12.19.0

## Steps to reproduce
```
const ses = new SESClient({ region: 'us-east-1' })
await ses.send(new SendTemplatedEmailCommand(params))
```

#### Observed behavior
```
MessageRejected: MessageRejected
    at deserializeAws_querySendTemplatedEmailCommandError (/home/user/project/node_modules/@aws-sdk/client-ses/dist/cjs/protocols/Aws_query.js:3534:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/user/project/node_modules/@aws-sdk/middleware-serde/dist/cjs/deserializerMiddleware.js:6:20
    at async /home/user/project/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:12:24
    at async StandardRetryStrategy.retry (/home/user/project/node_modules/@aws-sdk/middleware-retry/dist/cjs/defaultStrategy.js:56:46)
    at async /home/user/project/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22
    at async Command.send (/home/user/project/server/invites/cli.js:55:20)
    at async Promise.all (index 0) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: 'b3e47183-e2cd-437d-9f55-3453d72e66d7',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}
```

#### Expected behavior
Some indication on what exactly happened from the list https://docs.aws.amazon.com/ses/latest/DeveloperGuide/using-ses-api-error-codes.html

**Comment by ajredniwja** [comment]
Hey @pkit,  looking at the response you get, I see the `code` is not added which indicates the error better. 
For example: 
```
 Type: 'Sender',
  Code: 'InvalidParameterValue',
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: 'fb32ceb5-9605-4a23-9e6f-',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
```

can you share how you catch the error, I use try catch like: 

```

  try {    
  const data = await client.send(command);
  console.log(data);
  } catch (err) {
      console.log( err);
  }
```

Would like a complete code example to try to replicate this. With that being said, the SDK actually doesn't add or strip anything from the response which maybe useful in this case. 

https://github.com/aws/aws-sdk-js-v3/blob/2165d4a5c2aec2945900bbe8e79d497da8a80cfa/clients/client-ses/protocols/Aws_query.ts#L4550

**Comment by pkit** [comment]
@ajredniwja yup, found out that that's the actual response from the AWS HTTP API
Nothing more is there. Pity.
