### ISSUE TITLE
Credentials not exported by @aws-sdk/types

### ISSUE THREAD

**Issue by slimandslam** [aws/aws-sdk-js-v3#2248]
## Describe the bug
$ npm install @aws-sdk/types
Then use: 
import { Credentials } from "@aws-sdk/types"

## Your environment
React 17.02 or just Node v14.

#### SDK version number
`@aws-sdk/types@3.12.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node and React

#### Observed behavior
Error msg:  "Credentials is not exported by @aws-sdk/types"

#### Expected behavior
I'm expecting to create a Credentials object like:

const tempCredentials =  new Credentials({
   accessKeyId: AccessKeyId,
   secretAccessKey: SecretAccessKey,
   sessionToken: SessionToken
 });

I can see. "export interface Credentials {"
in https://github.com/aws/aws-sdk-js-v3/blob/main/packages/types/src/credentials.ts

**Comment by dl748** [comment]
Types are for TypeScript not Javascript.  Node does not understand .ts files and does not import them.  Also, its exporting an interface not a class or function, these are type definitions not executable code.

**Comment by dl748** [comment]
If you are just looking to override credentials, you can do so with the following code

```
import { Client } from '@aws-sdk/client-*'

const c = new Client({
  credentials: () => {
    return {
      accessKeyId: 'myaccesskey',
      secretAccessKey: 'mysecret',
    }
  }
})
```

You can even make the function async and wait for a promise

```
import { Client } from '@aws-sdk/client-*'

const sleep = async(ms) => new Promise((res) => setTimeout(res, ms));

const c = new Client({
  credentials: async() => {
    await sleep(20000);
    return {
      accessKeyId: 'myaccesskey',
      secretAccessKey: 'mysecret',
    }
  }
})
```

allowing you to read from a file, a database, or maybe call other services

**Comment by slimandslam** [comment]
Is this a documentation bug? I don't see anywhere in the documentation where you say that the JavaScript SDK v2 "Credentials" object is no longer available in SDK v3 and you can just use basic JSON like so:

```
 const tempCredentials =  {
   accessKeyId: AccessKeyId,
   secretAccessKey: SecretAccessKey,
   sessionToken: SessionToken
 };

```

**Comment by dl748** [comment]
Not sure, but just about everything is different in v3.  v3 has credential providers now, which are just a function instead of an object instance.
See documentation and code from 
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_credential_provider_node.html
or
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_credential_provider_env.html
or any of the @aws-sdk/credential-provider-* from
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/index.html

**Comment by ajredniwja** [comment]
@dl748, thanks for the explanation, @slimandslam I'd close this issue if there are no more questions.
