### ISSUE TITLE
Migration aws-sdk-js v2 to v3. Error Sharp: input-file-is-missing

### ISSUE THREAD

**Issue by alditis** [aws/aws-sdk-js-v3#2262]
## Describe the bug
In migration aws-sdk-js **v2** to **v3**
I get Error Sharp: "Input file is missing"
When I try to get an object from S3 using aws-sdk-js v3
But works when I using aws-sdk-js v2.

## Your environment
Ubuntu 18.04
Sharp version: 0.28.1

#### SDK version number
`@aws-sdk/client-s3@^3.12.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js (Lambda Function)

#### Details of the browser/Node.js/ReactNative version
node -v
v14.5.0

## Steps to reproduce
**Works with aws-sdk-js v2:**
```
const Sharp = require('sharp');
const AWS = require('aws-sdk');

const S3 = new AWS.S3({ signatureVersion: 'v4' });

const originalPhoto = (await S3.getObject({ Bucket: "myBucket", Key: "myKey" }).promise()).Body;
const originalPhotoDimensions = await Sharp(originalPhoto).metadata();
```
A Buffer is obtained:
![image](https://user-images.githubusercontent.com/2662209/114813491-d67b3580-9d77-11eb-92ae-f5d9bcadbedd.png)

**Error with aws-sdk-js v3:**
```
const Sharp = require('sharp');
const { S3Client, GetObjectCommand } = require("@aws-sdk/client-s3");

const S3 = new S3Client({ region: "us-east-1" });

const originalPhoto = (await S3.send(new GetObjectCommand({ Bucket: "myBucket", Key: "myKey" }))).Body;
const originalPhotoDimensions = await Sharp(originalPhoto).metadata(); // <--- Error
```
I understand that is because originalPhoto is not a Buffer:
![image](https://user-images.githubusercontent.com/2662209/114813645-2bb74700-9d78-11eb-9283-2e560386bb64.png)

#### Observed behavior
A Buffer is not obtained on this line:
`const originalPhoto = (await S3.send(new GetObjectCommand({ Bucket: "myBucket", Key: "myKey" }))).Body;`

The error:
```
ERROR   Unhandled Promise Rejection     
{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: Input file is missing",
```

#### Expected behavior
I was hoping to get a buffer on this line:
`const originalPhoto = (await S3.send(new GetObjectCommand({ Bucket: "myBucket", Key: "myKey" }))).Body;`

## Additional context
I posted my ask on StackOverFlow:
https://stackoverflow.com/questions/67100921/migration-aws-sdk-js-v2-to-v3-error-sharp-input-file-is-missing

**Comment by ajredniwja** [comment]
Hi @alditis, this happens because `body` returned is not string anymore. You'd need to try something like : https://github.com/aws/aws-sdk-js-v3/issues/1877#issuecomment-755387549

I see there is a SO example as well, I can help write an example if that doesnt resolve the problem.
