### ISSUE TITLE
Uncaught Exception complicates debugging

### ISSUE THREAD

**Issue by netbymatt** [aws/aws-sdk-js-v3#2263]
SDK v3.12.0
Node v14.15.0
Visual Studio Code v1.55.2 for debugging
Credentials loaded from ~/.aws/credentials
Actual package loaded @aws-sdk/client-s3 v3.12.0

I typically debug with "uncaught exceptions" turned on. The code in line 16 below pre-generates a default rejected promise that is then typically overwritten in the loop on the following lines. 

https://github.com/aws/aws-sdk-js-v3/blob/4f9f4a79b019c1c35530e05c4138fde88a6fb547/packages/property-provider/src/chain.ts#L16-L25

Promise.reject is considered an uncaught exception by the debugger thus it pauses here on each debug run. Even though the credentials are ultimately successfully loaded from the default location ~/.aws/credentials I need to step through this "exception" before actually getting to my code that I'm targeting for debug.

I believe a better solution would be to restructure the loop so the final return is where the rejected promise is generated.

**Comment by kilotone** [comment]
This has been driving me absolutely mad the last 3 days

**Comment by vargaendre** [comment]
Still happening with version 3.85.0
I also spent like two hours trying to figure out what I did wrong. Turns out that nothing.
I am glad this issue exists at least!

**Comment by ppold** [comment]
Has anyone found a workaround to silence that exception in the meantime?

**Comment by belenkymr** [comment]
Still happening with [v3.127.0](https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.127.0)

**Comment by SabeehY** [comment]
+1

**Comment by berkeleymalagon** [comment]
+1

**Comment by chriskovacs** [comment]
+1 ...this is driving my team nuts.

**Comment by nconnector** [comment]
+1 this is still happening

**Comment by RanVaknin** [comment]
Hi all,

I have marked this for prioritization, if someone wants to take a stab at a PR that would be very appreciated. 

Thanks,
Ran~

**Comment by trivikr** [comment]
Verified that VSCode pauses on Promise.reject when "Uncaught Exceptions" is turned on.

<details>
<summary>Screen recording</summary>

https://github.com/aws/aws-sdk-js-v3/assets/16024985/54a4fff2-b6c9-4a8c-9d78-18abded150eb

</details>
