### ISSUE TITLE
Cross-region CopyDBClusterSnapshot is failing due to `PreSignedurl could not be authenticated`

### ISSUE THREAD

**Issue by mertcanyalhi** [aws/aws-sdk-js-v3#2269]
## Describe the bug
When performing a cross-region `CopyDBClusterSnapshot` operation, the operation is failing with the following error: `InvalidParameterValue: PreSignedurl could not be authenticated`. 

#### SDK version number
`@aws-sdk/client-rds@3.13.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v14.16.0

## Steps to reproduce
```
            const client = new RDSClient({
                region: AWS_REGION_SRC
            });
            const cmdCopySnapshot = new CopyDBClusterSnapshotCommand({
                SourceDBClusterSnapshotIdentifier: 'arn:aws:rds:eu-central-1:000000000000:cluster-snapshot:rds:my-lovely-cluster-2021-04-15-07-12',
                TargetDBClusterSnapshotIdentifier: 'test',
                KmsKeyId: 'arn:aws:kms:eu-west-1:888888888888:key/00000000-0000-0000-0000-000000000000',
                CopyTags: true
            });
            const copyResult = await client.send(cmdCopySnapshot);
```

#### Observed behavior
- Passing an ARN under `SourceDBClusterSnapshotIdentifier` causes a `PreSignedUrl` to be generated, which is expected. 
- Tested the same operation with aws cli and aws-sdk v2, both work as expected with the exact same inputs (except for the `SourceRegion`, which does not exists in aws-sdk v3 due to the mechanism explained above).
- Compared the `PreSignedUrl` that was generated with aws-sdk v2 and noticed that aws-sdk v2 has added `TargetDBClusterSnapshotIdentifier` while aws-sdk v3 did not.
- Passing a `PreSignedUrl` as a parameter does not change the behavior. Tried the following:
  - A valid `PreSignedUrl`
  - A totally random URL
  - A totally random value

#### Expected behavior
The request should be successfully processed.

**Comment by ajredniwja** [comment]
Hi @mertcanyalhi thanks for opening this issue, when working with cross-region API calls, I got `A KMS key must be specified for copying encrypted snapshot across regions`, so I added one and I get `KMSKeyNotAccessibleFault`. Trying to make it work with another DB. Will post my findings.

**Comment by ajredniwja** [comment]
Hi there, I was able to work with it if I go to the console and do a copy snapShot from there I get a different `KMSKeyId`. 
If I use that `KMSKeyId` in my code to copy across regions, I get all 200s.
