### ISSUE TITLE
Cannot use fromTokenFile function

### ISSUE THREAD

**Issue by mrassili** [aws/aws-sdk-js-v3#2281]
## Describe the bug
I followed the steps for connecting to S3 client using the documentation here https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_credential_provider_web_identity.html but I get `TypeError: Object(...) is not a function` error

## Your environment
Web (React)

#### SDK version number
`@aws-sdk/client-s3@3.13.0`

#### Is the issue in the browser/Node.js/ReactNative?
Browser

#### Details of the browser/Node.js/ReactNative version
node v12.14.0

## Steps to reproduce
exactly as prescribed [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_credential_provider_web_identity.html#fromtokenfile)
```
const { S3Client, PutObjectCommand } = require("@aws-sdk/client-s3");
const { getDefaultRoleAssumerWithWebIdentity } = require("@aws-sdk/client-sts");
const { fromTokenFile } = require("@aws-sdk/credential-provider-web-identity");

const s3Client = new S3Client({
  credentials: fromTokenFile({
    roleAssumerWithWebIdentity: getDefaultRoleAssumerWithWebIdentity(),
  }),
});
```
#### Observed behavior
A runtime error is thrown 
![Screen Shot 2021-04-20 at 12 37 52 PM](https://user-images.githubusercontent.com/25288435/115397577-c6c77b00-a1d5-11eb-9c59-8e9efa18ab1f.png)
![Screen Shot 2021-04-20 at 12 38 18 PM](https://user-images.githubusercontent.com/25288435/115397629-d6df5a80-a1d5-11eb-83c1-9090b4bc2aff.png)
And it looks like `fromTokenFile` depends on `fromWebToken` and this is one is not exported

#### Expected behavior
Connect to s3 client using the provided credentials

**Comment by mrassili** [comment]
@AllanZhengYP @trivikr any help would be very appreciated, it's a blocker

**Comment by AllanZhengYP** [comment]
Hi @mrassili `fromTokenFile()` is suppose to be Node only, it provides the credentials for Kubernete environment. What use case do you need? If you are looking for assuming the role with the role ARN, you can try [`fromWebToken`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_credential_provider_web_identity.html#fromwebtoken)

**Comment by mrassili** [comment]
I have a project using Amazon EKS & OIDC authentication, I want the frontend app to be able to use that to connect to S3 without having to hardcode IAM access & secret keys in the code, what's the function I am supposed to assume the EKS authentication on the front? Should I move the code to the server side? Will it make sense, since I have to use the S3 to upload images on the client

**Comment by AllanZhengYP** [comment]
Hi @mrassili 

In this case you probably need to set up Cognito Identity for your application. We have more documentations for it: https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-credentials-browser.html

**Comment by mrassili** [comment]
@AllanZhengYP we ended up adding a server that connects to S3 using OIDC authentication. Much simpler. But thank you anyway!

**Comment by ajredniwja** [comment]
@mrassili glad things work for you now, I would like to close this issue now, please reach out if you have any other questions.
