### ISSUE TITLE
TypeError: Cannot read property 'byteLength' of undefined

### ISSUE THREAD

**Issue by indrsidhu** [aws/aws-sdk-js-v3#2282]
I am using Kinesis with v3 nodejs.

`Error TypeError: Cannot read property 'byteLength' of undefined
    at Object.fromArrayBuffer (/Users/mac/www/html/test-api/node_modules/@aws-sdk/util-buffer-from/dist/cjs/index.js:6:60)
    at Object.toBase64 [as base64Encoder] (/Users/mac/www/html/test-api/node_modules/@aws-sdk/util-base64-node/dist/cjs/index.js:23:31)
    at serializeAws_json1_1PutRecordsRequestEntry (/Users/mac/www/html/test-api/node_modules/@aws-sdk/client-kinesis/dist/cjs/protocols/Aws_json1_1.js:2626:80)
    at /Users/onebase/www/html/onebase/quoterules-api/node_modules/@aws-sdk/client-kinesis/dist/cjs/protocols/Aws_json1_1.js:2639:16
    at Array.map (<anonymous>)`

Code example is throwing above error is as follow : 
`// Import the required AWS SDK clients and commands for Node.js.
const { CognitoIdentityClient } = require("@aws-sdk/client-cognito-identity");
const {
  fromCognitoIdentityPool,
} = require("@aws-sdk/credential-provider-cognito-identity");
const { Kinesis, PutRecordsCommand } = require("@aws-sdk/client-kinesis");

// Configure Credentials to use Cognito
const REGION = "us-east-2";
const client = new Kinesis({
  region: REGION,
  credentials: fromCognitoIdentityPool({
    client: new CognitoIdentityClient({ region: REGION }),
    identityPoolId: "MY SECRET CODE", // IDENTITY_POOL_ID
  }),
});

var recordData = [];
// Create the Amazon Kinesis record.
var record = {
  Data: JSON.stringify({
    blog: "Wordpress",
    scrollTopPercentage: "25px",
    scrollBottomPercentage: "42px",
    time: new Date(),
  }),
  PartitionKey: "abc", // Must be a string.
};
recordData.push(record);
recordData.push(record);

console.log("recordDatarecordData", recordData);

const uploadData = async () => {
  try {
    const data = await client.send(
      new PutRecordsCommand({
        Records: recordData,
        StreamName: "visitorDataStream",
      })
    );
    console.log("data", data);
    console.log("Kinesis updated", data);
  } catch (err) {
    console.log("Error", err);
  }
};

uploadData();`

**Comment by arlyon** [comment]
Basically their documentation is incorrect here. You cannot send a string as data, it needs to be a Uint8Array. The next question is 'how do you convery arbitrary JS objects to Uint8Array?'. The lack of documentation from the library is frustrating.

**Comment by zerone2** [comment]
@arlyon 
I found this through package code. 
```
export interface PutRecordsRequestEntry {
  /**
   * <p>The data blob to put into the record, which is base64-encoded when the blob is
   *             serialized. When the data blob (the payload before base64-encoding) is added to the
   *             partition key size, the total size must not exceed the maximum record size (1
   *             MiB).</p>
   */
  Data: Uint8Array | undefined;

  /**
   * <p>The hash value used to determine explicitly the shard that the data record is
   *             assigned to by overriding the partition key hash.</p>
   */
  ExplicitHashKey?: string;

  /**
   * <p>Determines which shard in the stream the data record is assigned to. Partition keys
   *             are Unicode strings with a maximum length limit of 256 characters for each key. Amazon
   *             Kinesis Data Streams uses the partition key as input to a hash function that maps the
   *             partition key and associated data to a specific shard. Specifically, an MD5 hash
   *             function is used to map partition keys to 128-bit integer values and to map associated
   *             data records to shards. As a result of this hashing mechanism, all data records with the
   *             same partition key map to the same shard within the stream.</p>
   */
  PartitionKey: string | undefined;
}
```
I could see the data type, it should be Uint8Array | undefined. 
I already fixed my code and find this issue later.
I am now confident. Thanks so much :) 
That v3 documentation is too sparse

**Comment by ahmedelamine** [comment]
Check your credentials in s3Client
Try to type the credentials manual without env variables to eliminate confusion, then use the env variables

```
const s3Client = new S3Client({
  region: REGION,
  credentials: {
    accessKeyId: process.env.ACCESS_KEY,
    secretAccessKey: process.env.SECRET_ACCESS_KEY,
  }
});
```

**Comment by osulli** [comment]
> Check your credentials in s3Client Try to type the credentials manual without env variables to eliminate confusion, then use the env variables
> 
> ```
> const s3Client = new S3Client({
>   region: REGION,
>   credentials: {
>     accessKeyId: process.env.ACCESS_KEY,
>     secretAccessKey: process.env.SECRET_ACCESS_KEY,
>   }
> });
> ```

Why does this work @ahmedelamine ?

**Comment by ahmedelamine** [comment]
After you type the credentials manually, and the code work. Then use environment variables if it's not work, then you debug the environment variables.

**Comment by aldo-rd** [comment]
I goten same error when I used Pascal case style in **AccessKeyId** and **SecretAccessKey**:
```
const s3Client = new S3Client({
  region: REGION,
  credentials: {
    AccessKeyId: myAccessKeyId,
    SecretAccessKey: mySecretAccessKey,
  }
});
```

I changed to Camel style and it works:

```
const s3Client = new S3Client({
  region: REGION,
  credentials: {
    accessKeyId: myAccessKeyId,
    secretAccessKey: mySecretAccessKey,
  }
});
```
