### ISSUE TITLE
Remove duplicated common dependencies among modules

### ISSUE THREAD

**Issue by atyshka** [aws/aws-sdk-js-v3#2283]
### Is your feature request related to a problem? Please describe.
I'm not super familiar with the exact mechanics of how webpack and node modules bundle code, but I'm analyzing my application size and noticed that most of the usage from the aws sdk is from redundant files. I.e. here I have an example of the usage for including the kinesis-video and kinesis-video-signaling clients:

![Screenshot from 2021-04-21 11-46-37](https://user-images.githubusercontent.com/19317207/115582760-423d3100-a297-11eb-98fc-b6657cde68d1.png)

Note the common overlap of the @aws-sdk files from node_modules, duplicating code such as the middleware and sigv4 signer. These are by no means large but when you start to use more than a few modules they really start to add up

### Describe the solution you'd like
Some method that allows these different modules to share the common code

My import code:

```
import {
  KinesisVideoClient,
  GetSignalingChannelEndpointCommand,
} from "@aws-sdk/client-kinesis-video";
import {
  KinesisVideoSignalingClient,
  GetIceServerConfigCommand,
} from "@aws-sdk/client-kinesis-video-signaling";
```

**Comment by monken** [comment]
Can you verify that the two packages are using the same versions of, for example, `aws-sdk/middleware-stack`? You can search in your `yarn.lock` file for `"@aws-sdk/middleware-stack@`. You should only get one match. If there are more try to upgrade the client versions until the additional version is gone.
