### ISSUE TITLE
s3 DeleteObjectsCommand fails with 500

### ISSUE THREAD

**Issue by Drafter500** [aws/aws-sdk-js-v3#2290]
## Describe the bug
When executing `DeleteObjectsCommand` on s3 client it fails with 500 Internal Server Error

#### SDK version number
`@aws-sdk/client-s3@3.13.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v14.15.4

## Steps to reproduce
```JavaScript
const {
  S3Client,
  CreateBucketCommand,
  PutObjectCommand,
  DeleteObjectsCommand,
  ListObjectsCommand,
} = require('@aws-sdk/client-s3');

const bucketName = 'my-bucket';

const s3 = new S3Client({
  region: 'eu-central-1',
  endpoint: 'https://localstack:4566',
  forcePathStyle: true,
});

await s3.send(new CreateBucketCommand({Bucket: bucketName}));

await s3.send(new PutObjectCommand({
  Bucket: bucketName,
  Key: 'my/path',
  Body: 'my-value',
}));

const objects = await s3.send(new ListObjectsCommand({Bucket: bucketName}));

try {
  await s3.send(new DeleteObjectsCommand({
    Bucket: bucketName,
    Delete: {
      Objects: objects.Contents,
    },
  }));
} catch (e) {
  console.log(e); // 500 Internal Server Error
}
```

#### Observed behavior
DeleteObjectsCommand fails with 500.

#### Expected behavior
Command successfully finish

## Additional context
The same sample of code does not reproduce the issue in `^3.12.0`, so this seems to be a regression

**Comment by ajredniwja** [comment]
Hey @Drafter500 thanks for opening the issue, unfortunately I was not able to reproduce the issue, the only thing I changed was to change the endpoint. 500 errors indicate that the request can not be handled at that time. Is the error intermittent or you see it every-time? Have you tried retrying the request?
