### ISSUE TITLE
Importing `@aws-sdk/client-s3` does not work in InternetExplorer

### ISSUE THREAD

**Issue by just-boris** [aws/aws-sdk-js-v3#2292]
## Describe the bug

When I am importing `@aws-sdk/client-s3`, I have the following error in InternetExplorer:

```
Object doesn't support property or method 'from'
```

#### SDK version number
`@aws-sdk/client-s3@3.13.0`

#### Is the issue in the browser/Node.js/ReactNative?
Browser

#### Details of the browser/Node.js/ReactNative version

InternetExplorer 11

## Steps to reproduce

```js
import { S3 } from '@aws-sdk/client-s3';
const s3 = new S3(config);
```

#### Observed behavior

The code does not work in InterntetExplorer

#### Expected behavior

As far as I can understand from this comment: https://github.com/aws/aws-sdk-js-v3/issues/1095#issuecomment-755025978, InternetExplorer is still supported.

## Additional context

I tracked down the error, it happens at this line: https://github.com/aws/aws-sdk-js-crypto-helpers/blob/master/packages/crc32/src/index.ts#L23 (it is not directly in this package, but I opened the issue here, because this is the module I am using directly)

**Comment by just-boris** [comment]
P.S. When I got around the original error via a polyfill, I found a new one: 

```
Unable to set property 'attempts' of undefined or null reference
```

This error is happening around these lines: https://github.com/aws/aws-sdk-js-v3/blob/master/packages/middleware-retry/src/defaultStrategy.ts#L146-L152

`err` value does not have to be an object, it could be a primitive value too. In this particular case, it is a string from this code: https://github.com/aws/aws-sdk-js-crypto-helpers/blob/master/packages/sha256-browser/src/ie11Sha256.ts#L50,L56

**Comment by AllanZhengYP** [comment]
Hi @just-boris 

I put up a fix to the retry handler: https://github.com/aws/aws-sdk-js-v3/pull/2349. I haven't made change to make Uint8Array compatible with IE because I find they are many cases we use `Uint8Array.from` both in JS SDK and AWS Crypto Helpers, and they are on very hot path. Most likely we will provide guidance for using SDK in IE11 with polyfill rather than changing all `Uint8Array.from` to `new Uint8Array`(same as Uint32Array).

**Comment by just-boris** [comment]
Great, that works for me. I will wait for the PR to merge and then try the new SDK version in my project
