### ISSUE TITLE
promise {<pending>} 

### ISSUE THREAD

**Issue by MeRahulAhire** [aws/aws-sdk-js-v3#2299]
I'm trying out this code to listObject from my bucket as below
```js
const  AWS = require('@aws-sdk/client-s3')

const client = new AWS.S3({region: 'ap-south-1'})
const params = {
    Bucket : 'xyz'
}
const data = client.listObjects(params)
console.log(data)
```
and instead of showing me the results, it gives me the promise 
```zsh
C:\Users\Rahul\Desktop\cookie>node index
Promise { <pending> }

C:\Users\Rahul\Desktop\cookie>
```
Can anyone suggest me how to resolve this issue or why is it happening?

**Comment by christiantakle** [comment]
Its a promise you can use `.then` or `async/await` syntax
```
const  AWS = require('@aws-sdk/client-s3')

const client = new AWS.S3({region: 'ap-south-1'})
const params = {
    Bucket : 'xyz'
}
client.listObjects(params).then((data)  => console.log(data))
```

**Comment by MeRahulAhire** [comment]
@christiantakle thanks. It got working. I wish aws had documented it well enough. I guess the older ones for which I raised issue for looks good enough, helps to reduce the code size. I hope the SDK team at aws incudes it

**Comment by trivikr** [comment]
> I wish aws had documented it well enough

@MeRahulAhire Calling await on async operations is documented in client README.
For your specific example in `@aws-sdk/client-s3`, it's available at https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-s3/README.md#asyncawait

This README is also populated on npmjs homepage at https://www.npmjs.com/package/@aws-sdk/client-s3#user-content-asyncawait

As part of API Reference improvement, we're working on generating examples for each command in https://github.com/aws/aws-sdk-js-v3/projects/2#card-59234934

Are there some other ideas on how the documentation can be improved?

**Comment by MeRahulAhire** [comment]
@trivikr cant this work
```js
const data = client.listObjects(params)
```
without async and await like it was working in v2 aws-sdk? I think you can also add that for running the code off the lambda async handler. 

### As for the Docs,
Please, give a nice search bar which has autocomplete searches in the webpage like algolia (check react docs for it). I'm tired of using `ctrl + f` to find it.

Dark mode is must. 

Take the design inspiration from google docs - AWS is huge don't list everything once in a side column, Segregate them in a list of groups like serverless, container, ec2, etc. so that its easy to find and focus. 

UI can be more better

DynamoDB Docs isn't complete #2303 

For more info you can check [my video -  Why I hate AWS](https://www.youtube.com/watch?v=7wVYocGBjDQ)

**Comment by ajredniwja** [comment]
@MeRahulAhire, thank-you so much on your feedback, we look forward to incorporate most of that in our docs most of which were there in V2 API reference. The example above wont work as mentioned in above comment, comparing to V2, the example you mentioned would either need to have a callback or use send command after doing `client.listObjects(params)`. 

With that being said, we really appreciate your feedback, I personally have expressed similar concerns about the documentation in the past. I saw we had a similar conversation in the issue https://github.com/aws/aws-sdk-js-v3/issues/2184 as well which I was successfully able to convey to the team. 

I'd like to track this with https://github.com/aws/aws-sdk-js-v3/issues/2184 and close this one out. 

Please reach out if you have any other questions.

**Comment by MeRahulAhire** [comment]
@ajredniwja sure no worries 👍🏻
