### ISSUE TITLE
Get the Object URL of an uploaded file

### ISSUE THREAD

**Issue by nlucero** [aws/aws-sdk-js-v3#2301]
Is there anywhere in the documentation where it explains (with code samples ideally) how to get the Object URL of an uploaded file?

Scenario: I'm uploading files to a public `S3` bucket via the SDK. Once the file is uploaded, I need to fire a request to another external service and pass the public Object URL of the uploaded file to it:

![2021-04-23_16-27](https://user-images.githubusercontent.com/13350271/115926459-def6fe80-a450-11eb-9329-c986aa577b7a.png)

This is how I'm uploading the file:

```js
async function uploadFile(
  fileBuffer,
  remoteFileName,
  bucketName,
  region,
  acl
) {
  const s3 = new S3Client({ region })

  return await s3.send(
    new PutObjectCommand({
      Bucket: bucketName,
      Key: remoteFileName,
      Body: fileBuffer,
      ACL: acl,
    })
  )
}
```

The response from this command doesn't seem to contain the Object URL:

```json
{
  "$metadata": {
    "httpStatusCode": 200,
    "extendedRequestId": "...",
    "attempts": 1,
    "totalRetryDelay": 0
  },
  "ETag": "\"...\""
}
```

I've even tried getting it by firing a subsequent `GetObjectCommand` for the previously uploaded file. Again, the Object URL doesn't seem to be in the response:

```json
{
  "$metadata": {
    "httpStatusCode": 200,
    "extendedRequestId": "...",
    "attempts": 1,
    "totalRetryDelay": 0
  },
  "AcceptRanges": "bytes",
  "ContentLength": 186530,
  "ContentType": "application/octet-stream",
  "ETag": "\"...\"",
  "LastModified": "2021-04-23T20:31:08.000Z",
  "Metadata": {}
}
```

Is this scenario even supported by the v3 SDK? If so, which _command_ should I use to get the Object URL of an uploaded file?

**Comment by samueleastdev** [comment]
I need the same as this there are many cases where you need to key and bucket returned in a promise.all callback is one so you know what file has been uploaded.

~~~
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: undefined,
    extendedRequestId: 'PB9+9eU4rvF7SNNVAkgXY5BlIBHmVZG/6eTgHkJVPolBDHJ0sGEt9KP65x0pXuGG8mO4VMJ7UJY=',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  AcceptRanges: 'bytes',
  ArchiveStatus: undefined,
  BucketKeyEnabled: undefined,
  CacheControl: undefined,
  ContentDisposition: undefined,
  ContentEncoding: undefined,
  ContentLanguage: undefined,
  ContentLength: 1992246,
  ContentType: 'audio/mpeg',
  DeleteMarker: undefined,
  ETag: '"e54a9e69a99a1732444182b863d77480"',
  Expiration: undefined,
  Expires: undefined,
  LastModified: 2020-10-21T11:55:35.000Z,
  Metadata: {},
  MissingMeta: undefined,
  ObjectLockLegalHoldStatus: undefined,
  ObjectLockMode: undefined,
  ObjectLockRetainUntilDate: undefined,
  PartsCount: undefined,
  ReplicationStatus: undefined,
  RequestCharged: undefined,
  Restore: undefined,
  SSECustomerAlgorithm: undefined,
  SSECustomerKeyMD5: undefined,
  SSEKMSKeyId: undefined,
  ServerSideEncryption: undefined,
  StorageClass: undefined,
  VersionId: undefined,
  WebsiteRedirectLocation: undefined
}
~~~

**Comment by RanVaknin** [comment]
Hi @nlucero, and @samueleastdev 

The S3 API Doesn't offer any API operations that return the URL of an object. Since there is no API operation, the SDK can't offer that info because it's just a client.

However, an object's URL is always the same, following this convention:
`https://{bucket_name}.s3.amazonaws.com/{path}/{to}/{object_name}`

You have to know the key and the bucket you are using to make that request anyway, so just use that same info to construct this URL.

Let us know if you have any other questions.
Thanks,
Ran~
