### ISSUE TITLE
Missing API's in DynamoDB docs 

### ISSUE THREAD

**Issue by MeRahulAhire** [aws/aws-sdk-js-v3#2303]
I'm tying to get a hands on with v3 sdk for DynamoDB but I found that half of the API's like `ListTable`, `PutItem` and many more are missing and there's not clear mention how to use docs properly. A lot of things are missing and docs are incomplete.

Edit: unable to use `documentClient` Properly.

**Comment by ARTushar** [comment]
v3 doesn't have documentClient. You have to use marshall and unmarshall from @aws-sdk/util-dynamodb

**Comment by MeRahulAhire** [comment]
It's there https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/classes/_aws_sdk_lib_dynamodb.dynamodbdocument-1.html but is not documented well

**Comment by trivikr** [comment]
> v3 doesn't have documentClient. You have to use marshall and unmarshall from @aws-sdk/util-dynamodb

The DocumentClient was added for v3 in [@aws-sdk/lib-dynamodb](https://www.npmjs.com/package/@aws-sdk/lib-dynamodb)

**Comment by MeRahulAhire** [comment]
@trivikr the document client isn't documented well. In vscode I don't get any autocomplete like `documentClient.putItem' and it doesn't work
