### ISSUE TITLE
ReferenceError: ReadableStream is not defined

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-sdk-js-v3#2312]
## Describe the bug

If `chunker.ts` falls through a bunch of analysis cases it refers to the `ReadableStream` symbol, which is not imported or defined anywhere (and so is undefined):

https://github.com/aws/aws-sdk-js-v3/blob/28008c2a3e30cd234f447484d76777d5db56dad1/lib/lib-storage/src/chunker.ts#L22

#### SDK version number
`@aws-sdk/lib-storage@3.13.1`

#### Is the issue in the browser/Node.js/ReactNative?
Node

## Steps to reproduce

```ts
import tar from 'tar';

        const source = tar.c({
          gzip: true,
          cwd: files.root,
        }, files.fileNames);

        const upload = new Upload({
          client: await this.s3(),
          queueSize: 4, // optional concurrency configuration
          leavePartsOnError: false, // optional manually handle dropped parts
          params: {
            Bucket: this.bucketName,
            Key: this.remoteDataKey(pv),
            Body: source,
          },
        });
```

#### Observed behavior

```
ReferenceError: ReadableStream is not defined
```

#### Expected behavior

Not this exception.

## Additional context

To my mind a readable stream produced by the `tar` package should just work, but from the source in `chunker.ts` I can tell it's not going to because that stream fails the type analysis.

Unfortunately this looks like it's going to break with much of Node's duck-typed ecosystem.

**Comment by alexforsyth** [comment]
@rix0rrr i'm not able to reproduce your error. the code I have below works just fine for me. Node shouldn't care about the readable stream at all. The interfaces for streams are different between browsers and node, but thats an implementation detail that shouldn't be surfaced to users - so i'm a bit concerned you're getting the error.

Here's my code. I'm running it with `ts-node` to check types, although node should work just fine too.

```
import { c } from 'tar'; // has no default export 'tar'
import { Upload } from "@aws-sdk/lib-storage";
import { S3 } from "@aws-sdk/client-s3";

(async () => {

    const source = c({
        gzip: true,
        // cwd: "CWD",
      }, ["FILE1", "FILE2"]);


    const upload = new Upload({
        client: new S3({}),
        queueSize: 4, // optional concurrency configuration
        leavePartsOnError: false, // optional manually handle dropped parts
        params: {
            Bucket: "MY_BUCKET",
            Key: "MY_KEY",
            Body: source,
        },
    });

    upload.on("httpUploadProgress", (progress) => {
        console.log("upload progress: ", progress);
    });

    let result = await upload.done();
    console.log(result);
})();

```

Here's the pacakge.json
```
{
  "name": "repro-readable",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@aws-sdk/client-s3": "^3.14.0",
    "@aws-sdk/lib-storage": "^3.14.0",
    "@types/tar": "^4.0.4",
    "tar": "^6.1.0"
  }
}
```

**Comment by garrett-hopper** [comment]
I just ran into this issue when using [jszip](https://github.com/Stuk/jszip) which uses [readable-stream](https://github.com/nodejs/readable-stream#readme). When `@aws-sdk/lib-storage` tried to check if the `Body` was a `Readable`, it was a different `readable-stream` instance of `Readable` rather than the Node.js `Readable.`.
Setting a `READABLE_STREAM=disable` environment variable (see [readable-stream readable.js#L2](https://github.com/nodejs/readable-stream/blob/master/readable.js#L2) resolves this, however it doesn't seem ideal. I'm not sure where the change should occur though. Should `@aws-sdk/lib-storage` check for the [readable-stream](https://github.com/nodejs/readable-stream#readme) instance?

@alexforsyth, can this issue be reopened?

**Comment by S0c5** [comment]
I'm facing the same issue with a custom implementation of Stream:

```typescript
class CustomStream extends Stream {
  constructor(){ }
}

const MultiPart = new Upload({ client: s3Client, params: {  Body: new CustomStream()  }})
```
Can we reopen this issue to see how we can fix this issue?
