### ISSUE TITLE
TypeError: Cannot set property 'middlewareStack' of undefined on Cloudflare Workers

### ISSUE THREAD

**Issue by hungrymonkey** [aws/aws-sdk-js-v3#2320]
## Describe the bug
Dynamodb Client crashes whenever I attempt create a `ScanCommand` on Cloudflare Workers. `PutItemCommand` and `GetItemCommand` works.

## Your environment

webpack.config.js
```javascript
module.exports = {
	target: "webworker",
	entry: "./src/index.js", // inferred from "main" in package.json
	resolve: {
		extensions: ['.ts', '.tsx', '.js'],
		plugins: []
	},
	optimization: {
		minimize: false,
	  },
	output: {
		path: __dirname + "/dist",
		publicPath: "dist",
		filename: "worker.js"
	}
}
```
package.json
```json
{
  "private": true,
  "version": "1.0.0",
  "description": "A template for kick starting a Cloudflare Workers project",
  "main": "./src/index.js",
  "scripts": {
    "build": "webpack",
    "test": "echo \"Error: no test specified\" && exit 1",
    "format": "prettier --write '**/*.{js,css,json,md}'"
  },
  "devDependencies": {
    "prettier": "^1.18.2",
    "webpack": "^5.35.1",
    "webpack-cli": "^4.6.0"
  },
  "dependencies": {
    "@aws-sdk/client-dynamodb": "^3.13.1",
    "@aws-sdk/client-sqs": "^3.13.1",
    "hash.js": "^1.1.7",
    "path": "^0.12.7",
    "permit": "^0.2.4"
  }
}
```

#### SDK version number
`@aws-sdk/client-dynamodb@3.13.1`

#### Is the issue in the browser/Node.js/ReactNative?
Cloudflare Workers

#### Details of the browser/Node.js/ReactNative version
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`
wrangler --version
wrangler 1.16.0

## Steps to reproduce
Please share code or minimal repo, and steps to reproduce the behavior.
```
function myCredentialProvider() {
    return {
        // use wrangler secrets to provide these global variables
        accessKeyId: AWS_ACCESS_KEY_ID,
        secretAccessKey: AWS_SECRET_ACCESS_KEY
    }
}
const dbclient = new DynamoDBClient({
    region: "us-east-1",
    credentialDefaultProvider: myCredentialProvider
});
async function dynamoGetShips(dbclient) {

    // replace with your table name and key as appropriate
	const params = {
		TableName: "tablename",
		Select: "ALL_ATTRIBUTES",
		FilterExpression: "NOT_NULL"
	};
    const get = ScanCommand(
		params
	);
    const results = await dbclient.send(get);
	console.log(results)
    return results;
}
```

#### Observed behavior
A clear and concise description of what happens.
```
worker.js:3503 Uncaught (in promise) TypeError: Cannot set property 'middlewareStack' of undefined
    at Command (VM3 worker.js:3503)
    at ScanCommand (VM3 worker.js:15832)
    at dynamoGetShips (VM3 worker.js:21968)
    at handleGetShips (VM3 worker.js:21985)
    at Object.handler (VM3 worker.js:22038)
    at Router.route (VM3 worker.js:21123)
    at handleRequest (VM3 worker.js:22046)
    at VM3 worker.js:22003

var command_Command = /** @class */ (function () {
    function Command() {
        this.middlewareStack = constructStack();
    }
    return Command;
}());
```

#### Expected behavior
I should be able to scan a DynamoDB table.

#### Screenshots

<img width="1792" alt="Screen Shot 2021-04-28 at 10 21 22 PM" src="https://user-images.githubusercontent.com/771339/116505553-1231f700-a870-11eb-9a0e-84840adf76a0.png">

**Comment by AllanZhengYP** [comment]
Hi @hungrymonkey 

I find that in your reproduction code doesn't use `new` key name more the command:

```js
/*use new for command*/
const get = new ScanCommand(
    params
);
```

But I agree the error message is not helpful. If you are interested, you can contribute to add a check in client.send code: https://github.com/aws/aws-sdk-js-v3/blob/ca6f146946ff2ff178495fea902c3c18e93420a3/packages/smithy-client/src/client.ts#L40-L44 to require the command to be expected instance.

**Comment by hungrymonkey** [comment]
Hi @AllanZhengYP , 

Your explanation makes sense. I wondered why my GetItemCommand call worked. ScanCommand and many commands listed here do not have any sample code. I piece together the generic docs with call signature.

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/classes/scancommand.html
https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/dynamodb-example-table-read-write-batch.html

On second evaluation, all the commands has the keyword new.

**Comment by hungrymonkey** [comment]
I wonder if we are allowed to check the `new.target` keyword in ESMAScript 6

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target

**Comment by AllanZhengYP** [comment]
I think we can. Then it requires the validator to be generated in every command. It will add code to every single API. I would prefer adding a check in the send function once only, if it's viable.

**Comment by hungrymonkey** [comment]
@AllanZhengYP , I did some tests the code crashes on initialization. Without the `new` keyword, the code stops there. It will never reach the `DynamoDBClient.send()`

**Comment by vudh1** [comment]
Hi @hungrymonkey is this still persisting with the latest version of SDK?

**Comment by hungrymonkey** [comment]
@vudh1  I have not touch the SDK in months. This bug relates to the unhelpful errors message provided by the SDK. If the error messages changed, you can close the issue. If not, keep the issue up until somebody creates better debug messages. As AllahZhengYP noted, the problem is in the critical path. This issue would probably be on the back burner for Amazon.
