### ISSUE TITLE
Anonymous AWS Credentials (for S3)

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-sdk-js-v3#2321]
### Describe the solution you'd like

I need to make anonymous requests to S3. In the Java SDK, there are `AnonymousAWSCredentials` for this: https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/AnonymousAWSCredentials.html

Do you have something similar? How does it work for the JS SDK?

### Describe alternatives you've considered

I grepped the repository for the word "anonymous" but nothing obvious came up.

### Additional context

`GetObject` and `ListObjects` are operations that can be performed without authentication.

**Comment by stephankaag** [comment]
Workaround:

```new S3Client({
  signer: { sign: async (request) => request }
});
```

**Comment by andrecadete** [comment]
@AllanZhengYP 
Sorry but #2949 is closed as duplicate of this one...??

How is a does a request for Synchronicity relate to a request to add classes present on other SDKs?

I want to + #2949 but I have 0 interest about #2321.

**Comment by jordan-brough** [comment]
Ditto to the above comment. @DewaldDeJager could open a new ticket to resurface the issue you raised in #2949?

**Comment by tbartley** [comment]
This has been given the label `workaround-available` but the workaround seems to be to use V2 of the SDK. This is not really a work around.

**Comment by mrclay** [comment]
@tbartley FYI the workaround above works on V3.

**Comment by gurugautham** [comment]
When trying the workaround for the listObjectsV2 command I get the error: InvalidRequest: The authorization mechanism you have provided is not supported. Please use Signature Version 4.

**Comment by aBurmeseDev** [comment]
Hi everyone, checking in here. Looks like the workaround mentioned [above](https://github.com/aws/aws-sdk-js-v3/issues/2321#issuecomment-916336230) has been confirmed to work for both v2 and v3. For the team to consider this feature, we'll need to gather some specific use cases and how much impactful this will be for our customers. Please feel free to share your use case as well as 👍🏽 the original post for better reach. 
In the meantime, we suggest the available workaround and will check back here for updates.

**Comment by kslbdev** [comment]
can you read the comments properly? Specifically andrecadete's comment.

"Sorry but #2949 is closed as duplicate of this one...??". 

You close another issue as duplicate as this one, but this one is specific to signer!
