### ISSUE TITLE
How can I make an athena query using aws sdk in react.js.

### ISSUE THREAD

**Issue by simon-zhangmuye** [aws/aws-sdk-js-v3#2338]
Hi guys,
I am looking for a way to query athena in react.js.
Does anyone know how to do it?

**Comment by AllanZhengYP** [comment]
Hey can you make sure you are using the [@aws-sdk/client-athena](https://www.npmjs.com/package/@aws-sdk/client-athena) package? If you are, we have a workshop that includes a sample React frontend: https://github.com/aws-samples/aws-sdk-js-v3-workshop.
