### ISSUE TITLE
suggestion: set up greenkeeper for package updates

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#234]
[Greenkeeper](https://greenkeeper.io/) is a really good tool for automated dependency management.
We use it in [fastify](https://github.com/fastify/fastify) packages, and it's pretty helpful.

It can be set up once existing dependencies are updated.
Greenkeeper will take up task of updating dependencies (like lerna in PR https://github.com/aws/aws-sdk-js-v3/pull/233 for example)

**Comment by AllanFly120** [comment]
@trivikr This is helpful. I think using it is much better than without this tool.  A caveat is that most of our dependies lies in the dev dependencies which would only be used at release or doing code gen, we may not cover them in our github CI script and their breaking change may still break our release.

**Comment by AllanFly120** [comment]
@trivikr I'm going to setup the Greenkeeper. Do you think free version is enough for now?

**Comment by trivikr** [comment]
We were pending updating of Jest from v20->v24 prior to using greenkeeper
Jest was updated in #243

**Comment by trivikr** [comment]
The first PR to enable greenkeeper is at #248

**Comment by trivikr** [comment]
Closing as greenkeeper was set up in #248, and has posted update PRs since then (example #252)
