### ISSUE TITLE
ZA̡͊͠͝LGΌ causes "Invalid MD5 checksum on messages"

### ISSUE THREAD

**Issue by pauldraper** [aws/aws-sdk-js-v3#2362]
The unholy child weeps the blood of virgins, the tainted souls are summoned into the realm of the living, dooming humanity to an eternity of dread torture, transporting the programmer's consciousness into a world of ceaseless screaming. You have summoned Zalgo.

```ts
const decodeEscapedXML = (str: string) =>
  str
    .replace(/&amp;/g, "&")
    .replace(/&apos;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/&gt;/g, ">")
    .replace(/&lt;/g, "<");
```

https://github.com/aws/aws-sdk-js-v3/blob/v3.14.0/clients/client-sqs/protocols/Aws_query.ts#L3133-L3139

Maybe try using an XML parser instead?

---

There are multiple obvious problems with this:

1. `&#xD;` decodes to `&#xD;` (wrong) not carriage return (correct)
2. `&amp;lt;` decodes to `<` (wrong) not `&lt;` (correct)

Thanks to (1), all my HL7 messages in my SQS FIFO queue won't process because carriage returns broke the client. I haven't run into (2), but I'm sure I will eventually.

Such is the life of the foolish souls who try parsing XML with 5 lines of regex.

(Silver lining is thanks to the MD5 checksum, this bug only causes unavailability instead of corruption.)

**Comment by alexforsyth** [comment]
Love the description. Lemme take a look

**Comment by alexforsyth** [comment]
We're gonna do an internal review later this morning. When we have some consensus we'll open it up to public discussion/PRs

**Comment by trivikr** [comment]
I'm able to reproduce issue with SQS message message `hello\r\nworld`

```console
$ node -v
v14.16.1
```

<details>
<summary>package.json</summary>

```
    "@aws-sdk/client-sqs": "3.15.0",
    "md5": "2.3.0"
```

</details>

<details>
<summary>Code</summary>

```js
import { SQS } from "@aws-sdk/client-sqs";
import md5 from "md5";

const region = "us-west-2";
const client = new SQS({ region });

const QueueName = `test-${Date.now()}`;
const { QueueUrl } = await client.createQueue({ QueueName });

const MessageBody = `hello\r\nworld`;
console.log(MessageBody);
const { MD5OfMessageBody } = await client.sendMessage({
  MessageBody,
  QueueUrl,
});

console.log(
  `\nmd5 check for sent message: ${md5(MessageBody) === MD5OfMessageBody}`
);

const response = await client.receiveMessage({ QueueUrl });
console.log(
  `md5 check for received message: ${
    md5(MessageBody) === md5(response.Messages[0].Body)
  }`
);
console.log(
  `\nStrict Equality Comparison: ${MessageBody === response.Messages[0].Body}`
);

console.log(response.Messages[0].Body);

await client.deleteQueue({ QueueUrl });

```

</details>

<details>
<summary>Output</summary>

```console
$ node sqs.mjs
hello
world

md5 check for sent message: true
/Users/trivikr/workspace/test/node_modules/@aws-sdk/middleware-sdk-sqs/dist/cjs/receive-message.js:21
            throw new Error("Invalid MD5 checksum on messages: " + messageIds.join(", "));
                  ^

Error: Invalid MD5 checksum on messages: 6ddadd53-e4ce-44ea-abb8-a2e5ca1dcfe0
    at /Users/trivikr/workspace/test/node_modules/@aws-sdk/middleware-sdk-sqs/dist/cjs/receive-message.js:21:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/trivikr/workspace/test/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22
    at async file:///Users/trivikr/workspace/test/sqs.mjs:21:18
```

</details>

This issue is not reproducible with AWS SDK for JavaScript (v2), tested with `v2.897.0`.

**Comment by trivikr** [comment]
This is an issue with upstream dependency `fast-xml-parser` which is being discussed at https://github.com/NaturalIntelligence/fast-xml-parser/issues/342

While the fix is available, we'll provide a workaround in AWS SDK for JavaScript (v3).

**Comment by trivikr** [comment]
The upstream `fast-xml-parser` used to have an option called `decodeHTMLchar` in the past.
It was removed in favor of `tagValueProcessor` in https://github.com/NaturalIntelligence/fast-xml-parser/commit/5ac57a508b8156549e8e9c01848d5f7e627e43f9
