### ISSUE TITLE
AWS Lex V2 -- putSession command gives unknown format (base64 on gzip) messages and SessionState in response

### ISSUE THREAD

**Issue by hari-007** [aws/aws-sdk-js-v3#2363]
## Describe the bug
- Somehow, this javascript SDK for putSession command of Lex Runtime V2  module is always giving the unknown formatted response for messages and sessionState.
-  _I couldn't parse it or decode with generally known params like JSON parse or baseg4 decode._
- I added a console log and observed below output from this line [(**deserializeAws_restJson1PutSessionCommand**)](https://github.com/aws/aws-sdk-js-v3/blob/4904f6abdb9791a5abfc164504e554a2c4f0ffa9/clients/client-lex-runtime-v2/protocols/Aws_restJson1.ts#L662) 

It should return the decode/parsed data for messages and sessionState (JSON).

#### SDK version number
All 3 released versions of `@aws-sdk/client-lex-runtime-v2@3.14.0` and  `@aws-sdk/client-lex-runtime-v2@3.13.1` ...

#### Is the issue in the browser/Node.js/ReactNative?
`Node.js` from `Mac OS 10.15.*`

#### Details of the browser/Node.js/ReactNative version
`v12.22.1`

## Steps to reproduce
As per the below 2nd screenshot, you should get this issue straight away with the first response itself.

#### Observed behavior
- Response is not coming as expected format. Either encoded or unserialized or unparsed.
- Reading a piece of huge information or actual data from the response headers (messages and sessionState). I don't know why you went to this approach (Maybe because of HTTP2 or some other reasons)

#### Expected behavior
- Response of messages and sessionState should be a JSON like **recognizeUtterence** and other commands.
- Based on the size of messages and sessionState, content should be coming from the body instead

#### Screenshots
- _Screenshot 1:_ The console log code snippet and output for a request

![image](https://user-images.githubusercontent.com/5758223/117544047-7a5da700-afed-11eb-9a38-9c9580e62010.png)

- _Screenshot 2:_ putSession calling code as per the docs.

![image](https://user-images.githubusercontent.com/5758223/117544193-4636b600-afee-11eb-98d7-2f93614a2262.png)

## Additional context
- Below is the session state, I have sent with the request:
` {
        dialogAction: {
          type: 'Delegate'
        },
        intent: {
          name: 'WelcomeChat'
        },
        sessionAttributes: {}
      }`

**Comment by hari-007** [comment]
I got the solution after looking at API documentation from lex v2 developer docs. Actually, I found it in [recognizeUtterence](https://docs.aws.amazon.com/lexv2/latest/dg/API_runtime_RecognizeUtterance.html) instead of recognizeText.

### Solution for Observed issue 1:

- You always have to decode first and then decompress.  (_I used zlib and Buffer from node js core and you can use your own_)
- Below is the code which I got the solution: (_Note: Don't stringify the decoded content, just sent that buffer to zlib.gunzip_).

```js
const zlib = require('zlib');
const decoded_x_amz_header = 'H4sIAAAAAAAAAIuuVkrOzytJzStRslLySM3JyVcILU4t0lFQ0oFJhFQWpAIlA3ISM/NCUitKlGpjAf8/MMc2AAAA';

const decodedData = Buffer.from(decoded_x_amz_header, 'base64');
console.log(decodedData);

const decompressData = zlib.gunzipSync(decodedData).toString();
console.log(decompressData);
```

### Answer for Observed issue 2:
- At this moment, I haven't calculated the outcome of the worst-case possibility for the size of the headers limit issue by passing huge information through headers.
- Just to assume people are still using node 12 or less and the default header size is `8kb`. Then the maximum allowed slots (100) per intent and a response card can capture 50000 characters ( which is 50KB = 8 bits X 50,000) would be a 50KB.
- So, with the regular check, a single card is already exceeding the max header size. 
- But we have an advantage of gzip here and  I don't know how great we are compressing and by the worst-case possibility, which would be `5 MB` (50 KB of 1 response card slot times 100 slots per intent).

I am okay to close this issue now, with or without an answer for the second point.

**Comment by ajredniwja** [comment]
Hi @hari-007 thanks for opening this issue, and I am glad that you found the solution. I am not sure if thee is anything that might need to be answered since you covered it all. I will close this issue, please leave a comment if you have any questions.
