### ISSUE TITLE
Fixed in: https://github.com/aws/aws-sdk-js-v3/releases/tag/v1.0.0-alpha.22

### ISSUE THREAD

**Issue by thereallimardo** [aws/aws-sdk-js-v3#2366]
Fixed in: https://github.com/aws/aws-sdk-js-v3/releases/tag/v1.0.0-alpha.22

_Originally posted by @AllanZhengYP in https://github.com/aws/aws-sdk-js-v3/issues/881#issuecomment-585954064_

how is this a new fix when it shows advance coding ?  we can post the fix forward by using getBlob, -__-

**Comment by AllanZhengYP** [comment]
Hi @thereallimardo 

Can you elaborate the question? You are refering to an old version, the latest versions can be found on [releases page](https://github.com/aws/aws-sdk-js-v3/releases)
