### ISSUE TITLE
tslib ^2.0.0 dependency should be ^2.1.0

### ISSUE THREAD

**Issue by maniax89** [aws/aws-sdk-js-v3#2371]
## Describe the bug

when importing the `@aws/client-s3` package to an application that has `tslib>=2.0.0,<=2.1.0`, the project builds fail with

```
Attempted import error: '__spreadArray' is not exported from 'tslib'.
```

This function was introduced in 
https://github.com/microsoft/tslib/releases/tag/2.1.0 in this PR: https://github.com/microsoft/tslib/pull/133

I believe the current `package.json` for `@aws/client-s3` has `tslib: ^2.0.0`

## Your environment

```
yarn why tslib
```

```
yarn why v1.22.10
[1/4] 🤔  Why do we have the module "tslib"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "tslib@2.0.3"
info Has been hoisted to "tslib"
```

#### SDK version number
`@aws-sdk/client-s3@3.14.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
`node -v`
`v14.4.0`

## Steps to reproduce
`yarn install` and `yarn start` your application that has multiple packages that depend on `tslib`, specifically one that depends on one less than `2.1.0`

#### Observed behavior
```
Attempted import error: '__spreadArray' is not exported from 'tslib'.
```

#### Expected behavior
tslib dependency should match the build-time dependency (similar to https://github.com/aws/aws-sdk-js-v3/issues/2207 )

## Additional context
A workaround for `yarn` is to use [yarn resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) feature to force `tslib` >= `2.1.0`

```
"resolutions": {
    "@aws-sdk/client-s3/tslib": "^2.1.0"
  }
```

**Comment by talsalkini** [comment]
I have the same issue but with the library, @aws-sdk/protocol-http. I am using typescript with Yarn 2. 
The error message is:
`.../.yarn/cache/@aws-sdk-protocol-http-npm-3.15.0-c3dfc747e5-90b2b86edd.zip/node_modules/@aws-sdk/protocol-http/dist/es/httpRequest.js
Attempted import error: '__spreadArray' is not exported from 'tslib'.`

**Comment by trivikr** [comment]
The project is using tslib@2.2.0 as per yarn.lock

https://github.com/aws/aws-sdk-js-v3/blob/c7371b6e90e7729cc6f72434529c6691f1f9be55/yarn.lock#L11332-L11335

**Comment by vvo** [comment]
@trivikr yarn.lock is not used by parent projects when installing dependencies. This is only for developers contributing to this project.

**Comment by ajredniwja** [comment]
https://github.com/aws/aws-sdk-js-v3/commit/7040faac07976c1dcfd5240675b82a2f275b2a55 this should solve the issue.

**Comment by ajredniwja** [comment]
Will close this issue, please reach out if you have any other questions.
