### ISSUE TITLE
@aws-sdk/types 3.13.1 is not compatible with Typescript 3.x

### ISSUE THREAD

**Issue by rajivshah3** [aws/aws-sdk-js-v3#2372]
## Describe the bug
Basically the same issue as #2217. This line is not supported in Typescript 3.x:
https://github.com/aws/aws-sdk-js-v3/blob/4904f6abdb9791a5abfc164504e554a2c4f0ffa9/packages/types/src/util.ts#L109

#### SDK version number
`@aws-sdk/types@3.13.1`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
node: v12.19.1
tsc: v3.9.9

## Steps to reproduce
package.json:
```json
{
  "dependencies": {
    "@aws-sdk/types": "^3.13.1"
  },
  "devDependencies": {
    "typescript": "^3.9.9"
  }
}
```

test.ts:
```ts
import '@aws-sdk/types'
```

#### Observed behavior
Running `yarn && yarn tsc test.ts` gives the following output:
```
node_modules/@aws-sdk/types/dist/types/util.d.ts:92:42 - error TS1005: ',' expected.

92 export declare type UserAgentPair = [name: string, version?: string];
                                            ~

node_modules/@aws-sdk/types/dist/types/util.d.ts:92:60 - error TS1005: ',' expected.

92 export declare type UserAgentPair = [name: string, version?: string];
                                                              ~


Found 2 errors.
```

#### Expected behavior
Should compile properly on Typescript 3.x

## Additional context
The backwards-compatible types don't seem to exist at [`dist/types/ts3.4/util.d.ts`](https://unpkg.com/@aws-sdk/types@3.13.1/dist/types/ts3.4/util.d.ts) or [`types/ts3.4/util.d.ts`](https://unpkg.com/@aws-sdk/types@3.13.1/types/ts3.4/util.d.ts) in 3.13.1. They do appear at [`dist/types/ts3.4/util.d.ts`](https://unpkg.com/@aws-sdk/types@3.10.0/dist/types/ts3.4/util.d.ts) in 3.10.0, but I still get an error with that version. As mentioned in the linked issue, 3.6.1 works, but I haven't checked versions between 3.6.1 and 3.10.0. The backwards-compatible types exist for 3.6.1 exist at [`types/ts3.4/util.d.ts`](https://unpkg.com/@aws-sdk/types@3.6.1/types/ts3.4/util.d.ts), so I wonder if that's the issue (in 3.10.0 they were in `dist`).

**Comment by rajivshah3** [comment]
I manually made the change from awslabs/smithy-typescript#338 in `@aws-sdk/types`, ran `yarn pack`, and then `yarn add file://path/to/tarball` and `yarn tsc test.ts` seems to work now

**Comment by richenyadav001** [comment]
Same issue i am also facing
Nodejs Framework: nestjs
TS : "typescript": "^3.9.7"
AWS SDK:  "@aws-sdk/client-s3": "^3.17.0"

Nest has another module for aws sdk but its in aws V2

**Comment by trivikr** [comment]
The issue was with internal release script.
Updates about the fix: https://github.com/aws/aws-sdk-js-v3/issues/2474#issuecomment-871798569
