### ISSUE TITLE
How to disable attempt to get instance metadata when testing with dynamodb-local?

### ISSUE THREAD

**Issue by davidtheclark** [aws/aws-sdk-js-v3#2376]
## Describe the issue with documentation

I am writing tests against [dynamodb-local](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html). So I want to run the SDK with no real credentials.

To "turn off" authentication, I can set my `KEY`-related environment variables to fake values:

```js
process.env.AWS_ACCESS_KEY_ID = 'MOCK_AWS_ACCESS_KEY_ID';
process.env.AWS_SECRET_ACCESS_KEY = 'MOCK_AWS_SECRET_ACCESS_KEY';
```

But the SDK still tries to connect to an instance metadata endpoint, and fails if my test environment is offline:

```
Unable to connect to instance metadata service

      at ClientRequest.<anonymous> (node_modules/@aws-sdk/credential-provider-imds/dist/cjs/remoteProvider/httpRequest.js:14:34)
```

How can I tell the SDK to *not try* to connect to any instance metadata service, or else *not give up* if that attempt doesn't work?

## Steps to reproduce

Try to use the SDK in an offline environment with `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` set to fake values.

#### Observed behavior

The SDK fails hard with the error `Unable to connect to instance metadata service`.

#### Expected behavior

I can tell the SDK to accept the local testing situation (with [dynamodb-local](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html)).

#### Screenshots
N/A

## Additional context
N/A

**Comment by samchungy** [comment]
Have you specified the Dynamnodb endpoint?

**Comment by davidtheclark** [comment]
> Have you specified the Dynamnodb endpoint?

Yes. And I know that the tests are indeed using the dynamodb-local instance. It works as long as the machine is connected to the internet — even if there is no metadata to fetch, and no permissions to fetch it with.
