### ISSUE TITLE
How to prevent SDK leaking host information to AWS?

### ISSUE THREAD

**Issue by oliversalzburg** [aws/aws-sdk-js-v3#2383]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
When pre-signing an S3 URL for a client to upload an image to, the SDK will generate a URL that includes an `x-amz-user-agent` part that leaks information about our host system to the user and AWS:

`&x-amz-user-agent=aws-sdk-js%2F3.13.0%20os%2Flinux%2F4.14.181-140.257.amzn2.x86_64%20lang%2Fjs%20md%2Fnodejs%2F14.16.1%20api%2Fs3%2F3.13.0%20exec-env%2FAWS_ECS_EC2`

We would like this information to not be included in the URL. It is unclear to me what the SDK tries to achieve by including it in the first place.

**Comment by AllanZhengYP** [comment]
Hi @oliversalzburg 

Thank you a lot for reporting this. You are right that SDK should not expose any information about the user who generates the URL. It will be removed in next release. I will keep you posted on this thread.
