### ISSUE TITLE
How to configure retries and see the errors that are causing retries in v3?

### ISSUE THREAD

**Issue by davidtheclark** [aws/aws-sdk-js-v3#2384]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

I'm trying to understand retries in v3 of the SDK.

I have not found any v3 documentation that helps me understand how to configure retries (max attempts, how the backoff works, etc.).

I also haven't found any v3 documentation that tells me how I can run code when retries occur, e.g. with an event listener. I'd like to be able to log how many failed attempts were made before a successful attempt, and what the errors were.

Is there documentation that answers my questions, I just haven't been able to find it? If not, can you please explain how to accomplish these goals with v3?

(I saw https://github.com/aws/aws-sdk-js/issues/3611, but it seems focused on v2 so I opened a new issue.)

**Comment by plus-** [comment]
I'm also interested to hear more about this.

More specifically it seems I can't keep a DDB client instance alive for an extended period of time. Sooner or later it will no longer works and throws error (_Error response received from instance metadata service_)

Should I implement a retry strategy or reinstanciate the client more frequently, or maybe modify a particular option in the client?

**Comment by ajredniwja** [comment]
Hi @davidtheclark @plus- see the [upgrading guide](https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md) under maxRetries section. There is middleware which handles the retries. See https://github.com/aws/aws-sdk-js-v3/blob/main/packages/middleware-retry/src/StandardRetryStrategy.ts for standard retry strategy and finally you can look up information on how middleware can be used in your code see this [blog post](https://aws.amazon.com/blogs/developer/middleware-stack-modular-aws-sdk-js/). Closing this issue, please reach out if you have any questions.

**Comment by sybeck2k** [comment]
This information should be part of the SDK documentation - having it hidden in the upgrade notes or a blog post makes it non-trivial to find...
