### ISSUE TITLE
How to configure timeouts in v3?

### ISSUE THREAD

**Issue by davidtheclark** [aws/aws-sdk-js-v3#2405]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

I'm trying to understand timeouts in v3. So far, I haven't managed to find any documentation that answers these questions:

- What are the default timeouts?
- How do I configure the timeouts, if I want settings other than the defaults?

Is there documentation about this? If not, can you please help with these questions?

(I saw https://github.com/aws/aws-sdk-js/issues/3611, but since it was focused on v2 I thought I'd open a new issue.)

**Comment by AllanZhengYP** [comment]
Hi @davidtheclark 

The http options in v3 is configured differently in v3. You can refer to our [Upgrading Guide](https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md) and go to the `httpOptions` section to see how each of the V2 options migrated to the V3 options.

**Comment by davidtheclark** [comment]
@AllanZhengYP Those must be the bullet points you're indicating:

> connectionTimeout
> 
> v2: Sets the socket to timeout after failing to establish a connection with the server after connectTimeout milliseconds.
> v3: connectionTimeout is available in NodeHttpHandler options.
> timeout
> 
> v2: The number of milliseconds a request can take before automatically being terminated.
> v3: Hard request timeout is not available in NodeHttpHandler, but available as requestTimeout in FetchHttphandler in browsers

Does this mean you can no longer set the equivalent of `timeout` in Node.js? You have to use `connectTimeout` via a custom `NodeHttpHandler`?

The [`NodeHttpHandler`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/classes/_aws_sdk_node_http_handler.nodehttphandler-1.html) docs are extremely sparse. Is there more information somewhere about what it's for and how it works? If I only want to set `connectionTimeout`, can I just create a `NodeHttpHandler` with that setting, or do I also need to configure other settings for it to work correctly?

**Comment by AllanZhengYP** [comment]
Hey @davidtheclark 

> Does this mean you can no longer set the equivalent of timeout in Node.js? You have to use connectTimeout via a custom NodeHttpHandler?

The `timeout` config in v2 SDK equals to NodeHttpHandler's `socketTimeout` config, whereas `connectTimeout` config n v2 SDK equals to the NodeHttpHandler's `connectionTimeout`. You need to set them via a custom `NodeHttpHandler`. The related section is not up-to-date, I will update the UPGRADING.md to clarify it.

> The NodeHttpHandler docs are extremely sparse. Is there more information somewhere about what it's for and how it works?

I'm working on improving the our API reference experience in the [API Reference Improvement project](https://github.com/aws/aws-sdk-js-v3/projects/2). I plan to move the examples in the [UPGRADING.md](https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md) into the API reference page.

Please let me know if you have more suggestions.
