### ISSUE TITLE
endpoint path is ignored in DynamoDB client for requests

### ISSUE THREAD

**Issue by candiduslynx** [aws/aws-sdk-js-v3#2407]
## Describe the bug
When i perform any request, like listTables, I get an error, as the request goes to the resolved IP address, but doesn't use path provided. However, why `signingEscapePath` exists?

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
14

## Steps to reproduce
I create DynamoDB client as follows
```(js)
    const client = new DynamoDB(
        {
            endpoint: DYNAMODB_EP, // this actually has path in it
            endpointDiscoveryEnabled: false,
            disableHostPrefix: true,
            signingEscapePath: false,
            region: "localhost",
            logger: console.log
        });
    await client.listTables({});
```

#### Observed behavior
Request is sent using only resolved IP address.

#### Expected behavior
Request should use path as well.

**Comment by candiduslynx** [comment]
root cause in #2416

**Comment by antonkovalenko** [comment]
Me too!
I have also encountered this bug and my project is blocked!!

**Comment by vudh1** [comment]
Hi @candiduslynx, thanks for reaching out. I'm not able to reproduce this. Can you confirm if you still experience this with the latest version `3.42.0`?
