### ISSUE TITLE
PutParamaterCommand fails when Tags are included

### ISSUE THREAD

**Issue by wettowelreactor** [aws/aws-sdk-js-v3#2409]
## Describe the bug
Including tags with ssm PutParamaterCommand results in validation errors

## Your environment
AWS Lambda, Node 14

#### SDK version number
`@aws-sdk/package-name@version`
@aws-sdk/client-ssm@3.16.0

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`

## Steps to reproduce
Lambda triggered from SNS from successful EC2 ImageBuilder pipeline;
```javascript
import {
    PutParameterCommand,
    SSMClient,
} from "@aws-sdk/client-ssm";

const ssm_client = new SSMClient({region: process.env.AWS_REGION})

exports.handler = async (event: any) => {
    const record = event?.Records?.[0]
    const message = JSON.parse(record?.Sns?.Message)
    await processMessage(JSON.parse(record.Sns.Message))
}

async function processMessage(message: any) {
    const ami = message.outputResources.amis[0]

    const parameter = new PutParameterCommand({
        Name: `/ImagePipeline/latest`,
        DataType: `aws:ec2:image`,
        Type: `String`,
        Value: ami.image,
        Description: `Latest Base Image`,
        Overwrite: true,
        Tier: `Standard`,
        Tags: [
            {Key: `Source`, Value: `EC2 Image Builder`},
        ]
    })

    await ssm_client.send(parameter)
}
```
#### Observed behavior
A clear and concise description of what happens.
```
Client response:
{
  "__type": "ValidationException",
  "name": "ValidationException",
  "$fault": "client",
  "$metadata": {
    "httpStatusCode": 400,
    "requestId": "REDACT",
    "attempts": 1,
    "totalRetryDelay": 0
  }
}
```
#### Expected behavior
The parameter updates and get the proper tags attached.

#### Screenshots
Removing the Tags key from the PutParamaterCommand allows the function to work fine.

**Comment by ajredniwja** [comment]
Hey @wettowelreactor thanks for opening this issue. The tags and overwrite params can NOT be used together. To create a parameter with tags, please remove overwrite flag. To update tags for an existing parameter, please use [AddTagsTorResourceCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-ssm/classes/addtagstoresourcecommand.html). 

I was able to create one with `tags` without the `overwrite` filter and add tags using the `AddTagsTorResourceCommand`

Closing this issue now, please reach out if you have any other questions.
