### ISSUE TITLE
Pinpoint ListTemplatesCommand behaves diferently depending on PageSize attribute

### ISSUE THREAD

**Issue by warriorGod** [aws/aws-sdk-js-v3#2413]
## Describe the bug
I have a few templates in the pinpoint interface. When I create the ListTemplatesCommand with

```
{ ApplicationId: 'xxxx',
  test:createNotifications:setup      PageSize: '100',
  test:createNotifications:setup      Prefix: '_prefix',
  test:createNotifications:setup      TemplateType: 'EMAIL' }
```

I get my template back.

If I call it with 

```
{ ApplicationId: 'xxxx',
  test:createNotifications:setup      PageSize: '1',
  test:createNotifications:setup      Prefix: '_prefix',
  test:createNotifications:setup      TemplateType: 'EMAIL' }
```

I get back the empty list.

Issue: I though PageSize is for paginating the results and should not impact the search for the template.

## Your environment
linux

#### SDK version number
@aws-sdk/client-pinpoint@3.13.0

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v10.16.2

## Steps to reproduce
```
const params = { ApplicationId: 'xxx', PageSize: '100', Prefix: '_', TemplateType: 'EMAIL' }; // malformatted JSON if PageSize is a number
    const command = new ListTemplatesCommand(params);
    const response = await pinpointClient.send(command);
```

#### Observed behavior
When PageSize attribute is '1', no templates are found.

#### Expected behavior
As there is at least one template matching by prefix, I expect it to be returned.

#### Screenshots
/
## Additional context
/

**Comment by vudh1** [comment]
Hi @warriorGod, thanks for reaching out. I am not able to reproduce this issue with different `PageSize` values. Also, `ApplicationId` is not relevant to the `ListTemplatesCommandInput` interface according [this documentation](https://docs.aws.amazon.com/en_us/AWSJavaScriptSDK/v3/latest/clients/client-pinpoint/interfaces/listtemplatescommandinput.html). Let me know if you are still experiencing this with the latest version `3.42.0`
