### ISSUE TITLE
Creating multiple signed URL promises from polly fails with duplicate middleware error

### ISSUE THREAD

**Issue by ShayDahan99** [aws/aws-sdk-js-v3#2417]
## Describe the bug
When preforming multiple requests to web server that returns polly signed url (`getSynthesizeSpeechUrl`), error occurs with the following message: `Duplicate middleware name 'presignInterceptMiddleware'` 

## Your environment
- NodeJS Docker node:12.16.2-alpine3.10
 
#### SDK version number
`"@aws-sdk/polly-request-presigner": "^3.6.1"`
`"@aws-sdk/client-polly": "^3.6.1"`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v12.18.2

## Steps to reproduce
```typescript
    const params: SynthesizeSpeechInput[] = [...];
    const promises = await Promise.all(params.map(params => getSynthesizeSpeechUrl({
      client: this.client,
      params,
    })));
```

#### Observed behavior
As a result we receive `Duplicate middleware name 'presignInterceptMiddleware'` error. 

#### Expected behavior
To be able to send requests without getting this error.

## Additional context
I think it might be related to https://github.com/aws/aws-sdk-js-v3/issues/1857

**Comment by ajredniwja** [comment]
Hi @ShayDahan99, thanks for reporting this, I will post a PR shortly to fix this, should be pretty similar to the other issue.

**Comment by ShayDahan99** [comment]
Do you have any updates?

**Comment by gwhizofss** [comment]
Thank you for re-opening this.  I'm hitting this in Polly:
console.js:288 Playback failed. Error: Duplicate middleware name 'presignInterceptMiddleware'
    at Object.addRelativeTo (MiddlewareStack.js:185:31)
    at getSignedUrl (getSignedUrls.js:41:28)
    at getSynthesizeSpeechUrl (getSynthesizeSpeechUrl.js:6:30)

**Comment by gwhizofss** [comment]
I see this fix is merged. Is there a way for me to get access to the fix, in the SDK?

**Comment by kuhe** [comment]
The fix is available in the following version: https://www.npmjs.com/package/@aws-sdk/polly-request-presigner/v/3.621.0

and higher versions.
