### ISSUE TITLE
yarn add package return 404 not found

### ISSUE THREAD

**Issue by Kennnyoung** [aws/aws-sdk-js-v3#2429]
## Describe the bug
When I follow the instruction in readme to install from source, after executing step 6 yarn add ./path/to/vendor/folder/aws-package, it returns 

 An unexpected error occurred: "https://registry.yarnpkg.com/aws-sdk-client-s3-v3.16.0.tgz: Request failed \"404 Not Found\"".

#### SDK version number
aws-sdk/s3@3.16.0

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
14.16.1

## Steps to reproduce
follow the instructions in readme file install from source, then yarn pack s3 folder

#### Observed behavior
 An unexpected error occurred: "https://registry.yarnpkg.com/aws-sdk-client-s3-v3.16.0.tgz: Request failed \"404 Not Found\"".

**Comment by ajredniwja** [comment]
Hey @Kennnyoung thanks for opening this issue, I was not able to reproduce this issue, I followed all the steps in the readme. I would check if the paths are right and the file actually exists there. I usually use command `pwd` and use that.

**Comment by Kennnyoung** [comment]
Hi @ajredniwja Thank you for the reply! After deleting everything and reinstall, it seems to work now.
