### ISSUE TITLE
SQS Message Attribute DataType value is not validated

### ISSUE THREAD

**Issue by timothyfstephens** [aws/aws-sdk-js-v3#2433]
## Describe the bug

The type description for `Message(System)AttributeValues` include `DataType: string | undefined`
However, the code validates strictly for `Binary` `Number` and `String`

Additionally, the error reporting code for this seems to expect a slightly different structure than is being used.

#### SDK version number
from `yarn.lock`
```
"@aws-sdk/client-sqs@^3.16.0":
  version "3.16.0"
```
#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`
```
node -v
v12.19.0
```

## Steps to reproduce
```
new SQS({}).send({
  QueueUrl: [any],
  MessageAttributes: { test: { DataType: "string", StringValue: "test" } },
  MessageBody: "This is a test message",
});
```

#### Observed behavior
- An error is raised, but not correctly parsed/propogated through
- The raised error should be caught at compile time

#### Expected behavior
- The raised error correctly propogates to the logging system
- Typescript does not compile with bad `DataType`

#### Screenshots
First error received:
![Screen Shot 2021-05-26 at 12 53 32 PM](https://user-images.githubusercontent.com/1302067/119700775-a10b4280-be21-11eb-8f4a-c9fd61ea440b.png)

Actual error:
![Screen Shot 2021-05-26 at 12 53 54 PM](https://user-images.githubusercontent.com/1302067/119700793-a799ba00-be21-11eb-9252-42d740c4c1d4.png)

As you can see from the following lines above, there is an additional bug (looks like the same as the first error) where the error message isn't being parsed correctly.  Below is a screen shot of the offending area (note, I added the console.log(), and the ternary expression on line 1045 to handle the first error)
![Screen Shot 2021-05-26 at 12 56 04 PM](https://user-images.githubusercontent.com/1302067/119700868-bd0ee400-be21-11eb-8d17-048d6abd8d68.png)

**Comment by vudh1** [comment]
Hi @timothyfstephens thanks for reaching out. Are you still experiencing this with the latest version of the SDK?
