### ISSUE TITLE
@aws-sdk/s3-request-presigner breaks commands executed in parallel on the same client

### ISSUE THREAD

**Issue by gojko** [aws/aws-sdk-js-v3#2438]
## Describe the bug

When `@aws-sdk/s3-request-presigner` `getSignedUrl` is executed in parallel (with `Promise.all`) with another command on the same S3Client object, the other command returns an invalid result.

#### SDK version number
 * "@aws-sdk/client-s3": "^3.17.0",
 * "@aws-sdk/s3-request-presigner": "^3.17.0"

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version

```
$ node -v
v14.15.4
```

## Steps to reproduce

* replace the bucket name in the script below and run it in node
* make sure to use a missing file key (the key should not exist on S3)
* the script below should fail with an error on a nonexistent file (HeadObjectCommand should throw); make sure to use a missing file key ('no-file' below).
* Instead, it completes successfully, the HeadObjectCommand does not throw on an missing key

```js
const bucketName = 'SOME_BUCKET_HERE',
	missingKey = 'no-file',
	{ getSignedUrl } = require('@aws-sdk/s3-request-presigner'),
	{ GetObjectCommand, HeadObjectCommand, S3Client } = require('@aws-sdk/client-s3'),
	run = async function(bucketName) {
		const expiresIn = 10
		s3Client = new S3Client(),
			[signature, exists] = await Promise.all([
				getSignedUrl(s3Client, new GetObjectCommand({'Key': missingKey, 'Bucket': bucketName}), {expiresIn}),
				s3Client.send(new HeadObjectCommand({'Key': missingKey, 'Bucket': bucketName}))
			]);
		return {signature, exists};
	};
run(bucketName)
	.then(result => console.log({result}))
	.catch(error => console.error({error}));
```

#### Observed behavior

* instead of throwing on a non existent key, the HeadObjectCommand returns a result below
```
{
  result: {
    signature: '...',
    exists: { '$metadata': [Object], presigned: [Object] }
  }
}
```
* this only happens if the signer and the head object command execute in parallel and share the same client
* my best guess is this is because the presigner injects middleware that intercepts requests (judging by the fact that the response from HeadObjectCommand has a `presigned` field, curiously matching https://github.com/aws/aws-sdk-js-v3/blob/c7371b6e90e7729cc6f72434529c6691f1f9be55/packages/s3-request-presigner/src/getSignedUrl.ts#L55

#### Expected behavior

* getSignedUrl should not be interfering with other commands executing on the same client object in parallel

**Comment by yenfryherrerafeliz** [comment]
Hi @gojko, thanks for opening this issue. I can confirm that this was a problem in the version 3.37.0, nonetheless I just tested with the latest version and it is fixed. So, could you please try it out and let me know.

Thanks!
