### ISSUE TITLE
fix: node-http-handler tests which require NODE_TLS_REJECT_UNAUTHORIZED=0

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#244]
While updating jest v20->v24 in #243, some node-http-handler tests were commented out to unblock Jest upgrade https://github.com/aws/aws-sdk-js-v3/blob/1e156ab4ac5343058eaf7d448a428d8c4b72c844/packages/node-http-handler/src/node-http-handler.spec.ts#L79-L233

These tests need to be fixed

**Comment by alexforsyth** [comment]
Need to see if jest 26 fixes this issue

**Comment by RanVaknin** [comment]
This is terrible.
(test)

**Comment by RanVaknin** [comment]
This is terrible.
(test)

**Comment by RanVaknin** [comment]
This is terrible.
(test)
