### ISSUE TITLE
Complete multipart upload fails with XMLMalformed error

### ISSUE THREAD

**Issue by csombok** [aws/aws-sdk-js-v3#2445]
SDK: @aws-sdk/client-s3
Version: 3.15.0
S3 API service: Noobaa v5

**Describe the problem**

While implementing S3 multi-part upload with the SDK we have got the following error when calling the complete method after each parts had been uploaded successfully by using pre-signed URLs.

**Sample code:**

```
    const completeMultipartUploadParams: CompleteMultipartUploadCommandInput = {
      Bucket: 'sample-bucket',
      Key: 'sample-key',
      UploadId: 'sample-upload-id',
      MultipartUpload: multipartUpload,
    };

    const response = await client.completeMultipartUpload(completeMultipartUploadParams);
```
As I observed based on the code base the issue is caused by a miss-spelled XML element name. The request has **CompletedMultipartUpload** node name instead of **CompleteMultipartUpload**:

```
<?xml version="1.0" encoding="UTF-8"?>
<CompletedMultipartUpload
xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <Part>
    <ETag>&quot;41d1f08e3755fe7c170ad3f06aea9970&quot;</ETag>
    <PartNumber>1</PartNumber>
  </Part>
  <Part>
    <ETag>&quot;83b19bdbc1b0329e452a81d88dc5759a&quot;</ETag>
    <PartNumber>2</PartNumber>
  </Part>
</CompletedMultipartUpload>
```

**Manual workaround**

After manually updating the corresponding script(`node_modules\@aws-sdk\client-s3\dist\cjs\protocols\Aws_restXml.j`s) under the node_modules to fix the element name (**CompletedMultipartUpload** --> **CompleteMultipartUpload**) the complete operation successfully completed.

**AWS Request Reference**

https://docs.aws.amazon.com/AmazonS3/latest/API/API_CompleteMultipartUpload.html

**Comment by csombok** [comment]
Hello, Are there any update on this? The issue is a blocker for us. It seems there is no good workaround to solve it. Thank you in advance

**Comment by csombok** [comment]
I found there is a related issue (https://github.com/aws/aws-sdk-js-v3/issues/1814) and existing PR (https://github.com/aws/aws-sdk-js-v3/pull/2434).

**Comment by ajredniwja** [comment]
Added reviewers to the PR, waiting for a review.

**Comment by youbek** [comment]
Hi Guys!

We are using the Upload method from the lib-storage package, and it's also throwing the same `MalformedACLError`. Because the upload method from lib-storage uses `CompleteMultipartUploadCommand` under the hood.

**Comment by youbek** [comment]
@ajredniwja have you merged PR? or are you waiting for review still? Thanks

**Comment by ignlg** [comment]
This bug is still present on version v3.22. Multi-part upload is unusable because it cannot be completed. This is a blocker for midsize and large uploads.

**Comment by lafiosca** [comment]
Appears #2434 addresses this

**Comment by lafiosca** [comment]
I get this error even when I patch the library manually to correct the `CompletedMultipartUpload` node to `CompleteMultipartUpload` as suggested by the other threads.

This is what Chrome says the library is sending (with the patch):

```
<?xml version="1.0" encoding="UTF-8"?><CompleteMultipartUpload xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Part><PartNumber>1</PartNumber></Part></CompleteMultipartUpload>
```

**Comment by brettstack** [comment]
@lafiosca might need to add `ExposeHeaders: ["etag"]` also https://github.com/aws/aws-sdk-js-v3/issues/1814#issuecomment-893195867

**Comment by lafiosca** [comment]
Thanks for the tip @brettstack, looks promising. Unfortunately for me, I already worked around the problem and decided I didn't need multipart upload for my solution.

**Comment by victorlpgazolli** [comment]
You can replace the invalid XML using a middleware, link:

https://stackoverflow.com/questions/68558841/xml-error-completing-a-multi-part-upload-to-s3-with-aws-sdk-for-javascript-v3
