### ISSUE TITLE
DynamoDB client is timing out after some time

### ISSUE THREAD

**Issue by plus-** [aws/aws-sdk-js-v3#2455]
## Describe the bug
I'm instantiating DDB clients in a nodejs application at startup, those clients are then used by my various services (on HTTP requests or from job queues for example).

After some times (between a couple of days or several weeks) one of the client will crash with a TimeoutError or sometime a "Error response received from instance metadata service" message.

I can't pinpoint the exact reason why the client fails. Restarting the application will fix the issue obviously.

#### SDK version number
`"@aws-sdk/client-dynamodb": "^3.14.0"`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
This is happening in a Docker container with `node:14-alpine`

#### Observed behavior
All further call to the client will fail.

#### Expected behavior
Either the client can recover by itself or the documentation provides guidelines on the lifecycle (including when to kill/recreate the client) and/or expected lifespan of a DDB client.

## Additional context
The Docker container is running in ECS Fargate

**Comment by ajredniwja** [comment]
@plus- can you try using the latest version? I am not particularly able to reproduce it.

**Comment by plus-** [comment]
Actually, I've not had the issue since I've updated to 3.18 about a month ago
