### ISSUE TITLE
KinesisVideoMediaClient and GetMedia command has no response.

### ISSUE THREAD

**Issue by doongsilee** [aws/aws-sdk-js-v3#2457]
## Describe the bug

Hi. I'm trying GET_MEDIA API in react native application to handle realtime content from kvs.

Here are what I'm doing briefly.
```js
//Initialize Media Client with Amplify Auth
const MediaClient = new KinesisVideoMediaClient({
          region,
          credentials: Auth.currentCredentials,
          endpoint: endPoint.DataEndpoint,
        });

//Initialize GET MEDIA Command.
const urlcommand = new GetMediaCommand({
          StartSelector: {
            StartSelectorType: StartSelectorType.NOW,
          },
          StreamName: "B0001",
        });

//Send the command and It's stucked
const data = await MediaClient.send(urlcommand);

//Log the result is not printed
console.log(`the result is ${data}`);

```

The problem is that the send message is stuck and the response never comes back.
so the result log message below was never printed.

after some researches, I found [this post](https://github.com/aws/aws-sdk-js/issues/2013).
It looks similar but I'm not sure this is the same case. but anyway that was an SDK v2 issue. 
how I can I solve this in SDK v3? 
There are no [createReadStream] or [Request] in SDK v3.

I tried deserializeMiddleware but It's not working that I expected.
So do you have any idea about this?

#### SDK version number
`@aws-sdk/package-name@version`
3.14.0
#### Is the issue in the browser/Node.js/ReactNative?
Browser/Node.js/ReactNative
React Native
#### Details of the browser/Node.js/ReactNative version
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`
0.63.4

## Steps to reproduce
Please share code or minimal repo, and steps to reproduce the behavior.

#### Observed behavior
A clear and concise description of what happens.

#### Expected behavior
A clear and concise description of what you were expecting to happen.

**Comment by vudh1** [comment]
Hi @doongsilee, thanks for reaching out. I cannot reproduce the issue. Can you confirm if this behavior still happens in the latest version `3.42.0`?
