### ISSUE TITLE
Cannot use `lib-storage` in webpack project

### ISSUE THREAD

**Issue by korya** [aws/aws-sdk-js-v3#2459]
## Describe the bug

Cannot build a webpack project with the latest SDK installed. I get the following error: `Module not found: Error: Can't resolve 'fs' in ...`

#### SDK version number

- `@aws-sdk/client-s3@3.17.0`
- `@aws-sdk/lib-storage@3.17.0`

#### Is the issue in the browser/Node.js/ReactNative?

```
$ node -v
v15.14.0
$ npm -v
7.12.1
```

#### Details of the browser/Node.js/ReactNative version

Below is a minimal project to reproduce the problem:

```sh
$ tree
.
├── package-lock.json
├── package.json
└── src
    └── index.js

1 directory, 3 files
```

Contents of `package.json`:

```json
{
  "name": "ttt",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "webpack --mode development"
  },
  "devDependencies": {
    "webpack": "^4.46.0",
    "webpack-cli": "^3.3.12",
    "webpack-dev-server": "^3.11.2"
  },
  "dependencies": {
    "@aws-sdk/client-s3": "^3.17.0",
    "@aws-sdk/lib-storage": "^3.17.0"
  }
}
```

Contents of `src/index.js`:

```js
import { S3Client } from '@aws-sdk/client-s3';
import { Upload } from '@aws-sdk/lib-storage';

console.log('+=+ S3Client', S3Client);
console.log('+=+ Upload', Upload);
```

## Steps to reproduce

1. Create the project
2. Install deps: `npm install`
2. Try to build it using `npm run build` (or just by running `npx webpack`)

#### Observed behavior

I get the following error:

```sh

ERROR in ./node_modules/@aws-sdk/lib-storage/dist/es/runtimeConfig.js
Module not found: Error: Can't resolve 'fs' in '/Users/korya/dev/ttt/node_modules/@aws-sdk/lib-storage/dist/es'
 @ ./node_modules/@aws-sdk/lib-storage/dist/es/runtimeConfig.js 3:0-31 7:106-115
 @ ./node_modules/@aws-sdk/lib-storage/dist/es/bytelength.js
 @ ./node_modules/@aws-sdk/lib-storage/dist/es/Upload.js
 @ ./node_modules/@aws-sdk/lib-storage/dist/es/index.js
 @ ./src/index.js
```

#### Expected behavior

The project should have been successfully built.

**Comment by korya** [comment]
Cross-posted in https://github.com/webpack/webpack/issues/13498

**Comment by samchungy** [comment]
Have you added `"target": "node"` to your webpack config?

**Comment by korya** [comment]
No, the target is `web` in my original repo. In the example above, there is no webpack config so the target defaults to `web` as well. In both cases, I get the same error.

**Comment by mikvix** [comment]
same issue on an angular 12 project with webpack v5.39.1

**Comment by mrawdon** [comment]
I was able to fix this by using NormalModuleReplacementPlugin to replace runtimeConfig.js with runtimeConfig.browser.js in my webpack config.  A more elegant solution would be nice but this is working for now

```
      new webpack.NormalModuleReplacementPlugin(
        /.*@aws-sdk.*runtimeConfig.js/,
        function(resource){
          const browserConfig=resource.request.replace('runtimeConfig.js','runtimeConfig.browser.js');
          console.log(`Replacing ${resource.request} with ${browserConfig}`);
          //dont replace the request like the documentation says
          //https://stackoverflow.com/questions/56741909/normalmodulereplacementplugin-does-not-work-when-modifying-resourceregexp-slight
          resource.resource=browserConfig;
        }
      ),
```

**Comment by ajredniwja** [comment]
Try https://github.com/aws/aws-sdk-js-v3/issues/2564#issuecomment-879727349

**Comment by korya** [comment]
Yes, it is still a problem. There is a workaround posted in https://github.com/aws/aws-sdk-js-v3/issues/2459#issuecomment-872366386 but I would like to have it fixed.
