### ISSUE TITLE
Search option does not navigate correctly

### ISSUE THREAD

**Issue by gadavis2** [aws/aws-sdk-js-v3#2460]
## Describe the issue with documentation
Whenever I use the Search option (magnifying glass) and search for "dynamodb" or "apigateway", it navigates me to an incorrect URL.

## Steps to reproduce
Click on the magnifying glass icon, type "dynamodb", click on "@aws-sdk/client-dynamodb"...this doesn't work.

Versus clicking on the "@aws-sdk/client-dynamodb" in the list on the right side of the webpage...this works just fine.

#### Observed behavior
Takes me to a page that says...

Looking for Something?
We're sorry. The web address you entered is not a functioning page on our site. Try one of the following links to find the information you're looking for

#### Expected behavior
I expected it to take me to https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/index.html

#### Screenshots
none

## Additional context
none

**Comment by ajredniwja** [comment]
I was able to reproduce this, when searching in the api reference.

**Comment by AllanZhengYP** [comment]
Hi @gadavis2, we are aware of this issue and it's tracked in [our Project Board for API Reference improvment](https://github.com/aws/aws-sdk-js-v3/projects/2#card-59235029). Currently, anything inside of a service client is not searchable from the search bar on dependency pages(those for packages in `packages/` folder). You can track the board for any API Reference improvements we are doing.
