### ISSUE TITLE
`body` in PutObjectRequest should accept Buffer in Node.js

### ISSUE THREAD

**Issue by zanonnicola** [aws/aws-sdk-js-v3#2461]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

The `PutObjectRequest` in V3 expects the following types for the body: `internal.Readable | ReadableStream<any> | Blob | undefined`

I'm trying to save some JSON to S3. I was expecting the `body` to be able to receive `string` or at least `Buffer` but apparently the types don't allow that. In Node.js you don't have `Blobs` but `Buffers`.

```ts
function storeJsonToS3(location: string, filename: string, contents: string) {
  const request: PutObjectRequest = {
    Bucket: location,
    Key: filename,
    Body: Buffer.from(contents, 'utf8'), // TS error
    ContentType: 'application/json; charset=utf-8',
    CacheControl: 'max-age=60',
  };

  return s3Client.send(new PutObjectCommand(request));
}
```

The way I got around this was to cast it to any:

```ts
Buffer.from(contents, 'utf8') as any
```

But the types should reflect this possibility.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes (via Vercel Lambda Functions)

**Details of the browser/Node.js version**
`v12.x`

**SDK version number**
`@aws-sdk/client-s3": "^3.17.0`

**Expected behavior**
I'm expecting the types in Node.js ENV to reflect the allowed format in the body. The above code works and data is saved in S3 correctly if `Buffer` is used casted to `any`

**Comment by samchungy** [comment]
I think you're meant to use https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_lib_storage.html

**Comment by zanonnicola** [comment]
I could have used that but it's not a hard requirement. Also my Blob is very small and that library seems to be targeted for much bigger files.

Types for the `body` are correct there by the way.

**Comment by yenfryherrerafeliz** [comment]
Hi @zanonnicola, this should not be an issue now. As you can see [here](https://github.com/aws/aws-sdk-js-v3/blob/93d848b5baf828c1296db4dc6e1f78fe4f1a0e69/clients/client-s3/src/commands/PutObjectCommand.ts#L32) the parameter Body for the input now can be a Buffer or string.

I will close this issue since it should be resolved, but please create a new bug report if you have any issues, or just let me know if you have any comments.

Thanks!
