### ISSUE TITLE
forbidden auth with minio

### ISSUE THREAD

**Issue by locktongue** [aws/aws-sdk-js-v3#2465]
## Describe the bug
I am trying to upload some files to my Minio server using the SDK-v3, but the server returns a 403 authentication failure. I think my authentication information and server policy are fine, because I can access them with almost the same configuration on SDK-v2.

#### SDK version number
"@aws-sdk/client-s3": "^3.17.0",

#### Is the issue in the browser/Node.js/ReactNative?
Browser

#### Details of the browser/Node.js/ReactNative version
Chrome: 90.0.4430.212

## Steps to reproduce
1.run a minio docker with [this guide](http://docs.minio.org.cn/docs/master/minio-docker-quickstart-guide)
2.run script below in a react component
```javascript
import { useState } from 'react'

import {
  S3Client,
  PutObjectCommand,
} from '@aws-sdk/client-s3'

function useMinio() {
  const [instance, setInstance] = useState<S3Client | undefined>(undefined)

  const login = () => {
    if (instance) return instance

    const s3Instance = new S3Client({
      region: 'us-east-1',
      endpoint: {
        protocol: 'http',
        hostname: '127.0.0.1',
        port: 9000,
        path: '/',
      },
      forcePathStyle: true,
      credentials: { accessKeyId: 'qwer1234', secretAccessKey: 'qwer1234' },
    })

    console.log('instance', s3Instance)

    setInstance(s3Instance)
    return s3Instance
  }

  const uploadFile = async (file: File) => {
    let _inst = instance
    if (!_inst) _inst = await login()

    const fileName = file.name
    const photoKey = `pic/${fileName}`
    const uploadParams = {
      Bucket: 'testbucket',
      Key: photoKey,
      Body: file,
    }
    try {
      const data = await _inst.send(new PutObjectCommand(uploadParams))
      alert('Successfully uploaded photo.')
      // viewAlbum(albumName);
      return data
    } catch (err) {
      console.log(err)
      return alert('There was an error uploading your photo: ', err.message)
    }
  }

  return {
    instance,
    login,
    uploadFile,
  }
}
// uploadFile(file: File)

```

#### Observed behavior
403 Foibidden - like this:
PUT http://127.0.0.1:9000/testbucket/pic/test.png?x-id=PutObject 403 (Forbidden)

#### Expected behavior
Well, I guess the browser will alert me a success info

**Comment by microsoftly** [comment]
+1

**Comment by ajredniwja** [comment]
Cant open http://docs.minio.org.cn/docs/master/minio-docker-quickstart-guide can you setup a minimal repro repo?
