### ISSUE TITLE
Error in @aws-sdk/client-transcribe-streaming 

### ISSUE THREAD

**Issue by Jack-Sam** [aws/aws-sdk-js-v3#2466]
Hello
I have been trying to use @aws-sdk/client-transcribe-streaming in react native, but it's still not working.
It gives the error below:
TypeError: Invalid attempt to iterate non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
_createForOfIteratorHelperLoose@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.easybot&modulesOnly=false&runModule=true:101839:413
handleResult$@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.easybot&modulesOnly=false&runModule=true:102022:75
tryCatch@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.easybot&modulesOnly=false&runModule=true:7739:23
...

My code is as follows:
...
import 'react-native-get-random-values';
import 'react-native-url-polyfill/auto';

import { TranscribeStreamingClient, StartStreamTranscriptionCommand, MediaEncoding } from "@aws-sdk/client-transcribe-streaming";

...
const transStreamingClient = new TranscribeStreamingClient({
...
})

const _audioStreamFunc = async function*() {
  try {
    while (true)
    {
      const data = await getAudioDataPromise;
      // console.log('got data', data);
      if (!data) break;
      yield data;
    }
  } finally {
    
  }
}

const audioStreamFunc = function() {
  return {
    [Symbol.asyncIterator]: _audioStreamFunc
  }
}

...
    this.audioStream = audioStreamFunc();

    let command = new StartStreamTranscriptionCommand({
      LanguageCode: 'en-US',
      MediaSampleRateHertz: 16000,
      MediaEncoding: MediaEncoding.PCM,
      AudioStream: this.audioStream
    })

    try {
      const response = await transStreamingClient.send(command);
      const transcribesStream = response.TranscriptResultStream;
      const handleResult = async function() {
        for await (const data of transcribesStream) {
          console.log(data);
		  ...
        }
      };

      handleResult();
    } catch (e) {
      console.log(e);
    }
  }

...

Could anyone help me to make this work?
Thanks in advance.

_Originally posted by @Jack-Sam in https://github.com/aws/aws-sdk-js-v3/discussions/2447_

**Comment by ajredniwja** [comment]
Hi @Jack-Sam thanks for opening this issue, I have verified working code here: 
https://github.com/ajredniwja/transcribe-example

Also a complete working app found at: https://github.com/awsdocs/aws-doc-sdk-examples/tree/master/javascriptv3/example_code/cross-services/transcribe-streaming-app

Closing this issue now please let us know if that doesn't solve the issue or if you have any other questions.

**Comment by Jack-Sam** [comment]
Thanks for your email.
I am trying to use audio data from mobile microphone for aws transcribe
streaming.
But the sample code is getting data from file.
I used react-native-audio-record to get audio data and make it work with
the aws module, but unfortunately the accuracy was very low.
Maybe the implementation on getting and feeding data to the module has some
issues, or it's due to low processing speed on js side.
So now I am going to do this on native side.
I tried to find a java package. But I cannot find one for aws transcribe
streaming. (found one for aws transcribe)
Could you tell me what the name of java package for mobile is?
