### ISSUE TITLE
DynamoDB performance: client being CPU hungry - consuming entire CPU with relatively low request rate 

### ISSUE THREAD

**Issue by matej-prokop** [aws/aws-sdk-js-v3#2469]
## Describe the issue
During perf tests of DynamoDB client (`@aws-sdk/client-dynamodb`) we observed that the client consumes a lot of CPU for every request to DynamoDB. Eating entire one CPU core at ~330 requests to Dynamo per second.

#### SDK version number
`"@aws-sdk/client-dynamodb": "3.13.1"`

#### Details of Node.js version
Running as docker container based on `node:14.17.0-alpine3.11` image

## Additional context
We created a dummy Node.js application that runs HTTP server (Express.js). It has two routes:
1. one that reads data from DynamoDB (using `GetItemCommand`)
2. second that writes data to DynamoDB (using `UpdateItemCommand`)

Request to express API are mapped 1:1 to requests to DynamoDB. There is no other logic. Using simple data (string as key, integer as value) in Dynamo. We started the application as docker container with cpu-limit=1 (no getting more than 1 CPU core) and limit of 128 MB of memory. 

Then we ran a perf test for it - in each iteration - reading one random item from DB (1) and then doing one write (2). Our DynamoDB table was pre-scales so we didn't consumed more than 25% of provisioned capacity during the test (and there were no throttling events).    

#### Client initialization

On application startup, it initialize DynamoDBClient in following way:

```js
const { DynamoDBClient } = require("@aws-sdk/client-dynamodb");

const dynamoClient = new DynamoDBClient({
  region: "us-east-1,
  endpoint: undefined,
  apiVersion: "2012-08-10",
  credentials: {
    accessKeyId: "<<our-key-id>>",
    secretAccessKey: "<<our-access-key>>"
  }
  tableName: "<<our-table-name>>",
  maxAttempts: 5
})
```

and re-use it for all requests/queries to DynamoDB.

## Results
Max application throughput: 
- ~330 rps - when using DynamoDB (client from aws-sdk-js-v3)
- ~1900 rps - when using Redis instead of DynamoDB
- ~2500 rps - when replacing DynamoDB by in-memory storage

Is there any configuration option that makes DynamoDB client less CPU hungry? That we can use to increase max throughput...

**Comment by davidtheclark** [comment]
@matej-prokop I'm curious if you've seen the same problem with v2 of the SDK, or if you've only tried v3?

**Comment by matej-prokop** [comment]
I only tried v3 SDK
