### ISSUE TITLE
Type error in http-request-handler with AbortSignal in paginateScan

### ISSUE THREAD

**Issue by markhker** [aws/aws-sdk-js-v3#2472]
## Describe the bug
When I try to use abortSignal in paginateScan with the '@aws-sdk/abort-controller' AbortContoller I get a type error:
`TypeError: Failed to construct 'Request': member signal is not of type AbortSignal.
    at FetchHttpHandler.handle (fetch-http-handler.js?bc25:43)
    at eval (ScanCommand.js?b825:77)
    at eval (deserializerMiddleware.js?fa37:8)
    at step (tslib.es6.js?e7de:102)
    at Object.eval [as next] (tslib.es6.js?e7de:83)
    at eval (tslib.es6.js?e7de:76)
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js?e7de:72)
    at eval (deserializerMiddleware.js?fa37:4)
    at eval (middleware.js?c362:36)`

## Your environment
Node v14.16.1
Electron v13.0.1

#### SDK version number
`@aws-sdk/abort-controller: ^3.18.0`
`@aws-sdk/client-dynamodb: ^3.18.0`

#### Is the issue in the browser/Node.js/ReactNative?
Electron

#### Details of the browser/Node.js/ReactNative version
Electron v13.0.1

## Steps to reproduce
```js
const abortController = new AbortController()
    let tableData = []
    const paginatorConfig = {
      client: new DynamoDBClient({ credentials, region }),
      pageSize: 100,
    }
    const defaultScanParams = {
      TableName: 'table-name',
      ReturnConsumedCapacity: 'INDEXES',
    }

    const additionalArgs = {
      abortSignal: abortController.signal,
    }

    const paginator = paginateScan(paginatorConfig, defaultScanParams, additionalArgs)

    for await (const page of paginator) {
      if (tableData.length > 200) {
        abortController.abort()
      }
    tableData.push(page)
}
```

#### Observed behavior
Console is throwing an type error, when I pass the abort controller signal

#### Expected behavior
The abortSignal should be passed with the correct type

**Comment by hugomassing** [comment]
I have the same error with React using `UploadPart`. 

Your environment
React v16.3

SDK version number
@aws-sdk/abort-controller: ^3.18.0
@aws-sdk/client-s3: ^3.18.0

Is the issue in the browser/Node.js/ReactNative?
Browser 

Details of the browser/Node.js/ReactNative version
Chrome Version 90.0.4430.212

**Comment by markhker** [comment]
Any update on this?

**Comment by kuhe** [comment]
hi @markhker,

This error indicates the AbortController implementation that was provided to the request is not as expected. 

Is your electron environment overriding the global `fetch` or `AbortController` implementations? Are you using the `@aws-sdk/abort-controller` implementation or a global one? A configuration change may be able to fix this issue for you.

Otherwise, please provide a minimal reproduction repository, because this issue is not present in a default node.js or browser test environment.
