### ISSUE TITLE
waitFor for CloudFormation client

### ISSUE THREAD

**Issue by arantespp** [aws/aws-sdk-js-v3#2473]
### Is your feature request related to a problem? Please describe.

On CloudFormation SDK v2, we have the `waitFor` method, which is useful when we need to wait for some operation like deleting stack before performing other tasks. I didn't find a way to do the same using v3.

### Describe the solution you'd like

Like S3 v3, which has `waitForBucketExists`, it'd handy if we also have the `waitFor` for CloudFormation:

- stackExists
- stackCreateComplete
- stackDeleteComplete
- stackUpdateComplete
- stackImportComplete
- stackRollbackComplete
- changeSetCreateComplete
- typeRegistrationComplete

**Comment by shadow-light** [comment]
Also missing lots of waiters for IAM. There's only one at the moment...

**Comment by shadow-light** [comment]
Here's a compact implementation that should be functionality identical to the builtin ones. This one is for IAM user creation, but it is easy to adapt to any other feature just by changing the command and typings:

```typescript

import {IAMClient} from '@aws-sdk/client-iam'
import {GetUserCommand, GetUserCommandInput} from '@aws-sdk/client-iam'
import {WaiterConfiguration, WaiterResult, WaiterState, checkExceptions, createWaiter,
    } from "@aws-sdk/util-waiter"


export async function waitUntilUserExists(params:WaiterConfiguration<IAMClient>,
        input:GetUserCommandInput):Promise<WaiterResult>{
    return checkExceptions(await createWaiter(
            {minDelay: 1, maxDelay: 120, ...params}, input, async (client, cmd_input) => {
        try {
            return {
                state: WaiterState.SUCCESS,
                reason: await client.send(new GetUserCommand(cmd_input)),
            }
        } catch (exception){
            return {state: WaiterState.RETRY, reason: exception}
        }
    }))
}

```

Though I am confused as to why the builtin waiters seem to still retry upon 400 errors etc, unless I'm missing something. Example: https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-iam/waiters/waitForInstanceProfileExists.ts
