### ISSUE TITLE
Unable to pipe s3 getObject Body in v3 API

### ISSUE THREAD

**Issue by tbhaxor** [aws/aws-sdk-js-v3#2475]
https://github.com/aws/aws-sdk-js-v3/blob/72cc2dc89f89b6f3290bed623ebb43e5725bed0d/clients/client-s3/models/models_0.ts#L7076

It is typed here Readable but when I check the constructor name in the console.log I am getting IncomingMessage with the following properties and functions

```js
const file = await engineStore.getObject({ Key: image[req.query.source], Bucket: process.env.ENGINE_AWS_BUCKET, ResponseContentType: 'image/png' });
console.log(file.Body.constructor.name);
console.log(Object.keys(file.Body));
console.log(Object.getOwnPropertyNames(Object.getPrototypeOf(file.Body)));
```

Console Output
```
IncomingMessage
[
  '_readableState',   '_events',
  '_eventsCount',     '_maxListeners',
  'socket',           'httpVersionMajor',
  'httpVersionMinor', 'httpVersion',
  'complete',         'headers',
  'rawHeaders',       'trailers',
  'rawTrailers',      'aborted',
  'upgrade',          'url',
  'method',           'statusCode',
  'statusMessage',    'client',
  '_consuming',       '_dumped',
  'req'
]
[
  'constructor',     'connection',
  'setTimeout',      '_read',
  'destroy',         '_addHeaderLines',
  '_addHeaderLine',  '_dump',
  'logIn',           'login',
  'logOut',          'logout',
  'isAuthenticated', 'isUnauthenticated'
]
```

**Comment by ajredniwja** [comment]
Hey @tbhaxor thanks for opening this issue, I dont think I understand the question, can you please fill out the [issue template](https://github.com/aws/aws-sdk-js-v3/issues/new?assignees=&labels=bug%2C+needs-triage&template=---bug-report.md&title=).

**Comment by tbhaxor** [comment]
@ajredniwja The issue is moved to https://github.com/aws/aws-sdk-js-v3/issues/2479.

**Comment by ajredniwja** [comment]
Thanks, I'll have a look soon.
