### ISSUE TITLE
Unable to assume role appropriately with @aws-sdk/client-ecr 3.18.0 

### ISSUE THREAD

**Issue by jdziat** [aws/aws-sdk-js-v3#2477]
## Describe the bug
When upgrading to the latest version of @aws-sdk/client-ecr it no longer correctly authenticates. 

policy being used:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "ecr:*",
        "sts:*"
      ],
      "Resource":["*"]
    }
  ]
}
```
## Your environment
EKS - v1.19

#### SDK version number
`@aws-sdk/client-ecr@3.18.0`

#### Is the issue in the browser/Node.js/ReactNative?
Browser/Node.js/ReactNative

#### Details of the browser/Node.js/ReactNative version
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`

## Steps to reproduce
- Use terraform-aws-modules/iam/aws//modules/iam-assumable-role-with-oidc with the policy above
- Attempt to use the client-ecr package.

#### Observed behavior
Throws an error: 
```Unable to get image: nginx. AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity``

#### Expected behavior
Should be able to use the mounted service account

## Additional context
It is working correctly on version 3.6.0

**Comment by ajredniwja** [comment]
Hey @jdziat thanks for opening this issue, I couldn't find anything in the [changelog](terraform-aws-modules/iam/aws//modules/iam-assumable-role-with-oidc) that might possibly have an effect on this. I suspect if this is an issue with the SDK. I havent reproduced it yet, are there like steps which I can use? and also if you could provide the complete stack trace.

**Comment by carlosescura** [comment]
Hi @jdziat  and @ajredniwja 

We are experiencing the same issue. We had to stick to `3.17.0` to our SES and S3 clients.
Using our local development setup, everything works well, but when using `>3.17.0` and IRSA it fails.

Our way to get credentials is to rely on standard credential chain, with no modification or explicit definition of it:


```
import {
  SESClient,
} from '@aws-sdk/client-ses';

class AwsSESService {
  client: SESClient;
  senderEmail: string;

  constructor() {
    this.client = new SESClient({
      region: 'us-east-1',
    });
    this.senderEmail = 'abcd@abcd.com';
  }

  public async sendTemplateEmail(recipientEmail: string, templateName: string, templateData: string): Promise<string> {
    try {
      const input: SendTemplatedEmailCommandInput = {
        ConfigurationSetName: 'log_templated_email',
        Destination: {
          ToAddresses: [recipientEmail],
        },
        ReplyToAddresses: [this.senderEmail],
        Source: this.senderEmail,
        Template: templateName,
        TemplateData: templateData,
      };
      const command = new SendTemplatedEmailCommand(input);
      const response = (await this.client.send(command)) as SendTemplatedEmailResponse;
      return response.MessageId;
    } catch (error) {
     ...
    }
  }

}

export default AwsSESService;

```
