### ISSUE TITLE
Can't get the stream of object.Body from getObject method

### ISSUE THREAD

**Issue by tbhaxor** [aws/aws-sdk-js-v3#2479]
## Describe the bug

I am an old aws-sdk version user, thinking to switch to v3 from v2. In v2, I used to get the object stream by

```js
const file = s3.getObject({ Bucket: "my-bucket", Key: "storage/image.png" }).createReadStream()

// pipe file to express response
file.pipe(res)
```

#### SDK version number
`@aws-sdk/client-s3@3.18.0`

#### Is the issue in the browser/Node.js/ReactNative?
Nodejs

#### Details of the browser/Node.js/ReactNative version

```
$ node -v
v14.16.0
```

## Steps to reproduce

1. Setup the s3 client
2. Try to get the object and its stream as shown above

#### Observed behavior

First of all, you will not get `.createReadStream()`, you have to _await_ the response. When I check `file.Body`, in this case, I get `IncomingMessage`. It is confirmed by executing `console.log(file.Body.constructor.name)`

In the IntelliSense, it shows `pipeTo` method but actually it doesn't exists, confirmed by executing `console.log(Object.getOwnPropertyNames(Object.getPrototypeOf(file))`

#### Expected behavior

Get the stream of s3 object somehow

**Comment by neverendingqs** [comment]
I'm not sure I'm following, but wanted to point you to https://github.com/aws/aws-sdk-js-v3/issues/1096#issuecomment-620900466 in case you haven't seen it already.

Would something like this work for you?

```js
const response = await s3.getObject(params);
response.Body.pipe(...)
```

**Comment by tbhaxor** [comment]
> Would something like this work for you?

Already checked `pipe` doesn't exists in body fields `console.log(typeof response.Body.pipe) // undefined`

**Comment by samchungy** [comment]
You should switch the to v3 syntax. using S3Client.send() syntax.

**Comment by tbhaxor** [comment]
> You should switch to v3 syntax. using S3Client.send() syntax.

Using [GetObjectCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/classes/getobjectcommand.html) commands, already done that. Same properties and methods in `response.Body`

**Comment by neverendingqs** [comment]
> > Would something like this work for you?
> 
> Already checked `pipe` doesn't exists in body fields `console.log(typeof response.Body.pipe) // undefined`

Can you post a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), or something as close to it as possible?

This worked for me:

```js

const fs = require('fs');
const { S3 } = require('@aws-sdk/client-s3');

const s3 = new S3();

const response = await s3.getObject({
  Bucket: 'my-bucket',
  Key: 'my-key'
});

console.log(typeof response.Body.pipe)
// function

response.Body.pipe(fs.createWriteStream('./output.log'))
// response body written to 'output.log'
```

**Comment by tbhaxor** [comment]
I just checked it is working now.
