### ISSUE TITLE
unable to send voice message using PinpointSMSVoiceClient

### ISSUE THREAD

**Issue by Hari1402** [aws/aws-sdk-js-v3#2494]
## Describe the bug
when i tried sending the voice message using "SendVoiceMessageCommand" with "PinpointSMSVoiceClient" . i'm getting error "Cannot read property 'byteLength' of undefined".

## Your environment
local 

#### SDK version number
    "@aws-sdk/client-pinpoint-sms-voice": "^3.18.0",

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v14.15.4

## Steps to reproduce
const { PinpointSMSVoiceClient, SendVoiceMessageCommand } = require("@aws-sdk/client-pinpoint-sms-voice");
    let params = {
        Content: {
          SSMLMessage: {
            LanguageCode: "en-US",
            Text: `"<speak> <break time='1s'/> <prosody rate='slow'> Hi, this is a call from abc Thank You</prosody> </speak>"`,
            VoiceId: "Joey"
          }
        },
        DestinationPhoneNumber: '1234567890'
        OriginationPhoneNumber: '1234567890'
      }
    const AWSVoiceMessage = new PinpointSMSVoiceClient({ region: "us-east-1"});
    const message = new SendVoiceMessageCommand(params);        // look params attached above
     await AWSVoiceMessage.send(message);      // i get the error

i set the env variable  like this 
AWS_ACCESS_KEY_ID=access_key
AWS_SECRET_ACCESS_KEY=secreat_key
AWS_SESSION_TOKEN=sesssion_token

#### Observed behavior
getting error

#### Expected behavior
send the voice message

**Comment by ajredniwja** [comment]
@Hari1402 thanks for opening the issue, can you please share what error you are getting? 

You can follow the steps [here](https://docs.aws.amazon.com/code-samples/latest/catalog/code-catalog-javascriptv3-example_code-pinpoint.html) to check an example, of-course you'd need to use the `PinpointSMSVoiceClient`.

**Comment by Hari1402** [comment]
@ajredniwja this is the error message
"Cannot read property 'byteLength' of undefined\n at Object.fromArrayBuffer "

**Comment by ajredniwja** [comment]
I was not able to reproduce this, can you try the code like this: 

```javascript
(async ()=> {
    const { PinpointSMSVoiceClient, SendVoiceMessageCommand } = require("@aws-sdk/client-pinpoint-sms-voice");

    var params = {
        Content: {
          SSMLMessage: {
            LanguageCode: 'en-US',
            Text: "<speak> <break time='1s'/> <prosody rate='slow'> Hi, this is working</prosody> </speak>",
            VoiceId: 'Joey'
          }
        },
        DestinationPhoneNumber: '+11200004567',
        OriginationPhoneNumber: '+170457177569'
      };

    try {
        const AWSVoiceMessage = new PinpointSMSVoiceClient({ region: "us-west-2"});
        const message = new SendVoiceMessageCommand(params); 
        const response = await AWSVoiceMessage.send(message);

        console.log(response);
    } catch (error) {
        console.log(error)
    }

})();
```

**Comment by Hari1402** [comment]
@ajredniwja thanks for your time and support. It was a silly mistake from my side. i'm able to send voice call
