### ISSUE TITLE
POOL_IDS

### ISSUE THREAD

**Issue by nikhilatshaw** [aws/aws-sdk-js-v3#2495]
How can we get pool_ids/contents in aws-export.json file  as response after app creation similar to amplify-cli under aws-sdk/client-amplify

**Comment by ajredniwja** [comment]
Hey @nikhilatshaw thanks for opening the issue, but I dont really understand the question can you follow the [issue template](https://github.com/aws/aws-sdk-js-v3/issues/new?assignees=&labels=bug%2C+needs-triage&template=---bug-report.md&title=)?
