### ISSUE TITLE
[@aws-sdk/client-resource-groups-tagging-api] GetTagKeysCommand is missing the "MaxItems" field

### ISSUE THREAD

**Issue by Obirah** [aws/aws-sdk-js-v3#2496]
## Describe the bug
Looking at the documentation of the ["get-tag-keys" operation in the AWS CLI docs](https://docs.aws.amazon.com/cli/latest/reference/resourcegroupstaggingapi/get-tag-keys.html) one can see the API allows to pass the maximum amount of items returned in the response.

Contrary to that, the `@aws-sdk/client-resource-groups-tagging-api` package's client does not allow to specify the amount of returned items in the `GetTagKeysCommand`. Instead, each API call only returns 48 items, which leads to an unnecessary amount of API calls when querying all tag keys of a large AWS account.

#### SDK version number
`@aws-sdk/client-resource-groups-tagging-api@3.18.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Node v15.7.0

## Steps to reproduce
Instantiate `GetTagKeysCommand` -> the constructor's input only allows to pass a PaginationToken but no MaxItems count.

#### Observed behavior
It is not possible to specify the maximum amount of returned items.

#### Expected behavior
It is possible to specify the maximum amount of returned items.

**Comment by ajredniwja** [comment]
Hey @Obirah thanks for opening this issue, I believe the `maxItems` param is something which is specifically implemented in CLI and boto3 as well. Checking the other SDKs like Java, DotNet, ruby, they havent implemented this as of now. 

Also checked the [API reference](https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/API_GetTagKeys.html) for the request syntax.

This is not necessarily a bug but a feature request, I'll open a ticket with the `ResourceGroupsTaggingAPI` team, as they'll need to make the changes.

**Comment by Obirah** [comment]
Still an issue
