### ISSUE TITLE
TimestreamQuery doesn't support paramaterized inputs

### ISSUE THREAD

**Issue by alaycock** [aws/aws-sdk-js-v3#2502]
### Is your feature request related to a problem? Please describe.
There doesn't appear to be any solution for building a Timestream query with parameterized inputs, in order to prevent SQL injections. I also can't find any documentation regarding how Timestream addresses this concern. A query is just a simple string that is assumed to be safe, according to these documents.

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/TimestreamQuery.html#query-property

### Describe the solution you'd like
I feel like the following should be considered:
- Introducing a query builder, or adding the functionality to handle parameterized inputs into the `query` method.
- If there's another solution in place such that the above solution is not necessary, documenting said solution.
- If there is no solution in place, a recommendation to a query builder that would work for building Timestream queries.

### Describe alternatives you've considered
I've looked for alternate NPM packagers, but none seem to exist.

**Comment by davidmweber2** [comment]
This is a significant oversight by AWS. It seems as if the V2 API has this. Any progress on getting this fixed?
