### ISSUE TITLE
SSM GetParameterCommand hangs and times out when called from Lambda function

### ISSUE THREAD

**Issue by nikmartin** [aws/aws-sdk-js-v3#2510]
## Describe the bug
Trying to fetch a parameter from ssm in a Lambda function results in the Lambda function timing out.

#### SDK version number
` "@aws-sdk/client-ssm": "^3.18.0"`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Node 14.x Lambda runtime

## Steps to reproduce

1. Create lamba function, paste in below
2. `npm install @aws-sdk/client-ssm`
3. zip directory with index.js and node_modules
4. upload zip to Lambda function created in step 1
5. Make sure Lambda runtime execution role has ssm:GetParameter* permissions
6. Create SSM standard text parameter named 'testparam' with value 'Hello, world!'
7. Set lambda timeout to 15 seconds
8. use the HelloWorld test template to trigger function
9. wait for function to timeout.

```js
const { SSMClient, GetParameterCommand } = require('@aws-sdk/client-ssm');
const ssm = new SSMClient({ region: 'us-east-2' });
exports.handler = async (event, context, callback) => {
    try {
        const data = await ssm.send(new GetParameterCommand({ Name: 'testparam', WithDecryption: false }))
        console.log('data: ', data);
    } catch (err) {
        console.log('err: ', err, err.stack);
    }finally{
        console.log('hey now');
    }
};
```

#### Observed behavior
The function times out.

#### Expected behavior
The SSM parameter is printed to log output.

#### Screenshots
```
Logs:
START RequestId: 14bb97ab-e7ef-4da8-9d2a-bde101f6e6c7 Version: $LATEST
END RequestId: 14bb97ab-e7ef-4da8-9d2a-bde101f6e6c7
REPORT RequestId: 14bb97ab-e7ef-4da8-9d2a-bde101f6e6c7	Duration: 15015.71 ms	Billed Duration: 15000 ms	Memory Size: 128 MB	Max Memory Used: 97 MB	Init Duration: 565.58 ms	
2021-06-22T19:57:58.331Z 14bb97ab-e7ef-4da8-9d2a-bde101f6e6c7 Task timed out after 15.02 seconds

Payload:
{"errorMessage":"2021-06-22T19:57:58.331Z 14bb97ab-e7ef-4da8-9d2a-bde101f6e6c7 Task timed out after 15.02 seconds"}
```

**Comment by samchungy** [comment]
Have you tried 3.19?

**Comment by nikmartin** [comment]
@samchungy Should I? 3.18 was the latest when I opened this ticket.

**Comment by samchungy** [comment]
Give it a shot, I did submit a PR https://github.com/aws/aws-sdk-js-v3/pull/2452 which may have fixed it.

**Comment by nikmartin** [comment]
Same results using `"@aws-sdk/client-ssm": "^3.20.0"`

**Comment by samchungy** [comment]
![image](https://user-images.githubusercontent.com/18017094/125004740-87eee600-e09d-11eb-83ca-ec49ee4908c0.png)

Copy pasted your code and gave it a shot replicating your issue. Is your lambda deployed in a VPC or anything or is it just a simple lambda@edge?

**Comment by nikmartin** [comment]
Yes, it _is_ in a VPC because it also talks to DocumentDB.

**Comment by yenfryherrerafeliz** [comment]
Hi @nikmartin, thanks for opening this issue. Could you please let me know if this is a persistent issue for you?, if so, can you verify if is there any restriction, maybe from the vpc where the function lives in, that prevents the function to talk to the System Manager service. I just did a test from my account, from a lambda function and I got not issues.

Steps to reproduce:
- I created a new lambda function using Node 18.x, which also includes the AWS SDK for JavaScript V3.
- Granted ssm:getParameter permisions to the role assigned to the function.
- I set a 15 seconds timeout to the lambda function.
- I used the following code:
```js
import { SSMClient, GetParameterCommand } from '@aws-sdk/client-ssm';

export const handler = async(event) => {
    const ssm = new SSMClient({ region: 'us-east-2' });
    try {
        const data = await ssm.send(new GetParameterCommand({ Name: 'testparam', WithDecryption: false }))
        
        return invokeResponse(200, data);
    } catch (err) {
        return invokeResponse(500, {
            err: err,
            stack: err.stack,
        });
    } finally{
        console.log('finalized');
    }
};

const invokeResponse = (statusCode, body) => {
    const response = {
        statusCode: statusCode,
        body: JSON.stringify(body),
    };
    
    return response;
} 
```

Thanks!
