### ISSUE TITLE
Use newer blob reading method

### ISSUE THREAD

**Issue by jimmywarting** [aws/aws-sdk-js-v3#2512]
https://github.com/aws/aws-sdk-js-v3/blob/5d9bc5f32980f43a9b581b1f5101cdc7f2258173/packages/chunked-blob-reader/src/index.ts#L7

Blob is coming to NodeJS
But it is probably not going to implement a FileReader

use `blob.arrayBuffer()`, `.stream()` and `.text()` when possible
use fileReader as a fallback (or polyfill the methods on blob)
(or drop support for IE entirely)

**Comment by ajredniwja** [comment]
Thanks for opening this request, I'll let the team review it and prioritize accordingly when needed.
