### ISSUE TITLE
Simple S3 requests timing out in Lambda environment?

### ISSUE THREAD

**Issue by taschmidt** [aws/aws-sdk-js-v3#2513]
## Describe the bug
Making a simple S3 request seems to cause my lambda to time out when running remotely. Here's the code...

```TypeScript
export async function handler(input: TaskInputWithToken<SendToMediaConvertState>): Promise<TaskInputWithToken<SendToMediaConvertState>> {
    const log = new LambdaLog();
    
    log.info('Received input', { input });

    await new S3Client({}).send(new GetObjectCommand({ Bucket: 'bucket', Key: 'key' }));
}
```

I intentionally pass bogus values for Bucket and Key. Locally (I'm using the serverless framework, so "sls invoke local"), this immediately returns an AccessDenied error but when running in AWS, this request seems to hang until my lambda times out.

#### SDK version number
`@aws-sdk/client-s3@3.17.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
AWS Lambda - Node.js 14.x

## Steps to reproduce
Please share code or minimal repo, and steps to reproduce the behavior.

#### Observed behavior
Call takes an inordinately long time to return.

#### Expected behavior
Call should error out and return near instantaneously.

#### Screenshots
After lengthening my lambda timeout, I can get it to return... eventually. Here are logs of the above code:
![image](https://user-images.githubusercontent.com/228736/123093735-a2646680-d3f1-11eb-9794-21709d4bde8e.png)

You can see it eventually returns but why would it take over 13.5 seconds?!?

**Comment by samchungy** [comment]
Can you try 3.19? I think I fixed it with https://github.com/aws/aws-sdk-js-v3/pull/2452

**Comment by taschmidt** [comment]
Sadly this does not appear to have fixed the issue. I just upgraded to 3.19 and tried 3 runs, all of which took 10 seconds to return...

![image](https://user-images.githubusercontent.com/228736/123424839-ff455580-d586-11eb-9026-b43778b1e813.png)

**Comment by samchungy** [comment]
Huh I couldn't replicate it, tried with a few variations of bucket names, different errors and no hang. Node often keeps your process alive if there is a handle left open. Is something else leaving a handle open? What happens when you only import the s3 module and not the logger?

```
const { GetObjectCommand, S3Client } = require("@aws-sdk/client-s3");

exports.handler = async () => {
  await new S3Client({}).send(
    new GetObjectCommand({
      Bucket: "kickoff-dev-serverlessdeploymentbucket-fzcuxfqyzlsl",
      Key: "key",
    })
  );
};
```



![image](https://user-images.githubusercontent.com/18017094/123442447-3a439980-d618-11eb-9192-6592f2b645ae.png)

**Comment by taschmidt** [comment]
Not sure what changed from when I tested a couple days ago but it seems to be better now. It's down to about a second now?

![image](https://user-images.githubusercontent.com/228736/123547165-4a956a80-d725-11eb-8039-0b1ebb51cc37.png)

**Comment by ajredniwja** [comment]
@taschmidt thanks for bringing this up, I was not able to quite reproduce the behavior, can you share your use case and the code that you are using?

**Comment by taschmidt** [comment]
@ajredniwja I just deployed this little repo and it appears as though the GetObject command took almost 2 seconds to return.

https://github.com/taschmidt/aws-timeout-test

![image](https://user-images.githubusercontent.com/228736/125293919-7b5ecd80-e2e9-11eb-92cc-26893b68a2c9.png)
