### ISSUE TITLE
SNS Send is Sometimes Very Slow/Hangs

### ISSUE THREAD

**Issue by trademark18** [aws/aws-sdk-js-v3#2518]
## Describe the bug
Occasionally publishing an SNS message using client-sns takes much longer than normal.

## Your environment
Lambda Node.JS 14.x

#### SDK version number
`@aws-sdk/client-sns@3.18.0`

I saw that 3.19.0 just came out, but I haven't had it running long enough to know if the issue has been fixed by that release.  If someone knows of something in 3.19.0 that may have bearing on this, let me know!

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Lambda Node.JS 14.x

## Steps to reproduce
I haven't found a reliable way to reproduce.

#### Observed behavior
My lambda is invoked 190k times per day, and I get maybe 5-10 of these timeouts due to slow SNS publishes.

#### Expected behavior
My Lambda typically executes in about 90ms, but occasionally it times out at 3s waiting for `.send()` to complete.

#### Code
This is the code that seems to be hanging/slow.
```javascript
const result = await snsClient.send(new PublishCommand({
	Message: JSON.stringify(payload),
	TopicArn: process.env['LiveUpdateSnsTopicArn']
}));
```

## Additional context
I know this is a very infrequent issue, but whenever it happens in my application it causes data problems downstream.  I'd love to see if someone knows what might be the trouble, or if someone has had a similar issue.

I know these kinds of issues are a pain to figure out since it's intermittent and infrequent, so let me know if I can provide additional details or information to help.

**Comment by ajredniwja** [comment]
Hi @trademark18 thanks for bringing this up, I have seen this V2 of the SDK when using Lambda but it is very hard to reproduce, what I can do is reach out to Lambda/SNS team to see what happened as they have more visibility, they will need more info which I can ask about once I have a word from them. 

Also there is a limit on default lambda executions quota which might cause this problem see: https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html

It can be the case that you hit the limit and send more requests at that point SNS will wait and retry (which will be the delay in this case). 

I'd be glad to take this request to Lambda team as I said but what I mentioned might be the case.

**Comment by trademark18** [comment]
Hi @ajredniwja thanks for taking this on.  For what it's worth, I can rule out issues with lambda quotas since I'm not hitting those when these timeouts are happening.  I'm not aware of any SNS quotas or rate limits, but I can tell you that the issue seems to happen occasionally whether the system is under a heavy load or a normal load.
