### ISSUE TITLE
Types 3.19 not released

### ISSUE THREAD

**Issue by FizzBuzz791** [aws/aws-sdk-js-v3#2532]
## Describe the bug
Everything was just released at version 3.19 except types. We upgraded our packages to 3.19 and now the build step (tsc) is complaining about properties not existing;
`Property 'send' does not exist on type 'DynamoDBDocumentClient'.`

#### SDK version number
`@aws-sdk/lib-dynamodb@3.19.0`
`@aws-sdk/types@3.18.0`

## Steps to reproduce
Install the latest lib-dynamodb and types packages, try to send a command from the `DynamoDBDocumentClient` and note that tsc fails.

#### Observed behavior
tsc reports `Property 'send' does not exist on type 'DynamoDBDocumentClient'.`

#### Expected behavior
tsc compiles project.

**Comment by trivikr** [comment]
Related: https://github.com/aws/aws-sdk-js-v3/issues/2474#issuecomment-868932817

**Comment by trivikr** [comment]
The issue was with internal release script.
Updates about the fix: https://github.com/aws/aws-sdk-js-v3/issues/2474#issuecomment-871798569
