### ISSUE TITLE
Unable to use client-transcribe-streaming with AWS_PROFILE ENV assumed_role Credentials

### ISSUE THREAD

**Issue by brgaulin** [aws/aws-sdk-js-v3#2533]
## Describe the bug
When doing local development, and using AWS_PROFILE env var to help select the correct credentials/assume the correct role, the transcribe API is unable to work on its own.

#### SDK version number
`@aws-sdk/client-transcribe-streaming@3.19.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
```
$ node -v
v14.17.0
```

#### Relevant ~/.aws/config
```yaml
[default]
region = us-east-1
output = json

[profile dev]
region = us-east-1
role_arn = arn:aws:iam::123456789:role/dev-role
source_profile=default
```

#### Relevant ~/.aws/credentials
```yaml
[default]
aws_access_key_id = ACCESS_KEY_IS_HERE
aws_secret_access_key = SECRET_KEY_IS_HERE
```

## Steps to reproduce
```typescript
const {
  TranscribeStreamingClient,
  StartStreamTranscriptionCommand,
  PartialResultsStability,
  MediaEncoding,
  LanguageCode,
} = require('@aws-sdk/client-transcribe-streaming')

const transcribeClient = new TranscribeStreamingClient({ region: 'us-east-1' })

const transcribeInput = async function* () {
  for await (const chunk of process.stdin) {
    if (chunk.length > 6000) continue
    yield { AudioEvent: { AudioChunk: chunk } }
  }
}

const transcriptionCommand = new StartStreamTranscriptionCommand({
  LanguageCode: LanguageCode.EN_US,
  MediaSampleRateHertz: 16000,
  MediaEncoding: MediaEncoding.PCM,
  AudioStream: transcribeInput(),
  EnablePartialResultsStabilization: true,
  PartialResultsStability: PartialResultsStability.MEDIUM
})

transcribeClient.send(transcriptionCommand)
  .then(() => console.log('Success!'))
  .catch((err) => console.log('Fail', err))
```

#### Observed behavior
```bash
$ node ./src/test.js
Success!

$ AWS_PROFILE=dev node ./src/test.js
Fail Error [ERR_HTTP2_ERROR]: Protocol error
    at Http2Session.onSessionInternalError (internal/http2/core.js:754:26) {
  code: 'ERR_HTTP2_ERROR',
  errno: -505,
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
```

#### Expected behavior
Both examples would succeed

## Additional context
If I add in an s3:ListBuckets command above the transcribe client, I do notice that switching profiles does switch the output of the S3 command results, so it seems the s3 client is working ok with this type of auth, but something is up with transcribe

**Comment by brgaulin** [comment]
I'm not sure if this should work out of the box, but as a workaround, I am able to specify it more explicitly, and it does work ok:

```typescript
const {
  TranscribeStreamingClient,
  StartStreamTranscriptionCommand,
  PartialResultsStability,
  MediaEncoding,
  LanguageCode,
} = require('@aws-sdk/client-transcribe-streaming')

const { fromIni } = require("@aws-sdk/credential-provider-ini");
const { getDefaultRoleAssumer } = require("@aws-sdk/client-sts")
const transcribeClient = new TranscribeStreamingClient({ region: 'us-east-1', credentials: fromIni({
  profile: 'dev',
  roleAssumer: getDefaultRoleAssumer()
 })
})
```

**Comment by vudh1** [comment]
Hi @brgaulin, please response if you still experience this in the latest version of SDK.

**Comment by brgaulin** [comment]
Hello @vudh1 . Unfortunately I am no longer with an organization that is using AWS and this would be incredibly difficult for me to test. If you think this has been resolved in a newer version, this should be safe to close. 

In the event someone else stumbles across this post, they could make a new issue and reference the details here
