### ISSUE TITLE
[dynamodb] Add pagination support for DynamoDB Document client

### ISSUE THREAD

**Issue by twitu** [aws/aws-sdk-js-v3#2546]
### Is your feature request related to a problem? Please describe.
I'm frustrated by the lack of support for pagination with the Document client. Document client has the advantage of automatically inferring DDB specific types. If this can be coupled with the pagination style query it would be very easy to interface with DDB.

### Describe the solution you'd like
Support Document Client for paginator. The current type interfaces show it is not supported.

```
export declare function paginateQuery(config: DynamoDBPaginationConfiguration, input: QueryCommandInput, ...additionalArguments: any): Paginator<QueryCommandOutput>;
export interface DynamoDBPaginationConfiguration extends PaginationConfiguration {
    client: DynamoDB | DynamoDBClient;
}
```

### Describe alternatives you've considered
I have to choose between one of two options -
* (Re)implement pagination logic
* Write the DDB types for each argument (sometimes this is very difficult for large changing records)

**Comment by beanaroo** [comment]
I believe this may be a duplicate of https://github.com/aws/aws-sdk-js-v3/issues/2159

**Comment by twitu** [comment]
Yes this looks like a duplicate. Please close this if this is feature is being tracked in a more visible issue.

**Comment by twitu** [comment]
Closing in favour of #2159
