### ISSUE TITLE
convertToNumberAttr missing in v3.20.0

### ISSUE THREAD

**Issue by paul-uz** [aws/aws-sdk-js-v3#2547]
According to https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_util_dynamodb.html#converttonumberattr the const `convertToNumberAttr` should exist, but it doesn't.

**Comment by vudh1** [comment]
hi @paul-uz, thanks for reaching out. For the team to help you better, can you follow the [template](https://github.com/aws/aws-sdk-js-v3/issues/new?template=---bug-report.md) and provide reproducible code?
