### ISSUE TITLE
DocumentClient not fully compatible with v2 (promise)

### ISSUE THREAD

**Issue by donferi** [aws/aws-sdk-js-v3#2566]
## Describe the bug
`DocumentClient` API is not matching 1:1 with v2. Does `.promise` by default, which is useful but not compatible with older / libs code.

#### SDK version number
```
"@aws-sdk/client-dynamodb": "^3.20.0"
"@aws-sdk/lib-dynamodb": "^3.20.0"
"@aws-sdk/util-dynamodb": "^3.20.0"
```

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
`v14.15.4`

## Steps to reproduce
Using any of the methods directly with the v2 compatibility layer, example gotten from https://github.com/aws/aws-sdk-js-v3/pull/2097
```js
import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocument } from "@aws-sdk/lib-dynamodb";

const client = new DynamoDBClient({});
const ddbDoc = DynamoDBDocument.from(client);
await ddbDoc.put({
  TableName,
  Item: { id: "2", content: "content from DynamoDBDocument" },
});
```

While in v2 we had to:
```js
await ddbDoc.put({
  TableName,
  Item: { id: "2", content: "content from DynamoDBDocument" },
}).promise();
```

#### Observed behavior
Breaks because `.promise` is not a method on any of the `ddbDoc` methods like v2.

#### Expected behavior
`.promise()` to exist so we that it is compatible with v2.

### Side-question
Is there any advantages of using the new `send(new PutCommand ....` vs the v2 compatibility way?

**Comment by samchungy** [comment]
You're importing the wrong one if you want the v2 compatible style. Import `DynamoDBDocument` instead. The send style is the recommended approach as it loads less code. Combine that with tree shaking and your deployments will be alot smaller.

**Comment by ajredniwja** [comment]
Hey @donferi thanks for bringing this up, I am not sure if I understand your question correctly because all the API calls in V3 returns a promise which means you dont have to use `.promise`.  You want to use `.promise` to make sure it is compatible with v2?
