### ISSUE TITLE
API Gateway v3 compatiblity

### ISSUE THREAD

**Issue by Kikobeats** [aws/aws-sdk-js-v3#2567]
Hello,

I switched from `aws-sdk@2` to `@aws-sdk/client-api-gateway@3` since docs are showing a simple way to do that keeping the same API:

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-api-gateway/index.html#v2-compatible-style

However, in the practice, they are not working in the same way, or at least they are not implemented in the same way, since I experimented with 403 errors trying to interact with API Gateway API keys creation endpoint:

```
ERROR AccessDeniedException: User: arn:aws:sts::756511632239:assumed-role/microlink-int-function/microlink-int is not authorized to perform: apigateway:POST on resource: arn:aws:apigateway:us-east-1::/apikeys
```

Looks like a permission problem that probably will be resolved just by attaching the right permissions to the AWS credentials, but my point is, I'm not sure if this is an expected thing since I didn't need to do in the past at v2.

(BTW, how to resolve the permissions issue? 😄)

**Comment by ajredniwja** [comment]
Hey @Kikobeats, can you please share your use case and the code? I can try to find out whats going wrong

**Comment by Kikobeats** [comment]
Sure thing 🙂

From an AWS Lambda function, I'm calling API Gateway v1 endpoint for creating a new API key:

```
const AWS = require('@aws-sdk/client-api-gateway')


const {
    createdDate: createdAt,
    lastUpdatedDate: updatedAt,
    id,
    value: key
  } = await apiGateway.createApiKey({ name, enabled: true })
```

Doing that using v3 throw the error reported; do exactly the same, no code changes (just adding `.promise()` at the end) works like a charm.
