### ISSUE TITLE
Switch to undici instead of native Node HTTP

### ISSUE THREAD

**Issue by artur-ma** [aws/aws-sdk-js-v3#2569]
### Is your feature request related to a problem? Please describe.
No, but this should give a boost in performance, and solve some issue with native node HTTP client (see https://github.com/nodejs/node/issues/38533)

### Describe the solution you'd like
Switch to new official Node HTTP client, https://github.com/nodejs/undici instead of native 'http'

**Comment by trivikr** [comment]
We now provide a request handler in [@aws-sdk/undici-http-handler](https://www.npmjs.com/package/@aws-sdk/undici-http-handler) which uses modern, high performance Node.js undici client.

You can import it in your application, and pass it as `requestHandler` in your client configuration.

Example:
```js
import { S3 } from "@aws-sdk/client-s3";
import { UndiciHttpHandler } from "@aws-sdk/undici-http-handler";

const client = new S3({
  requestHandler: new UndiciHttpHandler(),
});

client.listBuckets().then(console.log);
```

If you have any feedback, please create a new issue or upvote existing issues at https://github.com/aws/aws-sdk-js-v3/issues
