### ISSUE TITLE
Metadata content-type will not programatically change from binary/octet-stream 

### ISSUE THREAD

**Issue by adherb** [aws/aws-sdk-js-v3#2570]
Hello,

I am unable to get the Metadata content-type to change to the relevant content type, it always remains as binary/octet-stream which does not allow me to view the content in the browser.

During the upload I am setting the ContentType, but this is not working.

Any help would be much appreciated.

Here is my code from my Next.js Api Route:
```js
import aws from "aws-sdk";
import { nanoid } from "nanoid";

export default async function handler(req, res) {
aws.config.update({
accessKeyId: process.env.ACCESS_KEY_ID,
secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
region: process.env.AWS_REGION,
signatureVersion: "v4",
});

const s3 = new aws.S3();
const post = await s3.createPresignedPost({
Bucket: process.env.BUCKET_NAME,
Metadata: { "x-amz-meta-content-type": req.query.contentType },
Fields: {
key: ${nanoid()}.${req.query.file.split(".").pop()},
ContentType: ${req.query.contentType},
ACL: "public-read",
},
Expires: 60, // seconds
Conditions: [
["content-length-range", 0, 1048576], // up to 1 MB
],
});
console.log(post);
res.status(200).json(post);
}
```

**Comment by ajredniwja** [comment]
Hey @adherb are you using V3 of the SDK?
For this particular example which seems to be in V2, I can try to work with it and come up with an example. 
If I am understanding it correctly, your requirement is to just change the the `content-type`? My question is you wanna do it with V2 or V3 of the SDK?

**Comment by adherb** [comment]
Hi @ajredniwja thanks for your reply. Yes, I though I was using the latest version. I'm happy to use whatever version you recommend.
Yes, I want to change the content type in AWS S3 so it is no longer the default of binary/octet-stream.
I'm happy to use which ever version is easiest to achieve the outcome.

**Comment by adherb** [comment]
From my understanding, the issue is with my front end code (pasted below). I can across this article, explaining how to set the correct headers: https://product.voxmedia.com/2019/2/26/18216980/dynamically-set-content-type-headers-on-a-fetch-request, but I still can't see to get it to work. I am appending the ...fields which include the content-type to formData, but I am still unable to get it to work.

const handleUpload1 = async (e) => {
    let file = e.target.files[0];
    const filename = encodeURIComponent(file.name);
    const contentType = encodeURIComponent(file.type);
    const res = await fetch(
      `/api/upload-url?file=${filename}&contentType=${contentType}`,
      {
        headers: {
          "content-type": contentType,
        },
      }
    );
    const { url, fields } = await res.json();
    const formData = new FormData();

    Object.entries({ ...fields, file }).forEach(([key, value]) => {
      formData.append(key, value);
    });
    formData.append("Content-Type", file.type);
    try {
      setLoading1(true);
      const upload = await fetch(url, {
        method: "POST",
        body: formData,
      });
      if (!upload.ok) {
        throw new Error("Upload didn't work!");
      }
      const location = `${"https://strong-curves-transformations.s3.amazonaws.com/"}${
        fields.key
      }`;
      const key = fields.key;
      setImage1(location);
      setImageKey1(key);
      // document.getElementById("upload1").value = "";
      setImagePreview1(window.URL.createObjectURL(file));
      setImageName1(file.name);
      setButtonText1("Image Uploaded");
      setLoading1(false);
    } catch (err) {
      console.log(err);
      setButtonText1("Upload Image");
      setLoading1(false);
    }
  };
