### ISSUE TITLE
Cognito login functionality

### ISSUE THREAD

**Issue by Meemaw** [aws/aws-sdk-js-v3#258]
Hey there. I'm skimming over sdk-js-v3 and could not find the Login/Register/... functionality for Cognito user pools.

Currently, I can do those with the `@aws-amplify/auth` package. Did I miss something, or are functions missing?

**Comment by tommedema** [comment]
Did you ever find an answer to this?

**Comment by jadbox** [comment]
@Meemaw You beat me to creating this issue. For some of my projects, I have to pull in Amplify when I only need the basic cognito sdk.

**Comment by AllanFly120** [comment]
Hi @jadbox @Meemaw @tommedema 

You need this package: [credential-provider-cognito-identity](https://github.com/aws/aws-sdk-js-v3/tree/master/packages/credential-provider-cognito-identity)([npm link](https://www.npmjs.com/package/@aws-sdk/credential-provider-cognito-identity/v/1.0.0-alpha.20)). 

You can supply the provider to client like this:
```typescript
import { S3Client } from "@aws-sdk/client-s3";
import { CognitoIdentityClient } from "@aws-sdk/client-cognito-identity";
import { fromCognitoIdentityPool } from "@aws-sdk/credential-provider-cognito-identity";
const client = new S3Client({
  credentials: fromCognitoIdentityPool({
    client: new CognitoIdentityClient({})// Or specify the region and other config you need
    identityPoolId: this.cognitoIdentityPoolId
  })
});
```
