### ISSUE TITLE
GetBucketAclCommand not giving Owner -> DisplayName in output but mentioned in document like you will be getting in response

### ISSUE THREAD

**Issue by PravinP252021** [aws/aws-sdk-js-v3#2586]
## Describe the bug
I migrated aws-sdk from v2 to v3 and for GetBucketAclCommand / ListBucketsComand i am not getting Owner->DisplayName, Email,URI in the response.

Below is the link where the mentioned above fields will be come.
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/interfaces/getbucketaclcommandoutput.html

## Your environment
Node - 14.17.1

#### SDK version number
"@aws-sdk/client-s3": "^3.17.0"

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Node - 14.17.1

## Steps to reproduce
you can execute above command will get output with mentioned field as key and value as undefined

**Comment by ajredniwja** [comment]
Hi @PravinP252021, checkin at a response of ListBucketsCommand from both the SDKs (listBuckets for v2), I get similar results with which consist of `buckets` object which has `creationDate` and `name` of the bucket and `Owner` object which has `DisplayName` and `Id` of the owner. 

Using the latest version of the SDK.

**Comment by ajredniwja** [comment]
Closing this issue now, please reach out if you see the issue with the latest version of the SDK.

**Comment by PravinP252021** [comment]
Thanks @ajredniwja for looking into issue.

As per your suggestion i updated node package to "@aws-sdk/client-s3": "^3.42.0" which is latest from  "@aws-sdk/client-s3": "^3.17.0"

still getting same issue

Output for  - ListBucketsCommand

{
  "$metadata": {
    "httpStatusCode": 200,
    "extendedRequestId": "jUyVZ+14TPRkOVi/dqHm2XrzBqUNd/XrDIvmndhuyQ9mm8wWaVfB0NZGEqZU2Q3ovJosd9+Qg8k=",
    "attempts": 1,
    "totalRetryDelay": 0
  },
  "Buckets": [
    {
      "Name": "aws-athena-query-results-13245608715184-ap-south-1",
      "CreationDate": "2020-10-16T14:09:40.000Z"
    }
  ],
  "Owner": {
    "ID": "babde0b1c31494f3b4b4bbf10628bc219a13c39f69266e87e41ad817262e5895"
  }
}

Output for - GetBucketAclCommand

{
  "$metadata": {
    "httpStatusCode": 200,
    "extendedRequestId": "xdyTX5fecpx3QRMYRDdzYXacf3qTAafzj2UIJ1CFxWfByAE0fqEbu14dY4y62pRBaNzjQdTtLoA=",
    "attempts": 1,
    "totalRetryDelay": 0
  },
  "Grants": [
    {
      "Grantee": {
        "ID": "babde0b1c31494f3b4b4bbf10628bc219a13c39f245666e87e41ad817262e5482",
        "Type": "CanonicalUser"
      },
      "Permission": "FULL_CONTROL"
    }
  ],
  "Owner": {
    "ID": "babde0b1c31494f3b4b4bbf10628bc219a13c39f69289997e41ad817262e5482"
  }
}
