### ISSUE TITLE
Upload() should use PutObject API for uploading smaller objects

### ISSUE THREAD

**Issue by AllanZhengYP** [aws/aws-sdk-js-v3#2593]
### Is your feature request related to a problem? Please describe.
As pointed out in https://github.com/aws/aws-sdk-js-v3/issues/2581, the `upload()` in `@aws-sdk/lib-storage` always uses S3's multipart upload API. Users may use it for all kinds of usecases. However, the multipart upload API makes excessive amount of API calls compared to S3 `PutObject` API, especially when users only upload smaller objects.

### Describe the solution you'd like
`upload()` should use only `PutObject` for object's size is detectable and smaller than given threshold.

### Describe alternatives you've considered
Document the difference of `upload()` and `s3.putObject()` better -- this is not ideal experience.

**Comment by Linkgoron** [comment]
Thanks for opening this feature request! I just want to point out that that the above is already implemented in v2 for `s3.upload`, but wasn't ported to the v3 implementation.

**Comment by Linkgoron** [comment]
Hi,

I've started working on this. I've got a working PR locally, however I still need to add some more tests for some edge-cases to make sure that everything is working correctly, and once I sort them out I'll open a PR - if there are no objections.
