### ISSUE TITLE
suggestion: http2 support for node-http-handler

### ISSUE THREAD

**Issue by ghost** [aws/aws-sdk-js-v3#260]
This would bring all the benefits of http2. I don't know which AWS services currently support http2 but I hope that every endpoint would support http2 someday in the future.

**Comment by AllanFly120** [comment]
Hey @Ghostium 

We designed the http handler as plugable, this way we can support other http handler than http or http2. We have the plan to support Http2 in the future.

**Comment by AllanFly120** [comment]
Close this issue because the H2 is available `node-http-handler` package: https://github.com/aws/aws-sdk-js-v3/blob/cbdec4285e95b0bc01e0698c976c99e6156ad357/packages/node-http-handler/src/index.ts#L2

Currently Transcribe Streaming client uses H2 in Nodejs by default.
