### ISSUE TITLE
@aws-sdk/credential-provider-node incorrect documentation

### ISSUE THREAD

**Issue by samchungy** [aws/aws-sdk-js-v3#2603]
## Describe the issue with documentation
A clear and concise description of what the issue is.

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_credential_provider_node.html

```
const { getDefaultRoleAssumerWithWebIdentity } = require("@aws-sdk/client-sts");
const { defaultProvider } = require("@aws-sdk/credential-provider-node");
const { S3Client, GetObjectCommand } = require("@aws-sdk/client-s3");

const provider = defaultProvider({
  roleAssumerWithWebIdentity: getDefaultRoleAssumerWithWebIdentity,
});

const client = new S3Client({ credentialDefaultProvider: provider });
```

Assigning `provider` to credentialDefaultProvider like the documentation suggests results in errors.

![image](https://user-images.githubusercontent.com/18017094/126416208-efae1441-0405-4d54-8735-c13fee15e6ac.png)

## Steps to reproduce
Please share code or minimal repo if required, and steps to reproduce the behavior.

```
import { DynamoDBClient, DynamoDBClientConfig } from '@aws-sdk/client-dynamodb';
import { defaultProvider } from '@aws-sdk/credential-provider-node';
  const dynamoDBClientConfig: DynamoDBClientConfig = {
    region: config.AWS_REGION,
    credentialDefaultProvider: defaultProvider({
      roleArn: config.ROLE_ARN,
      durationSeconds: config.DURATION,
    }),
  };
  ```

#### Observed behavior
A clear and concise description of what happens.

#### Expected behavior
A clear and concise description of what you were expecting to happen.

**Comment by hmgibson23** [comment]
Did you work out how to resolve this issue? It's happening to me too.

**Comment by TroutZen** [comment]
➕ - Also seeing the same error. @samchungy - Thanks for the workaround soln.

**Comment by adworacz** [comment]
Literally just ran into this as well. The documentation is either wrong, or the code needs to be updated to reflect the contract of the documentation.

**Comment by samchungy** [comment]
Yeah good finds, I didn't look into to it too much tbh @adworacz. Just wanted to highlight that the doco was wrong. I did also state:
> Depends on what you're trying to do?

In my case I was simply looking for how to use STS roles and `fromTemporaryCredentials` is the easiest way as it allows for chaining of roles too.
