### ISSUE TITLE
How to provide custom credentials to the client

### ISSUE THREAD

**Issue by dankolesnikov** [aws/aws-sdk-js-v3#2609]
We are using Vercel and the names for AWS Keys are reserved hence can't be inferred by the app.

How do I provide custom credentials? Cant find anything in the doc!

```
import { S3 } from '@aws-sdk/client-s3';

const s3 = new S3({
  accessKeyId: AWS_SHEPHERD_ACCESS_KEY, // error
  secretAccessKey: AWS_SHEPHERD_SECRET_KEY,
  region: 'us-west-1',
});
```

**Comment by vudh1** [comment]
Hi @dankolesnikov, thank you for reaching out. Here is one of the documentation that you can use to config credentials ([link](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/setting-credentials-node.html)). If you still find this is not helpful, please follow this [template](https://github.com/aws/aws-sdk-js-v3/issues/new?assignees=&labels=documentation&template=--documentation.md&title=) so we can help you better.
