### ISSUE TITLE
Provide distribution ID in DistributionAlreadyExists error type

### ISSUE THREAD

**Issue by maslade** [aws/aws-sdk-js-v3#2618]
### Is your feature request related to a problem? Please describe.
I am trying to automate the creation and deletion of distributions as part of a pull request process. When the PR is updated, I want to get the existing distribution's URL and announce it. My CallerReference is keyed off the PR ID, so subsequent runs will (intentionally) fail to create a new distribution. In that case I'd like to know the ID of the existing distribution so that I can request additional information about it.

I do see that the ID is exposed in the `message` property of the error, such as: "The caller reference that you are using to create a distribution is associated with another distribution. Already exists: E1SXXXXXXXXXX".

### Describe the solution you'd like
I'd like the above ID to be exposed in a property on the error, so that I would be able  handle it as:

    try {
        return await cloudfront.createDistributionWithTags(args);
    }
    catch(err) {
        if (err.name === 'DistributionAlreadyExists') {
            const { Id } = err.$metadata;
            return await cloudfront.getDistribution({ Id });
        } else {
            throw err;
        }    
    }

### Describe alternatives you've considered
Using tags to find the distribution I'm after. From what I gather - this requires me to page through the list of distributions and listing tags for each item, but I'm hoping to save the extra complexity if CallerReference fits the need.

**Comment by ajredniwja** [comment]
Hey @maslade thanks for opening this, the trait you are asking for is not modeled: https://github.com/aws/aws-sdk-js-v3/blob/30831c71cd241c58eee7531d86a366ce95363865/codegen/sdk-codegen/aws-models/cloudfront.2020-05-31.json#L3956

Which is not controlled by the SDK but the specific AWS service team, I have reached out to the cloudFront team for this, will update here once I hear back from them.
