### ISSUE TITLE
Invalid type for `PutObjectCommand.Body`

### ISSUE THREAD

**Issue by oliversalzburg** [aws/aws-sdk-js-v3#2629]
## Describe the bug
When trying to put an object into an S3 bucket, I get compilation errors due to an invalid type being used for `Body`.

#### SDK version number
`@aws-sdk/client-s3@3.19.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
`v16.4.1`

## Steps to reproduce
```ts
import { PutObjectRequest } from "@aws-sdk/client-s3";

const foo: PutObjectRequest = {
    Body: "something"
}
```
[TypeScript Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgBQK4wPICMBWBTAYxgCU8BHVPAZ3gF84AzKCEOAIgAEBDAdyoFoqAEwDWAegIAbYHgB2MQQGY2AbgBQaghFk1GECAC4U6bPiKkK1eAF5EauA7gAhCEICeRtlRZ4YAC2BZAHM2NVogA)

#### Observed behavior
Providing a string for `Body` will not be accepted, as it doesn't match any of the [accepted types for that field](https://github.com/aws/aws-sdk-js-v3/blob/fa60bf375c0a142263e4a67a330a79862cfa4102/clients/client-mediastore-data/models/models_0.ts#L378).

When forcing a string into the field, the S3 upload will actually be performed as expected.

When trying to provide a `Readable`, as the types suggest, I actually get a `NotImplemented: A header you provided implies functionality that is not implemented` response.

#### Expected behavior
The field should allow a pure string input, as the SDK seems to actually perform as expected with a string input.

The SDK documentation even uses a string input itself: https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/s3-example-creating-buckets.html#s3-example-upload-new-object

**Comment by AllanZhengYP** [comment]
Hi @oliversalzburg 

You can supply string to body, here's the [doc](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/interfaces/putobjectcommandinput.html):

```typescript
import { PutObjectCommandInput } from '@aws-sdk/client-s3';

cons foo: PutObjectCommandInput = { Body: "some string" }
```

The reason for the error you are seeing when supplying a steam is because SDK has a hard time infering the length of the body stream. Currently, we infer the length from the following values:
https://github.com/aws/aws-sdk-js-v3/blob/f0688feebddf979a4a3403d4108a6727cbdc3fd5/packages/util-body-length-node/src/index.ts#L9-L17

I will label this issue as a documentation, because they work as intended. We need to provide more helpful error message when we cannot infer the length rather than what's currently thrown.

**Comment by oliversalzburg** [comment]
@AllanZhengYP I don't understand how you expect that to compile when the type isn't matching the one [expected by the SDK](https://github.com/aws/aws-sdk-js-v3/blob/fa60bf375c0a142263e4a67a330a79862cfa4102/clients/client-mediastore-data/models/models_0.ts#L184).

I know the types are wrong and that a `string` is actually acceptable. That's why I opened this ticket.

**Comment by schof** [comment]
I agree. The types seem wrong here (including the v3 documentation which does not say you can use a string). 

Here is the workaround I used:

```typescript
import { Readable } from "stream";

// ...

const client = new S3Client({ region: "us-east-1" });
const params: PutObjectRequest = {
  Bucket: "whatever",
  Key: "some key",
  Body: dataString as unknown as Readable,
};
await client.send(new PutObjectCommand(params));

```

**Comment by kuhe** [comment]
closed because this was fixed some time ago and string is a valid input type of [PutObjectCommandInput](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/interfaces/putobjectcommandinput.html)
