### ISSUE TITLE
S3 Client `send` Throws/Rejects on 304 

### ISSUE THREAD

**Issue by ambroselittle** [aws/aws-sdk-js-v3#2635]
## Describe the bug
S3 JS client throws when IfNoneMatch causes a 304 response.

#### SDK version number
`@aws-sdk/client-s3@3.24.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`
v14.17.3

## Steps to reproduce
Pared down to the essentials. (Will not run as-is, but you can supply the vars, of course.)

```ts
import { S3, GetObjectCommand, GetObjectCommandInput } from '@aws-sdk/client-s3'

const s3 = new S3({
    region: region,
});


const commandOptions = { Bucket: bucket, Key: s3FilePath, } as GetObjectCommandInput;
if (etag) {
    commandOptions.IfNoneMatch = etag;
}

const obj = await s3.send(new GetObjectCommand(commandOptions));

```

#### Observed behavior
That last line throws:
```bash
Error: 
    at deserializeAws_restXmlGetObjectCommandError (/Volumes/Dev/Repos/some-app/node_modules/@aws-sdk/client-s3/protocols/Aws_restXml.ts:7251:39)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at /Volumes/Dev/Repos/some-app/node_modules/@aws-sdk/middleware-serde/src/deserializerMiddleware.ts:20:15
    at /Volumes/Dev/Repos/some-app/node_modules/@aws-sdk/middleware-signing/src/middleware.ts:26:22
    at StandardRetryStrategy.retry (/Volumes/Dev/Repos/some-app/node_modules/@aws-sdk/middleware-retry/src/StandardRetryStrategy.ts:83:38)
    at /Volumes/Dev/Repos/some-app/node_modules/@aws-sdk/middleware-logger/src/loggerMiddleware.ts:22:22
    at getObject (/Volumes/Dev/Repos/some-app/src/stuff/helpers/s3/s3CodeClient.ts:128:19)
    at loadFile (/Volumes/Dev/Repos/some-app/src/stuff/helpers/s3/s3CodeClient.ts:156:107)
    at realDownload (/Volumes/Dev/Repos/some-app/src/stuff/helpers/s3/s3CodeClient.spec.ts:193:5)
    at Object.<anonymous> (/Volumes/Dev/Repos/some-app/src/stuff/helpers/s3/s3CodeClient.spec.ts:185:5) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 304,
    requestId: undefined,
    extendedRequestId: '[the-id-was-here]',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}
```

#### Expected behavior
I do not consider 304 to be an exception. When I supply IfNoneMatch, I am explicitly anticipating that I may receive a 304 and have code to handle it as normal, non-exceptional flow.

I am (currently) catching and checking the metadata on the thrown Error, but I expect to check the status code in the `GetObjectCommandOutput` metadata (`obj.$metadata.httpStatusCode`) without an exception in this case. 

## Additional context
I am partly filing this because it is not at all clear that this is the intended behavior. It is certainly not what I expeected, and despite searching, I cannot find anything about if it is expected on your end. It was not clear what the `deserializer` in your `deserializerMiddleware` is expecting after a quick look.

I would suggest documenting [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/classes/getobjectcommand.html) the cases where it will throw. For example, if any non-200 is considered to warrant throwing/rejecting, then mention that. However, as I said, I don't see handling this case to be exceptional. I'd prefer to avoid the overhead of error handling for it.

**Comment by thebengeu** [comment]
@AllanZhengYP made #1591 throw 3xx response as exceptions [here](https://github.com/aws/aws-sdk-js-v3/blob/a14c9c52823571ec4ffca56137763599584bea32/clients/client-s3/protocols/Aws_restXml.ts#L7068). I understand why other 3xx redirections are thrown as exceptions, but should 304 be thrown as an exception?
