### ISSUE TITLE
dynamodbDocClient error

### ISSUE THREAD

**Issue by sriniscigithub** [aws/aws-sdk-js-v3#2636]
## Describe the bug
When i use the V3 DynamoDBClient code getting error
```typescript
import { dbResult, DynamoCodeSystem } from './types'
import { DynamoDBClient, GetItemCommand, PutItemCommand } from '@aws-sdk/client-dynamodb'
import { marshall, unmarshall } from '@aws-sdk/util-dynamodb'
import { TsRequest, CsMetaLoad } from 'src/interfaces/tsRequest'
import { getDynamoConfig, getDynamoDbTableName } from '@libs/dynamoDb/config'

export const getCodeSystem = async (cs:string) : Promise<DynamoCodeSystem|null> => {
  const dbclient = new DynamoDBClient(getDynamoConfig());
  const { Item } = await dbclient.send(new GetItemCommand({
    TableName: getDynamoDbTableName(),
    Key: marshall({
      key1: 'CodeSystem',
      key2: cs,
    }),
    ProjectionExpression: 'deleted, meta'
  }));

  if (Item===undefined) 
    return null;

  const item = unmarshall(Item);

  if (item.deleted===1)
    return null;

  return item.meta;
};
```

2021-08-02T23:05:01.169Z	be4582ab-8839-4ca5-8fd1-723ba28054b4	INFO	New DBDOC Clinet Aug 01 Error CredentialsProviderError: Could not load credentials from any providers
    at providers (/var/task/node_modules/@aws-sdk/client-dynamodb/node_modules/@aws-sdk/credential-provider-node/src/index.ts:66:13)
    at /var/task/node_modules/@aws-sdk/client-dynamodb/node_modules/@aws-sdk/property-provider/src/chain.ts:20:18
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at SignatureV4.credentialProvider (/var/task/node_modules/@aws-sdk/client-dynamodb/node_modules/@aws-sdk/property-provider/src/memoize.ts:72:22)
    at SignatureV4.signRequest (/var/task/node_modules/@aws-sdk/client-dynamodb/node_modules/@aws-sdk/signature-v4/src/SignatureV4.ts:220:25)
    at /var/task/node_modules/@aws-sdk/client-dynamodb/node_modules/@aws-sdk/middleware-signing/src/middleware.ts:28:18
    at StandardRetryStrategy.retry (/var/task/node_modules/@aws-sdk/client-dynamodb/node_modules/@aws-sdk/middleware-retry/src/StandardRetryStrategy.ts:83:38)
    at /var/task/node_modules/@aws-sdk/client-dynamodb/node_modules/@aws-sdk/middleware-logger/src/loggerMiddleware.ts:22:22
    at data (/var/task/node_modules/@aws-sdk/lib-dynamodb/src/commands/GetCommand.ts:48:20)
    at /var/task/src/functions/csLoadReq/webpack:/ts-load/src/libs/dynamoDb/codeSystem.ts:61:11 {
  tryNextLink: false,
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}

#### SDK version number
`@aws-sdk/package-name@version`

#### Is the issue in the browser/Node.js/ReactNative?
Browser/Node.js/ReactNative

#### Details of the browser/Node.js/ReactNative version
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`

## Steps to reproduce
Please share code or minimal repo, and steps to reproduce the behavior.

#### Observed behavior
A clear and concise description of what happens.

#### Expected behavior
A clear and concise description of what you were expecting to happen.

**Comment by ajredniwja** [comment]
Hi there, can you please share how you are setting the credentials?

**Comment by sriniscigithub** [comment]
I will share the screen. Please call me on my mobile +1(703) 962 0512

**Comment by hectorgabucio** [comment]
Hey! same happens to me. Unfortunately, it is difficult to reproduce (It happened to me yesterday 2 times but randomly)
My code is running on a docker container on ECS. I just configure the client with aws Region and endpoint

`  private constructor(
    awsRegion: string = process.env.AWS_REGION,
    endpoint: string = process.env.DB_ENDPOINT
  ) {
    this.client = new DynamoDBClient({
      region: awsRegion,
      endpoint: endpoint
    })`

**Comment by PoofyFoopy** [comment]
Having the same error.

DynamoDB V2 works but V3 has the credentials error for some reason.

My configuration is `{region: 'eu-west-1'}`.

I don't have any credentials set since this is running on Lambda and I'm assuming that any credentials required can be gotten from the Execution Role or the env variables that are provided by default by AWS Lambda.

**Comment by AllanZhengYP** [comment]
Hi @PoofyFoopy @sriniscigithub @hectorgabucio 

Without the affected SDK version it's hard to findout if the root cause is a bug already fixed. Can you try the latest version 3.28.0 to see if the error persists?

**Comment by hectorgabucio** [comment]
Hey @AllanZhengYP 
I tried in my ECS cluster, one node with the dependency on version 3.29.0. The other node with an old version (3.26.0).
The node with the newest version didnt fail with the "Unable to load credentials" error, so it seems fixed 🙏🏽 the node with the old version failed.

**Comment by AllanZhengYP** [comment]
@hectorgabucio Good to know it's fixed!
