### ISSUE TITLE
Error: 'request' is not exported by __vite-browser-external

### ISSUE THREAD

**Issue by subhendukundu** [aws/aws-sdk-js-v3#2648]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
I am trying to use `@aws-sdk/client-sns` with `esbuild` but won't build echoing an error `Error: 'request' is not exported by __vite-browser-external`.

I have tried to use this which doesnt fix the issue. https://github.com/aws-amplify/amplify-js/issues/7499#issuecomment-804386820

A reproducible example would be https://github.com/subhendukundu/worker-auth-providers/tree/discord/example

Are there any workarounds to fix it?

**Comment by klarkc** [comment]
Related #2478 

@subhendukundu in the related issue  there is a PR to fix the same kind of problem, might be useful

**Comment by Fanna1119** [comment]
i solved it with the following

```js


  resolve: {
    alias: [
      {
        find: '@', replacement: path.resolve(__dirname, './src'),
      },
      {
        find: './runtimeConfig', replacement: './runtimeConfig.browser',
      }

    ]
  }

```

**Comment by t-lock** [comment]
https://ui.docs.amplify.aws/getting-started/installation#vite

A sub-product of amplify also suggests what @Fanna1119 is using above, although pared down:

```
  resolve: {
    alias: [
      {
        find: "./runtimeConfig",
        replacement: "./runtimeConfig.browser",
      },
    ],
  },
```

Suitable workaround for me.
