### ISSUE TITLE
Publish all packages using Lerna

### ISSUE THREAD

**Issue by hassankhan** [aws/aws-sdk-js-v3#265]
Hi there,

Would be awesome if `lerna publish` was run on CI to automatically release all packages to NPM. This would resolve #172 and #173.

You can also use the `--conventionalcommits` flag to generate a `CHANGELOG.md` for all packages too.

Link for more reading: https://github.com/lerna/lerna/tree/master/commands/publish

**Comment by AllanFly120** [comment]
@hassankhan 

Thank your for the advise, these are also sulutions we are using. We have `CHANGELOG.md` for each package now if you notice. We are still working on refactoring our CI/CD system to work better with monorepo structure. Any recommendations are welcome!

**Comment by hassankhan** [comment]
@AllanFly120 using `lerna publish` automatically updates all `CHANGELOG.md` files for all packages too.
