### ISSUE TITLE
`ExpressionAttributeValues` in `UpdateItemCommand` TS Error

### ISSUE THREAD

**Issue by nazarvovk** [aws/aws-sdk-js-v3#2652]
## Describe the bug
Incorrect type on `ExpressionAttributeValues` **or** `UpdateItemCommand` not unmarshalling `ExpressionAttributeValues` properly.

## Your environment
Lambda NODEJS_14_X

#### SDK version number
`@aws-cdk/aws-dynamodb@1.117.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

## Steps to reproduce
If you pass marshalled values to ExpressionAttributeValues, it inserts them like maps
E.g.:
```ts
const command = new UpdateItemCommand({
  TableName: this.tableName,
  Key: marshall({
    PK: `CANDLESTICK#${candlestick.symbol}`,
    SK: candlestick.persistenceKey,
  }),
  UpdateExpression, // this is in form "set #key_test1 = :test1, #key_test2 = :test2"
  ExpressionAttributeValues: marshall(attributeValues), // attributeValues is of type Record<string, string>.
  ExpressionAttributeNames: attributeNames,
})
```
![pic](https://user-images.githubusercontent.com/25109107/128668712-c1a01833-231f-440f-9a59-305ec265fd74.png)

If you do it like that, it inserts the values correctly, but there's a ts error, it expects marshalled values:
```ts
const command = new UpdateItemCommand({
  TableName: this.tableName,
  Key: marshall({
    PK: `CANDLESTICK#${candlestick.symbol}`,
    SK: candlestick.persistenceKey,
  }),
  UpdateExpression,
  ExpressionAttributeValues: attributeValues, // Error here
  ExpressionAttributeNames: attributeNames,
})
```
![pic](https://user-images.githubusercontent.com/25109107/128669739-e0dfbfb0-59ad-4f50-aa02-5fb5256affaa.png)

The problem is only with `ExpressionAttributeValues`, `ExpressionAttributeNames` already accepts `{ [key: string]: string }` and works fine

#### Expected behavior
Either `ExpressionAttributeValues` needs to expect a type of `{ [key: string]: string }`, or should unmarshall the values to properly insert into the db

**Comment by samchungy** [comment]
Use the document client in @lib-dynamodb if you want that to be handled

**Comment by trivikr** [comment]
> Use the document client in `lib-dynamodb` if you want that to be handled

Yup, please use [@aws-sdk/lib-dynamodb](https://www.npmjs.com/package/@aws-sdk/lib-dynamodb) as it auto performs marshalling/unmarshalling for you.

**Comment by nazarvovk** [comment]
Thanks, @aws-sdk/lib-dynamodb works for me.

Though, it seems this here is a bug anyway.
