### ISSUE TITLE
Invalid signature when passing MaxResults as a number to GetApisCommand

### ISSUE THREAD

**Issue by LinusU** [aws/aws-sdk-js-v3#2665]
## Describe the bug

When passing in `MaxResults` as a number, e.g. `500`, to GetApisCommand, the entire request fails with a JSON parse error:

```text
SyntaxError: Unexpected token 
 in JSON at position 190
    at JSON.parse (<anonymous>)
    at /Users/linus/foo/node_modules/@aws-sdk/client-apigatewayv2/dist/cjs/protocols/Aws_restJson1.js:9712:21
    [...]
```

Adding some logging there revelas that the data received from the server indeed contains invalid JSON:

```text
{"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The Canonical String for this request should have been
'GET
/v2/apis
maxResults=500
amz-sdk-invocation-id:31281a7f-c0f1-4dfd-a449-253b0599a28b
amz-sdk-request:attempt=1; max=3
host:apigateway.eu-north-1.amazonaws.com
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20210812T145246Z
x-amz-user-agent:aws-sdk-js/3.25.0

amz-sdk-invocation-id;amz-sdk-request;host;x-amz-content-sha256;x-amz-date;x-amz-user-agent
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'

The String-to-Sign should have been
'AWS4-HMAC-SHA256
20210812T145246Z
20210812/eu-north-1/apigateway/aws4_request
83ed97e01b6649a1c062b777c2d0da249ae1d935b25b9e9c2af3171b008fb3b9'
"}
```

(note that that is actual newlines returned, not escaped `\n` tokens)

Turns out that you can easily work around this problem by passing in `MaxResults: "500"`, that is passing in a string instead of a number. If you look closely in the documentation you can see that `MaxResults` is actually documented as a string, it is however quite surprising that it isn't a number 😅 

#### SDK version number
`@aws-sdk/client-apigatewayv2@3.25.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Node.js `v16.5.0`

## Steps to reproduce

```js
const { ApiGatewayV2Client, GetApisCommand } = require('@aws-sdk/client-apigatewayv2')

const apiGatewayV2 = new ApiGatewayV2Client()

await apiGatewayV2.send(new GetApisCommand({ MaxResults: 500 }))
```

#### Observed behavior
```text
SyntaxError: Unexpected token 
 in JSON at position 190
```

#### Expected behavior
I expected to get a list of my first 500 APIs.

#### Screenshots
n/a

## Additional context
n/a

**Comment by eneskaya** [comment]
@LinusU did you get to find a fix for this issue? Or a cause? I'm experiencing the same thing.

**Comment by ajredniwja** [comment]
Hey everyone apologies the issue fell out of queue, the issue seems to be `MaxResults` expecting a string. 
```const result = await apiGatewayV2.send(new GetApisCommand({ MaxResults: '500' }))``` should resolve the issue. 

Closing this issue now please reach out/open a new issue if you have any other questions. Thanks

**Comment by medikoo** [comment]
I believe this should be reopened, as the way in which this error is reported is a clear bug.

How are we supposed to translate `SyntaxError: Unexpected token` error message into information that incorrect type was provided for a payload property ?

**Comment by kuhe** [comment]
errors like `SyntaxError: Unexpected token` should in the future contain a hint to check the `$response` field for more information. For an explanation of why it is not directly printed: https://github.com/aws/aws-sdk-js-v3/pull/4592

**Comment by ajredniwja** [comment]
The error message with latest version does mention to check the $response field for more information to handle errors. 
`error SyntaxError: Unexpected token 
 in JSON at position 190
  Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.`
