### ISSUE TITLE
aws

### ISSUE THREAD

**Issue by dj110919871** [aws/aws-sdk-js-v3#2669]
## Describe the issue with documentation
A clear and concise description of what the issue is.

## Steps to reproduce
Please share code or minimal repo if required, and steps to reproduce the behavior.

#### Observed behavior
A clear and concise description of what happens.

#### Expected behavior
A clear and concise description of what you were expecting to happen.

**Comment by AllanZhengYP** [comment]
@dj110919871 I will close this one for now. You can open a new issue with full information if you have questions with SDK
