### ISSUE TITLE
Streaming Transcribe Client -  speaker-change events missing in response

### ISSUE THREAD

**Issue by ShantanuNair** [aws/aws-sdk-js-v3#2691]
## Describe the bug
AWS Streaming Transcribe has [speaker diarization for streaming transcriptions with AWS Transcribe](https://aws.amazon.com/blogs/machine-learning/using-speaker-diarization-for-streaming-transcription-with-amazon-transcribe-and-amazon-transcribe-medical/) however the `speaker-change` events are missing in the [@aws-sdk/client-transcribe-streaming](https://github.com/aws/aws-sdk-js-v3/tree/main/clients/client-transcribe-streaming) v3.26.0 client distribution even when ShowSpeakerLabel is `true`.

[Relevant documentation - Identifying speakers in real-time streams](https://docs.aws.amazon.com/transcribe/latest/dg/diarization-streaming.html)

This seems to be because the ItemTypes enum in [clients/client-transcribe-streaming/models/models_0.ts](https://github.com/aws/aws-sdk-js-v3/blob/acbb59a589171a97f6a4276cb825c9c58d22d6f1/clients/client-transcribe-streaming/models/models_0.ts#L3) has only `PRONUNCIATION` and `PUNCTUATION` types and is missing the type for `speaker-change` type items.

#### SDK version number
`@aws-sdk/client-transcribe-streaming@3.26.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Node.js v14.16.1

## Steps to reproduce
In Node, import `@aws-sdk/client-transcribe-streaming@3.10.0` as a dependency and send the `StartStreamTranscriptionCommand` Command via the transcribe streaming client with `ShowSpeakerLabel: true`. Print each event of returned `StartStreamTranscriptionCommandOutput.TranscriptResultStream`. Send in audio containing multiple speakers and note lack of speaker-change type items even when consecutive words of complete speech segments (not partials) have different speakers speaking. 

```
const audioStream = async function* () {
  for await (const pcmChunk of inputStream){
    yield {
      AudioEvent: {
        AudioChunk: pcmChunk
      },
    };
  }
};

const startCommand = new StartStreamTranscriptionCommand({
  LanguageCode: "en-US",
  MediaEncoding: "pcm",
  MediaSampleRateHertz: 8000,
  AudioStream: audioStream(),
  ShowSpeakerLabel: true
});

const startCommandOutput = await transcribeClient.send(startCommand);

for await (const event of startCommandOutput.TranscriptResultStream) {
  for (const result of event.TranscriptEvent?.Transcript?.Results || []) {
    if (result.IsPartial === false) {
      const itemsTypes = result.Alternatives[0]?.Items.map(item => item.Type)
      console.log("Types:", itemsTypes);
      // speaker-change events are missing where they should be!!
    }
  }        
}
```

#### Observed behavior
Only pronunciation and punctuation types are seen - even when speakers change between consecutive words (we don't receive the speaker-change event).

```
Types:  [
  'pronunciation',
  'pronunciation',
  'punctuation',
  'pronunciation',
  'pronunciation',
  'punctuation'
]
```

#### Expected behavior
As explained in [documentation](https://docs.aws.amazon.com/transcribe/latest/dg/diarization-streaming.html), items of type `speaker-change` should be seen in Alternatives in between transcription results have speaker changes between words for complete speech segment transcript results.

```
Types:  [
  'pronunciation',
  'pronunciation',
  'punctuation',
  'speaker-change',
  'pronunciation',
  'pronunciation',
  'speaker-change',
  'punctuation'
]
```

## Additional context
the [deserializeAws_restJson1Item](https://github.com/aws/aws-sdk-js-v3/blob/acbb59a589171a97f6a4276cb825c9c58d22d6f1/clients/client-transcribe-streaming/protocols/Aws_restJson1.ts#L785) method deserializes these Items but
it looks like [models_0.ts](https://github.com/aws/aws-sdk-js-v3/blob/acbb59a589171a97f6a4276cb825c9c58d22d6f1/clients/client-transcribe-streaming/models/models_0.ts#L3) would need a type for the speaker change for speaker changes to be detected. Going by the documentation, it should look something like

```
export declare enum ItemType {
    PRONUNCIATION = "pronunciation",
    PUNCTUATION = "punctuation",
    SPEAKER_CHANGE = "speaker-change"
}
```

**Comment by vudh1** [comment]
Hi @ShantanuNair, thanks for reaching out. I'm not able to reproduce the issue. Can you confirm if you are still experiencing this under the latest SDK version `3.42.0`?
