### ISSUE TITLE
Add retry strategy options to `RemoteProviderConfig`

### ISSUE THREAD

**Issue by dmattia** [aws/aws-sdk-js-v3#2706]
### Is your feature request related to a problem? Please describe.

Occasionally, the AWS metadata services will fail to fetch credentials. One common cause I've seen is the status code 429 `TooManyRequestsException`, which means too many requests are sent in a short time period and the client is rate limited.

The `RemoteProviderConfig` type allows passing a `maxRetries` value to each client, however, it does not give options for how those retries should occur.

Here's an image of a trace where I had a client get rate limited with `maxRetries` set to 5. Notice, all of the calls fail, as all of the calls are separated by under 1ms. If the metadata endpoint is failing because of rate limiting issues, it is unlikely to not be rate limited .5ms later.

<img width="1380" alt="Screen Shot 2021-08-24 at 9 42 10 PM" src="https://user-images.githubusercontent.com/8922077/130717838-4e891fb6-373f-4eec-b125-4e5c1ee2f090.png">

### Describe the solution you'd like

I want to have an additional field to specify a retry strategy. This could be as simple as a `retryDelay` parameter that takes in how much time to wait for linear retries, or could be a set of fields that specifies if the retry should be exponential/linear, etc.

### Describe alternatives you've considered

none

### Additional context

none

**Comment by trivikr** [comment]
@dmattia We have an existing option to set retry mode for clients. It's not documented in developer guide, so I'll create a request with writers. It is similar to [AWS CLI retries](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-retries.html#cli-usage-retries-configure)

We will evaluate if this retry mode can be used for while fetching credentials.

In the mean time, I created two other reports based on your feature request:
* https://github.com/aws/aws-sdk-js-v3/issues/2707
* https://github.com/aws/aws-sdk-js-v3/issues/2709

Do you have information on the `path` of http request which is throwing `429 TooManyRequestsException`?

**Comment by aldegoeij** [comment]
related to my issue on the SecurityHub client: https://github.com/aws/aws-sdk-js-v3/issues/2741
