### ISSUE TITLE
TypeError: Cannot read property 'Error' of undefined in loadEc2ErrorCode

### ISSUE THREAD

**Issue by barryhagan** [aws/aws-sdk-js-v3#2718]
## Describe the bug

The error handling of @aws-sdk/client-ec2 when calling `DescribeSecurityGroupsCommand` can cause a reference error:

```
TypeError: Cannot read property 'Error' of undefined
    at loadEc2ErrorCode (/app/node_modules/@aws-sdk/client-ec2/dist/cjs/protocols/Aws_ec2.js:60280:21)
    at deserializeAws_ec2DescribeSecurityGroupsCommandError (/app/node_modules/@aws-sdk/client-ec2/dist/cjs/protocols/Aws_ec2.js:15876:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /app/node_modules/@aws-sdk/middleware-serde/dist/cjs/deserializerMiddleware.js:6:20
    at async /app/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:12:24
    at async StandardRetryStrategy.retry (/app/node_modules/@aws-sdk/middleware-retry/dist/cjs/StandardRetryStrategy.js:51:46)
    at async /app/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22
    
```

#### SDK version number
`"@aws-sdk/client-ec2": "^3.25.0",`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v16.5.0

## Steps to reproduce

This is the client code that produced the exception, but unclear what specific state in AWS causes an error response:
```
    const groups = await this.ec2Client.send(
      new DescribeSecurityGroupsCommand({
        Filters: [
          {
            Name: 'group-name',
            Values: 'mygroupname',
          },
        ],
      }),
    );
```

#### Observed behavior
If the `DescribeSecurityGroupsCommand` fails, it is possible that the `Errors` object is undefined in the API response, causing the TypeError

#### Expected behavior
Don't crash in an error handler please.

#### Screenshots
N/A

## Additional context
It looks like even if a guard like this was added to loadEc2ErrorCode:
`if (data.Errors?.Error?.Code !== undefined) {`
this code path would then crash inside deserializeAws_ec2DescribeSecurityGroupsCommandError because of this:
`errorCode = parsedBody.Errors.Error.code || parsedBody.Errors.Error.Code || errorCode;`

**Comment by ajredniwja** [comment]
Hey @barryhagan apologies as this issue was left out of queue I am trying to get back to all the old issues. I am having troubles reproducing this with the latest version of the SDK when using `DescribeSecurityGroupsCommand`, I tried to make the command fail in different scenarios but the  response included correct description of the errors.
Without determining the conditions under which the error is raised I believe this wont be reproducible.

**Comment by barryhagan** [comment]
Looks like it still happens: https://github.com/aws/aws-sdk-js-v3/issues/3777

Since this is a behavior of the EC2 api, I don't know if you can get a reliable repro, but it should be possible to better handle the possibility that the `Errors` is undefined in the client.

Mock an API response with that property undefined and handle the condition.
