### ISSUE TITLE
Presigner Host Injection accesses an invalid property

### ISSUE THREAD

**Issue by pshah123** [aws/aws-sdk-js-v3#2725]
## Describe the bug
The bug exists in the `s3-request-presigner` package. Specifically, attempting to presign an existing request using `presigner.presign(request)` fails with a string error (cannot trim undefined).

This is caused by the `SignatureV4` module attempting to access the `host` header, which does not exist. Issue #1988 addressed this and a PR was implemented to fill the `host` header automatically from the `hostname` property of the request. However, this fix introduces a bug as the property path is invalid.

While the fix retrieves the host header from the `.hostname` property of an `HttpRequest` object, this property path actually does not exist; the correct property path is `.endpoint.hostname`. Simply changing it to this or adding a `|| .endpoint.hostname` would work here.

The line to fix: https://github.com/aws/aws-sdk-js-v3/blob/648a41ab95d0786ea0227b42645883afd8f6ee2b/packages/s3-request-presigner/src/presigner.ts#L47

A temporary workaround for others is to inject the `.hostname` property into the request before presigning. The above fix will then retrieve the `.hostname` property to populate the host header.
```
const req = new HttpRequest(endpoint, region)
req.hostname = req.endpoint.hostname
const url = await presigner.presign(req)
```

A similar bug occurs with the protocol which is sometimes undefined, resulting in presigned urls that begin with `undefined//`.

## Your environment
Node.js 16.4.0

#### SDK version number
`@aws-sdk/s3-request-presigner@3.28.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v16.4.0

## Steps to reproduce
``` js
const client = new S3(...) // with your credentials
const presigner = new S3RequestPresigner({...client.config, sha256: Hash.bind(null, "sha256")})

const objectUrl = '...' // some S3 object URL
const region = '...'
const endpoint = parseUrl(objectUrl) // @aws-sdk/url-parser
const req = new HttpRequest(endpoint, region)

const url = await presigner.presign(req)
console.log(formatUrl(urlReq)) // @aws-sdk/util-format-url
```

#### Observed behavior
Error:
```
Uncaught TypeError: Cannot read property 'trim' of undefined
    at Object.getCanonicalHeaders (...path to project.../node_modules/@aws-sdk/signature-v4/dist/cjs/getCanonicalHeaders.js:20:62)
    at SignatureV4.presign (...path to project.../node_modules/@aws-sdk/signature-v4/dist/cjs/SignatureV4.js:41:56)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
While the error message refers to Signaturev4, the issue is actually in `s3-request-presigner` as described above.

**Comment by AllanZhengYP** [comment]
Hi @pshah123 

There's a line in question in your code snippet:

```JavaScript
const req = new HttpRequest(endpoint, region) // Which HttpRequest?
```

Current HttpRequest does include the `hostname`: https://github.com/aws/aws-sdk-js-v3/blob/b1a3975c8f70938f45a3ba8080cd186bf01b17d2/packages/protocol-http/src/httpRequest.ts#L7-L10
