### ISSUE TITLE
presigning an endpoint with port doesn't work

### ISSUE THREAD

**Issue by shyallegro** [aws/aws-sdk-js-v3#2726]
## Describe the bug
trying to presign an endpoint that has a none default port produce an invalid signature

## Your environment
browser

#### SDK version number
`@aws-sdk/s3-request-presigner@3.20.0`

#### Is the issue in the browser/Node.js/ReactNative?
Browser

#### Details of the browser/Node.js/ReactNative version
  Browsers:
    Chrome: 92.0.4515.159
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.84)

## Steps to reproduce
serving minio on port 9000
```const [hostname, port] = set.Endpoint?.split(':') || ['', ''];
const config = {
  region: set.Region || DEFAULT_REGION,
  credentials: {
	accessKeyId: set.Key,
	secretAccessKey: set.Secret
  },
  ...(set.Endpoint && {
	endpoint: {
	  protocol: set.useSSL ? 'https' : 'http',
	  hostname,
	  port,
	  path: '/',
	},
	forcePathStyle: true
  }),
} as S3ClientConfig;
const s3 = new S3Client(config);
const command = new GetObjectCommand({Key: bucketKeyEndpoint.Key, Bucket: bucketKeyEndpoint.Bucket});
getSignedUrl(s3, command, {expiresIn: FOUR_DAYS})
  .then(console.log);
```

#### Observed behavior
the signed URL doesn't work and an 403 XML error is shown

#### Expected behavior
the signed url should fetch the resource, in my case an image

## Additional context
after a lot of digging in the old V2 client and the new V3 I overridden `getSignedUrl` to replace the host header with 
```
 if (request.port) {
    request.headers['host'] = `${request.hostname}:${request.port}`;
  }
```
to solve the issue

**Comment by pshah123** [comment]
Based on the workaround it seems this is related to #2725 -- the host injection is not taking into account the correct parameters such as the correct hostname path and port, causing the presign to fail.

**Comment by shyallegro** [comment]
@pshah123 on #2725 an exception occurs in the code, in this case the result signed URL is invalid, however they looks very related and the one might also solve this issue.

**Comment by AllanZhengYP** [comment]
@shyallegro Thank you for the investigation to the issue. I will put up a fix soon.
