### ISSUE TITLE
CredentialsProviderError regression

### ISSUE THREAD

**Issue by oliversalzburg** [aws/aws-sdk-js-v3#2734]
## Describe the bug
After upgrading the AWS SDK, I can no longer upload to S3 due to `CredentialsProviderError`.

#### SDK version number
`@aws-sdk/client-s3@3.28.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
`v16.6.2`

## Steps to reproduce
Have an EC2 instance with an assigned policy that allows upload access to an S3 bucket. Then try to upload to that bucket.

#### Observed behavior
SDK will throw: `CredentialsProviderError: Could not load credentials from any providers`

#### Expected behavior
Files are uploaded to S3.

## Additional context
This used to work fine previously and I haven't changed our infrastructure.
#2636 may be related.

**Comment by AllanZhengYP** [comment]
Hi @oliversalzburg,

Can you share more information with your setup, like code snippet? I spun up a new AL 2 instance and tried the snippet bellow, it works fine: 

```javascript
const { S3Client, PutObjectCommand } = require("@aws-sdk/client-s3");
const { STS } = require("@aws-sdk/client-sts");
const REGION = "us-west-2";
const BUCKET = ""
const run = async () => {
  const sts = new STS({ region: REGION });
  console.log(await sts.getCallerIdentity({}));
  const s3Client = new S3Client({ region: REGION });
  const res = await s3Client.send(new PutObjectCommand({ Bucket: BUCKET, Key: "test", Body: "issue/2734" }));
  console.log(res);
}

(async () => {
  try {
    await run();
  } catch(e) {
    console.error(e);
    throw e;
  }
})();
```
The STS response indicates the role is indeed from the attached role.

**Comment by oliversalzburg** [comment]
Here is my code:
```ts
async uploadDocument(key: string, contentType: string, body: Buffer): Promise<void> {
    const configuration: S3ClientConfig = { region: "eu-central-1" };
    const client = new S3Client(configuration);
    const bucket = this._configuration.registry.get("bucket.documents.name");
    const dayFolder = `${moment.utc().startOf("day").toDate().getTime() / 1000}`;
    const documentKey = cryptoRandomString({
      length: 64,
      characters: "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcefghijklmnopqrstuvwxyz",
    });
    const request: PutObjectRequest = {
      // The typing for `Body` seems to be invalid.
      // See: https://github.com/aws/aws-sdk-js-v3/issues/2629
      Body: body as unknown as Readable,
      Bucket: bucket,
      ContentType: contentType,
      Key: `${dayFolder}/${documentKey}/${key}`,
    };
    const command = new PutObjectCommand(request);
    await client.send(command);
}
```
It has been working as expected for months.

Yesterday, after a new release rollout, I saw the `CredentialsProviderError` in both prod and dev environments, so I assumed it must have been a recent AWS SDK update introducing this.

Tonight the prod instance worked fine, the dev instance still threw the same error. I don't see why there wouldn't be any credentials available.

**Comment by oliversalzburg** [comment]
Well, after further investigating, I had to realize that a change in our CI scripts actually stripped the expected role off the service. My apologies.
