### ISSUE TITLE
Invalid package.json included in dist/es and dist/cjs in @aws-sdk/client-s3

### ISSUE THREAD

**Issue by hansottowirtz** [aws/aws-sdk-js-v3#2740]
## Describe the bug
In `@aws-sdk/client-s3`, there's a copy of its `package.json` included inside `dist/es` and `dist/cjs`. When looking for the `package.json` for one of the files inside `@aws-sdk/client-s3`, this will resolve to one of those `package.json`s

```js
import pkgDir from 'pkg-dir'

console.log(await pkgDir('./node_modules/@aws-sdk/client-s3/dist/es/index.js'))
// -> ./node_modules/@aws-sdk/client-s3/dist/es
```

The closest `package.json` should be `./node_modules/@aws-sdk/client-s3/package.json` and not `./node_modules/@aws-sdk/client-s3/dist/es/package.json`

Moreover, these `package.json`s are invalid as their `main` field is set to `./dist/cjs/index.js` which doesn't exist inside `./dist/cjs` (`./dist/cjs/dist/cjs/index.js` doesn't exist).

#### SDK version number
`@aws-sdk/client-s3@3.28.0`

## Additional context
I have never seen different `package.json`s being shipped inside dist folders, and I haven't seen another `@aws-sdk` module doing this.

**Comment by vudh1** [comment]
Hi @hansottowirtz , thanks for reaching out. First, please update the SDK version to the latest one `3.41.0`. If you still experience the same problem then, can you provide more information like additional reproducible code, logs for review?

**Comment by trivikr** [comment]
The `package.json` files were removed from dist folders when we moved source files to `src` folder in https://github.com/aws/aws-sdk-js-v3/pull/2845

**Comment by trivikr** [comment]
Verified that package.json files is only present in root folder of clients since v3.35.0

```console
$ yarn add @aws-sdk/client-s3@3.34.0 --exact
...

$ find node_modules/@aws-sdk/client-s3 -name "package.json"
node_modules/@aws-sdk/client-s3/dist/cjs/package.json
node_modules/@aws-sdk/client-s3/dist/es/package.json
node_modules/@aws-sdk/client-s3/package.json

$ yarn add @aws-sdk/client-s3@3.35.0 --exact
...

$ find node_modules/@aws-sdk/client-s3 -name "package.json"
node_modules/@aws-sdk/client-s3/package.json
```

**Comment by hansottowirtz** [comment]
I can confirm that it has been fixed, thanks!
