### ISSUE TITLE
Paginated call hits rate limit of API, also with "adaptive" retry set.

### ISSUE THREAD

**Issue by aldegoeij** [aws/aws-sdk-js-v3#2741]
REPOST from: https://github.com/aws/aws-sdk-js/issues/3873, seems more suited in this repo?

- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Paginated API call hits the rate limit, even with "adaptive" retry mode set.

Retry mode does seem to back-off exponentially over 3 attempts, however, the `totalRetryDelay` is still too short not to trigger another `429`.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
node v14 lts

**SDK version number**
3

**To Reproduce (observed behavior)**

On an account with a lot of findings (1000+) the paginated api hits the 3 calls per minute API rate limit, even with retry policy set to adaptive.

```typescript
const client = new SecurityHubClient({
  region: "eu-west-1",
  retryMode: "adaptive",
});
const findings = [];
for await (const page of paginateGetFindings({ client }, {})) {
  // page contains a single paginated output.
  findings.push(...page.Findings);
}
```

**Expected behavior**
Some way to set a specific retry millisecond amount, or the paginated call should know this for the specific API.

Apparently there is a `DefaultRateLimiter` in the retry middleware: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/classes/_aws_sdk_middleware_retry.defaultratelimiter-1.html but no idea how and where this should be used?

This: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/interfaces/_aws_sdk_middleware_retry.defaultratelimiteroptions-1.html seems to allow setting rate limiter details, but there are 0 docs on what to set for e.g. a 3 cpm API?

**Screenshots**

```bash
TooManyRequestsException: Too Many Requests
    at deserializeAws_restJson1GetFindingsCommandError (/Users/alexander/Projects/qrmr/badgehq/node_modules/@aws-sdk/client-securityhub/dist/cjs/protocols/Aws_restJson1.js:3690:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/alexander/Projects/qrmr/badgehq/node_modules/@aws-sdk/middleware-serde/dist/cjs/deserializerMiddleware.js:6:20
    at async /Users/alexander/Projects/qrmr/badgehq/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:11:20
    at async AdaptiveRetryStrategy.retry (/Users/alexander/Projects/qrmr/badgehq/node_modules/@aws-sdk/middleware-retry/dist/cjs/StandardRetryStrategy.js:51:46)
    at async /Users/alexander/Projects/qrmr/badgehq/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22
    at async makePagedClientRequest (/Users/alexander/Projects/qrmr/badgehq/node_modules/@aws-sdk/client-securityhub/dist/cjs/pagination/GetFindingsPaginator.js:12:12)
    at async paginateGetFindings (/Users/alexander/Projects/qrmr/badgehq/node_modules/@aws-sdk/client-securityhub/dist/cjs/pagination/GetFindingsPaginator.js:33:20)
    at async getAWSSecurityHubFindings (webpack-internal:///./pages/api/findings/index.ts:67:22)
    at async handler (webpack-internal:///./pages/api/findings/index.ts:109:21) 
```

```typescript
{
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 429,
    requestId: '4eeafa49-1889-4206-9254-d9e43ce7230c',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 3,
    totalRetryDelay: 1568
  }
}
```

**Additional context**

**Comment by trivikr** [comment]
Suggestions provided to avoid reaching rate limit:

**Option 1**: Provide a custom `maxAttempts` during client creation, which would increase the number of attempts before failure. This can be tried in both values for retryMode (`standard` or `adaptive`)
```js
const client = new SecurityHubClient({
  maxAttempts: 5
});
```

**Option 2**: Provide a custom delayDecider without jitter.
```js
const MAXIMUM_RETRY_DELAY = 20 * 1000;

// Exponential backoff time delay decider (without jitter)
const delayDecider = (delayBase, attempts) =>
  Math.floor(
    Math.min(MAXIMUM_RETRY_DELAY, 2 ** attempts * delayBase)
  );

const client = new SecurityHubClient({
  retryStrategy: new StandardRetryStrategy(() => Promise.resolve(5), {
    delayDecider,
  }),
});
```

**Option 3**: Provide a custom delayDecider with higher value for maximum retry delay.
```js
const MAXIMUM_RETRY_DELAY = 30 * 1000;

// Exponential backoff time delay decider (without jitter)
const delayDecider = (delayBase, attempts) =>
  Math.floor(
    Math.min(MAXIMUM_RETRY_DELAY, 2 ** attempts * delayBase)
  );

const client = new SecurityHubClient({
  retryStrategy: new StandardRetryStrategy(() => Promise.resolve(5), {
    delayDecider,
  }),
});
```

There are other options, but we'll explore them if the above ones do not solve your problem.

**Comment by vudh1** [comment]
Hi @aldegoeij , thanks for reaching out. Let us know if the suggestions above are not able to solve your problem.
