### ISSUE TITLE
AWS CRT binary not present in any of the following locations

### ISSUE THREAD

**Issue by berenddeboer** [aws/aws-sdk-js-v3#2753]
## Describe the bug

When upgrading to 3.29.0, and compiling a typescript file to a single javascript file with esbuild, and running that with node, you get:

```
AWS CRT binary not present in any of the following locations:

       /codebuild/output/bin/native/aws-crt-nodejs
        /codebuild/output/bin/linux-x64/aws-crt-nodejs
```

## Your environment

First saw this in a codebuild job, but happens everywhere. So for example AWS Linux Workspace.

#### SDK version number
`@aws-sdk/client-s3@3.29.0`

#### Is the issue in the browser/Node.js/ReactNative?
node.js

Seen with version 14 and 16.

#### Expected behavior
As per #2750 you should not pull in aws-crt and 200MB of dependencies.

**Comment by ffxsam** [comment]
I'm getting this too, as of today:

```json
{
    "errorType": "Error",
    "errorMessage": "AWS CRT binary not present in any of the following locations:\n\t/bin/native/aws-crt-nodejs\n\t/bin/linux-x64/aws-crt-nodejs",
    "stack": [
        "Error: AWS CRT binary not present in any of the following locations:",
        "\t/bin/native/aws-crt-nodejs",
        "\t/bin/linux-x64/aws-crt-nodejs",
        "    at node_modules/aws-crt/dist/native/binding.js (/var/task/empty-trash.js:79961:13)",
        "    at __require (/var/task/empty-trash.js:38:44)",
        "    at node_modules/aws-crt/dist/native/crt.js (/var/task/empty-trash.js:79976:37)",
        "    at __require (/var/task/empty-trash.js:38:44)",
        "    at node_modules/aws-crt/dist/index.js (/var/task/empty-trash.js:81249:28)",
        "    at __require (/var/task/empty-trash.js:38:44)",
        "    at node_modules/@aws-sdk/signature-v4-crt/dist/cjs/CrtSignerV4.js (/var/task/empty-trash.js:81368:21)",
        "    at __require (/var/task/empty-trash.js:38:44)",
        "    at node_modules/@aws-sdk/signature-v4-crt/dist/cjs/index.js (/var/task/empty-trash.js:81490:31)",
        "    at __require (/var/task/empty-trash.js:38:44)"
    ]
}
```

This broke our functions in production. Rolling back to 3.28.0 of the SDK fixed it.

@AllanZhengYP @ajredniwja ☝️💥 

(likely related to #2750)

**Comment by AllanZhengYP** [comment]
@berenddeboer Seems like I cannot transfer the issue because we are not in the same github org. Can you reopen this issue against [their repo](https://github.com/awslabs/aws-crt-nodejs)? This issue worths their attention.

**Comment by AllanZhengYP** [comment]
To bring up their attention, I manually copied this ticket to the CRT package repo: https://github.com/awslabs/aws-crt-nodejs/issues/251. I will close this one. You should follow up on the other ticket.

**Comment by berenddeboer** [comment]
@AllanZhengYP  I saw this on AWS CodeBuild jobs, so that's Ubuntu 20 I think.
