### ISSUE TITLE
Socket timeouts are not honored using DocumentClient

### ISSUE THREAD

**Issue by marvin1up** [aws/aws-sdk-js-v3#2756]
## Describe the bug
Code that sets a timeout for document client by providing a NodeHttpHandler to DynamoDb does not cause connections to timeout after the specified time.

#### SDK version number
`@aws-sdk/client-dynamodb@3.29.0`
`@aws-sdk/lib-dynamodb@3.29.0`
`@aws-sdk/node-http-handler@3.29.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v12.20.1

## Steps to reproduce
```
import { DynamoDB } from '@aws-sdk/client-dynamodb';
import { DynamoDBDocument } from '@aws-sdk/lib-dynamodb';
import { NodeHttpHandler } from '@aws-sdk/node-http-handler';

const { AWS_REGION } = process.env;

// Use default Https agent, but override the socket timeout
const requestHandler = new NodeHttpHandler({
  connectionTimeout: 30000,
  socketTimeout: 30000,
});

const options = {
  region: AWS_REGION,
  logger: console,
  maxAttempts: 2,
  requestHandler,
};
export const dynamodbClient = new DynamoDB(options);
// Pass the dynamodb instance with configured options to document client
export const ddbDocumentClient = DynamoDBDocument.from(dynamodbClient);
```

Elsewhere in code that is performing many DocumentClient.update operations, the update duration is logged.  When the service is heavily loaded, DynamoDb requests can succeed but after taking in excess of the configured timeout, or simply take so long that the lambda times out.  The configured timeout is completely ignored.

```
  while (waited < MAX_BACKOFF_MS) {
    try {
      waited = await randomWait({ retry, batchSize });

      const startTime = Date.now();
      const { $metadata } = await ddbDocumentClient.update(updateParams);
      const { requestId, totalRetryDelay, attempts } = $metadata;
      const updateDuration = Date.now() - startTime;

      if (updateDuration > 30000 || retry > 0) {
        // requestId is the underlying dynamo db
        const details = { requestId, updateDuration, totalRetryDelay, attempts, retry };
        log('info', { ...details, ...updateParams }, 'Retry or Excessive duration');
      }

      const debugInfo = { requestId, waited, updateDuration, attempts, retry, ...updateParams };
      log('debug', { ...debugInfo, functionName }, 'Done');
      return true;
    } catch (e) {
      // error handling if an error is ever raised (but none are raised)
    }

    // Must be a retryable error
    retry += 1;
    log('info', { updateParams, retry, previousWait: waited, functionName }, 'Will retry');
  }

  log('error', { ...updateParams, retry, waited, MAX_BACKOFF_MS, functionName }, 'Max reached');
  return false;
};

#### Observed behavior
Requests to `ddbDocumentClient.update()` routinely exceed the set timeout.  An example log entry is shown:
A large number of successful requests exceed the configured 30000 millisec timeout - in this case succeeding
after 67719 milliseconds (see the logged `updateDuration`)

```
attempts | 1
-- | --
awsRequestId | 12df016b-adec-40ad-9c01-c910a902a302
ConditionExpression | attribute_exists(id)
ExpressionAttributeValues.:val | 1630942959566
Key.id | Az5OnOlbXJboLn24TGKIatw61Z28Rr9eTtSOTgx1up
Key.private_partition_key | 364\|Az
lvl | INFO
msg | OneUp Retry or Excessive duration
requestId | F00R91NBH4S26E7F0CHAOVGFQJVV4KQNSO5AEMVJF66Q9ASUAAJG
retry | 0
TableName | fhir_r4_encounter
time | 2021-09-06T15:43:57.427Z
totalRetryDelay | 0
updateDuration | 67719
UpdateExpression | set private_synch_epoch = :val
```

#### Expected behavior
A TimeoutError is raised after the specified time - (30000 millisec in this example)

#### Screenshots
If applicable, add screenshots to help explain your problem.

## Additional context
Identical behavior is observed doing the equivalent thing using the V2 API.

**Comment by AllanZhengYP** [comment]
Hi @marvin1up 

Here the `socketTimeout` config means the socket will be closed after being idled for the supplied timeout. That is to say, the socket is only closed when there's no more request is actively using the socket. Whereas the `connectionTimeout` config means means the request handler will throw if the request spent too long before establishing a connection. 

In your case, the long duration is mostlikely caused by connection pooling. In heavy load situation, the requests are made but they wait in the connection pool untill a socket is available. But default, the max socket set by SDK is 50. So there are at most 50 concurrent connections. To mitigate the issue you can set a higher socket number like 200:

```TypeScript
import { Agent } from 'https';

const requestHandler = new NodeHttpHandler({
  connectionTimeout: 30000,
  socketTimeout: 30000,
  httpsAgent: new Agent({maxSockets: 200})
});

const options = {
  region: AWS_REGION,
  logger: console,
  maxAttempts: 2,
  requestHandler,
};
export const dynamodbClient = new DynamoDB(options);
```

**Comment by marvin1up** [comment]
Hey, that is very cool guidance.  Thanks so much.   I separately DID diagnose that the timeout was honored when it was set short, and the long delay was some other issue.  You point out the other issue (about the number of concurrent sockets).
