### ISSUE TITLE
s3 Client Depends on Unavailable 3.30.0 sts Client

### ISSUE THREAD

**Issue by SkySceneRock** [aws/aws-sdk-js-v3#2766]
When trying to run `npm install @aws-sdk/client-s3` for the latest version of @aws-sdk/client-s3 package. (3.30.0), the following error happens:  `npm ERR! code ETARGET
npm ERR! notarget No matching version found for @aws-sdk/client-sts@3.30.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.`

**Comment by AllanZhengYP** [comment]
Hi @SkySceneRock, I cannot reproduce the issue. The version in question does exist on NPM: https://www.npmjs.com/package/@aws-sdk/client-sts

Can you provide more information? like the tool and the command you are using.

**Comment by ajredniwja** [comment]
Was able to successfully install @aws-sdk/client-s3@3.30.0

**Comment by SkySceneRock** [comment]
Just tried it again this morning, and I was able to successfully install it with `npm install aws-sdk/client-s3`. Version number was 3.30.0 was successfully installed without `aws-sdk/client-sts`. Looks like it has been fixed since I originally reported it.

**Comment by AllanZhengYP** [comment]
@SkySceneRock Glad to hear that's fixed!
