### ISSUE TITLE
SQS client v3 `send` command fails with `TypeError: Cannot read property 'Code' of undefined`

### ISSUE THREAD

**Issue by dmolenaars** [aws/aws-sdk-js-v3#2777]
## Describe the bug
An uncaught TypeError in `loadQueryErrorCode` in `client-sqs/protocols/Aws_query.ts` causes the SQS client `send` command to fail when the `data` parameter of the `loadQueryErrorCode` function does not contain an `Error` object.

#### SDK version number
`@aws-sdk/client-sqs@3.20.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
`v14.6.0`

## Steps to reproduce
```typescript
import { SendMessageBatchCommand, SendMessageBatchCommandInput, SQSClient } from '@aws-sdk/client-sqs';

const sqsClient = new SQSClient({ region: process.env.AWS_REGION });

// example array, would normally be an array of JSON objects that are stringified with a max length of 10
const stringArray: string[] = ['a', 'b', 'c'];

// create a batch command input with a placeholder url and an array of entries
const commandInput: SendMessageBatchCommandInput = {
    QueueUrl: 'placeholder url',
    Entries: stringArray.map((item, index) => ({
      Id: `entryid-${index}`,
      MessageBody: item,
    })),
  }

const command = new SendMessageBatchCommand(commandInput);

await sqsClient.send(command);
```
#### Observed behavior
Under a consistent load, the `send` command failed once with the following error:
`TypeError: Cannot read property 'Code' of undefined`
We have not seen this error occur again.

#### Expected behavior
The `send` command sends the messages to the designated SQS queue when the request succeeds, or in case the request did not succeed, it returns the status code and ideally the reason why the request has failed.

**Comment by ajredniwja** [comment]
Hey @dmolenaars thanks for opening this issue, I was not able to reproduce the issue with the latest version of the package. Can you please try using the latest package?  `@aws-sdk/client-sqs@3.31.0`
