### ISSUE TITLE
AccessDenied errors don't tell you what permission is lacked

### ISSUE THREAD

**Issue by revmischa** [aws/aws-sdk-js-v3#2778]
## Describe the bug
When I get an AccessDenied error I'd really like to know what API call failed so I can fix my IAM policy.

In this instance I was able to guess it from the name of the function that failed but this is hardly developer-friendly or foolproof.

```
{
    "errorType": "AccessDenied",
    "errorMessage": "Access Denied",
    "Code": "AccessDenied",
    "name": "AccessDenied",
    "$fault": "client",
    "$metadata": {
        "httpStatusCode": 403,
        "attempts": 1,
        "totalRetryDelay": 0
    },
    "stack": [
        "AccessDenied: Access Denied",
        "    at null.deserializeAws_restXmlPutObjectTaggingCommandError (/node_modules/@aws-sdk/client-s3/protocols/Aws_restXml.ts:9518:39)",
        "    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
        "    at null.<anonymous> (/node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/middleware-serde/src/deserializerMiddleware.ts:20:18)",
        "    at null.<anonymous> (/node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/middleware-signing/src/middleware.ts:26:22)",
        "    at tye.retry (/node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/middleware-retry/src/defaultStrategy.ts:125:38)",
        "    at null.<anonymous> (/node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/middleware-logger/src/loggerMiddleware.ts:21:20)",
        "    at KCe.__doMultipartUpload (/node_modules/@aws-sdk/lib-storage/src/Upload.ts:220:7)",
        "    at KCe.done (/node_modules/@aws-sdk/lib-storage/src/Upload.ts:88:12)",
        "    at null.saveAvatar (/foo/bar.ts:87:3)",
    ]
}
```

#### SDK version number
`3.29.0` 

#### Is the issue in the browser/Node.js/ReactNative?
Node

#### Details of the browser/Node.js/ReactNative version
Node 14

## Steps to reproduce
Please share code or minimal repo, and steps to reproduce the behavior.

#### Observed behavior
A clear and concise description of what happens.

#### Expected behavior
A clear and concise description of what you were expecting to happen.

**Comment by ajredniwja** [comment]
@revmischa Hey, thank you for bringing this up, unfortunately the error message wont have the call that failed, while this is not necessarily a bug but a feature request. Marking it as one, will discuss with the team for the priority.
