### ISSUE TITLE
This is likely not portable. A type annotation is necessary. '@aws-sdk/client-s3/node_modules/@aws-sdk/protocol-http'

### ISSUE THREAD

**Issue by avromanov2009** [aws/aws-sdk-js-v3#2780]
## Describe the bug
When I try to build a project, it gives error message when typescript can't emit declarations for internal code.
(https://www.typescriptlang.org/tsconfig#stripInternal)

#### SDK version number
`@aws-sdk/client-s3@3.30.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Node v14.17.0

## Steps to reproduce
npm run build
NEST.JS v7.6.0

#### Observed behavior
When I try to build a project, it gives this message.

#### Expected behavior
Should build project without any errors.

#### Screenshots
![image](https://user-images.githubusercontent.com/1846296/133099194-be98f831-aec6-4ba2-a36b-7849eed681e3.png)
![image](https://user-images.githubusercontent.com/1846296/133099489-2ba7c421-0a89-4975-bfa6-3b2d0e735358.png)
![image](https://user-images.githubusercontent.com/1846296/133099585-f2edeca9-2f9a-4040-8593-5849f50f82b2.png)

**Comment by vudh1** [comment]
Hi @avromanov2009, thanks for reaching out. I'm not able to reproduce this problem. Can you send a sample of reproducible code?
