### ISSUE TITLE
How to authenticate a user using @aws-sdk/client-cognito-identity-provider ?

### ISSUE THREAD

**Issue by raja-vcomply** [aws/aws-sdk-js-v3#2784]
**User Authentication**
I am trying to find the details of how can I authenticate users using @aws-sdk/client-cognito-identity-provider 

**Tried to post the problem to StackOverflow but got no answer**
So finally I thought it would be best to ask here

Anyone here please help with the documentation

**Comment by raja-vcomply** [comment]
@audionerd @trevorrowe @vvo @voidus @

**Comment by ajredniwja** [comment]
Hey @raja-vcomply ,thanks for opening the issue, you can go through the dev guide found [here](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/loading-browser-credentials-cognito.html) which should solve your problem, please reach out if you have any other questions.
