### ISSUE TITLE
Client fails to send put command when key has a forward slash

### ISSUE THREAD

**Issue by vasco-santos** [aws/aws-sdk-js-v3#2808]
## Describe the bug

When using the client to send a PutCommand with a key containing one or more forward slashes it fails with:
```
TypeError: Cannot read properties of undefined (reading '#text')
Aws_restXml.ts:14762
```

However, according to the [documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html), a forward slash is a valid character to use for a key.

It seems related to how the command is serialized 

## Your environment
Mac OS

#### SDK version number
`@aws-sdk/client-s3@3.28.0`

#### Is the issue in the browser/Node.js/ReactNative?
Service worker + Cloudflare Worker

#### Details of the browser/Node.js/ReactNative version
Chromium / Safari service worker using https://github.com/hugomrdias/playwright-test

## Steps to reproduce
Please share code or minimal repo, and steps to reproduce the behavior.

```js
const s3Client = new S3Client(/** params */)
const commandParams = {
    Bucket: s3BucketName,
    Key: 'foo/bar',
    Body: blob
  }
await s3Client.send(new PutObjectCommand(commandParams))
```

#### Observed behavior

Send throws
```
TypeError: Cannot read properties of undefined (reading '#text')
Aws_restXml.ts:14762
```

#### Expected behavior
S3 client handles keys with slashes as documented in S3 support

#### Screenshots

![image](https://user-images.githubusercontent.com/7295071/134205787-d1a487ab-3a76-4b7c-a520-d81acd189929.png)

**Comment by ajredniwja** [comment]
Hey @vasco-santos thanks for opening this issue, was not able to reproduce the same with the latest version of the SDK. 
Can you please try to upgrade the version and see if that solves the issue for you?
