### ISSUE TITLE
Waiters should return result of last command

### ISSUE THREAD

**Issue by samchungy** [aws/aws-sdk-js-v3#2809]
### Is your feature request related to a problem? Please describe.
I am using the `waitUntilSpotInstanceRequestFulfilled` function but it's pointless if it does not return me the last call result so I can obtain the instance ID of the spot instance.

In general, why don't the waiters return the payload of the last operation? I feel this would be very handy.

### Describe the solution you'd like
The waiter should return the final result of the command it uses to check the status of what we are awaiting.

### Describe alternatives you've considered
- Writing my own waiter
- Calling the same thing the waiter called again to retrieve the result..

**Comment by michaelwittig** [comment]
I'm not sure about the alternative "Calling the same thing the waiter called again to retrieve the result."
The APIs are eventual consistent. There is no guarantee that your read returns the same data as the one performed inside the waiter?

**Comment by samchungy** [comment]
> I'm not sure about the alternative "Calling the same thing the waiter called again to retrieve the result." The APIs are eventual consistent. There is no guarantee that your read returns the same data as the one performed inside the waiter?

Indeed, hence the request for this 😅

**Comment by michaelwittig** [comment]
@samchungy I agree. I added my 👍 Unfortunatelly, not many people seem to be using waiters ... :)
