### ISSUE TITLE
Throttling Exception - Slow down; sudden increase in rate of requests...occurs on loop

### ISSUE THREAD

**Issue by leverarch-app** [aws/aws-sdk-js-v3#2815]
## Describe the bug
Performing analyzeDocument in a loop throws throttling errors

`{
"errorType": "ThrottlingException",
"errorMessage": "Slow down; sudden increase in rate of requests. Please ramp up your traffic gradually.",
"code": "ThrottlingException",
"message": "Slow down; sudden increase in rate of requests. Please ramp up your traffic gradually.",
"time": "2021-09-21T20:16:05.820Z",
"requestId": "xxx",
"statusCode": 400,
"retryable": true,
"stack": [
    "ThrottlingException: Slow down; sudden increase in rate of requests. Please ramp up your traffic gradually.",
    "    at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:52:27)",
    "    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
    "    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
    "    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:688:14)",
    "    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)",
    "    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)",
    "    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10",
    "    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)",
    "    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:690:12)",
    "    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"
]
}`

## Your environment
Running as a Lambda function

#### SDK version number
@aws-sdk/client-textract 3.330

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
14.30, also occurs in Lambda

## Steps to reproduce
```js
const array = await Promise.all(

  images.map(async (image, key) => {
    // Create Buffer
    const buffer = fs.readFileSync(image);

    // Extract
    const results = textract.analyzeDocument({
      Document: {
        Bytes: buffer,
      },
      FeatureTypes: ["FORMS"],
    });

    const data = await results.promise();

    console.log("...page " + key + " done");

    await unlinkAsync(image);

    return data;
  })
);
```

#### Observed behavior
Error posted above

#### Expected behavior
Analyze document to occur for each loop iteration

#### Screenshots
n/a
## Additional context
n/a

**Comment by vudh1** [comment]
Hi @leverarch-app, I am not able to reproduce using your code. Here is a [sample](https://docs.aws.amazon.com/textract/latest/dg/analyzing-document-text.html#node.js) of how to use Textract in Node.js. Please comment if this is not helpful, and send a reproducible code so we can investigate more.
