### ISSUE TITLE
@aws-sdk/client-cognito-identity: SerializationException: Start of list found where not expected

### ISSUE THREAD

**Issue by woodcockjosh** [aws/aws-sdk-js-v3#2831]
## Describe the bug
Principal tags must be singular when developer token is created but the principal tags inside the cognito token are plural when the token is actually created. 

If you try to pass an array as a principal tag it breaks. So either plural principal tags should be allowed when creaating the token or singular principal tag should exist when the token is created. 

## Your environment
nodejs 14

#### SDK version number
`@aws-sdk/client-cognito-identity@3.31.0`

#### Is the issue in the browser/Node.js/ReactNative?
No

#### Details of the browser/Node.js/ReactNative version
N/A

## Steps to reproduce
```typescript
    const command = new GetOpenIdTokenForDeveloperIdentityCommand({
      IdentityPoolId: 'poolId',
      PrincipalTags: {
          pluralTags: ['helloWorld1', 'helloWorld2']
      },
      Logins: {
        [input.developerProviderName]: 'abcdefg1234567',
      },
    });

    const client: CognitoIdentityClient = new CognitoIdentityClient({
      region: 'us-east-1',
    });

    const openIdTokenResponse: GetOpenIdTokenForDeveloperIdentityResponse = await client.send(
      command,
    );
```

#### Observed behavior
When an array of principal tag values is provided
```text
SerializationException: Start of list found where not expected
at deserializeAws_json1_1GetOpenIdTokenForDeveloperIdentityCommandError (/var/app/node_modules/@aws-sdk/client-cognito-identity/protocols/Aws_json1_1.ts:1366:39)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at /var/app/node_modules/@aws-sdk/middleware-serde/src/deserializerMiddleware.ts:18:20
at /var/app/node_modules/@aws-sdk/middleware-signing/src/middleware.ts:24:22
at StandardRetryStrategy.retry (/var/app/node_modules/@aws-sdk/middleware-retry/src/StandardRetryStrategy.ts:83:38)
at /var/app/node_modules/@aws-sdk/middleware-logger/src/loggerMiddleware.ts:22:22 +82ms
```

When a single principal tag value is provided like this

```typescript
    const command = new GetOpenIdTokenForDeveloperIdentityCommand({
      IdentityPoolId: 'poolId',
      PrincipalTags: {
          singularTag: 'helloWorld'
      },
      Logins: {
        [input.developerProviderName]: 'abcdefg1234567',
      },
    });

    const client: CognitoIdentityClient = new CognitoIdentityClient({
      region: 'us-east-1',
    });

    const openIdTokenResponse: GetOpenIdTokenForDeveloperIdentityResponse = await client.send(
      command,
    );
```

 token is created with multiple values like this

```json
  "https://aws.amazon.com/tags": {
    "principal_tags": {
      "singularTag": [
          "helloWorld"
      ]
    }
  }
```

#### Expected behavior
It should generate an IDP token with a property in the token body like this: 
```json
  "https://aws.amazon.com/tags": {
    "principal_tags": {
      "pluralTags": [
        "helloWorld1",
        "helloWorld2"
      ]
    }
  }
```

or 

```json
  "https://aws.amazon.com/tags": {
    "principal_tags": {
      "singularTag": "helloWorld"
    }
  },
```

#### Screenshots
N/A

## Additional context
N/A

**Comment by kuhe** [comment]
hey @woodcockjosh,

As far as I can tell, the SDK is adhering to the service API structure of requiring that PrincipalTags has singular string values, [link](https://docs.aws.amazon.com/cognitoidentity/latest/APIReference/API_GetOpenIdTokenForDeveloperIdentity.html). 

When you say "token is created with multiple values like this", what kind of request or response contains this structure?

```json
  "https://aws.amazon.com/tags": {
    "principal_tags": {
      "singularTag": [
          "helloWorld"
      ]
    }
  }
```

**Comment by woodcockjosh** [comment]
The structure exists in the cognito token. We can say that the principal tags are supposed to have singular values but then why do they become an array in the token?

**Comment by kuhe** [comment]
I see what you mean now, after decoding the token. There might be a service API design reason for this, if I'm able to find out I'll update here.

**Comment by kuhe** [comment]
I spoke to a Cognito developer and they said it was a limitation of the current API and will log the issue to investigate.
