### ISSUE TITLE
Unable to invoke Lambda functions that belong to regions other than us-east-1 if specify an endpoint

### ISSUE THREAD

**Issue by esperecyan** [aws/aws-sdk-js-v3#2833]
## Describe the bug
Unable to invoke Lambda functions that belong to regions other than us-east-1 using InvokeCommand.

The problem does not occur when calling from the AWS CLI.

#### SDK version number
`@aws-sdk/client-lambda@3.34.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v16.10.0

#### Others
- Docker Desktop 4.0.1
- Windows 10 2004 (64bit)
- aws-cli/2.0.55 Python/3.7.7 Windows/10 exe/AMD64

## Steps to reproduce
1. Clone https://github.com/esperecyan/test-aws-sdk
2. Run `npm install`
3. Run `npm run dev`
4. Open http://localhost:8081/us-east-1 to run the function in the us-east-1 region, and it will run successfully.
5. Open http://localhost:8081/ap-northeast-1 and run the function for the ap-northeast-1 region, you get ResourceNotFoundException.

#### Observed behavior
If I open http://localhost:8081/ap-northeast-1, I see ResourceNotFoundException and I see the following exception in the Docker console.

> ResourceNotFoundException: ResourceNotFoundException
> &nbsp;&nbsp;&nbsp;&nbsp;at deserializeAws_restJson1InvokeCommandError (/usr/src/app/node_modules/@aws-sdk/client-lambda/dist/cjs/protocols/Aws_restJson1.js:5106:41)
> &nbsp;&nbsp;&nbsp;&nbsp;at processTicksAndRejections (node:internal/process/task_queues:96:5)
> &nbsp;&nbsp;&nbsp;&nbsp;at async /usr/src/app/node_modules/@aws-sdk/middleware-serde/dist/cjs/deserializerMiddleware.js:6:20
> &nbsp;&nbsp;&nbsp;&nbsp;at async /usr/src/app/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:11:20
> &nbsp;&nbsp;&nbsp;&nbsp;at async StandardRetryStrategy.retry (/usr/src/app/node_modules/@aws-sdk/middleware-retry/dist/cjs/StandardRetryStrategy.js:51:46)
> &nbsp;&nbsp;&nbsp;&nbsp;at async /usr/src/app/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22
> &nbsp;&nbsp;&nbsp;&nbsp;at async Module.invokeLambda (file:///usr/src/app/nodejs/test.mjs?0.9203241069953989:8:19)
> &nbsp;&nbsp;&nbsp;&nbsp;at async file:///usr/src/app/nodejs/index.mjs:7:10 {
> &nbsp;&nbsp;'$fault': 'client',
> &nbsp;&nbsp;'$metadata': {
> &nbsp;&nbsp;&nbsp;&nbsp;httpStatusCode: 404,
> &nbsp;&nbsp;&nbsp;&nbsp;requestId: undefined,
> &nbsp;&nbsp;&nbsp;&nbsp;extendedRequestId: undefined,
> &nbsp;&nbsp;&nbsp;&nbsp;cfId: undefined,
> &nbsp;&nbsp;&nbsp;&nbsp;attempts: 1,
> &nbsp;&nbsp;&nbsp;&nbsp;totalRetryDelay: 0
> &nbsp;&nbsp;},
> &nbsp;&nbsp;Type: 'User'
> }

#### Expected behavior
If I open http://localhost:8081/ap-northeast-1, I see `{"message":"Hello World"}`.

## Additional context
The problem does not occur when calling from the AWS CLI.

- If you run `aws lambda invoke --function-name test-aws-sdk-us-east-1-echo --payload eyAibWVzc2FnZSI6ICJIZWxsbyBXb3JsZCIgfQ== --region us-east-1 --endpoint http://localhost:4566 output.txt`, it will be run successfully.
- If you run `aws lambda invoke --function-name test-aws-sdk-ap-northeast-1-echo --payload eyAibWVzc2FnZSI6ICJIZWxsbyBXb3JsZCIgfQ== --region ap-northeast-1 --endpoint http://localhost:4566 output.txt`, it will be run also successfully.

**Comment by vudh1** [comment]
Hi @esperecyan, I am not able to reproduce this issue. Can you check if you are still experiencing this with the latest version?

**Comment by esperecyan** [comment]
@vudh1 Thanks for the confirmation.

I re-cloned https://github.com/esperecyan/test-aws-sdk, ran `npm install` `npm install @aws-sdk/client-lambda@3.43.0` (https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.44.0) and I ran `npm run dev`.

However, accessing http://localhost:8081/us-east-1 returns `{"message":"Hello World"}`, and accessing http://localhost:8081/ap-northeast-1 returns the same as before `{"name":"ResourceNotFoundException","$fault":"client","$metadata":{"httpStatusCode":404,"attempts":1,"totalRetryDelay":0},"Type":"User"}` is returned.

My current environment, which reproduces the above results, is as follows.

- Docker Desktop 4.2.0
- Windows 10 2004 (64bit)
- package-lock.json
  https://cdn.discordapp.com/attachments/511077066628661271/917596750284472340/package-lock.json

**Comment by esperecyan** [comment]
I updated the repository and fixed the version of the Docker images.

**Comment by esperecyan** [comment]
When I created a Lambda function on AWS to ap-northeast-1 and called it from the local @aws-sdk/client-lambda without specifying an endpoint, the region specification in the LambdaClient constructor was not ignored.

It seems that a region is ignored when an endpoint is specified.

As mentioned earlier, this problem is specific to the AWS SDK, and the AWS CLI does not ignore a region even when an endpoint is specified.

**Comment by esperecyan** [comment]
It was due to the fact that the access key was empty.
I changed the `credentials` in the LambdaClient constructor from `{ accessKeyId: '', secretAccessKey: '' }` to `{ accessKeyId: 'dummy', secretAccessKey: 'dummy' }` and it now works correctly.
My apologies.
