### ISSUE TITLE
Error when PutObjectCommand executed with readStream in Body.

### ISSUE THREAD

**Issue by clement-faure** [aws/aws-sdk-js-v3#2855]
## Describe the bug
I'm not able to put object to bucket using command PutObjectCommand when using readStream in Body.

## Your environment
Next.JS / Apollo Server

#### SDK version number
"@aws-amplify/auth": "^4.3.9",
"@aws-amplify/core": "^4.3.1",
"@aws-sdk/client-cognito-identity-provider": "^3.34.0",
"@aws-sdk/client-s3": "^3.34.0",
"@aws-sdk/s3-request-presigner": "^3.34.0",

#### Is the issue in the browser/Node.js/ReactNative?
Node.JS

#### Details of the browser/Node.js/ReactNative version
"node": "^12.20.2"

## Steps to reproduce
Put file to S3 using readStream

#### Observed behavior
Error: "A header you provided implies functionality that is not implemented"
See screenshot above for full error log

#### Expected behavior
Put should work normally.

I've tried uploaded without specifying Body and folders are well created on AWS S3
I've also tried to directly save file on my server and it is working fine, so the problem doesn't come from my file which is a basic png.

#### Screenshots
<img width="504" alt="Capture d’écran 2021-10-01 à 16 44 30" src="https://user-images.githubusercontent.com/23209488/135639660-8e6b944f-876c-4637-bb0f-d045170ad87a.png">

<img width="1248" alt="Capture d’écran 2021-10-01 à 16 27 10" src="https://user-images.githubusercontent.com/23209488/135639541-5ad2ba35-7ef3-4b4f-b922-9b8acd78e11e.png">

**Comment by clement-faure** [comment]
Extra note : all works fine with aws-sdk v2 with the same logic.

<img width="527" alt="Capture d’écran 2021-10-03 à 09 34 30" src="https://user-images.githubusercontent.com/23209488/135744557-b645a3ee-51b7-4573-8cd8-846af6d94e16.png">

**Comment by samchungy** [comment]
You're comparing upload vs put here, @aws-sdk/lib-storage has the upload method

**Comment by clement-faure** [comment]
Indeed, thank you so much, i missed this module !
