### ISSUE TITLE
How to refresh credentials by using fromCognitoIdentityPool and sample code issue

### ISSUE THREAD

**Issue by dms-jeremy** [aws/aws-sdk-js-v3#2862]
## Describe the issue with documentation
Hi, 

We have two main inquiries about setting credentials by using Cognito service. 

### 1. Sample code issue
We follow this [AWS JS v3 guidance](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/loading-browser-credentials-cognito.html) to retrieve credentials by fromCognitoIdentityPool. But some code snippet of this guidance seems not correct or out of date for me. For example,

First code snippet. 
```javascript
const {fromCognitoIdentityPool} = require("@aws-sdk/credential-provider-cognito-identity");
```
However, it mentioned in [Usage](https://github.com/aws/aws-sdk-js-v3/tree/main/packages/credential-provider-cognito-identity#usage) in [credential-provider-cognito-identity package](credential-provider-cognito-identity). 
>You probably shouldn't, at least directly. Please use @aws-sdk/credential-providers instead.

Second code snippet.
```javascript
// Get the Amazon Cognito ID token for the user. 'getToken()' below.
let idToken = getToken();
let COGNITO_ID = "COGNITO_ID"; // 'COGNITO_ID' has the format 'cognito-idp.REGION.amazonaws.com/COGNITO_USER_POOL_ID'
let loginData = {
  [COGNITO_ID]: idToken,
};
const s3Client = new S3Client({
    region: REGION,
    credentials: new CognitoIdentityClient({region:REGION}),
    identityPoolId: 'IDENTITY_POOL_ID',
    logins: {
            loginData
        },
      }),
    });

// Strips the token ID from the URL after authentication.
window.getToken = function () {
  var idtoken = window.location.href;
  var idtoken1 = idtoken.split("=")[1];
  var idtoken2 = idtoken1.split("&")[0];
  var idtoken3 = idtoken2.split("&")[0];
  return idtoken3;
};
```
I don't think this code could be ran correctly, because CognitoIdentityClient does not accept identityPoolId and logins as parameters. Furthermore, using loginData in logins:{}, it was lead to error 
> TypeError: tokenOrProvider is not a function
    at /Users/xxxx/cognito-project/js-v3-version/node_modules/@aws-sdk/credential-provider-cognito-identity/dist/cjs/resolveLogins.js:11:22

This could be fixed by removing '{}' in logins as following:
`logins: loginData,`

Third code snippet
```javascript
// Import the required AWS SDK for JavaScript v3 modules.                   
const {fromCognitoIdentityPool} = require("@aws-sdk/credential-provider-cognito-identity");
const {CognitoIdentityProviderClient} = require("@aws-sdk/client-cognito-identity-provider");
// Set the default credentials.
const creds = new fromCognitoIdentityPool({
client: new CognitoIdentityClient({region: "REGION",
 IdentityPoolId: "IDENTITY_POOL_ID"
});
```
It had syntax issue for missing closed '});'

Fourth code snippet
```javascript
// Called when an identity provider has a token for a logged in user
function userLoggedIn(providerName, token) {
  creds.params.Logins = creds.params.logins || {};
  creds.params.Logins[providerName] = token;
                    
  // Expire credentials to refresh them on the next request
  creds.expired = true;
}
```
Q: Where creds came from? I can't find a way in any further clues. 

### 2. How to refresh credentials by using fromCognitoIdentityPool?
In V2 version [AWS.CognitoIdentityCredentials](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityCredentials.html), I can see there are some methods such as `refresh`, `needRefresh`. How can I refresh the credentials by newly acquired ID token from Cognito User Pool when credentials has expired? 

Thanks.

**Comment by shadow-light** [comment]
There's some mistakes in how you've copied the code from that page. Especially the second snippet which should be

```javascript
const s3Client = new S3Client({
    region: REGION,
    credentials: fromCognitoIdentityPool({
        client: new CognitoIdentityClient({region:REGION}),
        identityPoolId: 'IDENTITY_POOL_ID',
        logins: {
            // Optional tokens, used for authenticated login.
        },
    })
});
```

Note that `logins` etc are arguments for `fromCognitoIdentityPool` not `CognitoIdentityClient`, and in your case you seem to be passing them to `S3Client` by mistake?

**Comment by dms-jeremy** [comment]
Hi @shadow-light 

Thanks for your response. I should paste full snippet, so I update my original post. You can also see the second code snippet as the same as the screenshot as following. 

<img width="1007" alt="second-code-snippet" src="https://user-images.githubusercontent.com/91508905/135751057-5f3c36ac-c7f9-4f1a-854e-8b560c290d05.png">


Hence you are correct, those parameter should be in `fromCognitoIdentityPool`, instead of `CognitoIdentityClient`. But this is how they put in the page. That's what I think this document should be updated, and runnable at least.

**Comment by shadow-light** [comment]
Ah I see what you mean. I was looking at just their first snippet. Yea you're right, the rest of them look to have the mistakes you mentioned.
