### ISSUE TITLE
credential-providers FromIni specifying profile not working.

### ISSUE THREAD

**Issue by skluthe** [aws/aws-sdk-js-v3#2871]
## Describe the bug
When using fromIni even if you specify a profile it's using the default profile.

#### SDK version number
"@aws-sdk/credential-providers": "^3.34.0"

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v16.10.0

## Steps to reproduce
Create a credentials file with multiple profiles:
```ini
[default]
aws_access_key_id=test
aws_secret_access_key=invalid_key
[newprofile]
aws_access_key_id=workingid
aws_secret_access_key=workingkey
```
Then initialize an sdk client and use fromIni to try to select your new profile.
```js
import { STSClient, AssumeRoleCommand } from "@aws-sdk/client-sts"
import { fromIni } from "@aws-sdk/credential-providers"

async function stsAuthTest(){
    const stsclient = new STSClient({ region: "us-east-1" })
    const params = {
        credentials: fromIni({
            profile: 'newprofile',
            filepath: "~/.aws/credentials"
        }),
        RoleArn: "arnthatisvalidwithyourkey",
        RoleSessionName: "AssumeRoleSession1",
        DurationSeconds: 900
    }
    try {
        const data = await stsclient.send(new AssumeRoleCommand(params));
        credentials = data.Credentials
    } catch (err) {
        console.log(err)
    }
}
```

#### Observed behavior
STS will fail to get new temporary credentials and throw errors relating to invalid/missing credentials

#### Expected behavior
I would expect the correct profile to be used during the client creation when specifying a profile instead of only allowing the default.

## Additional context
Current environment is a vue 3 electron app if that changes anything.

**Comment by vudh1** [comment]
Hi @skluthe you are initializing credentials for `AssumeRoleCommand`, not `STSClient`. Please make sure to have your credentials  for STSClient:

```js
    const stsclient = new STSClient({ region: "us-east-1" , credentials: CREDENTIALS})
```
Feel free to reopen if this is not helpful.
