### ISSUE TITLE
migration guide - DynamoDB client: error narrowing behavior changed

### ISSUE THREAD

**Issue by Moarqi** [aws/aws-sdk-js-v3#2874]
## Describe the issue with documentation
Previously, you were able to narrow down the error type thrown by a DynamoDB client by comparing the errors `code` property. The error thrown by the v3 clients misses the property `code` and instead provides the same information in the property `name`. It would be very helpful if this information could be included in the [migration guide](https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md).

## Steps to reproduce
Upgrade code that uses the v2 lib and narrows down errors happening when using the DynamoDB client using the `error.code` property. In our case, we checked if `error.code === 'ConditionalCheckFailedException'`.

#### Observed behavior
Narrowing down the error does not work as `error.code` is undefined.

#### Expected behavior
Either include this to the migration guide or change the behavior accordingly.

#### Workaround/Fix
Use `error.name` instead of `error.code`.

**Comment by dibell** [comment]
+1 to changing the behavior rather than the docs. This breaks a number of libraries.
