### ISSUE TITLE
What happened to DynamoDB documentClient

### ISSUE THREAD

**Issue by cyberwombat** [aws/aws-sdk-js-v3#288]
This is more of a question than a feature request.  I am using/previewing the new AWS SDK for JavaScript - especially the DynamoDB component.   I am using it successfully except for one thing - I cannot find a trace of DocumentClient as found in v2

Is this still to come or has been replaced by something else?

**Comment by AllanFly120** [comment]
Hey @cyberwombat,

It is still to come. It is on our to-do list before we get SDK V3 out of preview.
