### ISSUE TITLE
Release a debug version of npm packages with sources and source maps

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#2895]
### Is your feature request related to a problem? Please describe.
The source code and source maps were removed in order to reduce publish/install size of AWS SDK for JavaScript (v3). The both help a subset of customers who write their server application in TypeScript and would like to debug SDK code.

* Source code was removed in https://github.com/aws/aws-sdk-js-v3/pull/2873
* Source maps were removed in https://github.com/aws/aws-sdk-js-v3/pull/2867

### Describe the solution you'd like
Re-introduce TypeScript source code and source maps in a debug version of SDK.
For example, release version "X.Y.Z-debug" which contains source code and source maps for every version "X.Y.Z" released.

This solution would be similar to https://github.com/aws/aws-sdk-js-v3/issues/2889  

### Describe alternatives you've considered
When faced with issues in their TypeScript applications, customers will have to do any of the following to unblock themselves:
* Create an issue on AWS SDK for JavaScript GitHub repo.
* Debug through JavaScript code of the SDK.

### Additional context
* Node.js started supporting source maps in [Feb 2020](https://nodejs.medium.com/source-maps-in-node-js-482872b56116).
* Idea discussed prior in another npm package https://github.com/googleapis/google-cloud-node/issues/2867#issuecomment-625568159

**Comment by moltar** [comment]
Totally agree with @trivikr here. Source maps are essential for development, debugging (using a debugger) and even production builds, if you want to get any meaningful errors reported.

Without source maps, this is what I am looking at in a debugger (just line noise):

![screenshot-20211112T122149-K39sXuG5](https://user-images.githubusercontent.com/491247/141414285-65ec3669-4fbd-4521-b631-a736d6ed16c6.png)
