### ISSUE TITLE
Dom lib required for TS to compile in Node app

### ISSUE THREAD

**Issue by mikewim** [aws/aws-sdk-js-v3#2896]
## Describe the bug
Dom lib required by typescript in order to successfully compile node app

#### SDK version number
`@aws-sdk/lib-dynamodb@3.36.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the Node.js
v12.22.4

## Steps to reproduce

- Create a fresh TS workspace
- Set minimal tsconfig.json and **do not include "dom"** in lib array
- Install @aws-sdk/lib-dynamodb@3.36.0
- `import { DynamoDBDocumentClient } from "@aws-sdk/lib-dynamodb";` into hello world file
- run `tsc` to compile project

#### Observed behavior
The source code fails to compile with error:
<img width="1414" alt="Screen Shot 2021-10-13 at 11 43 12 AM" src="https://user-images.githubusercontent.com/13955751/137167669-49b73e0b-e99a-4501-9eb5-9b763dec9dfc.png">

#### Expected behavior
lib installed into node app should not require "dom" types to compile

## Additional context
If you add "dom" to lib array in tsconfig.json, source code will compile successfully

**Comment by ibqn** [comment]
I hit this error with `@aws-sdk/util-dynamodb` package

```sh
$ yarn build
yarn run v1.22.10
$ tsc
lambda-fns/node_modules/@aws-sdk/util-dynamodb/dist-types/ts3.4/models.d.ts:12:59 - error TS2304: Cannot find name 'Blob'.
12 export declare type NativeAttributeBinary = ArrayBuffer | Blob | Buffer | DataView | File | Int8Array | Uint8Array | Uint8ClampedArray | Int16Array | Uint16Array | Int32Array | Uint32Array | Float32Array | Float64Array | BigInt64Array | BigUint64Array;
                                                             ~~~~

lambda-fns/node_modules/@aws-sdk/util-dynamodb/dist-types/ts3.4/models.d.ts:12:86 - error TS2304: Cannot find name 'File'.
12 export declare type NativeAttributeBinary = ArrayBuffer | Blob | Buffer | DataView | File | Int8Array | Uint8Array | Uint8ClampedArray | Int16Array | Uint16Array | Int32Array | Uint32Array | Float32Array | Float64Array | BigInt64Array | BigUint64Array;
                                                                                        ~~~~


Found 2 errors.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jfirebaugh** [comment]
For discussions of how this might be fixed, see https://stackoverflow.com/questions/65848540 and https://github.com/microsoft/TypeScript/issues/31894.

**Comment by thw0rted** [comment]
Sadly I think the most common solution you'll find in the wild is people adding a triple-slash reference to DOM types, which, yes, pollutes the global namespace of anyone who includes your library with all the DOM types.

You might also be interested in following https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1207 which, if implemented, could allow you to import individual types from the DOM without having them exist in global scope.
