### ISSUE TITLE
Misleading error message - Cannot read property 'byteLength' of undefined

### ISSUE THREAD

**Issue by ameotoko** [aws/aws-sdk-js-v3#2898]
## Describe the bug
The exception `Cannot read property 'byteLength' of undefined` is thrown by a client instance in many cases, but, as pointed out in https://github.com/aws/aws-sdk-js-v3/issues/2411#issuecomment-864127937, the problem might be, that keys in the `credentials` object are spelled in PascalCase, instead of camelCase.

I just had the same problem, and this was indeed what caused it. What makes it worse is the fact, that in the [SDK Reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/modules/credentials.html), lower-case properties marked as `readonly`, so you would never think to dig in that direction.

#### SDK version number
`@aws-sdk/client-s3@v3`, `@aws-sdk/lib-storage@v3`

#### Is the issue in the browser/Node.js/ReactNative?
Browser

**Comment by ajredniwja** [comment]
Thanks for bringing this up, a better error message should be populated. Will take it to the team to decide the priority for this.

**Comment by evanottinger** [comment]
Same issue, regardless of if PascalCase or camelCase notation is used.

```
const credentials = {
    SessionToken: process.env.AWS_SESSION_TOKEN
  }

  const client = new CloudFormationClient({
    credentials,
    region: 'us-east-2',
  });
```

**Comment by AllanZhengYP** [comment]
Removing the needs-review because we know it requires a better error message. But it's not blocking customer from making request to AWS services. We will implement a fix soon.
