### ISSUE TITLE
A Node.js application written in ESM uses CommonJS distribution of the SDK

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#2900]
### Is your feature request related to a problem? Please describe.
A Node.js application written in ESM uses CommonJS distribution of the SDK.

Example code:
```js
// index.mjs
import { DynamoDB } from "@aws-sdk/client-dynamodb";

const client = new DynamoDB({});
await client.listTables({});
```

* In VSCode, add a breakpoint on the line which calls listTables.
* Click on "Run and Debug" in the Debugging View to start debugging.
* The debug session will break at listTables.
* Click on "Step Into" debug action.
* Note that debug session steps into `node_modules/@aws-sdk/property-provider/dist-cjs/chain.js`

It uses distribution in `dist-cjs` and not in `dist-es`

<details>
<summary>Screen recording</summary>

https://user-images.githubusercontent.com/16024985/137387077-75425c67-ccc1-43e9-a025-7786b248116d.mov

</details>

### Describe the solution you'd like
~~The Node.js application written in ESM should use distribution in `dist-es`~~
The Node.js application written in ESM should use folder in `dist-node-esm` (UPDATE April 2022)

### Describe alternatives you've considered
A different distribution for Node.js ESM, which can be take up while implementing Node.js specific distributions in https://github.com/aws/aws-sdk-js-v3/issues/2889 to avoid increasing install size.

### Additional context
* Debugging in VSCode https://code.visualstudio.com/docs/editor/debugging
* Conditional Exports in Node.js https://nodejs.org/api/packages.html#packages_conditional_exports

**Comment by tenjaa** [comment]
I am trying to use aws-cdk with the nodejs function. This bundles my lambda code with esbuild.
Using top-level await forces me to use ESM as target, which did not work and lead me to this issue.
Do you know a workaround for the time being?

**Comment by trivikr** [comment]
> Do you know a workaround for the time being?

@tenjaa Can you create a new [bug report](https://github.com/aws/aws-sdk-js-v3/issues/new?assignees=&labels=bug%2C+needs-triage&template=---bug-report.md&title=)?

**Comment by trivikr** [comment]
Changes needed if (and when) we publish Node.js (ESM) artifacts in future.

```
  "main": "./dist-node-cjs/index.js",
  "module": "./dist-node-esm/index.js",
  "exports": {
    "require": "./dist-node-cjs/index.js",
    "import": "./dist-node-esm/index.js",
  },
```

The naming is picked up from suggestions in https://github.com/aws/aws-sdk-js-v3/issues/3531

**Comment by simonbuchan** [comment]
Note that those recommendations are largely for the case where you have globalish state that could cause problems when there are multiple versions bundled. So far as I've seen messing around in the internals so far, this repo mostly just has caches and the like, nothing like the v2 global config.

That said, so long as you don't need to manage the wrappers, that should work fine. I've had lots of headaches managing multiple builds.

The real question though, is if you actually need a commonjs build at all at this point? You're either running directly in node or though a bundler, in both cases you have native ESM support in their supported versions:  node v12.22.0 stabilized esm support, and that's the oldest supported version.

**Comment by simonbuchan** [comment]
Ah, of course, you can't `require()` a module.

**Comment by skyrpex** [comment]
> Node.js official docs recommend two solutions for dual-packaging: An [ESM wrapper](https://nodejs.org/api/packages.html#approach-1-use-an-es-module-wrapper) or [Isolate State](https://nodejs.org/api/packages.html#approach-2-isolate-state).
> 
> On quick look, the ESM wrapper appears to be a better solution as:
> 
> * The install size is expected to increase just a little because of wrapper code. Emitting distinct ESM artifacts will double the install size for Node.js variant.
> * The build time will not increase significantly, as we just need to create a wrapper. There are existing community supported utilities like [gen-esm-wrapper](https://www.npmjs.com/package/gen-esm-wrapper). Generating distinct ESM artifacts will require a new run of TypeScript compiler.
> * The maintenance burden will be low in ESM wrapper solution. We don't have to manage another TSConfig/dist folder/build script.
> 
> If we decide to use ESM Wrapper, the package.json would be as follows:
> 
> ```
>   "main": "./dist-node/index.js",
>   "module": "./dist-node/index.mjs",
>   "exports": {
>     "require": "./dist-node/index.js",
>     "import": "./dist-node/index.mjs",
>   },
> ```

Yup, it's important to use either .cjs or .mjs file extensions, otherwise one of the bundles will be broken (depending on whether the library's package.json has a `"type":"module"` or not in it.

**Comment by trivikr** [comment]
Closing this in favor of https://github.com/aws/aws-sdk-js-v3/issues/3223
