### ISSUE TITLE
Cannot use DynamoDBDocument::update to append a string to a string set attribute

### ISSUE THREAD

**Issue by karlrwjohnson** [aws/aws-sdk-js-v3#2903]
## Describe the bug

Using DynamoDBDocument::update to add a string to a string set attribute fails (in an unexpected way) when you use  `AttributeUpdates`. It fails with the message "Only DELETE action is allowed when no attribute value is specified", as if no value was passed at all, when in reality I'm passing a `Set` instance.

I believe it has something to do with how `Set`s are marshaled between lib-dynamo-db and client/dynamodb.

(On the other hand, I can use `UpdateExpression` and `ExpressionAttributeValues: { ":param": new Set(['value']) }` just fine. This only seems to affect Set values in `AttributeUpdates`.)

#### SDK version number
`@aws-sdk/client-dynamodb@^3.36.1`
`@aws-sdk/lib-dynamodb@^3.36.1`
`@aws-sdk/util-dynamodb@3.36.1`

I am also using "local DynamodDB" via Docker: `amazon/dynamodb-local:1.17.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
```
$ node --version
v14.16.0
```

## Steps to reproduce

Below is an anonymized and simplified version of the code that caused this bug.

```
import { DynamoDBDocument } from '@aws-sdk/lib-dynamodb'; // ==3.36.1
const dynamoDBDocument: DynamoDBDocument;
const TableName: string;l
const Key: string;
await dynamoDBDocument.update({
  TableName,
  Key,
  AttributeUpdates: {
    SomeStringSetColumn: {
      Action: 'ADD',
      Value: new Set(['value to append'])
    }
  }
});
```

I'm passing a `Set` instance to the `Value` attribute. I assume that's how the API is supposed to be used.

But judging by the stack trace (next section), the set is turned into `undefined` when it's marshaled and sent to `@aws-sdk/client-dynamodb`.

(When I step through it in my debugger, I find that [`marshall()`](https://github.com/aws/aws-sdk-js-v3/blob/main/packages/util-dynamodb/src/marshall.ts#L30) calls [`convertToSetAttr()`](https://github.com/aws/aws-sdk-js-v3/blob/main/packages/util-dynamodb/src/convertToAttr.ts#L20) - which returns a `{ SS: string }` - and then `marshall()` tries to extract the nonexistant `.M` from that returned value. This causes `.Value` to become `undefined` when it's marshalled.)

#### Observed behavior

When I run the above (more or less), it fails with the stack trace below. It's as if the `Set` is turned into `undefined` as it's being marshalled.

```
ValidationException: One or more parameter values were invalid: Only DELETE action is allowed when no attribute value is specified
    at deserializeAws_json1_0UpdateItemCommandError (.../node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:4014:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async .../node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:6:20
    at async .../node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
    at async StandardRetryStrategy.retry (.../node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async .../node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at async .../node_modules/@aws-sdk/lib-dynamodb/dist-cjs/commands/UpdateCommand.js:37:26
    at async addUserToGroup (file:///tmp/example.js) {
  __type: 'com.amazon.coral.validate#ValidationException',
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: '2b93758f-73f7-459f-ad62-c81c09c1aeda',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}
```

#### Expected behavior
The request should be marshaled properly.

#### Screenshots
n/a

## Additional context
n/a

**Comment by vudh1** [comment]
Hi @karlrwjohnson I am not able to reproduce your problem. Are you still experiencing this with the latest version?
