### ISSUE TITLE
client-redshift: how to query?

### ISSUE THREAD

**Issue by dougofredo** [aws/aws-sdk-js-v3#2905]
Hello,
I can't any documentation explaining how to write a query for redshiftClient. 
Can we do something like redshiftClient.send( QUERY_COMMAND(myQuery) ) ? where myQuery is a string representing a SQL query.
The only command I see using the query word is QueryParameterBag, but I doubt this is it.
Thanks for your help.

**Comment by kyeljmd** [comment]
@kherkeladze The said documentation is quite sparse. Not sure one can use it.
