### ISSUE TITLE
Error when building app using "@aws-sdk/client-route-53": "3.37.0"

### ISSUE THREAD

**Issue by VictorMorenoJimenez** [aws/aws-sdk-js-v3#2921]
## Describe the bug
Installed "@aws-sdk/client-route-53": "3.37.0" in a CDK typescript project.
Tried to execute npm run build, and got the following error:

```
> tsc

node_modules/@aws-sdk/client-route-53/dist-types/ts3.4/Route53.d.ts:97:5 - error TS1005: '}' expected.

97 
   


Found 1 error.

npm ERR! code ELIFECYCLE
npm ERR! errno 2

npm ERR! Exit status 2
npm ERR! 

```

Fixed adding closing } at the end of the file `node_modules/@aws-sdk/client-route-53/dist-types/ts3.4/Route53.d.ts`

#### SDK version number
"@aws-sdk/client-route-53": "3.37.0" 

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`

```
node -v
v14.18.1
```
```
npx: installed 1 in 2.282s

  System:
    OS: Linux 5.11 Linux Mint 20.2 (Uma)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 571.79 MB / 15.21 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.18.1 - /usr/bin/node
    npm: 6.14.15 - /usr/bin/npm
  Managers:
    Cargo: 1.55.0 - ~/.cargo/bin/cargo
    pip3: 20.0.2 - /usr/bin/pip3
  Utilities:
    Make: 4.2.1 - /usr/bin/make
    GCC: 9.3.0 - /usr/bin/gcc
    Git: 2.25.1 - /usr/bin/git
  Virtualization:
    Docker: 20.10.9 - /usr/bin/docker
  IDEs:
    Nano: 4.8 - /usr/bin/nano
    VSCode: 1.61.1 - /usr/bin/code
    Vim: 8.1 - /usr/bin/vim
  Languages:
    Bash: 5.0.17 - /usr/bin/bash
    Perl: 5.30.0 - /usr/bin/perl
    Python3: 3.8.10 - /usr/bin/python3
    Rust: 1.55.0 - /home/victor/.cargo/bin/rustc
  Browsers:
    Chrome: 94.0.4606.81
    Firefox: 93.0
```
## Steps to reproduce
Please share code or minimal repo, and steps to reproduce the behavior.

#### Observed behavior
Build returns error.

#### Expected behavior
Build without problem. Missing }.

**Comment by oscarwest** [comment]
Getting the same error with `"@aws-sdk/client-route-53": "^3.41.0",`

**Comment by fusionfoxy** [comment]
I am also seeing this error with `"@aws-sdk/client-route-53": "^3.42.0",`

**Comment by AllanZhengYP** [comment]
Hi @oscarwest @VictorMorenoJimenez 

Which TypeScript version are you using? Are you using TypeScript < 4.0? I think the error will go away if you switch to newer TypeScript version. We use a tool([downlevel-dts](https://www.npmjs.com/package/downlevel-dts)) to transpile newer TypeScript definitions syntax to older syntax. The tool could may generates invalid definitions. 

Can you share the exact `@aws-sdk/client-route-53/dist-types/ts3.4/Route53.d.ts` content where it throws? So we can have a better help you find the root cause.

/cc @ajredniwja

**Comment by VictorMorenoJimenez** [comment]
> Hi @oscarwest @VictorMorenoJimenez
> 
> Which TypeScript version are you using? Are you using TypeScript < 4.0? I think the error will go away if you switch to newer TypeScript version. We use a tool([downlevel-dts](https://www.npmjs.com/package/downlevel-dts)) to transpile newer TypeScript definitions syntax to older syntax. The tool could may generates invalid definitions.
> 
> Can you share the exact `@aws-sdk/client-route-53/dist-types/ts3.4/Route53.d.ts` content where it throws? So we can have a better help you find the root cause.
> 
> /cc @ajredniwja

node_modules/@aws-sdk/client-route-53/dist-types/ts3.4/Route53.d.ts:97:5 - error TS1005: '}' expected. That's the line with error, I'm using a Typescript version < 4

**Comment by VictorMorenoJimenez** [comment]
Error solved using a Typescript version > 4.
Regards.

**Comment by VictorMorenoJimenez** [comment]
I'm also having problems with other SDK clients with Typescript < 4, maybe it is a good idea to alert users or add that dependency in documentation. 

Regards.

**Comment by oscarwest** [comment]
Can confirm that setting typescript ^4.0.0 in package.json resolutions fixed the error

**Comment by gherlein** [comment]
node_modules/@aws-sdk/client-route-53/dist-types/ts3.4/Route53.d.ts is not complete!  

mkdir test;cd test
npm install @aws-sdk/client-route-53
cat node_modules/@aws-sdk/client-route-53/dist-types/ts3.4/Route53.d.ts

The file DOES NOT HAVE A CLOSING }

And yes, I am on typescript > 4

tsc -v
Version 4.5.4

**Comment by gherlein** [comment]
> node_modules/@aws-sdk/client-route-53/dist-types/ts3.4/Route53.d.ts is not complete!
> 
> mkdir test;cd test npm install @aws-sdk/client-route-53 cat node_modules/@aws-sdk/client-route-53/dist-types/ts3.4/Route53.d.ts

I fixed this by finding that I was using yarn, which installs it's own tsc

I was using yarn, which installs it's OWN typescript.

88665a1e55c0:/src/cdk/single-ec2-dev> tsc -v
Version 4.5.4
88665a1e55c0:/src/cdk/single-ec2-dev> yarn build
yarn run v1.22.17
$ tsc -v
Version 3.9.10

So it absolutely was the version bing different.

yarn add typescript
yarn add v1.22.17
[1/4] 🔍 Resolving packages...
[2/4] 🚚 Fetching packages...
[3/4] 🔗 Linking dependencies...

✨ Done in 3.37s.
88665a1e55c0:~/src/cdk/single-ec2-dev> yarn build
yarn run v1.22.17
$ tsc -v
Version 4.5.4
