### ISSUE TITLE
Expose type for DynamoDbItem used by marshall, unmarshall

### ISSUE THREAD

**Issue by marvin1up** [aws/aws-sdk-js-v3#2923]
### Is your feature request related to a problem? Please describe.
In this page, the call to Converter unmarshall is documented
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_util_dynamodb.html#unmarshall-1 the argument to unmarshall, `data` is documented as having type `{}`.

It actually has type `{ [key: string]: AttributeValue }`.  But no type is exported defining the type of the input, so other code has no way to use types to ensure that the correct input is being provided to `unmarshall` 

### Describe the solution you'd like
Export a type, `DynamoDBItem` defined like `{ [key: string]: AttributeValue }` which would then be the input to `unmarshall` and the return type of `marshall`.

### Describe alternatives you've considered
I am using a definition of lambda types from a 3rd party library `aws-lambda`.  But the definition there conflicts with the "real" definition, and using or creating types not maintained by the API itself is ultimately going to be wrong.

**Comment by alFReD-NSH** [comment]
Related to #2634
