### ISSUE TITLE
Model has mandatory values with allowed undefined instead of optional breaking OpenAPI spec generation

### ISSUE THREAD

**Issue by Hi-Fi** [aws/aws-sdk-js-v3#2938]
## Describe the bug
When generating API model with TSOA, generation fails as undefined is not valid value for OpenAPI (see https://github.com/lukeautry/tsoa/issues/891

#### SDK version number
`@aws-sdk/client-codebuild@3.38.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Node v16.11.0

## Steps to reproduce
Model including following (used) model:
```
import * as CodeBuild from '@aws-sdk/client-codebuild';

export interface TestOrCoverageReportResult {
  report: CodeBuild.Report;
  testCases?: CodeBuild.TestCase[];
  testCoverages?: CodeBuild.CodeCoverage[];
}
```

#### Observed behavior
TSOA throws error. There's also issue related to that in TSOA tracker (https://github.com/lukeautry/tsoa/issues/1031), but this apispec cretion worked fine with AWS-SDK v2 as model had just normal mandatory values (https://github.com/aws/aws-sdk-js/blob/af5475f66c30b32ac03882393b0508dd4fedb3e5/clients/codebuild.d.ts#L2722-L2735 vs. https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-codebuild/src/models/models_0.ts#L3594-L3612).
```
Generate routes error.
 Error: Unknown type: UndefinedKeyword
At: /workspace/release-document-service/service/node_modules/@aws-sdk/client-codebuild/dist-types/models/models_0.d.ts:3149:3149.
This was caused by 'number | undefined' 
```

#### Expected behavior
Apispec is generated successfully. If undefined is valid value, those are marked as optional in model so apispec can be generated.

**Comment by vudh1** [comment]
Hi @Hi-Fi, thank you for reaching out. Unfortunately, I am not able to reproduce the issue you addressed above with the latest version of the package. Can you try to use the latest version (v3.39.0)?

**Comment by Hi-Fi** [comment]
Sorry, example was a bit bad. Here's complete one that shows error. 

index.ts
```
import {
    Controller,
    Post,
    Route,
    SuccessResponse,
  } from '@tsoa/runtime';
import * as CodeBuild from '@aws-sdk/client-codebuild';

@Route('health')
export class ExampleController extends Controller {
    @SuccessResponse(200, 'Returns test')
    @Post()
  public async health (): Promise<CodeBuild.Report> {
    return {} as CodeBuild.Report; 
  }
}
```
tsoa.json
```
{
    "entryFile": "./index.ts",
    "noImplicitAdditionalProperties": "throw-on-extras",
    "spec": {
      "outputDirectory": "apimodel",
      "specFileBaseName": "apispec",
      "host": "example.com",
      "basePath": "/example",
      "yaml": true,
      "specVersion": 3
    }
  }
```

Those file in same directory commands that show error (run in same dir as files)
```
npm i @aws-sdk/client-codebuild
npx tsoa spec
```

As mentioned issue at TSOA side is also open, but also here as types have changed between aws-sdk v2 and v3.
