### ISSUE TITLE
Can't compile typescript with @aws-sdk/credential-provider-web-identity

### ISSUE THREAD

**Issue by chriskuech** [aws/aws-sdk-js-v3#2948]
## Describe the bug
TypeScript cannot transpile `@aws-sdk/credential-provider-web-identity` due to TS1005 and TS1160 compiler errors.

The `@aws-sdk/credential-provider-web-identity` was added transitively through `@aws-sdk/credential-provider-node`.

## Your environment
macOS

#### SDK version number
`@aws-sdk/credential-provider-web-identity@3.38.0`
`@aws-sdk/credential-provider-node@3.38.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v16.3.0

## Steps to reproduce
1. Add @aws-sdk/credential-provider-node to your project, transitively adding the offending module.
2. Configure the project for typescript compilation using the tsconfig.json below. 
3. Run `tsc`.

#### Observed behavior
The compiler throws an error:
```
node_modules/@aws-sdk/credential-provider-web-identity/dist-types/ts3.4/fromWebToken.d.ts:21:19 - error TS1005: ']' expected.

21     [K in keyof T as `${Uncapitalize<string & K>}`]: T[K];
                     ~~

node_modules/@aws-sdk/credential-provider-web-identity/dist-types/ts3.4/fromWebToken.d.ts:21:49 - error TS1005: '(' expected.

21     [K in keyof T as `${Uncapitalize<string & K>}`]: T[K];
                                                   ~

node_modules/@aws-sdk/credential-provider-web-identity/dist-types/ts3.4/fromWebToken.d.ts:31:1 - error TS1160: Unterminated template literal.

31 
   
```

#### Expected behavior
Compilation succeeds.

#### Screenshots
![image](https://user-images.githubusercontent.com/3680671/139179016-1e810323-ae0f-4e3a-a47d-611b061c1800.png)

## Additional context
tsconfig.json
```json
{
  "compilerOptions": {
    "target": "ES2018",
    "module": "commonjs",
    "lib": [
      "es2018"
    ],
    "importHelpers": true,
    "removeComments": true,
    "declaration": true,
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": false,
    "inlineSourceMap": true,
    "inlineSources": true,
    "experimentalDecorators": true,
    "strictPropertyInitialization": false,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "skipLibCheck": true,
    "noEmit": false,
    "rootDir": "src",
    "outDir": "dist"
  },
  "exclude": [
    "node_modules/*"
  ]
}
```

**Comment by koenpunt** [comment]
This is probably a Typescript version issue; what version of the typescript dependency you're using?

**Comment by halyna-MA** [comment]
@koenpunt I have the same one. "typescript": "3.9.7"

**Comment by abCods** [comment]
Facing the same issue. Using version 3.8.3 of Typescript.

**Comment by muneebsajjad-zameen** [comment]
@vudh1  any workaround for this  until it is fixed ?

**Comment by cookt** [comment]
@muneebsajjad-zameen You can apply the change in the pr above to your local node_modules. @vudh1 Since you've assigned yourself to this bug, can you take a look at the pr? @AllanZhengYP Can you do the same as you've assigned yourself to the [other bug referencing this issue](https://github.com/aws/aws-sdk-js-v3/pull/3121).

**Comment by gbvanrenswoude** [comment]
Best solution is to move to typescript@^4, if you cannot for some reason (e.g. project limitations), [lucasfloriani](https://github.com/lucasfloriani) created a nice patch in https://github.com/aws/aws-sdk-js-v3/pull/3121
