### ISSUE TITLE
Support synchronous requests

### ISSUE THREAD

**Issue by DewaldDeJager** [aws/aws-sdk-js-v3#2949]
### Is your feature request related to a problem? Please describe.
Often times an application that already exists is migrated to AWS or engineers decide to use AWS-managed services for parts of the application. A very common use-case is configuration management. Some of the most commonly used configuration mechanisms for Node.js applications are raw environment variables, raw config files, `dotenv`, `node-config` and a number of other community packages. Enterprise-grade projects will typically abstract away the source of the config and take a code-first approach so that the source of the values can be swapped out transparently and so that config values only need to be changed in a single place. An example of this is having a `config` module that exports configuration objects, as shown below:

config/index.js:
```javascript
module.exports = {
  port: process.env.PORT || 3000,
  baseUrl: process.env.BASE_URL || 'https://somedefault.com', // These values can come from any source,
  apiKey: process.env.API_KEY,
  ....
}
```

app.js
```javascript
const config = require('./config')
const express = require('express')
const app = express()
...
app.listen(config.port, () => console.log(`Listening on port ${config.port}`))
```

One thing that almost all these methods have in common are that they are synchronous. The configuration is loaded synchronously and is required before anything else can be set up. Some implementations may pull the configuration from source with every usage and some might only pull the configuration from source when the application starts up, but either way these are usually done synchronously.

If an engineer wanted start using AWS SSM Parameter Store for configuration values or AWS Secrets Manager for secrets, it would require a lot of changes to the code because the clients only support asynchronous calls. This problem is compounded when working on a project with hundreds, if not thousands, of files. This has forced engineers to become crafty and find ways to force these clients and their operations to be executed synchronously. The most common method I have seen is spawning a child process and synchronously waiting for it to complete. This is very hacky and error-prone.

### Describe the solution you'd like
The AWS SDK client should support synchronous requests out of the box, perhaps by having a `sendSync` method on the clients. An example of this would be:

```javascript
const { SSMClient, GetParameterCommand, GetParametersCommand } = require('@aws-sdk/client-ssm')
const REGION = 'eu-west-1'
const ssmClient = new SSMClient({ region: REGION })

const parameter = ssmClient.sendSync(new GetParameterCommand({
  Name: `/demo-api/dev/string`
}))

console.log(JSON.stringify(parameter))
```

With an expected output similar to:
```json
{
  "$metadata": {
    "httpStatusCode": 200,
    "requestId": "f3cf63bd-035c-4cd5-80fd-a9c2495c1f72",
    "attempts": 1,
    "totalRetryDelay": 0
  },
  "Parameter": {
    "ARN": "arn:aws:ssm:eu-west-1:XXXXXXXXXXXX:parameter/demo-api/dev/string",
    "DataType": "text",
    "LastModifiedDate": "2021-10-14T10:26:23.454Z",
    "Name": "/demo-api/dev/string",
    "Type": "String",
    "Value": "Hello world!",
    "Version": 1
  }
}
```

### Describe alternatives you've considered
1. Modifying the application code to use the asynchronous client (Lots of boilerplate and prevents transparently swapping out the configuration source)
2. Forcing the client code to execute synchronously (For example spawning a child process)

**Comment by AllanZhengYP** [comment]
Close as duplicated to https://github.com/aws/aws-sdk-js-v3/issues/2321, please comment their if you have more questions.
