### ISSUE TITLE
Missing Peer Dependency | @aws-sdk/client-s3 missing @aws-sdk/signature-v4-crt

### ISSUE THREAD

**Issue by zraineri** [aws/aws-sdk-js-v3#2960]
## Describe the bug

@aws-sdk/client-s3 is missing the dependency @aws-sdk/signature-v4-crt requested by @aws-sdk/middleware-sdk-s3

Yarn response:
`shell
➤ YN0002: │ @aws-sdk/client-s3@npm:3.39.0 doesn't provide @aws-sdk/signature-v4-crt (pa4175), requested by @aws-sdk/middleware-sdk-s3
`

#### SDK version number
@aws-sdk/client-s3@npm:3.39.0

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v16.11.1

## Steps to reproduce
Run an install with yarm

## Also Referenced

It's been referenced elsewhere but was closed without response

https://github.com/aws/aws-sdk-js-v3/issues/2806#issue-1002278203
https://github.com/aws/aws-sdk-js-v3/issues/2750#issuecomment-938530934

**Comment by francoisauclair911** [comment]
Same error using `@aws-sdk/client-ssm`

**Comment by ajredniwja** [comment]
Closing this issue and tracking it with https://github.com/aws/aws-sdk-js-v3/issues/2822. Please feel free to add comments in that if you have any other concerns. Thankyou
