### ISSUE TITLE
Failed waiter should return the last API call response

### ISSUE THREAD

**Issue by AllanZhengYP** [aws/aws-sdk-js-v3#2964]
### Is your feature request related to a problem? Please describe.
When working on https://github.com/aws/aws-sdk-js-v3/pull/2944, I find currently if a waiter is in the `FAILED` state, the users do not have access to the underlying API call the detected the failed state, hense they cannot recover from it. For example: when using the CloudFormation `waitUntilChangeSetCreateComplete ` waiter: https://github.com/aws/aws-sdk-js-v3/blob/51ebe9c24fa6753b63c772c19312af6a521b93ed/tests/e2e/ensure-test-stack.js#L41-L54

If the stack deployment doesn't generate a change set, the waiter will in FAILED state, which is expected. The user need to detect if the FAILED state is caused by no changeset generated, if so, they can simply omit it. 

### Describe the solution you'd like
The waiter should expose the last API call response in the thrown error of the the waiter.

### Describe alternatives you've considered
Update the CloudFormation waiter model to not fail if there's no changeset generated.

**Comment by samchungy** [comment]
Could you simply make it return the whole last result please? 🙏 

https://github.com/aws/aws-sdk-js-v3/issues/2809
