### ISSUE TITLE
client-iam: GetAccountAuthorizationDetailsCommand: UserPolicyList in UserDetail unexpectedly returns undefined

### ISSUE THREAD

**Issue by ndhuutai** [aws/aws-sdk-js-v3#2975]
## Describe the bug

`UserPolicyList` in `UserDetail` namespace can return `undefined` when the doc shows only `PolicyDetail[]`
Similarly, `PermissionsBoundary` also can return `undefined` when the doc shows only `AttachedPermissionsBoundary` type.

I used `GetAccountAuthorizationDetailsCommand` 

`UserDetail` link: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-iam/modules/userdetail.html

#### SDK version number
`@aws-sdk/client-iam@3.39.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
`14.17.3`

## Steps to reproduce
Use `GetAccountAuthorizationDetailsCommand` 

`.send(new GetAccountAuthorizationDetailsCommand({}))`

#### Observed behavior
As described above. The response from using the command returned an unexpected value of `undefined` where other types are expected.

#### Expected behavior
Expected value to not be `undefined` and if there's no `UserPolicyList`, to be an empty array. Sames goes for `PermissionsBoundary`

#### Screenshots

![aws-bug](https://user-images.githubusercontent.com/30916803/139969508-e1351383-a044-4247-a213-fa0545e7bd83.png)
![aws-doc](https://user-images.githubusercontent.com/30916803/139969632-f8fc1cff-607d-47e3-a5eb-396b0c98b1cd.png)

## Additional context
N/A

**Comment by ajredniwja** [comment]
Able to reproduce it using: 
```
(async ()=> {
    const { IAMClient, GetAccountAuthorizationDetailsCommand } = require("@aws-sdk/client-iam"); // CommonJS import
    const client = new IAMClient({region: 'us-west-2'});
    const command = new GetAccountAuthorizationDetailsCommand({});
    const response = await client.send(command);
    // console.log(response)
})();
```

Since it is an optional param, I am trying to see if the SDK is actually deserializing it correctly or not, if not then it seems to be the problem with smithy code, will post updates as I move forward.
