### ISSUE TITLE
SyntaxError: invalid regexp group on older builds of Firefox (<= 77)

### ISSUE THREAD

**Issue by jamesaucode** [aws/aws-sdk-js-v3#2979]
## Describe the bug
Application that has `@aws-sdk/*` fails to run on Firefox version 77 or earlier. It throws a `SyntaxError: invalid regexp group` error on load.

#### SDK version number
```
"@aws-sdk/client-firehose": "3.36.1",
"@aws-sdk/client-kinesis": "3.36.1",
"@aws-sdk/client-personalize-events": "3.36.1",
"@aws-sdk/client-pinpoint": "3.36.1",
"@aws-sdk/util-utf8-browser": "3.36.0",
"@aws-sdk/client-cloudwatch-logs": "3.36.1",
"@aws-sdk/client-cognito-identity": "3.36.1",
"@aws-sdk/credential-provider-cognito-identity": "3.36.1",
"@aws-sdk/types": "3.36.0",
"@aws-sdk/util-hex-encoding": "3.36.0",
"@aws-sdk/client-location": "3.36.1",
"@aws-sdk/client-lex-runtime-service": "3.36.0"
"@aws-sdk/client-comprehend": "3.36.1",
"@aws-sdk/client-polly": "3.36.1",
"@aws-sdk/client-rekognition": "3.36.1",
"@aws-sdk/client-textract": "3.36.1",
"@aws-sdk/client-translate": "3.36.1",
"@aws-sdk/eventstream-marshaller": "3.36.0",
"@aws-sdk/util-utf8-node": "3.36.0",
"@aws-sdk/client-s3": "3.36.1",
"@aws-sdk/s3-request-presigner": "3.36.1",
"@aws-sdk/util-create-request": "3.36.0",
"@aws-sdk/util-format-url": "3.36.0",
```

#### Is the issue in the browser/Node.js/ReactNative?
Browser

#### Details of the browser/Node.js/ReactNative version
```
  Browsers:
    Chrome: 83.0.4103.61
    Firefox: 77.0
```
## Steps to reproduce
1. Create a new Javascript application (In our case we use CRA)
2. Add `@aws-sdk/*` package as dependency
3. Use `@aws-sdk/*` package in application code, for example `const s3Client = new S3Client(...); s3Client.send(new GetObjectCommand(...));`
4. Run application on older builds of Firefox (version 77 or earlier)

#### Observed behavior
From the console, application crashes (blank page). A `SyntaxError: invalid regexp group` error is thrown.

#### Expected behavior
Application runs normally.

## Additional context
We are upgrading amplify's `aws-sdk` versions library wide, but we encounter problems running our integration tests which uses Firefox@77.

**Comment by AllanZhengYP** [comment]
This issue is fixed in #3008
