### ISSUE TITLE
Global import Error: Cannot find module '@aws-sdk/client-ec2'

### ISSUE THREAD

**Issue by newmizanur** [aws/aws-sdk-js-v3#2991]
#### SDK version number
`@aws-sdk/client-ec2@3.39.0`

#### Error
Getting error `Error: Cannot find module '@aws-sdk/client-ec2'`

**Comment by ajredniwja** [comment]
@newmizanur can you share how you install and use the client? You can most of the times add it to your package.json or just do an `npm install @aws-sdk/client-ec2` from the same directory before using the client. I hope that solve your problems too.

**Comment by newmizanur** [comment]
@ajredniwja It's not a local(project level) install issue. If you install it globally `npm install @aws-sdk/client-ec2 -g` then import it to any project, it doesn't work. I don't want to add it as project dependencies, because I'm using it for deployment automation to get the IP list of instances. I hope, you get the answer.
