### ISSUE TITLE
SQS FIPS Endpont ENOTFOUND in GovCloud (US)

### ISSUE THREAD

**Issue by kylelaker** [aws/aws-sdk-js-v3#3000]
## Describe the bug

Using the new features in v3.40.0 to pass `useFipsEndpoint: true`, the endpoint URL for SQS (and possibly other services) in the AWS GovCloud (US) partition, and specifically in `us-gov-west-1` is invalid according to https://aws.amazon.com/compliance/fips/ and is not a resolvable hostname.

#### SDK version number
`@aws-sdk/client-sqs@3.40.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js (but likely all)

#### Details of the browser/Node.js/ReactNative version
Current Node.js version using in the Node.js 14.x Lambda runtime

## Steps to reproduce
```ts
import { SQSClient } from "@aws-sdk/client-sqs";
const sqs = SQSClient({ useFipsEndpoint: true, region: "us-gov-west-1" });
sqs.send(new SendMessageCommand({ QueueUrl: process.env.QUEUE_URL, MessageBody: JSON.stringify({ "message": "Hello world"})});
```

#### Observed behavior
The created URL is `sqs-fips.us-gov-west-1.amazonaws.com`. This results in an `ENOTFOUND` error in Lambda when trying to hit the endpoint. It is not possible to resolve `sqs-fips.us-gov-west-1.amazonaws.com`.

```
getaddrinfo ENOTFOUND sqs-fips.us-gov-west-1.amazonaws.com
```

#### Expected behavior
Per https://aws.amazon.com/compliance/fips/ the proper endpoint is `sqs.us-gov-west-1.amazonaws.com`. That host does resolve.

## Additional context
https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-sqs/src/endpoints.ts#L4 seems to be correct so I am not sure where `-fips` is getting injected. Do the "regular" `us-gov-` region endpoints need to be tagged as `fips` and `dualstack`?

**Comment by trivikr** [comment]
Verified that `sqs-fips.us-gov-west-1.amazonaws.com` is returned when `useFipsEndpoint` is set to true in `@aws-sdk/client-sqs@v3.40.0`

<details>
<summary>Code</summary>

```js
import { SQSClient } from "@aws-sdk/client-sqs"; // v3.40.0

const region = "us-gov-west-1";
const useFipsEndpoint = true;

const client = new SQSClient({ region, useFipsEndpoint });
console.log(await client.config.endpoint());

```

</details>

<details>
<summary>Output</summary>

```console
{
  hostname: 'sqs-fips.us-gov-west-1.amazonaws.com',
  port: undefined,
  protocol: 'https:',
  path: '/',
  query: undefined
}
```

</details>

**Comment by trivikr** [comment]
The hostname is `sqs-fips.us-gov-west-1.amazonaws.com` as:
* fips variant is not present in RegionHash: https://github.com/aws/aws-sdk-js-v3/blob/d7aa2c329c62a9c2957631502bfe8da7fda86a4f/clients/client-sqs/src/endpoints.ts#L38-L46
* fips variant in PartitionHash returns `sqs-fips.{region}.amazonaws.com` https://github.com/aws/aws-sdk-js-v3/blob/d7aa2c329c62a9c2957631502bfe8da7fda86a4f/clients/client-sqs/src/endpoints.ts#L164-L185

In endpoints.json, the variants are not defined for this specific case. The endpoint resolution algorithms falls back to variants defined at partition level:
* https://github.com/aws/aws-sdk-js-v3/blob/d7aa2c329c62a9c2957631502bfe8da7fda86a4f/codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/endpoints.json#L17450-L17467
* https://github.com/aws/aws-sdk-js-v3/blob/d7aa2c329c62a9c2957631502bfe8da7fda86a4f/codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/endpoints.json#L14328-L14332

Checking internally on what should be the right behavior.

**Comment by trivikr** [comment]
> Checking internally on what should be the right behavior.

Update: This bug exists in all AWS SDKs, and a service level default variant needs to be defined for SQS to not include `-fips` in FIPS endpoints in gov partition.

The AWS SDK for JavaScript (v3) will pick up the fix when endpoints.json is updated.

**Comment by kylelaker** [comment]
I'm not sure exactly when this was fixed; however, we did notice that we were able to use the `{ useFipsEndpoint: true }` at least in 3.55.0. I _think_ it was 8fa517a2c56d2f98a2e4a9c4ea6fd99b6ce61a71?

**Comment by trivikr** [comment]
The bug was fixed when endpoints.json was updated
