### ISSUE TITLE
Release scripts should update CodeGen code (if necessary)

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#302]
**Describe the bug**
* When v0.2.0 was published in commit https://github.com/aws/aws-sdk-js-v3/commit/477dc72f2196f0b9c17dc5fef86017a2d2fd4d27, it updated devDependency `@aws-sdk/client-documentation-generator` from `^0.1.0-preview.1` to `^0.1.0-preview.2`
* It didn't update CodeGen in https://github.com/aws/aws-sdk-js-v3/blob/4013705828b1081a4a05c15106f9c09d854a8eef/packages/package-generator/src/ClientModuleGenerator.ts#L273 which was fixed in #301

**To Reproduce (observed behavior)**
Run release scripts

**Expected behavior**
If release scripts are updating some package version which affects CodeGen, related code change should also be made.

**Comment by AllanFly120** [comment]
We need to fix it but maybe in the future. Currently it's not a blocker since all these codegen releted packages will be marked as preview and private forever.

**Comment by trivikr** [comment]
Closing as we switched to java codegen in `smithy-codegen`
