### ISSUE TITLE
[client-ec2] InvalidParameterValue error on calling CopySnapshotCommand

### ISSUE THREAD

**Issue by vudh1** [aws/aws-sdk-js-v3#3021]
## Describe the bug
[client-ec2] InvalidParameterValue error on calling CopySnapshotCommand

#### SDK version number
`@aws-sdk/client-ec2@3.41.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v16.6.1

## Steps to reproduce
* Create [Amazon EBS snapshot](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-creating-snapshot.html#ebs-create-snapshot).
* Run the below example code.

```js
import { EC2 } from "@aws-sdk/client-ec2"; // v3.41.0

const region = "us-west-2";
const client = new EC2({ region });

// Snapshot ID of the EBS snapshot.
const SnapshotId = "snap-09ebe438103e4fdc2";
const params = {
  SourceRegion: region,
  SourceSnapshotId: SnapshotId,
};
console.log(await client.copySnapshot(params));
```

#### Observed behavior
Following error is thrown:

```console
/Users/trivikr/workspace/test/node_modules/@aws-sdk/client-ec2/dist-cjs/protocols/Aws_ec2.js:7956
    return Promise.reject(Object.assign(new Error(message), response));
                                        ^

InvalidParameterValue: The protocol in PresignedUrl should be http or https
    at deserializeAws_ec2CopySnapshotCommandError (/Users/trivikr/workspace/test/node_modules/@aws-sdk/client-ec2/dist-cjs/protocols/Aws_ec2.js:7956:41)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /Users/trivikr/workspace/test/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:6:20
    at async /Users/trivikr/workspace/test/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
    at async StandardRetryStrategy.retry (/Users/trivikr/workspace/test/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /Users/trivikr/workspace/test/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at async file:///Users/trivikr/workspace/test/copysnapshot.v3.mjs:11:13 {
  Code: 'InvalidParameterValue',
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: '57ae2df2-26bc-4fb9-8c9b-6c2a66c7e0c9',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}
```

#### Expected behavior
It should share SnapshotId of copied snapshot in the response.

**Comment by trivikr** [comment]
The equivalent code which works in v2:

```js
import AWS from "aws-sdk"; // v1.1028.0

const region = "us-west-2";
const client = new AWS.EC2({ region });

const SnapshotId = "snap-09ebe438103e4fdc2";
const params = {
  SourceRegion: region,
  SourceSnapshotId: SnapshotId,
};
console.log(await client.copySnapshot(params).promise());
```

Output:

```console
{ SnapshotId: 'snap-0f15a2c6a4b992bdd', Tags: [] }
```

**Comment by trivikr** [comment]
This happens because presigned URL is escaped in `copySnapshotPresignedUrlMiddleware`, when service is expecting the non-escaped URL.

https://github.com/aws/aws-sdk-js-v3/blob/fff5e2a3e2f5c1e0f3b22ea1f3b6cc28cd2658f0/packages/middleware-sdk-ec2/src/index.ts#L68

Values set in `PresignedUrl` while testing:
* with escapeUri which throws error: `https%3A%2F%2Fec2.us-west-2.amazonaws.com%2F%3F...`
* without escapeUri which succeeds the call: `https://ec2.us-west-2.amazonaws.com/?...`

**Comment by trivikr** [comment]
The escapeUri call was added in https://github.com/aws/aws-sdk-js-v3/pull/773, which was released in `@aws-sdk/middleware-sdk-ec2@v1.0.0-alpha.4`

**Comment by trivikr** [comment]
The bug was fixed for `@aws-sdk/middleware-sdk-rds` in https://github.com/aws/aws-sdk-js-v3/pull/2711
However, it was not fixed in `@aws-sdk/middleware-sdk-ec2`

ToDo: Remove call to escapeUri in `middleware-sdk-ec2/src/index.ts`

**Comment by trivikr** [comment]
Fix is posted in https://github.com/aws/aws-sdk-js-v3/pull/3022
