### ISSUE TITLE
Bundle sizes are way too large

### ISSUE THREAD

**Issue by moltar** [aws/aws-sdk-js-v3#3023]
AWS SDK v3 creates bundle sizes that are way too large. We use a few clients, and it is adding 2.3MB of code (out of 3.8MB), which is ~ 60% of our total bundle size.

![screenshot-20211115T143520-APQaQm7K](https://user-images.githubusercontent.com/491247/141740533-41464450-8a05-40bb-a29f-9f6ee57754ee.png)

- Built by `esbuild`
- Generated using https://bundle-buddy.com/

At this point I don't see any reason for using the modular version when the **entire** `aws-sdk@2` is [just 2.9MB](https://bundlephobia.com/package/aws-sdk@2.1028.0) and doesn't even need to be bundled, as it is already pre-installed.

**Comment by trivikr** [comment]
> AWS SDK v3 creates bundle sizes that are way too large. We use a few clients, and it is adding 2.3MB of code (out of 3.8MB), which is ~ 60% of our total bundle size.

@moltar If you want to reduce bundle size of your app, you need to use tree shaking with bare-bones client and only import the specific commands your application is using. We've provided a summary under "Importing a service client" section of our [blog post](https://aws.amazon.com/blogs/developer/modular-packages-in-aws-sdk-for-javascript/).

Can you share bundle size comparisons between importing sub-module in v2 vs importing bare-bones clients with specific commands in v3? The [bundle buddy](https://bundle-buddy.com/) website imports entire package.

**Comment by moltar** [comment]
> you need to use tree shaking

We use `esbuild` (via AWS CDK), which [supports tree shaking](https://esbuild.github.io/api/#tree-shaking).

> with bare-bones client

I am not sure what this means.

I read the blog post and it doesn't do anything different (in v3) than what we do.

Here are all of the import statements for `@aws-sdk/*`, from all of the files, from the entire project :

```ts
import { SFN } from '@aws-sdk/client-sfn'
import { StartExecutionInput } from '@aws-sdk/client-sfn'
import { SFNClient, StartExecutionCommand } from '@aws-sdk/client-sfn'
import { SecretsManager, SecretsManagerClientConfig } from '@aws-sdk/client-secrets-manager'
import type { PutEventsRequestEntry } from '@aws-sdk/client-eventbridge'
import { SecretsManager } from '@aws-sdk/client-secrets-manager'
import { EventBridge } from '@aws-sdk/client-eventbridge'
import { SQS } from '@aws-sdk/client-sqs'
import { SSM } from '@aws-sdk/client-ssm'
import { _Object, S3 } from '@aws-sdk/client-s3'
```

But from the screenshot above, it seems like the heavy-hitters are:

 - `@aws-sdk/client-s3` (973 KB)
 - `@aws-sdk/client-eventbridge` (471 KB)
 - `@aws-sdk/client-sts` (144 KB) - this is not directly used, but it's a dependency of a dependency.
 - `@aws-sdk/client-sqs` (231 KB)

How shall we import/use these differently to take advantage of tree shaking and bare-bones clients?

> Can you share bundle size comparisons between importing sub-module in v2 vs importing bare-bones clients with specific commands in v3? 

Can't, because we don't use v2 version yet.

**Comment by moltar** [comment]
> bare-bones client

Oh, I think I know now what you mean here.

Using `S3Client` vs the entire `S3` class.

I just tried it, and it makes no difference in bundle size:

## Using `S3`

```ts
import { S3 } from '@aws-sdk/client-s3'

const s3 = new S3({})

s3.deleteObject({
  Bucket: '',
  Key: '',
})
```

Bundle size: 4563450 bytes

## Using `S3Client`

```ts
import { DeleteObjectCommand, S3Client } from '@aws-sdk/client-s3'

const s3 = new S3Client({})

s3.send(
  new DeleteObjectCommand({
    Bucket: '',
    Key: '',
  }),
)
```

Bundle size: 4563592

---

Bundling is done this way:

```sh
#!/bin/sh

set -ex

export HANDLER="$1"
export BUILD_DIR="$(mktemp -d)"

npx esbuild \
  --log-level=error \
  --color=false \
  --bundle "$HANDLER" \
  --outfile="$BUILD_DIR/index.js" \
  --metafile="$BUILD_DIR/metafile.json" \
  --sourcemap=inline \
  --platform=node
```

**Comment by moltar** [comment]
Maybe related: https://github.com/aws/aws-sdk-js-v3/issues/2056#issuecomment-792275400

**Comment by moltar** [comment]
Passing `--main-fields=module,main` to `esbuild` indeed makes a difference between two approaches.

But I don't know what are the implications of this.

**Comment by suds-sky** [comment]
@moltar, I had similar issue and by providing this flag `--sources-content=false` to reduce the source map size by not including the original source code makes the bundle significantly smaller. Can you give it a try

https://esbuild.github.io/api/#sources-content

**Comment by moltar** [comment]
@suds-sky nice one!! That's amazing.

**Comment by moltar** [comment]
@vudh1 any reason this was closed? Can you please link to a solution, if there was any? Thanks!

**Comment by vudh1** [comment]
This is mistakenly closed. Reopen for more discussion.

**Comment by danielvy** [comment]
I'm using Rollup and full treeshaking enabled and adding over 400k to the bundle size when including _@aws-sdk/client-dynamodb_ just to `GetItem` and `Query` a DynamoDB table seems way too much. And I couldn't find any way to reduce it. 

Why does it have to be so big? Why does it have to include all the code that will never be used in a browser (like getting connection config from local file system)?

**Comment by trivikr** [comment]
> Why does it have to include all the code that will never be used in a browser (like getting connection config from local file system)?

It doesn't need to be.

We've evaluating publishing environment specific artifacts in https://github.com/aws/aws-sdk-js-v3/issues/2889, starting with Node.js (commonjs). Please upvote/comment your ideas there.

**Comment by nickhudkins** [comment]
@danielvy you aren't talking about the `node_modules` size are you? You mean that when bundling, with something like webpack, or esbuild, for use in the browser, the bundle size is massive, and tree-shaking seems to not work.

@trivikr I am not sure where the disconnect is here, but this issue has been going on since the release of v3, and the fixes that continue to be prioritized are to focus on shrinking `node_modules` size (only relevant to folks in a NodeJS environment)

Can we expect any focus on browser bundle size improvements?

**Comment by trivikr** [comment]
> Can we expect any focus on browser bundle size improvements?

I'd answered this earlier, the browser bundle size have been small since the beginning.

> If you want to reduce bundle size of your app, you need to use tree shaking with bare-bones client and only import the specific commands your application is using. We've provided a summary under "Importing a service client" section of our [blog post](https://aws.amazon.com/blogs/developer/modular-packages-in-aws-sdk-for-javascript/).

This was a follow-up response from @moltar 

> Passing `--main-fields=module,main` to `esbuild` indeed makes a difference between two approaches.

Closing as the issue shared here was specific to esbuild, and workaround is available.

From [esbuild docs](https://esbuild.github.io/api/#platform):

> The [main fields](https://esbuild.github.io/api/#main-fields) setting is set to browser,module,main but with some additional special behavior. If a package supports module and main but not browser then main is used instead of module if that package is ever imported using require(). This behavior improves compatibility with CommonJS modules that export a function by assigning it to module.exports.

Please create a specific issue if any changes are needed in the SDK.
