### ISSUE TITLE
Module not found: Error: Can't resolve 'aws-crt'

### ISSUE THREAD

**Issue by alexandergaldones** [aws/aws-sdk-js-v3#3025]
After installing the most recent package, I am getting this WARNING issue 

`
WARNING in ./node_modules/@aws-sdk/util-user-agent-node/dist-es/is-crt-available.js 3:96-114
Module not found: Error: Can't resolve 'aws-crt' in '/usr/src/app/node_modules/@aws-sdk/util-user-agent-node/dist-es'

@ ./node_modules/@aws-sdk/util-user-agent-node/dist-es/index.js 5:0-52 16:23-37
 @ ./node_modules/@aws-sdk/client-dynamodb/dist-es/runtimeConfig.js 13:0-65 21:870-886
 @ ./node_modules/@aws-sdk/client-dynamodb/dist-es/DynamoDBClient.js 12:0-73 17:24-42
 @ ./node_modules/@aws-sdk/client-dynamodb/dist-es/index.js 2:0-33 2:0-33
`

I am using node version 14-alphine with my docker

And here's my installed packages in package.json

`

  "devDependencies": {
    "@aws-sdk/client-dynamodb": "^3.39.0",
    "@aws-sdk/lib-dynamodb": "^3.40.0",
    "@aws-sdk/util-dynamodb": "^3.38.0",
    ...
    ...
`

Any idea how to resolve this?

**Comment by bluepeter** [comment]
This is a known bug that AWS seems to be studiously avoiding. What's up? It's been like this for weeks for me.

**Comment by bluepeter** [comment]
See https://github.com/aws/aws-sdk-js-v3/issues/2750
