### ISSUE TITLE
client-marketplace-entitlement-service: GetEntitlementsCommand fails with TypeError: Unions must have exactly one non-null member. Keys EntitlementValueType,IntegerValue were not null

### ISSUE THREAD

**Issue by pmahoney** [aws/aws-sdk-js-v3#3029]
## Describe the bug
client-marketplace-entitlement-service: GetEntitlementsCommand fails with `TypeError: Unions must have exactly one non-null member. Keys EntitlementValueType,IntegerValue were not null`

## Your environment

- Linux
- node 14
- typescript 4.4.4

#### SDK version number
`@aws-sdk/client-marketplace-entitlement-service@3.41.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`
```
node -v
v14.18.0
```

## Steps to reproduce

Edit the code to add a real productCode and customerIdentifier, then run with node.

```js
const aws = require('@aws-sdk/client-marketplace-entitlement-service');

const marketplaceEntitlementServiceClient =
  new aws.MarketplaceEntitlementServiceClient({
    region: 'us-east-1',
  });

const productCode = '<code>';
const customerIdentifier = '<id>';
(async () => {
  try {
    const out = await marketplaceEntitlementServiceClient.send(
      new aws.GetEntitlementsCommand({
        ProductCode: productCode,
        Filter: {
          CUSTOMER_IDENTIFIER: [customerIdentifier],
        },
      }));
    console.log(out);
  } catch (e) {
    console.log(e);
  }
})();
```

#### Observed behavior
```
TypeError: Unions must have exactly one non-null member. Keys EntitlementValueType,IntegerValue were not null.
    at Object.expectUnion (/app/node_modules/@aws-sdk/client-marketplace-entitlement-service/node_modules/@aws-sdk/smithy-client/dist-cjs/parse-utils.js:122:15)
    at deserializeAws_json1_1Entitlement (/app/node_modules/@aws-sdk/client-marketplace-entitlement-service/dist-cjs/protocols/Aws_json1_1.js:152:70)
    at /app/node_modules/@aws-sdk/client-marketplace-entitlement-service/dist-cjs/protocols/Aws_json1_1.js:163:16
    at Array.map (<anonymous>)
    at deserializeAws_json1_1EntitlementList (/app/node_modules/@aws-sdk/client-marketplace-entitlement-service/dist-cjs/protocols/Aws_json1_1.js:159:10)
    at deserializeAws_json1_1GetEntitlementsResult (/app/node_modules/@aws-sdk/client-marketplace-entitlement-service/dist-cjs/protocols/Aws_json1_1.js:184:15)
    at Object.deserializeAws_json1_1GetEntitlementsCommand (/app/node_modules/@aws-sdk/client-marketplace-entitlement-service/dist-cjs/protocols/Aws_json1_1.js:22:16)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /app/node_modules/@aws-sdk/client-marketplace-entitlement-service/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:6:20
    at async /app/node_modules/@aws-sdk/client-marketplace-entitlement-service/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20 {
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}                      
```

#### Expected behavior
Return an object containing the Entitlements.

## Additional context
The commandline client `aws marketplace-entitlement get-entitlements --product-code <code> --filter CUSTOMER_IDENTIFIER=<id>` succeeds with the same AWS credentials and same product code and customer id. It prints:

```
{
    "Entitlements": [
        {
            "ProductCode": "<code>",
            "Dimension": "free_trial",
            "CustomerIdentifier": "<id>",
            "Value": {
                "IntegerValue": 1
            },
            "ExpirationDate": "2021-12-15T15:23:20.371000-06:00"
        }
    ]
}
```

By adding log output to `parse_utils.js`, I see that prior to the call to `expectUnion()`, the data is:

```
{
  CustomerIdentifier: '<id>',
  Dimension: 'free_trial',
  ExpirationDate: 1639603400.371,
  ProductCode: '<code>',
  Value: { EntitlementValueType: 'int', IntegerValue: 1 }
}
```

I also asked this on [same question on StackOverflow](https://stackoverflow.com/q/69993882/454156), but at this point it seems like a bug.

**Comment by pmahoney** [comment]
The code example works with (at least) `@aws-sdk/client-marketplace-entitlement-service@3.6.1`

**Comment by pmahoney** [comment]
I've narrowed it down:

The code example fails with `@aws-sdk/client-marketplace-entitlement-service@3.31.0`
The code example works with `@aws-sdk/client-marketplace-entitlement-service@3.30.0`

**Comment by yenfryherrerafeliz** [comment]
Hi @pmahoney, thanks for opening this issue. Are you still experiencing the same behavior with the latest version?, if so, could you please provide debug logs?. You can enable debug logs as follow:

```js
const client = new S3Client({
    region: 'REGION',
    logger: {
        debug(...content) {
             console.log('Debug: ', JSON.stringify(content))
        },
        info(...content) {
            console.log('Info: ', JSON.stringify(content))
        },
    }
})

```

Note: Please redact any sensitive information.

Thanks!

**Comment by yenfryherrerafeliz** [comment]
@pmahoney  seems like that error comes from the validation introduced with the following [PR](https://github.com/aws/aws-sdk-js-v3/pull/2746). I would like to see how the response you are getting looks like, but it may need to be logged before the deserialization process happens, otherwise the exception being thrown will prevent the response from being logged.

**Comment by yenfryherrerafeliz** [comment]
@pmahoney in case you can not generate debug logs with the code I provided to you, would it be possible for you to execute the same request with the aws cli?, so you can provide the response you are getting.

Note: Please redact any sensitive information!

Thanks!

**Comment by pj-spoelders** [comment]
This still seems to be an issue, downgrading to 3.30.0 helped for me.

**Comment by yenfryherrerafeliz** [comment]
I have reviewed the implementation and it indeed generate an exception based on the response received. I will mark this issue to be reviewed so we can address this further.

Thanks!
