### ISSUE TITLE
DynamoDB ListTableCommand results in Cannot read property 'byteLength' error

### ISSUE THREAD

**Issue by AlexWang-16** [aws/aws-sdk-js-v3#3030]
## Describe the bug
I'm following the code example from https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/dynamodb-examples-using-tables.html. When I try this code, I'm getting an error that says "Cannot read property 'byteLength' of undefined".

Does anyone know why this is happening? I double checked that my user has the correct credentials and permissions to list dynamodb tables by using AWS CLI command `aws dynamodb list-tables`. The same error is emitted for both react-js application and when I execute it as a standalone script within a new npm project.

## Your environment
macOS, node.js, aws-sdk-js-v3

#### SDK version number
`@aws-sdk/client-dynamodb@3.41.0`

#### Is the issue in the browser/Node.js/ReactNative?
Browser (ReactJS v17.0.2) and Node.js (standalone npm project)

#### Details of the browser/Node.js/ReactNative version
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`

npx envinfo output:
```
  Browsers:
    Chrome: 94.0.4606.81
    Edge: 95.0.1020.53
    Firefox: 93.0
    Safari: 15.1
```

Node JS: v12.22.6

## Steps to reproduce
Please share code or minimal repo, and steps to reproduce the behavior.

1. Create a user in your AWS account that allows you to list all dynamodb tables under eu-west-1.
2. Create. a few empty dynamodb tables.
3. Copy and paste the following code

Node JS Code:
```
// index.js
import DynamoDb from '@aws-sdk/client-dynamodb';

const { DynamoDBClient, ListTablesCommand } = DynamoDb;
const fetchData = async () => {
    const client = new DynamoDBClient({
      region: "eu-west-1",
      credentials: {    // Credentials omitted
        AccessKeyId: "XXXXXXX", 
        SecretAccessKey: "XXXXXXXX"
      }
    });
    const command = new ListTablesCommand({});
    try {
      const response = await client.send(command);
      console.log('-- response --');
      console.log(JSON.stringify(response));
    } catch (err) {
      console.log(err);
    }
};
fetchData();
```

4. Substitute your credentials under credentials object.
5. From terminal execute "node index.js"

#### Observed behavior
Observe the following error and stacktrace

```
TypeError: Cannot read property 'byteLength' of undefined
    at Object.fromArrayBuffer (/Users/wangal/dev/troubleshoot/aws-test/node_modules/@aws-sdk/util-buffer-from/dist-cjs/index.js:6:60)
    at castSourceData (/Users/wangal/dev/troubleshoot/aws-test/node_modules/@aws-sdk/hash-node/dist-cjs/index.js:29:31)
    at Hash.update (/Users/wangal/dev/troubleshoot/aws-test/node_modules/@aws-sdk/hash-node/dist-cjs/index.js:12:26)
    at hmac (/Users/wangal/dev/troubleshoot/aws-test/node_modules/@aws-sdk/signature-v4/dist-cjs/credentialDerivation.js:36:10)
    at Object.getSigningKey (/Users/wangal/dev/troubleshoot/aws-test/node_modules/@aws-sdk/signature-v4/dist-cjs/credentialDerivation.js:11:29)
    at SignatureV4.getSigningKey (/Users/wangal/dev/troubleshoot/aws-test/node_modules/@aws-sdk/signature-v4/dist-cjs/SignatureV4.js:139:39)
    at SignatureV4.signRequest (/Users/wangal/dev/troubleshoot/aws-test/node_modules/@aws-sdk/signature-v4/dist-cjs/SignatureV4.js:98:73)
    at async /Users/wangal/dev/troubleshoot/aws-test/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:13:18
    at async StandardRetryStrategy.retry (/Users/wangal/dev/troubleshoot/aws-test/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /Users/wangal/dev/troubleshoot/aws-test/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22 {
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
```

#### Expected behavior
It should provide me with a list of dynamodb table names

**Comment by ajredniwja** [comment]
Hey @AlexWang-16 thanks for bringing this up, are you able to run it in an isolated node env? I use the code given here https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/classes/listtablescommand.html and it seems to be working fine. Also would recommend not to hard code the credentials. [The doc](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/setting-credentials.html) mentions the best practices for credentials as well.
