### ISSUE TITLE
Redshift Data API errors when attempting to run CancelStatement

### ISSUE THREAD

**Issue by amardatar** [aws/aws-sdk-js-v3#3056]
## Describe the bug
The Redshift Data Client throws an error when attempting to cancel a running query. The error may be unrelated to the JS SDK itself but rather a function of the API.

The returned error on the first attempt to cancel a statement is:
```ERROR: function pg_cancel_backend(bigint) does not exist\n  Hint: No function matches the given name and argument types. You may need to add explicit type casts.```

On subsequent attempts, the error changes to:
```Could not cancel a query that is already in ABORTED state with ID: <ID>```

Checking running processes via `stv_inflight` from the cluster in question indicates the process is still running after these attempts.

#### SDK version number
`@aws-sdk/client-redshift-data@3.42.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v17.0.1

## Steps to reproduce
Sample code (requiring suitable replacements for `config` and `execConfig`):
```
const { RedshiftDataClient, ExecuteStatementCommand, CancelStatementCommand } = require("@aws-sdk/client-redshift-data");

const client = new RedshiftDataClient(config);
const execStmtCmd = new ExecuteStatementCommand(execConfig);
client.send(execStmtCmd).then(data => {
    const cancelStmtCmd = new CancelStatementCommand({ Id: data.Id });
    client.send(cancelStmtCmd).then(console.log);
});
```

#### Observed behavior
A client error is returned: `ValidationException: ERROR: function pg_cancel_backend(bigint) does not exist
  Hint: No function matches the given name and argument types. You may need to add explicit type casts.`

#### Expected behavior
The statement should be successfully cancelled.

#### Screenshots
N/A

## Additional context
Attempting to run `select pg_cancel_backend(<process id>)` succeeds; attempting to run `select pg_cancel_backend(<process id>::bigint)` fails.

**Comment by vudh1** [comment]
Hi @amardatar thanks for reaching out. I am not able to reproduce your problem. Currently, I am using v3.44.0 so can you try to see if you still experience this with the latest version of SDK? Here is the code that I used that successfully runs both `ExecuteStatementCommand` and `CancelStatementCommand`:
```js
const { RedshiftDataClient, ExecuteStatementCommand, CancelStatementCommand } = require("@aws-sdk/client-redshift-data");

const client = new RedshiftDataClient({region: REGION})

var params = {
    Database: DATABASE, /* required */
    Sql: SQL, /* required */
  };

const execStmtCmd = new ExecuteStatementCommand(params);

client.send(execStmtCmd).then(data => {
    console.log(data);
    const cancelStmtCmd = new CancelStatementCommand({ Id: data.Id });
    client.send(cancelStmtCmd).then(console.log);
});
```

**Comment by amardatar** [comment]
Hi @vudh1 confirming this is still happening on v3.44.0

I'm not certain about this but I wonder if it relates to the PIDs available in Redshift. In my cluster, an example PID is `1073857187`. In theory I think that's still a regular integer (and as far as I can tell Redshift still reports it as an integer), however in the past the PIDs were typically 5 digits long. The [Redshift documentation](https://docs.aws.amazon.com/redshift/latest/dg/PG_CANCEL_BACKEND.html) shows a shorter PID, I wonder if that might be causing issues as this has worked successfully in the past.

Full output from running the code above (redacted where appropriate):
```
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'b76397d6-dd94-4af2-a8bf-378e59ecabef',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  ClusterIdentifier: '***',
  CreatedAt: 2021-12-10T03:26:13.925Z,
  Database: '***',
  DbUser: '***',
  Id: 'b89f5677-b50a-4ad6-9a67-428854f2546b',
  SecretArn: undefined
}
/node_modules/@aws-sdk/client-redshift-data/dist-cjs/protocols/Aws_json1_1.js:238
    return Promise.reject(Object.assign(new Error(message), response));
                                        ^

ValidationException: ERROR: function pg_cancel_backend(bigint) does not exist
  Hint: No function matches the given name and argument types. You may need to add explicit type casts.
    at deserializeAws_json1_1CancelStatementCommandError (/node_modules/@aws-sdk/client-redshift-data/dist-cjs/protocols/Aws_json1_1.js:238:41)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:6:20
    at async /node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
    at async StandardRetryStrategy.retry (/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: 'aec2e14b-1c31-4585-a0bc-45c416198823',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}
```
