### ISSUE TITLE
EventBridgeClient PutEventsCommand timeout on client.send

### ISSUE THREAD

**Issue by alanhobbart** [aws/aws-sdk-js-v3#3059]
## Describe the bug
@aws-sdk/client-eventbridge

When I call **client.send** in a lambda function on AWS i get Task timed out error. 
{
  "errorMessage": "2021-11-23T16:50:23.576Z e8119198-aafa-403c-8016-55e6b6314563 Task timed out after 20.02 seconds"
}

When I run the same lambda from my local environment, it runs fine, and I can see the event in the AWS logs. EventBridge permission has been added to the Lambda on AWS

Rough sample code
```js
import { EventBridgeClient, PutEventsCommand } from '@aws-sdk/client-eventbridge';

const client = new EventBridgeClient({ region: '@@@@' });
const dataToSend = {
      eventName: ['@@@@'],
    };
const entry = {
      Entries: [
        {
          EventBusName: '@@@@',
          Source: '@@@@',
          DetailType: '@@@@',
          Detail: JSON.stringify(dataToSend),
        },
      ],
    };
 const command = new PutEventsCommand(entry);
  
    try {
      const data = await client.send(command);
      client.destroy();
    } catch (error) {
      log.info(JSON.stringify(error));
    }
```

#### SDK version number
`@aws-sdk/client-eventbridge@3.41.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

## Steps to reproduce
Execute a putEvent from inside a lambda.

**Comment by btanmayee** [comment]
Hello,

I am too facing the same issue. Any update on this one please.

**Comment by alanhobbart** [comment]
The issue I had was due to the lambda using a VPC in it's config. Once an interface VPC endpoint for EventBridge was added it started to work. see below.
https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-related-service-vpc.html

**Comment by btanmayee** [comment]
Thank you for input.
I tried adding a VPC endpoint for EventBridge and it created successfully, but when actually running an operation lambda still gives timeout. Any other pointer if any.

Thank you.

**Comment by btanmayee** [comment]
In actions for VPC endpoint gave "- events:*" and also in lambda role gave the same. Is this something wrong, which is creating a timeout
