### ISSUE TITLE
Large increase of credential-provider-node package size 

### ISSUE THREAD

**Issue by nolan-m** [aws/aws-sdk-js-v3#3061]
## Describe the bug
We were previously on 1.0.0-gamma.1 and upgraded to the latest due to a detected vulnerability.  Now the packaged size has increased tremendously.  This is bloating our lambda zip from 2MB to 11MB just from upgrade these packages. This is even more of a concern since we are using more than one credential-provider package in the same project.  You can see from the screenshots the difference in dependencies installed.  Is this intentional or an error that something got included in the build output?

## Your environment
MacOS

#### SDK version number
`@aws-sdk/credential-provider-node@3.40.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v14.17.4

## Steps to reproduce
Please share code or minimal repo, and steps to reproduce the behavior.
Install latest version of credential-provider-node and inspect dependency size.

#### Observed behavior
Lots of dependencies installed.

#### Expected behavior
Smaller package size.

#### Screenshots
<img width="793" alt="Screen Shot 2021-11-23 at 4 15 12 PM" src="https://user-images.githubusercontent.com/5704672/143144095-d57e62d7-f4b7-4a16-8b7c-2a1dbb9f5fb8.png">
3.40.0
<img width="474" alt="Screen Shot 2021-11-23 at 12 53 54 PM" src="https://user-images.githubusercontent.com/5704672/143144096-7b238121-2e46-4d56-9f52-3802890c06ab.png">
1.0.0-gamma.1
<img width="377" alt="Screen Shot 2021-11-23 at 4 26 00 PM" src="https://user-images.githubusercontent.com/5704672/143144739-b3948dd4-ed68-41b8-ab15-59d63968455a.png">

**Comment by vudh1** [comment]
Hi @nolan-m we have fixed this in @3.41.0 ([link](https://github.com/aws/aws-sdk-js-v3/pull/3006)). Feel free to reopen if this is not helpful.
