### ISSUE TITLE
Ini file takes over env variables for specifying credentials

### ISSUE THREAD

**Issue by rprovodenko** [aws/aws-sdk-js-v3#3065]
## Describe the bug
When specifying AWS_PROFILE, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN and AWS_CREDENTIAL_EXPIRATION sdk still uses the ini file for credentials. V2 SDK works fine.

```
    const sts = new STS({});
    console.log(await sts.getCallerIdentity().promise()); // logs correct user from AWS_PROFILE
    const client = new STSClient({ region: "us-east-1" });
    const command = new GetCallerIdentityCommand();
    console.log(await client.send(command)) // logs incorrect user from the ini file
```

Must be because of this line: https://github.com/aws/aws-sdk-js-v3/blob/main/packages/credential-provider-node/src/index.ts#L57

#### SDK version number
`@aws-sdk/client-sts@3.42.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

**Comment by vudh1** [comment]
Hi @rostislavdeepcrawl thanks for reaching out. I am able to reproduce your problem. We will investigate this problem more. 
Also, you can only set `AWS_PROFILE` or set `AWS_ACCSS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, `AWS_SESSION_TOKEN` would overwrite the user of `AWS_PROFILE`.

Getting the correct behavior from JS v2 and CLI v1/v2 that returns the user from AWS_PROFILE.


```js
const sts = new AWS.STS({}); //v2.1044.0
console.log(await sts.getCallerIdentity().promise());
```

```cli
AWS_PROFILE=<NAME> AWS STS get-caller-identity
```

However, for JS v3 SDK:
```js
const command = new GetCallerIdentityCommand();
console.log(await client.send(command)) 
```
This returns the user from ini file.

**Comment by kuhe** [comment]
I'm not able to reproduce this on the latest version, setting to closing-soon.
