### ISSUE TITLE
Can't initialize S3 or Cloudwatch clients

### ISSUE THREAD

**Issue by rubfergor** [aws/aws-sdk-js-v3#3068]
## Describe the bug
When trying to initialize any client, an error is thrown.

#### SDK version number
`@aws-sdk/client-cloudwatch-logs@3.42.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node

#### Details of the browser/Node.js/ReactNative version
`v14.18.1`.

## Steps to reproduce
Try to initialize a client (with or without the captureAWS function from `aws-xray-sdk-core`, the result is the same)
```typescript
  const client = captureAWSv3Client(
    //@ts-expect-error: known error in X-Ray
    new CloudWatchLogsClient({})
  ) as CloudWatchLogsClient;
```

#### Observed behavior
```typescript
TypeError: Cannot destructure property 'environmentVariableSelector' of 'undefined' as it is undefined.
    at Object.loadConfig (/Users/ruben/Git/app/node_modules/@aws-sdk/client-cloudwatch-logs/node_modules/@aws-sdk/node-config-provider/src/configLoader.ts:28:5)
    at Object.getRuntimeConfig (/Users/ruben/Git/app/node_modules/@aws-sdk/client-cloudwatch-logs/dist-cjs/runtimeConfig.js:38:170)
    at new CloudWatchLogsClient (/Users/ruben/Git/app/node_modules/@aws-sdk/client-cloudwatch-logs/dist-cjs/CloudWatchLogsClient.js:15:43)
```

#### Expected behavior
You should be able to initialize the client and issue commands to it

## Extra information
I'm on a Lerna monorepo, using Yarn, in case that might be of interest.

**Comment by vudh1** [comment]
Hi @rubfergor, thanks for reaching out. I am not able to reproduce the problem above. First, make sure you are on the latest version of SDK. Also, here are some suggestions for initializing client on both S3 and Cloudwatch.

```js
const { S3Client } = require("@aws-sdk/client-s3"); //@3.44.0
const s3Client = new S3Client({region: "us-west-2"});

const { CloudWatchLogsClient } = require("@aws-sdk/client-cloudwatch-logs"); //@3.43.0
const cloudWatchLogsClientclient = new CloudWatchLogsClient({ region: "us-west-2" });
```

Also, you can use these documentations:
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/index.html
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-cloudwatch-logs/index.html


Feel free to reopen this if this is not helpful.
