### ISSUE TITLE
Add a client for Evidently

### ISSUE THREAD

**Issue by dmattia** [aws/aws-sdk-js-v3#3073]
### Is your feature request related to a problem? Please describe.

The v3 sdk does not appear to have support for the brand new CloudWatch Evidently feature flag service.

### Describe the solution you'd like

Add a client for Evidently

**Comment by ffxsam** [comment]
Why do we even have to ask for this? The feature is live, and the v3 SDK doesn't support it, yet v2 SDK does?

**Comment by trivikr** [comment]
We'll release `v3.44.0` today around 6pm PT with Evidently.

**Comment by ffxsam** [comment]
Perfect, thank you! I hope Amazon starts putting a higher priority on AWS SDK v3 over v2, which really ought to be deprecated in the near future.

**Comment by trivikr** [comment]
The [@aws-sdk/client-evidently](https://www.npmjs.com/package/@aws-sdk/client-evidently) is now available on npm.
