### ISSUE TITLE
Cannot find module '@aws-sdk/signature-v4-crt' in v `3.43.0`

### ISSUE THREAD

**Issue by GonzaloHirschToptal** [aws/aws-sdk-js-v3#3074]
## Describe the bug
Upon trying to update to version `3.43.0` we are greeted with the error:
<details>
<summary>Open the error:</summary>
<pre><code>
7:18:16 PM:   Error message
7:18:16 PM:   A Netlify Function failed to require one of its dependencies.
7:18:16 PM:   Please make sure it is present in the site's top-level "package.json".
​
7:18:16 PM:   In file "/opt/build/repo/functions/models.js"
7:18:16 PM:   Cannot find module '@aws-sdk/signature-v4-crt'
7:18:16 PM:   Require stack:
7:18:16 PM:   - /opt/buildhome/node-deps/node_modules/@netlify/zip-it-and-ship-it/dist/runtimes/node/bundlers/zisi/resolve.js
7:18:16 PM:   - /opt/buildhome/node-deps/node_modules/@netlify/zip-it-and-ship-it/dist/runtimes/node/bundlers/zisi/traverse.js
7:18:16 PM:   - /opt/buildhome/node-deps/node_modules/@netlify/zip-it-and-ship-it/dist/runtimes/node/bundlers/esbuild/src_files.js
7:18:16 PM:   - /opt/buildhome/node-deps/node_modules/@netlify/zip-it-and-ship-it/dist/runtimes/node/bundlers/esbuild/index.js
7:18:16 PM:   - /opt/buildhome/node-deps/node_modules/@netlify/zip-it-and-ship-it/dist/runtimes/node/bundlers/index.js
7:18:16 PM:   - /opt/buildhome/node-deps/node_modules/@netlify/zip-it-and-ship-it/dist/runtimes/node/index.js
7:18:16 PM:   - /opt/buildhome/node-deps/node_modules/@netlify/zip-it-and-ship-it/dist/runtimes/index.js
7:18:16 PM:   - /opt/buildhome/node-deps/node_modules/@netlify/zip-it-and-ship-it/dist/main.js
7:18:16 PM:   - /opt/buildhome/node-deps/node_modules/@netlify/build/src/plugins_core/functions/index.js
7:18:16 PM:   - /opt/buildhome/node-deps/node_modules/@netlify/build/src/steps/get.js
7:18:16 PM:   - /opt/buildhome/node-deps/node_modules/@netlify/build/src/core/main.js
7:18:16 PM:   - /opt/buildhome/node-deps/node_modules/@netlify/build/src/core/bin.js
</code></pre>
</details>

## Your environment

We are working with Netlify functions, and our dependencies are:
<details>
<summary>See dependencies:</summary>
<pre><code>
"dependencies": {
		"@aws-sdk/client-s3": "3.28.0",
		"@middy/core": "2.5.3",
		"@middy/http-cors": "2.5.3",
		"@middy/http-error-handler": "2.5.3",
		"@middy/http-json-body-parser": "2.5.3",
		"@middy/http-response-serializer": "2.5.3",
		"@octokit/core": "3.5.1",
		"@semantic-release/changelog": "5.0.1",
		"@semantic-release/git": "9.0.1",
		"@serverless-jwt/netlify": "0.2.1",
		"auth0": "2.37.0",
		"axios": "0.24.0",
		"conventional-changelog-conventionalcommits": "4.6.1",
		"http-errors": "1.8.1",
		"jsonwebtoken": "8.5.1",
		"mailgun.js": "4.0.1",
		"middy": "0.36.0",
		"mongodb": "4.2.0",
		"netlify": "8.0.4",
		"unique-names-generator": "4.6.0"
	}
</code></pre>
</details>

#### SDK version number
@aws-sdk/client-s3@3.43.0

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Node.js 12, the version available in Netlify Functions

## Steps to reproduce
Just trying to build or running a dev script with this newer version simply breaks.

#### Observed behavior
A dependencies installation error while trying to bundle the Netlify Functions.

#### Expected behavior
Not breaking while installing dependencies.

## Additional context
Using version `3.28.0` works, but anything newer appears not to. I referred from [this issue](https://github.com/aws/aws-sdk-js-v3/issues/2750), but the topic was closed and the conclusion was to downgrade to `3.28.0`.

**Comment by samchungy** [comment]
Since you're using esbuild, you just need to declare it as external
