### ISSUE TITLE
Clients accept any Commands - regression

### ISSUE THREAD

**Issue by m-radzikowski** [aws/aws-sdk-js-v3#3075]
## Describe the bug

You can put any `Command` to any `Client#send()` method.

I believe this is a regression introduced in 3.18.0. Before the command type was checked and TS threw an error if we tried to pass a Command for a different type of Client.

#### SDK version number

1.134.0

#### Is the issue in the browser/Node.js/ReactNative?

Node.js

#### Details of the browser/Node.js/ReactNative version

14.18.1

## Steps to reproduce

```ts
import {S3Client} from '@aws-sdk/client-s3';
import {PutRecordsCommand} from '@aws-sdk/client-kinesis';

const s3 = new S3Client({});

await s3.send(new PutRecordsCommand({ // this is Kinesis command, not S3, but TS does not report any problem here
    StreamName: targetStreamName,
    Records: records,
}));
```

#### Observed behavior

Runtime error, in this particular case:

> "SyntaxError: Unexpected token < in JSON at position 0"

#### Expected behavior

TS error, preventing us from building such code.

## Additional context

I'm ashamed to lose too much time trying to find this bug in my code, which was a result of copy-paste...

**Comment by ajredniwja** [comment]
Hey @m-radzikowski thanks for opening this issue, unfortunately I was not able to get similar results when I was reproducing this, can you please confirm what your SDK version is?

**Comment by m-radzikowski** [comment]
SDK version: 3.44.0

Here is a repo with reproduction: https://github.com/m-radzikowski/aws-sdk-js-v3-issue3075
