### ISSUE TITLE
Signature mismatch for execute api service

### ISSUE THREAD

**Issue by chaitanya11** [aws/aws-sdk-js-v3#308]
**Describe the bug**
Getting signature mismatch when using generated signature as bellow

**SDK version number**
0.1.0-preview.2

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
v8.9.4

**To Reproduce (observed behavior)**
```
export const signRequest = async (request) => {
    Logger.info('Generating signed request');
    const signature = new SignatureV4({
        service: 'execute-api',
        region: 'us-east-1',
        credentials: {
            accessKeyId: getEnv(ENV.CREDENTIALS.ACCESS_KEY),
            secretAccessKey: getEnv(ENV.CREDENTIALS.SECRET_KEY),
            sessionToken: getEnv(ENV.CREDENTIALS.SESSION_TOKEN)
        },
        applyChecksum: false
    });
    const result = await signature.sign(request);
    Logger.debug(`Signature is ${JSON.stringify(result)}`);
    return result;
};
```

Request is 
```
             {
                    method: "POST",
                    protocol: "https:",
                    path: url.pathname,
                    hostname: url.host,
                    headers: {
                        "X-Amz-Content-Sha256": "UNSIGNED-PAYLOAD",
                        'x-api-key': NBA.API_KEY,
                        'Content-Type': 'application/json'
                    },
                    body: nbaReq
                }
```

**Expected behavior**
should generate signature headers from the given request.

**Error Message**
`The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n .....`

**Comment by AllanFly120** [comment]
Hey @chaitanya11 
Are you using it with AWS APIs? Can you share what service you are using?

**Comment by chaitanya11** [comment]
Hi @AllanFly120,
I am using it for 'execute-api' service (Api gateway).
