### ISSUE TITLE
getObject returns data in response.Body._readableState.buffer.head.data

### ISSUE THREAD

**Issue by hamzahamidi** [aws/aws-sdk-js-v3#3080]
## Describe the bug
I 'm just trying to get the content of JSON file. But, I can't access the data directly in response.Body. I have to go through `file.Body._readableState.buffer.head.data`. Is this the normal behavior?

#### SDK version number
` "@aws-sdk/client-s3": "3.43.0",`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`
Node v14.17.3
## Steps to reproduce
Please share code or minimal repo, and steps to reproduce the behavior.

```
const { S3 } = require("@aws-sdk/client-s3");

const  s3Client = new S3(s3Config);

const response = s3Client.getObject({
      Bucket: config.aws.s3.buckets[type].name,
      Key: objectName
    });

const data = file.Body._readableState.buffer.head.data.toString('utf-8')
```

#### Expected behavior
I expect the data to be available in Body directly
```
const data = file.Body.toString('utf-8')
```

**Comment by fishcharlie** [comment]
Duplicate of https://github.com/aws/aws-sdk-js-v3/issues/1877?

**Comment by ajredniwja** [comment]
@hamzahamidi thanks for opening this issue, this one is well explained in the conversation for https://github.com/aws/aws-sdk-js-v3/issues/1877 which was indicated by @fishcharlie can you please take a look and let me know if you still have any questions?

**Comment by fishcharlie** [comment]
@ajredniwja Sorry for chiming in here. #1877 is ACTIVELY waiting for a reply from AWS. The current behavior/regression from v2 is AWFUL.

This needs to be corrected by AWS ASAP.

I don't believe someone from AWS saying this issue is a duplicate without addressing or providing an update on #1877 is acceptable.

So yes, my question is when will AWS fix this regression? (Feel free to reply on #1877).

Getting an item from S3 should NOT be this difficult...

**Comment by ajredniwja** [comment]
@fishcharlie I understand the concern here, the explanation behind this was simply that the `body` returned by `getObject` is of type `Readable | ReadableStream | Blob`. The [docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/modules/getobjectoutput.html#body) mention the same as well. This particular issue was pointed towards 1877 as it explains a lot of details on what is happening.  I do understand how this is a regression. I will take your feedback to the team and would let them decide if they will be changing that.

**Comment by fishcharlie** [comment]
> I will take your feedback to the team and would let them decide if they will be changing that.

@ajredniwja At the **very** least AWS should provide an update on #1877 once a decision is made.

Again, I'll say it over and over. Getting an item from S# should **NOT** be this difficult.

**Comment by hamzahamidi** [comment]
Thanks for the feedback. I'm closing this on favor of #1877
