### ISSUE TITLE
client-s3: upload() flow is incomplete

### ISSUE THREAD

**Issue by OhadR** [aws/aws-sdk-js-v3#3083]
## Describe the bug

I try to use the new API for S3 upload. unlike the "old" API, here it is cumbersome: First, I have to make an API for  `CreateMultipartUpload`, to get an upload-id, and only then i can use the JS call (with UploadPartCommandInput).

furthermore, in order to call `CreateMultipartUpload`, i need to authenticate first, so there is a lot of HTTP mess that i have to deal with before i can use the new js-api.

the old js-api was very good and simple. AWS.S3.upload()

#### SDK version number
`@aws-sdk/client-s3@3.43.0`

#### Expected behavior
it could be great to init the upload with another js-api, without the need in AJAX/HTTP call.

**Comment by nihakue** [comment]
Have you seen @aws-sdk/lib-storage ? Looks like when they moved to v3, they split this functionality out of the client and into its own library.

**Comment by ajredniwja** [comment]
@OhadR thanks for opening this issue, the `upload` equivalent would be `lib-storage` in this case. You can try it out using the example given [here](https://github.com/aws/aws-sdk-js-v3/blob/a2fe393abf423ce2c23c90e87632aa18a88499fb/lib/lib-storage/README.md), hope that helps. 

Closing this issue now, please reach out if that doesn't solve the problem. Thanks
