### ISSUE TITLE
Importing `paginateDescribeInstanceTypes` breaks tree-shaking

### ISSUE THREAD

**Issue by ZauberNerd** [aws/aws-sdk-js-v3#3093]
## Describe the bug
Using the "bare-bones client" imports I usually get small-ish bundles `~230kb` with esbuild + `--minify`.
However when I import `paginateDescribeInstanceTypes` the whole bundle blows up to 2.1mb (minified).

#### SDK version number
`@aws-sdk/client-ec2@3.44.0`

#### Is the issue in the browser/Node.js/ReactNative?
Browser

#### Details of the browser/Node.js/ReactNative version
N/A as the problem happens during bundling

## Steps to reproduce
```javascript
import {
  EC2Client,
  DescribeInstanceTypesCommand,
  paginateDescribeInstanceTypes,
} from "@aws-sdk/client-ec2";

console.log({ EC2Client, DescribeInstanceTypesCommand, paginateDescribeInstanceTypes });
```

Switch between `DescribeInstanceTypesCommand` and `paginateDescribeInstanceTypes` in the above code snippet and bundling it via:
```sh
esbuild --bundle *.ts --outdir=dist --metafile=dist/metafile.json --sourcemap --minify
```

#### Observed behavior
Importing `paginateDescribeInstanceTypes` blows up the bundle and includes everything (same size as when importing:
```javascript
import { EC2 } from "@aws-sdk/client-ec2";
console.log(EC2);
```

#### Expected behavior
As with other `Describe*` and `paginate*` methods, importing them should not result in bundling the entire EC2 library.

#### Screenshots
Small bundle (source map explorer on bundle-buddy):
![small bundle on bundle-buddy (source map explorer)](https://user-images.githubusercontent.com/249542/145718878-4d6af43a-fd97-46d4-a7c2-06c38d92a648.png)
Large bundle (source map explorer on bundle-buddy):
![large bundle on bundle-buddy (source map explorer)](https://user-images.githubusercontent.com/249542/145718879-01a5929b-e1c6-49d7-bdf0-4f1b6db71ca2.png)

## Additional context
Related to: https://github.com/aws/aws-sdk-js-v3/issues/3023

**Comment by kuhe** [comment]
note for fix: the paginators should not attempt to use the aggregated client, since that static import blows up tree-shaking.

**Comment by kuhe** [comment]
the fix was released in https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.287.0
