### ISSUE TITLE
CloudFront createInvalidation Typescript error (still present)

### ISSUE THREAD

**Issue by nprasovict** [aws/aws-sdk-js-v3#3096]
## Describe the bug
This is re-opening of the https://github.com/aws/aws-sdk-js-v3/issues/2956

#### SDK version number
`@aws-sdk/client-cloudfront@3.43.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`
~~~
$ node -v
v12.20.1
~~~
## Steps to reproduce
See https://github.com/aws/aws-sdk-js-v3/issues/2956

#### Observed behavior
See https://github.com/aws/aws-sdk-js-v3/issues/2956

#### Expected behavior
Clean compile

#### Screenshots
It seems that tail of the `models_0.d.ts` file is missing:

![Selection_006](https://user-images.githubusercontent.com/58190557/146275250-5c74176a-dde8-4a6d-83ee-b2f093cf90f8.png)

## Additional context
Version `3.36.0` still works.

**Comment by Mike-Petersen** [comment]
Having the same issue in the newest version 3.67.0

**Comment by yenfryherrerafeliz** [comment]
Hi @nprasovict, thanks for opening this issue. Could you please try with the latest version?, which is @aws-sdk/client-cloudfront@3.112.0. I did test it and I got not issues. Also you can see [here](https://github.com/aws/aws-sdk-js-v3/blob/51b55220f5125a559d25b763c039e50c1e143f90/clients/client-cloudfront/src/commands/CreateInvalidationCommand.ts#L23) that CreateInvalidationCommandOutput extends from CreateInvalidationResult, and [here](https://github.com/aws/aws-sdk-js-v3/blob/51b55220f5125a559d25b763c039e50c1e143f90/clients/client-cloudfront/src/models/models_0.ts#L6173) you can see that that interface contains the field Validation.

Thanks!

**Comment by nprasovict** [comment]
I updated one of our projects to use 3.112.0 and I still see the part of the source code is missing.
![Selection_001](https://user-images.githubusercontent.com/58190557/174627125-4ca85551-7eec-4b0c-8bc5-1dbffa03721a.png)

Also, to make sure it's not the npm on my workstation misbehaving, I downloaded npm distribution archive with:
```
wget $(npm view @aws-sdk/client-cloudfront@3.112.0 dist.tarball)
```
and the file `dist-types/ts3.4/models/models_0.d.ts` from the archive indeed seems to be missing source code starting with line `314`..

**Comment by thefat32** [comment]
Please @yenfryherrerafeliz read #3847 it looks like "strip-comments" is breaking ts3.4 declaration files in multiple packages

**Comment by ajredniwja** [comment]
Hey thanks for opening the issue, we'll track this issue with https://github.com/aws/aws-sdk-js-v3/issues/3847
