### ISSUE TITLE
S3: Simpler Multipart Uploads in V3

### ISSUE THREAD

**Issue by medanat** [aws/aws-sdk-js-v3#310]
**Is your feature request related to a problem? Please describe.**

I might have not been looking in the right place, but I can't find a method matching `s3.upload` (https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property) in v3. Specifically something that handles all the stages of multipart uploads (initiate multipart, upload part, complete multipart).

**Describe the solution you'd like**

A method similar to the v2 `s3.upload` which does all the heavy lifting for multipart uploads using something like the managed upload module (https://github.com/aws/aws-sdk-js/blob/master/lib/s3/managed_upload.js).

**Describe alternatives you've considered**

- PUT Object Command (not suitable for multipart I believe and the response does not match that of the complete multipart command.
- Manual multipart (initiate, upload parts, complete) which can be cumbersome and error prone.

**Additional context**

N/A

Thanks!

**Comment by alexforsyth** [comment]
We're working on this with https://github.com/alexforsyth/aws-sdk-js-v3/pull/new/experimental/storage-upload

**Comment by alexforsyth** [comment]
Quick update: This should be merged as part of https://github.com/aws/aws-sdk-js-v3/pull/1547. This will be going out this week was part of the next release.

**Comment by medanat** [comment]
Thank you - much appreciated!

**Comment by trivikr** [comment]
Closing as @aws-sdk/lib-storage is published: https://www.npmjs.com/package/@aws-sdk/lib-storage
