### ISSUE TITLE
[Error: not implemented] on CreatePlatformEndpointCommand

### ISSUE THREAD

**Issue by mather4** [aws/aws-sdk-js-v3#3103]
## Describe the bug
When I try to create an endpoint with `CreatePlatformEndpointCommand` (or execute really any command) I'm getting this same error `not implemented`. The only thing I've done that yields a different error is if I remove region from the params when creating the client. Then it errors Region is missing in the same place.

## Your environment
React Native. Using react-native-push-notification

#### SDK version number
SNS service from the AWS SDK for JavaScript v3 (6.14.7)

#### Is the issue in the browser/Node.js/ReactNative?
ReactNative

#### Details of the browser/Node.js/ReactNative version
v0.64.0

## Steps to reproduce
```js
import { CognitoIdentityClient } from "@aws-sdk/client-cognito-identity";
import { fromCognitoIdentityPool } from "@aws-sdk/credential-provider-cognito-identity";
import { SNSClient, CreatePlatformEndpointCommand } from "@aws-sdk/client-sns";
import PushNotification from "react-native-push-notification";

const sns = new SNSClient({
    region,
    credentials: fromCognitoIdentityPool({
        client: new CognitoIdentityClient({ region }),
        identityPoolId: identityPoolId,
    })
});

PushNotification.configure({    
    onRegister: function (token) {
        const params = {
            PlatformApplicationArn: platformApplicationArn,
            Token: token
        }
        const command = new CreatePlatformEndpointCommand(params);

        const res = await sns.send(command)
        .catch((err) => {
            console.log(err) //// this is the "[Error: not implemented]"
            throw err 
        })
    }
    ...
})
```
#### Observed behavior
Always throws `[Error: not implemented]`

**Comment by mather4** [comment]
After upgrading react-native I now have this error: `URL.hostname is not implemented`. Still not clear on how to resolve but closer...

**Comment by klozano** [comment]
Same here, any news on this?

**Comment by nathounet26** [comment]
Same here when I'm using @aws-sdk/client-cognito-identity-provider package and trying to send a command.
It's very annoying. Is there any progress with fixing it?

**Comment by mather4** [comment]
This is how I ended up solving this https://stackoverflow.com/questions/70413410/error-url-hostname-is-not-implemented-aws-sns-in-react-native-android

**Comment by RanVaknin** [comment]
Hi all, 
Sorry for the late response.

This is expected behavior and not an issue. We require you add these imports when using the modularized SDK for ReactNative. This is from the [**"Getting Started"** portion of the AWS-JS-SDK V3 docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/index.html#getting-started):

> If you are consuming modular AWS SDK for JavaScript on react-native environments, you will need to add and import following polyfills in your react-native application:
> 
> [react-native-get-random-values](https://www.npmjs.com/package/react-native-get-random-values)
> [react-native-url-polyfill](https://www.npmjs.com/package/react-native-url-polyfill)
> ```js
> import "react-native-get-random-values";
> import "react-native-url-polyfill/auto";
> ```
