### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'getReader')

### ISSUE THREAD

**Issue by DomeQdev** [aws/aws-sdk-js-v3#3104]
## Describe the bug
When I'm trying to use AbortMultipartUploadCommand, i'm getting this error: 
```js
TypeError: Cannot read properties of null (reading 'getReader')
```

#### SDK version number
`@aws-sdk/client-s3@3.44.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
JavaScript V8 9.7 (Cloudflare Workers)

## Steps to reproduce
I'm trying to use this code:
```js
let multipart = await aws.send(new AbortMultipartUploadCommand({
        Bucket: bucket,
        Key: key,
        UploadId
}));
```
All values are fine, i'm getting error above.

#### Observed behavior
I'm getting error

#### Expected behavior
I expect to abort multipart upload without any errors and get [this](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/interfaces/abortmultipartuploadcommandoutput.html) output.

**Comment by ajredniwja** [comment]
I have seen similar errors when errors are not properly catched as well.
