### ISSUE TITLE
package-generator generate client will fail if /tmp is on a different device than the target directory.

### ISSUE THREAD

**Issue by everett1992** [aws/aws-sdk-js-v3#311]
**Describe the bug**
`package-generator generate client` will fail if /tmp is on a different device than the target directory.

You cannot `rename` a file across partitions or devices. 
https://github.com/aws/aws-sdk-js-v3/blob/master/packages/package-generator/src/importModule.ts#L44
```
Error: EXDEV: cross-device link not permitted, rename '/tmp/pk9bBD' -> '/local/target'
```

**SDK version number**
    "@aws-sdk/package-generator": "0.1.0-preview.2"

**Is the issue in the browser/Node.js?**
build-tool, linux, but I think windows too.

**To Reproduce (observed behavior)**
Use a computer with more than one device.
Run the `./generator client` while on a different device than /tmp.

**Comment by AllanFly120** [comment]
I've notice this, because we are using `rename`, the script doesn't work accross the device. I will mark this as feature request and prioritize this when we can.

**Comment by trivikr** [comment]
Update: After moving to smithy, we're no longer using `@aws-sdk/package-generator` in master
We need to check if Java CodeGenerator has same issue.
