### ISSUE TITLE
(lib-dynamodb): Improve native number conversion

### ISSUE THREAD

**Issue by nicolaslt** [aws/aws-sdk-js-v3#3111]
### Is your feature request related to a problem? Please describe.
When the dataset in Dynamo includes a BigDecimal, the JS sdk is forcing the user to use the `wrapNumbers` option, due to `BigInt` not supporting decimals.

This in turn mangles the data structure of the overall document and may not allow correct parsing by the client. For cases where there is no way to guarantee correct detection in between `{value: string}` as a Dynamo number an `{value: string}` as an actual slice of the document that shouldn't go through custom number parsing.

For example, a document may have phone numbers, which in this example should stay as string as they could be written down with the `+` or with only digits, but a custom number handling, happening after the sdk's conversion would not necessarily know not to parse the string as a number.

### Describe the solution you'd like
Give the client the option to do their own wrapping or number conversions.

This could be by giving control over the name of the `value` property, and encourage, but not require, the use of `Symbol` to remove any ambiguity.

### Describe alternatives you've considered
Allowing the client to give their own number conversion function that could return any type they would like. This however would probably require a substantial refactor, and probably breaking change due to making `NativeAttributeValue` a generic type

### Additional context
I would be happy to make a pull request myself. I chose to open a discussion first, considering the range of solutions and their different impact.

**Comment by kuhe** [comment]
I'm not completely understanding the example problem. Could you add a code sample or PR?

**Comment by kuhe** [comment]
related: https://github.com/aws/aws-sdk-js-v3/issues/3066

**Comment by nicolaslt** [comment]
@kuhe The main issue is the loss of information that this particular field in the document was meant to be a number.

In my case I'm not in control of the schema of the document but I am in control of the system that runs a user-provided schema on top of user-provided data.

With the current situation, I am not able to write a detection mechanism that would be able to tell the user their schema doesn't match with their data because the information I have from the SDK is schemaless.

Here's a made up example.

Say we have a document that contains a phone number and a couple of BigDecimal:
```json
{
  "M": {
    "phoneNumber": {
      "M": {
        "value": {
           "S": "0123458"
        },
      }
    },
    "someBigDecimalData": {
      "N": "0.123456787"
    },
    "nestedBigDecimalData": {
      "M": {
        "value": {
           "N": "45.583383238523"
        }
      }
    }
  }
}
```

With `wrapNumbers`, this unmarshals to:
```json
{
  "phoneNumber": {
      "value": "0123458"
  },
  "someBigDecimalData": {
      "value": "0.123456787"
  },
  "nestedBigDecimalData": {
    "value": {
      "value": "45.583383238523"
    }
  }
}
```

Now, if my user tells me their data has this schema, I won't be able to detect it's incorrect in some cases. Did the user mean to have some values wrapped by `value` in their own schema? Was it instead wrapped by the SDK because it's a number?

```json
{
  "phoneNumber": "Int",
  "someBigDecimalData": "BigDecimal",
  "nestedBigDecimalData": "BigDecimal"
}
```

The correct schema in this case should be
```json
{
  "phoneNumber": { "value": "String"},
  "someBigDecimalData": "BigDecimal",
  "nestedBigDecimalData": {
    "value": "BigDecimal"
  }
}
```

If I was given more control over `wrapNumbers`, for example accepting a key of my choosing, I could replace "value" with a unique reference (say `Symbol("DynamoNumber")` or "__internal__wrappedNumberFromDynamo").

This would give an unmarshal document of the shape:
```json
{
  "phoneNumber": {
      "value": "0123458"
  },
  "someBigDecimalData": {
      "__internal__wrappedNumberFromDynamo"": "0.123456787"
  },
  "nestedBigDecimalData": {
    "value": {
      "__internal__wrappedNumberFromDynamo"": "45.583383238523"
    }
  }
}
```

With this change, my "Int" processing can throw and be useful to my user because it can detect it was given an object with `value` as a key which should never happen; and my `BigDecimal` parser can also look for the specific key with guarantees it won't clash with anything user provided

**Comment by nicolaslt** [comment]
I'm going to close this one, I don't have time to PR it myself anymore
