### ISSUE TITLE
FOSSA report: No license found in `@aws-sdk/client-*`

### ISSUE THREAD

**Issue by moltar** [aws/aws-sdk-js-v3#3114]
## Describe the bug

FOSSA report is all of a sudden reporting that "No license found" in all of the SDK packages.

## Your environment

N/A

#### SDK version number

`@aws-sdk/*@3.45.0`

#### Is the issue in the browser/Node.js/ReactNative?

Node.js

#### Details of the browser/Node.js/ReactNative version

N/A

## Steps to reproduce

Use FOSSA to scan for license conflicts.

#### Observed behavior

![screenshot-20211227T091937-1qGgXvr0](https://user-images.githubusercontent.com/491247/147427794-a00d69de-5610-480c-8779-d611bac7d383.png)

#### Expected behavior

AWS SDK packages to be licensed.

#### Screenshots

See above.

## Additional context

N/A

**Comment by moltar** [comment]
@fossas

**Comment by RanVaknin** [comment]
Hi @moltar , Thanks for reaching out.

I have never used Fossa before. Seems like a paid 3rd party tool. Right now all our packages have Apache 2.0 licenses. Maybe this was a problem in previous versions?

Let me know if this is still a problem. If it is can you please add in depth repro steps and I could take a look.

Thank you.
