### ISSUE TITLE
[deno] config-resolver fails to build

### ISSUE THREAD

**Issue by christophgysin** [aws/aws-sdk-js-v3#3117]
## Describe the bug

I'm maintaining a fork of aws-sdk-js-v3 for deno.

Commit 7c6a7901f222273f7e82f169eaaf23b08c803596 adds imports and re-exports of some types. This causes deno to fail while compiling typescript, with the error:
```
error: TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { RegionHash, PartitionHash };
         ~~~~~~~~~~
```
This can be fixed easily by changing the line to:
```ts
export type { RegionHash, PartitionHash };
```
[A similar issue](https://github.com/aws/aws-sdk-js-v3/issues/2597) has [previously been fixed this way](https://github.com/aws/aws-sdk-js-v3/commit/e64373551195565fdde2a6cda494e3c53a1f20c3).

However, I wonder if it would be acceptable to simply enable that check in the typescript config:

https://www.typescriptlang.org/tsconfig#isolatedModules

That would prevent this from happening again in the future.

**Comment by RanVaknin** [comment]
@christophgysin thanks for submitting.

Was able to confirm with the team that this is a bug.
Will add to the backlog.

Thanks.

**Comment by RanVaknin** [comment]
Hi, 

Unfortunately we are not able to prioritize Deno related work and we don't want to keep this open when we know this is not in the near future. 

Apologies,
Ran~
