### ISSUE TITLE
@aws-sdk/client-documentation-generator is not published to npm

### ISSUE THREAD

**Issue by everett1992** [aws/aws-sdk-js-v3#312]
**Describe the bug**
@aws-sdk/client-documentation-generator is not published to npm.

https://github.com/aws/aws-sdk-js-v3/tree/master/packages/client-documentation-generator

@aws-sdk/client-documentation-generator is a dependency of the packages that are created by @aws-sdk/package-generator, which is published.

I'd suggest removing package-generator, or removing client-documentation-generator from the generated dependencies, or publishing client-documentation-generator.

**Comment by AllanFly120** [comment]
Hey @everett1992,

The package-generator is not published, see [here](https://github.com/aws/aws-sdk-js-v3/blob/d709e50cd2b4df5ffd532c4fc1159ef9a8bd1c4c/packages/package-generator/package.json#L3). We published that package only in the first 1 or 2 releases, we will deprecate this package from NPM.
