### ISSUE TITLE
client-route-53/dist-types/ts3.4/Route53.d.ts file is malformed, no closing } - cannot compile

### ISSUE THREAD

**Issue by gherlein** [aws/aws-sdk-js-v3#3131]
## Describe the bug

``` console
$ mkdir test;cd test
$ npm install @aws-sdk/client-route-53
$ cat node_modules/@aws-sdk/client-route-53/dist-types/ts3.4/Route53.d.ts
```

you will see that the file does not have a closing }

```console
$ tail -n 5 node_modules/@aws-sdk/client-route-53/dist-types/ts3.4/Route53.d.ts

    createKeySigningKey(args: CreateKeySigningKeyCommandInput, options?: __HttpHandlerOptions): Promise<CreateKeySigningKeyCommandOutput>;
    createKeySigningKey(args: CreateKeySigningKeyCommandInput, cb: (err: any, data?: CreateKeySigningKeyCommandOutput) => void): void;
    createKeySigningKey(args: CreateKeySigningKeyCommandInput, options: __HttpHandlerOptions, cb: (err: any, data?: CreateKeySigningKeyCommandOutput) => void): void;
```

NO CLOSING BRACE

This generates errors:
```console
$ tsc
node_modules/@aws-sdk/client-route-53/dist-types/ts3.4/Route53.d.ts:97:5 - error TS1005: '}' expected.
```

## Your environment
```console
$ tsc -v
Version 4.5.4

$ node --version
v16.13.1
```

#### SDK version number
`"@aws-sdk/client-route-53": "^3.45.0"`

#### Is the issue in the browser/Node.js/ReactNative?
Node, but probably affects all

#### Details of the browser/Node.js/ReactNative version
```console
$ node --version
v16.13.1
```

## Steps to reproduce
see above

#### Observed behavior
```
$ tsc
node_modules/@aws-sdk/client-route-53/dist-types/ts3.4/Route53.d.ts:97:5 - error TS1005: '}' expected.
tail -n 5 node_modules/@aws-sdk/client-route-53/dist-types/ts3.4/Route53.d.ts
```

#### Expected behavior
node_modules/@aws-sdk/client-route-53/dist-types/ts3.4/Route53.d.ts should be a complete file

#### Screenshots
NA

## Additional context
NA

**Comment by trivikr** [comment]
Probably related: https://github.com/aws/aws-sdk-js-v3/issues/2921

**Comment by gherlein** [comment]
CLOSE as DUPLICATE

I was using yarn, which installs it's OWN typescript.

88665a1e55c0:~/src/cdk/single-ec2-dev> tsc -v
Version 4.5.4
88665a1e55c0:~/src/cdk/single-ec2-dev> yarn build
yarn run v1.22.17
$ tsc -v
Version 3.9.10

So it absolutely was the version bing different.  

 yarn add typescript
yarn add v1.22.17
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
<snip>
✨  Done in 3.37s.
88665a1e55c0:~/src/cdk/single-ec2-dev> yarn build
yarn run v1.22.17
$ tsc -v
Version 4.5.4
