### ISSUE TITLE
s3.selectObjectContent returns SignatureDoesNotMatch error

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#315]
**Describe the bug**

**SDK version number**
* works in v2: `aws-sdk@2.504.0`
* fails in v3: `@aws-sdk/client-s3-node@0.1.0-preview.2 `

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
v10.16.0

**To Reproduce (observed behavior)**
* Download [airport-codes.csv](https://github.com/datasets/airport-codes/blob/master/data/airport-codes.csv) and upload it in `<YOUR_S3_BUCKET>`
* Code which works in v2:
```javascript
const AWS = require("aws-sdk");
const s3Bucket = <YOUR_S3_BUCKET>;

(async () => {
  const s3 = new AWS.S3({
    region: "us-west-2"
  });

  const result = await s3
    .selectObjectContent({
      Bucket: s3Bucket,
      Key: "airport-codes.csv",
      Expression: "select * from s3object s where s.iso_country='AD'",
      ExpressionType: "SQL",
      RequestProgress: {
        Enabled: true
      },
      InputSerialization: {
        CSV: {
          FileHeaderInfo: "Use"
        }
      },
      OutputSerialization: {
        CSV: {}
      }
    })
    .promise();

  const events = result.Payload;

  for await (const event of events) {
    if (event.Records) {
      console.log(event.Records.Payload.toString());
    }
  }
})();

```
* Code which fails with SignatureDoesNotMatch in v3:
```javascript
const { S3 } = require("@aws-sdk/client-s3-node");
const s3Bucket = <YOUR_S3_BUCKET>;

(async () => {
  const client = new S3({
    region: "us-west-2"
  });

  const result = await client.selectObjectContent({
    Bucket: s3Bucket,
    Key: "airport-codes.csv",
    Expression: "select * from s3object s where s.iso_country='AD'",
    ExpressionType: "SQL",
    RequestProgress: {
      Enabled: true
    },
    InputSerialization: {
      CSV: {
        FileHeaderInfo: "Use"
      }
    },
    OutputSerialization: {
      CSV: {}
    }
  });

  const events = result.Payload;

  for await (const event of events) {
    if (event.Records) {
      console.log(`record: ${event.Records.Payload.toString()}`);
    }
  }
})();

```

**Expected behavior**
s3.selectObjectContent returns stream of data in result.Payload same as in v2

**Screenshots**

<img width="786" alt="v2-vs-v3" src="https://user-images.githubusercontent.com/16024985/62572578-e9bacb80-b848-11e9-9e94-7326e6b94c0d.png">

**Comment by trivikr** [comment]
Steps tried (to match headers in v2 and v3) while debugging which didn't help:
* added `"x-amz-content-sha256": "UNSIGNED-PAYLOAD"` just in SelectObjectContentCommand like it's done in PutObjectCommand command ([code](https://github.com/aws/aws-sdk-js-v3/blob/8bf91e2e411af302e920abc5fae008e4642597e9/packages/client-s3-node/commands/PutObjectCommand.ts#L64-L75))
* added `"Content-Type": "application/octet-stream"` in SelectObjectContentCommand just like it's done in GetObjectCommand ([code](https://github.com/aws/aws-sdk-js-v3/blob/8bf91e2e411af302e920abc5fae008e4642597e9/packages/client-s3-node/commands/GetObjectCommand.ts#L64-L73))
* passed `{unsignableHeaders: new Set(["content-length"])}` to disable signing of `"content-length"` in signer-middleware ([code](https://github.com/aws/aws-sdk-js-v3/blob/379a5c11f4620d974ba201c16c0453e0cc82fe29/packages/signing-middleware/src/index.ts#L20))
* removed middleware expectContinue from S3Client ([code](https://github.com/aws/aws-sdk-js-v3/blob/cee0f13d6d5ef738812d834fa84d727c2d382d6b/packages/client-s3-node/S3Client.ts#L118-L126))

**Comment by simonbuchan** [comment]
I also get this error with `new CreateMultipartUploadCommand({ Bucket, Key })` in `@aws-sdk/client-s3-node@0.1.0-preview.9`, with client that is working with `ListObjectsV2` and `GetObject` successfully.

**Comment by trivikr** [comment]
Revisiting this issue testing with `@aws-sdk/client-s3@1.0.0-alpha.15`
* Code: https://github.com/trivikr/aws-sdk-js-tests/blob/ce9ebbfadce04e3aad3cc1f14e3070c45930683d/src/shared/utils.js
* Branch: https://github.com/trivikr/aws-sdk-js-tests/tree/s3-selectObjectContent-test

Output:
```console
Data returned by v2:
AD-0001,heliport,Camí Heliport,,EU,AD,AD-04,La Massana,,,,"42.546257, 1.51916"
AD-ALV,heliport,Andorra la Vella Heliport,3450,EU,AD,AD-07,Andorra La Vella,,ALV,,"42.511174, 1.533551"


Data returned by v3:
(node:55667) UnhandledPromiseRejectionWarning: TypeError: response.Payload is not async iterable
    at /Users/trivikr/workspace/aws-sdk-js-tests/src/node/index.js:17:38
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:55667) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:55667) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by AllanFly120** [comment]
Close this issue because we recently moved to alpha clients. See [here](https://github.com/aws/aws-sdk-js-v3/issues/944) for more information. Please post a new issue if the bug persists in alpha clients.
