### ISSUE TITLE
Support multiple major versions of a single service

### ISSUE THREAD

**Issue by AllanFly120** [aws/aws-sdk-js-v3#316]
**Is your feature request related to a problem? Please describe.**
When a service release a new major version api that contains breaking change, code-generator should be able to generate different service clients instead of making breaking change on existing client.

For example, Cloudfront has an existing api [cloudfront-2016-11-25](https://github.com/aws/aws-sdk-js/blob/master/apis/cloudfront-2016-11-25.min.json), from which the SDK generates a client `client-cloudfront-node`. When Cloudfont makes breaking change and release a new major version like [cloudfront-2017-03-25](https://github.com/aws/aws-sdk-js/blob/master/apis/cloudfront-2017-03-25.min.json), instead of still generate the same client `client-cloudfront-node`, the code gen should detect this change and generate `client-cloudfront-v2-node` client.

**Describe the solution you'd like**
Because the code gen doesn't have the information of whether there's a mojor version API prior to the current API, we should inject this information to the API during the release.
In the release automation system, we can inject a `major_version` to the API metadata like `v2` or `v3`. When code gen executes, it will append such `major_version` to the client name.

**Describe alternatives you've considered**
We can also maintain a record of all versions of every service in the SDK. It works but we should only have 1 source of truth when doing code-gen, which is the service API model.

**Comment by trivikr** [comment]
It'll be difficult for customers to link between API dates and versions, for example `2017-03-25` and `v2` in the above case.
We should continue to provide an option to pass `apiVersion` in the constructor and select CodeGen based on the apiVersion provided.

**Comment by AllanFly120** [comment]
This is actually an invalid feature request. Service API are never allowed to do breaking change even within difference major versions(date version). [AWS Java SDK V2](https://github.com/aws/aws-sdk-java-v2) only keeps one version of each service client and it always targests at newest service model.
