### ISSUE TITLE
Support DynamoDB expression builder

### ISSUE THREAD

**Issue by AllanZhengYP** [aws/aws-sdk-js-v3#3165]
### Is your feature request related to a problem? Please describe.
Many other AWS SDKs provide abstractions for [DynamoDB expressions](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.html). They are more intuitive by providing mapping from variables to expression, and they also handle the encoding. Some examples from other AWS SDKs:
* [Go SDK DyanmoDB expression builder](https://aws.amazon.com/blogs/developer/introducing-amazon-dynamodb-expression-builder-in-the-aws-sdk-for-go/)
  * [Getting Amazon DynamoDB Table Items Using Expression Builder](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/dynamo-example-scan-table-item.html)
* [Boto3 DynamoDB condition expression](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/customizations/dynamodb.html#dynamodb-conditions)
* [Java V1 SDK expression builder](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/xspec/ExpressionSpecBuilder.html)

Currently the closest library provided by SDK team is the [Expression package in DynamoDB data mapper](https://github.com/awslabs/dynamodb-data-mapper-js/tree/master/packages/dynamodb-expressions), but it is more of a building block for the data mapper, with confusing interface for public consumption. 

### Describe the solution you'd like
Provide an expression builder similar to example above.

### Issues:
* https://github.com/aws/aws-sdk-js-v3/issues/2009

**Comment by spridev** [comment]
Here are some existing JS/TS alternatives, using different approaches and syntaxes:

- https://github.com/awslabs/dynamodb-data-mapper-js/tree/master/packages/dynamodb-expressions
- https://github.com/faceteer/expression-builder
- https://gitlab.com/monster-space-network/typemon/dynamon

Looking at the existing official solutions above, I do personally like the builder pattern used in Java. This reminds me of the usual SQL query builders like [Laravel Eloquent](https://laravel.com/docs/9.x/eloquent) or [Knex.js](http://knexjs.org/). Chainable methods, clean syntax, easy to understand.

Finally, I would rather not wrap the `DynamoDBClient` within another class, with a magic `update` method for example (like in [Dynamon](https://gitlab.com/monster-space-network/typemon/dynamon)). I feel like the following approach gives more flexibility and control to the user:

```js
const expr = new ExpressionBuilder().buildForUpdate();

const response = await ddb.send(
  new UpdateItemCommand({
    TableName: TABLE_NAME,
    Key: marshall({
      PK: 'USER#1234',
      SK: 'USER#1234',
    }),

    // Solution 1
    UpdateExpression: expr.content,
    ExpressionAttributeNames: expr.names,
    ExpressionAttributeValues: expr.values,

    // Solution 2
    ...expr
  })
);
```

Is this feature still pending or already in the roadmap? I think it's an important missing piece for the DynamoDB DX. Once the syntax has been determined, I will try to implement it, either here or as an independent package.
