### ISSUE TITLE
aws-sdk/lib-storage upload to s3 fail with the 400 bad request

### ISSUE THREAD

**Issue by qq5250142** [aws/aws-sdk-js-v3#3177]
## Describe the bug
I am using the lib-storage to parallel upload to the S3 ,it all goes well when the video for upload is less than the 5M,but when i upload a video which over than the 5M ,it failed at the end of the progress on 100%, the browser console get the 400 bad request ,and the response message is below
<Error>
<Code>
MalformedXML
</Code>
<Message>
The XML you provided was not well-formed or did not validate against our published schema
</Message>
<RequestId>
TYR3G92CZ6S54M2V
</RequestId>
<HostId>
nDXl3tm43g39lJMzq/LJ/0lr0b/e9m6SIvpO9hoJRV28FOe9nQoJwff2ehjVV2f8+utn1dzYN/4=
</HostId>
</Error>
here is my code like your example
![image](https://user-images.githubusercontent.com/3973456/148897103-6372986a-e2ac-4da2-ab39-7d84c360c84a.png)

#### SDK version number
`@aws-sdk/lib-storage@3.45.0`

#### Is the issue in the browser/Node.js/ReactNative?
Browser

#### Details of the browser/Node.js/ReactNative version
chrome 96.0.4664.110

here are the request payload 
<?xml version="1.0" encoding="UTF-8"?><CompleteMultipartUpload xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Part><PartNumber>1</PartNumber></Part><Part><PartNumber>2</PartNumber></Part><Part><PartNumber>3</PartNumber></Part></CompleteMultipartUpload>

![image](https://user-images.githubusercontent.com/3973456/148898369-2ef32342-9967-408c-8bea-ff8daacbca98.png)

can someone help me ? thanks so much

**Comment by qq5250142** [comment]
the response message
![image](https://user-images.githubusercontent.com/3973456/148898600-4ddf1091-f39e-402f-9ebe-455d4c622d3f.png)

**Comment by abstractalchemist** [comment]
Getting the exact same error with similar code.  It seems at least one problem appears to be with the UploadPartCommand parsing the result of the request.  The ETag property appears to be undefined even though if you look at the developer tools in Chrome the request actually contains an ETag Header in the response.  I'm not sure if that is a problem.

**Comment by martin-upheal** [comment]
We've experienced the problem manifesting in the same way and the issue was in incorrect S3 bucket CORS configuration. For the AWS SDK to work, it needs access to `ETag` header in the upload part response. The access to response headers is ruled by [ExposeHeader](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ManageCorsUsing.html#cors-expose-headers) element. In our case the ExposeHeader was empty => SDK couldn't access it => CompleteMultipartUpload request failed due to missing ETags.

After configuring the CORS on S3 bucket in the following way, the multipart upload started to work without a problem with both v2 and v3 javascript SDK:
```
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "PUT",
            "POST"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": [
            "x-amz-server-side-encryption",
            "x-amz-request-id",
            "x-amz-id-2",
            "ETag"
        ],
        "MaxAgeSeconds": 3000
    }
]
```

**Comment by abstractalchemist** [comment]
Someone else has verified, at least for me, that this will fix the issue.  Probably more of a configuration issue with configuring s3 bucket for cors access than a bug in the library.

**Comment by shuzootani** [comment]
same here

**Comment by RanVaknin** [comment]
It seems like this issue was solved. @martin-upheal thanks for looking into this.
I'll mark this resolved. Feel free to reopen the issue if something arises and I can take a look.

Thanks!
