### ISSUE TITLE
Vite apps will not build because of resolving imports

### ISSUE THREAD

**Issue by SINePrime** [aws/aws-sdk-js-v3#3202]
## Describe the bug
Vite projects will not build.

#### SDK version number
`@aws-sdk/util-defaults-mode-browser@3.47.0`

#### Is the issue in the browser/Node.js/ReactNative?
Browser.

#### Details of the browser/Node.js/ReactNative version
Node v17.2.0.

## Steps to reproduce
Try to build a Vite react app which depends on @aws-sdk/util-defaults-mode-browser@3.47.0.

#### Observed behavior
When trying to build a Vite app which depends on `@aws-sdk/util-defaults-mode-browser@3.47.0`, fails with error:
```
node_modules/.pnpm/@aws-sdk+util-defaults-mode-browser@3.47.0/node_modules/@aws-sdk/util-defaults-mode-browser/dist-es/resolveDefaultsModeConfig.js:3:9: 
error: No matching export in "node_modules/.pnpm/bowser@2.11.0/node_modules/bowser/src/bowser.js" for import "parse"
    3 │ import { parse } from "bowser";
```

#### Expected behavior
I expect the app to build.

## Additional context
The exact line of this error is: https://github.com/aws/aws-sdk-js-v3/blob/9152e210c6ec29f34bb070eaf2874039022e6ab7/packages/util-defaults-mode-browser/src/resolveDefaultsModeConfig.ts#L4

This is a regression from issue #1992, which was solved by pull request #1991; using the default import fixes this bug.

**Comment by jsmenzies** [comment]
Forgive me, i'm new to frontend dev but is this responsible for the following error? 
I'm building a SvelteKit application which I believe uses Vite.

'parse' is not exported by node_modules/.pnpm/bowser@2.11.0/node_modules/bowser/src/bowser.js, imported by node_modules/.pnpm/@aws-sdk+util-defaults-mode-browser@3.47.0/node_modules/@aws-sdk/util-defaults-mode-browser/dist-es/resolveDefaultsModeConfig.js

file: @aws-sdk+util-defaults-mode-browser@3.47.0/node_modules/@aws-sdk/util-defaults-mode-browser/dist-es/resolveDefaultsModeConfig.js:3:9
