### ISSUE TITLE
quicksight module not building

### ISSUE THREAD

**Issue by yonus** [aws/aws-sdk-js-v3#3204]
## Describe the bug
I have dependency on quicksight.  When I build project I get error as following:

110 | node_modules/@aws-sdk/client-quicksight/dist-types/ts3.4/QuickSight.d.ts(384,5): error TS1005: '}' expected

## Your environment
 Node.js 12
#### SDK version number
`@aws-sdk/client-quicksight": "^3.47.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

**Comment by vudh1** [comment]
Hi @yonus do you have sample of reproducible code that we can use to investigate more?
