### ISSUE TITLE
React-native Iot-core example

### ISSUE THREAD

**Issue by sidd2217** [aws/aws-sdk-js-v3#3206]
Hi,
I'm new to iot.
I couldn't find a way on internet or in documentation on how to receive iot-core test messages sent via esp32 -> aws -> react-native app.
I went through this [https://github.com/aws/aws-iot-device-sdk-js-v2/tree/main/samples](url) but it's supported for the v2 version for pubsub, and i couldn't find the docuementation for the same in v3.
If anyone have done this please do suggest me on how should i implement that.

My goal is to turn on/off led on board esp32 when toggled via react-native app.
If anyone has any ideas on how should i implement this do tell.

OS- Win10
Iot device - ESP32
App - React-native ( Android only ).

**Comment by pankti-0627** [comment]
any solution you got?

**Comment by sidd2217** [comment]
@pankti-0627 
Yeah, I did a round about way which goes as 
For esp messages to my app.
esp32 -> aws iotcore -> awslambda -> myserver -> app

For app to esp32 I went as 
App -> aws API gateway -> aws lambda ->aws iot core -> esp32
