### ISSUE TITLE
createInvalidation Typescript error

### ISSUE THREAD

**Issue by fmunozdambo** [aws/aws-sdk-js-v3#3207]
## Describe the bug
Typescript project fails to compile when attempting to access Invalidation member of result returned from call using class CloudFront method createInvalidation

## Your environment
macOS BigSur

#### SDK version number
`@aws-sdk/client-cloudfront@3.47.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node/js

#### Details of the browser/Node.js/ReactNative version
v14.12.0

## Steps to reproduce
```js
import { CloudFrontClient, CreateInvalidationCommandInput,
CreateInvalidationCommandOutput } from '@aws-sdk/client-cloudfront';

this.cfClient = new CloudFrontClient({
            region: this.region,
            credentials: {
                accessKeyId: this.credentials.key,
                secretAccessKey: this.credentials.secret,
            },
        });

const params: CreateInvalidationCommandInput = {
            DistributionId: id,
            InvalidationBatch: {
                CallerReference: something,
                Paths: {
                    Items: [path],
                    Quantity: 1,
                },
            },
        };

const invalidation: Invalidation = (await this.cfClient.send(new CreateInvalidationCommand(params))).Invalidation;
```
#### Observed behavior
error TS2339: Property 'Invalidation' does not exist on type 'CreateInvalidationCommandOutput'.

#### Expected behavior
Compile succesfully

**Comment by ajredniwja** [comment]
Hey @fmunozdambo thanks for opening this issue, I was not able to reproduce it with `v3.117`. 
Can you possibly check what you get in response:
```
    const response = await cfClient.send(new CreateInvalidationCommand(params));

    console.log(response);
```
