### ISSUE TITLE
Explore alternatives of Jest for unit testing

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#3208]
### Is your feature request related to a problem? Please describe.
Jest has been associated with multiple issues:
* Folks in Node.js community [don't](https://twitter.com/brianleroux/status/1480626080188821504) [like](https://twitter.com/matteocollina/status/1453029660925861901) [Jest](https://twitter.com/AhmadNassri/status/1375094293917003780) mainly because [it injects globals](https://github.com/facebook/jest/issues/2549) and rewires the complicated module system. Also, the project owner Facebook reduced the funding for jest sometime in 2018-2019, and the project is primarily run by volunteers and Open Collective.
* Long history of jest discussing [memory leaks](https://github.com/facebook/jest/issues?q=is%3Aissue+is%3Aopen+memory+leak+sort%3Aupdated-desc).
* Our [existing tests](https://github.com/aws/aws-sdk-js-v3/issues/3162) have memory leak.
* Jest [force exits](https://github.com/aws/aws-sdk-js-v3/issues/3150) when run in workspace.

### Describe the solution you'd like
Explore alternatives of Jest which are easy to migrate to:
* The vite team has done great job with multiple projects in the past, and as of Jan 2022 the [vitest](https://twitter.com/search?q=vitest) framework has good reviews.
* We've been using [mocha](https://www.npmjs.com/package/mocha) for writing browser tests. It has been among the popular test frameworks in JavaScript ecosystem for long.
* The [tape](https://www.npmjs.com/package/tape) and [tap](https://www.npmjs.com/package/tap) has been other test frameworks preferred by JS community.

### Describe alternatives you've considered
* Keep using jest, and find fixes/workarounds to the existing issues.
* Explore bindings alternative to ts-jest, like [babel-jest](https://www.npmjs.com/package/babel-jest) or [@swc/jest](https://www.npmjs.com/package/@swc/jest)

**Comment by philiiiiiipp** [comment]
We where using `jest` for the past years and noticed immense memory leaks especially when importing the `aws-sdk`, both v2 and v3. After stumbling over this issue a day ago, I tried all of your suggestions. `vitest` reduced our memory consumption from **>25GB** to **<1GB** with relatively minimal effort. The syntax is very close to jest's so just full-text replacing `jest.` to `vi.` made already 90% of our tests go.
