### ISSUE TITLE
@aws-sdk/client-connect/DescribeContactFlowModuleCommand returns unexpected InternalServerErrorException

### ISSUE THREAD

**Issue by gailmiller** [aws/aws-sdk-js-v3#3210]
## Describe the bug
This is my first bug report please be kind to me :) If I have missed anything it is not intentional.

When I try to export an Amazon Connect module, occasionally this function doesn’t work for that module as expected and continuously returns a InternalServerErrorException after previously working successfully.  The ONLY difference, that I can think of between a working one and a not working one, is that the module that is no longer working has had a name change in Amazon Connect GUI.  Everything else has been similar BAU adds moves and changes to the module call flows via Amazon Connect GUI.  I now have 2 broken modules , but if I TRY to specifically replicate it, it doesn’t always happen.

#### SDK version number
`@aws-sdk/client-connect@43`
`@aws-sdk/client-connect@45`
`@aws-sdk/client-connect@46`
`@aws-sdk/client-connect@47`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v16.4.1

## Steps to reproduce
Typescript Snippet producing the error:
```js
const params: DescribeContactFlowModuleCommandInput = {
InstanceId: SourceConnectInstanceId,
ContactFlowModuleId: CallFlowModule.Id || callFlowModuleSummary.Id, // find the id in the input list matching or by name from returned list,
};
debuglog('Params', params);
const command = new DescribeContactFlowModuleCommand(params);
const CallFlowModuleScript = await connect_connection
.send(command)
.catch(async (err) => {
    console.error(JSON.stringify(err)); // Circular reference error in V 46+
    return err;
)};
```

#### Observed behavior
This is the error I get back in V43 and 45
```
{"name":"InternalServerErrorException","$fault":"client","$metadata":{"httpStatusCode":500,"requestId":"59af8901-ab6b-4c29-a040-ff060fe5b300","attempts":3,"totalRetryDelay":251}}}
```

Which implies it’s an input parameters issue, but I can guarantee that the input of the instance id and the module id are 100% correct (as I do a lookup based on NAME and match to a returned list of modules using the list module function:  id and name – I have also done visual inspections of the input parameters based on the ARN in Amazon Connect of the modules)  And other modules in the same for loop using the same logic work just fine.  And ONE of module was working until recently when I had to change the module name in the GUI.

So I thought – maybe it’s been patched?

I just recompiled with both 46 and 47 to be sure and they both produce this new version of the error.  Same code – just recompiled with the same test input:
```
2022-01-19T02:48:16.821Z           e1c454a5-b247-4830-828b-bfc926786351             ERROR               Invoke Error       {
    "errorType": "TypeError",
    "errorMessage": "Converting circular structure to JSON\n    --> starting at object with constructor 'IncomingMessage'\n    |     property 'req' -> object with constructor 'ClientRequest'\n    --- property 'res' closes the circle",
    "stack": [
        "TypeError: Converting circular structure to JSON",
        "    --> starting at object with constructor 'IncomingMessage'",
        "    |     property 'req' -> object with constructor 'ClientRequest'",
        "    --- property 'res' closes the circle",
        "    at JSON.stringify (<anonymous>)",
        "    at /var/task/src/lambdas/CallFlowSync.js:1:12844",
        "    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
        "    at async m (/var/task/src/lambdas/CallFlowSync.js:1:12750)",
        "    at async Runtime.t.handler (/var/task/src/lambdas/CallFlowSync.js:1:23867)"
    ]
}
```
Which after some investigation was a JSON.stringify failing on the new error message which appears in 46 (this is the raw JSON spit out of it):
```
2022-01-19T03:52:33.678Z           2ea2bb95-a015-41d7-ae10-56c549d9bf9e             ERROR               src/lambdas/CallFlowSync.handler: ERROR InternalServerErrorException: Internal server error
    at deserializeAws_restJson1DescribeContactFlowModuleCommandError (/var/task/node_modules/@aws-sdk/client-connect/dist-cjs/protocols/Aws_restJson1.js:7780:41)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /var/task/node_modules/@aws-sdk/client-connect/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /var/task/node_modules/@aws-sdk/client-connect/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
    at async StandardRetryStrategy.retry (/var/task/node_modules/@aws-sdk/client-connect/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /var/task/node_modules/@aws-sdk/client-connect/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at async m (/var/task/src/lambdas/CallFlowSync.js:1:12750)
    at async Runtime.t.handler (/var/task/src/lambdas/CallFlowSync.js:1:23835) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 500,
    requestId: '93a9287d-9926-4f4d-b117-d67d99c29c17',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 3,
    totalRetryDelay: 364
  },
  '$response': HttpResponse {
    statusCode: 500,
    headers: {
      date: 'Wed, 19 Jan 2022 03:52:33 GMT',
      'content-type': 'application/json',
      'content-length': '36',
      connection: 'keep-alive',
      'x-amzn-requestid': '93a9287d-9926-4f4d-b117-d67d99c29c17',
      'access-control-allow-origin': '*',
      'access-control-allow-headers': '*',
      'x-amzn-errortype': 'InternalServerErrorException',
      'x-amz-apigw-id': 'MLKoRH20SwMFyBA=',
      'x-amzn-trace-id': 'Root=1-61e78b01-00dd90f355a3a8c530563cd7'
    },
    body: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      socket: null,
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 500,
      statusMessage: 'Internal Server Error',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [ClientRequest],
      [Symbol(kCapture)]: false,
      [Symbol(RequestTimeout)]: undefined
    }
  }
}
```

#### Expected behavior
It should return successfully as far as I can tell, there is no obvious reason as to why the response is InternalServerErrorException

#### Screenshots
NA

## Additional context
I cant add a lot more to this one as the cause is hidden behind Amazon Connect.  It could also be something IN those modules, but I cannot tell at this stage.  One thing that makes me think this ISNT the case, is one of my modules required a name change, and was working until AFTER the name change. 

The business requirement it: I need to import and export/synchonise/automate for CI/CD call flows between DEV/UAT/Prod etc Amazon Connect instances, and doing it by hand is prone to errors.

**Comment by dobrynin** [comment]
Also facing this but when trying to get an API Key from API Gateway.

**Comment by lspellman-opsguru** [comment]
Also facing this error: 
```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'IncomingMessage'
    |     property 'req' -> object with constructor 'ClientRequest'
    --- property 'res' closes the circle
```
but with DynamoDb client executing a put to add an item (first one) to an existing table.

**Comment by jannamamer** [comment]
Also encountering the same TypeError but on `DescribeLogStreamsCommand` of CloudWatch Logs Client



```
{
    "errorType": "TypeError",
    "errorMessage": "Converting circular structure to JSON\n    --> starting at object with constructor 'TLSSocket'\n    |     property '_httpMessage' -> object with constructor 'ClientRequest'\n    --- property 'socket' closes the circle",
    "stack": [
        "TypeError: Converting circular structure to JSON",
        "    --> starting at object with constructor 'TLSSocket'",
        "    |     property '_httpMessage' -> object with constructor 'ClientRequest'",
        "    --- property 'socket' closes the circle",
        "    at JSON.stringify (<anonymous>)",
    ]
}
```

My code
```
  const describeLogStreamsCommand = new DescribeLogStreamsCommand({
    logGroupName: logGroupName,
    logStreamNamePrefix: logStreamNamePrefix
  })

  const cloudwatchClient = new CloudWatchLogsClient({})
  const response =  await cloudwatchClient.send(describeLogStreamsCommand)
```

**Comment by yenfryherrerafeliz** [comment]
Hi @gailmiller, thanks for opening this issue. I tried to reproduce the reported behavior, but I was not able to. I think this maybe could be a problem with the definition of the flow, or maybe a service side issue, but without a reproducible case I can not assure anything. I would suggest you to try with the latest sdk version, which at the time I tested was 3.113.0. Another thing you could do is, to please try with the aws cli and if you get the same behavior we could reach out to the service team, to see if they see anything at their end. 
Here is the code I used:
 ```js
 import {
    ConnectClient,
    DescribeContactFlowModuleCommand,
} from "@aws-sdk/client-connect";

const instanceId = 'INSTANCE-ID';
const callFlowModuleId = 'FLOW-ID';
const params = {
    InstanceId: instanceId,
    ContactFlowModuleId: callFlowModuleId, // find the id in the input list matching or by name from returned list,
};
const connectClient = new ConnectClient({
    region: 'us-east-1'
});
const command = new DescribeContactFlowModuleCommand(params);
const response = await connectClient.send(command);

console.log('Response: ', response);
 ```
 
 Thanks!

**Comment by gailmiller** [comment]
hi @yenfryherrerafeliz ,
This was fixed back in version 50s (yes there was a legit bug, yes I was testing every version until it was resolved as I needed the code working).  Someone definitely fixed it, I am not sure who that was.  So correct, the problem no longer exists.  I had kind of assumed that this ticket was closed, I didn't realise it was still open.  Closing.
