### ISSUE TITLE
[s3] EPROTO error while PUTting a file

### ISSUE THREAD

**Issue by ffxsam** [aws/aws-sdk-js-v3#3219]
## Describe the bug
This bug occurs occasionally, while using `PutObjectCommand` to write a file to S3.

#### SDK version number
`@aws-sdk/client-s3@3.47.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
14.18.1

## Steps to reproduce
???

#### Observed behavior
Randomly, I get an EPROTO error while writing a file to S3: https://sentry.io/share/issue/d8c93d01f7a2438b82c63c610eb541f3/

#### Expected behavior
I would expect S3 PUT operations to work properly.

I realize this isn't much info to go on, but hopefully someone can help me troubleshoot this and figure out where the problem is occurring.

**Comment by matootie** [comment]
I'm seeing the same issue but with the `CopyObjectCommand`.

**Comment by florian-netlight** [comment]
The same problem occurs when sending a `GetObjectCommandInput` object, while the full error output is the following 
```javascript
{
    "errorType": "Error",
    "errorMessage": "write EPROTO",
    "code": "EPROTO",
    "errno": -71,
    "syscall": "write",
    "$metadata": {
        "attempts": 1,
        "totalRetryDelay": 0
    },
    "stack": [
        "Error: write EPROTO",
        "    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)"
    ]
}
```

**Comment by ttres** [comment]
I've saw a similar issue, on @aws-sdk/client-ecs: "^3.52.0" package for node.js (14.15.4), running on AWS Fargate ECS task. The workaround was to update the Config object, [set the maxRetries](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#maxRetries-property) and the 
[retryDelayOptions](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#retryDelayOptions-property). This caused a new API call to be executed shortly after the failed, without aborting the code.
Consider that it may be a good practice to update the [httpOptions timeout value](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#httpOptions-property), as well.

**Comment by rmclaughlin-nelnet** [comment]
Hi, is there an update to this? We are running into the same issue. Here is the error we are getting

```
ERROR   Unhandled Promise Rejection     
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "Error: write EPROTO",
    "reason": {
        "errorType": "Error",
        "errorMessage": "write EPROTO",
        "code": "EPROTO",
        "errno": -71,
        "syscall": "write",
        "$metadata": {
            "attempts": 1,
            "totalRetryDelay": 0
        },
        "stack": [
            "Error: write EPROTO",
            "    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: Error: write EPROTO",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:400:28)",
        "    at processPromiseRejections (internal/process/promises.js:245:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:96:32)"
    ]
}
```

**Comment by RanVaknin** [comment]
This is likely an issue with Node 14 which is now deprecated. Please upgrade to node 18.

Thanks,
Ran~
