### ISSUE TITLE
`GetBucketAclCommand` throws `SignatureDoesNotMatch` error

### ISSUE THREAD

**Issue by hitlk** [aws/aws-sdk-js-v3#322]
**Describe the bug**
It throws `SignatureDoesNotMatch` error when getting bucket acl.

**SDK version number**
`@aws-sdk/client-s3-node@0.1.0-preview.2`

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
v10.15.3

**To Reproduce (observed behavior)**
sample code
```javascript
const {S3Client} = require('@aws-sdk/client-s3-node')
const {GetBucketAclCommand} = require('@aws-sdk/client-s3-node/commands/GetBucketAclCommand')
const s3 = new S3Client({
    credentials: {
        accessKeyId: 'xxx',
        secretAccessKey: 'xxx'
    }
    region: 'us-east-1'
})
const getBucketAcl = new GetBucketAclCommand({
    Bucket: 'mock'
})
s3.send(getBucketAcl).then(data => console.log(data))
```

**Expected behavior**

**Screenshots**

**Additional context**
After some investigation, I found that the query string was omitted when signing.
Please see below
[https://github.com/aws/aws-sdk-js-v3/blob/03237744a276b095e07b06f3d678adcaf02c551f/packages/signature-v4/src/getCanonicalQuery.ts#L7-L40](https://github.com/aws/aws-sdk-js-v3/blob/03237744a276b095e07b06f3d678adcaf02c551f/packages/signature-v4/src/getCanonicalQuery.ts#L7-L40)
The request uri of`GetBucketAclCommand` is `"/{Bucket}?acl"`, and function `getCanonicalQuery` should return `acl` instead of empty string.

**Comment by ajredniwja** [comment]
Hey @hitlk, thank-you for reaching out to us with your issue.

Can you try using the alpha s3 client, using

```npm install @aws-sdk/client-s3```

Please reach out if the issue still persists.

**Comment by hitlk** [comment]
@ajredniwja 
I have tried and it works. Thanks.
