### ISSUE TITLE
Evaluate providing ESM artifact for Node.js once TypeScript provides stable support

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#3223]
### Is your feature request related to a problem? Please describe.
The AWS SDK for JavaScript (v3) currently does not provide a separate ESM artifact for Node.js
Users either use the CJS artifact or ES5 artifact.

### Describe the solution you'd like
TypeScript 4.5 added [Experimental Nightly-Only ECMAScript Module Support in Node.js](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#esm-nodejs).
The existing issues are being discussed [here](https://www.typescriptlang.org/docs/handbook/esm-node.html), and official documentation can be viewed [here](https://www.typescriptlang.org/docs/handbook/esm-node.html).

Provide ESM artifacts once TypeScript support gets stable.

### Describe alternatives you've considered
Not providing ESM artifacts for AWS SDK for JavaScript (v3) packages.

### Additional context
TypeScript version needs to be bumped to 4.6 with named export support before picking this up. Details in https://github.com/aws/aws-sdk-js-v3/issues/3217

**Comment by trivikr** [comment]
TypeScript 4.7 Beta added ECMAScript Module Support in Node.js
https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/#esm-nodejs

The TypeScript 4.7 Final will be released in late-May 2022.

**Comment by trivikr** [comment]
As per Node.js docs, we can also use an [ESM Wrapper](https://nodejs.org/api/packages.html#approach-1-use-an-es-module-wrapper) instead of emitting ESM artifacts.

**Comment by trivikr** [comment]
Revisiting after merging Node.js and browser utilities in `util-base64`
* clients https://github.com/aws/aws-sdk-js-v3/pull/4140
* packages https://github.com/aws/aws-sdk-js-v3/pull/4141

As we use `@tsconfig/node14` as base for clients, we can do the same for packages and follow-up experimenting with export maps with `dist-es/index.js` for ESM support.

**Comment by kuhe** [comment]
related: https://github.com/aws/aws-sdk-js-v3/issues/3622
