### ISSUE TITLE
InvalidSignatureException error with `GET` request

### ISSUE THREAD

**Issue by alisaliso** [aws/aws-sdk-js-v3#3247]
## Describe the bug
I'm making chat with @aws-sdk/client-chime-sdk-messaging and the `GET` requests return `InvalidSignatureException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.` error. The `POST` requests are working

#### SDK version number
`@aws-sdk/client-chime-sdk-messaging@3.48.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v16.13.2

## Steps to reproduce
```js
import { ChimeSDKMessagingClient, ListChannelMessagesCommand } from "@aws-sdk/client-chime-sdk-messaging";

const credentials = {
    accessKeyId: "accessKeyId",
    secretAccessKey: "secretAccessKey",
    sessionToken: "sessionToken"
};

const ChannelArn = "arn:aws:chime:us-east-1:ChannelArn";

const userArn = "arn:aws:chime:us-east-1:userArn";

const chimeClient = new ChimeSDKMessagingClient({
    region: "us-east-1",
    credentials
});

const params = {
    ChannelArn,
    MaxResults: 50,
    NextToken: null,
    ChimeBearer: userArn
};

const command = new ListChannelMessagesCommand(params);

try {
    const data = await chimeClient.send(command);
    console.log("listChannelMessages DATA ->", data);
} catch (error) {
    console.error("listChannelMessages ERROR ->", error);
}
```

#### Observed behavior
The `ListChannelMessagesCommand ` request returns `InvalidSignatureException` error

#### Expected behavior
Should return list of messages and nextToken

## Additional context
The problem occurs only for the `POST` requests, I've tried not to pass credentials directly but via env variables as suggest in this [issue](https://github.com/aws/aws-sdk-js-v3/issues/1569)

I've found similar open  [issue](https://github.com/aws/aws-sdk-js-v3/issues/2996), their suggestion was to use `POST` as `GET` request but I can't change requests method

**Comment by vudh1** [comment]
Hi @alisaliso `NextToken` is optional, so you do not need to include it in `params`, or `undefined` should be a correct input here.
