### ISSUE TITLE
Cannot set applyChecksum in S3 (client)

### ISSUE THREAD

**Issue by Narretz** [aws/aws-sdk-js-v3#3254]
The upgrading guide mentions that the option `s3DisableBodySigning` has been renamed to `applyChecksum`
https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md

However, the [S3(Client) class](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/interfaces/s3clientconfig.html) doesn't have the config option `applyChecksum`. So in turn, it's not possible for the signature to have applyChecksum = false. The whole code path is missing afaict.

This is especially frustrating, as `s3DisableBodySigning` in v2 is by default `true`. So the upgrade guide is also incomplete at this point.

#### SDK version number
`@aws-sdk/client-s3@^3.48.0`
`@aws-sdk/signature-v4@3.47.2`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v16.13.0

## Steps to reproduce
```
const space = new S3({
  endpoint,
  credentials: {
    accessKeyId: process.env.DO_S3_ACCESS_KEY_ID,
    secretAccessKey: process.env.DO_S3_SECRET_ACCESS_KEY,
  },
  applyChecksum: false,
});
```

#### Observed behavior
This will fail the typecheck, but even if you ignore that, outgoing requests to S3 will have something like  `x-amz-content-sha256': 'c2f1c48b1f90ffffaa1f6c642814ec7ba7af717f386af4d4fd84d9d00eb95c7d`,

#### Expected behavior
The request should have `'X-Amz-Content-Sha256': 'UNSIGNED-PAYLOAD'`.

**Comment by ajredniwja** [comment]
Would also need to update `UPGRADING.md`

**Comment by Narretz** [comment]
I guess it should look something like this:

```
import { S3 } from '@aws-sdk/client-s3';
import { SignatureV4 } from '@aws-sdk/signature-v4';
import { Sha256 } from '@aws-crypto/sha256-js';

const space = new S3({
  endpoint,
  credentials,
  signer: new SignatureV4({
    applyChecksum: false,
    credentials,
    region: 'us-east-1',
    uriEscapePath: false,
    service: 's3',
    sha256: Sha256,
  }),
});
```

As you can see you must set more values, where the values aren't 100% obvious. So it would definitely make sense to have applyChecksum somehow in the basic config

**Comment by yenfryherrerafeliz** [comment]
Hi @Narretz, sorry to hear about your issues. Would it be an option for you to provide the checksum when executing the put object request?, for example:

```js
import {PutObjectCommand, S3Client} from "@aws-sdk/client-s3";
import crypto from "crypto";

const client = new S3Client({
    region: 'us-east-2',
})
const body = 'BODY';
const response = await client.send(new PutObjectCommand({
    Bucket: process.env.TEST_BUCKET,
    Key: process.env.TEST_KEY,
    Body: body,
    ChecksumSHA256: crypto.createHash('SHA256').update(body).digest('base64')
}))

console.log(response)
```

Thanks!

**Comment by Narretz** [comment]
I actually didn't resolve this problem back when I posted. But when I used the new sdk a few months ago, I didn't encounter this problem. Either it was fixed in the sdk or by the s3 compatible Digitalocean spaces service I'm using. So this can be closed I think.
