### ISSUE TITLE
Too many concurrent S3 CopyObject calls results in EMFILE error

### ISSUE THREAD

**Issue by ffxsam** [aws/aws-sdk-js-v3#3270]
## Describe the bug

It seems that the `CopyObjectCommand` can't run more than a few hundred or so calls concurrently. Yet AWS support said it can do 3500 per second. I'm getting an EMFILE error. Details below.

#### SDK version number
`@aws-sdk/client-s3@3.49.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v14.18.1 locally (Lambda 14.x)

## Steps to reproduce
I have a simple bit of code that's copying several files (in this case, 1600 of them):

```ts
for (const fileBatch of _chunk(files, 2000)) {
    // eslint-disable-next-line no-await-in-loop
    await Promise.all(
      fileBatch.map(file =>
        file.sourceObj.copyTo(process.env.STORAGE_BUCKET, file.destKey)
      )
    );
  }
```

And `sourceObj.copyTo()` is a reference to my own abstraction:

```ts
  /**
   * Copy S3 object to another location, or an entirely different bucket.
   * @param bucket Bucket to copy to
   * @param key Destination key
   * @param storageClass Storage class
   */
  public async copyTo(
    bucket: string,
    key: string,
    storageClass: StorageClass = 'INTELLIGENT_TIERING'
  ): Promise<S3Object> {
    try {
      await S3Object.s3.send(
        new CopyObjectCommand({
          Bucket: bucket,
          CopySource: `/${this.bucket}/${this.key}`,
          Key: key,
          StorageClass: storageClass,
        })
      );
    } catch (e) {
      logS3Error(e, 'copyTo', {
        bucket: this.bucket,
        key: this.key,
        destBucket: bucket,
        destKey: key,
        storageClass,
      });
      throw e;
    }

    return new S3Object({
      bucket,
      key,
    });
  }
```

The Lambda invocation is failing, and I'm seeing this error in the logs:

```
{
    "errorType": "Error",
    "errorMessage": "connect EMFILE 52.216.243.120:443 - Local (undefined:undefined)",
    "code": "EMFILE",
    "errno": -24,
    "syscall": "connect",
    "address": "52.216.243.120",
    "port": 443,
    "$metadata": {
        "attempts": 1,
        "totalRetryDelay": 0
    },
    "stack": [
        "Error: connect EMFILE 52.216.243.120:443 - Local (undefined:undefined)",
        "    at internalConnect (net.js:934:16)",
        "    at defaultTriggerAsyncIdScope (internal/async_hooks.js:452:18)",
        "    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1077:9)",
        "    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:8)",
        "    at GetAddrInfoReqWrap.callbackTrampoline (internal/async_hooks.js:130:17)"
    ]
}
```

If I break the the chunks down into chunks of 200 vs 2000, then it works fine:

```ts
    for (const fileBatch of _chunk(files, 200)) {
      // eslint-disable-next-line no-await-in-loop
      await Promise.all(
        fileBatch.map(file =>
          file.sourceObj.copyTo(process.env.STORAGE_BUCKET, file.destKey)
        )
      );
    }
```

Not sure what's going on. Is the SDK doing some sort of file operation that would be causing this? Is there a temporary log file?

#### Observed behavior
See above.

#### Expected behavior
No error should be thrown by the SDK.

**Comment by ffxsam** [comment]
One additional detail, not sure if this matters:

The S3 client is using X-Ray:

```ts
  static s3 = process.env.IS_LOCAL
    ? new S3Client({ maxAttempts: 20 })
    : (AWSXRay.captureAWSv3Client(
        new S3Client({ maxAttempts: 20 }) as any
    ) as S3Client);
```

Is it possible X-Ray is doing something locally in the Node.js environment to cause this?

**Comment by adrai** [comment]
@ffxsam did this work better for you with an older version?
For me v3.46.0 was better: https://github.com/aws/aws-sdk-js-v3/issues/3019#issuecomment-1025461631

**Comment by ffxsam** [comment]
@adrai I haven't checked, but thanks for linking to that issue. I'll consider my issue a dupe and close it.
