### ISSUE TITLE
@aws-sdk/lib-dynamodb unmarshall is converting string set to empty object

### ISSUE THREAD

**Issue by chuckntaylor** [aws/aws-sdk-js-v3#3271]
## Describe the bug
When I use the `DynamoDBDocument.get()` from the @aws-sdk/lib-dynamodb package. I am getting unusual behavior where a string set type 'SS' is coming back as an empty object `{}`. I have two separate projects using this library and configuration, but only one project seems to be having this issue.

## Your environment
Mac OS 12.2
Node v16.13.0
NPM v8.1.0

#### SDK version number
`@aws-sdk/lib-dynamodb@3.49.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Node v16.13.0
NPM v8.1.0

## Steps to reproduce
Please share code or minimal repo, and steps to reproduce the behavior.

#### Observed behavior
Attached is an image of an Item in the database - taken from the AWS console. Please note, the `products` attribute is the string set I am having trouble with.
<img width="419" alt="Screen Shot 2022-02-01 at 11 59 03 AM" src="https://user-images.githubusercontent.com/17050325/152014653-9f7f2b4f-c520-4647-b78f-286504c6066b.png">

Here is a sample of the code used to retrieve the item from the database:
```ts
export const dbGetCode2 = async (input: { code: string }) => {
  const getParams: GetCommandInput = {
    TableName: CODES_TABLE,
    Key: {
      code: input.code,
    },
  }

  try {
    const response = await dbDocClient.get(getParams)
    if (!response || !response.Item) {
      return null
    } else {
      console.log('Code Found:', pretty(response.Item)) // pretty is just a util for JSON.stringify(obj, null, 2)
      return response.Item
    }
  } catch (err) {
    console.error(err)
    return null
  }
}
```

The end result ends up being this:
```
{
  "purpose": "INSTANT REDEEM CODE",
  "code": "MSYQC3T",
  "products": {},
  "redemption_email": "batman@gotham.org",
  "created_by": "ADMIN",
  "created": 1635774033596,
  "redeemed": true,
  "redemption_date": 1635774039291
}
```

#### Expected behavior
To have products come back as a `Set<string>`

## Additional context

I have done an additional experiment where I get the item using the `@aws-sdk/client-dynamodb@3.49.0` directly. Since it gives back the unmarshalled attributes, I see in this instance that all the data comes back. If I then unmarshall the attributes using `@aws-sdk/util-dynamodb@3.49.0`, I again have an empty object come back.

For what I have just described, here is application code I used in my experiment:

```ts
import { DynamoDBClient, GetItemCommand, GetItemCommandInput } from '@aws-sdk/client-dynamodb'
import { unmarshall } from '@aws-sdk/util-dynamodb'

const dbClient = new DynamoDBClient({ region: 'us-east-1' })

export const dbGetCode = async (input: { code: string }) => {
  const getParams: GetItemCommandInput = {
    TableName: CODES_TABLE,
    Key: {
      code: { S: input.code },
    },
  }

  const command = new GetItemCommand(getParams)

  const response = await dbClient.send(command)
  console.log('Response Raw', pretty(response.Item))
  console.log('Response UnMarshalled', pretty(unmarshall(response.Item)))
  if (response.Item) {
    return unmarshall(response.Item)
  }
  return null
}
```

The console logs that came back from this are:
```
Response Raw {
  "purpose": {
    "S": "INSTANT REDEEM CODE"
  },
  "code": {
    "S": "MSYQC3T"
  },
  "products": {
    "SS": [
      "dogBT",
      "dogHS"
    ]
  },
  "redemption_email": {
    "S": "batman@gotham.org"
  },
  "created_by": {
    "S": "ADMIN"
  },
  "created": {
    "N": "1635774033596"
  },
  "redeemed": {
    "BOOL": true
  },
  "redemption_date": {
    "N": "1635774039291"
  }
}
Response UnMarshalled {
  "purpose": "INSTANT REDEEM CODE",
  "code": "MSYQC3T",
  "products": {},
  "redemption_email": "batman@gotham.org",
  "created_by": "ADMIN",
  "created": 1635774033596,
  "redeemed": true,
  "redemption_date": 1635774039291
}
```

**Comment by chuckntaylor** [comment]
@pele7208 Nobody has responded thus far. I have been moving my project over to MongoDB Atlas as time permits.

**Comment by bellydrum** [comment]
Would also love an answer on this...

**Comment by sashee** [comment]
I encountered this also, and it's not a bug in the dynamodb utils. The string set is converted to a native JS Set, and the JSON.stringify outputs {} for that. See [here](https://github.com/aws/aws-sdk-js-v3/blob/main/packages/util-dynamodb/src/convertToNative.ts#L35).

If you want a string list (as is in my case), you can convert it to an array: ```[...unmarshall(response.Item).products]```

**Comment by A-ndy-git** [comment]
+1. Having the same problem as OP. A populated `Set<string>` is returned as `{}` from `@aws-sdk/lib-dynamodb`.

Can we up the priority of this? Seems like quite a major issue that the SDK isn't properly processing an intrinsic data type...

**Comment by RanVaknin** [comment]
Hi @chuckntaylor ,
I apologize for the late response. Thank you for the detailed reproduction steps. I will take a look into it.

**Comment by RanVaknin** [comment]
Hi @chuckntaylor ,

unfortunately I'm not able to reproduce your issue. Since this thread has lots of comments and upvotes I wonder if I misunderstood you, but here is my code(plain JS):

**_Boilerplate ddbDocClient.js_**
```js
import { DynamoDBDocumentClient} from "@aws-sdk/lib-dynamodb";
import { DynamoDBClient } from "@aws-sdk/client-dynamodb";

const REGION = "us-east-1"

const ddbClient = new DynamoDBClient({ region: REGION });

const marshallOptions = {
    convertEmptyValues: false, // false, by default.
    removeUndefinedValues: false, // false, by default.
    convertClassInstanceToMap: false, // false, by default.
};

const unmarshallOptions = {
    wrapNumbers: false, // false, by default.
};

const translateConfig = { marshallOptions, unmarshallOptions };

const ddbDocClient = DynamoDBDocumentClient.from(ddbClient, translateConfig);

export { ddbDocClient };


```

**_getItem.js_**
```js

import { ddbDocClient } from "./libs/ddbDocClient.js";
import { GetCommand } from "@aws-sdk/lib-dynamodb";

export const dbGetCode2 = async () => {
    
  const getParams =  {
      TableName: "CODES_TABLE",
      Key: {
        code: "MSYQ3T",
      }
    }
  
    try {
      const response = await ddbDocClient.send(new GetCommand(getParams))
      if (!response || !response.Item) {
        return null
      } else {
        console.log('Code Found:', response.Item) // pretty is just a util for JSON.stringify(obj, null, 2)
        return response.Item
      }
    } catch (err) {
      console.error(err)
      return null
    }
  }
  dbGetCode2();
```

**_Logs_**
```console
Code Found: {
  purpose: 'INSTANT REDEEM CODE',
  code: 'MSYQ3T',
  redemption_email: 'batman@gotham.org',
  products: Set(2) { 'dogBT', 'dogHS' },
  created_by: 'ADMIN',
  created: 1635774033596,
  redeemed: true,
  redemption_date: 1635774039291
}
```

Can you look at it and tell me if that helps at all? The sooner I can get your issue replicated the sooner I can submit a fix.

Thanks for your patience!

**Comment by RanVaknin** [comment]
Ahhh after reading some of the comments I see the issue.  
Let me know if you are unblocked (it has been a while..) and I can close the thread.

Thanks.

**Comment by chuckntaylor** [comment]
@RanVaknin , thanks for taking a look. I'm not sure why you were able to see Set(2) in your logs and I could not. I have admittedly moved everything to MongoDB, so I'm not technically 'blocked' anymore. Can you elaborate on where I went wrong?
