### ISSUE TITLE
S3 copyObjectCommand + getSignedUrl fails.

### ISSUE THREAD

**Issue by CraigglesO** [aws/aws-sdk-js-v3#3283]
## Describe the bug
When creating a signed url of a copy object, the URI is built incorrectly (one param is supposed to be a header, not a URI... more below)

#### SDK version number
'@aws-sdk/s3-request-presigner@^3.46.0'
'@aws-sdk/client-s3@^3.46.0'

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
node version: v16.13.2

## Steps to reproduce
Please share code or minimal repo, and steps to reproduce the behavior.

NOT WORKING:

```js
import fetch from 'node-fetch'
import { getSignedUrl } from '@aws-sdk/s3-request-presigner'
import { S3Client, CopyObjectCommand } from '@aws-sdk/client-s3'

const client = new S3Client({ region: 'ca-central-1' })

const url = await getSignedUrl(client, new CopyObjectCommand({
  Bucket: 'db-ca-central-1',
  Key: 'b.json',
  CopySource: 'db-us-east-1/a.json'
}), { expiresIn: 43_200 }).catch((err) => console.log(err))

console.log(url)

const res = await fetch(url, { method: 'PUT', headers: { 'x-amz-copy-source': 'db-us-east-1/a.json' } })
  .then(res => res.text())
  .catch(() => ({ err: 'Failed to upload chunk.' }))

console.log('res', res)
```

In this case the URI includes `X-Amz-SignedHeaders=host` HOWEVER there are two pain points here:

1) there is no documentation that I need to specify `x-amz-copy-source` as an included header. This took hours to figure out
2) With sdk-js-v3 the URI `X-Amz-SignedHeaders` doesn't include `x-amz-copy-source` and there is no way to add it because the code is (i believe) [incomplete](https://github.com/aws/aws-sdk-js-v3/blob/main/packages/s3-request-presigner/src/presigner.ts)

However, with the previous SDK, the URI is built correctly `X-Amz-SignedHeaders=host%3Bx-amz-copy-source` and adding in the header with the PUT request properly builds the file:

WORKING

```js
import fetch from 'node-fetch'
import S3 from 'aws-sdk/clients/s3.js'

const s3 = new S3({ region: 'ca-central-1', signatureVersion: 'v4' })

const url = await s3.getSignedUrlPromise('copyObject', {
  Bucket: 'db-ca-central-1',
  Key: 'b.json',
  Expires: 43_200, // 1 minute expire period.
  CopySource: 'db-us-east-1/a.json'
})

console.log(url)

const res = await fetch(url, { method: 'PUT', headers: { 'x-amz-copy-source': 'db-us-east-1/a.json' } })
   .then(res => res.text())
   .catch(() => ({ err: 'Failed to upload chunk.' }))

console.log('res', res)
```

Something interesting to note:

[as linked earlier](https://github.com/aws/aws-sdk-js-v3/blob/main/packages/s3-request-presigner/src/presigner.ts) I think an easy fix would be to add functionality described in the documents.

The [docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/interfaces/_aws_sdk_types.requestpresigningarguments-1.html) claim support for `signableHeaders` which I believe lets you add to the list of headers you're allowed to use.

Although, I think the best solution is to auto add support for the `x-amz-copy-source` header when using the `CopyObjectCommand` inside `getSignedUrl` and specify in the docs that you have to personally add the `x-amz-copy-source` header.

I wish the S3 environment could just read this information from the URI instead of the header though.

**Comment by RanVaknin** [comment]
Hi @CraigglesO ,

I'm not sure I quite understand the problem. Can you not generate a pre-signed url? Or can you not use the URL to make a put request with it?

I am able to do it with V3. When you add the `CopySource` field in your `CopyObjectCommand` that `x-amz-copy-source` will be attached to the signing request.


You can see in the presigned URL generated that it contains the correct header.
```
https://testbucket-3650.s3.us-east-1.amazonaws.com/test_item_123.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=REDACTED&X-Amz-Date=20220614T224003Z&X-Amz-Expires=43200&X-Amz-Signature=REDACTED&X-Amz-SignedHeaders=host&x-amz-copy-source=testbucket-3650%2Fmilk123.txt&x-id=CopyObject
```

You can log your middleware at the "build" stage to see the request header being added to the signer:
```console
HttpRequest {
  method: 'PUT',
  hostname: 's3.us-east-1.amazonaws.com',
  port: undefined,
  query: { 'x-id': 'CopyObject' },
  headers: { 'x-amz-copy-source': 'testbucket-3650/milk123.txt' },
  body: undefined,
  protocol: 'https:',
  path: '/testbucket-3650/test_item_123.txt'
}
```

I just omitted the `headers: { 'x-amz-copy-source': 'db-us-east-1/a.json' }` from your fetch call since you have that header already from building the updateCommand.

Let me know If I am missing anything.
Thanks!
