### ISSUE TITLE
Cannot find module after switching to yarn workspaces

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#329]
**Describe the bug**
Peer dependencies are not clickable after switching to yarn workspaces

**To Reproduce (observed behavior)**
* Clone the package and run `yarn`
* Open any file in VSCode which uses peer dependencies from monorepo (eg. node-http-handler.ts)
* Notice that it shows "Cannot find module" warning

![cannot-find-module](https://user-images.githubusercontent.com/16024985/63477110-8465fd80-c438-11e9-9013-7d4b789f8f43.png)

**Expected behavior**
Since yarn workspaces manages all dependencies in single node_modules in root folder, the module should be accessible from VSCode

**Comment by AllanFly120** [comment]
Provide a solution here for anyone may encounter this problem. This happens because the `.d.ts` is not available for `@aws-sdk/types`. You can run the following command to build the dependency packages in batch. For example, if you are working on `@aws-sdk/node-http-handler`, you can run:
```
lerna run pretest --scope '@aws-sdk/node-http-handler' --include-filtered-dependencies  
```

**Comment by trivikr** [comment]
👆the lerna run pretest command is successful with `yarn@1.17.3` and fails with `yarn@1.16.0`

**Comment by trivikr** [comment]
Example GitHub repo where peer dependencies are clickable even before build https://github.com/Izhaki/mono.ts

**Comment by trivikr** [comment]
We should try TypeScript project references to fix this issue https://www.typescriptlang.org/docs/handbook/project-references.html

**Comment by trivikr** [comment]
Fixed in https://github.com/aws/aws-sdk-js-v3/issues/1026
