### ISSUE TITLE
Ability to control config and credentials providers

### ISSUE THREAD

**Issue by moltar** [aws/aws-sdk-js-v3#3290]
### Is your feature request related to a problem? Please describe.

See https://github.com/aws/aws-sdk-js-v3/issues/3019

### Describe the solution you'd like

Ability to specify a provider for both config and credentials, and strictly adhere to that, without trying to fall back to other options, especially file reading from disk.

### Describe alternatives you've considered

https://github.com/aws/aws-sdk-js-v3/issues/3019#issuecomment-966900587

### Additional context

In the Lambda environments credentials are always in the environment, and config is not present on disk. Trying to read from disk causes too much resource usage (sockets) and thereby seeing a lot of errors during high loads.

**Comment by kuhe** [comment]
Does overriding the client config `credentialsProvider` function allow you to shut off file system reads?
