### ISSUE TITLE
Using HTTP/2 with Lambda

### ISSUE THREAD

**Issue by clhuang** [aws/aws-sdk-js-v3#3292]
### Is your feature request related to a problem? Please describe.
Would like to be able to send Lambda requests over HTTP/2 (in Node.js).

The current lambda client initializes the requestHandler with NodeHttpHandler by default, and despite supporting HTTP/2 requests, the following code fails as the service returns a 400 error:

```js
const { Lambda } = require('@aws-sdk/client-lambda');
const { NodeHttp2Handler } = require('@aws-sdk/node-http-handler');

const lambda = new Lambda({ region: 'us-west-2', requestHandler: new NodeHttp2Handler() });
lambda.listFunctions({}).then(console.log).catch(console.error);
```

### Describe the solution you'd like
The lambda endpoints appear to support HTTP/2 (see https://github.com/aws/aws-sdk-js/issues/2300), and it would be nice if the AWS v3 SDK actually sent HTTP/2 requests that the lambda service accepted.

### Describe alternatives you've considered
I have noticed that, by modifying the headers the NodeHttp2Handler sends, I am able to make the aforementioned snippet work. In particular, at this point in the code: https://github.com/aws/aws-sdk-js-v3/blob/main/packages/node-http-handler/src/node-http2-handler.ts#L88, I can set `[constants.HTTP2_HEADER_AUTHORITY]: undefined` (where it is normally an empty string) and that allows the lambda service to accept the HTTP/2 request and process it as expected.

Curious what is different about the lambda service, versus the other services that the sdk is configured by default to use HTTP/2, and why this header change makes a difference.

**Comment by jean343** [comment]
To make the workaround simpler, one can create a middleware.

```javascript

const lambda = new Lambda({ region: "us-west-2", requestHandler: new NodeHttp2Handler() });
lambda.middlewareStack.add(
  (next) => async (args) => {
    const { request } = args;
    request.headers[":authority"] = request.hostname;
    return next(args);
  },
  {
    step: "build",
    priority: "low",
    override: true,
  }
);

```

Let me know if this helps :)
