### ISSUE TITLE
@aws-sdk/s3-presigned-post conditions generated from fields should be escaped

### ISSUE THREAD

**Issue by jeanbmar** [aws/aws-sdk-js-v3#3312]
## Describe the bug

It's impossible to submit a field value which contains a $ character. It should be possible by escaping them according to (https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-HTTPPOSTConstructPolicy.html):

Escape Sequence | Description
-- | --
\\\ | Backslash
\\$ | Dollar symbol
\b | Backspace
\f | Form feed
\n | New line
\r | Carriage return
\t | Horizontal tab
\v | Vertical tab
\uxxxx | All Unicode characters

The upload will be rejected because the condition generated automatically here is not escaped:
https://github.com/aws/aws-sdk-js-v3/blob/c376e57bcd41d2c26af2a1434dc45abaa0fe1326/packages/s3-presigned-post/src/createPresignedPost.ts#L65

Escaping a value prior to submit it isn't a valid solution since it will change the stored value as far as I know. If I can store a metadata containing "$" using the AWS console, I should be able to store it as well from a post request. Right now it's impossible.

#### SDK version number
`@aws-sdk/s3-presigned-post@3.20.0`

#### Is the issue in the browser/Node.js/ReactNative?
Browser and Node.js

#### Details of the browser/Node.js/ReactNative version
Node.js 16.13.1

## Steps to reproduce

Create an upload with a meta field containing a $ character, and submit it.
```js
const { url, fields } = await createPresignedPost(client, {
        Bucket: BUCKET,
        Key: 'abc',
        Fields: {
            'x-amz-meta-whatever': '123$$123',
        },
    });
```

#### Observed behavior
Upload fails with policy issue.

#### Expected behavior
We should be able to store a plain $ in a metadata field. We can do it in the AWS console.

## Additional context
Solution could be to escape the value at https://github.com/aws/aws-sdk-js-v3/blob/c376e57bcd41d2c26af2a1434dc45abaa0fe1326/packages/s3-presigned-post/src/createPresignedPost.ts#L65

**Comment by jeanbmar** [comment]
I've monkey-patched to escape as `\$` and it doesn't work. `${$}` doesn't work either. Smells like a server-side issue bug :(.

**Comment by RanVaknin** [comment]
Hi @jeanbmar ,

I am having a problem reproducing your issue. Sending the request from my Node environment works just fine:

**My code:**
```js
import { createPresignedPost } from "@aws-sdk/s3-presigned-post";
import { S3Client } from "@aws-sdk/client-s3";

const client = new S3Client({ region: "us-east-1" });

let config ={
    Bucket: "testbucket",
    Key: 'abc',
    Fields: {
        'x-amz-meta-whatever': '123$$123',
    }
}

try {
    const response = await createPresignedPost(client, config);
    console.log(response)
} catch (error) {
    console.log(error)
}

```

**Logs:**

```console
{
  url: 'https://s3.us-east-1.amazonaws.com/testbucket-3650',
  fields: {
    'x-amz-meta-whatever': '123$$123',
    bucket: 'testbucket-3650',
    'X-Amz-Algorithm': 'AWS4-HMAC-SHA256',
    'X-Amz-Credential': 'REDACTED/20220616/us-east-1/s3/aws4_request',
    'X-Amz-Date': '20220616T210700Z',
    key: 'abc',
    Policy: <your policy / auto generated policy here>,
    'X-Amz-Signature': REDACTED
  }
}
```

Do you get a policy error when submitting a form with this presigned POST? Or when generating this pre-sign?.
If you can share some actual code, and a stacktrace that would help me reproduce.

Thank you very much!
