### ISSUE TITLE
npm i @aws-sdk/client-s3 installation error

### ISSUE THREAD

**Issue by ognitio-technologies** [aws/aws-sdk-js-v3#3337]
## Describe the bug
Showing error installing npm i @aws-sdk/client-s3

#### SDK version number
@aws-sdk/client-s3 3.52.0

#### Screenshots
<img width="1139" alt="Screenshot 2022-02-19 at 5 45 03 PM" src="https://user-images.githubusercontent.com/72864567/154800320-b8f7894d-eada-4d75-8075-7ee9302ea133.png">

Error: 
arun@Aruns-MacBook-Air eventshut-ui-mainnet % npm i npm install @aws-sdk/client-s3
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
npm ERR! code 1
npm ERR! path /Users/arun/Development/Ognitio/Eventshut/Frontend/eventshut-ui-mainnet/node_modules/aws-crt
npm ERR! command failed
npm ERR! command sh -c node ./scripts/install.js
npm ERR! info TOOL Using Unix Makefiles generator.
npm ERR! info TOOL Building only the install target, as specified from the command line.
npm ERR! ERR! OMG CMake executable is not found. Please use your system's package manager to install it, or you can get installers from there: http://cmake.org.
npm ERR! /Users/arun/Development/Ognitio/Eventshut/Frontend/eventshut-ui-mainnet/node_modules/cmake-js/lib/cMake.js:117
npm ERR!         throw new Error("CMake executable is not found. Please use your system's package manager to install it, or you can get installers from there: http://cmake.org.");
npm ERR!               ^
npm ERR! 
npm ERR! Error: CMake executable is not found. Please use your system's package manager to install it, or you can get installers from there: http://cmake.org.
npm ERR!     at CMake.verifyIfAvailable (/Users/arun/Development/Ognitio/Eventshut/Frontend/eventshut-ui-mainnet/node_modules/cmake-js/lib/cMake.js:117:15)
npm ERR!     at CMake.build (/Users/arun/Development/Ognitio/Eventshut/Frontend/eventshut-ui-mainnet/node_modules/cmake-js/lib/cMake.js:287:10)
npm ERR!     at BuildSystem._invokeCMake (/Users/arun/Development/Ognitio/Eventshut/Frontend/eventshut-ui-mainnet/node_modules/cmake-js/lib/buildSystem.js:70:40)
npm ERR!     at async buildFromRemoteSource (/Users/arun/Development/Ognitio/Eventshut/Frontend/eventshut-ui-mainnet/node_modules/aws-crt/scripts/build.js:151:5)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/arun/.npm/_logs/2022-02-19T12_10_12_073Z-debug-0.log
arun@Aruns-MacBook-Air eventshut-ui-mainnet % 

attached

**Comment by vudh1** [comment]
Hi @ognitio-technologies thanks for reaching out. I suspect this is because of `aws-crt`. Please install this first and try to install the s3 client again.

```
$ yarn add aws-crt
```
