### ISSUE TITLE
@aws-sdk/lib-storage package.json

### ISSUE THREAD

**Issue by Fzlw** [aws/aws-sdk-js-v3#3351]
## Describe the bug
In @aws-sdk/lib-storage package.json
I think `browser` has a problem
"./runtimeConfig": "./src/runtimeConfig.browser"
"./dist-es/runtimeConfig": "./dist-es/runtimeConfig.browser"
reference @aws-sdk/client-cognito-identity

#### SDK version number
`@aws-sdk/client-s3@3.52.0`
`@aws-sdk/lib-storage@3.52.0`

#### Is the issue in the browser/Node.js/ReactNative?
Browser

#### Details of the browser/Node.js/ReactNative version
`Browsers:
    Chrome: 98.0.4758.109
    Firefox: 96.0.3
    Safari: 14.1`

## Steps to reproduce
Please share code or minimal repo, and steps to reproduce the behavior.

#### Observed behavior
A clear and concise description of what happens.

#### Expected behavior
A clear and concise description of what you were expecting to happen.

**Comment by jonaswitt** [comment]
Running into the same issue using @aws-sdk/lib-storage 3.67.0, looks like the PR #3352 is exactly what's needed!

**Comment by daddz** [comment]
Also running into this issue. Any ETA for merging the fix @aws-sdk-js-team?

**Comment by RanVaknin** [comment]
@Fzlw , @jonaswitt , @daddz 
Thank you for your patience. the fix has been merged.

@Fzlw thank you for your contribution! 👏
