### ISSUE TITLE
Support for waitUntilServicesStable

### ISSUE THREAD

**Issue by PhilLavoie** [aws/aws-sdk-js-v3#3359]
### Is your feature request related to a problem? Please describe.
When you programmatically update a service, for example, you would like to be able to check that it succeeds.

### Describe the solution you'd like
This solution is already implemented in the [AWS CLI](https://docs.aws.amazon.com/cli/latest/reference/ecs/wait/services-stable.html) and the [AWS SDK JS V2](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ECS.html#servicesStable-waiter).

### Describe alternatives you've considered
Well, I've considered going back to the SDK V2. In the meantime, I think I'm going to look at the source code and do something similar.

### Additional context
None

**Comment by jensiepoo** [comment]
+1 on this
