### ISSUE TITLE
AWS SDK v3 UpdateItemCommand TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by jdiegosierra** [aws/aws-sdk-js-v3#3365]
## Describe the issue with documentation
I'm not able to do an update an item using SDK v3 and I'm following the documentation https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/interfaces/updateitemcommandinput.html

## Steps to reproduce
Described here https://stackoverflow.com/questions/70980349/aws-sdk-v3-transactwriteitemscommand-typeerror-cannot-read-property-0-of-unde

I'm using this configuration 
```
  "TableName": "boxes",
  "Key": {
      "id": "36"
  },
  "UpdateExpression": "set isOpen = :isOpen",
  "ExpressionAttributeValues": {
      ":isOpen": {
          "BOOL": true
      }
  }
```

**Comment by flanamacca** [comment]
So the issue is your key.  You need to define the type of the key as well

SO 
 "Key": {
      "id": {"S": "36"}
  },


I had to debug the code to work this out.  

    AttributeValue.visit = (value, visitor) => {
        if (value.S !== undefined)
            return visitor.S(value.S);
        if (value.N !== undefined)
            return visitor.N(value.N);
        if (value.B !== undefined)
            return visitor.B(value.B);
        if (value.SS !== undefined)
            return visitor.SS(value.SS);
        if (value.NS !== undefined)
            return visitor.NS(value.NS);
        if (value.BS !== undefined)
            return visitor.BS(value.BS);
        if (value.M !== undefined)
            return visitor.M(value.M);
        if (value.L !== undefined)
            return visitor.L(value.L);
        if (value.NULL !== undefined)
            return visitor.NULL(value.NULL);
        if (value.BOOL !== undefined)
            return visitor.BOOL(value.BOOL);
        return visitor._(value.$unknown[0], value.$unknown[1]);   // <!--- This is the fail
    };

So 2 parts here:
1) The error condition is broken
2) The tutorial needs to be updated

Hope that helps everyone!

**Comment by jdiegosierra** [comment]
Thanks @flanamacca!!!
