### ISSUE TITLE
Missing/invalid dependency declaration on @aws-sdk/signature-v4-crt

### ISSUE THREAD

**Issue by oliversalzburg** [aws/aws-sdk-js-v3#3375]
## Describe the bug
Using certain parts of the SDK does not work, because the dependency declarations are invalid.

#### SDK version number
`@aws-sdk/client-s3@npm:3.53.1`
`@aws-sdk/s3-request-presigner@npm:3.53.1`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
`v16.14.0`

## Steps to reproduce
`yarn install @aws-sdk/client-s3`

#### Observed behavior
Received warnings about invalid/missing dependency declarations:
```shell
➤ YN0002: │ @aws-sdk/client-s3@npm:3.53.1 doesn't provide @aws-sdk/signature-v4-crt (p3de4d), requested by @aws-sdk/middleware-sdk-s3
➤ YN0002: │ @aws-sdk/s3-request-presigner@npm:3.53.1 doesn't provide @aws-sdk/signature-v4-crt (pb9ba7), requested by @aws-sdk/middleware-sdk-s3
```

#### Expected behavior
Missing dependency declarations of this kind are not allowed in our code base, which requires us to fix the SDK itself through manual patches. The SDK should have proper dependency declarations that allow installation without warnings/errors and should not require consumers to patch the SDK themselves.

## Additional context
For other consumers who struggle with the same issue, it can be worked around with the following package extensions:
```yml
packageExtensions:
  "@aws-sdk/client-s3@*":
    dependencies:
      "@aws-sdk/signature-v4-crt": "*"
  "@aws-sdk/s3-request-presigner@*":
    dependencies:
      "@aws-sdk/signature-v4-crt": "*"
```

**Comment by RanVaknin** [comment]
Hi @oliversalzburg,

The `aws-crt` package is large, so we intentionally exclude it from the `@aws-sdk/client-s3` package.

You can read more about it [here](https://github.com/aws/aws-sdk-js-v3/issues/2822), but I saw you commented on this issue in the past so you might be aware of it already.

Please consider contributing to our documentation with your workaround.

Thank you!

**Comment by oliversalzburg** [comment]
This is not a documentation issue. This was an issue with your dependency declarations. You have fixed it in the meanwhile. Probably in 16aa22042c92b33c702f775b87e830fb767e479c. Thanks for the attentive support.
