### ISSUE TITLE
TypeError: Class extends value undefined is not a constructor or null in @aws-sdk/client-cloudwatch-events

### ISSUE THREAD

**Issue by garayush** [aws/aws-sdk-js-v3#3389]
## Describe the bug
On using 3.53.0 version of "@aws-sdk/client-*" packages, we are getting the following error on running our tests:

```
TypeError: Class extends value undefined is not a constructor or null
      at Object.<anonymous> (node_modules/@aws-sdk/client-cloudwatch-events/dist-cjs/models/CloudWatchEventsServiceException.js:5:64)
      at Object.<anonymous> (node_modules/@aws-sdk/client-cloudwatch-events/dist-cjs/models/models_0.js:7:44)
```

#### SDK version number
`@aws-sdk/client-cloudwatch-events@3.53.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`
```
npx envinfo --browsers
  Browsers:
    Chrome: 98.0.4758.109
    Firefox: 91.6.0
    Safari: 15.3

node -v
v16.13.1
```
## Steps to reproduce
On running lerna bootstrap and npm watch, tests fail

#### Observed behavior
```
 FAIL  packages/lambda/test/api/schema.unit.ts
  ● Test suite failed to run

    TypeError: Class extends value undefined is not a constructor or null

      at Object.<anonymous> (node_modules/@aws-sdk/client-cloudwatch-events/dist-cjs/models/CloudWatchEventsServiceException.js:5:64)
      at Object.<anonymous> (node_modules/@aws-sdk/client-cloudwatch-events/dist-cjs/models/models_0.js:7:44)
```

#### Expected behavior
Tests should pass

## Additional context
Contents of CloudWatchEventsServiceException.js

```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CloudWatchEventsServiceException = void 0;
const smithy_client_1 = require("@aws-sdk/smithy-client"); <--- CODE BREAKING HERE
class CloudWatchEventsServiceException extends smithy_client_1.ServiceException {
    constructor(options) {
        super(options);
        Object.setPrototypeOf(this, CloudWatchEventsServiceException.prototype);
    }
}
exports.CloudWatchEventsServiceException = CloudWatchEventsServiceException;
```

**Comment by nazreen** [comment]
Hey! I had the very same error and the culprit was duplicated dependencies

I had `smithy-client` version 3.49.0 alongside 3.55.0
There were many versions as each @aws-sdk sub-package would have its own `@aws-sdk/smithy-client`

I fixed it by updating all my `@aws-sdk` sub packages (i.e. client-sts, client-dynamodb) to the same latest version.

**Comment by RanVaknin** [comment]
Hi @garayush ,

Unfortunately I cannot replicate your error without having any code from your application. 
You mentioned you are running tests. Can you share that code? Accurate steps to reproduce? 

Here is a [good example](https://github.com/aws/aws-sdk-js-v3/issues/3425) of how steps to reproduce should look. The more info the better.
Thanks.

**Comment by garayush** [comment]
> Hey! I had the very same error and the culprit was duplicated dependencies
> 
> I had `smithy-client` version 3.49.0 alongside 3.55.0 There were many versions as each @aws-sdk sub-package would have its own `@aws-sdk/smithy-client`
> 
> I fixed it by updating all my `@aws-sdk` sub packages (i.e. client-sts, client-dynamodb) to the same latest version.

This worked for me! Thanks!
