### ISSUE TITLE
GetObjectCommand stuck after some time

### ISSUE THREAD

**Issue by dudilugasi** [aws/aws-sdk-js-v3#3391]
## Describe the bug
i have an express server that serves files from s3. after a few hours, when i tryng to get a file from GetObjectCommand i get no reponse at all, and freeze. no error is sent, no response, nothing...

## Your environment
linux docker

#### SDK version number
`@aws-sdk/client-s3@^3.48.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
node v14.18.3

## Steps to reproduce
const { S3Client, GetObjectCommand } = require('@aws-sdk/client-s3')

const express = require('express')
const app = express()
const port = 3000

app.get('/', (req, res) => {
	const command = new GetObjectCommand({
		Bucket: "***",
		Key: "****"
	});

	let response = await s3.send(command);
	
	res.pipe(response.Body)
})

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
})

#### Observed behavior
after of a few hours of use we can get a response from s3

#### Expected behavior
the file should be downloaded

**Comment by net-monitor** [comment]
It happened when we try to reuse the command.
the first time we get body: null from the response, after retry we get stuck from AWS lib in send command without get any response or error

**Comment by RanVaknin** [comment]
Hi @dudilugasi ,

I'm having a hard time understanding what happens. What you are describing is not a known issue with the SDK. Is your linux container and server running locally and you letting your computer sleep? Sometimes a Node server will have to be rebooted after the computer is sleeping, Im not sure what default behavior for a Docker container is.

Additionally, I'm not sure if you copied your code directly from your file, but a lot of it does not make any sense. It's missing the initialization of the S3 and should not work without it.  Also, you are calling the GetObjectCommand with an asterisk * as if you are trying to fetch all object in the bucket and pipe them in the response. If you are trying to fetch all the object from a bucket then use the [`ListObjectCommand`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/classes/listobjectscommand.html)

If you can give me more context of what you are trying to do, I can try to replicate your environment and issue.
