### ISSUE TITLE
No support for Chinese characters?

### ISSUE THREAD

**Issue by ffxsam** [aws/aws-sdk-js-v3#3397]
## Describe the bug
A customer of ours tried to invoke a Lambda function (from the browser) which passed a payload including Chinese characters, and the characters were rejected:

`InvalidRequestContentException: Could not parse request body into json: Could not parse payload into json: Invalid UTF-8 start byte 0x97
 at [Source: (byte[])"{"userId":"fe420afc-ae45-4bad-8afa-d05d254e5328","id":"1c3946fd-fcd8-4917-adb1-8dad49ea793b","replace":false,"fileId":"3c2b3869-2138-4bcd-8273-ed439bde7785","fileCategory":"audio","bucket":"xx","key":"staging/audio/3c2b3869-2138-4bcd-8273-ed439bde7785.wav","duration":56.748798,"originalFilename":"�� OST�& Background S01 �p�.wav"}"; line: 1, column: 334]`

We're converting the payload to a Uint8Array, which might be the problem. If I test using Uint16Array, I can see the characters are preserved:

```js
const name = '暗夜长梦';
const uintArray = new Uint16Array(Array.from(name).map(c => c.charCodeAt(0)));

console.log(
  Array.from(uintArray).map(ascii => String.fromCharCode(ascii)).join('')
);
// Output: '暗夜长梦'
```

#### SDK version number
`@aws-sdk/client-lambda@3.53.0`

#### Is the issue in the browser/Node.js/ReactNative?
Browser

#### Details of the browser/Node.js/ReactNative version
```
  Browsers:
    Brave Browser: 91.1.26.74
    Chrome: 98.0.4758.109
    Firefox: 97.0.1
    Safari: 15.3
```

## Steps to reproduce
```js
function stringToUint8Array(str: string): Uint8Array {
  return new Uint8Array(Array.from(str).map(c => c.charCodeAt(0)));
}

const data = await lambda.send(new InvokeCommand({
  FunctionName: 'xyz',
  Payload: stringToUint8Array(
    JSON.stringify(payload)
  ),
}));
```

#### Observed behavior
Chinese characters are not decoded properly.

#### Expected behavior
I would expect the InvokeCommand to accept Uint16Array. Unfortunately, if I pass a Uint16Array, I get an error response from the invocation: `Unexpected end of JSON input`

**Comment by ffxsam** [comment]
I've addressed this with a simple workaround:

```js
import * as Base64 from 'js-base64';

Payload: stringToUint8Array(
  JSON.stringify({
    originalFilename: Base64.encode(filename),
  })
)
```

**Comment by AllanZhengYP** [comment]
Hi @ffxsam 

Can you try whether supplying the string of the JSON to the Payload parameter directly? Even if we mark the `Payload` parameter as `Uint8Array` type, the `string` should still be valid input. If it works, we should consider widening the input types to `TypedArray | Blob | Buffer | string`. Please comment here if it solves the problem or not.

**Comment by ffxsam** [comment]
Yep, this worked!

```ts
      const params = {
        FunctionName: process.env.VUE_APP_PROCESSOR_LAMBDA_NAME,
        Payload: JSON.stringify({
          userId: rootState.auth.user.userId,
          id: mediaId,
          replace: !!replaceMediaId,
          fileId,
          fileCategory: fileType.category,
          bucket: process.env.VUE_APP_UPLOAD_BUCKET,
          key: destKey,
          duration,
          originalFilename: filename,
        }),
      } as unknown as InvokeCommandInput;
```

I generally find the `Uint8Array` type requirement to be problematic and difficult to work with, as it requires too much casting:

```ts
const data = JSON.parse(Buffer.from(data.Payload!).toString());
```

And now that I've realized the shortcomings of `Uint8Array` when it comes to non-Latin languages, I really do wish we could just use `string` types throughout the SDK without getting TypeScript errors.

**Comment by ffxsam** [comment]
@RanVaknin Hey Ran! Any particular reason why was this reopened? Is it still an issue that someone's planning on solving in a more official capacity?

**Comment by RanVaknin** [comment]
@ffxsam ,

Might have been opened by mistake. 
sorry.
