### ISSUE TITLE
SignatureV4 Presign without Session Token

### ISSUE THREAD

**Issue by kazkansouh** [aws/aws-sdk-js-v3#3417]
## Describe the bug

From [sigv4-create-canonical-request.html](https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html) it has the following:

> For some services, you must include the X-Amz-Security-Token query parameter in the canonical (signed) query string. For other services, you add the X-Amz-Security-Token parameter at the end, after you calculate the signature. For details, see the API reference documentation for that service.

Unfortunately, the `@aws-sdk/signature-v4` does not support this feature during pre-sign. It assumes that if the session token is present it will always add the `X-Amz-Security-Token` canonical query string. This means its not possible to generate a pre-signed URL for some services. E.g. `iotdevicegateway` is one example of such a service.

A configuration option should be added to the `presign` function to support this feature.

#### SDK version number
`@aws-sdk/signature-v4@3.54.0`

#### Is the issue in the browser/Node.js/ReactNative?

Observed in browser/React - but should affect all.

#### Details of the browser/Node.js/ReactNative version
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`

```
$ npx envinfo --browsers
  Browsers:
    Chrome: 99.0.4844.51
    Firefox: 91.7.0esr
```

## Steps to reproduce

Generate temporary credentials with `sts` and then use the `SignatureV4.presign` function to generate a URL for the `iotdevicegateway` service. This will result in a request that is rejected with a `403` HTTP error.

Below is some code demonstrating this:
```javascript
import { SignatureV4 } from '@aws-sdk/signature-v4'
import { Sha256 } from '@aws-crypto/sha256-js'
import { HttpRequest } from '@aws-sdk/protocol-http'
import { formatUrl } from '@aws-sdk/util-format-url'

const signer = new SignatureV4({
  credentials,
  region: 'eu-west-2',
  service: 'iotdevicegateway',
  sha256: Sha256,
})
const req = new HttpRequest({
  protocol: 'wss',
  hostname: 'xxxxxxxxxxxxxx-ats.iot.eu-west-2.amazonaws.com',
  path: '/mqtt',
  method: 'GET',
  headers: { host: 'xxxxxxxxxxxxxx-ats.iot.eu-west-2.amazonaws.com' },
})
signer.presign(req, { expiresIn: 3600 }).then((req) => {
  console.log(req)
  console.log(formatUrl(req))
}
```

In the above `credentials` is obtained using `@aws-sdk/credential-providers`. Importantly, the credential obtained has `sessionToken` set.

#### Observed behavior

Pre-signed request is rejected with HTTP 403 - forbidden.

#### Expected behavior

Pre-signed request is is accepted.

## Additional context

After looking at the source code, there is a workaround by removing the `sessionToken` from the credential and then adding it back in after the request has been pre-signed. See the following code:

```javascript
credentials().then((credentials) => {
  const signer = new SignatureV4({
    credentials: { ...credentials, sessionToken: undefined },
    region: 'eu-west-2',
    service: 'iotdevicegateway',
    sha256: Sha256,
  })
  const req = new HttpRequest({
    protocol: 'wss',
    hostname: 'xxxxxxxxxxxxxx-ats.iot.eu-west-2.amazonaws.com',
    path: '/mqtt',
    method: 'GET',
    headers: { host: 'xxxxxxxxxxxxxx-ats.iot.eu-west-2.amazonaws.com' },
  })
  signer.presign(req, { expiresIn: 3600 }).then((req) => {
    if (
      typeof credentials.sessionToken === 'string' &&
      typeof req.query === 'object'
    ) {
      req.query['X-Amz-Security-Token'] = credentials.sessionToken
    }
    console.log(req)
    console.log(formatUrl(req))
  }
}
```

While this works, it is not ideal as it relies on internal behaviour of the SDK.

**Comment by huntharo** [comment]
@kazkansouh - I tried reproducing this issue using the new Lambda URLs that support IAM signing.

I was able to submit signed and presigned requests without issue without using your workaround (which I had tried but it failed due to a temporary bug with query strings being passed to Lambda URLs when signing was enabled).

I'm curious if you could try sending a request with your code (without the workaround on session token) to a Lambda URL that you have deployed.  If that works then the issue may be more a bug (perhaps one that they have to keep now for backwards compatibility) or a spec difference used by IOT that the libraries currently do not support well.

I created a repo here that deploys a Lambda URL that requires IAM auth and a CLI tool that signs/presigns the requests and sends them, showing that there is no issue when the target is something other than IOT:

https://github.com/huntharo/lambda-url-signing

**Comment by kazkansouh** [comment]
Hello @huntharo, thankyou for the info.

I've taken a look at your code but not run it. Just to help clarify the [comment in your code](https://github.com/huntharo/lambda-url-signing/blob/cb2bbafbd05dfa30ef6bf5579ec197fc1369c943/packages/cli/src/index.ts#L32-L35):

The underlying issue is that different AWS API endpoint can expect the SigV4 to be computed slightly differently w.r.t. how the the session token is handled. Probably because the services are built by different teams and they like to keep backwards compatibility. If it works for you with the `lambda` service you should be fine. I have only experienced the issue with `iotdevicegateway`, but other services could also follow the same interpretation - which is explicitly allowed in the SigV4 documentation.

This bug post was a suggestion that the `presign` function supports both interpretations.

**Comment by kazkansouh** [comment]
Hello @RanVaknin. To answer your questions. I used this to presign the WSS URL for the MQTT broker in AWS IoT Core. This was within an SPA to view/control IoT devices. Session tokens were obtained from Cognito along with policies that limit their access on the MQTT service. Originally I looked at IoT SDK but it was not appropriate as it is intended for end devices and not an SPA/control app. Further, the IoT JS SDK is designed for node and makes use of c libraries along with lots of additional features for dealing with items like device shadows which is not needed in the control application.

I am not the only person to come across this need, see below:

* https://github.com/aws/aws-sdk-js/issues/1456#issuecomment-296127524
* https://stackoverflow.com/a/53320582 (wrong solution as session token not handled, see comment, but shows how easy it is to run into this problem)
* https://github.com/aws/aws-sdk-go/issues/2485#issuecomment-469366846
* https://github.com/pedrohbtp/aws_signv4_mqtt (another project which wrote SigV4 from scratch because of this issue)
* https://github.com/aws/aws-sdk-js/issues/2254#issuecomment-423697986

There are more links, but hopefully you get the idea. In reality, the required change to the presign function would be minimal and be backwards compatible. Adding a optional Boolean flag to enable the alternative SigV4 interpretation and two simple if statements around handling the session token is all that is needed.
