### ISSUE TITLE
Retry on RDSDataClient's "Communications link failure"

### ISSUE THREAD

**Issue by susovan87** [aws/aws-sdk-js-v3#3425]
## Describe the bug
`RDSDataClient`'s `send` operation is failing frequently as Serverless Aurora Data API automatically pause after certain idle period. Configuring `RDSDataClientConfig`'s `maxAttempts` has no effect on retry behaviour. The `response.$metadata.attempts` on the error response of the failed call is always showing `1`.

Please note, the same issue [aws-sdk-js/issues/2914](https://github.com/aws/aws-sdk-js/issues/2914) has been fixed on **[aws-sdk-js](https://github.com/aws/aws-sdk-js) v2** as part of [aws-sdk-js/pull/2931](https://github.com/aws/aws-sdk-js/pull/2931). Similar fix is needed for the **v3**.

## Your environment
Reproducible while running code on `Node 14` locally as well as inside AWS Lambda.

#### SDK version number
`@aws-sdk/client-rds-data@3.53.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
`Node v14.18.3` inside docker image `public.ecr.aws/lambda/nodejs:14`

## Steps to reproduce
1. Create a Serverless Aurora cluster [instructions](https://docs.aws.amazon.com/en_pv/AmazonRDS/latest/AuroraUserGuide/aurora-serverless.create.html)
2. With the "pause compute capacity after consecutive minutes of inactivity" set to the minimum of 5 minutes
3. Once commissioned wait 5-10 minutes for Aurora to scale to 0 capacity units (i.e. paused).
4. Run minimal query script below (replacing ARNs as required) - it will fail with the error reported above.
Wait ~30-60 seconds and re-run the query script - it will return a result.
```javascript
import { RDSDataClient, ExecuteStatementCommand } from "@aws-sdk/client-rds-data";

const client = new RDSDataClient({
  region: 'us-east-1',
  maxAttempts: 10,
});

async function main() {
  const command = new ExecuteStatementCommand({
    sql: 'select * from information_schema.tables',
    secretArn: '***',
    resourceArn: '***',
    database: '***',
  });
  try {
    const result = await client.send(command);
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error(error);
  }
}
main();
```

#### Observed behavior
After 5-10 minutes of inactivity, Aurora to scale to 0 capacity units (i.e. paused). Then if you run the above code, it is giving below error response
```
BadRequestException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.; SQLState: 08S01
    at deserializeAws_restJson1BadRequestExceptionResponse (/Users/sughosh/Documents/GitHub/dependency-info-aggregator/node_modules/@aws-sdk/client-rds-data/dist-cjs/protocols/Aws_restJson1.js:486:23)
    at deserializeAws_restJson1ExecuteStatementCommandError (/Users/sughosh/Documents/GitHub/dependency-info-aggregator/node_modules/@aws-sdk/client-rds-data/dist-cjs/protocols/Aws_restJson1.js:405:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/sughosh/Documents/GitHub/dependency-info-aggregator/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /Users/sughosh/Documents/GitHub/dependency-info-aggregator/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
    at async StandardRetryStrategy.retry (/Users/sughosh/Documents/GitHub/dependency-info-aggregator/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /Users/sughosh/Documents/GitHub/dependency-info-aggregator/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at async main (file:///Users/sughosh/Documents/GitHub/dependency-info-aggregator/src/test.js:16:20) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: '68c1e816-a4ba-4b16-a886-f36134147de7',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  '$response': HttpResponse {
    statusCode: 400,
    headers: {
      'x-amzn-requestid': '68c1e816-a4ba-4b16-a886-f36134147de7',
      'x-amzn-errortype': 'BadRequestException:http://internal.amazon.com/coral/com.amazon.rdsdataservice/',
      'content-type': 'application/json',
      'content-length': '190',
      date: 'Tue, 15 Mar 2022 15:37:18 GMT',
      connection: 'close'
    },
    body: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 400,
      statusMessage: 'Bad Request',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [ClientRequest],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 12,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0,
      [Symbol(RequestTimeout)]: undefined
    }
  }
}
```

#### Expected behavior
As I have configured `maxAttempts: 10` for `RDSDataClient` instance, it should retry 10 times before failing using built-in exponential backoff strategy by default. Though, the actual error response is showing `response.$metadata.attempts: 1` and `response.$metadata.totalRetryDelay: 0`.

**Comment by susovan87** [comment]
While digging into the code-base for a possible fix, found a work-around by customising the `retryDecider` of `StandardRetryStrategy`. Please find the working code below..
```javascript
import { RDSDataClient, ExecuteStatementCommand } from "@aws-sdk/client-rds-data";
import { StandardRetryStrategy } from "@aws-sdk/middleware-retry"

const RETRY_ATTEMPTS = 10;
const retryOptions = {
  retryDecider: (err) => {
    if (err && err.name === 'BadRequestException'
      && err.message.match(/^Communications link failure/)
      && err.$metadata?.httpStatusCode === 400) {
      return true
    }

    return false
  }
}
const retryStrategy = new StandardRetryStrategy(async () => RETRY_ATTEMPTS, retryOptions)
const client = new RDSDataClient({
  region: 'us-east-1',
  maxAttempts: RETRY_ATTEMPTS,
  retryStrategy: retryStrategy
});

async function main() {
  const command = new ExecuteStatementCommand({
    sql: 'SELECT * FROM information_schema.tables LIMIT 1;',
    secretArn: '***',
    resourceArn: '***',
    database: '***',
  });
  try {
    const result = await client.send(command);
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error(error);
  }
}
main();
```

I still believe, a permanent fix should be incorporated into the SDK, so that people don't have to deal with those undocumented complexities while interacting with RDS Data API using aws-sdk-js-v3. As this issue is already fixed in **aws-sdk-js v2** [PR #2931](https://github.com/aws/aws-sdk-js/pull/2931), we should not encounter it again after migrating from v2.

**Comment by RanVaknin** [comment]
Hi  @susovan87 ,

I have tested it also in the CLI and this seems to be a service related issue. 
Im in contact with engineers from the RDS-data service team. Since you have found a workaround, and it's an older version it will most likely have low priority.

I'll keep you posted.

**Comment by RanVaknin** [comment]
Hi @susovan87 ,

Thanks for your patience. 
Proposed fixed are driven by community engagement. Since this is a low impact issue on an older version, with a workaround available, currently there is no action item to fix this issue.

Sorry.
