### ISSUE TITLE
HeadObjectCommand does not return user metadata

### ISSUE THREAD

**Issue by funes79** [aws/aws-sdk-js-v3#3446]
## Describe the bug

Calling a simple head command on an existing Key does not return any metadata, neither system nor user metadata.
```
  const input = {
    Bucket: bucket,
    Key: key,
  };
  const clientS3 = new S3Client({
    region:  s3_bucket_region,
    credentials: userCredentials,
  });
  const command = new HeadObjectCommand(input);
```

#### SDK version number

`@aws-sdk/client-s3": "^3.54.1"`

#### Is the issue in the browser/Node.js/ReactNative?

browser/React

#### Details of the browser/Node.js/ReactNative version
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`

## Steps to reproduce
Please share code or minimal repo, and steps to reproduce the behavior.

#### Observed behavior
A clear and concise description of what happens.

#### Expected behavior
A clear and concise description of what you were expecting to happen.

#### Screenshots
![image](https://user-images.githubusercontent.com/20202121/159042761-f1e8a56b-c541-450f-9e0b-ce53fb0df972.png)

**Comment by kuhe** [comment]
hi @funes79 ,

Based on my reading of these docs:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/ManageCorsUsing.html for using ExposeHeaders
and
https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html for User-defined object metadata

You'll want to set `ExposeHeaders` in the bucket CORS configuration to allow it to show the metadata that you want. For user-defined metadata, that means the `x-amz-meta-___` value that you've set on the object.

**Comment by funes79** [comment]
Thanks for the tip. These are the current settings
```
        "ExposeHeaders": [
            "x-amz-server-side-encryption",
            "x-amz-request-id",
            "x-amz-id-2",
            "ETag"
        ],
```
I will change them and try again
