### ISSUE TITLE
InvalidSignatureException and NetworkError when using @aws-sdk/client-eventbridge in ReactNative

### ISSUE THREAD

**Issue by giovannigiordano** [aws/aws-sdk-js-v3#3450]
## Describe the bug
Sending `PutCommand` within a ReactNative application often throws `InvalidSignatureException` or `NetworkError`

#### SDK version number
`@aws-sdk/client-eventbridge@3.53.0`

#### Is the issue in the browser/Node.js/ReactNative?
ReactNative

#### Details of the browser/Node.js/ReactNative version
0.64.3
I am using expo managed workflow, so I cannot paste the result of `react-native -v`

## Steps to reproduce
I cannot reproduce the bug, I have found it on Sentry and we have around 5k errors in 1 week.

The code is:
```js
const client = new EventBridgeClient({
  credentials: credentials,
  region: "eu-west-1",
});

const command = new PutEventsCommand({
  Entries: [
    {
      Detail: JSON.stringify(snakeCaseKeys(payload)),
      DetailType: event.type,
      EventBusName: "event-bus",
      Source: "source",
    },
  ],
});

const result = await this.client.send(command);
```
The credentials are retrieved through Cognito user pool.

#### Observed behavior
Sending a `PutEventsCommand` throws `InvalidSignatureException` or `NetworkError`

#### Expected behavior
Sending a `PutEventsCommand` should not throw `InvalidSignatureException` or `NetworkError`

## Additional context
For the authentication part I use Cognito.

**Comment by giovannigiordano** [comment]
Hi @RanVaknin,
thanks for the answer.
What do you mean by services configured to work with EventBridge? We have event bus target rules to aws lambdas, but I think this is not relevant.
The payload are plain objects like:
```
{
  ean: 123456789,
  quantity: 20,
  warehouse_id: '12345678-11-22222222'
}
```
We don't have any log anymore because we have filtered them to avoid reaching quotas on sentry.
Let me know how can I help.

Thanks

**Comment by RanVaknin** [comment]
Hi @giovannigiordano ,

Can you please add the stack trace so I can try to get some more clues as to where the problem is stemming from.
