### ISSUE TITLE
StartSyncExecutionCommand appending sync- is not working with stepfunctions local sync/express locally

### ISSUE THREAD

**Issue by marseam** [aws/aws-sdk-js-v3#3451]
## Describe the bug
When running step functions local, creating the client and using StartSyncExecutionCommand, it seems to append 'sync-' to the payload url

 `AWS SDK error wrapper for Error: getaddrinfo ENOTFOUND sync-127.0.0.1`
## Your environment
Mac OS 12.2 Monterey

#### SDK version number
` "@aws-sdk/client-sfn": "^3.54.0"`

#### Is the issue in the browser/Node.js/ReactNative?
No

## Steps to reproduce
Please share code or minimal repo, and steps to reproduce the behavior.

1. Run **express/sync** step functions with step function local[Step functions Local
](https://docs.aws.amazon.com/step-functions/latest/dg/sfn-local-docker.html)

2. Create a step functions client, for the docker instance and execute sync command

 ```js
 const stepFunctionRoleARN = describeStepFunctionResult.roleArn as string;
  const sfnLocalClient = new SFNClient({
    endpoint: `http://127.0.0.1:8080`,
    region: 'us-east-1',
  });

  const createLocalSFNResult = await sfnLocalClient.send(
    new CreateStateMachineCommand({
      definition: stepFunctionDefinition,
      name: 'CreateAccountStateMachine',
      roleArn: stepFunctionRoleARN,
      type: 'EXPRESS',
    })
  );

  const startLocalSFNExecutionResult = await sfnLocalClient.send(
    new StartSyncExecutionCommand({
      stateMachineArn: `${
        createLocalSFNResult.stateMachineArn as string
      }#ErrorPath`,
      input: JSON.stringify({
        companyName: 'Test Company',
    })
  );
```
#### Observed behavior
AWS SDK error wrapper for Error: getaddrinfo ENOTFOUND sync-127.0.0.1 error is thrown, it seems to append  sync- to the beginning of the payload url

#### Expected behavior
Expected the command to be sent to the correct url on docker without appending the sync command

#### Screenshots
![image](https://user-images.githubusercontent.com/2734403/159244966-e2936e82-2dfc-45bc-af6d-0a7be25161fd.png)## Additional context

**UPDATE**

I have added    `disableHostPrefix: true`in the clint context but now getting `UnsupportedOperation: Unsupported Operation: 'StartSyncExecution'`

**Comment by yenfryherrerafeliz** [comment]
Hi @marseam, apologies for responding to this so late. If this is still an issue for you, you need to update to the latest version of the SDK where this problem may be already fixed. I just did a test and I did not get the host prefixed with "sync-".

Code I used:
```js
import {CreateStateMachineCommand, SFNClient} from "@aws-sdk/client-sfn";

const client = new SFNClient({
    region: 'us-east-2',
    endpoint: "http://127.0.0.1"
});
client.middlewareStack.add( next => args => {
    console.log(args.request);

    return next(args);
}, {
    step: "finalizeRequest"
})
const response = await client.send(new CreateStateMachineCommand({
    definition: 'Definition',
    name: 'Name',
    roleArn: 'RoleArn',
    type: "EXPRESS"
}));

```

Output I got:
```console
HttpRequest {
  method: 'POST',
  hostname: '127.0.0.1',
  port: undefined,
  query: {},
  headers: {
  }
}
```
Thanks!
