### ISSUE TITLE
Typo in generated docs:  // proccess err and data.

### ISSUE THREAD

**Issue by perpil** [aws/aws-sdk-js-v3#3460]
## Describe the issue with documentation
In the callbacks section of any sdk doc i.e. for [S3](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/index.html#callbacks) there is a typo in the sample code comment.

```javascript
// callbacks.
client.send(command, (err, data) => {
  // proccess err and data.
});
```
should be:

`// process err and data.`

Note this typo appears twice in the S3 doc.

```javascript
// callbacks.
client.abortMultipartUpload(params, (err, data) => {
  // proccess err and data.
});
```

## Additional context
The error is likely in the doc generation process because the same typo appears in every javascript client doc.

**Comment by AllanZhengYP** [comment]
Close as it's already fixed in https://github.com/aws/aws-sdk-js-v3/pull/3489
