### ISSUE TITLE
Add date in endpoints update commit from release automation

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#3473]
### Is your feature request related to a problem? Please describe.
The commit message for endpoints update is `update client endpoints to latest`
For example: https://github.com/aws/aws-sdk-js-v3/commit/523b0fdf831d3d2f8b49fc33b45cb8d0b1520653

This is not helpful, as the same commit message will be used for all clients updates.

### Describe the solution you'd like
Add date in the commit message. For example, `update client endpoints as of 2022/03/24`

**Comment by AllanZhengYP** [comment]
Fixed in https://github.com/aws/aws-sdk-js-v3/commit/1c2da1dfcff3c3e016d5532dbc374e5b331e6919
