### ISSUE TITLE
Update endpoints.json in endpoints update commit

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#3474]
### Is your feature request related to a problem? Please describe.
Example with reference to release https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.56.0
* Commit https://github.com/aws/aws-sdk-js-v3/commit/c093315d7b1f48fee007d6033f5ab399f7a9f6a2 updates endpoints.json file.
* The endpoints are updated in a separate commit:
  * If the client is going to have API updates, it would be part of clients update commit. This case was not present in v3.56.0
  * If the client is not going to have API updates, it would be part of endpoints update commit https://github.com/aws/aws-sdk-js-v3/commit/523b0fdf831d3d2f8b49fc33b45cb8d0b1520653

This will be an operational issue as there are separate commits.

### Describe the solution you'd like
Have a separate commit which combines endpoints.json and endpoints.ts updates for all clients.

**Comment by AllanZhengYP** [comment]
Fixed in https://github.com/aws/aws-sdk-js-v3/commit/1c2da1dfcff3c3e016d5532dbc374e5b331e6919
