### ISSUE TITLE
Unable to pass message to generated Smithy exception

### ISSUE THREAD

**Issue by eduardomourar** [aws/aws-sdk-js-v3#3492]
## Describe the bug
We are unable to pass additional information (using the `message` during initialization) whenever throwing an error that was generated by Smithy. The `message` property is being excluded from the type, so our code fails when using the TypeScript compiler.

#### SDK version number
`@aws-sdk/smithy-client@3.53.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the Node.js version
v16.14.0

## Steps to reproduce
First, we defined an Exception shape in your Smithy model that contained a property called `message`. Then, we used the Smithy TypeScript plugin to generate a server SDK. From the type-system perspective, we were not allowed to pass the message whenever instantiating any of those exceptions. The code to reproduce can be found in this unit test [here](https://github.com/aws/aws-sdk-js-v3/blob/d6a82d5ea8e6f1c62933e17ad167203fc7980a89/packages/smithy-client/src/exceptions.spec.ts#L14-L29).

#### Observed behavior
The following message is shown during compilation of the code provided above:
> TS2345: Argument of type '{ message: string; code: string; $metadata: {}; }' is not assignable to parameter of type 'ExceptionOptionType<SomeException, ServiceException>'.
      Object literal may only specify known properties, and 'message' does not exist in type 'ExceptionOptionType<SomeException, ServiceException>'.

#### Expected behavior
I expected to be able to a message for an Exception so that it is reflected in the HTTP responses to our customers.

**Comment by ajredniwja** [comment]
@eduardomourar Thanks for creating a PR, I was able to approve and run the test. Can have someone take a look soon.
