### ISSUE TITLE
Allow instances of commands to be passed to DynamoDB transactions

### ISSUE THREAD

**Issue by ghost** [aws/aws-sdk-js-v3#3495]
### Is your feature request related to a problem? Please describe.
It doesn't appear to be currently possibly to pass an array of command instances to a transaction command, which seems a bit odd as the data structure is almost identical.  Right now, you need to pass raw objects to transactions even if you already have valid commands.

### Describe the solution you'd like
The transact commands should take other command instances like `PutCommand` and `DeleteCommand`.
```js
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import {
  DynamoDBDocumentClient,
  PutCommand,
  TransactWriteCommand,
} from '@aws-sdk/lib-dynamodb';

const client = DynamoDBDocumentClient.from(new DynamoDBClient());
const itemA = new PutCommand({
  /* data */
});
const itemB = new PutCommand({
  /* data */
});

await client.send(new TransactWriteCommand({ TransactItems: [itemA, itemB] }));
```

### Describe alternatives you've considered
Currently the only option is to manually construct them doing something like:

```js
await client.send(
  new TransactWriteCommand({
    TransactItems: [
      {
        Put: {
          /* itemA data */
        },
      },
      {
        Put: {
          /* itemB data */
        },
      },
    ],
  }),
);
```

### Additional context
We have some logic where we sometimes run a one off operation (`PutCommand` directly) or sometimes multiple commands inside a transaction.  It'd be nice to simply reuse the existing command  rather than duplicating logic/code to recreate the item.

**Comment by morioust** [comment]
Yes please -- honestly I assumed this was how it was supposed to work at first, it would be the most intuitive way.

**Comment by poudelroshan** [comment]
Waiting for this request to be fulfilled.

**Comment by ben-sommer** [comment]
Any ETA on this?

**Comment by trivikr** [comment]
ToDo: Check if TransactItems does not accept JavaScript native types.

**Comment by yenfryherrerafeliz** [comment]
Adding a needs-review label in order to investigate this further.

**Comment by aBurmeseDev** [comment]
Hi @morioust and everyone else on the thread - thanks for your patience.

Upon further team discussion, we're not going to consider this request at the moment, unfortunately. The reason being, we'd like to keep the consistency across AWS SDKs and if we're going to implement this, we're going to have to make a special case for JavaScript SDK to modify the service interface. 

Thank you all for reaching out and sharing your feedback.

**Comment by aBurmeseDev** [comment]
Hi @morioust and everyone else on the thread - thanks for your patience.

Upon further team discussion, we're not going to consider this request at the moment, unfortunately. The reason being, we'd like to keep the consistency across AWS SDKs and if we're going to implement this, we're going to have to make a special case for JavaScript SDK to modify the service interface. 

Thank you all for reaching out and sharing your feedback.
