### ISSUE TITLE
Cannot load credentials from ini when using source_profile in conjunction with credential_process

### ISSUE THREAD

**Issue by clhuang** [aws/aws-sdk-js-v3#3505]
## Describe the bug
credentials fail to load when a profile profile1 assumes a role via profile2, where profile2 gets its credentials from a process. The setup works with boto3, but not @aws-sdk.

## Your environment
mac os 12.3
node 16.13.0

#### SDK version number
`@aws-sdk/client-sts@3.58.0`

#### Is the issue in the browser/Node.js/ReactNative?
node

#### Details of the browser/Node.js/ReactNative version
v16.13.0

## Steps to reproduce
in .aws/credentials:
```
[profile1]
source_profile=profile2
role_session_name=whatever
role_arn=whatever

[profile2]
credential_process=whatever
```

run in node, with AWS_PROFILE=profile1:
```js
const { STS } = require('@aws-sdk/client-sts');
new STS({}).getCallerIdentity().then(console.log, console.error);
```

#### Observed behavior
fails with `CredentialsProviderError: Could not load credentials from any providers`

#### Expected behavior
Credentials successfully load.

**Comment by cornerman** [comment]
I am having the exact same issue. Is there any workaround available? :)

**Comment by clhuang** [comment]
@cornerman I have a patch for the aws-sdk that I used: https://gist.github.com/clhuang/4d05a17f2f4fe0f097a54c6eba00ce6f

**Comment by cornerman** [comment]
@clhuang Thank you!

From this, I have created a repository on which you can depend: https://github.com/cornerman/aws-sdk-credential-provider-ini.

You can use it in your package.json as: `"@aws-sdk/credential-provider-ini": "github:cornerman/aws-sdk-credential-provider-ini.git#semver:3.110.0"`.

**Comment by yenfryherrerafeliz** [comment]
Hi @clhuang, thanks for opening this issue. Could you please try specifying the profile when instancing the client as follow:
```js
import {STS} from "@aws-sdk/client-sts";
import {fromIni} from "@aws-sdk/credential-providers";

const sts = new STS({
    region: 'REGION',
    credentials: fromIni({profile: 'profile1'})
});
const response = await sts.getCallerIdentity({});

console.log('Response: ', response);
```

Thanks!

**Comment by clhuang** [comment]
It does not work. I receive the error:
`CredentialsProviderError: Profile <profile2> could not be found or parsed in shared credentials file.`

**Comment by clhuang** [comment]
in resolveProfileData, there is no mechanism to handle process credentials, so it falls through to the error: https://github.com/aws/aws-sdk-js-v3/blob/main/packages/credential-provider-ini/src/resolveProfileData.ts#52

**Comment by yenfryherrerafeliz** [comment]
>in resolveProfileData, there is no mechanism to handle process credentials, so it falls through to the error: https://github.com/aws/aws-sdk-js-v3/blob/main/packages/credential-provider-ini/src/resolveProfileData.ts#52

Hi @clhuang, I agree with you. 

I can confirm that the only way the credentials are loaded from credential_process is if the profile being used in the SDK is the same that has the settings for credential_process, which means that sourcing a profile will not work if the source profile intent to load the credentials from a process. At this time I will mark this issue to be reviewed so we can investigate and address this further.

Thanks!

**Comment by clhuang** [comment]
@yenfryherrerafeliz I have created a PR: https://github.com/aws/aws-sdk-js-v3/pull/3865/files

**Comment by deividasm** [comment]
We are also facing this issue. Thank you for looking into it 🙏
