### ISSUE TITLE
Add ability of breakpoint transmission  to lib-storage 

### ISSUE THREAD

**Issue by RichardLeeY** [aws/aws-sdk-js-v3#3509]
### Is your feature request related to a problem? Please describe.
With `aws-sdk/lib-storage` , I can create a upload task to concurrently transfer data to S3 , and I can implement a process bar easily .That's really good for me.  When I need to transfer video file larger than 1GB  to S3 , Mostly All things go well. Sometimes for some network issues, the transmission stoped.How should I resume transmission from the breakpoint ?   As we all know It will cost a long time if I start from the beginning.

### Describe the solution you'd like
Add a new interface like `resumeUpload`,  When the data transmission fail, I can resume the task by my `uploadId`.

### Describe alternatives you've considered
By now, I have to hack with `MultipartUploadCommand` `uploadPartCommand` etc in `aws-sdk/client-s3` . And unfortunately I didn't find a clear example of breakpoint transmission yet.

**Comment by trivikr** [comment]
The S3 Transfer Manager in AWS SDK for Java v1 supports pause/resume. The application has to explicitly call pause though.

Blog post: https://aws.amazon.com/blogs/developer/pausing-and-resuming-transfers-using-transfer-manager/
