### ISSUE TITLE
SSM sendCommandCommand seems to be missing the executionTimeout parameter 

### ISSUE THREAD

**Issue by johnlabarge** [aws/aws-sdk-js-v3#3516]
### Is your feature request related to a problem? Please describe.
I need to extend the timeout for a script I want to run on the instance via the javascript client, however I do not see a way to set the executionTimeout.  Specifically I've tried to put it in the parameters block as 
`                            Parameters: {
                                commands: [
                                ...
                                ],
                             "executionTimeout": "12000"
                            },`
(the type for command input requires that Parameters be { [key: string] : string[] }

### Describe the solution you'd like
I'd like to have a way to specific the execution timeout that worked and documentation for it.

### Describe alternatives you've considered
I'm considering abandoning this path and trying to manufacture AMIs.  My enterprise-y setup makes all of this very challenging.

**Comment by chadvanklompenburg** [comment]
Ran into this same bug today.  Can it be bumped?

**Comment by aBurmeseDev** [comment]
Hi @johnlabarge and @chadvanklompenburg - thanks for reaching out and apology for not getting to you sooner.

If I understand correctly, the ask here is to set the `executionTimeout` in SSM [`sendCommand`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/ssm/command/SendCommandCommand/). 

According to service API documentation, you may set `timeoutSeconds` within `mainSteps` element of SSM document if you're using schema version 2.2 or in earlier versions, it's set in `runtimeConfig`.

```json
schema version 2.2
   "mainSteps": [
      {
         "action": "aws:runPowerShellScript",
         "name": "example",
         "inputs": {
            "timeoutSeconds": "60",
            "runCommand": [
               "Write-Output {{Message}}"
            ]
         }
      }
   ]
```

```json
schema version 1.2
    "runtimeConfig":{
        "aws:runShellScript":{
            "properties":[
                {
                    "id":"0.aws:runShellScript",
                    "runCommand":"{{ commands }}",
                    "workingDirectory":"{{ workingDirectory }}",
                    "timeoutSeconds":"{{ executionTimeout }}"
                }
            ]
        }
    }
```

Here's [documentation](https://docs.aws.amazon.com/systems-manager/latest/userguide/documents-schemas-features.html#documents-schema-onex) that you may find it helpful.

Best,
John
