### ISSUE TITLE
util-dynamodb fails to marshall basic arrays (breaks things like executeStatement functionality when using DynamoDB Document Client)

### ISSUE THREAD

**Issue by ghost** [aws/aws-sdk-js-v3#3529]
## Describe the bug
You can't execute PartiQL statements with `Parameters` using the document client - it throws 100% of the time.

#### SDK version number
```
@aws-sdk/client-dynamodb@3.67.0
@aws-sdk/lib-dynamodb@3.67.0
```

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
```
v17.8.0
```

## Steps to reproduce
```js
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import {
  DynamoDBDocumentClient,
  ExecuteStatementCommand,
} from '@aws-sdk/lib-dynamodb';

const client = DynamoDBDocumentClient.from(new DynamoDBClient());

await client.send(
  new ExecuteStatementCommand({
    Statement: 'select * from MyTable where apple = ? and berry = ?',
    Parameters: ['red', 'blue'],
  }),
);
```

#### Observed behavior
When the document client marshalls the parameters, it converts them all to undefined internally, which results in the following error:

```
ValidationException: 1 validation error detected: Value '[]' at 'parameters' failed to satisfy constraint: Member must have length greater than or equal to 1
```

Adding some console logs inside the internals of the SDK:

```js
// before marshalling
{
  Statement: 'select * from MyTable where apple = ? and berry = ?',
  Parameters: [ 'red', 'blue' ]
}

// after marshalling
ExecuteStatementCommand {
  middlewareStack: {
    add: [Function: add],
    addRelativeTo: [Function: addRelativeTo],
    clone: [Function: clone],
    use: [Function: use],
    remove: [Function: remove],
    removeByTag: [Function: removeByTag],
    concat: [Function: concat],
    applyToStack: [Function: cloneTo],
    resolve: [Function: resolve]
  },
  input: {
    Statement: 'select * from MyTable where apple = ? and berry = ?',
    Parameters: [ undefined, undefined ]
  }
}
```

#### Expected behavior
It should successfully execute the PartiQL statement and return the items.  If you fully remove the document client logic and just use the base DynamoDB client, things work as expected.

#### Screenshots
n/a

## Additional context
Something is going wrong in the marshalling, which ultimately results in an error being thrown.

**Comment by edmundcong** [comment]
i believe that should be `Parameters: [ {S: 'red'}, {S: 'blue'} ]` no?

**Comment by yenfryherrerafeliz** [comment]
Hi, thanks for opening this issue. I can confirm that this behavior was a limitation in that SDK version, but with the latest version it is working correctly. At the moment I tested the version was 3.142.0.

Thanks!
