### ISSUE TITLE
Clock skew information available on middleware

### ISSUE THREAD

**Issue by elorzafe** [aws/aws-sdk-js-v3#353]
**Is your feature request related to a problem? Please describe.**
Customers have issue with their apps when devices has clock skew problems. Specially for signing request and refreshing credentials.
https://github.com/aws-amplify/amplify-js/issues/2014

**Describe the solution you'd like**
Add clock skew information that can be used for refresh credentials properly. Ideally to send this over the credentials handler.

**Describe alternatives you've considered**
Handle this on the App, or add external logic to solve this can be messy and will require to invoke the api a second time instead of handling that on the middleware.

**Comment by pravgupt** [comment]
@AllanFly120 is there any update on when this can be available? This will be a blocker for us.

**Comment by trivikr** [comment]
Clockskew correction was enabled by default in https://github.com/aws/aws-sdk-js-v3/pull/459
