### ISSUE TITLE
SQS Casing issues, please can it be consistent between what is supplied in the event & the send function

### ISSUE THREAD

**Issue by Ancient-Dragon** [aws/aws-sdk-js-v3#3532]
### Is your feature request related to a problem? Please describe.
I find it frustrating when the message attributes of a SNS event which has come through SQS into a lambda cannot be directly sent to another SQS queue.

### Describe the solution you'd like
Either when receiving a message the message attributes are in CamelCase or when sending a message with message attributes you can send them in lowerCamelCase.

### Describe alternatives you've considered
At the moment, I have to write a function to convert all of my messages attributes which isn't ideal.
This is the method I am currently using:
```ts
const capitalizeObjectKeys = (obj: MessageAttributeMap): MessageAttributeMap => {
  const results: MessageAttributeMap = {};
  Object.entries(obj).forEach(([attributeName, value]) => {
    const entries = Object.entries(value);
    const capsEntries = entries.map((entry) => [entry[0][0].toUpperCase() + entry[0].slice(1), entry[1]]);
    const attributesCapitalised = Object.fromEntries(capsEntries);
    results[attributeName] = attributesCapitalised;
  });
  return results;
};
```

### Additional context
Here is the error I get when I'm trying to send a message with an attribute which uses lower camel case:
ERROR	Something went wrong publishing to deadletter queue InvalidParameterValue: The message (user) attribute 'payloadType' must contain a non-empty message attribute value.

```ts
"MessageAttributes": {
        "payloadType": {
            "stringValue": "TestData",
            "binaryValue": null,
            "stringListValues": [],
            "binaryListValues": [],
            "dataType": "String"
        },
}
```
I made the event below generic but my is of the same format. Which is what I receive from SQS.
```json
{
    "messageId": "",
    "receiptHandle": "",
    "body": "{\"foo\": \"bar\"}",
    "attributes": {
        "ApproximateReceiveCount": "1",
        "SentTimestamp": "1649668282953",
        "SenderId": "",
        "ApproximateFirstReceiveTimestamp": "1649668282963"
    },
    "messageAttributes": {
        "payloadType": {
            "stringValue": "TestData",
            "binaryValue": null,
            "stringListValues": [],
            "binaryListValues": [],
            "dataType": "String"
        },
        "formattedMessageTimestamp": {
            "stringValue": "2022-04-06T09:41:47.000Z",
            "binaryValue": null,
            "stringListValues": [],
            "binaryListValues": [],
            "dataType": "String"
        },
        "messageTimestamp": {
            "stringValue": "1649238107",
            "binaryValue": null,
            "stringListValues": [],
            "binaryListValues": [],
            "dataType": "String"
        }
    },
    "md5OfMessageAttributes": "",
    "md5OfBody": "",
    "eventSource": "aws:sqs",
    "eventSourceARN": "",
    "awsRegion": "us-east-1"
}
```

**Comment by enchorb** [comment]
+1, this is a major annoyance

**Comment by michael-land** [comment]
+1

**Comment by NoahCardoza** [comment]
+1

**Comment by sakopov** [comment]
I have been trying to figure out what is going on here for hours until I found this issue. Looks like a simple serialization bug that should be addressed by the SDK...

**Comment by aBurmeseDev** [comment]
Hi @Ancient-Dragon and everyone else on the thread - thanks for your patience.

Upon team discussion we had today, we were able to verify and confirm that this's service API related behavior and SDK doesn't have control over it. I can submit a request to service team on behalf but won't be able to guarantee that this would be considered. 

Again thank you all for reaching out!
