### ISSUE TITLE
Credentials are incorrectly marked required to call/create Cognito client

### ISSUE THREAD

**Issue by Amplifiyer** [aws/aws-sdk-js-v3#354]
**Describe the bug**
Credentials param is mandatory (like in all other clients) for cognito client 

**SDK version number**
V3 preview

**Is the issue in the browser/Node.js?**
Browser

**To Reproduce (observed behavior)**
Create cognito client, credentials params is mandatory. Pass in undefined, gets the following error:
"ensure credentials error Error: "No input provided for required configuration parameter: credentials" from https://github.com/aws/aws-sdk-js-v3/blob/master/packages/config-resolver/src/index.ts#L43

**Expected behavior**
Credentials should not be required to call cognito service. Cognito service takes in identity pool id or identity id and returns credentials which are used elsewhere.

**Comment by AllanFly120** [comment]
Seems to duplicated with #185. 

The [model](https://github.com/aws/aws-sdk-js-v3/blob/master/models/cognito-identity/2014-06-30/service-2.json) to the cognito-identity service doesn't model some the command doesn't need credential. We need to support customizations to the cognito identity client like in the [V2](https://github.com/aws/aws-sdk-js/blob/master/lib/services/cognitoidentity.js). I will mark it as feature request.

**Comment by trivikr** [comment]
Verified that credentials are no longer required to be passed in CognitoIdentityClient constructor in test repo in PR https://github.com/aws-samples/aws-sdk-js-tests/pull/4
