### ISSUE TITLE
ESBuild doesn't tree shake *Client imports

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#3542]
## Describe the bug
ESBuild doesn't tree shake *Client imports

> This is probably an issue with esbuild or my configuration. I'm creating a bug report with minimal repro.

#### SDK version number
`@aws-sdk/client-acm@3.67.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
```console
$ node -v
v16.14.2

$ ./node_modules/.bin/esbuild --version
0.14.36
```

## Steps to reproduce

```js
// bare-bones-client.mjs
import { ACMClient, ListCertificatesCommand } from "@aws-sdk/client-acm";

export const listCertificates = () => {
  const client = new ACMClient({ region: "us-west-2" });
  return client.send(new ListCertificatesCommand({}));
};
```

```js
// aggregated-client.mjs
import { ACM } from "@aws-sdk/client-acm";

export const listCertificates = () => {
  const client = new ACM({ region: "us-west-2" });
  return client.listCertificates({});
};

```

#### Observed behavior
```console
$ ./node_modules/.bin/esbuild bare-bones-client.mjs --bundle --outfile=out.js --platform=node 
  out.js  750.0kb
```

```console
$ ./node_modules/.bin/esbuild aggregated-client.mjs --bundle --outfile=out.js --platform=node 
  out.js  749.9kb
```

#### Expected behavior
I was expecting the bundle created from `bare-bones-client.mjs` to be much smaller.

**Comment by trivikr** [comment]
This is probably an issue with esbuild or some configuration, as it's present in `@aws-sdk/client-acm@3.0.0` too.

```console
$ ./node_modules/.bin/esbuild bare-bones-client.mjs --bundle --outfile=out.js --platform=node
  out.js  542.4kb

$ ./node_modules/.bin/esbuild aggregated-client.mjs --bundle --outfile=out.js --platform=node
  out.js  542.4kb
```

**Comment by trivikr** [comment]
Probably related https://github.com/evanw/esbuild/issues/1420

**Comment by AllanZhengYP** [comment]
I don't see you supplied a `tree-shake` config, [here](https://github.com/aws/aws-sdk-js-v3/blob/71acd153dd82ee8d8d180f55e6fba0ee18f1ea8a/scripts/benchmark-size/runner/calculate-size/bundlers-size.ts#L64-L71) is the esbuild config I used for our bundler test.

**Comment by trivikr** [comment]
From esbuild docs on [tree shaking](https://esbuild.github.io/api/#tree-shaking), it's enabled when bundling
> By default, tree shaking is only enabled either when [bundling](https://esbuild.github.io/api/#bundle) is enabled

Verified that `--tree-shaking=true` doesn't change the bundle size:

```console
$ ./node_modules/.bin/esbuild bare-bones-client.mjs --bundle --outfile=out.js --platform=node -
-tree-shaking=true
  out.js  750.0kb

$ ./node_modules/.bin/esbuild aggregated-client.mjs --bundle --outfile=out.mjs --platform=node --tree-shaking=true
  out.mjs  749.9kb 
```

**Comment by trivikr** [comment]
Prior issues related to bundling:
* https://github.com/aws/aws-sdk-js-v3/issues/1504
* https://github.com/aws/aws-sdk-js-v3/issues/1617

**Comment by trivikr** [comment]
Experimented with cjs code, but there's no difference:

```js
// bare-bones-client.js
const { ACMClient, ListCertificatesCommand } = require("@aws-sdk/client-acm");

export const listCertificates = () => {
  const client = new ACMClient({ region: "us-west-2" });
  return client.send(new ListCertificatesCommand({}));
};
```

```js
// aggregated-client.js
const { ACM } = require("@aws-sdk/client-acm");

export const listCertificates = () => {
  const client = new ACM({ region: "us-west-2" });
  return client.listCertificates({});
};
```

```console
$ ./node_modules/.bin/esbuild bare-bones-client.js --bundle --outfile=out.js --platform=node 
  out.js  749.7kb

$ ./node_modules/.bin/esbuild aggregated-client.js --bundle --outfile=out.js --platform=node
  out.js  749.6kb
```

**Comment by trivikr** [comment]
This happens as esbuild can't tree shake [commonjs modules](https://esbuild.github.io/api/#platform)

> This means tree shaking will likely not happen for packages that provide both module and main since tree shaking works with ECMAScript modules but not with CommonJS modules.

The application can explicitly pass `--main-fields=module,main` to enable tree-shaking 
```console
$ ./node_modules/.bin/esbuild aggregated-client.mjs --bundle --outfile=out.js --platform=node --main-fields=module,main
  out.js  591.5kb

$ ./node_modules/.bin/esbuild bare-bones-client.mjs --bundle --outfile=out.js --platform=node --main-fields=module,main
  out.js  486.9kb
```
