### ISSUE TITLE
issue with aws service discovery javascript

### ISSUE THREAD

**Issue by Ravi-Rsankar** [aws/aws-sdk-js-v3#3547]
Im developing a nodejs application that needs to register to the AWS service discovery on the app start. I'm using the @aws-sdk/client-servicediscovery lib in my node application. As a reference, I am using the code from here: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-servicediscovery/index.html.

```js
const { ServiceDiscoveryClient, CreateHttpNamespaceCommand } = require("@aws-sdk/client-servicediscovery");
const client = new ServiceDiscoveryClient({ region: "xxx" });
const params = {
    "ServiceId":"xxx",
    "InstanceId":"xxx",
    "CreatorRequestId":new Date(new Date().toUTCString()),
    "Attributes": {
        AWS_INSTANCE_IPV4: "xxx.xx.xx.xx",
        AWS_INSTANCE_PORT: xxx,
        service: "xxx",
      }
};

const command = new CreateHttpNamespaceCommand(params);
client.send(command).then(
    (data) => {
      console.log(data)
    },
    (error) => {
        console.log(error)
    }
  );

```
While running the app, getting these errors.
```js
/application/node_modules/@aws-sdk/shared-ini-file-loader/dist-cjs/slurpFile.js:5
const { readFile } = fs_1.promises;
        ^

TypeError: Cannot destructure property `readFile` of 'undefined' or 'null'.
    at Object.<anonymous> (/application/node_modules/@aws-sdk/shared-ini-file-loader/dist-cjs/slurpFile.js:5:27)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/application/node_modules/@aws-sdk/shared-ini-file-loader/dist-cjs/loadSharedConfigFiles.js:8:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```
I am new to the AWS SDK so need some help registering my service to the service discovery. Thanks in advance!

**Comment by khitrenovich** [comment]
Same issue here when bumping `@aws-sdk` packages from 3.36.x to latest.... Do you have any updates. please?

**Comment by brunobasto** [comment]
Same here. Anyone found a solution?

**Comment by khitrenovich** [comment]
> Same issue here when bumping `@aws-sdk` packages from 3.36.x to latest.... Do you have any updates. please?

Update (May 23, 2022) - 
Bump to v3.95 across the board of all the services we are using brings no changes.

![image](https://user-images.githubusercontent.com/3424762/169830619-f609a454-165f-49f5-92ce-e086fc306339.png)

**Comment by dopedwolf** [comment]
@mbunge Did you find a solution to this?

**Comment by ajredniwja** [comment]
This is possibly related to https://github.com/aws/aws-sdk-js-v3/issues/3828

**Comment by jasonterando** [comment]
Any updates?

**Comment by WarleyGabriel** [comment]
Hi guys, I'm using two AWS packages:
```
"@aws-sdk/client-secrets-manager": "^3.282.0"
"@aws-sdk/client-ssm": "^3.282.0"
``` 
Node.JS version `16.19.1` and I'm also facing this error, it's like:

```
  TypeError: Cannot destructure property 'writeFile' of 'fs_1.promises' as it is undefined.

      1 | const Confidence = require('confidence')
    > 2 | const { SecretsManagerClient, GetSecretValueCommand } = require('@aws-sdk/client-secrets-manager')
```

I was testing a possible fix locally and I needed to change, from:

```
const fs_1 = require("fs");
const { writeFile } = fs_1.promises;
```

to (I saw it on that [TODO](https://github.com/aws/aws-sdk-js-v3/blame/f98392cc24241e7c388af7cb750be75a6bc3c6b4/packages/shared-ini-file-loader/src/getSSOTokenFromFile.ts#L1)):
```
const fs_1 = require("fs/promises");
const { writeFile } = fs_1;
```

In three files: 
- writeSSOTokenToFile
- slurpFile
- getSSOTokenFromFile

After it I got success on the tests that I was running.

Can anyone help, applying those changes on the SDK?

**Comment by WarleyGabriel** [comment]
> Hi guys, I'm using two AWS packages:
> 
> ```
> "@aws-sdk/client-secrets-manager": "^3.282.0"
> "@aws-sdk/client-ssm": "^3.282.0"
> ```
> 
> Node.JS version `16.19.1` and I'm also facing this error, it's like:
> 
> ```
>   TypeError: Cannot destructure property 'writeFile' of 'fs_1.promises' as it is undefined.
> 
>       1 | const Confidence = require('confidence')
>     > 2 | const { SecretsManagerClient, GetSecretValueCommand } = require('@aws-sdk/client-secrets-manager')
> ```
> 
> I was testing a possible fix locally and I needed to change, from:
> 
> ```
> const fs_1 = require("fs");
> const { writeFile } = fs_1.promises;
> ```
> 
> to (I saw it on that [TODO](https://github.com/aws/aws-sdk-js-v3/blame/f98392cc24241e7c388af7cb750be75a6bc3c6b4/packages/shared-ini-file-loader/src/getSSOTokenFromFile.ts#L1)):
> 
> ```
> const fs_1 = require("fs/promises");
> const { writeFile } = fs_1;
> ```
> 
> In three files:
> 
> * writeSSOTokenToFile
> * slurpFile
> * getSSOTokenFromFile
> 
> After it I got success on the tests that I was running.
> 
> Can anyone help, applying those changes on the SDK?

I've just realized that I was mocking `fs` in my test:

```
jest.mock('fs')
```

I changed to use `jest.spyOn(fs, 'writeFileSync').mockReturnValue({})`, now it's working!

**Comment by zterlizz** [comment]
You can also mock the 'fs' module and retain functionality using `jest.requireActual()` like this:
```
jest.mock('fs', () => ({
  ...jest.requireActual('fs'),
  openSync: jest.fn(),
  createReadStream: jest.fn(),
  writeFileSync: jest.fn(),
  writeSync: jest.fn(),
  closeSync: jest.fn()
}));
```
All 'fs' functionality will remain and only the listed functions will be mocked: openSync, createReadStream, writeFileSync, writeSync, closeSync.

**Comment by aBurmeseDev** [comment]
Thanks everyone for posting here and apologies for the long silence. I came across this and wanted to check if this behavior is still reproducible with recent NodeJS versions?
