### ISSUE TITLE
http could not be found within the project.

### ISSUE THREAD

**Issue by MuhammadAbdullah54321** [aws/aws-sdk-js-v3#3549]
## Describe the bug
I have tried to use this package but it has some core bugs with Node environment for react-native 

## Your environment
Mac OS  Version 11.6.5 (20G527)

#### SDK version number
`@aws-sdk/client-elasticsearch-service`

#### Is the issue in the browser/Node.js/ReactNative?
ReactNative

#### Details of the browser/Node.js/ReactNative version
react-native-cli: 2.0.1
react-native: 0.63.4
node version: v16.8.0

## Steps to reproduce
Install this package in react-native app and you will see this issue

#### Observed behavior
as soon as I import `const { HttpRequest } = require("@aws-sdk/protocol-http");` my app crashes

#### Expected behavior
`http` is one of the very basic module, it should not be the cause of crashing 

#### Screenshots
<img width="576" alt="Screenshot 2022-04-19 at 11 40 09 PM" src="https://user-images.githubusercontent.com/34376568/164073199-440323c6-cff0-47a9-a074-5025dda25f89.png">

## Additional context
You can read similar issues here: 
https://github.com/facebook/react-native/issues/375
https://github.com/facebook/react-native/issues/15048
https://stackoverflow.com/questions/29371694/react-native-and-requirehttp

**Comment by RanVaknin** [comment]
@MuhammadAbdullah54321 Hi,

I apologize for the late reply.

Here are the steps I've taken to reproduce your error:
- I have created my react native project locally with:
```
expo init myproject
cd myproject
expo start
```

- Installed the dependency:
```
expo install @aws-sdk/protocol-http
```

- In my `app.js` I have required the dependency:
```
import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View } from 'react-native';
const { HttpRequest } = require("@aws-sdk/protocol-http");

export default function App() {
  return (
    <View>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

```

I'm not experiencing any crash when importing and rebuilding my app, and unable to reproduce your code's behavior at this moment.

Can you please provide me with more details like your file structure, how you set up your project, or any other specific information regarding your project so I can try to better understand what is happening on your end.

Thanks!
