### ISSUE TITLE
(lib-dynamodb) Typescript: Don't require strings for AttributeValues that are N

### ISSUE THREAD

**Issue by jcollum-nutrien** [aws/aws-sdk-js-v3#3551]
### Is your feature request related to a problem? Please describe.

![image](https://user-images.githubusercontent.com/99687439/164285862-57294fff-2d46-4471-a340-1b46b71618fa.png)

In the code executing `divisionID` is a number. But I can't place it in an AttributeValue of `{N: divisionID }` instead I have to do `{N: divisionID.toString() }`. So I'm taking a number and converting it to a string so I can use it in a numeric field? This is odd and counter-intuitive. 

### Describe the solution you'd like
I realized that the SDK wants to serialize everything to a string before transmission. I think it would be nice if that was handled for me in this case. 

### Describe alternatives you've considered
None

### Additional context
None

**Comment by kuhe** [comment]
Are you using [`@aws-sdk/lib-dynamodb`](https://github.com/aws/aws-sdk-js-v3/blob/main/lib/lib-dynamodb/README.md)?

You should be able to write your command as

```
const params = {
    Key: {
        'name-brand-division': hashKey, // typeof 'string'
        divisionID: divisionID // typeof 'number'
    }
}
```
