### ISSUE TITLE
CORS requests to https://wellarchitected.<region>.amazonaws.com/<path> fail due to error "blocked by CORS policy: Request header field amz-sdk-invocation-id is not allowed by Access-Control-Allow-Headers in preflight response"

### ISSUE THREAD

**Issue by vforvalerio87** [aws/aws-sdk-js-v3#3553]
## Describe the bug
CORS requests to https://wellarchitected.<region>.amazonaws.com/<path> fail due to error "blocked by CORS policy: Request header field amz-sdk-invocation-id is not allowed by Access-Control-Allow-Headers in preflight response".

## Your environment
Chrome, calls are to eu-west-1

#### SDK version number
`@aws-sdk/package-name@3.72.0`

**Comment by vforvalerio87** [comment]
Possibly related tohttps://github.com/aws/aws-sdk-js-v3/issues/1376

**Comment by AndyOR-Apis** [comment]
Also seeing this when trying to use the Lex Bot features.

Error: "Access to fetch at 'https://models-v2-lex.eu-west-1.amazonaws.com/bots' from origin 'http://localhost:4200' has been blocked by CORS policy: Request header field amz-sdk-invocation-id is not allowed by Access-Control-Allow-Headers in preflight response."

**Comment by CatsNipYummy** [comment]
@AndyOR-Apis facing the same issue on my end. Is it still the case for you?

**Comment by vforvalerio87** [comment]
@AndyOR-Apis @CatsNipYummy I know it's for a different service but this is what we ended up doing in the meantime:
- For some projects, we proxy requests through one of our API endpoints (the requests come from our server so there's no CORS). I simply have a "/awsproxy" endpoint which takes a JSON payload with AWS sdk function name and params
- For other projects, we simply reverted to v2 of the SDK, as most services don't seem to send "amz-sdk-invocation-id" as an HTTP header in API calls

**Comment by RanVaknin** [comment]
Reading the internal comments on ticket `V666613687` saying this is fixed. Can someone please give this another shot and see if this was indeed solved upstream? 

Since this is not an SDK related issue but an issue with the upstream service, I'm going to go ahead and close this issue.

Thanks,
Ran~
