### ISSUE TITLE
No ResourceNotFoundException in @aws-sdk/client-s3

### ISSUE THREAD

**Issue by trevorr** [aws/aws-sdk-js-v3#3558]
## Describe the issue with documentation

This documentation indicates that `ResourceNotFoundException` is available for the S3 client: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/classes/resourcenotfoundexception.html

I'd like to check for that error in Typescript as described here: https://aws.amazon.com/blogs/developer/service-error-handling-modular-aws-sdk-js/

## Steps to reproduce

Run `npm install @aws-sdk/client-s3`:

```json
  "dependencies": {
    "@aws-sdk/client-s3": "^3.76.0",
```

Import `ResourceNotFoundException`:

```ts
import { ResourceNotFoundException } from "@aws-sdk/client-s3";
```

#### Observed behavior

```
Module '"@aws-sdk/client-s3"' has no exported member 'ResourceNotFoundException'. ts(2305)
```

#### Expected behavior

`ResourceNotFoundException` would be imported and available for `instanceof` checks.

**Comment by rayandrew** [comment]
you can use `NotFound` or other exceptions that are defined inside:
- https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-s3/src/models/models_0.ts
- https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-s3/src/models/models_1.ts
