### ISSUE TITLE
Distribute browser packages as ES-modules

### ISSUE THREAD

**Issue by just-boris** [aws/aws-sdk-js-v3#356]
**Is your feature request related to a problem? Please describe.**

Currently all packages (node and browser) contain commonjs modules. 
ES-modules are more size-efficient, because they do not have an extra transpilation overhead, plus they allow other optimizations, like module concatenation and tree-shaking.

As an example of impact, I can tell you that in my projects I was able to reduce the final bundle size by 25% when switched to es-modules.

Moreover, es-modules natively work in modern browsers, whereas commonjs modules always require some preprocessing in order to run there.

**Describe the solution you'd like**

All `@aws-sdk/*-browser` modules export es-module artifacts. Basically, it can be achieved via updating the `tsconfig.json` file for the respective modules.

**Comment by trivikr** [comment]
Thank you @just-boris for the suggestion
Can you share an example which explains size efficiency of ES-modules?

**Comment by AllanFly120** [comment]
ES Module are now available since [release v1.0.0-alpha.16](https://github.com/aws/aws-sdk-js-v3/commit/488f6aa42f3450f0ea1eeabbaa37c6f819d9e02b)

**Comment by just-boris** [comment]
Thank you!
