### ISSUE TITLE
Cant find variable Credential

### ISSUE THREAD

**Issue by bimix** [aws/aws-sdk-js-v3#3573]
## Describe the bug
I am using the Timestream SDK for React-Native but I am facing an issue when configuring the client. 

```
import { TimestreamQueryClient, CreateDatabaseCommand } from "@aws-sdk/client-timestream-query";

const client = new TimestreamQueryClient({
   region: "eu-west-1",
   credentials: new Credentials('XXXXXXXXXXXX', 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXX'), // fails here
   apiVersion: 'latest'
});

```
## Your environment
React Native

#### SDK version number
"@aws-sdk/client-timestream-query": "^3.79.0",

#### Is the issue in the browser/Node.js/ReactNative?
ReactNative

#### Details of the browser/Node.js/ReactNative version
"react-native": "0.68.0"

## Steps to reproduce
Install SDK in a bare RN project, and have the configuration code set as I do above. Run RN app.

#### Expected behavior
No error.

**Comment by ajredniwja** [comment]
Hey @bimix thanks for opening this issue, can you please share complete reproducible code? For above piece of code I can run it just fine using my own credentials.
