### ISSUE TITLE
ES6 imports don't work in `@aws-sdk/client-iotsitewise`

### ISSUE THREAD

**Issue by diehbria** [aws/aws-sdk-js-v3#3578]
## Describe the bug
Importing the client cannot be done utilizing ES6, as documented in https://www.npmjs.com/package/@aws-sdk/client-iotsitewise 

Works:
```js
const { IoTSiteWiseClient } = require("@aws-sdk/client-iotsitewise");
```

Does **not** work:
```js
import { IoTSiteWiseClient } from "@aws-sdk/client-iotsitewise";
```

## Your environment
OSX

#### SDK version number
`@aws-sdk/client-iotsitewise@3.80.0`

#### Is the issue in the browser/Node.js/ReactNative?
Browser

#### Details of the browser/Node.js/ReactNative version
`v14.19.1`

## Steps to reproduce
`npm i --save @aws-sdk/client-iotsitewise`
and then attempt to import:

```js
import { IoTSiteWiseClient } from "@aws-sdk/client-iotsitewise";
```

#### Observed behavior
`Module not found: Error: Can't resolve 'aws-sdk/client-iotsitewise' in $REDACTED_DIRECTORY`

#### Expected behavior
To be able to import utilizing the officially documented ES6 syntax

## Additional context
Has been an issue for at least several months.

**Comment by trivikr** [comment]
Assigning to @ajredniwja for triaging

**Comment by RanVaknin** [comment]
Hi @diehbria!

I reproduced your steps and ran into the same issue when using ES6 import statement.

I was able to run the file by renaming my file  from `filename.js` to `filename.mjs` indicating that this is a module.
Here are the official node [docs](https://nodejs.org/api/esm.html#enabling) 

Please let me know if this works for you.

**Comment by diehbria** [comment]
@RanVaknin thank you for the work around

but two comments:

- documentation states usage as `import { IoTSiteWiseClient, AssociateAssetsCommand } from "@aws-sdk/client-iotsitewise";`
- Even if you update the documentation to specify `.mjs`, this is a non-standard way for libraries to behave and will cause confusion on users. The SDKs should be bundled so they can be imported in ES6 _without_ a special `mjs` file extension. I cannot think of a single other library that requires users to specify `.mjs` to utilize `import` syntax.

**Comment by RanVaknin** [comment]
Hi @diehbria,

You don't have to use the `.mjs` extension to make it work. Please refer to [this part of the doc](https://nodejs.org/api/packages.html#type),
and consider the following project setup:
 
```
.
├── package.json
├── package-lock.json
└── some_folder_name/
    └── sample.js
``` 

**sample.js:**
```
import { IoTSiteWiseClient, AssociateAssetsCommand } from "@aws-sdk/client-iotsitewise";
```


**package.json:**
```
{
  "dependencies": {
    "@aws-sdk/client-iotsitewise": "^3.85.0",
    "serve": "^13.0.2"
  },
  "type": "module"
}
```

**Explanation:**
> Files ending with .js are loaded as ES modules when the nearest parent package.json file contains a top-level field "type" with a value of "module".
> 
> The nearest parent package.json is defined as the first package.json found when searching in the current folder, that folder’s parent, and so on up until a node_modules folder or the volume root is reached.
> 
> If the nearest parent package.json lacks a "type" field, or contains "type": "commonjs", .js files are treated as [CommonJS](https://nodejs.org/api/modules.html). If the volume root is reached and no package.json is found, .js files are treated as [CommonJS](https://nodejs.org/api/modules.html).


**Conclusion:**
This is a Node.JS requirement, and not an SDK specific issue. I'm going to close the ticket. If you feel like this is in fact SDK related, please feel free to open another ticket.
