### ISSUE TITLE
Build fails with: export 'getRegionInfo' (imported as 'getRegionInfo') was not found in '@aws-sdk/config-resolver'

### ISSUE THREAD

**Issue by gouthasnm** [aws/aws-sdk-js-v3#3581]
## Describe the bug
Build fails with:

ERROR in ./node_modules/@aws-sdk/client-location/dist-es/endpoints.js 82:17-30
export 'getRegionInfo' (imported as 'getRegionInfo') was not found in '@aws-sdk/config-resolver' (possible exports: NODE_REGION_CONFIG_FILE_OPTIONS, NODE_REGION_CONFIG_OPTIONS, REGION_ENV_NAME, REGION_INI_NAME, resolveEndpointsConfig, resolveRegionConfig)
 @ ./node_modules/@aws-sdk/client-location/dist-es/runtimeConfig.shared.js 2:0-56 10:138-163
 @ ./node_modules/@aws-sdk/client-location/dist-es/runtimeConfig.browser.js 12:0-84 24:27-49
 @ ./node_modules/@aws-sdk/client-location/dist-es/LocationClient.js 10:0-73 18:20-38
 @ ./node_modules/@aws-sdk/client-location/dist-es/index.js 2:0-33 2:0-33
 @ ./node_modules/@aws-amplify/geo/lib-esm/Providers/AmazonLocationServiceProvider.js 157:0-165 300:25-39 305:26-56 396:25-39 401:26-63 473:25-39 478:26-60
 @ ./node_modules/@aws-amplify/geo/lib-esm/Geo.js 156:0-90 239:28-57
 @ ./node_modules/@aws-amplify/geo/lib-esm/index.js 1:0-28 1:0-28
 @ ./node_modules/aws-amplify/lib-esm/index.js 36:0-39 36:0-39
 @ ./src/components/FireBoltApplicationLayout.tsx 20:0-34 21:0-35 43:0-17 44:0-14 52:23-46
 @ ./src/index.tsx 8:0-79 13:35-60

ERROR in ./node_modules/@aws-sdk/client-location/dist-es/runtimeConfig.browser.js 59:29-59
export 'DEFAULT_USE_DUALSTACK_ENDPOINT' (imported as 'DEFAULT_USE_DUALSTACK_ENDPOINT') was not found in '@aws-sdk/config-resolver' (possible exports: NODE_REGION_CONFIG_FILE_OPTIONS, NODE_REGION_CONFIG_OPTIONS, REGION_ENV_NAME, REGION_INI_NAME, resolveEndpointsConfig, resolveRegionConfig)
 @ ./node_modules/@aws-sdk/client-location/dist-es/LocationClient.js 10:0-73 18:20-38
 @ ./node_modules/@aws-sdk/client-location/dist-es/index.js 2:0-33 2:0-33
 @ ./node_modules/@aws-amplify/geo/lib-esm/Providers/AmazonLocationServiceProvider.js 157:0-165 300:25-39 305:26-56 396:25-39 401:26-63 473:25-39 478:26-60
 @ ./node_modules/@aws-amplify/geo/lib-esm/Geo.js 156:0-90 239:28-57
 @ ./node_modules/@aws-amplify/geo/lib-esm/index.js 1:0-28 1:0-28
 @ ./node_modules/aws-amplify/lib-esm/index.js 36:0-39 36:0-39
 @ ./src/components/FireBoltApplicationLayout.tsx 20:0-34 21:0-35 43:0-17 44:0-14 52:23-46
 @ ./src/index.tsx 8:0-79 13:35-60

## Your environment
Unix

#### SDK version number
`@aws-sdk/config-resolver@2.1077.0`

#### Is the issue in the browser/Node.js/ReactNative?
ReactNative

#### Details of the browser/Node.js/ReactNative version
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`
v14.18.3

## Steps to reproduce
Please share code or minimal repo, and steps to reproduce the behavior.
NA

#### Observed behavior
A clear and concise description of what happens.
Build fails
#### Expected behavior
Build Completes

#### Screenshots
NA

## Additional context
This issue started happening after aws-sdk upgrade from 2.1043.0 to 2.1077.0

**Comment by ajredniwja** [comment]
@gouthasnm thanks for opening this issue would you be able to share more info about your use case, the package you mention https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_config_resolver.html seems to be an internal package which is not advised to used directly. 

If you can share your code that'll be great for me to reproduce the error.
