### ISSUE TITLE
Document that some credential-providers are only available in Node.js environment

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#3586]
## Describe the issue with documentation
The README for `@aws-sdk/credential-providers` does not document which providers are available in which environments.
For example, the `fromEnv` credential provider is only available in Node.js environment.

## Steps to reproduce
Refer https://github.com/aws/aws-sdk-js-v3/blob/0d4912d4a8f9bed50424a8831527ee29d3fbf1b6/packages/credential-providers/README.md

#### Observed behavior
From documentation, it appears that `fromEnv` is available in all environments

#### Expected behavior
Call out which credential providers are available in which environments.

**Comment by t-lock** [comment]
I believe there is a larger issue here, where providers which _should_ be available in the browser rely on Node built-in modules, such as `http` and `os`. This is the case for `fromCognitoIdentityPool`.
