### ISSUE TITLE
Athena: StartQueryExecutionCommand - No output location provided

### ISSUE THREAD

**Issue by Schoko19961** [aws/aws-sdk-js-v3#3589]
## Describe the bug
When the StartQueryExecutionCommand is executed `ResultConfiguration -> OutputLocation` has to be provided even though it is configured in the Workgroup.

#### SDK version number
`@aws-sdk/client-athena@3.82.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Node.js 14.x (Lambda)

## Steps to reproduce
```
const client = new AthenaClient({});
const command = new StartQueryExecutionCommand({
    QueryString: `SELECT * FROM "${process.env.ATHENA_TABLE}"`,
    QueryExecutionContext: {
      Catalog: process.env.ATHENA_CATALOG,
      Database: process.env.ATHENA_DATABASE,
    },
    WorkGroup: process.env.ATHENA_WORKGROUP
  });
await client.send(command);
```

#### Observed behavior
The Query fails with the exception: `InvalidRequestException`

`No output location provided. An output location is required either through the Workgroup result configuration setting or as an API input.`

#### Expected behavior
Query succeeds without an OutputLocation provided in the request.

## Additional context
ATHENA_TABLE = Name of the table
ATHENA_CATALOG = "AwsDataCatalog" (AWS Glue Data Catalog)
ATHENA_DATABASE = Database name from Glue
ATHENA_WORKGROUP = Name of the Workgroup

The query works fine if OutputLocation is filled in the command parameters.

**Comment by ajredniwja** [comment]
Hey @Schoko19961 thanks for opening this issue, I believe this is is the desired behavior by the service as the documentation mentions: https://docs.aws.amazon.com/athena/latest/APIReference/API_ResultConfiguration.html

"To run the query, you must specify the query results location using one of the ways: either for individual queries using either this setting (client-side), or in the workgroup, using [WorkGroupConfiguration](https://docs.aws.amazon.com/athena/latest/APIReference/API_WorkGroupConfiguration.html). If none of them is set, Athena issues an error that no output location is provided. For more information, see [Query Results](https://docs.aws.amazon.com/athena/latest/ug/querying.html). If workgroup settings override client-side settings, then the query uses the settings specified for the workgroup."

I hope that helps please reach out if you have any other questions.
