### ISSUE TITLE
How can I get plaintext for a Uint8Array field for KMS?

### ISSUE THREAD

**Issue by paololim** [aws/aws-sdk-js-v3#3596]
## Describe the bug
When getting the response for `GenerateDataKeyPairCommand`, I expect `publicKey` in the response to be decodable to `string`. It looks like the data might be in a binary format? HEre's what I am trying to do in typescript:

```ts
  const cdk = await kmsClient.send(
    new GenerateDataKeyPairCommand({
      KeyId,
      KeyPairSpec: DataKeyPairSpec.RSA_4096,
    }),
  );

  const cdkPublicKey = toUtf8(cdk.PublicKey); // cdk.PublicKey is a Uint8Array
  console.log('cdkPublicKey', cdkPublicKey);
```

#### SDK version number
`@aws-sdk/client-kms": "^3.85.0`

## Steps to reproduce
In typescript:
```ts
  const cdk = await kmsClient.send(
    new GenerateDataKeyPairCommand({
      KeyId,
      KeyPairSpec: DataKeyPairSpec.RSA_4096,
    }),
  );

  const cdkPublicKey = toUtf8(cdk.PublicKey); // cdk.PublicKey is a Uint8Array
  console.log('cdkPublicKey', cdkPublicKey);
```

#### Observed behavior
Inability to use AWS' library methods to get the string representation of `PublicKey` and other similar fields.

#### Expected behavior
Ability to decode the `Uint8Array` fields such as `PublicKey` to string, where we can get the plaintext.

#### Screenshots
<img width="882" alt="Screen Shot 2022-05-06 at 6 40 46 AM" src="https://user-images.githubusercontent.com/85070/167116761-801b7fe5-0701-4588-8348-e484c819a3f9.png">

## Additional context
When using the AWS CLI, I get the exact thing I need - the plaintext string for `PublicKey`:
```
aws kms generate-data-key-pair \
--key-id arn:aws:kms:us-east-1:414583787973:key/b432eb41-617f-4b44-addf-4870c7021462 \
--key-pair-spec RSA_4096
{
    ...
    ...
    "PublicKey": "MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA8zpg35PbIC/+KCHiGSZr/SY80uZIlNYkO3P2YRL9bMdk6m2Syj+TjOpjx67Wj+vrHyVYabY8WgN5S/Qu3qJro08rBkT3cxIwHVB7iJr5geJ6/SwK3j8T2ZyA8ZaiCx3+qf6YOGzAoik2X5krIkol+SpNxs9vEhmMcJ4jwWW/8+/CZN0CjQ0QAyjjaojKcBZdxhzDZ2Vqe7vWp5AjRzlcwLnygCkywgkvSStAheePIQ6hyFdFbHJVCIE7zeG+ata9q6ouGspo4CFNdrVGn/MRb79vzeTnbnsuUvGIXcPSqONKCZeMRA+IzStkzxpZ2OoUYjPalFHv2kM+fLUFrJR4FO4d+w6WdMPlLFDD7qKaw3jnDSOmTPM73Isw4bYIjmSa00JQuMK1Nh0duW9nsR0XOuWKHo9uYDlwm43Sd9zij2wVzmy0FIXbj8ipt4ggZGkDiczK/q7XXsgMEGCgdPn0hcWUjoCqBlh0++cOLRTpHf52APVMhEJdsjimoOdGh97jZmQUwTKxA5l3hKkxEhHgVehRZDexHdQWgZpi28cEH5vCMUNCJo29awtp3YnUkO19lVEY18dourdeFji+FfELlqtl1VVh0DIohqneLBemDef2fT1olQyez//JckWJYIGwqRIk0AfxUSMe0hRT5evdotJ5guQCKZmoNvgwUXBKG8kCAwEAAQ==",
    "KeyId": "arn:aws:kms:us-east-1:414583787973:key/b432eb41-617f-4b44-addf-4870c7021462",
    "KeyPairSpec": "RSA_4096"
}
```

**Comment by trivikr** [comment]
@paololim Can you provide what the reason this issue was, and how you got help?
