### ISSUE TITLE
No regex pattern for SQS API request parameters

### ISSUE THREAD

**Issue by redvivi** [aws/aws-sdk-js-v3#3601]
## Describe the issue with documentation
No regex pattern is available for Request parameters for SQS API in https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html#API_ReceiveMessage_RequestParameters, contrary to https://docs.aws.amazon.com/textract/latest/dg/API_StartDocumentAnalysis.html#API_StartDocumentAnalysis_RequestParameters

It would be useful to validate input parameters.

Speaking of which, what is the expected pattern for queueUrl ?

**Comment by yenfryherrerafeliz** [comment]
Hi @redvivi, thanks for reaching out. I will pass your suggestion to the correspondent team. However, I can see that there is a description about how each parameter value should be, which you could consider to create your validations, for example:
>MaxNumberOfMessages
The maximum number of messages to return. Amazon SQS never returns more messages than this value (however, fewer messages might be returned). Valid values: 1 to 10. Default: 1.
    type: Integer
    Required: No

> MessageAttributeName.N
    The name of the message attribute, where N is the index.
        The name can contain alphanumeric characters and the underscore (_), hyphen (-), and period (.).
        The name is case-sensitive and must be unique among all attribute names for the message.
        The name must not start with AWS-reserved prefixes such as AWS. or Amazon. (or any casing variants).
        The name must not start or end with a period (.), and it should not have periods in succession (..).
        The name can be up to 256 characters long.

In the case of the queueUrl, this is a value that you can get in different ways:
- By using the AWS console; go to  Amazon SQS Service -> On the queue list, click on the desired one, then under details you will see something named URL, and that is your queueUrl.
- You could also use the SDK to get the queue url by providing the queue name, see my example below:
   ```js
    import {GetQueueUrlCommand, SQSClient} from "@aws-sdk/client-sqs";
    const clientParams = {
        region: 'REGION'
    };
    const sqsClient = new SQSClient(clientParams);
    const command = new GetQueueUrlCommand({
        QueueName: 'YOUR-QUEUE-NAME,
        //QueueOwnerAWSAccountId: '' // Provide this value if the queue is under another AWS account than yours
    });
    const response = await sqsClient.send(command);
    
    if (response['$metadata']['httpStatusCode'] === 200 ) {
        const queueUrl = response.QueueUrl;
        console.log('QueueUrl: ', queueUrl);
    }
   ```
The queue URL format should be something as follow:
-  https://sqs.REGION.amazonaws.com/AWS-ACCOUNT-NUMBER/SQS-QUEUE-NAME

Please if you have any questions just let me know.

Thanks!

**Comment by redvivi** [comment]
Thanks @yenfryherrerafeliz ,

Unfortunately, it partially answers to my request.

The provided example in my OP shows a regex pattern I could implement to validate inputs.

The documentation you quoted mentions the type of data, not the pattern nor their structure.

For instance, an integer can be either positive or negative. The aim to validate the input via regex is to prevent these kind of wrong parameters to be used when calling the functions.

**Comment by yenfryherrerafeliz** [comment]
@redvivi I agree with you, would be really nice to have the regex pattern ready to take and use. As I said before I will pass this suggestion to the correspondent team.

> Unfortunately, it partially answers to my request.

Please find below a regex pattern that can address the pattern for queueUrl. This is not something official, rather was something that I created myself:
- ``` (https|http)[:][\/]{2}(sqs)[.][a-z]{2}[-][a-z]{3,}[-][0-9]{1}[.](amazonaws.com)[\/][0-9]{12}[\/]{1}[a-zA-Z0-9-_]{0,80} ```

Thanks!
