### ISSUE TITLE
Protocol error in kinesis putRecords in aws sdk > 3.81.0

### ISSUE THREAD

**Issue by gugu** [aws/aws-sdk-js-v3#3602]
## Describe the bug
node:internal/http2/util in new NghttpError at line 556:5

#### SDK version number
```
        "@aws-sdk/client-dynamodb": "3.87.0",
        "@aws-sdk/client-kinesis": "3.88.0",
        "@aws-sdk/client-s3": "^3.88.0",
        "@aws-sdk/client-sqs": "^3.87.0",
```
#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Node.js v16.15.0

## Steps to reproduce

Reproduces only in production :( Code:

```typescript
    const usRequests: StatRequest[] = [];
    const euRequests: StatRequest[] = [];
    async function sendToKinesis(requests: StatRequest[], kinesis: KinesisClient, streamName: string) {
        if (requests.length >= flushAfter) {
            const requestsToSend = requests.splice(0);
            try {
                await kinesis.send(
                    new PutRecordsCommand({
                        StreamName: streamName,
                        Records: requestsToSend.map((data, idx) => ({
                            Data: textEncoder.encode(JSON.stringify(data)),
                            PartitionKey: idx.toString(),
                        })),
                    }),
                );
            } catch (err) {
                logger.error(err as Error);
                Sentry.captureException(err);
            }
        }
    }

await sendToKinesis(usRequests, usKinesis, "some-us-stream");
await sendToKinesis(euRequests, euKinesis, "some-eu-stream");

```

#### Observed behavior
Getting this error in 90% cases:
```
Error: Protocol error
  File "node:internal/http2/util", line 556, col 5, in new NghttpError
  File "node:internal/http2/core", line 785, col 26, in Http2Session.onSessionInternalError
  File "node:internal/async_hooks", line 130, col 17, in Http2Session.callbackTrampoline
```

#### Expected behavior
No error

## Additional context
3.81 worked fine

**Comment by curtdept** [comment]
https://github.com/aws/aws-sdk-js-v3/pull/3577#issuecomment-1119876067

**Comment by yenfryherrerafeliz** [comment]
Hi @gugu, thanks for reporting this. I expect that one of our developers take a look to this as soon as possible. In the meantime you could use the version 3.81 as @curtdept recommended.

Thanks!

**Comment by AllanZhengYP** [comment]
Hi @gugu, I found we didn't handle the server-side session close properly, it MAY caused the issue. I put up a fix #3619 for it and it will be shipped in today's release. Can you confirm whether it fix the issue for you?

**Comment by curtdept** [comment]
@AllanZhengYP just testing now, should know in about 40 mins

**Comment by curtdept** [comment]
@AllanZhengYP @up73k @L1fescape this appears to be stable and resolved. LGTM.

**Comment by cesarfd** [comment]
Hi, still failing with 3.95.0 (Node 16.15.0)

**Comment by curtdept** [comment]
@cesarfd do you have more error details? Im still stable atm.

**Comment by cesarfd** [comment]
> @cesarfd do you have more error details? Im still stable atm.

Pretty much the exact Protocol Error as @gugu described. Client is initialized with default settings, no special http flags or anything else.

**Comment by AllanZhengYP** [comment]
Hi @cesarfd Can you share your code snippet and where's the code is run? Like Node version, the platform and version, and other runtime information that will help use reproduce the case. @gugu mentions it happens 90% of the case, so it should be reproducable.

**Comment by DanielMuller** [comment]
I upgraded from 3.87.0 to 3.95.0. I haven't seen the error `Error [ERR_HTTP2_INVALID_SESSION]: The session has been destroyed` since (~last 10h).
The code and env is very similar to @cesarfd , with the difference that I am running Node16 with Lambda (I guess it's 16.14?)

**Comment by AllanZhengYP** [comment]
This ticket can be closed since the users have confirmed the issue resolves. If you are still experiencing this issue in newer SDK versions, please create a separate issue.

**Comment by cesarfd** [comment]
Hi, sorry for the late comment but I'm still getting the exact same protocol error with the latest 3.105.0. Any ideas?

**Comment by gugu** [comment]
Same issue, nothing was changed

**Comment by gugu** [comment]
@AllanZhengYP can you please reopen this issue? 3.110.0, same problem
