### ISSUE TITLE
signature-v4: generates wrong signature if method is lowercase

### ISSUE THREAD

**Issue by Lewenhaupt** [aws/aws-sdk-js-v3#3612]
## Describe the bug
[signature-v4](https://github.com/aws/aws-sdk-js-v3/tree/master/packages/signature-v4) generates incorrect signature if method is lowercase.

#### SDK version number
`@aws-sdk/signature-v4@3.75.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v14.18.3 

## Steps to reproduce
```js
const request = new HttpRequest({
      hostname: url.hostname,
      path: url.pathname,
      protocol: url.protocol,
      method: 'get',
      body: init!.body,
      headers: Object.fromEntries(headers.entries()),
    });
const signer = new SignatureV4({
    credentials: credentials || defaultProvider(),
    service: service,
    region: region,
    sha256: Sha256,
    applyChecksum: false,
});
```

#### Observed behavior
Incorrect signature is generated

#### Expected behavior
Expected the signature to be correct regardless of the case of the method

**Comment by Lewenhaupt** [comment]
> @Lewenhaupt thanks for opening this issue can you please share complete code(the method you use). 
> I use code like this which works fine.
> ```js
>   // Create the HTTP request
>   var request = new HttpRequest({
>       body: JSON.stringify(document),
>       headers: {
>       },
>       hostname: domain,
>       method: 'PUT',
>       path: ''
>   });
>       
>   // Sign the request
>   var signer = new SignatureV4({
>       credentials: defaultProvider(),
>       region: region,
>       service: 'es',
>       sha256: Sha256
>   });
>   
>   var signedRequest = await signer.sign(request);  
> ```

Try with lowercase put.

**Comment by RanVaknin** [comment]
@Lewenhaupt ,

This is not a bug. Method verbs are always uppercase per [RFC 7231](https://www.rfc-editor.org/rfc/rfc7231#section-4.1):
>This specification defines a number of standardized methods that are
   commonly used in HTTP, as outlined by the following table.  By
   convention, standardized methods are defined in all-uppercase
   US-ASCII letters.

Thanks,
Ran~
