### ISSUE TITLE
Missing DynamoDB ValidationException

### ISSUE THREAD

**Issue by m-radzikowski** [aws/aws-sdk-js-v3#3618]
## Describe the bug

DynamoDB will return a `ValidationException` in a variety of situations. One is when you send `UpdateItem` command with `UpdateExpression: SET nonexistingField = nonexistingField + 1`.

I tried importing `ValidationException` from `@aws-sdk/client-dynamodb`, `@aws-sdk/smithy-client`, and `@aws-sdk/types`. In all cases I get "TS2305: Module ... has no exported member 'ValidationException'.".

#### SDK version number

- `@aws-sdk/client-dynamodb@3.92.0`
- `@aws-sdk/lib-dynamodb@3.92.0`
- `@aws-sdk/types@3.78.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version

node: v16.13.1

## Additional context

As per https://aws.amazon.com/blogs/developer/service-error-handling-modular-aws-sdk-js/ there should be a class for each exception.

**Comment by yenfryherrerafeliz** [comment]
Hi @m-radzikowski, thanks for reaching out. ValidationException is not a class, instead is just a message that tell what the error is about. So, the class that is being thrown for this type of error is DynamoDBServiceException, which implementation can be found [here](https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-dynamodb/src/models/DynamoDBServiceException.ts), and this member can be easily imported from the dynamodb-client package.

Thanks!

**Comment by m-radzikowski** [comment]
I see. The `DynamoDBServiceException` is a bit of a "catch-all", though. I but understand that those errors are from different "levels" - DynamoDBServiceException and ValidationException. Thanks.
