### ISSUE TITLE
Add ability to limit bandwidth for S3 uploads

### ISSUE THREAD

**Issue by adamerce** [aws/aws-sdk-js-v3#3620]
### Is your feature request related to a problem? Please describe.
Currently there is no way to limit bandwidth while uploading S3 objects using the AWS SDK. This means that uploading an object could consume too much bandwidth and interfere with other processes running in parallel. There should be a way to configure a maximum bandwidth in cases where network bandwidth is limited.

### Describe the solution you'd like
Both the AWS CLI and Python SDK provide options for specifying the max bandwidth when uploading S3 objects: https://docs.aws.amazon.com/cli/latest/topic/s3-config.html and https://boto3.amazonaws.com/v1/documentation/api/latest/reference/customizations/s3.html#boto3.s3.transfer.TransferConfig. There should be a similar option for doing this using the Javascript SDK as either a part of the S3ClientConfig: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/interfaces/s3clientconfig.html or as parameter to the PutObject command.

### Describe alternatives you've considered
Currently, I have not seen an alternative way to limit bandwidth on S3 uploads in javascript

**Comment by kuhe** [comment]
I couldn't find any evidence that it is possible to limit the throughput of a single request in any browser while not affecting others.
