### ISSUE TITLE
Missing `@aws-sdk/smithy-client` dependency in `@aws-sdk/lib-storage`

### ISSUE THREAD

**Issue by mhassan1** [aws/aws-sdk-js-v3#3626]
## Describe the bug
In https://github.com/aws/aws-sdk-js-v3/commit/cbab94e901aec4650ab9e0eb19a4515e44d4ba62, an import of `@aws-sdk/smithy-client` was added, but that dependency is not in `package.json` of `@aws-sdk/lib-storage`. This breaks strict environments, like Yarn Plug'n'Play.

#### SDK version number
`@aws-sdk/lib-storage@3.92.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
`16.14.2`

## Steps to reproduce
```js
require('@aws-sdk/lib-storage')
```

#### Observed behavior
`Cannot find module '@aws-sdk/smithy-client'`

#### Expected behavior
No error

**Comment by pmiszczak-cksource** [comment]
I have the same problem. After downgrading from `3.95.0` to `3.80.0` it seems to work. I use `node@16.14.2` and `pnpm@6.24.2`

**Comment by kesavab** [comment]
I have the same problem

**Comment by ajbieber** [comment]
Experiencing the same issue using `@aws-sdk/lib-dynamodb`. Experiencing this issue with version `3.95.0`, `3.92.0` and `3.80.0`. Downgraded to `3.33.0` successfully

**Comment by ajredniwja** [comment]
Hi @mhassan1 thanks for opening this issue, I see `@aws-sdk/lib-storage` has dependency on `client-s3` which has a dependency on `smithy-client`. I'd advice to add the package to your package.json.

**Comment by mhassan1** [comment]
`@aws-sdk/lib-storage` should not `require` a transitive dependency, since that is ambiguous and breaks in strict environments like Yarn Plug'n'Play. It also may not work if `node_modules` hoisting results in `@aws-sdk/smithy-client` not being available to `@aws-sdk/lib-storage`, e.g. when using [nohoist](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/).

**Comment by ajredniwja** [comment]
@mhassan1 yes you are right, I was able to discuss this with my team, I will open a PR for this shortly.

**Comment by mhassan1** [comment]
I had opened https://github.com/aws/aws-sdk-js-v3/pull/3627, but feel free to decline that.

**Comment by ajredniwja** [comment]
Merged the PR, thanks for your contribution, closing the issue.
