### ISSUE TITLE
Error On importing the package in cpanel 

### ISSUE THREAD

**Issue by HasibullahMahmood** [aws/aws-sdk-js-v3#3628]
## Describe the bug
My Nodejs server runs without error if the below import code is commented and just by uncommenting the below code the server crashes and give the following error
const { TranscribeClient, StartTranscriptionJobCommand } = require('@aws-sdk/client-transcribe');

Error: EEXIST: file already exists, uv_pipe_open
    at new Socket (net.js:330:24)
    at process.getStdin [as stdin] (internal/bootstrap/switches/is_main_thread.js:179:17)
    at get (<anonymous>)
    at getOwn (internal/bootstrap/loaders.js:156:5)
    at NativeModule.syncExports (internal/bootstrap/loaders.js:268:31)
    at ModuleWrap.<anonymous> (internal/bootstrap/loaders.js:248:22)
    at NativeModule.getESMFacade (internal/bootstrap/loaders.js:253:17)
    at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:233:10)
    at loadNativeModule (internal/modules/cjs/helpers.js:40:9)
    at Function.Module._load (internal/modules/cjs/loader.js:772:15) {
  errno: -17,
  code: 'EEXIST',
  syscall: 'uv_pipe_open'
}
net.js:330
    err = this._handle.open(fd);

## Your environment
Nodejs version 16.15.0
Cpanel
#### SDK version number
`@aws-sdk/package-name@version`
"@aws-sdk/client-transcribe": "^3.95.0",

#### Is the issue in the browser/Node.js/ReactNative?
Browser/Node.js/ReactNative
Node.js
#### Details of the browser/Node.js/ReactNative version
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`
Nodejs version 16.15.0
## Steps to reproduce
Please share code or minimal repo, and steps to reproduce the behavior.

#### Observed behavior
A clear and concise description of what happens.

#### Expected behavior
A clear and concise description of what you were expecting to happen.

**Comment by RanVaknin** [comment]
Hi @HasibullahMahmood,

I see that you have omitted the "Steps to reproduce" part from this ticket. Without those details I don't have any context of what you are trying to do with the Transcribe client, and how it interacts with your existing code. 

For me to be able to reproduce the error you are experiencing, I would need more information from you, like your node.js server code, including the import statements, or any other pieces of information that I would need to reproduce your environment.

If you haven't already, please consider following [ this documentation page](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-transcribe/index.html) to set up your Transcribe Client. Perhaps by following these steps you can unblock yourself.
