### ISSUE TITLE
Class 'XXCommand' incorrectly implements interface 'Command<>'

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#363]
**Describe the bug**
* I'm getting the following error while examining types of PutItemCommand:
`Class 'PutItemCommand' incorrectly implements interface 'Command<InputTypesUnion, PutItemInput, OutputTypesUnion, PutItemOutput, DynamoDBResolvedConfiguration, Readable>'.`
* This error appears with other commands too - like DeleteItemCommand, GetItemCommand, ScanCommand, UpdateItemCommand

**SDK version number**
@aws-sdk/client-dynamodb-node@0.1.0-preview.2 

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
v10.16.0

**To Reproduce (observed behavior)**
* `yarn add @aws-sdk/client-dynamodb-node`
* `import { PutItemCommand } from "@aws-sdk/client-dynamodb-node/commands/PutItemCommand";` in some file
* `new PutItemCommand()`
* open `PutItemCommand.d.ts`

**Expected behavior**
No TypeScript error in type definitions of AWS JS SDK v3

**Screenshots**
![PutItemCommandTypeScriptError](https://user-images.githubusercontent.com/16024985/64996203-2b03b980-d892-11e9-9c3a-49a5c2a0f786.png)

**Additional context**
Repo which uses AWS JS SDK v3 is using typescript@3.5.3

**Comment by AllanFly120** [comment]
Close this issue because we recently moved to alpha clients. See [here](https://github.com/aws/aws-sdk-js-v3/issues/944) for more information. Please post a new issue if the bug persists in alpha clients.

**Comment by trivikr** [comment]
Verified that PutItemCommand doesn't show TypeScipt error anymore
![Screen Shot 2020-03-06 at 9 45 52 AM](https://user-images.githubusercontent.com/16024985/76108391-52a92400-5f8f-11ea-9450-8d25afbe7856.png)

```
$ yarn list @aws-sdk/client-dynamodb
└─ @aws-sdk/client-dynamodb@1.0.0-alpha.22
```
