### ISSUE TITLE
[shared-ini-file-loader] Upgrade the code to support node 14 to node 18.

### ISSUE THREAD

**Issue by SmashingQuasar** [aws/aws-sdk-js-v3#3638]
### Describe the bug

As of today, the code supports Node 12 to (possibly) node 16. It does not support node 18.
The problem originates from the way the `fs` module is used. In Node 14 the `promises` API has been splitted to `fs/promises`. Currently in Node 18, it is no longer possible to import `promises` from `fs`. It has to be imported properly from `fs/promises`.
Node 12 is no longer maintained and has reached the end of it's LTS status. The current LTS is Node 16.

### Expected Behavior

The code should comply to the recommended practices for the current LTS and offer support to the widest range of supported Node versions. This is currently not the case as the code uses an old import that no longer exists.

### Current Behavior

Currently, the files`getSSOTokenFromFile.ts` and  `slurpFile.ts` use the Node 12 and inferior import module. This prevents the `shared-ini-file-loader` package to be used with Node 18. Considering this package is shared among several clients and packages, it prevents a large part of the code base to be compatible with Node 18.

### Reproduction Steps

The fastest way to reproduce this problem is to use a Node 18 version and try to execute the unit test. Node.JS will throw an error saying that `fs` cannot be deconstructed as `{ readFile }` since it is undefined.

### Possible Solution

There are two imports to modify.

One is in `getSSOTokenFromFile.ts`, the other in `slurpFile.ts`.
Modifying those two imports makes the code compatible with Node 18. 

### Additional Information/Context

This modification will break compatibility with Node 13 and inferior.
Since those versions are no longer maintained by the Node.JS team, it should not be a major concern. 

### SDK version used

3.95

### Environment details (OS name and version, etc.)

Debian Bullseye

**Comment by SmashingQuasar** [comment]
I opened a PR resolving this issue here: https://github.com/aws/aws-sdk-js-v3/pull/3639

**Comment by yenfryherrerafeliz** [comment]
Hi @SmashingQuasar thank you for reaching out. We really appreciate this contribution, but we still support Node v12.x and the proposed changes may break customer, nonetheless [here](https://github.com/aws/aws-sdk-js-v3/issues/3641) is an announcement for when we may stop supporting Node v2. 

Thanks!

**Comment by SmashingQuasar** [comment]
Thanks for your quick answer, we'll use a fork in the meantime. :)
