### ISSUE TITLE
Stop exporting V2-style service client

### ISSUE THREAD

**Issue by AllanFly120** [aws/aws-sdk-js-v3#364]
**Is your feature request related to a problem? Please describe.**

Now with V3 you can import a service client like:
```javascript
const {DynamoDB} = require('@aws-sdk/client-dynamodb-browser');
const client = new DynamoDB({region, credential});
client.listTables({}, callback);
```
This makes switching from V2 SDK as smooth as possible. But it introduces a significant overhead code-size-wise. Because the class with all the available operations can be huge. 
Whereas this way you can acheive significantly smaller bundle size:
```javascript
const {DynamoDBClient, ListTablesCommand} = require('@aws-sdk/client-dynamodb-browser');
const client = new DynamoDB({region, credential});
const listTables = new ListTablesCommand({});
client.send(listTables).then(callback);
```
This makes code size smaller. It also works better on serverless services(i.e. AWS Lambda). But the V2 bridging interface make users confuse like #261 

**Describe the solution you'd like**
Remove the V2-like client class like: https://github.com/aws/aws-sdk-js-v3/blob/master/clients/browser/client-dynamodb-browser/DynamoDB.ts in every service package

**Comment by trivikr** [comment]
Removing v2-style service client won't reduce bundle size for importing clients and commands separately. Although v3-style helps reduce bundle size, it requires more code to be written and more imports to be managed. Some developers might prefer simplicity over performance.

**Comment by AllanFly120** [comment]
@trivikr Yea removing the V2 stype client will reduce the confusion. Some user gave us some very helpful feedback here also: https://github.com/aws/aws-sdk-js-v3/issues/213#issuecomment-476445865

**Comment by Amplifiyer** [comment]
I agree that the V3 style of imports should be default, but I don't think we should take away the V2 style just yet. It's substantially more work for customers to move from V2 to V3 using command interface and the flexibility provided in V3 is great to allow customers do it at their own pace (or in a timely fashion you can deprecate V2 style clients).

**Comment by trivikr** [comment]
> It's substantially more work for customers to move from V2 to V3 using command interface

Example diff for switching to v2 style:
```diff
-import AWS from "aws-sdk";
+import { DynamoDB } from "@aws-sdk/client-dynamodb";
-const client = new AWS.DynamoDB();
+const client = new DynamoDB();
/* Code to populate params inside a function */
-const result = await client.query(params).promise();
+const result = await client.query(params);
```

Example diff for switching to command style:
```diff
-import AWS from "aws-sdk";
+import { DynamoDBClient, QueryCommand } from "@aws-sdk/client-dynamodb";
-const client = new AWS.DynamoDB();
+const client = new DynamoDBClient();
/* Code to populate params inside a function */
-const result = await client.query(params).promise();
+const result = await client.send(new QueryCommand(params));
```

Of course the more commands customers use, they'll have to import them in command style. Assuming that they've written code such that only specific commands are used per file, it shouldn't be an issue.
If their code is calling multiple commands in single file (say 10+), then the code needs to be refactored. 

@Amplifiyer Are there other concerns over the work required in migration?

**Comment by Amplifiyer** [comment]
It's much straightforward for customers who are using modular client imports from V2 SDK such as `import * as DynamoDB from 'aws-sdk/clients/dynamodb'`. All they need to do is update the import and everything works as is. While in command interface, they have to update the code everywhere a service call is happening (not just the client generation).

**Comment by trivikr** [comment]
> All they need to do is update the import and everything works as is

They also need to update commands to remove `.promise()` call:
```diff
-import * as DynamoDB from "aws-sdk/clients/dynamodb";
+import * as DynamoDB from "@aws-sdk/client-dynamodb";
 
 const client = new DynamoDB();
 /* Code to populate params inside a function */
-const result = await client.query(params).promise();
+const result = await client.query(params);
```

In modular style, they'll have to create Command object in addition to remove `.promise()` as follows:
```diff
-import * as DynamoDB from "aws-sdk/clients/dynamodb";
+import * as DynamoDB from "@aws-sdk/client-dynamodb";
 
 const client = new DynamoDB();
 /* Code to populate params inside a function */
-const result = await client.query(params).promise();
+const result = await client.send(new QueryCommand(params));
```

**Comment by Amplifiyer** [comment]
I see, maybe customers using callbacks in V2 wouldn't have to change anything?

**Comment by ajredniwja** [comment]
I agree that removing v2 style clients will result in reducing the confusion.

**Comment by trivikr** [comment]
> maybe customers using callbacks in V2 wouldn't have to change anything?

That's right, no changes are required in calling of commands if customers still use `.then` as follows:
```diff
-import * as DynamoDB from "@aws-sdk/client-dynamodb";
+import * as db from "@aws-sdk/client-dynamodb";
 
-const client = new DynamoDB();
+const client = new db.DynamoDB();
 /* Code to populate params inside a function */
 const result = client.query(params).then((err, data) => {
   // Do stuff with err or data
});
```

For modular style, they'll have to edit the commands as follows:
```diff
-import * as DynamoDB from "@aws-sdk/client-dynamodb";
+import * as db from "@aws-sdk/client-dynamodb";
 
-const client = new DynamoDB();
+const client = new db.DynamoDB();
 /* Code to populate params inside a function */
-const result = client.query(params).then((err, data) => {
+const result = client.send(new QueryCommand(params)).then((err, data) => {
   // Do stuff with err or data
 });
```

Given that JS SDK v3 encourages using await everywhere (README/API reference/Developer Guide), I think users will stick to callbacks only if it's very difficult to allocate time for additional work to switch to await.

In the case where callbacks are still used, I think customers will mostly continue to use v2, and write their new projects/features in v3.

**Comment by trivikr** [comment]
> maybe customers using callbacks in V2 wouldn't have to change anything?

That's right, the callbacks will work in idiomatic way.

v2-style:
```diff
-import * as DynamoDB from "@aws-sdk/client-dynamodb";
+import * as db from "@aws-sdk/client-dynamodb";
  
-const client = new DynamoDB();
+const client = new db.DynamoDB();
  /* Code to populate params inside a function */
 const result = client.query(params, (err, data) => {
    // Do stuff with err or data
 });
```

command style:
```diff
-import * as DynamoDB from "@aws-sdk/client-dynamodb";
+import * as db from "@aws-sdk/client-dynamodb";
  
-const client = new DynamoDB();
+const client = new db.DynamoDB();
  /* Code to populate params inside a function */
-const result = client.query(params, (err, data) => {
+const result = client.send(new QueryCommand(params)).then((err, data) => {
    // Do stuff with err or data
 });
```

Given that JS SDK v3 encourages using await everywhere (README/API reference/Developer Guide), I think users will stick to callbacks only if it's very difficult to find time/resources for additional work required to switch to await.

In the case where callbacks are still used, I think customers will mostly continue to use v2, and write their new projects/features in v3.

**Comment by trivikr** [comment]
Responses from Gitter channel:
![Screenshot from 2019-11-22 08-54-13](https://user-images.githubusercontent.com/16024985/69444850-0dc1f000-0d06-11ea-8e87-0b80c0ff593a.png)

**Comment by trivikr** [comment]
Resolving as we decided to keep v2-style (legacy) clients in v3 for ease of migration
