### ISSUE TITLE
Compilation fails when aws-crt is not included

### ISSUE THREAD

**Issue by Clete2** [aws/aws-sdk-js-v3#3640]
### Describe the bug

I depend on `@aws-sdk/client-quicksight@3.99.0` and I am using the `ListUsers` and `DeleteUser` command. You can see my repo [here](https://github.com/StateFarmIns/terraform-aws-quicksight-user-pruning).

When I don't add `aws-crt` I get the following compilation error:

```
 ~/d/g/g/quicksight-pruning-test   master ±  yarn build
yarn run v1.22.19
$ webpack && echo '// This file is committed because Terraform needs it to be there. Source code is in src folder' > pruneQuickSightUsers.js && cat dist/pruneQuickSightUsers.js >> pruneQuickSightUsers.js
asset pruneQuickSightUsers.js 4.46 MiB [emitted] [minimized] (name: pruneQuickSightUsers)
orphan modules 3.4 MiB [orphan] 615 modules
runtime modules 1.25 KiB 5 modules
built modules 2.68 MiB [built]
  javascript modules 2.65 MiB
    modules by path ./node_modules/fast-xml-parser/src/*.js 43.2 KiB 9 modules
    modules by path ./node_modules/entities/lib/*.js 11.8 KiB
      ./node_modules/entities/lib/index.js 3.6 KiB [built] [code generated]
      + 3 modules
    ./src/pruneQuickSightUsers.ts + 255 modules 2.6 MiB [not cacheable] [built] [code generated]
    ./node_modules/@aws-sdk/util-user-agent-node/dist-es/is-crt-available.js 290 bytes [built] [code generated]
  json modules 30 KiB
    ./node_modules/entities/lib/maps/entities.json 28.4 KiB [built] [code generated]
    ./node_modules/entities/lib/maps/legacy.json 1.24 KiB [built] [code generated]
    ./node_modules/entities/lib/maps/xml.json 62 bytes [built] [code generated]
    ./node_modules/entities/lib/maps/decode.json 308 bytes [built] [code generated]

WARNING in ./node_modules/@aws-sdk/util-user-agent-node/dist-es/is-crt-available.js 3:96-114
Module not found: Error: Can't resolve 'aws-crt' in '/Users/m9ox/dev/git/github/quicksight-pruning-test/node_modules/@aws-sdk/util-user-agent-node/dist-es'
 @ ./node_modules/@aws-sdk/util-user-agent-node/dist-es/index.js 5:0-52 16:23-37
 @ ./node_modules/@aws-sdk/client-ses/dist-es/runtimeConfig.js 12:0-65 22:898-914
 @ ./node_modules/@aws-sdk/client-ses/dist-es/SESClient.js 10:0-73 15:24-42
 @ ./node_modules/@aws-sdk/client-ses/dist-es/index.js 2:0-28 2:0-28
 @ ./src/NotificationManager.ts 37:0-66 40:29-38 56:47-63
 @ ./src/pruneQuickSightUsers.ts 39:0-60 61:42-61

1 warning has detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.72.1 compiled with 1 warning in 28973 ms
✨  Done in 30.57s.
```

### Expected Behavior

I shouldn't have to install `aws-crt` as a dependency manually to get compilation to work.

### Current Behavior

I must `yarn add aws-crt` to get compilation to work.

### Reproduction Steps

1. `yarn add @aws-sdk/client-quicksight`
2. Invoke the QuickSight client from code
3. Try to compile from TypeScript w/ webpack
4. Compilation error

### Additional Information/Context

I saw other issues around this, but they were all resolved in the past. This seems like a new issue to me.

### SDK version used

3.99.0

### Environment details (OS name and version, etc.)

Happens on Mac & Linux

**Comment by yenfryherrerafeliz** [comment]
Hi @Clete2, thank you for reaching out. By using the default configuration for webpack I got not issues. 
Please see my below:

<summary>My dependencies:</summary>
<details>

```json
"dependencies": {
    "@aws-sdk/client-quicksight": "3.99.0",
  },
```
</details>

<summary>My output: </summary>
<details>

```sh
webpack
asset main.js 167 KiB [compared for emit] [minimized] (name: main) 1 related asset
orphan modules 1.68 MiB [orphan] 284 modules
runtime modules 937 bytes 4 modules
cacheable modules 1.44 MiB
  modules by path ./node_modules/@aws-crypto/ 105 KiB
    modules by path ./node_modules/@aws-crypto/sha256-browser/ 66.2 KiB 11 modules
    modules by path ./node_modules/@aws-crypto/ie11-detection/ 11.9 KiB 7 modules
    modules by path ./node_modules/@aws-crypto/util/build/*.js 9.73 KiB 5 modules
    modules by path ./node_modules/@aws-crypto/supports-web-crypto/ 17.3 KiB
      ./node_modules/@aws-crypto/supports-web-crypto/build/index.js 467 bytes [built] [code generated]
      + 2 modules
  modules by path ./node_modules/@aws-sdk/ 2.53 KiB
    ./node_modules/@aws-sdk/util-utf8-browser/dist-es/index.js + 2 modules 2.31 KiB [built] [code generated]
    ./node_modules/@aws-sdk/util-locate-window/dist-es/index.js 228 bytes [built] [code generated]
  ./src/index.js + 117 modules 1.31 MiB [built] [code generated]
  ./node_modules/bowser/es5.js 25.4 KiB [built] [code generated]

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value.
Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

webpack 5.72.1 compiled with 1 warning in 2464 ms
✨  Done in 2.92s.
```
</details>

So, in order to investigate this further could you please:
- Provide the webpack configuration that you are using
- Let me know if you are compiling for browser?

Note: Please redact any sensitive information.

Thanks!

**Comment by yenfryherrerafeliz** [comment]
Hi @Clete2, thanks for providing this information. I was able to reproduce the error this time. I noticed this error is generated just when building for node, but if the target is web there is not issues. I will mark this as investigating so we can look into this further. I will use this thread to provide updates regarding any resolution about this.

Thanks!

**Comment by yenfryherrerafeliz** [comment]
Hi @Clete2, after further investigation we noticed that what you are getting is just a warning that does not prevent the compilation to work. The warning complains about aws-crt, which is a not required dependency, since it is just used for specific cases like multi regional clients, etc. What we can do to suppress the warning is maybe to add this dependency as optional, nonetheless this may be done in future releases.

Thanks!

**Comment by Clete2** [comment]
@yenfryherrerafeliz Makes sense to me. Thank you!
