### ISSUE TITLE
[Announcement] Upgrade to Node.js >=14.x by 2022-10-31

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#3641]
Starting November 1 2022, the AWS SDK For JavaScript (v3) will no longer support Node.js 12.x which was EOL on April 30, 2022.

We encourage you to upgrade to Node.js 14.x or later. We recommend Node.js 16.x, which was released on April 26, 2021 and became active LTS on October 28, 2021.

More details in blog post [Announcing the end of support for Node.js 12.x in the AWS SDK for JavaScript (v3)](https://aws.amazon.com/blogs/developer/announcing-the-end-of-support-for-node-js-12-x-in-the-aws-sdk-for-javascript-v3/)

**Comment by trivikr** [comment]
This issue is for announcement and can be closed when support for Node.js <14.x ends on November 1, 2022.

**Comment by TysonAndre** [comment]
1. I had a question about something that wasn't clear from the issue or the announcement - How will the releases that start using Node.js 14 only syntax or features or dependencies be versioned?

E.g. will this just be a minor release, or will there be major releases of all `@aws-sdk/*` packages of aws-sdk-js-v3.
(to prevent accidentally updating transitive dependencies to versions that wouldn't work in Node.js 12)

If a developer is locally using Node.js 14 to develop, and runs a fresh `npm install` or `npm update`, they may create releases that wouldn't work in environments using the (no longer supported) Node.js 12 released (especially if the testing process used a newer Node.js than the deployment environment)
2. Another question: If newer releases of libraries in aws-sdk-js-v3 are used after that date, what will happen? Will they emit a deprecation notice but attempt to run anyway?

**Comment by trivikr** [comment]
> How will the releases that start using Node.js 14 only syntax or features or dependencies be versioned?
> E.g. will this just be a minor release, or will there be major releases of all @aws-sdk/* packages of aws-sdk-js-v3

The will be a minor release as per [AWS SDKs and Tools maintenance policy](https://docs.aws.amazon.com/sdkref/latest/guide/maint-policy.html):

> AWS reserves the right to stop support for an underlying dependency without increasing the major SDK version

---

> If newer releases of libraries in aws-sdk-js-v3 are used after that date, what will happen? Will they emit a deprecation notice but attempt to run anyway?

The deprecation notice is already emitted in versions released since May 25, 2022.

As mentioned in the blog post, we knowingly won't make code changes to break applications in Node.js 12.x
However, we'll target newer version of ECMAScript which works in Node.js 14.x+. Some features may not work if TypeScript code uses those newer ECMAScript features. As mentioned in the blog post, you can continue to use AWS SDK for JavaScript (v3) versions released before November 1, 2022 in Node.js <14.x.
