### ISSUE TITLE
ListInstancesCommand on js @aws-sdk/client-sso-admin return undefined

### ISSUE THREAD

**Issue by cpfarher** [aws/aws-sdk-js-v3#3648]
### Describe the bug

I'm trying to get **sso instances** with the api described here: [https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-sso-admin/index.html][1] without success. 

For that I write something like this:

    import {ListInstancesCommand, SSOAdminClient} from '@aws-sdk/client-sso-admin';
    const client = new SSOAdminClient({credentials: {accessKeyId: 'foo', secretAccessKey: 'bar'}, region: 'us-east-2'});
    const response = await client.send(new ListInstancesCommand({MaxResults: 100}))

That code returns a success response(200) but the instance object was undefined. This is the dump of response:

    {"$metadata": 
                  {
                   "httpStatusCode":200,
                   "requestId":"7a87a1a7-d0f8-4a79-be2c-0aa9c179bdac",
                   "attempts":1,
                   "totalRetryDelay":0
                  },
     "Instances": undefined,
     "NextToken": undefined
    }

While, If I use exactly the same keys on de [CLI][2] it works and I got 1 instance:

    aws sso-admin list-instances --max-items 100
The response:

    {
        "Instances": [
            {
                "InstanceArn": "arn:aws:sso:::instance/ssoins-6684c191c332b481",
                "IdentityStoreId": "d-9a6710feea"
            }
        ]
    }

Also, to know if it is something specific with the `@aws-sdk/client-sso-admin` in js, I implemented exactly the same idea with ruby:
[https://github.com/cpfarher/aws-sdk-client-sso-admin-ruby](https://github.com/cpfarher/aws-sdk-client-sso-admin-ruby)
and I got the same instance as with the CLI. So, I presume that is a bug in the js library

  [1]: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-sso-admin/index.html
  [2]: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sso-admin/list-instances.html

### Expected Behavior

Get the same result of instances with js library, CLI, and Ruby library.

### Current Behavior

return undefined for js library and return 1 instance when I use CLI or Ruby library of AWS.

### Reproduction Steps

JS:     
    import {ListInstancesCommand, SSOAdminClient} from '@aws-sdk/client-sso-admin';
    const client = new SSOAdminClient({credentials: {accessKeyId: 'foo', secretAccessKey: 'bar'}, region: 'us-east-2'});
    const response = await client.send(new ListInstancesCommand({MaxResults: 100}))

Ruby: 
    https://github.com/cpfarher/aws-sdk-client-sso-admin-ruby

CLI:
    aws sso-admin list-instances

### Additional Information/Context

Package.json
"@aws-sdk/client-iam": "^3.9.0",
"@aws-sdk/client-sso-admin": "^3.95.0",
"@aws-sdk/types": "^3.6.1",

Node: v14.17.6, 

### SDK version used

3

### Environment details (OS name and version, etc.)

Linux 5.13.0-41-generic #46~20.04.1-Ubuntu SMP Wed Apr 20 13:16:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by yenfryherrerafeliz** [comment]
Hi @cpfarher, thanks for reaching out. I tried to reproduce the reported behavior but in my case I got successfully results. Please see below my code:
<details>

```js
import {SSOAdminClient, ListInstancesCommand} from "@aws-sdk/client-sso-admin";

const params = {
    region: 'REGION',
};
const ssoAdminClient = new SSOAdminClient(params);
const listInstancesCommand = new ListInstancesCommand({
    MaxResults: 100
});
const promise = ssoAdminClient.send(listInstancesCommand);

promise.then(response => {
    console.log('Response: ', response);
}).catch(reason => {
    console.log('Error: ', reason);
});
```
</details>

And here is my response:
<details>

```js
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'e457f28a-3bfa-45d2-bceb-c9214760491f',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Instances: [
    {
      IdentityStoreId: 'IDENTITY_STORED_ID',
      InstanceArn: 'arn:aws:sso:::instance/SSOID'
    }
  ],
  NextToken: undefined
}

```
</details>

I could notice that in your JS code you are specifying the credentials and the region directly, while that for ruby and cli you are using what is configure on your environment or profile, so that could you please confirm that you are using the same credentials and region that you used for ruby and cli also for JS?. 

Thanks!

**Comment by cpfarher** [comment]
> Hi @cpfarher, thanks for reaching out. I tried to reproduce the reported behavior but in my case I got successfully results. Please see below my code:
> 
> ```js
> import {SSOAdminClient, ListInstancesCommand} from "@aws-sdk/client-sso-admin";
> 
> const params = {
>     region: 'REGION',
> };
> const ssoAdminClient = new SSOAdminClient(params);
> const listInstancesCommand = new ListInstancesCommand({
>     MaxResults: 100
> });
> const promise = ssoAdminClient.send(listInstancesCommand);
> 
> promise.then(response => {
>     console.log('Response: ', response);
> }).catch(reason => {
>     console.log('Error: ', reason);
> });
> ```
> 
> And here is my response:
> 
> ```js
> {
>   '$metadata': {
>     httpStatusCode: 200,
>     requestId: 'e457f28a-3bfa-45d2-bceb-c9214760491f',
>     extendedRequestId: undefined,
>     cfId: undefined,
>     attempts: 1,
>     totalRetryDelay: 0
>   },
>   Instances: [
>     {
>       IdentityStoreId: 'IDENTITY_STORED_ID',
>       InstanceArn: 'arn:aws:sso:::instance/SSOID'
>     }
>   ],
>   NextToken: undefined
> }
> ```
> 
> I could notice that in your JS code you are specifying the credentials and the region directly, while that for ruby and cli you are using what is configure on your environment or profile, so that could you please confirm that you are using the same credentials and region that you used for ruby and cli also for JS?.
> 
> Thanks!

Hey thanks for you answer, yes, I used exaclty the same, but is it this line right?. I realized that in ruby I "build" a credential object while in js I call directly without calling any method form the sdk: 
```js
const client = new SSOAdminClient({credentials: {accessKeyId: 'foo', secretAccessKey: 'bar'}, region: 'us-east-2'});
```
obviously I replace foo and bar with the keys generated on AWS for the user that I used here.

**Comment by yenfryherrerafeliz** [comment]
> Yes, I used exactly the same, but is it this line right?.

@cpfarher - Yes, you can also pass the credentials when instancing the client, so that that line is also correct. In my case I have the credentials configured in my AWS credentials file, however I got successfully results even providing the credentials as you did. 
[Here](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/setup-credentials.html) is also some documentation about setting up credentials in your environment.

Did you get the same results when using my code?

Thanks!

**Comment by cpfarher** [comment]
> > Yes, I used exactly the same, but is it this line right?.
> 
> @cpfarher - Yes, you can also pass the credentials when instancing the client, so that that line is also correct. In my case I have the credentials configured in my AWS credentials file, however I got successfully results even providing the credentials as you did. [Here](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/setup-credentials.html) is also some documentation about setting up credentials in your environment.
> 
> Did you get the same results when using my code?
> 
> Thanks!

Yes, I got exactly the same result (undefined)

**Comment by yenfryherrerafeliz** [comment]
@cpfarher - Yes, I used the same versions you provided. Please see below my dependencies:
```json
"dependencies": {
    "@aws-sdk/client-iam": "3.9.0",
    "@aws-sdk/client-sso-admin": "3.95.0",
    "@aws-sdk/types": "3.6.1"
 }
```

Could you try enabling logger?, and then share the results. here is a sample code to do this:
```js
const params = {
    region: 'REGION',
    credentials: {accessKeyId: 'ACCESS-KEY-ID', secretAccessKey: 'SECRET-ACCESS-KEY'},
    logger: {
        info: function (log) {
            console.log('Info:', log);
        },
    }
};
``` 

And the whole code would looks as follow:
```js
import {SSOAdminClient, ListInstancesCommand} from "@aws-sdk/client-sso-admin";

const params = {
    region: 'REGION',
    credentials: {accessKeyId: 'ACCESS-KEY-ID', secretAccessKey: 'SECRET-ACCESS-KEY'},
    logger: {
        info: function (log) {
            console.log('Info:', log);
        },
    }
};
const ssoAdminClient = new SSOAdminClient(params);
const listInstancesCommand = new ListInstancesCommand({
    MaxResults: 100
});
const promise = ssoAdminClient.send(listInstancesCommand);
```

Note: please redact any sensitive information.

Thanks!

**Comment by cpfarher** [comment]
> 

Sure, Here is the output:
```json 
{"clientName":"SSOAdminClient","commandName":"ListInstancesCommand","input":{"MaxResults":100},"output":{},"metadata":{"httpStatusCode":200,"requestId":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","attempts":1,"totalRetryDelay":0}}
```

I put the string `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx` instead the real requestId

**Comment by cpfarher** [comment]
> @cpfarher - Yes, I used the same versions you provided. Please see below my dependencies:
> 
> ```json
> "dependencies": {
>     "@aws-sdk/client-iam": "3.9.0",
>     "@aws-sdk/client-sso-admin": "3.95.0",
>     "@aws-sdk/types": "3.6.1"
>  }
> ```
> 
> Could you try enabling logger?, and then share the results. here is a sample code to do this:
> 
> ```js
> const params = {
>     region: 'REGION',
>     credentials: {accessKeyId: 'ACCESS-KEY-ID', secretAccessKey: 'SECRET-ACCESS-KEY'},
>     logger: {
>         info: function (log) {
>             console.log('Info:', log);
>         },
>     }
> };
> ```
> 
> And the whole code would looks as follow:
> 
> ```js
> import {SSOAdminClient, ListInstancesCommand} from "@aws-sdk/client-sso-admin";
> 
> const params = {
>     region: 'REGION',
>     credentials: {accessKeyId: 'ACCESS-KEY-ID', secretAccessKey: 'SECRET-ACCESS-KEY'},
>     logger: {
>         info: function (log) {
>             console.log('Info:', log);
>         },
>     }
> };
> const ssoAdminClient = new SSOAdminClient(params);
> const listInstancesCommand = new ListInstancesCommand({
>     MaxResults: 100
> });
> const promise = ssoAdminClient.send(listInstancesCommand);
> ```
> 
> Note: please redact any sensitive information.
> 
> Thanks!

```
{
  clientName: 'SSOAdminClient',
  commandName: 'ListInstancesCommand',
  input: { MaxResults: 100 },
  output: { Instances: undefined, NextToken: undefined },
  metadata: {
    httpStatusCode: 200,
    requestId: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}

```
I replaced the real requestId by X

**Comment by cpfarher** [comment]
I build a repo for nodejs: https://github.com/cpfarher/aws-sdk-client-sso-admin-nodejs and it works!, it's weird, I used exactly the same code as I used in the other app. So it appears to be some bug in my other app :face_with_spiral_eyes:
