### ISSUE TITLE
Cloudsearch: Allow adding multiple search index at once

### ISSUE THREAD

**Issue by ShivamJoker** [aws/aws-sdk-js-v3#3650]
### Describe the feature

Ability to add multiple indexes in one request like we have in the AWS console

![image](https://user-images.githubusercontent.com/23727670/170861822-a2e64a81-e036-47f1-8607-47302f198dd3.png)

### Use Case

Right now we can only add one index at a time using `DefineIndexFieldCommand`, I have multiple indexes which I want to add. 
So I will have to run a loop and send the command request many times.

### Proposed Solution

```js
const command = new DefineIndexFieldCommand({
  DomainName: "ziki-artists",
  // allow indexField to be an array
  IndexField: [{
    IndexFieldName: "test",
    IndexFieldType: "text",
  }]
});
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

"@aws-sdk/client-cloudsearch": "^3.100.0",

### Environment details (OS name and version, etc.)

Manjaro Linux x86_64

**Comment by yenfryherrerafeliz** [comment]
Hi @ShivamJoker, 

I know this feature would be a great one to have in our SDK; however we prioritize bug fixes and feature requests based on community engagement and reactions. At this time there is not intention to implement this feature. 

Thanks!
