### ISSUE TITLE
Documentation pages are not rendered correctly

### ISSUE THREAD

**Issue by dvsu** [aws/aws-sdk-js-v3#3665]
# Describe the issue

The content of documentation page is incorrectly rendered in the browser. In this example, I choose [DynamoDB](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/classes/dynamodb.html) documentation page to describe the issue in details.

<img width="807" alt="rendered-2" src="https://user-images.githubusercontent.com/55182282/171986305-3349abce-3e37-467c-b2a3-8502e8699244.png">

If we check the HTML of the page, we can see the non-code content is actually wrapped in code block.

```html
<section>
  ...
  <ul class="tsd-descriptions active">
    <li class="tsd-description current">
      ...
      <div class="tsd-comment tsd-typography">
        <div class="lead">...</div>
          <pre>
            <code>...</code>
          </pre>
        </div>
      </div>
    </li>
  </ul>
</section>
```

Below is the screenshot of 2 HTML sections, `batchWriteItem` which has issue as per description and `createBackup` which has no issue. 

<img width="725" alt="html" src="https://user-images.githubusercontent.com/55182282/171986288-87df6e93-9b1f-4db0-a435-1978a8a911b5.png">

***Rendered output***

<img width="776" alt="rendered-1" src="https://user-images.githubusercontent.com/55182282/171986303-42aa8224-354c-4e28-8fa0-5c6f5b6bb720.png">

Affected sections on DynamoDB page:
- [batchWriteItem](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/classes/dynamodb.html#batchwriteitem)
- [createGlobalTable](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/classes/dynamodb.html#createglobaltable)
- [deleteTable](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/classes/dynamodb.html#deletetable)
- [describeLimits](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/classes/dynamodb.html#describelimits)
- [putItem](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/classes/dynamodb.html#putitem)
- [query](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/classes/dynamodb.html#query)
- [restoreTableToPointInTime](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/classes/dynamodb.html#restoretabletopointintime)
- [transactWriteItems](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/classes/dynamodb.html#transactwriteitems)

# Preliminary check

I randomly picked 10 services to check whether the issue persists on the other page. Below is the result.

***Good*** ✅
- [Amplify](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-amplify/classes/amplify.html)
- [API Gateway](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-api-gateway/classes/apigateway.html)
- [Cloud9](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-cloud9/classes/cloud9.html)
- [CloudFormation](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-cloudformation/classes/cloudformation.html)
- [RDS](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-rds/classes/rds.html)

***Bad*** ⚠
- [DynamoDB](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/classes/dynamodb.html)
- [EC2](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-ec2/classes/ec2.html)
- [EKS](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-eks/classes/eks.html)
- [Route 53](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-route-53/classes/route53.html)
- [S3](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/classes/s3.html)

It seems the issue may propagate to other documentation pages as well.

# Environment

This issue has been reproduced using the following browsers

**Brave** Version 1.39.111 Chromium: 102.0.5005.61 (Official Build) (arm64)
**Google Chrome** Version 102.0.5005.61 (Official Build) (arm64)
**Firefox** Version 101.0 (64-bit)
**Safari** Version 15.5 (17613.2.7.1.8)

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/classes/dynamodb.html
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-ec2/classes/ec2.html
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-eks/classes/eks.html
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-route-53/classes/route53.html
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/classes/s3.html

**Comment by ypliu-AWS** [comment]
> Thanks for opening this issue @dvsu, I have reached out to the docs team to check whats going wrong where. V606035294

This issue has been resolved in the latest API reference.

**Comment by MYoung25** [comment]
We appreciate you bringing this to our attention. We have released a [dev preview](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/) of the new API documentation for AWS SDK for JavaScript v3 based on your and other customers' feedback. Please let us know your thoughts on the new documentation by [providing feedback](https://github.com/aws/aws-sdk-js-v3/issues/new?assignees=&labels=documentation%2Cneeds-triage&template=documentation.yml&title=%28short+issue+description%29). We have a list of [outstanding issues](https://github.com/aws/aws-sdk-js-v3/discussions/4656) to address before our new documentation is GA'd. Thank you!

**Comment by ajredniwja** [comment]
Closing this issue now.
