### ISSUE TITLE
ERROR NPM INSTALL @aws-sdk/client-s3

### ISSUE THREAD

**Issue by ddslima** [aws/aws-sdk-js-v3#3671]
### Describe the bug

npm install @aws-sdk/client-s3
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @aws-sdk/middleware-sdk-s3@3.105.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

### Expected Behavior

npm install @aws-sdk/client-s3
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @aws-sdk/middleware-sdk-s3@3.105.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

### Current Behavior

npm install @aws-sdk/client-s3
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @aws-sdk/middleware-sdk-s3@3.105.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

### Reproduction Steps

npm install @aws-sdk/client-s3
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @aws-sdk/middleware-sdk-s3@3.105.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

### SDK version used

3.54.0

### Environment details (OS name and version, etc.)

MACOS

**Comment by sl-omideidivandi** [comment]
i get the same issue with latest but installing [3.109.0](https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.109.0) works for me
