### ISSUE TITLE
No way to know when you can call SSM.

### ISSUE THREAD

**Issue by johnlabarge** [aws/aws-sdk-js-v3#3676]
### Describe the bug

There is no way to tell whether an instance is ready to run SSM documents. As a result it repeatedly throws an error similar to: 
```
InvalidInstanceId: Instances [[i-xxxxxx]] not in a valid state for account xxxx  
```
I worked around it by 
```js
const retrySSMCommand = async(attempts: number, instanceId: string ) => {
    if (attempts == 0) {
        throw Error ("failed to complete ssm command.")
    }
    const commandInput = {
        DocumentName: "AWS-RunShellScript",
    //@ts-ignore
        Parameters: {
            commands: [ //...]
            "executionTimeout": ["3000"]
        },
        InstanceIds: [instanceId],
        TimeoutSeconds: 6000
    };
            const command = new SendCommandCommand(commandInput);
            const response = ssmClient.send(command)
            response.then((info) => {
                const commandId = info.Command?.CommandId
                if (commandId) {
                        pollCommand(commandId)
                       //...
                } else {
                    throw new Error("send command failed")
                }
            }).catch((e) => {
                console.log("error with ssm command: "+e)
                return retrySSMCommand(attempts-1,instanceId,password)
            })
        } 
    return { success: true, times: attempts};
    }
```

My check before this to try to get a glimmer as to whether ssm is ready is: 
```js
const waitForSsm = async (instance:string) => {
    await timer(5000)
    const filter = {Key:"InstanceIds",Values:[instance]}
    const command = new DescribeInstanceInformationCommand({Filters:[filter]})
    var result = await ssmClient.send(command)
    var info = result.InstanceInformationList?.[0]
    var agentVersion = info?.AgentVersion
    if (agentVersion) {
        var pingStatus = info?.PingStatus;
        if (pingStatus == 'Online') { 
            console.log("ping status is online"); 
            return;
        }
    } else {
        console.log("waiting again")
    }
    waitForSsm(instance);
}
```

This is some ugly stuff indeed. I'd love to know if there is a better way.  This is simple automation script to setup a developer productivity tool in EC2. 

### Expected Behavior

There should be some way to query the instance to determine if the session manager is ready to accept documents.  

### Current Behavior

Current behavior is that I repeatedly catch those errors until the document finally goes through. 

### Reproduction Steps

Create a new instance and run a shell script document even with all status indicators that the instance is ready for ssm commands it still is not. 

### Possible Solution

This may reach back to the AWS api or it may be something you can hack into the client - not sure but something needs to tell the orchestrator - the automation program - definitively whether the instance is ready for ssm. 

### Additional Information/Context

This may be an issue with AWS SSM itself. I guess I should just bite the bullet and have devs use EKS clusters.

### SDK version used

v3. 60.0 (typescript)

### Environment details (OS name and version, etc.)

Mac OS X 12.4

**Comment by yenfryherrerafeliz** [comment]
Hi @johnlabarge, thanks for opening this issue. We do not have this option/feature available in none of our SDKs, however, we have a cross SDK repository to handle this type of requests, so that I recommend you to please post a feature request there. Here is the [link](https://github.com/aws/aws-sdk).

Thanks!
