### ISSUE TITLE
How do you use DAX with the DynamoDB v3 client?

### ISSUE THREAD

**Issue by dzou** [aws/aws-sdk-js-v3#3687]
### Describe the issue

Are there any instructions how to use DAX with the aws-sdk v3 Dynamo client? I could only find examples of how to do it with the v2 client, but I want to use the v3 client.

For context, we already are using v3 in many places; would be disappointing to have to migrate to v2 to use DAX.

### Links

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DAX.client.run-application-nodejs.03-getitem-test.html

**Comment by ajredniwja** [comment]
Hi @dzou thanks for opening this issue, you can use [@aws-sdk/client-dax](https://www.npmjs.com/package/@aws-sdk/client-dax). https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dax/globals.html

Is that what you were looking for?

**Comment by dzou** [comment]
@ajredniwja -- No, `@aws-sdk/client-dax` is different. That is a much lower-level client, which only appears to let you create/delete clusters. But we want to do something where the Dynamo client will hit DAX first to check cache, and then fallback to Dynamo if it's not there.

See this example in the AWS documentation: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DAX.client.run-application-nodejs.03-getitem-test.html

The `amazon-dax-client` automatically lets you hit DAX first, then hit Dynamo if missing.

**Comment by ajredniwja** [comment]
@dzou my bad, unfortunately it is not supported currently. There is an internal feature request for the DAX team. 
See https://github.com/aws/aws-sdk/issues/232

I'll close this issue in favor of the existing issue and try to get an update on it.
Let me know if you have any other questions.
