### ISSUE TITLE
__dirname is not defined Please check if you have installed   @aws-sdk/signature-v4-crt

### ISSUE THREAD

**Issue by sharabiania** [aws/aws-sdk-js-v3#3692]
### Describe the bug

Trying to send an event to the event bridge using this code which is from the examples in the documentation:

```js
const client = new EventBridgeClient({ region: "us-east-2" });

const command = new PutEventsCommand({
  EndpointId: "something....ypm",
  Entries: [
    {
      Time: item.time,
      Detail: JSON.stringify(item),
      DetailType: item.eventType,
      EventBusName: process.env.EVENT_BUS_NAME,
      Source: item.source,
    },
  ],
});

const res = await client.send(command);
```

client.send() throws this exception:

```console
__dirname is not defined\nPlease check if you have installed \"@aws-sdk/signature-v4-crt\" package explicitly. \nFor more information please go to https://github.com/aws/aws-sdk-js-v3#functionality-requiring-aws-common-runtime-crt
```

I have already installed `npm install @aws-sdk/signature-v4-crt` but sill get the above error message.

### Expected Behavior

Send event to the EventBridge

### Current Behavior

Throws exception that package is missing and __dirname is undefine. Package is already installed.

### Reproduction Steps

Use the code above

### SDK version used

3.110

### Environment details (OS name and version, etc.)

Node.js 16

**Comment by RanVaknin** [comment]
Hi @sharabiania ,

Can you please provide full code? I'm missing a lot of information about what you are trying to do.
That snippet you provided is missing import statements, `async` keyword to go with the `await`. The code right now is not executable, and I cannot make up the missing code without more context.

Many thanks!

**Comment by sharabiania** [comment]
Hi @RanVaknin,

This is a code for a Lambda handler, I'm trying to put an event in EventBridge so the full code for the lambda handler is:

```
import {
  EventBridgeClient, 
  PutEventsCommand,
} from "@aws-sdk/client-eventbridge";


export async function handler(event) {

  const client = new EventBridgeClient({region: "us-east-2"});
     const command = new PutEventsCommand({
        EndpointId: 'something....ypm',
        Entries: [{
          Time: item.time,
          Detail: JSON.stringify(item),
          DetailType: item.eventType,
          EventBusName: process.env.EVENT_BUS_NAME,
          Source: item.source,
        }]
      });
       const res = await client.send(command);
    }
}
```

And dependecies in my Package.json:

```
 "devDependencies": {
    "@serverless-stack/cli": "^1.2.3",
    "@serverless-stack/resources": "^1.2.3",
    "@tsconfig/node16": "^1.0.2",
    "@typescript-eslint/eslint-plugin": "^5.26.0",
    "typescript": "^4.6.4",
  },

 "dependencies": {
    "@aws-sdk/client-eventbridge": "^3.110.0",
    "@aws-sdk/signature-v4-crt": "^3.110.0",
    "@types/aws-lambda": "^8.10.97",
    "aws-crt": "^1.12.4",
    "eslint-config-serverless-stack": "^0.69.7",
    "aws-cdk-lib": "2.28.0"
  }
```

**Comment by RanVaknin** [comment]
Hi @sharabiania , 

Thanks for the more details. Unfortunately I'm not able to reproduce your issue. I'm able to create events and send them to my EventBus without any issues using your code:

```js
import { EventBridgeClient, PutEventsCommand } from "@aws-sdk/client-eventbridge"; 
  
export async function handler() {
  
    const client = new EventBridgeClient({region: "us-east-1"});
        const command = new PutEventsCommand({
            EndpointId: '<<Your Endpoint>>',
            Entries: [{
              Detail: JSON.stringify({hello:"world"}),
              DetailType: 'hello',
              EventBusName: 'test_event_bus',
              Source: "test_app"
            }]
        });

    try {
        const res = await client.send(command);
        console.log(res)
    } catch (error) {
        console.log(error)
    }
}
```

I'm not sure why you are getting the `__dirname` error. It usually stems from a that global being called from a module rather than an commonJS file. Can you please add your complete error stack trace?

Thanks!

**Comment by sharabiania** [comment]
@RanVaknin Update: When I remove the `EndpointId` it works for me, but it uses the Default Event Bus.

**Comment by sharabiania** [comment]
My full Package.json:

```
{
  "eslintConfig": {
    "extends": [
      "serverless-stack"
    ]
  },
  "name": "qx-events-pipeline",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "sst start",
    "build": "sst build",
    "deploy": "sst deploy --stage dev --region us-east-2",
    "deploy-staging": "sst deploy --stage staging --region us-east-2",
    "deploy-prod": "sst deploy --stage prod --region us-east-2",
    "remove": "sst remove",
    "console": "sst console",
    "typecheck": "tsc --noEmit",
    "test": "vitest run",
    "lint": "eslint -c \"../.eslintrc\" \"**/*.ts\" --ignore-path \"../.eslintignore\"",
    "lint-fix": "eslint -c \"../.eslintrc\" \"**/*.ts\" --ignore-path \"../.eslintignore\" --fix"
  },
  "workspaces": [
    "backend"
  ],
  "devDependencies": {
    "aws-cdk-lib": "2.28.0",
    "@serverless-stack/cli": "^1.2.3",
    "@serverless-stack/resources": "^1.2.3",
    "@tsconfig/node16": "^1.0.2",
    "@typescript-eslint/eslint-plugin": "^5.26.0",
    "eslint": "^8.16.0",
    "eslint-import-resolver-typescript": "^2.7.1",
    "eslint-plugin-import": "^2.26.0",
    "typescript": "^4.6.4",
    "vitest": "^0.12.9"
  },
  "peerDependencies": {
    "aws-cdk-lib": "2.28.0"
  },
  "dependencies": {
    "@aws-sdk/client-eventbridge": "^3.110.0",
    "@aws-sdk/signature-v4-crt": "^3.110.0",
    "@types/aws-lambda": "^8.10.97",
    "aws-crt": "^1.12.4",
    "eslint-config-serverless-stack": "^0.69.7",
    "aws-cdk-lib": "2.28.0"
  }
}
```

**Comment by RanVaknin** [comment]
@sharabiania, this is odd.
I don't see anything outstanding with the `package.json` 

I wonder if your endpoint subdomain is the problem. Mine ends with `.veo` like in [the docs](https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_Endpoint.html). I wonder if that makes a difference. 
Can you try setting up another global endpoint (you need two event buses in two different regions with the same name).
You can check the [Eventbridge API](https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_CreateEndpoint.html) for more in depth explanation of each required field

Do you have any rules? If so I suggest you detach them from the bus for now and see if you can isolate the issue.

**Comment by RanVaknin** [comment]
Can you try to delete your `package.json` and `package-lock.json` and run `npm init` again? I know this seems silly but I feel like this is an NPM issue.

**Comment by sharabiania** [comment]
@RanVaknin 
I have already tried all that before creating an issue here :)

- Deleting Package.json
- Deleting Package-lock.json
- Deleting node_modules
- Clear npm cache `npm cache clear --force`
- Using CDK instead of SST
- Using node version 14.x in both my lambda and local environment.
- Using node version 16.x
- CommonJS vs ESM when building using esBuild
- Adding/Removing `type: module` in package json

**Comment by RanVaknin** [comment]
Hi @sharabiania ,

Thanks for being thorough in going through your steps. Can you take a look in [these docs](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/events/put-events.html) and try to make the same request from the CLI? Im asking you to do this so we can make sure it is an SDK issue an not service related.

I have consulted other devs on our team and they can't really pinpoint why this is happening. Since this is not reproducible, we are left with a lot of guess-work.

Thanks again.
