### ISSUE TITLE
signature-v4 has a transitive dependency aws-crt#1.12.4 which has a size of 600MB+

### ISSUE THREAD

**Issue by amitlevy-bu** [aws/aws-sdk-js-v3#3715]
### Describe the bug

Our container image size has grown to a size of `1.2 GB`, investigating the issue I found that `aws-crt#1.12.4` is the source of the issue.
![image](https://user-images.githubusercontent.com/98011907/174469118-d411234d-552a-40a8-b43b-e3acb286a4e6.png)

Using `aws-crt#1.12.3` has a normal size, by adding to `package.json`:
```json
  "resolutions": {
    "aws-crt": "1.12.3"
  }
```

I got:
![image](https://user-images.githubusercontent.com/98011907/174469197-a02f9ee0-6ca0-4844-b54e-ea6831861d6e.png)

Used package version: `@aws-sdk/signature-v4-crt@3.110.0`

### Expected Behavior

I expect to have a package size of:
`Disk size with transitive dependencies: "36.52MB"`

### Current Behavior

I get a huge size of package:
`Disk size with transitive dependencies: "633.91MB"`

### Reproduction Steps

1. `rm -rf node_modules yarn.lock package-lock.json && yarn`
2. `yarn why aws-crt`
3. See that the size of package is 600MB+ 

### Possible Solution

in signature-v4 package, change `package.json`  `"aws-crt": "^1.12.2"` to `"aws-crt": "1.12.3"` until a proper release of `aws-crt` is out.

### SDK version used

@aws-sdk/signature-v4-crt@3.110.0

### Environment details (OS name and version, etc.)

Fedora 36

**Comment by RanVaknin** [comment]
@amitlevy-bu Hi Amit,

I was able to reproduce your issue. 
Let me talk to the team and see what can be done. 

Thanks!

**Comment by amitlevy-bu** [comment]
Thank you @RanVaknin

**Comment by sbSteveK** [comment]
v1.12.5 should fix this issue: https://github.com/awslabs/aws-crt-nodejs/releases/tag/v1.12.5

**Comment by amitlevy-bu** [comment]
Thanks @RanVaknin @sbSteveK , size is back to normal
