### ISSUE TITLE
Pausing and resuming transcription @aws-sdk/client-transcribe-streaming causing error

### ISSUE THREAD

**Issue by ricardotwilio** [aws/aws-sdk-js-v3#3720]
### Describe the bug

`TranscribeStreaming` from `@aws-sdk/client-transcribe-streaming` has a `destroy` method that, as per the [source code](https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-transcribe-streaming/src/TranscribeStreamingClient.ts#L296), it is designed to destroy underlying resources, including sockets. However, after invoking destroy upon an existing client and initialising the client again, the application fails with the following error:

**`Another stream is in progress with the same session ID`**

This application makes use of `@aws-sdk/client-transcribe-streaming` so as to start/stop/restart the transcription on demand. For that, we have tried creating a new `TranscribeStreaming` every-time we want to start/restart transcribing audio, and destroying the client for stopping the transcription.

#### A simplified version of the client
```typescript
export class AwsTranscribeStrategy implements TranscriptionsStrategy {
  // (...)
  constructor(private accessKeyId: string, private secretAccessKey: string, private sessionToken: string) { }

  public async startTranscription() {
    this.params = {
      LanguageCode: LanguageCode.EN_US,
      MediaEncoding: MediaEncoding.PCM,
      MediaSampleRateHertz: 16000,
      AudioStream: this.audioStream(),
    };

    this.client = new TranscribeStreaming({
      region: 'us-east-1',
      credentials: { accessKeyId, secretAccessKey, sessionToken },
    });
  
    const command = new StartStreamTranscriptionCommand(this.params);
    const response = await this.client.send(command);
  }

  public stopTranscription() {
    this.client?.destroy();
  }
  // (...)
}
```

#### Somewhere else in the application
```typescript
if (someCondition) {
    transcriber.startTranscription();
} else {
    transcriber.stopTranscription();
}
```

Staring the transcription works fine and the application receives and processes the `TranscriptResultStream` events as expected.

However, stopping the transcription (by destroying the client) and trying to start it again causes the application to fail with the following error.

![image](https://user-images.githubusercontent.com/63280641/174757760-129e93ef-f41c-462c-85df-41f94eb91bfb.png)

So, it looks like the destroy method on the TranscribeStreaming instance does not actually close the session, or perhaps there is something we are missing?

### Expected Behavior

Calling `destroy()` on the `TranscribeStreaming`  client closes the connection and clears all the resources so that a new transcriptions over websockets session can be started by sending a new `StartStreamTranscriptionCommand` command.

### Current Behavior

Calling `destroy()` on a TranscribeStreamingClient instance with an ongoing stream transcription over websockets (initiated with a `StartStreamTranscriptionCommand`) and trying to start a new transcriptions session results in an error. **_Another stream is in progress with the same session ID_**

### Reproduction Steps

1) Create a `TranscribeStreaming` or `TranscribeStreamingClient`with valid credentials.
2) Create a `StartStreamTranscriptionCommand` (example params in the description)
3) Start transcribing by sending the command through the client ([see example](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-transcribe-streaming/index.html#send-the-speech-stream))
4) Destroy the client invoking `destroy()` method.
5) Repeat steps (1), (2) and (3)

### SDK version used

3.100

### Environment details (OS name and version, etc.)

macOS monterrey, 12.4

**Comment by RanVaknin** [comment]
Hi @ricardotwilio ,
Thanks for reaching out about this interesting issue.

In full disclosure I have never worked with `@aws-sdk/client-transcribe-streaming` before. Can you let me know which audioStream method you opted to use? If there is a front end client needed to reproduce this can you please add some basic code that will allow me to run it?

If you can share how you setup that audio stream that will help a lot. Thank you very much!
