### ISSUE TITLE
Connection timeouts don’t include socket pool wait time

### ISSUE THREAD

**Issue by silverlyra** [aws/aws-sdk-js-v3#3722]
### Describe the bug

When a command sent through the AWS SDK blocks waiting for a socket to free up in `NodeHttpHandler`’s HTTP agent, those requests can block indefinitely – the returned `Promise` is not necessarily ever resolved or rejected.

We experienced this in production, and I was at first very confused as to how it would be possible.

### Expected Behavior

Setting [the `connectionTimeout` option](https://github.com/aws/aws-sdk-js-v3/blob/main/packages/node-http-handler/src/node-http-handler.ts#L17-L21) should reliably abort requests that cannot establish a connection within the timeout, even when the reason is due to `maxSockets` contention.

### Current Behavior

`NodeHttpHandler` only [starts the timeout countdown after the `socket` event](https://github.com/aws/aws-sdk-js-v3/blob/main/packages/node-http-handler/src/set-connection-timeout.ts#L9). There is no way to set a timeout on acquiring a socket from the `https.Agent`’s pool.

### Reproduction Steps

Construct an explicit `NodeHttpHandler` with an explicit `httpsAgent` whose `maxSockets` is set to `1`, and cause an AWS SDK request to take long time. Another request made during that will never resolve nor reject its `Promise`, even when `connectionTimeout` is set.

### Possible Solution

Move [the `setTimeout`](https://github.com/aws/aws-sdk-js-v3/blob/main/packages/node-http-handler/src/set-connection-timeout.ts#L12) out of the `socket` event handler.

### Additional Information/Context

By default, `NodeHttpHandler` [sets a `maxSockets` of 50](https://github.com/aws/aws-sdk-js-v3/blob/main/packages/node-http-handler/src/node-http-handler.ts#L64), meaning that the default SDK configuration can trigger this behavior.

The [official developer guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/node-configuring-maxsockets.html) describes how to use a different value of that (or set it to `Infinity`); may also be nice to add a note that users may wish to always set `connectionTimeout` when using a limited socket pool.

Might also be a good idea to not set a different default [`maxSockets` than Node.js itself does](https://nodejs.org/api/http.html#agentmaxsockets) (`Infinity`), or simply to have the default behavior be to use the [default](https://nodejs.org/api/http.html#httpglobalagent) Node.js HTTP[S] agents.

### SDK version used

@aws-sdk/node-http-handler 3.82.0

### Environment details (OS name and version, etc.)

Amazon Linux 2

**Comment by RanVaknin** [comment]
@silverlyra, 

Can you please check out workaround suggested by @askldjd to see if it solves your issue?

Thanks,
Ran~
