### ISSUE TITLE
IAMClient builds an invalid service endpoint

### ISSUE THREAD

**Issue by cheslip** [aws/aws-sdk-js-v3#373]
**Describe the bug**
When building the service endpoint, `IAMClient` inserts the region into the URL, like this:
`iam.us-east-1.amazonaws.com`.

According to [AWS docs](https://docs.aws.amazon.com/general/latest/gr/rande.html), the URL for all non-GovCloud regions should be `iam.amazonaws.com`.

**SDK version number**
0.1.0-preview.2

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
```
❯  node -v
v12.10.0
```

**To Reproduce (observed behavior)**
```typescript
import { IAMClient } from "@aws-sdk/client-iam-node/IAMClient";
import { ListAccessKeysCommand } from "@aws-sdk/client-iam-node/commands/ListAccessKeysCommand";

const iam = new IAMClient({
  credentials: {
    accessKeyId: "<key id>",
    secretAccessKey: "<access key>"
  }
});

iam.send(new ListAccessKeysCommand({}));
```

**Expected behavior**
`IAMClient` should send the list-access-keys command

**Screenshots**
```
❯  ts-node index.ts 
(node:68286) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND iam.us-east-1.amazonaws.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)
(node:68286) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:68286) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Additional context**
Tried adding an empty region to the `IAMClient` constructor, but URL is built as `iam..amazonaws.com`

**Comment by cheslip** [comment]
I was able to make it work by modifying the hostname with middleware:

```typescript
iam.middlewareStack.add(
  next => args => {
    args.request.hostname = "iam.amazonaws.com";
    return next(args);
  },
  {
    step: "build"
  }
);
```

**Comment by afeld** [comment]
I was able to work around by overriding the `endpoint`:

```js
new IAMClient({
  region,
  endpoint: "https://iam.amazonaws.com",
  // ...
});
```

**Comment by AllanFly120** [comment]
Hi @afeld @cheslip 

The issue has been fixed in the latest beta clients. Please refer to #944 for more information. If this problem persists in beta clients, please open a new issue so we can better tracking and fixing it.
