### ISSUE TITLE
No obvious way to apply a signed URL to an existing SDK request

### ISSUE THREAD

**Issue by qhenkart** [aws/aws-sdk-js-v3#3761]
### Describe the issue

I would assume this to be an easy and well documented recipe. I have a signed URL that I have received from my server, now I am trying to utilize the transcribe stream SDK to run it using my signature. However it is not clear to me how I can overwrite the signedURL that I've provided with the SDK's attempts to generate one

I've tried adding the endpoint config to the client but that had no affect. Any tips would be great

Nothing in the docs about this 

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-transcribe-streaming/index.html

**Comment by qhenkart** [comment]
Please tell me this isn't the proper way to do it
```
  client = new TranscribeStreamingClient({
    endpoint: url,
    signer: () => {
      return {
        presign: () => {
          return Promise.resolve({ protocol: "wss", hostname: "", path: url.slice(5) })
        },
      }
    },
  })


```

**Comment by kuhe** [comment]
You should be able to modify the URL with a middleware function https://aws.amazon.com/blogs/developer/middleware-stack-modular-aws-sdk-js/.

**Comment by yenfryherrerafeliz** [comment]
Hi @qhenkart, thanks for opening this issue. Could you please let me know if the documentation provided by @kuhe was helpful for your inquire?

Thanks!

**Comment by qhenkart** [comment]
Hi @yenfryherrerafeliz 

It was helpful to get the documentation to know how to properly handle something like this. I found the middleware utility to be fairly complicated. In the end I kept my hacky implementation because it was simple, worked and was easy to read for other devs.

I think the documentation would be greatly improved by some real world examples and recipes

**Comment by yenfryherrerafeliz** [comment]
Hi @qhenkart, I am glad you got a working workaround that meet your needs. I will pass your suggestion to the correspondent team about improving the examples from the documentation.

In the meantime I will close this issue.

Thank you!
