### ISSUE TITLE
Release 3.121.0 has sub-dependency versions defined that don't exist; can't install

### ISSUE THREAD

**Issue by timmywil** [aws/aws-sdk-js-v3#3766]
### Describe the bug

A recent release has bumped version numbers of some dependencies without releasing matching versions of those dependencies, possibly just one dependency, but I'm not sure how to check them all. This means npm/yarn installs of certain aws sdk packages will fail with 404s.

### Expected Behavior

Successful install.

### Current Behavior

```sh
$ npm install @aws-sdk/client-dynamodb
```

Result:
![image](https://user-images.githubusercontent.com/192451/176785183-ff42532d-b908-41c0-84d5-7688ce2a6b75.png)

```sh
$ npm install @aws-sdk/util-dynamodb
```

Result:
![image](https://user-images.githubusercontent.com/192451/176785370-8b9971a1-ed89-4a24-8ec3-e3cd7b5bb6d6.png)

### Reproduction Steps

```sh
$ npm install @aws-sdk/client-dynamodb
```

Also see:

```sh
$ npm info @aws-sdk/client-sts version
3.118.1
```

### Possible Solution

Release version 3.121.0 of client-sts, and any other missing sub-dependencies from the recent release, if any.

### SDK version used

3.121.0

### Environment details (OS name and version, etc.)

Windows 10

**Comment by halfnibble** [comment]
We are experiencing this problem as well. It seems like `3.121.0` _should_ be released, but it's not available on npmjs.

**Comment by yenfryherrerafeliz** [comment]
Hi @timmywil thanks for reporting this. We are currently investigating this and I will use this thread to provide updates as soon as I get it.

Thanks!

**Comment by yenfryherrerafeliz** [comment]
@timmywil in the meantime please use the version 3.118.0 which is working fine.

Thanks!

**Comment by yenfryherrerafeliz** [comment]
Linked GitHub issue [here](https://github.com/aws/aws-sdk-js-v3/issues/3767)

**Comment by yenfryherrerafeliz** [comment]
Hi @timmywil, this issue is caused by a npm outage, which we can follow up [here](https://status.npmjs.org/incidents/6wr25yb0b2dd).

Thanks!

**Comment by HongsCode** [comment]
@yenfryherrerafeliz 
When installing, can I choose the version?

I want @aws-sdk/client-cognito-identity package, but still occur issue.

npm ERR! notarget No matching version found for @aws-sdk/client-sts@3.121.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@aws-sdk/client-cognito-identity'
npm ERR! notarget

**Comment by itstriolink** [comment]
Same issue here, I couldn't find that specific version anywhere else besides here.

**Comment by HongsCode** [comment]
> @yenfryherrerafeliz When installing, can I choose the version?
> 
> I want @aws-sdk/client-cognito-identity package, but still occur issue.
> 
> npm ERR! notarget No matching version found for @aws-sdk/client-sts@3.121.0. npm ERR! notarget In most cases you or one of your dependencies are requesting npm ERR! notarget a package version that doesn't exist. npm ERR! notarget npm ERR! notarget It was specified as a dependency of '@aws-sdk/client-cognito-identity' npm ERR! notarget

---------------------------------------
use below in package.json and not fail

"@aws-sdk/client-cognito-identity": "^3.118.1"

**Comment by timmywil** [comment]
Thanks, seems to be working now. Closing my issue.
