### ISSUE TITLE
can't install client-config-service

### ISSUE THREAD

**Issue by diogobaltazar** [aws/aws-sdk-js-v3#3767]
### Describe the bug

Can't install the module due to uninstalled dependencies. But the dependencies' versions don't exist.

```
$ npm install @aws-sdk/client-config-service
npm install @aws-sdk/client-config-service
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @aws-sdk/client-sts@3.121.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

However, after `npm i @aws-sdk/client-sts`: 

```
$ npm info @aws-sdk/client-sts version
3.118.1
```

### Expected Behavior

Successful install

### Current Behavior

```
$ npm install @aws-sdk/client-config-service
npm install @aws-sdk/client-config-service
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @aws-sdk/client-sts@3.121.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

### Reproduction Steps

```
$ npm install @aws-sdk/client-config-service
```

### Possible Solution

Is it requesting a non-existing version?

### SDK version used

3.121.0

### Environment details (OS name and version, etc.)

ubuntu 20.04

**Comment by diogobaltazar** [comment]
Seems to work with:

```
npm i @aws-sdk/client-config-service@3.118.1
```

**Comment by yenfryherrerafeliz** [comment]
Hi @diogobaltazar thanks for reporting this. I can confirm the reported behavior. We will investigate this and I will use this thread to provide updates as soon as I get it.

Thanks!

**Comment by yenfryherrerafeliz** [comment]
Hi @diogobaltazar this issue is caused by a npm outage. We can see a status about it [here](https://status.npmjs.org/incidents/6wr25yb0b2dd).

Thanks.

**Comment by halfnibble** [comment]
Reposting here since this is the "non-duplicate" issue.
Can the aws-sdk-js-v3 team try republishing? NPM is saying they've fixed the publish issue, but that does not appear to automatically restore missing publishes.

**Comment by partharamanujam** [comment]
Reposting request here since this is the non-duplicate issue.
Please re-publish the package, or submit a ticket with npmjs for restoring the missing tarball.

**Comment by halfnibble** [comment]
Not sure what the resolution was, but this appears to be working now. Thanks.
https://www.npmjs.com/package/@aws-sdk/client-sts

## Current Tags

| Version | Downloads (Last 7 Days) | Tag |
| --------|--------------------------|-----|
| [1.0.0-alpha.18](https://www.npmjs.com/package/@aws-sdk/client-sts/v/1.0.0-alpha.18) | 1 | alpha |
| [3.121.0](https://www.npmjs.com/package/@aws-sdk/client-sts/v/3.121.0) | 0 | latest |
| [1.0.0-gamma.11](https://www.npmjs.com/package/@aws-sdk/client-sts/v/1.0.0-gamma.11) | 1 | gamma |
| [1.0.0-beta.5](https://www.npmjs.com/package/@aws-sdk/client-sts/v/1.0.0-beta.5) | 1 | beta |

**Comment by partharamanujam** [comment]
I too can confirm that this is now working for me 👍

**Comment by yenfryherrerafeliz** [comment]
Hi, missing packages are now available in npm and this issue should be resolved.

Thanks!
