### ISSUE TITLE
Version 3.121.0 is broken

### ISSUE THREAD

**Issue by bstienst** [aws/aws-sdk-js-v3#3768]
### Describe the bug

Doing npm update and I get this error:

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @aws-sdk/client-sts@3.121.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

### Expected Behavior

It updates to the latest.  Appears you are releasing a new version and broke npm

### Current Behavior

wont npm update

### Reproduction Steps

npm update 

### Possible Solution

Please fix your release

### SDK version used

3.121.0

### Environment details (OS name and version, etc.)

cloudshell

**Comment by yenfryherrerafeliz** [comment]
Hi @bstienst  thanks for reporting this. We have also a similar ticket [here](https://github.com/aws/aws-sdk-js-v3/issues/3767). We will investigate this and I will use this thread to provide updates as soon as I get it. We also have a similar ticket here

Thanks!

**Comment by yenfryherrerafeliz** [comment]
@bstienst in the meantime you could use the version 3.118.0, which does not have this issue.

Thanks!

**Comment by bstienst** [comment]
We are trying, but it keeps trying to load 3.121.0.  We are not directly using client-sts.  Its a dependency of other packages we are using.

**Comment by yenfryherrerafeliz** [comment]
Hi @bstienst , this issue is caused by a npm outage, which we can follow up [here](https://status.npmjs.org/incidents/6wr25yb0b2dd).

Thanks!

**Comment by JayceDugan** [comment]
[NPM updated status](https://status.npmjs.org/incidents/6wr25yb0b2dd):

> A fix has been implemented and we are monitoring the results. We are determining  which packages require backfill. Please open a ticket with support if your package has missing versions. https://npmjs.com/support

So fix implemented but 3.121.0 [hasn't come back just yet.](https://www.npmjs.com/package/@aws-sdk/client-sts)

**Comment by halfnibble** [comment]
Can the AWS team try republishing instead of waiting for an npmjs ticket?

**Comment by shubguptaa** [comment]
Facing the same issue, but using 3.118.1 works for me

**Comment by partharamanujam** [comment]
Facing the same issue - This package is mentioned as a dependency of @aws-sdk/client-cognito-identity-provider which is causing an error.

> npm ERR! code ETARGET
> npm ERR! notarget No matching version found for @aws-sdk/client-sts@3.121.0.
> npm ERR! notarget In most cases you or one of your dependencies are requesting
> npm ERR! notarget a package version that doesn't exist.
> npm ERR! notarget
> npm ERR! notarget It was specified as a dependency of '@aws-sdk/client-cognito-identity-provider'
> npm ERR! notarget

**Comment by azrikahar** [comment]
For anyone having trouble downgrading as the affected packages may be nested dependencies, we can use  [npm overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) (or yarn resolutions for yarn users) to make it'll installed the available version, which seems to be `3.118.1` at the moment.

For example, adding the following in the package.json file:

```js
  "overrides": {
    "@aws-sdk/client-sts": "3.118.1"
  }
```

(and add additional entries in the overrides for any other affected packages in your particular project)

**Comment by NecoHorne** [comment]
> For anyone having trouble downgrading as the affected packages may be nested dependencies, we can use [npm overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) (or yarn resolutions for yarn users) to make sure it'll install the available version, which seems to be `3.118.1` at the moment.
> 
> For example, adding the following in the package.json file:
> 
> ```js
>   "overrides": {
>     "@aws-sdk/client-sts": "3.118.1"
>   }
> ```
> 
> (and add additional entries in the overrides for any other affected packages in your particular project)

Unfortunately this is not working on my Elastic beanstalk instance, eb deploy keeps failing.

**Comment by ashen780** [comment]
for the yarn, u can use `resolution`
`  "resolutions": {
    "@aws-sdk/client-sts": "3.118.1",
    "@aws-sdk/credential-provider-ini": "3.118.1"
  }`

**Comment by rbargholz** [comment]
It's fixed for me.

**Comment by wp-dpa** [comment]
It resolved itself by now, agreed

**Comment by yenfryherrerafeliz** [comment]
Hi, missing packages are now available in npm and this issue should be resolved.

Thanks!
