### ISSUE TITLE
npm install client-sqs 3.121.0 fails due to client-sts incompatibility 

### ISSUE THREAD

**Issue by BerndWessels** [aws/aws-sdk-js-v3#3769]
### Describe the bug

`npm install @aws-sdk/client-sqs` for latest version `3.121.0` fails with

```
C:\test>npm i @aws-sdk/client-sqs
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @aws-sdk/client-sts@3.121.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@aws-sdk/client-sqs'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bernd\AppData\Roaming\npm-cache\_logs\2022-07-01T07_24_20_817Z-debug.log
```

### Expected Behavior

`npm install @aws-sdk/client-sqs` should succeed

### Current Behavior

`npm install @aws-sdk/client-sqs` fails with

```
C:\test>npm i @aws-sdk/client-sqs
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @aws-sdk/client-sts@3.121.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@aws-sdk/client-sqs'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bernd\AppData\Roaming\npm-cache\_logs\2022-07-01T07_24_20_817Z-debug.log
```

### Reproduction Steps

`npm install @aws-sdk/client-sqs` in any new npm project.

### Possible Solution

Feels like the required dependencies `@aws-sdk/client-sts` build or deploy has failed since it is still on  `latest: 3.118.1`

### SDK version used

latest: 3.121.0

### Environment details (OS name and version, etc.)

Windows 11, latest

**Comment by sunrisemoment** [comment]
Same issue here. MacOS Catalina, Monterey
![image](https://user-images.githubusercontent.com/25312891/176847982-9864807f-9c21-4793-9a8c-2e051e95f316.png)

**Comment by alok-singh** [comment]
Facing same issue need urgent help

![image](https://user-images.githubusercontent.com/14344214/176850447-f3c6b151-0c7e-40be-94a2-fce60052c7bf.png)

**Comment by NecoHorne** [comment]
[issue 3768](https://github.com/aws/aws-sdk-js-v3/issues/3768) 
[issue 3767](https://github.com/aws/aws-sdk-js-v3/issues/3767)

**Comment by shresthdeepgupta** [comment]
npm ERR! notarget No matching version found for @aws-sdk/client-sts@3.121.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

Same issue

**Comment by yenfryherrerafeliz** [comment]
Hi @BerndWessels, thanks for reporting this.

There was a npm outage yesterday that made some packages not to be available, even though they were published. However, the issue was fixed by npm, and the packages are now available. 

Thanks!
