### ISSUE TITLE
(short issue description)

### ISSUE THREAD

**Issue by ravikrranjan** [aws/aws-sdk-js-v3#3771]
### Describe the bug

![image](https://user-images.githubusercontent.com/18529652/176863888-b1ed2cf2-8ed6-4045-aeef-14c077f2ceb5.png)
we are creating presigned url for multi part upload. where number  of may be  200-300. we wanted to get all presinged url through single api(node express) call.  after using the application some time. we are getting the error 

### Expected Behavior

api should return presigned url for all the part

### Current Behavior

getPartPresignedUrl : - ProviderError: Error response received from instance metadata service

![image](https://user-images.githubusercontent.com/18529652/176864497-e4c8b5ed-a95b-449e-838e-ba8a89e8b75b.png)

### Reproduction Steps

Error generated in by sdk

node_modules/@aws-sdk/credential-provider-node/node_modules/@aws-sdk/credential-provider-imds/dist/cjs/remoteProvider/httpRequest.js:22:38)

### SDK version used

"@aws-sdk/client-s3": "3.18.0"

### Environment details (OS name and version, etc.)

ECS

**Comment by halfnibble** [comment]
You may already be aware, but 429 generally means you're being throttled. I recommend creating a queue with a small delay between each request.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429

**Comment by ravikrranjan** [comment]
When we are trying to throttled the request on local env. never throttling the request . I tried to send 1M request same time.
 where on ECS container it's throttling with easily with 200-300 request
 
Do you have any idea why on ECS not local ?
