### ISSUE TITLE
Cannot read property 'Error' of undefined" exception at loadEc2ErrorCode

### ISSUE THREAD

**Issue by orly-schwartz** [aws/aws-sdk-js-v3#3777]
### Describe the bug

EC2 api calls causes  `“Cannot read property 'Error' of undefined" exception at loadEc2ErrorCode”`

### Expected Behavior

error handler function should not throw exception 

### Current Behavior

Upon initiation of the “describe instances” api call, sporadically, for some of the calls, the “Cannot read property 'Error' of undefined\\n	at loadEc2ErrorCode” exception was thrown. 
For example 5 out of the 6000 api calls ailed (rate 20 rps)
The issue happened also when running the “create tag” command.

Stack: 

```console
:{\"message\":\"Cannot read property 'Error' of undefined\",\"stack\":\"TypeError: Cannot read property 'Error' of undefined\\n	at loadEc2ErrorCode (/opt/app/node_modules/@aws-sdk/client-ec2/dist-cjs/protocols/Aws_ec2.js:65707:21)\\n	at deserializeAws_ec2DescribeInstancesCommandError (/opt/app/node_modules/@aws-sdk/client-ec2/dist-cjs/protocols/Aws_ec2.js:14422:17)\\n	at runMicrotasks (<anonymous>)\\n	at processTicksAndRejections (node:internal/process/task_queues:96:5)\\n	at async /opt/app/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24\\n	at async /opt/app/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20\\n	at async StandardRetryStrategy.retry (/opt/app/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)\\n	at async /opt/app/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22\\n	at async execute (/opt/app/src/services/executer/Executer.ts:99:16)\\n	at async ConsumerService.invoke (/opt/app/src/services/consumer/ConsumerService.ts:122:34)\"}}"
```

### Reproduction Steps

run the DescribeInstancesCommand repeatedly a large number of time at a rate of 20 rps
```js
await this.ec2Client.send(
      new DescribeInstancesCommand({
        MaxResults: 20
      }),
    );
```

### SDK version used

@aws-sdk/client-ec2@3.121.0

### Environment details (OS name and version, etc.)

Linux 5.10.76-linuxkit x86_64

**Comment by RanVaknin** [comment]
Hi @orly-schwartz ,

I'm not able to reproduce the error.
Can you tell me how you set up your resources to get 20 reads per second? 

Thanks.
~Ran

**Comment by orly-schwartz** [comment]
Hi @RanVaknin ,

Im not setting up anything , the Request token bucket refill rate for non-mutating actions (filtered/paginated) is 20 rps

Thanks,
Orly
