### ISSUE TITLE
Peer dependency warning for abort-controller dependency in lib-storage

### ISSUE THREAD

**Issue by jekh** [aws/aws-sdk-js-v3#3784]
### Describe the bug

Installing @aws-sdk/lib-storage results in a missing peer dependency warning for @aws-sdk/abort-controller. @aws-sdk/lib-storage [declares a peer dependency on @aws-sdk/abort-controller here](https://github.com/aws/aws-sdk-js-v3/blob/main/lib/lib-storage/package.json#L33). However, it looks like @aws-sdk/abort-controller is optional (lib-storage functions without it, as long as you don't want to abort), and it's also possible to use an alternate AbortController implementation.

Would it be possible to set the peerDependency to optional, using the the same method as this PR? https://github.com/aws/aws-sdk-js-v3/pull/3465 That should take care of unnecessary peer dependency warnings.

### Expected Behavior

No peer dependency warning when @aws-sdk/abord-controller is not installed

### Current Behavior

There is a peer dependency warning

### Reproduction Steps

Add @aws-sdk/lib-storage to a project without @aws-sdk/abort-controller. pnpm is particularly good about showing missing peer dependency warnings.

### Possible Solution

Adding a `peerDependenciesMeta` section to package.json with abort-controller set to optional should fix the issue:
```json
 "peerDependenciesMeta": {
    "@aws-sdk/abort-controller": {
      "optional": true
    }
  },
```

### SDK version used

3.121.0

### Environment details (OS name and version, etc.)

Node 16

**Comment by ajredniwja** [comment]
@jekh thanks for opening this issue, I can discuss it with the team and open a PR for the solution.

**Comment by nireld** [comment]
Up

**Comment by kuhe** [comment]
this is no longer applicable since lib-storage has no peerDependency on abort-controller anymore, as of v3.363.0.
