### ISSUE TITLE
GreengrassV2 Client fails with CORS policy: Request header field amz-sdk-invocation-id is not allowed

### ISSUE THREAD

**Issue by vcarnogu** [aws/aws-sdk-js-v3#3787]
### Describe the bug

`GreengrassV2Client` SDK V3 fails when called from Web browser. Response is blocked because some HTTP headers are not allowed by the back-end service.

### Expected Behavior

Response data should be returned.

### Current Behavior

Response is:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://greengrass.eu-central-1.amazonaws.com/greengrass/v2/coreDevices/device1. (Reason: header ‘amz-sdk-invocation-id’ is not allowed according to header ‘Access-Control-Allow-Headers’ from CORS preflight response).

### Reproduction Steps

Run code like this in a web browser.

```js
const loginData = {
    [cognitoIdp]: idToken
}

const client = new GreengrassV2Client({
  region: REGION,
  credentials: fromCognitoIdentityPool({
    clientConfig: { region: REGION }, 
    identityPoolId: identityPool,
    logins: loginData
  })
});


const input = {coreDeviceThingName: "device1"}
const command = new GetCoreDeviceCommand(input);

response = await client.send(command);
```

### Possible Solution

Similar to this: https://github.com/aws/aws-sdk-js-v3/issues/1590 the Greengrass API team need to support retry CORS headers. I assume: `amz-sdk-invocation-id`, `amz-sdk-request`

### Additional Information/Context

POST CORS pre-flight only allows:

access-control-allow-headers: Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent,X-Amz-Content-Sha256

### SDK version used

@aws-sdk/client-greengrassv2: 3.121.0

### Environment details (OS name and version, etc.)

aws-sdk-js/3.121.0 os/macOS/10.15 lang/js md/browser/Firefox_101.0 api/greengrassv2/3.121.0

**Comment by RanVaknin** [comment]
Hi @vcarnogu ,

Thanks for reaching out about this issue. Can you please open the same issue in the [IOT repo](https://github.com/aws/aws-iot-device-sdk-js-v2)?
I don't mean to bounce you around, we just have dedicated engineers on that team that can better help you.

Please let me know if you need anything else.
Thanks!

**Comment by vcarnogu** [comment]
@RanVaknin it is not a IoT Device SDK v2 related (it doesn't have GetCoreDevice function or equivalent). It it related to '@aws-sdk/client-greengrassv2' of  aws-sdk-js-v3, specifically this https://github.com/aws/aws-sdk-js-v3/tree/main/clients/client-greengrassv2. I understand the change needs to be done not in the JS library but on the backend Greengrass service to allow new headers by the service team like in https://github.com/aws/aws-sdk-js-v3/issues/1590.
