### ISSUE TITLE
Kinesis Video Client browser config issue

### ISSUE THREAD

**Issue by danemauland** [aws/aws-sdk-js-v3#3794]
### Describe the bug

In the runtimeConfig file for the browser, there is a check that throws an error if credentialDefaultProvider does not exist. However, the Kinesis Video Client declaration file states for the credentialDefaultProvider: "Default credentials provider; Not available in browser runtime."

### Expected Behavior

I expected the kinesis video client to not throw an error when the credentialDefaultProvider is missing in a browser environment

### Current Behavior

It throws an error when the credentialDefaultProvider is missing in a browser environment

### Reproduction Steps

```js
import { KinesisVideoClient, GetSignalingChannelEndpointCommand } from "@aws-sdk/client-kinesis-video";
import { KinesisVideoSignalingClient, GetIceServerConfigCommand } from "@aws-sdk/client-kinesis-video-signaling";

const region = ""
const ChannelARN = ""

const kinesisVideoClient = new KinesisVideoClient({region: "REGION", })

const getSignallingChannelEndpointResponse = await kinesisVideoClient.send(new GetSignalingChannelEndpointCommand({
  ChannelARN,
  SingleMasterChannelEndpointConfiguration: {
    Protocols: ['WSS', 'HTTPS'],
    Role: 'VIEWER'
  }
}))
```

### SDK version used

3

### Environment details (OS name and version, etc.)

Ubuntu 20.04

**Comment by RanVaknin** [comment]
Hi @danemauland ,
There is no default credential provider for browser. You have to explicitly tell the SDK how you want credentials to be configured when calling the SDK from a browser environment.

In your case I'd suggest you use `fromCognitoIdentityPool()` method from `@aws-sdk/credential-providers` to get temporary credentials that call your desired Kinesis command. Here is [an example](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/loading-browser-credentials-cognito.html) to help you with that.
 
I hope this answers your question. Thanks.
