### ISSUE TITLE
Cannot find name 'ReadableStream'.

### ISSUE THREAD

**Issue by chrisguttandin** [aws/aws-sdk-js-v3#3807]
### Describe the bug

Since version 3.127.0 the `client-dynamodb` package can't be used anymore without including the `'DOM'` lib in the tsconfig. TypeScript complains:

```txt
node_modules/@aws-sdk/types/dist-types/serde.d.ts:58:33 - error TS2304: Cannot find name 'ReadableStream'.
```

I guess the change was introduced here: https://github.com/aws/aws-sdk-js-v3/commit/f311cab406a16274dc2487dfe55c36b45a5811f5

### Expected Behavior

I would expect the SDK to be usable with the type definitions for Node.js only. Adding the `'DOM'` lib in the tsconfig fixes the issue but it also makes TypeScript believe it has access to all the DOM APIs which is not the case at runtime. Therefore it's not really an option.

### Current Behavior

The code doesn't compile.

### Reproduction Steps

Create a project which uses `@aws-sdk/client-dynamodb@3.127.0` or above.

### Possible Solution

I would suggest to only use the `ReadableStream` when it is defined on the global scope. This should work in the browser and also outside. It will return `never` instead of the expected type which exactly matches the runtime behavior.

This could be a fix:

```ts
type OptionalReadableStream = typeof globalThis extends { ReadableStream: infer GlobalReadableStream } ? GlobalReadableStream : never;
/**
 * The interface contains mix-in utility functions to transfer the runtime-specific
 * stream implementation to specified format. Each stream can ONLY be transformed
 * once.
 */
export interface SdkStreamMixin {
    transformToByteArray: () => Promise<Uint8Array>;
    transformToString: (encoding?: string) => Promise<string>;
    transformToWebStream: () => OptionalReadableStream;
}
```

The `OptionalReadableStream` gets assigned to the global `ReadableStream` definition in case there is one. If there is none it becomes `never`.

### Additional Information/Context

Please let me know if I should provide a PR with the proposed fix from above. I would be happy to do so.

### SDK version used

3.127.0

### Environment details (OS name and version, etc.)

typescript@4.7.4

**Comment by stocks29** [comment]
This is also true of `cognito-client-identity-provider`

**Comment by chrisguttandin** [comment]
@barryhagan I think it would be a bit better to add a `.d.ts` file to a Node.js-only project which sets `ReadableStream` to `never` to prevent any unintended usage.

```ts
type ReadableStream = 'never';
```

**Comment by chrisguttandin** [comment]
@barryhagan That makes sense. I wasn't aware that so many packages do this.

But I think the fix that I proposed above (to define a custom `OptionalReadableStream` based on the availability of a global `ReadableStream`) should still work in those scenarios.

**Comment by ClaudenirFreitas** [comment]
Same incident with `aws-xray-sdk-core`... 

```
<repo>/node_modules/aws-xray-sdk-core/node_modules/@aws-sdk/types/dist-types/ts3.4/serde.d.ts:34:33 - error TS2304: Cannot find name 'ReadableStream'.
34     transformToWebStream: () => ReadableStream;
                                   ~~~~~~~~~~~~~~
Found 1 error.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by davekiss** [comment]
Also hitting this issue with `@aws-sdk/client-personalize-runtime`

```
lib/recommend-lambda/node_modules/@aws-sdk/client-personalize-runtime/node_modules/@aws-sdk/types/dist-types/ts3.4/serde.d.ts:34:33 - error TS2304: Cannot find name 'ReadableStream'.

34     transformToWebStream: () => ReadableStream;
                                   ~~~~~~~~~~~~~~


Found 1 error.
```
