### ISSUE TITLE
Share bundle size badges through bundlephobia

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#381]
**Is your feature request related to a problem? Please describe.**
* We currently show downloads for our packages https://github.com/aws/aws-sdk-js-v3/tree/master/clients/node/client-s3-node
* It would be helpful if we can view bundle sizes too https://badgen.net/#bundlephobia

**Describe the solution you'd like**
* Show badges with bundle sizes from bundlephobia
* bundlephobia is backed by chrome performance fund https://github.com/pastelsky/bundlephobia/issues/179#issuecomment-514259340

**Describe alternatives you've considered**
Viewing bundlesize by explicitly visiting bundlephobia website, and sharing package name

**Comment by trivikr** [comment]
bundlephobia shows missing dependency error when Node.js specific dependencies are used, like `console`, `file`, `process`, `v8`, `worker_threads` etc
* Example with jest https://github.com/pastelsky/bundlephobia/issues/222

This applies to some AWS JS SDK v3 packages like [client-s3-node](https://bundlephobia.com/result?p=@aws-sdk/client-s3-node@0.1.0-preview.4)
https://github.com/aws/aws-sdk-js-v3/blob/1fd0fab5da141d934eb98624d6c23b347806bb47/clients/node/client-s3-node/test/smoke/index.spec.ts#L5

**Comment by trivikr** [comment]
FYI: bundlephobia is now showing info for beta versions
* [@aws-sdk/client-dynamodb@1.0.0-beta.1](https://bundlephobia.com/result?p=@aws-sdk/client-dynamodb@1.0.0-beta.1)
* [@aws-sdk/signature-v4@1.0.0-beta.1](https://bundlephobia.com/result?p=@aws-sdk/signature-v4@1.0.0-beta.1)

**Comment by RanVaknin** [comment]
Closing because Bundlephobia not actively maintained.
