### ISSUE TITLE
@aws-sdk/client-s3 - endpoint doesn't work for signed URL

### ISSUE THREAD

**Issue by dmarczydlo** [aws/aws-sdk-js-v3#3811]
### Describe the bug

The constructor parameter endpoint doesn't work as expected. Looks like this param is skipped for some reason.

### Expected Behavior

The `endpoint` will be usable - the CDN will be able to configure for s3 instead of s3 URI 

### Current Behavior

The endpoint is not usable. Doesn't matter that `endpoint` is added to the s3 client configuration - aways the URL based on S3 URI

### Reproduction Steps

```javascript
const AWS = require("@aws-sdk/client-s3");
const s3request = require("@aws-sdk/s3-request-presigner");

const test = async () => {
  const client = new AWS.S3Client({
    endpoint: {
      hostname: "xxx",
      protocol: "http",
      path: "/",
    },
    bucketEndpoint: false,
    region: "xxx",
    credentials: {
      accessKeyId: "xxx",
      secretAccessKey: "xxx",
    },
  });
  const myKey = "xxx";
  const myBucket = "ixxx";
  const bucketParams = {
    Key: myKey,
    Bucket: myBucket,
  };

  const signedUrlExpireSeconds = 60 * 60;

  const command = new AWS.PutObjectCommand(bucketParams);
  const signedUrl = await s3request.getSignedUrl(client, command, {
    expiresIn: signedUrlExpireSeconds,
  });

  console.log(signedUrl);
};
test();

```

### Additional Information/Context

When the `endpoint` is defined (as string or Object - doesn't matter) the normal S3 URI is returning instead of CDN domain.

### SDK version used

3.131.0

### Environment details (OS name and version, etc.)

MacOS

**Comment by yenfryherrerafeliz** [comment]
Hi @dmarczydlo, thanks for opening this issue. I was trying to reproduce the reported behavior but by using the code below I was able to use custom endpoint. 
Please see:
```js
import {PutObjectCommand, S3Client} from "@aws-sdk/client-s3";
import {getSignedUrl} from "@aws-sdk/s3-request-presigner";

const s3Client = new S3Client({
    region: 'us-east-2',
    endpoint: {
        hostname: 'default-hostname.amazon.com',
        protocol: 'http',
        path: '/',
    },
    bucketEndpoint: false,
});
const mKey = 'MY-KEY';
const mBucket = 'MY-BUCKET';
const mParams = {
    Bucket: mBucket,
    Key: mKey
};
const signedUlrExpiredSeconds = 60 * 60;
const putObjectCommand = new PutObjectCommand(mParams);
const signedUrl = await getSignedUrl(s3Client, putObjectCommand, {
    expiresIn: signedUlrExpiredSeconds
});

console.log(signedUrl);
```
Output:
```console
http://MY-BUCKET.default-hostname.amazon.com/MY-KEY?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=xxxx%2F20220721%2FREGION%2Fs3%2Faws4_request&X-Amz-Date=20220721T173422Z&X-Amz-Expires=3600&X-Amz-Signature=ecc53e580b1a1547e41804ae296aa9170814de48282134101ca0107516139748&X-Amz-SignedHeaders=host&x-id=PutObject
```

Please let me know if I am omitting any details here.

Thanks!

**Comment by dmarczydlo** [comment]
but @yenfryherrerafeliz you have bucket URL instead of CDN.

**Comment by yenfryherrerafeliz** [comment]
@dmarczydlo sorry for the delayed response. You should be able to use a custom s3 endpoint by setting bucketEndpoint to true and providing the url as the bucket parameter. 

Example below:
```js
import {GetObjectCommand, S3Client} from "@aws-sdk/client-s3";
import {getSignedUrl} from "@aws-sdk/s3-request-presigner";

const s3Client = new S3Client({
    region: 'us-east-2',
    bucketEndpoint: true
});
const mParams = {
    Bucket: 'cloudfrontid.cloudfront.net',
    Key: 'FILE.txt'
};
const getObjectCommand = new GetObjectCommand(mParams);
const signedUrl = await getSignedUrl(s3Client, getObjectCommand, {
    expiresIn: 3600
});

console.log(signedUrl);
```
See output:
```console
https://cloudfrontid.cloudfront.net/FILE.txt?...
```

Please let me know if this unblock you.

Thanks!

**Comment by CN91** [comment]
IS there any ?! documentation on where /how I can use. bucketEndPoint in the latest version? I can't seem to find a. single example of it and according to my package the 'bucketEndpoint' config doesn't even exist anymore.
