### ISSUE TITLE
Lambda Invoke Internal Failed at Parsing Payload

### ISSUE THREAD

**Issue by gpablo6** [aws/aws-sdk-js-v3#3820]
### Describe the bug

I've try using node v16.12.0 and v18.1.0 with the @aws-sdk/client-lambda:3.100.0 and 3.131.0 to do a simple function invocation with its corresponding `invoke` method. For execution I'm using typescript:4.7.4 and ts-node 10.9.1

When I tested on the console I got the desired result. And the credentials I'm using are from the same account. I've successfully reproduce the results using aws-cli on Ubuntu too.

### Expected Behavior

I'm expecting to get some similar results as those from the interface test case that are kind like the following:

`{"c":true,"b":"HERE GOES A BLOB OF TEXT...","origin":"sls-agent"}`

Or at least just get some other error response from the function invocation.

### Current Behavior

I'm getting the following error: 

`SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /home/gpablo/Ayllu/ayllu-cardano-endpoints/node_modules/@aws-sdk/client-lambda/dist-cjs/protocols/Aws_restJson1.js:8230:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async deserializeAws_restJson1InvokeCommandError (/home/gpablo/Ayllu/ayllu-cardano-endpoints/node_modules/@aws-sdk/client-lambda/dist-cjs/protocols/Aws_restJson1.js:4423:15)
    at async /home/gpablo/Ayllu/ayllu-cardano-endpoints/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /home/gpablo/Ayllu/ayllu-cardano-endpoints/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
    at async StandardRetryStrategy.retry (/home/gpablo/Ayllu/ayllu-cardano-endpoints/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /home/gpablo/Ayllu/ayllu-cardano-endpoints/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22 {
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}`

At just this point in the code:

`const output = await clientHandler.invoke(params);`

I'm not able to move from here...

### Reproduction Steps

The function to create the client is the following one:

` function createClient(awsCredentials: any, lambdaRegion: string, lambdaEndpoint:string) { 
       return new Lambda({ 
               credentials: <CredentialProvider>awsCrendentials, 
               region: lambdaRegion,
                endpoint: lambdaEndpoint    
            });
}
`

Then I passed down the following <InvokeCommandInput>: 

`{
    FunctionName: "ayllu-api-test-v2-dev-getUserById",
    InvocationType: "RequestResponse",
    LogType: "Tail",
    Payload: data
}`

At first I thought the `data` was the issue. The raw input is the following one: `'{"queryStringParameters": {"user_id": 1}}'`
I've already try many forms to passed it down and I'm almost 100% sure that this is not the issue. Including the following parsings for `Payload` parameter :

- `Payload: fromUtf8(JSON.stringify(payload))`
- `Payload: `'${payload}'`
- `Payload: fromUtf8('{"queryStringParameters": {"user_id": 1}}')`
- `Payload: '{"queryStringParameters": {"user_id": 1}}'`

And many more. 
When I log to console just before invocation everything seems ok with the following result:

`{
  FunctionName: 'getUserById',
  InvocationType: 'RequestResponse',
  LogType: 'Tail',
  Payload: '{"queryStringParameters": {"user_id": 1}}'
}
`

### Possible Solution

I was thinking that maybe passing it down as base64 would be better, as in the cli I was also in needed to do that for it to work. But I've not seen anyone doing it that way when exemplifying the SDK.

### SDK version used

3.131.0

### Environment details (OS name and version, etc.)

Ubuntu 20.04.4 LTS

**Comment by yenfryherrerafeliz** [comment]
Hi @gpablo6, thanks for opening this issue. I tried to reproduce the reported inconvenient but I was not able to. According with the error there is a "<" symbol that is causing the JSON conversion to fail. This error could be either or sending the request or receiving the response. So, could you please try the following:
- Try invoking the function that does return something simple, like '{"key":"Value"}', and if it works, then the issue may be in the response returned by invoking the function. 
Please see my reproduction details:
- SDK versions: 3.100 and 3.131
- Code:
```js
import {Lambda} from "@aws-sdk/client-lambda";

const lambda = new Lambda({
    region: 'REGION',
});
const textEncoder = new TextEncoder();
const payload = '{"queryStringParameters": {"user_id": 1}}';
const params = {
    FunctionName: "FUNCTION-NAME",
    InvocationType: "RequestResponse",
    LogType: "Tail",
    Payload: payload,
};
const response = await lambda.invoke(params);

console.log('Response: ', response);
```
Response:
```console
Response:  {
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'REQUEST-ID',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  ExecutedVersion: '$LATEST',
  FunctionError: undefined,
  LogResult: 'LogResult',
  Payload: Uint8Array(50) [
    bytes...
  ],
  StatusCode: 200
}
```

Thanks!
