### ISSUE TITLE
SSO Admin Conflict exception defined as non-retryable error

### ISSUE THREAD

**Issue by leelalagudu** [aws/aws-sdk-js-v3#3822]
### Describe the bug

- When trying to [assign customer managed policy reference to permission set](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-sso-admin/classes/attachcustomermanagedpolicyreferencetopermissionsetcommand.html) in quick succession, there's a possibility to hit [conflict exception](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-sso-admin/classes/conflictexception.html) as the state would not have been propagated
- However, the SDK's smithy trait defines this [as a non-transient error i.e. http code 409](https://github.com/aws/aws-sdk-js-v3/blob/main/codegen/sdk-codegen/aws-models/sso-admin.json#L433) causing the calling code to immediately throw the exception.
- Per the SDK's docs for conflict exception, the recommended response for this is to retry, and with a 409 the SDK would not retry.

### Expected Behavior

- SDK should automatically retry on getting a "Conflict exception" making this a transient error in the model

### Current Behavior

- SDK does not retry on getting "Conflict exception" 

### Reproduction Steps

- Try processing about 10 customer managed policies attachment to the same permission set in a map wrapped in a try and catch and with the SSO admin client having "maxRetries" set to 2. 
- Instead of the client retrying, you would hit the exception block on the first instance. 

### Possible Solution

- Make conflict exception a transient error , marking it retryable

### SDK version used

3.131.0

### Environment details (OS name and version, etc.)

Node 16_X Lambda standard runtime

**Comment by ajredniwja** [comment]
@leelalagudu thanks for opening this issue, can you please share the code you are using with all the package information if possible.

**Comment by leelalagudu** [comment]
Hi @ajredniwja , here is the sampe code that would trigger this conflict exception. Ensure that customerManagedPoliciesList is an array of type [customerManagedPolicyReference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-sso-admin/interfaces/customermanagedpolicyreference.html). 

This is reproducible with `aws-sso-admin-client` package version 3.132.0.

Please let me know if you need any other information. 

`  await Promise.all(
            customerManagedPoliciesList.map(
              async (customerManagedPolicyArn: string) => {
                await ssoAdminClientObject.send(
                  new AttachManagedPolicyToPermissionSetCommand({
                    InstanceArn: instanceArn,
                    PermissionSetArn:
                      "somePermissionSetArn",
                    ManagedPolicyArn: customerManagedPolicyArn,
                  })
                );              
              }
            )
          );`

**Comment by leelalagudu** [comment]
Hi @ajredniwja , do you need any other details from me around the issue reproduction your end?

**Comment by ajredniwja** [comment]
Hey @leelalagudu thanks for providing more info, I was looking for minimal repro code to run, I'll try to work and use similar attributes and see if Im able to reproduce

**Comment by leelalagudu** [comment]
@ajredniwja , that is the minimal reproducible code. Ensure the `customerManagedPoliciesList` array has more about 10 elements , given that the API does not validate if these policies exist at the permission set creation, you could just use dummy values for name and path like 
```typescript
const customerManagedPoliciesList = [
{
Name: "cmp-1"
},
{
Name: "cmp-1"
},
{
Name: "cmp-1"
},
{
Name: "cmp-1"
},
{
Name: "cmp-1"
},
{
Name: "cmp-1"
},
{
Name: "cmp-1"
},
{
Name: "cmp-1"
},
{
Name: "cmp-1"
},
{
Name: "cmp-1"
},
{
Name: "cmp-1"
},
]
```

**Comment by leelalagudu** [comment]
@ajredniwja , following up on this - do you still need any other details from my end for reproducing the issue?

**Comment by allquixotic** [comment]
For context, the feature in aws-sso-extensions-for-enterprise that depends on this is very much needed by my organization (customer-managed policies). This is the highest priority AWS issue I'm tracking at the moment.

**Comment by ajredniwja** [comment]
Hey again, 

> @ajredniwja , that is the minimal reproducible code. I am not sure what additional details you're looking for. If it helps, here's some additional context around the test data.
> 
> This should throw the `ConflictException` error. To validate the retry behaviour , set `maxRetries: 2` or another number greater than 1, and you will notice that the SDK does not retry on getting a `ConflictException` due to the error code being 409

`maxRetries` is not a part of V3 see https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md 
https://github.com/aws/aws-sdk-js-v3/pull/1244

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-sso-admin/classes/conflictexception.html#_retryable mentions to retry using appropriate backoff logic.

Standard retry strategy: https://github.com/aws/aws-sdk-js-v3/blob/main/packages/middleware-retry/src/StandardRetryStrategy.ts

Was able to to confirm that the Go sdk follows similar modeling.

**Comment by RanVaknin** [comment]
Hi @leelalagudu,

>Per the SDK's docs for conflict exception, the recommended response for this is to retry, and with a 409 the SDK would not retry.

Can you tell me where did you read this?

I read our internal spec for retries and 409 is neither listed as a retryable errors nor mentioned there under transient errors. 

In addition, each SDK client is auto-generated from the API model of the respective AWS service that interacts with it. 
That smithy trait you brought up is defined by the service team and we dont have control over that.

I think the best solution is for you to implement your own retryer logic forcing retries on 409s. This is a fairly straightforward implementation with lots of examples here on the repo and in our docs.

Let me know if you have any other thoughts.
Thanks,
Ran~
