### ISSUE TITLE
[lex-v2-client] Second RecognizeText request fails

### ISSUE THREAD

**Issue by ArielMannes** [aws/aws-sdk-js-v3#3836]
### Describe the bug

I initialize a client, then post RecognizeText. First command succeds.

Then I post another RecognizeText for the same client, and it aborts with exit code 13 (Promise was never resolved).

### Expected Behavior

It should post the command and at the very least reject the promise.

### Current Behavior

The promise is never fulfilled nor rejected.

### Reproduction Steps

```javascript
import { LexRuntimeV2Client, RecognizeTextCommand } from '@aws-sdk/client-lex-runtime-v2';
import * as crypto from 'crypto';

const botDetails = {
  region: 'us-west-2',
  accessKey: '<my-access-key>',
  secretKey: '<my-secret-key>',
  BotName: '<bot-name>',
  botId: '<bot-id>',
  botAliasId: '<bot-alias-id>',
  sessionId: `my-session-${crypto.randomBytes(32).toString('hex')}`
}

const txtCmdInput = {
  botId: botDetails.botId,
  botAliasId: botDetails.botAliasId,
  localeId: 'en_US',
  sessionId: botDetails.sessionId,
};

const sendTextCommand = async (message) => {
  txtCmdInput.text = message;
  try {
    const ans = await lexV2Client.send(new RecognizeTextCommand(txtCmdInput));
    console.log(`got txt answer:\n${JSON.stringify(ans)}`);
  } catch (error) {
    console.error(`got an error :${error.message}`);
    throw error;
  }
};

const conversation = async () => {
  try {
    await sendTextCommand('i want a bouquet');
    await sendTextCommand('roses');
    await sendTextCommand('sunday');
    await sendTextCommand('noon');
    await sendTextCommand('yes');
  } catch (error) {
    console.error(error);
  }
};

const lexV2Client = new LexRuntimeV2Client({
  credentials: {
    accessKeyId: botDetails.accessKey,
    secretAccessKey: botDetails.secretKey,
  },
  region: botDetails.region
});

await conversation();
```

### SDK version used

3.137.0

### Environment details (OS name and version, etc.)

Windows 10, Node 16.16

**Comment by ArielMannes** [comment]
I also tried using the runtime without any difference:
import { LexRuntimeV2 } from '@aws-sdk/client-lex-runtime-v2';
import * as crypto from 'crypto';

const botDetails = {
  region: 'us-west-2',
  accessKey: '<my-access-key>',
  secretKey: '<my-secret-key>',
  BotName: '<bot-name>',
  botId: '<bot-id>',
  botAliasId: '<bot-alias-id>',
  sessionId: `my-session-${crypto.randomBytes(32).toString('hex')}`
}

const txtCmdInput = {
  botId: botDetails.botId,
  botAliasId: botDetails.botAliasId,
  localeId: 'en_US',
  sessionId: botDetails.sessionId,
};

const sendTextRuntime = async (message) =>{
  try {
  txtCmdInput.text = message;
    const ans = await lexV2Runtime.recognizeText(txtCmdInput);
    console.log(`got txt answer:\n${JSON.stringify(ans)}`)
  } catch (error) {
    console.error(`got an error :${error.message}`);
    throw error;
  }
};

const conversation = async () => {
  try {
    await sendTextRuntime('i want a bouquet');
    await sendTextRuntime('roses');
    await sendTextRuntime('sunday');
    await sendTextRuntime('noon');
    await sendTextRuntime('yes');
  } catch (error) {
    console.error(error);
  }
};

const lexV2Runtime = new LexRuntimeV2({
  credentials: {
    accessKeyId: botDetails.accessKey,
    secretAccessKey: botDetails.secretKey,
  },
  region: botDetails.region
});

await conversation();

cc: @orgads

**Comment by jesukaransachin** [comment]
@ArielMannes I am getting a similar error the second time when calling RecognizeTextCommand. Were you able to resolve?

Error [ERR_HTTP2_STREAM_ERROR]: Stream closed with error code NGHTTP2_REFUSED_STREAM
    at new NodeError (d:\Chatbot\chatbot\lib\internal\errors.js:372:5)
    at ClientHttp2Stream._destroy (d:\Chatbot\chatbot\lib\internal\http2\core.js:2332:13)
    at _destroy (d:\Chatbot\chatbot\lib\internal\streams\destroy.js:102:25)
    at ClientHttp2Stream.destroy (d:\Chatbot\chatbot\lib\internal\streams\destroy.js:64:5)
    at Http2Stream.onStreamClose (d:\Chatbot\chatbot\lib\internal\http2\core.js:544:12)
    at Http2Stream.callbackTrampoline (node:internal/async_hooks:130:17) {code: 'ERR_HTTP2_STREAM_ERROR', $metadata: {…}, stack: 'Error [ERR_HTTP2_STREAM_ERROR]: Stream closed…Trampoline (node:internal/async_hooks:130:17)', message: 'Stream closed with error code NGHTTP2_REFUSED_STREAM', toString: ƒ, …} Error [ERR_HTTP2_STREAM_ERROR]: Stream closed with error code NGHTTP2_REFUSED_STREAM
    at new NodeError (d:\Chatbot\chatbot\lib\internal\errors.js:372:5)
    at ClientHttp2Stream._destroy (d:\Chatbot\chatbot\lib\internal\http2\core.js:2332:13)
    at _destroy (d:\Chatbot\chatbot\lib\internal\streams\destroy.js:102:25)
    at ClientHttp2Stream.destroy (d:\Chatbot\chatbot\lib\internal\streams\destroy.js:64:5)
    at Http2Stream.onStreamClose (d:\Chatbot\chatbot\lib\internal\http2\core.js:544:12)
    at Http2Stream.callbackTrampoline (d:\Chatbot\chatbot\lib\internal\async_hooks.js:130:17)

**Comment by ArielMannes** [comment]
@jesukaransachin  It seems that you have HTTP 2 error. are you behind a proxy or a firewall that does not support http2?

**Comment by ArielMannes** [comment]
I added a timeOut between calls and it solved the issue - 
```javascript
import { setTimeout } from 'timers/promises';
const conversation = async () => {
  try {
    await sendTextCommand('i want a bouquet');
    await setTimeout(5, 'result');
    await sendTextCommand('roses');
    await setTimeout(5, 'result');
    await sendTextCommand('sunday');
    await setTimeout(5, 'result');
    await sendTextCommand('noon');
    await setTimeout(5, 'result');
    await sendTextCommand('yes');
  } catch (error) {
    console.error(error);
  }
};

```
