### ISSUE TITLE
client-kms: No matching version found for @aws-sdk/client-sts@3.142.0

### ISSUE THREAD

**Issue by jucelinux** [aws/aws-sdk-js-v3#3840]
### Describe the bug

ETARGET
No matching version found for @aws-sdk/client-sts@3.142.0

### Expected Behavior

Install package

### Current Behavior

```
npm i @aws-sdk/client-kms
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @aws-sdk/client-sts@3.142.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@aws-sdk/client-kms'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jucelino/.npm/_logs/2022-08-02T21_11_02_599Z-debug.log

```

### Reproduction Steps

`npm i @aws-sdk/client-kms
`

### SDK version used

3.142.0

### Environment details (OS name and version, etc.)

Ubuntu 22, node v12.22.7, npm 6.14.15

**Comment by RanVaknin** [comment]
@jucelinux 

Im not sure why you are seeing this error.  I have no issues running ```npm i @aws-sdk/client-kms```.


Try updating to a newer version of npm:

```
npm install -g npm@latest
```

**Comment by jucelinux** [comment]
thanks for the help @RanVaknin

I will test your suggestion and investigate if this is a problem in my environment.
