### ISSUE TITLE
Missing documentation for Route53 Change object

### ISSUE THREAD

**Issue by m-dressler** [aws/aws-sdk-js-v3#3848]
### Describe the issue

The documentation does not - or at least no accessibly - document what a Change in the ChangeResourceRecordSetsCommand is expected to be structured like.

### Links

https://github.com/aws/aws-sdk-js-v3/blob/a38fd62688/clients/client-route-53/src/models/models_0.ts#L1929

**Comment by ajredniwja** [comment]
https://docs.aws.amazon.com/Route53/latest/APIReference/API_ChangeBatch.html
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-route-53/interfaces/changebatch.html

I think above mentioned docs is what you are looking for,.

**Comment by m-dressler** [comment]
Naturally this perfectly describes the ChangeBatch object (actually came from there), yet the inner Change object is undocumented. 
I found the object structure somewhere else, but though it might be helpful to have the ts definition in the directly in the SDK!

**Comment by johnelkins** [comment]
> Naturally this perfectly describes the ChangeBatch object (actually came from there), yet the inner Change object is undocumented. I found the object structure somewhere else, but though it might be helpful to have the ts definition in the directly in the SDK!

Were you initially having weird "TypeError: Cannot read properties of undefined (reading 'Changes')" by chance?

I am at my wits end at this point trying to create a new alias.

I didn't think I would have this many problems going from cjs to mjs... starting to regret that decision.

**Comment by m-dressler** [comment]
I mean it's related - while I didn't face that problem not using TypeScript, since those types are not defined as I am pointing out in this issue, TS might give you a hard time.

**Comment by RanVaknin** [comment]
Hi @m-dressler ,

Not sure why it was hard to find, maybe our documentation wasn't working at the time?

At any rate, [`Change`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-route-53/interfaces/change.html) will be an object with [`Action`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-route-53/interfaces/change.html#action-1) field and [`ResourceRecordSet`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-route-53/interfaces/change.html#resourcerecordset-1) field.

Thanks,
Ran~
