### ISSUE TITLE
Support S3 Client Side Encryption

### ISSUE THREAD

**Issue by jaschaio** [aws/aws-sdk-js-v3#3857]
### Describe the feature

I am having a very hard time trying to decrypt a KMS Client Side encrypted S3 File.

In PHP I can just use the `S3EncryptionClientV2`. Unfortunately it's [not supported by the JavaScript SDK](https://docs.aws.amazon.com/general/latest/gr/aws_sdk_cryptography.html).

Any particular reason why?

### Use Case

I want to decrypt AWS SES messages stored in S3 using Node.js

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

v3.149.0

### Environment details (OS name and version, etc.)

OSX

**Comment by yenfryherrerafeliz** [comment]
Hi @jaschaio, thanks for opening this feature request. We do not have any information about when this will be implemented for JS SDK, nonetheless I will use this thread to provide updates regarding, as soon as we get more details.

Thanks!

**Comment by danstucky** [comment]
@yenfryherrerafeliz It's been a year. It seems like the AWS team just forgot to implement this portion of the sdk for Node? As far as I can tell it exists for all the others. Do you know if it will _ever_ be supported?

**Comment by hfuss** [comment]
https://www.npmjs.com/package/@aws-crypto/client-node

Are folks to use this library in the meantime to manually manage the client-side encryption / decryption of the objects from S3? Is that even possible? This is a very large gap in the NodeJS support for AWS S3 as its supported in all other popular languages.

**Comment by kellertk** [comment]
Hi! The S3 encryption client you're referring to in PHP is not actually S3-specific. When you encrypt on the client side before sending your data to S3, you're free to use any encryption method you'd like. Some SDK languages, like PHP, Java, and Go, implement a client-side library that includes preconfigured encryption best practices to make client-side encryption with S3 easier. In our internal terminology, we refer to self-contained client-side functionality as a _high level library_, or HLL for short.

In the JavaScript SDK, examples of HLLs are the `lib-storage` S3 client, and the `lib-dynamodb` DynamoDB client. In JavaScript we did not implement a client-side encryption client, and we have no plans to do so at this time. One solution that we recommend is to use the @aws-crypto/client-node package linked earlier. This is part of the [AWS Encryption SDK for JavaScript](https://github.com/aws/aws-encryption-sdk-javascript) and should have all the functionality you need to implement client-side encryption and decryption.
