### ISSUE TITLE
Can't compile lib-storage on Vite 3

### ISSUE THREAD

**Issue by alexdemers** [aws/aws-sdk-js-v3#3867]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I can't build my basic project with Vite, TypeScript, React and `@aws-sdk/lib-storage@3.150.0`.

I created a basic vite project, added `@aws-sdk/lib-storage` and `@aws-sdk/client-s3`.

Added the code:
```
const uploader = new Upload({
  client: new S3({}),
  params: {
    Bucket: "test",
    Key: "test",
  },
});
```

... and that's it. So a basic Vite project with TypeScript and React and the above code.

I followed everything in https://ui.docs.amplify.aws/react/getting-started/troubleshooting#vite as quite a few posts were referring to these modifications.

### SDK version number

@aws-sdk/client-s3@^3.150.0

### Which JavaScript Runtime is this issue in?

Browser

### Details of the browser/Node.js/ReactNative version

Browsers: Chrome: 104.0.5112.101, Safari: 15.5

### Reproduction Steps

`git clone https://github.com/alexdemers/example-vite-aws`
`cd example-vite-aws`
`yarn`
`yarn vite build`

### Observed Behavior

```
'Readable' is not exported by __vite-browser-external, imported by node_modules/@aws-sdk/lib-storage/dist-es/chunker.js
file: /Users/.../example-vite-aws/node_modules/@aws-sdk/lib-storage/dist-es/chunker.js:2:9
1: import { Buffer } from "buffer";
2: import { Readable } from "stream";
            ^
3: import { getChunkBuffer } from "./chunks/getChunkBuffer";
4: import { getChunkStream } from "./chunks/getChunkStream";
error during build:
Error: 'Readable' is not exported by __vite-browser-external, imported by node_modules/@aws-sdk/lib-storage/dist-es/chunker.js
    at error (file:///Users/.../example-vite-aws/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at Module.error (file:///Users/.../example-vite-aws/node_modules/rollup/dist/es/shared/rollup.js:12412:16)
    at Module.traceVariable (file:///Users/.../example-vite-aws/node_modules/rollup/dist/es/shared/rollup.js:12771:29)
    at ModuleScope.findVariable (file:///Users/.../example-vite-aws/node_modules/rollup/dist/es/shared/rollup.js:11423:39)
    at FunctionScope.findVariable (file:///Users/.../example-vite-aws/node_modules/rollup/dist/es/shared/rollup.js:6355:38)
    at ChildScope.findVariable (file:///Users/.../example-vite-aws/node_modules/rollup/dist/es/shared/rollup.js:6355:38)
    at TrackingScope.findVariable (file:///Users/.../example-vite-aws/node_modules/rollup/dist/es/shared/rollup.js:6355:38)
    at Identifier.bind (file:///Users/.../example-vite-aws/node_modules/rollup/dist/es/shared/rollup.js:7422:40)
    at BinaryExpression.bind (file:///Users/.../example-vite-aws/node_modules/rollup/dist/es/shared/rollup.js:5252:23)
    at IfStatement.bind (file:///Users/.../example-vite-aws/node_modules/rollup/dist/es/shared/rollup.js:5252:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected Behavior

Expected to build on Vite in the browser.

**Comment by ajredniwja** [comment]
Hey there thanks for opening this issue, I have seen a few issues with Vite before caused when the conversion is done by vite CommonJS dependencies to ESM

Vite V3 uses V22 of @rollup/commonjs, which supports the configuration option [strictRequires](https://github.com/rollup/plugins/tree/master/packages/commonjs#strictrequires). Setting this option to true in the vite.config.ts  should fix the issue. 

Can also write your own plugin to get around it see https://github.com/aws/aws-sdk-js/issues/1769#issuecomment-1139826624

My vite.config.ts with successful build 

```
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import basicSsl from '@vitejs/plugin-basic-ssl'

// https://vitejs.dev/config/
export default defineConfig({
  build: {
    rollupOptions: {
      external: ["react"],
      output: {
        globals: {
          react: "React"
        }
      }
    },
    commonjsOptions: {
      include: [/node_modules/],
      extensions: [".js", ".cjs"],
      strictRequires: true,
    },
  },
  resolve: {
    alias: {
      crypto: 'crypto-browserify',
      stream: 'stream-browserify',
      process: 'process/browser'
    }
  },
  plugins: [react(), basicSsl()],
})
```

**Comment by alexdemers** [comment]
Thank you for your help @ajredniwja ! Yes, it does work now with my main project.
