### ISSUE TITLE
Add toll costs to the result of route calculation in clients/client-location

### ISSUE THREAD

**Issue by Nxtra** [aws/aws-sdk-js-v3#3881]
### Describe the feature

Add toll costs to the `CalculateRouteResponse` object which is the response of executing a calculate route command. ( [clients/client-location/src/models/models_0.ts](https://github.com/aws/aws-sdk-js-v3/blob/d47bdb1f31fca2a8d8deec77dfb53b3fb1996393/clients/client-location/src/models/models_0.ts) )

### Use Case

It's great that the location client allows for route calculation of vehicles different from cars, like trucks.
This differentiates the AWS location package from the Google alternatives.

However when calculating truck specific routes companies almost always want to know the toll costs among a route.
When no toll costs are present it's hard to know for companies whether or not to send a truck along a certain route because the cost of the ride is unclear.

### Proposed Solution

- Update `CalculateRouteResponse` object with TollCosts
- Add extra optional fields to `CalculateRouteRequest` (like emissionType) to allow for correct tollCost calculation.

https://github.com/aws/aws-sdk-js-v3/blob/d47bdb1f31fca2a8d8deec77dfb53b3fb1996393/clients/client-location/src/models/models_0.ts

In the case of the HERE provider this is the API to abstract from: https://developer.here.com/documentation/fleet-telematics/api-reference.html#operation%2FcalculateRouteUsingGET

### Other Information

I suspect that there will be some HERE vs Esri differences which will make a general abstraction over both of them harder to implement.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

2.1202.0

### Environment details (OS name and version, etc.)

any

**Comment by ajredniwja** [comment]
Hey @Nxtra thanks for opening this issue, I see you have mentioned V3 code in the description but mentioned V2 of the SDK was used however this will needed to be implemented by the `locations` team. I have opened a request with them. P72645358

**Comment by aBurmeseDev** [comment]
Hi there - sorry for the long wait. I just checked in with the service team and they had confirmed that TollCosts was added to `CalculateRouteResponse` which I was also able to confirm.

Let us know if you still encounter any issue, closing this now.
