### ISSUE TITLE
Add tail command to CloudWatch Logs Client

### ISSUE THREAD

**Issue by brianfoody** [aws/aws-sdk-js-v3#3891]
### Describe the feature

It looks like the tail command is unsupported by the SDK. It's an extremely convenient command I'd like to leverage through a dev tool I'm building but without the SDK call I'll have to write custom logic.

### Use Case

Building an AWS Developer tool which I want to include lambda function logging in so need an SDK command to invoke rather than CLI.

### Proposed Solution

```
const response = await logs.send(new TailCommand({
   logGroupName: "<GROUP>",
   lastToken: "<TOKEN>"
}))

const logs = result.Logs;
const token = result.Token;
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.44.0

### Environment details (OS name and version, etc.)

mac OS Monterey

**Comment by ajredniwja** [comment]
Hey @brianfoody thanks for opening this issue, this will needed to be implemented by the CloudWatch team. I will open a request with them and see if they have any plans for it.
