### ISSUE TITLE
totalRetryDelay observed is less than retryAfterSeconds

### ISSUE THREAD

**Issue by sivantcy** [aws/aws-sdk-js-v3#3894]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I'm using Smithy and the retryable trait with @httpHeader("Retry-After") and retryAfterSeconds. in the service I'm returning header with Retry-After = 2. I have ts client that generated directly thought Smithy. in the logs the value of totalRetryDelay is around 50. how does it possible that totalRetryDelay value is less than the value in Retry-After after 3 attempts?

### SDK version number

@aws-sdk/package-name@version, ...

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node.js 14

### Reproduction Steps

1. create a service that returns error and header with the header  Retry-After = "2"
2. create a smithy model with error that look like that: 
@error("server")
@retryable
@httpError(500)
structure InternalServerException {
    message: String,
    @httpHeader("Retry-After")
    retryAfterSeconds: Integer //To be retried by client after configured seconds.
}
3. generate ts client directly
4. throw this error from the service
5. check the logs that uses the generated ts client.
6. check that attempts are equal to 3 and the value in totalRetryDelay
 

### Observed Behavior

the attempts value was 3, but totalRetryDelay was around 5

### Expected Behavior

attempts=3 and totalRetryDelay around 4000

**Comment by trivikr** [comment]
During deep dive, we noticed that `retryAfterSeconds` value is populated in error, but it's not consumed by retry middleware.

Example model:
https://github.com/aws/aws-sdk-js-v3/blob/cdccc0d68505085288cfa1db8c6f3bea86035b53/codegen/sdk-codegen/aws-models/mobile.json#L702-L720

Example generated code:
https://github.com/aws/aws-sdk-js-v3/blob/51c24224fe8622d011775dd89c6255a7edd29470/clients/client-mobile/src/protocols/Aws_restJson1.ts#L830-L846

The `delayDecider` in retry should either value in `retryAfterSeconds` as min, or override the value as it's enforced by the service 
https://github.com/aws/aws-sdk-js-v3/blob/51c24224fe8622d011775dd89c6255a7edd29470/packages/middleware-retry/src/StandardRetryStrategy.ts#L98-L101

**Comment by trivikr** [comment]
The solution would be to read value in `Retry-After` from `error.$response`

It's done in some other places like auth middleware

https://github.com/aws/aws-sdk-js-v3/blob/1675f42e755321c4626c86cff53a96f6efe4683b/packages/middleware-signing/src/middleware.ts#L32

**Comment by sivantcy** [comment]
I already sent Retry-After in the header response and I see it affects the totalRetryDelay value. before sending Retry-After in the header response the totalRetryDelay was around 400, I guess it related to some default value

**Comment by sivantcy** [comment]
thanks for fixing it. from the CR, it look like the time between the retries is fixed without using the backoff strategy.  is there any reason not to use this as a base time for the backoff strategy?

**Comment by trivikr** [comment]
The fix ensures that when serve responds with specific value in retry after header, the value computed for retry is at least that value. Retry Strategy will use value returned by delay decider only if the value returned is greater than the wait time requested by the service.
