### ISSUE TITLE
client-cloudformation - Unable to remove Rollback Triggers

### ISSUE THREAD

**Issue by simi-obs** [aws/aws-sdk-js-v3#3896]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When creating/updating stack, you are able to add RollbackConfiguration.RollbackTriggers (alarms).

To remove the alarms from rollback configuration it is required that you provide empty array for RollbackTriggers (docs [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_RollbackConfiguration.html))

However the way [serialization works](https://github.com/aws/aws-sdk-js-v3/blob/40e752a45cfe52385f9ca12ba50f592655afe305/clients/client-cloudformation/src/protocols/Aws_query.ts#L5942) it seems, that the RollbackTriggers are not added to RollbackConfiguration when empty array is provided. Can this problem be somehow mitigated? I am open to opening a PR for fix, if you can point me where to fix this.

### SDK version number

@aws-sdk/client-cloudformation@3.137.0, ...

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

18.2

### Reproduction Steps

1. Add Rollback Trigger to your cloudformation stack.
2. Try to remove the Rollback Trigger.

### Observed Behavior

Rollback triggers were not removed

### Expected Behavior

Rollback triggers should be removed

### Possible Solution

There should be a change in how RollbackConfiguration is serialized.

I.e. in case RollbackTriggers array is provided (even if empty), serializator should add it to the request.

**Comment by kuhe** [comment]
I have made a prospective fix in the linked PR, however it is failing a protocol test. This means that the prescribed serialization behavior for this operation is at odds with the service implementation. I will have to consult internally to see how this will be reconciled. 

In the meantime, you can modify the request before it is sent out like this, or alternatively perhaps using middleware (not shown).

```js
const { CloudFormation, UpdateStackCommand } = require("@aws-sdk/client-cloudformation");

// ...

  const originalUpdateStackCommandSerializeFn = UpdateStackCommand.prototype.serialize;
  UpdateStackCommand.prototype.serialize = function (input, context) {
    return originalUpdateStackCommandSerializeFn
      .bind(this)(input, context)
      .then((request) => {
        const triggers = input?.RollbackConfiguration?.RollbackTriggers;
        if (Array.isArray(triggers) && triggers.length === 0) {
          request.body.replace("&RollbackConfiguration.RollbackTriggers=", "");
          request.body += "&RollbackConfiguration.RollbackTriggers=";
        }
        return request;
      });
  };
```

**Comment by kuhe** [comment]
I've gotten confirmation from the upstream teams that this can be corrected. The patch from #4003 will be in the next release.
