### ISSUE TITLE
S3 Select SelectObjectContentCommand SDK v3 is giving empty response.

### ISSUE THREAD

**Issue by anudeepchscitara** [aws/aws-sdk-js-v3#3902]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

S3 select object content is not giving response with the request params which are working for v2 of sdk.

### SDK version number

@aws-sdk/client-s3@3.95.0, @aws-sdk/client-s3@3.165.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.13.0

### Reproduction Steps

Use the below code to reproduce the issue, please make sure to provide proper values

```js
import { S3Client, SelectObjectContentCommand } from "@aws-sdk/client-s3";
const client = new S3Client({ credentials: { accessKeyId: "", secretAccessKey: "" } });
const command = new SelectObjectContentCommand({
    Bucket: "",
    Key: "",
    ExpressionType: "SQL",
    Expression: "SELECT * FROM s3object[*].results[*] r;",
    InputSerialization: {
        Type: "DOCUMENT",
    },
    OutputSerialization: {
        JSON: {
            RecordDelimiter: "\n",
        },
    },
});
const response = await client.send(command);
console.log('response ---------', response);
```

```json
output:
--------------------
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: undefined,
    extendedRequestId: 'ED8aU5mHi6NlciJxXyzY5t0NXYIlalmoF3eEUuYs2h2/ebYGXW6zdwEgdlwvq1FZDuUGNLcDCMc=',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Payload: {
    [Symbol(Symbol.asyncIterator)]: [AsyncGeneratorFunction: [Symbol.asyncIterator]]
  }
}
```

### Observed Behavior

getting empty response.

### Expected Behavior

should return stream

**Comment by anudeepchscitara** [comment]
hi @ajredniwja, please let me know if you are not able to reproduce the issue.

**Comment by ajredniwja** [comment]
Hey @anudeepchscitara thanks for opening this issue, I will take a look soon and try to reproduce it, would need to write minimal code, would be great if you can provide better code to run otherwise I'll just post what I come up with

**Comment by anudeepchscitara** [comment]
@ajredniwja I updated the code please use the proper values to reproduce the issue.

**Comment by anudeepchscitara** [comment]
@ajredniwja hope you able to reproduce and able make some progress, looking forward to close the issue.

**Comment by RanVaknin** [comment]
Hi @anudeepchscitara ,

```js
    InputSerialization: {
        Type: "DOCUMENT",
    },
```

This input is invalid. There is no `Type` field on [`InputSerialization` ](https://docs.aws.amazon.com/AmazonS3/latest/API/API_InputSerialization.html)
Instead you need to use `CompressionType`:

>**CompressionType**
>_Specifies object's compression format. Valid values: NONE, GZIP, BZIP2. Default Value: NONE._
>
>Type: String
>
>Valid Values: NONE | GZIP | BZIP2
>
>Required: No


Are you following some documentation for this code snippet? 

Thanks,
Ran~
