### ISSUE TITLE
ECONNRESET triggers retries; but the retry is not successful

### ISSUE THREAD

**Issue by ronak2121** [aws/aws-sdk-js-v3#3905]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

My Lambda makes calls out to S3 and periodically sees ECONNRESET errors. I'm seeing the SDK triggering its automated retries as per the previous issue here: https://github.com/aws/aws-sdk-js-v3/issues/1196 but I'm not seeing the retry actually succeed.

{"code":"ECONNRESET","name":"TimeoutError","$metadata":{"attempts":2,"totalRetryDelay":1}}'

I would have expected the second attempt would succeed as you try the request with a brand new socket.

### SDK version number

@aws-sdk/client-s3@3.121.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node JS 14.x

### Reproduction Steps
```js
import { S3 } from '@aws-sdk/client-s3';
import { Handler, Context, S3Event } from 'aws-lambda';

const s3 = new S3({})

export const handler: Handler = async (event: S3Event, context: Context) => {
  await s3.getObject({
    Bucket: event.Records[0].s3.bucket.name,
    Key: event.Records[0].s3.object.key,
  });
}
```
### Observed Behavior

{"code":"ECONNRESET","name":"TimeoutError","$metadata":{"attempts":2,"totalRetryDelay":1}}'

### Expected Behavior

Retry to succeed since it would open a new socket, establish a new connection and issue the request

**Comment by ajredniwja** [comment]
Hey @ronak2121 thanks for opening the issue, the error which gets retired is for NodeJS timeouts, this might not be related to the SDK, however I would need more information (specific use case with reproducible example) to verify in under what conditions the code errors out.
