### ISSUE TITLE
@aws-sdk/xhr-http-handler's TransformStream is not working in firefox browser

### ISSUE THREAD

**Issue by prashant-kumar-masand** [aws/aws-sdk-js-v3#3914]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When i am trying to upload file to S3 bucket using PutObjectCommand from "@aws-sdk/client-s3" i am getting an error in firefox browser as :- Uncaught ReferenceError: TransformStream is not defined

In file xhr-http-handler.ts of @aws-sdk/xhr-http-handler TransformStream is not working in firefox browser version 91

i am using the "@aws-sdk/xhr-http-handler": "^3.162.0", inside S3Client as a request handler to track file upload progress in a more efficient way.

### SDK version number

 "@aws-sdk/xhr-http-handler": "^3.162.0"

### Which JavaScript Runtime is this issue in?

Browser

### Details of the browser/Node.js/ReactNative version

Browsers:     Chrome: 105.0.5195.102     Firefox: 91.13.0 

### Reproduction Steps

import { S3Client, PutObjectCommand } from '@aws-sdk/client-s3';
import { XhrHttpHandler } from '@aws-sdk/xhr-http-handler';
import { CognitoIdentityClient } from '@aws-sdk/client-cognito-identity';
import { fromCognitoIdentityPool } from '@aws-sdk/credential-provider-cognito-identity';

const s3Client = new S3Client({
  region: region,
  credentials: fromCognitoIdentityPool({
    client: new CognitoIdentityClient({ region: region }),
    identityPoolId: cognitoPoolId,
  }),
  requestHandler: new XhrHttpHandler({}),
});

const bucketParams = {
         Bucket: bucketName,
         Key: filePath,
         Body: fileDetails,
      }
      
const data = await s3Client.send(new PutObjectCommand(bucketParams));

### Observed Behavior

error message in short :
Uncaught ReferenceError: TransformStream is not defined 

error file location :
[xhr-http-handler.ts:228](@aws-sdk/xhr-http-handler/src/xhr-http-handler.ts)

### Expected Behavior

when try to upload a file on S3 bucket on firefox browser older version using @aws-sdk/xhr-http-handler as a requestHandler for S3Client it should let it happen without error.

### Possible Solution

so the problem is no polyfill is used to support Web Streams API for older browsers 
needed to use https://github.com/MattiasBuelens/web-streams-polyfill in order to support Web Streams Api for older browsers

**Comment by ajredniwja** [comment]
Hey @prashant-kumar-masand thanks for opening this issue, the [api reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_xhr_http_handler.html) here mentions you will have to supply polyfills, for example for TextEncoder and TransformStream, for environments that do not implement them natively.

The recommended HttpHandler for browser-like environments is [@aws-sdk/fetch-http-handler](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_fetch_http_handler.html), which is the default.
