### ISSUE TITLE
S3 Multipart Upload Fails When ContentLength is Provided

### ISSUE THREAD

**Issue by mritterfigma** [aws/aws-sdk-js-v3#3915]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

S3 Multipart Uploads are not working in the V3 SDK. They are not working because completing the multi-part upload fails due to malformed XML:

```
MalformedXML: The XML you provided was not well-formed or did not validate against our published schema
at throwDefaultError (/src/upnode/node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
at deserializeAws_restXmlCompleteMultipartUploadCommandError (/src/upnode/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:3087:43)
```

This is an SDK bug that has been described before (https://github.com/aws/aws-sdk-js-v3/issues/1814, https://github.com/aws/aws-sdk-js-v3/issues/2445) and was allegedly fixed by https://github.com/aws/aws-sdk-js-v3/pull/2835. Unfortunately, I am finding that it still persists on `v3.165.0`, which contains the commit (https://github.com/aws/aws-sdk-js-v3/commit/7e634cfab78d0a82864f828c4c8c10c9d0cccc97).

Is there more action I can take to get this to work? It is blocking adoption of the V3 SDK for my team.

### SDK version number

@aws-sdk/lib-storage@3.165.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.15.1

### Reproduction Steps

To reproduce, try to use lib-storage's `Upload` with a file greater than 5MB. If the file is too small, it will not trigger multi-part upload.

```
import { S3Client } from '@aws-sdk/client-s3'
import { Upload } from '@aws-sdk/lib-storage'

upload = new Upload({
  client: new S3Client({}),
  params: const params = {
    Bucket: "xxxx",
    Key: "yyyy",
    Body: "zzzz",
  }
})
await upload.done()
```

### Observed Behavior

The upload hangs for a long time, then finally fails with the following error:

```
MalformedXML: The XML you provided was not well-formed or did not validate against our published schema
at throwDefaultError (/src/upnode/node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
at deserializeAws_restXmlCompleteMultipartUploadCommandError (/src/upnode/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:3087:43)
```

### Expected Behavior

Expected that the multipart upload succeeds.

### Possible Solution

It is not clear why the fix PR is not working. Perhaps it depends on another npm module that must be updated in order to get the desired behavior?

**Comment by JacopoBonta** [comment]
@mritterfigma can be related to [this one](https://github.com/aws/aws-sdk-js-v3/issues/2673#issuecomment-1276331098)?

**Comment by AJB99** [comment]
@ajredniwja Did you even read the original post? It clearly states that this bug only occurs when `ContentLength` is provided as a param to the `Upload` command.

I ran into this issue myself and just wasted two days trying to figure out what the issue was. Perhaps AWS might want to at least document this "feature". Or possibly grace us with a Dev Support Engineer that isn't so lazy that they don't even bother to read the issues before providing a "solution".

I can confirm @mritterfigma findings. When you remove the `ContentLength` param from the `new Upload` constructor then multipart uploads work as expected.

Can anyone from AWS please comment why this is, and what side effects removing the `ContentLength` param could trigger.

**Comment by andyslack** [comment]
Yes, I have the same issue, Upload works fine for smaller files (e.g. 1-2mb) but when I try to upload a 50mb file, I get the same `The XML you provided was not well-formed or did not validate against our published schema` error.

I am not passing `ContentLength` but I am still getting the error.

**Comment by DougReeder** [comment]
FWIW, I am also seeing this — if I use Upload for a stream longer than about 5.1MB, the stream will have all its bytes read, then Upload appears to hang for a number of minutes, then I get the unhelpful error message about XML.  Not sending the Content-Length appears to allow it to work.

It's disappointing that this hasn't been fixed after a year and a half — I'm looking at chucking your SDK in favor of calling the REST endpoints directly.

**Comment by usman-nst** [comment]
"I am facing the same issue"

**Comment by RanVaknin** [comment]
Hi everyone,

I'm sorry for the late response for this issue.

I have written my own repro code explicitly providing the `ContentLength` parameter in the upload and using a 100mb file to test with and I'm not seeing this issue.

```js
import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";
import { Upload } from "@aws-sdk/lib-storage";
import fs from "fs";
import path from "path";

const s3Client = new S3Client({ region: "us-east-1" });

async function uploadFile() {
  const filePath = "./testfile100mb"; 
  const fileStream = fs.createReadStream(filePath);
  const fileSize = fs.statSync(filePath).size;

  const upload = new Upload({
    client: s3Client,
    params: {
      Bucket: "testbucket-REDACTED",
      Key: path.basename(filePath),
      Body: fileStream,
      ContentLength: fileSize, 
    },
  });

  upload.on("httpUploadProgress", (progress) => {
    console.log(progress);
  });

  try {
    const result = await upload.done();
    console.log("Upload completed successfully:", result);
  } catch (error) {
    console.error("Upload failed:", error);
  }
}

uploadFile();
```

Results in:

```
{
  loaded: 5242880,
  total: 104857600,
  part: 2,
  Key: 'testfile100mb',
  Bucket: 'testbucket-REDACTED'
}
{
  loaded: 10485760,
  total: 104857600,
  part: 1,
  Key: 'testfile100mb',
  Bucket: 'testbucket-REDACTED'
}
{
  loaded: 15728640,
  total: 104857600,
  part: 3,
  Key: 'testfile100mb',
  Bucket: 'testbucket-REDACTED'
}
{
  loaded: 20971520,
  total: 104857600,
  part: 4,
  Key: 'testfile100mb',
  Bucket: 'testbucket-REDACTED'
}
{
  loaded: 26214400,
  total: 104857600,
  part: 6,
  Key: 'testfile100mb',
  Bucket: 'testbucket-REDACTED'
}
{
  loaded: 31457280,
  total: 104857600,
  part: 8,
  Key: 'testfile100mb',
  Bucket: 'testbucket-REDACTED'
}
{
  loaded: 36700160,
  total: 104857600,
  part: 5,
  Key: 'testfile100mb',
  Bucket: 'testbucket-REDACTED'
}
{
  loaded: 41943040,
  total: 104857600,
  part: 7,
  Key: 'testfile100mb',
  Bucket: 'testbucket-REDACTED'
}
{
  loaded: 47185920,
  total: 104857600,
  part: 9,
  Key: 'testfile100mb',
  Bucket: 'testbucket-REDACTED'
}
{
  loaded: 52428800,
  total: 104857600,
  part: 10,
  Key: 'testfile100mb',
  Bucket: 'testbucket-REDACTED'
}
{
  loaded: 57671680,
  total: 104857600,
  part: 13,
  Key: 'testfile100mb',
  Bucket: 'testbucket-REDACTED'
}
{
  loaded: 62914560,
  total: 104857600,
  part: 15,
  Key: 'testfile100mb',
  Bucket: 'testbucket-REDACTED'
}
{
  loaded: 68157440,
  total: 104857600,
  part: 14,
  Key: 'testfile100mb',
  Bucket: 'testbucket-REDACTED'
}
{
  loaded: 73400320,
  total: 104857600,
  part: 11,
  Key: 'testfile100mb',
  Bucket: 'testbucket-REDACTED'
}
{
  loaded: 78643200,
  total: 104857600,
  part: 12,
  Key: 'testfile100mb',
  Bucket: 'testbucket-REDACTED'
}
{
  loaded: 83886080,
  total: 104857600,
  part: 16,
  Key: 'testfile100mb',
  Bucket: 'testbucket-REDACTED'
}
{
  loaded: 89128960,
  total: 104857600,
  part: 17,
  Key: 'testfile100mb',
  Bucket: 'testbucket-REDACTED'
}
{
  loaded: 94371840,
  total: 104857600,
  part: 20,
  Key: 'testfile100mb',
  Bucket: 'testbucket-REDACTED'
}
{
  loaded: 99614720,
  total: 104857600,
  part: 18,
  Key: 'testfile100mb',
  Bucket: 'testbucket-REDACTED'
}
{
  loaded: 104857600,
  total: 104857600,
  part: 19,
  Key: 'testfile100mb',
  Bucket: 'testbucket-REDACTED'
}
Upload completed successfully: {
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'REDACTED',
    extendedRequestId: 'REDACTED',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  ServerSideEncryption: 'AES256',
  VersionId: 'REDACTED',
  Bucket: 'testbucket-REDACTED',
  ETag: '"REDACTED"',
  Key: 'testfile100mb',
  Location: 'https://testbucket-REDACTED.s3.us-east-1.amazonaws.com/testfile100mb'
}
```

I'm not sure if this was fixed from the time this issue was created, but currently Im not able to reproduce this at this point in time. I tried forcing the error by providing `ContentLength: 0` and `ContentLength: undefined` and both resulted in a successful upload as well.

If anyone is running into this in the future, it would be helpful to understand how the request is sent when this XML validation error is being thrown. The SDK might not serializing the data correctly. You can verify the raw request if you add this middleware:

client.middlewareStack.add(next => async (args) => {
 console.log(args.request)
 const response = await next(args);
 console.log(response);
 return response;
}, {step: 'finalizeRequest'})

This would capture the request before its being sent over the wire and might reveal some discrepancy that caused the error.

Thanks,
Ran~

**Comment by DougReeder** [comment]
FWIW, I ran some Multipart uploads both with and without ContentLength.  All of them succeeded.  I haven't changed the version of aws-sdk-js-v3 I use, so it's looking like a server-side change fixed this. :-S

Does it help Multipart to have a ContentLength?

**Comment by RanVaknin** [comment]
Hi @DougReeder ,

The SDK should be able to calculate Content length on its own. There should not be a need for you to that.

Happy to hear this went away. I'm going to close and lock the thread.
If anyone else running into this issue in the future please open a _new issue_ so your comments would be more discoverable.

Thanks,
Ran~
