### ISSUE TITLE
Does @aws-sdk/lib-storage Upload - Multipart upload verify integrity of uploaded objects?

### ISSUE THREAD

**Issue by camhart** [aws/aws-sdk-js-v3#3920]
### Describe the issue

Is data integrity verified when using multi-part uploading with the lib-storage Upload class?

The Documentation makes no mention of data integrity.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_lib_storage.html

**Comment by ajredniwja** [comment]
Hey @camhart thanks for opening this issue, When you upload an object, you can optionally include a precalculated checksum as part of your request. Amazon S3 compares the provided checksum to the checksum that it calculates by using your specified algorithm. If the two values don't match, Amazon S3 reports an error. 

https://docs.aws.amazon.com/AmazonS3/latest/userguide/checking-object-integrity.html

Applicable commands of S3 (PutObject, PutBucketCors, etc.) will automatically compute the MD5 checksums for of the request payload. You can also specify a different checksum algorithm in the commands' ChecksumAlgorithm parameter to use a different checksum algorithm. You can find more infomation in the [S3 feature announcement](https://aws.amazon.com/blogs/aws/new-additional-checksum-algorithms-for-amazon-s3/)

**Comment by camhart** [comment]
@ajredniwja That's not how it works with multipart uploads though.  Multipart uploads must include the MD5 hash on each individual part.  My files are many GB in size, so I want to utilize multipart upload, but I need some way to sign each individual part.

So am I correct in understanding that the SDK does not offer the ability to verify data integrity using multipart uploads?  If so, I'd like to make this a feature request (also the documentation should point all of this out).

**Comment by yenfryherrerafeliz** [comment]
Hi @camhart, sorry to hear about your issues. We have a bug marked to be reviewed [here](https://github.com/aws/aws-sdk-js-v3/issues/4321). However, in the meantime you could use the workaround provided in the following [comment](https://github.com/aws/aws-sdk-js-v3/issues/2673#issuecomment-991455219).

Thanks!
