### ISSUE TITLE
using @aws-sdk/smithy-client in react-native returns "Credential is missing is missing"

### ISSUE THREAD

**Issue by sivantcy** [aws/aws-sdk-js-v3#3921]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I generated a ts client through Smithy which using [@aws-sdk/smithy-client](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_smithy_client.html#aws-sdksmithy-client).
I'm not using credential for the authentication, my authentication base on parameter in the header. when I using the client though another node package it works well, but when I'm trying to use the client though react-native package, I am getting the error "Credential is missing is missing" although I don't want to use credential.
how can I use the generated ts client without credential in react-native package?

### SDK version number

@aws-sdk/package-name@version, ...

### Which JavaScript Runtime is this issue in?

React Native

### Details of the browser/Node.js/ReactNative version

0.70

### Reproduction Steps

1. create a service without credential authentication
2. create a smithy model with error that look like that:
3. generate ts client directly
4. use the generated client in react native package

### Observed Behavior

Credential is missing is missing error

### Expected Behavior

send the request as is

### Possible Solution

not enforce credential in the generated client

**Comment by ajredniwja** [comment]
Hey @sivantcy thanks for opening this issue, the package is marked as an internal package which mentions you should not be using it at least directly. With that being said I see it only happening in ReactNative app so it might be related to just react too, can you share the code you used for reproduction steps too that I may use and investigate more?
