### ISSUE TITLE
Analog to createPresignedPost from v2?

### ISSUE THREAD

**Issue by raygesualdo** [aws/aws-sdk-js-v3#395]
**Is your feature request related to a problem? Please describe.**

For creating presigned POST URLs and form field values, the v2 API has a [`createPresignedPost`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#createPresignedPost-property) function. Looking through v3, I don't see a corresponding function. Is this intentional? Or am I missing something?

**Describe the solution you'd like**

Have a single function that provides the URL and form fields necessary to perform direct uploads to S3.

**Describe alternatives you've considered**

- Staying with v2.
- Recreating v2's functionality in user-land around v3.

**Additional context**

N/A

**Comment by AllanFly120** [comment]
Thanks @raygesualdo 

This is a feature that not yet implemented in V3. I have labeled it as a feature request.

**Comment by joedevgee** [comment]
Any timeline update on implementing this feature?
