### ISSUE TITLE
S3 GetBucketLifecycleConfigurationCommand does not work if rules is empty

### ISSUE THREAD

**Issue by XDXXDXXDXXDXXDX** [aws/aws-sdk-js-v3#3973]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

GetBucketLifecycleConfigurationCommand throws error when backend return empty rules

### SDK version number

@aws-sdk/client-s3@3.171.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.15.0

### Reproduction Steps

```js
import {
    S3Client,
    GetBucketLifecycleConfigurationCommand,
} from "@aws-sdk/client-s3";

// init s3Client ...

(async () => {
    try {
        const data = await s3Client.send(new GetBucketLifecycleConfigurationCommand(params));
        console.log(data);
    } catch (err) {
        console.log(err);
    }
})();
```

### Observed Behavior

// throw error
TypeError: Expected object, got string: 
    at expectObject (/Users/dongxiang.xie/Desktop/uss-s3/node_modules/@aws-sdk/smithy-client/dist-cjs/parse-utils.js:130:11)
    at deserializeAws_restXmlGetBucketLifecycleConfigurationCommand (/Users/dongxiang.xie/Desktop/uss-s3/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:3873:86)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/dongxiang.xie/Desktop/uss-s3/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /Users/dongxiang.xie/Desktop/uss-s3/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
    at async StandardRetryStrategy.retry (/Users/dongxiang.xie/Desktop/uss-s3/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /Users/dongxiang.xie/Desktop/uss-s3/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at async file:///Users/dongxiang.xie/Desktop/uss-s3/getBucketLifecycleConfiguration.js:22:22 {
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}

### Expected Behavior

``
// response with no rules field
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: undefined,
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}

### Possible Solution

node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js
`parseBody` method

`parseBody` should return empty object(`{}`) when reponse xml is empty tag like `<LifecycleConfiguration></LifecycleConfiguration>`

### Additional Information/Context

backend responese sample: 
with rules(it works ok)
![image](https://user-images.githubusercontent.com/40033292/191700708-5dc563cd-c417-4311-a915-1a33836b7ede.png)

without rules(internal throw error)
![image](https://user-images.githubusercontent.com/40033292/191700985-e7ece462-8501-43c2-8c7f-927853e171d6.png)

PS: I can get the correct results using Python's SDK, so I think this is a problem with JSSDK parsing

**Comment by yenfryherrerafeliz** [comment]
Hi @XDXXDXXDXXDXXDX, thanks for opening this issue. I tried to reproduce the reported behavior but I am not sure how you could get a response with an empty rule field. In my case I get "NoSuchLifecycleConfiguration: The lifecycle configuration does not exist" when there are not rules created. Could you please provide any other details that would help me reproduce this issue?, could you please also show how you create the instance of the client?

Note: Please redact any sensitive information.

Thanks!

**Comment by XDXXDXXDXXDXXDX** [comment]
@yenfryherrerafeliz Thanks for the reminder that we found the problem! The storage backend I connected to is implemented by ourselves. When implementing this interface, the backend does not return 404 when the rule is empty according to the interface specification. Thanks again!
