### ISSUE TITLE
Entities dependency bumps up bundle size by 13 KB

### ISSUE THREAD

**Issue by AllanZhengYP** [aws/aws-sdk-js-v3#3978]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The `entities` dependency was introduced in the PR: https://github.com/aws/aws-sdk-js-v3/pull/2381 to solve the xml decoding issues. It's a 13 KB Gzipped un-treeshakable dependency. It has larger footprint than several SDK clients source code Gzipped. 

Now that the issue has been fixed in the mentioned dependency: https://github.com/aws/aws-sdk-js-v3/issues/2375#issuecomment-837611624, the dependency can be removed.

### SDK version number

@aws-sdk/client-s3

### Which JavaScript Runtime is this issue in?

Browser

### Details of the browser/Node.js/ReactNative version

all browsers

### Reproduction Steps

https://github.com/aws-amplify/amplify-js/pull/10362

### Observed Behavior

Bundle analytics report of [bundling Amplify-js library with 3.175.0 release of the SDK](https://github.com/aws-amplify/amplify-js/pull/10362): 

https://dev.d30eefz4azmpyu.amplifyapp.com/storage-new.html 

### Expected Behavior

The `entities` dependency not installed

### Possible Solution

Bump up `fast-xml-parser` to 4.0.0+

**Comment by trivikr** [comment]
Bumping fast-xml-parser to 4.x is not straightforward, as API has changed along with some options and protocol tests are failing.

For future reference, the commits can be picked from attempt:
* smithy-ts https://github.com/awslabs/smithy-typescript/pull/594
* aws-sdk-js-v3 https://github.com/aws/aws-sdk-js-v3/pull/3989

**Comment by kuhe** [comment]
fast xml parser is currently at 4.2.5 and entities is not imported in the sdk
