### ISSUE TITLE
Missing dependency in s3-presigned-post

### ISSUE THREAD

**Issue by ferbs** [aws/aws-sdk-js-v3#3981]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

`s3-presigned-post/src/createPresignedPost.ts` imports `@aws-sdk/middleware-endpoint` but does not include it as a dependency in package.json, breaking strict build environments (pnpm and Yarn PNP)

### SDK version number

@aws-sdk/package-name@version, ...

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.15.0

### Reproduction Steps

pnpm i @aws-sdk/s3-presigned-post
pnpm build

### Observed Behavior

```
Cannot find module "@aws-sdk/middleware-endpoint"
```

### Expected Behavior

No error, dependency installed

### Possible Solution

will submit a PR

**Comment by bmccann36** [comment]
same issue here https://github.com/aws/aws-sdk-js-v3/issues/3983#issue-1384429924

**Comment by yenfryherrerafeliz** [comment]
Hi @ferbs, this issue has been fixed by the following [PR](https://github.com/aws/aws-sdk-js-v3/pull/3988).

Thanks!
