### ISSUE TITLE
Multipart upload error on Safari using @aws-sdk/lib-storage: NotReadableError: The I/O read operation failed.

### ISSUE THREAD

**Issue by raghavdhingra** [aws/aws-sdk-js-v3#3986]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I am using Upload component from `@aws-sdk/lib-storage`.

Here's the code snippet which I am using,

```js
import { Upload } from "@aws-sdk/lib-storage";
import { S3Client } from "@aws-sdk/client-s3";

const creds = {
    accessKeyId: process.env.REACT_APP_ACCESSKEYID,
    secretAccessKey: process.env.REACT_APP_SECRETACCESSKEY,
};

const parallelUploads3 = new Upload({
      client: new S3Client({ region: "us-west-2", credentials: creds }),
      leavePartsOnError: false, // optional manually handle dropped parts
      params: {
        Bucket: process.env.REACT_APP_AWSBUCKET,
        Key: "file name",
        Body: file,
      },
});

parallelUploads3.on("httpUploadProgress", function (progress) {
      const progressPercentage = Math.round(
        (progress.loaded / progress.total) * 100
      );
     setPercentage(progressPercentage);
});

const uploadedfile = await parallelUploads3.done();
```

This works well in Chrome browser, but in Safari it throw the given error:

```
"NotReadableError:" The I/O read operation failed
```
Nothing else 🤔

### SDK version number

@aws-sdk/lib-storage@3.171.0

### Which JavaScript Runtime is this issue in?

Browser

### Details of the browser/Node.js/ReactNative version

v16.17.0

### Reproduction Steps

With the current implementation for the upload function on reactjs, and initiate the application on Safari.
Try to upload a video, and it will throw the following error.

```
"NotReadableError:" The I/O read operation failed
```

### Observed Behavior

On Safari Version 15.6.1:
When I try to upload a 12.9GB video using the Multipart upload function, it throwed an error `"NotReadableError:" The I/O read operation failed`

### Expected Behavior

Any size video which anyone upload should be uploaded without any error, or issue on Safari.

**Comment by yenfryherrerafeliz** [comment]
Hi @raghavdhingra, thanks for opening this issue. This seems to be a limitation / issue from the browser side. Could you please confirm if this issue happens also with other type of files that are not videos?

Thanks!
