### ISSUE TITLE
DOM lib still required for TS to compile in Node app

### ISSUE THREAD

**Issue by marshmellow1328** [aws/aws-sdk-js-v3#3991]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I suspect fixing https://github.com/aws/aws-sdk-js-v3/issues/2896 has revealed another issue with DOM lib required for Typescript.

> ../node_modules/.pnpm/@aws-sdk+types@3.178.0/node_modules/@aws-sdk/types/dist-types/endpoint.d.ts:48:10 - error TS2304: Cannot find name 'URL'.

### SDK version number

@aws-sdk/client-cloudformation@3.178.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

16.17.0

### Reproduction Steps

* Create a fresh TS workspace
* Set minimal tsconfig.json and do not include "dom" in lib array
* Install @aws-sdk/lib-dynamodb@3.178.0
* import { DynamoDBDocument } from "@aws-sdk/lib-dynamodb"; into hello world file
* run tsc to compile project

### Observed Behavior

Error while compiling typescript

> ../node_modules/.pnpm/@aws-sdk+types@3.178.0/node_modules/@aws-sdk/types/dist-types/endpoint.d.ts:48:10 - error TS2304: Cannot find name 'URL'.

### Expected Behavior

Should compile successfully without needing the DOM lib defined in the tsconfig.json

### Additional Information/Context

If you add "dom" to lib array in tsconfig.json, source code will compile successfully

**Comment by kuhe** [comment]
Please create a minimal reproduction repository containing a package.json, tsconfig.json, and sample `.ts` file to compile. URL has been globally available in NodeJS since v10 according to https://nodejs.org/docs/latest-v14.x/api/url.html#url_class_url.

You can also try setting `skipLibCheck` to true in tsconfig.json.
