### ISSUE TITLE
Reduce install and bundle size by optimizing code gen

### ISSUE THREAD

**Issue by everett1992** [aws/aws-sdk-js-v3#3996]
### Describe the feature

The sdk code gen creates a lot of duplicate code for every command and type in the service model. Optimizing the code generator to use more helper functions should reduce the size of each client - affecting local install size, bundle size, parsing time, and potentially runtime performance. I'm not confident about runtime performance, but my understanding is that javascript runtimes are better at optimizing functions that are called repeatedly. 

Examples from @aws-sdk/client-dynamodb@3.180.0

#### dist-cjs/models/models_0.js[^1]
```typescript
const ArchivalSummaryFilterSensitiveLog = (obj) => ({ ...obj });
exports.ArchivalSummaryFilterSensitiveLog = ArchivalSummaryFilterSensitiveLog;
const AttributeDefinitionFilterSensitiveLog = (obj) => ({ ...obj, });
exports.AttributeDefinitionFilterSensitiveLog = AttributeDefinitionFilterSensitiveLog;
```
repeated 154 times for different functions. 
This could be reduced with a helper saving ~18 bytes per type.
```typescript
const assign = (obj) => ({ ...obj });
const ArchivalSummaryFilterSensitiveLog = assign;
exports.ArchivalSummaryFilterSensitiveLog = ArchivalSummaryFilterSensitiveLog;
const AttributeDefinitionFilterSensitiveLog = assign;
exports.AttributeDefinitionFilterSensitiveLog = AttributeDefinitionFilterSensitiveLog;
```

#### dist-cjs/protocols/Aws_json1_0.js
Every command matches this pattern
```typescript
const serializeAws_json1_0BatchExecuteStatementCommand = async (input, context) => {
    const headers = {
        "content-type": "application/x-amz-json-1.0",
        "x-amz-target": "DynamoDB_20120810.BatchExecuteStatement",
    };
    let body;
    body = JSON.stringify(serializeAws_json1_0BatchExecuteStatementInput(input, context));
    return buildHttpRpcRequest(context, headers, "/", undefined, body);
};
exports.serializeAws_json1_0BatchExecuteStatementCommand = serializeAws_json1_0BatchExecuteStatementCommand;
```

Switching to a helper saves about 40kb
```typescript
const command = (target, fn, input, context) => {
  const headers = {
    "content-type": "application/x-amz-json-1.0",
    "x-amz-target": target,
  };
  let body;
  body = JSON.stringify(fn(input, context));
  return buildHttpRpcRequest(context, headers, "/", undefined, body);
}

// repeat for each command. Event this could be optimized for size, but I think it's caused by tsc, not aws codegen.
const serializeAws_json1_0BatchExecuteStatementCommand = command.bind(null, "DynamoDB_20120810.BatchExecuteStatement", serializeAws_json1_0BatchExecuteStatementInput)
exports.serializeAws_json1_0BatchExecuteStatementCommand = serializeAws_json1_0BatchExecuteStatementCommand;

```

[^1]: My examples are from dist-cjs which was compiled targeting ES2018, rather than dist-es which targets es5, but the repetition is present in both, and the source typescript.

These are the simplest examples I could find but a lot of the generated code has repetitive structure that could be abstracted into helpers.

### Use Case

Bundling aws sdk and smity clients for the web or lambda.

### Proposed Solution

Optimize the code gen

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.180.0

### Environment details (OS name and version, etc.)

node

**Comment by kuhe** [comment]
This is a favorite topic of mine. I have worked on improvements in this area such as https://github.com/awslabs/smithy-typescript/pull/576, which I plan to also apply to JSON protocols like your example. 

But they are not a high priority compared to functional features and fixes, and I don't know when I can continue this.

PRs are welcome. For this one the generator is located at https://github.com/awslabs/smithy-typescript/blob/main/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java#L213 as `generateOperationSerializer`.

**Comment by kuhe** [comment]
closing this because it is being addressed in a continuous manner

**Comment by kuhe** [comment]
Don't ask me why I made this list, but just as a record, here are some PRs related to reducing generated code size:

* https://github.com/aws/aws-sdk-js-v3/pull/3830 generalized data mapping function ( codegen )
* https://github.com/aws/aws-sdk-js-v3/pull/4198 reduce object copy operations ( runtime  perf.)
* https://github.com/aws/aws-sdk-js-v3/pull/4300 created compression algo for Endpoints2.0 Rulesets ( runtime  perf.)
* https://github.com/aws/aws-sdk-js-v3/pull/4496 remove the need for aggregated client in paginators (runtime perf.)
* https://github.com/smithy-lang/smithy-typescript/pull/722 remove unnecessary log filters ( codegen )
* https://github.com/smithy-lang/smithy-typescript/pull/730 shorten serde function names ( codegen )
* https://github.com/aws/aws-sdk-js-v3/pull/4616 general data extraction function ( codegen )
* https://github.com/smithy-lang/smithy-typescript/pull/735 serde elision for JSON ( codegen )
* https://github.com/smithy-lang/smithy-typescript/pull/736 generate aggregated clients using a factory ( codegen )
* https://github.com/smithy-lang/smithy-typescript/pull/1150 generate unified error dispatcher ( codegen )
* https://github.com/smithy-lang/smithy-typescript/pull/1108 generate re-usable string constants ( codegen )
* https://github.com/aws/aws-sdk-js-v3/pull/5567 XML builder  codegen  
* https://github.com/aws/aws-sdk-js-v3/pull/5681 lazy load optional credential resolvers (runtime perf.)
* https://github.com/aws/aws-sdk-js-v3/pull/5855 reduce generation of duplicate functions ( codegen )
* https://github.com/smithy-lang/smithy-typescript/pull/1107 generate HttpRequest objects in builder pattern ( codegen )
* https://github.com/smithy-lang/smithy-typescript/pull/1114 generate paginators with a factory ( codegen )
* https://github.com/smithy-lang/smithy-typescript/pull/1118 generate commands with a factory ( codegen )
* https://github.com/smithy-lang/smithy-typescript/pull/1146 partial bundling for CJS artifacts (runtime perf.)
