### ISSUE TITLE
getSignedUrl returning error when using PutObjectCommand

### ISSUE THREAD

**Issue by SharkBait80** [aws/aws-sdk-js-v3#4010]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When using PutObjectCommand to generate signed URL, the error returned is: 
`TypeError: (0 , middleware_sdk_s3_1.getCheckContentLengthHeaderPlugin) is not a function`
Using GetObjectCommand works fine, and the signed URL is generated.

### SDK version number

@aws-sdk/client-s3@^3.181.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.16.0

### Reproduction Steps

```
const s3Key = `uploads/upload.csv`;
    const client = new S3Client({});
    const command = new PutObjectCommand({
      Bucket: UPLOAD_BUCKET,
      Key: s3Key,
    });
    console.log(`Presign command: ${JSON.stringify(command)}`);
    return await getSignedUrl(client, command, { expiresIn: 3600 });
```

### Observed Behavior

An error was thrown.

TypeError: (0 , middleware_sdk_s3_1.getCheckContentLengthHeaderPlugin) is not a function

### Expected Behavior

No error to be thrown, and the presigned URL to be returned.

### Possible Solution

Possibly, an issue with middleware resolution in https://github.com/aws/aws-sdk-js-v3/blob/33e68228fb64c53dd8f89e6be76dd5f46edc3cfd/clients/client-s3/src/commands/PutObjectCommand.ts

**Comment by ajredniwja** [comment]
Hey @SharkBait80 thanks for opening this issue, using the code provided I was able to successfully get the `url`. 

```js
import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";

(async() => {
    const client = new S3Client({});
    const command = new PutObjectCommand({
        Bucket: "bucket",
        Key: 's3Key',
    });
    console.log(`Presign command: ${JSON.stringify(command)}`);
    const url = await getSignedUrl(client, command, { expiresIn: 3600 });
    console.log(`Presigned URL: ${url}`);
})();
```
Output: 
```
Presign command: {"middlewareStack":{},"input":{"Bucket":"bucket","Key":"s3Key"}}
Presigned URL: https://bucket.s3.us-west-2.amazonaws.com/s3Key?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=
```

**Comment by SharkBait80** [comment]
Interesting. I'm still getting the error. I wonder if it could be a version mismatch between @aws-sdk/client-s3 and @aws-sdk/s3-request-presigner ?

**Comment by ajredniwja** [comment]
Can you check with config like: 
```json
    "dependencies": {
        "@aws-sdk/client-s3": "^3.181.0",
        "@aws-sdk/s3-request-presigner": "^3.181.0"
    }
```

**Comment by SharkBait80** [comment]
Deleting my base node_modules and running `yarn` has fixed the issue.
