### ISSUE TITLE
TypeError: Class constructor Client cannot be invoked without 'new' (v3.185.0)

### ISSUE THREAD

**Issue by techncl** [aws/aws-sdk-js-v3#4022]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When we invoke the s3 client
`const client = new S3Client(config)`

we are getting this error in the console

```console
S3Client.js:29 Uncaught (in promise) TypeError: Class constructor a cannot be invoked without 'new'
    at new t (S3Client.js:29:24)
    at new k (index.ts:53:20)
    at $ (index.ts:63:9)
    at async window.onload (index.ts:4:3)
```

I noticed that you recently set the target version to es5 in the [tsconfig file](https://github.com/aws/aws-sdk-js-v3/commit/f077318be171d65352e71409e82fc486a39f6cda) which apparently causes [this issue](https://bobbyhadz.com/blog/typescript-class-constructor-cannot-be-invoked-without-new)

### SDK version number

aws-sdk-js-v3@v3.185.0

### Which JavaScript Runtime is this issue in?

Browser

### Details of the browser/Node.js/ReactNative version

 Browsers:     Chrome: 105.0.5195.125     Firefox: 103.0.2     Safari: 15.6.1

### Reproduction Steps

Invoke the S3Client like: 

`const client = new S3Client(config)`

### Observed Behavior

When you click the upload button, some JS is called that's supposed to display a message, but that message wasn't showing up; I checked the console and saw this

```console
S3Client.js:29 Uncaught (in promise) TypeError: Class constructor a cannot be invoked without 'new'
    at new t (S3Client.js:29:24)
    at new k (index.ts:53:20)
    at $ (index.ts:63:9)
    at async window.onload (index.ts:4:3)
```

when I click the line that it's pointing to, it highlights the last line (of the code below) in red

```js
function S3Client(configuration) {
        var _this = this;
        var _config_0 = __getRuntimeConfig(configuration);
        var _config_1 = resolveRegionConfig(_config_0);
        var _config_2 = resolveEndpointsConfig(_config_1);
        var _config_3 = resolveRetryConfig(_config_2);
        var _config_4 = resolveHostHeaderConfig(_config_3);
        var _config_5 = resolveAwsAuthConfig(_config_4);
        var _config_6 = resolveBucketEndpointConfig(_config_5);
        var _config_7 = resolveUserAgentConfig(_config_6);
        var _config_8 = resolveEventStreamSerdeConfig(_config_7);
        _this = _super.call(this, _config_8) || this;
```

### Expected Behavior

Not to see this error in the console

### Possible Solution

To not set the target to es5

**Comment by santiagomera** [comment]
Started getting the same error a few minutes ago. Resolved by reverting to the previous version of the aws sdk I was using.

**Comment by techncl** [comment]
Yep, me too.

**Comment by RanVaknin** [comment]
Thanks for bringing this to our attention. 

We will look into this and update here.

Thanks,
Ran~

**Comment by automartin5000** [comment]
> 



> Could you also try the latest `v3.186.0` package versions of modules from `@aws-sdk`?
> 
> I believe this problem is specific to 3.185.0 and `dist-es` (typically used by browsers), where there was an incorrect mix of ES5 and ES2020 modules in the `dist-es` distribution folders.

`3.186.0` seems to have fixed the problem for me.

**Comment by kimmolinna** [comment]
Previously I was able to use the latest version with ` import("@aws-sdk/client-s3")` but now I have to define the version ` import("@aws-sdk/client-s3@3.186.0")` But I can confirm that version `3.186.0`is working.

**Comment by techncl** [comment]
I can confirm that 3.186 seems to have solved the issue too.

**Comment by RanVaknin** [comment]
This seems to have been solved. If the problem rises again please open a new issue. 

Thank you,
Ran~
