### ISSUE TITLE
DBSnapshotNotFound has been replaced by DBSnapshotNotFoundFault

### ISSUE THREAD

**Issue by grzegorz-faryna-mergermarket** [aws/aws-sdk-js-v3#4023]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Update @aws-sdk/client-rds from 3.179.0 to 3.181.0 caused a change of error that is thrown when calling `rds.describeDBSnapshots({ DBSnapshotIdentifier })`, when pointed database snapshot does not exist.
It used to throw `DBSnapshotNotFound `error. Which was inlined with error described in https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeDBSnapshots.html 

Now it is throwing `DBSnapshotNotFoundFault`. From my point of view it looks like a bug, because it is not aligned with https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeDBSnapshots.html 

### SDK version number

@aws-sdk/client-rds@3.181.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.15.1

### Reproduction Steps

```js
try {
  await rds.describeDBSnapshots({ DBSnapshotIdentifier })
} catch (error) {
  if (error instanceof Error && error.name === 'DBSnapshotNotFound') {
    // should get into here
  } else {
    // gets here, because error.name is 'DBSnapshotNotFoundFault', instead of 'DBSnapshotNotFound'
  }
}
```

### Observed Behavior

```console
{
  "name": "DBSnapshotNotFoundFault",
  "$fault": "client",
  "$metadata": {
    "httpStatusCode": 404,
    "requestId": "b25ee74e-8838-44b0-9148-0961d7fa6235",
    "attempts": 1,
    "totalRetryDelay": 0
  },
  "xmlns": "http://rds.amazonaws.com/doc/2014-10-31/",
  "Error": {
    "Type": "Sender",
    "Code": "DBSnapshotNotFound",
    "Message": "DBSnapshot <DBSnapshotIdentifier> not found.",
    "message": "DBSnapshot <DBSnapshotIdentifier> not found."
  },
  "RequestId": "b25ee74e-8838-44b0-9148-0961d7fa6235"
}
```

### Expected Behavior

`rds.describeDBSnapshots({ DBSnapshotIdentifier })` throws `DBSnapshotNotFound` instead of `DBSnapshotNotFoundFault`

**Comment by RanVaknin** [comment]
Hi @grzegorz-faryna-mergermarket ,

I understand the issue you are experiencing. The [official recommendation](https://aws.amazon.com/blogs/developer/service-error-handling-modular-aws-sdk-js/) is to use instanceOf and not using the `name` field, so I can't promise any changes. I will assign it to the dev team for further consideration.


**For the dev team**, here are repro and output comparisons with the CLI and Golang SDK:

CLI:
```console
$ aws rds describe-db-snapshots --db-snapshot-identifier adasdadsd

An error occurred (DBSnapshotNotFound) when calling the DescribeDBSnapshots operation: DBSnapshot adasdadsd not found.
```

Go SDK:
```go
func main() {
	cfg, err := config.LoadDefaultConfig(context.TODO(), config.WithRegion("us-east-1"), config.WithClientLogMode(aws.LogResponseWithBody))
	if err != nil {
		log.Fatalf("unable to load SDK config, %v", err)
	}

	client := rds.NewFromConfig(cfg)

	out, err := client.DescribeDBSnapshots(context.Background(), &rds.DescribeDBSnapshotsInput{
		DBSnapshotIdentifier: aws.String("iaisb8qjkas"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(len(out.DBSnapshots))
}
```

output:
```console
<ErrorResponse xmlns="http://rds.amazonaws.com/doc/2014-10-31/">
  <Error>
    <Type>Sender</Type>
    <Code>DBSnapshotNotFound</Code>
    <Message>DBSnapshot iaisb8qjkas not found.</Message>
  </Error>
  <RequestId>redacted</RequestId>
</ErrorResponse>
panic: operation error RDS: DescribeDBSnapshots, https response error StatusCode: 404, RequestID: redacted, DBSnapshotNotFound: DBSnapshot iaisb8qjkas not found.

```
Thanks,
Ran
