### ISSUE TITLE
GetObjectCommand eventually stops returning

### ISSUE THREAD

**Issue by grassick** [aws/aws-sdk-js-v3#4029]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Calling GetObjectCommand works just fine for 100,000s of requests. But eventually, after a few days, it starts returning slower  (sometimes 130 seconds, sometimes 65 seconds, sometimes 90 seconds). Then at some point it just simply stops returning. The promise is neither resolved nor rejected. No error is put out to the console.

Our server has been connecting to AWS for years using an older Node.js client called "knox". I just recently switched to the official AWS client, v3, and that's when this problem started.

Others have run into this exact bug:

https://github.com/aws/aws-sdk-js-v3/issues/3391

https://stackoverflow.com/questions/73256172/nodejs-amazon-aws-sdk-s3-client-stops-working-intermittently

Restarting the node process immediately solves the problem and requests become fast once again.

### SDK version number

@aws-sdk/client-s3@3.186.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v14.17.1

### Reproduction Steps

It only happens after days of 100,000+ requests per day. Here's the call that's made:

```js
    try {
      const response = await this.client.send(new GetObjectCommand({ Bucket: this.bucket, Key: key }))
      return { statusCode: response.$metadata.httpStatusCode!, body: response.Body as Readable, metadata: response.Metadata }
    } catch (err) {
      if (err.$metadata?.httpStatusCode) {
        return { statusCode: err.$metadata.httpStatusCode! }
      }
      throw err
    }
```

Nothing magic and it works fine for the first 100,000 requests.

### Observed Behavior

Promise is neither resolved nor rejected. No error message to console, no exception thrown.

### Expected Behavior

Call to resolve or reject. To do it within a reasonable time, not over 2 minutes, or never.

### Possible Solution

I've looked at netstat and don't see any unusual sockets. No idea.

### Additional Information/Context

Happens consistently on our server, but only after a few days. Is bad since server processes need to be reloaded, or all image serving will stop.

**Comment by grassick** [comment]
This is still happening as of today and I just did a server reset to fix it once again.

**Comment by ftr-lwilson** [comment]
Hi @yenfryherrerafeliz!

Just wondering if there has been any progress on this issue?

We recently migrated from the v2 SDK to v3 and have unfortunately run into the same problem in our production environment. Like @grassick, a simple restart seems to breathe life back into it. However this was not sustainable, and we had to revert back to v2. 

Looking forward to hearing any updates about this as we are keen to use the v3 SDK, but cannot do so in the current state.

**Comment by RanVaknin** [comment]
Might be related to #4332

**Comment by grassick** [comment]
This is still going on as of March 2023. The number of sockets open on our server grows and grows until the server stops responding properly. We are downgrading to v2 for now. This is a blocker in moving to v3, so please don't deprecate v2 until this is solved!

**Comment by yenfryherrerafeliz** [comment]
Hi @grassick, @ftr-lwilson, could you please confirm if this issue is still happening in the latest version?. We have included the following changes [here](https://github.com/aws/aws-sdk-js-v3/pull/4561), which enables keep alive option for sockets, which will help in keeping sockets alive longer.

Thanks!
