### ISSUE TITLE
Parsing body failing if AWS rate limit exceeded

### ISSUE THREAD

**Issue by Jojnas** [aws/aws-sdk-js-v3#4038]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Function https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-codecommit/src/protocols/Aws_json1_1.ts#L14669 works correctly only if AWS does not send the response "Rate exceeded" error.

After little debugging I have figured out that the below content is passed to "encoded" variable.
![image](https://user-images.githubusercontent.com/11946576/195572031-88af6a87-c91c-4d49-a1dc-55b6f5b30503.png)

After trying to JSON.parse such a response it fails with error: "Unexpected token < in JSON at position"

### SDK version number

2.1229.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.15.1

### Reproduction Steps

To run more requests than AWS Codecommit API rate limit in parallel.

### Observed Behavior

It throws 500.

### Expected Behavior

To get metadata and return 429 response.

**Comment by yenfryherrerafeliz** [comment]
Hi @Jojnas, sorry for the delay on answering to this. Could you please clarify if the issue is when using the AWS SDK for JavaScript V3, or when using V2?. 
Because here you refer to a V3 implementation:
>Function https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-codecommit/src/protocols/Aws_json1_1.ts#L14669 works correctly only if AWS does not send the response "Rate exceeded" error.

but the version that you have provided is:
>2.1229.0

It will also be helpful if  you show the sample code that caused this error for you. 

Thanks!
