### ISSUE TITLE
got "Error: read ECONNRESET     at TLSWrap.onStreamRead" when uploading file to s3 bucket of Asia Pacific (Mumbai) 

### ISSUE THREAD

**Issue by zenghj** [aws/aws-sdk-js-v3#4045]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Fail to upload file to s3 bucket. It seems to be related to the bucket region. With the same code, uploading to bucket of Asia Pacific (Mumbai) (region: ap-south-1) will get the error, but uploading to bucket of Europe (London) (region: eu-west-2) or bucket of EU (London) (region: eu-west-2) will be successfully.

### SDK version number

3.186.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.6.0

### Reproduction Steps
```js
// // Import required AWS SDK clients and commands for Node.js.
const { PutObjectCommand, S3Client } = require( "@aws-sdk/client-s3");
// // import { s3Client } from "./libs/s3Client.js"; // Helper function that creates an Amazon S3 service client module.
const fs = require('fs')
const path = require('path')

s3Client = new S3Client({
  region: 'ap-south-1',
  credentials: {
    accessKeyId: 'xxxxxx',
    secretAccessKey: 'xxxx'
  }
})

const fileStream = fs.createReadStream('/path-to-my-local-file/test.txt');

// Set the parameters
 const uploadParams = {
  Bucket: 'my-bucket-name',
  // Add the required 'Key' parameter using the 'path' module.
  Key: 'test.txt',
  // Add the required 'Body' parameter
  Body: fileStream,
};


// Upload file to specified bucket.
 const run = async () => {
  try {
    const data = await s3Client.send(new PutObjectCommand(uploadParams));
    console.log("Success", data);
    return data; // For unit tests.
  } catch (err) {
    console.log("Error", err);
  }
};
run();
```
### Observed Behavior

got error:
```console
Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read',
  name: 'TimeoutError',
  '$metadata': { attempts: 3, totalRetryDelay: 478 }
}
```
### Expected Behavior

upload file successfully

**Comment by yenfryherrerafeliz** [comment]
Hi @zenghj, thanks for opening this issue. I am not sure why you are getting this error; did you make sure it is not a network restriction from your environment?, I just tried on my end and I got not issues. 

I used the code below:
```js
const {S3Client, PutObjectCommand} = require("@aws-sdk/client-s3");
const fs = require("fs");
const path = require("path");
const client = new S3Client({region: 'ap-south-1'})
const bucket = 'BUCKET';
const fileStream = fs.createReadStream('./test.txt');
const uploadParams = {
    Bucket: bucket,
    Key: 'test.txt',
    Body: fileStream,
};
// Upload file to specified bucket.
(async () => {
    try {
        const data = await client.send(new PutObjectCommand(uploadParams));
        console.log("Success", data);
        return data; // For unit tests.
    } catch (err) {
        console.log("Error", err);
    }
})();

```
Response I got:
```console
Success {
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'REQUEST-OD',
    extendedRequestId: 'EXTENDED-REQUEST-ID',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  ETag: 'ETAG'
}

```

Thanks!

**Comment by zenghj** [comment]
I don't why, but I debugged the program and I found If I change the request protocol from https to http, it could be uploaded successfully.
So now I can resolve it by enforcing to use http:
`
const s3Client = new S3Client({
  region: 'ap-south-1',
  tls: false,
  credentials: {
    accessKeyId: 'xxxx',
    secretAccessKey: 'xxxx'
  }
})
`
Thanks anywhere!

**Comment by Jeric-Disney** [comment]
hi @yenfryherrerafeliz I have the same error. I cannot upload files larger than 50kb.

<img width="697" alt="Screen Shot 2022-10-19 at 10 20 41 AM" src="https://user-images.githubusercontent.com/105732335/196582395-d29aec06-73c2-4d44-a94b-74445e8ec126.png">

**Comment by Jeric-Disney** [comment]
uploading more than 50kb fails with this code(see below). But, 50kb and below is uploading successfully.

<img width="630" alt="Screen Shot 2022-10-19 at 1 00 24 PM" src="https://user-images.githubusercontent.com/105732335/196601565-6778fd72-139a-4d70-8f8e-67f73ca662b4.png">

**Comment by yenfryherrerafeliz** [comment]
Hi @Jeric-Disney, I just uploaded a 65 KB file and then a 65 MB file and I got not issues; I will ask internally about this, however, some times the issue comes from limitations from the network, and also have you checked if is there any policy on your bucket that prevent a file to be over 50 KB?

Thanks!

**Comment by Jeric-Disney** [comment]
Hello @yenfryherrerafeliz I don't have any policies on my bucket. It's weird that I also don't find any solutions. I also tried aws-sdk and even signed urls - still the same error.

**Comment by Jeric-Disney** [comment]
Hi @yenfryherrerafeliz I tested on my other machine, and it worked. So the problem was just firewall issues. Thank you so much for the quick response.

**Comment by yenfryherrerafeliz** [comment]
@Jeric-Disney you are very welcome.
