### ISSUE TITLE
Incorrect source code for node.js sample in 'STS Client - AWS SDK for JavaScript v3' page under 'v2 compatible style' section

### ISSUE THREAD

**Issue by gdm** [aws/aws-sdk-js-v3#4047]
### Describe the issue

'promise()' was missing in the following code sample (from https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-sts/index.html Under 'v2 compatible style')

Existing code (as of 2022-10-17):
```
// Promises.
client
  .assumeRole(params)
  .then((data) => {
    // process data.
  })
```

Correct one (with 'promise()')
```
// Promises.
client
  .assumeRole(params)
  .promise()
  .then((data) => {
    // process data.
  })
```

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-sts/index.html

**Comment by yenfryherrerafeliz** [comment]
Hi @gdm, thanks for opening this issue.

The method assumeRole will return a promise, so that I do not understand why we should call a method called promise(). Could you please provide more details about why and how we should use your suggested changes?

Thanks!
