### ISSUE TITLE
DynamoDBClient default maxAttempts is 3, inconsistent with other AWS SDK clients

### ISSUE THREAD

**Issue by amdhing** [aws/aws-sdk-js-v3#4049]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

DynamoDB Client for V3 has the same maxAttempts as other AWS Service clients, and this is inconsistent with V2 or other DynamoDB clients for other AWS SDKs. 
Clients for all other AWS SDKs (including aws-sdk-js) have a default (usually 3) for other AWS services, but 8 or 10 as default for DynamoDB clients.

While I understand it may be late to change this behavior, would be super helpful if this change is explicitly called out on the docs along with a sample on setting the `maxAttempts` for V3 vs `maxRetries` for V2. Currently only thing called out is that its `maxAttempts` for V3 instead of `maxRetries`.

Thanks a mil!

### SDK version number

@aws-sdk/client-dynamodb@3.190.0, ...

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.17.0

### Reproduction Steps

```
// V3
import { DynamoDBClient } from "@aws-sdk/client-dynamodb";

const ddbClient = new DynamoDBClient();

export { ddbClient };
console.log(await ddbClient.config.maxAttempts())
```

### Observed Behavior

Output
```
3
```

### Expected Behavior

SDK V2 - https://github.com/aws/aws-sdk-js/blob/1ca7b9894d72b01425852c079cb47e378e206886/lib/services/dynamodb.js#L44
```
 defaultRetryCount: 10,
```

**Comment by RanVaknin** [comment]
Hi @amdhing ,

Thanks for opening this issue, we appreciate you engaging in the community and trying to make the SDK better!

Since there is no bug here I changed the label to documentation. 
A similar request for documentation was already mentioned here #3611 , I will assign higher priority and let the engineers on the team know.

Thanks!
Ran

**Comment by trivikr** [comment]
Looks like the `defaultRetryCount` was manually added as a customization in v2 in commit https://github.com/aws/aws-sdk-js/commit/449413051d821f0453afc779042ad4d4a300e1af

The code search shows that it's only enabled for DynamoDB in v2 https://github.com/search?q=repo%3Aaws%2Faws-sdk-js%20defaultRetryCount&type=code

Since this value is not driven by configuration, the next steps would be to find whether the retry count is increased in other SDKs. If yes, a config driven solutions using a Smithy trait needs to be developed instead of adding a customization.

**Comment by RanVaknin** [comment]
@trivikr ,

In GO SDK v1 and v2 the default retry attempts for the standard retryer is 3.

We need to keep this as `needs-review` as a house keeping item to update the documentation for the Retryer.

**Comment by RanVaknin** [comment]
Hi @amdhing ,

the SDK v3 follows the cross SDK (newer SDK versions) convention of 3 max attempts. Im not sure why JS SDK v2 had 10, it might have been some customization that we are not going to carry over to v3. 

you can manually configure the max attempts if you wish. 

Thanks for your patience. 
Ran~

**Comment by amdhing** [comment]
Hi @RanVaknin 

Thanks for your response. Literally **every** aws sdk has a separate DynamoDB retry policy where the max retries are NOT 3. This is not just in JS SDK v2. For clarity, I am only sharing some other SDKs here.

My point is, no other AWS SDK except JS v3 SDK has max retries for DynamoDB clients at 3. If the following references are in fact the authoritative sources of DDB retry policies, this is clearly an oversight/miss when building the initial version of this JS SDK, and docs **must** mention this change, as SDK upgrades from v2 to v3 may degrade experience for DynamoDB customers.

10 in java-v1: https://github.com/aws/aws-sdk-java/blob/098550632a128cded122ddb10c20e620adc394b2/aws-java-sdk-core/src/main/java/com/amazonaws/retry/PredefinedRetryPolicies.java#L55
8 in java-v2: https://github.com/aws/aws-sdk-java-v2/blob/824e67058584721cc396d85bbbe3f48b2ce14d7d/services/dynamodb/src/main/java/software/amazon/awssdk/services/dynamodb/DynamoDbRetryPolicy.java#L39C50-L39C50

10 in go: https://github.com/aws/aws-sdk-go/blob/70cfeb89bfc667fa5c7b8e7575659d1f586e5b79/service/dynamodb/customizations.go#L30

10 in python: https://github.com/boto/botocore/blob/b92c6f66cbd269695125f090e21db4548d560237/botocore/data/_retry.json#L130

Happy to share more resources and references internally if needed.
