### ISSUE TITLE
AWS Node SDK support for Stream Transcriber

### ISSUE THREAD

**Issue by pietrop** [aws/aws-sdk-js-v3#405]
**Is your feature request related to a problem? Please describe.**

I was wondering if there are any plans to add support for the  AWS Stream Transcriber to the node SDK., to use on live streams, microphone etc..

**Describe the solution you'd like**

See [IBM Watson STT API reference for Recognize audio (WebSockets)](https://cloud.ibm.com/apidocs/speech-to-text/speech-to-text?code=node#recognize-audio-websockets-) for an example of how this could be done.

**Describe alternatives you've considered**

I have used the code from the [amazon-transcribe-websocket-static](https://github.com/aws-samples/amazon-transcribe-websocket-static) from the AWS amplify example. But it be great if it was part of the node SDK to make it easier and cleaner to integrate in future projects.

**Additional context**

I am aware there is already support for the ruby SDK, [Announcing Amazon Transcribe streaming transcription support in the AWS SDK for Ruby](https://aws.amazon.com/blogs/developer/announcing-amazon-transcribe-streaming-transcription-support-in-the-aws-sdk-for-ruby/)

**Comment by AllanFly120** [comment]
Close this issue as the package has been usable in https://www.npmjs.com/package/@aws-sdk/client-transcribe-streaming
