### ISSUE TITLE
Credential is missing for AssociateSoftwareTokenCommand 

### ISSUE THREAD

**Issue by francescreig** [aws/aws-sdk-js-v3#4062]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Hello,

I've been trying to implement software token association with AWS Cognito in a JavaScript application (built with React) but following the API Reference for that (this [guide](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-cognito-identity-provider/classes/associatesoftwaretokencommand.html)) whenever I try to execute the command I get
```javascript
Error: Credential is missing
    at SignatureV4.credentialProvider (runtimeConfig.browser.js:16)
    at SignatureV4.<anonymous> (SignatureV4.js:169)
    at step (tslib.es6.js:102)
    at Object.next (tslib.es6.js:83)
    at tslib.es6.js:76
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js:72)
    at SignatureV4.signRequest (SignatureV4.js:165)
    at SignatureV4.<anonymous> (SignatureV4.js:85)
    at step (tslib.es6.js:102)
```

Searching on other sites I think it my be something related to the `CognitoIdentityProviderClient`, the way it is configured (possibly on the `credentials` or `credentialsDefaultProvider`?, but on the documentation it is not explicitly said that it has to be configured in some way, just with
```javascript
const client = new CognitoIdentityProviderClient({ region: AWS_REGION });
```
Moreover, I also set send the session returned by `InitiateAuth` command from a user into the `AssociateSoftwareTokenCommand`, but I am not able to get successful response.

Actually, I also found the same exact issue on a StackOverflow post, describing the same: [post](https://stackoverflow.com/questions/70555636/error-credential-is-missing-for-associatesoftwaretokencommand-with-aws-cognitoi).

### SDK version number

@aws-sdk/client-cognito-identity-provider@3.180.0

### Which JavaScript Runtime is this issue in?

Browser

### Details of the browser/Node.js/ReactNative version

v16.14.0

### Reproduction Steps

Try to run this commands and see the output:
```javascript
const client = new CognitoIdentityProviderClient({ region: AWS_REGION });
const command = new AssociateSoftwareTokenCommand({Session: session });
const response = await client.send(command)
```
(Here session comes from the `InitiateAuthCommand` response)

### Observed Behavior

Stacktrace described before:
```javascript
Error: Credential is missing
    at SignatureV4.credentialProvider (runtimeConfig.browser.js:16)
    at SignatureV4.<anonymous> (SignatureV4.js:169)
    at step (tslib.es6.js:102)
    at Object.next (tslib.es6.js:83)
    at tslib.es6.js:76
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js:72)
    at SignatureV4.signRequest (SignatureV4.js:165)
    at SignatureV4.<anonymous> (SignatureV4.js:85)
    at step (tslib.es6.js:102)
```

### Expected Behavior

I expect to get the object with secret code and the session to use into `VerifySoftwareTokenCommand`.
```json
{
   "SecretCode": "string",
   "Session": "string"
}
```

### Possible Solution

It has to be something related with the `CognitoIdentityProviderClient`. Possibly on the Promise resolver of the `credentialsDefaultProvider`.

**Comment by RanVaknin** [comment]
Hi @francescreig ,

Sorry for the late response, this issue fell between the cracks.

You are getting this error because the SDK's credential chain will automatically look in a couple places to see if you have provided it valid AWS credentials, and if it doesn't find any it will throw this error.

The SDK will need valid credentials to then call `AssociateSoftwareTokenCommand`. From the looks of it, your client is never getting constructed with the credentials to begin with. 

Please refer to this [doc](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/setting-credentials-node.html), in particular [Loading credentials in Node.js from the shared credentials file](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/loading-node-credentials-shared.html).

Let me know if you have any other questions.
Thanks,
Ran~
