### ISSUE TITLE
Missed tslib dependency in @aws-sdk/types 3.199.0

### ISSUE THREAD

**Issue by koshic** [aws/aws-sdk-js-v3#4075]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Base tsconfig for cjs has importHelpers: true, so 'tslib' must be in dependencies for any compiled package:
https://github.com/aws/aws-sdk-js-v3/blob/f9bc7afd7af7535c0de8123d0820faa8ebec7e16/tsconfig.cjs.json#L3-L5

'types' package has no dependencies, only devDependencies:
https://github.com/aws/aws-sdk-js-v3/blob/f9bc7afd7af7535c0de8123d0820faa8ebec7e16/packages/types/package.json#L42-L49

It could be ok for types-only (in TS terms) package, but 'middleware-sdk-s3' imports EndpointURLScheme enum from 'types' package:
https://github.com/aws/aws-sdk-js-v3/blob/f9bc7afd7af7535c0de8123d0820faa8ebec7e16/packages/util-endpoints/src/lib/parseURL.ts#L1-L8

And yes, dist-cjs/index.js requires 'tslib':
<img width="691" alt="image" src="https://user-images.githubusercontent.com/20106607/197289095-d8893f11-fd61-4e7b-8ab2-7ba0fabb870f.png">

As a result, we have an error inside strict environment like Yarn PnP:
```console
@aws-sdk/types tried to access tslib, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
Required package: tslib
Required by: @aws-sdk/types@npm:3.193.0 (via <doesnt matter>/.yarn/cache/@aws-sdk-types-npm-3.193.0-3d57d20985-2979d25628.zip/node_modules/@aws-sdk/types/)
```

In my case stack trace begins from 's3-client'.

### SDK version number

3.194.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v19.0.0

### Reproduction Steps

yarn pnp, cjs, s3-client and SelectObjectContentCommand.

### Observed Behavior

'missed dependency'

### Expected Behavior

no error

### Possible Solution

add missed dependency to 'types' package

**Comment by dszczepaniak-cksource** [comment]
I can confirm the issue occurs for `@aws-sdk+types@3.193.0` as well

**Comment by lensbart** [comment]
Encountered the issue in `3.199.0`

**Comment by mhassan1** [comment]
This should be resolved by https://github.com/aws/aws-sdk-js-v3/pull/4128.
