### ISSUE TITLE
Error: The edge runtime does not support Node.js 'buffer' module

### ISSUE THREAD

**Issue by mattiaz9** [aws/aws-sdk-js-v3#4077]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

This library doesn't work in an edge runtime environment, because it uses modules/primitives that don't exist in an edge runtime.

Since edge functions are getting more and more popular, it'd be nice that this library supports it.

### SDK version number

@aws-sdk/client-s3@3.194.0, @aws-sdk/s3-request-presigner@3.194.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.9.0

### Reproduction Steps

Create a blank NextJS project and add this (example) api endpoint:
```ts
import type { PageConfig } from "next"
import type { NextRequest } from "next/server"
import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3"
import { getSignedUrl } from "@aws-sdk/s3-request-presigner"

import { env } from "@/env/server"

export default async function handle(req: NextRequest) {
  const filename = "test"

  const s3 = new S3Client({
    endpoint: env.STORAGE_ENDPOINT,
    region: "auto",
    credentials: {
      accessKeyId: env.STORAGE_ACCESS_KEY,
      secretAccessKey: env.STORAGE_SECRET_KEY,
    },
  })
  const command = new PutObjectCommand({
    Bucket: env.STORAGE_BUCKET_NAME,
    Key: filename,
  })

  const url = await getSignedUrl(s3, command, { expiresIn: 3600 })

  return new Response(JSON.stringify({ url }), { status: 200 })
}

export const config: PageConfig = {
  runtime: "experimental-edge",
}
```

### Observed Behavior

When I make the api call from the frontend I get this error:
```
error - Error: The edge runtime does not support Node.js 'buffer' module.
Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime
    at <unknown> (webpack-internal:///(middleware)/./node_modules/next/dist/server/web/adapter.js:172)
    at Object.get (webpack-internal:///(middleware)/./node_modules/next/dist/server/web/adapter.js:172:19)
    at eval (webpack-internal:///(middleware)/./node_modules/@aws-crypto/util/build/convertToBuffer.js:9:56)
    at (middleware)/./node_modules/@aws-crypto/util/build/convertToBuffer.js (evalmachine.<anonymous>:424:1)
    at __webpack_require__ (evalmachine.<anonymous>:37:33)
    at fn (evalmachine.<anonymous>:269:21)
    at eval (webpack-internal:///(middleware)/./node_modules/@aws-crypto/util/build/index.js:6:25)
    at (middleware)/./node_modules/@aws-crypto/util/build/index.js (evalmachine.<anonymous>:435:1)
    at __webpack_require__ (evalmachine.<anonymous>:37:33)
    at fn (evalmachine.<anonymous>:269:21)
    at eval (webpack-internal:///(middleware)/./node_modules/@aws-crypto/crc32/build/index.js:5:14)
```

### Expected Behavior

It should run in an edge environment.

### Possible Solution

Use only edge APIs: https://edge-runtime.vercel.app/features/available-apis

**Comment by LunaticMuch** [comment]
There's an interesting code snippet coming from https://github.com/vercel/next.js/issues/43115#issuecomment-1321785193

I created a quick [gist](https://gist.github.com/LunaticMuch/63696e2a001a292bd2c839c92941c10c) so I won't lose it

**Comment by timclark97** [comment]
I ran into this issue as well. My workaround was to use [aws4fetch](https://github.com/mhart/aws4fetch/tree/master), which is built using the native fetch and crypto primitives that most edge runtimes support. Requires a bit more research into how to interact with the underlining AWS API of whatever service you want to use, but works very well.

**Comment by leeonfield** [comment]
In case someone need, upgrade next.js version to @13.3.0 or above will fix this error
> refer to changelog: https://github.com/vercel/next.js/releases/tag/v13.3.0
> - provide Buffer polyfill to client and edge: https://github.com/vercel/next.js/pull/47610

**Comment by RanVaknin** [comment]
Hi,

We re-reviewed this as a team. AWS SDK only officially supports the Node.js runtime. 
The solution here would be for Edge Runtime to add `buffer` for the AWS SDK to work.
