### ISSUE TITLE
CloudWatch Logs Client -   StartQueryCommand() STRING_VALUE can not be converted to a Long.

### ISSUE THREAD

**Issue by igoralves1** [aws/aws-sdk-js-v3#4080]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I want to query CloudWatch using a Lambda in nodeJs (V16) deployed with Serverless.

I am using [CloudWatch Logs Client - AWS SDK for JavaScript v3](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-cloudwatch-logs/index.html), [StartQueryCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-cloudwatch-logs/classes/startquerycommand.html) and [GetQueryResultsCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-cloudwatch-logs/classes/getqueryresultscommand.html) methods. 

Since there is no a clear documentation on how to `GET LOGS FROM CLOUDWATCH USING NODEJS SDK V3` I am following some posts that are using `Boto3-Python` - [How to query cloudwatch logs using boto3 in python](https://stackoverflow.com/questions/59240107/how-to-query-cloudwatch-logs-using-boto3-in-python). 

Following the logic in that previous post, it seems that 1st we need to use the params (`{startTime : ..., endTime : ... , logGroupName : ... , queryString : ...}`) on `StartQueryCommand()` in order to get a `queryId`, based on the documentation and in the stackoverflow post, previous mentioned. Following the idea, we should use this `queryId` in the `GetQueryResultsCommand()` in order to get a result with the real response - the LOGS.

This is the code that I am using:

```
'use strict'

const { CloudWatchLogsClient, StartQueryCommand, GetQueryResultsCommand } = require("@aws-sdk/client-cloudwatch-logs")

const client = new CloudWatchLogsClient({ region: "us-east-1" });
console.log('🚀 CloudWatchLogsClient - client', client)

const getAllLogs = async (params) => {
    try {
        console.log('🚀 START getAllLogs')
      
        // Specified as epoch time, the number of seconds since January 1, 1970, 00:00:00 UTC
        // https://www.epochconverter.com/

        // https://stackoverflow.com/questions/59240107/how-to-query-cloudwatch-logs-using-boto3-in-python

        const startTime = '1664582400'
        const endTime = '1666569600'
        const logGroupName = 'aws/lambda/fnPublishMQTTCron-dev'
        const queryString = 'fields @timestamp, @message| sort @timestamp desc| limit 20'

        const input = {
            startTime : startTime,
            endTime : endTime,
            logGroupName : logGroupName,
            queryString : queryString
        }
        console.log('🚀 input', input)

        const command = new StartQueryCommand(input)
        console.log('🚀 command', command)
        const queryId = await client.send(command)
        console.log('🚀 response', queryId)
        // console.log('🚀 JSON.stringify()', JSON.stringify(queryId))
        
        
        const GetQueryResultsCommandId = new GetQueryResultsCommand(queryId);
        console.log('🚀 GetQueryResultsCommandId', GetQueryResultsCommandId)
        const GetQueryResultsCommandOutput = await client.send(GetQueryResultsCommandId);
        console.log('🚀 GetQueryResultsCommandOutput', GetQueryResultsCommandOutput)

    //   return JSON.stringify(response)
      return GetQueryResultsCommandOutput
    } catch (error) {
      console.log('🚀 getAllLogs - error.stack:', error.stack)
      return error.stack
    }
  }
```

When I make the request (I am using HTTPS GET), I get the following error as a result:

```
2022-10-24T18:24:13.126Z	1c74467c-b155-4152-a783-bd6b7ed0d50b	INFO	🚀 getAllLogs - error.stack: SerializationException: STRING_VALUE can not be converted to a Long
    at throwDefaultError (/var/task/node_modules/@aws-sdk/client-cloudwatch-logs/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at deserializeAws_json1_1StartQueryCommandError (/var/task/node_modules/@aws-sdk/client-cloudwatch-logs/dist-cjs/protocols/Aws_json1_1.js:1959:51)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /var/task/node_modules/@aws-sdk/client-cloudwatch-logs/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /var/task/node_modules/@aws-sdk/client-cloudwatch-logs/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20
    at async StandardRetryStrategy.retry (/var/task/node_modules/@aws-sdk/client-cloudwatch-logs/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /var/task/node_modules/@aws-sdk/client-cloudwatch-logs/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at async getAllLogs (/var/task/src/CloudWatch/CloudWatch.js:32:25)
    at async Runtime.module.exports.fnGetCloudWatch [as handler] (/var/task/src/CloudWatch/fnGetCloudWatch.js:9:22)

``` 

It is going in `catch (error)` showing some issue at the line `const queryId = await client.send(command)`.
Seems to be a `parse error` related to the `module` at `/var/task/node_modules/@aws-sdk/client-cloudwatch-logs/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22`. 

Does someone know how to solve this?

### SDK version number

@aws-sdk/package-name@version, V3

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Chrome latest version, MAC OS - Monterey 12.3

### Reproduction Steps

Run this endpoint `https://amgb2wd2rk.execute-api.us-east-1.amazonaws.com/dev/logs`

### Observed Behavior

Error

```
2022-10-24T18:24:13.126Z	1c74467c-b155-4152-a783-bd6b7ed0d50b	INFO	🚀 getAllLogs - error.stack: SerializationException: STRING_VALUE can not be converted to a Long
    at throwDefaultError (/var/task/node_modules/@aws-sdk/client-cloudwatch-logs/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at deserializeAws_json1_1StartQueryCommandError (/var/task/node_modules/@aws-sdk/client-cloudwatch-logs/dist-cjs/protocols/Aws_json1_1.js:1959:51)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /var/task/node_modules/@aws-sdk/client-cloudwatch-logs/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /var/task/node_modules/@aws-sdk/client-cloudwatch-logs/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20
    at async StandardRetryStrategy.retry (/var/task/node_modules/@aws-sdk/client-cloudwatch-logs/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /var/task/node_modules/@aws-sdk/client-cloudwatch-logs/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at async getAllLogs (/var/task/src/CloudWatch/CloudWatch.js:32:25)
    at async Runtime.module.exports.fnGetCloudWatch [as handler] (/var/task/src/CloudWatch/fnGetCloudWatch.js:9:22)
```

### Expected Behavior

Get a JSON response with all the logs from the test `logGroup`

### Possible Solution

Parse error somewhere,

### Additional Information/Context

AWS to put a functional piece os code on how to use the SDK. I can do this if needed.

**Comment by RanVaknin** [comment]
Hi @igoralves1 ,

I'd like to address a few points:

>Since there is no a clear documentation on how to GET LOGS FROM CLOUDWATCH USING NODEJS SDK V3

It is impossible to include a code example for each operation on the SDK, it's simply too big and unmaintainable. 

**Regarding the issue at hand:**

Right off the bat I see a few issues with your code. The most noticable one and the reason you are running into the `STRING_VALUE can not be converted to a Long` error is that both `startTime` and `endTime` are of type number and you setting the input as a string. Per the [official docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-cloudwatch-logs/interfaces/startquerycommandinput.html#starttime):
<img width="682" alt="image" src="https://user-images.githubusercontent.com/50976344/197641056-ab4f8578-e14e-4e7c-b30d-413966930913.png">

Additionally, you will run into more issues here:

```js
        const queryId = await client.send(command)
        console.log('🚀 response', queryId)
        // console.log('🚀 JSON.stringify()', JSON.stringify(queryId))
        
        
        const GetQueryResultsCommandId = new GetQueryResultsCommand(queryId);
        // ^ this input is set incorrectly and will most likely throw an error when supplied to the request. queryId in this case is poorly named.
        // It should be something like :
        // new GetQueryResultsCommand(queryId.queryId). consider renaming this variable to something like "data" or "response"
        
        // like:
        // const data = await.client.send(command)
        // const GetQueryResultsCommandId = new GetQueryResultsCommand(data.queryId);
        
        console.log('🚀 GetQueryResultsCommandId', GetQueryResultsCommandId)
        const GetQueryResultsCommandOutput = await client.send(GetQueryResultsCommandId);
        console.log('🚀 GetQueryResultsCommandOutput', GetQueryResultsCommandOutput)
```

Let me know if this helps.
Thanks,
Ran~

**Comment by RanVaknin** [comment]
@igoralves1 ,

>After your help it took me some hrs doing reverse eng with SDK V2 to finally realize that I should pass a json {queryId: 'theQueryId' } to the GetQueryResultsCommand() and not an actual string queryId.

You need only to read the docs and see what each method takes in and what it returns.
It takes a JS object per [the documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-athena/interfaces/getqueryresultscommandinput.html).

Every command in the SDK for example: `getSomethingCommand` will take a JS object of type `getSomethingCommandInput` as input, and return a JS object as output in the same convention `getSomethingCommandOutput`

If you are having a hard time figuring out the input types consider using TypeScript or other non-dynamically typed language. It was created for this exact situation. Javascript has no type assertion so it "allows" you to input whatever wherever and the debug errors are not always helpful.

Here is an example of how type assertion can help 
<img width="735" alt="image" src="https://user-images.githubusercontent.com/50976344/197873272-fd74cddd-2f3f-4c38-9ada-b7b59a26b65c.png">


Good luck,
Ran~
