### ISSUE TITLE
@aws-sdk/client-s3: HeadObjectOutput is missing some fields

### ISSUE THREAD

**Issue by JacopoBonta** [aws/aws-sdk-js-v3#4088]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The `HeadObject` request doesn't return some information such as the `VersionId`.

The information is present inside the response header (`x-amz-version-id`) but then is undefined in the `HeadObjectCommandOutput` object response.

### SDK version number

@aws-sdk/client-s3@3.171.0

### Which JavaScript Runtime is this issue in?

Browser

### Details of the browser/Node.js/ReactNative version

Chrome: 106.0.5249.119

### Reproduction Steps

It's easy to reproduce the issue as it is sufficient to perform a HEAD request using the SDK.

Here is a snippet of my code, where we build the command, send it, and print out the result:
```
const head_command = new HeadObjectCommand({
    Bucket: 'versioned',
    Key: 'file-9',
});

const result = await S3Client.client.send(head_command);

console.debug(JSON.stringify(result, null, 2));
```

### Observed Behavior

_Output_
```
{
  "$metadata": {
    "httpStatusCode": 200,
    "attempts": 1,
    "totalRetryDelay": 0
  },
  "LastModified": "2022-10-25T13:18:33.000Z",
  "ContentLength": 22,
  "ContentType": "application/octet-stream",
  "Metadata": {}
}
```

Here you can see the response headers, note for example, the `x-amz-version-id`, which is present but missing in the above output:

<img width="430" alt="Screenshot 2022-10-25 at 15 19 48" src="https://user-images.githubusercontent.com/9072396/197784401-edf7522e-6a08-432d-9042-7f8dea96a84e.png">

### Expected Behavior

I expect to see the headers value inside the response object as if I'm making the request using the CLI.

For example, performing a `head-object` using the CLI, the `VersionId` and `ETag` values get returned correctly.

```
$ aws s3api head-object --bucket versioned --key file-9
{
    "LastModified": "2022-10-25T13:18:33+00:00",
    "ContentLength": 22,
    "ETag": "\"ef61c9cc933635ec4a6472ed0b840451\"",
    "VersionId": "03395ff4-f4a1-4184-88f5-4022d8112e35",
    "ContentType": "application/octet-stream",
    "Metadata": {}
}
```

**Comment by RanVaknin** [comment]
Hi @JacopoBonta ,

I'm not sure why you are experiencing this. I'm able to run `headObject` just fine:

```js
import { S3Client, HeadObjectCommand } from '@aws-sdk/client-s3'; // version: ^3.196.0"

const client = new S3Client({ region: 'us-east-1' });

const command = new HeadObjectCommand({
    Bucket: myBucket,
    Key: myKey
});

try {
    const data = await client.send(command);
    console.log(data)
} catch (error) {
    console.log(error);
}
```
outputs:

```js
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'redacted',
    extendedRequestId: 'redacted',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  AcceptRanges: 'bytes',
  LastModified: 2022-10-25T19:37:46.000Z,
  ContentLength: 13,
  ETag: 'redacted',
  VersionId: 'y7e2RlK7_vmHRsGwiK3zsS2hW73KC6wE',
  ContentType: 'text/plain',
  Metadata: {}
}
```

I see you are using an older version. I suggest you pull the latest version of `@aws-sdk/client-s3`.
Does that help at all?

Thanks,
Ran~

**Comment by JacopoBonta** [comment]
Thanks for looking into this, Ran.
I have just tried updating the library to version `3.196.0` and still got the error, but I discovered that it only happens on my webapp - the same request performed from a Node.js script works by returning everything as expected.

**Comment by RanVaknin** [comment]
Hi @JacopoBonta 
Can you check your CORS configuration to allow headers?

Thanks,
Ran

**Comment by kuhe** [comment]
https://docs.aws.amazon.com/AmazonS3/latest/userguide/enabling-cors-examples.html

**Comment by JacopoBonta** [comment]
Thanks for the suggestion, it turns out it was an issue with headers not being exposed so in the browser they were ignored.

Using Localstack for example, fixing the issue was a matter to allow the header and then expose it, like this:

```
docker run --rm -d -it -p 9146:9146 -p 4510-4559:4510-4559 -e "DISABLE_CORS_CHECKS=1" -e "LOCALSTACK_EDGE_PORT=9146" -e "EXTRA_CORS_ALLOWED_HEADERS=ETag,x-amz-version-id" -e "EXTRA_CORS_EXPOSE_HEADERS=ETag,x-amz-version-id" localstack/localstack:0.14.5
```

Thanks again for your support! I'll close this as this is not a bug affecting this library.
