### ISSUE TITLE
Allow to create anonymous client

### ISSUE THREAD

**Issue by yenfryherrerafeliz** [aws/aws-sdk-js-v3#4093]
### Describe the feature

Sometimes, you need to create an AWS client that is not associated to any credentials in order to access some services such as S3 and CloudSearch, which allow anonymously access. For example, you may need to download an object in a bucket that is publicly readable.

With PHP we do the following to create an anonymous client:
- Docs [here](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_anonymous.html)

```php
$s3Client = new S3Client([
    'version'     => 'latest',
    'region'      => 'us-west-2',
    'credentials' => false
]);
```

### Use Case

To interact with some AWS services that allow anonymously access such as S3 and CloudSearch.  

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.194.0

### Environment details (OS name and version, etc.)

nodejs

**Comment by trivikr** [comment]
Action item for this task:
* Find what decides the ability to create Anonymous client. For example, it might be a trait in smithy model. Use AWS SDK for PHP as a reference
* For the clients which have this hint, implement a way to make authentication optional.

**Comment by trivikr** [comment]
Re-adding needs-triage to gather following data:
* Do SDKs other than PHP provide this feature of anonymous clients?
* What's the customer use case for this feature? Share some examples.

**Comment by yenfryherrerafeliz** [comment]
Hi @trivikr, thanks for taking a look to this.

> Do SDKs other than PHP provide this feature of anonymous clients?

Yes, as of right now I know [java does](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/AnonymousAWSCredentials.html).
> What's the customer use case for this feature? Share some examples.

The use case is explicitly said in the description:
> Sometimes, you need to create an AWS client that is not associated to any credentials in order to access some services such as S3 and CloudSearch, which allow anonymously access. For example, you may need to download an object in a bucket that is publicly readable.

An example is a bucket that is public and does not require authentication in order to interact with it.

Thanks!

**Comment by trivikr** [comment]
@yenfryherrerafeliz Please share examples where users requested for this feature.

We couldn't find any in the GitHub issue description.

**Comment by yenfryherrerafeliz** [comment]
@trivikr [here](https://github.com/aws/aws-sdk-js-v3/issues/2321) is an old feature request for this.

**Comment by mrclay** [comment]
FYI the V2 workaround works here, too: https://github.com/aws/aws-sdk-js-v3/issues/2321#issuecomment-916336230

**Comment by ConnorBrennan** [comment]
We are trying to use the JS SDK to provide citizens with access to public files, and the inability to perform anonymous requests is making it much more difficult.  The City of Denver would definitely appreciate this feature being implemented!

**Comment by unphased** [comment]
the workaround is NOT WORKING somewhere between `@aws-sdk/client-s3` `v3.620` and `v3.637`!!! Can someone shed light on this please.

**Comment by kuhe** [comment]
What is the error message?

Does this work if you provide a mock set of credentials?

```ts
import { S3 } from "@aws-sdk/client-s3";

const s3 = new S3({
  region: "us-west-2",
  credentials: {
    secretAccessKey: "MOCK",
    accessKeyId: "MOCK",
  },
  signer: {
    async sign(req) {
      return req;
    }
  }
});
```

**Comment by esdandreu** [comment]
```ts
const client =  new S3({
    region,
    signer: {
        async sign(req) {
            return req;
        },
    },
});
```
This client fails to do
```ts
const response = await client.listObjectsV2({ Bucket });
```
With
```
CredentialsProviderError: Could not load credentials from any providers
```
Being the bucket public and having a permissive policy. But @kuhe 's [suggestion](https://github.com/aws/aws-sdk-js-v3/issues/4093#issuecomment-2332449392)
```ts
const client =  new S3({
    region,
    credentials: { accessKeyId: "", secretAccessKey: "" },
    signer: {
        async sign(req) {
            return req;
        },
    },
});
```
Does succeed!

It can be abstracted to **try** to use an authenticated client while falling back to an unauthenticated one
```ts
async function getS3Client(region: string): Promise<S3> {
    try {
        // Attempt to get credentials using the default provider chain.
        const credentials = await defaultProvider()();
        return new S3({ region, credentials });
    } catch (error) {
        if (error.name === "CredentialsProviderError") {
            // Fallback to unauthenticated S3 client.
            return new S3({
                region,
                credentials: { accessKeyId: "", secretAccessKey: "" },
                signer: { sign: async req => req },
            });
        }
        throw error;
    }
}
```
