### ISSUE TITLE
Unexpected empty auth scheme config

### ISSUE THREAD

**Issue by EntePF** [aws/aws-sdk-js-v3#4094]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

After upgrading to sdk version 3.195.0 my Lambdas fail with "Unexpected empty auth scheme config" when trying to access secrets or putting events.

### SDK version number

@aws-sdk/client-secrets-manager@3.195.0, @aws-sdk/client-cloudwatch-events@3.195.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node.js 16.x

### Reproduction Steps

Use this in a Lambda:
```
await new SecretsManagerClient({
    region: process.env.AWS_REGION,
  }).send(new GetSecretValueCommand({
    SecretId: secretId,
  }));
```
or
```
await new CloudWatchEventsClient({
    region: process.env.AWS_REGION,
  }).send(new PutEventsCommand({
    Entries: [{
      Source: 'someSource',
      DetailType: 'someType',
      Detail: JSON.stringify({
        type: 'info',
      }),
    }],
  }));
```

### Observed Behavior

```
ERROR	Invoke Error 	{
    "errorType": "Error",
    "errorMessage": "Unexpected empty auth scheme config",
    "$metadata": {
        "attempts": 1,
        "totalRetryDelay": 0
    },
    "stack": [
        "Error: Unexpected empty auth scheme config",
        "    at Object.signer (/var/task/index.js:3255:19)",
        "    at /var/task/index.js:3370:36",
        "    at StandardRetryStrategy.retry (/var/task/index.js:2205:48)",
        "    at async /var/task/index.js:1459:24",
        "    at async Runtime.handler (/var/task/index.js:37654:22)"
    ]
}
```

### Expected Behavior

No error to be thrown and Lambda execution role to be used.

### Possible Solution

The error does not happen in 3.194.0. I had to downgrade all sdk packages I use.

### Additional Information/Context

The Lambdas are compiled using NodejsFunction (aws-cdk-lib@2.45.0 and esbuild@0.15.12).

**Comment by kuhe** [comment]
Could you check what version of `@aws-sdk/middleware-signing` you had installed? It is a dependency of the various client packages. 

The error you encountered is in `3.188.0` of middleware-signing, but if you update your packages to all be at 3.195.0 it should not occur.

**Comment by EntePF** [comment]
I checked the package-lock and indeed I had 3.186.0 installed transitively due to a peer dependency of `"@aws-sdk/client-codeartifact": "^3.183.0"`. I guess that was just an issue with my registry not pulling a newer version, because after forcing `^3.190.0` once just one version was installed.

After this the correct update the Lambdas work fine, thank you very much :)
