### ISSUE TITLE
@aws-sdk/client-s3: exception while calling s3 with unknown operation: Unable to find operation for request to service s3: PUT /

### ISSUE THREAD

**Issue by ryanbeaz** [aws/aws-sdk-js-v3#4103]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Running into an internal error when trying to create an S3 bucket.

### SDK version number

@aws-sdk/client-s3@3.196.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.17.1

### Reproduction Steps

```
const client = new S3Client({
     endpointProvider: () => ({url: new URL('http://localhost:4566')}),
     forcePathStyle: true, // i tried toggling this...no luck
});

const input = {Bucket: 'test'};
const command = new CreateBucketCommand(input);
await client.send(command);
```

Same thing happens if I specify the endpoint as a string:

```
const client = new S3Client({
     endpoint: 'http://localhost:4566', // this worked in @aws-sdk/client-s3@3.190.0
     forcePathStyle: true,
});

const input = {Bucket: 'test'};
const command = new CreateBucketCommand(input);
await client.send(command);
```

### Observed Behavior

```
exception while calling s3 with unknown operation: Unable to find operation for request to service s3: PUT /
InternalError: exception while calling s3 with unknown operation: Unable to find operation for request to service s3: PUT /
```

### Expected Behavior

Bucket to have been created successfully.

**Comment by kuhe** [comment]
I tried version 3.196.0 and its contemporary packages and wasn't able to reproduce this issue. 

Can you post the output of this endpoint resolution test?

```js
import { S3, CreateBucketCommand } from "@aws-sdk/client-s3"; // or require
import { getEndpointFromInstructions } from "@aws-sdk/middleware-endpoint"; // or require

const client = new S3({
    endpoint: "http://localhost:4566",
    forcePathStyle: true,
});

console.log(
  await getEndpointFromInstructions(
    { Bucket: "test" }, 
    CreateBucketCommand, 
    client.config
  )
);
```

I get this:
```
{
  headers: {},
  properties: { authSchemes: [ [Object] ] },
  url: URL {
    href: 'http://localhost:4566/test',
    origin: 'http://localhost:4566',
    protocol: 'http:',
    username: '',
    password: '',
    host: 'localhost:4566',
    hostname: 'localhost',
    port: '4566',
    pathname: '/test',
    search: '',
    searchParams: URLSearchParams {},
    hash: ''
  }
}
```
which is the correct path to PUT for a createBucket operation.

**Comment by ryanbeaz** [comment]
@kuhe I get this 
<img width="364" alt="Screen Shot 2022-10-26 at 4 44 17 PM" src="https://user-images.githubusercontent.com/10524468/198144405-75cdccf7-3a94-4cd9-8020-d2e8d1534167.png">

**Comment by ryanbeaz** [comment]
@kuhe i think it worked: 

```
console.log
    {
      headers: {},
      properties: { authSchemes: [ [Object] ] },
      url: URL {
        href: 'http://localhost:4566/test',
        origin: 'http://localhost:4566',
        protocol: 'http:',
        username: '',
        password: '',
        host: 'localhost:4566',
        hostname: 'localhost',
        port: '4566',
        pathname: '/test',
        search: '',
        searchParams: URLSearchParams {},
        hash: ''
      }
    }
    ```

**Comment by ryanbeaz** [comment]
Configuration issue on our end...sorry for the wasted time. Thank you for the help!
