### ISSUE TITLE
Write to SQS fails with o.config.endpoint is not a function

### ISSUE THREAD

**Issue by rcoundon** [aws/aws-sdk-js-v3#4105]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

We attempted to upgrade our TypeScript lambda function to version  3.197.0 from 3.190.0 but have encountered a problem. When writing to an SQS FIFO queue with the AWS SDK bundled using esbuild, the SDK throws an error which states only:
```o.config.endpoint is not a function```

This happens in the latest version 3.197.0, reverting to 3.190.0 stops the error from happening and the message is written correctly.

### SDK version number

@aws-sdk/client-sqs@3.197.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

16.16.0

### Reproduction Steps

```ts
async writeMessage() {
  try {
    const sqsClient = new SQSClient({ region: process.env.REGION });
    const command = new SendMessageCommand({
      MessageBody: 'some message',
      QueueUrl: process.env.QUEUE_URL,
      MessageGroupId: 'group1',
  });
  await sqsClient.send(command);
  } catch (err) {
    console.log(JSON.stringify(err));
  }
}
```

### Observed Behavior

An error is thrown with message:

o.config.endpoint is not a function

### Expected Behavior

No error and message is written to the queue

**Comment by kuhe** [comment]
I'm not able to reproduce this issue. Could you set up a small repo that shows this? 
Also please include your stack trace.

It could be that you have some other packages in the `@aws-sdk` scope that are not at the same version.

**Comment by rcoundon** [comment]
I'll try to create a reproduction. In the meantime, this is the `package.json`
```json
    "@aws-cdk/aws-apigatewayv2-alpha": "2.39.1-alpha.0",
    "@aws-sdk/client-dynamodb": "3.197.0",
    "@aws-sdk/client-s3": "3.197.0",
    "@aws-sdk/client-sqs": "3.197.0",
    "@aws-sdk/client-ssm": "3.197.0",
    "@aws-sdk/lib-dynamodb": "3.197.0",
    "@aws-sdk/s3-request-presigner": "3.197.0",
    "@aws-sdk/types": "3.197.0",
    "@aws-sdk/util-dynamodb": "3.197.0",
```

Stack trace looks like this:

```
 "    at /opt/nodejs/node_modules/@thundra/core/dist/thundra.js:1:243218")
        "    at processTicksAndRejections (node:internal/process/task_queues:96:5)")
        "    at null.<anonymous> (/node_modules/@aws-sdk/middleware-serde/dist-es/deserializerMiddleware.js:2:26)")
        "    at null.<anonymous> (/node_modules/@aws-sdk/middleware-signing/dist-es/middleware.js:10:20)")
        "    at StandardRetryStrategy.retry (/node_modules/@aws-sdk/middleware-retry/dist-es/StandardRetryStrategy.js:47:46)")
        "    at async /opt/nodejs/node_modules/@thundra/core/dist/thundra.js:1:242926")
        "    at null.<anonymous> (/node_modules/@aws-sdk/middleware-sdk-sqs/dist-es/send-message-batch.js:3:18)")
        "    at null.<anonymous> (/node_modules/@aws-sdk/middleware-logger/dist-es/loggerMiddleware.js:3:22))
```

**Comment by 1oglop1** [comment]
@kuhe I have the same issue with RDS `CopyDBSnapshotCommand` during the cross-region copy, the source of the problem is coming from here: https://github.com/aws/aws-sdk-js-v3/blob/5b4e72127841a2071065e3f7780723ee4469dec9/packages/middleware-sdk-rds/src/index.ts#L57

the `options` object looks different from the interface defined in the file.

I tried this with the version `3.198.0` and same as OP the version `3.190.0` does not have the problem

**Comment by kuhe** [comment]
I opened PR #4120 to fix the bug in RDS, but I will most likely need more information for the original SQS issue.

The RDS bug, while it has the same error name as the reported one for SQS, happens in code that is specific to RDS.

**Comment by rcoundon** [comment]
I'm struggling to create a reproduction in a dedicated, separate project. Maybe it's helpful, I'm seeing a similar problem in the repo that has the issue with a GetItem request from DynamoDB. The actual error message there is:
```
2022-10-28T22:04:48.334Z	d3299f58-8793-4fe0-8aaa-08fb7bf5bb7b	ERROR	Invoke Error 	
{
    "errorType": "OneTableError",
    "errorMessage": "OneTable execute failed \"get\" for \"InventoryEventSubscriptionModel. o.config.endpoint is not a function",
    "code": "TypeError",
    "name": "OneTableError",
    "context": {
        "err": {
            "errorType": "TypeError",
            "errorMessage": "o.config.endpoint is not a function",
            "$metadata": {
                "attempts": 1,
                "totalRetryDelay": 0
            },
            "stack": [
                "TypeError: o.config.endpoint is not a function",
                "    at /opt/nodejs/node_modules/@thundra/core/dist/thundra.js:1:244065")
                "    at null.<anonymous> (/node_modules/@aws-sdk/middleware-serde/dist-es/deserializerMiddleware.js:2:26)")
                "    at null.<anonymous> (/node_modules/@aws-sdk/middleware-signing/dist-es/middleware.js:10:20)")
                "    at StandardRetryStrategy.retry (/node_modules/@aws-sdk/middleware-retry/dist-es/StandardRetryStrategy.js:47:46)")
                "    at async /opt/nodejs/node_modules/@thundra/core/dist/thundra.js:1:243773")
                "    at null.<anonymous> (/node_modules/@aws-sdk/middleware-logger/dist-es/loggerMiddleware.js:3:22))
            ]
        },
        "trace": {
            "model": "InventoryEventSubscriptionModel",
            "cmd": {
                "TableName": "xxxxxxxx-ariston-plugins-backend-ofs-events-table",
                "Key": {
                    "PK": {
                        "S": "INVENTORY_SUBSCRIPTION"
                    },
                    "SK": {
                        "S": "INVENTORY_SUBSCRIPTION"
                    }
                },
                "ConsistentRead": false
            },
            "op": "get",
            "properties": {
                "PK": "INVENTORY_SUBSCRIPTION",
                "SK": "INVENTORY_SUBSCRIPTION"
            }
        }
    },
    "date": "2022-10-28T22:04:47.693Z",
    "stack": [
        "OneTableError: OneTable execute failed \"get\" for \"InventoryEventSubscriptionModel. o.config.endpoint is not a function",
        "    at Table.execute (/node_modules/dynamodb-onetable/dist/mjs/Table.js:615:23)")
        "    at Model.run (/node_modules/dynamodb-onetable/dist/mjs/Model.js:331:22)")
        "    at Model.get (/node_modules/dynamodb-onetable/dist/mjs/Model.js:574:16)")
        "    at Function.getInventoryEventsPage (/src/main/transit/db/ofsEventsTable/InventoryEventsDao.ts:6:22)")
        "    at null.processInventoryEvents (/src/main/service/resourceInventory/resourceInventoryService.ts:59:24)")
        "    at null.handleInventoryEvents (/src/main/handlers/resourceInventory/resourceInventoryHandler.ts:49:3))
    ]
}
```

When trying to reproduce I've included both `dynamodb-onetable` and `@thundra/core` but still no joy.
One thing I do see is that the version of the @aws-sdk/* inside dynamodb-onetable is set to 
```
        "@aws-sdk/client-dynamodb": "^3.188.0",
        "@aws-sdk/util-dynamodb": "^3.188.0"
```
So maybe there's a conflict in certain circumstances but the curious thing is, as I said, if I apply this in a dedicated repo, it doesn't happen. I'll carry on trying

**Comment by mitsuru-kasai** [comment]
I got the same error with `cognito-identity-provider` client of version `3.194.0`.
I didn't get with one of version `3.193.0`.

Minimum reproduction code is this.

```typescript
import { CognitoIdentityProviderClient } from '@aws-sdk/client-cognito-identity-provider'

const cognito = new CognitoIdentityProviderClient({})

cognito.config.endpoint().then((endpoint) => console.log(endpoint))
```

Execution
```
$ npx ts-node src/scripts/test.ts 
```

Error log
```
/code/src/scripts/test.ts:5
cognito.config.endpoint().then((endpoint) => console.log(endpoint))
               ^
TypeError: cognito.config.endpoint is not a function
    at Object.<anonymous> (/code/src/scripts/test.ts:5:16)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module.m._compile (/code/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Object.require.extensions.<computed> [as .ts] (/code/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Function.Module._load (node:internal/modules/cjs/loader:838:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at phase4 (/code/node_modules/ts-node/src/bin.ts:649:14)
    at bootstrap (/code/node_modules/ts-node/src/bin.ts:95:10)
```

**Comment by mitsuru-kasai** [comment]
FYI;
It seems to work with giving an endpoint option when initializing.

for example, this code works.

```typescript
// /code/src/scripts/test.ts 
import { CognitoIdentityProviderClient } from '@aws-sdk/client-cognito-identity-provider'

const cognito = new CognitoIdentityProviderClient({
  endpoint: "http://example.com"
})

cognito.config.endpoint().then((endpoint) => console.log(endpoint))
```

Result
```
{
  hostname: 'example.com',
  port: undefined,
  protocol: 'http:',
  path: '/',
  query: undefined
}
```

**Comment by mitsuru-kasai** [comment]
I found the potential code.

In `3.193`, the function `() => getEndpointFromRegion(...)` is set as default value of config.endpoint if config.endpoint is not set.
https://github.com/aws/aws-sdk-js-v3/blob/v3.193.0/packages/config-resolver/src/endpointsConfig/resolveEndpointsConfig.ts#L57-L59

But now, undefined is set as default value of config.endpoint.
https://github.com/aws/aws-sdk-js-v3/blob/47ca922276bc9cfb22076af79b8b1db4fd43abed/packages/middleware-endpoint/src/resolveEndpointConfig.ts#L88

**Comment by kuhe** [comment]
`resolveEndpointsConfig` and `getEndpointFromRegion` are no longer used in client packages with the latest versions. 

client.config.region is no longer set automatically, see https://github.com/aws/aws-sdk-js-v3/issues/4122.

**Comment by mitsuru-kasai** [comment]
@kuhe 
Thank you so much!

And I'm sorry for confusing this issue.
My case seemed to be irrelevant the @rcoundon 's original problem.
