### ISSUE TITLE
Location field in Upload utility in lib-storage is wrong

### ISSUE THREAD

**Issue by yoniheib** [aws/aws-sdk-js-v3#4109]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The calculated Location field (based on Bucket and endpoint) is wrong.

In this line: https://github.com/aws/aws-sdk-js-v3/blob/d600213292eb1bea870c43420367f78406db1c82/lib/lib-storage/src/Upload.ts#L158
The locationBucket is appended with endpoint.hostname, but endpoint.hostname already contains the bucket.
This causes the locationBucket to appear twice and creates an invalid URI.

### SDK version number

@aws-sdk/lib-storage@3.197.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node.JS 16

### Reproduction Steps

I used the example for the lib-storage library and the Location field was wrong.

### Observed Behavior

For bucket name: test-bucket-staging

Location field is:
https://test-bucket-staging.test-bucket-staging.s3.us-west-1.amazonaws.com/test-image.jpeg

### Expected Behavior

For bucket name: test-bucket-staging

I would expect the field to be:
https://test-bucket-staging.s3.us-west-1.amazonaws.com/test-image.jpeg

### Possible Solution

I'm assuming that only endpoint.hostname should be used, but unsure about the other possible implications of this change.

**Comment by RanVaknin** [comment]
Hi @yoniheib ,

Can you include your code? 

Thanks,
Ran~

**Comment by yoniheib** [comment]
Sure:

`import {
  S3Client, 
  type CompleteMultipartUploadCommandOutput
} from '@aws-sdk/client-s3';
import { Upload } from '@aws-sdk/lib-storage';
const s3 = new S3Client({ region: 'us-west-1' });

const S3DefaultUploadParams = {
  Bucket: process.env.AWS_S3_BUCKET as string,
  ACL: 'public-read',
};

export async function uploadFileToS3()
 {
  const params = {
    ...S3DefaultUploadParams,
    Key: 'test',
    Body: 'TEST',
  };
  const upload = new Upload({ client: s3, params});
  const result = await upload.done() as CompleteMultipartUploadCommandOutput;
  console.log(result.Location);
  
  return result.Location;
};`

When I run this the Location value is:
https://<BUCKET_NAME>.<BUCKET_NAME>.s3.us-west-1.amazonaws.com/test

**Comment by RanVaknin** [comment]
Hi @yoniheib ,

I'm able to confirm that this is incorrect behavior. Will assign it to the dev team to fix.

Thanks!
Ran~

**Comment by wallind** [comment]
I also just ran into it on [3.198.0](https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.198.0)

**Comment by wallind** [comment]
not gonna pretend to be qualified on the full implications of the setting but `forcePathStyle` seems to fix the issue at least for a simple photo upload use-case.

```typescript
// define a shared client for the various functions
const s3Client = new S3Client({
        ...otherConfig
        
	forcePathStyle: true,
})
```

result:

```
I20221027-22:17:20.922(-4)? result {
I20221027-22:17:20.924(-4)?   '$metadata': {
I20221027-22:17:20.925(-4)?     httpStatusCode: 200,
I20221027-22:17:20.925(-4)?     requestId: 'P2NSBZVXDT753M3H',
I20221027-22:17:20.926(-4)?     extendedRequestId: 'SvMrs1RmhlO4YcPMN5glkprdNnV+TqI1Ksp8rIqeNBknLPoiZKD81lCISzavhZtbariJ20nmRc8=',
I20221027-22:17:20.927(-4)?     cfId: undefined,
I20221027-22:17:20.927(-4)?     attempts: 1,
I20221027-22:17:20.928(-4)?     totalRetryDelay: 0
I20221027-22:17:20.929(-4)?   },
I20221027-22:17:20.929(-4)?   ETag: '"cdd1701eccfcab7ecdbb5f9b136af71f"',
I20221027-22:17:20.929(-4)?   Bucket: 'kbi-dev-photo-uploads',
I20221027-22:17:20.930(-4)?   Key: 'uploads/profileImages/1666923440713',
I20221027-22:17:20.930(-4)?   Location: 'https://s3.us-east-2.amazonaws.com/kbi-dev-photo-uploads/uploads/profileImages/1666923440713'
I20221027-22:17:20.931(-4)? }
```

https://s3.us-east-2.amazonaws.com/kbi-dev-photo-uploads/uploads/profileImages/1666923440713. The URL format is a bit different than I'm used to but it renders my image so yeah seems like a temporary workaround.
