### ISSUE TITLE
EvalError: Code generation from strings disallowed for this context

### ISSUE THREAD

**Issue by subhendukundu** [aws/aws-sdk-js-v3#4112]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

This library doesn't work in an edge runtime environment with `esbuild`.

### SDK version number

@cloudflare/workers-types@3.18.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Cloudflare Edge functions

### Reproduction Steps

```
import { SNSClient, PublishCommand } from "@aws-sdk/client-sns";
const params = {
  Message: "Cool message",
  PhoneNumber: phoneWithCountry,
};
const command = new PublishCommand(params);

try {
  const data = await client.send(command);
  console.log("[success send]", data);
} catch(e) {
   console.log(e);
}
```

### Observed Behavior

https://community.cloudflare.com/t/evalerror-code-generation-from-strings-disallowed-for-this-context/356430

### Expected Behavior

IIt should run.

### Possible Solution

Maybe not using eval or new Function.

**Comment by kuhe** [comment]
Latest versions of this SDK no longer use `new Function`. A fix was merged in https://github.com/aws/aws-sdk-js-v3/pull/4136

**Comment by subhendukundu** [comment]
Yes, verified as fixed. Thanks
