### ISSUE TITLE
Credential Provider from JSON file

### ISSUE THREAD

**Issue by AllanZhengYP** [aws/aws-sdk-js-v3#412]
**Is your feature request related to a problem? Please describe.**
The V3 doesn't have an quivalent to [JSON file credential provider](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-json-file.html). We should have an quivalent in V3

**Describe the solution you'd like**
Desbribed in [this doc](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-json-file.html)

**Comment by RanVaknin** [comment]
We will revisit this issue if we got more requests from customers.
