### ISSUE TITLE
@aws-sdk/client-polly 3.200.0 Error

### ISSUE THREAD

**Issue by MichaelWalker-git** [aws/aws-sdk-js-v3#4133]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The 3.200.0 release creates a browser side error when compiling:

```
./node_modules/@aws-sdk/client-polly/node_modules/@aws-sdk/property-provider/dist-es/chain.js 10:16
Module parse failed: Unexpected token (10:16)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     for (const provider of providers) {
|       promise = promise.catch(err => {
>         if (err?.tryNextLink) {
|           return provider();
|         }

```

### SDK version number

@@aws-sdk/client-polly@3.200.0

### Which JavaScript Runtime is this issue in?

Browser

### Details of the browser/Node.js/ReactNative version

v18.4.0

### Reproduction Steps

Running this inside a React/ Amplify application.

```yarn start```

Commenting out the import for (@aws-sdk/client-polly) leads to no errors while compiling.

### Observed Behavior

Breaking compilation

### Expected Behavior

Renders webpage

**Comment by koshic** [comment]
@MichaelWalker-git your toolchain (or some config) is outdated - old babel / webpack / etc. Optional chaining supported from Node 14 - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#browser_compatibility, so from Node & SDK standpoint it's a 100% valid javascript code.

**Comment by yenfryherrerafeliz** [comment]
Hi @MichaelWalker-git, thanks for opening this issue. What @koshic said make sense to me. I tried to reproduce the reported error by doing the following:
- Created a react app:
    - ```npx create-react-app appname```
- Installed Polly dependency:
    - yarn add @aws-sdk/client-polly
- Imported and used the client somewhere in the code
- Started the app:
    - ```yarn start```

and I did not not get any issues. So, would it be possible for you to upgrade your project's dependencies to their latest version?; you can do that by running ```yarn upgrade```, and they will be updated unless otherwise specified in package.json.

Thanks!
