### ISSUE TITLE
Bump typedoc to v0.23.x

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#4134]
### Describe the feature

Bump typedoc to v0.23.x or latest

### Use Case

There are bunch of dependabot alerts due to transitive dependencies of typedoc@0.19.x:
* Inefficient Regular Expression Complexity in marked https://github.com/advisories/GHSA-5v2h-r2cx-5xgj
* Regular Expression Denial of Service (REDoS) in Marked https://github.com/advisories/GHSA-4r62-v4vq-hr96

We use typedoc for generating our docs, and it's not shipped in SDK artifacts. These issues won't impact our customers directly, and won't slow down our documents generation as we own the generation as well as source code. However, they appear in our security tickets and reviews.

The typedoc@0.19.2 is also officially compatible only with typescript "3.9.x || 4.0.x", while our source code is on typescript 4.6.3. This can create issues with generation of docs.

### Proposed Solution

Bump typedoc to v0.23.x or latest

### Other Information

Prior internal discussions in JS-3393

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

main

### Environment details (OS name and version, etc.)

N/A

**Comment by trivikr** [comment]
cc @eduardomourar who offered help with bumping typedoc in https://github.com/awslabs/smithy-typescript/pull/563#issuecomment-1298811963

**Comment by trivikr** [comment]
Previous attempt: https://github.com/aws/aws-sdk-js-v3/pull/3712

The build had failed as PluginHost export was removed in https://github.com/TypeStrong/typedoc/commit/22df5746dc8bf7df0a26ff47e1f1d82737461f05 which was released with [v0.21.0](https://github.com/TypeStrong/typedoc/releases/tag/v0.21.0). The plugins are now passed automatically.

**Comment by trivikr** [comment]
The plugin we use for lerna typedoc-plugin-lerna-packages itself doesn't support typedoc@0.20.0
Issue being discussed in https://github.com/marcj/typedoc-plugin-lerna-packages/issues/34

Typedoc added preliminary support for monorepos though in v0.21.x which we may have to evaluate https://github.com/TypeStrong/typedoc#monorepos--workspaces

**Comment by eduardomourar** [comment]
Created #4139 to help drive the discussion and the implementation itself.

**Comment by eduardomourar** [comment]
We are leveraging [the monorepo feature](https://github.com/TypeStrong/typedoc#monorepos--workspaces) from typedoc as you mentioned it. Find below the screenshots of the results:

* Root project
<img width="1362" alt="root-after" src="https://user-images.githubusercontent.com/16357187/199546989-d8035c68-8695-4e68-8ec2-8de3ac2b2ca0.png">

* Sample client
<img width="1363" alt="client-after" src="https://user-images.githubusercontent.com/16357187/199547032-4a80f627-39d7-43f4-9cf3-1750dede0a44.png">

**Comment by eduardomourar** [comment]
Keep in mind that I have been unable to run typedoc into the whole project due to this out of memory issue: https://github.com/TypeStrong/typedoc/issues/1606

**Comment by eduardomourar** [comment]
I believe the `@aws-sdk/service-client-documentation-generator` plugin (and possibly `@aws-sdk/core-theme-documentation-generator`) could be later removed by modifying the typescript codegen to include [the categories tags](https://typedoc.org/tags/category/).
