### ISSUE TITLE
Provide a concrete usage example for authentication and querying/subscribing

### ISSUE THREAD

**Issue by DarkTrick** [aws/aws-sdk-js-v3#4143]
### Describe the issue

Currently, there is not much information on how to use AppSyncClient and how to create a query.

This would be nice:
- Authentication example: Provide a concrete example of how to connect to AppSync with API key authentication.
- Authentication example: Provide a concrete example on how to connect to AppSync with cognito authentication.
- Authentication example: Provide a concrete example on how to connect to AppSync with lambda authentication.
- Query example: Provide a concrete example of how to run a query (especially, how to set the `AssociateApiCommandInput` values for `AssociateApiCommand`, which seems to be the way to run queries).
- Subscription example: Same as above, but for a subscription query.

### Links

- https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-appsync/classes/appsyncclient.html
- https://github.com/aws/aws-sdk-js-v3

**Comment by kannieWeesNie** [comment]
i agree, thanks

**Comment by MYoung25** [comment]
We appreciate you bringing this to our attention. We have released a [dev preview](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/) of the new API documentation for AWS SDK for JavaScript v3 based on your and other customers' feedback. Please let us know your thoughts on the new documentation by [providing feedback](https://github.com/aws/aws-sdk-js-v3/issues/new?assignees=&labels=documentation%2Cneeds-triage&template=documentation.yml&title=%28short+issue+description%29). We have a list of [outstanding issues](https://github.com/aws/aws-sdk-js-v3/discussions/4656) to address before our new documentation is GA'd. Thank you!

One of the key improvements is providing example syntax for every command, including [AssociateApiCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/client/appsync/command/AssociateApiCommand/)
