### ISSUE TITLE
Error while code build in @aws-sdk/util-endpoints version 3.202.0

### ISSUE THREAD

**Issue by shaileshnit** [aws/aws-sdk-js-v3#4146]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

In my Reactjs project, I have the following npm packages: 
```
{
...,
"dependencies": {
     ...,
"   "aws-amplify": "^1.3.3",
    "aws-appsync": "^4.1.4",
    "aws-appsync-subscription-link": "^3.0.9",
    "aws4fetch": "^1.0.13",
   ...,
   "react": "^17.0.2",
   ...
},
...
}
```

While the code build, it is showing "Failed to compile" with the following error: 

```console
./node_modules/@aws-sdk/util-endpoints/dist-es/lib/index.js 1:9
Module parse failed: Unexpected token (1:9)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
> export * as aws from "./aws";
| export * from "./booleanEquals";
| export * from "./getAttr";
```

```console
npm timing command:run-script Completed in 208821ms
npm verb exit 1
npm timing npm Completed in 209073ms
npm verb code 1
```

### SDK version number

@aws-sdk/util-endpoints@3.202.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.5.0

### Reproduction Steps

```
{
...,
"dependencies": {
     ...,
"   "aws-amplify": "^1.3.3",
    "aws-appsync": "^4.1.4",
    "aws-appsync-subscription-link": "^3.0.9",
    "aws4fetch": "^1.0.13",
    ...,
    "react": "^17.0.2",
    ...
},
...
}
```

### Observed Behavior

```console
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'run',
npm verb cli   'build',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@7.19.1
npm info using node@v16.5.0
npm timing npm:load:whichnode Completed in 0ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:C:\Users\sktni\AppData\Roaming\nvm\v16.5.0\node_modules\npm\npmrc Completed in 1ms
npm timing config:load:builtin Completed in 1ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 1ms
npm timing config:load:file:D:\Job\test\issue\swae-2-0-client\.npmrc Completed in 1ms
npm timing config:load:project Completed in 1ms
npm timing config:load:file:C:\Users\sktni\.npmrc Completed in 1ms
npm timing config:load:user Completed in 1ms
npm timing config:load:file:D:\usr\local\etc\npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:credentials Completed in 1ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 9ms
npm timing npm:load:configload Completed in 9ms
npm timing npm:load:setTitle Completed in 1ms
npm timing npm:load:setupLog Completed in 1ms
npm timing npm:load:cleanupLog Completed in 2ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load:projectScope Completed in 1ms
npm timing npm:load Completed in 30ms
npm timing config:load:flatten Completed in 3ms
[..................] / : timing config:load:flatten Completed in 3ms
> swae-2-0-client@0.1.0 build
> react-scripts --max_old_space_size=8192 build
```

Creating an optimized production build...ad:flatten Completed in 3ms
Failed to compile..] / : timing config:load:flatten Completed in 3ms

```console
./node_modules/@aws-sdk/util-endpoints/dist-es/lib/index.js 1:9
Module parse failed: Unexpected token (1:9)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
> export * as aws from "./aws";
| export * from "./booleanEquals";
| export * from "./getAttr";
```

```console
npm timing command:run-script Completed in 208821ms
npm verb exit 1
npm timing npm Completed in 209073ms
npm verb code 1
```

### Expected Behavior

Build Successfully

**Comment by shaileshnit** [comment]
@yenfryherrerafeliz I am still getting error. Please help me asap

>export * as aws from "./aws";
| export * from "./booleanEquals";
| export * from "./getAttr";

**Comment by yenfryherrerafeliz** [comment]
Hi @shaileshnit, could you please provide the details about how to reproduce the error?, did you get the issue when running ```npm run build``` ?

Thanks!

**Comment by shaileshnit** [comment]
@yenfryherrerafeliz Yes after "npm run build", I am getting following logs:

npm verb cli [
npm verb cli 'C:\Program Files\nodejs\node.exe',
npm verb cli 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
npm verb cli 'run',
npm verb cli 'build',
npm verb cli '--verbose'
npm verb cli ]
npm info using npm@7.19.1
npm info using node@v16.5.0
npm timing npm:load:whichnode Completed in 0ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:C:\Users\sktni\AppData\Roaming\nvm\v16.5.0\node_modules\npm\npmrc Completed in 1ms
npm timing config:load:builtin Completed in 1ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 1ms
npm timing config:load:file:D:\Job\test\issue\swae-2-0-client.npmrc Completed in 1ms
npm timing config:load:project Completed in 1ms
npm timing config:load:file:C:\Users\sktni.npmrc Completed in 1ms
npm timing config:load:user Completed in 1ms
npm timing config:load:file:D:\usr\local\etc\npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:credentials Completed in 1ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 9ms
npm timing npm:load:configload Completed in 9ms
npm timing npm:load:setTitle Completed in 1ms
npm timing npm:load:setupLog Completed in 1ms
npm timing npm:load:cleanupLog Completed in 2ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load:projectScope Completed in 1ms
npm timing npm:load Completed in 30ms
npm timing config:load:flatten Completed in 3ms
[..................] / : timing config:load:flatten Completed in 3ms

swae-2-0-client@0.1.0 build
react-scripts --max_old_space_size=8192 build

Creating an optimized production build...ad:flatten Completed in 3ms
Failed to compile..] / : timing config:load:flatten Completed in 3ms

./node_modules/@aws-sdk/util-endpoints/dist-es/lib/index.js 1:9
Module parse failed: Unexpected token (1:9)
File was processed with these loaders:

./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
export * as aws from "./aws";
| export * from "./booleanEquals";
| export * from "./getAttr";

npm timing command:run-script Completed in 208821ms
npm verb exit 1
npm timing npm Completed in 209073ms
npm verb code 1

**Comment by yenfryherrerafeliz** [comment]
@shaileshnit, I am currently investigating this. I will get back to you as soon as possible.

Thanks!

**Comment by yenfryherrerafeliz** [comment]
@shaileshnit Are you using the default webpack configuration?, if not, could you please provide the one you are using in order to better root cause the issue. 

Thanks!
