### ISSUE TITLE
Marshalling array values (aka list value in dynamodb) crashes when calling DynamoDBDocument.update()

### ISSUE THREAD

**Issue by TomasB** [aws/aws-sdk-js-v3#4155]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Calling `DynamoDBDocument.update()` crashes when `AtributeUpdates` contains update where value is an array.

See the attached code.

### SDK version number

@aws-sdk/client-dynamodb@3.204.0, @aws-sdk/lib-dynamodb@3.204.0, @aws-sdk/util-dynamodb@3.204.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.18.1

### Reproduction Steps

Snippets of relevant pieces and bits:
```js
const docClient = DynamoDBDocument.from( DynamoDBClient({ region: 'us-west-2' }));
....
  const d = {
    id: 'testid',
    name: 'test',
    testSet: new Set([9, 8, 7]),
    testArray: [1, 2, 3],
  };
 
 await docClient.update({
    TableName: 'testTable',
    Key: {
      category: 'testCategory',
    },
    AttributeUpdates: {
      name: {
        Action: 'PUT',
        Value: d.name,
      },
      testSet: {
        Action: 'PUT',
        Value: d.testSet,
      },
      testList: {
        Action: 'PUT',
        Value: d.testArray,
      },
    },
  });
```

### Observed Behavior

That code crashes as soon as we introduce saving array (list) value.
If I comment out updating `testList` value, then the above code works, including numbers set.

When it crashes, here is the stack:
```console
{
    "errorMessage": "Cannot read properties of undefined (reading '0')",
    "errorType": "TypeError",
    "stackTrace": [
        "TypeError: Cannot read properties of undefined (reading '0')",
        "    at Object.AttributeValue.visit (/Users/tomas/dev/terrayn/brain-functions/node_modules/@aws-sdk/client-dynamodb/dist-cjs/models/models_0.js:501:40)",
        "    at serializeAws_json1_0AttributeValue (/Users/tomas/dev/terrayn/brain-functions/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3182:38)",
        "    at serializeAws_json1_0AttributeValueUpdate (/Users/tomas/dev/terrayn/brain-functions/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3206:45)",
        "    at /Users/tomas/dev/terrayn/brain-functions/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3177:20",
        "    at Array.reduce (<anonymous>)",
        "    at serializeAws_json1_0AttributeUpdates (/Users/tomas/dev/terrayn/brain-functions/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3171:34)",
        "    at serializeAws_json1_0UpdateItemInput (/Users/tomas/dev/terrayn/brain-functions/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:4442:31)",
        "    at serializeAws_json1_0UpdateItemCommand (/Users/tomas/dev/terrayn/brain-functions/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:507:27)",
        "    at serialize (/Users/tomas/dev/terrayn/brain-functions/node_modules/@aws-sdk/client-dynamodb/dist-cjs/commands/UpdateItemCommand.js:40:72)",
        "    at /Users/tomas/dev/terrayn/brain-functions/node_modules/@aws-sdk/middleware-serde/dist-cjs/serializerMiddleware.js:12:27",
        "    at /Users/tomas/dev/terrayn/brain-functions/node_modules/@aws-sdk/middleware-endpoint/dist-cjs/endpointMiddleware.js:20:16",
        "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
        "    at async /Users/tomas/dev/terrayn/brain-functions/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22"
    ]
}
```

### Expected Behavior

Being able to pass array as value, which is saved as list in dynamo db.

### Possible Solution

When marshalling an array value, it should be marshalled as an object with "L" key, i.e., array=["a", 3] should be marshalled as:
```
  "fieldName": {
    "L": [
      {
        "S": "a"
      },
      {
        "N": "3"
      }
    ]
  }
```

At least that's how the value looks like in DynamoDb → Edit Item → view as JSON

### Additional Information/Context

I managed to patch (hack, i.e. I don't expect this to be the final solution) locally, directly in node_modules.

https://github.com/kuhe/aws-sdk-js-v3/blame/47ca922276bc9cfb22076af79b8b1db4fd43abed/lib/lib-dynamodb/src/commands/utils.ts#L39

```
const processKeysInObj = (obj: any, processFunc: Function, keyNodes: KeyNode[]) =>
  keyNodes.reduce(
    (acc, { key, children }) => ({
      ...acc,
      [key]: key==="Value" && Array.isArray(acc[key])
         ? { L: processKeyInObj(acc[key], processFunc, children) }
         : processKeyInObj(acc[key], processFunc, children),
    }),
    obj
  );
```

I'm checking for `key === "Value"` since when `key === "Items"` then this will break retrieving items from dynamoDb.
And, of course, all this is applicable only when the value type is array.

I have tested that with empty array as well as nested arrays (i.e. `[1, 2, 'a', [3, 'b']]`) and it worked as expected.

**Comment by AndrewGuenther** [comment]
I ran into this as well when performing a v2 -> v3 migration. Wild that we're getting pressured to move to v3 when issues like this exist...

**Comment by anandkumarpatel** [comment]
+1 also seeing this. current workaround is to use `UpdateItemCommand` and manually make the dynamodb object. but would be good to not have to use that.
