### ISSUE TITLE
Logger middleware doesn't log failed requests

### ISSUE THREAD

**Issue by simonbuchan** [aws/aws-sdk-js-v3#4158]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Using the `logger` option to enable the logger middleware only logs successful requests.

If nothing else, this is extremely confusing, but I'm raising it as a bug as I think it is very unlikely to be a deliberate choice.

### SDK version number

@aws-sdk/middleware-logger@3.201.0

### Which JavaScript Runtime is this issue in?

Browser

### Details of the browser/Node.js/ReactNative version

Edge: Spartan (44.22621.674.0), Chromium (107.0.1418.35)

### Reproduction Steps

```js
const { S3 } = require("@aws-sdk/client-s3");

async function main() {
  const s3 = new S3({
    region: "us-east-1",
    signer: { sign: (request) => request }, // workaround lack of anonymous credentials
    logger: {
      // ignore endpoints logging spam by not including logger.debug
      info: console.info,
      warn: console.warn,
      error: console.error,
    },
  })
  console.log("existing object");
  await s3.headObject({
    Bucket: "amazoncloudwatch-agent",
    Key: "amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm",
  }).catch((error) => {
    console.log("response error: %O", error.message);
  });
  console.log("missing object");
  await s3.listObjectsV2({
    Bucket: "amazoncloudwatch-agent",
    Key: "no-such-object",
  }).catch((error) => {
    console.log("response error: %O", error.message);
  });
}

main();
```

### Observed Behavior

```
existing object
{
  clientName: 'S3Client',
  commandName: 'HeadObjectCommand',
  input: {
    Bucket: 'amazoncloudwatch-agent',
    Key: 'amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm'
  },
  output: {
    AcceptRanges: 'bytes',
    LastModified: 2022-08-29T19:27:47.000Z,
    ContentLength: 49701120,
    ETag: '"823cdc9a7792124a4003b285d36d14ad"',
    VersionId: 'Zg_jVaskis_5s0SKBglWJWJKa568vUeF',
    ContentType: 'application/octet-stream',
    Metadata: {}
  },
  metadata: {
    httpStatusCode: 200,
    requestId: 'VC2C36TWMAMZPXGD',
    extendedRequestId: 'G3ET2YuAbLvmgRyDJ3tos9cSY7R1NwvczYoff5sYNhuHQEmgmLmVMRt6XrkwzylwETBK7ywIfbo=',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}
missing object
response error: 'Access Denied'
```

### Expected Behavior

I'd like to get roughly equivalent output for error responses too, probably as a `logger.error` (else why take a logger object).

### Possible Solution

The root of the issue is that the middleware-logger code, simplified, does:

```ts
export const loggerMiddleware = () => (next, context) => (args) => {
  const response = await next(args);
  const { $metadata: metadata, ...output } = response.output;
  logger.info({ (stuff from context, args), output, metadata });
  return response;
};
```

Here, `next` has to include `middleware-serde` so that there is something interesting in response, but in the error case the deserializer will throw an exception.

The straightforward fix is to update `middleware-logger` to look something like:

```ts
export const loggerMiddleware = () => (next, context) => (args) => {
  try {
    const response = await next(args);
    const { $metadata: metadata, ...output } = response.output;
    logger.info({ (stuff from context, args), output, metadata });
    return response;
  } catch (error) {
    logger.error({ (stuff from context, args), error, metadata: error.$metadata });
    throw error;
  }
};
```

One problem with this is that the `middleware-serde` both deserializes the error and throws the exception, so there's no good source for the `output` field: if it's a response error rather than e.g. signing then there will be a `error.$response`, but it only contains a read `ReadableStream` (or equivalent for Node), which is pretty useless. This is probably actually correct, though, as you haven't gotten the service output, the error output would be in a different shape and thus should be in a different property anyway.

Another concern might be that there's not a great way to filter error responses for sensitive details?

**Comment by simonbuchan** [comment]
I'm happy to work on a PR if you are OK with the suggested solution, or have another idea.

**Comment by ajredniwja** [comment]
@simonbuchan thanks for opening this issue, I have discussed with the team and they would be happy to review a PR. Thanks
