### ISSUE TITLE
getSignedUrl 3.204.0 makes AWS Lambda function to timeout

### ISSUE THREAD

**Issue by acerbisgianluca** [aws/aws-sdk-js-v3#4162]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I updated `@aws-sdk/s3-request-presigner` and `@aws-sdk/client-s3` from `3.194.0` to `3.204.0` and now, without touching the code, the Lambda function times out when the execution reaches `getSignedUrl`.

### SDK version number

@aws-sdk/s3-request-presigner@3.204.0, @aws-sdk/client-s3@3.204.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node 16

### Reproduction Steps

`S3Service` class:

```typescript
import { GetObjectCommand, S3Client } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';

export class S3Service {
  private static client = new S3Client({});

  public static async createPreSignedUrl(key: string): Promise<string> {
    const command = new GetObjectCommand({ Bucket: 'YOUR_BUCKET', Key: key });
    return getSignedUrl(S3Service.client, command, { expiresIn: 60 });
  }
}
```

Then call `await S3Service.createPreSignedUrl('key')` in an async function.

### Observed Behavior

While running on AWS Lambda, the code above gets stuck on the `createPreSignedUrl` call and the Lambda function runs out of time with this error: `Task timed out after 10.25 seconds`.

This only happens with version `3.204.0`.

### Expected Behavior

If I downgrade to version `3.194.0`, the code above runs just fine and returns the URL string.

**Comment by kuhe** [comment]
I can't reproduce this with your code and version. Please provide a small repository that demonstrates the issue.

Since you don't need a real S3 object to presign a URL, it can be very small.

**Comment by acerbisgianluca** [comment]
Apparently that part of the code alone works, but inside my application it blocks the execution. I'll investigate further and let you know.
