### ISSUE TITLE
sdk-stream-mixin (util-stream-node) `transformToString()` incorrectly processing PNG files from a stream

### ISSUE THREAD

**Issue by PaulSearcy** [aws/aws-sdk-js-v3#4166]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Transforming PNG downloaded from S3 bucket to string using `transformToString()` results in a file size bigger then the original file and OS (Mac) says file is corrupted when attempting to open.

Using node streams and piping the response does work. See reproduction code section for code and details.

### SDK version number

@aws-sdk/client-s3@3.204.0, @aws-sdk/util-stream-node@3.201.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.17.1

### Reproduction Steps

Using `transformToString()` results in broken png file. 

```js
const data = await s3Client
		.send(new GetObjectCommand({
			Bucket: 'testBucket',
			Key:'testPng.png'
		}))
const body = await data.Body.transformToString()
fs.writeFileSync('./testPng.png', body)
```

Using node streams results in a valid png file.
```js
const testStream = fs.createWriteStream('./testPng.png')
await data.Body.pipe(testStream)
```

### Observed Behavior

When stream of PNG file was saved back to drive as file it had larger file size and could not be opened as a PNG. 

### Expected Behavior

`transformToString()`  to correctly process a streamed PNG file from an S3 bucket

**Comment by nstankov-bg** [comment]
I confirm this is an issue.

**Comment by kuhe** [comment]
`await data.Body.transformToString("binary")`

**Comment by PaulSearcy** [comment]
> `await data.Body.transformToString("binary")`

Can you please explain? 

In that when passing the stream to Node it accurately detects the encoding. When calling `.transformToString()` without any arguments it doesn't detect the proper encoding.

Here is the exact section of the documentation I was following for handling streams. 
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/index.html#streams

While I understand the image is being streamed as binary. Shouldn't `.transformToString()` given the context of a stream with unknown format account for the fact that the stream could be binary and detect for that?  
https://github.com/aws/aws-sdk-js-v3/blob/main/packages/util-stream-node/src/sdk-stream-mixin.ts

At the very least what I'm brining up here is that the default behavior here should account for the wide variety of usages. If Node understands how to handle a binary stream without additional arguments shouldn't also this?

**Comment by kuhe** [comment]
Can you provide an example of Node.js transforming to string without knowing the encoding?
In my local testing, the only way to avoid specifying the encoding is to use the stream Buffer directly, which does not apply to the method `.transformToString()`.

My local testing shows the following:
```js
  const read = fs.readFileSync(__dirname + "/github.png");

  fs.writeFileSync(__dirname + "/test-ok1.png", read.toString("binary"), "binary"); // specify string encoding
  fs.writeFileSync(__dirname + "/test-ok2.png", read); // use stream without encoding

  fs.writeFileSync(__dirname + "/test-fail1.png", read.toString(), "binary"); // incomplete encoding info
  fs.writeFileSync(__dirname + "/test-fail2.png", read.toString("binary")); // incomplete encoding info
  fs.writeFileSync(__dirname + "/test-fail3.png", read.toString()); // incomplete encoding info
```

**Comment by PaulSearcy** [comment]
> Can you provide an example of Node.js transforming to string without knowing the encoding? In my local testing, the only way to avoid specifying the encoding is to use the stream Buffer directly, which does not apply to the method `.transformToString()`.

I think here is my mis-understanding of the implementation.  `transformToString` is specific in that it _must_ be provided the encoding ('binary') to be able to transform the stream for 'non-textual'  streams. Rather than being entirely able to infer the encoding directly from the stream. With a best effort attempt through `fromArrayBuffer(buf.buffer, buf.byteOffset, buf.byteLength).toString(encoding as BufferEncoding)` which won't work for a binary stream. 

The main use case I would be using `.transformToString()` for is downloading objects from S3. In that case I _wouldn't_ know the encoding of the target object due to the objects being in many different formats. (XML, JSON, PNG, JPEG, etc) Without some additional code to check for the content-type and branch the code based on it. So I think then that the solution I have to pass the stream to Node to handle is the write direction then. 

Unless there is a way implemented in `client-s3` that enables you to process a stream directly regardless of content-type? 

That said, thank you for your time and illuminating the nuances here that I couldn't find an answer for elsewhere!

**Comment by kuhe** [comment]
You should be able to do this with one of the other mixin methods:

```js
const body = await data.Body.transformToByteArray()
fs.writeFileSync('./testPng.png', body)
```

**Comment by PaulSearcy** [comment]
Some more context is that the code utilizing this sdk is part of a _REST API_ that will eventually be on a Lambda.

 Returning the the results of `Body.transformToByteArray()` directly as a response to the request made just passes the raw U8IntArray back to the client.  [fs.writeFile()](https://nodejs.org/dist/latest-v18.x/docs/api/fs.html#fswritefilefile-data-options-callback)  automatically handles a buffer (ignores encoding too) and therefore why it works, since I'm guessing it internally transforms the buffer.

**Comment by PaulSearcy** [comment]
@kuhe I think a new function called `transformToBuffer` would resolve this issue. 

While there isn't a utility function already to do this in node. https://github.com/nodejs/readable-stream/issues/403

The method in the link to just create an array, push the chunks of stream into it and then `Buffer.concat(array)` is pretty straight forward. 

Should I just create a new issue for this or change the title of this ticket? Either way I could potentially  write a PR if there isn't plans to implement something like this.

**Comment by kuhe** [comment]
You can create a feature request. However, there would need to be a significant amount of demand in order to add it. 

Isn't the conversion from Uint8Array to Buffer just `Buffer.from(array)`?

**Comment by PaulSearcy** [comment]
> You can create a feature request. However, there would need to be a significant amount of demand in order to add it.
> 
> Isn't the conversion from Uint8Array to Buffer just `Buffer.from(array)`?

`transformToBuffer` would take the _stream_ and convert it to a buffer directly. 
Ex. `data.Body.transformToBuffer()`

I did some further research and Node core actually _does_ support this  directly. 
https://nodejs.org/dist/latest-v18.x/docs/api/webstreams.html#streamconsumersbufferstream

It just requires Node 16.7.0 + which won't be an issue since there is already the function `transformToWebStream` already. With comments about needing Node 17+
