### ISSUE TITLE
Missing generateMac in kms client in the latest sdk

### ISSUE THREAD

**Issue by DrRek** [aws/aws-sdk-js-v3#4167]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The kms client in the aws sdk is missing the `generateMac` function.

### SDK version number

@aws-sdk latest used by new lambdas created in the browser

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

I'm using the default lambda and editing the code in the browser

### Reproduction Steps

1. Create a new empty nodejs16 lambda function (idk if it's relevant, but I'm on region eu-central-1)
2. Write the following as content of `index.js`
```const AWS = require('aws-sdk');

exports.handler = async (event) => {
    const kms = new AWS.KMS();
    kms.generateMac()

    return {
        statusCode: 200,
        body: "test",
    };
};
```

3. deploy and run the code with any input

### Observed Behavior

As you can see from the output the command we get "generateMac is not a function". 

### Expected Behavior

Try to follow the same steps using the `generateRandom` function and everything works without error.

### Additional Information/Context

I know I'm not supplying the correct input nor handling the promise, this is just a minimal example to show the problem.

**Comment by kuhe** [comment]
Lambda uses V2. The version is not updated frequently. It is provided for development/testing, but if you want to use the latest version you should provide it to the lambda function by uploading it as part of your function code.

**Comment by ajredniwja** [comment]
Please see https://docs.aws.amazon.com/lambda/latest/dg/nodejs-package.html, you'll need to bundle the modules that use from the SDK. Thanks
