### ISSUE TITLE
Nullish coalescing issues with node js version 12.22.0-buster nextjs even after using babel plugin

### ISSUE THREAD

**Issue by bharatjangid20** [aws/aws-sdk-js-v3#4179]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Nullish coalescing is not supported in Node version 12.22.0-buster also in some cases where even after using babel plugin it's giving issues and breaking the deployment.

### SDK version number

3.208.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

nodejs version 12.22

### Reproduction Steps

Nuliish coalescing is not supported on node version 12.22.0-buster while builing the project.

### Observed Behavior

https://user-images.githubusercontent.com/117355931/201332304-a4c36f2a-d794-4593-b48d-1191db3cdbaf.png

Attached the image where you can see the error says syntax error. 

### Expected Behavior

the error should not come and deployment should not break becasue of syntax error.

### Possible Solution

please add additional checks, instead of ?? we can explicitly put condition that if value is 0 still we will treat it as value else false.

**Comment by bharatjangid20** [comment]
@trivikr can you please look at it ?

**Comment by trivikr** [comment]
> Node version 12.22.0-buster

We ended support for Node.js 12.x on November 1, 2022 with release [v3.201.0](https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.201.0).
If you want to continue using Node.js 12.x in your application, please use version <=v3.200.0.
We recommend Node.js 18.x LTS.

For details, please check out blog post [Announcing the end of support for Node.js 12.x in the AWS SDK for JavaScript (v3)](https://aws.amazon.com/blogs/developer/announcing-the-end-of-support-for-node-js-12-x-in-the-aws-sdk-for-javascript-v3/) from May 2022.
