### ISSUE TITLE
sdk throws exception when parsing error response from sfn sendTaskSuccess

### ISSUE THREAD

**Issue by everett1992** [aws/aws-sdk-js-v3#4184]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When sending a sendTaskSuccess request with a very large body the sdk throws an unexpected error

Unexpected token H in JSON at position 0

The actual response from sfn is 
```
HTTP content length exceeded 1049600 bytes.
```

Headers are
```
HttpResponse {
  statusCode: 413,
  headers: {
    'content-type': 'text; charset=utf-8',
    'content-length': '43',
    date: 'Mon, 14 Nov 2022 04:04:05 GMT',
    connection: 'close'
  },
```

Maybe sfn is miss behaving by responding with text, but I think aws-sdk should check response headers before de-serializing. 

### SDK version number

@aws-sdk/client-sfn@3.209.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.12.0

### Reproduction Steps
```js
import {SFN} from '@aws-sdk/client-sfn'

const sfn = new SFN({})

await sfn.sendTaskSuccess({
  output: "a".repeat(1049601),
  taskToken: "",
});
```

### Observed Behavior

```
SyntaxError: Unexpected token H in JSON at position 0
```

### Expected Behavior

```
SfnServiceException:  HTTP content length exceeded 1049600 bytes.
```

### Possible Solution

 - Update the aws json protocol generator check content-type before de serializing errors.
 - Update sfn to use json protocol errors.

**Comment by everett1992** [comment]
When I use a smaller, but still too large output I get a reasonable error so I'm guessing my really large request was dropped by a load balancer or other server in from of Step Functions 
```
1 validation error detected: Value at 'output' failed to satisfy constraint: Member must have size less than or equal to 262144 bytes in UTF-8 encoding
```

**Comment by yenfryherrerafeliz** [comment]
Hi @everett1992, thanks for opening this issue. Basically, according to the documentation [here](https://docs.aws.amazon.com/step-functions/latest/apireference/API_SendTaskSuccess.html#API_SendTaskSuccess_RequestSyntax), there is a length constraint for the parameter output of 262144, and therefore that, whenever the value of "output" is over this length limit, then you get an error from the service API. I can confirm that there is an issue parsing the response from the service API, since the SDK expect the response to be a JSON string, but the response gotten it is not.

Thanks!

**Comment by everett1992** [comment]
When I'm just over the 262144 limit I get modeled json exception 
```
1 validation error detected: Value at 'output' failed to satisfy constraint: Member must have size less than or equal to 262144 bytes in UTF-8 encoding
```

If I use a _really_ large request then I get

```
SyntaxError: Unexpected token H in JSON at position 0
```

because the service didn't respond with JSON. I be this would happen for any service or operation, not just operations with documented length constraints. It's probably a load balancer or proxy before the service host that rejects the request.

I guess I already reported this issue to smithy-typescript https://github.com/awslabs/smithy-typescript/issues/555

**Comment by yenfryherrerafeliz** [comment]
Hi @everett1992, this issue has been fixed and can be confirmed [here](https://github.com/awslabs/smithy-typescript/blob/e9836bc3739450fac0a6d1a1d91100a1a09a6cb6/packages/middleware-serde/src/deserializerMiddleware.ts#L32). If a response from the service can't be deserialized then, you will get an exception as follow:
```
SyntaxError: Unexpected token H in JSON at position 0
  Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.
```
Basically you will get more details about why the parsing failed by inspecting the hidden field {error}.$response as follow:
```js
import {SendTaskSuccessCommand, SFNClient} from "@aws-sdk/client-sfn";

const client = new SFNClient({
    region: "us-east-2"
});
try {
    const response = await client.send(new SendTaskSuccessCommand({
        output: "#".repeat(1049601),
        taskToken: ""
    }));
    console.log(response)
} catch (e) {
    console.log(e.$response);
}
```

I will resolve this issue for now, but please feel free of opening a new issue if is there anything else that we can help with.

Thanks!
