### ISSUE TITLE
typescript compilation error / missing types

### ISSUE THREAD

**Issue by mehtamanan** [aws/aws-sdk-js-v3#4191]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Typescript compiler is failing with the following errors:

```
node_modules/@aws-sdk/config-resolver/dist-types/endpointsConfig/NodeUseDualstackEndpointConfigOptions.d.ts(1,39): error TS2307: Cannot find module '@aws-sdk/node-config-provider' or its corresponding type declarations.
node_modules/@aws-sdk/config-resolver/dist-types/endpointsConfig/NodeUseFipsEndpointConfigOptions.d.ts(1,39): error TS2307: Cannot find module '@aws-sdk/node-config-provider' or its corresponding type declarations.
node_modules/@aws-sdk/config-resolver/dist-types/regionConfig/config.d.ts(1,59): error TS2307: Cannot find module '@aws-sdk/node-config-provider' or its corresponding type declarations.
node_modules/@aws-sdk/middleware-retry/dist-types/configurations.d.ts(1,39): error TS2307: Cannot find module '@aws-sdk/node-config-provider' or its corresponding type declarations.
```

### SDK version number

@aws-sdk/client-secrets-manager@3.210.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

16.14.1

### Reproduction Steps

```
pnpm init
pnpm i @aws-sdk/client-secrets-manager
```

```
import { SecretsManagerClient, GetSecretValueCommand } from '@aws-sdk/client-secrets-manager';

(async () => {
    const client = new SecretsManagerClient({ region: 'us-west-2' });
    const response = await client.send(new GetSecretValueCommand({
        SecretId: 'somekey'
    }))
    console.log(response)
})().then(console.log).catch(console.log)
```

### Observed Behavior

Typescript compiler is failing with the following errors:

```
node_modules/@aws-sdk/config-resolver/dist-types/endpointsConfig/NodeUseDualstackEndpointConfigOptions.d.ts(1,39): error TS2307: Cannot find module '@aws-sdk/node-config-provider' or its corresponding type declarations.
node_modules/@aws-sdk/config-resolver/dist-types/endpointsConfig/NodeUseFipsEndpointConfigOptions.d.ts(1,39): error TS2307: Cannot find module '@aws-sdk/node-config-provider' or its corresponding type declarations.
node_modules/@aws-sdk/config-resolver/dist-types/regionConfig/config.d.ts(1,59): error TS2307: Cannot find module '@aws-sdk/node-config-provider' or its corresponding type declarations.
node_modules/@aws-sdk/middleware-retry/dist-types/configurations.d.ts(1,39): error TS2307: Cannot find module '@aws-sdk/node-config-provider' or its corresponding type declarations.
```

### Expected Behavior

Project to compile without errors

**Comment by RanVaknin** [comment]
Hi @mehtamanan ,

Thanks for opening this issue 😃 

Unfortunately I'm not able to replicate your errors.
I'm able to run your code just fine:

```js
// sample.js

import { SecretsManagerClient, GetSecretValueCommand } from '@aws-sdk/client-secrets-manager';

(async () => {
    const client = new SecretsManagerClient({ region: 'us-east-1' });
    const response = await client.send(new GetSecretValueCommand({
        SecretId: mySecret
    }))
    console.log(response)
})().then(console.log).catch(console.log)
```

```console
$ node sample.js
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: REDACTED,
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  ARN: REDACTED,
  CreatedDate: 2022-06-02T22:14:54.561Z,
  Name: REDACTED,
  SecretBinary: undefined,
  SecretString: REDACTED,
  VersionId: 'f9ab09c8-359a-43bc-b61d-83b6886ee8e3',
  VersionStages: [ 'AWSCURRENT' ]
}
```

Is there any other pieces of code that you have omitted that might cause this issue?
Note: I'm not using `pnpm`, I'm not sure if that is the root cause of your issue, but I suggest you try to run this with `npm`.

Many thanks,
Ran~

**Comment by Everton-Sales** [comment]
Erros in Amplify (next12):
TypeScript erros in:
@aws-sdk/lib-dynamodb and @aws-sdk/client-s3

**Comment by RanVaknin** [comment]
Hi @mehtamanan ,

I'm not able to reproduce this error.

I've followed your repro code and successfully able to retrieve the secret.
```console
$ touch sample.ts
$ pnpm init
$ pnpm i @aws-sdk/client-secrets-manager
$ tsc sample.ts --target es6 --moduleResolution node
// compiles into sample.js
$ node sample.js

{
  '$metadata': {
    httpStatusCode: 200,
    requestId: REDACTED,
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  ARN: REDACTED,
  CreatedDate: 2022-06-02T22:14:54.561Z,
  Name: REDACTED,
  SecretBinary: undefined,
  SecretString: REDACTED,
  VersionId: 'f9ab09c8-359a-43bc-b61d-83b6886ee8e3',
  VersionStages: [ 'AWSCURRENT' ]
}
```

Where are you running into this compile error? Any info that can help me repro this would be helpful.
Can you try `pnpm i @aws-sdk/node-config-provider` ? Maybe installing that dependency explicitly will help solve your issue?

Thanks,
Ran~

**Comment by mehtamanan** [comment]
Hi @RanVaknin, The pnpm lockfile doesn't list `@aws-sdk/node-config-provider` as a dependency for `@aws-sdk/config-resolver` and as a result, the package doesn't get fetched and leads to a compile time error.


snippet from pnpm-lock.yaml:
```
  /@aws-sdk/config-resolver/3.209.0:
    resolution: {integrity: sha512-wLXI1Jg9xx9wE8vdIfOgSKnoBWbn9j3IvW4+7PnM/nf5xC30/Jp4j+JndEG/BKyDQF7HJQTIeRpSkwKaqJhCRA==}
    engines: {node: '>=14.0.0'}
    dependencies:
      '@aws-sdk/signature-v4': 3.208.0
      '@aws-sdk/types': 3.208.0
      '@aws-sdk/util-config-provider': 3.208.0
      '@aws-sdk/util-middleware': 3.208.0
      tslib: 2.4.1
    dev: false
```

I was able to work around it by patching the dependencies using pnpm.packageExtensions:
```
{
  ...
  "pnpm": {
    "packageExtensions": {
      "@aws-sdk/config-resolver": {
        "dependencies": {
          "@aws-sdk/node-config-provider": "*"
        }
      },
      "@aws-sdk/middleware-retry": {
        "dependencies": {
          "@aws-sdk/node-config-provider": "*"
        }
      },
      "@aws-sdk/node-config-provider": {
        "dependencies": {
          "@types/node": "18.11.9"
        }
      },
      "@aws-sdk/types": {
        "dependencies": {
          "tslib": "2.4.1"
        }
      }
    }
  }
}
``` 

I'm not very familiar with the inner workings of npm but what happens to a package's devDependencies during `npm install`? `@aws-sdk/node-config-provider` is a dev dependency for `@aws-sdk/config-resolver` and if it isn't pulled into `node_modules`, it'll cause typescript projects to error out at compile time due to missing types.

Should all types for a typescript package be provided as production dependencies? Does it make sense to move `@aws-sdk/node-config-provider` from devDependency to dependency for `@aws-sdk/config-resolver` and other impacted packages?

**Comment by RanVaknin** [comment]
@mehtamanan I see what you are saying but in order for the team to address your concern I'll need to be able to reproduce your issue.

Since following your steps previously did not result in the same error, are you able to upload a minimal Github repo that will help me reproduce your issue? 

Thank you very much,
Ran~
