### ISSUE TITLE
Documentation on how to call AppSync query/mutation from GraphQl from lambda

### ISSUE THREAD

**Issue by davideicardi** [aws/aws-sdk-js-v3#4202]
### Describe the issue

We cannot find any official documentation on how to call an AppSync query or mutation inside a lambda.
We only found the issue #2227. Can you confirm that this is the correct way to do this?

I suggest to put an official documentation for this scenario.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-appsync/index.html

**Comment by RanVaknin** [comment]
Hi @davideicardi ,

Thanks for your patience. The `@aws-sdk/client-appsync` package that the SDK has is for control plane operations like creating and managing your API, and also configuring data sources. The SDK does not offer a direct way to interact with the API that you create. 

If you create an appsync API that use IAM based auth, you can use the SDK's v4 signer to sign your requests, however this is not unique to appsync, that is a general signer that you can use to interact with any AWS service.

Unfortunately writing and maintaining service specific documentation is not something we can provide here on the SDK team. Documentation including code examples, are owned by individual service teams.  

With that being said, here is an example on how to use the SDK utility packages to sign the request:

```js
import { SignatureV4 } from '@aws-sdk/signature-v4';
import { createRequest } from '@aws-sdk/util-create-request';
import { Sha256 } from '@aws-sdk/crypto-sha256-js';
import fetch from 'node-fetch';


const region = 'us-east-1';
const endpoint = "https://REDACTED.appsync-api.us-east-1.amazonaws.com/graphql"


const signer = new SignatureV4({
    credentials: {
        accessKeyId: "REDACTED",
        secretAccessKey: "REDACTED"
    },
    region,
    service: 'appsync',
    sha256: Sha256
});

const makeSignedAppSyncRequest = async (query) => {
    const body = JSON.stringify({ query });
    const request = {
        method: 'POST',
        headers: {
            'Content-Type': 'application/graphql',
            'host': new URL(endpoint).hostname,
        },
        protocol: 'https:',
        hostname: new URL(endpoint).hostname,
        path: '/graphql',
        body: body,
        region: region,
        service: 'appsync',
    };

    const signedRequest = await signer.sign(request, {
        signingDate: new Date(),
    });

    const response = await fetch(endpoint, {
        method: signedRequest.method,
        headers: signedRequest.headers,
        body: signedRequest.body,
    });

    return response.json();
};

const query = `
query {
    getNote(id: "sample-id-123") {
        id
        title
        content
    }
}
`;


makeSignedAppSyncRequest(query)
    .then(response => {
        console.log(response);
    })
    .catch(error => {
        console.error("Error fetching data:", error);
    });
```

Lambda doesnt change much. Youll just have to run this same code from a Lambda handler. 

Thanks,
Ran~
