### ISSUE TITLE
DOM types is missing in tsconfig file

### ISSUE THREAD

**Issue by eduardomourar** [aws/aws-sdk-js-v3#4204]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

After [PR #625](https://github.com/awslabs/smithy-typescript/pull/625), the DOM types have been removed from the default tsconfig.json file (before the value for lib included the DOM).

### SDK version number

3.212.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.15.1

### Reproduction Steps

Just copy a client SDK folder (e.g. `clients/client-lambda`). Then run for that project in isolation:
```bash
npm install
npx tsc -p tsconfig.cjs.json
```

### Observed Behavior

We get the following error during compilation:
> src/models/models_0.ts:3518:43 - error TS2304: Cannot find name 'Blob'.

### Expected Behavior

To compile successfully without having to change the tsconfig.json file that was originally generated.

### Possible Solution

* Include `"lib": ["es2020", "dom"]` into the tsconfig.json
* Another option in to add the Blob to the global declaration (similar to [this PR here](https://github.com/aws/aws-sdk-js-v3/pull/3889/files))

### Additional Information/Context

Related to https://github.com/aws/aws-sdk-js-v3/issues/2896.

**Comment by kanocarra** [comment]
I am also seeing this issue
