### ISSUE TITLE
Smithy Client default error handler to handle "x-amz-request-id"

### ISSUE THREAD

**Issue by officialcliffman** [aws/aws-sdk-js-v3#4209]
### Checkboxes for prior research

- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When the s3-client returns an error, it fails to grab the request id as the header is "x-amz-request-id".

On successful request, the s3-client will parse the request id like so:
[https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-s3/src/protocols/Aws_restXml.ts#L12006](https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-s3/src/protocols/Aws_restXml.ts#L12006)

Whereas the smithy client is currently:
[https://github.com/aws/aws-sdk-js-v3/blob/main/packages/smithy-client/src/default-error-handler.ts#L22](https://github.com/aws/aws-sdk-js-v3/blob/main/packages/smithy-client/src/default-error-handler.ts#L22)

### SDK version number

@aws-sdk/client-s3:3.212.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.15.0

### Reproduction Steps

Getting an object that doesn't exist.

### Observed Behavior

Throws the expected error but the "requestId" is coming back as undefined.

### Expected Behavior

Return the error response with the requestId.

### Possible Solution

Replicate the line from:
[https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-s3/src/protocols/Aws_restXml.ts#L12009](https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-s3/src/protocols/Aws_restXml.ts#L12009)

And add to:
[https://github.com/aws/aws-sdk-js-v3/blob/main/packages/smithy-client/src/default-error-handler.ts#L24](https://github.com/aws/aws-sdk-js-v3/blob/main/packages/smithy-client/src/default-error-handler.ts#L24)

**Comment by RanVaknin** [comment]
Hi @officialcliffman ,

The links you have provided are broken.
>When the s3-client returns an error, it fails to grab the request id as the header is "x-amz-request-id".

Since the link is broken I'm not exactly sure what you are referring to. 

Here is an example of a response from a request I've made to s3 object that doesn't exist:

```console
$ node sample.js          
...
...
...
    at async /test_folder/4209_s3_fail_smithy/sample.js:11:18 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 404,
    requestId: '543R5Z6....REDACTED',
    extendedRequestId: REDACTED,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Code: 'NoSuchKey',
  Key: 'hello666.txt',
  RequestId: '543R5Z6....REDACTED',
  HostId: REDACTED
}
```

RequestId here is returned both in the metadata and in the body.

Can you please provide a better description of what seems to be wrong?

Thanks,
Ran

**Comment by officialcliffman** [comment]
Hi @RanVaknin,

Apologies for the links, they have now been updated and fixed. As per [AWS S3 docs](https://aws.amazon.com/premiumsupport/knowledge-center/s3-request-id-values/) the s3 request id header is expected to be "x-amz-request-id" however the [Smithy error handler](https://github.com/aws/aws-sdk-js-v3/blob/main/packages/smithy-client/src/default-error-handler.ts#L24) doesn't account for this header. I believe it should behave the same as a [successful request](https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-s3/src/protocols/Aws_restXml.ts#L12009) and have the functionality to return "x-amz-request-id".

Thanks,
Jon

**Comment by RanVaknin** [comment]
Hi @officialcliffman ,

Thanks for the clarification. 
It seems like those s3 docs have all 3 headers accounted for because this was added to our code generation files. That Smithy client however, is a hand written client and did not get updated as part of the modification made to the codegen.

I'll add an action item for us to fix this. 

Thank you!
Ran
