### ISSUE TITLE
Document recommended style for logging calls

### ISSUE THREAD

**Issue by everett1992** [aws/aws-sdk-js-v3#4211]
### Describe the feature

The type of logger in @aws-sdk/types is very open and allows any arguments.

```
info: (...content: any[]) => void;
```

Popular logging libraries use different argument patterns and orders. Some expect meta objects first, some expect var args, some support callbacks.
 - winston expects (string, meta)
 - pino expects (meta, string)

#### pino
```
{"level":30,"time":1668795910526,"pid":1870501,"hostname":"...","msg":"something went wrong"}
```
#### winston
```
{"level":"info","message":"something went wrong","stack":"Error\n    at Object.<anonymous> (test.ts:8:13)\n    ..."}
```
#### pino
```
{"level":30,"time":1668796367853,"pid":1874536,"hostname":"...","err":{"type":"Error","message":"message","stack":"Error: message\n    at Object.<anonymous> (test.ts:8:13) ...},"msg":"something went wrong"}
```
#### winston
```
{"level":"info","message":{}}
```

As you can see loggers depend on the order of arguments to include the error and stack trace.

### Use Case

When writing middleware I want to know how I should format my log calls.
 - what order should I put messages and context objects
 - should I wrap context in a object or use varargs
 - what levels should I use (the style guide should give examples of info, debug, trace, warn, error... so middleware are consistent)
 
 When passing a logger to a client constructor I want to know logs will be properly formatted.

### Proposed Solution

Define a style guide covering recommended log implementations, order and types of parameters, and log levels.
Potentially narrow the typescript type for logger to match a specific order.
Potentially create wrappers or examples of converting a logger to the expected format.

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### SDK version used

3.x

### Environment details (OS name and version, etc.)

N/A

**Comment by amazlite** [comment]
I would define a universal interface for logging, so that customers can write adapters for whatever libraries they prefer. SDK might provide 1-2 adapters for most popular logging frameworks.
