### ISSUE TITLE
Kinesis client very low performance

### ISSUE THREAD

**Issue by sridhard** [aws/aws-sdk-js-v3#4213]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Hi,
We are using kinesis client to put records to kinesis stream. We are using kinesis client in proxy mode.

App(LoadTester) --------->Proxy - Kinesis client - nodejs ------------------->KinesisStream

The performance of Kinesis client is very very low. Below is the code:
```
    let eventWrapper = {};
    eventWrapper.event = event;
    eventWrapper.eventTime = Math.floor(new Date().getTime() / 1000);
    eventWrapper.eventSrc = eventSource.EVENT_SRC_APP;

    let recordParams = {
      Data : Buffer.from(JSON.stringify(eventWrapper)),
      PartitionKey : 'user-' + eventWrapper.eventTime,
      StreamName : 'analytics-events'
    };

    try {
      const command = new PutRecordCommand(recordParams);
      const response = await kinesisClient.send(command);
      return { statusCode: 200 }
    } catch(err) {
      console.log('Exception in handling event: ', err);
      fastify.log.error('Exception in handling event:' + JSON.stringify(event) + ' exception: ' + err);
      throw fastify.httpErrors.internalServerError('Exception in handling event:' + JSON.stringify(event) + ' exception: ' + err);
    }    
```
If I comment line 
##### "const response = await kinesisClient.send(command);" 
then from APP(LoadTester) I am able to achieve 14500 requests/sec. If I uncomment line to send to kinesis then the requests/sec drops to 220 which is very very low.

### SDK version number

SDK v3, Latest

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node 14.16.1

### Reproduction Steps

Run load test with kinesis client in nodejs

### Observed Behavior

Performance/throughput is very low. unacceptable.

### Expected Behavior

Without sending record to kinesis we are able to acheive 14500 requests/sec. Performance with sending record to kinesis should be atleast 8000-10000 requests/sec

**Comment by sridhard** [comment]
Please note that I am creating kinesis client only once as below:
```
const kinesisClient = new KinesisClient({ 
  region: "ap-south-1",
  credentials: fromIni({
    profile: 'analyticsserver'
  })
});
```

**Comment by RanVaknin** [comment]
Hi @sridhard ,

> If I uncomment line to send to kinesis then the requests/sec drops to 220 which is very very low.

I'm confused. If you remove the function call at :
`      const response = await kinesisClient.send(command);
` how is the request being sent? The code provided does not reflect this behavior.

Thanks,
Ran~
