### ISSUE TITLE
Type Error in GetCommand in @aws-sdk/lib-dynamodb

### ISSUE THREAD

**Issue by Everton-Sales** [aws/aws-sdk-js-v3#4214]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Amplify error in compilation:

Type error: Argument of type 'GetCommand' is not assignable to parameter of type 'Command<ServiceInputTypes, GetItemCommandInput | GetCommandInput, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<...>>'.

### SDK version number

@aws-sdk/client-dynamodb: "^3.211.0"

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

"next": "^12.3.1", "aws-amplify": "^5.0.1","@aws-sdk/client-dynamodb": "^3.211.0", "@aws-sdk/client-s3": "^3.211.0", "@aws-sdk/lib-dynamodb": "^3.211.0", "@aws-sdk/types": "^3.208.0",

### Reproduction Steps

Software compilation on AWS Amplify and code on github:

try {
    const params: GetCommandInput = {
      TableName: table,
      Key: {
        [itemName]: item
      },
    };
    const data = await ddbDocClient.send(new GetCommand(params));
    return JSON.stringify(data.Item);
  }

### Observed Behavior

If I remove the typescript it compiles without errors...
Same with @aws-sdk/client-s3...

### Expected Behavior

Typescript working properly

**Comment by RanVaknin** [comment]
Hi @Everton-Sales,

Can you please give more in depth repro steps than: "Software compilation on AWS Amplify and code on github"?
Full code sample including your tsconfig would be helpful.

Thank you.
Ran

**Comment by Everton-Sales** [comment]
Problem solved...
I had Next version 11 in PROD and version 12 in DEV, I matched PROD and Amplify asked if I would like to migrate to version 12 and I said yes. After this step, no more Typescript error occurred.
Sorry and Thank you.
