### ISSUE TITLE
Some utils not included with embedded package on Lambda Node 18

### ISSUE THREAD

**Issue by paul-uz** [aws/aws-sdk-js-v3#4215]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Using Node 18, which has the v3 SDK included,`@aws-sdk/util-base64` is not available, but `@aws-sdk/util-arn-parser` is.

### SDK version number

@aws-sdk/util-base64

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

18

### Reproduction Steps

Use the code below in a MJS file.

```javascript
import { fromBase64 } from '@aws-sdk/util-base64';
import { parse } from '@aws-sdk/util-arn-parser';

export const handler = async (event) => {
    const response = {
        statusCode: 200,
        body: JSON.stringify({
            base64: fromBase64('aGVsbG8gd29ybGQ='),
            arnParse: parse('<insert your own ARN here>'),
        }),
    };
    return response;
};
```

### Observed Behavior

Lambda errors out with the following:

```json
{
  "errorType": "Error",
  "errorMessage": "Cannot find package '@aws-sdk/util-base64' imported from /var/task/index.js",
  "trace": [
    "Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@aws-sdk/util-base64' imported from /var/task/index.js",
    "    at new NodeError (node:internal/errors:393:5)",
    "    at packageResolve (node:internal/modules/esm/resolve:865:9)",
    "    at moduleResolve (node:internal/modules/esm/resolve:958:20)",
    "    at moduleResolveWithNodePath (node:internal/modules/esm/resolve:909:12)",
    "    at defaultResolve (node:internal/modules/esm/resolve:1173:79)",
    "    at nextResolve (node:internal/modules/esm/loader:163:28)",
    "    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)",
    "    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)",
    "    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)",
    "    at link (node:internal/modules/esm/module_job:75:36)"
  ]
}
```

### Expected Behavior

I would expect the following:

```json
{
  "statusCode": 200,
  "body": "{\"base64\":{\"0\":104,\"1\":101,\"2\":108,\"3\":108,\"4\":111,\"5\":32,\"6\":119,\"7\":111,\"8\":114,\"9\":108,\"10\":100},\"arnParse\":{\"partition\":\"aws\",\"service\":\"lambda\",\"region\":\"eu-west-1\",\"accountId\":\"XXXXXXXX\",\"resource\":\"layer:Foo-layer:95\"}}"
}
```

**Comment by paul-uz** [comment]
Looks like util-base64 was added in `v3.202.0`, meaning the embedded package is a a lower version. Anyone know what version it is exactly? And how often it is updated?

**Comment by trivikr** [comment]
> looks like its v3.188.0? At least, thats the version of `util-base64-node` it has

Yes. The AWS SDK for JavaScript (v3) version provided by Lambda is a slightly older version, i.e. v3.188.0
The `@aws-sdk/util-base64` was published in [v3.202.0](https://github.com/aws/aws-sdk-js-v3/blob/main/CHANGELOG.md#32020-2022-11-02).

It'll be available once the version of v3 is upgraded in Lambda Provided SDK.
Please refer our README for stability of internal packages: https://github.com/aws/aws-sdk-js-v3#stability-of-modular-packages

**Comment by paul-uz** [comment]
> It'll be available once the version of v3 is upgraded in Lambda Provided SDK.

When will this be?

> Please refer our README for stability of internal packages: https://github.com/aws/aws-sdk-js-v3#stability-of-modular-packages

`util` packages are not in the list linked

**Comment by trivikr** [comment]
> When will this be?

Historically, Lambda team has been updating SDK versions once in 3-4 months.
You can find current supported version in [Lambda Runtimes](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html).

> `util` packages are not in the list linked

The `util` packages fall under `remaining @aws-sdk/*`

**Comment by thelegendtubaguy** [comment]
Almost a year later, that 3-4 month timeframe is _really_ understated.

**Comment by thscott** [comment]
The current runtime is still using [v3.188.0](https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.188.0), which is now more than a year ago.

Is there any documentation anywhere as to when or how often updates to the lambda provided SDK are made? I realise that you can just bundle it or use layers, but it's getting to the point where there's not much point even having a default version provided by lambda.

**Comment by trivikr** [comment]
Closing, as Lambda Provided JS SDK v3 was updated in multiple stages (v3.362.0, v3.362.0, v3.515.0, v3.552.0) and is updated more often now.

**Comment by thscott** [comment]
@trivikr It's good that it's updated more often now, but is there anywhere that actually documents what the current version used is?

The link you posted previously (https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) no longer has this information - looking at the internet archive, that column was removed somewhere between [Feb 25](https://web.archive.org/web/20240225003205/https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) and [March 06](https://web.archive.org/web/20240306185829/https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html).

**Comment by trivikr** [comment]
> is there anywhere that actually documents what the current version used is?

No. The AWS Lambda Developer Guide provides example source code to find [Runtime-included SDK versions](https://docs.aws.amazon.com/lambda/latest/dg/lambda-nodejs.html#nodejs-sdk-included).
