### ISSUE TITLE
Aws-Sdk v3 does not bundle using EsBuild

### ISSUE THREAD

**Issue by LeviSklaroff** [aws/aws-sdk-js-v3#4217]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Hello,

I'm attempting to bundle a browser application that makes use of the amazon-chime-js-sdk which contains the `@aws-sdk/client-chime-messaging-sdk`. I've been unable to successfully bundle the application using Esbuild version 0.15.14 as it's attempting to use the non-browser version of the cjs distribution of the aws-js-sdk. 

Verbose logs of finding but not using the es distribution:

```
"../node_modules/@aws-sdk/smithy-client"
          Attempting to load
  "../node_modules/@aws-sdk/smithy-client/dist-es/index.js" as a file
            Checking for file "index.js"
            Found file "index.js"
        Found main field "main" with path "./dist-cjs/index.js"
          No "browser" map found in directory
  "../node_modules/@aws-sdk/smithy-client"
          Attempting to load
  "../node_modules/@aws-sdk/smithy-client/dist-cjs/index.js" as a file
            Checking for file "index.js"
            Found file "index.js"
        Resolved to
  "../node_modules/@aws-sdk/smithy-client/dist-cjs/index.js" because of
  "require"
  
```
Error being produced:

```
[ERROR] Could not resolve "buffer"

    ../@aws-sdk/hash-node/dist-cjs/index.js:5:25:
      5 │ const buffer_1 = require("buffer");
        ╵                          ~~~~~~~~

  The package "buffer" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "--platform=node" to do that, which will remove this error.
```

### SDK version number

@aws-sdk/client-chime-messaging-sdk@3.210.0

### Which JavaScript Runtime is this issue in?

Browser

### Details of the browser/Node.js/ReactNative version

v14.20.0

### Reproduction Steps

- Create or use a browser application
- Include esbuild and either @aws-sdk/client-chime-messaging-sdk@3.210.0 or the amazon-chime-sdk-js@3.8.0
- Attempt to bundle using npx esbuild src/app.ts --bundle --outfile=out.js --define:browser=true --platform=browser --format=esm

### Observed Behavior

Fails to bundle

### Expected Behavior

Application should bundle successfully as a browser application.

### Possible Solution

I've also created an issue to EsBuild as this might be a bundler issue. https://github.com/evanw/esbuild/issues/2692

**Comment by yenfryherrerafeliz** [comment]
Hi @LeviSklaroff, thanks for opening this issue. I tried to reproduce the reported behavior but I could not. What I did was:

- I Initialized a new project with ```npm init project-name```
- Then, I installed ```@aws-sdk/client-chime-sdk-messaging": "^3.216.0"``` by running ```npm i @aws-sdk/client-chime-sdk-messaging@3.216.0```
- Then, I installed esbuild by running ```npm i esbuild```
- Then, I created a ts file and used the sdk:
    ```js
        import {
            ChimeSDKMessagingClient,
            ListTagsForResourceCommand
        } from "@aws-sdk/client-chime-sdk-messaging";
    
        const client = new ChimeSDKMessagingClient({
            region: 'us-east-2'
        });
        (async () => {
            const response = await client.send(new ListTagsForResourceCommand({
                ResourceARN: 'RESOURCE_ARN'
            }));
        })();
    ```
- Then, I ran ```npx esbuild src/app.ts --bundle --outfile=out.js --define:browser=true --platform=browser --format=esm```

- And I got good results:
    ```console
       [PROJECT_DIR]$ npx esbuild src/app.ts --bundle --outfile=out.js --define:browser=true --platform=browser --format=esm 
     
       out.js  259.0kb
    
   ⚡ Done in 77ms
    ```
I see you  got a workaround in the following [thread](https://github.com/aws/amazon-chime-sdk-js/issues/2494), so, does that solve your issue?, if not, could you please provide any other details I may be missing to reproduce this error.

Thanks!

**Comment by asquithea** [comment]
I had this issue too.

I was using Serverless Framework to build the backend using essentially these settings:

```
esbuild:
  outputFileExtension: .mjs
  format: esm
```

This results in the CJS distribution being bundled.

Changing to this (per https://github.com/evanw/esbuild/issues/2692) helped:

```
esbuild:
  outputFileExtension: .mjs
  format: esm
  mainFields: ["browser", "module", "main"]
```

Positive suggestion that might help with these support queries:

Almost everyone is going to be trying to use this library in the context of another popular framework. For example, if you're doing serverless development, you're likely going to be on SAM, Serverless Framework, or SST. Or for the front end, React, Angular, NextJS...

If you knock up a couple of small but realistic projects (e.g. including a few legacy CJS libraries) and try to set them up per the documentation for Node 18 with ESM, I think it will help surface issues that people are running into - and has the added benefit that you can point folks at these demos to tell them how to set their builds up correctly.

**Comment by WtfJoke** [comment]
Affected by this too, related issue: https://github.com/aws/aws-cdk/issues/29310

Example-Repo with reproducer (SSM client) can be found here: https://github.com/WtfJoke/cdk-nodejs-esm-bug-reproducer/blob/main/lib/hello.ts

**Comment by kuhe** [comment]
we added additional bundling support in https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.592.0, please open a new issue if encountering a bundling problem with that version or later.

recent bundling issues are unrelated to this original report from 2022
