### ISSUE TITLE
3.209.0 introduces marshalling issue

### ISSUE THREAD

**Issue by adrai** [aws/aws-sdk-js-v3#4222]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Updating from 3.208.0 to 3.209.0 has issues when the retrieved object in dynamodb contain null values.

```js
import { DynamoDBClient } from '@aws-sdk/client-dynamodb'
import { DynamoDBDocumentClient, GetCommand } from '@aws-sdk/lib-dynamodb'

const ddbClient = DynamoDBDocumentClient.from(new DynamoDBClient({ region: 'eu-west-1' }), {
  marshallOptions: {
      removeUndefinedValues: true
  }
})

const org = (await ddbClient.send(new GetCommand({
  TableName: 'my-table-for-organisations',
  Key: { id }
}))).Item
console.log(org)
// org is looking like this in dynamodb:
// {
//  "id": "b512877f-e373-454f-87ee-7385c5ef51dc",
//  "address": {
//     "city": "Perugia",
//     "country": "IT",
//     "line1": "Via XYZ",
//     "postalCode": "06121",
//     "state": null
//   },
//   taxNumber: null
// }
```

generates:
```
TypeError: Cannot read properties of null (reading 'S')
    at AttributeValueFilterSensitiveLog (/var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/models/models_0.js:1328:13)
    at /var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/models/models_0.js:1414:128
    at Array.reduce (<anonymous>)
```

### SDK version number

@aws-sdk/client-dynamodb@3.209.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.13.1

### Reproduction Steps

```js
import { DynamoDBClient } from '@aws-sdk/client-dynamodb'
import { DynamoDBDocumentClient, GetCommand } from '@aws-sdk/lib-dynamodb'

const ddbClient = DynamoDBDocumentClient.from(new DynamoDBClient({ region: 'eu-west-1' }), {
  marshallOptions: {
      removeUndefinedValues: true
  }
})

const org = (await ddbClient.send(new GetCommand({
  TableName: 'my-table-for-organisations',
  Key: { id }
}))).Item
console.log(org)
// org is looking like this in dynamodb:
// {
//  "id": "b512877f-e373-454f-87ee-7385c5ef51dc",
//  "address": {
//     "city": "Perugia",
//     "country": "IT",
//     "line1": "Via XYZ",
//     "postalCode": "06121",
//     "state": null
//   },
//   taxNumber: null
// }
```

### Observed Behavior

generates:
```
TypeError: Cannot read properties of null (reading 'S')
    at AttributeValueFilterSensitiveLog (/var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/models/models_0.js:1328:13)
    at /var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/models/models_0.js:1414:128
    at Array.reduce (<anonymous>)
```

### Expected Behavior

should marshall without errors

### Possible Solution

downgrade to 3.208.0

### Additional Information/Context

see https://github.com/aws/aws-sdk-js-v3/issues/4222#issuecomment-1326720155

maybe also related: #3846, #4237

**Comment by bluepeter** [comment]
Experiencing this issue as well. I am getting frustrated by the continuing cadence of serious bugs from v3... almost to the point of going back to v2.

**Comment by adrai** [comment]
fyi: changing this line seems to fix it

https://github.com/aws/aws-sdk-js-v3/blob/246d6534c53dcf9bd2eb6a620cb5b6c04b27451a/clients/client-dynamodb/src/models/models_0.ts#L11030
```diff
-[key]: AttributeValueFilterSensitiveLog(value),
+[key]: value ? AttributeValueFilterSensitiveLog(value) : undefined,
```

// cc: @kuhe @trivikr

**Comment by tushar-sg** [comment]
facing the same issue in the latest "3.216.0".

**Comment by avegao** [comment]
I can confirm that latest version 3.216.0 still broken and with 2.208 works as expected

**Comment by yenfryherrerafeliz** [comment]
Hi @adrai, thanks for opening this issue. I can confirm this is a bug and seems to be happening due to the loggerMiddleware, we need to do a deeper investigation to understand what the problem is, however, as workaround we could either turn off the info logger by doing the following:
Just pass the following parameter to the client:
```js
 logger: {
     info: undefined
 }
```
Example:
```js
const ddbClient = DynamoDBDocumentClient.from(
    new DynamoDBClient({
        region: 'us-east-2',
        logger: {
            info: undefined
        }
    }), {
    marshallOptions: {
        removeUndefinedValues: true
    }
});
```

Or you could also use the DynamoDBClient without DynamoDBDocumentClient.

I will provide more updates as soon as get them.

Thanks!

**Comment by yenfryherrerafeliz** [comment]
Repro Steps:

- Put a record with a null value into a dynamodb table:
```js
import {DynamoDBClient, PutItemCommand} from '@aws-sdk/client-dynamodb'
import { DynamoDBDocumentClient, GetCommand } from '@aws-sdk/lib-dynamodb'

const ddbClient = DynamoDBDocumentClient.from(
    new DynamoDBClient({
        region: 'us-east-2'
    }), {}
);
const response = await ddbClient.send(new PutItemCommand({
    TableName: 'test-table',
    Item: {
        name: {
            NULL: true
        },
        id: {
            S: 'UID-10202020202021'
        }
    }
}))

console.log(response);

```
- Then, lets try to get that same item:
```js
import {DynamoDBClient, PutItemCommand} from '@aws-sdk/client-dynamodb'
import { DynamoDBDocumentClient, GetCommand } from '@aws-sdk/lib-dynamodb'

const ddbClient = DynamoDBDocumentClient.from(
    new DynamoDBClient({
        region: 'us-east-2',
    }), {
    marshallOptions: {
        removeUndefinedValues: true
    }
});
const response = await ddbClient.send(new GetCommand({
    TableName: 'test-table',
    Key: {
        id: 'UID-10202020202021'
    }
}))

console.log(response);
```
- And we get:
```console
PROJECT_DIR/node_modules/@aws-sdk/client-dynamodb/dist-cjs/models/models_0.js:1328
    if (obj.S !== undefined)
            ^

TypeError: Cannot read properties of null (reading 'S')
    at AttributeValueFilterSensitiveLog (PROJECT_DIR/node_modules/@aws-sdk/client-dynamodb/dist-cjs/models/models_0.js:1328:13)
    at PROJECT_DIR/node_modules/@aws-sdk/client-dynamodb/dist-cjs/models/models_0.js:1414:128
    at Array.reduce (<anonymous>)
    at GetItemOutputFilterSensitiveLog (PROJECT_DIR/node_modules/@aws-sdk/client-dynamodb/dist-cjs/models/models_0.js:1414:40)
    at PROJECT_DIR/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:16:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file://PROJECT_DIR/src/getItem.js:12:18

Node.js v18.3.0

```

**Comment by yenfryherrerafeliz** [comment]
Hello @adrai, I have not updates yet. I have reviewed your proposed solution and I agree it could fix the problem, however, this still needs to be reviewed by the team. I will provide updates as soon as possible.

Thanks!

**Comment by RanVaknin** [comment]
@yenfryherrerafeliz ,

This was brought up [here](https://github.com/aws/aws-sdk-js-v3/issues/3846) and it is a known issue and assigned a `p0`. Someone is working on a fix for it so feel free to close this ticket in favor of tracking it on the initial ticket.

@avegao @adrai @bluepeter @tushar-sg Please comment on issue as well so it will be clear that this is impacting more people.

Thank you,
Ran~

**Comment by adrai** [comment]
@RanVaknin since the used SDK version is different, I don't thing the root cause of that issue is the same...
Would love to keep both open in that case.
3.209.0 introduced that issue for me... and the other issue is related to 3.142.0

**Comment by asnaeb** [comment]
Facing this issue as well. A temporary solution while the cause has been found might as well be changing

https://github.com/aws/aws-sdk-js-v3/blob/246d6534c53dcf9bd2eb6a620cb5b6c04b27451a/clients/client-dynamodb/src/models/models_0.ts#L10885
 and its siblings to
```js
if (obj?.S !== undefined) return { S: obj.S };
```

**Comment by kuhe** [comment]
opened a PR with a fix: https://github.com/aws/aws-sdk-js-v3/pull/4249
