### ISSUE TITLE
Multipart Upload using XhrHttpHandler is inconsistent and fails randomly in Firefox

### ISSUE THREAD

**Issue by coccoalberto97** [aws/aws-sdk-js-v3#4226]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When using `XhrHttpHandler` for uploading files with a size > 5 MB in firefox using Multipart upload it randomly fails (looks like a 50% chance with 2 parts with a 6MB file).

Looks like there is a race condition happening after combining the responses for every part.
 

### SDK version number

@aws-sdk/xhr-http-handler@3.198.0, @aws-sdk/lib-storage@3.198.0, @aws-sdk/client-s3@3.198.0

### Which JavaScript Runtime is this issue in?

Browser

### Details of the browser/Node.js/ReactNative version

Firefox 107.0

### Reproduction Steps

Try to upload an image or a video with a size > 5 MB in Firefox using `XhrHttpHandler`, `S3Client`, and `Upload` from aws-sdk.

```js

import {S3Client} from "@aws-sdk/client-s3";
import {Upload} from "@aws-sdk/lib-storage";
import {XhrHttpHandler} from "@aws-sdk/xhr-http-handler";

[...] Code 

const requestHandler: any = new XhrHttpHandler({});

const client = new S3Client({
        requestHandler,
        region:  "us-east-1",
        credentials: {
            accessKeyId: "accessKeyId",
            secretAccessKey: "secretAccessKey",
            sessionToken: "sessionToken"
        }
    });

    const multipartUpload = new Upload({
        client,
        params: {
            Bucket: "BUCKET_NAME",
            Key: "key",
            Body: blob
        },
        leavePartsOnError: true,
        abortController: abortController as any
    });

    let response: any;

   try{
     response = await multipartUpload.done();  // <-- this is throwing the error
    }catch(e){
        console.error(e);
        throw e;
    }
return response.ETag;

```

### Observed Behavior

The Upload randomly fails even when every request returns 200 success. 

Error: 

```
 TypeError: parsedObjToReturn is undefined
    parseBody Aws_restXml.js:9888
    promise callback*parseBody Aws_restXml.js:9871
    deserializeAws_restXmlCompleteMultipartUploadCommand Aws_restXml.js:2951
    deserialize CompleteMultipartUploadCommand.js:50
    deserializerMiddleware deserializerMiddleware.js:4
    awsAuthMiddleware middleware.js:10
    retry StandardRetryStrategy.js:47
    retryMiddleware retryMiddleware.js:5
    userAgentMiddleware user-agent-middleware.js:27
    recursionDetectionMiddleware index.js:10
    hostHeaderMiddleware index.js:17
    addExpectContinueMiddleware index.js:11
    contentLengthMiddleware index.js:23
    serializerMiddleware serializerMiddleware.js:9
    endpointMiddleware endpointMiddleware.js:16
    ssecMiddleware index.js:32
    validateBucketNameMiddleware validate-bucket-name.js:10
    loggerMiddleware loggerMiddleware.js:3
    send client.js:17
    __doMultipartUpload Upload.js:213
    done Upload.js:35
```
![Screenshot 2022-11-24 at 16 46 44](https://user-images.githubusercontent.com/30443179/203823881-ad327410-2aee-406c-9c18-9934ab4d4495.png)

### Expected Behavior

In Firefox It should complete the upload without error when every put request returns 200 as like in every other browser.

### Additional Information/Context

Using multipart Upload in React typescript application.

**Comment by coccoalberto97** [comment]
I think this might help you find the root cause

In xhrHttpHandler sometimes in the loading hook of the `handle` function
```
case XMLHttpRequest.LOADING:
    if (isText) {
        writer.write(streamCursor > 0 ? xhr.responseText.slice(streamCursor) : xhr.responseText);
        streamCursor = xhr.responseText.length;
    }
break;
```
`xhr.responseText` does not contain the whole response but only the XML definition line 

this:

```
<?xml version="1.0" encoding="UTF-8"?>
```
instead of this:

```
<?xml version="1.0" encoding="UTF-8"?>

<CompleteMultipartUploadResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Location>data.jpg</Location><Bucket>bucket</Bucket><Key>data.jpg</Key><ETag>&quot;ETAG&quot;</ETag></CompleteMultipartUploadResult>
```

When it writes (`writer.write`) only the first raw Uploader throws an error.

As a workaround, I changed the `TransformStream` to enqueue only at the `done` hook.

**Comment by aBurmeseDev** [comment]
Hi @coccoalberto97 - apologies for the long silence here. 

Firstly, I wanted to confirm if you have tried using the latest version of the AWS SDK, as this issue may have been addressed in a more recent release. 

Additionally, have you had the opportunity to test with alternative HTTP handlers, such as the NodeHttpHandler? It would be helpful to know if the issue persists with different HTTP handlers or if it is specific to the `XhrHttpHandler`.

By gathering this additional information, we can better understand the scope of the issue and potentially identify workarounds or alternative solutions. If the issue is still present in the latest SDK version and occurs across multiple HTTP handlers, we can explore further investigation and potentially report it to the AWS SDK team for their consideration.
