### ISSUE TITLE
DynamoDB ConditionalCheckFailedException use case description incorrect

### ISSUE THREAD

**Issue by RossWilliams** [aws/aws-sdk-js-v3#4228]
### Describe the issue

client-dynamo db includes a comment for ConditionalCheckFailedException

```
/**
 * <p>A condition specified in the operation could not be evaluated.</p>
 */
```

This comment is valid for the exception when it is thrown for violations of `ExpectedAttributeValue.Exists`, a legacy parameter.

However, this exception is also created when `ConditionExpression` evaluates to false. In this case the description of the exception is not correct, since the the condition was in fact evaluated.

The description in the developer guide for `ConditionalCheckFailedException` is accurate. See:
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.Errors.html

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/classes/conditionalcheckfailedexception.html

**Comment by yenfryherrerafeliz** [comment]
Hi @RossWilliams, thanks for opening this issue. The API reference for DynamoDB [here](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PutItem.html#API_PutItem_Errors) says the same:
>ConditionalCheckFailedException
    A condition specified in the operation could not be evaluated.
    HTTP Status Code: 400

I guess it also refers that the condition failed or was not true, but I agree it ca be confusing. I will pass your feedback to the correspondent team.

Thanks!
