### ISSUE TITLE
AppSync EvaluateCodeCommand throws 403

### ISSUE THREAD

**Issue by riywo** [aws/aws-sdk-js-v3#4229]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The simple command below returns 403. Nothing is recorded on CloudTrail.

### SDK version number

@aws-sdk/client-appsync 3.216.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.11.0

### Reproduction Steps

```js
import {
  AppSyncClient,
  EvaluateCodeCommand,
  RuntimeName,
} from "@aws-sdk/client-appsync";

const client = new AppSyncClient({
  region: "us-west-2",
});

const command = new EvaluateCodeCommand({
  runtime: {
    name: RuntimeName.APPSYNC_JS,
    runtimeVersion: "1.0.0",
  },
  code: "console.log()",
  context: "{}",
  function: "request",
});

await client.send(command);
```

### Observed Behavior

```
ForbiddenException: Forbidden
    at throwDefaultError (/workspaces/w/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at deserializeAws_restJson1EvaluateCodeCommandError (/workspaces/w/node_modules/@aws-sdk/client-appsync/dist-cjs/protocols/Aws_restJson1.js:2025:51)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /workspaces/w/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /workspaces/w/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20
    at async StandardRetryStrategy.retry (/workspaces/w/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /workspaces/w/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at async file:///workspaces/w/test.mjs:22:1 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 403,
    requestId: 'df932c30-e9a7-44ac-9b91-8af3d24bd6c5',
    extendedRequestId: undefined,
    cfId: 'gC70HQTJrE3F_S7Q6x3HEpt5bfbQtAgUtEXx52l7ZaaAePrnTK0mUQ==',
    attempts: 1,
    totalRetryDelay: 0
  }
}
```

### Expected Behavior

Return 200.

### Possible Solution

No idea.

### Additional Information/Context

SDK v2 works:

```js
const AWS = require("aws-sdk");

const client = new AWS.AppSync({
  region: "us-west-2",
});

client
  .evaluateCode({
    runtime: {
      name: "APPSYNC_JS",
      runtimeVersion: "1.0.0",
    },
    code: "console.log()",
    context: "{}",
    function: "request",
  })
  .promise()
  .then(console.log)
  .catch(console.error);
```

**Comment by yenfryherrerafeliz** [comment]
Hi @riywo, thanks for opening this issue. I can confirm that this issue was bug in a previous version where the path of the request was missing some information, but it was fixed with the following [commit](https://github.com/aws/aws-sdk-js-v3/commit/8fd2c31ddb3f50d4974b86937303ea0d802d4f08). So, please update to the latest version and the problem should be gone.

Thanks!
