### ISSUE TITLE
Chime SDK Messaging Using filter rules to filter messages not working?

### ISSUE THREAD

**Issue by ReflexFox** [aws/aws-sdk-js-v3#4233]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I want to try to develop users private chat feature in one chime channel so i found [filter-msgs](https://docs.aws.amazon.com/chime-sdk/latest/dg/filter-msgs.html)
but not working

https://docs.aws.amazon.com/chime-sdk/latest/dg/filter-msgs.html 

https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_messaging-chime_PutChannelMembershipPreferences.html
https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_messaging-chime_SendChannelMessage.html

### SDK version number

@aws-sdk/package-name@version, ...

### Which JavaScript Runtime is this issue in?

Browser

### Details of the browser/Node.js/ReactNative version

chrome 107.0.5304.110 (arm64)

### Reproduction Steps

UserA Call PutChannelMembershipPreferences API Result 
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/42571543/204225143-858deb5b-d61e-4c3d-bfce-b158335e5627.png">

UserA Call SendChannelMessage API Payload 
<img width="976" alt="image" src="https://user-images.githubusercontent.com/42571543/204225950-62467458-ef00-49c2-8ab8-8776785e24a8.png">

UserB Call PutChannelMembershipPreferences API Result
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/42571543/204225026-55632f9d-2080-4319-a377-808c4c3943f9.png">
UserB in messagingSessionDidReceiveMessage Callback Received Message
headers: {x-amz-chime-event-type: 'CREATE_CHANNEL_MESSAGE', x-amz-chime-message-type: 'STANDARD'}
payload: "{\"Content\":\"test\",\"Persistence\":\"PERSISTENT\",\"Redacted\":false,\"LastUpdatedTimestamp\":\"2022-11-28T08:07:03.073Z\",\"Sender\":{\"Name\":\"zhiXXXXX\",\"Arn\":\"arn:aws:chime:us-east-1:561263042312:app-instance/77aac046-e9ee-4a3c-9ad2-8f48d6b6e633/user/zhiXXXXXX\"},\"Type\":\"STANDARD\",\"MessageId\":\"9f89d0de502ddd50fa0db4df671872e26b9eb3182e83031ed48e38dd4e1f8ee3\",\"CreatedTimestamp\":\"2022-11-28T08:07:03.073Z\",\"Status\":{\"Value\":\"SENT\"},\"ChannelArn\":\"arn:aws:chime:us-east-1:561263042312:app-instance/77aac046-e9ee-4a3c-9ad2-8f48d6b6e633/channel/93e1014fc35cbe3f9c98ecd34a10898e5a38b979c5bb14fcfadc524d99024229\",\"Metadata\":\"{\\\"uuid\\\":\\\"49640437-a793-4bb9-af56-facb1a48b71d\\\",\\\"target\\\":\\\"direct\\\",\\\"receiver\\\":\\\"yangXXXXXXX\\\"}\",\"MessageAttributes\":{\"type\":{\"StringValues\":[\"yangXXXXXXXX\"]}}}"
type: "CREATE_CHANNEL_MESSAGE"

### Observed Behavior

UserB in messagingSessionDidReceiveMessage Callback Receives the message sent by UserA

### Expected Behavior

UserB in messagingSessionDidReceiveMessage Callback cannot receive UserA message Because UserA message payload has MessageAttributes

**Comment by ReflexFox** [comment]
SDK version number
"@aws-sdk/client-chime-sdk-messaging": "^3.194.0",

**Comment by yenfryherrerafeliz** [comment]
Hi @ReflexFox, thanks for opening this issue. Could you please confirm you are using the AWS SDK for JavaScript V3?, if so, could you please provide a sample code that we can use to reproduce the reported behavior?

Note: Please redact any sensitive information.

Thanks!
