### ISSUE TITLE
client-provider-env should detect non reserved names from Vercel

### ISSUE THREAD

**Issue by middleFiddle** [aws/aws-sdk-js-v3#4239]
### Describe the feature

I'd like a way to declare  custom env-var names for the defaultProvider

### Use Case

I can't ship a feature because of environmental variable naming convention issues.  Vercel deployments do not allow the use of AWS_ACCESS_KEY_ID or AWS_SECRET_ACCESS_KEY.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.202

### Environment details (OS name and version, etc.)

Ubuntu 20.04.5 Focal Fossa (wsl2)

**Comment by magoz** [comment]
Same here. What's the recommended workaround?
