### ISSUE TITLE
Refactor socket timeout, certificates, and other configuration currently held by RequestHandler.

### ISSUE THREAD

**Issue by everett1992** [aws/aws-sdk-js-v3#4245]
### Describe the feature

If a client user wants to configure the connection timeout, socket timeout, http keep alive, or certificates used by a client they have to construct a RequestHandler and pass it  to client configuration

### Use Case

If the user just wants to provide a cacert they have to overrides the defaults for all other settings, including picking the RequestHandler implementation which is normally based on environment (browser, native, node) but also requires knowledge from the services definition ([eg http1.1 vs h2](https://github.com/aws/aws-sdk-js-v3/blob/main/codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddHttp2Dependency.java#L48))

```js
new ExampleClient({
  requestHandler: new NodeHttpHandler({
    connectionTimeout,
    socketTimeout,
    httpAgent: new http.Agent({ keepAlive: true }),
    httpsAgent: new https.Agent({ cacert, keepAlive: true })
  })
})
```

### Proposed Solution

I propose hoisting these configuration points into the constructor

```js
new ExampleClient({
  connectionTimeout?: number | Provider<number>,
  socketTimeout?: number | Provider<number>,
  keepAlive?: boolean | Provider<boolean>,
  ca?: string | Buffer | ...,
  requestHandler?: (options) => Requesthandler,
})
```

Clients would have defaults for each of these values, the options would be fed into the requestHandler function.
RequestHandlers could ignore or warn when an unsupported feature is used (like setting ca with a FetchHttpAgent).

### Other Information

This affects both aws-sdk's and smithy-typescript generic clients.

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### SDK version used

3.222.0

### Environment details (OS name and version, etc.)

linux

**Comment by Litee** [comment]
How about an alternative? We could define `httpsAgentOptionOverrides` property in the constructor instead.

**Comment by yenfryherrerafeliz** [comment]
Hi @everett1992, thanks for opening this feature request. I understand that this could be a nice feature to have, but I have discussed with the team about it, and at this time there is not intention to implement this feature request, at least in the near future.

Thanks!

**Comment by kuhe** [comment]
@everett1992 constructor passthrough is available now https://github.com/aws/aws-sdk-js-v3/blob/main/supplemental-docs/CLIENTS.md#new-in-v35210

```ts
// Example: short form requestHandler configuration.
import { DynamoDBClient } from "@aws-sdk/client-dynamodb";

const client = new DynamoDBClient({
  requestHandler: {
    requestTimeout: 3_000,
    httpsAgent: { maxSockets: 25 },
  },
});
```
