### ISSUE TITLE
Add some common message in case of network error in xhr-http-handler

### ISSUE THREAD

**Issue by andrei-hameza** [aws/aws-sdk-js-v3#4250]
### Describe the feature

It would be great to get some certain error message in case of network error in xhr-http-handler.

### Use Case

I use aws-sdk-js-v3 to make requests to aws firehose. Many of our users experience network connection problems from time to time(especially iOS). As a result a request can fail. I create instance of StandardRetryStrategy with my version of retryDecider to take this problem into account. To match network errors I use the next regexp:
```typescript
const errorMessageRegex = new RegExp(/failed to fetch|load failed|network error/i)

const retryDecider: RetryDecider = (error) => {
  if (errorMessageRegex.test(error.message)) {
    return true
  }

  return defaultRetryDecider(error)
}
```
However, sometimes it doesn't help, because a browser can provide a localised version of the messages above(ex. "TypeError: Veza s mrežom je prekinuta.") or just empty message.

So, I need some common message in case of network error to match it properly and to make a retry.

### Proposed Solution

For example, axios has the next implementaion:
```typescript
// Handle low level network errors
request.onerror = function handleError() {
  // Real errors are hidden from us by the browser
  // onerror should only fire if it's a network error
  reject(new AxiosError('Network Error', AxiosError.ERR_NETWORK, config, request));

  // Clean up request
  request = null;
};
```

I suggest to implement something similar to it.
```typescript
xhr.addEventListener("error", reject(new Error("Network Error")));
```
https://github.com/aws/aws-sdk-js-v3/blob/main/packages/xhr-http-handler/src/xhr-http-handler.ts#L133

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.216.0

### Environment details (OS name and version, etc.)

iOS, Android, MacOS

**Comment by andrei-hameza** [comment]
@ajredniwja Any updates on it? Still need it so much & can implement myself if you don't mind.

**Comment by andrei-hameza** [comment]
@kuhe Thx a lot!

**Comment by andrei-hameza** [comment]
@kuhe @yenfryherrerafeliz 
Could I ask you to add one more piece of code? My bad, current solution is not full.

Reason:
`readystatechange` event fires BEFORE `error` event. As a result promise will be resolved (not rejected) because `xhr.readyState` is equal to XMLHttpRequest.DONE. 

https://github.com/aws/aws-sdk-js-v3/blob/main/packages/xhr-http-handler/src/xhr-http-handler.ts#L141-L142

Solution:
Add additional check for `xhr.status` in case of XMLHttpRequest.DONE state. If `status === 0` the promise shouldn't be resolved and further action should be delegated to `onerror` handler.

Again, axios library has smth similar:
https://github.com/axios/axios/blob/v1.x/lib/adapters/xhr.js#L125

Thanks.

**Comment by kuhe** [comment]
@andrei-hameza could you submit a PR for this change?

**Comment by andrei-hameza** [comment]
@kuhe Yes, I can
