### ISSUE TITLE
Can't compile with @aws-sdk/client-dynamodb v3.222.0

### ISSUE THREAD

**Issue by tinvm** [aws/aws-sdk-js-v3#4254]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug
when i'm trying to import 'aws-sdk/client-dynamodb' to my project. When compile i get an error: 

![image](https://user-images.githubusercontent.com/13530763/205573488-e29c5bdd-5285-49f2-8e07-f0bf8c89a155.png)

### SDK version number

@aws-sdk/client-dynamodb @3.222.0

### Which JavaScript Runtime is this issue in?

Browser

### Details of the browser/Node.js/ReactNative version

Vue.js v2 and antdv freamwork

### Reproduction Steps

vue-cli-service serve

### Observed Behavior

compile

### Expected Behavior

crash app

**Comment by ajredniwja** [comment]
Hey @tinvm thanks for opening this issue, the description lacks reproduction steps with VueJs can you please add minimal reproducible code of how you are importing the SDK or setup a repo? 

Previously, I have seen some problems with web-pack with VueJs but would need to replicate before coming to a conclusion. 

Also see: https://vuejs.org/guide/scaling-up/tooling.html
