### ISSUE TITLE
Allow non-aws-service clients to use endpoint middleware. 

### ISSUE THREAD

**Issue by everett1992** [aws/aws-sdk-js-v3#4255]
### Describe the feature

Allow services without the aws.api#service trait to use the `Endpoint` middleware and runtime client plugin rather than `CustomEndpoints`.

### Use Case

The CustomEndpoints middleware adds a required `endpoint` [input config](https://github.com/aws/aws-sdk-js-v3/blob/main/packages/config-resolver/src/endpointsConfig/resolveCustomEndpointsConfig.ts#L10) so callers _must_ provide an endpoint. Because it is an endpoint config other middleware or runtime config plugins cannot add defaults or default providers and callers will _always_ have to provide the endpoint.

`smithy.rules#endpointRuleSet` is an undocumented model trait that defines parameterized endpoint and auth configuration. The trait is [not documented](https://awslabs.github.io/smithy/2.0/spec/index.html) but are used in [aws models](https://github.com/aws/aws-sdk-js-v3/blob/main/codegen/sdk-codegen/aws-models/accessanalyzer.json#L89).

Aside from allowing runtime configuration of endpoints based on multiple parameters, rather than requiring a endpoint, the endpointRuleSet trait can configure [auth scheme](https://github.com/aws/aws-sdk-js-v3/blob/main/packages/middleware-signing/src/middleware.ts#L26) which could be used to disable sigv4 auth added by including a `aws.auth#sigv4` trait in a model for services that support different auth schemes on different endpoints. As far as I know this is not possible with the  CustomEndpoints middleware.

### Proposed Solution

Update [this code](https://github.com/aws/aws-sdk-js-v3/blob/main/codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddBuiltinPlugins.java#L54-L69) to add `Endpoint` for any model with endpoint v2, not just aws services.

Also requires https://github.com/awslabs/smithy-typescript/pull/644 else code gen will fail if the model does not have a aws.api#service trait. 

If this proposal cannot be implemented an alternative would be to allow non-aws service clients to opt-out of the `CustomEndpoints` middleware and use runtime configuration to disable sigv4.

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### SDK version used

smithy-aws-typescript-codegen 0.12.0

### Environment details (OS name and version, etc.)

N/A

**Comment by ajredniwja** [comment]
Hey @everett1992 thanks for opening this feature request, I am not sure about if this will be picked up by the team soon but I can have a discussion with them. Tagging it for review with the SDK team.

**Comment by kuhe** [comment]
Shouldn't be any issue in only requiring a ruleset trait. PR welcome.
