### ISSUE TITLE
DAX Support fo V3 SDK

### ISSUE THREAD

**Issue by paul-uz** [aws/aws-sdk-js-v3#4263]
### Describe the feature

The v3 SDK does not support DAX, as confirmed here https://github.com/aws/aws-sdk/issues/232

### Use Case

I want to use DAX with the v3 SDK

### Proposed Solution

Implement support for DAX in v3

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

v3

### Environment details (OS name and version, etc.)

Lambda Node 18

**Comment by kellertk** [comment]
Hi there! As discussed here https://github.com/aws/aws-sdk/issues/232, this client implemented as a separate (closed source) software package and is not released as an SDK component. At this time we have no plans to implement a DAX client in the SDK natively, but I'll keep this issue open for tracking purposes.

**Comment by paul-uz** [comment]
I've opened this feature request to get it added to the SDK, or at least have v3 support the current DAX library.

If it's not going to be supported, what exactly are people supposed to do?

As I've said before, going back to the v2 SDK just for DAX is not an acceptable solution, and I'm sure others will agree.

Why the hesitancy to support DAX in the v3 SDK?

**Comment by rizowski** [comment]
If this isn't supported for V3, we are blocked from further upgrading our node version on lambda since the aws-sdk v2 isn't bundled in the node 18 environment and we use that to minimize our deployment size.

**Comment by paul-uz** [comment]
> If this isn't supported for V3, we are blocked from further upgrading our node version on lambda since the aws-sdk v2 isn't bundled in the node 18 environment and we use that to minimize our deployment size.

Looks like you a sh*t out of luck then as its been confirmed they are not going to support DAX with V3.

**Comment by paul-uz** [comment]
@kellertk can we get an update?

Where can we address the team responsible for the Dax client that uses the v2 SDK (`aws-sdk`)?

What is their reasoning for not wanting to write an updated Dax client for the v3 SDK? Can you confirm if Dax is being canned as a feature? If not, we _need_ a v3 compatible Dax client.

**Comment by RoniqueRicketts** [comment]
Reverting to version 2 of AWS-SDK seems like a pain since we've just moved 3 applications to DynamoDB with hopes to using DAX to speed it up. I was thinking DAX would be the true accelerator to our projects.

**Comment by Blikingor** [comment]
@kellertk, I do feel like I missing something here, considering: 

- AWS SDK v2 going into maintenance mode
- There is [nudging to migrate](https://github.com/aws/aws-sdk-js/pull/4345) to v3 
- The nodejs18.x lambda runtime has [SDK v3 bundled](https://aws.amazon.com/blogs/compute/node-js-18-x-runtime-now-available-in-aws-lambda/) and [Node 16 LTS ends in September](https://nodejs.dev/en/about/releases/).

Is [amazon-dax-client](https://www.npmjs.com/package/amazon-dax-client) the only way of using DAX from a nodejs lambda? How are we suppose to use DAX from a nodejs18.x lambda function without bloating it with SDKv2?

**Comment by paul-uz** [comment]
> @kellertk, I do feel like I missing something here, considering: 
> 
> - AWS SDK v2 going into maintenance mode
> - There is [nudging to migrate](https://github.com/aws/aws-sdk-js/pull/4345) to v3 
> - The nodejs18.x lambda runtime has [SDK v3 bundled](https://aws.amazon.com/blogs/compute/node-js-18-x-runtime-now-available-in-aws-lambda/) and [Node 16 LTS ends in September](https://nodejs.dev/en/about/releases/).
> 
> Is [amazon-dax-client](https://www.npmjs.com/package/amazon-dax-client) the only way of using DAX from a nodejs lambda? How are we suppose to use DAX from a nodejs18.x lambda function without bloating it with SDKv2?

You're not missing anything mate, thats exactly it.

There is no way to use DAX without the v2 SDK.

**Comment by RoniqueRicketts** [comment]
@paul-uz I really think AWS has dropped the ball with this. I really love Dynamodb and I have this e-commerce app built on Dynamodb but looking at my database response I am getting double digit response time I’d love to bring it down to single digits and the only way to do that right now is to downgrade to AWS-JS-v2 that’s sucks. I love Dynamodb db but I think I made an error choosing it for such an important project. 😭😤If they are getting rid of DAX then at least give us another updated tool to use for caching. Unless they want us to stand up some redis DB  for our DynamoDbs. Just merely gorging through this thread shows that a number of developers are using Dynamodb. Come on Amazon make this right.

**Comment by rizowski** [comment]
DAX client appeared on the v3 docs:
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/dax/

I haven't attempted to try it yet.

**Comment by RoniqueRicketts** [comment]
It doesn’t work with version 3 at all. It’s ridiculous.

**Comment by cameck** [comment]
Still no CRUD operation support noted in those docs.Sent from my iPhoneOn Aug 2, 2023, at 3:47 PM, Ronique Ricketts ***@***.***> wrote:﻿
It doesn’t work with version 3 at all. It’s ridiculous.

**Comment by trivikr** [comment]
Closing, as the DynamoDB team, the current owner of npm module [amazon-dax-client](https://www.npmjs.com/package/amazon-dax-client) has no plans to support new major SDK versions in immediate future as per https://github.com/aws/aws-sdk/issues/232#issuecomment-1342031401

**Comment by paul-uz** [comment]
Can we keep this open, please, so we can try and gain traction to get this implemented?

**Comment by poloroid** [comment]
@paul-uz FYI I've opened a case with support today for the feature request, will keep this thread up to date on answers received.

**Comment by poloroid** [comment]
@paul-uz here's unfortunate answer i got from support:

> As far as the V3-only solution, I can confirm it's on the team's roadmap, but there's no timeline I can share for release. In general, support engineers are not privy to when a roadmap item will be released or what the timeline for it would be.
> Currently, the recommendation is to use V2.
> 
> To keep up on the latest releases for AWS services, you can go to the link below. When DynamoDB or DAX makes an update to their service, you'll be able to see an announcement for it.
> [https://aws.amazon.com/new/ ](https://aws.amazon.com/new/)
> 
> I understand that what I've shared above isn't necessarily what you're hoping to hear, but I am creating a feature request internally to add to the support for a release of V3 to use with DAX.

**Comment by paul-uz** [comment]
> @paul-uz here's unfortunate answer i got from support:
> 
> > As far as the V3-only solution, I can confirm it's on the team's roadmap, but there's no timeline I can share for release. In general, support engineers are not privy to when a roadmap item will be released or what the timeline for it would be.
> > Currently, the recommendation is to use V2.
> > 
> > To keep up on the latest releases for AWS services, you can go to the link below. When DynamoDB or DAX makes an update to their service, you'll be able to see an announcement for it.
> > [https://aws.amazon.com/new/ ](https://aws.amazon.com/new/)
> > 
> > I understand that what I've shared above isn't necessarily what you're hoping to hear, but I am creating a feature request internally to add to the support for a release of V3 to use with DAX.

Oh I know. I'm the one that pretty much got this out of them in the end after asking and asking.

**Comment by kellertk** [comment]
> Can we keep this open, please, so we can try and gain traction to get this implemented?

Hi @paul-uz, I'm going to be closing this issue, for the same reason we closed #232. The data plane client for DAX will not be implemented in the AWS SDK, because these are and always have been different codebases. This is analogous to how the [aws/sagemaker-python-sdk](https://github.com/aws/sagemaker-python-sdk) is a separate product from [boto/boto3](https://github.com/boto/boto3), even though they are both AWS Python SDKs, or how the [Amazon Chime JS SDK](https://github.com/aws/amazon-chime-sdk-js) is a different product from the general JS SDK. They are also owned by different teams with different roadmaps. 

Teams within Amazon gather customer feedback to know what work to prioritize. We've provided your feedback to the DAX team, both from here and from Amazon Premium Support, and we've been in contact with the team since then. The DAX team is also a customer of ours - they consume the AWS JS SDK as part of their library - so we will also be working with them to update their software before AWS SDK for JS v2 becomes end of support. I have no specific timelines I can share with you here. You should watch for new releases on the [DAX release page](http://dax-sdk.s3-website-us-west-2.amazonaws.com/), which is where you will find an update once one is released. 

Because no further work in the AWS JS SDK on this issue is possible, I will be closing this. You can continue to provide feedback directly to the DynamoDB team by following the "Feedback" link on the bottom of the DynamoDB page on the AWS Console.
