### ISSUE TITLE
Add mixin to help convert blobs to string

### ISSUE THREAD

**Issue by kuhe** [aws/aws-sdk-js-v3#4265]
### Describe the feature

https://github.com/aws/aws-sdk-js-v3/issues/2252

There is a widely supported request for a convenient way to convert a lambda invocation response (blob) to string.
This can be done with some user code, but we can also apply an official mixin method to make it easier for users.

### Use Case

lambda invocation response payload

### Proposed Solution

apply a mixin similar to the one used for Streaming collectors in https://github.com/aws/aws-sdk-js-v3/tree/main#streams

### Acknowledgements

- [X] I may be able to implement this feature request

### SDK version used

3.222.0

### Environment details (OS name and version, etc.)

all

**Comment by RanVaknin** [comment]
related: https://github.com/aws/aws-sdk-js-v3/issues/2123

**Comment by kuhe** [comment]
- [x] payload blobs (like Lambda::invoke's input and output) now accept strings on input and convert easily to strings on output.
- [ ] the potential second half of this feature would be to make non-payload blobs automatically convert from string to Uint8Array. This can be seen for example in https://github.com/aws/aws-sdk-js-v3/issues/4800.

**Comment by kuhe** [comment]
https://github.com/aws/aws-sdk-js-v3/issues/5181
