### ISSUE TITLE
Aws sdk Connect Client  Issue in react native

### ISSUE THREAD

**Issue by arunraj915** [aws/aws-sdk-js-v3#4268]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I have called '@aws-sdk/client-connect' api in my react native mobile app. And I got this issue
{[TypeError: Network request failed]
 '$metadata': { attempts: 1, totalRetryDelay: 0 },
   line: 21622,
    column: 33}

Here attached my code for reference

<img width="576" alt="code" src="https://user-images.githubusercontent.com/12539988/207045608-a2192b2c-4b36-4911-abe7-5cf48f429915.png">

### SDK version number

@aws-sdk/package-name@version, ...

### Which JavaScript Runtime is this issue in?

React Native

### Details of the browser/Node.js/ReactNative version

react-native: 0.68.2,react-native-cli: 2.0.1

### Reproduction Steps

  const client = new ConnectClient({ region: "REGION", credentials: {
                accessKeyId: '***************',
                secretAccessKey: '*****************'
            } });
            const params = {
                ContactFlowId: "**********************",
                DestinationPhoneNumber: "+18336021681",
                InstanceId: "*************************",
                QueueId: "*****************************",
                Attributes: {"Name": "MyAttribute"},
                };
                  const command = new AssociateApprovedOriginCommand(params);
            try {
                const data = await client.send(command);
               console.log("data");
               console.log(data);
              } catch (error) {
               console.log(error);
               } finally {
                console.log("error");
              }

### Observed Behavior

 ReactNativeJS  { [TypeError: Network request failed]
                             │ '$metadata': { attempts: 1, totalRetryDelay: 0 },
                             │ line: 21622,
                             │ column: 33,
                             └ sourceURL: 'http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.cef&modulesOnly=false&runModule=true' }

### Expected Behavior

I Want to connect call amazon connect through mobile using this  sdk @aws-sdk/client-connect in react native 

### Possible Solution

amazon connect region was singapore. But my claim mobile number was united states

**Comment by arunraj915** [comment]
Hi @RanVaknin,
              Thank you for replied. That issue not came , But I have got another issue. 'BadRequestException: Invalid request body'. Can you help me what param i have missed in this request

**Comment by RanVaknin** [comment]
Hi @arunraj915 ,

Where did you get those parameters from? From the [documentation page](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-connect/interfaces/associateapprovedorigincommandinput.html), `AssociateApprovedOriginCommand` takes only `InstanceId` and `Origin` as input parameters.

I highly suggest you work with an IDE like VS code. You can ctrl+space and it will tell you what kind of arguments you need to pass in to each command:

<img width="821" alt="image" src="https://user-images.githubusercontent.com/50976344/211116156-1c3a851c-a5a4-4c79-832b-7c07d71654d3.png">

For more info on how to use this command please see the [official Connect API Docs](https://docs.aws.amazon.com/connect/latest/APIReference/API_AssociateApprovedOrigin.html)

Thanks,
Ran~
