### ISSUE TITLE
Using an incorrect API ID with the API Gateway management API results in unhelpful `Unexpected token M in JSON at position 0` error

### ISSUE THREAD

**Issue by roblframpton** [aws/aws-sdk-js-v3#4269]
### Checkboxes for prior research

**Update: I made a mistake and was incorrectly using the API ID of a Rest API, not my websocket ID.  I am leaving this open with a new title because I still think this error message is confusing and could probably be cleaner.**

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I am trying to make a call to the API Gateway Management API, using the JavaScript client, from AWS Lambda.  For any call I make (I have tried both `deleteConnection` and `postToConnection`) I am getting the error message `Unexpected token M in JSON at position 0`.  ~I am fairly sure this is a bug, because this error does not correspond to my inputs in any way, and it occurs quite deep in the stack trace.~  This is caused by using the incorrect API ID, but the error message is not at all clear and lead me to investigate other inputs which could have been JSON formatted.

### SDK version number

@aws-sdk/client-apigatewaymanagementapi@3.226.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

nodejs14.x (AWS Lambda)

### Reproduction Steps

This is my AWS Lamba handler:

```typescript
import { ApiGatewayManagementApi } from '@aws-sdk/client-apigatewaymanagementapi';

export const handler: Handler = async (event, context, callback) => {
    const apiGatewayClient = new ApiGatewayManagementApi({
      endpoint: 'https://apiid.execute-api.us-east-2.amazonaws.com',
    });
    await apiGatewayClient.postToConnection({
      ConnectionId: 'some_connection_id',
      Data: Buffer.from('{ data: "some_data" }'),
    });
}
```

Note that at no point am I passing any string which starts with `M`.  ~I'm not sure the `Data` parameter even needs to be JSON formatted anyway, and it gives this error regardless of the input (and I really have tried everything).  It also occurs for the `deleteConnection` call, so I think it is a lower-level issue.  My API id in the `endpoint` parameter is definitely correct.~

### Observed Behavior

The following exception:

```
{
    "errorType": "SyntaxError",
    "errorMessage": "Unexpected token M in JSON at position 0",
    "$metadata": {
        "attempts": 1,
        "totalRetryDelay": 0
    },
    "stack": [
        "SyntaxError: Unexpected token M in JSON at position 0",
        "    at JSON.parse (<anonymous>)",
        "    at /opt/nodejs/node_modules/@aws-sdk/client-apigatewaymanagementapi/dist-cjs/protocols/Aws_restJson1.js:253:21",
        "    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
        "    at async parseErrorBody (/opt/nodejs/node_modules/@aws-sdk/client-apigatewaymanagementapi/dist-cjs/protocols/Aws_restJson1.js:258:19)",
        "    at async deserializeAws_restJson1PostToConnectionCommandError (/opt/nodejs/node_modules/@aws-sdk/client-apigatewaymanagementapi/dist-cjs/protocols/Aws_restJson1.js:161:15)",
        "    at async /opt/nodejs/node_modules/@aws-sdk/client-apigatewaymanagementapi/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24",
        "    at async /opt/nodejs/node_modules/@aws-sdk/client-apigatewaymanagementapi/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20",
        "    at async StandardRetryStrategy.retry (/opt/nodejs/node_modules/@aws-sdk/client-apigatewaymanagementapi/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)",
        "    at async /opt/nodejs/node_modules/@aws-sdk/client-apigatewaymanagementapi/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:5:22"
    ]
}
```

### Expected Behavior

~No exception~  A clearer exception message.

### Possible Solution

I can only assume this in an internal issue, since the error does not correlate with any of my inputs

**Comment by RanVaknin** [comment]
Hi @roblframpton ,

I'm glad to hear that you have unblocked yourself. Regarding an error message, when running your code locally I was able to get a somewhat sensible error message by wrapping the API call with a try catch block:

```js
import { ApiGatewayManagementApi, PostToConnectionCommand } from '@aws-sdk/client-apigatewaymanagementapi';

const apiGatewayClient = new ApiGatewayManagementApi({endpoint: myEndpoint});


try {
    const data = await apiGatewayClient.send(new PostToConnectionCommand({
        ConnectionId: 'some_connection_id',
        Data: Buffer.from('{ data: "some_data" }'),
    }));   
    console.log(data)
} catch (error) {
    console.log(error)
}
```
Output:
```console
NotFoundException: No method found matching route @connections/some_connection_id for http method POST.
```

Hope this helps,
Thanks,
Ran~
