### ISSUE TITLE
Incorrect non-null assertion in region config breaks Smithy awsRestJson users

### ISSUE THREAD

**Issue by RossWilliams** [aws/aws-sdk-js-v3#4270]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

packages/config-resolver/src/regionConfig/resolveRegionConfig.ts includes a non-null type assertion on [line 52](https://github.com/aws/aws-sdk-js-v3/blob/e7b1535fb6707bb84241d0bd21ca339037094246/packages/config-resolver/src/regionConfig/resolveRegionConfig.ts#L52).

The input type for this function does not require a `useFipsEndpoint` property, but if this property is not supplied this method will throw an exception since it will try to call a property that is undefined. This causes issues for users of Smithy which do not want users to configure FIPS endpoints.

Suggest returning false if `useFipsEndpoint` is not defined and removing non-null assertion.

### SDK version number

@aws-sdk/config-resolver@3.228.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

16.8.3

### Reproduction Steps

delete `useFipsEndpoint` config option from any client runtimeConfig.ts file and attempt to execute command

### Observed Behavior

TypeError

### Expected Behavior

No error, `useFipsEndpoint` is optional

### Possible Solution

return false if `useFipsEndpoint` is not defined and removing non-null assertion.

**Comment by eduardomourar** [comment]
The same applies for the `useDualstackEndpoint` property and you can check a reproduction output in the codebuild run [here](https://us-west-2.codebuild.aws.amazon.com/project/eyJlbmNyeXB0ZWREYXRhIjoiYkthUUxndUkzQ2FreVlQVlFaUmM2RWU4SXFrd3VwbStjcGZ5NXhORjFlQ1BnTlU5RmFJcmdwU2FnSGRhdmo0dVhudlM2Tm1rTG02U1NMaGkydU5LZUFiQlNPSTh6cXVxN1Zta2pMdkhINTduIiwiaXZQYXJhbWV0ZXJTcGVjIjoiblFJTmhOdFkzZ2FEZXZSaCIsIm1hdGVyaWFsU2V0U2VyaWFsIjoxfQ%3D%3D/build/36f8f08a-5fcb-432e-b89f-1a2e62d07760).

**Comment by kuhe** [comment]
We will use the linked PR as the fix, I plan to merge it later today.
