### ISSUE TITLE
Unable to download latest version from npm

### ISSUE THREAD

**Issue by buttaravi** [aws/aws-sdk-js-v3#4275]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

sh-3.2$ npm install
Debugger attached.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @aws-sdk/credential-provider-node@3.229.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

### SDK version number

@aws-sdk/credential-provider-node@3.229.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.15.1

### Reproduction Steps

add @aws-sdk/credential-provider-node@3.229.0 as dependency in package json
run npm install

### Observed Behavior

Looks like new version published one hour ago. It started failing to find the new version. 

### Expected Behavior

Should find and download latest one published to npm

**Comment by RanVaknin** [comment]
Hi @buttaravi 

I'm not entirely sure about why you are running into this.

Can you share the contents of your `package.json` file?
Maybe you are adding that dependency wrong.

You can try removing that dependency from your `package.json` file, and run 
```
npm i @aws-sdk/credential-provider-node@3.229.0
```

Thanks,
Ran~
