### ISSUE TITLE
removeUndefinedValues not working as expected in latest version

### ISSUE THREAD

**Issue by paul-uz** [aws/aws-sdk-js-v3#4280]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I have `removeUndefinedValues: true` for my DynamoDBDocumentClient.

I am then constructing a set of Update parameters, based on some data sent to the function. Some values are set, some are undefined.

My params look like this:

```javascript
{
  TableName: 'My-Table',
  Key: { channelID: 'd3998ab0-a6ae-44c8-8cbc-35571873a11d' },
  UpdateExpression: 'set #id = :id, #accessData = :accessData, #schedules = :schedules, #publicationData.#updatedAt = :updatedAt, #publicationData.#updatedBy = :updatedBy',
  ExpressionAttributeNames: {
    '#id': 'streamID',
    '#accessData': 'accessData',
    '#schedules': 'schedules',
    '#publicationData': 'publicationData',
    '#updatedAt': 'updatedAt',
    '#updatedBy': 'updatedBy'
  },
  ExpressionAttributeValues: {
    ':id': '321',
    ':accessData': undefined,
    ':schedules': undefined,
    ':updatedAt': '2022-12-13T11:14:26Z',
    ':updatedBy': 'System'
  }
}
```

Now I would expect the undefined parts to be removed, but they are not. Instead I get the error

> ValidationException: Invalid UpdateExpression: An expression attribute value used in expression is not defined; attribute value: :schedules

### SDK version number

"@aws-sdk/client-dynamodb": "^3.229.0", "@aws-sdk/lib-dynamodb": "^3.229.0",

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node 18

### Reproduction Steps

Use params above in Update command

### Observed Behavior

See error thrown

### Expected Behavior

Undefined parts removd from params and command is successful

**Comment by yenfryherrerafeliz** [comment]
Hi @paul-uz, thanks for opening this issue. You are getting that error because you are using a field in the UpdateExpression that is empty, and any field you use in the UpdateExpression needs to have a valid value. In your case you have the following update expression:
>UpdateExpression: 'set #id = :id, #accessData = :accessData, #schedules = :schedules, #publicationData.#updatedAt = :updatedAt, #publicationData.#updatedBy = :updatedBy',

which includes the field 'schedules', but it is undefined and therefore you get an error. I tried with some previous version and is the same, it requires that any field used in the expression to have a value, however, if you have used an old version where this is different could you please post here which one it is so we can take a look?

Thanks!

**Comment by paul-uz** [comment]
So what is "removeUndefinedValues" for exactly?
