### ISSUE TITLE
lib-dynamodb Provide own marshall function

### ISSUE THREAD

**Issue by zoellner** [aws/aws-sdk-js-v3#4289]
### Describe the feature

allow users to provide their own marshall/unmarshall functions when using DynamoDBDocument

### Use Case

Given the number of issues with the marshall function in aws-sdk-js-v3, this would allow me to just plugin the marshall code from aws-sdk v2 which was working just fine.
It would also allow people to make additions, e.g. #3066

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

latest

### Environment details (OS name and version, etc.)

any

**Comment by yenfryherrerafeliz** [comment]
Hi @zoellner, thanks for opening this issue. You can override the marshalling implementation of the SDK by injecting a custom middleware as follow:

```js
import {DynamoDBClient, ListTablesCommand} from '@aws-sdk/client-dynamodb';
import { DynamoDBDocument } from '@aws-sdk/lib-dynamodb';

const client = new DynamoDBClient({
    region: 'us-east-2'
});
const ddbDocClient = DynamoDBDocument.from(client);
ddbDocClient.middlewareStack.addRelativeTo( next => args => {
    const input = args.input = yourCustomMarshallingFunction(args.input);
    
    return next(args);
}, {
    name: "DocumentMarshall",
    relation: "before",
    toMiddleware: "serializerMiddleware",
    override: true,
});
```

Please let me know if that works for you.

Thanks!

**Comment by zoellner** [comment]
Thank you. That should work
