### ISSUE TITLE
Unable to find documentation on how to set System-Defined Cache-Control with Upload function 

### ISSUE THREAD

**Issue by ezrover** [aws/aws-sdk-js-v3#4305]
### Describe the issue

Seeking documentation or an example on how to set the Cache-control meta data on a S3 object during Upload.

### Links

https://github.com/aws/aws-sdk-js-v3/issues/1891

**Comment by RanVaknin** [comment]
Hi @ezrover ,

Thanks for reaching out!

Cache-Control exists on the `putObjectCommandRequest` as a request parameter, not under metadata.
for example:

```js
try {
  const upload = new Upload({
      client: new S3Client({region: "us-east-1"}),
      params: {
          Bucket: 'foo-bucket',
          Key: 'foo.txt',
          Body: "hello world",
          CacheControl: "max-age=120"
      },
  });
  await upload.done();
} catch (err) {
  console.log(err);
}
```

Will result in the following:

<img width="2125" alt="image" src="https://user-images.githubusercontent.com/50976344/210024676-185c8eb8-a5a1-4546-9da5-ff7b0cc1227c.png">

Let me know if that helps :) 

Thanks,
Ran~
