### ISSUE TITLE
Cannot use @aws-sdk/client-apigatewaymanagementapi with AWS SAM CLI

### ISSUE THREAD

**Issue by ryk0ga** [aws/aws-sdk-js-v3#4306]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Hi.

I installed `@aws-sdk/client-apigatewaymanagementapi` and tried to run a Lambda function with `sam local invoke` command.

However, it only returned an error that the **NodeUseDulastackEndpointConfigOptions.d.ts** file could not be found.

Indeed, when I checked the SAM build results, the file did not exist.

I don't intend to use `@aws-sdk/client-apigatewaymanagementapi` locally, but I need the `sam local invoke` command to work.

Currently, the same error occurs in functions that do not use this package, so I am reporting this as a bug.

### SDK version number

@aws-sdk/client-apigatewaymanagementapi@3.235.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

18.12.0

### Reproduction Steps

sam build && sam local invoke ${FUNCTION_NAME}

### Observed Behavior

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\~\\AppData\\Roaming\\AWS SAM\\layers-pkg\\lambdalayer\\nodejs\\node_modules\\@aws-sdk\\client-apigatewaymanagementapi\\node_modules\\@aws-sdk\\config-resolver\\dist-types\\ts3.4\\endpointsConfig\\NodeUseDualstackEndpointConfigOptions.d.ts'

### Expected Behavior

`sam local invoke` command works properly.

**Comment by RanVaknin** [comment]
Hi @ryk0ga,

Can you please add some reproduction code? 

Thanks,
Ran
