### ISSUE TITLE
Unhelpful DynamoDB response

### ISSUE THREAD

**Issue by naimGur** [aws/aws-sdk-js-v3#4308]
### Describe the feature

Showing whether the item is found and deleted, or not even found in the `delete()` command's response would be more helpful. The user of this method does not know if `delete()` method deleted the item or not. We are using one more request to find out if the item is deleted in our code.

### Use Case

I want to implement the delete operation on DynamoDB. But since DynamoDB's response to `delete()` does not let me know if the item is deleted or not, I have to use `get()` after calling the `delete()` to see if the `delete()` function succeeded or not. And it causes more cost considering we have to use one more request every time we want to delete an item from DynamoDB. Here is how I use the library and the response I get.

My implementation:
```

import { DynamoDBDocument } from "@aws-sdk/lib-dynamodb";


export class DdbConector {
  ddbDoc: DynamoDBDocument;

  constructor(ddbClient: DynamoDBDocument) {
    this.ddbDoc = ddbClient;
  }


async deleteItem(TableName: string, id: string): Promise<void> {
    const res  = await this.ddbDoc.delete( { TableName, Key: {id} } )
    console.log(res) // shared the response below
  }

}
```
This is the successful scenario's response. That means the item is deleted from DynamoDB:
```
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'c7a1e277-dc3e-40a1-9122-ad580484b56d',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Attributes: undefined,
  ConsumedCapacity: undefined,
  ItemCollectionMetrics: undefined
}
```
And this is an unsuccessful scenario response. In this scenario, the Item is not found in DynamoDB:

```

{
    '$metadata': {
        httpStatusCode: 200,
        requestId: '3fdd38b8-e7e2-4bfe-9541-7f0aab49d6b6',
        extendedRequestId: undefined,
        cfId: undefined,
        attempts: 1,
        totalRetryDelay: 0
    },
    Attributes: undefined,
    ConsumedCapacity: {
    CapacityUnits: 1,
    GlobalSecondaryIndexes: undefined,
    LocalSecondaryIndexes: undefined,
    ReadCapacityUnits: undefined,
    Table: undefined,
    TableName: 'Customers',
    WriteCapacityUnits: undefined
    },
    ItemCollectionMetrics: undefined
}
```

### Acknowledgements

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

"@aws-sdk/lib-dynamodb": "^3.226.0"

### Environment details (OS name and version, etc.)

Windows 11, NodeJs, Typescript, Serverless-framework

**Comment by RanVaknin** [comment]
Hi @naimGur ,

Thank you for opening a feature request! 
The responses you are seeing are responses from the DynamoDB service and not the SDK client. We can't do anything about what the service is returning.

from an API design perspective, running a delete command on a resource that returns 200 is enough to validate that a record is deleted.
Instead of making another call you can simply wrap your call with a try catch block and add logic:

```js
async deleteItem(TableName: string, id: string): Promise<void> {
    try {
      const res  = await this.ddbDoc.delete( { TableName, Key: {id} } )
      console.log(res) // shared the response below
    } catch (error) {
      // delete was not successful, add logic here to handle an unsuccessful delete.
    }
}
```

Since there is not really anything for us to do here I'm going to close this FR.
Thanks again!
Ran
