### ISSUE TITLE
DynamoDB ListTablesCommand does not respect Limit parameter

### ISSUE THREAD

**Issue by Doug-AWS** [aws/aws-sdk-js-v3#432]
**Describe the bug**
Here's my code:

```
(async function() {
  const DDB = require('@aws-sdk/client-dynamodb-node')
  const dbClient = new DDB.DynamoDBClient({ region: 'us-west-2' })

  // Just list up to 5 tables
  const params = {
    Limit: 5
  }

  const command = new DDB.ListTablesCommand({ params })

  try {
    const results = await dbClient.send(command)
    console.log(results.TableNames.join('\n'))
  } catch (err) {
    console.error(err)
  }
})()
```
**SDK version number**
V3 beta

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
v10.16.2

**To Reproduce (observed behavior)**
Run the code

**Expected behavior**
Only 5 table names listed

**Comment by ajredniwja** [comment]
Closing this issue as it works if you use the alpha client, using

 ```npm install @aws-sdk/client-dynamodb```

Please reach out if you have any questions.
