### ISSUE TITLE
unable to find documenation on how to create email/domain identity in aws SES 

### ISSUE THREAD

**Issue by codelife123** [aws/aws-sdk-js-v3#4327]
### Describe the issue

Seeking documentation or an example on how to create email identity in SES service.
is it possible to do using v3 javascript sdk ?
I coudln't find the correct command for this task in [https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-ses/globals.html](url)

I see there is an example for deleting identity. but no example for creating identity
[https://docs.aws.amazon.com/ses/latest/dg/example_ses_DeleteIdentity_section.html](url)

this is what I'm trying to do. seems it's possible to in v2 but couldn't find a way to in v3
[https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SESV2.html#createEmailIdentity-property](url)

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-ses/globals.html

**Comment by RanVaknin** [comment]
Hi @codelife123 ,

What you are looking for is in [SESv2 client ](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-sesv2/classes/createemailidentitycommand.html):

```js
import { SESv2Client, CreateEmailIdentityCommand } from "@aws-sdk/client-sesv2";

const client = new SESv2Client(config);

const command = new CreateEmailIdentityCommand(input);

try{
    await client.send(command);
} catch (err){
    console.log(err)
}
```

Let me know if you need anything else 👍 

Thanks,
Ran~

**Comment by codelife123** [comment]
thanks for the reply. 
that's correct that's in v2 , but according AWS docs it's better to migrate from v2 to v3 because v2 support will be end soon.
isn't it ?
I thought all v2 features is available in v3 as well also I don't want to install an entire aws bundle  to use small portion of it.

if this is not available in v3 will it be added in future ?

until then can I use both v2 and v3 sdk inside my codebase, because I have already implemented lot of features using v3 sdk so I can't go back convert all of them to v2.

**Comment by codelife123** [comment]
thanks again
it worked.
