### ISSUE TITLE
node-config-provider package causing types not to work on non node environments

### ISSUE THREAD

**Issue by froggydood** [aws/aws-sdk-js-v3#4329]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The `node-config-provider` package is using the `NodeJS.ProcessEnv` type. This means that whenever you have a project that uses that package either directly or transiently through another package, it refers to `@types/node`. This means that when you aren't working in a node environment, e.g. cloudflare workers, when you import the types for the environment you are in, you get a lot of type clashes. This is because both types declare a lot of the same base javascript types and classes.

Therefore you cannot compile with sctrict type checking when using that package.

### SDK version number

@aws-sdk/node-config-provider@3.226.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

16.10.0

### Reproduction Steps

Create a fresh cloudflare worker environment in typescript.
Install `@aws/node-config-provider`
Import it somewhere in the code
Run `tsc`

It should error due to the conflict between node types and worker types

### Observed Behavior

`tsc` erros due to the conflict between worker types and node types

### Expected Behavior

node types shouldn't be imported therefore there should be no errors

### Possible Solution

Change the `NodeJS.ProcessEnv` type to a simple `Record<string, string>`, so it doesn't rely on node types.

As done in pull request [#4319](https://github.com/aws/aws-sdk-js-v3/pull/4319)

**Comment by yenfryherrerafeliz** [comment]
Hi @froggydood, thanks for opening this issue. I have left a comment on the PR you posted. 

Thanks!

**Comment by yenfryherrerafeliz** [comment]
The following [PR](https://github.com/aws/aws-sdk-js-v3/pull/4319), which fix this issue, has been merged.

Thanks!
