### ISSUE TITLE
PublishCommand from @aws-sdk/client-iot-data-plane does not work from aws lambda for shadow topic

### ISSUE THREAD

**Issue by vidyakhedkar** [aws/aws-sdk-js-v3#4331]
```js
const {
  IoTDataPlaneClient,
  PublishCommand,
} = require("@aws-sdk/client-iot-data-plane");

const client = new IoTDataPlaneClient({
  region: "ap-south-1",
  endpoint: <url>,
  credentials: {
    accessKeyId: <key>,
    secretAccessKey: <secret>,
  },
});

exports.updateShadow =  async (device, newPrice) => {
    const message = {
      state: {
        desired: {
          welcome: "aws-iot",
          device_id: device,
          name: "signage01",
          price: newPrice,
        },
      },
    };
    const publishInput = {
      topic: "$aws/things/mything/shadow/name/my_shadow_name/update",
      contentType: "application/json",
      payload: JSON.stringify(message),
      qos: 1,
    };
    const command = new PublishCommand(publishInput);
    console.log(JSON.stringify(message));
    client.send(command).then(console.log);
  }
```

This code works perfectly on local machine but fails to execute from aws lambda.
Similar code for python SDK works fine.

```python
import json
import boto3

client = boto3.client('iot-data', region_name='ap-south-1')

def lambda_handler(event, context):
    print(event)
    # TODO implement
    # Change topic, qos and payload
    response = client.publish(
        topic='$aws/things/mything/shadow/name/my_shadow_name/update',
        qos=1,
        payload=json.dumps({
      "state": {
        "desired": {
          "welcome": "aws-iot",
          "device_id": 12,
          "name": "signage01",
          "price": "frompython lambda",
        }
      }
    })
    )
    print(response)
    
    return {
        'statusCode': 200,
        'body': json.dumps('Published to topic')
    }

```
### Expected Behavior

Should be able to publish a message to shadow topic using   IoTDataPlaneClient PublishCommand from aws lambda.

### Current Behavior

Lambda executes successfully but the message does not reach to MQTT topic.

### Reproduction Steps

Run the above node.jscode in aws lambda function.

### SDK version used

 "@aws-sdk/client-iot-data-plane": "^3.238.0",

### Environment details (OS name and version, etc.)

aws lambda
Both node.js and python lambda are using same iam role.

**Comment by RanVaknin** [comment]
Hi @vidyakhedkar,

You mentioned that `PublishCommand` "doesn't work", and lambda executes successfully, but you are not capturing any errors from your execution.

```js
client.send(command).then(console.log); 
// you are not logging anything, and if there is an error, you are not capturing it. 

// instead do this:
client.send(command)
.then(data => {console.log(data)})
.catch(err => {console.log(err)}); 


// or even better, use await instead of chaining callbacks, and wrap in a try catch block:
try{
  const response = await client.send(command);
  console.log(response)
} catch (error) {
  console.log(error)
}
```
This way if an execution error happens you can catch the error and handle it.

Let me know if this helps,

Thanks,
Ran~

**Comment by vidyakhedkar** [comment]
Thanks Ran for getting back to me.
I found what was the issue.
I had added the lambda to VPC so it was timing out publishing to the MQTT
topic.
It started working when I removed it from VPC.
Can you tell me what is the way if I want to access RDS in VPC and publish
to MQTT topic then how the lambda should be configured?

Regards,
-Vidya

**Comment by RanVaknin** [comment]
Hi @vidyakhedkar ,

It sounds like [this doc](https://docs.aws.amazon.com/lambda/latest/dg/configuration-vpc.html) is what you are looking for.

Since I don't fully know the landscape of your architecture it would be impossible to provide a solution since its never "one-answer-fits-all" situation. If you have some mores specific fine grained question, I can do my best to help.

Thanks,
Ran~

**Comment by vidyakhedkar** [comment]
Thanks a lot Ran.

I will look into it.

We can close this issue.

Regards,
-Vidya
