### ISSUE TITLE
Getting error: `TypeError: Cannot read properties of undefined (reading 'byteLength')` when requesting signed URL from MRAP

### ISSUE THREAD

**Issue by LawrenceWarren** [aws/aws-sdk-js-v3#4335]
#### The issue
I am trying to get a signed URL for an S3 object via a Multi-Region Access Point. I can fetch a signed URL for the object when trying to access directly from a bucket, but not when accessing through the MRAP. I can fetch other resources from an MRAP.

#### Code

```typescript
import { everything_relevant } from '@aws-sdk/various-sdks';

const MRAP = 'arn:aws:s3::0123456789:accesspoint/my_mrap_id.mrap';
const BUCKET = 'my-bucket-name';

const CLIENT = new S3Client({
  region: 'eu-west-1',
  disableMultiregionAccessPoints: false,
  credentials: {
    accessKeyId: env.ACCESS_KEY_ID as string,
    secretAccessKey: env.SECRET_ACCESS_KEY_ID as string
  }
});

export async function get_s3_presigned_url(
  key: string,
  version: string | undefined = undefined,
  mrap: boolean = false
) {
  try {
    const get_obj = new GetObjectCommand({
      Bucket: mrap ? MRAP : BUCKET,
      Key: key,
      VersionId: version,
      ResponseCacheControl: CACHE_CONTROL_HEADER
    });

    let url = await getSignedUrl(CLIENT, get_obj, { expiresIn: 30 * 60 });
    console.log(`URL is ${url}`);
    return url;
  } catch (error) {
    console.error(error);
    return error as string;
  }
}
```

### Expected Behavior

If I call 

```typescript
const url = get_s3_presigned_object_url('path/to/myobject.png', undefined, false)
``` 
or 

```typescript
const url = get_s3_presigned_object_url('path/to/myobject.png', undefined, true)
```

`url` will be a valid URL to the object, regardless of whether the MRAP or S3 bucket is used

_(I'd like to stress, using the MRAP endpoint to actually call the `GetObjectCommand` does work, I do get the object. It is only when trying to get a presigned URL that it fails)_

### Current Behavior

If I call 
```typescript
const url = get_s3_presigned_object_url('path/to/myobject.png', undefined, false)
```
Then the `GetObjectCommand` uses the bucket ID; `url` is a valid URL to the object. **Success 🎉**

If I call
```typescript
const url = get_s3_presigned_object_url('path/to/myobject.png', undefined, true)
``` 
Then the `GetObjectCommand` uses the MRAP ID; I do not get a valid URL to the object; the following error is logged:

```
TypeError: Cannot read properties of undefined (reading 'byteLength')
    at fromArrayBuffer (~/docs/my_proj/node_modules/@aws-sdk/util-buffer-from/dist-cjs/index.js:6:60)
    at castSourceData (~/docs/my_proj/node_modules/@aws-sdk/hash-node/dist-cjs/index.js:29:51)
    at Hash.update (~/docs/my_proj/node_modules/@aws-sdk/hash-node/dist-cjs/index.js:12:26)
    at hmac (~/docs/my_proj/node_modules/@aws-sdk/signature-v4/dist-cjs/credentialDerivation.js:36:10)
    at getSigningKey (~/docs/my_proj/node_modules/@aws-sdk/signature-v4/dist-cjs/credentialDerivation.js:22:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
```

### Reproduction Steps

Copy/paste the code above, using your own correct values for:

* MRAP ID
* S3 Bucket ID
* AWS_ACCESS_KEY_ID
* AWS_SECRET_ACCESS_KEY

And then call the function.

### SDK version used

@aws-sdk/client-s3: "3.245.0", @aws-sdk/s3-request-presigner: "3.245.0", @aws-sdk/signature-v4-crt: "^3.226.0"

### Environment details (OS name and version, etc.)

MacOS 13.1, NodeJS v16.17.0

**Comment by RanVaknin** [comment]
Hi @LawrenceWarren ,

Thanks for opening this issue. It seems like the presign utility does not recognize an MRAP as a valid bucket name. 
For comparison, the Golang SDK handles MRAP as a valid argument.

I will label this as `needs-review` and our on-call will take a look at it.

___
### Observation and repro steps:

The specific issue is here in [here](https://github.com/aws/aws-sdk-js-v3/blob/5ba763a786b04262ed8807bef583a9bb0bb6656d/packages/s3-request-presigner/src/getSignedUrl.ts#L26)
`AuthScheme` now has a `signingRegionSet` property. If we use an MRAP, the region would be resolved as "*". That case needs to be handled with something like:

```diff
    const authScheme = endpointV2.properties?.authSchemes?.[0];
+   let signingRegion = "";
+        if (authScheme.signingRegionSet){
+            signingRegion = authScheme.signingRegionSet.join(",")
+        } else {
+            signingRegion = authScheme.signingRegion
+        }
    s3Presigner = new S3RequestPresigner({
      ...client.config,
      signingName: authScheme?.signingName,
-      region: async () => authScheme?.signingRegion,
+      region: async () => signingRegion
    });
```

To reproduce:

- Create an MRAP and attach a bucket to it.
- Create a new project:
```console
mkdir 4335-issue && cd 4335-issue
touch sample.js
npm init -yes
npm i @aws-sdk/s3-request-presigner @aws-sdk/client-s3 @aws-sdk/signature-v4-crt
```

**Code:**

```js
// sample.js code:
import { S3Client, GetObjectCommand, PutObjectCommand, CreateBucketCommand } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";

// Constants:
const MRAP = "arn:aws:s3::0123456789:accesspoint/my_mrap_id.mrap";
const BODY = "hello-world";
const KEY = "hello.txt"

const client = new S3Client({ region: "us-east-1", disableMultiregionAccessPoints: false });

async function put(){
	try {
		await client.send(new PutObjectCommand({
			Bucket: MRAP,
			Key: KEY,
			Body: BODY
		}))  
	} catch (error) {
		console.log()
	}
}
put() // put on mrap works

async function signGet(){
	const getCommand = new GetObjectCommand({
		Bucket: MRAP,
		Key: KEY
	})
	const signedUrl = await getSignedUrl(client, getCommand, {expiresIn: 3600} );
}
signGet() // presign doesnt
```


Thanks,
Ran~

**Comment by LawrenceWarren** [comment]
I appreciate you getting back to me on this, many thanks

**Comment by kithoffman** [comment]
Has there been any update on this @RanVaknin ?

**Comment by yenfryherrerafeliz** [comment]
Hi @LawrenceWarren, @kithoffman, this issue is fixed in the latest version, however right now we have another issue and is that the presigned url is being generated with the region as undefined, but to workaround this you just need to provide the parameter signingRegion to the options of the getSignedUlr function as follow:

```js
import { S3Client, GetObjectCommand } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";

// Constants:
const MRAP = "arn:aws:s3::123456789:accesspoint/mifxb7t43swrs.mrap";
const KEY = "hello.txt"
const client = new S3Client({ region: "us-east-2"});
const getCommand = new GetObjectCommand({
    Bucket: MRAP,
    Key: KEY
})
const signedUrl = await getSignedUrl(client, getCommand, {expiresIn: 3600, signingRegion: "us-east-1"});
console.log(signedUrl)
```

I hope this helps!

Thanks!

**Comment by LawrenceWarren** [comment]
Amazing work guys, thanks for getting this done.
