### ISSUE TITLE
Unexpected empty auth scheme config in middleware-signing/3.226.0

### ISSUE THREAD

**Issue by stevefan** [aws/aws-sdk-js-v3#4338]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

My on a dynamodb put, my lambda throws this error:

```
INFO	Error Error: Unexpected empty auth scheme config
    at Object.signer (/var/runtime/node_modules/@aws-sdk/middleware-signing/dist-cjs/configurations.js:45:23)
    at /var/runtime/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:12:34
    at StandardRetryStrategy.retry (/var/runtime/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:52)
    at async /var/runtime/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at async Runtime.putItemHandler [as handler] (file:///var/task/src/handlers/put-item.mjs:35:22)
```

Implicated code in putItemHandler:
```
<DynamoDBDocumentClient>.send(new PutCommand(...));
```

I've seen a similar error fixed by downgrading packages in this related issue:
https://github.com/aws/aws-sdk-js-v3/issues/4094

Downgrading @aws-sdk/middleware-signing/3.226.0 to @aws-sdk/middleware-signing/3.215.0 fixed this issue for me as well.

### SDK version number

@aws-sdk/middleware-signing/3.226.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.17.1

### Reproduction Steps

```js
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import { DynamoDBDocumentClient, PutCommand } from '@aws-sdk/lib-dynamodb';
const client = new DynamoDBClient({ region: process.env.AWS_REGION });
const ddbDocClient = DynamoDBDocumentClient.from(client);

const tableName = process.env.

    var params = {
        TableName : tableName,
        Item: { id : id, name: name }
    };

    try {
        const data = await ddbDocClient.send(new PutCommand(params));
        console.log("Success - item added or updated", data);
      } catch (err) {
        console.log("Error", err.stack);
      }
```

### Observed Behavior

```
INFO	Error Error: Unexpected empty auth scheme config
    at Object.signer (/var/runtime/node_modules/@aws-sdk/middleware-signing/dist-cjs/configurations.js:45:23)
    at /var/runtime/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:12:34
    at StandardRetryStrategy.retry (/var/runtime/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:52)
    at async /var/runtime/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at async Runtime.putItemHandler [as handler] (file:///var/task/src/handlers/put-item.mjs:35:22)
```

### Expected Behavior

No signing error, successful put to DynamoDB.

### Possible Solution

Downgrading @aws-sdk/middleware-signing/3.226.0 to @aws-sdk/middleware-signing/3.215.0 fixed this issue for me.

**Comment by yenfryherrerafeliz** [comment]
Hi @stevefan, thanks for opening this issue. For what I could understand you are running this in a lambda function?, if so, are you using lambda layers to use the AWS SDK for JavaScript V3 there?, since you are using dynamodb client and lib dynamodb, could you please provide which version of those packages are you using?

In my local environment I did not have any issues by doing the following:
- Created a new project ``` npn init ```
- Installed the used dependencies: ``` npm i @aws-sdk/client-dynamodb ``` and ``` npm i @aws-sdk/lib-dynamodb ```
- Then, I created a js file as follow ```"src/index.js"```
- The, I used the coded below:
```js
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import { DynamoDBDocumentClient, PutCommand } from '@aws-sdk/lib-dynamodb';

const client = new DynamoDBClient({
    region: process.env.TEST_REGION
});
const ddbDocClient = DynamoDBDocumentClient.from(client);
const tableName = 'test-table'
const params = {
    TableName : tableName,
    Item: {
        id : 'test-id',
        name: 'name'
    }
};
try {
    const data = await ddbDocClient.send(new PutCommand(params));
    console.log("Success - item added or updated", data);
} catch (err) {
    console.log("Error", err.stack);
}

```
And here is the output I get:

```console
Success - item added or updated {
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'REQUEST-ID',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Attributes: undefined,
  ConsumedCapacity: undefined,
  ItemCollectionMetrics: undefined
}

```

Thanks!

**Comment by kenny-alvizuris-cko** [comment]
Hello, I'm currently having the same error. 

I'm using `"@aws-sdk/client-secrets-manager": "^3.190.0"`, I'm creating a new AWS Secret Manager client like this:

```ts
const secretsManagerClient = new SecretsManagerClient({ region: 'eu-west-1' });

const input: GetSecretValueCommandInput = {
  SecretId: 'some id',
};

const command = new GetSecretValueCommand(input);
try {
  const resp = await secretsManagerClient.send(command);
} catch (error) {
  console.log(error)
}
```


output:
```sh
Error: Unexpected empty auth scheme config
        at Object.signer (/Users/kenny/api/dashboard/node_modules/@aws-sdk/middleware-signing/dist-cjs/configurations.js:45:23)
        at /Users/kenny/api/dashboard/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:12:34
        at /Users/kenny/api/dashboard/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:52
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at /Users/kenny/api/dashboard/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:5:22 {
      '$metadata': { attempts: 1, totalRetryDelay: 0 }
    }
```

I'm trying to find a version that does not use `@aws-sdk/middleware-signing/3.226.0`, will update if I find the root cause

**Comment by yenfryherrerafeliz** [comment]
Hey @stevefan, @kenny-alvizuris-cko, I found [this](https://github.com/aws/aws-sdk-js-v3/issues/4094) related issue where the problem was due to a version of aws-sdk/middleware-signing that was pinned by the package.lock.json file. See the comment [here ](https://github.com/aws/aws-sdk-js-v3/issues/4094#issuecomment-1293107810). So, would you be able to force your dependencies to be updated?, what I usually do is to delete the package.lock.json file and run ``` npm i ``` or ```yarn``` and they get updated.

Please let me know.

Thanks!
