### ISSUE TITLE
Getting error `STRING_VALUE can not be converted to milliseconds since epoch` when retrieving traces

### ISSUE THREAD

**Issue by jorgechiapello** [aws/aws-sdk-js-v3#4343]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Running a pretty standard GetTraceSummariesCommand with the XRayClient throws the following error:  `STRING_VALUE can not be converted to milliseconds since epoch` .

### SDK version number

@aws-sdk/client-xray@3.252.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.3.0

### Reproduction Steps

Run the following:
```js
const main = async () => {
  const client = new XRayClient({
    region: "<ANY_REGION>",
  });

  const now = new Date();
  const beforeNow = new Date();
  beforeNow.setHours(now.getHours() - 1);

  const command = new GetTraceSummariesCommand({
    StartTime: beforeNow,
    EndTime: now
  });
  
  const resp = await client.send(command);
}
main();
```

### Observed Behavior
```bash
SerializationException: STRING_VALUE can not be converted to milliseconds since epoch
    at throwDefaultError (C:\Users\JorgeChiapello\WebstormProjects\testingXrayClient\node_modules\@aws-sdk\smithy-client\dist-cjs\default-error-handler.js:8:22)
    at deserializeAws_restJson1GetTraceSummariesCommandError (C:\Users\JorgeChiapello\WebstormProjects\testingXrayClient\node_modules\@aws-sdk\client-xray\dist-cjs\protocols\Aws_restJson1.js:1511:51)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\JorgeChiapello\WebstormProjects\testingXrayClient\node_modules\@aws-sdk\middleware-serde\dist-cjs\deserializerMiddleware.js:7:24
    at async C:\Users\JorgeChiapello\WebstormProjects\testingXrayClient\node_modules\@aws-sdk\middleware-signing\dist-cjs\middleware.js:14:20
    at async C:\Users\JorgeChiapello\WebstormProjects\testingXrayClient\node_modules\@aws-sdk\middleware-retry\dist-cjs\retryMiddleware.js:27:46
    at async C:\Users\JorgeChiapello\WebstormProjects\testingXrayClient\node_modules\@aws-sdk\middleware-logger\dist-cjs\loggerMiddleware.js:5:22 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: 'f8ba3fd1-e750-43f9-86c8-915697b60760',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}
```

### Expected Behavior

Return traces.

### Possible Solution

The problem seems to be that the client is casting the `StartTime` and `EndTime` into strings before sending the command when serializing them, check [here](https://github.com/aws/aws-sdk-js-v3/blob/8d0aefae1233b61352426d8c8bd930e955400265/clients/client-xray/src/protocols/Aws_restJson1.ts#L664).

When `toString()` is removed, it works perfectly.

Change introduced recently in [here](https://github.com/aws/aws-sdk-js-v3/commit/cc3bba8b4ccdaa9173adc032ff1c34ad56bd8ed1#diff-7568d68a6102503833b0857019306e9b65214c8d338a4c7bf26209bc1fdee604L444)

### Additional Information/Context

aws-cli version 2.2.21 
Python version 3.8.8

**Comment by mmcmaster-seek** [comment]
I've encountered the same issue by calling `EventBridge.putEvents` using @aws-sdk/client-eventbridge version 3.252.0. Works in 3.245.0

**Comment by bibekgupta3333** [comment]
I have encountered same type issue when putting event in event bridge in "@aws-sdk/client-eventbridge": "^3.54.0"
![image](https://user-images.githubusercontent.com/46109418/213386779-ca1f5e4a-82d3-4d84-ba9c-9ae7381b3b07.png)

**Comment by nguyentoanit** [comment]
Same to me. I got this issue when emitting an event in `"@aws-sdk/client-eventbridge": "3.252.0",`
This didn't happen in `3.245.0`.

**Comment by toelen** [comment]
Same to me for `eventbridge.putEvents`

**Comment by bibekgupta3333** [comment]
- `...(input.Time != null && { Time: Math.round(input.Time.getTime() / 1000).toString() })`
- this above internal command timestamp is causing issue.
