### ISSUE TITLE
SSM Client ThrottlingException: Rate exceeded with pagination

### ISSUE THREAD

**Issue by 1oglop1** [aws/aws-sdk-js-v3#4350]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I am getting ThrottlingException while using paginator to describe SSM parameters.

### SDK version number

@aws-sdk/client-ssm@3.254.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.0.0

### Reproduction Steps

This code produced the error.
```js
import * as ssm from "@aws-sdk/client-ssm";


(async function () {
const client = new ssm.SSMClient({region: process.env['AWS_REGION']});

const paginator = ssm.paginateDescribeParameters(
  {client, pageSize:5},
  {}
  )

const data = []

for await (const page of paginator){

    const result = page.Parameters
    data.push(...result?? [])
}

console.log(JSON.stringify(data))

})();
```

### Observed Behavior

```
@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8
    const response = new exceptionCtor({
                     ^
node_modules/@cspotcode/source-map-support/source-map-support.js:722
ThrottlingException: Rate exceeded
```

### Expected Behavior

no throttling exception

**Comment by yenfryherrerafeliz** [comment]
Hi @1oglop1, thanks for opening this issue. The error that you are receiving means that you have exceeded the number of allowed api calls or request in a specific period of time. You can find more information about this error [here](https://aws.amazon.com/premiumsupport/knowledge-center/ssm-parameter-store-rate-exceeded/). However, if this is not your case and you are receiving this error just by doing one api call please let me know.

Thanks!

**Comment by jdimeo** [comment]
Yes, this is a real bug- if I use the built in paginator to list parameters, that shouldn't necessarily lead to a 400 error.

**Comment by yenfryherrerafeliz** [comment]
@jdimeo glad you got what was causing this for you. Please feel free of opening a new issue if is there anything that we can help with.

Thanks!
