### ISSUE TITLE
util-user-agent-node and signature-v4-multi-region fails with ESM

### ISSUE THREAD

**Issue by ciscoheat** [aws/aws-sdk-js-v3#4373]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

In version 3.257.0 I suddenly get an ESM-related error when using vitest with a SvelteKit site. By configuring vite to inline the packages, it works again.

### SDK version number

@aws-sdk/util-user-agent-node@3.257.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.10.0

### Reproduction Steps

Sorry but I cannot reproduce this in an easy way. I'm hoping that the error is well-known and has an easy fix.

### Observed Behavior

```
SyntaxError: Cannot use import statement outside a module
 ❯ Object.compileFunction node:vm:360:18

Module .../node_modules/.pnpm/@aws-sdk+util-user-agent-node@3.257.0/node_modules/@aws-sdk/util-user-agent-node/dist-es/is-crt-available.js:1 seems to be an ES Module but shipped in a CommonJS package. You might want to create an issue to the package "@aws-sdk/util-user-agent-node" asking them to ship the file in .mjs extension or add "type": "module" in their package.json.

As a temporary workaround you can try to inline the package by updating your config:

// vitest.config.js
export default {
  test: {
    deps: {
      inline: [
        "@aws-sdk/signature-v4-multi-region"
      ]
    }
  }
}
```

### Expected Behavior

No error message, it used to work fine.

### Additional Information/Context

The suggested workaround works, when adding this to `vite.config.js`

```ts
import { defineConfig } from 'vite';

export default defineConfig(({ command }) => {
  return {
    test: {
      deps: {
        inline: ['@aws-sdk/util-user-agent-node', '@aws-sdk/signature-v4-multi-region']
      }
    }
  }
}
```

**Comment by RanVaknin** [comment]
Hi @ciscoheat ,

Thanks for opening this issue.

Since you are using a 3rd party tool,  and we don't have repro steps there is no way we can root cause this. 
>suddenly get an ESM-related error when using vitest with a SvelteKit site. By configuring vite to inline the packages, it works again.

This being a sudden change is worrisome, this might be a breaking change from the SDK side.
Can you help us somehow reproduce this error?

**Comment by ciscoheat** [comment]
Hello Ran, it is difficult to reproduce. By just adding the @aws-sdk library to an empty project gives no problem. And the build works without error with SvelteKit, but when testing it with Vitest, the error occurs, even though they are using the same configuration (both are built on Vite).

I'm not importing any of the mentioned libraries, this is my only reference, in a single file:

```ts
import { S3Client, PutObjectCommand, DeleteObjectCommand } from '@aws-sdk/client-s3';
```

And to make things more confusing, there is no reference to this file in the tests.

**Comment by danielzting** [comment]
I am getting the same error on @aws-sdk/client-s3 v3.267.0

If you would like to investigate the commit is [here](https://gitlab.com/freetail-hackers/rodeo/-/tree/8e2711130cb2a21428ef466f2a8d5d91ff189d8f). It only popped up when I imported from @aws-sdk/client-s3 in the file under test.
