### ISSUE TITLE
v3 Upgrade guide references a link to bucketEndpoint that does not exist

### ISSUE THREAD

**Issue by supersime** [aws/aws-sdk-js-v3#4394]
### Describe the issue

There was a change in https://github.com/aws/aws-sdk-js-v3/commit/1bb77006c0a83f41028dbb928c2e723cd36dec3c that added the following text and associated link to the UPGRADING guide (which is hosted at https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md):

> `s3BucketEndpoint` changed to `bucketEndpoint`. See more in [v3 reference for bucketEndpoint](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/interfaces/s3clientconfig.html#bucketendpoint)

Two issues:
1. The link https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/interfaces/s3clientconfig.html#bucketendpoint does not seem to exist - it takes you to the top of the page rather than a section on `bucketEndpoint`.
2. Related to (1), there is no description of the `bucketEndpoint` at all on the https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/interfaces/s3clientconfig.html page.

### Links

https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/interfaces/s3clientconfig.html

**Comment by yenfryherrerafeliz** [comment]
Hi @supersime, thanks for bringing this to our attention. I agree we need to update our documentation regarding endpoints since a few changes were done regarding to this, after endpoint 2.0. I will mark this issue to be reviewed so we can address this further.  

Thanks!

**Comment by eamon0989** [comment]
Any update on this issue? I'm having trouble with TypeScript saying that `bucketEndpoint` does not exist on type `S3ClientConfigType`, but I can't find any documentation on it apart from what is mentioned in this issue.
```ts
  Object literal may only specify known properties, and 'bucketEndpoint' does not exist in type 'S3ClientConfigType'.ts(2345)
```

**Comment by kuhe** [comment]
A fix was released today that allows bucket inputs to serve as request endpoints.

```ts
const s3 = new S3({
  region: "us-west-2",
  bucketEndpoint: true,
});

const get = await s3.getObject({
  Bucket: "https://my-bucket.s3.us-west-2.amazonaws.com/", // can be any URL, localhost etc.
  Key: "filename.ext",
});
```

https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.525.0 
https://www.npmjs.com/package/@aws-sdk/client-s3/v/3.525.0
