### ISSUE TITLE
Cannot find module for @aws-sdk/util-utf8 on Node v18 Lambda runtime

### ISSUE THREAD

**Issue by hanneswidrig** [aws/aws-sdk-js-v3#4401]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I'm using the Node v18 runtime with three `@aws-sdk/*` packages, the clients have no issues, but I get Cannot find module on `util-utf8`, any ideas?

```
// package.json - dependencies
"@aws-sdk/client-apigatewaymanagementapi": "3.254.0",
"@aws-sdk/client-dynamodb": "3.254.0",
"@aws-sdk/util-utf8": "3.254.0",
```

```
2023-02-03T16:08:11.158Z	undefined	ERROR	Uncaught Exception 	{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module '@aws-sdk/util-utf8'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module '@aws-sdk/util-utf8'",
        "Require stack:",
        "- /var/task/index.js",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:1000:17)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1035:21)",
        "    at async start (file:///var/runtime/index.mjs:1200:23)",
        "    at async file:///var/runtime/index.mjs:1206:1"
    ]
}
```

### SDK version number

@aws-sdk/util-utf8

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Runtime Version: nodejs:18.v4

### Reproduction Steps

Use @aws-sdk/util-utf8 in ESM Node v18 Lambda runtime.

### Observed Behavior

Uncaught exception `Runtime.ImportModuleError` when Lambda runs.

### Expected Behavior

Lambda runs successfully

**Comment by yenfryherrerafeliz** [comment]
Hi @hanneswidrig, thanks for opening this issue. I can confirm that this package seems to be missing when using lambda along with node v18, which includes the version 3 of the JS SDK. I will investigate with the internal team about this and I will get back to you as soon as I get any response.'

Thanks!

**Comment by yenfryherrerafeliz** [comment]
Hi @hanneswidrig, I got an answer from the team and basically the situation here is that the version of the SDK, that is embedded with lambda as of right now, when node runtime is v18, is 3.188 and in that version the package @aws-sdk/util-utf8 is not available yet. However, you have the option to use "@aws-sdk/util-utf8-node" which will do most likely the same. 

[Here](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#w347aac23c27) is the docs from lambda where we can confirm what I just said.

Please let me know if you have any questions or comments.

Thanks!

**Comment by hanneswidrig** [comment]
@yenfryherrerafeliz Thanks for the information, do you know when `@aws-sdk/util-utf8` will be available in the node v18 runtime?

**Comment by yenfryherrerafeliz** [comment]
Hi @hanneswidrig, I do not know as of right now. I know the lambda team updates the SDK once every quarter, but I do not have a specific date for when it will updated next. I will reach out to them to ask about it, and will get back to you as soon as they respond.

Thanks!

**Comment by everett1992** [comment]
Are you using [NodeJSFucntion](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs.NodejsFunction.html) cdk construct or a bundler that excludes @aws-sdk/* modules?

**Comment by hanneswidrig** [comment]
@everett1992 I'm using the `NodeJsFunction` cdk construct.

```
		const connectLambda = new NodejsFunction(this, "ConnectLambda", {
			runtime: Runtime.NODEJS_18_X,
			handler: "handler",
			entry: "src/lambda/web-socket/connectLambda.ts",
			logRetention: RetentionDays.ONE_WEEK,
			role,
			securityGroups,
			vpc,
			bundling: { minify: false },
			environment: {
				TABLE_NAME: connectionsTable.tableName,
			},
		});
```

**Comment by everett1992** [comment]
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs.BundlingOptions.html#externalmodules

By default NodeJSFunction [excludes](https://esbuild.github.io/api/#external) `@aws-sdk/*` when the runtime is >=18.x. You're able to use @aws-sdk/client-apigatewaymanagementapi because it's included in sdk 3.188.0 which is included [with the runtime](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html), but @aws-sdk/util-utf8 was added in a later sdk version and isn't built into the runtime.

You can disable this behavior and include your @aws-sdk dependencies in the bundle you create for lambda by setting bundlingOptions.externalModules to an empty array, or a list of the packages you wish to exclude.

**Comment by hanneswidrig** [comment]
@everett1992 I will close this issue, the `externalModules` property was somewhat confusing to me but now it's more clear, thanks!

**Comment by trivikr** [comment]
Issues on aws-cdk:
* https://github.com/aws/aws-cdk/issues/24089
* https://github.com/aws/aws-cdk/issues/24090
