### ISSUE TITLE
Is adaptive retryMode supported or not?

### ISSUE THREAD

**Issue by mifi** [aws/aws-sdk-js-v3#4403]
### Describe the issue

according to https://docs.aws.amazon.com/sdkref/latest/guide/feature-retry-behavior.html

> retry_mode value adaptive is not supported.

but as far as I can see from code, it is supported. Which one is correct? And is it experimental or not?

### Links

https://docs.aws.amazon.com/sdkref/latest/guide/feature-retry-behavior.html

**Comment by RanVaknin** [comment]
Hi @mifi ,

Adaptive retries are supported in v3 as of https://github.com/aws/aws-sdk-js-v3/commit/0c9a14391b4a9193cad4fa533a39ff5e0296c1c5

I'll contact our doc writer to update that api reference.

Thanks,
Ran~

**Comment by RanVaknin** [comment]
This is now fixed. @mifi thanks for letting us know.

All the best,
Ran~
