### ISSUE TITLE
Protocol error when using NodeHttp2Handler for S3 client

### ISSUE THREAD

**Issue by vecerek** [aws/aws-sdk-js-v3#4406]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Hi, I'm trying to use HTTP/2 to fetch S3 objects. However, I see HEAD requests for S3 objects consistently fail with `Protocol error`. I was searching extensively whether this is an expected behavior but I couldn't find any official documentation on whether S3 is HTTP/2-compatible or not. I've seen similar issues like [this one for kinesis](https://github.com/aws/aws-sdk-js-v3/issues/3780).

### SDK version number

@aws-sdk/client-s3@3.264.0,@aws-sdk/node-http-handler@3.257.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node v18.13

### Reproduction Steps

```ts
import { NodeHttp2Handler } from "@aws-sdk/node-http-handler";
import { HeadObjectCommand, S3 } from "@aws-sdk/client-s3";

const env = process.env;

const client = new S3({
  credentials: {
    accessKeyId: env.AWS_ACCESS_KEY,
    secretAccessKey: env.AWS_SECRET_KEY,
  },
  encryption: env.AWS_S3_ENCRYPTION,
  endpoint: env.AWS_S3_ENDPOINT,
  region: env.AWS_REGION,
  requestHandler: new NodeHttp2Handler({
    requestTimeout: 100,
    sessionTimeout: 300,
  }),
});

const res = await client.send(
  new HeadObjectCommand({
    Bucket: "my-bucket",
    Key: "my-key",
  })
);
```

### Observed Behavior

```
Error: Protocol error
Error [ERR_HTTP2_ERROR]: Protocol error
    at new NghttpError (node:internal/http2/util:556:5)
    at Http2Session.onSessionInternalError (node:internal/http2/core:792:26)
    at Http2Session.callbackTrampoline (node:internal/async_hooks:130:17)
```

### Expected Behavior

I'd expect to get a proper response from S3 or to find some documentation that says HTTP/2 is not supported for S3.

**Comment by yenfryherrerafeliz** [comment]
Hi @vecerek, thanks for opening this issue. It looks like S3 does not support http2 yet, because I tried to fetch an object using a http2 client, without using the SDK, and I got the same error. I will reach to the internal team to ask about this and I will get back to you, with a more precise answer, as soon as they reply back.

Thanks!

**Comment by yenfryherrerafeliz** [comment]
Hi @vecerek, I got confirmation that S3 does not support http2 yet. Actually, right now most of the services that do support http2 use the http2handler by default, which is the case for kinesis, transcribe, and lex-rumtime clients.

If you have any comments please just let me know.

Thanks!
