### ISSUE TITLE
Intermittent ERR_HTTP2_INVALID_SESSION error when using HTTP/2.

### ISSUE THREAD

**Issue by jean343** [aws/aws-sdk-js-v3#4423]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The SDK returns error `ERR_HTTP2_INVALID_SESSION` and stops making new calls to AWS after the error shows up. This only happens with HTTP/2.

```
Error [ERR_HTTP2_INVALID_SESSION]: The session has been destroyed
```

The error is already in the issues, and it was mentioned here https://github.com/aws/aws-sdk-js-v3/issues/3602, however, I do not have permission to re-open it.

### SDK version number

@aws-sdk/node-http-handler@3.264.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

16.14.0

### Reproduction Steps

In my case, I am using the `LambdaClient` with the `NodeHttp2Handler`. It should happen with any HTTP/2 enabled services.

```javascript
  const { LambdaClient } = require("@aws-sdk/client-lambda");
  const { NodeHttp2Handler } = require("@aws-sdk/node-http-handler");
  const client = new LambdaClient({
    requestHandler: new NodeHttp2Handler(),
  });
```

The previous snippet does work in dev, however it fails in production under a heavy workload.

### Observed Behavior

```
Error [ERR_HTTP2_INVALID_SESSION]: The session has been destroyed
```

### Expected Behavior

It should not error out :)

### Possible Solution

After a lot of investigation, it turns out it's a race condition in the `NodeHttp2Handler`.

It's possible that the session in [getSession](https://github.com/aws/aws-sdk-js-v3/blob/main/packages/node-http-handler/src/node-http2-handler.ts#L179) gets closed or destroyed, but that no errors are triggered, and `destroySessionCb` isn't called. In this case, the call to `getSession` will always return the same destroyed session, thus preventing new calls from succeeding.

I have tried with the following code successfully.

```javascript
    if (existingSessions.length > 0 && !disableConcurrentStreams) {
      const [session] = existingSessions;
      if (session.destroyed || session.closed) {
        this.deleteSessionFromCache(authority, session);
      } else {
        return session;
      }
    }
```

**Comment by yenfryherrerafeliz** [comment]
Hi @jean343, could you please confirm if this issue is still happening for you with the latest version of the SDK?

I look forward to your response.

Thanks!
