### ISSUE TITLE
ExecuteStatement match query filters regardless of order when using nextToken

### ISSUE THREAD

**Issue by adriancova** [aws/aws-sdk-js-v3#4424]
### Describe the feature

When using PartiQL for DynamoDB queries the ExecuteStatement Statement + NextToken fields should recognize that the query/statement is the same even though one or more of the 'and clauses' are in a different order.

### Use Case

When using a map/object to build the Statement the object itself changes on following requests due to adding the nextToken field and we end up with "NextToken does not match request" error.

### Other Information

This is an example of how I came up with this issue:

Given a filter body:

```
{
  "valueOne":"someValue", 
  "valueTwo":{"$exists":false},
  "valueThree": "someOtherValue"
}
```

I can create the statement: 

`SELECT * FROM "SomeTable"."valueOneGSI" where "valueOne" = 'someValue' AND "valueTwo" IS MISSING AND "valueThree" = 'someOtherValue'`

I then receive the Items and a NextToken and I send both to the client. In a subsequent request the filter body will be:

```
{
  "valueOne":"someValue", 
  "valueThree": "someOtherValue",
  "nextToken": "token",
  "valueTwo":{"$exists":false}
}
```

for whatever reason the fields order is changed so when building the statement it turns out like:

`SELECT * FROM "SomeTable"."valueOneGSI" where "valueOne" = 'someValue' AND "valueThree" = 'someOtherValue' AND "valueTwo" IS MISSING`

And that's when the "NextToken does not match request" error happens even though the query is essentially the same since the GSI being used didn't change and is the first value in the where clause.

I ended up making sure I order the filters alphabetically (excluding the GSI which always goes first) to solve this issue on my end, but it'd be nice if this was supported out of the box.

Edit: I suspect this is the same issue posted here: https://repost.aws/questions/QUPwuGGFjoRea4qIy6dNKj2g/next-token-from-execute-statement-returns-error-next-token-does-not-match-request-in-lambda-function

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.262.0

### Environment details (OS name and version, etc.)

N/A

**Comment by aBurmeseDev** [comment]
Hi @adriancova - thanks for reaching out and sorry for the delay.

I attempted to reproduce this and it seems like you'd have to add `AND` clauses in alphabetical order for the request to succeed, just like you mentioned. I'm not sure if we can manipulate the string before sending it to the service, without breaking changes. I can definitely bring it up to team discussion but can't guarantee if it will be considered.
