### ISSUE TITLE
Occasional Signature Expired errors when fetching secrets from within Lambda

### ISSUE THREAD

**Issue by denitsa-md** [aws/aws-sdk-js-v3#4429]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Ever since we upgraded to v3, we've been getting occasional `SignatureExpired (Signature expired: date is now earlier than date )` errors when trying to fetch secrets from SecretsManager from within a Lambda.

We see the errors appearing every few days which results in getting a couple hundred events in our DLQ and then the errors magically stop.

In this case we're trying to fetch secrets so we can connect to a mongo db.

Here is the code diff before and after migrating to v3 (pasting a screenshot as I think it's easier to see the migration step):

![image](https://user-images.githubusercontent.com/21036599/218429798-08e0c4aa-3ea8-47bc-ab40-a6388bd8354f.png)

Any ideas on why we suddenly might be seeing this and suggestions for a fix?

### SDK version number

@aws-sdk/client-secrets-manager@3.266.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

18

### Reproduction Steps

We only get the error once every few days so we have no way of reproducing this consistently. But this is the code used to fetch secrets.

```js
import { SecretsManagerClient, GetSecretValueCommand } from '@aws-sdk/client-secrets-manager';
import { configuration } from './configuration';

// Secrets are fetched and kept outside the main handler, to avoid multiple calls to SecretsManager
async function initSecrets(): Promise<Record<string, string>> {
  const secretsManager = new SecretsManagerClient({
    region: configuration.aws.region,
    apiVersion: '2017-10-17',
    maxAttempts: 3,
  });
  const getSecretCommand = new GetSecretValueCommand({
    SecretId: configuration.secretId,
  });
  const response = await secretsManager.send(getSecretCommand);
  if (!response.SecretString) {
    throw new Error(`Secret not found`);
  }
  return JSON.parse(response.SecretString);
}

const _secretCache = initSecrets();
export async function getSecretValue(secretProp: string): Promise<string> {
  const secrets = await _secretCache;
  if (!secrets[secretProp]) {
    throw new Error("Couldn't parse secret");
  }
  return secrets[secretProp];
}
```

This is the code used to call `getSecretValue`:

```js
import { MongoClient, Db as Database } from 'mongodb';
import { getSecretValue } from './secrets';

const getMongoClient = async (): Promise<MongoClient> => {
  const mongoClient = await MongoClient.connect(await getSecretValue('SOME_SECRET'));
  return mongoClient;
};

export const getDatabase = async (dbName: string): Promise<Database> => {
  const mongoClient = await getMongoClient();
  return mongoClient.db(dbName);
};
```

### Observed Behavior

Every few days we get this error. It fails many times in a short timespan and then stops.

```console
{
    "level": "error",
    "timestamp": "2023-02-10T13:23:51.755Z",
    "payload": {
        "message": "Failed to connect to Mongo.",
        "error": {
            "type": "SecretsManagerServiceException",
            "message": "Signature expired: 20230210T131358Z is now earlier than 20230210T131851Z (20230210T132351Z - 5 min.)",
            "stack": [
                "InvalidSignatureException: Signature expired: 20230210T131358Z is now earlier than 20230210T131851Z (20230210T132351Z - 5 min.)",
                "at throwDefaultError (/var/task/node_modules/@aws-sdk/client-secrets-manager/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)",
                "at deserializeAws_json1_1GetSecretValueCommandError (/var/task/node_modules/@aws-sdk/client-secrets-manager/dist-cjs/protocols/Aws_json1_1.js:580:51)",
                "at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
                "at async /var/task/node_modules/@aws-sdk/client-secrets-manager/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24",
                "at async /var/task/node_modules/@aws-sdk/client-secrets-manager/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20",
                "at async /var/task/node_modules/@aws-sdk/client-secrets-manager/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46",
                "at async /var/task/node_modules/@aws-sdk/client-secrets-manager/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:5:22",
                "at async initSecrets (/var/task/secrets.js:16:22)",
                "at async getSecretValue (/var/task/secrets.js:24:21)",
                "at async getDatabase (/var/task/mongo.js:9:34)"
            ],
            "name": "InvalidSignatureException",
            "$fault": "client",
            "$metadata": {
                "httpStatusCode": 400,
                "requestId": "ddf18d42-fd59-4cb6-8de3-472c238efcd4",
                "attempts": 1,
                "totalRetryDelay": 0
            },
            "__type": "InvalidSignatureException"
        }
    }
}
```

I also don't understand why the timestamp in the brackets is different than the timestamps from "is now earlier than"

```
Signature expired: 20230210T131358Z is now earlier than 20230210T131851Z (20230210T132351Z - 5 min.)
```

### Expected Behavior

No `Signature expired` errors.

**Comment by yenfryherrerafeliz** [comment]
Hi @denitsa-md, thanks for opening this issue. I will try to reproduce the reported behavior so I can better understand what could be causing the issue on your end. Could you please let me know if you are using the sdk that comes embedded with the node18 runtime on lambda?, and could you please confirm if "getSecretValue" is the handler function for your lambda?, if not, could you please provide the code for the handler?

Thanks!

**Comment by denitsa-md** [comment]
Hey @yenfryherrerafeliz! Thanks for picking this up so quickly. 

1. We haven't been using the embedded SDK, but version `@aws-sdk/client-secrets-manager": "^3.266.0`. We can try to just move this to our dev dependencies and rely on the build in SDK.

2. The `getSecretValue` function is called in this piece of code:

```
#mongo.ts

import { MongoClient, Db as Database } from 'mongodb';
import { getSecretValue } from './secrets';

const getMongoClient = async (): Promise<MongoClient> => {
  const mongoClient = await MongoClient.connect(await getSecretValue('SOME_SECRET'));   <----- HERE
  return mongoClient;
};

export const getDatabase = async (dbName: string): Promise<Database> => {
  const mongoClient = await getMongoClient();
  return mongoClient.db(dbName);
};
```

And the handler in turn calls `getDatabase` like so:


```
#index.ts

export const handler = async (event: SNSEvent, context: Context): Promise<void> => {

  if (!event) {
    logger.warn('Received empty event.');
    return;
  }

  if (!database) {
    try {
      database = await getDatabase(configuration.mongo.database);   <----- HERE
      attachmentsCollection = database.collection<Attachment>(
        configuration.mongo.collections.attachments
 ...       
```

**Comment by steve-c-thompson** [comment]
@denitsa-md are you using provisioned concurrency? I see this same issue in my lambda, where I'm also storing a promise in global scope. It appears related to **The NodeJS Async Init Problem** in this post: https://barker.tech/aws-lambda-nodejs-async-init-88b5c24af567

With a lot of ugly logging, on Lambda init I see my `async init` start and make a request to get the Secret, but then that Secret isn't retrieved. Only after the first request to the `handler` function is the `init()` allowed to finish, and I can see my Secret retrieved. If five minutes have passed between Lambda init and the first `handler` request, I see the `SignatureExpired` error.

My low-rent solution is a warmer that pings the lambda every 4 minutes, to stay under that 5 minute limit.

**Comment by denitsa-md** [comment]
@steve-c-thompson No, we're just using unreserved account concurrency. But it's great to keep the issue you encountered in mind!

I actually feel that we stopped getting the issue after we switched to the build-in SDK. So I'll close this for now and cross our fingers it's fixed 🤞

**Comment by sparent** [comment]
I was experiencing the same issue. For now I had to revert to the full aws-sdk package but I would prefer to use the client packages instead to keep our code package size down.
