### ISSUE TITLE
rds.modifyDBInstance(params).promise()  fails to update password

### ISSUE THREAD

**Issue by imendi** [aws/aws-sdk-js-v3#4439]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I'm trying to update the cluster master user password like so ..

```
const changeClusterPassword = async (clusterId: string, username: string, newPassword: string) => {
  const params = {
    DBClusterIdentifier: clusterId,
    MasterUserPassword: newPassword,
    ApplyImmediately: true,
    ScalingConfiguration: {
      AutoPause: true,
      MaxCapacity: 0,
      MinCapacity: 0
    }
  };

  try {
    await rds.modifyDBCluster(params).promise();
    console.log(`Successfully changed password for user ${username} in RDS cluster ${clusterId}`);
  } catch (err) {
    console.error(`Failed to change password for user ${username} in RDS cluster ${clusterId}: ${err.message}`);
  }
};
```
I'm getting this error : 
ERROR	Failed to change password for user postgres in RDS cluster reset-test: You can only specify scaling configuration for an Aurora Serverless v1 cluster.

The problem is that the cluster's capacity type is Provisioned: single-master so it's obviously not a Serverless v1 cluster. 

I also tried performing the update using the AWS-cli with an user with the same role I'm using from the SDK and it was able to perform the change. It doesn't seem to be a permissions issue. But just to make sure here is the policy attached to the lambda role. 

```
{
    "Statement": [
        {
            "Action": [
                "ssm:GetParameters",
                "ssm:GetParameter",
                "secretsmanager:GetSecretValue",
                "ssm:PutParameter",
                "secretsmanager:PutSecretValue"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:ssm:us-east-1:801430957106:parameter/*",
                "arn:aws:secretsmanager:us-east-1:xxxxxxxxxxxx:cluster:secret:*"
            ]
        },
        {
            "Action": [
                "rds:ModifyDBInstance"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:rds:us-east-1:xxxxxxxxxxxx:cluster:db:*"
            ]
        },
        {
            "Action": [
                "rds:ModifyDBCluster"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:rds:us-east-1:xxxxxxxxxxxx:cluster:*"
            ]
        }
    ],
    "Version": "2012-10-17"
}
```

### SDK version number

@aws-sdk/package-name@version, ...

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

I'm running this from a lambda function on top of a docker image of public.ecr.aws/lambda/nodejs:16

### Reproduction Steps

Run the snippet of code pasted in the description within a lambda function an Aurora Postgres cluster provisioning one db.t4g.medium instance. 
 

### Observed Behavior

2023-02-15T18:37:09.763Z	01337f35-8dd9-4f66-8201-0963838473b0	ERROR	Failed to change password for user postgres in RDS cluster xxxxxxxx: You can only specify scaling configuration for an Aurora Serverless v1 cluster.

### Expected Behavior

I would expect to have the master password updated.

**Comment by RanVaknin** [comment]
Hi @imendi ,

Thanks for opening this issue. 
Since you said the same action works on the CLI, my thoughts are either you are not running the same command, or the SDK does something slightly differently. 

To be sure, Id like to compare the SDK logs to the CLI logs - that would help us see where the discrepancy lies. 

Can you please do the following:
- show us which command you used in the CLI
- run that same command in CLI with the --debug flag enabled and share those logs here.
- share logs from SDK. You can intercept the request by using middleware like so:

```js
rds.middlewareStack.add(next => args => {
    console.log('before sign: ' , args.request);
    return next(args);
}, {step: 'build'})
```

Thank you very much,
Ran~

**Comment by imendi** [comment]
Ran, thank you for the quick response. 

I found the issue. 

```
    ScalingConfiguration: {
      AutoPause: true,
      MaxCapacity: 0,
      MinCapacity: 0
    }
```

by setting ScalingConfiguration the API is assuming the cluster is a Serverless v1 because the property is only used on that kind of cluster.
