### ISSUE TITLE
Global services should not require a region

### ISSUE THREAD

**Issue by fjinkis** [aws/aws-sdk-js-v3#4441]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I'm opening a new issue because [#1955](https://github.com/aws/aws-sdk-js-v3/issues/1995) was closed and IAM client still requires for a region even though it's a global service.

### SDK version number

@aws-sdk/client-iam@3.272.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.2.0

### Reproduction Steps

```javascript
const { IAM } = require('@aws-sdk/client-iam');
const { fromEnv } = require('@aws-sdk/credential-providers');
const { get } = require('lodash');

async function main(profile) {
  try {
    const iam = new IAM({
      apiVersion: '2010-05-08',
      credentials: fromEnv()
    });
    const NO_INPUT_OBJECT = {};
    const user = await iam.getUser(NO_INPUT_OBJECT);
    console.log(
      `Hello, "${get(user, 'User.UserName')}"`
    );
  } catch (error) {
    console.error(error);
  }
}

main();
```javascript

### Observed Behavior

```bash
Error: Region is missing
    at default (/home/fjinkis/repos/.../node_modules/@aws-sdk/config-resolver/dist-cjs/regionConfig/config.js:10:15)
    at /home/fjinkis/repos/.../node_modules/@aws-sdk/node-config-provider/dist-cjs/fromStatic.js:6:83
    at /home/fjinkis/repos/.../node_modules/@aws-sdk/property-provider/dist-cjs/chain.js:11:28
    at async coalesceProvider (/home/fjinkis/repos/.../node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:14:24)
    at async /home/fjinkis/repos/.../node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:26:28
    at async useFipsEndpoint (/home/fjinkis/repos/.../node_modules/@aws-sdk/config-resolver/dist-cjs/regionConfig/resolveRegionConfig.js:21:74)
    at async resolveParams (/home/fjinkis/repos/.../node_modules/@aws-sdk/middleware-endpoint/dist-cjs/adaptors/getEndpointFromInstructions.js:29:40)
    at async getEndpointFromInstructions (/home/fjinkis/repos/.../node_modules/@aws-sdk/middleware-endpoint/dist-cjs/adaptors/getEndpointFromInstructions.js:7:28)
    at async /home/fjinkis/repos/.../node_modules/@aws-sdk/middleware-endpoint/dist-cjs/endpointMiddleware.js:8:26
    at async /home/fjinkis/repos/.../node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:5:22
```bash

### Expected Behavior

Hello, "fjinkis"

### Possible Solution

Set region to a fixed value like `us-east-1` in IAMClient class.

### Additional Information/Context

_No response_

**Comment by yenfryherrerafeliz** [comment]
Hi @fjinkis, thanks for opening this issue. I agree with this issue, as of right now every service requires the region. I will mark this issue to be reviewed so we can address this further. 

Thanks!

**Comment by RanVaknin** [comment]
Hi @fjinkis,

This is intentional. Check out my comment [here](https://github.com/aws/aws-sdk-go-v2/issues/1778#issuecomment-1210031692). 

It's kind of a minor thing, but I have seen this question come up a few times now. Do you have any suggestion on how to better document this? 

Thanks,
Ran~

**Comment by fjinkis** [comment]
Hey @RanVaknin! Sorry for my late reply. According to the [IAM service page](https://docs.aws.amazon.com/general/latest/gr/iam-service.html), the endpoint seems to be the same for almost all regions (except for the US gov). I think that we shouldn't specify the region just for a use case, however, if it is intentional I understand that.
Regarding your question, maybe you can add a note in the documentation of those global services like IAM explaining that you decided to keep the region as required only for compatibility reasons or something.

**Comment by yenfryherrerafeliz** [comment]
Hi @fjinkis, thanks for your suggestion about updating our documentation. I will pass this feedback to the correspondent team.

I will resolve this issue for now, but please feel free of opening a new issue if is there anything else that we can assist you with.

Thanks!
