### ISSUE TITLE
Snyk vulnerability error for @aws-sdk/client-dynamodb@3.272.0

### ISSUE THREAD

**Issue by aluminick** [aws/aws-sdk-js-v3#4449]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

We're getting this error from  Snyk for version @3.272.0

 
```
  Issues with no direct upgrade or patch:
  ✗ Prototype Pollution [High Severity][https://security.snyk.io/vuln/SNYK-JS-FASTXMLPARSER-3325616] in fast-xml-parser@4.0.11
  

introduced by @aws-sdk/client-dynamodb@3.272.0 > @aws-sdk/client-sts@3.272.0 > fast-xml-parser@4.0.11
  This issue was fixed in versions: 4.1.2
```

### SDK version number

@aws-sdk/client-dynamodb@3.272.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v14.18.1

### Reproduction Steps

`snyk test`

### Observed Behavior

Snyk throws error

### Expected Behavior

Snyk should run without errors.

**Comment by RanVaknin** [comment]
Hi @aluminick,

Thanks for opening the issue. 

This should be updated [here](https://github.com/awslabs/smithy-typescript/blob/82a5a399cf31a9de686f87adc28c08fddc9358b6/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java#L107). I'll mark it for review. 

Thanks,
Ran~

**Comment by zach-cribl** [comment]
This Snyk finding also applies to these clients:
- @aws-sdk/client-cloudfront
- @aws-sdk/client-ssm
- @aws-sdk/client-cloudwatch
- @aws-sdk/client-elastic-load-balancing-v2

The package.json dependency would need to be updated [here](https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-cloudfront/package.json#L57) for example. I've verified this as present in @3.272 for all named packages. For client-ssm, fast-xml-parser is introduced by the above mentioned dependency called @aws-sdk/client-sts. 

Do these need to be a separate issue?

**Comment by RanVaknin** [comment]
Hi @zach-cribl ,

No. All of the SDK cliients are code-generated from the service models of the AWS service it interacts with. This means that there is a 1 "source of truth" in this case, its [here](https://github.com/awslabs/smithy-typescript/blob/82a5a399cf31a9de686f87adc28c08fddc9358b6/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java#L107).
This line would need to be updated with the most recent dependency of xml-parser and would need to be tested.

I've added this to the backlog, someone will take a look at it based on prioritization. 

Thanks,
Ran~

**Comment by prmanojbabu** [comment]
Hi Team
When can we expect it to be fixed ?

**Comment by jeremy-brooks** [comment]
This one has come up as a high vulnerability in AWS Inspector scans, any update on a fix at all?

**Comment by trivikr** [comment]
This issue was already fixed in https://github.com/aws/aws-sdk-js-v3/pull/4454, and published in https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.276.0
