### ISSUE TITLE
Connection created using Amazon OpenSearch Service SDK cannot be accepted with Amazon Elasticsearch Service SDK

### ISSUE THREAD

**Issue by lucsan** [aws/aws-sdk-js-v3#4453]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

ValidationException: Connection created using Amazon OpenSearch Service SDK cannot be accepted with Amazon Elasticsearch Service SDK
    at throwDefaultError (/Users/luke/projects/dataLoader/dataService/node_modules/@aws-sdk/client-elasticsearch-service/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)

### SDK version number

@aws-sdk/client-elasticsearch-service": "^3.272.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.10.0

### Reproduction Steps

mount the following code as a node js file and run with node yourFilename.js

```js
const {
  ElasticsearchServiceClient,
  AcceptInboundCrossClusterSearchConnectionCommand
} = require("@aws-sdk/client-elasticsearch-service")

const client = new ElasticsearchServiceClient({ region: "eu-west-2" })

const params = {
  /** input parameters */
  CrossClusterSearchConnectionId: 'https://search-some-es-instance.eu-west-2.es.amazonaws.com'
}
const command = new AcceptInboundCrossClusterSearchConnectionCommand(params)

console.log(command)

async function stuff() {
  // async/await.
  try {
    const data = await client.send(command);
    // process data.
  } catch (error) {
    console.log(error)

    // error handling.
  } finally {
    // finally.
  }
}

stuff()
```

### Observed Behavior
```console
AcceptInboundCrossClusterSearchConnectionCommand {
  middlewareStack: {
    add: [Function: add],
    addRelativeTo: [Function: addRelativeTo],
    clone: [Function: clone],
    use: [Function: use],
    remove: [Function: remove],
    removeByTag: [Function: removeByTag],
    concat: [Function: concat],
    applyToStack: [Function: cloneTo],
    identify: [Function: identify],
    resolve: [Function: resolve]
  },
  input: {
    CrossClusterSearchConnectionId: 'https://search-###.eu-west-2.es.amazonaws.com'
  }
}
ValidationException: Connection created using Amazon OpenSearch Service SDK cannot be accepted with Amazon Elasticsearch Service SDK
    at throwDefaultError (/Users/luke/projects/dataLoader/dataService/node_modules/@aws-sdk/client-elasticsearch-service/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at deserializeAws_restJson1AcceptInboundCrossClusterSearchConnectionCommandError (/Users/luke/projects/dataLoader/dataService/node_modules/@aws-sdk/client-elasticsearch-service/dist-cjs/protocols/Aws_restJson1.js:1178:51)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/luke/projects/dataLoader/dataService/node_modules/@aws-sdk/client-elasticsearch-service/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /Users/luke/projects/dataLoader/dataService/node_modules/@aws-sdk/client-elasticsearch-service/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20
    at async /Users/luke/projects/dataLoader/dataService/node_modules/@aws-sdk/client-elasticsearch-service/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /Users/luke/projects/dataLoader/dataService/node_modules/@aws-sdk/client-elasticsearch-service/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:5:22
    at async stuff (/Users/luke/projects/dataLoader/dataService/essdk3/main.js:24:18) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: 'b6b8926e-d0d8-4552-bac0-2b93d334211f',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}
```
### Expected Behavior

A connection to an es instance

### Possible Solution

make @aws-sdk/client-elasticsearch-service work with eleasticsearch

### Additional Information/Context

from aws sdk 3.  Code used taken from https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-elasticsearch-service/index.html

**Comment by RanVaknin** [comment]
Hi @lucsan,

The error is pretty self explanatory. Are you following some documentation or a tutorial that suggest that Elasticsearch can accept connections from opensearch? 

Thanks,
Ran~

**Comment by lucsan** [comment]
Yes, as illustrated in the email, and as requested in the submission form,
I included the github page from which I cut and paste the code. My only
contribution was to provide a working HTTP for an elasticsearch instance
and to mount the code in nodejs.

The error tells me an elasticsearch tool wont let me look in elasticsearch
because it's an opensearch tool, this, I think, is a bug or it's a
confused A.I. Perhaps I am using the wrong tool to interact with the data
on my elasticsearch instance? In which case would you be able to inform me
of the correct tool?

Many Thanks

Luke

**Comment by RanVaknin** [comment]
Hi @lucsan ,

The link you mentioned just showed the necessary imports and boilerplate code you need to use the elasticSearch SDK client, not which values to use for which fields.

>My only contribution was to provide a working HTTP for an elasticsearch instance
and to mount the code in nodejs.

If you look in this [documentation](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/cross-cluster-search.html), the first line under limitations:

> You can't connect an Elasticsearch domain to an OpenSearch domain.

As I mentioned before the error is self explanatory, this is the intended behavior.
My suggestion is to read the OpenSearch API docs to get a better understanding how the API works, and then using the SDK will be easier. 

Thanks,
Ran~

**Comment by lucsan** [comment]
Hi Ran,

I feel your not understanding my issues. We are running elasticsearch v6 as
provided by AWS, not opensearch, I would like to connect to our
elasticsearch instance using AWS sdk3 and read a bit of data from it, and,
as you point out, neither the boiler plate nor the documentation list which
fields are needed | optional and the type of value they accept, or did I
miss this?

if @aws-sdk/client-elasticsearch-service": "^3.272.0 wont connect to an
elasticsearch instance then it should be renamed (maybe
client-opensearch-service), and I am left asking, what is the tool I need?
Also you are strongly signalling that this is a documentation issue, not a
bug, yet you closed the documentation ticket.

Thanks

Luke

**Comment by RanVaknin** [comment]
Hi @lucsan ,

Thanks for the information, this required a bit of digging. 
Just as a nugget of information, AWS branched off of elasticSearch into Opensearch:

>This project includes OpenSearch (derived from Elasticsearch 7.10.2) and OpenSearch Dashboards (derived from Kibana 7.10.2). Additionally, the OpenSearch project is the new home for our previous distribution of Elasticsearch (Open Distro for Elasticsearch),

[full article 
](https://aws.amazon.com/blogs/opensource/introducing-opensearch/)

In addition, the AWS SDK is to interact with the control plane of the managed service - APIs like creating/updating a domain. Searching and indexing is not a part of the published OpenSearch API. 
For that you will need to use the [ElasticSearch SDK](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/master/introduction.html) / [OpenSearch SDK](https://opensearch.org/docs/latest/clients/javascript/index).

Since neither of those are owned by our team, I can't be much help.

If you have any additional questions please let me know.
Thanks,
Ran~

**Comment by lucsan** [comment]
That's some awesome detective work Ran, exactly what I was looking for,

Thanks

Luke
