### ISSUE TITLE
command.resolveMiddleware is not a function on @aws-sdk/smithy-client

### ISSUE THREAD

**Issue by cihad** [aws/aws-sdk-js-v3#4456]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I get the following error when I run the code snippet below.

### SDK version number

@aws-sdk/client-cloudfront@3.276.0, @aws-sdk/smithy-client@3.272.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node v16.14.2

### Reproduction Steps

```js
const {
  CloudFrontClient,
  GetFunctionCommand,
} = require('@aws-sdk/client-cloudfront');

const client = new CloudFrontClient({
  region: 'us-east-1',
  credentials: {
    accessKeyId: process.env.NX_AWS_ACCESS_KEY_ID,
    secretAccessKey: process.env.NX_AWS_SECRET_ACCESS_KEY,
  },
});

(async () => {
  const getFunctionCommand = new GetFunctionCommand({
    Name: 'setCustomHostHeader',
  })
  const data = await client.send(getFunctionCommand);
})()
```

### Observed Behavior

I got this error:

```js
/home/cihad/projects/deneme/node_modules/@aws-sdk/smithy-client/dist-cjs/client.js:13
        const handler = command.resolveMiddleware(this.middlewareStack, this.config, options);
                                ^
source-map-support.js:475
TypeError: command.resolveMiddleware is not a function
    at CloudFrontClient.send (/home/cihad/projects/deneme/node_modules/@aws-sdk/smithy-client/dist-cjs/client.js:13:33)
    at /home/cihad/projects/deneme/dist/apps/api/webpack:/nx-deneme/apps/api/src/routes/domain/router.js:54:6
    at Generator.next (<anonymous>)
    at fulfilled (/home/cihad/projects/deneme/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Expected Behavior

I expect to get the function data.

### Possible Solution

When I debug, I saw that the send function in `@aws-sdk/smithy-client/dist-cjs/client.js` worked 2 times. 1st run was normal.  However, when it ran for the 2nd time, I detected that the `command` on the `13` line was a `promise`.  This is why the error is caused.

### Additional Information/Context

I am using these other packages on package.json:
```
@aws-sdk/client-cloudfront@3.276.0
@aws-sdk/client-cognito-identity@3.276.0
@aws-sdk/client-s3@3.276.0
@aws-sdk/credential-provider-cognito-identity@3.276.0
````

**Comment by RanVaknin** [comment]
Hi @cihad ,

I refactored your code a bit and with the installed packages does not produce any error for me:

**index.js:**
```js
const {
    CloudFrontClient,
    GetFunctionCommand,
  } = require('@aws-sdk/client-cloudfront');
  
const client = new CloudFrontClient()


async function run(){
    try {
        const getFunctionCommand = new GetFunctionCommand({
            Name: 'myfunction',
        })
        const data = await client.send(getFunctionCommand);
        console.log(data)
    } catch (error) {
        console.log(error)
    }
}
run()
```

```console
$ node index.js 
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'REDACTED',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  ETag: 'REDACTED',
  ContentType: 'application/octet-stream',
  FunctionCode: Uint8Array(423) [
    102, 117, 110,  99, 116, 105, 111, 110,  32, 104,  97, 110,
    100, 108, 101, 114,  40, 101, 118, 101, 110, 116,  41,  32,
    123,  10,  32,  32,  32,  32,  47,  47,  32,  78,  79,  84,
     69,  58,  32,  84, 104, 105, 115,  32, 101, 120,  97, 109,
    112, 108, 101,  32, 102, 117, 110,  99, 116, 105, 111, 110,
     32, 105, 115,  32, 102, 111, 114,  32,  97,  32, 118, 105,
    101, 119, 101, 114,  32, 114, 101, 113, 117, 101, 115, 116,
     32, 101, 118, 101, 110, 116,  32, 116, 114, 105, 103, 103,
    101, 114,  46,  32,
    ... 323 more items
  ]
}
$ npm list
4456-cloudfront-signer-problem-smithy@1.0.0 /REDACTED/REDACTED/REDACTED/4456-cloudfront-signer-problem-smithy
├── @aws-sdk/client-cloudfront@3.276.0
└── @aws-sdk/smithy-client@3.272.0
```

You said you are making use of `aws-sdk/smithy-client@3.272.0` but I don't see the usage in your code? If that dependency isnt used try and removing it. Otherwise you can try deleting package.json and package-lock.json and running npm install again. 

Let me know how it goes.
Thanks,
Ran~

**Comment by cihad** [comment]
Thanks Ran,

This issue isn't related @aws-sdk. I'm sorry. This is completely my fault. I forgot to use `await` operator and I'm sending a promise to the `client.send` function instead a command.
