### ISSUE TITLE
Make config parameter in client constructors optional (TypeScript)

### ISSUE THREAD

**Issue by SachinShekhar** [aws/aws-sdk-js-v3#4462]
### Describe the feature

Instead of

```ts
new DynamoDBClient({})
```

I want to do this:

```typescript
new DynamoDBClient()
```

### Use Case

When I don't need to pass config object to a client constructor (let's say, I am in AWS environment or I have set appropriate environment variables etc), I need to use an empty object. This is frustrating.

### Proposed Solution

It's as easy as putting `= {}` in constructor. It won't break anything.

```typescript
constructor(config: DynamoDBClientConfig = {}) {
  // ...
  // ...
}
```
But, changes need to be made in dozens of places.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.272.0

### Environment details (OS name and version, etc.)

macOS 13.2.1 + Node v18.13.0 + typescript 4.9.4

**Comment by yenfryherrerafeliz** [comment]
Hi @SachinShekhar, thanks for opening this feature request. I will add a needs-review and priority label to this feature request so it gets added to our backlog. However, I have to make you aware that we have other items with higher priority that we will wok on first, and therefore I do not guarantee we will look at this item in the near future.

Thanks!

**Comment by RanVaknin** [comment]
related
https://github.com/aws/aws-sdk-js-v3/issues/4579

**Comment by yenfryherrerafeliz** [comment]
Hi @SachinShekhar, this feature has been implemented and is available in the latest version of the SDK. Now, the parameters expected by the client are optional. I will close this issue as resolved, but please if you have any other inquires that we can help with, feel free of opening a new issue.

Thanks!
