### ISSUE TITLE
No retry on ECONNREFUSED

### ISSUE THREAD

**Issue by adiktofsugar** [aws/aws-sdk-js-v3#4466]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When middleware-retry encounters an ECONNREFUSED error, it throws rather than retries. I experienced this when trying to run `s3Client.send(new PutObjectCommand({...}))`, but the root cause seems to be a problem with [service-error-classification#isTransientError](https://github.com/aws/aws-sdk-js-v3/blob/main/packages/service-error-classification/src/index.ts#L26).

To get around this, I created a custom retrystrategy, but even that isn't a great solution since I have to retry for _any_ error because the retrystrategy only gets retryerrorinfo, which only has the error type given be service-error-classification, which doesn't (in my opinion) classify ECONNREFUSED correctly.

### SDK version number

@aws-sdk/middleware-retry@3.272.0,@aws-sdk/util-retry@3.272.0,@aws-sdk/service-error-classification@3.272.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.15.0

### Reproduction Steps

```
import { S3Client, PutObjectCommand } from '@aws-sdk/client-s3';

const s3Client = new S3Client({ region: 'us-east-1' );
await s3Client.send(new PutObjectCommand({ Bucket: 'fake', Key: 'key-1', Body: 'anything', ContentType: 'text/plain' }));
```
When the s3 service happens to respond with ECONNREFUSED, this fails. I do not know enough about the aws-sdk to fake the endpoints and creates something realistic to get it to work end-to-end.

### Observed Behavior

This error was thrown. I don't have the full error as this is thrown from middleware-retry
```
Error: connect ECONNREFUSED <ip>:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: <ip>,
  port: 443,
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
```

### Expected Behavior

That ECONNREFUSED would be treated as a transient error and would be retried as such.

### Possible Solution

Change service-error-classification's `isTransientError` to return true for `ECONNREFUSED` errors.

I assume it was some issue on the AWS backend that caused it, like a service restart, but it would be nice if it was handled by aws, since that kind of thing is outside my control.

Alternatively, allowing the retryStrategy to access the original sdkError to make that decision on its own, or adding another error type on ECONNREFUSED errors, although personally I believe this to be similar to ECONNRESET errors and should be handled the same way.

### Additional Information/Context

This doesn't happen often, and happened in my company's CI environment.

**Comment by RanVaknin** [comment]
Hi @adiktofsugar ,

Thanks for bringing this to our attention. Based on behavior of other SDKs Im inclined to say you are right and ECONNREFUSED should be added to transient errors list. 

I've marked this for review by one of the SDEs, once they review it they can decide whether or not to implement.
___ 
Proposed fix:
In [`constants.ts`](https://github.com/aws/aws-sdk-js-v3/blob/ab0e7be36e7e7f8a0c04834357aaad643c7912c3/packages/service-error-classification/src/constants.ts):

```diff
- export const NODEJS_TIMEOUT_ERROR_CODES = ["ECONNRESET", "EPIPE", "ETIMEDOUT"];
+ export const NODEJS_TIMEOUT_ERROR_CODES = ["ECONNRESET", "ECONNREFUSED", "EPIPE", "ETIMEDOUT"];
```
And / Or same fix [here ](https://github.com/aws/aws-sdk-js-v3/blob/ab0e7be36e7e7f8a0c04834357aaad643c7912c3/packages/service-error-classification/src/constants.ts)

Thanks,
Ran~
