### ISSUE TITLE
Upload with xhr-http-handler fails: XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by Fiyin-Anne** [aws/aws-sdk-js-v3#4473]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I am trying to upload files using `@aws-sdk/lib-storage` (Upload instance). I've seen that to incrementally monitor the upload progress, I need to also use `@aws-sdk/xhr-http-handler`. But it does not work as expected.

### SDK version number

@aws-sdk/xhr-http-handler@3.274.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v14.16.0

### Reproduction Steps

```js
const { Upload } = require("@aws-sdk/lib-storage");
const { S3Client, S3 } = require("@aws-sdk/client-s3");
const { XhrHttpHandler } = require("@aws-sdk/xhr-http-handler");

const tests3 = () => {
  const parallelUploads3 = new Upload({
      client: new S3Client({
          requestHandler: new XhrHttpHandler({}),
          credentials: {
              accessKeyId,
              secretAccessKey
          },
          region: S3REGION
      }),
      params: { 
          ACL:'public-read',
          Bucket: S3BUCKET, 
          Key:  "test.txt",
          Body: "filestream text"
     },
     tags: [], // optional tags
     queueSize: 4, // optional concurrency configuration
     partSize: 1024 * 1024 * 5, // optional size of each part, in bytes, at least 5MB
     leavePartsOnError: false, // optional manually handle dropped parts
  })
  .on("httpUploadProgress", (progress) => {
     console.log("UPLOADPROGRESS", progress);
  })
  .done()
  .then((resp) => {
    console.log("RESP:::", resp)
  }).catch((err) => {
    console.log("ERROR:::", err)
  })
}

```

### Observed Behavior

The file did not get uploaded to my s3 bucket. Instead, I got this error message.

```
ReferenceError: XMLHttpRequest is not defined
    at XhrHttpHandler.handle (/home/runner/tests3/node_modules/@aws-sdk/xhr-http-handler/dist-cjs/xhr-http-handler.js:55:21)
    at /home/runner/tests3/node_modules/@aws-sdk/client-s3/dist-cjs/commands/PutObjectCommand.js:53:58
    at /home/runner/tests3/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:5:32
    at /home/runner/tests3/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/check-content-length-header.js:21:16
    at /home/runner/tests3/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:26
    at async /home/runner/tests3/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /home/runner/tests3/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:58:20
    at async /home/runner/tests3/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:5:22
    at async Promise.all (index 0) {
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
```

But it uploads correctly when I remove the `requestHandler` parameter from the S3 client object.

### Expected Behavior

- To upload the file correctly and return the upload progress.

**Comment by kuhe** [comment]
`XMLHttpRequest` is available in browsers. For Node.js the default request handler should be sufficient to report upload progress.
