### ISSUE TITLE
I am getting an "ERR_INVALID_ARG_TYPE" error while using typescript

### ISSUE THREAD

**Issue by bayurzxsmtp** [aws/aws-sdk-js-v3#4475]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

This is a Lambda function written in TypeScript that gets triggered by S3 events. The Lambda function scans a DynamoDB table to retrieve all the connection IDs of connected clients, and then sends a message to each connected client using the ApiGatewayManagementApiClient library. If sending a message fails, the function tries to delete the connection ID from the DynamoDB table.

but I am getting this error instead
```
{
    "code": "ERR_INVALID_ARG_TYPE",
    "$metadata": {
        "attempts": 1,
        "totalRetryDelay": 0
    }
}
```
I am using typescript, if I had inputed an incorrect parameter, it would have been detected
I can't trace the error to its point of origin since.

### SDK version number

@aws-sdk/client-apigatewaymanagementapi

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

It runs on aws-lambda. It should be v14.21.2

### Reproduction Steps

```
async function sendMessageToClient(connectionId: string, payload) {
  try {
    console.log('Sending message to a connection', connectionId)

    const apiGatewayManagementApi = new ApiGatewayManagementApiClient({
      apiVersion: "2018-11-29",
      endpoint: `https://${apiId}.execute-api.us-east-1.amazonaws.com/${stage}`
    });

    console.log("apiId", apiId, "stage", stage, "payload", payload);
    

    const postToConnectionCommand = new PostToConnectionCommand({
      ConnectionId: connectionId,
      Data: payload
    });
    console.log("postToconnection command", postToConnectionCommand);
    

    const response = (await apiGatewayManagementApi.send(postToConnectionCommand));
    
    console.log("response", response);
    

  } catch (err) {
    console.log('Failed to send message', JSON.stringify(err))
    console.log('Failed !!!!', err)
    if (err.statusCode === 410) {
      console.log('Stale connection')

      await deleteItem(connectionsTable, connectionId)
    }
  }

}
```
![connectionId_and_payload](https://user-images.githubusercontent.com/92230919/221415854-4e46d64c-63ac-4cf5-805a-6d1f1bb4e75a.png)

### Observed Behavior

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
    at __node_internal_captureLargerStackTrace (internal/errors.js:412:5)
    at __node_internal_addCodeToName (internal/errors.js:168:9)
    at new NodeError (internal/errors.js:322:7)
    at Function.from (buffer.js:334:9)
    at writeBody (/node_modules/@aws-sdk/client-apigatewaymanagementapi/node_modules/@aws-sdk/node-http-handler/dist-cjs/write-request-body.js:22:32)
    at writeRequestBody (/node_modules/@aws-sdk/client-apigatewaymanagementapi/node_modules/@aws-sdk/node-http-handler/dist-cjs/write-request-body.js:13:9)
    at /node_modules/@aws-sdk/client-apigatewaymanagementapi/node_modules/@aws-sdk/node-http-handler/dist-cjs/node-http-handler.js:96:38
    at new Promise (<anonymous>)
    at NodeHttpHandler.handle (/node_modules/@aws-sdk/client-apigatewaymanagementapi/node_modules/@aws-sdk/node-http-handler/dist-cjs/node-http-handler.js:49:16)
    at /node_modules/@aws-sdk/client-apigatewaymanagementapi/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:5:26
    at /node_modules/@aws-sdk/client-apigatewaymanagementapi/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20
    at /node_modules/@aws-sdk/client-apigatewaymanagementapi/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at /node_modules/@aws-sdk/client-apigatewaymanagementapi/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:5:22
    at sendMessageToClient (/src/functions/sendUploadNotifications/handler.ts:88:23)
    at sendUploadNotifications (/src/functions/sendUploadNotifications/handler.ts:58:9)
    at runRequest (/node_modules/@middy/core/index.js:84:32) {
  code: 'ERR_INVALID_ARG_TYPE',
  '$metadata': { attempts: 1, totalRetryDelay: 0 }

### Expected Behavior

I was meant to receive a message through my web socket connection that upload was successful.

### Possible Solution

I assumed that the payload was meant to be a string but, I tried to JSON.stringify but typescript rejects string
![image](https://user-images.githubusercontent.com/92230919/221417160-5829f138-ec58-4134-a473-e24a129ae405.png)

**Comment by bayurzxsmtp** [comment]
I ignored the thrown error by typescript and ran it like that, `JSON.stringify(payload)`. It worked

I think `node_modules\@aws-sdk\client-apigatewaymanagementapi\dist-types\models\models_0.d.ts` needs to be updated

![image](https://user-images.githubusercontent.com/92230919/221420081-fbdf72c4-973b-47dc-ba70-816ce5b2952e.png)

**Comment by RanVaknin** [comment]
Hi @bayurzxsmtp ,

The SDK clients are all code generated from the API model of the service with which they interact, so we can't make changes to the input types in the model.  You'll notice on the top of that file you edited, you'll see this written:
>// smithy-typescript generated code

This indicates that this code is auto-generated and suggests that you should not edit this file. 

In your case, [this](https://github.com/aws/aws-sdk-js-v3/blob/main/codegen/sdk-codegen/aws-models/apigatewaymanagementapi.json#L1962-L1971) is the "source of truth" in regards to how the `Data` field is defined. 
In the model file you can see that it is a "blob", or binary - not a String.
The JS V3 SDK generated type for Smithy's "blob" shape - is Uint8Array. 

The ts error that you ignored is probably because the encoding isnt the same. You can solve it by doing one of the following:

```js
import {fromUtf8 } from '@aws-sdk/util-utf8-node';

/*
some code
*/

const postToConnectionCommand = new PostToConnectionCommand({
    ConnectionId: connectionId,
    Data: fromUtf8(JSON.stringify(payload)));
});
```

or

```js
/*
some code
*/

const postToConnectionCommand = new PostToConnectionCommand({
    ConnectionId: connectionId,
    Data: Buffer.from(JSON.stringify(payload)));
});
```

This is intended behavior.

Let us know if you have any questions.
Thanks,
Ran~
