### ISSUE TITLE
DynamoDB Waiters (waitUntilTableExists) causing 'Internal Server Error'

### ISSUE THREAD

**Issue by DarrenNavitas** [aws/aws-sdk-js-v3#4479]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Following the code as set out in the Developer Guide and as soon as I invoke a waitUntilTableExists() waiter, an error is thrown and the response is just 

`{
    "message": "Internal Server Error"
}`

As soon as the waiter code is active in the lambda function I instantly get the response shown above.  If I forgo using the waiter no issues at all.

I'm probably doing something obviously wrong - but I can't see what it is!

Following code example in first 'scenario' https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/javascript_dynamodb_code_examples.html

### SDK version number

@aws-sdk/client-dynamodb

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node.js 18.x

### Reproduction Steps

`
import { 
  DynamoDBClient,
  ListTablesCommand,
  CreateTableCommand,
  waitUntilTableExists
} from "@aws-sdk/client-dynamodb";
`

Code that creates a table (successfully)..... then...

`const results = await waitUntilTableExists(
                                  { client: ddbClient, maxWaitTime: 15, maxDelay: 2, minDelay: 1 },
                                  { TableName: tableName }
                                );`

### Observed Behavior

As soon as the waiter code is invoke an internal server error exception is thrown

### Expected Behavior

Expected a WaiterResult object to be returned

**Comment by DarrenNavitas** [comment]
Hi @RanVaknin 

Thanks for the reply!  Sorry for not including the code first time round - it's part of a bigger function that handles various event route keys from the API Gateway.  The process flow is actually `ListTables` (initially and held in memory) and then when the POST event is fired then the event.PathParameters contains the table name.  If it's not in the list then the `CreateTableCommand -> WaitUntilTableExists` process is used to create the new table and then post data to it.

I've trimmed down the code so provide the parts that would be utilised in the process.  Please let me know if you can see anything that might be causing my issue.

``` javascript
import { 
  DynamoDBClient,
  ListTablesCommand,
  CreateTableCommand,
  waitUntilTableExists
} from "@aws-sdk/client-dynamodb";

import {
  DynamoDBDocumentClient,
  ScanCommand,
  PutCommand,
  GetCommand,
  DeleteCommand,
  QueryCommand
} from "@aws-sdk/lib-dynamodb";

const ddbClient = new DynamoDBClient({});
const dynamo = DynamoDBDocumentClient.from(ddbClient);

let currentTables;

export const handler = async (event, context) => {
  if(!currentTables) 
  {
    let listOfTablesResult = await ddbClient.send(new ListTablesCommand({}));
    currentTables = listOfTablesResult.TableNames;
  }
  let body;
  let statusCode = 200;
  let tableName =  event.pathParameters.GDSID;
  const headers = {
    "Content-Type": "application/json",
  };

  try {
        switch (event.routeKey) {
        case "POST /items/{GDSID}":
            if (!currentTables.includes(tableName)) //If table doesn't exist
            {
              const params = {
                AttributeDefinitions: [
                  {
                    AttributeName: "User",
                    AttributeType: "S",
                  },
                  {
                    AttributeName: "DateTime", 
                    AttributeType: "S",
                  },
                ],
                KeySchema: [
                  {
                    AttributeName: "User",
                    KeyType: "HASH",
                  },
                  {
                    AttributeName: "DateTime", //ATTRIBUTE_NAME_2
                    KeyType: "RANGE",
                  },
                ],
                BillingMode: "PAY_PER_REQUEST",
                TableName: tableName,
                StreamSpecification: {
                  StreamEnabled: false,
                },
              };

             var createTbl = await client.send(new CreateTableCommand(params));
              currentTables.push(tableName);

              // Wait for table to be created
              const waiterConfig = {
                client : ddbClient,
                maxWaitTime : 120,
              };
              try 
              {
                 const results = await waitUntilTableExists(waiterConfig, {TableName: tableName});
              } 
              catch (e) 
              {
                body = e;
              }
            
              if (results.state != 'SUCCESS') {
                throw `Table Creation Delayed - ${results.reason}`;
              }
            }
            
            let putJSON = JSON.parse(event.body);
            await dynamo.send(
              new PutCommand({
                TableName: "GDSKeyLogging" + event.pathParameters.GDSID,
                Item: {
                    DateTime : new Date().toISOString(),
                    User: putJSON.User,
                    Entry: putJSON.Entry
                },
              })
            );
            body = `Put new Item into table ${tableName}`;
        break;

      default:
        throw new Error(`Unsupported route: "${event.routeKey}"`);
    }
  } catch (err) {
    statusCode = 400;
    body = err.message ? err.message : err;
  } finally {
    body = JSON.stringify(body);
  }

  return {
    statusCode,
    body,
    headers,
  };
};
``` 

Thanks
Darren

**Comment by RanVaknin** [comment]
Hi Darren,

The code looks ok aside from this:

```js
             var createTbl = await client.send(new CreateTableCommand(params));

             // Instead should be:
             var createTbl = await ddbClient.send(new CreateTableCommand(params));
```

and also:
```js
              try 
              {
                 const results = await waitUntilTableExists(waiterConfig, {TableName: tableName});
              } 
              catch (e) 
              {
                body = e;
              }
            
            // results is undefined here since its declared in the scope of the trycatch
              if (results.state != 'SUCCESS') {
                throw `Table Creation Delayed - ${results.reason}`;
              }
```



Its difficult to test and debug this in a context of lambda. If this doesnt solve your issue, I think the best way to debug this would be for you to add a middleware step to log the request

```js
const ddbClient = new DynamoDBClient({})

ddbClient.middlewareStack.add(next => args => {
    console.log('my request: ' , args.request);
    return next(args);
}, {step: 'deserialize'})
```

If you have cloudwatch logs connected to your lambda, these logs will be visible there and then right before the 500 error occurs the middleware should log all the request fields. 
it should look something like that:

```console
my request:  HttpRequest {
  method: 'POST',
  hostname: 'dynamodb.us-east-1.amazonaws.com',
  port: undefined,
  query: {},
  headers: {
    'content-type': 'application/x-amz-json-1.0',
    'x-amz-target': 'DynamoDB_20120810.CreateTable',
    'content-length': '391',
    host: 'dynamodb.us-east-1.amazonaws.com',
    'x-amz-user-agent': 'aws-sdk-js/3.282.0',
    'user-agent': 'aws-sdk-js/3.282.0 os/darwin/21.6.0 lang/js md/nodejs/18.13.0 api/dynamodb/3.282.0',
    'amz-sdk-invocation-id': 'REDACTED',
    'amz-sdk-request': 'attempt=1; max=3',
    'x-amz-date': '20230302T201929Z',
    'x-amz-content-sha256': 'REDACTED',
    authorization: 'AWS4-HMAC-SHA256 Credential=REDACTED/20230302/us-east-1/dynamodb/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-target;x-amz-user-agent, Signature=REDACTED'
  },
  body: '{"AttributeDefinitions":[{"AttributeName":"CUSTOMER_ID","AttributeType":"N"},{"AttributeName":"CUSTOMER_NAME","AttributeType":"S"}],"KeySchema":[{"AttributeName":"CUSTOMER_ID","KeyType":"HASH"},{"AttributeName":"CUSTOMER_NAME","KeyType":"RANGE"}],"ProvisionedThroughput":{"ReadCapacityUnits":1,"WriteCapacityUnits":1},"StreamSpecification":{"StreamEnabled":false},"TableName":"MY_TABLE"}',
  protocol: 'https:',
  path: '/'
}
```

Let me know if this helps.
Thanks,
Ran~

**Comment by DarrenNavitas** [comment]
Thanks for the help. The code issues were where I had been testing multiple things and forgot to tidy things up correctly!

I've implemented the middleware step you suggested - and can see in the Cloudwatch that it seems to be failing to get a response from the DescribeTable request (that the waitUntilTableExits function obviously performs in the background )

```
2023-03-03T15:29:03.141Z	7ca6f7b1-7e53-4c7c-bb78-a04f9c93afc0	INFO	my request:  HttpRequest {
  method: 'POST',
  hostname: 'dynamodb.eu-west-2.amazonaws.com',
  port: undefined,
  query: {},
  headers: {
    'content-type': 'application/x-amz-json-1.0',
    'x-amz-target': 'DynamoDB_20120810.DescribeTable',
    'content-length': '33',
    host: 'dynamodb.eu-west-2.amazonaws.com',
    'X-Amzn-Trace-Id': 'Root=1-6402123d-2ef1059d7695de9c25011426;Parent=7560a6b976fea97a;Sampled=0',
    'x-amz-user-agent': 'aws-sdk-js/3.188.0',
    'user-agent': 'aws-sdk-js/3.188.0 os/linux/4.14.255-301-238.520.amzn2.x86_64 lang/js md/nodejs/18.13.0 md/crt-avail api/dynamodb/3.188.0 exec-env/AWS_Lambda_nodejs18.x',
    'amz-sdk-invocation-id': 'REDACTED',
    'amz-sdk-request': 'attempt=1; max=3',
    'x-amz-date': '20230303T152903Z',
    'x-amz-security-token': 'REDACTED',
    'x-amz-content-sha256': 'REDACTED',
    authorization: 'AWS4-HMAC-SHA256 Credential=REDACTED/20230303/eu-west-2/dynamodb/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-security-token;x-amz-target;x-amz-user-agent, Signature=REDACTED'
  },
  body: '{"TableName":"GDSKeyLogging52A0"}',
  protocol: 'https:',
  path: '/'
}

```

After this request the next entry is :

```
2023-03-03T15:29:05.519Z 7ca6f7b1-7e53-4c7c-bb78-a04f9c93afc0 Task timed out after 3.01 seconds

```

**Comment by RanVaknin** [comment]
Hi @DarrenNavitas,

I think I know the issue. You need to update the lambda function configuration to have a longer timeout, because by default the timeout is 3seconds. Since your waiter is taking longer the Lambda timeouts first.

You can run this code locally to change it:

```js
const { LambdaClient, UpdateFunctionConfigurationCommand } = require('@aws-sdk/client-lambda')

const client = new LambdaClient({region: "us-east-1"})

try {
    await client.send(new UpdateFunctionConfigurationCommand({
        FunctionName: "myfunction",
        Timeout: 15 // 1 min , 60 max
    }))
} catch (err) {
    console.log(err)
}
```

Or even easier from the CLI:
```
aws lambda update-function-configuration --function-name myfunction --timeout 15 --region us-east-1
```

Let me know if that helps,

Thanks,
Ran~

**Comment by DarrenNavitas** [comment]
Hi Ran,
Thanks for the response.  I tried your suggestion - increasing the timeout to 15 secs and then 30 secs......

The cloudwatch logs were still showing that was timing out (Even when I'm testing with an existing table).

So I thought I'd go back a step and try using the DescribeTableCommand directly.  This also timed out, but usefully threw an error that stated I didn't have permission to run that command !!!!

Having checked the IAM management Role that was assigned to the Lambda function - it had many permissions but not DescribeTable.  Once added, the DescribeTableCommand worked - and then in turn the waitUntilTableExists also worked !!

As suspected - it was something simple after all!

Many thanks for your help and patience !

Cheers
Darren

**Comment by RanVaknin** [comment]
Hi Darren,

Thanks for the follow up, glad you figure it out.

All the best,
Ran~
