### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'socket')

### ISSUE THREAD

**Issue by parvej-code** [aws/aws-sdk-js-v3#4484]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I have trying to get object from s3. But whenever I am trying to fetch it using bellow code

```
s3Client.send(
  new GetObjectCommand({
    Bucket: 'My-Bucket-Name',
    Key: 'My-Key',
  }),
)
```

It shows bellow error

```
Error	3/1/2023, 10:08:09 AM [ExceptionsHandler] Cannot read properties of undefined (reading 'socket') - {
  stack: [
    "TypeError: Cannot read properties of undefined (reading 'socket')\n" +
      '    at Object.responseOnEnd [as end] (node:_http_client:679:22)\n' +
      '    at TransformOperationExecutor.transform (/opt/projects/sketch_server/node_modules/src/TransformOperationExecutor.ts:207:39)\n' +
      '    at TransformOperationExecutor.transform (/opt/projects/sketch_server/node_modules/src/TransformOperationExecutor.ts:327:31)\n' +
      '    at TransformOperationExecutor.transform (/opt/projects/sketch_server/node_modules/src/TransformOperationExecutor.ts:327:31)\n' +
      '    at ClassTransformer.instanceToPlain (/opt/projects/sketch_server/node_modules/src/ClassTransformer.ts:25:21)\n' +
      '    at Object.classToPlain (/opt/projects/sketch_server/node_modules/src/index.ts:23:27)\n' +
      '    at ClassSerializerInterceptor.transformToPlain (/opt/projects/sketch_server/node_modules/@nestjs/common/serializer/class-serializer.interceptor.js:53:37)\n' +
      '    at ClassSerializerInterceptor.serialize (/opt/projects/sketch_server/node_modules/@nestjs/common/serializer/class-serializer.interceptor.js:46:20)\n' +
      '    at /opt/projects/sketch_server/node_modules/@nestjs/common/serializer/class-serializer.interceptor.js:35:54\n' +
      '    at /opt/projects/sketch_server/node_modules/rxjs/src/internal/operators/map.ts:58:33'
  ]
} 
```

Here is my dependency

```
 "@aws-sdk/client-s3": "^3.278.0",
```

### SDK version number

 "@aws-sdk/client-s3": "^3.278.0"

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.0.0

### Reproduction Steps

Added in description

### Observed Behavior

Added in description

### Expected Behavior

Added in description

**Comment by RanVaknin** [comment]
Hi @parvej-code ,

Can you please include a complete code example including imports? 

Thanks,
Ran~

**Comment by parvej-code** [comment]
@RanVaknin 

```
import { S3Client, GetObjectCommand } from '@aws-sdk/client-s3';

const s3Client = new S3Client({
  region: 'AWS_REGION',
  credentials: {
    accessKeyId: 'AWS_ACCESS_KEY_ID',
    secretAccessKey: 'AWS_SECRET_ACCESS_KEY',
  },
});


s3Client.send(
  new GetObjectCommand({
    Bucket: 'My-Bucket-Name', //replace with actual bucket name
    Key: 'My-Key', // replace with actual key
  }),
)

```

**Comment by RanVaknin** [comment]
Hi @parvej-code ,

If you are passing `'AWS_REGION'`, `'AWS_ACCESS_KEY_ID'` and `'AWS_SECRET_ACCESS_KEY'` as values then thats where your error is. If you are, you need to pass the actual AWS region and credentials information in your config.

Otherwise the code looks correct and the problem may be with your setup. Are you running this from your local machine or on a lambda? Are you passing config information via environment variables or hardocding it in? 

The more information you can share the better, this is not a lot to go off of. 

Thanks,
Ran~

**Comment by parvej-code** [comment]
Obviously I have replaced those with actual value. I am not gonna share my actual cred here. @RanVaknin There is nothing wrong with my config as PutCommand works. BTW I am doing it from local machine.

**Comment by leoander01** [comment]
I had a similar problem in NestJS and I managed to solve it like this:
```typescript
// s3.service.ts

import { S3Client, GetObjectCommand } from '@aws-sdk/client-s3'

buildS3() {
  return new S3Client({
    region: 'AWS_S3_REGION',
    credentials: {
      accessKeyId: 'AWS_S3_ACCESS_KEY_ID',
      secretAccessKey: 'AWS_S3_SECRET_ACCESS_KEY',
    },
  })
}

async getObjectStream(key: string): Promise<Readable> {
  const s3 = this.buildS3()
  const getObjectCommand = new GetObjectCommand({
    Bucket: 'AWS_S3_BUCKET_NAME',
    Key: key,
  });
  const { Body } = await this.s3.send(getObjectCommand)
  return Body as Readable
}
```
And in the `controller` I made the return like this:
```typescript
// app.controller.ts

@Get(':key')
async getFile(@Param('key') key: string, @Res() res: Response) {
  const stream = await this.s3Service.getObjectStream(key)
  stream.pipe(res)
}
```

**Comment by parvej-code** [comment]
@leoander01 Thank you. It worked

**Comment by RanVaknin** [comment]
Hi, 

Your usage of Nest.js was the piece of information I was missing.
Now looking at the stack trace I don't see a mention to the SDK. 
This is clearly an error from a Nest.js plugin or middleware.

Since getObject is working as expected and theres no action item from the SDK team I feel confident we can close.
If you run into additional problems feel free to open an additional issue.

Thanks,
Ran~
