### ISSUE TITLE
NotAuthorizedException for AdminInitateAuth with valid Refresh Token

### ISSUE THREAD

**Issue by flodaniel** [aws/aws-sdk-js-v3#4485]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Sometimes (not always) when calling `AdminInitiateAuth` with the code below, we receive an `NotAuthorizedException`. When we then proceed to take the exact same refresh token (and other required params) and rebuild the request with Postman, the refresh completes successfully. 

```ts
 const adminInitiateAuthCommand: AdminInitiateAuthCommand = new AdminInitiateAuthCommand({
            ClientId: this.awsCognitoConfig.clientId,
            AuthFlow: "REFRESH_TOKEN_AUTH",
            UserPoolId: this.awsCognitoConfig.userPoolId,
            AuthParameters: {
                REFRESH_TOKEN: "THE_REFRESH_TOKEN",
            },
        });

        const adminInitiateAuthOutput: AdminInitiateAuthCommandOutput =
            await this.cognitoClient.send(adminInitiateAuthCommand);
```

We are not sure when and why we receive a `NotAuthorizedException`. We have set the expiry of our refresh tokens to 3 years. 

### SDK version number

 "@aws-sdk/client-cognito-identity-provider": "3.272.0"

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.14.2

### Reproduction Steps

Sadly I am not able to provide reproducable steps, as it appears that the error occurs at random on our side. We have been unable to find any hints when specifically the error occurs. 

### Observed Behavior

This is the error reported by the SDK

```json
{
   "name":"NotAuthorizedException",
   "$fault":"client",
   "$metadata":{
      "httpStatusCode":400,
      "requestId":"5bb9f2d1-b09d-45eb-8fd0-720fbe7d7007",
      "attempts":1,
      "totalRetryDelay":0
   },
   "__type":"NotAuthorizedException"
}
``` 

### Expected Behavior

We would expect to receive new AWS credentials for that refresh token.

### Additional Information/Context

We already chatted with AWS premium support, which was unable to help us (at least for now).

Especially the fact that we can use the same refresh token, that causes the `NotAuthorizedException` to then get a new code via a REST request is what leaves us baffled.

**Comment by RanVaknin** [comment]
HI @flodaniel ,

Thanks for opening this issue. 

The error that you are seeing is coming from the server, since the request makes it to the server, there should be some logs associated with that request ID you have there. The technical account manager that is working with you needs to go to the Cognito service team, provide the requestID and investigate the request logs that are failing.

To make it clear, Im not saying that the issue is coming from the service, it might be caused by some client related issue, the problem is - the SDK is a client and lives on your machine, so we on the SDK team do not have visibility to your usage or logs.

A few suggestions for self debug:
1. add a custom middleware step that logs the request:

```js
client.middlewareStack.add(next => args => {
    console.log('before sign: ' , args.request);
    return next(args);
}, {step: 'build'})
```

2. add retryer logic to retry on that specific error:

```js
const RETRY_ATTEMPTS = 3;
const retryOptions = {
  retryDecider: (err) => {
    if (err && err.name === 'NotAuthorizedException'
      && err.$metadata?.httpStatusCode === 400) {
        console.log("Retrying")
      return true
    }
    return defaultRetryDecider(err)
  }
}
const retryStrategy = new StandardRetryStrategy(async () => RETRY_ATTEMPTS, retryOptions)

const cognitoClient = new CognitoIdentityProviderClient({
    retryStrategy: retryStrategy,
    maxAttempts: RETRY_ATTEMPTS
})
```

Let me know if this helps.
Thanks,
Ran~

**Comment by flodaniel** [comment]
Hi @RanVaknin,
thanks for the fast reply!
I will implement both suggestions and we will follow up with support again! Thanks for your help already.

I will report back, once we see any (or no) changes.

**Comment by RanVaknin** [comment]
Sounds good. 
Thank you.
Ran~
