### ISSUE TITLE
Still getting migration error after updation

### ISSUE THREAD

**Issue by joravkumar** [aws/aws-sdk-js-v3#4487]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The project is using the older aws-sdk which gives the error of migration and not working. After updating the packages and migrating the code. The error is still there even though the old package was not even used and removed the package-lock and package.json

Tried deleting node_modules and reinstalling the packages but not working.

### SDK version number

@aws-sdk/client-s3@^3.282.0, @aws-sdk/lib-storage@^3.282.0, @aws-sdk/s3-request-presigner@^3.282.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.12.1

### Reproduction Steps

Update the packages which use the old **aws-sdk** package to the new SDK.

### Observed Behavior

![Screenshot 2023-03-02 at 1 03 42 PM](https://user-images.githubusercontent.com/42232691/222362621-86b86f58-f78a-4dd5-a44f-20546c5cf84f.png)

### Expected Behavior

The migration error should not be shown after updating.

**Comment by RanVaknin** [comment]
Hi @joravkumar,

>Tried deleting node_modules and reinstalling the packages but not working.

In addition to deleting node_modules you can try deleting `package.json` and `package-lock.json` and reinstall only the v3 dependencies. 

You probably have still have some v2 related dependencies. You can run `npm list -a` to get a full tree of your dependencies and then remove the older ones explicitly with npm uninstall <dependency> 
If you are not sure you can paste the contents of `npm list-a` here and we can further investigate it.

Thanks,
Ran~
