### ISSUE TITLE
Typescript compilation fails for HttpRequest using SignatureV4 and NodeHttpHandler.

### ISSUE THREAD

**Issue by samurous** [aws/aws-sdk-js-v3#4490]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When trying to use the HttpRequest Object from SignatureV4.sign in NodeHttpHandler, the types do not match.

### SDK version number

"@aws-sdk/credential-provider-node": "^3.282.0",     "@aws-sdk/node-http-handler": "^3.282.0",     "@aws-sdk/protocol-http": "^3.282.0",     "@aws-sdk/signature-v4": "^3.282.0",

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node v18.14.2

### Reproduction Steps

Run
```bash
npm i @aws-sdk/credential-provider-node@3.282.0 @aws-sdk/node-http-handler@3.282.0 @aws-sdk/protocol-http@3.282.0 @aws-sdk/signature-v4@3.282.0
```

Try to compile
```typescript
import { SignatureV4 } from "@aws-sdk/signature-v4";
import { NodeHttpHandler } from "@aws-sdk/node-http-handler";
import { Sha256 } from "@aws-crypto/sha256-js";
import { HttpRequest } from "@aws-sdk/protocol-http";
import { defaultProvider as defaultCredentialProvider } from "@aws-sdk/credential-provider-node";

const signer = new SignatureV4({
  service: "execute-api",
  region: "eu-central-1",
  credentials: defaultCredentialProvider(),
  sha256: Sha256,
});

export const handler = async (url: string) => {
  const apiUrl = new URL(url);
  const request = new HttpRequest({
    hostname: apiUrl.hostname.toString(),
    path: apiUrl.pathname,
    method: "GET",
    headers: {
      "Content-Type": "application/json",
      host: apiUrl.hostname.toString(),
    },
  });
  const signedRequest = await signer.sign(request);
  const client = new NodeHttpHandler();
  const { response } = await client.handle(signedRequest);
};
```

### Observed Behavior

Unable to compile TypeScript

```
Argument of type 'import("/root/repos/integration/gutenberg/node_modules/@aws-sdk/types/dist-types/http").HttpRequest' is not assignable to parameter of type 'import("/root/repos/integration/gutenberg/node_modules/@aws-sdk/protocol-http/dist-types/httpRequest").HttpRequest'.

Property 'clone' is missing in type 'import("/root/repos/integration/gutenberg/node_modules/@aws-sdk/types/dist-types/http").HttpRequest' but required in type 'import("/root/repos/integration/gutenberg/node_modules/@aws-sdk/protocol-http/dist-types/httpRequest").HttpRequest'.
```

### Expected Behavior

Compiles without errors.

**Comment by kuhe** [comment]
notes for fix: `NodeHttpClient::handle` is asking for the class `HttpRequest` which has a clone method. Other signatures are asking for the `HttpRequest` interface, which does not have the method.
