### ISSUE TITLE
Missing dependency in @aws-sdk/client-secrets-manager

### ISSUE THREAD

**Issue by olvresc** [aws/aws-sdk-js-v3#4494]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

My lambda has a dependency which is a private repository that uses  @aws-sdk/client-secrets-manager

Lambda is written in typescript and deployed via Serverless Framework

### SDK version number

 @aws-sdk/client-secrets-manager@3.54.0 / @aws-sdk/client-secrets-manager@latest

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.x

### Reproduction Steps

Attach AGW on Lambda

secrets-manager.ts (dependency of my main lambda function)

```
import { SecretsManagerClient, GetSecretValueCommand } from '@aws-sdk/client-secrets-manager';

export default class SecretsManager {
  private readonly secretsManagerClient: SecretsManagerClient;

  constructor() {
    const awsConfig = {
      region: process.env.AWS_DEFAULT_REGION,
    };
    this.secretsManagerClient = new SecretsManagerClient(awsConfig);
  }

  async getSecret(name: string) {
    const response = await this.secretsManagerClient.send(new GetSecretValueCommand({ SecretId: name }));
    return response.SecretString;
}
```

### Observed Behavior

Error occured when calling the lambda throught AGW

````
 "Runtime.ImportModuleError: Error: Cannot find module 'uuid'",
        "Require stack:",
        "- /var/task/node_modules/@aws-sdk/client-secrets-manager/dist-cjs/protocols/Aws_json1_1.js",
        "- /var/task/node_modules/@aws-sdk/client-secrets-manager/dist-cjs/commands/CancelRotateSecretCommand.js",
        "- /var/task/node_modules/@aws-sdk/client-secrets-manager/dist-cjs/SecretsManager.js",
        "- /var/task/node_modules/@aws-sdk/client-secrets-manager/dist-cjs/index.js",
````

### Expected Behavior

N/A

**Comment by RanVaknin** [comment]
Hi @olvresc ,

Can you provide more in-depth reproduction steps? Actual code used. Does this appear after uploading assets to lambda?

Thanks,
Ran

**Comment by olvresc** [comment]
> Hi @olvresc ,
> 
> Can you provide more in-depth reproduction steps? Actual code used. Does this appear after uploading assets to lambda?
> 
> Thanks, Ran

@RanVaknin 

Thanks for the response! I've updated the description.

**Comment by Mrinalaot** [comment]
Thanks @olvresc for raising this issue.

Facing the same issue after taking latest build 😢 
**dist-cjs** folder missing in **client-secrets-manager** & **client-sqs**

`× Unhandled exception in handler 'xyz-api'.
× Runtime.ImportModuleError: Error: Cannot find module 'D:\Users\xyz\node_modules\@aws-sdk\client-secrets-manager\dist-cjs\index.js'. Please verify that the package.json has a valid "main" entry`

Waiting for resolution...

Regards,
Mrinal

**Comment by koshic** [comment]
@Mrinalaot files are present in 3.288.0, 'main' field is also correct

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/20106607/224387705-4695d2a3-3465-419d-939f-95da71307d29.png">

```shell
node -p 'require.resolve("@aws-sdk/client-secrets-manager").split("node_modules")[1]'
node -p 'fs.readFileSync(require.resolve("@aws-sdk/client-secrets-manager"), "utf8")'
```

**Comment by Mrinalaot** [comment]
@koshic actually this issue I am facing in windows, in my personal Mac it's working as expected and files are also present.

**Comment by RanVaknin** [comment]
Hi @koshic ,

The code you added is a typescript code and cannot be run from a lambda context.
Are you running the transpiled JS code on lambda? Based on the error it doesn't look like it.

I think the issue is with lambda Node 16. JS SDK v3 isnt included in lambda on Node16.

Using lambda node v18, I have run the following and it works as expected:

```js
import { SecretsManagerClient, GetSecretValueCommand } from '@aws-sdk/client-secrets-manager';

const client = new SecretsManagerClient({region: "us-east-1"})

export const handler = async(event) => {
    try {
        const res = await client.send(new GetSecretValueCommand({ 
            SecretId: "my-secret"
        }));
        console.log(res.ARN)
    } catch (error) {
        console.log(error)
    }
};
```

@Mrinalaot , your issue seems unrelated, you are also using a much older version. 
I suggest you update to the latest version and if the issue persists please open a separate issue on github and fill the intake form in its entirety. 

Thanks,
Ran~
