### ISSUE TITLE
PITR configuration is not supported in DynamoDB CreateTableCommand docs

### ISSUE THREAD

**Issue by allanchua101** [aws/aws-sdk-js-v3#4499]
### Describe the issue

It seems that Point in time recovery (PITR) feature is not documented on the DynamoDB Client CreateTableCommand or 
 CreateTableCommandInput docs.

### Links

[DynamoDB Client - CreateTableCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/classes/createtablecommand.html)
[DynamoDB Client - CreateTableCommandInput](
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/interfaces/createtablecommandinput.html)

**Comment by RanVaknin** [comment]
Hi @allanchua101 ,

To enable PITR you need to use the appropriate command [`RestoreTableToPointInTimeCommand`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/classes/restoretabletopointintimecommand.html). It is unrelated to the create table command.

Thanks,
Ran~

**Comment by allanchua101** [comment]
Thanks @RanVaknin!

**Comment by allanchua101** [comment]
@RanVaknin, This command you've shared is used for performing a restore operation. What I'm hoping to get hold of is the capability to create a DynamoDB table with PITR turned-on. It would be similar with how PITR works in the documentation of CloudFormation. 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dynamodb-table-pointintimerecoveryspecification.html
