### ISSUE TITLE
Resurfaced: DynamoDBDocument can't unmarshall null

### ISSUE THREAD

**Issue by adclark1** [aws/aws-sdk-js-v3#4504]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

If I'm not mistaken, it appears that the latest version of @aws-sdk/middleware-logger (released today) has caused the bug described in the following previously closed issues to resurface:

https://github.com/aws/aws-sdk-js-v3/issues/3846
https://github.com/aws/aws-sdk-js-v3/issues/4222

It's causing this error again when fetching items with null attributes using @aws-sdk/lib-dynamodb:

TypeError: Cannot read properties of null (reading 'S')

### SDK version number

@aws-sdk/middleware-logger@3.287.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Lambda nodejs16.x

### Reproduction Steps
```js
const { DynamoDBClient } = require('@aws-sdk/client-dynamodb');
const { DynamoDBDocumentClient, GetCommand } = require('@aws-sdk/lib-dynamodb');

const ddbClient = new DynamoDBClient();
const ddbDocClient = DynamoDBDocumentClient.from(ddbClient);

const response = await ddbDocClient.send(new GetCommand({
    TableName: 'table',
    Key: {
      pk: 'pk',
      sk: 'sk',
    },
  }));
```
### Observed Behavior
```console
TypeError: Cannot read properties of null (reading 'S')

{
    "errorType": "TypeError",
    "errorMessage": "Cannot read properties of null (reading 'S')",
    "stack": [
        "TypeError: Cannot read properties of null (reading 'S')",
        "    at AttributeValueFilterSensitiveLog (/var/task/test/node_modules/@aws-sdk/client-dynamodb/dist-cjs/models/models_0.js:1328:13)",
        "    at /var/task/test/node_modules/@aws-sdk/client-dynamodb/dist-cjs/models/models_0.js:1414:128",
        "    at Array.reduce (<anonymous>)",
        "    at GetItemOutputFilterSensitiveLog (/var/task/test/node_modules/@aws-sdk/client-dynamodb/dist-cjs/models/models_0.js:1414:40)",
        "    at /var/task/test/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:17:21",
        "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
        ...
    ]
}

```
### Expected Behavior

Successful retrieval of item with a null attribute without an error being thrown.

### Additional Information/Context

Seeing this with the latest version of @aws-sdk/client-dynamodb and @aws-sdk/lib-dynamodb being used. It appears to be the dependencies they have on @aws-sdk/middleware-logger.

**Comment by yenfryherrerafeliz** [comment]
Hi @adclark1, sorry you are having this issue. I can confirm that this is a bug and I will push to have a fix soon. In the meantime please set logger to undefined when instancing the client, and it will prevent the error from happening. 
Example:
```js
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import { DynamoDBDocumentClient, GetCommand } from '@aws-sdk/lib-dynamodb';

const ddbClient = new DynamoDBClient({
    region: 'us-east-2',
    logger: undefined // HERE
});
const ddbDocClient = DynamoDBDocumentClient.from(ddbClient);

const response = await ddbDocClient.send(new GetCommand({
    TableName: 'test-table',
    Key: {
        id: 'someid'
    },
}));
console.log(response)

```

Thanks!

**Comment by adclark1** [comment]
Good to know. Thanks!

**Comment by oyatrides** [comment]
Hello, I'm having this problem as well on   "@aws-sdk/client-dynamodb": "^3.287.0",  "@aws-sdk/lib-dynamodb": "^3.287.0"
Runtime : nodejs18.x
Logger used:  "@aws-lambda-powertools/logger": "^1.5.1"

Using the logger: undefined workaround in the meantime. Just posting a comment to share my versions numbers.
Thank you for the hard work!

**Comment by kuhe** [comment]
this was fixed in https://github.com/aws/aws-sdk-js-v3/pull/4502, it should release today in approximately 4 hours.

**Comment by kuhe** [comment]
the fix is in https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.288.0

**Comment by adclark1** [comment]
Thank you!

**Comment by oyatrides** [comment]
It works great, thanks !
