### ISSUE TITLE
(@aws-sdk/cloudfront-signer) getSignedCookies does not work

### ISSUE THREAD

**Issue by mvs5465** [aws/aws-sdk-js-v3#4516]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When using the package `@aws-sdk/cloudfront-signer` and calling the `getSignedCookies()` method, no cloudfront policy is returned.

`CloudFront-Signature` and `CloudFront-Key-Pair-Id` are returned correctly. The `CloudFront-Policy` header is undefined and results in a malformed policy error.

### SDK version number

@aws-sdk/cloudfront-signer@3.289.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.14.2

### Reproduction Steps

```js
    import * as cloudfront from "@aws-sdk/cloudfront-signer";

    const signedCookies = cloudfront.getSignedCookies({
      url: 'https://*',
      keyPairId: 'myKeyPairId',
      dateLessThan: new Date(new Date().getTime() + (sessionDuration * 1000)).toISOString(),
      privateKey: 'myKeyPair',
    });
```

### Observed Behavior

`CloudFront-Policy` is undefined

### Expected Behavior

`CloudFront-Policy` should be populated.

### Additional Information/Context

https://stackoverflow.com/questions/75255739/cloudfront-malformed-policy-error-with-aws-cloudfront-signer-v3

**Comment by mvs5465** [comment]
This equivalent code in SDKv2 works fine:

```
    const expTime = new Date(Date.now() + props.sessionDurationMilliseconds);
    const signer = new AWS.CloudFront.Signer(props.keyPairId, props.privateKey);

    const policy = {
      Statement: [
        {
          Resource: 'https://*',
          Condition: {
            DateLessThan: { 'AWS:EpochTime': expTime.getTime() },
          },
        },
      ],
    };

    const signedCookies = signer.getSignedCookie({
      policy: JSON.stringify(policy),
    });
    ```

**Comment by yenfryherrerafeliz** [comment]
Hi @mvs5465, sorry you are facing this issue. Basically, you need to provide the policy as parameter in order to get the 'CloudFront-Policy' field returned. 
A working example, based on your code, would be:
```js
import * as cloudfront from "@aws-sdk/cloudfront-signer";
import fs from "fs";

const keyPairId = 'KEY-PAIR-ID';
const privateKeyContent = await fs.readFileSync('../private_key.pem', {});
const expTime = new Date(Date.now() + 3600);
const policy = {
    Statement: [
        {
            Resource: 'https://*',
            Condition: {
                DateLessThan: { 'AWS:EpochTime': expTime.getTime() },
            },
        },
    ],
};
const cookies = cloudfront.getSignedCookies({
    privateKey: privateKeyContent,
    keyPairId: keyPairId,
    policy: JSON.stringify(policy)
})

```

Thanks!
