### ISSUE TITLE
@aws-sdk/client-sfn: field.name.toLowerCase is not a function

### ISSUE THREAD

**Issue by timoly** [aws/aws-sdk-js-v3#4524]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When using @aws-sdk/client-sfn ListExecutionsCommand throws

### SDK version number

@aws-sdk/client-sfn@3.290.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

18.15.0

### Reproduction Steps

```js
const params: ListExecutionsCommandInput = {
    stateMachineArn: '{stateMachineArn}' ,
    statusFilter: 'RUNNING',
  }
const command = new ListExecutionsCommand(params)
const res = await sfnClient.send(command)
```

### Observed Behavior

```console
TypeError: field.name.toLowerCase is not a function
    at Fields.setField (/data/{project}/node_modules/@aws-sdk/protocol-http/dist-cjs/Fields.js:12:33)
    at Object.set (/data/{project}/node_modules/@aws-sdk/protocol-http/dist-cjs/headersProxy.js:15:20)
    at wrappedHeaderMw (/data/{project}/node_modules/@newrelic/aws-sdk/lib/v3/smithy-client.js:56:43)
```

### Expected Behavior

command doesn't throw

**Comment by ahmednaser94** [comment]
I confirm this bug, solved by returning to an older version
<img width="697" alt="image" src="https://user-images.githubusercontent.com/39867467/224969939-7b380cf0-c881-4814-84eb-5ce5086e5a0e.png">

**Comment by GedByrneSpeedy** [comment]
We also had the same issue when using 

`"@aws-sdk/client-sqs": "^3.26.0",`

we got it working by reverted to using 

`"@aws-sdk/client-sqs": "3.26.0",`

**Comment by bliu13** [comment]
I've also ran into this problem on `"@aws-sdk/client-secrets-manager": "3.290.0"`. Downgrading to `"3.289.0"` was fine.

This was the error, and it's not related to New Relic if that is relevant.
```
TypeError: field.name.toLowerCase is not a function
    at Fields.setField (/var/task/node_modules/@aws-sdk/protocol-http/dist-cjs/Fields.js:12:33)
    at Object.set (/var/task/node_modules/@aws-sdk/protocol-http/dist-cjs/headersProxy.js:15:20)
    at wrappedHeaderMw (/var/task/node_modules/@newrelic/aws-sdk/lib/v3/smithy-client.js:56:43)
    at /var/task/node_modules/@aws-sdk/middleware-serde/dist-cjs/serializerMiddleware.js:13:12
    at async /var/task/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
    ...
```

**Comment by kuhe** [comment]
We believe this is due to a recent update our code not handling the `Symbol` object key set on the header object, done by NewRelic instrumentation. 

We do not generally expect a Symbol to be set on a data object, and it was not an accepted type in the `TypeScript` interface, but we still plan to investigate and release a fix if it is possible to continue to support compatibility with this existing use case.

**Comment by offloda** [comment]
I've also ran into this problem on `"@aws-sdk/client-dynamodb": "3.290.0"`

`TypeError: field.name.toLowerCase is not a function
    at Fields.setField (/var/task/build/node_modules/@aws-sdk/protocol-http/dist-cjs/Fields.js:12:33)`

**Comment by k2xl** [comment]
Seeing this with SES as well. Anyone know which version to revert for that one?

**Comment by danyalsandeelo** [comment]
Why did we get this with the fixed versions? It makes sense with ^ being used but why with fixed version?

**Comment by k2xl** [comment]
Reverting sqs to .289 fixed for me

**Comment by danyalsandeelo** [comment]
I feel like I have started getting this error after updating it to **3.292.0**. @trivikr 
 

**SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.**

**Comment by trivikr** [comment]
> SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.

Please create a new [bug report](https://github.com/aws/aws-sdk-js-v3/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug-report.yml&title=TITLE+FOR+BUG+REPORT), and our Support Engineer will look into it.

**Comment by ahmednaser94** [comment]
> I feel like I have started getting this error after updating it to **3.292.0**. @trivikr
> 
> **SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.**

@danyalsandeelo 
Here too with me and it is a production bug now on AWS, but works fine on my machine 

![image](https://user-images.githubusercontent.com/39867467/225800508-629fd193-ff4e-410c-a677-45f353ba8b80.png)

**Comment by GedByrneSpeedy** [comment]
We too are seeing the same Signature issue when deployed to an EB instance in conjunction with NewRelic.  Running locally, it works fine.  As a workaround, i've just downgraded both AWS SDK and NewRelic to known to be working previous versions :

"@aws-sdk/client-sesv2": "3.26.0",
"newrelic": "9.7.5",
