### ISSUE TITLE
What happened to the docs? It's not loading...

### ISSUE THREAD

**Issue by jove0610** [aws/aws-sdk-js-v3#4541]
### Describe the issue

Some of the docs are not working..

Go to https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/index.html

On the right side under clients try clicking the:
@aws-sdk/cognito-identity
@aws-sdk/cognito-identity-provider

it doesn't work:

![image](https://user-images.githubusercontent.com/39666463/225822997-3e75e6c4-4a77-49bf-9bae-a2a38f460945.png)

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-cognito-identity
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-cognito-identity-provider

**Comment by RanVaknin** [comment]
Hi @jove0610,
We are actively updating our docs, it is fixed now.

Sorry for the inconvenience. 

Thanks,
Ran~

**Comment by RanVaknin** [comment]
Hi @jove0610 ,

Thanks for letting us know. We are working on a fix that will go live any minute. 
You can refer to the v2 docs for now, or we will be happy to help you here if you need any info.

Thanks,
Ran~
