### ISSUE TITLE
[@aws-sdk/client-iot-data-plane] ERR_INVALID_URL after trying to publish message to ATS endpoint

### ISSUE THREAD

**Issue by Rinoir** [aws/aws-sdk-js-v3#4542]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When trying to publish MQTT message to the ATS endpoint, using `PublishCommand` from `@aws-sdk/client-iot-data-plane` package, I'm getting an error `ERR_INVALID_URL`

It was working before migrating to the aws sdk v3

URL is the one returned by command `aws iot describe-endpoint --endpoint-type iot:Data-ATS`

Code is deployed to the Lambda function

### SDK version number

@aws-sdk/client-iot-data-plane@3.292.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.x

### Reproduction Steps

```
import {
  IoTDataPlaneClient,
  PublishCommand,
} from '@aws-sdk/client-iot-data-plane';

const deviceChannel = new IoTDataPlaneClient({
  endpoint: IOT_ENDPOINT,
});

await deviceChannel.send(
  new PublishCommand({
    topic: receiver,
    payload: Buffer.from(JSON.stringify(payload)),
    qos: 0,
  }),
};
```

### Observed Behavior

Error occurs while function's execution

```
{ "input": "1234asdf-ats.iot.us-west-2.amazonaws.com", "code": "ERR_INVALID_URL" }
```

### Expected Behavior

Executes PublishCommand without an error and sends MQTT message to the topic

**Comment by keslerm** [comment]
Hit this same issue, prefixing the endpoint with `https://` fixes it.

I don't know if this is expected or not

**Comment by yenfryherrerafeliz** [comment]
Hi @Rinoir, sorry about your issues. What @keslerm says is correct, basically, the v2 sdk adds the missing pieces when you provide an incomplete url as endpoint, but v3 does not. In this case, you need to preffix the provided endpoint with the right protocol.
Example:
```js
import {
  IoTDataPlaneClient,
  PublishCommand,
} from '@aws-sdk/client-iot-data-plane';

const deviceChannel = new IoTDataPlaneClient({
  endpoint: 'https://' + IOT_ENDPOINT,
});

await deviceChannel.send(
  new PublishCommand({
    topic: receiver,
    payload: Buffer.from(JSON.stringify(payload)),
    qos: 0,
  }),
};
```

Thanks!

**Comment by Rinoir** [comment]
Thank you @keslerm @yenfryherrerafeliz. It did resolve the issue I was having.
Would be nice to have this behaviour reflected in the docs, since now it's a little different from v2 and docs might safe some time for other people doing similar migrations.
