### ISSUE TITLE
aws-sdk's AbortSignal can't be given to Response

### ISSUE THREAD

**Issue by koSakano** [aws/aws-sdk-js-v3#4582]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The `abortController.signal` passed to `client.send` is internally passed to `Respnose`, but an error occurred in that area.
```
const abortController = new AbortController();
const client = new S3Client(clientParams);

const requestPromise = client.send(new CreateBucketCommand(commandParams), {
  abortSignal: abortController.signal,
});
```

### SDK version number

@aws-sdk/ababort-controller@3.296.0 @aws-sdk/client-s3@3.296.0

### Which JavaScript Runtime is this issue in?

Browser

### Details of the browser/Node.js/ReactNative version

Chrome: 111.0.5563.110

### Reproduction Steps

```ts
import { AbortController } from '@aws-sdk/abort-controller';

const controller = new AbortController();
// Type 'AbortSignal' is missing the following properties from type 'AbortSignal': reason, throwIfAborted, addEventListener,  removeEventListener, dispatchEvent
new Response(url, { signal: controller.signal });
```
https://github.com/aws/aws-sdk-js-v3/blob/9152e210c6ec29f34bb070eaf2874039022e6ab7/packages/fetch-http-handler/src/fetch-http-handler.ts#L75

### Observed Behavior

TypeError: Failed to construct 'Request': Failed to read the 'signal' property from 'RequestInit': Failed to convert value to 'AbortSignal'.

### Expected Behavior

Works like a standard AbortController.

**Comment by RanVaknin** [comment]
Hi @koSakano , 

Can confirm this is only happening after bundling for web.

**Comment by koSakano** [comment]
@RanVaknin 
Yes, I can confirm that it probably only happens after bundling for the web.
This did not happen with Node18.

**Comment by kuhe** [comment]
For browsers, don't bundle the AbortController implementation from the `@aws-sdk/abort-controller` package. 

Just use the browser's native AbortController, and it should be fine.

**Comment by koSakano** [comment]
@kuhe 
The browser's native AbortController is not available because it has a different type than the aws-sdk's AbortController.
```ts
// The browser's native AbortController
const abortController = new AbortController();
const client = new S3Client(clientParams);

const requestPromise = client.send(new CreateBucketCommand(commandParams), {
  // error occurred
  abortSignal: abortController.signal,
});
 ```
For example, in this case you will get the following error.
```
No overload matches this call.
  Overload 1 of 3, '(command: Command<ServiceInputTypes, PutObjectCommandInput, ServiceOutputTypes, PutObjectCommandOutput, SmithyResolvedConfiguration<...>>, options?: HttpHandlerOptions | undefined): Promise<...>', gave the following error.
    Type 'AbortSignal' is not assignable to type 'import(".../node_modules/@aws-sdk/types/dist-types/abort").AbortSignal'.
  Overload 2 of 3, '(command: Command<ServiceInputTypes, PutObjectCommandInput, ServiceOutputTypes, PutObjectCommandOutput, SmithyResolvedConfiguration<...>>, cb: (err: any, data?: PutObjectCommandOutput | undefined) => void): void', gave the following error.
    Argument of type '{ abortSignal: AbortSignal; }' is not assignable to parameter of type '(err: any, data?: PutObjectCommandOutput | undefined) => void'.
      Object literal may only specify known properties, and 'abortSignal' does not exist in type '(err: any, data?: PutObjectCommandOutput | undefined) => void'.
```

**Comment by kuhe** [comment]
override the type error with `abortController.signal as any`, until a fix is made.

**Comment by kuhe** [comment]
in https://github.com/aws/aws-sdk-js-v3/pull/4591 I've loosened the type requirement such that this should no longer be a compilation error in future versions

**Comment by koSakano** [comment]
@kuhe 
I've confirmed that the error no longer occurs in v.3.303.0. Thanks for the fix.
