### ISSUE TITLE
S3Client: unable to upload full ReadableStream to S3

### ISSUE THREAD

**Issue by BDeus** [aws/aws-sdk-js-v3#4595]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Hi,
i searched for any kind of information, but i can't find a solution and it seems a bug that is to big to be one.
I'm currently unable to push a ReadableStream with this kind of implementation
```
    const s3 = new S3Client(awsConfig);
    await s3.send(new PutObjectCommand({
        Bucket: bucket,
        Key: key,
        Body:  fs.createReadStream(srcFilePath),
    }));
```
It randomly loses the end of files like if the stream is not entirely read.

Does anyone have this kind of issue or solution to it?
(for information i had not this kind of issue with sdk v2)

### SDK version number

@aws-sdk/client-s3: 3.279.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.13.0

### Reproduction Steps

Generate a file and stream it to S3Client
```
    const s3 = new S3Client();
    await s3.send(new PutObjectCommand({
        Bucket: bucket,
        Key: key,
        Body:  fs.createReadStream(srcFilePath),
    }));
```

### Observed Behavior

Get the S3 object and the file miss the end of file uploaded.

### Expected Behavior

No missing data in file that is uploaded

**Comment by RanVaknin** [comment]
Hi @BDeus ,

It would be helpful to know what kind of error youre running into? A try/catch block would be helpful to identify errors.

For example:

```
.
└── myfolder/
    ├── hello.txt
    ├── package-lock.json
    ├── package.json
    └── index.js
```

index.js
```js
import { S3Client, PutObjectCommand } from '@aws-sdk/client-s3';
import * as fs from 'fs';

const client = new S3Client({ region: 'us-east-1' });
async function put(){
    try{
        const response = await client.send(new PutObjectCommand({
            Bucket: 'my-bucket',
            Key: 'my-key.txt',
            Body: fs.createReadStream("hello.txt")
        }));
        console.log(response)
    } catch (error) {
        console.log(error);
    }
}
put()
```

output:
```
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'REDACTED',
    extendedRequestId: 'RADACTED,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  ETag: '"REDACTED"',
  ServerSideEncryption: 'AES256',
  VersionId: 'qDoQf7zPLd3dHI_iwW0K1wZIZ.cZf0RM'
}
```
___
Reading:

```js
async function get(){
    try{
        const response = await client.send(new GetObjectCommand({
            Bucket: 'my-bucket',
            Key: 'my-key.txt'
        }))
        const str = await response.Body.transformToString();
        console.log(str);
    } catch (error) {
        console.log(error);
    }
}
get()
```

output:
```
hello world
```

Thanks,
Ran~

**Comment by BDeus** [comment]
Hi,
sorry for the false bug.
I can reproduce my bug and it appears that is related to a readablestream.pipe chain error.
The command `.on('end', () => {resolve())`was called before the output stream as finished.
Not related to aws-sdk, thanks for your time
