### ISSUE TITLE
S3 stops responding with streams to requests

### ISSUE THREAD

**Issue by Eli35A** [aws/aws-sdk-js-v3#4596]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Hey, I migrated from v2 to v3 recently and this bug most likely came with it, I didn’t find the cause and I wonder if it’s anything within the library itself. It works and runs normally at first and after some time I can notice that the requests do arrive to the service but the S3 library doesn’t respond with the stream for some files and some files do work, it doesn’t throw any errors when that happens.

### SDK version number

@aws-sdk/client-s3@3.229.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v14.16.0

### Reproduction Steps

The S3 has region, endpoint and credentials as parameters for the config, the rest are dependent on their default values
```
const getObjectResponse: GetObjectCommandOutput = await S3.getObject({
 Bucket: file.bucket
 Key: file.key
});

return getObjectResponse.Body as SdkStream<Readable>;
```

### Observed Behavior

There are no more logs after the request arrives and the stream is not being returned

### Expected Behavior

To return the stream that was requested

### Additional Information/Context

The memory most likely doesn’t affect this, it happened at random times with low memory usage

**Comment by RanVaknin** [comment]
Hi @Eli35A ,

Can you please elaborate on what this means?
>S3 library doesn’t respond with the stream for some files and some files do work, it doesn’t throw any errors when that happens.

What is the returned error?

Please refer to my response [here](https://github.com/aws/aws-sdk-js-v3/issues/4595#issuecomment-1490825971), and see if it helps.

Thanks,
Ran~

**Comment by Eli35A** [comment]
Hi,
I found some more issues that have a similar problem as mine (It all works normally at first but after a few days of running, more and more requests just disappear without a response/error) and found this potential solution https://github.com/aws/aws-sdk-js-v3/issues/3560#issuecomment-1484140333 

I'm just curious to understand why the default S3Client configuration values were changed between V2 and V3, it sounds as if it could possibly be the cause of the problem, thank you!

**Comment by codinronan** [comment]
> Hi @Eli35A ,
> 
> Can you please elaborate on what this means?
> 
> > S3 library doesn’t respond with the stream for some files and some files do work, it doesn’t throw any errors when that happens.
> 
> What is the returned error?
> 
> Please refer to my response [here](https://github.com/aws/aws-sdk-js-v3/issues/4595#issuecomment-1490825971), and see if it helps.
> 
> Thanks, Ran~

Just adding my own experience here, this is also happening to us and there are no errors, no logs. There's nothing I can hook into, no exceptions thrown, no syscall errors to hook into - absolutely nothing. It's just... gone. This happens on our lambda and on local testing and after the exact same number of test files so I've been able to narrow this down specifically to the client.send(GetObjectCommand) call.

@aws-sdk/client-s3@3.304.0

**Comment by RanVaknin** [comment]
Hi @codinronan , 

Thanks for the follow up and the explanation. Are you able to consistently reproduce this? If so It would be helpful if you can share some sample code that can demonstrate this behavior. 

Thank you,
Ran~

**Comment by rijkvanzanten** [comment]
> This issue has not received a response in 1 week. If you still think there is a problem, please leave a comment to avoid the issue from automatically closing.

Problem still exists 🙋🏻‍♂️ The fact that it isn't getting addressed doesn't mean the problem doesn't exist.

**Comment by Eli35A** [comment]
> Hi @codinronan ,
> 
> Thanks for the follow up and the explanation. Are you able to consistently reproduce this? If so It would be helpful if you can share some sample code that can demonstrate this behavior.
> 
> Thank you, Ran~

Hey, the way I reproduced this bug is by configuring the S3 client with a custom httpsAgent, setting the “maxSockets” property to 1 and purposely hanging up the socket by (for example) canceling the download on the browser from the client-side. 

In this situation, the client-side action hangs up the only socket available and you can’t download anymore with that S3 client.

**Comment by RanVaknin** [comment]
Hi @rijkvanzanten,

A `response-requested` label will be added to any issue that requires a response from customer who reported the issue. In this case I asked for some information on how to reproduce the issue. No one answered within a week so our automation kicked in and notified of closure (extra 4 days if I remember correctly). 

Often times customers ask questions without all the info, and by us probing with clarifying questions, sometimes it helps them figure out the issue on their own. This is what the label and auto-close bot are for. We don't expect customers to go back and close the issue when they figure things out on their end, so this helps close stale issues.

Hi @Eli35A ,

I appreciate the clarifying details. I'll look into this with priority. 

All the best,
Ran~

**Comment by rijkvanzanten** [comment]
@RanVaknin Fair enough! :) I've been burned hard before by auto-closing bots and totally glanced over the label requirement that kicked off the bot. I wrongly assumed it was one of those "x days of inactivity" based triggers that were popular for a while 🙈 Anywho, I believe #3560, #4596, and #3722 to all be symptoms of the same root bug

**Comment by codinronan** [comment]
@RanVaknin I could reliably reproduce it before putting one of the fixes in the linked threads in place, I'll try to grab a minimal version of our previous code and share it here in the next day or two.

**Comment by Eli35A** [comment]
This is still relevant. 👍

**Comment by ethanshry** [comment]
Still facing this issue in `@aws-sdk/client-s3: 3.385.0`. Can confirm https://github.com/aws/aws-sdk-js-v3/issues/3560#issuecomment-1484140333 appears to resolve the issue.

**Comment by RanVaknin** [comment]
Hi everyone on the thread.

A lot of people have commented here on the thread without sharing a complete code example, so I'll be hypothesizing, but based on the description of the problem, its likely that you are all getting the object without consuming the stream. In v2 the object body was provided as a buffer, whereas in v3 it is provided as a stream. When the stream remains open, it will cause the application to hang (or different behavior depending on the environment you are in).

Since this was opened we added more documentation that addresses the change in behavior [here](https://github.com/aws/aws-sdk-js-v3/blob/main/supplemental-docs/CLIENTS.md#request-handler-requesthandler) and [here](https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md#amazon-s3).

Please let me know if this solves your issue.

Thanks,
Ran~
