### ISSUE TITLE
presignedUrl and PUT request: header 'abc' must be included in signature

### ISSUE THREAD

**Issue by marwie** [aws/aws-sdk-js-v3#4601]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Trying to upload a file with presignedURL while providing metadata headers does return error (400)

### SDK version number

"@aws-sdk/client-s3": "^3.301.0",     "@aws-sdk/credential-providers": "^3.301.0",     "@aws-sdk/s3-request-presigner": "^3.301.0",

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

18.15.0

### Reproduction Steps

```js
const command = new PutObjectCommand({
        Bucket: process.env.S3_BUCKET,
        Key: key,
        ContentType: 'application/octet-stream',
        // ServerSideEncryption: "AES256",
        Metadata: {
            "x-amz-meta-test": "bar"
        }
    });
    const url = await getSignedUrl(client, command, {
        expiresIn: 3600,
        signableHeaders: new Set(['x-amz-meta-test']),
    });
    const r = await fetch(url, {
        method: 'PUT',
        headers: {
            'Content-Type': 'application/octet-stream',
            // "x-amz-server-side-encryption": "AES256",
            "x-amz-meta-test": "bar"
        },
        body: 'This is a test kms file!'
    });
    r.text().then((value) => {
        console.log('StatusCode: ', r.status);
        console.log('StatusText: ', r.statusText);
        console.log('Text: ', value);
    });
```

### Observed Behavior

presigned URL:   
``https://s3.us-XXXX.backblazeb2.com/NXXXXXXXXXXXXXXXorts/8dfa499a-981b-53df-bb3f-c3dc096049ab.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=0026eXXXXXXXXXXXX0000005%2F20230331%2FusXXXXXXXX%2Faws4_request&X-Amz-Date=20230331T131125Z&X-Amz-Expires=3600&X-Amz-Signature=466e06ce9XXXXXXXXXX2635fccdcf9fcb&X-Amz-SignedHeaders=host&x-amz-meta-test=bar&x-id=PutObject``

Receiving error

```
StatusCode:  400
StatusText:
Text:  <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Error>
    <Code>InvalidRequest</Code>
    <Message>header 'x-amz-meta-test' must be included in signature</Message>
</Error>
```

### Expected Behavior

File is uploaded and written with `test` key in file meta

### Additional Information/Context

running on B2

**Comment by RanVaknin** [comment]
Hi @marwie ,

try this
```diff
const command = new PutObjectCommand({
        Bucket: process.env.S3_BUCKET,
        Key: key,
        ContentType: 'application/octet-stream',
        // ServerSideEncryption: "AES256",
        Metadata: {
-            "x-amz-meta-test": "bar"
+            "test": "bar"
        }
    });
    const url = await getSignedUrl(client, command, {
        expiresIn: 3600,
        signableHeaders: new Set(['x-amz-meta-test']),
    });
    const r = await fetch(url, {
        method: 'PUT',
        headers: {
            'Content-Type': 'application/octet-stream',
            // "x-amz-server-side-encryption": "AES256",
            "x-amz-meta-test": "bar"
        },
        body: 'This is a test kms file!'
    });
    r.text().then((value) => {
        console.log('StatusCode: ', r.status);
        console.log('StatusText: ', r.statusText);
        console.log('Text: ', value);
    });

```
By default Metadata argument gets an `x-amz-meta-*` prefix, so you are creating an `x-amz-meta-x-amz-meta-test` header. 

Additionally your content type will not be enforced because we drop that header unless a content-length is added as well (notice its not included in your signature)

Thanks,
Ran~

**Comment by marwie** [comment]
Hello @RanVaknin changed the code to the following, unfortunately it didnt change help

```js
const command = new PutObjectCommand({
        Bucket: process.env.S3_BUCKET,
        Key: key,
        ContentType: 'application/octet-stream',
        // ...opts,
        // ServerSideEncryption: "AES256",
        Metadata: {
            "test": "bar"
        },
    });
    const url = await getSignedUrl(client, command, {
        expiresIn: 3600,
        signableHeaders: new Set(['x-amz-meta-test']),
        // requestPresigned: true,
    });
    console.log(url);
    const str = "This is a test file!";
    const buf = Buffer.from(str, 'utf8');
    const len = buf.length;
    const r = await fetch(url, {
        method: 'PUT',
        headers: {
            'Content-Type': 'application/octet-stream',
            'Content-Length': len,
            // 'Content-MD5': md5,
            // "x-amz-server-side-encryption": "AES256",
            "x-amz-meta-test": "bar"
        },
        body: str
    });
```

tried also with `body: buf` 

Receiving

``xml
<Code>InvalidRequest</Code>
    <Message>header 'x-amz-meta-test' must be included in signature</Message>
```

the presigned url looks like this
``https://s3.us-west-002.backblazeb2.com/xxxxxxxxxxxxxxxxxxxx/8dfa4xxxxxxxxxxxxxxxxxxxx096049ab.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=0026ecb0d7b3dcc0000000005%2F20230331%2Fus-west-002%2Fs3%2Faws4_request&X-Amz-Date=20230331T181526Z&X-Amz-Expires=3600&X-Amz-Signature=0f58055ccxxxxxxxxxxxxxxxxxxx567f97398&X-Amz-SignedHeaders=host&x-amz-meta-test=bar&x-id=PutObject``
