### ISSUE TITLE
TrustedAdvisorResourceDetails metadata does not have equal length to TrustedAdvisorCheckDescription metadata in @aws-sdk/client-support

### ISSUE THREAD

**Issue by hayfordar** [aws/aws-sdk-js-v3#4607]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I am leveraging `@aws-sdk/client-support` to gather Trusted Advisor check results periodically for my AWS Account. In short, this entails listing all Trusted Advisor checks, then getting the Trusted Advisor check results for each check ID.

The documentation in both [`TrustedAdvisorResourceDetails`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-support/interfaces/trustedadvisorcheckdescription.html#metadata-1) and [`TrustedAdvisorCheckDescription`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-support/interfaces/trustedadvisorresourcedetail.html#metadata) suggests that the `metadata` for each are ordered lists of the values and corresponding column headers, respectively. Unfortunately, these arrays frequently do not have the same length, and thus I cannot produce an `Object` containing the key-value pairs for a given `flaggedResource`'s metadata. This is especially true when looking at the `cost_optimizing` check category, as there are columns like `Day 1`, `Day 2`, `Day 3`, ... `Day 14`, and occasionally only a few days worth of data will be populated. 

For example a Check that looks like:
```console
{
                "category": "cost_optimizing",
                "description": "Checks the Amazon Elastic Compute Cloud (Amazon EC2) instances that were running at any time during the last 14 days and alerts you if the daily CPU utilization was 10% or less and network I/O was 5 MB or less on 4 or more days. Running instances generate hourly usage charges. Although some scenarios can result in low utilization by design, you can often lower your costs by managing the number and size of your instances.\n<br><br>\nEstimated monthly savings are calculated by using the current usage rate for On-Demand Instances and the estimated number of days the instance might be underutilized. Actual savings will vary if you are using Reserved Instances or Spot Instances, or if the instance is not running for a full day. To get daily utilization data, download the report for this check. \n<br>\n<br>\n<h4 class='headerBodyStyle'>Alert Criteria</h4><br>\nYellow: An instance had 10% or less daily average CPU utilization and 5 MB or less network I/O on at least 4 of the previous 14 days.<br>\n<br>\n<h4 class='headerBodyStyle'>Recommended Action</h4><br>\nConsider stopping or terminating instances that have low utilization, or scale the number of instances by using Auto Scaling. For more information, see <a href=\"http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Stop_Start.html\" target=\"_blank\">Stop and Start Your Instance</a>, <a href=\"http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/terminating-instances.html\" target=\"_blank\">Terminate Your Instance</a>, and <a href=\"http://docs.aws.amazon.com/AutoScaling/latest/DeveloperGuide/WhatIsAutoScaling.html\" target=\"_blank\">What is Auto Scaling?</a><br>\n<br>\n<h4 class='headerBodyStyle'>Additional Resources</h4><br>\n<a href=\"http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-monitoring.html\" target=\"_blank\">Monitoring Amazon EC2</a><br>\n<a href=\"http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AESDG-chapter-instancedata.html\" target=\"_blank\">Instance Metadata and User Data</a><br>\n<a href=\"http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/Welcome.html\" target=\"_blank\">Amazon CloudWatch Developer Guide</a><br>\n<a href=\"http://docs.aws.amazon.com/AutoScaling/latest/DeveloperGuide/WhatIsAutoScaling.html\" target=\"_blank\">Auto Scaling Developer Guide</a>",
                "id": "Qch7DwouX1",
                "metadata": [
                    "Region/AZ",
                    "Instance ID",
                    "Instance Name",
                    "Instance Type",
                    "Estimated Monthly Savings",
                    "Day 1",
                    "Day 2",
                    "Day 3",
                    "Day 4",
                    "Day 5",
                    "Day 6",
                    "Day 7",
                    "Day 8",
                    "Day 9",
                    "Day 10",
                    "Day 11",
                    "Day 12",
                    "Day 13",
                    "Day 14",
                    "14-Day Average CPU Utilization",
                    "14-Day Average Network I/O",
                    "Number of Days Low Utilization"
                ],
                "name": "Low Utilization Amazon EC2 Instances"
}
```

Can have a flagged resource in the corresponding check results that looks like:
```console
{
                "isSuppressed": false,
                "metadata": [
                    "us-east-1a",
                    "i-0000000000",
                    "definitely-an-instance",
                    "c5.xlarge",
                    "$122.40",
                    "1.4%  2.33MB",
                    "0.9%  0.26MB",
                    "0.8%  0.19MB",
                    "0.8%  0.19MB",
                    "0.8%  0.19MB",
                    "0.8%  0.18MB",
                    "0.9%",
                    "0.56MB",
                    "6 days"
                ],
                "region": "us-east-1",
                "resourceId": "abcdefghijklmnop",
                "status": "warning"
}
```

Based on the flagged resource, I can see that we _probably_ have the first five and last three columns, but it's hard to feel confident on the Day 1 ... Day 14 columns. 

### SDK version number

@aws-sdk/client-support@3.267.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.18.1

### Reproduction Steps

Here's a snippet that gets the unique `flaggedResources` whose `metadata` array has a different number of elements than the corresponding `metadata` array of the corresponding check description

```js
import {
	DescribeTrustedAdvisorCheckResultCommand,
	DescribeTrustedAdvisorChecksCommand,
	SupportClient,
} from "@aws-sdk/client-support";

(async () => {
	let mismatched = [];
	const client = new SupportClient({
		credentials: {
			accessKeyId: "",
			secretAccessKey: "",
			sessionToken: "",
		},
	});

	// Get checks
	const { checks } = await client.send(
		new DescribeTrustedAdvisorChecksCommand({
			language: "en",
		})
	);

	const checksInCategory = checks.filter(
		(c) => c.category === "cost_optimizing"
	);

	// For each check
	for (const check of checksInCategory) {
		// Get results
		const { result } = await client.send(
			new DescribeTrustedAdvisorCheckResultCommand({
				checkId: check.id,
			})
		);
		// Filter to those where Check column count !== Resource metadata value count
		const mismatchedInCheck = result?.flaggedResources?.reduce(
			(mismatched, resource) => {
				return resource.metadata.length === check.metadata.length
					? mismatched
					: [
							...mismatched,
							{ ...resource, checkMetadata: check.metadata },
					  ];
			},
			[]
		);
		mismatched = mismatched.concat(mismatchedInCheck);
	}

	console.log(JSON.stringify(mismatched));
})();
```

### Observed Behavior

This produces a couple hundred results in my account similar to those shown in the description of the ticket. Most often it's the case of `Day 1`, `Day 2`, ... `Day 14` columns not having corresponding data every day, but the problem exists elsewhere as well.

### Expected Behavior

I expected that the length of the check description metadata array would match the corresponding `flaggedResources` metadata Array. If this is not always the case, how can one be sure they have mapped the right column to the right value? 

### Possible Solution

I'm guessing `null` or `undefined` values are not possible in that `metadata` array found in each `TrustedAdvisorResourceDetail`; thus gaps occur in the Array of values and we have to guess the column correlation.

**Comment by RanVaknin** [comment]
Hi @cloudyparts , @hayfordar , 

Can you please upgrade to the latest version of the SDK and test again? 

Thanks,
Ran~

**Comment by cloudyparts** [comment]
Confirmed. The latest version of the SDK client now contain `null` values for missing data.

Thank you @RanVaknin

**Comment by RanVaknin** [comment]
You are welcome 😄
