### ISSUE TITLE
@aws-sdk/client-s3 producing error on image upload

### ISSUE THREAD

**Issue by himyuni** [aws/aws-sdk-js-v3#4626]
### Checkboxes for prior research

- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

trying to upload a image to s3. the error it's generating is horrible, i tried to find the solution everywhere, nothing seems working. The generated error saying its UnknownError. how i am suppose to find the problem and fix it where aws is saying it's a unknown error :D.

### SDK version number

@aws-sdk/package-name@3.306.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

14.9.1

### Reproduction Steps
```js
const client = new S3({
    region: process.env.AWS_S3_REGION,
    credentials: {
        ccessKeyId: process.env.AWS_ACCESS_KEY,
        secretAccessKey: process.env.AWS_SECRET_KEY
    }
})

const upload = async (name, file, bucket=process.env.AWS_S3_BUCKET) => {

    const uploader = {
        Bucket: bucket,
        Key: name,
        Body: Buffer.from(file.data)
    }

    const upload = await client.putObject(uploader, (err, data) => {
        console.log('callback')
        console.log(err)
        console.log(data)
    })

    return {
        etag: upload.ETag.replace(/\"/g,""),
        location: upload.Location,
        key: Key,
        bucket: bucket
    }
}
```
### Observed Behavior
```console
400: UnknownError
    at throwDefaultError (/app/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-    handler.js:8:22)
    at deserializeAws_restXmlPutObjectCommandError (/app/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:5782:43)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /app/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /app/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20
    at async /app/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /app/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:58:20
    at async /app/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26 {
        '$fault': 'client',
        '$metadata': {
        httpStatusCode: 400,
        requestId: '6ACVW778TJGP01YP',
        extendedRequestId:    'qv518QMX7msriUZgvRtEvysSdhAMKb2xUWUlEc8aOrkZSBB/Z7kQ2AAXLZU6KsUF4NOzLX01Fs4=',
        cfId: undefined,
        attempts: 1,
        totalRetryDelay: 0
    }
}
```
### Expected Behavior

Should've uploaded the image.

**Comment by yenfryherrerafeliz** [comment]
Hi @himyuni, thanks for opening this issue. I agree that getting UnknownError as error message is not helpful. I will bring this into the team to discuss how the desserialization for this type of errors can be improved. However, something you can do as of right now is to log the response before it is parsed, and there you will the whole message that comes with the response.
Here is what you can do:
```js
// 1 - First create a custom handler 
class MyCustomHandler extends NodeHttpHandler {
    handle(request, {abortSignal}) {
        const promise = super.handle(request, {abortSignal});

        return promise.then((response) => {
            const body = response.response.body;
            console.log((typeof body));
            (async () => {
                console.log(await Promise.resolve(body))
            })();
            return response;
        });
    }
}
// 2 - Then, use the custom handler in the client
const client = new S3({
    region: 'us-east-2',
    requestHandler: new MyCustomHandler()
})
// 3 - 
const upload = async (name, file, bucket=process.env.TEST_BUCKET) => {
    const uploader = {
        Bucket: bucket,
        Key: name,
        Body: Buffer.from(file)
    }
    const upload = await client.putObject(uploader);

    return {
        etag: upload.ETag.replace(/\"/g,""),
        location: '',
        key: name,
        bucket: bucket
    }
}
const file = fs.readFileSync('./image.png', {});
const response = await upload(process.env.TEST_KEY, file)
```

Please let me know if that helps.

Thanks!

**Comment by himyuni** [comment]
actually I fixed the issue. after 2 days of debugging. I found The error, it was in the previous line where I called the upload function. but don't know why aws was producing the error.

Previous Code
        const fileName = `client/avatar/${generateFileName()}.${fileExtension(reqFile.data)}` -> this was the cause of the error
        const avatar = await aws.s3.upload(fileName, reqFile.data)

After Fix
        const fileName = `client/avatar/${generateFileName()}.${fileExtension(reqFile.name)}`
        const avatar = await aws.s3.upload(fileName, reqFile.data)

The `fileExtension` function only take string as a param. this function could've generate the error and stopped the execution. But don't know why it was carrying forward the execution to the upload function.
