### ISSUE TITLE
Presigned URL in S3Client

### ISSUE THREAD

**Issue by OldManMeta** [aws/aws-sdk-js-v3#4634]
### Describe the feature

Apologies if someone has already suggested this - I have been searching.

I'd like to understand if it's possible to configure the S3Client with a presigned URL as the endpoint, and no credentials required.

### Use Case

I'm using your Upload module at the moment for large files, and I would prefer not to have to send that data (proxy it) through my server, but enable a client app to upload directly to the storage using a presigned URL.

### Proposed Solution

Something to the effect of

```
const S3 = new S3Client({    
    region: "auto",
    endpoint: secureURL
});
```

### Other Information

I tried it, but of course get a credentials missing error. Just thought it would be handy as I already generate presigned URLs from my server (so not having the data issues) and would like to use them with the S3Client rather than having to build some jank monster that deals with the file types and issues that come with it. S3Client is fantastic in that respect.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.310.0

### Environment details (OS name and version, etc.)

Win 11 - vscode, publish blobs to S3 storage

**Comment by RanVaknin** [comment]
HI @OldManMeta ,

I'm not sure I understand your use case. After you generate a presigned PUT url, you can just use something like node-fetch to upload the file. You don't need to use the AWS SDK to do that. 

Something like:

```js
const response = await fetch(signedUrl, {
    method: 'PUT',
    body: myBody,
    headers: signedUrl.headers
});
```

Perhaps I'm misunderstanding you?

Thanks,
Ran~

**Comment by OldManMeta** [comment]
@RanVaknin - thanks for the response. Sorry for not being clearer - the use case I have for this is in using your Upload module for large files. The built in management of multipart and progress make it much easier to implement then doing it from scratch.

So I'd like to be able to modify the S3Client with a presigned URL to get the same benefits of large multi-part uploads while specifying the URL, something like this:

```
const S3 = new S3Client({    
    region: "auto",
    endpoint: <PRE_SIGNED_URL>
    requestHandler: new XhrHttpHandler({}), 
});
```

Cheers

**Comment by RanVaknin** [comment]
Hi @OldManMeta ,

Unfortunately what you are asking is not possible. A presigned URL is scoped to a single operation (PutObject, GetObject, etc..), while a multipart upload has 3 operations in its flow: CreateMultipartUpload, Initiate Upload, and complete the upload. 

I assume your code snippet is meant to be pseudocode to demonstrate how you expect the feature to work, however its important to me to explain what endpoint in this case does; The `endpoint` argument that the client takes is meant for specifying custom endpoints, for example if you are running something like LocalStack and want to intercept the client calls and implement your own logic you'll use the `endpoint` argument for that. It's not meant to be an S3 bucket endpoint. for 99% of customers this should be left untouched, the default endpoint resolution logic will take the region and service name, and will form the correct endpoint for the appropriate AWS partition. 

Thanks for taking the time and submitting a feature request, we really appreciate you engaging in the community. We hope to hear back from you in the future.

Thanks,
Ran~
