### ISSUE TITLE
Wrong imported libary name

### ISSUE THREAD

**Issue by tung1998** [aws/aws-sdk-js-v3#4636]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

@aws-sdk/lib-storage/dis-es/chunker.js
`import { Readable } from "stream";`
it must be 
`import { Readable } from "stream-browserify";`

### SDK version number

@aws-sdk/lib-storage@3.310.0

### Which JavaScript Runtime is this issue in?

Browser

### Details of the browser/Node.js/ReactNative version

nuxt 3

### Reproduction Steps

install module, check file @aws-sdk/lib-storage/dis-es/chunker.js

### Observed Behavior

cause error "Right-hand side of 'instanceof' is not an object"  Readable 

### Expected Behavior

rename import module

**Comment by RanVaknin** [comment]
Hi @tung1998 ,

Can you please upload a minimal github repository so we can reproduce this issue? 

Thanks,
Ran~
