### ISSUE TITLE
Modify single CloudFront distribution property without impacting other

### ISSUE THREAD

**Issue by doteric** [aws/aws-sdk-js-v3#4637]
### Describe the feature

Hello 👋 

The problem I've faced recently is that a specific version of `@aws-sdk/client-cloudfront` did not support OACs (Origin Access Control) which caused the `GetDistribution` and later `UpdateDistribution` to not contain the `OriginAccessControlId` value which led to the s3 bucket not being accessible through the CloudFront distribution.
Now a question from my side is, can this be prevented in the future? I'm talking about a situation where a feature is added to CloudFront and the used aws-sdk does not support it and getting the distribution details results in missing data. Currently I'll be hosting the solution via an `AWS Lambda` so I assume periodic updates to aws-sdk happen there, but still the problem can occur at some point.

Just to clarify - I would mostly be interested in the ability to update **origin custom headers** without impacting anything else.

### Use Case

Ability to update just a single value without affecting anything else.

### Proposed Solution

Command to update only the origin custom headers of a specific origin in a CloudFront distribution.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

previously v3.107.0, now v3.157.0 (lambda nodev18)

### Environment details (OS name and version, etc.)

AWS Lambda

**Comment by RanVaknin** [comment]
Hi @doteric ,

Thanks for opening the issue. Im a bit confused from your description on what actually seems to be the problem. 
From what I can see `OriginAccessControlId` was added to the Cloudfront api model 8 months ago.

> I'm talking about a situation where a feature is added to CloudFront and the used aws-sdk does not support it and getting the distribution details results in missing data. Currently I'll be hosting the solution via an AWS Lambda so I assume periodic updates to aws-sdk happen there, but still the problem can occur at some point. 

In order for a new feature that rolled out service side to get reflected in the SDK, you will need to maintain the latest version of it. The SDK is a simple client that facilitates calls to AWS on your behalf. Like any other node dependency, Lambda will not automatically update your SDK for you, you are in charge of maintaining your dependencies and making sure they are up to date when services release new features.

>Command to update only the origin custom headers of a specific origin in a CloudFront distribution.

There is a specific command called [`updateOriginAccessControlCommand`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-cloudfront/classes/updateoriginaccesscontrolcommand.html) exactly for that.

Thanks,
Ran~

**Comment by doteric** [comment]
Hey @RanVaknin 
Thanks for replying 💪 

Answering your questions/concerns:
> From what I can see OriginAccessControlId was added to the Cloudfront api model 8 months ago.
> In order for a new feature that rolled out service side to get reflected in the SDK, you will need to maintain the latest version of it. The SDK is a simple client that facilitates calls to AWS on your behalf. Like any other node dependency, Lambda will not automatically update your SDK for you, you are in charge of maintaining your dependencies and making sure they are up to date when services release new features.
That's exactly what I mentioned, to make sure that the CloudFront distribution gets updated properly the aws-sdk version needs to be kept high enough to support all features, because the `DescribeDistribution` command won't output all the details about the distribution otherwise. In such situation some configuration of a distribution can be set wrongly after using the `DescribeDistribution` and UpdateDistribution` command, and AFAIK that's the only way to update some parts of the CloudFront distribution. Therefore my feature request was the ability to update only particular parts of the CF distribution without impacting anything else. Do you know what I mean or would you want me to give a more detailed example?

> There is a specific command called [updateOriginAccessControlCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-cloudfront/classes/updateoriginaccesscontrolcommand.html) exactly for that.

From what I see this command is responsible for updating the OAC, it does not have anything to do with update the **origin customer headers of a origin on a CloudFront distribution**. Or am I wrong?

Appreciate the help :bow:

**Comment by RanVaknin** [comment]
Hi @doteric,

>That's exactly what I mentioned, to make sure that the CloudFront distribution gets updated properly the aws-sdk version needs to be kept high enough to support all features, because the `DescribeDistribution` command won't output all the details about the distribution otherwise. 

This is correct, but to be exact, what will happen on `DescribeDistribution` is that the raw response will have the most up to date data (new field added to the raw response), the only issue is that the SDK wont know how to serialize that, so when you go to print you serialized response it will miss that added field.

>In such situation some configuration of a distribution can be set wrongly after using the DescribeDistribution and UpdateDistribution command, and AFAIK that's the only way to update some parts of the CloudFront distribution.

If I understood you correctly, you are requesting a new method to update the specific origin custom headers on an origin? Something like `UpdateOriginCustomHeader`?  If that is the case, then its not possible from an SDK's perspective.
The SDK is completely auto-generated from the API model of each AWS service and the SDK team cannot add/remove methods that deviate from the model.

From a service perspective this is possible, but this will likely won't get implemented. I'm not a Cloudfront expert so maybe I'm missing the use case here, but it sounds like a particular need that can be covered by simply updating the SDK to the latest version. 

A problem that sometime is happening is that service team will start returning new information without updating the service model and customers will notice data being returned, but not serialized.
Then we have to request that the new info will be added to the model ([for example](https://github.com/aws/aws-sdk-js-v3/issues/4597#issuecomment-1491866775)). In this case, all the service team needs to do is update the model, and customers will be required to clone the latest version of the SDK to have those changes reflected. However in your case, the model is already updated. 

Thanks,
Ran~

**Comment by doteric** [comment]
Hey again @RanVaknin ,
Thank you for the detailed response 💪 

I was also thinking that for it to make sense it would require work outside of the aws js sdk as to how CloudFront distribution updating via the SDK works. So as of now the only thing that we can do is make sure to check if the used aws-sdk version supports all new CloudFront features. 🤷‍♂️  
If you plan to improve this though in the future then I'd be more than happy and please let me know also.

Just as a side note - we will be using the built-in aws-sdk version in `nodejs18.x` on AWS Lambdas. Do you know by any chance if that is updated often or even updated at all? From the docs I've noticed that they mention about this version changing therefore I assume it is updated from time to time.

**Comment by RanVaknin** [comment]
Hi @doteric ,

No worries, its my pleasure! 🙂

> Do you know by any chance if that is updated often or even updated at all? 

It updates once every 3-6 months. I'm not aware of any strict release schedule so I can't be more specific but this was news to me as well. For my own lambdas, I just maintain the SDK version manually and IMO that should be the case for customers as well.

Sorry we couldn't accept your feature request, but I do appreciate you reaching out and engaging in the community. 
Looking forward to hearing from you in the future.

All the best,
Ran~
