### ISSUE TITLE
InvalidParameterException: User does not have delivery config set to turn on SOFTWARE_TOKEN_MFA

### ISSUE THREAD

**Issue by samaybhavsar** [aws/aws-sdk-js-v3#4645]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I am trying to create a user using AdminCreateUserCommand and the setting the MFA config using AdminSetUserMFAPreferenceCommand

```js
const setUserMFAPreferenceCmd =
                    new AdminSetUserMFAPreferenceCommand({
                        SMSMfaSettings: {
                            Enabled: false,
                            PreferredMfa: false,
                        },
                        // AdminSetUserMFAPreferenceRequest
                        SoftwareTokenMfaSettings: {
                            // SoftwareTokenMfaSettingsType
                            Enabled: true,
                            PreferredMfa: true,
                        },
                        Username: cognitoUserId, // required
                        UserPoolId: USER_POOL_ID, // required
                    });
                const setUserMFAPreferenceCmdOutput = await cognitoClient.send(
                    setUserMFAPreferenceCmd
                );
```

No sure what I am doing wrong here, it gives me the following error:-

InvalidParameterException: User does not have delivery config set to turn on SOFTWARE_TOKEN_MFA

### SDK version number

@aws-sdk/client-cognito-identity-provider 3.306.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.14.2

### Reproduction Steps

Code to create user

```js
const signUpCommand = new AdminCreateUserCommand({
                UserPoolId: USER_POOL_ID,
                Username: cognitoUserId,
                MessageAction: 'SUPPRESS',
                UserAttributes: [
                    { Name: 'email', Value: email },
                    { Name: 'phone_number', Value: userBody.phone },
                    { Name: 'phone_number_verified', Value: 'true' },
                    { Name: 'given_name', Value: userBody.firstName },
                    { Name: 'family_name', Value: userBody.lastName },
                    {
                        Name: 'custom:orgId',
                        Value: userBody.organization,
                    },
                    {
                        Name: 'custom:userId',
                        Value: dbUserId,
                    },
                ],
                DesiredDeliveryMediums: ['EMAIL', 'SMS'],
            });
            logger.info(signUpCommand);
            const signUpCommandOutput = await cognitoClient.send(signUpCommand);
```

Code to update MFA preference

```js
const setUserMFAPreferenceCmd =
                    new AdminSetUserMFAPreferenceCommand({
                        SMSMfaSettings: {
                            Enabled: false,
                            PreferredMfa: false,
                        },
                        // AdminSetUserMFAPreferenceRequest
                        SoftwareTokenMfaSettings: {
                            // SoftwareTokenMfaSettingsType
                            Enabled: true,
                            PreferredMfa: true,
                        },
                        Username: cognitoUserId, // required
                        UserPoolId: USER_POOL_ID, // required
                    });
                const setUserMFAPreferenceCmdOutput = await cognitoClient.send(
                    setUserMFAPreferenceCmd
                );
```

### Observed Behavior

InvalidParameterException: User does not have delivery config set to turn on SOFTWARE_TOKEN_MFA

### Expected Behavior

Should set MFA preference so that when the user logs in for the first time, it asks to setup MFA

**Comment by samaybhavsar** [comment]
Hi Ran,

Thanks for the response. I do have the MFA setup as optional and Authenticator apps is selected as MFA method.

<img width="829" alt="Screen Shot 2023-04-21 at 1 03 52 PM" src="https://user-images.githubusercontent.com/748607/233694131-34cd8cdc-67e2-43d0-955c-6db2a256f06b.png">

I am creating user with API (express app). While creating user, I would want to have an option if I want to enforce MFA or not. If MFA is enforced, whenever the user logs in, he will be asked to setup MFA. The 2nd part is something which I was able to do using the APIs.

I did a lot of search on internet and was also going through cognito and found that I am getting the same error on the interface as well. I believe that this issue is not with this library but with the internal AWS APIs. Would be great if you can guide me on where to raise this issue ?

The screenshot below shows the error which I get on the interface when switching from MFA inactive to MFA active.

<img width="1508" alt="Screen Shot 2023-04-21 at 1 11 55 PM" src="https://user-images.githubusercontent.com/748607/233695723-71613466-e5d9-4d93-ba32-a2015e8186f1.png">

**Comment by RanVaknin** [comment]
Hi @samaybhavsar ,

I'm pretty sure this is the expected behavior and not a bug with AWS. I'm not a Cognito expert, but I can tell you that aside from enabling MFA on your pool, you need to call `AssociateSoftwareTokenCommand` and `VerifySoftwareTokenCommand` with a success status before being able to enable MFA on your user.

This is discussed in the doc I shared in my previous comment, you can also take a look at [this](https://repost.aws/knowledge-center/cognito-user-pool-totp-mfa) blogpost that explains the whole flow. They are using the CLI but the commands are the same using the SDK.

Thanks,
Ran~

**Comment by samaybhavsar** [comment]
Thanks Ran,

I figured this out. From what I understand, we cannot enforce MFA to a user from Cognito. If we need to do this, we would have to setup it up first which can happen after logging in. We cannot force user to setup MFA while logging in for the first time. And if required, this has to be handled outside of Cognito.
