### ISSUE TITLE
Missing Output structure for DescribeClusterCommand from client-kafka

### ISSUE THREAD

**Issue by pfarkya** [aws/aws-sdk-js-v3#4653]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Before the version 3.315.0 of @aws-sdk/client-kafka does returns the object with deep nested value. Now it doess't contain most of the fields from output structure.

### SDK version number

@aws-sdk/client-kafka@3.315.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

16.18.0

### Reproduction Steps

Run the following code snippet with version 3.312.0 and version 3.315.0. Add Credential and ARN value before running it.

```js
const { DescribeClusterCommand, KafkaClient } = require('@aws-sdk/client-kafka')
const cli = new KafkaClient({region: 'us-east-1'})
const command = new DescribeClusterCommand({ClusterArn: '<ARN VALUE>'})
try {
  const response = await cli.send(command)
   console.log()
} catch (error) {
   console.error(error)
}
```

### Observed Behavior

```
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: '<>',
    extendedRequestId: undefined,
    cfId: '<>',
    attempts: 1,
    totalRetryDelay: 0
  },
  ClusterInfo: {
    ClusterArn: '<>',
    ClusterName: '<>',
    CurrentVersion: '<>',
    EnhancedMonitoring: 'DEFAULT',
    NumberOfBrokerNodes: 3,
    State: 'ACTIVE',
    StorageMode: '<>',
    Tags: { },
    ZookeeperConnectString: '<>',
    ZookeeperConnectStringTls: '<>'
  }
}
```

### Expected Behavior

```
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: '<>',
    extendedRequestId: undefined,
    cfId: '<>',
    attempts: 1,
    totalRetryDelay: 0
  },
  ClusterInfo: {
    ClusterArn: '<>',
    BrokerNodeGroupInfo : { 
      ClientSubnets: ['']
     },
     ClientAuthentication: {
        Unauthenticated: {
          Enabled: true
        }
     }
    ClusterName: '<>',
    CurrentVersion: '<>',
    EnhancedMonitoring: 'DEFAULT',
    NumberOfBrokerNodes: 3,
    State: 'ACTIVE',
    StorageMode: '<>',
    Tags: { },
    ZookeeperConnectString: '<>',
    ZookeeperConnectStringTls: '<>'
  }
}
```

### Possible Solution

Might passing wrong value to take function. In this PR https://github.com/aws/aws-sdk-js-v3/pull/4625. Deserialisation might be need to change.

**Comment by RanVaknin** [comment]
Hi @pfarkya ,

Thanks for bringing this issue up and raising the PR.
This issue is with the Smithy-typescript code generator. I have confirmed the reported behavior and we will work on it with priority. 

Thanks!
Ran~

**Comment by kuhe** [comment]
Could you use a previous version such as https://www.npmjs.com/package/@aws-sdk/client-kafka/v/3.312.0 while a fix is being worked on?

**Comment by kuhe** [comment]
A patch was released for this issue in https://www.npmjs.com/package/@aws-sdk/client-kafka/v/3.321.1.

**Comment by pfarkya** [comment]
@kuhe Thanks for quick resolution.

I didn't aware about that this file is been generated by codegen. Thanks for new PR.

Should I need to close it or it does an automated stuff.

**Comment by kuhe** [comment]
You can close this issue if you consider it resolved.
