### ISSUE TITLE
Cost Explorer Client Issue

### ISSUE THREAD

**Issue by raziyehb** [aws/aws-sdk-js-v3#4658]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

We consume the CostExplorer Client to make the api calls - recently we get an error as below:
```

Called GetCostAndUsage.
App.tsx:112 ... got error Error: config.endpointProvider is not set.
```

### SDK version number

aws-sdk/client-cost-explorer@~3.106.0 (3.264.0)

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

TangerinbeBox console / Chrome v110.0.5481.177  / Node v14.17.4 

### Reproduction Steps

- Create a new instance of CostExplorerClient

```js
  this.client = new CostExplorerClient({
            credentials: credentials ,
            region: region,
            logger: console
        });
```

- Make an API call by passing the command to CostExplorerClient

```js
const params = { 
   Granularity: Granularity.MONTHLY, 
   Metrics: [Metric.NET_UNBLENDED_COST], 
   TimePeriod: { Start: '2022-09-01', End: '2022-09-30' }
} 

const getCostAndUsageCommand = new GetCostAndUsageCommand(params); 

const response: GetCostAndUsageCommandOutput = await costExplorerClient.send(getCostAndUsageCommand);

```

### Observed Behavior

```
Called GetCostAndUsage.
App.tsx:112 ... got error Error: config.endpointProvider is not set.
```

### Expected Behavior

Receive the api response (This call was previously working, we suspect the new patch update broken the api call)

**Comment by yenfryherrerafeliz** [comment]
Hi @raziyehb, sorry to hear about your issues. I just tried to reproduce this issue and I was not able to. As you can see below when running the provided code I get successful response:

```js
import {CostExplorerClient, GetCostAndUsageCommand, Granularity, Metric} from "@aws-sdk/client-cost-explorer";

const client = new CostExplorerClient({
    region : process.env.TEST_REGION,
    logger: console
});
const params = {
    Granularity: Granularity.MONTHLY,
    Metrics: [Metric.NET_UNBLENDED_COST],
    TimePeriod: { Start: '2022-09-01', End: '2022-09-30' }
};
const getCostAndUsageCommand = new GetCostAndUsageCommand(params);
const response = await client.send(getCostAndUsageCommand);

console.log(response)
```
Response:

```console
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'req-id',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  DimensionValueAttributes: [],
  ResultsByTime: [
    {
      Estimated: false,
      Groups: [],
      TimePeriod: [Object],
      Total: [Object]
    }
  ]
}

```

Could you please update to the latest version and see if the issue persists?, if so, could you please let me know which region are you providing to the client?

Thanks!

**Comment by raziyehb** [comment]
Hi @yenfryherrerafeliz

I am testing in both IAD and ZHY region. Latest version, you mean **3.321.1**?

**Comment by yenfryherrerafeliz** [comment]
@raziyehb as of today is v3.325.0. I will try my tests again with the regions you have provided.

Thanks!

**Comment by raziyehb** [comment]
@yenfryherrerafeliz have you had a chance to test it in IAD and ZHY?

**Comment by raziyehb** [comment]
We upgrade the version to v3.325.0 it fixed the issue in our Tangerinebox console but broke the client in our non TB console.

**Comment by yenfryherrerafeliz** [comment]
Hi @raziyehb, can you please explain what is TB "Tangerinebox" or non TB console?

Thanks!
