### ISSUE TITLE
Please improve the fonts in the new API documentation

### ISSUE THREAD

**Issue by nathanpeck** [aws/aws-sdk-js-v3#4659]
### Describe the issue

Please fix the fonts throughout the [new developer documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/)

The headers are all using an ugly squished font that looks like it has the aspect ratio messed up. The glyphs are too short, and should be taller: 
![image](https://user-images.githubusercontent.com/3495674/234135470-a2cad505-474e-4e6f-b3a3-c6c387a23ab2.png)

According to the code it is supposed to be Amazon Ember, but the display looks absolutely nothing like the actual typography demo site for Amazon Ember: https://developer.amazon.com/en-US/alexa/branding/echo-guidelines/identity-guidelines/typography

Something is clearly very, very wrong with the styling or the font weight in use.

And please, please use a monospace font for all method and parameter names. These things are code, not text.
![image](https://user-images.githubusercontent.com/3495674/234135614-9164b4f7-6eb1-4724-aab2-58198a66a95b.png)

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/client/ecs/

**Comment by MYoung25** [comment]
The font issue was fixed in today's release, once again, thank you for taking the time to leave us feedback!
