### ISSUE TITLE
Let go of "new" phrasing.

### ISSUE THREAD

**Issue by cpyle0819** [aws/aws-sdk-js-v3#4661]
### Describe the issue

The bulk of the landing page describes how V3 is different from V2. V3 has been around long enough now to stop calling it "new". Dedicate the landing page to V3 features in isolation and relegate differences from V2 to the migration section.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/

**Comment by MYoung25** [comment]
Thanks for taking the time to leave feedback!  The current landing page's language is copied from the [README](https://github.com/aws/aws-sdk-js-v3/blob/main/README.md). 

Closer to when the new docs enter GA, there will be a language update

**Comment by kuhe** [comment]
would accept PR for this
