### ISSUE TITLE
Prefer the old version

### ISSUE THREAD

**Issue by jhylton** [aws/aws-sdk-js-v3#4662]
### Describe the issue

the new version does not take into account command output. Makes it dificult to understand what will be returned without running the command.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/client/ec2/command/DescribeInstancesCommand/

**Comment by MYoung25** [comment]
Hi!  Thanks for taking the time to leave us feedback, we hear you and understand your request to include the response types.

I will look into ways for us to include the return types in the example syntax.  You are [not alone](https://github.com/aws/aws-sdk-js-v3/discussions/4656#discussioncomment-5721222) in wanting this so I'll try to prioritize this

**Comment by kuhe** [comment]
@MYoung25 the output shape could be used to generate a structural type hint similar to the input shape.

**Comment by MYoung25** [comment]
@kuhe That is exactly what I was thinking

**Comment by MYoung25** [comment]
I'm pleased to confirm output shapes are now showing in the Example Syntax!  Please don't hesitate to continue leaving us feedback, and thank you again for taking the time to let us know how we can get better
