### ISSUE TITLE
AWS SDK v3 no retry on connection issue

### ISSUE THREAD

**Issue by wanching0730** [aws/aws-sdk-js-v3#4666]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The connectTimeout attribute in v2 no longer supported in v3, there is no way to set connection timeout value. The default connection timeout is 120s which is too long and it's more than the Lambda timeout that we set. Kindly assist.

### SDK version number

@aws-sdk/client-lambda@3.289.0, @aws-sdk/client-dynamodb@3.128.0, @aws-sdk/client-s3@3.289.0, @aws-sdk/client-secrets-manager@3.289.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node v18.15.0

### Reproduction Steps

```
const requestHandler = new NodeHttpHandler({
  requestTimeout: 1500,
});
const secretManager = new SecretsManagerClient({
  endpoint: SECRETS_MANAGER_VPCE,
  requestHandler,
  maxAttempts: 3,
  region: 'ap-southeast-1'
});

return await secretManager.send(new GetSecretValueCommand({ SecretId: secretName }));
```

### Observed Behavior

<img width="746" alt="timeout" src="https://user-images.githubusercontent.com/23547944/234441428-28c49a50-21f9-4dfa-822b-2bec523aaca4.png">

### Expected Behavior

There should be a way to set connection timeout in v3, which is the replace the connectTimeout in HttpOptions in v2.

**Comment by RanVaknin** [comment]
Hi @wanching0730 ,
We are working on un-deprecating connectionTimeout. Can you please an older version of the SDK in the meantime while we work to re-introduce this config option?

Thank you very much,
Ran~

**Comment by trivikr** [comment]
The fix was pushed in PR https://github.com/aws/aws-sdk-js-v3/pull/4669
It'll be released with v3.322.0 around 1pm Pacific either on Thu 04/27 or Fri 04/28

In the meantime, please use <= v3.295.0 as a workaround.

**Comment by wanching0730** [comment]
Noted on that, thank you very much

**Comment by trivikr** [comment]
The fix was released in https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.321.1
