### ISSUE TITLE
ConnectionTimeout not working as intended in >=v3.296.0

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#4668]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

ConnectionTimeout not working as intended in >=v3.296.0

### SDK version number

@aws-sdk/node-http-handler@3.296.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.20.0

### Reproduction Steps

```js
import { S3 } from "@aws-sdk/client-s3";
import { NodeHttpHandler } from "@aws-sdk/node-http-handler";

const client = new S3({
  requestHandler: new NodeHttpHandler({
    // For repro this value should be between time taken for socket assigned, and time taken by request.
    connectionTimeout: 40,
  }),
});

await client.listBuckets({});
```

### Observed Behavior

With `v3.295.0`, there's no error thrown as connection doesn't timeout.

### Expected Behavior

With `v3.296.0`, the timeout error is thrown as connectionTimeout is considered as requestTimeout.

```console
/Users/trivikr/workspace/test/node_modules/@aws-sdk/node-http-handler/dist-cjs/node-http-handler.js:91
                reject(Object.assign(new Error(`Connection timed out after ${timeout} ms`), { name: "TimeoutError" }));
                                     ^

Error [TimeoutError]: Connection timed out after 40 ms
    at ClientRequest.<anonymous> (/Users/trivikr/workspace/test/node_modules/@aws-sdk/node-http-handler/dist-cjs/node-http-handler.js:91:38)
    at Object.onceWrapper (node:events:627:28)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.emitRequestTimeout (node:_http_client:839:9)
    at Object.onceWrapper (node:events:627:28)
    at TLSSocket.emit (node:events:525:35)
    at TLSSocket.Socket._onTimeout (node:net:550:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  '$metadata': { attempts: 4, totalRetryDelay: 420 }
}
```

### Possible Solution

This happened as `connectionTimeout` was incorrectly deprecated in https://github.com/aws/aws-sdk-js-v3/pull/4508

Possible solution:
* Undeprecate `connectionTimeout`, and re-introduce the functionality.
* Change request timeout error message to `Request timeout out` to not be confused with connectionTimeout

**Comment by RanVaknin** [comment]
related: #4666

**Comment by trivikr** [comment]
Related: https://github.com/aws/aws-sdk-js-v3/issues/4618
