### ISSUE TITLE
Use example for GenerateRandomCommand not corresponding

### ISSUE THREAD

**Issue by gm-mmurillo** [aws/aws-sdk-js-v3#4672]
### Describe the issue

The example showed in GenerateRandomCommand  section is for GenerateDataKey in KMS.

![image](https://user-images.githubusercontent.com/110182402/234916238-c0206f03-042c-4164-8ab9-1629fce7e56a.png)

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/client/kms/command/GenerateRandomCommand/

**Comment by MYoung25** [comment]
Thanks for letting us know!

**Comment by MYoung25** [comment]
I have confirmed the behavior and was able to reproduce locally, in addition, I was able to get a fix deployed in today's release.  If you still observe the bug, please don't hesitate to reach back out.  Once again, thanks for taking the time to let us know!
