### ISSUE TITLE
Formatting error on AdminCreateUserCommand

### ISSUE THREAD

**Issue by igorrocha** [aws/aws-sdk-js-v3#4676]
### Describe the issue

There seems to be a formatting error on the AdminCreateUserCommand page, after the second paragraph. What should be displayed as text is being shown as HTML code instead:
![image](https://user-images.githubusercontent.com/9059660/232877566-4be4ea01-0d4b-4af3-b887-a6543262dc79.png)

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-cognito-identity-provider/classes/admincreateusercommand.html

**Comment by RanVaknin** [comment]
Hi @igorrocha ,

Thanks for letting us know and providing feedback :) We appreciate it. 

@MYoung25 Can you please take a look?

Thanks,
Ran~

**Comment by MYoung25** [comment]
Thanks for bringing this up, this is actually one of the reasons we decided to launch a new docs site https://github.com/aws/aws-sdk-js-v3/discussions/4656.

This is unlikely to be fixed prior to the new docs entering GA
