### ISSUE TITLE
Support synchronous requests

### ISSUE THREAD

**Issue by wyattisimo** [aws/aws-sdk-js-v3#4677]
### I'm creating this issue to request that feature request https://github.com/aws/aws-sdk-js-v3/issues/2949 be reopened.

* https://github.com/aws/aws-sdk-js-v3/issues/2949 was incorrectly closed as a duplicate of https://github.com/aws/aws-sdk-js-v3/issues/2321.
* The fact that it was incorrectly closed as a duplicate is also noted here: https://github.com/aws/aws-sdk-js-v3/issues/2321#issuecomment-1117610713.
* https://github.com/aws/aws-sdk-js-v3/issues/2949 is now locked, so I cannot add a comment to request re-opening it.

### Use Case

See https://github.com/aws/aws-sdk-js-v3/issues/2949

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.306.0

### Environment details (OS name and version, etc.)

Linux

**Comment by aBurmeseDev** [comment]
Hi @wyattisimo - apologies for the long wait.

It would take a lot of time to rewrite everything since all of our code is asynchronous, but I'm sure there are many other ways to implement it your own, so unfortunately, we have decided not to plan this feature.
