### ISSUE TITLE
presigned URL of S3 with endpoint writes to the wrong key

### ISSUE THREAD

**Issue by alonvim** [aws/aws-sdk-js-v3#4687]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Generating a presigned url for an S3 object when the S3 client is initialized with endpoint, the object gets written to the wrong key (including `BUCKET_NAME` as key prefix by mistake).

### SDK version number

@aws-sdk/client-s3@3.321.1,@aws-sdk/s3-request-presigner@3.321.1

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node -v: v16.19.0

### Reproduction Steps

Generate the presigned url for the custom domain
```js
const { S3Client, PutObjectCommand } = require("@aws-sdk/client-s3");
const { getSignedUrl } = require('@aws-sdk/s3-request-presigner');

const bucketName = 'images.my-domain.com';
const objectKey = `spongebob.jpeg`;

// Initialize the S3 client with us-east-1 region and Signature Version 4
const s3 = new S3Client({
    endpoint: `https://${bucketName}/`,
  });

// const expirationTime = 3600; // URL will be valid for one hour (in seconds)

const command = new PutObjectCommand({
    Bucket: bucketName,
    Key: objectKey,
    ContentType: 'application/octet-stream'
});

console.log(getSignedUrl);
getSignedUrl(s3, command, ).then(signature => {
    console.log(signature);
});
```

### Observed Behavior

When initializing the client without custom endpoint the file gets written to key: `spongebob.jpeg`
When initializing the client **with** custom endpoint the filte gets written to key `images.my-domain.com/spongebob.jpeg`

### Expected Behavior

Using presigned url with custom endpoint to upload file writes the file to the specified key without adding a prefix of the `BUCKET_NAME`

### Additional Information/Context

To use the custom endpoint we set a CNAME on our domain to s3 aws domain:

CNAME 
images.my-domain.com
value: `3.{my-region}.amazonaws.com`

**Comment by RanVaknin** [comment]
Hi @alonvim ,

This is because you are using the endpoint config option on your client. This is not an s3 endpoint. 
Please refer to my comment [here](https://github.com/aws/aws-sdk-js-v3/issues/4570#issuecomment-1481730014).

I keep seeing customers making this mistake. Did you read this in some documentation?

Thanks,
Ran~

**Comment by y-golde** [comment]
@RanVaknin Thanks for answering so quickly, like the comment you've mentioned we're also trying to migrate from v2, our code in v2 used to look like this:

```typescript
import { S3 } from 'aws-sdk';

const getTempURL = () => {
  const client = new S3({ endpoint: 'myBucket.mydomain.com', s3BucketEndpoint: true });
  return client.getSignedUrlPromise('getObject', {
    Key: 'myKey',
    Bucket: 'myBucket.mydomain.com',
    Expires: 3600,
  });
};

(async () => {
  console.log(await getTempURL()); // outputs https://mybucket.mydomain.com/myKey?AWSAccessKeyId=[...]
})();
```

after we've migrated to v3 we looked through the docs and didn't find any way to use the `s3BucketEndpoint` option - resulting in urls like: `images.my-domain.com/images.my-domain.com/myKey?[...]` instead.

My question is how can we implement 's3BucketEndpoint' in v3?

**Comment by RanVaknin** [comment]
Hi @y-golde ,

This is interesting, I will make a note of it and try to add this specific section into the migration guide.
In your case to get your endpoint to resolve to what you have there you also have to specify `forcePathStyle: true` in your config options. 

Can you let me know if that works for you?

Thanks,
Ran~

**Comment by y-golde** [comment]
Hi @RanVaknin, Unfortunately It did not work for me :\ using the example @alonvim provided:
```typescript
// Initialize the S3 client with us-east-1 region and Signature Version 4
const s3 = new S3Client({
  endpoint: `https://${bucketName}/`,
  forcePathStyle: true,
});
```
Returns: https://images.my-domain.com/images.my-domain.com/spongebob.jpeg?X-Amz-Algorithm=[...]

Which later uploads the new image to a `images.my-domain.com` folder inside of the `images.my-domain.com` bucket :(
