### ISSUE TITLE
getSignedUrl with Metadata produced invalid URL

### ISSUE THREAD

**Issue by omerlh** [aws/aws-sdk-js-v3#4694]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I am using the package to create a pre-signed url:

```js
const client = new S3Client({ region: 'us-east-1' });

const command = new PutObjectCommand({
  Bucket: 'my-bucket',
  Key: filename,
  ContentType: 'application/octet-stream',
  ServerSideEncryption: 'aws:kms',
  Metadata: { delimiter: '|' },
});

const url = await getSignedUrl(client, command, {
  expiresIn: TTL_SECONDS,
});
```

But when trying to use the pre-signed URL I am getting the following error:

```xml
<Error>
  <Code>AccessDenied</Code>
  <Message>There were headers present in the request which were not signed</Message>
  <HeadersNotSigned>x-amz-meta-delimiter</HeadersNotSigned>
  <RequestId><></RequestId>
  <HostId><></HostId>
</Error>
```

I am passing all the required headers to use the metadata:

```
curl '<pre-signed url>' \
  -X 'PUT' \
  -H 'Accept: */*' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 1013' \
  -H 'Content-Type: application/octet-stream' \
  -H 'x-amz-meta-delimiter: |' \
  -H 'x-amz-server-side-encryption: aws:kms' \
  -T <path to file>
```

Looking at similar issues like #3906 I've tried setting either the `unhoistableHeaders` or `signableHeaders` but the `X-Amz-SignedHeaders` still does not contain the `x-amz-meta-delimiter` header.

What am I missing?

### SDK version number

@aws-sdk/s3-request-presigner@3.325.0, @aws-sdk/client-s3@3.325.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.12.0

### Reproduction Steps

Use the code in the issue above to create the pre-signed URL and try to upload a file to the bucket with metadata

### Observed Behavior

The request failed with 403 forbidden 

### Expected Behavior

File uploaded successfully with metatadata

**Comment by RanVaknin** [comment]
Hi @omerlh ,

I'm not sure why you are running into this issue.

Consider my sample code:

```js
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import { S3Client, PutObjectCommand }  from "@aws-sdk/client-s3";
import fetch from "node-fetch"

const s3Client = new S3Client({
    region: "us-east-1"
});


export const bucketParams = {
    Bucket: `testbucket`,
    Key: `01-object-${Math.ceil(Math.random() * 10 ** 10)}`,   // unique object name for each test
    Body: "hello world",
    Metadata: { delimiter: '|' },
};

export const run = async () => {

    try {
      const command = new PutObjectCommand(bucketParams);
      const signedUrl = await getSignedUrl(s3Client, command, {
        expiresIn: 3600,
      });
      
      console.log(signedUrl)
      const response = await fetch(signedUrl, {method: 'PUT', body: bucketParams.Body, headers: signedUrl.headers});
      console.log(response)

    } catch (err) {
      console.log("Error creating presigned URL", err);
    }
}
run()
```

Generated Presigned URL:

```
https://testbucket-REDACTED.s3.us-east-1.amazonaws.com/01-object-REDACTED?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=REDACTED/20230503/us-east-1/s3/aws4_request&X-Amz-Date=20230503T211105Z&X-Amz-Expires=3600&X-Amz-Signature=REDACTED&X-Amz-SignedHeaders=content-length;host&x-amz-meta-delimiter=|&x-id=PutObject
```

response:

```console
Response {
  size: 0,
  [Symbol(Body internals)]: {
    body: PassThrough {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      [Symbol(kCapture)]: false,
      [Symbol(kCallback)]: null
    },
    stream: PassThrough {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      [Symbol(kCapture)]: false,
      [Symbol(kCallback)]: null
    },
    boundary: null,
    disturbed: false,
    error: null
  },
  [Symbol(Response internals)]: {
    type: 'default',
    url: 'https://testbucket.s3.us-east-1.amazonaws.com/01-object-REDACTED?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=REDACTED%2F20230503%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230503T211105Z&X-Amz-Expires=3600&X-Amz-Signature=REDACTED&X-Amz-SignedHeaders=content-length%3Bhost&x-amz-meta-delimiter=%7C&x-id=PutObject',
    status: 200,
    statusText: 'OK',
    headers: {
      connection: 'close',
      'content-length': '0',
      date: 'Wed, 03 May 2023 21:11:06 GMT',
      etag: '"REDACTED"',
      server: 'AmazonS3',
      'x-amz-id-2': 'REDACTED',
      'x-amz-request-id': 'REDACTED',
      'x-amz-server-side-encryption': 'AES256',
      'x-amz-version-id': 'REDACTED'
    },
    counter: 0,
    highWaterMark: 16384
  }
}
```

S3 console:
![image](https://user-images.githubusercontent.com/50976344/236052068-f3320de8-9a34-4a21-b47c-f844110200da.png)


I hope this helps and achieves what you need. 

Thanks,
Ran~

**Comment by omerlh** [comment]
What is the type of `signedUrl`? When I am testing it the function returns string, which doesn't have `signedUrl.headers`. I assume this is where my error coming from....

**Comment by RanVaknin** [comment]
Hi @omerlh ,

Totally my fault, I have some ready-to-go repro code in Golang I used to reproduce this, and in Go the presigner returns a url object. So in this case you are right, this is a string and signedUrl.headers would be undefined. 

The interesting behavior to me is that the object was uploaded with the metadata even without signing that particular header. I'm not entirely sure what your expected result here, but if it's that the uploaded object will have the metadata header attached to it, you can try removing that explicit header from your cURL command and send the request without using the `unhoistableHeaders` property.

If you absolutely must sign that header, adding that header into a set under signableHeaders and explicitly sending the request with that header did work for me:

```js
const headers = new Set();
headers.add('x-amz-meta-delimiter')

// ... some code ...

const signedUrl = await getSignedUrl(s3Client, command, {
    expiresIn: 3600,
    unhoistableHeaders: headers
})
```

With cURL:

```
curl -v --location --request PUT 'https://testbucket-REDACTED.s3.us-east-1.amazonaws.com/01-object-REDACTED?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=REDACTED/20230504/us-east-1/s3/aws4_request&X-Amz-Date=20230504T233157Z&X-Amz-Expires=3600&X-Amz-Signature=REDACTED&X-Amz-SignedHeaders=content-length;host;x-amz-meta-delimiter&x-id=PutObject' \
--header 'Content-Length: 11' \
--header 'x-amz-meta-delimiter: |' \
--header 'Connection: keep-alive' \
--header 'Content-Type: text/plain' \
--data-raw '"hello world"'
```
output:

```
< HTTP/1.1 200 OK
< x-amz-id-2: REDACTED
< x-amz-request-id: REDACTED
< Date: Thu, 04 May 2023 23:56:25 GMT
< x-amz-version-id: REDACTED.Ft4v.ugNP8.nkA4JczTgdz08
< x-amz-server-side-encryption: AES256
< ETag: "REDACTED"
< Server: AmazonS3
< Content-Length: 0
```

Object is uploaded to s3 bucket with the metadata as expected.

I still have a feeling I might be missing something and that our setup is not entirely the same. Let me know if you need any additional help.

Thanks,
Ran~

**Comment by omerlh** [comment]
Ok so it is working - passing the metadata header to the pre-signer is enough and there is no need to pass it again when uploading the file. I am not sure if this how things *should* work from S3 perspective, but it's good enough for me :)
