### ISSUE TITLE
(short issue description)

### ISSUE THREAD

**Issue by Aterxerxes** [aws/aws-sdk-js-v3#4696]
### Describe the issue

We don't know what data Shape the PutParameterCommand returns. Please provide an example on this page.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/client/ssm/command/PutParameterCommand/

**Comment by RanVaknin** [comment]
Hi, 

We are aware of the issue and actively working on fixing this.

Thanks you for being an active member of our community, we appreciate your feedback!

All the best,
Ran~

**Comment by MYoung25** [comment]
I'm pleased to share that I have confirmed response shapes are now showing in the Example Syntax!  This was fixed in today's release.  Like @RanVaknin said, thank you for taking the time to leave us feedback!

**Comment by Aterxerxes** [comment]
I really appreciate the prompt response and the actions taken. 🙂👍
