### ISSUE TITLE
ExecuteStatementCommand in lib-dynamodb failing with lists

### ISSUE THREAD

**Issue by cpyle0819** [aws/aws-sdk-js-v3#4703]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The `ExecuteStatementCommand` from `lib-dynamodb` is failing when given a list as a parameter.

### SDK version number

@aws-sdk/client-dynamodb: "^3.210.0"

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

18.12.1

### Reproduction Steps

```js
import {
  DynamoDBDocumentClient,
  ExecuteStatementCommand,
} from "@aws-sdk/lib-dynamodb";

const client = new DynamoDBClient({});
const docClient = DynamoDBDocumentClient.from(client);

const command = new ExecuteStatementCommand({
  Statement: `INSERT INTO Coffees value {'varietal':?, 'profile':?}`,
  Parameters: ["arabica", ["chocolate", "floral"]],
});
await docClient.send(command);

```

### Observed Behavior

```console
TypeError: Cannot read properties of undefined (reading '0')
    at AttributeValue.visit (/Users/corepyle/Documents/teams/aws-doc-sdk-examples/javascriptv3/node_modules/@aws-sdk/client-dynamodb/dist-cjs/models/models_0.js:645:40)
```

### Expected Behavior

Expected the parameters array to be able to handle an array parameter.

### Additional Information/Context

Working version with the base client:
```
import { ExecuteStatementCommand, DynamoDBClient } from "@aws-sdk/client-dynamodb";

const client = new DynamoDBClient({});

const command = new ExecuteStatementCommand({
  Statement: `INSERT INTO Coffees value {'varietal':?, 'profile':?}`,
  Parameters: [{ S: "arabica" }, { L: [{ S: "chocolate" }, { S: "floral" }] }],
});
await client.send(command);
```

**Comment by cpyle0819** [comment]
Hey, Ran. lib-dynamodb exports the ExecuteStatementCommand so data attribute types can be avoided. It sounds like you're telling me not to use that command from lib-dynamodb. It's a documented part of the library. Is that wrong?

**Comment by RanVaknin** [comment]
Hi @cpyle0819 , 

I totally missed that part. Partly because we don't have an example for it anywhere! 

I'm able to reproduce the bug with the provided code and confirm that the serialization fails when trying to insert an array of arrays.

Will add to backlog. 
Thanks,
Ran~

**Comment by samuel-bach** [comment]
Same error also gets thrown for objects:
```js
const command = new ExecuteStatementCommand({
  Statement: `INSERT INTO Coffees value {'varietal':?, 'profile':?}`,
  Parameters: ["arabica", { foo: "bar"}],
});
```

**Comment by kitsunde** [comment]
@RanVaknin Could the typescript defs be fixed first since I am assuming this will take some time? `ExecuteStatementCommand ` accepts `NativeAttributeValue` because of: https://github.com/aws/aws-sdk-js-v3/blob/main/packages/util-dynamodb/src/models.ts#L15 but it doesn't seem to actually handle `{foo: 'bar'}` as a value.

What seem to be happening is a parameter:

`{foo: 'bar'}`

becomes

`{ foo: {S: 'bar'} }`

but if you nest it:

`{ inner: {foo: 'bar'} }`

It understands the inner parts just fine:

` { inner: { M: { foo: { S: 'bar' } } } }`

Effectively using the document client with PartiQL becomes not practical.
