### ISSUE TITLE
Poor documentation for inherited or extended interfaces (lib-dynamodb)

### ISSUE THREAD

**Issue by everett1992** [aws/aws-sdk-js-v3#4704]
### Describe the issue

Maybe this problem is unique or exacerbated in lib-dyanmodb but aws-sdk's documentation for types that are unions, extensions, or derived from other types is very poor. 

For example, I'm trying to understand ExecuteStatementCommand so I opened [the page for the command](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/classes/_aws_sdk_lib_dynamodb.ExecuteStatementCommand.html)

* There's no overview or examples
* There's no link to the [api documentation](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_ExecuteStatement.html)
* There's no link to the base client-dynamodb documentation

I'm interested in the commands parameters, and I'm familiar enough with aws-sdk-js-v3 to know that that's the Commands input parameter so I follow the link to [ExecuteStatementCommandInput](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/types/_aws_sdk_lib_dynamodb.ExecuteStatementCommandInput.html) where the entirety of the documentation is

```
ExecuteStatementCommandInput: Omit<__ExecuteStatementCommandInput, "Parameters"> & {
    Parameters?: NativeAttributeValue[];
}
```

None of the parts of the code block are links, there's no explanation of what __ExecuteStatementCommandInput is until I read the code. I figure I should go to client-dyanmodb's documentation, but the search bar only offers results from lib-dynamodb.

I went to the [home page](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/index.html) and looked for `client-dynamodb` in the clients list but couldn't find it. It's listed as [@aws-sdk/dynamodb](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/) for some reason.

 - [ ] Input and Command pages should link to or include the aws api documentation
 - [ ] Types that are inherited, composed, or mapped from other types should be flattened and their members enumerated, or at-least offer links to the source types.
 - [ ] search should be global across all modules (with sections or priority for the current module)
 - [ ] clients should be listed as `dynamodb` or `@aws-sdk/clients-dynamodb`, not `@aws-sdk/dynamodb` 

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/classes/_aws_sdk_lib_dynamodb.ExecuteStatementCommand.html#constructor

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/types/_aws_sdk_lib_dynamodb.ExecuteStatementCommandInput.html

**Comment by MYoung25** [comment]
Hi @everett1992,

Thank you for taking the time to leave us feedback!  In our current documentation, this is not unique to lib-dynamodb.  To solve the root cause, we have [launched a preview](https://github.com/aws/aws-sdk-js-v3/discussions/4656) of updated documentation, and are actively working on including the packages in `lib/*` and `packages/*` in the preview.

We are prioritizing our efforts into solving many of the issues you brought up, and more, in the preview of our new docs.  Again, I appreciate you sharing your thoughts with us, and will use your feedback to prioritize providing high-value documentation.

**Comment by everett1992** [comment]
ohh, I thought I was looking at the preview because there's a header asking for feedback

> New API Documentation - Developer Preview Available
> We are excited to announce the [developer preview](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/) of our new API documentation for AWS SDK for JavaScript v3. Please follow instructions on the landing page to leave us your feedback.

I didn't realize that was other docs that were the preview
