### ISSUE TITLE
Provide a shortcut to focus the search bar

### ISSUE THREAD

**Issue by FlorentCollin** [aws/aws-sdk-js-v3#4706]
### Describe the issue

Assign a shortcut to focus the search bar directly. This would allow to not have to click on the search bar each time.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/

**Comment by RanVaknin** [comment]
Hi @FlorentCollin ,

Thanks for the feedback. I will discuss it with the team and see if we can implement this.

All the best,
Ran~

**Comment by MYoung25** [comment]
Hi @FlorentCollin,

Thanks for taking the time to check out the preview and leave feedback.  I wanted to reach out and get a better understanding of the experience you're proposing.  What keyboard command/shortcut did you have in mind?

**Comment by FlorentCollin** [comment]
Hi @MYoung25, most sites tend to use `command + k` (or `ctrl + k` on linux/windows) or the `/` key.
For example, the following sites use `command + k`:

- [GitHub](https://github.com/)
- [React documentation](https://react.dev/learn)
- Most discussion apps: Slack, Discord, etc.
- Most sites using [DocSearch](https://docsearch.algolia.com/)
