### ISSUE TITLE
ctrl-clicking doesn't open in new tab

### ISSUE THREAD

**Issue by damiensawyer** [aws/aws-sdk-js-v3#4716]
### Describe the issue

On [this](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/client/quicksight/) page (and others similar I assume), it would be good to be able to ctrl-click on links to open them in new tabs. It's not uncommon to have half a dozen or more commands' docs open at once to cross reference etc. 

Currently ctrl-clicking navigates the exisitng page. This is, I believe, non standard browser behaviour. 

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/client/quicksight/

**Comment by MYoung25** [comment]
Hi @damiensawyer,

Thanks for taking the time to check out our new API Reference and leave us feedback!  I've confirmed the behavior, it looks like its related to a performance improvement.

**Comment by RanVaknin** [comment]
Hi @damiensawyer ,

I'm using mac, and clicking on Cmd + click does open a new tab without closing the current. 
Can you please verify that this is still an issue?

Thanks,
Ran~

**Comment by damiensawyer** [comment]
Hi Ran,

Thanks for following up.

I'm on a different machine, but still Windows. It appears to be working
fine now.

Cheers
