### ISSUE TITLE
No information or example on how to create a handler function in TS

### ISSUE THREAD

**Issue by eltonmoreno-catho** [aws/aws-sdk-js-v3#4717]
### Describe the issue

There's no clear example or information about to use the AWS SDK v3 for Lambda function development. The  actual documentation contains many examples and information about create, delete, list, update or invoke a lambda function, things that can be setted and done with Terraform, but nothing about to create the lambda function itself, specially, if we try to use Typescript and want to use typed vars.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/client/lambda/

**Comment by yenfryherrerafeliz** [comment]
Hi @eltonmoreno-catho, have you taken a look to the following section [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/client/lambda/command/CreateFunctionCommand/) where explains how to create a function by using the CreateFunctionCommand operation?

Thanks!
