### ISSUE TITLE
@aws-sdk/eventstream-serde-node v3.226.0 Not Found

### ISSUE THREAD

**Issue by yukha-dw** [aws/aws-sdk-js-v3#4724]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I've stumbled this error why installing `@aws-sdk/client-s3@^3.226.0`:
> yarn install --frozen-lockfile --production=false
```
error An unexpected error occurred: "https://registry.yarnpkg.com/@aws-sdk/eventstream-serde-universal/-/eventstream-serde-universal-3.226.0.tgz: Request failed \"404 Not Found\"".
```

### SDK version number

@aws-sdk/client-s3@3.226.0, @aws-sdk/client-s3@3.329.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

16.19.0

### Reproduction Steps

```
mkdir s3bug && cd s3bug
npm init -y
npm install @aws-sdk/client-s3
```

### Observed Behavior

```
npm notice
npm notice New major version of npm available! 8.19.4 -> 9.6.6
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.6.6
npm notice Run npm install -g npm@9.6.6 to update!
npm notice
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@aws-sdk%2feventstream-serde-universal - Not found
npm ERR! 404
npm ERR! 404  '@aws-sdk/eventstream-serde-universal@3.329.0' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-05-15T10_27_47_994Z-debug-0.log
```

### Expected Behavior

install client-s3 correctly

**Comment by llllvvuu** [comment]
npm outage currently:

https://status.npmjs.org/incidents/drj38qn6qm59
https://github.com/search?q=+npm+ERR%21+404&type=issues&s=created&o=desc

**Comment by yenfryherrerafeliz** [comment]
@yukha-dw could you please try again now?. I just did it and had not issue when doing so.

```console
 npm install @aws-sdk/client-s3
```

Result:
```console

added 100 packages, and audited 101 packages in 6s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

```
Thanks!

**Comment by yukha-dw** [comment]
@llllvvuu thanks, i've mistaken as only @aws-sdk/client-s3 who has problem. I'll close this
