### ISSUE TITLE
Documentation display order

### ISSUE THREAD

**Issue by plwww** [aws/aws-sdk-js-v3#4725]
### Describe the issue

The three column, sorted-row display is difficult to scan through quickly, as closely related functions end up scattered widely across the page. A more traditional approach, carrying the sorted list through an entire column then wrapping back to top to start the next column, would be more readable, 

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/Package/-aws-sdk-client-s3/

**Comment by MYoung25** [comment]
Hi @plwww,

Thanks for taking the time to leave us feedback!  That page is likely to see some updates as we work towards including the public packages in `packages/` and `lib/` folders.  I've also made a note of your feedback so I don't lose it.

Best,

Michael

**Comment by MYoung25** [comment]
Hi @plwww,

I made a design change that makes it a bit easier to see (and search) all the types, would love to hear your thoughts on the new design!

**Comment by plwww** [comment]
Oh yes, that's much easier to read through, and filter as well.
