### ISSUE TITLE
RangeError: Invalid time value

### ISSUE THREAD

**Issue by 4m4rel** [aws/aws-sdk-js-v3#4728]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Hello!
I faced a bug on my project and saw the discussion [here](https://github.com/aws/aws-sdk-js-v3/issues/4355). 
Seems like reinstalling AWS dependencies really helps, but I'd like to know, if possible, why this bug is occurring? Can I do something to be sure that libraries will work as expected?

### SDK version number

@aws-sdk/s3-presigned-post@3.317.0, @aws-sdk/s3-request-presigner@3.315.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.20.0

### Reproduction Steps

```
import { S3Client, GetObjectCommand, PutObjectCommand } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import { createPresignedPost } from "@aws-sdk/s3-presigned-post";
import { fromIni } from '@aws-sdk/credential-providers';

let options = {
    credentials: fromIni({}),
    region: process.env.region
}

let s3Client = new S3Client(options);

(async function() {

const params = {
  Bucket: 'dummy',
  Fields: {
    key: 'dummy_key',
    'content-type': 'application/pdf',
    'content-length': '3682374'
  },
  Expires: 3600
};

 try {
            const rsltDat = await createPresignedPost(s3Client, params );
        } catch(err) {
console.log(err);

        }

})();
```

### Observed Behavior

RangeError: Invalid time value

### Expected Behavior

No RangeError

### Possible Solution

Reinstall AWS dependencies

### Additional Information/Context

Was discussed at https://github.com/aws/aws-sdk-js-v3/issues/4355

**Comment by yenfryherrerafeliz** [comment]
@4m4rel thanks for opening this discussion. Due to that this issue is not reproducible at my end I do not have any information about why this happened. My guess is that probably some corrupted dependencies, or outdated dependencies being pinned and that altered the behavior of the SDK's client. However, if you happen to have a reproducible scenario we will be happy to investigate this further.

Thanks!
