### ISSUE TITLE
how to use aws lambda sdk? documentation is not readable

### ISSUE THREAD

**Issue by Andriy-Kulak** [aws/aws-sdk-js-v3#4730]
### Describe the issue

Documentation is not readable. Can you please provide a basic working example of how to use aws lambda sdk with specific params, etc?  Providing 1,000 interfacing without any explainations or explaining on basic set up is not very helpful

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/Package/-aws-sdk-client-lambda/

**Comment by MYoung25** [comment]
Hi @Andriy-Kulak,

Thanks for taking the time to leave us feedback, that page is under active development.  We are working hard to make some significant improvements and make it useful for the hundreds of thousands of types across `@aws-sdk/*` packages.

In the meantime: the [developer guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/javascript_lambda_code_examples.html), [LambdaClient reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/client/lambda/), and [CreateFunctionCommand reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/client/lambda/command/CreateFunctionCommand/) should be good places to start.

Best,

Michael
