### ISSUE TITLE
Where dark mode?

### ISSUE THREAD

**Issue by ElmarTalibzade** [aws/aws-sdk-js-v3#4734]
### Describe the issue

eye hurty-hurty :(

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/introduction/

**Comment by ElmarTalibzade** [comment]
Much appreciated!

**Comment by MYoung25** [comment]
@ElmarTalibzade dark mode is now available in the preview!

**Comment by ElmarTalibzade** [comment]
Thank you. My eyes are happy now!

**Comment by MYoung25** [comment]
Mine too 😉
