### ISSUE TITLE
PutObjectCommandInput.SSECustomerKey type is incorrect

### ISSUE THREAD

**Issue by DavidZbarsky-at** [aws/aws-sdk-js-v3#4736]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

This is a dupe of https://github.com/aws/aws-sdk-js-v3/issues/2081 that I am reopening because the explanation didn't make sense to me. I am still seeing this issue, but I am using `PutObjectCommandInput` as advised, rather than `PutObjectRequest`. See also generated types at https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/interfaces/putobjectcommandinput.html#ssecustomerkey-7

Is there something in the codegen process that is supposed to expand the type to account for conversions?

### SDK version number

@aws-sdk/client-v3@latest

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

16

### Reproduction Steps

```
const data: PutObjectCommandInput = {
    SSECustomerKey: Buffer.from('foo')
}
```

### Observed Behavior

```(property) SSECustomerKey?: string | undefined
Type 'Buffer' is not assignable to type 'string'.ts(2322)
models_0.d.ts(8835, 5): The expected type comes from property 'SSECustomerKey' which is declared here on type 'PutObjectCommandInput'```

### Expected Behavior

no type error

### Possible Solution

_No response_

### Additional Information/Context

_No response_

**Comment by yenfryherrerafeliz** [comment]
Hi @DavidZbarsky-at, sorry to hear about your issues. Right now, SSECustomerKey parameter is expected to be string, so that it needs to be provided as so. You can see it's definition [here](https://github.com/aws/aws-sdk-js-v3/blob/45df38afdaf09468648553c9ce36abaca54653d0/clients/client-s3/src/models/models_1.ts#L1057). However, I can mark this as a feature request, but, I would need you to provide more details about why this change is needed?, and what exactly is your use case?.

For now, for you to prevent this error from happening you can convert the buffer returned to string as follow:
```js
const data: PutObjectCommandInput = {
    SSECustomerKey: Buffer.from('foo').toString()
}
```

Thanks!

**Comment by DavidZbarsky-at** [comment]
@yenfryherrerafeliz Hi, thanks for responding.

Here is how the parameter is used: https://github.com/aws/aws-sdk-js-v3/blob/e3fc520933f9210df7aac254dd3e30889fbb7889/packages/middleware-ssec/src/index.ts#L25-L43

In particular, note https://github.com/aws/aws-sdk-js-v3/blob/e3fc520933f9210df7aac254dd3e30889fbb7889/packages/middleware-ssec/src/index.ts#L39-L40 which allows using a buffer view. In fact, if you pass in a strong, it will be converted to a Uint8Array anyway.

So I'm requesting that the type be adjusted to allow passing in a Uint8Array containing the SSECustomerKey.

My application is storing keys in memory as Uint8Array already, so adding extra conversions to string (which the SDK will then convert back to Uint8Array) is just visual noise and wasted CPU cycles.

Please let me know if you have additional questions and thanks for your consideration!

**Comment by yenfryherrerafeliz** [comment]
@DavidZbarsky-at, thanks for providing this information. I will mark this feature request to be reviewed so we can evaluate this further.

Thanks!

**Comment by DavidZbarsky-at** [comment]
Thanks! Quick note - I'd consider this to be a bug in the existing type definitions rather than a new feature. Looking forward to seeing this fixed!

**Comment by yenfryherrerafeliz** [comment]
@DavidZbarsky-at, @jstastny, this is actually not considered as a bug. The type expected for SSECustomerKey is a string and needs to be provided as so. This type is actually defined by the service itself and the SDK just follows its directives regarding typing. We could leave this as a feature-request if you people want but it would be considered as low priority for now. 

Thanks!

**Comment by DavidZbarsky-at** [comment]
@yenfryherrerafeliz Hi, did you have a chance to review the code links I posted in https://github.com/aws/aws-sdk-js-v3/issues/4736#issuecomment-1556185809?

I don't think this statement is correctL "The type expected for SSECustomerKey is a string".

The code handles `ArrayBuffer.isView(value)`. Here's an updated link to the relevant stanza on mainhttps://github.com/aws/aws-sdk-js-v3/blob/51f316ea2d674b1ca78fd7236d6a606d53a88b21/packages/middleware-ssec/src/index.ts#L39-L43

If the type is provided by the service, that's fine, it just needs to be fixed upstream. Is that code public or is that something AWS-internal?

**Comment by yenfryherrerafeliz** [comment]
Hi @DavidZbarsky-at, yes, I reviewed the code you have linked, but we expect the parameters to be provided as the service has defined them, regardless how it is handled internally. Of course we can consider this as a feature request, but to be considered a bug we need to differ from the type set by the service model. I reviewed the Java SDK and PHP SDK and they also both expect the same type. Here you can confirm from the service model that this field is marked as [string](https://github.com/aws/aws-sdk-js-v3/blob/51f316ea2d674b1ca78fd7236d6a606d53a88b21/codegen/sdk-codegen/aws-models/s3.json#L30064C9-L30064C9). I know a wrapper here would be ideal, but this is something we could consider for future implementations.

Please let me know if you have any questions.

Thanks!

>If the type is provided by the service, that's fine, it just needs to be fixed upstream. Is that code public or is that something AWS-internal?
 
For JS SDK here is where the service models are:
https://github.com/aws/aws-sdk-js-v3/tree/main/codegen/sdk-codegen/aws-models
