### ISSUE TITLE
Offer Copy/Paste for npm install script

### ISSUE THREAD

**Issue by Elevating7734** [aws/aws-sdk-js-v3#4748]
### Describe the issue

As a time saver, many sites now offer the ability to copy/paste the installation script. It would be helpful to have the same option when looking up SDK calls from the documentation site.

Ex: https://www.npmjs.com/package/@aws-sdk/client-s3

![image](https://github.com/aws/aws-sdk-js-v3/assets/120058928/141815a5-1d94-4d5e-b1c5-f9bb669d9e1a)

### Links

Example AWS documentation:

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/Package/-aws-sdk-client-s3/

**Comment by MYoung25** [comment]
Hi @Elevating7734,

Thanks for taking the time to look at the new api reference and leave us feedback! This _should_ be relatively easy (famous last words!).  I've made a note to look into it in the future, however I believe there is currently an internal blocker to adding this.

Thanks again for leaving feedback!

Best,
Michael

**Comment by MYoung25** [comment]
Hi @Elevating7734, 

I have added copy/pastable npm install scripts to all packages for multiple package managers.  Thanks again for taking time to leave us feedback!

Best,

Michael
