### ISSUE TITLE
Quick access to common services

### ISSUE THREAD

**Issue by mitchmcleod-ew** [aws/aws-sdk-js-v3#4752]
### Describe the issue

It would be very helpful for a short list of 5-10 of the most commonly used service interfaces to be listed above the rest of the service list on the sidebar of the new JS v3 docs.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/client/s3/

**Comment by MYoung25** [comment]
Hi @mitchmcleod-ew,

Thanks for taking the time to check out the new api reference and leave feedback.  I've made a note of your feedback and will see if its something we can accommodate in a future release.

Best,

Michael

**Comment by RanVaknin** [comment]
Hi @mitchmcleod-ew ,

Sorry for the long response time. This is now implemented:
<img width="345" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/50976344/e4d8e09e-a955-43ef-aa4f-ca7936b9b826">


Thanks again for your feedback,
Ran~
