### ISSUE TITLE
Navigation towards all services/classes is needs

### ISSUE THREAD

**Issue by ak2i** [aws/aws-sdk-js-v3#4764]
### Describe the issue

After I see detail of API or class definition, I can not go back to upper hierarchy menu....

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/

**Comment by RanVaknin** [comment]
Hi @ak2i ,

Can you share a screenshot of what you mean?

<img width="704" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/50976344/67abfd18-2fd5-4bb4-9bb6-8796c02ad300">

For example the doc page for `GetObjectCommand` has the directory path as a link at the top.

If you can elaborate that would be helpful.

Thanks,
Ran~
