### ISSUE TITLE
Cloudflare Workers environment don't have FileReader defined

### ISSUE THREAD

**Issue by limzykenneth** [aws/aws-sdk-js-v3#4765]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Following up on #4369, the SDK still doesn't work fully in a Cloudflare Workers environment. The main reason is that there is use of FileReader in the codebase which isn't present in the Workers environment (only in browser environment).

From what I can see the use of FileReader is to get around the lack of full Blob support, although as far as I'm aware there isn't an environment where Blob.text() is not fully supported while FileReader is (node.js have no Blob support until recently but it doesn't have FileReader either, while Blob.text() seems to be available whenever Blob itself is in browser or otherwise).

Is there some reason why FileReader should be used instead of just using Blob's features directly?

### SDK version number

@aws-sdk/client-s3@3.335.0

### Which JavaScript Runtime is this issue in?

Browser

### Details of the browser/Node.js/ReactNative version

Cloudflare Workers, wrangler@2.12.2

### Reproduction Steps

```js
await client.deleteObject({
  Bucket: "my-bucket",
  Key: "filename"
});
```

### Observed Behavior

```
ReferenceError: FileReader is not defined
  Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.
    at t3 (/tmp/tmp-157240-Le6BggT4YM6F/worker.js:7397:16)
    at new Promise (<anonymous>)
    at o (/tmp/tmp-157240-Le6BggT4YM6F/worker.js:7396:20)
    at Object.n2 [as streamCollector] (/tmp/tmp-157240-Le6BggT4YM6F/worker.js:7394:70)
    at dd (/tmp/tmp-157240-Le6BggT4YM6F/worker.js:6011:434)
    at tS (/tmp/tmp-157240-Le6BggT4YM6F/worker.js:3486:18)
    at deserialize (/tmp/tmp-157240-Le6BggT4YM6F/worker.js:2575:43)
    at /tmp/tmp-157240-Le6BggT4YM6F/worker.js:8120:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /tmp/tmp-157240-Le6BggT4YM6F/worker.js:8179:160 {
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
```

### Expected Behavior

No error should be present

### Possible Solution

I'm currently monkey patching the relevant part of the dependency by directly using Blob.text() instead of FileReader and noticed no issues.

**Comment by RanVaknin** [comment]
Hi @limzykenneth ,

As @trivikr mentioned in the previous thread, AWS does not guarantee support for 3rd party offerings like Cloudflare Workers. AWS supports Lambda as a serverless offering. 

Im going to convert this into a feature request.

Thanks,
Ran~

**Comment by limzykenneth** [comment]
Sure that's fine. I'm still curious why FileReader is used instead of Blob directly though.

**Comment by stukennedy** [comment]
There is a way around this (without a monkey-patch) ... if you use the API via fetch instead by generating a presigned URL then you can call the command that way.

```
export const deleteFile = async (key: string) => {
  const url = await getSignedUrl(
    r2,
    new DeleteObjectCommand({ Bucket: bucketName, Key: key }),
    { expiresIn: 3600 }
  );
  await fetch(url, {
    method: 'DELETE',
  });
};
```

**Comment by vvo** [comment]
Can I ask: what is the S3 client trying to deserialize exactly? Since a simple GetObjectCommand is working in Cloudflare workers, I would have expected HeadObjectCommand to do less things and works for sure.

What is HeadObjectCommand trying to deserialize that requires FileReader exactly? Thanks!

**Comment by limzykenneth** [comment]
@stukennedy That gives a `TypeError: Can't modify immutable headers.` and even if it worked I would need to parse the XML response manually if I need anything from the response body.

**Comment by auniverseaway** [comment]
I also ran into this issue trying to use `HeadBucketCommand` as well in CF Workers. The alternatives do not look good...

1. Use the older aws-sdk - Looks to be EOL any day now.
2. Use aws4fetch - Returns XML responses (in my testing).

**Comment by riderx** [comment]
> There is a way around this (without a monkey-patch) ... if you use the API via fetch instead by generating a presigned URL then you can call the command that way.
> 
> ```
> export const deleteFile = async (key: string) => {
>   const url = await getSignedUrl(
>     r2,
>     new DeleteObjectCommand({ Bucket: bucketName, Key: key }),
>     { expiresIn: 3600 }
>   );
>   await fetch(url, {
>     method: 'DELETE',
>   });
> };
> ```

This work also for `HeadBucketCommand ` @auniverseaway !

```js
async function getSizeChecksum(c: Context, fileId: string) {
  const client = initS3(c)
  const command = new HeadObjectCommand({
    Bucket: getEnv(c, 'S3_BUCKET'),
    Key: fileId,
  })
  const url = await getSignedUrlSDK(client, command)
  const response = await ky.head(url)
  const contentLength = response.headers.get('content-length')
  const checksum = response.headers.get('x-amz-meta-crc32')
  const size = contentLength ? parseInt(contentLength, 10) : 0
  return { size, checksum }
}
```

**Comment by aza547** [comment]
Trying this solution of sign and fetch the URL works great to `DeleteObjectCommand` / `DeleteObjectsCommandobjects`.

Attempting it for `DeleteBucketCommand` gives this error...

```
<?xml version= \"1.0\" encoding= \"UTF-8\"?>
<Error>
    <Code>InvalidArgument</Code>
    <Message>Invalid Argument: Unsupported search param(s) "X-Amz-Algorithm",
        "X-Amz-Content-Sha256", "X-Amz-Credential", "X-Amz-Date", "X-Amz-Expires",
        "X-Amz-Signature", "X-Amz-SignedHeaders" on a DELETE bucket route</Message>
</Error>
```

Saw some references claiming signing URLs is only supported for GETs and PUTs. Although clearly it works for some DELETEs.

**Comment by aBurmeseDev** [comment]
Hi everyone, thank you for your patience. After further discussion with the team, we recommend exploring the workarounds mentioned in this issue thread and considering the use of a polyfill for the FileReader API in your application bundle. The FileReader used in SDK is only to read Blobs and polyfil doesn't need to read files. 

As previously stated, AWS does not guarantee support for third-party offerings like Cloudflare Workers. However, we are committed to assisting you in unblocking your workflow. If you have already tried the suggested workarounds and polyfill but the problem persists, please let us know, and we will provide further guidance.

**Comment by limzykenneth** [comment]
This is kinda old but for me it is the same as before, I've monkey patched the FileReader stuff to be one line based on the blob that is already there and it works just fine. I still don't understand why FileReader is needed despite it basically only supporting browsers and even with Node.js you will need a separate solution, when Blob is available in any standard JS environment. It's fine if there are no wish to change this, I just find it odd to not go for the simpler standard solution.

Here's my monkey patch diff:
```diff
diff --git a/node_modules/@smithy/fetch-http-handler/dist-es/stream-collector.js b/node_modules/@smithy/fetch-http-handler/dist-es/stream-collector.js
index a7b4e83..5dceb81 100644
--- a/node_modules/@smithy/fetch-http-handler/dist-es/stream-collector.js
+++ b/node_modules/@smithy/fetch-http-handler/dist-es/stream-collector.js
@@ -27,19 +27,5 @@ async function collectStream(stream) {
     return res;
 }
 function readToBase64(blob) {
-    return new Promise((resolve, reject) => {
-        const reader = new FileReader();
-        reader.onloadend = () => {
-            if (reader.readyState !== 2) {
-                return reject(new Error("Reader aborted too early"));
-            }
-            const result = (reader.result ?? "");
-            const commaIndex = result.indexOf(",");
-            const dataOffset = commaIndex > -1 ? commaIndex + 1 : result.length;
-            resolve(result.substring(dataOffset));
-        };
-        reader.onabort = () => reject(new Error("Read aborted"));
-        reader.onerror = () => reject(reader.error);
-        reader.readAsDataURL(blob);
-    });
+    return blob.text();
 }
```

**Comment by riderx** [comment]
Since AWS is not helping i have personally ditched all their stuff and will not deal with it anymore.
This is just bloated code.
On the other hand if you still need it Cloudflare made some magic and support now most of nodejs API you just need to update the workers version to the last one:
https://developers.cloudflare.com/workers/runtime-apis/nodejs/
