### ISSUE TITLE
the code sample did not work without Buffer.from() in typescript.

### ISSUE THREAD

**Issue by ssagli** [aws/aws-sdk-js-v3#4782]
### Describe the issue

I was trying out the code sample given in the lambda invokeCommand documentation, and it kept giving me the type error. I was looking for a solution and found this https://github.com/aws/aws-sdk-js-v3/issues/4475 and was able to resolve the issue. I would appreciate it if you could update the documentation to add `Buffer.from()` for the Payload value.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/client/lambda/command/InvokeCommand/

**Comment by RanVaknin** [comment]
Related #4786

**Comment by kuhe** [comment]
fixed in https://github.com/awslabs/smithy-typescript/pull/777

**Comment by RanVaknin** [comment]
<img width="2139" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/50976344/96c5376c-4ebe-45d7-8024-a94cf3d946ab">

Type documentation expanded. 
Closing.
