### ISSUE TITLE
Invalid type for `DetectLabelsCommandOutput`

### ISSUE THREAD

**Issue by hamza-shezad** [aws/aws-sdk-js-v3#4790]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

`DetectLabelsCommandOutput` can be `undefined` in the case of `Image.Bytes` in `DetectLabelsCommand` contains data that is not an image.

### SDK version number

@aws-sdk/client-rekognition@3.333.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.16.0

### Reproduction Steps

```js
const image = readFileSync("./path-to-json-file.json");
const client = new RekognitionClient({
	credentials: fromEnv(),
	region: AWS_REGION,
});
const command = new DetectLabelsCommand({
	Image: {
		Bytes: image,
	},
	Features: ["GENERAL_LABELS", "IMAGE_PROPERTIES"],
	MinConfidence: 70,
	Settings: {
		GeneralLabels: {
			LabelCategoryInclusionFilters: ["Text and Documents"],
		},
	},
});
const response = await client.send(command)
```

### Observed Behavior

`response` is `undefined`

### Expected Behavior

`response` to be `{}` or to throw.

### Possible Solution

Add `undefined` to the type of `DetectLabelsCommand`

**Comment by yenfryherrerafeliz** [comment]
Hi @hamza-shezad, I am not sure why you are getting undefined as response, because you should receive a message like the following:
```console
 const exception = new models_0_1.InvalidImageFormatException({
                      ^
InvalidImageFormatException: Request has invalid image format

```
I used the code below:
```js
import {DetectLabelsCommand, RekognitionClient} from "@aws-sdk/client-rekognition";
import {readFileSync} from "fs";

const image = readFileSync("../package.json");
const client = new RekognitionClient({
    region: process.env.TEST_REGION,
});
const command = new DetectLabelsCommand({
    Image: {
        Bytes: image,
    },
    Features: ["GENERAL_LABELS", "IMAGE_PROPERTIES"],
    MinConfidence: 70,
    Settings: {
        GeneralLabels: {
            LabelCategoryInclusionFilters: ["Text and Documents"],
        },
    },
});
const response = await client.send(command)

console.log(response)
```

Could you please help me with enabling error logs to track what could be causing that behavior at your end, you just need to add a logger object to the client and implementing the error function as follow:

```js
const client = new RekognitionClient({
    region: process.env.TEST_REGION,
    logger: {
        error: function (content) {
            console.log(content)
        }
    }
});
```
A full example would be:
```js
import {DetectLabelsCommand, RekognitionClient} from "@aws-sdk/client-rekognition";
import {readFileSync} from "fs";

const image = readFileSync("../package.json");
const client = new RekognitionClient({
    region: process.env.TEST_REGION,
    logger: {
        error: function (content) {
            console.log(content)
        }
    }
});
const command = new DetectLabelsCommand({
    Image: {
        Bytes: image,
    },
    Features: ["GENERAL_LABELS", "IMAGE_PROPERTIES"],
    MinConfidence: 70,
    Settings: {
        GeneralLabels: {
            LabelCategoryInclusionFilters: ["Text and Documents"],
        },
    },
});
const response = await client.send(command)

console.log(response)
```

Thanks!
