### ISSUE TITLE
Selectable aws-sdk v3 release number

### ISSUE THREAD

**Issue by mbreen704** [aws/aws-sdk-js-v3#4793]
### Describe the issue

Being able to select a specific release number for the sdk might prove useful in scenarios where using an older version of the sdk is either a requirement or the default for an environment. An example would be the Node 18.x runtime that can be set for lambdas, which I believe is only up to aws-sdk version 3.188.0, correct me if I'm wrong. Without this ability, knowing what is and isn't included in any particular version would require scanning through each individual release up to the one the user is currently using.

**Comment by mbreen704** [comment]
Apologies for the confusion and the mistake tag, I wasn't too sure how to word this myself and don't normally post to GitHub issues. 

Here is a more concrete example - https://repost.aws/questions/QUE0VhKI07RWyNtTVZiFdzcw/cannot-find-package-aws-sdk-client-scheduler-error#:~:text=For%20node18%2C%20latest,page%3D6.
For this instance, if it had been possible to set what version one is currently working on, in this case 3.188.0, then one could have more easily noticed that client-scheduler package is not available in the version they are working with. 

An instance where I have seen this functionality before is with Unity docs, where you can set what version of Unity you are working with via a dropdown in the upper left corner. https://docs.unity3d.com/Manual/index.html

**Comment by RanVaknin** [comment]
Hi @mbreen704 ,

Thanks for the clarification. There is no way to select an SDK version from a drop down. As mentioned in the rePost answer you shared, lambda with Node 18 has a set version of the SDK that it embeds (as of this moment its 3.188.0). This is not something the SDK team controls - it is controlled by the lambda service team and is not updated regularly (a few times a year).
If you want to use features like `client-scheduler` that is only available on newer SDK versions, you need to upload your own version of the SDK to lambda. This can be done either by bundling + minifying as shown in the last link I shared, or by uploading your dependencies as a Lambda layer and linking that layer to your lambda function. 

Let me know if you have any other questions.
Thanks,
Ran~
