### ISSUE TITLE
fast-xml-parser dependency has a vulnerability

### ISSUE THREAD

**Issue by jdforsythe** [aws/aws-sdk-js-v3#4801]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Just as it says on the tin, one of your dependencies has a vulnerability

```sh
$ yarn audit --groups dependencies
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ fast-xml-parser vulnerable to Regex Injection via Doctype    │
│               │ Entities                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ fast-xml-parser                                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.2.4                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @aws-sdk/client-s3                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @aws-sdk/client-s3 > fast-xml-parser                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1092243                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ fast-xml-parser vulnerable to Regex Injection via Doctype    │
│               │ Entities                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ fast-xml-parser                                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.2.4                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @aws-sdk/client-s3                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @aws-sdk/client-s3 > @aws-sdk/client-sts > fast-xml-parser   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1092243                    │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

### SDK version number

@aws-sdk/client-s3@3.347.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

all

### Reproduction Steps

Just run `npm audit` in your repo. Or install @aws-sdk/client-s3 in a new project and run `npm audit`

### Observed Behavior

Vulnerability present

### Expected Behavior

No vulnerability present

### Possible Solution

Upgrade fast-xml-parser to >=4.2.4 or stop parsing XML and remove it

### Additional Information/Context

https://www.npmjs.com/advisories/1092243

**Comment by RanVaknin** [comment]
Hi @jdforsythe 
Thank you for letting us know. We are on it.

Ran~

**Comment by bkaws** [comment]
Hi @jdforsythe, this was [patched](https://github.com/aws/aws-sdk-js-v3/commit/602d7dd49ce24a57f56333c5db88642e0e26bc31) in version 3.347.1 on June 6.

**Comment by jdforsythe** [comment]
@bkaws @RanVaknin my mistake - Dependabot opened PRs for 3.347.0 on several of our repos this morning.

I manually bumped to 3.347.1 and the vuln is fixed. Thanks!
