### ISSUE TITLE
How to chain and memoize credential providers

### ISSUE THREAD

**Issue by bullett445** [aws/aws-sdk-js-v3#4809]
### Describe the issue

I didn't find a description how to provide config values for multiple credential providers nor how to build an own credential provider chain with individual configs.

The default provider chains seem to be assembled using the property-provider package which is not described and marked as internal.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/

**Comment by kuhe** [comment]
https://www.npmjs.com/package/@aws-sdk/credential-providers

Implementation is up to the user to decide.

Example of chained provider using JavaScript.

```ts

import { fromIni } from "@aws-sdk/credential-providers";
import { fromEnv } from "@aws-sdk/credential-providers";

let credentials;

const chainedCachedProvider = async () => {
  if (credentials) return credentials;

  const order = [fromIni(iniConfig), fromEnv(envConfig)];
  for (const provider of order) {
    try {
      credentials = await provider();
      return credentials;
    } catch(e) {
      continue;
    }
  }
  throw new Error('no successful credential provider');
}

```

We do not mark the memoize and chain functions implemented in the SDK as public because they are subject to change.
