### ISSUE TITLE
@aws-sdk/cloudfront-signer missing tslib dependency

### ISSUE THREAD

**Issue by chris-codaio** [aws/aws-sdk-js-v3#4814]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

`dist-cjs/index.js` has a dependency on `tslib` that is undeclared in `package.json`.  This breaks usage of this library when used in a strict dependency environment such as `pnpm`.

index.js
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const tslib_1 = require("tslib");
tslib_1.__exportStar(require("./sign"), exports);
```

package.json
```
 ...
  "dependencies": {
    "@aws-sdk/url-parser": "3.347.0"
  },
  ...
```

### SDK version number

@aws-sdk/cloudfront-signer@3.347.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node: v16.17.1

### Reproduction Steps

Attempt to use `@aws-sdk/cloudfront-signer` from a repo using `pnpm` for package management.

### Observed Behavior

```
Error: Cannot find module 'tslib'
Require stack:
- .../@aws-sdk+cloudfront-signer@3.347.0/node_modules/@aws-sdk/cloudfront-signer/dist-cjs/index.js
...
```

### Expected Behavior

Declare the dependency.

### Possible Solution

Add tslib to the list of runtime dependencies in `package.json`.

**Comment by yenfryherrerafeliz** [comment]
Hi @chris-codaio, sorry to hear about your issues. I am not sure why you are experiencing this, because [here](https://github.com/aws/aws-sdk-js-v3/blob/9055419c2754f44fb3c924160323853f9e358b2a/packages/url-parser/package.json#L25) we can see that tslib is a dependency of @aws-sdk/url-parser, and @aws-sdk/url-parser is a dependency of @aws-sdk/cloudfront-signer. Maybe the problem is that you are using an outdated version of the SDK?, could you please try to update the SDK to the latest version?

Please let me know if that helps!

Thanks!

**Comment by yenfryherrerafeliz** [comment]
Hi @chris-codaio, can you please confirm if this issue still happens for you using the latest version of the SDK?. tslib is not a direct dependency of @aws-sdk/cloudfront-signer, and therefore I do not think it should be included as so. 
I just created a fresh project with pnpm, installed the @aws-sdk/cloudfront-signer@3.433.0 package and here is the lock file generated by pnpm:
```
lockfileVersion: '6.0'

settings:
  autoInstallPeers: true
  excludeLinksFromLockfile: false

dependencies:
  '@aws-sdk/cloudfront-signer':
    specifier: ^3.433.0
    version: 3.433.0

packages:

  /@aws-sdk/cloudfront-signer@3.433.0:
    resolution: {integrity: sha512-I86TTLVSAFb0nMVPWxNipVwkmf0dw0FEchoA1sJx5j9YPyBhc0gzg3Af1Qkzzty+Pkwwc+CtPbqHkYxbXI1tFg==}
    engines: {node: '>=14.0.0'}
    dependencies:
      '@smithy/url-parser': 2.0.12
    dev: false

  /@smithy/querystring-parser@2.0.12:
    resolution: {integrity: sha512-fytyTcXaMzPBuNtPlhj5v6dbl4bJAnwKZFyyItAGt4Tgm9HFPZNo7a9r1SKPr/qdxUEBzvL9Rh+B9SkTX3kFxg==}
    engines: {node: '>=14.0.0'}
    dependencies:
      '@smithy/types': 2.4.0
      tslib: 2.6.2
    dev: false

  /@smithy/types@2.4.0:
    resolution: {integrity: sha512-iH1Xz68FWlmBJ9vvYeHifVMWJf82ONx+OybPW8ZGf5wnEv2S0UXcU4zwlwJkRXuLKpcSLHrraHbn2ucdVXLb4g==}
    engines: {node: '>=14.0.0'}
    dependencies:
      tslib: 2.6.2
    dev: false

  /@smithy/url-parser@2.0.12:
    resolution: {integrity: sha512-qgkW2mZqRvlNUcBkxYB/gYacRaAdck77Dk3/g2iw0S9F0EYthIS3loGfly8AwoWpIvHKhkTsCXXQfzksgZ4zIA==}
    dependencies:
      '@smithy/querystring-parser': 2.0.12
      '@smithy/types': 2.4.0
      tslib: 2.6.2
    dev: false

  /tslib@2.6.2:
    resolution: {integrity: sha512-AEYxH93jGFPn/a2iVAwW87VuUIkR1FVUKB77NwMF7nBTDkDrrT/Hpt/IrCJ0QXhW27jTBDcf5ZY7w6RiqTMw2Q==}
    dev: false

```

So, I think you should have not issues now, but if so, please make sure you test with a fresh project.

I look forward to your response.

Thanks!

**Comment by chris-codaio** [comment]
It looks like the distribution file still has an explicit undeclared dependency on tslib.

```
❯ cat node_modules/@aws-sdk/cloudfront-signer/dist-cjs/index.js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const tslib_1 = require("tslib");
tslib_1.__exportStar(require("./sign"), exports);
```
