### ISSUE TITLE
[util-dynamodb] marshall overload signatures are broken due to more general overload matching first

### ISSUE THREAD

**Issue by pedropedruzzi** [aws/aws-sdk-js-v3#4828]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

A number of fine grained overload signatures were added to the marshall function by PR #3539. In theory this improvement would allow the return of e.g. `marshall(10)` to be detected as having type `AttributeValue.NMember` and so forth.

However, this doesn't currently work because the object/map sinature apparently matches `any` type, so the next signatures don't ever get a chance to match.

### SDK version number

@aws-sdk/util-dynamodb@3.350.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.16.0

### Reproduction Steps

Just try to tsc the follow TS snippet:

```typescript
import { AttributeValue } from '@aws-sdk/client-dynamodb';
import { marshall } from '@aws-sdk/util-dynamodb';

const attributeValue: AttributeValue = marshall(10);
```

### Observed Behavior

The above code fails to TS compile with error `Type 'Record<string, AttributeValue>' is not assignable to type 'AttributeValue'.` because the return is incorrectly detected as `Record<string, AttributeValue>`.

### Expected Behavior

No TS compilation errors. According to overload signature `export declare function marshall(data: number, options?: marshallOptions): AttributeValue.NMember;`, the call `marshall(10)` should return type `AttributeValue.NMember` instead which is assignable to `AttributeValue`. 

### Possible Solution

Rearrange the order of overload signature moving the more general one to the end of the list. Will send a PR shortly.

**Comment by RanVaknin** [comment]
Hi @pedropedruzzi ,

Thanks for opening this issue. I'm able to confirm that this is an issue. Will review this with the team. 

Thanks,
Ran~

**Comment by trivikr** [comment]
Reopening, as the fix was reverted in https://github.com/aws/aws-sdk-js-v3/pull/4909

**Comment by sasucker** [comment]
Were there reports of broken types that led to this revert?
