### ISSUE TITLE
S3Client no longer supports  bucketEndpoint = true,

### ISSUE THREAD

**Issue by sannies** [aws/aws-sdk-js-v3#4831]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

It looks to me as if the BucketEndpointInputConfig is accidentally not part of the S3ClientConfigType even though it should.

bucketEndpoint disappeared after 3.190.0``

### SDK version number

3.350.0

### Which JavaScript Runtime is this issue in?

Browser

### Details of the browser/Node.js/ReactNative version

any

### Reproduction Steps

     
```
this.s3 = new S3({
            credentials: fromApi(this.credentials$),
            bucketEndpoint: true,
            region: 'us-east-1'
});
```

The error is:

`Argument of type '{ credentials: CredentialProvider; bucketEndpoint: boolean; region: string; }' is not assignable to parameter of type 'S3ClientConfigType'.   Object literal may only specify known properties, and 'bucketEndpoint' does not exist in type 'S3ClientConfigType'.
`
### Observed Behavior

Argument of type '{ credentials: CredentialProvider; bucketEndpoint: boolean; region: string; }' is not assignable to parameter of type 'S3ClientConfigType'.   Object literal may only specify known properties, and 'bucketEndpoint' does not exist in type 'S3ClientConfigType'.

### Expected Behavior

just work!

### Possible Solution

add BucketEndpointInputConfig to S3ClientConfigType 
and add it to the S3Client constructor.

**Comment by RanVaknin** [comment]
Hi @sannies ,

Can you try using `endpoint` instead of `bucketEndpoint` , and add `forcePathStyle: true` as well to the client config? 
```js
const client = new S3Client({
  region: 'us-east-1',
  forcePathStyle: true,
  endpoint: 'http://customS3Endpoint.com',
})
```
Thanks,
Ran~
