### ISSUE TITLE
Better side panel UI for nested type. 

### ISSUE THREAD

**Issue by artidataio** [aws/aws-sdk-js-v3#4842]
### Describe the issue

I like that the new page has side panel when input parameter's type is clicked. In the previous version, you have to navigate out of the command page which is less convenient. 

However, many of the input parameters' type are nested on several levels. When you click on deeper type, you will lose track on the   parent's type info, and there is no way to reach it back. I suggest the side panel has [breadcrumbs](https://mui.com/material-ui/react-breadcrumbs/) UI to keep track of the nested type and easy navigation to parent's type.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/client/sesv2/command/SendEmailCommand/

**Comment by MYoung25** [comment]
Hi @artidataio,

First, thanks for taking the time to leave us feedback.  Due to the side panel being hard to read, we have actually moved it to the bottom.  I believe the change to the split panel instead of side panel _may_ give us the opportunity to add some sort of breadcrumbs to the nested type panel.

I can't promise this is something we'll be able to implement.

Best,

Michael

**Comment by RanVaknin** [comment]
Hi @artidataio 

I think this is what you were hoping for?
<img width="601" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/50976344/7a6f820c-7643-4b94-bce2-a66eaf27433b">


Thanks,
Ran~

**Comment by artidataio** [comment]
@RanVaknin That's at the type of service and command level. 

The better example for my explanation is here: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/Package/-aws-sdk-client-sesv2/Interface/SendEmailCommandInput/. You can tell that you need parameter `content` with type of `EmailContent`. Then you click the `EmailContent` which opened up side (or bottom) panel that tells its parameter which one of them is `Template`.  Then, if you click the `Template` type the side panel will now display the members of Template's type. The problem is you now lose track the parent of `Template` which is `EmailContent` as there is no mention of `EmailContent` at all on the `Template`'s side panel. 

The breadcrumbs UI is just a suggestion, the main thing is I want to have access to the parent's type when my side panel is on its child.

**Comment by RanVaknin** [comment]
Hi @artidataio,

Thanks for your patience. After reviewing this again with the team, we decided we are not going forward with implementing this feature. Even though this would be a good nice-to-have, it is unlikely to get prioritized in the near future and therefore we are going to close this. If other feature requests of this nature come up again we can reevaluate. 

Thanks again,
Ran~
