### ISSUE TITLE
show package command to install the package needed

### ISSUE THREAD

**Issue by MorganPersson** [aws/aws-sdk-js-v3#4845]
### Describe the issue

It's unclear which package is needed to install to use this (and probably all other things) so it would be nice if there was a command line option to copy.

Ex:
Installation with npm:
```bash
npm install @aws-sdk/client-sso-admin
```

with yarn:
```bash
yarn add @aws-sdk/client-sso-admin
``` 

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/client/sso-admin/

**Comment by MYoung25** [comment]
Thanks for taking the time to leave us feedback!

We actually _just_ added copy/paste installation commands related to: https://github.com/aws/aws-sdk-js-v3/issues/4748.

Best,

Michael
