### ISSUE TITLE
TS issue: `@aws-sdk/client-lambda` `InvokeCommandInput` has type issue for key `Payload`

### ISSUE THREAD

**Issue by hirenchauhan2** [aws/aws-sdk-js-v3#4846]
### Describe the issue

Hi,

I'm migrating from V2 SDK to V3 using the codemod  `npx aws-sdk-js-codemod -t v2-to-v3 -v 2 DIR/FILES_GLOB`.

While checking code for invoking Lambda using code I'm getting a Type error for the key `Payload` of params of the interface `InvokeCommandInput` which is needed for creating the `InvokeCommand`.

Currently, the `Payload` key only takes the `Uint8Array` as value. But, from examples in `aws-doc-sdk-examples/javascriptv3/example_code/lambda/actions/invoke.js` [invoke.js](https://github.com/awsdocs/aws-doc-sdk-examples/blob/5dbae7914954c656edaea2f01464482aa887515b/javascriptv3/example_code/lambda/actions/invoke.js#LL13C1-L13C1) uses the `Payload: JSON.stringify(data)`.

So, can we ignore the type error by putting `@ts-ignore` just to avoid the compiler errors? Or is it required to pass the Buffer to Payload?

### Links

https://github.com/awsdocs/aws-doc-sdk-examples/blob/5dbae7914954c656edaea2f01464482aa887515b/javascriptv3/example_code/lambda/actions/invoke.js#LL13C1-L13C1

**Comment by tcyrus** [comment]
According to awsdocs/aws-doc-sdk-examples#4731, this is a TS issue and not a documentation issue.
I believe the current issue tracking this is #4623.

**Comment by hirenchauhan2** [comment]
Thanks @tcyrus, closing this issue, will watch that one!
