### ISSUE TITLE
Add a table of contents

### ISSUE THREAD

**Issue by awong-gravity** [aws/aws-sdk-js-v3#4851]
### Add a table of contents of the S3Client Operations. 

Currently there is only a single list of the operations with a long summary next to each. This results in having to scroll a long list and scan a sparse list on the command side to see what operations are available.

Adding a table of contents that jumps to each command would make it much easier to navigate and view which commands are available. 

Alternatively, limit the "summary" to a maximum line length. The "summary" given for `CreateBucketCommand` and `CreateMultipartUploadCommand`, for example, are much too long and make it hard to scan the available operations.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/client/s3/

**Comment by MYoung25** [comment]
Hi @awong-gravity,

Thanks for taking the time to leave us feedback!  I've spent some time thinking about ways to improve the experience.

S3 has some of the longest descriptions, and I agree that it makes it hard to scan.  So far, the best idea I've had is to enable the ability for each user to choose the relevant information, you can see a demo of the proposed behavior at https://cloudscape.design/examples/react/table.html and if you click the gear icon you can choose what fields you're seeing.

Would the ability to show/hide the summary help?
