### ISSUE TITLE
TypeError: Invalid RFC-7231 date-time value raised when using s3 HeadObjectCommand

### ISSUE THREAD

**Issue by K3vChan** [aws/aws-sdk-js-v3#4855]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When using the old sdk it's not raised but I'm assuming it has something to do with something the following payload

```
{
    "AcceptRanges": "bytes",
    "LastModified": "2023-05-27T02:18:59+00:00",
    "ContentLength": 422272,
    "ETag": "\"33db6f56ef62a689e0bcc2aadd34f23f\"",
    "CacheControl": "max-age=0",
    "ContentType": "image/jpeg",
    "Expires": "1969-12-31T16:00:00-08:00",
    "ServerSideEncryption": "AES256",
    "Metadata": {}
}
```

### SDK version number

@aws-sdk/client-s3 3.354.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v14.19.3

### Reproduction Steps

fetch the head of an object with an old date

### Observed Behavior

error thrown

### Expected Behavior

date to be returned even if it's in the past

**Comment by yenfryherrerafeliz** [comment]
Hi @K3vChan, sorry to hear about your issues. I could not reproduce on my end, but by looking at the implementation where the date is parsed, which is found [here](https://github.com/dustin-lennon/aws-sdk-js-v3/blob/2003986a259811dd0758c01fd04a9d55d405ad13/packages/smithy-client/src/date-utils.ts#L98), is probably that there is not a regex pattern that matches the date in the format that you may be  getting in , which indeed will cause an error.

To confirm this, could you please do the following so we can see the value for the headers before they are parsed:
```js
import {HeadObjectCommand, S3Client} from "@aws-sdk/client-s3";

const client = new S3Client({
    region: 'us-east-2'
});
client.middlewareStack.addRelativeTo(next => async (args) => {
    const { response } = await next(args);
    const headers = response.headers;
    const headersToShow = [];
    for (const [key, value] of Object.entries(headers)) {
        if (key.startsWith("x-amz-")) {
            continue;
        }

        headersToShow[key] = value;
    }

    console.log(headersToShow);

    return {
        response,
        output: {
            $metadata: {
                statusCode: 200
            }
        }
    };
}, {
    name: "logSerializeResponse",
    toMiddleware: "deserializerMiddleware",
    relation: "after",
    step: "deserialize",
    override: true
})
await client.send(new HeadObjectCommand({
    Bucket: process.env.TEST_BUCKET,
    Key: process.env.TEST_KEY
}));
```

I look forward to your response.

Thanks!
