### ISSUE TITLE
fast-xml-parser dependency has a vulnerability

### ISSUE THREAD

**Issue by jdforsythe** [aws/aws-sdk-js-v3#4870]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

```sh
$ yarn audit --groups dependencies
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ low           │ fast-xml-parser regex vulnerability patch could be improved  │
│               │ from a safety perspective                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ fast-xml-parser                                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @aws-sdk/client-s3                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @aws-sdk/client-s3 > fast-xml-parser                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1092278                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ low           │ fast-xml-parser regex vulnerability patch could be improved  │
│               │ from a safety perspective                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ fast-xml-parser                                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @aws-sdk/client-s3                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @aws-sdk/client-s3 > @aws-sdk/client-sts > fast-xml-parser   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1092278                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

### SDK version number

@aws-sdk/client-s3@3.357.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

all

### Reproduction Steps

Run `npm audit`

### Observed Behavior

vulnerability present

### Expected Behavior

no vulnerability present

### Possible Solution

No patch appears to be available yet. Track fast-xml-parser for an update.

### Additional Information/Context

https://www.npmjs.com/advisories/1092278

@bkaws @RanVaknin here we go again!

I did double-check this time, and v3.357.0 is the newest version.

**Comment by jdforsythe** [comment]
Tracking issue: https://github.com/NaturalIntelligence/fast-xml-parser/issues/591

**Comment by aaleksandrov** [comment]
`fast-xml-parser` author has just published a fixed version v 4.2.5
https://www.npmjs.com/package/fast-xml-parser

**Comment by yenfryherrerafeliz** [comment]
Hi @jdforsythe, thanks for reporting this. We are currently working on getting a patch for this. 

Thanks!

**Comment by kuhe** [comment]
fast-xml-parser dependency is set to 4.2.5 in the following released version:
https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.359.0
