### ISSUE TITLE
Aborted AbortSignal does not stop retries

### ISSUE THREAD

**Issue by u873838** [aws/aws-sdk-js-v3#4871]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Aborting an `abortSignal` that is passed to client (e.g. Lambda) calls as part of `__HttpHandlerOptions` does stop retries.

### SDK version number

@aws-sdk/client-lambda@3.357.0,@aws-sdk/node-http-handler@3.357.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.3.0

### Reproduction Steps

```js
const { Agent } = require('node:http');
const { Lambda} = require('@aws-sdk/client-lambda');
const { NodeHttpHandler } = require("@aws-sdk/node-http-handler");

(async () => {
  const signal = AbortSignal.timeout(2_000);

  const  l = new Lambda({
    region: 'us-west-2',
    maxAttempts: 7,
    endpoint: 'http://127.0.0.1/',
    requestHandler: new NodeHttpHandler({
      httpAgent: new Agent({}),
    }),
  });
  await l.invoke({
    FunctionName: 'test-fn',
  }, {
    abortSignal: signal,
  });
})();
```

### Observed Behavior

The following error is thrown after approximately 4 seconds.
```
Error [AbortError]: Request aborted
    at /node/node_modules/@aws-sdk/node-http-handler/dist-cjs/node-http-handler.js:66:36
    at new Promise (<anonymous>)
    at NodeHttpHandler.handle (/node/node_modules/@aws-sdk/node-http-handler/dist-cjs/node-http-handler.js:51:16)
    at /node/node_modules/@aws-sdk/client-lambda/dist-cjs/commands/InvokeCommand.js:38:58
    at /node/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:5:32
    at /node/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:26
    at async /node/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /node/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
    at async /node/index.js:16:3 {
  '$metadata': { attempts: 8, totalRetryDelay: 4475 }
}
```

### Expected Behavior

The `invoke` call to throw after 2 seconds (or whenever the `AbortSignal` is aborted).

### Additional Information/Context

The current AbortSignal usage is very strange compared to Go's `context.Context` and C#'s `CancellationToken`, where one would expect all processing to halt after the given timeout has passed.

**Comment by RanVaknin** [comment]
Hi @u873838 ,

Thanks for opening this issue. 

Like you have mentioned, the abortSignal passed down to the operation options is "ignored" by the retry middleware. This is because AbortError is defined as a retryable error which is an incorrect classification. 
Its important to note that the middleware will retry, however the actual API call will not be attempt by the handler since it recognized the abort. 

I will create a PR to declassify AbortError as a retryable error so this could be avoided.

Thanks,
Ran~
