### ISSUE TITLE
AbortSignal overwrites onabort rather than using addEventListener, preventing multiple use

### ISSUE THREAD

**Issue by u873838** [aws/aws-sdk-js-v3#4872]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The `AbortSignal` interface ([spec](https://dom.spec.whatwg.org/#interface-AbortSignal)) defines `AbortSignal` as extending the [EventTarget](https://dom.spec.whatwg.org/#eventtarget) interface, which provides the `addEventListener` method for defining event listeners.

When an `AbortSignal` is passed to client calls, the `onabort` method is used instead for signaling aborts. This is unexpected, as this behaves differently than standard functions that accept `AbortSignal` arguments. It also prevents the same `AbortSignal` from being used for simultaneous SDK calls.

### SDK version number

@aws-sdk/client-lambda@3.357.0,@aws-sdk/node-http-handler@3.357.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.3.0

### Reproduction Steps

```js
const { Agent } = require('node:http');
const { Lambda } = require('@aws-sdk/client-lambda');
const { NodeHttpHandler } = require("@aws-sdk/node-http-handler");
const express = require('express');

(async () => {
  const app = express();
  app.use('/delay', (req, res) => {
    setTimeout(() => {
      res.json({});
    }, 3_000);
  });

  await new Promise((resolve) => {
    app.listen(8080, '127.0.0.1', () => {
      resolve();
    });
  });

  const signal = AbortSignal.timeout(2_000);
  signal.addEventListener('abort', () => {
    console.log('outer abort handler 1');
  });

  const  l = new Lambda({
    region: 'us-west-2',
    maxAttempts: 1,
    endpoint: 'http://127.0.0.1:8080/delay',
    requestHandler: new NodeHttpHandler({
      httpAgent: new Agent({}),
    }),
  });
  console.log(await Promise.allSettled([
    l.invoke({
      FunctionName: 'test-fn',
    }, {
      abortSignal: signal,
    }),
    l.invoke({
      FunctionName: 'test-fn',
    }, {
      abortSignal: signal,
    }),
  ]));
})();
```

### Observed Behavior

```
outer abort handler 1
[
  {
    status: 'fulfilled',
    value: {
      '$metadata': [Object],
      Payload: [Uint8ArrayBlobAdapter [Uint8Array]],
      StatusCode: 200
    }
  },
  {
    status: 'rejected',
    reason: Error [AbortError]: Request aborted
        at node/node_modules/@aws-sdk/node-http-handler/dist-cjs/node-http-handler.js:66:36
        at new Promise (<anonymous>)
        at NodeHttpHandler.handle (node/node_modules/@aws-sdk/node-http-handler/dist-cjs/node-http-handler.js:51:16)
        at node/node_modules/@aws-sdk/client-lambda/dist-cjs/commands/InvokeCommand.js:38:58
        at node/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:5:32
        at node/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:26
        at async node/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
        at async node/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
        at async Promise.allSettled (index 1)
        at async node/index.js:33:15 {
      '$metadata': [Object]
    }
  }
]
```

### Expected Behavior

I expected both `.invoke` calls to fail with a "Request aborted" error.

### Possible Solution

Update the internal `AbortSignal` type to extend `EventTarget`, and use addEventListener throughout the SDK to register abort handlers.

**Comment by kuhe** [comment]
Using the latest AWS SDK and doing a fresh install overwriting any existing lockfiles to get version 3.1.0 of the `@smithy/node-http-handler` or `@smithy/fetch-http-handler` should enable the use of `addEventListener` for abortSignals.

**Comment by kuhe** [comment]
in a future update to the AWS SDK for JavaScript (v3), we will raise the minimum version of those http-handlers to bring in the fix automatically as well.
