### ISSUE TITLE
@aws-sdk/client-dynamodb should be a full dependency of @aws-sdk/util-dynamodb

### ISSUE THREAD

**Issue by jfirebaugh** [aws/aws-sdk-js-v3#4876]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

`@aws-sdk/util-dynamodb` lists `@aws-sdk/client-dynamodb` as a devDependency, but imports it in public type definition files, so it should be a full dependency.

This is similar to #4481 and #4482. Please consider fixing them holistically, so that this class of issue does not recur in other context.

### SDK version number

@aws-sdk/util-dynamodb@3.358.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.16.0

### Reproduction Steps

```
pnpm init
pnpm i @aws-sdk/util-dynamodb typescript
echo "hoist=false" >.npmrc
```

tsconfig.json:
```
{
  "compilerOptions": {
    "lib": ["es2018", "dom"],
  }
}
```

index.ts:
```
import * as UtilDynamoDB from "@aws-sdk/util-dynamodb"
```

Run `pnpm tsc`.

### Observed Behavior

```
node_modules/.pnpm/@aws-sdk+util-dynamodb@3.358.0/node_modules/@aws-sdk/util-dynamodb/dist-types/convertToAttr.d.ts:1:32 - error TS2307: Cannot find module '@aws-sdk/client-dynamodb' or its corresponding type declarations.

1 import { AttributeValue } from "@aws-sdk/client-dynamodb";
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/@aws-sdk+util-dynamodb@3.358.0/node_modules/@aws-sdk/util-dynamodb/dist-types/convertToNative.d.ts:1:32 - error TS2307: Cannot find module '@aws-sdk/client-dynamodb' or its corresponding type declarations.

1 import { AttributeValue } from "@aws-sdk/client-dynamodb";
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/@aws-sdk+util-dynamodb@3.358.0/node_modules/@aws-sdk/util-dynamodb/dist-types/marshall.d.ts:1:32 - error TS2307: Cannot find module '@aws-sdk/client-dynamodb' or its corresponding type declarations.

1 import { AttributeValue } from "@aws-sdk/client-dynamodb";
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Expected Behavior

Compiles successfully.

**Comment by kuhe** [comment]
in #5223 I'm moving it to peer first. We can move to a dependency later when doing the same for lib-dynamodb.
