### ISSUE TITLE
The S3.GetObject no longer returns the result as a string

### ISSUE THREAD

**Issue by priyalakshmiP** [aws/aws-sdk-js-v3#4881]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The S3.GetObject no longer returns the result as a string

### SDK version number

@aws-sdk/package-name@version, ...

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

NodeJS 18.x

### Reproduction Steps

https://github.com/aws/aws-sdk-js-v3/issues/1877

The S3.GetObject no longer returns the result as a string
Above is the previously opened issue. Tried the solution as per the above issue.

const streamToString = (stream) =>
    new Promise((resolve, reject) => {
      const chunks = [];
      stream.on("data", (chunk) => chunks.push(chunk));
      stream.on("error", reject);
      stream.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
    });

const s3Command = new GetObjectCommand({
      Bucket: art[0].location.s3Location.bucketName, 
      Key: art[0].location.s3Location.objectKey
    });

  const s3data = await s3cli.send(s3Command);
   //     console.log("s3data..."+JSON.stringify(Object.keys(s3data.Body)));

 
const bodyContents = await streamToString(s3data);
    console.log("bodyContents..."+bodyContents);

Receiving error "stream.on is not a function" 

Runtime: NodeJS runtime => 18.x which has a default AWS SK V3

### Observed Behavior

https://github.com/aws/aws-sdk-js-v3/issues/1877

Receiving error "Stream.on is not a function" 

Runtime: NodeJS runtime => 18.x which has a default AWS SK V3

### Expected Behavior

Should be able to get the data from S3

### Possible Solution

Need suggestion from the developer

### Additional Information/Context

Need suggestion from the developer

**Comment by yenfryherrerafeliz** [comment]
Hi @priyalakshmiP, sorry to hear about your issues. We have introduced a new feature that allows us to convert the body of a bucket's object to a string by doing the following:
```js
import {S3Client, GetObjectCommand} from "@aws-sdk/client-s3";

const client = new S3Client({
    region: 'us-east-2'
});
const response = await client.send(new GetObjectCommand({
    Bucket: process.env.TEST_BUCKET,
    Key: process.env.TEST_KEY
}));
console.log(await response.Body.transformToString('utf-8'));
```

This feature is available after version 3.357.

Thanks!

**Comment by priyalakshmiP** [comment]
@yenfryherrerafeliz 
A little background of functionality of our code.

During Source stage of code pipeline the source files are read from GitHub, zips it and the artifact is placed in S3.
During deployment stage of code pipeline, the zip file is read from S3 (using s3.getObject in V2), unzipped and processed.
The s3.getObject response type in AWS SDK V2 is a Buffer.

Tried below options for NodeJS 18.x runtime (AWS SDK V3):

Option 1: await s3Response.Body.transformToByteArray('utf-8')
          Resulted in Error "Invalid filename"

Option 2: Since the response type in V2 was a buffer tried converting the readable stream to buffer
   	      Installed npm package 'stream-to-buffer', included the package to project directory and added the below code

            const { S3Client, GetObjectCommand } = require("@aws-sdk/client-s3");  
            const streamToBuffer = require("stream-to-buffer");
            const s3cli = new S3Client({ region: "us-east-1" });
            
            const s3Command = new GetObjectCommand({
              Bucket: art[0].location.s3Location.bucketName, 
              Key: art[0].location.s3Location.objectKey
            });
            const s3Response = await s3cli.send(s3Command);
    	      const buffer = await streamToBuffer(s3Response);

    	    Resulted in Error "stream.on is not a function"

Option 3: Installed npm package 'stream', included the package to project directory and added the below code

  const { S3Client, GetObjectCommand } = require("@aws-sdk/client-s3");  
  const stream = require('stream');
  const s3cli = new S3Client({ region: "us-east-1" });
  
  function streamToBuffer(stream)
  {
    console.log("inside streamToBuffer method...");
    return new Promise((resolve,reject) => {
      const chunks = [];
      stream.on("data",(chunk) => chunks.push(chunk));
      stream.on("end",() => resolve(Buffer.concat(chunks)));
      stream.on("error",(error) => reject(error));
    });  
  }

  const s3Command = new GetObjectCommand({
    Bucket: art[0].location.s3Location.bucketName, 
    Key: art[0].location.s3Location.objectKey
  });
  const s3Response = await s3cli.send(s3Command);

  const buffer = await streamToBuffer(s3Response); 

  Resulted in Error "stream.on is not a function"

Option 4: Installed npm package 'stream', included the package to project directory and added the below code

const { S3Client, GetObjectCommand } = require("@aws-sdk/client-s3");  
const stream = require('stream');
const s3cli = new S3Client({ region: "us-east-1" });

function streamToBuffer(stream)
{
  return new Promise((resolve,reject) => {
    const chunks = [];
    stream.read = function ()
    {
      const chunk = this.read();
      if(chunk)
      {
        chunks.push(chunk);
        stream.read();
      }
      else
      {
        resolve(Buffer.concat(chunks));
      }
    };
    stream.read();
    stream.on("error", (error) => reject(error));
  });  
}

const s3Command = new GetObjectCommand({
  Bucket: art[0].location.s3Location.bucketName, 
  Key: art[0].location.s3Location.objectKey
});
const s3Response = await s3cli.send(s3Command);

const buffer = await streamToBuffer(s3Response); 

Resulted in Error "this.read is not a function"

**Comment by yenfryherrerafeliz** [comment]
@priyalakshmiP, if you need to have a body from the body then you need to do the following:

```js
const byteArray = await response.Body.transformToByteArray();
const buffer = Buffer.from(byteArray)
```

Here is a full example:
```js
import {S3Client, GetObjectCommand} from "@aws-sdk/client-s3";

const client = new S3Client({
    region: 'us-east-2'
});
const response = await client.send(new GetObjectCommand({
    Bucket: process.env.TEST_BUCKET,
    Key: process.env.TEST_KEY
}));
const byteArray = await response.Body.transformToByteArray();
const buffer = Buffer.from(byteArray)
```

This option is also available after version 3.357.0.

I hope this helps!

Thanks!

**Comment by priyalakshmiP** [comment]
@yenfryherrerafeliz - Do we have to import any npm package for the buffer ?

**Comment by priyalakshmiP** [comment]
@yenfryherrerafeliz 
Trying to get the ZipFile from S3. The ZipFile contains the files from GitHub

With V2, 
const data = await s3.getObject(params).promise(); 
const zip = new AdmZip(data.Body);
const zipEntries = zip.getEntries();

zipEntries has the entryName (GitHub files path) 

But with V3,
 const s3Response = await s3cli.send(s3Command);
 const chunks = [];
 for await (const chunk of s3Response.Body)   // process the object content in chunks
 {  
     console.log("Chunk..."+JSON.stringify(chunk));         
     chunks.push(chunk);    
 }
    console.log("Chunks..."+JSON.stringify(chunks));

chunks do not have the entryName (GitHub files path)
