### ISSUE TITLE
No matching version found for @aws-sdk/util-stream@3.360.0.

### ISSUE THREAD

**Issue by gabrielleandro0801** [aws/aws-sdk-js-v3#4890]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Hi
We're trying to install some libs from AWS but we're getting this error from the lib util-stream
![image](https://github.com/aws/aws-sdk-js-v3/assets/71289016/d0766731-7c86-43ca-b804-644deb8316e8)

The npm [page](https://www.npmjs.com/package/@aws-sdk/util-stream?activeTab=versions) shows it was released 19 hours ago

### SDK version number

@aws-sdk/client-dynamodb@3.254.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node v18.12.0

### Reproduction Steps

``` bash
npm i @aws-sdk/client-dynamodb@3.254.0
```

### Observed Behavior

NPM complains about the version 3.360.0 of the lib @aws-sdk/util-stream.

### Expected Behavior

We wanted the lib to be installed.

**Comment by RanVaknin** [comment]
Hi @gabrielleandro0801 ,

Can you please be more specific on how you are seeing this error? 

> npm i @aws-sdk/client-dynamodb@3.254.0

This is a much older release, and I have no problem installing it.

Same goes to util-stream:

```console
$ npm i @aws-sdk/util-stream                                                                                                                                                                                   

added 14 packages, and audited 15 packages in 375ms

found 0 vulnerabilities

$ npm list
4890@1.0.0 /Users/rvaknin/test_folder/4890
└── @aws-sdk/util-stream@3.360.0
```

Can you better articulate what seems to be the problem and under which conditions it is happening? 

Additionally, you might want to delete your `package.json` and `node_modules` and reinstall your dependencies.

Thanks,
Ran~

**Comment by gabrielleandro0801** [comment]
Hi, @RanVaknin

I think we can close this issue now. Now I'm able to install this and other AWS libs.
For some reason, yesterday I couldn't install, where I was having this error. Somehow it is working perfectly today.

Thank you :smile:
