### ISSUE TITLE
Does not retry when download s3 using readable streams

### ISSUE THREAD

**Issue by jponc** [aws/aws-sdk-js-v3#4897]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I'm trying to do the following:
1. download 50-100 different files (via streams)
2. appending the body readable stream to [archiver](https://www.npmjs.com/package/archiver)
3. archiver zips it on the fly and pipes it to a stream passthrough
4. stream passthrough is my Body input for PutObjectCommand (to another s3 bucket).

Looks like AWS is terminating idle the connection after 5 minutes (this is possible since perhaps archiver hasn't reached the last remaining streams to download).

So all I want is for s3client to retry the connection when receiving `ECONNRESET`.

By the way I'm also running this in lambda. Here's the sample error thrown:

```
2023-06-29T11:04:41.991Z	bd9c0236-c515-52dc-ad83-5f21a32e4bfe	INFO	Error: aborted
    at connResetException (node:internal/errors:717:14)
    at TLSSocket.socketCloseListener (node:_http_client:462:19)
    at TLSSocket.emit (node:events:525:35)
    at node:net:322:12
    at TCP.done (node:_tls_wrap:588:7) {
  code: 'ECONNRESET'
}
```

### SDK version number

@aws-sdk/client-s3@^3.362.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

NodeJS 18

### Reproduction Steps

```typescript
import * as Archiver from "archiver";
import { Readable } from "stream";
import { S3Client, GetObjectCommand } from "@aws-sdk/client-s3";
import { Stream } from "stream";
import { Upload } from "@aws-sdk/lib-storage";
import { NodeHttpHandler } from "@aws-sdk/node-http-handler";
import { Agent } from "https";

const streamPassThrough = new Stream.PassThrough();

const region = "ap-southeast-2";
const keysToZip = ["file1.mov", "file2.mov"];
const outputKey = "myzip.zip"
const sourceBucket = "source-bucket"
const outputBucket = "output-bucket"

const run = async () => {


  const s3Client = new S3Client({
    region: region,
    requestHandler: new NodeHttpHandler({
      httpsAgent: new Agent({
        keepAlive: true,
      }),
    }),
  });

  const archive = Archiver("zip", { zlib: { level: 6 } });
  archive.pipe(streamPassThrough);

  // This gets readable streams from s3
  const s3FileDwnldStreams = await Promise.all(
    keysToZip.map(async (key) => {
      const getObjectCommand = new GetObjectCommand({
        Bucket: sourceBucket,
        Key: key,
      });

      const item = await s3Client.send(getObjectCommand);
      if (!item.Body) {
        throw new Error(`s3 item body not found for key: ${key}`);
      }

      // Get readable stream from s3 object to download
      const stream = item.Body as Readable;

      const tokens = key.split("/");
      const fileName = tokens[tokens.length - 1];

      return {
        stream,
        fileName,
      };
    })
  );

  // Attach readable streams into archive
  s3FileDwnldStreams.forEach((s3FileDwnldStream) => {
    archive.append(s3FileDwnldStream.stream, {
      name: s3FileDwnldStream.fileName,
    });
  });
  archive.finalize();

  // initialize uploader
  const uploader = new Upload({
    client: s3Client,
    params: {
      Bucket: outputBucket,
      Body: streamPassThrough,
      Key: `${Date.now()}-${outputKey}`,
      ContentType: "application/zip",
    },
    partSize: 100 * 1024 * 1024, // Set partSize to 100MB
  });

  await uploader.done();
};

run().then(() => console.log("done")).catch((err) => console.log(err))
```

### Observed Behavior

It does not ertry on `ECONNRESET`

### Expected Behavior

Should retry

**Comment by RanVaknin** [comment]
Hi @jponc ,

[`ECONNRESET`](https://github.com/aws/aws-sdk-js-v3/blob/d036e2e43cd33cfd497871f97dde907c3078b2fd/packages/service-error-classification/src/constants.ts#L52)`](https://github.com/aws/aws-sdk-js-v3/blob/d036e2e43cd33cfd497871f97dde907c3078b2fd/packages/service-error-classification/src/constants.ts#L52) is defined as a retryable error so it should be retried. 
I will write up some sample repro to test this and get back to you. 

Thanks,
Ran~

**Comment by RanVaknin** [comment]
Hi @jponc ,

I was not able to force the SDK to throw an ECONNRESET intentionally, mocking networking layer errors is difficult, but I'm not convinced that your assumption is correct.

See [this older issue](https://github.com/aws/aws-sdk-js-v3/issues/4045#issue-1410499931) and [this one ](https://github.com/aws/aws-sdk-js-v3/issues/3905)
>It does not ertry on ECONNRESET

Your print statement should print something similar to this:

```console
Error: connect ECONNREFUSED ::1:5050
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1532:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 5050,
  '$metadata': { attempts: 3, totalRetryDelay: 245 }
```

With the retry attempts printed in the metadata below to show the SDK is retrying ECONNRESET as it is a transient error.

In your original description, the error pasted mentiones `Error: aborted
    at connResetException (node:internal/errors:717:14)`.
 
To me this seems that the S3 services closed the connection early, perhaps because of the long idle time.
You can try and increase the timeout to the max (15min) and see if this solves your issue.


Thanks,
Ran~

**Comment by jponc** [comment]
Thanks @RanVaknin , yeah not sure what's going on on my end, but yeah it seems that it's not retrying.. I actually found out the issue - I have an open socket connection to AWS, that has been sitting idle for 5 minutes, then AWS closes the connection hence getting `ECONNRESET`.

I've restructured my code so instead of opening up all sockets at once, I just open it when I need it. Anyway thanks heaps for looking into it cheers 🎉

**Comment by BillyLevin** [comment]
Hi @jponc are you able to share how you fixed this issue? I think I'm having the exact same problem

**Comment by jponc** [comment]
Are you also trying to use `archiver` NPM package? My error is mainly related to the sockets being idle for 5 minutes, hence AWS server terminates it.

So what I ended up doing is to only open the socket connection when I'm ready to consume the data.

```typescript
      const archive = Archiver("zip", { zlib: { level: 9 } });
      archive.pipe(streamPassThrough);

      const queue: QueueItem[] = keysToZip.map((key) => {
        const tokens = key.split("/");
        const fileName = tokens[tokens.length - 1];

        return {
          fileName,
          key,
        };
      });

      const MAX_CONCURRENCY = 3;

      const finalize = (err) => {
        if (err) {
          throw new Error(`finalise error ${err}`);
        }

        archive.finalize();
      };

      async.eachLimit(
        queue,
        MAX_CONCURRENCY,
        async (queueItem, next) => {
          console.log(`Processing: ${queueItem.fileName}`);
          const getObjectCommand = new GetObjectCommand({
            Bucket: this.sourceBucket,
            Key: queueItem.key,
          });

          const item = await s3Client.send(getObjectCommand);
          if (!item.Body) {
            throw new Error(`s3 item body not found for key: ${queueItem.key}`);
          }

          // Get readable stream from s3 object to download
          const stream = item.Body as Readable;

          stream.on("end", next);
          archive.append(stream, { name: queueItem.fileName });
        },
        finalize
      );
```

**Comment by BillyLevin** [comment]
@jponc Yes I'm using `archiver` to do the same thing you're doing - stream a zip to S3. Thanks a lot for posting your solution, I'll try this out!
