### ISSUE TITLE
Recent reordering of marshall function overload signatures returns incorrect signature

### ISSUE THREAD

**Issue by jeremydaly** [aws/aws-sdk-js-v3#4901]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The change made in commit cb4a0e3 incorrectly reorders the overload that returns `AttributeValue[]` type instead of `Record<string, AttributeValue>` when passing in a JavaScript object to be marshalled.

### SDK version number

@aws-sdk/util-dynamodb@3.363.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.15.0

### Reproduction Steps

```typescript
import { marshall } from '@aws-sdk/util-dynamodb';

const data = {
  pk: 'abc',
  sk: 'xyz'
}

const ExpressionAttributeValues = marshall(data);

```

### Observed Behavior

The code above assigns `ExpressionAttributeValues` a type of `AttributeValue[]`.

### Expected Behavior

`ExpressionAttributeValues` should be assigned a type of `Record<string, AttributeValue>`.

### Possible Solution

Swap the two overload signatures so that the one returning `Record<string, AttributeValue>` takes precedence. Otherwise this breaks a lot of existing implementations.

**Comment by kuhe** [comment]
it's possible the object was typed as `any` in code not shown, which matches array signatures
