### ISSUE TITLE
Breaking change regarding CredentialsProviderError in v3.363.0

### ISSUE THREAD

**Issue by paavohuhtala** [aws/aws-sdk-js-v3#4907]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The error class `CredentialsProviderError ` was moved from `@aws-sdk/property-provider` to `@smithy/property-provider` in SDK v3.363.0, which broke `instanceof` checks using the type. This was not documented in the changelog, and I noticed this only by reading the SDK source code (using Renovate's [generated version diff](https://app.renovatebot.com/package-diff?name=@aws-sdk%2fcredential-provider-sso&from=3.362.0&to=3.363.0)).

### SDK version number

@aws-sdk/credential-provider-sso@3.363.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.16.1

### Reproduction Steps

This requires some setup to actually reproduce, but the basic idea is this:

```typescript
// Version 3.363.0
import { STS } from '@aws-sdk/client-sts'
// Version 3.357.0
import { CredentialsProviderError } from '@aws-sdk/property-provider'

// In a function or in an environment with top-level async/await support
try {
  const sts = new STS({})
  await sts.getCallerIdentity({})
} catch (e: unknown) {
  if (e instanceof CredentialsProviderError) {
    console.log("Login out of date, please renew SSO session")
  } else {
    console.error("Unknown error when getting caller identity", e)
  }
}
```

### Observed Behavior

We are using `instanceof` checks with the error class `CredentialsProviderError` in our SSO login handling code to detect when an SSO session needs to be renewed in local development. `instanceof` [is the recommended way](https://aws.amazon.com/blogs/developer/service-error-handling-modular-aws-sdk-js/) to handle errors in AWS SDK v3. An automatic version update broke our SSO handling, because there are now two different instances of `CredentialsProviderError` in two separate packages. `@aws-sdk/property-provider` was presumably deprecated in the same release (or earlier) as well, but it's not mentioned in the changelog.

Admittedly, [on NPM](https://www.npmjs.com/package/@aws-sdk/property-provider) the package is documented as "An internal package" and that "You probably shouldn't [use this], at least directly", but I would argue thrown exceptions are absolutely a part of the public interface of the SDK (especially with the aforementioned recommendation to use `instaceof`), and therefore should be included in changelog notices.

### Expected Behavior

I expected one or some of this things:
- I expected this not to be changed in a minor release, because it's a breaking change (though since AWS SDK v3 doesn't use semver I guess anything goes)
- But if the change had to be done, I would have appreciated if `@aws-sdk/property-provider` remained available for at least one more version and would re-export the new class type to maintain backwards compatibility, most likely with a deprecation warning or even hard error to help people migrate to the new package.
- In any case, I expected changes like this to be documented in the changelog.

### Possible Solution

For folks using the SDK, the solution is to remove the dependency to `@aws-sdk/property-provider`, add `@smithy/property-provider` and update the related import(s).

For AWS, there are many things that could be done:

- Update the changelog to document the change.
- Even better, you could release a version of `@aws-sdk/property-provider` which comes with a deprecation notice for all users that are still using it.
- Ideally, I'd expect there to be a clear policy that error / exception classes are considered a part of the public interface of the SDK and not hidden in "internal" packages, because catching and `instanceof` checking the errors is the recommended (and only) way to handle errors with the SDK.
- Implement some mechanism to detect that multiple different versions of SDK packages are being used, and provide a warning / error on import or when clients are created.

**Comment by RanVaknin** [comment]
Hi @paavohuhtala ,

Thanks for raising this important issue. I have brought this to the team and after discussing it, we have decided to export `CredentialsProviderError` out of the internal package to avoid issues of this sort coming up in the future.

We are also looking into re-exporting `property-provider` so that it will import the dependency from smithy-typescript automatically and prevent folks from needing to change their import structure.

Please keep an eye on our upcoming releases for this fix.

Thanks again,
Ran~

**Comment by kuhe** [comment]
fix released in this version: https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.366.0
