### ISSUE TITLE
Type 'MicrophoneStream' must have a '[Symbol.asyncIterator]()' method that returns an async iterator

### ISSUE THREAD

**Issue by stevensu1977** [aws/aws-sdk-js-v3#4921]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I use example from readme , 

 import MicrophoneStream from 'microphone-stream';

code :
```js
  const micStream = new MicrophoneStream();
    // // this part should be put into an async function
    
    micStream.setStream(
    await window.navigator.mediaDevices.getUserMedia({
        video: false,
        audio: true,
    })
    );
    const audioStream = async function* () {
    for await (const chunk of micStream) {
        yield { AudioEvent: { AudioChunk: pcmEncodeChunk(chunk) /* pcm Encoding is optional depending on the source */ } };
    }
    };
```
but "for await (const chunk of micStream)" get error message:

Type 'MicrophoneStream' must have a '[Symbol.asyncIterator]()' method that returns an async iterator

### SDK version number

@aws-sdk/client-transcribe-streaming: "^3.363.0"

### Which JavaScript Runtime is this issue in?

Browser

### Details of the browser/Node.js/ReactNative version

Chrome: 114.0.5735.198

### Reproduction Steps

N/A

### Observed Behavior

N/A

### Expected Behavior

N/A

**Comment by yenfryherrerafeliz** [comment]
Hi @stevensu1977, sorry to hear about your issues. Could you please clarify if this issue happens when doing any operation with the SDK?, because MicrophoneStream is not part of the SDK itself. By looking at your code I presume that probably you should treat MicrophoneStream as readable stream, and by doing so you can use the event listener to listen for new chunk of data as follow:

```js
const micStream = new MicrophoneStream();
// // this part should be put into an async function

micStream.setStream(
    await window.navigator.mediaDevices.getUserMedia({
        video: false,
        audio: true,
    })
);
const audioStream = async function* () {
    micStream.on('data', (chunk) => {
        yield { AudioEvent: { AudioChunk: pcmEncodeChunk(chunk) /* pcm Encoding is optional depending on the source */ } };
    })
};
```

But again since MicrophoneStream is not part of the SDK this is just a suggestion.

I hope this helps!

Thanks!
