### ISSUE TITLE
Missing QueryCommand

### ISSUE THREAD

**Issue by ashtonm1** [aws/aws-sdk-js-v3#4923]
### Describe the issue

The new documentation features the CancelQueryCommand twice but does not have the QueryCommand

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/timestream-query/

**Comment by RanVaknin** [comment]
Thanks for letting us know. This does seem like a bug in the documentation. 

I'll assign it to our backlog.

Thanks,
Ran~

**Comment by MYoung25** [comment]
Good find, thanks for bringing it to our attention.  QueryCommand is documented https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-timestream-query/Class/QueryCommand/ but it _is_ also supposed to be on the page you linked.

I will take a look into why this is occurring.

Best,

Michael

**Comment by ashtonm1** [comment]
Thanks for having a look and thanks for the link to QueryCommand.

Cheers,

Ashton

**Comment by MYoung25** [comment]
Once again, thanks for bringing this up.

I was able to find and fix the root cause, it should be released by end of week!  I'm going to mark this as closing soon, if you continue to see it, please reopen/remove the tag
