### ISSUE TITLE
Invalid types for PutObjectCommandInput / PutObjectCommand body

### ISSUE THREAD

**Issue by theDanielJLewis** [aws/aws-sdk-js-v3#4930]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

`PutObjectCommand`'s `Body` param is of type PutObjectCommandInput, which claims to accept `string | Blob | Uint8Array | Readable | ReadableStream<any> | Buffer | undefined`.

However, put a Blob in there and you'll get this error:

> TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Blob.

Okay, so string, Buffer, ArrayBuffer, Array, or an Array-like object are acceptable?

So if I give `body` an ArrayBuffer, then I get this TypeScript error in dev and build:

> Type error: Type 'ArrayBuffer' is not assignable to type 'string | Uint8Array | Readable | Buffer | Blob | ReadableStream<any> | undefined'.
  Type 'ArrayBuffer' is missing the following properties from type 'Buffer': write, toJSON, equals, compare, and 96 more.

So I just can't win!

### SDK version number

@aws-sdk/client-s3@^3.363.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node. or 20.4.0

### Reproduction Steps

```js
async function uploadFile({ filename, fileContent }) { // Filecontent is a dataURL
  const blob = dataURLtoBlob(fileContent);
  var arrayBuffer = await blob.arrayBuffer();
  const params: PutObjectCommandInput = {
    Bucket: "MY_BUCKET", 
    Key: filename, 
    Body: blob, // or arrayBuffer
  try {
    const results = await s3Client.send(new PutObjectCommand(params));
    console.log(
      "Successfully created " +
        params.Key +
        " and uploaded it to " +
        params.Bucket +
        "/" +
        params.Key
    );
    return results; // For unit tests.
  } catch (err) {
    console.log("Error", err);
  }
}
```

### Observed Behavior

Error messages above.

A type like ArrayBuffer will successfully upload, but build fails. A type like Blob is supposedly supported according to the type, but the upload will fail.

### Expected Behavior

I expect the types to match and not get an error.

### Possible Solution

Either update the types, or update what can be uploaded.

**Comment by theDanielJLewis** [comment]
Thanks for the response!

As an early developer, it would really help if there was consistency in these type bindings within the code, not only buried in the documentation (which is already hard enough to search and missing a lot).

**Comment by RanVaknin** [comment]
Hi @theDanielJLewis ,

Thanks for the feedback. If you are using a modern IDE, the documentation will appear on the tooltip when you'll start writing PutObjectCommand(.. and it will show the function signature with the suggested inputs. 

>the documentation (which is already hard enough to search and missing a lot).

If you have specific advice on how to make the docs better, feel free to submit a documentation issue and propose changes. 

At any rate, I'm glad it now works. 
All the best,
Ran~
