### ISSUE TITLE
PutBucketCorsCommand always throw MalformedXML

### ISSUE THREAD

**Issue by maha-saad** [aws/aws-sdk-js-v3#4931]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

PutBucketCorsCommand throw this error 
 **MalformedXML: The XML you provided was not well-formed or did not validate against our published schema.**

### SDK version number

@aws-sdk/client-s3@3.354.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node v14.20.1

### Reproduction Steps

```js
async createBucket() {
	const command = new CreateBucketCommand({ Bucket: this._bucketName, ACL: BucketCannedACL.private });
	await this._s3Client.send(command);

	const corsCommand = new PutBucketCorsCommand({
		Bucket: this._bucketName,
		CORSConfiguration: {
			CORSRules: [
				{
					AllowedHeaders: ["*"],
					AllowedMethods: ['GET', 'PUT', 'HEAD', 'POST'],
					AllowedOrigins: ["*"],
					ExposeHeaders: ["ETag"],
					MaxAgeSeconds: 5000
				}
			]
		}
	});
	await this._s3Client.send(corsCommand);
}
```

### Observed Behavior

PutBucketCorsCommand throw this error 
 **MalformedXML: The XML you provided was not well-formed or did not validate against our published schema.**

### Expected Behavior

pass successfully and set cors configuration to the bucket

**Comment by yenfryherrerafeliz** [comment]
Hi @maha-saad, sorry to hear about your issues. I just tried to reproduce the reported behavior but I was not able to.
Here is the piece of code that I used:
```js
import { S3Client, PutBucketCorsCommand } from "@aws-sdk/client-s3";

const client = new S3Client({
    region: process.env.TEST_REGION,
});
const cmd = new PutBucketCorsCommand({
    Bucket: process.env.TEST_BUCKET,
    CORSConfiguration: {
        CORSRules: [
            {
                AllowedHeaders: ["*"],
                AllowedMethods: ["GET", "PUT", "HEAD", "POST"],
                AllowedOrigins: ["*"],
                ExposeHeaders: ["ETag"],
                MaxAgeSeconds: 5000
            }
        ]
    }
});
const response = await client.send(cmd);

console.log(response)
```

Response:
```console
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'REDACTED',
    extendedRequestId: 'REDACTED',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}

```

However, could you please make sure all your sdk dependencies are updated, and if so, could you please enable debug logs and provide those logs here so we can investigate this further. To enable debug logs you just need to pass an object implementing the desired level method, in the logger parameter of the client as follow:

```js
const client = new S3Client({
    region: process.env.TEST_REGION,
    logger: {
        error: (log) => {
            console.log('Error: ', log)
        }
    }
});
```

Note: Please redact any sensitive information.

Thanks!

**Comment by maha-saad** [comment]
thanks @yenfryherrerafeliz for your response, I caught the issue
I'm using this dockerized s3 image `minio/minio` for development before deployment, so I didn't test the behavior on actual aws s3.

Now when I tried on aws it works fine, so the issue wasn't in library, it seems related to minio image

Thank you
