### ISSUE TITLE
All the paginate* functions names end with 1 in the documentation

### ISSUE THREAD

**Issue by dnafication** [aws/aws-sdk-js-v3#4936]
### Describe the issue

All the function names that begins with paginate has 1 at the end. 😂 

![image](https://github.com/aws/aws-sdk-js-v3/assets/6381587/3eea3018-a913-4b2f-a3fe-5c5a408d0b4b)
![image](https://github.com/aws/aws-sdk-js-v3/assets/6381587/d87a40ee-1d8e-4347-a9c6-e02158b1d779)

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-cloudformation/
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-cloudformation/Function/paginateListExports1/

**Comment by RanVaknin** [comment]
Hi @dnafication ,

Thanks for opening this issue. I'll have someone take a look.

All the best,
Ran~

**Comment by MYoung25** [comment]
Thanks for letting us know, this was caused by the migration to `@smithy/*` packages.  I have identified a fix and it _should_ become available by Tuesday.

I'm adding a closing soon tag to auto close this issue in a few days.

Best,

Michael
