### ISSUE TITLE
DynamoDB Client UpdateItemCommand -- Inaccurate Error Message

### ISSUE THREAD

**Issue by offscriptdev** [aws/aws-sdk-js-v3#4939]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Attempting to use the `DELETE` expression on an existing attribute that is not of type `SS` will result in an error with a misleading message.

### SDK version number

@aws-sdk/client-dynamodb@3.363.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node v18.16.0

### Reproduction Steps

```TypeScript
// service.dynamodb.ts
import {DynamoDBClient, DynamoDBClientConfig} from '@aws-sdk/client-dynamodb'

const clientConfig: DynamoDBClientConfig = {
  region: process.env.DYNAMO_REGION,
  endpoint: process.env.DYNAMO_ENDPOINT,
}

const client = new DynamoDBClient(clientConfig)

export default client
```

```TypeScript
// putItem.dynamodb.ts
import client from './service.dynamodb.js'
import {PutItemCommand} from "@aws-sdk/client-dynamodb";

export async function putItem() {
    const command = new PutItemCommand({
        TableName: 'testTable',
        Item: {
            'id': {
                S: 'uniqueItemId'
            },
            'stringSet': {
                S: 'one' // incorrectly use S when we should use SS 
            }
        }
    })
    await client.send(command)
}
```

```TypeScript
// updateItem.dynamodb.ts
import client from './service.dynamodb.js'
import {UpdateItemCommand} from "@aws-sdk/client-dynamodb";

export async function updateItem() {
    const command = new UpdateItemCommand({
        TableName: 'testTable',
        Key: {
            'id': {
                S: 'uniqueItemId'
            }
        },
        ExpressionAttributeNames: {
            "#stringSet": 'stringSet'
        },
        ExpressionAttributeValues: {
            ':stringSet': {
                SS: ['one']
            }
        },
        UpdateExpression: "DELETE #stringSet :stringSet"
    })
    await client.send(command)
}
```

```TypeScript
// index.dynamodb.ts
import {putItem} from "./putItem.dynamodb.js";
import {updateItem} from "./updateItem.dynamodb.js";

await putItem()
await updateItem()
```

`node ./index.dynamodb.js`

### Observed Behavior

ValidationException: **An operand in the update expression has an incorrect data type**
    at throwDefaultError (/xtr/code/offscriptdev/dynamodb/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at /xtr/code/offscriptdev/dynamodb/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:18:39
    at de_UpdateItemCommandError (/xtr/code/offscriptdev/dynamodb/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:2511:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /xtr/code/offscriptdev/dynamodb/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /xtr/code/offscriptdev/dynamodb/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20
    at async /xtr/code/offscriptdev/dynamodb/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /xtr/code/offscriptdev/dynamodb/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
    at async updateItem (file:///xtr/code/offscriptdev/dynamodb/build/dynamodb/updateItem.js:21:20)
    at async file:///xtr/code/offscriptdev/dynamodb/build/app.js:6:1 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: 'c03d1d5e-19c5-4f2f-89f6-c7d894b63178',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  __type: 'com.amazon.coral.validate#ValidationException'
}

### Expected Behavior

It would have saved a lot of time if the error for this was instead something like, "The DELETE update expression can only be used on an item with a SS attribute, and the attribute you were trying to update was of type S"

### Possible Solution

I'd need to dig into the sdk to pinpoint where the error handling could be improved. If no one grabs this issue, I'd be willing to do this for my own sanity.

### Additional Information/Context

The issue with this error is that it points to the update expression as being the problem, but the update expression is correctly formed. This incorrect/misleading error lead me to waste a lot of time trying to wrangle the update expression into an acceptable format. If I had known to look towards the item itself, my troubleshooting time would have been significantly lower.

To be a bit more specific, the term `operand in the update expression` is what really threw me for a loop. The update expression was `DELETE #stringSet :stringSet` and thus I assumed the operands were the instructions I had programmed into `#stringSet` and  `:stringSet`.

**Comment by RanVaknin** [comment]
Hi @offscriptdev,

Thanks for raising this issue, I'm sorry to hear that you were having trouble root causing the issue with the update statement. 

What you are witnessing is a server side error not an SDK error. 
Unlike SDK validation errors that the SDK can throw for something like missing fields in a request, Service side errors
can be identified by the `httpStatusCode` and the `requestId` field and , these identifiers are given by the server to all round-tripped requests.

Since the source of the error is the service itself, unfortunately there is no action the SDK team can take.

Thanks again,
Ran~
