### ISSUE TITLE
ListObjectsCommandInput marker type is only string (should be also undefined)

### ISSUE THREAD

**Issue by shirady** [aws/aws-sdk-js-v3#4940]
### Describe the issue

Hello,
In `ListObjectsCommandInput`
`Marker` type is a `string`, but since it is typescript it should be also `undefined` (should appear in the doc as Bucket parameter: `Bucket string \ undefined`.
Using `undefined` in the marker is crucial for iterating the bucket with a loop in order to list all the keys.

### Links

Here is the link to your documentation:
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-s3/Class/ListObjectsCommand/

**Comment by RanVaknin** [comment]
Hi @shirady ,

Thanks for raising the issue. I'm not sure why `Marker` being undefined is necessary here. Marker is used for paginated requests and doesn't need to be supplied when you are not paginating through responses. 

Can you write a simple example that can highlight the need for this?

**Comment by shirady** [comment]
HI @RanVaknin,
Here is an example (taken from [here](https://github.com/noobaa/noobaa-core/blob/9821946bd4b68e7611ea57f07bfef708e05dab16/src/lambda_funcs/copy_between_bucket.js#L67-L84)):

```
async function list_all(s3, bucket) {
...
    let truncated = true;
    let marker; // undefined by default

    while (truncated) {
        const list = await s3.listObjects({ Bucket: bucket, Marker: marker }).promise();
         ...
        truncated = list.IsTruncated;
        marker = list.NextMarker;
    }
...
}
```
It uses AWS SDK V2, I wish to do the migration to AWS SDK V3 with minimal code changes.

**Comment by RanVaknin** [comment]
Hi @shirady the example you shared seems like an example on how to implement a paginator yourself, and is a private repo not owned by AWS. 

In v3 paginatable operations have defined paginator functions that you should take advantage of, instead of implementing your own.

So to listObjects you can use:

```js
import { S3Client, paginateListObjectsV2 } from "@aws-sdk/client-s3";

const client = new S3Client({ region: "us-east-1" });


const paginator = paginateListObjectsV2({ client }, {
    Bucket: "testbucket",
  });

async function run(){
    for await (const page of paginator) {
        for (const object of page.Contents || []) {
          console.log(object.Key);
        }
      }
}
run()
```

Let me know if this is helpful,

Thanks,
Ran~

**Comment by shirady** [comment]
Hi @RanVaknin,
Your suggestion is about `ListObjectsV2` and I asked about `ListObjects` (the older version).
As I said, I wish to make minor code changes while migrating from AWS SDK V2 to AWS SDK V3.
Anyway, maybe the example could be useful sometime, thank you.

**Comment by RanVaknin** [comment]
Hi @shirady ,

Im not sure what the advantage of using the older listObjects command with a handwritten paginator when you have a v2 of that same command (gives you the same output + more data) and added support for built in pagination? 

>I wish to make minor code changes while migrating from AWS SDK V2 to AWS SDK V3.
ok:

Same code using v3:

```js
import { S3Client, ListObjectsCommand } from "@aws-sdk/client-s3";

async function list_all(s3, bucket) {
    const objects_map = new Map();
    let truncated = true;
    let marker;

    while (truncated) {
        const response = await s3.send(new ListObjectsCommand({
            Bucket:bucket,
            Marker: marker
        }))
        if (response.Contents && response.Contents.length) {
            for (const obj of response.Contents) {
                objects_map.set(obj.Key, obj);
            }
        }
        truncated = response.IsTruncated;
        marker = response.NextMarker;
    }
    console.log(objects_map)
    return objects_map;
}
```

Thanks,
Ran~
