### ISSUE TITLE
Cannot find module '@smithy/abort-controller' in @aws-sdk/lib-storage@3.367.0

### ISSUE THREAD

**Issue by WhiteKiwi** [aws/aws-sdk-js-v3#4942]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

```
    Cannot find module '@smithy/abort-controller' from '../../node_modules/.pnpm/@aws-sdk+lib-storage@3.367.0_@aws-sdk+client-s3@3.367.0/node_modules/@aws-sdk/lib-storage/dist-cjs/Upload.js'
```
![image](https://github.com/aws/aws-sdk-js-v3/assets/32415680/f359e36b-f65c-49a2-82b2-e49f0c845c2c)

### SDK version number

@aws-sdk/lib-storage@3.367.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.16.0

### Reproduction Steps

Install and import '@aws-sdk/lib-storage@3.367.0'

### Observed Behavior

Cannot find module '@smithy/abort-controller'

### Expected Behavior

Find module '@smithy/abort-controller'

### Possible Solution

Add '@smithy/abort-controller' in 'devDependencies' to the 'dependencies'

**Comment by yenfryherrerafeliz** [comment]
Hi @WhiteKiwi, sorry to hear about your issues. "@smithy/abort-controller" is indeed a dev dependency of @aws-sdk/lib-storage, which can be confirmed [here](https://github.com/aws/aws-sdk-js-v3/blob/6dd73dda712bf53c2b11f9a3b16ab43145214871/lib/lib-storage/package.json#L40). I am also not able to reproduce this issue on my end. Can you please make sure your dependencies are up to date?, could you please maybe try deleting the package-lock.json file?, and see if that fixes the problem. 

Thanks!

**Comment by WhiteKiwi** [comment]
Hi! 
I have confirmed that this issue is occurring only in pnpm.

First, devDependencies is not a dependency that is installed after the library is deployed.
For '@aws-sdk/lib-storage', it can be used as a phantom dependency at npm because it relies on '@smithy/abort-controller' in its sub-packages.
However, pnpm does not allow phantom dependencies, so only the dependencies specified in package.json's dependencies are accessible in the package.


You can recreate it in the repo below.
https://github.com/WhiteKiwi/issues/tree/aws-sdk-js-v3/4942

My English is not good enough at English. If there's anything you don't understand, please comment.
Thank you for reading it.

**Comment by yenfryherrerafeliz** [comment]
@WhiteKiwi thanks for this information. Your English is perfect, so do not worry. I will investigate this further and I will get back to you as soon as possible.

Thanks!

**Comment by minidonut** [comment]
I've got same issue +1
