### ISSUE TITLE
getSignedUrl is not working with Typescript Version 4.9.5 #4451

### ISSUE THREAD

**Issue by BrenoMazieiro** [aws/aws-sdk-js-v3#4950]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Getting error as Argument of type 'S3Client' is not assignable to parameter of type 'Client<any, ServiceInputTypes, MetadataBearer, any> while using getSignedUrl() function in typescript@4.9.5

### SDK version number

@aws-sdk/s3-request-presigner": "3.369.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.16.0

### Reproduction Steps

```js
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import { GetObjectCommand, GetObjectRequest, S3Client} from "@aws-sdk/client-s3";

export const getsignedUrl = async (params: GetObjectRequest) => {
    try {
        const command = new GetObjectCommand(params)
        const client = new S3Client({
            region: process.env.TEST_REGION
        })
        const signedUrl = await getSignedUrl(client, command, { expiresIn: 15 * 60 });
        return signedUrl
    } catch (err: any) {
        console.log('Error Genrating Signed URL: ', err);
        throw new Error(err?.message || 'Error Generating Signed URL')
    }
}
```

### Observed Behavior

Argument of type 'S3Client' is not assignable to parameter of type 'Client<any, ServiceInputTypes, MetadataBearer, any>'.
  The types of 'middlewareStack.concat' are incompatible between these types.
    Type '<InputType extends ServiceInputTypes, OutputType extends ServiceOutputTypes>(from: MiddlewareStack<InputType, OutputType>) => MiddlewareStack<...>' is not assignable to type '<InputType extends ServiceInputTypes, OutputType extends MetadataBearer>(from: MiddlewareStack<InputType, OutputType>) => MiddlewareStack<InputType, OutputType>'.
      Types of parameters 'from' and 'from' are incompatible.
        Type 'MiddlewareStack<InputType, OutputType>' is not assignable to type 'MiddlewareStack<InputType, ServiceOutputTypes>'.
          Types of property 'addRelativeTo' are incompatible.
            Type '(middleware: MiddlewareType<InputType, OutputType>, options: RelativeMiddlewareOptions) => void' is not assignable to type '(middleware: MiddlewareType<InputType, ServiceOutputTypes>, options: RelativeMiddlewareOptions) => void'.
              Types of parameters 'middleware' and 'middleware' are incompatible.
                Type 'MiddlewareType<InputType, ServiceOutputTypes>' is not assignable to type 'MiddlewareType<InputType, OutputType>'.
                  Type 'InitializeMiddleware<InputType, ServiceOutputTypes>' is not assignable to type 'MiddlewareType<InputType, OutputType>'.
                    Type 'InitializeMiddleware<InputType, ServiceOutputTypes>' is not assignable to type 'InitializeMiddleware<InputType, OutputType>'.
                      Call signature return types 'InitializeHandler<InputType, ServiceOutputTypes>' and 'InitializeHandler<InputType, OutputType>' are incompatible.
                        Type 'Promise<InitializeHandlerOutput<ServiceOutputTypes>>' is not assignable to type 'Promise<InitializeHandlerOutput<OutputType>>'.
                          Type 'InitializeHandlerOutput<ServiceOutputTypes>' is not assignable to type 'InitializeHandlerOutput<OutputType>'.
                            Types of property 'output' are incompatible.
                              Type 'ServiceOutputTypes' is not assignable to type 'OutputType'.
                                'ServiceOutputTypes' is assignable to the constraint of type 'OutputType', but 'OutputType' could be instantiated with a different subtype of constraint 'MetadataBearer'.
                                  Type 'AbortMultipartUploadCommandOutput' is not assignable to type 'OutputType'.
                                    'AbortMultipartUploadCommandOutput' is assignable to the constraint of type 'OutputType', but 'OutputType' could be instantiated with a different subtype of constraint 'MetadataBearer'.ts(2345)

### Expected Behavior

getSignedUrl() function should work properly

**Comment by BrenoMazieiro** [comment]
Same problem on: https://github.com/aws/aws-sdk-js-v3/issues/4451

But it was closed.

**Comment by yenfryherrerafeliz** [comment]
Hi @BrenoMazieiro, sorry to hear about your issues. Basically, this issue occurs when the versions for "@aws-sdk/s3-request-presigner" and "@aws-sdk/client-s3" are different. So, could you please make sure those two packages are in the same version?, to corroborate this you could do:
```console
$ npm list @aws-sdk/s3-request-presigner
$ npm list @aws-sdk/client-s3
```

I hope this helps!

Thanks!
