### ISSUE TITLE
KMS Client - using GetPublicKeyCommand complains with TS2345

### ISSUE THREAD

**Issue by TaherKapasi** [aws/aws-sdk-js-v3#4951]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When using AWS SDK 3.369.0 - when trying to acquire a public key from KMS, we get the following typescript error `Argument of type 'GetPublicKeyCommand' is not assignable to parameter of type 'Command<ServiceInputTypes, GetPublicKeyCommandInput, ServiceOutputTypes, GetPublicKeyCommandOutput, SmithyResolvedConfiguration<...>>` whereas in version 3.359.0 it works fine.  

```
import { KMSClient, GetPublicKeyCommand } from '@aws-sdk/client-kms';
const kms = new KMSClient({ region: "eu-west-2" });
let publicSigningKey = await kms.send(new GetPublicKeyCommand({ KeyId: '<a-key-id>' }))
```

### SDK version number

@aws-sdk/client-kms@3.369.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.16.0

### Reproduction Steps

```
import { KMSClient, GetPublicKeyCommand } from '@aws-sdk/client-kms';
const kms = new KMSClient({ region: "eu-west-2" });
let publicSigningKey = await kms.send(new GetPublicKeyCommand({ KeyId: '<a-key-id>' }))
```

### Observed Behavior

TS2345: Argument of type 'GetPublicKeyCommand' is not assignable to parameter of type 'Command<ServiceInputTypes, GetPublicKeyCommandInput, ServiceOutputTypes, GetPublicKeyCommandOutput, SmithyResolvedConfiguration<...>>

### Expected Behavior

No TS  errors

### Additional Information/Context
typescript 5.1.6

**Comment by RanVaknin** [comment]
Hi @TaherKapasi,

Which version of TS are you using? Also can you try removing `node_modules` and `package-lock.json` and running `npm install` again? 

Let us know if that solves your issue.

Thanks,
Ran~

**Comment by neummichel** [comment]
Hello 👋 
Just to chime in, I encountered a similar issue with `@aws-sdk/client-sqs` and `ChangeMessageVisibilityBatchCommand`. Removing the lock files and reinstalling dependencies does solve the issue for me (TS 4.9.5)
