### ISSUE TITLE
Missing Types in v3 sdk

### ISSUE THREAD

**Issue by ghidalgo93** [aws/aws-sdk-js-v3#4952]
### Describe the issue

I'm in the middle of migrating my node application from the v2 aws-sdk to the v3 and have run into an issue with would seem to make it difficult to fully migrate over. I see that part of this migration calls for modularization of packages, so instead of importing the entire `aws-sdk` package you would instead import just `@aws-sdk/client-eventbridge` for example. There are some types I use in my project that I don't see in the new v3 @aws-sdk package. For example, the `AWSError. type is imported from `aws-sdk/lib/error.d.ts` and the `StackName` type from `aws-sdk/clients/cloudformation.d.ts`

I don't see these types in the v3 docs, so I find myself confused - Is this going to cause issues as I try to migrate over from v2 to v3? Will the non-scoped aws-sdk package stay around? Are there missing docs or types?

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-cloudformation/

**Comment by RanVaknin** [comment]
Hi @ghidalgo93 ,

please refer to this v3 error handling guide.
https://aws.amazon.com/blogs/developer/service-error-handling-modular-aws-sdk-js/

If this is not helpful, you can give us a concrete example on how you error handle and I'll try giving you a concrete example on how to achieve the same with v3. 

Thanks,
Ran~
