### ISSUE TITLE
did not return the expected Messages field in MetricDataResult

### ISSUE THREAD

**Issue by blindperson** [aws/aws-sdk-js-v3#4957]
### Describe the issue

after upgrade aws-sdkV2 to @aws-sdk/client-cloudwatch V3.359.0, when call `const response = new CloudWatch({}).getMetricData(param)`, we found that `response.MetricDataResults` will not return `Messages` field, Is this field only returned when certain errors occur or in other situations? please help have a look, thanks

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/Package/-aws-sdk-client-cloudwatch/Interface/MetricDataResult/

**Comment by yenfryherrerafeliz** [comment]
Hi @blindperson, the only scenario where MetricDataResults will not be present in the response is if an error is returned from that request. However, if this is not what is happening right now for you, could you please provide a reproduction code along with its response so we can investigate this further.

Thanks!
