### ISSUE TITLE
defaultRegionInfoProvider function missing after 3.185.0 release on all clients

### ISSUE THREAD

**Issue by adityahegde007** [aws/aws-sdk-js-v3#4958]
### Describe the feature

Earlier every aws service client had above method which used to provide default region for any service initialized with respective class object. Which is one way to identify the services enabled with "aws-global" region tag. every client had it's own endpoints list to cater them. Now only util-endpoints are served which are generic for all services along with ruleset and config resolver. which doesn't meet requirement to identify the regions supported by each aws service.

example:
s3: aws-global
ec2: all 23 regions
route53: aws global

### Use Case

Existing implementation (3.185.0)serves the purpose of identifying supported regions for each service and can query them by regions list. For s3 querying with region name "aws-global" fetch complete list of buckets. Now with latest changes after 3.185.0 need to query with specific region where results are duplicate for every region. (geo-redundancy). This is just an example of s3 similar use case exist for others as well. 

Also need list of regions/endpoints supported by each service within client object.

### Proposed Solution

bring back the implementation of endpoints scoped within each aws adk client package to serve it.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.185.0 ==>3.369.0

### Environment details (OS name and version, etc.)

any

**Comment by aBurmeseDev** [comment]
Hi @adityahegde007 - sorry for the long wait.

Per team discussion, we won't be able to implement at this time due to endpoints implication, unfortunately. Closing it now.
