### ISSUE TITLE
Type error with GetParameterCommand from client-ssm documentation example

### ISSUE THREAD

**Issue by andreidmt** [aws/aws-sdk-js-v3#4960]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Using the [example from the documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/ssm/command/GetParameterCommand/), retrieving a parameter from SSM throws a Typescript error.

![image](https://github.com/aws/aws-sdk-js-v3/assets/5057797/375c5db9-6e86-4048-b39b-2f1dc9fc20e9)

### SDK version number

@aws-sdk/client-ssm@3.369

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.15.0

### Reproduction Steps

Run the following example taken from the official docs:

```ts
import { SSMClient, GetParameterCommand } from "@aws-sdk/client-ssm"
const client = new SSMClient({})
const input = {
  Name: "STRING_VALUE",
  WithDecryption: true || false,
}
const command = new GetParameterCommand(input)
const response = await client.send(command)

console.log(response.Parameter)
```

### Observed Behavior

`client.send` will throw a typescript error:

```
1. typescript: Argument of type 'GetParameterCommand' is not assignable to parameter of type 'Command<ServiceInputTypes, GetParameterCommandInput, ServiceOutputTypes, GetParameterCommandOutput, SmithyResolvedConfiguration<...>>'.
```

### Expected Behavior

To not throw any type errors.

**Comment by yenfryherrerafeliz** [comment]
Hi @andreidmt, sorry to hear about your issues. I tried to reproduce the reported behavior and I was not able to. Could you please try removing your ``` package-lock.json ``` and running ``` npm install ```, because this seems to be a version conflicting issues.

Please let me know if this help.

Thanks!

**Comment by andreidmt** [comment]
Hey @yenfryherrerafeliz, doing a full reset `rm -rf package-lock.json node_modules **/node_modules && npm install` solved it.

I did update all packages recently using [`ncu`](https://www.npmjs.com/package/npm-check-updates) and ran `npm i` at the monorepo root level (npm workspace). I'll revert to the commit before the error/upgrade and see if I can reproduce the issue and understand better who's the culprit.

Thanks again, closing.
