### ISSUE TITLE
The S3.GetObjectCommand in AWS SDK V3 no longer returns the result as expected as that of AWS SDK V2

### ISSUE THREAD

**Issue by priyalakshmiP** [aws/aws-sdk-js-v3#4961]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Trying to get the ZipFile from S3. The ZipFile contains the file entries from GitHub
Difference the responseBody with AWS SDK V2 (S3.GetObject) and AWS SDK V3 (S3.GetObjectCommand)

### SDK version number

AWS SDK V2

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

NodeJS

### Reproduction Steps

Trying to get the ZipFile from S3. The ZipFile contains the files from GitHub

With V2,
const data = await s3.getObject(params).promise();
const zip = new AdmZip(data.Body);
const zipEntries = zip.getEntries();

zipEntries has the entryName (GitHub files path)

![image](https://github.com/aws/aws-sdk-js-v3/assets/70784588/ea3df215-1623-40fe-8648-6cd08c191938)

But with V3,
const s3Response = await s3cli.send(s3Command);
const chunks = [];
for await (const chunk of s3Response.Body) // process the object content in chunks
{
console.log("Chunk..."+JSON.stringify(chunk));
chunks.push(chunk);
}
console.log("Chunks..."+JSON.stringify(chunks));

chunks do not have the entryName (GitHub files path). Has only the rawEntryName (as per the response from V2) but not the entryName filed which has the orignial GitHub file path

![image](https://github.com/aws/aws-sdk-js-v3/assets/70784588/daebda49-b67c-4a13-8cea-57e788d0f8fe)

Does the S3 response body will not return the GitHub files (entryName) in AWS SDK V3 as that of AWS SDK V2 ?

### Observed Behavior

chunks do not have the entryName (GitHub files path). Has only the rawEntryName (as per the response from V2) but not the entryName filed which has the orignial GitHub file path

### Expected Behavior

chunks should have the entryName (GitHub files path)

**Comment by yenfryherrerafeliz** [comment]
Hi @priyalakshmiP, sorry to hear about your issues. With V3 what you could do is the following, assuming that AdmZip expect a string type as parameter:

```js
import {GetObjectCommand, S3Client} from "@aws-sdk/client-s3";
import AdmZip from "adm-zip";

const client = new S3Client({});
const response2 = await client.send(new GetObjectCommand({
    Bucket: "bucket",
    Key: "key"
}));
const buffer = Buffer.from(await response2.Body.transformToByteArray())
const zip = new AdmZip(buffer.toString('utf-8'), {});
const zipEntries = zip.getEntries();
```

Note: Please make sure you are in the latest version of the SDK since transformToByteArray was introduced recently.

I hope this helps!

Thanks!

**Comment by priyalakshmiP** [comment]
@yenfryherrerafeliz - Thank you. This worked.
I used the below code. AdmZip expected an object in my case.

import {GetObjectCommand, S3Client} from "@aws-sdk/client-s3";
import AdmZip from "adm-zip";

const client = new S3Client({});
const response2 = await client.send(new GetObjectCommand({
    Bucket: "bucket",
    Key: "key"
}));
const buffer = Buffer.from(await response2.Body.transformToByteArray())
const zip = new AdmZip(buffer);
const zipEntries = zip.getEntries();

**Comment by yenfryherrerafeliz** [comment]
@priyalakshmiP I am glad that it worked. Please feel free of opening a new issue if you need something else that we are able to help.

Thanks!
