### ISSUE TITLE
The requestTimeout parameter in the NodeHttpHandlerOptions description is incorrect

### ISSUE THREAD

**Issue by sdw-123-sdw** [aws/aws-sdk-js-v3#4963]
### Describe the issue

Hello writers and contributors, I have some questions about the requestTimeout parameter in the official documentation for NodeHttpHandlerOptions.
The description of "requestTimeout" in the documentation is as follows: "The number of milliseconds a request can take before automatically being terminated." Does this time include the connection time? Does this parameter refer to the time from sending the connection establishment message to disconnecting the connection, or the time from establishing the connection to disconnecting it, or does it refer to disconnecting the connection after it has been idle for "requestTimeout" duration?
Looking forward to your answer.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/interfaces/_aws_sdk_node_http_handler.NodeHttpHandlerOptions.html

**Comment by yenfryherrerafeliz** [comment]
Hi @sdw-123-sdw, thanks for opening this issue.  The following implementation [here](https://github.com/aws/aws-sdk-js-v3/blob/4b0faf7db1ce1e4a23f33327f736266f5fda50fd/packages/node-http-handler/src/set-socket-timeout.ts#L4C11-L4C21), shows how this parameter is used in our code, which basically uses the nodejs http lib implementation, to set the request timeout by calling request.setTimeout, and the nodejs documentation says that, this timeout is set once the socket connects, which means that this timeout just applies for the time the request is being sent. [Here](https://nodejs.org/api/http.html#requestsettimeouttimeout-callback) is the nodejs documentation.

Please let me know if this helps!

Thanks!

**Comment by sdw-123-sdw** [comment]
Hi @yenfryherrerafeliz ,thank you very much for your answer, which has solved my problem.

**Comment by yenfryherrerafeliz** [comment]
@sdw-123-sdw you are very welcome. If you need anything else that we are able to help, please feel free in opening a 
new issues.

Thanks!
