### ISSUE TITLE
Issue when enabling fips mode on the SDK

### ISSUE THREAD

**Issue by vineet199** [aws/aws-sdk-js-v3#4965]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I am trying to use the aws-sdk in FIPS mode. However, some of the functions, such as the createHash function in aws-sdk is not FIPS compliant. This is the value set in my aws config as well - 

region=us-east-1
use_fips_endpoint=true

### SDK version number

@aws-sdk/client-secrets-manager@3.369.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node v20.5.0

### Reproduction Steps
```js
const { SecretsManagerClient, GetSecretValueCommand } = require("@aws-sdk/client-secrets-manager");
const client = new SecretsManagerClient({ region: "us-east-1"});
try{
    crypto.setFips(true);
} catch(e){
    console.error("Error when enabling fips", e);
}
const input = {
    SecretId: "<secret_id>"
}
const command = new GetSecretValueCommand(input);
const response = yield client.send(command);
```
### Observed Behavior
```console
[PID : 43032 AT :13-07-2023 17:08:46.207] WARN: Unhandled rejection Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at createHash (node:crypto:138:10)
    at Hash.reset (/Users/user/myproject/node_modules/@smithy/hash-node/dist-cjs/index.js:23:39)
    at new Hash (/Users/user/myproject/node_modules/@smithy/hash-node/dist-cjs/index.js:12:14)
    at getPayloadHash (/Users/user/myproject/node_modules/@smithy/signature-v4/dist-cjs/getPayloadHash.js:18:26)
    at SignatureV4.signRequest (/Users/user/myproject/node_modules/@smithy/signature-v4/dist-cjs/SignatureV4.js:116:71)
    at async /Users/user/myproject/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:16:18
    at async /Users/user/myproject/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /Users/user/myproject/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
```
### Expected Behavior

When fips is disabled, the above code snippet works fine and retrieves the secret from the secret manager client successfully

**Comment by RanVaknin** [comment]
Hi @vineet199 ,

I'm not entirely sure why you need this part of your code as this is a Node functionality, and is unrelated to the SDK: 
```js
try{
    crypto.setFips(true);
} catch(e){
    console.error("Error when enabling fips", e);
}
```

All you need to do to turn on fips, by enabling it in the config object for your client:

```js
const { SecretsManagerClient, GetSecretValueCommand} = require("@aws-sdk/client-secrets-manager")

const client = new SecretsManagerClient({
    region: "us-east-1",
    useFipsEndpoint: true
});

// custom middleware to log the request - proving that the request is going out to the proper FIPS endpoint.
client.middlewareStack.add(next => args => {
    console.log('before sign: ' , args.request);
    return next(args);
}, {step: 'build'})


async function getSecret(){
    try {
        const response = await client.send(new GetSecretValueCommand({
            SecretId : "my-secret-3425",
        }))
        console.log(response)
    } catch (error) {
       console.log(error) 
    }
}
getSecret()
```

In this output you can see the hostname logged by the middleware, routing the request to the proper FIPS endpoint.
```console
$ node sample.js
before sign:  HttpRequest {
  method: 'POST',
  hostname: 'secretsmanager-fips.us-east-1.amazonaws.com',
  port: undefined,
  query: {},
  headers: {
    'content-type': 'application/x-amz-json-1.1',
    'x-amz-target': 'secretsmanager.GetSecretValue',
    'content-length': '29'
  },
  body: '{"SecretId":"my-secret-REDACTED"}',
  protocol: 'https:',
  path: '/',
  username: undefined,
  password: undefined,
  fragment: undefined
}
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'REDACTED',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  ARN: 'arn:aws:secretsmanager:us-east-1:REDACTED:secret:my-secret-REDACTED-REDACTED',
  CreatedDate: 2022-06-02T22:14:54.561Z,
  Name: 'my-secret-3425',
  SecretString: REDACTED
  VersionId: 'REDACTED',
  VersionStages: [ 'AWSCURRENT' ]
}
```

Can you provide us with more context as why the Node.js crypto library is needed here? 

Thanks,
Ran~

**Comment by yenfryherrerafeliz** [comment]
Hi @vineet199, could you please confirm if you have fips build of nodejs?

I think this issue [here](https://github.com/nodejs/help/issues/753) could be related.

Thanks!

**Comment by vineet199** [comment]
Hi @yenfryherrerafeliz,

The application is compiled with Node js v20.5.0, which has FIPS support.
When crypto.setFips(true), we believe, the application will only use cryptographic functions that are fips compliant.
However, if you check the observed behaviour, you can see that some middleware cryptographic function in the aws sdk, is using a function that is not fips compliant. ( the createHash function probably uses the md5 crypto algorithm which is not fips compliant)
We are under the impression that, setting the use_fips_endpoints flag in the sdk would enforce the usage of fips compliant endpoints, not sure if it enforces usage of FIPS compliant crypto functions.

Thank you for your patience!

**Comment by yenfryherrerafeliz** [comment]
@vineet199, when "use_fips_endpoints" is set to true then, it just make the SDK to send the requests to endpoints that are fips compliant. The SDK is actually not using MD5, but sha256. You can actually reproduce this at your end, without using the SDK by doing the following:
```js
import crypto, { createHash } from "crypto";
crypto.setFips(true);
const hash = createHash("sha256");
```

As you can see we are just using a nodejs native cryptographic function to create a sha256 hash. So, do you know what would be the fips compliance function that we should be using in this case?

Please let me know.

Thanks!

**Comment by vineet199** [comment]
Hi @yenfryherrerafeliz,

You are absolutely right. We were looking into it recently and found that the openssl we were using required a fips compliance configuration step, which we had overlooked, on configuring and enabling fips mode in the openssl library installed, the aws-sdk works as expected. This issue can be considered as invalid. 

Thank you for your efforts and support
