### ISSUE TITLE
BUG: there is no way to search for output object (such as GetObjectCommandOutput)

### ISSUE THREAD

**Issue by markcarroll** [aws/aws-sdk-js-v3#4974]
### Describe the issue

The new documentation is a major step backwards.  To find the output for a command I have to:

1. Search for the package that command is in (S3 in this example)
2. Search for the command itself (GetObjectCommand)
3. Click on the result as the preview does not show the output 
4. Scroll down to see the output that is listed at the bottom
5. Click on the reference to the command output object
6. Now click in to the linked object

None of which is very discoverable nor usable.  I should be able to search for `GetObjectCommandOutput` from the front page and it _tell ME_ which package it is in and which command it comes from. 

and _still_ it does not show a reference to `__WithSdkStreamMixin` and the `transformToByteArray` method. 

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/

**Comment by kuhe** [comment]
We've updated the docs to make some of the previously missing core types available again.

Here is the page for the command or operation: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/command/GetObjectCommand/

The output type now contains links describing the streaming format of the body:
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-s3/Interface/GetObjectCommandOutput/

And from that page, there is a link to the base response type containing the rest of the response values: 
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-s3/Interface/GetObjectOutput/

The SdkStreamMixin, also now linked from the CommandOutput type page, describes additional methods on the streaming blob payload (body) that simplify transforming it to other formats: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-smithy-types/Interface/SdkStreamMixin/

**Comment by kuhe** [comment]
`GetObjectCommandOutput` can be found directly using the search at the top center of the page.

**Comment by markcarroll** [comment]
Definitely a big improvement.  However, since this is a huge change from v2 GetObject, and this is the most confusing multiple layers of clicks to get to a page that doesn't actually tell you anything about how to use this response, it seems like there could at least be examples of how to use this properly.

**Comment by kuhe** [comment]
There is some more info about how to convert streaming response bodies such as those from S3::GetObject here: https://github.com/aws/aws-sdk-js-v3/#streams. This describes helper methods for converting that stream into a string and other types.
