### ISSUE TITLE
About modifying the "delaybase" parameter in "retry".

### ISSUE THREAD

**Issue by sdw-123-sdw** [aws/aws-sdk-js-v3#4975]
### Describe the issue

Hello, authors and contributors. We are currently using the "StandardRetryStrategy" from the "@aws-sdk/middleware-retry" package to configure retries. Unfortunately, we noticed that it has been deprecated. I would like to know when the maintenance of the StandardRetryStrategy will be discontinued.

Following the guidance, I found the "StandardRetryStrategy" in the "@aws-sdk/util-retry" package. After reading the source code, I couldn't find a constructor or any function that allows modifying the "delaybase" parameter. I would like to know how I can make the StandardRetryStrategy capable of setting the "delaybase" or how to enable the "delaybase" parameter in the StandardRetryStrategy class from the "@aws-sdk/middleware-retry" package.

I am looking forward to your response.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/classes/_aws_sdk_middleware_retry.StandardRetryStrategy.html
https://github.com/aws/aws-sdk-js-v3/blob/4b0faf7d/packages/util-retry/src/StandardRetryStrategy.ts

**Comment by yenfryherrerafeliz** [comment]
Hi @sdw-123-sdw, thanks for opening this issue. The package @aws-sdk/middleware-retry is deprecated, and it will probably not receive new changes, but it will be still available to be used. For the new package for retries, @aws-smithy/util-retry, you can provide a custom delaybase parameter by using the ConfiguredRetryStrategy class. Here is a quick example:
```js
import { S3Client } from "@aws-sdk/client-s3";
import { ConfiguredRetryStrategy } from "@aws-sdk/util-retry";

const client = new S3Client({
  retryStrategy: new ConfiguredRetryStrategy(
    4, // max attempts.
    (attempt: number) => 100 + attempt * 1000 // backoff function. Here is where you should set your custom delay base
  ),
});
```

[Here](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/Package/-aws-sdk-util-retry/) is the documentation for this package.

Please let me know if that helps!

Thanks!
