### ISSUE TITLE
DynamoDB: Expose item attributes when conditional update expression fails

### ISSUE THREAD

**Issue by misterjoshua** [aws/aws-sdk-js-v3#4976]
### Describe the feature

When using `UpdateCommand`, the DynamoDB document client should support responding with the values returned from the DynamoDB service when `ReturnValuesOnConditionCheckFailure` is set to `ALL_OLD`, and when a `ConditionalCheckFailedException` is thrown.

### Use Case

I want to include details about the record that failed to update in an error I throw when the conditional check fails.

### Proposed Solution

Perhaps you could add an "attributes" property to `ConditionalCheckFailedException` and populate that property with the return item's attributes.

### Other Information

I tried to reach into the exception's `$response`, but I can't find the right way to read the response body to get this information. I have to send a second query to fetch this information, which increases the cost of getting this information using this SDK and adds another round-trip to the DynamoDB service.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.365.0

### Environment details (OS name and version, etc.)

Ubuntu Linux

**Comment by RanVaknin** [comment]
Hi @misterjoshua ,

What you are referring to is support for this feature of returning the failed item structure in the response of `ConditionalCheckFailedException `?
Since you didn't share your code I cant tell what you are doing wrong, but the SDK serializes that value and prints it correctly. 

```js
async function updateItem() {
    
    const params = {
        TableName: "my-foo-table",
        Key: marshall({
            pk: "testKey",
        }),
        UpdateExpression: "SET #v = :value",
        ExpressionAttributeNames: {
            "#v": "value"
        },
        ExpressionAttributeValues: marshall({
            ":value": "testValue",
        }),
        ConditionExpression: "attribute_not_exists(pk)",
        ReturnValuesOnConditionCheckFailure: "ALL_OLD",
    };

    try {
        const data = await client.send(new UpdateItemCommand(params));
        console.log(data);
    } catch (err) {
        console.log(err);
    }
}

updateItem();
```

Will result in:

```
ConditionalCheckFailedException: The conditional request failed
<StackTrace Redacted>
    at async updateItem (/Users/REDACTED/REDACTED/REDACTED/sample.js:47:22) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: 'REDACTED',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Item: { pk: { S: 'testKey' }, value: { S: 'testValue' } },
  __type: 'com.amazonaws.dynamodb.v20120810#ConditionalCheckFailedException'
}
```

I dont think this is related, but Im using 
```
├── @aws-sdk/client-dynamodb@3.370.0
└── @aws-sdk/util-dynamodb@3.370.0

```
Hope this helps.

Thanks,
Ran~

**Comment by misterjoshua** [comment]
Thanks, Ran. Looks like I've made an error. Sorry about the wasted issue.
