### ISSUE TITLE
AWSSDK not able to access S3 from within pio

### ISSUE THREAD

**Issue by joaocasarin** [aws/aws-sdk-js-v3#4977]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

None of my apps written both in typescript or javascript are NOT able to access the resource S3 from AWS when running from within a pod in our EKS cluster.
Although that happens with the JS scripts, it works fine when using `aws s3 cp s3://bucket/key .`, therefore there is a bug with the SDK.

### SDK version number

@aws-sdk/client-s3: ^3.363.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node: v18.16.0

### Reproduction Steps

Create a ServiceAccount in k8s attached to a custom assumable role in AWS with permissions to access the bucket, add that service account to the pod.
When it is done, some environment variables will be added to the pod, such as `AWS_DEFAULT_REGION`, `AWS_ROLE_ARN`, `AWS_REGION` and some others.
With that set and with awscli installed in the container, it works fine when using the cli.

Simple snippet of code provided in the [official docs](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/javascript_s3_code_examples.html):
```ts
const s3 = require("@aws-sdk/client-s3");
const s3Client = new s3.S3Client({ region: "us-west-2" });

s3Client
    .send(
        new s3.GetObjectCommand({
            Bucket: "app-artifacts",
            Key: "index.js",
        })
    )
    .then((data) => {
        console.log(data);
    })
    .catch((e) => console.log(e));
```

That code is executed using `node file.js`, `yarn start` etc...

That is just one of the codes I tried. It won't work anyway, with or without a server running it. It will always take 20 minutes to resolve the `s3Client.send(...)` command and always end up in TIMEOUT:
`12-07-2023 20:10:33 error: index - Error occurred: TimeoutError: connect ETIMEDOUT 172.31.2.175:443 `

This happens in 100% of the times.

I tried JAVA SDK as well and didn't work, so probably both got issues. The only SDK that actually worked was Boto3 for Python.

Code that worked for python:
```py
import boto3
import botocore

BUCKET_NAME = 'my-bucket' # replace with your bucket name
KEY = 'my_image_in_s3.jpg' # replace with your object key

s3 = boto3.resource('s3')

try:
    s3.Bucket(BUCKET_NAME).download_file(KEY, 'my_local_image.jpg')
except botocore.exceptions.ClientError as e:
    if e.response['Error']['Code'] == "404":
        print("The object does not exist.")
    else:
        raise
```

### Observed Behavior

The bucket can be accessed with the awscli from within the pod, but cannot be accessed (timeout of 20min) when using a JS script.

### Expected Behavior

Since awscli can do the job, then the access to the bucket is fine from the pod, so any code that tries to access the s3 resource should work.

### Additional Information/Context

Our AWS is internal and is wrapped with a security layer, so it is not available for outside the VPN. The pod can access the bucket with the ServiceAccount.

Even with the Service Account, the folder `~/.aws` does not exist and the awscli still works.
When I run `aws sts get-caller-identity` I can see the role being used and other info like session token etc..

**Comment by joaocasarin** [comment]
hi, any thoughts about this issue? I'd like to use JS at work for this app since this sdk seems more solid thant python's boto3..

**Comment by RanVaknin** [comment]
Hi @joaocasarin,

I was able to successfully Dockerize my application and run it from EKS.

runner code
```js
import { S3Client, ListBucketsCommand } from '@aws-sdk/client-s3';

const client = new S3Client({ region: 'us-east-1' });

try {
    const data = await client.send(new ListBucketsCommand({}));
    console.log(data)
} catch (error) {
    console.log(error);
}
```

Dockerfile:
```
FROM --platform=linux/amd64 node:18

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

CMD ["node", "sample.mjs"]
```

Logs from the pod:

```console
$ kubectl logs js-on-eks-app-REDACTED

{
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'REDACTED',
    extendedRequestId: 'REDACTED',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Buckets: [
    { Name: 'REDACTED-athena', CreationDate: 2022-08-02T21:03:10.000Z },
    {
      Name: 'REDACTED',
      CreationDate: 2022-05-05T21:00:37.000Z
    },
    {
      Name: 'amazon-connect-REDACTED',
      CreationDate: 2023-07-27T19:51:44.000Z
    },
    {
      Name: 'aws-glue-assets-REDACTED-us-east-1',
      CreationDate: 2022-11-02T21:29:20.000Z
    },
    {
      Name: 'aws-logs-REDACTED-us-east-1',
      CreationDate: 2022-10-18T06:01:40.000Z
    },
```

As you can see, running JS SDK code on EKS is not broken. Another way to rule out an SDK issue will be to remove the SDK code altogether and from the same pod write the request yourself using node-fetch or axios directly to the service. My guess is that you're going to hit a similar issue.

When you run the command with the python SDK / CLI you can enable the debug logs and see if the request is going into a different IP address (different than the `172.31.2.175:443 ` your error specified). Maybe this specific IP address need to be allow-listed in your network ACL and or security group.

Another thing to try is to deploy this application in another pod altogether? maybe this specific pod is incorrectly configured? 

My best guess is that you have some networking rules that are misconfigured and are blocking traffic between the pod and AWS. Unfortunately I'm not an EKS expert and can't advise you on the correct networking configuration. For this you might want to create an internal ticket using the AWS console and request to be routed to the EKS team for additional help. 

Thanks,
Ran~

**Comment by joaocasarin** [comment]
Hi @RanVaknin, thanks for the attempt to reproduce that issue!
I am still trying to debug what you said in our side but we got some issues not related to the SDK at the same time, that's why it's taking a bit longer than the expected
