### ISSUE TITLE
[Bug client-s3]: MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit

### ISSUE THREAD

**Issue by offchan42** [aws/aws-sdk-js-v3#4978]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I was following this guide: https://github.com/awsdocs/aws-doc-sdk-examples/tree/main/javascriptv3/example_code/nodegetstarted

and I got the following warning: `MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit`.

The code succeeded though. Is the warning critical?

### SDK version number

@aws-sdk/client-s3@3.370.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.4.0

### Reproduction Steps

Follow the instruction in this [README file](https://github.com/awsdocs/aws-doc-sdk-examples/tree/main/javascriptv3/example_code/nodegetstarted).

### Observed Behavior

Warning message: **(node:35080) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)**

### Expected Behavior

No warning

### Possible Solution

The `client-s3` module might be leaking memory.

This is a minimal code to reproduce the issue:
```js
import { CreateBucketCommand, S3Client } from '@aws-sdk/client-s3'
const s3Client = new S3Client({ region: 'us-east-1' })

const data = await s3Client.send(
  new CreateBucketCommand({ Bucket: 'PUT_BUCKET_NAME_HERE' })
)
console.log(data)
```

You can try to run it and will see the warning even if the bucket creation succeeds.

**Comment by yenfryherrerafeliz** [comment]
Hi @off99555, could you please confirm if you are still experiencing this issue?. I tried to replicate it on my end but I did not get any warnings. Please see below:

```js
import { CreateBucketCommand, S3Client } from '@aws-sdk/client-s3'

const s3Client = new S3Client({
    region: 'us-east-1',
})

const data = await s3Client.send(
    new CreateBucketCommand({ Bucket: 'abcdef-hf-mybucket' })
)
console.log(data)
```
Response:
```console
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'redacted',
    extendedRequestId: 'redacted',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Location: '/abcdef-hf-mybucket'
}

```

Thanks!

**Comment by mdwekat** [comment]
I'm still getting the error:

```shell
(node:20971) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:588:17)
    at TLSSocket.addListener (node:events:606:10)
    at Readable.on (node:internal/streams/readable:904:35)
    at TLSSocket._wrapHandle (node:_tls_wrap:674:8)
    at TLSSocket.reinitializeHandle (node:_tls_wrap:683:22)
    at internalConnectMultiple (node:net:1123:30)
    at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
    at listOnTimeout (node:internal/timers:575:11)
    at process.processTimers (node:internal/timers:514:7)
```

This is the code I tried:

```js
// test-s3-upload.js
import { PutObjectCommand, S3Client } from '@aws-sdk/client-s3';

const client = new S3Client({
  region: '<region>',
  credentials: {
    accessKeyId: '<ID>',
    secretAccessKey: '<KEY>',
  },
});

//Upload a file to s3
const run = async () => {
  const buffer = Buffer.from('Hello World!');

  try {
    const data = await client.send(
      new PutObjectCommand({
        Bucket: '<SOME_BUCKET>',
        Key: 'hello.txt',
        Body: buffer,
      }),
    );
    console.log('Success', data);
  } catch (err) {
    console.log('Error', err);
  }
};

run();
```

Then run with:

```shell
node --trace-warnings test-s3-upload.js
```
Versions:
@aws-sdk/client-s3: `v3.398.0`
node: `v20.5.1`

**Comment by off99555** [comment]
@yenfryherrerafeliz Yes, I can confirm that the warning still exists even if the command fails (e.g. access denied or wrong access key specified in environment variables)

**Comment by bobsquito** [comment]
I hit the same issues but downgrading node to v18 solved it

**Comment by trusktr** [comment]
I have the same exact error, but I'm not using AWS. I'm doing an `npm install`. Maybe some package (or npm itself?) is trying to use network during install and causing the error.

It seems harmless though. Like, even if code is written properly, if some code is, for example, sending more than 10 requests and has properly added more than 10 event handlers for each of those requests (just guessing here) then it is plausible to see this error, but it won't actually mean anything is wrong.

This is as if a DOM API like `window.addEventListener('whatever', listener)` would automatically log a warning to console after an arbitrary 10 event listeners were added, even if they were all totally valid listeners.

There's probably nothing to do here, and just hope the codes that are adding listeners (could be more than one package in the system, so it could add up) are properly removing listeners when they're done.

If *you* are the one adding listeners in your own code, *then* this warning could actually be useful if you didn't expect listeners to keep growing.

This warning is probably just useless noise most likely.

**Comment by tirthbodawala** [comment]
facing the same issue with Node v20.9.0

**Comment by farzadso** [comment]
I'm also experiencing this with the latest version of the libraries. Also using Windows but I'm experiencing the issue on my Linux servers.

Why was this closed? https://github.com/aws/aws-sdk-js-v3/issues/1828

**Comment by rahul1368** [comment]
I am also facing the same issue with Node v20.7.0

**Comment by nolawnchairs** [comment]
Almost a year since this issue was opened, and the issue is still there with the latest NPM install and Node 20.

**Comment by farzadso** [comment]
I have come to the understanding that this is a network-related issue. It has never happened on production servers.

**Comment by Terkea** [comment]
same issue here

**Comment by aBurmeseDev** [comment]
Hey all - apologies for the long silence here. 

The error "MaxListenersExceededWarning: Possible EventEmitter memory leak detected" is a warning message from Node.js indicating that there might be a potential memory leak due to an excessive number of event listeners being added to an EventEmitter instance.

Upon reviewing the comments and investigating the error, here are a couple suggestions you can take to resolve this issue:
- Use the [smithy/node-http-handler](https://github.com/aws/aws-sdk-js-v3/blob/main/supplemental-docs/CLIENTS.md#request-handler-requesthandler): install and import the package `npm install @smithy/node-http-handler`

```js
import { NodeHttpHandler } from "@smithy/node-http-handler";
import https from "https";

new S3Client({
  requestHandler: new NodeHttpHandler({
    httpsAgent: new https.Agent({
      keepAlive: true,
      maxSockets: 200, // default is 50 per client.
    }),

    // time limit (ms) for receiving response.
    requestTimeout: 15_000,

    // time limit (ms) for establishing connection.
    connectionTimeout: 6_000,
  }),
});
```
- Use the destroy() method: When you're done with an AWS service client instance, make sure to call the destroy() method to properly clean up any resources and event listeners associated with it. This will help prevent potential memory leaks.
```js
const client = new S3Client({
  region: '<region>',
  credentials: {
    accessKeyId: '<ID>',    
    secretAccessKey: '<KEY>',
  },
});

const run = async () => {
  try {
    // Your existing code...
  } catch (err) {
    console.log('Error', err);
  } finally {
    // Destroy the client instance
    client.destroy();
  }
};
```

Let me know if issue persists after trying the methods mentioned. 
Best,
John
