### ISSUE TITLE
Non-existent types in the aws-sdk for JS v3

### ISSUE THREAD

**Issue by ghidalgo93** [aws/aws-sdk-js-v3#4983]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I had opened up another issue describing the missing `AWSError` type I had been using in my code base for generic error logging (which I was then told was because there are new ways of logging errors in v3) but I'm finding some other missing types.

I'm migrating my project's code over to the recommended v3 aws-sdk for JS and there are some types (my project uses TS) that no longer exist in the model-generated @aws-sdk/client-<SERVICE> code. According to these official docs [aws-sdk-js-v3 repo](https://github.com/aws/aws-sdk-js-v3#generated-code):

```
The v3 codebase is generated from internal AWS models that AWS services expose. We use smithy-typescript to generate all code in the /clients subdirectory. These packages always have a prefix of @aws-sdk/client-XXXX and are one-to-one with AWS services and service operations.
```

As stated above, this isn't the first time I've seen instances of the new v3 SDK differing from v2. We had previously been using types like:

import { StackName } from 'aws-sdk/clients/cloudformation';

which wasn't really an issue because it's just a string, but there are one's that get a bit trickier like:

import { RuleResponseList } from 'aws-sdk/clients/eventbridge';

which is itself an Array of Rules which are fairly complex and that I really do not want to type myself.

The v3 migration opts to completely remove imports from aws-sdk/* so I'm stuck... is this an oversight and just something that needs to be brought to the AWS team's attention or am I missing how to import these types in v3?

### SDK version number

@aws-sdk/client-cloudformation 3.370.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.18.0

### Reproduction Steps

1) importing the following types:

```
import { RuleResponseList } from 'aws-sdk/clients/eventbridge';
import { StackName } from 'aws-sdk/clients/cloudformation';
```

2) removing the aws-sdk v2 imports and moving over to the modular `@aws-sdk/client-cloudformation` import:

```
import { StackName, RuleResponseList, CloudFormation } from '@aws-sdk/client-cloudformation'; 
```

### Observed Behavior

gives the following errors:

```
Module '"@aws-sdk/client-cloudformation"' has no exported member 'StackName'. [2305]
Module '"@aws-sdk/client-cloudformation"' has no exported member 'RuleResponseList'. [2305]
```

### Expected Behavior

Expected to be able to use these types.

### Possible Solution

Adding types that were present in the v2 aws-sdk to the auto-generated smithy-typescript code.

**Comment by ghidalgo93** [comment]
Update: I had mostly given up on the codmod script, but looks like that does give me the following typing from the eventbridge client:

```
import AWS_EventBridge, { EventBridge } from "@aws-sdk/client-eventbridge";
```

where the rules response list can be typed as:
```
  let foo: Array<AWS_EventBridge.Rule> = [];
```

Is this the pattern that v3 should follow going forward? If so, this can be closed up (some documentation for this would be incredible though!)

**Comment by RanVaknin** [comment]
Hi @ghidalgo93 ,

I'm sorry to hear that Codmod is not working as expected.
In order to help you can you give us an example of how you are using  Cloudformation? Im not sure why you are importing StackName in the first place as it is a String, and not an interface or type.

Here is an example of how to use v3 to call DescribeStack:
 
 ```js
 import { CloudFormationClient, DescribeStacksCommand } from '@aws-sdk/client-cloudformation';

const client = new CloudFormationClient({
    region: "us-east-1",
})

async function run(){
    try {
        const response = await client.send(new DescribeStacksCommand({
            StackName: "foo-stack"
        }))
        console.log(response)
    } catch (error) {
        console.log(error)
    }
}
run()
 ```

**Comment by paul-uz** [comment]
Keep open please

**Comment by RanVaknin** [comment]
@paul-uz I don't see an issue here unless you have more insight to the problem?

Unless the problem is with Codemod and then the Codemod repo itself would be the place for this issue. 

Thanks,
Ran~
