### ISSUE TITLE
Possible RevokeSecurityGroupIngressCommand broken

### ISSUE THREAD

**Issue by vjdv** [aws/aws-sdk-js-v3#4984]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Since version 202 of ec2-client, the following code stops working:

```typescript
/** Clean security group permissions by reading current permissions and then revoking them **/
export async function borrarPermisosActualesSG(grupoSeguridad: string) {
  const client = new EC2Client({ region: "us-east-1", credentials: awsSecrets() });
  log.info(`Borrando permisos anteriores`);
  const command = new DescribeSecurityGroupsCommand({ GroupIds: [grupoSeguridad] });
  const r1 = await client.send(command);
  if (!r1.SecurityGroups) return;
  const currentPermisions = r1.SecurityGroups.flatMap((s) => (s.IpPermissions === undefined ? [] : s.IpPermissions));
  if (currentPermisions.length === 0) return;
  const command2 = new RevokeSecurityGroupIngressCommand({ GroupId: grupoSeguridad, IpPermissions: currentPermisions });
  await client.send(command2);
  log.info(`Los anteriores permisos fueron borrados (${currentPermisions.length})`);
}
```

### SDK version number

@aws-sdk/client-ec2@202

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.17.0

### Reproduction Steps

```typescript
function awsSecrets() {
  return { accessKeyId: config.aws.accessKey, secretAccessKey: config.aws.secretKey };
}

borrarPermisosActualesSG("security-group");
```

### Observed Behavior

Read current permissions but when revoking occurs following error:

**InvalidRequest: The request received was invalid.**

```json
{
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: '61ac6d0d-c049-4660-be3c-d54b756c7d12',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Code: 'InvalidRequest'
}
```

### Expected Behavior

OK as in v201

### Additional Information/Context

Tried to upgrade to last version and stopped working

**Comment by yenfryherrerafeliz** [comment]
Hi @vjdv, sorry to hear about your issues. Could you please enable error logs so I can see what is the error message that explains why the request is invalid. You can enable error logs by the following:
```js
const client = new EC2Client({
    region: "us-east-1",
    credentials: awsSecrets(),
    logger: {
        error: (content) => {
            console.log("[ERROR]: ", content);
        }
    }
});
```
Could you please also provide the correct version of the SDK?, 202 is not a valid version. You can figure out this by executing the following command:
``` console
$ npm list @aws-sdk/client-ec2 
```

Note: Please make sure you redact any sensitive information.

Looking forward to your answer.

Thanks!

**Comment by vjdv** [comment]
This started in versión `@aws-sdk/client-ec2@3.202.0`

It's working ok in `@aws-sdk/client-ec2@3.201.0`

I added this logger:

```typescript
logger: {
      error: (content: any) => {
        console.log("[ERROR]: ", content);
      },
      debug: (content: any) => {
        console.log("[DEBUG]: ", content);
      },
      info: (content: any) => {
        console.log("[INFO]: ", content);
      },
      warn: (content: any) => {
        console.log("[WARN]: ", content);
      }
    }
```

but I see same error from before with some `[DEBUG]:  endpoints` before

I tried to upgrade from 49 to current (371).

**Comment by vjdv** [comment]
`@aws-sdk/client-ec2@3.201.0` prints:

```json
[INFO]:  {
  clientName: 'EC2Client',
  commandName: 'RevokeSecurityGroupIngressCommand',
  input: { GroupId: 'sg-0769e84ad3c9523d0', IpPermissions: [ [Object] ] },
  output: { Return: true, UnknownIpPermissions: undefined },
  metadata: {
    httpStatusCode: 200,
    requestId: 'b40b7f48-c9bf-4936-80a5-5fe4d5f4014a',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}
```

Same info is sended to `RevokeSecurityGroupIngressCommand`:

```json
{
  "GroupId": "sg-xxxxxxxxxxxxxxxxx",
  "IpPermissions": [
    {
      "FromPort": 22,
      "IpProtocol": "tcp",
      "IpRanges": [
        {
          "CidrIp": "201.141.54.215/32",
          "Description": "ssh_prueba1"
        }
      ],
      "Ipv6Ranges": [],
      "PrefixListIds": [],
      "ToPort": 22,
      "UserIdGroupPairs": []
    }
  ]
}
```

**Comment by vjdv** [comment]
Added this to `borrarPermisosActualesSG()` before send to `RevokeSecurityGroupIngressCommand`:

```js
currentPermisions.forEach((o) => {
    delete o.Ipv6Ranges;
    delete o.PrefixListIds;
    delete o.UserIdGroupPairs;
  });
```

and now is working in `@aws-sdk/client-ec2@3.202.0` and `@aws-sdk/client-ec2@3.379.1`

**Comment by yenfryherrerafeliz** [comment]
Hi @vjdv, that makes sense. Basically, those parameters are not part of the input expected by RevokeSecurityGroupIngressCommand, which we can confirm [here](https://github.com/aws/aws-sdk-js-v3/blob/fcb5278018350acf4111a56bc868decc1e520bec/clients/client-ec2/src/models/models_6.ts#L8680). Thanks for letting me know. I will resolve this issue, but please if you happen to need anything else that we can help you with, feel free of opening a new issue.

Thanks!
