### ISSUE TITLE
New docs for Kinesis missing examples

### ISSUE THREAD

**Issue by flaviut** [aws/aws-sdk-js-v3#4985]
### Describe the issue

This seems like a common problem throughout the new docs, but let's focus on the Kinesis docs since I don't have time to take make my gut feeling into something more concrete.

For example, https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-kinesis-video-media/ has an of example of how to import the package and how to send a basic command, while the new docs don't have these examples.

There's another full example at https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-kinesis-video-media/classes/getmediacommand.html, but again, [the new docs don't have this](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-kinesis-video-media/Class/GetMediaCommand/).

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/kinesis-video-media/

**Comment by yenfryherrerafeliz** [comment]
Hi @flaviut, thanks for reporting this. I will mark this issue with a needs-review label so we can further address it. 

Thanks!

**Comment by RanVaknin** [comment]
Hey @yenfryherrerafeliz and @flaviut ,

The new docs offer examples on a per-operation basis. 
Kinesis Video Media API only has one operation - `GetMediaCommand`:

![image](https://github.com/aws/aws-sdk-js-v3/assets/50976344/0e667a23-1eb6-42da-8c3a-843451a4b4c7)

So by clicking on the operation in the docs, you are able to see the full example, including all the nested input and output shapes, something that was not available in the old docs:

![image](https://github.com/aws/aws-sdk-js-v3/assets/50976344/249b7fd2-168d-43a8-9251-9a38568a5890)

I hope this clears things up.

Thanks,
Ran~

**Comment by flaviut** [comment]
I see--that makes sense. I suppose this is a matter of me "holding it wrong". This is the area I see on my screen above the fold, but only the highlighted area has really useful information, and it doesn't stick out in any way:

![image](https://github.com/aws/aws-sdk-js-v3/assets/5213469/9c0e8580-12f9-4570-891d-dd7f2b0e07d5)

Fine if you want to leave it that way, but hopefully the source of my confusion is clear. I think this particular module might be an exception though--I clicked through a few other modules, and the emphasis is, correctly, on the commands:

![image](https://github.com/aws/aws-sdk-js-v3/assets/5213469/fae53092-02e8-4dd2-a7a7-7ac7e5b58076)

**Comment by RanVaknin** [comment]
Hi @flaviut ,

Thanks for the feedback. The new docs are definitely not perfect, and we are working on improving them.
Your feedback is valuable, and we will take it into consideration in future releases, perhaps making this more obvious. 

It seems like this is not an issue as of now. If you are running into additional issues in the future please dont hesitate to contact us. 

Thanks again!
Ran~
