### ISSUE TITLE
PRICING API - ENOTFOUND

### ISSUE THREAD

**Issue by poojagurubasappa** [aws/aws-sdk-js-v3#5001]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Error: getaddrinfo ENOTFOUND api.pricing.eu-west-1.amazonaws.com.

Unable to use the pricing api.

### SDK version number

"@aws-sdk/client-pricing": "^3.370.0"

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.13.2

### Reproduction Steps

Trying to programmatically invoke the pricing details through a nodejs application. 
`const client = new PricingClient({ region: "eu-west-1"});
  const input = {
    ServiceCode: "AmazonS3"
  }
  const command = new DescribeServicesCommand(input);
  const response = await client.send(command);
  return response;`

### Observed Behavior

Always receiving the error 
`Error: getaddrinfo ENOTFOUND api.pricing.eu-west-1.amazonaws.com
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)`

### Expected Behavior

Obtain the response

### Possible Solution

Check for the api url that the SDK invokes

**Comment by RanVaknin** [comment]
Hi @poojagurubasappa ,

This problem arises because the pricing API does not have a valid endpoint on `eu-west-1`. Based on the [service documentation](), the only two regions that it supports are `us-east-1` and `ap-south-1`.

> <h3 id="billing-pricing" style="color: rgb(22, 25, 31); font-size: 1.375em; font-weight: 700; line-height: 1.226em; margin-bottom: 0.75em; margin-top: 1.25em; padding: 0px; scroll-margin-top: 100px; font-family: &quot;Amazon Ember&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">AWS Price List Service</h3><div class="table-container" style="display: flex; flex-flow: row nowrap; margin: 20px 0px; color: rgb(22, 25, 31); font-family: &quot;Amazon Ember&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="table-contents" style="border-right-color: ; border-bottom-color: ; border-left-color: ; border-top: 1px solid var(--color-text-home-header-secondary-bkwtrh,#d5dbdb); box-shadow: rgba(0, 28, 36, 0.3) 0px 1px 1px 0px, rgba(0, 28, 36, 0.15) 1px 1px 1px 0px, rgba(0, 28, 36, 0.15) -1px 1px 1px 0px; display: inline-block; max-height: 60vh; overflow: auto;">
> 
> Region Name | Region | Endpoint | Protocol
> -- | -- | -- | --
> US East (N. Virginia) | us-east-1 | api.pricing.us-east-1.amazonaws.com | HTTPS
> Asia Pacific (Mumbai) | ap-south-1 | api.pricing.ap-south-1.amazonaws.com | HTTPS
> 
> </div></div>

To solve this problem:

```js
const client = new PricingClient({ region: "us-east-1"}); 
// rest of your code...
```

Thanks,
Ran~

**Comment by poojagurubasappa** [comment]
Thanks @RanVaknin . I figured that out. Is there a way to filter the results for eu-west-1 alone?

**Comment by RanVaknin** [comment]
Hi @poojagurubasappa ,

That is a good question. The service documentation is not super clear about this. From poking around at some internal implementations I can see you can specify a location attribute with the region you need:

```js
const { PricingClient, GetProductsCommand } = require("@aws-sdk/client-pricing"); 

const client = new PricingClient({ region: "us-east-1" });

const command = new GetProductsCommand({
    ServiceCode: "AmazonS3",
    Filters: [{
        Type: "TERM_MATCH",
        Field: "location",
        Value: "EU (Ireland)"
    }]
});


async function run(){
    try {
        const response = await client.send(command)
        console.log(response)
    } catch (error) {
        console.log(error)
    }
}
run()
```

I believe their API uses some uniform language that is used throughout AWS, in particular with services like EC2 to define filters like `location`. 
Unfortunately their docs are not clear about this. 
I hope you have the information you need to get unblocked.

let me know if you need anything else.
Thanks,
Ran~
