### ISSUE TITLE
S3Client send() didnt catch the error

### ISSUE THREAD

**Issue by Zakisu** [aws/aws-sdk-js-v3#5002]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

when i send command in S3Client.send() still throw an error even i have wrote the catch

### SDK version number

@aws-sdk/client-s3@3.370.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node 19.5

### Reproduction Steps

```
const s3_params = {
                Bucket: 'xxxx',
                Key: 'xxxx.pdf'
            }
            const command_head = new AWS.HeadObjectCommand(s3_params);
            const metadata = await s3.send(command_head, (err, data) => {
                // process err and data.
                if (err) {
                    console.error('not found');
                    reject(err);
                } else {
                    return data;
                }
            });
```

### Observed Behavior

not found (catch error message)
 NotFound: UnknownError
     at de_NotFoundRes (/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:6100:23)
     at de_HeadObjectCommandError (/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:4706:25)
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
     at async /node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
     at async /node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20
     at async /node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46
     at async /node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26 {
   '$fault': 'client',
   '$metadata': {
     httpStatusCode: 404,
     requestId: 'ab13cd00-d6cf-4086-ab64-0a2893d1d452',
     extendedRequestId: '2neauXNY+qA8ePcUqKzaAbcDeFGQos8L1dvPufI4OC2i9bHX9wgqTVkm0KEXso=',
     cfId: undefined,
     attempts: 1,
     totalRetryDelay: 0
   }
 }

### Expected Behavior

didnt throw the error, only console 'not found'

**Comment by RanVaknin** [comment]
Hi @Zakisu ,

Your code snippet is incomplete, but from what I can tell you are using v2 syntax with the v3 SDK and they are not designed the same way. For example, `send()` does not take a callback like v2 did. You should wrap your execution with a try/catch block to surface errors.

I assume you are running into this during migration from v2 to v3. I suggest that you give the [developer guide](https://github.com/aws/aws-sdk-js-v3/blob/main/README.md) a good read before doing this. 

Additionally I suggest you look through the [v3 docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/command/HeadObjectCommand/), and there are lots of examples on how to use the SDK. From the docs:

```js
import { S3Client, HeadObjectCommand } from "@aws-sdk/client-s3"; 
const client = new S3Client(config);
const input = { 
    // input1,
    // input2,
};
const command = new HeadObjectCommand(input);
const response = await client.send(command);
```

And if that doesn't help there is a whole [example repo](https://github.com/awsdocs/aws-doc-sdk-examples/tree/main/javascriptv3/example_code/s3#code-examples) you can refer to to see real life examples.

I hope this helps.
Thanks,
Ran~

**Comment by Zakisu** [comment]
> Hi @Zakisu ,
> 
> Your code snippet is incomplete, but from what I can tell you are using v2 syntax with the v3 SDK and they are not designed the same way. For example, `send()` does not take a callback like v2 did. You should wrap your execution with a try/catch block to surface errors.
> 
> I assume you are running into this during migration from v2 to v3. I suggest that you give the [developer guide](https://github.com/aws/aws-sdk-js-v3/blob/main/README.md) a good read before doing this.
> 
> Additionally I suggest you look through the [v3 docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/command/HeadObjectCommand/), and there are lots of examples on how to use the SDK. From the docs:
> 
> ```js
> import { S3Client, HeadObjectCommand } from "@aws-sdk/client-s3"; 
> const client = new S3Client(config);
> const input = { 
>     // input1,
>     // input2,
> };
> const command = new HeadObjectCommand(input);
> const response = await client.send(command);
> ```
> 
> And if that doesn't help there is a whole [example repo](https://github.com/awsdocs/aws-doc-sdk-examples/tree/main/javascriptv3/example_code/s3#code-examples) you can refer to to see real life examples.
> 
> I hope this helps. Thanks, Ran~

Hello @RanVaknin I used AWS SDK v3. We can use callbacks in send() (though it's not recommended). Maybe you need to read the docs: https://github.com/aws/aws-sdk-js-v3/tree/main/clients/client-s3#callbacks.
This is my code

```
const generateWatermark = async (params) => {
    return new Promise(async (resolve, reject) => {
        try {
            const now = moment().locale('id').format('DD MMMM YYYY')
            const s3 = new AWS.S3Client(config.aws);
            const s3_params = {
                Bucket: 'xxxxx',
                Key: 'xxxx.pdf'
            }
            const command_head = new AWS.HeadObjectCommand(s3_params);
            const metadata = await s3.send(command_head, (err, data) => {
                // process err and data.
                if (err) {
                    console.error('not found');
                    reject(err);
                } else {
                    return data;
                }
            });
            const command_object = new AWS.GetObjectCommand(s3_params);
            let url = await getSignedUrl(s3, command_object);
            axios({
                url: url,
                method: 'GET',
                responseType: 'arraybuffer'
            }).then(response => {
                resolve({ body: originalData, meta: metadata })
            }).catch(err => {
                reject(err)
            });
        } catch (error) {
            reject(error);
        }
    })
}
```
