### ISSUE TITLE
Command duplication in JavaScript SDK API docs

### ISSUE THREAD

**Issue by kovacstomi** [aws/aws-sdk-js-v3#5007]
### Describe the issue

The `AdminUpdateUserAttributesCommand` is defined two times. I assume one of them should be the non-admin `UpdateUserAttributesCommand`.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/client/cognito-identity-provider/

**Comment by RanVaknin** [comment]
Hi @kovacstomi ,

This does seem like a bug. Adding to our doc rework backlog. 
Thanks for letting us know.

All the best,
Ran~

**Comment by kuhe** [comment]
This is fixed in the official docs: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/cognito-identity-provider/

(without preview URL path)
