### ISSUE TITLE
[Bug][client-rekognitionstreaming] systemClockOffset Value does not affect signature date

### ISSUE THREAD

**Issue by thaddmt** [aws/aws-sdk-js-v3#5008]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Attempting to set the `systemClockOffset` config value does not seem to affect the date signature when signing requests. When manually setting my system clock foward an hour and adding a `systemClockOffset` of -3600000 I still get an invalid signature exception like so:

```
Config code:
    const clientconfig: RekognitionStreamingClientConfig = {
      credentials,
      region: this.region,
      systemClockOffset: -3600000,
    };

System clock time: 17:22 GMT-0700

Error message: 
"{"Message":"Signature not yet current: 20230725T002213Z is still later than 20230724T232718Z (20230724T232218Z + 5 min.)"}"
```

### SDK version number

@aws-sdk/client-rekognitionstreaming@3.360.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Chrome 114

### Reproduction Steps

1. Set system clock ahead one hour
2. Add config for `systemClockOffset` minus one hour (3600000 ms)
3. Attempt to start create a `StartFaceLivenessSessionCommand`
```
    const clientconfig: RekognitionStreamingClientConfig = {
      credentials,
      region: this.region,
      systemClockOffset: -3600000,
    };
    this._client = new RekognitionStreamingClient(clientconfig);

const response = await this._client.send(
      new StartFaceLivenessSessionCommand({
        ChallengeVersions: 'FaceMovementAndLightChallenge_1.0.0',
        SessionId: this.sessionId,
        LivenessRequestStream: livenessRequestGenerator,
        VideoWidth: this.videoEl.videoWidth.toString(),
        VideoHeight: this.videoEl.videoHeight.toString(),
      })
    );
```
5. Receive error for invalid signature exception

### Observed Behavior

Received error for an invalid signature exception

### Expected Behavior

Request should succeed, system clock offset should counterbalance the system clock

**Comment by thaddmt** [comment]
Added a minimal repro branch here - https://github.com/thaddmt/aws-sdk-js-tests/tree/liveness-clock-offset

Added instructions on using the branch here, copied below for clarity - https://github.com/aws-samples/aws-sdk-js-tests/pull/150

- `yarn install`; `yarn start:web`
- Set system clock one hour ahead
- Inspect network tab for the `StartFaceLivenessSesssion` API and see error from server about invalid signature exception

<img width="1336" alt="Screenshot 2023-07-25 at 11 35 45 AM" src="https://github.com/aws-samples/aws-sdk-js-tests/assets/68032955/149fcf1f-dd23-4fd9-8582-68253dd934e7">

**Comment by trivikr** [comment]
The systemClockOffset needs to be passed in client configuration.

Commented in https://github.com/aws-samples/aws-sdk-js-tests/pull/150/files#r1273913897

@thaddmt Can you verify this fix? We verified it with STS getCallerIdentity operation.

**Comment by thaddmt** [comment]
Yep was my mistake on the STS branch only. On STS the systemClockOffset was in the wrong place.

But on the rekognitiongstreaming branch i still see the issue

**Comment by thaddmt** [comment]
if it helps at all, when the STS getCallerIdentity call fails it throws an error without returning a response.

When the StartFaceLivenessSession command fails it successfully returns a response, establishes a websocket connection but the ws connection immediately returns the invalid signature exception

**Comment by thaddmt** [comment]
Re-opening with a more concise ticket - https://github.com/aws/aws-sdk-js-v3/issues/5011
