### ISSUE TITLE
[bug][rekognitionstreaming] Signature not yet current

### ISSUE THREAD

**Issue by thaddmt** [aws/aws-sdk-js-v3#5011]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Minimal repro - https://github.com/aws-samples/aws-sdk-js-tests/pull/150

When manually setting the system clock ahead one hour and attempting to run the `StartFaceLivenessSession` command, the connection is established but the server immediately returns an InvalidSignatureException on the ws connection.

<img width="1336" alt="Screenshot 2023-07-25 at 11 35 45 AM" src="https://github.com/aws/aws-sdk-js-v3/assets/68032955/7078370a-4620-4c7d-a19b-f1491a26d0cf">

Using the `systemClockOffset` configuration does not seem to have an effect on this error message.

```
Config code:
    const clientconfig: RekognitionStreamingClientConfig = {
      credentials,
      region: this.region,
      systemClockOffset: -3600000,
    };

System clock time: 17:22 GMT-0700

Error message: 
"{"Message":"Signature not yet current: 20230725T002213Z is still later than 20230724T232718Z (20230724T232218Z + 5 min.)"}"
```

### SDK version number

@aws-sdk/client-rekognitionstreaming@3.360.0

### Which JavaScript Runtime is this issue in?

Browser

### Details of the browser/Node.js/ReactNative version

Chrome 114

### Reproduction Steps

1. pull down repro branch and run `yarn install` - https://github.com/aws-samples/aws-sdk-js-tests/pull/150
2. Set system clock ahead one hour
3. Run `yarn start:web` on repro branch

### Observed Behavior

When opening the repro app browser console network tab, you can inspect the `StartFaceLivenessSession` network request and the first message will be an `InvalidSignatureException`

<img width="1336" alt="Screenshot 2023-07-25 at 11 35 45 AM" src="https://github.com/aws/aws-sdk-js-v3/assets/68032955/d4b8a64f-3e73-4ed8-91dd-3c6c2df69ac1">

### Expected Behavior

Should not have an invalid signature exception

### Possible Solution

Possibly because systemClockOffset is not applied correctly to the signature?

**Comment by thaddmt** [comment]
When setting the systemClockOffset value to -360000 I see that the X-Amz-Date header value is not updated correctly with -360000, but when setting that value in other API's, like the sts `GetCallerIdentity` I see that value is updated correctly

**Comment by trivikr** [comment]
The issue appears to be with systemClockOffset not being applied when signing an event stream in middleware-websocket 

https://github.com/aws/aws-sdk-js-v3/blob/53df336b65f8dc5a73ec4ef149edcc4e8d539b18/packages/middleware-websocket/src/get-event-signing-stream.ts#L20

**Comment by trivikr** [comment]
A workaround was posted in https://github.com/thaddmt/aws-sdk-js-tests/pull/1

@thaddmt Can you verify if the workaround works for your use case?

**Comment by trivikr** [comment]
Fix posted at https://github.com/aws/aws-sdk-js-v3/pull/5015
