### ISSUE TITLE
code snippet copied sits over the nav bar weirdly

### ISSUE THREAD

**Issue by mewc** [aws/aws-sdk-js-v3#5013]
### Describe the issue

![Screenshot 2023-07-26 at 4 57 29 pm](https://github.com/aws/aws-sdk-js-v3/assets/15105417/2968829a-e332-4e8b-a9db-0ea83dfc5a41)

![Screenshot 2023-07-26 at 4 58 10 pm](https://github.com/aws/aws-sdk-js-v3/assets/15105417/9f8edfa3-013c-4029-9259-d253e477e61b)

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/

**Comment by RanVaknin** [comment]
Hi @mewc ,

Thanks for reaching out. 
I'm not sure I follow what seems to be the problem. The copy button is added to the bottom right of the overall container.
Is there a specific issue in the way it is being displayed? I was able to scroll and copy the code fine. 

If you have a better idea please feel free to draw / link some other docs that do it better so we can review this as a team.

Thanks!
Ran~

**Comment by mewc** [comment]
> Hi @mewc ,
> 
> Thanks for reaching out. 
> I'm not sure I follow what seems to be the problem. The copy button is added to the bottom right of the overall container.
> Is there a specific issue in the way it is being displayed? I was able to scroll and copy the code fine. 
> 
> If you have a better idea please feel free to draw / link some other docs that do it better so we can review this as a team.
> 
> Thanks!
> Ran~

Hi ran, the z index is wrong as it sits over the nav bar when scrolling when it should be under, with the rest of the page

**Comment by RanVaknin** [comment]
Hi @mewc ,

I believe the intention was for it to float above the entire container, and if I had to guess this is "baked" in with the documentation engine. 

Unless it's something that is blocking the view from the code snippet itself / preventing customers from scrolling snippet, the team will likely not prioritize this.

We do appreciate your feedback, and if this is still an issue you are passionate about, please feel free to open a discussion on the discussions tab. 

Thanks again!
Ran~
