### ISSUE TITLE
What is the value of the config? 

### ISSUE THREAD

**Issue by sanjay-growexxer** [aws/aws-sdk-js-v3#5019]
### Describe the issue

Why is the value of the variable config not given in this example? 

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/ssm/command/GetDocumentCommand/

**Comment by RanVaknin** [comment]
Hi @sanjay-growexxer ,

The config spec is found in the [client page itself](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/ssm/), at the bottom of the page:
<img width="1331" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/50976344/88c63676-a5da-411f-9c4f-c4a380dfc0b0">

I hope this helps,
Thanks,
Ran~
