### ISSUE TITLE
new S3Client() , The property “disableHostPrefix” is not effective.

### ISSUE THREAD

**Issue by A-afflatus** [aws/aws-sdk-js-v3#5022]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

```json
{
    region: "******",
    endpoint: "https://******",
    credentials: {
      accessKeyId: "******",
      secretAccessKey: "******"
    },
    disableHostPrefix: true
  }
```
I expect it to be like this:
 http://host/bucketName/...
But the final access is still：
http://backetName.host/....
I am very distressed right now！！！
The file list request is still accessing as follows.
<img width="356" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/130149563/f7214b9b-c9bd-4613-bce2-0542ac1a3767">

### SDK version number

 "@aws-sdk/client-s3": "^3.379.1",

### Which JavaScript Runtime is this issue in?

Browser

### Details of the browser/Node.js/ReactNative version

electron react 18.2.0

### Reproduction Steps

```ts
new S3Client({
          ...client,
          disableHostPrefix: true,
        })
```

### Observed Behavior

http://bucketName.host/

### Expected Behavior

http://host/bucketName/

**Comment by RanVaknin** [comment]
Hi @A-afflatus ,

You need to use `ForcePathStyle` instead of `disableHostPrefix`
That would ensure the bucket endpoint would be treated as a path style bucket endpoint rather than the default virutal hosted bucket endpoint.

Thanks,
Ran~

**Comment by A-afflatus** [comment]
Thank you very much
