### ISSUE TITLE
Shape not found

### ISSUE THREAD

**Issue by SteveEarl-AWS** [aws/aws-sdk-js-v3#5024]
### Describe the issue

```json
{"name":"EvaluationFormItem.SectionMember","pkg":"@aws-sdk/client-connect","type":"Interface","text":"SectionMember"}
```

I'm getting a message "Sorry, we couldn't find that shape" when attempting to view the SectionMember docs.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/connect/command/DescribeEvaluationFormCommand/

**Comment by RanVaknin** [comment]
duplicate https://github.com/aws/aws-sdk-js-v3/issues/5023
