### ISSUE TITLE
getSignedUrl not working

### ISSUE THREAD

**Issue by lakshmankashyap** [aws/aws-sdk-js-v3#5030]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

error TS2345: Argument of type 'S3Client' is not assignable to parameter of type 'Client<any, ServiceInputTypes, MetadataBearer, any>'.
  The types of 'middlewareStack.concat' are incompatible between these types.
    Type '<InputType extends ServiceInputTypes, OutputType extends ServiceOutputTypes>(from: MiddlewareStack<InputType, OutputType>) => MiddlewareStack<...>' is not assignable to type '<InputType extends ServiceInputTypes, OutputType extends MetadataBearer>(from: MiddlewareStack<InputType, OutputType>) => MiddlewareStack<InputType, OutputType>'.
      Types of parameters 'from' and 'from' are incompatible.
        Type 'MiddlewareStack<InputType, OutputType>' is not assignable to type 'MiddlewareStack<InputType, ServiceOutputTypes>'.
          Types of property 'addRelativeTo' are incompatible.
            Type '(middleware: MiddlewareType<InputType, OutputType>, options: RelativeMiddlewareOptions) => void' is not assignable to type '(middleware: MiddlewareType<InputType, ServiceOutputTypes>, options: RelativeMiddlewareOptions) => void'.
              Types of parameters 'middleware' and 'middleware' are incompatible.
                Type 'MiddlewareType<InputType, ServiceOutputTypes>' is not assignable to type 'MiddlewareType<InputType, OutputType>'.
                  Type 'InitializeMiddleware<InputType, ServiceOutputTypes>' is not assignable to type 'MiddlewareType<InputType, OutputType>'.
                    Type 'InitializeMiddleware<InputType, ServiceOutputTypes>' is not assignable to type 'InitializeMiddleware<InputType, OutputType>'.
                      Call signature return types 'InitializeHandler<InputType, ServiceOutputTypes>' and 'InitializeHandler<InputType, OutputType>' are incompatible.
                        Type 'Promise<InitializeHandlerOutput<ServiceOutputTypes>>' is not assignable to type 'Promise<InitializeHandlerOutput<OutputType>>'.
                          Type 'InitializeHandlerOutput<ServiceOutputTypes>' is not assignable to type 'InitializeHandlerOutput<OutputType>'.
                            Types of property 'output' are incompatible.
                              Type 'ServiceOutputTypes' is not assignable to type 'OutputType'.
                                'ServiceOutputTypes' is assignable to the constraint of type 'OutputType', but 'OutputType' could be instantiated with a different subtype of constraint 'MetadataBearer'.
                                  Type 'AbortMultipartUploadCommandOutput' is not assignable to type 'OutputType'.
                                    'AbortMultipartUploadCommandOutput' is assignable to the constraint of type 'OutputType', but 'OutputType' could be instantiated with a different subtype of constraint 'MetadataBearer'.

### SDK version number

@aws-sdk/package-name@version, ...

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.18.1 

### Reproduction Steps

// Create the config obj with credentials
// Always use environment variables or config files
const s3Configuration: S3ClientConfig = {
  apiVersion: '2006-03-01',
  region: process.env.AWS_REGION,
  credentials: {
    accessKeyId: process.env.AWS_S3_ACCESS_KEY || '',
    secretAccessKey: process.env.AWS_S3_ACCESS_SECRET || '',
  },
};

// Instantiate a new s3 client
const s3 = new S3Client(s3Configuration);

  return await getSignedUrl(s3, command, { expiresIn: 604800 });

### Observed Behavior

May be due to typescript

### Expected Behavior

May be due to typescript

**Comment by SerhiiProdan** [comment]
Can confirm the exact same issue.

**Comment by esinx** [comment]
If you have any other @aws-sdk/* package installed along with the package you are trying to use, see if their versions all match. 

I had the exact same issue and resolved by upgrading the outdated packages with mismatched  versions.

<img width="470" alt="Screenshot 2023-08-01 at 2 44 29 AM" src="https://github.com/aws/aws-sdk-js-v3/assets/62971511/970c7721-bdb7-4993-9e4f-3516b9c1ac77">

<img width="488" alt="Screenshot 2023-08-01 at 2 44 42 AM" src="https://github.com/aws/aws-sdk-js-v3/assets/62971511/1a85bde3-305f-467b-894c-f1aa23cd61f3">

**Comment by RanVaknin** [comment]
@esinx is correct. 
the presigner and s3 client are meant to be used together and the versions should match. 

@lakshmankashyap  can you please run `npm i @aws-sdk/s3-request-presigner @aws-sdk/client-s3` and see if this solves your issue? 

Thanks,
Ran~

**Comment by SerhiiProdan** [comment]
So here is my `yarn why` output. 

![Screenshot 2023-08-02 at 11 48 14 AM](https://github.com/aws/aws-sdk-js-v3/assets/110036376/33ad8bfd-706c-4cdb-8cae-10c538f02d4c)

As soon as I use yarn workspaces some peer dependencies are sharing an outdated version of `@smithy/smithy-client`.
I think that causing a problem on my side.

**Comment by RanVaknin** [comment]
In order to make sure there are no transitive dependencies that are causing a version mismatch, and to ensure the SDK imports the `@smithy` dependencies you can try deleting your `package-lock.json` and `node_modules` and then run `npm install` and let npm resolve the dependency tree correctly. 

Thanks,
Ran~
