### ISSUE TITLE
Missing Required Parameter in Docs

### ISSUE THREAD

**Issue by Rosslington** [aws/aws-sdk-js-v3#5031]
### Describe the issue

The docs do not state that "MessageGroupID" is required for the "SendMessageCommand".

MissingParameter: The request must contain the parameter MessageGroupId.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/sqs/command/SendMessageCommand/

**Comment by RanVaknin** [comment]
Hi @Rosslington ,

`MessageGroupID` is only required for FIFO queues, and this is covered in the documentation:

>This parameter applies only to FIFO (first-in-first-out) queues.
>
>The tag that specifies that a message belongs to a specific message group. Messages that belong to the same message group are processed in a FIFO manner (however, messages in different message groups might be processed out of order). To interleave multiple ordered streams within a single queue, use MessageGroupId values (for example, session data for multiple users). In this scenario, multiple consumers can process the queue, but the session data of each user is processed in a FIFO fashion.
>
>You must associate a non-empty MessageGroupId with a message. If you don't provide a MessageGroupId, the action fails.
>
>ReceiveMessage might return messages with multiple MessageGroupId values. For each MessageGroupId, the messages are sorted by time sent. The caller can't specify a MessageGroupId.
>
>The length of MessageGroupId is 128 characters. Valid values: alphanumeric characters and punctuation (!"#$%&'()*+,-./:;=?[]^_{|}~).
>
>For best practices of using MessageGroupId, see [Using the MessageGroupId Property ](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/using-messagegroupid-property.html)
 in the Amazon SQS Developer Guide.
>
>MessageGroupId is required for FIFO queues. You can't use it for Standard queues.

So if your queue is not a FIFO queue, this parameter is not required. Unfortunately the operation docs are directly generated from the Service's API docs, and the SDK team cannot change them. If you have feedback on how to make this documentation better, consider leaving the SQS team [feedback](https://docs-feedback.aws.amazon.com/feedback.jsp?feedback_destination_id=ff583b9e-7b1c-4133-9c4c-745b070bb05e&topic_url=https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SendMessage.html#SQS-SendMessage-request-MessageGroupId).

Thanks,
Ran~
