### ISSUE TITLE
New documentation does not tell you which input parameters are required or optional. Old docs do.

### ISSUE THREAD

**Issue by paul-uz** [aws/aws-sdk-js-v3#5033]
### Describe the issue

New docs - https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-opensearch/Interface/UpdateDomainConfigCommandInput/

Old docs - https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-opensearch/interfaces/updatedomainconfigcommandinput.html

Old docs actually tell you which members are required or optional. Looks like AWS have taken 1 step forward, 2 steps back.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-opensearch/Interface/UpdateDomainConfigCommandInput/

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-opensearch/interfaces/updatedomainconfigcommandinput.html

**Comment by RanVaknin** [comment]
Hi @paul-uz ,

Thanks for opening this issue. 
The intended page to look at the input parameters is the operation doc itself: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/opensearch/command/UpdateDomainConfigCommand

The way I got there is: Main page-> opensearch (on the left nav bar) -> operation name.

However, I agree that even if you wanted to pull up the interface (from say, the search bar) the required info should be present. 
I'll add it to the backlog, this will get picked up as a bigger effort to smooth some sharp edges we have in the new docs.

Thanks again for your feedback.
Ran~

**Comment by RanVaknin** [comment]
We have looked into this, and the proposed solution was to make the actual operation page (containing the required/ optional info) more prominent to direct customers to it. We are unable at this time to "patch" this interface page because of limitations of the documentation engine.
