### ISSUE TITLE
Bug in @aws-sdk/lib-dynamodb - '@smithy/smithy-client' not found

### ISSUE THREAD

**Issue by QUTOnline** [aws/aws-sdk-js-v3#5035]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I am receiving the following error when using lib-dynamodb: 

```shell
"Runtime.ImportModuleError: Error: Cannot find module '@smithy/smithy-client'",
        "Require stack:",
        "- /var/task/node_modules/@aws-sdk/lib-dynamodb/dist-cjs/commands/BatchExecuteStatementCommand.js",
        "- /var/task/node_modules/@aws-sdk/lib-dynamodb/dist-cjs/DynamoDBDocument.js",
        "- /var/task/node_modules/@aws-sdk/lib-dynamodb/dist-cjs/index.js"
```

It looks like @smithy/smithy-client is listed as a dev dependency but is required in the core code of the package. As such is not installed when using the package and this error is received.

### SDK version number

@aws-sdk/lib-dynamodb@3.379.1

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.16.0

### Reproduction Steps

Simply requiring something from this package creates this error:

`const { DynamoDBDocumentClient } = require('@aws-sdk/lib-dynamodb');`

### Observed Behavior

```shell
"Runtime.ImportModuleError: Error: Cannot find module '@smithy/smithy-client'",
        "Require stack:",
        "- /var/task/node_modules/@aws-sdk/lib-dynamodb/dist-cjs/commands/BatchExecuteStatementCommand.js",
        "- /var/task/node_modules/@aws-sdk/lib-dynamodb/dist-cjs/DynamoDBDocument.js",
        "- /var/task/node_modules/@aws-sdk/lib-dynamodb/dist-cjs/index.js"
```

### Expected Behavior

Not an error.

### Possible Solution

Move the package into dependencies maybe?

**Comment by RanVaknin** [comment]
Hi @QUTOnline, 

Unfortunately Im not able to reproduce the reported issue. 

I created a new js project,
```console
$ npm init -y

{
  "name": "5035",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {},
  "description": ""
}

$ npm i @aws-sdk/lib-dynamodb
$ npm list 
5035@1.0.0 /Users/rvaknin/test_folder/5035
└── @aws-sdk/lib-dynamodb@3.379.1
```

With this code:
```js
const { DynamoDBDocumentClient } = require('@aws-sdk/lib-dynamodb');

console.log("requiring module works.")
```

```console
$ node sample.js
requiring module works.
```

Can you provide any additional information that can be used to reproduce this issue?

Thanks,
Ran~

**Comment by Chaoste** [comment]
I'm seeing the same error on my side in our CI pipeline but also locally if I install solely the production dependencies with `npm install --omit=dev`.

**Comment by radahh-rest** [comment]
We see this issue in our dependabot build whilst running jest tests:
```
FAIL src/<snip>.test.ts
  ● Test suite failed to run

    Cannot find module '@smithy/smithy-client' from 'node_modules/@aws-sdk/lib-dynamodb/dist-cjs/commands/BatchExecuteStatementCommand.js'

    Require stack:
      node_modules/@aws-sdk/lib-dynamodb/dist-cjs/commands/BatchExecuteStatementCommand.js
      node_modules/@aws-sdk/lib-dynamodb/dist-cjs/DynamoDBDocument.js
      node_modules/@aws-sdk/lib-dynamodb/dist-cjs/index.js
      src/<snip>.test.ts

    > 1 | import { DeleteCommand, DynamoDBDocumentClient, GetCommand, UpdateCommand } from '@aws-sdk/lib-dynamodb';
        | ^
      2 | import { Logger } from '<snip>';
      3 | import { mockClient } from 'aws-sdk-client-mock';
      4 | import 'aws-sdk-client-mock-jest';

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.<anonymous> (node_modules/@aws-sdk/lib-dynamodb/dist-cjs/commands/BatchExecuteStatementCommand.js:5:25)
      at Object.<anonymous> (node_modules/@aws-sdk/lib-dynamodb/dist-cjs/DynamoDBDocument.js:4:40)
      at Object.<anonymous> (node_modules/@aws-sdk/lib-dynamodb/dist-cjs/index.js:4:22)
```

**Comment by RanVaknin** [comment]
Hi all, 

I have still yet to hear back about reproduction steps. 

One thing I can suggest is to delete node_modules and package-lock.json and re-run `npm install` 

As is stands this is not reproducible. 

Waiting back to hear back about actionable repro steps.
Thanks,
Ran~

**Comment by Chaoste** [comment]
Can't reproduce it anymore even when only installing prod dependencies. I assume that at the time of writing, this was caused since the simthy client was only defined as peer dep. Probably that was fixed again :)
