### ISSUE TITLE
ExportApiCommand returns an error screen on the apigatewayv2 docs

### ISSUE THREAD

**Issue by cshields236** [aws/aws-sdk-js-v3#5037]
### Describe the issue

- The command also has no summary on the apigatewayv2 page
- After reaching the error screen the documentation pages become unresponsive until the browser window is refreshed

![image](https://github.com/aws/aws-sdk-js-v3/assets/42182485/d10363f3-8902-4637-a51f-d5b822a72d48)

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/apigatewayv2/command/ExportApiCommand/

**Comment by ajredniwja** [comment]
Maybe similar to: https://github.com/aws/aws-sdk-js-v3/issues/5085

**Comment by kuhe** [comment]
note to maintainers, this is different from https://github.com/aws/aws-sdk-js-v3/issues/5085. 

this is due to the operation having no documentation trait, causing the structural examples not to be appended to anything because no docblock is generated.

**Comment by kuhe** [comment]
the fix will take a few days to make it into the docs site
