### ISSUE TITLE
Process unexpectedly terminates while mixing getObject and uploads using the same client

### ISSUE THREAD

**Issue by hugoArregui** [aws/aws-sdk-js-v3#5039]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

While mixing getObject requests and uploads in the same s3 client, the process unexpectedly terminates

### SDK version number

@aws-sdk/client-s3@3.379.1,@aws-sdk/lib-storage@3.379.1

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.12.1

### Reproduction Steps

```js
import { Upload } from '@aws-sdk/lib-storage'
import { S3 } from '@aws-sdk/client-s3'
import { randomBytes } from 'crypto'
import { Readable } from 'stream'
import 'dotenv/config'

const totalSamples = 100
const sampleSize = 1024 * 1024

const prefix = 'test'

async function main() {
  const bucket = process.env.S3_BUCKET

  const client = new S3({ region: 'us-east-1' })

  const uploads: Upload[] = []
  const queries: Promise<any>[] = []
  const samples: Readable[] = []

  for (let i = 0; i < totalSamples; i++) {
    samples.push(Readable.from(randomBytes(sampleSize)))
  }

  for (let i = 0; i < totalSamples; i++) {
    const sample = samples[i]
    const key = `${prefix}/test-${i}`
    const upload = new Upload({
      params: {
        Bucket: bucket,
        Key: key,
        Body: sample
      },
      client,
      queueSize: 3
    })
    upload.on('httpUploadProgress', (progress) => {
      console.log(key, progress)
    })
    uploads.push(upload)
  }

  for (let i = 0; i < totalSamples * 2; i++) {
    const j = Math.floor(Math.random() * 100)
    const key = `${prefix}/test-${j}`
    queries.push(client.getObject({ Bucket: bucket, Key: key }))
  }

  console.log('Running')
  try {
    await Promise.all([Promise.all(uploads.map((u) => u.done())), Promise.all(queries)])
    console.log('ok')
  } catch (err) {
    console.log('ERROR', err)
  }
}

main().catch(console.error)
```

### Observed Behavior

You may need to execute the script twice, the first one the objects are not there so the getobject will fail, the second time the process is exited, not by an error not by a successful termination.

This is the current output:

```
❯ yarn build && node dist/script.js
$ tsc -p tsconfig.json
Done in 1.05s.
Running
```

### Expected Behavior

The process to complete, either by error or by a successful termination

**Comment by yenfryherrerafeliz** [comment]
Hi @hugoArregui, thanks for opening this report. Could you please update to the latest version of the SDK and see if that behavior happens there for you?. I tried to replicate the issue on my end but everything worked just fine.
Here is the code I have used:
```js
import { Upload } from '@aws-sdk/lib-storage'
import { S3 } from '@aws-sdk/client-s3'
import { randomBytes } from 'crypto'
import { Readable } from 'stream'

const totalSamples = 10
const sampleSize = 1024 * 1024

const prefix = 'test'

async function main() {
    const bucket = process.env.TEST_BUCKET
    const client = new S3({ region: 'us-east-2' })
    const uploads = []
    const queries = []
    const samples = []

    for (let i = 0; i < totalSamples; i++) {
        samples.push(Readable.from(randomBytes(sampleSize)))
    }

    for (let i = 0; i < totalSamples; i++) {
        const sample = samples[i]
        const key = `${prefix}/test-${i}`
        const upload = new Upload({
            params: {
                Bucket: bucket,
                Key: key,
                Body: sample
            },
            client,
            queueSize: 3
        })
        upload.on('httpUploadProgress', (progress) => {
            console.log(key, progress)
        })
        uploads.push(upload)
    }

    for (let i = 0; i < totalSamples * 2; i++) {
        const j = Math.floor(Math.random() * totalSamples)
        const key = `${prefix}/test-${j}`
        queries.push(client.getObject({ Bucket: bucket, Key: key }).then((response) => {
            console.log("GetObject for key: ", key)
        }))
    }

    console.log('Running')
    try {
        const promises = uploads.map((u) => u.done().then((response) => {
            console.log("Upload for: ", response.ETag)
        })).concat(queries);
        await Promise.all(promises)
        console.log('ok')
    } catch (err) {
        console.log('ERROR', err)
    }
}

main().catch(console.error)
```
Here is the results I got:
```
GetObject for key:  test/test-0
GetObject for key:  test/test-1
GetObject for key:  test/test-1
GetObject for key:  test/test-5
GetObject for key:  test/test-5
GetObject for key:  test/test-7
GetObject for key:  test/test-1
GetObject for key:  test/test-8
GetObject for key:  test/test-8
GetObject for key:  test/test-8
GetObject for key:  test/test-6
GetObject for key:  test/test-1
GetObject for key:  test/test-7
GetObject for key:  test/test-2
GetObject for key:  test/test-9
GetObject for key:  test/test-5
GetObject for key:  test/test-9
GetObject for key:  test/test-9
GetObject for key:  test/test-3
GetObject for key:  test/test-4
test/test-7 {
  loaded: 1048576,
  total: 1048576,
  part: 1,
  Key: 'test/test-7',
  Bucket: 'MYBUCKET'
}
Upload for:  "4c25f3e72d5437edce7f3ced3a1f5302"
test/test-5 {
  loaded: 1048576,
  total: 1048576,
  part: 1,
  Key: 'test/test-5',
  Bucket: 'MYBUCKET'
}
Upload for:  "23a73491686880127c6e31595a8cc9f2"
test/test-4 {
  loaded: 1048576,
  total: 1048576,
  part: 1,
  Key: 'test/test-4',
  Bucket: 'MYBUCKET'
}
Upload for:  "12908211f77b2a93ecfd37709b604335"
test/test-6 {
  loaded: 1048576,
  total: 1048576,
  part: 1,
  Key: 'test/test-6',
  Bucket: 'MYBUCKET'
}
Upload for:  "fa3e9a5e19d3904bffbb449bf21bd1f8"
test/test-1 {
  loaded: 1048576,
  total: 1048576,
  part: 1,
  Key: 'test/test-1',
  Bucket: 'MYBUCKET'
}
Upload for:  "259db42df462ed03f1391437b01017c1"
test/test-2 {
  loaded: 1048576,
  total: 1048576,
  part: 1,
  Key: 'test/test-2',
  Bucket: 'MYBUCKET'
}
Upload for:  "18d10a709bbcb7bd8493464d8a83d5b0"
test/test-0 {
  loaded: 1048576,
  total: 1048576,
  part: 1,
  Key: 'test/test-0',
  Bucket: 'MYBUCKET'
}
Upload for:  "a686e84cde14709bba7a7690b96e885e"
test/test-3 {
  loaded: 1048576,
  total: 1048576,
  part: 1,
  Key: 'test/test-3',
  Bucket: 'MYBUCKET'
}
Upload for:  "de41fcaf543a2a13963a2fbf21bcc302"
test/test-8 {
  loaded: 1048576,
  total: 1048576,
  part: 1,
  Key: 'test/test-8',
  Bucket: 'MYBUCKET'
}
Upload for:  "eaf993921801b857357b61edb0d5a131"
test/test-9 {
  loaded: 1048576,
  total: 1048576,
  part: 1,
  Key: 'test/test-9',
  Bucket: 'MYBUCKET'
}
Upload for:  "b0d64e12b14755903f41d6890150df5d"
ok

```

Please let me know.

Thanks!

**Comment by hugoArregui** [comment]
@yenfryherrerafeliz thanks for taking a look, I can still reproduce it with version `3.398.0`, have you tried running it twice right? because the first time it finished on my machine as well, since there is nothing to download.

**Comment by yenfryherrerafeliz** [comment]
@hugoArregui, yes, I made sure the objects get created, and after that I tried many times but did not see the issue. However, if this happens at your end I can try to find which scenario causes this. However, if you think is there any other detail I should consider please let me know. Also, have you tried this with creating a new project from scratch?

Please let me know.

Thanks!

**Comment by yenfryherrerafeliz** [comment]
@hugoArregui I will clone your repo and test.

**Comment by lukeTheWizard** [comment]
Is this fixed? I am getting the same behavior on "@aws-sdk/lib-storage": "^3.410.0"

**Comment by marianogoldman** [comment]
We are still able to reproduce it by using the code in the repo @hugoArregui created above.

**Comment by Olian04** [comment]
I'm also seeing this. Do we know what's causing it?

**Comment by aBurmeseDev** [comment]
HI everyone - I'm following up on the issue that was previously raised. I want to clarify if this is still a valid and ongoing issue or if it has been resolved with the recent version updates. I wasn't able to reproduce this behavior on my end with latest version.

If you are still experiencing the behavior mentioned earlier, please try the approach suggested in the comment above, which involves collecting the stream data.

**Comment by hugoArregui** [comment]
> I can't reproduce it with the provided code.
> 
> Can you try the following? When you retrieve an object, collect the stream instead of letting it hang there.
> 
> ```js
> const getObject = client.getObject({ ... });
> 
> await getObject.Body?.transformToString(); // collects the stream.
> ```

This works great, but my example was a minimal example trying to reproduce what I believe is a problem since it's something that should work. So although this would be a fix and I appreciate the response, I think the underlying problem still remains

**Comment by kuhe** [comment]
We can't collect the stream for you because we don't know where you intend to pipe the data.

As of the latest version, there should be a socket exhaustion warning before the application crashes.
