### ISSUE TITLE
Shape not found

### ISSUE THREAD

**Issue by leon-adarcewicz** [aws/aws-sdk-js-v3#5046]
### Describe the issue

```json
{"name":"AttributeValue.LMember","pkg":"@aws-sdk/client-dynamodb","type":"Interface","text":"LMember"}
```

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/client/dynamodb/command/PutItemCommand/

**Comment by yenfryherrerafeliz** [comment]
Hi @leon-adarcewicz, thanks for opening this issue. Can you please provide more details about what is being reported here?

Thanks!

**Comment by leon-adarcewicz** [comment]
Hi @yenfryherrerafeliz! 
Honestly I don't remember any more. I don't have any issues at the moment. 
I assume that this issue appeared when I tried migrate aws skd v2 to v3 and I tried to did it service by service. So at some point I tried to use sdk for Dynamo v3 alongside with aws sdk v2 package.

**Comment by kuhe** [comment]
https://github.com/aws/aws-sdk-js-v3/issues/5264

there is some contextual information about DynamoDB's unique atttributeValue system in https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-lib-dynamodb/
