### ISSUE TITLE
Optional parameters are not marked / hard to identify

### ISSUE THREAD

**Issue by vigne-Sh** [aws/aws-sdk-js-v3#5051]
### Describe the issue

What lead to this issue ?

* Was migrating the code packages which consumes  (aws-sdk) `v2` libraries  to `v3`

* When Referencing the latest api docs for migrating a function call in `EC2`

[DescribeVpcEndpointsCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/ec2/command/DescribeVpcEndpointsCommand/) shows the required input & output through `DescribeVpcEndpointsCommand Input ` & `DescribeVpcEndpointsCommand Output`

* looking at the alternate api reference - [API_DescribeVpcEndpoints](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeVpcEndpoints.html)

 * clearly states whether the params are required or not
 
 ```
 For Eg.
 
#  Filters params for the above mentioned function call 

Filter.N

    The filters.

        ip-address-type - The IP address type (ipv4 | ipv6).

        service-name - The name of the service.

        tag:<key> - The key/value combination of a tag assigned to the resource. Use the tag key in the filter name and the tag value as the filter value. For example, to find all resources that have a tag with the key Owner and the value TeamA, specify tag:Owner for the filter name and TeamA for the filter value.

        tag-key - The key of a tag assigned to the resource. Use this filter to find all resources assigned a tag with a specific key, regardless of the tag value.

        vpc-id - The ID of the VPC in which the endpoint resides.

        vpc-endpoint-id - The ID of the endpoint.

        vpc-endpoint-state - The state of the endpoint (pendingAcceptance | pending | available | deleting | deleted | rejected | failed).

        vpc-endpoint-type - The type of VPC endpoint (Interface | Gateway | GatewayLoadBalancer).

    Type: Array of [Filter](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Filter.html) objects
    
    Required: No
```

* And so does the deprecated API docs - [describevpcendpointscommandinput](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-ec2/interfaces/describevpcendpointscommandinput.html) of `v3`

`Properties`
[DryRun?](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-ec2/interfaces/describevpcendpointscommandinput.html#dryrun-333)
[Filters?](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-ec2/interfaces/describevpcendpointscommandinput.html#filters-110)
[MaxResults?](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-ec2/interfaces/describevpcendpointscommandinput.html#maxresults-114)
[NextToken?](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-ec2/interfaces/describevpcendpointscommandinput.html#nexttoken-228)
[VpcEndpointIds?](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-ec2/interfaces/describevpcendpointscommandinput.html#vpcendpointids-2)

* It would be great if those `?` or `Required` fields are present visibly in the latest API reference, will save some time and reduce the confusion. 

### Links

[latest v3 api reference ](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-ec2/Class/DescribeVpcEndpointsCommand/) - which needs change

[Deprecated v3 api reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-ec2/interfaces/describevpcendpointscommandinput.html)

[existing api reference](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeVpcEndpoints.html)

**Comment by RanVaknin** [comment]
Hi @vigne-Sh ,

Thanks for opening the issue. 

The new docs only annotate required params with the required keywords. Not required is not annotated at all. 
![image](https://github.com/aws/aws-sdk-js-v3/assets/50976344/6722f42d-8995-42cc-9828-ca47aad39d73)

Is this issue about marking non required params as not required? 

Thanks,
Ran~

**Comment by vigne-Sh** [comment]
Yes issue about marking non required params as `?` optional similar to 

<img width="944" alt="Screenshot 2023-08-07 at 6 14 55 PM" src="https://github.com/aws/aws-sdk-js-v3/assets/34839394/3ab654d1-34da-491f-8588-87c671a04c8f">

* I totally missed to noticed the `Required` tag next to `$metadata` till now. 

* Adding `?` ( optional ) to not-required `params` could make it easier to migrate the functions and easy to look through 

* Apart from that, rest of the details in docs is perfect ( was able to migrate from `v2` to `v3` in short span )
