### ISSUE TITLE
Region is missing in `upload` error in `@aws-sdk/lib-storage`

### ISSUE THREAD

**Issue by kikajanovcik** [aws/aws-sdk-js-v3#5052]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

It appears that when calling `upload.done()`, the region from client is not identified and the call throws `Error: Region is missing`.

I have seen this [similar bug ](https://github.com/aws/aws-sdk-js-v3/issues/4766) reported where the user adds `region` to `params` too, but this has not worked for me nor I saw it in the documentation.

### SDK version number

@aws-sdk/client-s3@3.369.0, @aws-sdk/lib-storage@3.383.0

### Which JavaScript Runtime is this issue in?

Browser

### Details of the browser/Node.js/ReactNative version

any

### Reproduction Steps

Sample code:

```js
const bucket = new S3Client({
  credentials: fromCognitoIdentityPool({
    identityPoolId: context.get('awsConfig').identityPoolId,
    logins: {
      'accounts.google.com': User.idToken(),
    },
    userIdentifier: User.getEmail(),
  }),
  region: 'us-east-1',
  endpoint,
  forcePathStyle: true,
  maxAttempts: 10,
});
};

const upload = new Upload({
  client: bucket,
  params: {
    Bucket: context.get('awsConfig').attachmentsBucket,
    Key: key,
    ContentType: file.type,
    ContentDisposition: contentDisposition,
    Body: file,
  },
  queueSize: 1,
});

const data = await upload.done();
```

### Observed Behavior

Happens in `Upload.js` at

```js
const resolved = await Promise.all([this.client.send(new PutObjectCommand(params)), clientConfig?.endpoint?.()]);
```

### Expected Behavior

Upload works

**Comment by RanVaknin** [comment]
Hi @kikajanovcik ,

fromCognitoIdentityPool uses STS client under the hood, so you might need to add the region to the clientConfig object that you can pass into it:

```js
const bucket = new S3Client({
  credentials: fromCognitoIdentityPool({
    identityPoolId: context.get('awsConfig').identityPoolId,
    clientConfig: {region: 'us-east-1'},
    logins: {
      'accounts.google.com': User.idToken(),
    },
    userIdentifier: User.getEmail(),
  }),
  region: 'us-east-1',
  endpoint,
  forcePathStyle: true,
  maxAttempts: 10,
});
};
```

Let us know if this works. Thanks,
Ran~

**Comment by kikajanovcik** [comment]
Hi @RanVaknin,

This indeed solved the region issue, thanks! However now it throws an error below, which I was reading could be related to regions?

`SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method`

**Comment by RanVaknin** [comment]
Hi @kikajanovcik ,

If the SDK builds the endpoint correctly: `https://myurl.cloudfront.net/aws-bucket-name/path/to/file` Im not sure how constructing that same endpoint yourself solves the issue? 

My only speculation is that making the request to cloudfront might result in Cloudfront overwriting / adding some headers causing the signature calculated vs the signature sent to be different.

Can you please provide me with some more detail about your setup. What does manually building your own url looks like?

Thanks,
Ran~

**Comment by kikajanovcik** [comment]
Hi @RanVaknin,

I am not building this url, I am seeing it built by aws sdk to make the signing request. I believe it's incorrect because the `https://myurl.cloudfront.net` already points to `aws-bucket-name` so the `aws-bucket-name` should be omitted.

This is the existing code from v2:
```
const bucket = AWS.S3({
  endpoint,
  s3BucketEndpoint: true,
  maxRetries: 10,
  params: {
    Bucket: context.get('awsConfig').attachmentsBucket,
  },
});

const upload = bucket.upload(
  {
    Key: key,
    ContentType: file.type,
    ContentDisposition: contentDisposition,
    Body: file,
  },
  {
    queueSize: 1,
  }
);
```

Where the `Location` from the `upload.send` response is: `https://myurl.cloudfront.net/path/to/file`.

From what I see, `forcePathStyle` does not replace the `bucketEndpoint` functionality - is there any way I could achieve this?

**Comment by RanVaknin** [comment]
Hi @kikajanovcik ,

Thanks for the additional information. I can see the use case now. 
Im not entirely sure why `s3BucketEndpoint` was omitted, but we will review this as a team and potentially re-introduce this after a discussion. 

Stay tuned. 

Thanks,
Ran~

**Comment by tudou99** [comment]
I use 'S3Client' to upload files for private domain names.

Assuming the target address is`ip: port/test/{bucket}/{key}`. `/test` is reverse proxied by nginx

Normally, the s3 signature URL is/{bucket}/{key}

If the virtual domain name`/test` is added. The client signature is`/test/{bucket}/{key}`.

First, create the `S3Client`

```ts
const s3 = new S3Client({
    endpoint: ip:port,
});


// The request sent is: `ip:port/{bucket}/{key}`
// Local signature URL：`/{bucket}/{key}`
// service signature URL：`/{bucket}/{key}`
// So we need to intercept and process it here

 s3.middlewareStack.add(
    (next) => (args) => {
      args.request.path = "/test" + args.request.path;
      return next(args);
    },
    { step: "finalizeRequest" },
  );

// The request sent is: `ip:port/test/{bucket}/{key}`
// Local signature URL：`/{bucket}/{key}`
// service signature URL：`/{bucket}/{key}`
```

**Comment by kuhe** [comment]
A fix was released today that allows bucket inputs to serve as request endpoints.

https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.525.0 
https://www.npmjs.com/package/@aws-sdk/client-s3/v/3.525.0
