### ISSUE TITLE
Async Invocation of Lambda with Decoding text causes problems

### ISSUE THREAD

**Issue by brucedeen** [aws/aws-sdk-js-v3#5062]
### Describe the issue

with v2 the expectation was the async invoke returns a javascript object in Payload.

I had a helper method built around this and various interactions. 

We layered the string, or object as an option.

With v3 and it being a BLOB_VALUE isn't necessarily true when it's an Event Invoke. it is still an object payload.  Is it too much to ask for some of this to be backwards compatible and if it is, then can you update the documentation that says an empty Object if an Event invoke type otherwise a blob_value?

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/lambda/command/InvokeCommand/

**Comment by RanVaknin** [comment]
Hi @brucedeen ,

After testing this behavior with both v2 and v3, I can confirm that both versions are consistent in their handling of "Event" type invocations. Specifically, for asynchronous ("Event" type) invocations, Lambda processes asynchronous invocations by placing them in an internal queue to be processed independently, **_and the response will be sent with an empty payload._** This aligns with Lambda's documented behavior, and it's possible there's been some confusion regarding the expected outcome.

>Event – Invoke the function asynchronously. Send events that fail multiple times to the function's dead-letter queue (if one is configured). **_The API response only includes a status code._**

To shed some light on the current situation with JS SDK v3:
The `payload` type is generated into a BLOB as per the service's [API model specification](https://github.com/aws/aws-sdk-js-v3/blob/main/codegen/sdk-codegen/aws-models/lambda.json#L6307-L6311), and not as an object. This was done to prioritize cross-browser compatibility, as this ensures the SDK functions reliably across various web browsers and environments. As a direct consequence, certain responses, like the Lambda Payload, are presented in their raw binary form to ensure comprehensive compatibility. This choice implies that developers need to manually decode this data into a more readable format using tools like TextDecoder:

```js
const client = new LambdaClient({
    region: "us-east-1",
})

const command = new InvokeCommand({
    FunctionName: "myLambdaFunction",
    InvocationType: 'RequestResponse'
});

try {
    const response = await client.send(command);

    const decoder = new TextDecoder('utf-8');
    const decodedPayload = decoder.decode(response.Payload);

    console.log("raw payload:", response.Payload)
    console.log("decoded payload:", decodedPayload)
} catch (error) {
    console.log(error)
}
```

outputs:
```console
$ node sample.mjs
raw payload: Uint8ArrayBlobAdapter(50) [Uint8Array] [
  123,  34, 115, 116,  97, 116, 117, 115, 67, 111,
  100, 101,  34,  58,  50,  48,  48,  44, 34,  98,
  111, 100, 121,  34,  58,  34,  92,  34, 72, 101,
  108, 108, 111,  32, 102, 114, 111, 109, 32,  76,
   97, 109,  98, 100,  97,  33,  92,  34, 34, 125
]
decoded payload: {"statusCode":200,"body":"\"Hello from Lambda!\""}
```

>it is still an object payload. Is it too much to ask for some of this to be backwards compatible and if it is

We recognize this seems like an added step compared to v2, however, major version changes inherently come with alterations, and backward compatibility is never guaranteed. 

As far as a long term solution for this, we can convert this to a feature request in which we can implement something similar to the recently added Mixin types for s3.getObject method, by introducing utilities to streamline the handling of binary data.

I'll add this to our backlog. 

Thanks again.
Ran~
