### ISSUE TITLE
@aws-sdk/cloudfront-signer Not all code paths return a value

### ISSUE THREAD

**Issue by marwan-a** [aws/aws-sdk-js-v3#5063]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Getting a compilation error when using TypeScript `v4.2.3` with `noImplicitReturns: true` in the `tsconfig.json`.

```
node_modules/@aws-sdk/cloudfront-signer/src/sign.ts:333:3 - error TS7030: Not all code paths return a value.

333   setPolicyParameters({
      ~~~~~~~~~~~~~~~~~~~


Found 1 error.

```

### SDK version number

@aws-sdk/cloudfront-signer@3.378.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.14.0

### Reproduction Steps

Attempt to run `tsc` with package `@aws-sdk/cloudfront-signer` with `noImplicitReturns: true` in the `tsconfig.json`

### Observed Behavior

```
node_modules/@aws-sdk/cloudfront-signer/src/sign.ts:333:3 - error TS7030: Not all code paths return a value.

333   setPolicyParameters({
      ~~~~~~~~~~~~~~~~~~~


Found 1 error.

```

### Expected Behavior

Successful compliation

### Possible Solution

Specify return type

**Comment by RanVaknin** [comment]
Hi @marwan-a ,

Is the expectation that running `tsc` on a .ts file that just has the import line would cause this error?

Otherwise can you share some actual code that triggers this behavior? 

Thanks,
Ran~

**Comment by marwan-a** [comment]
Hi @RanVaknin 

The function `setPolicyParameters` returns `false`  `if (!url || !dateLessThan)`

Where the remainder of the function does not return a value. This returned boolean is not used where this function is called. 

Compiling my project while having the `TypeScript` option `noImplicitReturns: true` results in a compilation error `TS7030: Not all code paths return a value`.

Since this returned value is not used, perhaps throw an Error if this is an error or return nothing.

Thanks

**Comment by RanVaknin** [comment]
Hi @marwan-a ,

It seems like typescript is running checks on the dependency source code. Is there a reason you are running ts checks against the SDKs source code? 

Did you define your `include` and `exclude` correctly on the `tsconfig.json` file? 

It should exclude your node_modules, something like this:
```json
{
    "compilerOptions": {
      "target": "ES2023",
      "module": "commonjs",
      "strict": true,
      "esModuleInterop": true,
      "outDir": "./dist",
      "lib": ["ES2023", "DOM"],
      "noImplicitReturns": true
    },
    "include": ["src/**/*.ts"],
    "exclude": ["node_modules"]
}
```
Thanks,
Ran~

**Comment by marwan-a** [comment]
Fixed! It seems there was a deep import for one of the types of the input params. Thanks for help.
