### ISSUE TITLE
The list of instances from DescribeInstanceTypeOfferingsCommand is not full

### ISSUE THREAD

**Issue by AlexeyMoiseev** [aws/aws-sdk-js-v3#5068]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When I'm trying to get the list of offered instance types for the specified zone by `DescribeInstanceTypeOfferingsCommand` - this is not completely full. For example `m6a.xlarge` for `us-east-1a`. `m6a.xlarge` is not part of the list. But I can use such instance type to create EC2 via Console.

### SDK version number

@aws-sdk/client-ec2@3.387.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.16.1

### Reproduction Steps

```
const ec2_client = new EC2Client({
	credentials: {
		accessKeyId,
		secretAccessKey
	},
	region: 'us-east-1'
});

const data = await ec2_client.send(new AWS_EC2_SDK.DescribeInstanceTypeOfferingsCommand({
	LocationType: 'availability-zone',
	Filters: [{ Name: 'location', Values: ['us-east-1a'] }]
}));
```

### Observed Behavior

The list of offered types is not full. For example, there is no m6a.xlarge, but I am able to specify it via Console.

### Expected Behavior

The list of offered types should be the same as I can use it via Console.

**Comment by RanVaknin** [comment]
Hi @AlexeyMoiseev ,

The code you shared will return an incomplete list of results. Since this list operation is paginatable to see the entire list of available instance types in the response you got to paginate through the entire list:

```js
import { EC2Client, paginateDescribeInstanceTypeOfferings } from "@aws-sdk/client-ec2";

const ec2_client = new EC2Client({
    region: 'us-east-1'
});

async function run() {
    try {
        const params = {
            LocationType: 'availability-zone',
            Filters: [{ Name: 'location', Values: ['us-east-1a'] }]
        };

        const paginatorConfig = {
            client: ec2_client,
            pageSize: 500 
        };

        const paginator = paginateDescribeInstanceTypeOfferings(paginatorConfig, params);

        for await (const page of paginator) {
            console.log(page);
        }

    } catch (error) {
        console.log(error);
    }
}
run();
```

Results:
```
<more results>
    {
      InstanceType: 'c6a.2xlarge',
      LocationType: 'availability-zone',
      Location: 'us-east-1a'
    },
    {
      InstanceType: 'c5n.xlarge',
      LocationType: 'availability-zone',
      Location: 'us-east-1a'
    },
    {
      InstanceType: 'r6idn.12xlarge',
      LocationType: 'availability-zone',
      Location: 'us-east-1a'
    },
    {
      InstanceType: 'm6a.xlarge',
      LocationType: 'availability-zone',
      Location: 'us-east-1a'
    },
<more results>
```

Thanks,
Ran~
