### ISSUE TITLE
New Docs Are MIssing `CreateInputCommand` for MediaLive Client

### ISSUE THREAD

**Issue by RanVaknin** [aws/aws-sdk-js-v3#5085]
### Describe the bug

As the title suggest our new docs [are missing](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/medialive/) `CreateInputCommand` for MediaLive client. The [old docs have this](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-medialive/classes/createinputcommand.html) operation.

Im sure if this is missing there are others that are also missing. We need to root cause this and see if it affects other operations.

Ran~

**Comment by kuhe** [comment]
An internal fix is in review.

**Comment by kuhe** [comment]
we'll be deploying the fix in a future release
