### ISSUE TITLE
While not speaking, real-time transcription generates a lot of miscellaneous output

### ISSUE THREAD

**Issue by ASK-Lee** [aws/aws-sdk-js-v3#5087]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I'm using the AWS Transcribe real-time transcription feature in the Chime Meeting SDK. However, it transcribes a lot of miscellaneous input, even when I'm not speaking. Is this caused by background noise? How can I avoid this?

### SDK version number

aws-sdk-js-v3v3.382.0

### Which JavaScript Runtime is this issue in?

Browser

### Details of the browser/Node.js/ReactNative version

Chrome 115 lastest version

### Reproduction Steps

Call the Chime Meeting SDK to create a meeting, then use the startMeetingTranscription method to enable real-time transcription. Employ the subscribeToTranscriptEvent method to listen for transcription events, retrieve the transcribed text, and display it. However, as long as the audio is enabled, even without speaking, a substantial amount of unexpected text data will be received.

### Observed Behavior

No

### Expected Behavior

When I'm not speaking, no transcription output is generated.

### Possible Solution

Do you need to set a volume threshold and noise filtering when collecting transcription audio?

**Comment by yenfryherrerafeliz** [comment]
Hi @ASK-Lee, thanks for opening this report. Could you please provide a sample code that we can use to reproduce this issue?, and also understand more about your implementation.


Thanks!
