### ISSUE TITLE
SageMaker API - Add support for ListPipelineExecutionsCommand to search by status

### ISSUE THREAD

**Issue by vkonapalli** [aws/aws-sdk-js-v3#5091]
### Describe the feature

Currently SDK doesn't support to fetch list of pipeline executions based on the status 

### Use Case

I am building an internal app that data scientists use for searching pipeline executions based on Date, status etc... SDK support date (createdBefore, createdAfter) but it doesn't support to query by execution status. 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.391.0

### Environment details (OS name and version, etc.)

Mac 13.4

**Comment by RanVaknin** [comment]
Hi @vkonapalli ,

Thanks for the feature request. This could be a cool feature however it's not something that we can implement from an SDK's standpoint. The SDK is a client, and as such it is modeled based on the service's API model.  Specifically, the SDKs are code generated from the API model of the various AWS services. That means that it's the _service itself_ that needs to add support for this feature.

The best course of action for you is to open an internal ticket in the AWS console and ask to submit a feature request to the service team directly. 

Thanks again
Ran~
