### ISSUE TITLE
How to `AWS.events.on` in AWS SDK V3?

### ISSUE THREAD

**Issue by shirady** [aws/aws-sdk-js-v3#5093]
### Describe the issue

Hello,
In AWS SDK V2 [documentation](https://docs.aws.amazon.com/pt_br/AWSJavaScriptSDK/latest/AWS.html#events-property) there is an example:

```javascript
AWS.events.on('send', function startSend(resp) {
  resp.startTime = new Date().getTime();
}).on('complete', function calculateTime(resp) {
  var time = (new Date().getTime() - resp.startTime) / 1000;
  console.log('Request took ' + time + ' seconds');
});

new AWS.S3().listBuckets(); // prints 'Request took 0.285 seconds'
```

What is the equivalent way to do it in AWS SDK V3?

### Links

https://docs.aws.amazon.com/pt_br/AWSJavaScriptSDK/latest/AWS.html#events-property

**Comment by RanVaknin** [comment]
Hi @shirady ,

In all the newer SDKs we moved from request handlers to a middleware stack. 
You can read more about it in our [readme](https://github.com/aws/aws-sdk-js-v3#middleware) and also in a dedicated blogpost [here](https://aws.amazon.com/blogs/developer/middleware-stack-modular-aws-sdk-js/).

So in your case:
```js
const myMiddleware = (next) => async (args) => {
    const startTime = new Date().getTime();
    const roundTrippedResponse = await next(args);
  
    const endTime = new Date().getTime();
    const time = (endTime - startTime) / 1000;
    console.log('Request took ' + time + ' seconds');
  
    return roundTrippedResponse;
  };

s3.middlewareStack.add(myMiddleware, "build" )
```

Thanks,
Ran~
