### ISSUE TITLE
Inconsistent UI element for client pages

### ISSUE THREAD

**Issue by ypliu-AWS** [aws/aws-sdk-js-v3#5096]
### Describe the issue

There is a info button (the letter "i" with a circle around it) in the top-right corner that when clicked, shows the Table of Contents for a client page. However, if you navigate to another service using the left navigation pane, this info button won't show up until you manually refresh the webpage.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/

**Comment by RanVaknin** [comment]
Hi @ypliu-AWS ,

Thanks for the report. this indeed seems like a bug. Adding to our backlog.

All the best,
Ran~

**Comment by aBurmeseDev** [comment]
Hi @ypliu-AWS - this has been fixed. Thanks again for your feedback. 

Closing now.
