### ISSUE TITLE
[S3] Discuss lib-storage in PutObjectCommand documentation

### ISSUE THREAD

**Issue by pgib** [aws/aws-sdk-js-v3#5097]
### Describe the issue

I ~~spent~~ wasted quite a bit of time trying to upload from a `Readable` source using the `PutObjectCommand` when a simple improvement to either the documentation or error messaging would have told me exactly what the problem is. This was acknowledged in #2348 but no action has been taken.

When providing a `Body` value that is a stream, if the content length cannot be determined, you end up with the following error:

```
NotImplemented: A header you provided implies functionality that is not implemented
```

This is extremely unhelpful. "A header you provided"? Which header specifically? I didn't provide one.

In my case, the readable stream was the `.stdout` of a process invoked by `spawn()`. If I wrote it out to a file and then provided a readable stream using `fs.createReadStream()` and passed _that_ as the `Body`, it works fine. But skipping that step–which is what I want to do, and what worked in the previous version SDK, does not. The relevant information can be found in the [AWS SDK v3 upgrading instructions](https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md#s3-multipart-upload), but nothing would have pointed me there to suggest this would have been necessary.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/command/PutObjectCommand/

**Comment by RanVaknin** [comment]
Hi @pgib ,

Sorry to hear that this was not very discoverable. We did in fact [add a middleware](https://github.com/aws/aws-sdk-js-v3/blob/015cd7913197ffe26830e9c3497418f6d2142d92/packages/middleware-sdk-s3/src/check-content-length-header.ts#L33) to help detect this issue but it required using a logger to get this to appear:

```js
const s3 = new S3Client({
    region: "us-east-1",
    logger: {
        warn(message) {
          console.warn(message);
        }
    }
});
```

We will change the middleware to raise this as a warning without specifying a logger for further discoverability. 

Thanks,
Ran~

**Comment by pgib** [comment]
@RanVaknin That would be great! I think this will help many-a-developer.

**Comment by pgib** [comment]
(Also, thanks for the tip about using the logger. That will probably be helpful to note as well...)

**Comment by tedyu** [comment]
@RanVaknin 
I have seen this error in our deployment.
Since the feed of mongodb documents can be quite large, we don't want to hold them in memory just to obtain the total length.

Do you have recommendation how this should be handled ?

Thanks

BTW this seems to be new with client v3 - there is no such error for our code using client v2.

**Comment by kuhe** [comment]
The warning was restored to the PutObject operation. It will warn when a stream of unspecified length is given to PutObject, and will recommend using the Upload `@aws-sdk/lib-storage` class instead.

We don't have the ability to customize individual operation (command) documentation at this time, it is being investigated internally but we don't have an estimate as to when it might be ready.
