### ISSUE TITLE
Credential provider is not being generated for "@aws-sdk/client-codecatalyst@npm:3.395.0"

### ISSUE THREAD

**Issue by alexforsyth** [aws/aws-sdk-js-v3#5113]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

It looks like the AWS SDK Client for codecatalyst does not support the credential provider option at all. I am unclear why this is the case, but it seems to be an oversight on how this is being generated. Users of the SDK are forced to (1) write some middleware to get around this issue or (2) only rely on creds taken from local configurations.

There does not seem to be any technical reason codecatalyst can't support a credential provider.

Following the steps from this guide here:
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_credential_providers.html#examples.

```
import { CodeCatalystClient, VerifySessionCommand, CodeCatalyst } from '@aws-sdk/client-codecatalyst';
import { S3Client } from '@aws-sdk/client-s3';
import { fromSSO } from "@aws-sdk/credential-providers"; 
....
```
Working Example with s3
```
const s3ClientWithCreds = new S3Client({
      credentials: fromSSO({
        ...
      })
    })
```

Issue with with CodeCatalystClient
```

const CodeCatalystClientWithCreds = new CodeCatalystClient({
      credentials: fromSSO({ // not valid type
        ...
      })
    })
```

### SDK version number

"@aws-sdk/client-codecatalyst@npm:3.395.0"

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.16.1

### Reproduction Steps

Following the steps from this guide here:
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_credential_providers.html#examples.

```
import { CodeCatalystClient, VerifySessionCommand, CodeCatalyst } from '@aws-sdk/client-codecatalyst';
import { S3Client } from '@aws-sdk/client-s3';
import { fromSSO } from "@aws-sdk/credential-providers"; 
....
```
Working Example with s3
```
const s3ClientWithCreds = new S3Client({
      credentials: fromSSO({
        ...
      })
    })
```

Issue with with CodeCatalystClient
```
const CodeCatalystClientWithCreds = new CodeCatalystClient({
      credentials: fromSSO({ // not valid type
        ...
      })
    })
```

### Observed Behavior

Codecatalyst client does not support a credential provider option.

### Expected Behavior

Codecatalyst client should support a credential provider option.

### Possible Solution

Looks like the model being used to generate this client isn't correct. Unclear why.

**Comment by RanVaknin** [comment]
Hi @alexforsyth ,

Thanks for the report. This looks like a bug. 

Reproduction:
- create a project, with a ts file: `sample.ts`:

```ts
import { CodeCatalystClient, ListAccessTokensCommand } from '@aws-sdk/client-codecatalyst';

const CodeCatalystClientWithCreds = new CodeCatalystClient({
    region: "us-east-1",
    credentials: {} // <--- errors out here
  })
```
The tooltip shows: `Object literal may only specify known properties, and 'credentials' does not exist in type 'CodeCatalystClientConfigType'.ts(2353)
`
Seems like there is no credentials object in this generated client. This might be a codegen bug.
I'll need to investigate this with the team and get back to you.

Thanks,
Ran~

**Comment by RanVaknin** [comment]
Hi @alexforsyth ,

CodeCatalyst only supports token, not credentials:

You probably can do something like this:

```js
import { CodeCatalystClient, ListAccessTokensCommand } from '@aws-sdk/client-codecatalyst';

const CodeCatalystClientWithCreds = new CodeCatalystClient({
    region: "us-east-1",
    token: {
        token: "my-sso-token",
        expiration: // some date.
    }
  })
```

Can you tell us what you are trying to achieve?

Thanks,
Ran~
