### ISSUE TITLE
ResourceARN & Tags should be changed to resourceArn & tags

### ISSUE THREAD

**Issue by satish4584** [aws/aws-sdk-js-v3#5121]
### Describe the issue

The code should look like below:
ResourceARN & Tags are incorrect.
```js
import { CloudWatchLogsClient, TagResourceCommand } from "@aws-sdk/client-cloudwatch-logs"; // ES Modules import
// const { CloudWatchLogsClient, TagResourceCommand } = require("@aws-sdk/client-cloudwatch-logs"); // CommonJS import
const client = new CloudWatchLogsClient(config);
const input = { // TagResourceRequest
  resourceArn: "STRING_VALUE", // required
  tags: { // Tags // required
    "<keys>": "STRING_VALUE",
  },
};
const command = new TagResourceCommand(input);
const response = await client.send(command);
// {};
```
### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/client/cloudwatch/command/TagResourceCommand/

**Comment by RanVaknin** [comment]
Hi @satish4584 ,

Thanks for the report. This does seem like the doc is generated incorrectly. Ill add this to our backlog. 
Ran~

**Comment by RanVaknin** [comment]
Hi @satish4584 ,

After looking again at this, you are looking at the wrong docs. Mainly you are mixing Cloudwatch Client and CloudwatchLogs Client. 

The casing is correct. 

Thanks,
Ran~
