### ISSUE TITLE
Cannot find module for @aws-sdk/util-retry on Node v18 Lambda runtime

### ISSUE THREAD

**Issue by albertodiazdorado** [aws/aws-sdk-js-v3#5122]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I am using AWS Lambda with the Node v18 runtime. I am using several `@aws-sdk/*` packages, which should be globally available in the Node v18 runtime of AWS Lambda. This holds true for most packages. However, I get this error when trying to use `@aws-sdk/util-retry`. The code looks like this:

```js
import {
  DynamoDBClient,
  UpdateItemCommand,
  QueryCommand
} from "@aws-sdk/client-dynamodb";
import { ConfiguredRetryStrategy } from "@aws-sdk/util-retry";
import {
  CloudWatchClient,
  PutMetricDataCommand
} from "@aws-sdk/client-cloudwatch";
```

and the error is:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@aws-sdk/util-retry' imported from /var/task/index.mjs
```
How can I know in advance which `@aws-sdk/*` packages are available at runtime and which are not?

cf. https://github.com/aws/aws-sdk-js-v3/issues/4401

### SDK version number

@aws-sdk/util-retry

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

`nodejs18.x` (whatever AWS Lambda uses)

### Reproduction Steps

Use @aws-sdk/util-retry in ESM Node v18 Lambda runtime.

### Observed Behavior

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@aws-sdk/util-retry' imported from /var/task/index.mjs

### Expected Behavior

Import works

**Comment by yenfryherrerafeliz** [comment]
Hi @albertodiazdorado, this is not an issue really. @aws-sdk/util-retry was introduced in version 3.222.0, which can be confirmed [here](https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.222.0), and the version embedded in lambda is 3.188.0, which can be seen [here](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#w365aac19c29). Also, @aws-sdk/util-retry has been moved to @smith/util-retry. Something you can do is to either, upload a node_modules folder with this package installed, or create a lambda layer and also upload this dependency. The exact dependency name is @smithy/util-retry.

[Here](https://docs.aws.amazon.com/lambda/latest/dg/chapter-layers.html) is the documentation for lambda layers, in case you would opt for this option and need guidance regarding.

Please let me know if that helps!

Thanks!
