### ISSUE TITLE
Add Acceptable Input Values for `retryMode` in Client Config.

### ISSUE THREAD

**Issue by bennettellis** [aws/aws-sdk-js-v3#5123]
### Describe the issue

The documentation for the v3 Node/js SDK is HORRID compared to V2. Can someone make this actually a priority? SImply listing config properties without actually providing any detail about the acceptable values for each is RIDICULOUS. How the hell is someone supposed to use the SDK when this kind of information is missing.
Specific example: retryMode. How the hell would anyone know what value to provide for that?

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/

**Comment by RanVaknin** [comment]
Hi @bennettellis ,

I agree that the new v3 docs were launched a bit prematurely. Aside from adding possible inputs for `retryMode` I didn't see anything specific enough for us to act on in your report. 

Currently we are tracking changes to the config page in the docs with priority [here ](https://github.com/aws/aws-sdk-js-v3/issues/5054).

If you have additional specific and actionable feedback, feel free to open another documentation issue. 

Thanks,
Ran~
