### ISSUE TITLE
getSignedUrl with ChecksumMode ENABLED Fails

### ISSUE THREAD

**Issue by iheffernan** [aws/aws-sdk-js-v3#5125]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When creating an S3 presigned URL for a GET with `ChecksumMode: 'ENABLED'` an error is thrown.

Error is 
```
Cannot read properties of undefined (reading 'x-amz-checksum-crc32')
TypeError: Cannot read properties of undefined (reading 'x-amz-checksum-crc32')
    at validateChecksumFromResponse (/Users/ian/WebstormProjects/byrst-web/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/validateChecksumFromResponse.js:13:53)
    at /Users/ian/WebstormProjects/byrst-web/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:68:79
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/ian/WebstormProjects/byrst-web/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
    at async getSignedUrl (/Users/ian/WebstormProjects/byrst-web/node_modules/@aws-sdk/s3-request-presigner/dist-cjs/getSignedUrl.js:54:24)
```

### SDK version number

@aws-sdk/s3-request-presigner@3.391.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node.js v18.17.1

### Reproduction Steps

```
const s3Client = new S3Client();
const command = new GetObjectCommand({
    Bucket: 'my-bucket',
    Key: 'test-key.txt',
    ChecksumMode: "ENABLED"
});
const url = await getSignedUrl(s3Client, command, {
    expiresIn: 10,
    unhoistableHeaders: new Set(['x-amz-checksum-mode'])
});
console.log(url);
```

NOTE: Removing or commenting out `ChecksumMode` in the provided `GetObjectCommand` works.

### Observed Behavior

Internal AWS client code throws when calling.

### Expected Behavior

I expect that I would get an S3 presigned URL that when used will have ChecksumMode enabled.

**Comment by iheffernan** [comment]
One other note - I am using the same AWS SDK version - `3.391.0` for both the `client-s3` and `s3-request-presigner` packages.

**Comment by RanVaknin** [comment]
Hi @iheffernan ,

Thanks for opening this issue. 
Im able to confirm this is a problem. I see @kuhe had already created a fix for this.

All the best,
Ran~
