### ISSUE TITLE
[Typescript] CognitoIdentityProviderClient.send with ListUsersCommand 

### ISSUE THREAD

**Issue by keith88kwok** [aws/aws-sdk-js-v3#5127]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

```
import { CognitoIdentityProviderClient, ListUsersCommand } from "@aws-sdk/client-cognito-identity-provider";

const client = new CognitoIdentityProviderClient({ region: "your-region" });

const listUsers = async ({ userPoolId }) => {
  
    const command = new ListUsersCommand({
      UserPoolId: userPoolId,
    });
  
    return client.send(command);
  };
  
export default listUsers;
```

 client.send(**command**);

Will have an error as follow:
> Argument of type 'ListUsersCommand' is not assignable to parameter of type 'Command<ServiceInputTypes, ListUsersCommandInput, ServiceOutputTypes, ListUsersCommandOutput, SmithyResolvedConfiguration<...>>'.
>   Types of property 'resolveMiddleware' are incompatible.
>     Type '(clientStack: MiddlewareStack<ServiceInputTypes, ServiceOutputTypes>, configuration: CognitoIdentityProviderClientResolvedConfig, options?: HttpHandlerOptions | undefined) => Handler<...>' is not assignable to type '(stack: MiddlewareStack<ServiceInputTypes, ServiceOutputTypes>, configuration: SmithyResolvedConfiguration<HttpHandlerOptions>, options: any) => Handler<...>'.

### SDK version number

@aws-sdk/client-cognito-identity-provider@^3.395.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.19.1

### Reproduction Steps

```
import { CognitoIdentityProviderClient, ListUsersCommand } from "@aws-sdk/client-cognito-identity-provider";

const client = new CognitoIdentityProviderClient({ region: "your-region" });

const listUsers = async ({ userPoolId }) => {
  
    const command = new ListUsersCommand({
      UserPoolId: userPoolId,
    });
  
    return client.send(command);
  };
  
export default listUsers;
```

### Observed Behavior

Have type error 

### Expected Behavior

Have not had any type error

**Comment by RanVaknin** [comment]
Hi @keith88kwok ,

I'm not sure why you are running into this issue. Im able to successfully list my user pool:

sample.ts
```ts
import { CognitoIdentityProviderClient, ListUsersCommand } from "@aws-sdk/client-cognito-identity-provider";

const client = new CognitoIdentityProviderClient({ region: "us-east-1" });

const listUsers = async (userPoolId) => {
  
    const command = new ListUsersCommand({
      UserPoolId: userPoolId,
    });
  
    try {
      const response = await client.send(command);
      console.log(response)
    } catch (error) {
      console.log(error)
    }

    
  };
  
listUsers("myUserPoolId")
```

Result:

```console
$ tsc sample.ts
$ node sample.js 
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'f6a86255-b189-4772-8a35-24abd364ab3d',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Users: [
    {
      Attributes: [Array],
      Enabled: true,
      UserCreateDate: 2022-08-25T23:37:59.587Z,
      UserLastModifiedDate: 2022-08-25T23:40:36.404Z,
      UserStatus: 'FORCE_CHANGE_PASSWORD',
      Username: 'asd'
    },
    ... more results ....
```

Can you share the content of your `tsconfig.json` file? Additionally, try deleting your `node_modules` and `package-lock.json` and run `npm install` again to see if it solves the issue. Maybe there is some version mismtach between your other dependencies.

Thanks,
Ran~
