### ISSUE TITLE
Improve logger interface

### ISSUE THREAD

**Issue by Nevon** [aws/aws-sdk-js-v3#5128]
### Describe the feature

Make the logger interface actually have a reasonably defined interface for what the logging methods may be called with, so that it's actually possible to write an adapter to existing logging libraries. The logging interface in the v2 SDK was crap because you just got a string, but at least you knew you were getting a string.

### Use Case

The current interface doesn't tell you what types the logging methods will be called with, nor how many arguments it will be called with. It's literally `...any[]`, which is all but impossible to adapt to a normal logger without doing crazy stuff at runtime to figure out all the myriad combinations that you may be called with.

https://github.com/awslabs/smithy-typescript/blob/3fb4f4e4ce2b4b3895a16ef45ec3aa9dca3e674b/packages/types/src/logger.ts#L7-L13

So far I've seen cases where the logger gets called with a string as the first argument, other places it gets called with an object as the first argument. It's variadic, so who knows how many arguments you may get called with.

### Proposed Solution

Just some examples of what would at least be workable.

```ts
type LogContext = Record<string, unknown>

export interface Logger {
  trace?: (message: string, context?: LogContext) => void;
  debug: (message: string, context?: LogContext) => void;
  info: (message: string, context?: LogContext) => void;
  warn: (message: string, context?: LogContext) => void;
  error: (message: string, context?: LogContext) => void;
}
```

or:

```ts
interface LogLine {
 message: string;
 [key: string]: unknown
}

export interface Logger {
  trace?: (line: LogLine) => void;
  debug: (line: LogLine)) => void;
  info: (line: LogLine)) => void;
  warn: (line: LogLine)) => void;
  error: (line: LogLine)) => void;
}
```

Or dare I say:

```ts
type LogValue =
  | string
  | number
  | boolean
  | null
  | Error
  | LogValue[]
  | { [key: string]: LogValue }
interface LogLine {
 message: string;
 [key: string]: LogValue
}

export interface Logger {
  trace?: (line: LogLine) => void;
  debug: (line: LogLine) => void;
  info: (line: LogLine) => void;
  warn: (line: LogLine) => void;
  error: (line: LogLine) => void;
}
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.395.0

### Environment details (OS name and version, etc.)

Any

**Comment by RanVaknin** [comment]
Hi @Nevon,

>which is all but impossible to adapt to a normal logger without doing crazy stuff at runtime to figure out all the myriad combinations that you may be called with.

Can you please provide an example of what makes it impossible?

Thanks,
Ran~
