### ISSUE TITLE
When sending ReceiveMessageCommand or SendMessageCommand to existing queue, NonExistentQueue error is triggered, works on SDK v2

### ISSUE THREAD

**Issue by faizjamil** [aws/aws-sdk-js-v3#5134]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Using the AWS SDK V3 to attempt to send and receive messages from an SQS queue does not work and gives a queue does not exist error.
Now what's weird here is that i've tried this exact same operation, same queue URL on both the AWS CLI and AWS SDK v2 and both times I had no issue.

### SDK version number

@aws-sdk/client-sqs@3.395.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.17.1

### Reproduction Steps

```js
        const sqsClient = new SQSClient({ region: 'us-east-1' });
        const messageToReceive = new ReceiveMessageCommand({
          QueueURL: <queue URL>
          MaxNumberOfMessages: 1
        });
        const response = await sqsClient.send(messageToReceive);
        console.log(response);
 ```

In case it's needed, here's the code I used in v2 of the SDK

```
AWS.config.update({ region: 'us-east-1' });
const v2SQSClient = new AWS.SQS();
  const messageToReceiveParams = {
    QueueUrl: <Queue URL>,
    MaxNumberOfMessages: 1
  };
  v2SQSClient.receiveMessage(messageToReceiveParams, (err, data) => {
    if (err) {
      console.log('Receive Error', err);
    } else {
      console.log('DATA: ', data);
    }
  });
```

### Observed Behavior

```
 AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist for this wsdl version.
     at throwDefaultError (/usr/app/bin/server.js:30620:22)
     at /usr/app/bin/server.js:30629:9
     at de_ReceiveMessageCommandError (/usr/app/bin/server.js:13289:20)
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
     at async /usr/app/bin/server.js:27278:24
     at async /usr/app/bin/server.js:20257:20
     at async /usr/app/bin/server.js:27155:46
     at async /usr/app/bin/server.js:19953:22
     at async /usr/app/bin/server.js:19608:26 {
   '$fault': 'client',
   '$metadata': {
     httpStatusCode: 400,
     requestId: <request id>
     extendedRequestId: undefined,
     cfId: undefined,
     attempts: 1,
     totalRetryDelay: 0
   },
   Type: 'Sender',
   Code: 'AWS.SimpleQueueService.NonExistentQueue',
   Detail: ''
 }
```

### Expected Behavior

I expect to get a message as a response.

### Additional Information/Context

I have checked both my credentials and my region, both are set correctly and to the same values as the creds and region the AWS CLI and the v2 SDK use.

**Comment by yenfryherrerafeliz** [comment]
Hi @faizjamil, thanks for opening this report. Can you please verify that the region of the queue, which can be confirmed from the console, matches the one defined for the SQS client, used to do the request?, also can you please make sure you are providing the correct queue-url. I just tested on my end and everything works just fine.
Please see below:
```js
import {SQSClient, ReceiveMessageCommand} from "@aws-sdk/client-sqs";

const client = new SQSClient({
    region: "us-east-2"
});
const response = await client.send(new ReceiveMessageCommand({
    QueueUrl: "https://sqs.us-east-2.amazonaws.com/565495631452/test-queue",
    MaxNumberOfMessages: 1
}))

console.log(response)
```
Results:
```
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'Redacted',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}

```

Please let me know.

Thanks!

**Comment by faizjamil** [comment]
Ok well, I was able to access the queue I was having trouble with using your code. Through some trial and error I learned that there was some kind of issue with my code, might have had to do with constructing and then sending the ReceiveMessageCommand. Thanks for the assistance as I probably wouldn't have figure it out as quickly if at all.
