### ISSUE TITLE
Lack of Documentation on aws-sdk/client-elasticsearch-service

### ISSUE THREAD

**Issue by WarrenWongCodes** [aws/aws-sdk-js-v3#5144]
### Describe the issue

I am attempting to migrate from [elasticsearch.js ](https://www.npmjs.com/package/elasticsearch/v/15.5.0)to the new `aws-sdk/client-elasticsearch-service` specifically version `3.395.0`. 

Asides from [setting up the client](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/) I do not see any documentation on attempting to conduct **search/query operations**. 

I am attempting to migrate from the old `elasticsearch.js` `searchParams`, `searchResponse` fields to the new syntax, as well as the [Scroll API](https://www.elastic.co/guide/en/elasticsearch/reference/current/scroll-api.html).  Are these types, interfaces, and functionality supported or any documentation on this? Thank you very much.

`searchParams` :
```export interface SearchParams extends GenericParams {
    analyzer?: string | undefined;
    analyzeWildcard?: boolean | undefined;
    defaultOperator?: DefaultOperator | undefined;
    df?: string | undefined;
    explain?: boolean | undefined;
    storedFields?: NameList | undefined;
    docvalueFields?: NameList | undefined;
    fielddataFields?: NameList | undefined;
    from?: number | undefined;
    ignoreUnavailable?: boolean | undefined;
    allowNoIndices?: boolean | undefined;
    expandWildcards?: ExpandWildcards | undefined;
    lenient?: boolean | undefined;
    lowercaseExpandedTerms?: boolean | undefined;
    preference?: string | undefined;
    q?: string | undefined;
    routing?: NameList | undefined;
    scroll?: TimeSpan | undefined;
    searchType?: "query_then_fetch" | "dfs_query_then_fetch" | undefined;
    size?: number | undefined;
    sort?: NameList | undefined;
    _source?: NameList | undefined;
    _sourceExclude?: NameList | undefined;
    _sourceInclude?: NameList | undefined;
    terminateAfter?: number | undefined;
    stats?: NameList | undefined;
    suggestField?: string | undefined;
    suggestMode?: "missing" | "popular" | "always" | undefined;
    suggestSize?: number | undefined;
    suggestText?: string | undefined;
    timeout?: TimeSpan | undefined;
    trackScores?: boolean | undefined;
    version?: boolean | undefined;
    requestCache?: boolean | undefined;
    index?: NameList | undefined;
    type?: NameList | undefined;
}
```
`searchResponse` :

```
export interface SearchResponse<T> {
    took: number;
    timed_out: boolean;
    _scroll_id?: string | undefined;
    _shards: ShardsResponse;
    hits: {
        total: number;
        max_score: number;
        hits: Array<{
            _index: string;
            _type: string;
            _id: string;
            _score: number;
            _source: T;
            _version?: number | undefined;
            _explanation?: Explanation | undefined;
            fields?: any;
            highlight?: any;
            inner_hits?: any;
            matched_queries?: string[] | undefined;
            sort?: string[] | undefined;
        }>;
    };
    aggregations?: any;
}
```

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/elasticsearch-service/

**Comment by RanVaknin** [comment]
Hi @WarrenWongCodes,

`aws-sdk/client-elasticsearch-service` is a management client meant to interact with the control plane for elastic search services.  This API provides ways to create and manage elastic search domains.

`elasticsearch.js` was a data plane api client. It let you read and write data from your provisioned resources. 

These two are not the same in terms of functionality. I _think_ what you want to use is https://github.com/elastic/elasticsearch.

Thanks,
Ran
