### ISSUE TITLE
Add MiddlewareStack in Step 'build'

### ISSUE THREAD

**Issue by shirady** [aws/aws-sdk-js-v3#5148]
### Describe the issue

Hello,
I'm trying to find a solution for migrating this part of the code from AWS SDK V2 to AWS SDK V3 which uses request handler in step 'build':

Code snippet using AWS SDK V2:
````javascript
const AWS = require('aws-sdk');
const querystring = require('querystring');
...
const s3 = new AWS.S3(s3_client_params);
...
const query_params = { something_to_get: true };
const res = await s3.getObjectTagging({
    Bucket: bucket_name,
    Key: key_name,
}).on('build', req => {
    const sep = req.httpRequest.search() ? '&' : '?';
    const query_string = querystring.stringify(query_params);
    const req_path = `${req.httpRequest.path}${sep}${query_string}`;
    req.httpRequest.path = req_path;
}).promise();
````
`req.httpRequest.path` after is: '/bucket_name/key_name?tagging&<query_string>'

I tried to create a middleware on the specific command - I added printing but I couldn't see `?tagging` part (I tried to change the priority and it didn't help as well).

Code snippet using AWS SDK V3:
Notes:
- There is no `search()` method on `HttpRequest` class, so I tried something else.
- I'm aware that I'm using `S3` and not `S3Client` (in the file there are many commands that we use). 
````javascript
const { S3, PutObjectTaggingCommand} = require('@aws-sdk/client-s3');
const AWS = require('aws-sdk');
const querystring = require('querystring');

function get_middleware_stack_adds_query_string(query_params) {
    const middleware_stack_adds_query_string = (next, context) => async args => {
        const path_and_query_string = args.request.path;
        const full_dummy_url = `https://example.com${path_and_query_string}`;
        const parsed_url = new URL(full_dummy_url);
        const original_query_string = parsed_url.search;
        const sep = original_query_string === '' ? '?' : '&';
        const query_string = querystring.stringify(query_params);
        const req_path = `${path_and_query_string}${sep}${query_string}`;
        args.request.path = req_path;

        // result.response contains data returned from next middleware.
        const result = await next(args);
        return result;
    };
    return middleware_stack_adds_query_string;
}
...
const s3 = new S3(s3_client_params);
const query_params = { something_to_get: true };
...
const getObjectTagging = new GetObjectTaggingCommand(params_req);
const my_middleware_stack = get_middleware_stack_adds_query_string(query_params);
getObjectTagging.middlewareStack.add(my_middleware_stack, { step: 'build', name: 'getFromCache'});
res = await s3.send(getObjectTagging);
````
req.httpRequest.path after is: `/bucket_name/key_name?<query_string>` (no tagging part).

Thank you,

If there is more information and examples on the middleware-stack please attach links, it can be helpful (I'm aware of your [readme](https://github.com/aws/aws-sdk-js-v3#middleware) and the blogpost [here](https://aws.amazon.com/blogs/developer/middleware-stack-modular-aws-sdk-js/)).

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/HttpRequest.html#search-property
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/classes/_aws_sdk_protocol_http.httprequest-1.html
https://github.com/aws/aws-sdk-js-v3#middleware
https://aws.amazon.com/blogs/developer/middleware-stack-modular-aws-sdk-js/

**Comment by RanVaknin** [comment]
Hi @shirady ,

I'm a bit confused about what you are trying to do here. Are you sending this to an local S3 server? Because the live S3 server will not process arbitrary query parameters like `something_to_get`.

Also Im not sure if this is a bug in the code, but `original_query_string` is incorrectly named. As you extract this query string from the dummy URL, not the original one.

If you just want to add a query parameter to your request you can do this:

```js
s3client.middlewareStack.add(next => args => {
    args.request.query.something_to_get = 'true'
    console.log(args.request);
    return next(args);
}, {step: 'build'})
```

Will result in both `tagging` and `something_to_get` being present on the request.

```
HttpRequest {
  method: 'GET',
  hostname: 'testbucket.s3.us-east-1.amazonaws.com',
  port: undefined,
  query: { tagging: '', something_to_get: 'true' },
  headers: {},
  body: undefined,
  protocol: 'https:',
  path: '/foo5.txt',
  username: undefined,
  password: undefined,
  fragment: undefined
}
```

Thanks,
Ran~

**Comment by shirady** [comment]
Hi @RanVaknin,
Your suggested code snippet helped me.
Yes, there are parts on the code where the server is not AWS, but a mock to test things.
I have another part in the code where I need to use middleware, but I create a change that I'm not able to remove.

In AWS SDK V2 it was:
```javascript
const AWS = require('aws-sdk');
const querystring = require('querystring');
...
const s3 = new S3(s3_client_params)
...
const query_params = { versionId: "rasWWGpgk9E4s0LyTJgusGeRQKLVIAFf" };
await s3.headObject({ Bucket: bucket_name, Key: text_file1 }).on('build', req => {
    const sep = req.httpRequest.search() ? '&' : '?';
    const query_string = querystring.stringify(query_params);
    const req_path = `${req.httpRequest.path}${sep}${query_string}`;
    req.httpRequest.path = req_path;
}).promise();
```

I tried to change it according to your suggestion:
```javascript
const { S3, PutObjectTaggingCommand} = require('@aws-sdk/client-s3');
...
const s3 = new S3(s3_client_params);
...
s3.middlewareStack.add(next => args => {
    args.request.query.versionId = 'rasWWGpgk9E4s0LyTJgusGeRQKLVIAFf'; // represents query_params = { versionId: "rasWWGpgk9E4s0LyTJgusGeRQKLVIAFf" }
    return next(args);
}, {step: 'build', name: 'addVersionId'});
await s3.headObject(params_req);
s3.middlewareStack.remove('addVersionId');
```
But all the rest of the actions still had the mentioned `versionId` even after removing the middleware (I also tried to create another one with the same code just `args.request.query.versionId = undefined`, and it didn't solve it.
How can I set the middleware to run only once?

Thanks,
Shira

**Comment by kuhe** [comment]
when you call `middlewareStack.add`, the second part is called the middlewareOptions.

You have it as `{step: 'build', name: 'addVersionId'}`.

To prevent duplication, set `override: true` on this object.

```js
middlewareStack.add(someMiddlewareFunction, { step: 'build', override: true, name: 'addVersionId' });
```

**Comment by shirady** [comment]
Hi @kuhe,
Thank you for your answer. I found a workaround for this code part.
I still want to understand your suggestion - why do you think it's a duplication case?

**Comment by kuhe** [comment]
the middlewarestack gets copied internally in a few places, if there's no override setting it may be duplicated unintentionally even if it seems you are not calling the add function multiple times. We should probably default override to true.
