### ISSUE TITLE
Use IAM Role of EC2 instance to get aws credential 

### ISSUE THREAD

**Issue by softdev1029** [aws/aws-sdk-js-v3#5155]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

With aws-sdk V2, I got this issue: https://github.com/aws/aws-sdk-js/issues/4487

- I installed `@aws-sdk/client-s3` and `@aws-sdk/s3-request-presigner`.
The installed version is:
"@aws-sdk/client-s3": "^3.395.0",
"@aws-sdk/s3-request-presigner": "^3.395.0",

- I used the latest node version (18.17.1)

But still I get `Error: Credential is missing`

- I tried `aws configure list` in ec2 instance CLI and it successfully returns the info.
- To simulate `aws configure list` in JS and to obtain AWS credentials using an IAM role in JavaScript, I used the @aws-sdk/credential-provider-imds package from the AWS SDK v3.
This package retrieves temporary credentials by making a request to the EC2 instance metadata service (IMDS) when the code is running on an EC2 instance with an associated IAM role.
I installed the required package:

```
yarn add @aws-sdk/credential-provider-imds
```

I used the package to obtain temporary credentials:

```
const { fromInstanceMetadata } = require("@aws-sdk/credential-provider-imds");
```

But I get this error:

```
> Uncaught TypeError: Cannot read properties of undefined (reading 'readFile')
  at ./node_modules/@aws-sdk/credential-provider-imds/node_modules/@smithy/shared-ini-file-loader/dist-es/getSSOTokenFromFile.js (getSSOTokenFromFile.js:3:1)
```

- To directly determine whether we are using IMDSv1 or IMDSv2 by making a request to the metadata service and observing the response,

I did on my ec2 instance.

```
curl http://169.254.169.254/latest/meta-data/
```

It returns the data such as:

```
ami-id
ami-launch-index
ami-manifest-path
block-device-mapping/
events/
hibernation/
hostname
iam/
identity-credentials/
instance-action
instance-id
instance-life-cycle
instance-type
local-hostname
local-ipv4
mac
metrics/
network/
placement/
profile
public-hostname
public-ipv4
public-keys/
reservation-id
security-groups
services/
```

But when I try:

```
curl http://169.254.169.254/latest/api/token
```

It doesn't return anything.

It means we are using IMDSv1 instead of v2 on our EC2 instance.

### SDK version number

@aws-sdk/client-s3@3.395.0, @aws-sdk/s3-request-presigner@3.395.0"

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node 18.17.1

### Reproduction Steps

With aws-sdk V2, I got this issue: https://github.com/aws/aws-sdk-js/issues/4487

- I installed `@aws-sdk/client-s3` and `@aws-sdk/s3-request-presigner`.
The installed version is:
"@aws-sdk/client-s3": "^3.395.0",
"@aws-sdk/s3-request-presigner": "^3.395.0",

```
import { getSignedUrl as getSigned } from "@aws-sdk/s3-request-presigner";^M
const { fromInstanceMetadata } = require("@aws-sdk/credential-provider-imds");^M
 
export const getSignedUrl = (url) => {
  const { S3Client, GetObjectCommand } = require("@aws-sdk/client-s3");        ^M
  const credentials = fromInstanceMetadata();^M
  const s3Client = new S3Client({ region: "us-east-1",credentials }); 
```

### Observed Behavior

I get `Error: Credential is missing`

### Expected Behavior

No error happens when using the above code.

**Comment by yenfryherrerafeliz** [comment]
Hi @softdev1029, this error typically means that not aws credentials were found. Can you please confirm that your ec2 instance has a role attached?. If you have the AWS CLI installed, you can confirm this by doing the following:

```console
aws ec2 describe-iam-instance-profile-associations --region us-east-2 --query "IamInstanceProfileAssociations[?InstanceId=='INSTANCE-ID'].IamInstanceProfile.Arn"
```

Please replace "INSTANCE-ID" with your ec2 instance id.

Please let me know the results.

Thanks!

**Comment by softdev1029** [comment]
@yenfryherrerafeliz 

```
aws ec2 describe-iam-instance-profile-associations --region us-east-1 --query "IamInstanceProfileAssociations[?InstanceId=='i-0e3dc6a677b704c0b'].IamInstanceProfile.Arn"

An error occurred (UnauthorizedOperation) when calling the DescribeIamInstanceProfileAssociations operation: You are not authorized to perform this operation.
```

At first, my IAM role attached to the EC2 instance `i-0e3dc6a677b704c0b` doesn't have a permission for `describe-iam-instance-profile-associations`.
So I added an inline policy to the role.

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "ec2:DescribeIamInstanceProfileAssociations",
      "Resource": "*"
    }
  ]
}
```

Now, I get this result.


```
aws ec2 describe-iam-instance-profile-associations --region us-east-1 --query "IamInstanceProfileAssociations[?InstanceId=='i-0e3dc6a677b704c0b'].IamInstanceProfile.Arn"
[
    "arn:aws:iam::084709402479:instance-profile/AllowS3ForEC2"
]
```

**Comment by yenfryherrerafeliz** [comment]
@softdev1029 Ok, I can see the instance has a role attached. Thanks for confirm it. I will work on some tests and I will get back to you with some updates soon.

Thanks!

**Comment by softdev1029** [comment]
Thanks

**Comment by yenfryherrerafeliz** [comment]
Hi @softdev1029, this issue is also the same as this one [here](https://github.com/aws/aws-sdk-js/issues/4487), which is also being handled by Ran. If your application is not running at server side, in your EC2 instance, so then ec2 instance profile will not work as credential provider.

I will close this issue, but please feel free of opening a new issue for any other issues that we may assist you with.

Thanks!
