### ISSUE TITLE
Missing types for S3Client in @aws-sdk/client-s3

### ISSUE THREAD

**Issue by etowahadams** [aws/aws-sdk-js-v3#5164]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Types are not properly generated for the S3Client. Other have [noted](https://stackoverflow.com/questions/71166409/unable-to-compile-typescript-property-send-does-not-exist-on-s3client/71173522#71173522) this issue on StackOverflow. Using S3Client `send` will give a `Property 'send' does not exist` ts error. 

### SDK version number

"@aws-sdk/client-s3": "^3.400.0",

### Which JavaScript Runtime is this issue in?

Browser

### Details of the browser/Node.js/ReactNative version

Chrome: 115.0.5790.170     Edge: 114.0.1823.67     Safari: 16.4

### Reproduction Steps

```
pnpm create vite my-react-ts --template react-ts
cd my-react-ts
pnpm install
pnpm install @aws-sdk/client-s3
```
In `App.tsx`
```
import { S3Client } from '@aws-sdk/client-s3'

S3Client.send()
```
### Observed Behavior

If you try 
```
import { S3Client } from '@aws-sdk/client-s3'

S3Client.send()
```
You will get 
```
Property 'send' does not exist on type 'typeof S3Client'.ts(2339)
```

Looking in `dist-types/S3Client.d.ts`, the types for `send` are missing

``` javascript 
export declare class S3Client extends __Client<__HttpHandlerOptions, ServiceInputTypes, ServiceOutputTypes, S3ClientResolvedConfig> {
    /**
     * The resolved configuration of S3Client class. This is resolved and normalized from the {@link S3ClientConfig | constructor configuration interface}.
     */
    readonly config: S3ClientResolvedConfig;
    constructor(...[configuration]: __CheckOptionalClientConfig<S3ClientConfig>);
    /**
     * Destroy underlying resources, like sockets. It's usually not necessary to do this.
     * However in Node.js, it's best to explicitly shut down the client's agent when it is no longer needed.
     * Otherwise, sockets might stay open for quite a long time before the server terminates them.
     */
    destroy(): void;
}
```

### Expected Behavior

I expect the type for `send` to be as described in [the docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-s3/Class/S3Client/) 

```
send | send<InputType extends ClientInput, OutputType extends ClientOutput>(command: Command<ClientInput,  InputType, ClientOutput, OutputType,  SmithyResolvedConfiguration<HandlerOptions>, options?:  HandlerOptions): Promise<OutputType> |  
send | send<InputType extends ClientInput, OutputType extends ClientOutput>(command: Command<ClientInput,  InputType, ClientOutput, OutputType,  SmithyResolvedConfiguration<HandlerOptions>, cb: (err: any, data?:  OutputType) = void): void |  
send | send<InputType extends ClientInput, OutputType extends ClientOutput>(command: Command<ClientInput,  InputType, ClientOutput, OutputType,  SmithyResolvedConfiguration<HandlerOptions>, options:  HandlerOptions, cb: (err: any, data?: OutputType) = void): void

```

**Comment by RanVaknin** [comment]
Hi @etowahadams ,

You need to instantiate the client first before you can access its methods, and also you need to specify which command you want to send.

```diff
import { S3Client } from '@aws-sdk/client-s3'

+ const client = new S3Client({region: 'us-east-1' })

- S3Client.send()
+ client.send() 
```

Please refer to our [developer guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/welcome.html), our [README](https://github.com/aws/aws-sdk-js-v3/blob/main/README.md),  or countless examples in our [documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/command/GetObjectCommand/) to understand the structure and syntax.

Thanks,
Ran~

**Comment by etowahadams** [comment]
Ah I was being an idiot when I tried to reproduce a minimal example, I apologize. I got excited when I saw the same error as in my project where I do instantiate the client. Must be something wrong with my tsconfig. Sorry for wasting your time. 

![image](https://github.com/aws/aws-sdk-js-v3/assets/14843470/5eed2f50-ff05-4b58-9278-8d43961069d3)
