### ISSUE TITLE
Document how to replicate the old retry behavior

### ISSUE THREAD

**Issue by joebowbeer** [aws/aws-sdk-js-v3#5170]
### Describe the issue

The documentation regarding retry is lacking.

In the AWS SDK JavaScript V3 docs, it's difficult to find the link to the smithy-typescript repo whose packages can be used to customize the retry behavior.

It would be helpful to provide more examples of how to replicate the old behavior.

I think the equivalent retry strategy to the first one below is actually:

```ts
  retryStrategy: new ConfiguredRetryStrategy(6, (attempt) => 1100 * 2 ** (attempt - 1)))
```

---

> I think ConfiguredRetryStrategy can be used to replicate the old behavior

```ts
// v2 api
import AWS from 'aws-sdk'
const cloudwatch = new AWS.CloudWatch({
  apiVersion: '2010-08-01',
  maxRetries: 5,
  retryDelayOptions: { base: 1100 }
});

// v3 api
import { CloudWatch } from '@aws-sdk/client-cloudwatch'
import { ConfiguredRetryStrategy } from '@aws-sdk/util-retry'
const cloudwatch = new CloudWatch({
  apiVersion: '2010-08-01',
  retryStrategy: new ConfiguredRetryStrategy(6, 1100)
});
```

_Originally posted by @cdignam-segment in https://github.com/aws/aws-sdk-js-v3/issues/3611#issuecomment-1662824777_

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/Package/-aws-sdk-util-retry/

**Comment by RanVaknin** [comment]
Hi @joebowbeer ,

Thanks for bringing this to our attention. This information can be found in the [`UPGRADING.md`](https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md) doc in our repo. I have fixed the link to direct customers to the new docs - pulling info from the smithy-typescript repo which is the new owner of that `util-retry` package. 

Thanks again,
Ran~
