### ISSUE TITLE
Missing upgrade instructions for `apis/metadata.json`

### ISSUE THREAD

**Issue by mrgrain** [aws/aws-sdk-js-v3#5176]
### Describe the issue

The AWS CDK team has relied on the `metadata.json` file that is shipped as part of SDK v2 to programmatically extract information about the SDK.
https://github.com/aws/aws-sdk-js/blob/master/apis/metadata.json

The upgrading guide does not include instructions how to migrate this feature.

### Links

https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md
https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/migrating-to-v3.html

**Comment by RanVaknin** [comment]
Hi @mrgrain ,

`metadata.json` on v2 was done for internal consumption, and not for external use. 
I will contact you internally for further steps. 

Thanks,
Ran~
