### ISSUE TITLE
"CredentialsProviderError: Profile is configured with invalid SSO credentials" when setting session name

### ISSUE THREAD

**Issue by nikki603** [aws/aws-sdk-js-v3#5186]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

`fromIni` credentials returned using a profile created by AWS SSO CLI and setting an SSO session name as recommended throw an CredentialsProviderError when trying to use them in any AWS SDK client request. There is no issue when SSO session name is left blank.

### SDK version number

@aws-sdk/credential-providers@3.405.0, @aws-sdk/client-sts": "3.405.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.16.0

### Reproduction Steps

1. Configure SSO with a session name.
```
> aws configure sso
SSO session name (Recommended): test
SSO start URL [None]: https://d-xxxx.awsapps.com/start
SSO region [None]: us-east-1
SSO registration scopes [sso:account:access]:
...

> aws --version
aws-cli/2.13.2 Python/3.11.4 Windows/10 exe/AMD64 prompt/off
```

This updates the ~/.aws/config file like:
```
[profile my-sso]
sso_session = test
sso_account_id = 11111111111
sso_role_name = Admin
region = us-east-1
output = json
[sso-session test]
sso_start_url = https://d-xxxx.awsapps.com/start
sso_region = us-east-1
sso_registration_scopes = sso:account:access
```

3. Get credentials and try to use them
app.js

```
import { STSClient, GetCallerIdentityCommand } from "@aws-sdk/client-sts";
import { fromIni } from "@aws-sdk/credential-providers";

const credentials = fromIni({ profile: "my-sso" });
const stsclient = new STSClient({ credentials: credentials });
const stscommand = new GetCallerIdentityCommand({});
await stsclient.send(stscommand);
```

```
> node app.js
```

### Observed Behavior

C:\Projects\aws-sts-debug\node_modules\@aws-sdk\credential-provider-sso\dist-cjs\validateSsoProfile.js:8
        throw new property_provider_1.CredentialsProviderError(`Profile is configured with invalid SSO credentials. Required 
parameters "sso_account_id", ` +
              ^

CredentialsProviderError: Profile is configured with invalid SSO credentials. Required parameters "sso_account_id", "sso_region", "sso_role_name", "sso_start_url". Got sso_session, sso_account_id, sso_role_name, region, output
Reference: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html
    at validateSsoProfile (C:\Projects\aws-sts-debug\node_modules\@aws-sdk\credential-provider-sso\dist-cjs\validateSsoProfile.js:8:15)
    at resolveSsoCredentials (C:\Projects\aws-sts-debug\node_modules\@aws-sdk\credential-provider-ini\dist-cjs\resolveSsoCredentials.js:8:136)
    at resolveProfileData (C:\Projects\aws-sts-debug\node_modules\@aws-sdk\credential-provider-ini\dist-cjs\resolveProfileData.js:28:66)
    at C:\Projects\aws-sts-debug\node_modules\@aws-sdk\credential-provider-ini\dist-cjs\fromIni.js:8:56
    at async coalesceProvider (C:\Projects\aws-sts-debug\node_modules\@smithy\property-provider\dist-cjs\memoize.js:14:24)   
    at async SignatureV4.credentialProvider (C:\Projects\aws-sts-debug\node_modules\@smithy\property-provider\dist-cjs\memoize.js:33:24)
    at async SignatureV4.signRequest (C:\Projects\aws-sts-debug\node_modules\@smithy\signature-v4\dist-cjs\SignatureV4.js:106:29)
    at async C:\Projects\aws-sts-debug\node_modules\@aws-sdk\middleware-signing\dist-cjs\awsAuthMiddleware.js:16:18
    at async C:\Projects\aws-sts-debug\node_modules\@smithy\middleware-retry\dist-cjs\retryMiddleware.js:27:46
    at async C:\Projects\aws-sts-debug\node_modules\@aws-sdk\middleware-logger\dist-cjs\loggerMiddleware.js:7:26 {
  tryNextLink: false,
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}

### Expected Behavior

STS GetCallerIdentityCommand is successful.

**Comment by JFMajer** [comment]
I had similar issue and I think that you need to change fromIni to fromSSO.
Then your code should work.

```
import { fromSSO } from "@aws-sdk/credential-providers";

const REGION = "eu-north-1";

const client = new STSClient({
  region: REGION,
  credentials: fromSSO({ profile: "dev" }),
});
```

In your case:
```
import { STSClient, GetCallerIdentityCommand } from "@aws-sdk/client-sts";
import { fromSSO } from "@aws-sdk/credential-providers";

const credentials = fromSSO({ profile: "my-sso" });
const stsclient = new STSClient({ credentials: credentials });
const stscommand = new GetCallerIdentityCommand({});
await stsclient.send(stscommand);
```

**Comment by nikki603** [comment]
duplicate of https://github.com/aws/aws-sdk-js-v3/issues/5158

**Comment by nikki603** [comment]
decided to go with 
```
import { STSClient, GetCallerIdentityCommand } from "@aws-sdk/client-sts";
import { fromNodeProviderChain } from "@aws-sdk/credential-providers";

const credentialProvider = fromNodeProviderChain({ profile: "my-sso" });
const stsclient = new STSClient({ credentials: credentialProvider });
const stscommand = new GetCallerIdentityCommand({});
await stsclient.send(stscommand);
```
