### ISSUE TITLE
Import error in @smithy/hash-node module: No matching export in "node-modules-polyfills:crypto" for import "createHmac" / "createHash" 

### ISSUE THREAD

**Issue by ashwinstrellix** [aws/aws-sdk-js-v3#5205]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I am using @smithy/hash-node for my usecase on generating pre-signed url without client to download artifacts from S3 bucket. Usage is via cloudflare's wrangler java script code. During code deploy, in building stage it fails with following errors:

✘ [ERROR] No matching export in "node-modules-polyfills:crypto" for import "createHash"

    node_modules/@smithy/hash-node/dist-es/index.js:4:9:
      4 │ import { createHash, createHmac } from "crypto";
        ╵          ~~~~~~~~~~

✘ [ERROR] No matching export in "node-modules-polyfills:crypto" for import "createHmac"

    node_modules/@smithy/hash-node/dist-es/index.js:4:21:
      4 │ import { createHash, createHmac } from "crypto";
        ╵                      ~~~~~~~~~~

I would able to fix this by changing import to following locally:
`import { createHash, createHmac } from "crypto-browserify";`

I also cross verified whether we have any functions within in-built crypto library too, but its not defined. We need a code fix in @smithy/hash-node to make it work. 

Kindly check once. Thanks

### SDK version number

@aws-sdk/hash-node": "^3.374.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.6.1

### Reproduction Steps

Please refer to code snippet here:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/example_s3_Scenario_PresignedUrl_section.html

### Observed Behavior

✘ [ERROR] No matching export in "node-modules-polyfills:crypto" for import "createHash"

    node_modules/@smithy/hash-node/dist-es/index.js:4:9:
      4 │ import { createHash, createHmac } from "crypto";
        ╵          ~~~~~~~~~~

✘ [ERROR] No matching export in "node-modules-polyfills:crypto" for import "createHmac"

    node_modules/@smithy/hash-node/dist-es/index.js:4:21:
      4 │ import { createHash, createHmac } from "crypto";
        ╵                      ~~~~~~~~~~

### Expected Behavior

Should build without error

### Possible Solution

Changing import from
`import { createHash, createHmac } from "crypto";`
to
`import { createHash, createHmac } from "crypto-browserify";`

**Comment by yenfryherrerafeliz** [comment]
Hi @ashwinstrellix, could you please provide a sample code where it shows how you are using this package?, are you installing this package directly?, or are you using another package that depends on @aws-sdk/hash-node?. In general, I think that the problem here is that the wrong runtime is being targeting when bundling. Please note that @aws-sdk/hash-node is intended to be used in nodejs runtime.

Please let me know.

Thanks!

**Comment by ashwinstrellix** [comment]
@yenfryherrerafeliz  Please find the code snippet provided below:

```
// index.js file (Only relevant code snippet is added here)

import { HttpRequest } from '@aws-sdk/protocol-http'
import { S3RequestPresigner } from '@aws-sdk/s3-request-presigner'
import { Hash } from '@aws-sdk/hash-node'
import { parseUrl } from '@aws-sdk/url-parser'
import { formatUrl } from '@aws-sdk/util-format-url'

const s3_url_obj = parseUrl(`https://${bucket}.s3.${region}.amazonaws.com/${s3_obj_path}`);
const presigner = new S3RequestPresigner({
  credentials: cred,
  region,
  expiresIn: 86400,
  sha256: Hash.bind(null, "sha256"), // In Node.js
});
let s3_req = new HttpRequest(s3_url_obj)
const s3_url = await presigner.presign(s3_req);


// package.json

{
    "name": "example",
    "private": true,
    "version": "1.0.0",
    "description": "package for creating cloudflare workers templates",
    "main": "index.js",
    "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1",
        "format": "prettier --write '**/*.{js,css,json,md}'"
    },
    "devDependencies": {
        "prettier": "^1.17.0"
    },
    "dependencies": {
        "@aws-sdk/hash-node": "^3.374.0",
        "@aws-sdk/protocol-http": "^3.374.0",
        "@aws-sdk/s3-request-presigner": "^3.410.0",
        "@aws-sdk/url-parser": "^3.374.0",
        "@aws-sdk/util-format-url": "^3.410.0",
        "aws-sdk": "^2.958.0"
    }
}

```

**Comment by yenfryherrerafeliz** [comment]
@ashwinstrellix, so basically your issue is that @aws-sdk/hash-node must be used when running on nodejs runtimes, which is not your case, since you are bundling for browsers. The package you should be using in this case is @aws-crypto/sha256-browser and import Sha256 as follow:

```js
import {S3RequestPresigner} from "@aws-sdk/s3-request-presigner";
import {Sha256} from "@aws-crypto/sha256-browser";
import {HttpRequest} from "@aws-sdk/protocol-http";
import {parseUrl} from "@aws-sdk/url-parser";
import {fromIni} from "@aws-sdk/credential-providers";

const bucket = process.env.TEST_BUCKET;
const region = process.env.TEST_REGION;
const s3_obj_path = process.env.TEST_KEY;
const s3_url_obj = parseUrl(`https://${bucket}.s3.${region}.amazonaws.com/${s3_obj_path}`);
const presigner = new S3RequestPresigner({
    credentials: creds,
    expiresIn: 86400,
    sha256: Sha256
});
let s3_req = new HttpRequest(s3_url_obj)
const s3_url = await presigner.presign(s3_req);

console.log(s3_url)
```
I am also curious about why not to use getSignedUrl instead as follow:
```js
import {GetObjectCommand, S3Client} from "@aws-sdk/client-s3";
import {getSignedUrl} from "@aws-sdk/s3-request-presigner";

const client = new S3Client({
    region: "us-east-2"
});
const signedUrl = await getSignedUrl(client, new GetObjectCommand({
    Bucket: process.env.TEST_BUCKET,
    Key: process.env.TEST_KEY
}));

console.log(signedUrl);
```

Please let me know if that helps!

Thanks!

**Comment by ashwinstrellix** [comment]
@yenfryherrerafeliz  yes this helps. Thank you so much.
