### ISSUE TITLE
Missing mapping for QuickSight GenerateEmbedUrlForRegisteredUserCommand FeatureConfigurations property

### ISSUE THREAD

**Issue by Miguel-Henriques** [aws/aws-sdk-js-v3#5208]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

## Summary
Heya,

I am trying to embed the QuickSight dashboards with [State persistence and Bookmarks](https://aws.amazon.com/about-aws/whats-new/2023/05/amazon-quicksight-state-persistence-bookmarks-embedded-dashboards/) features enabled via AWS Lambda using the bundled SDK, however it seems there's 2 issues:

- The latest bundled version of the SDK in Lambda NodeJS 18 is 3.188.0 is entirely missing the mapping of these props
- The latest version of the SDK (at current time) only includes mapping for the State persistence feature

Note the command succeeds, however not with the intended response as the FeatureConfigurations prop is not included in the request body.

#### SDK Version 3.188.0
<img width="1113" alt="bundled_version" src="https://github.com/aws/aws-sdk-js-v3/assets/49489051/f6e97540-bb85-416b-990b-c756b4c0da34">

#### SDK Version (Main)
<img width="904" alt="latest_sdk" src="https://github.com/aws/aws-sdk-js-v3/assets/49489051/de6345dc-e026-457f-869d-00dd5fa470bc">

The expected props are defined under `RegisteredUserDashboardEmbeddingConfiguration`.

These mappings are a by-product of the `serializeAws_restJson1GenerateEmbedUrlForRegisteredUserCommand` body generation.

I didn't immediately open a PR with the fix because I'm not familiar with the typescript generator, however at first sight it seems it originates from there (don't quote me on this).

For now I'll probably just do the API call directly without using the SDK but it would be nice to have this fixed in the meantime.

### SDK version number

@aws-sdk/clients/client-quicksight/src/protocols/Aws_restJson1.ts

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

nodejs:18.v12

### Reproduction Steps

```
const input: GenerateEmbedUrlForRegisteredUserRequest = {
      AwsAccountId: this.clientConfig.accountId,
      UserArn: `arn:aws:quicksight:${this.clientConfig.administrationRegion}:${this.clientConfig.accountId}:user/${this.userConfig.namespace}/${userName}`,
      ExperienceConfiguration: {
        Dashboard: {
          InitialDashboardId: initialDashboardId,
          FeatureConfigurations: {
            StatePersistence: {
              Enabled: true,
            },
            Bookmarks: {
              Enabled: true,
            },
          },
        },
      },
    };
    const command = new GenerateEmbedUrlForRegisteredUserCommand(input);
    const response = await this.baseClient.send(command);
```

### Observed Behavior

I did set up a middleware to observe the HTTP request before/after serialization:

![Screenshot 2023-09-13 at 19 10 17](https://github.com/aws/aws-sdk-js-v3/assets/49489051/0d93c788-1437-488b-a6ee-316118c7b20b)

### Expected Behavior

The API call should include the `FeatureConfigurations` prop as part of the `RegisteredUserDashboardEmbeddingConfiguration`.

### Possible Solution

I believe there may be something wrong with the Typescript generator considering the models are well defined and the mappings seem to be generated.

**Comment by RanVaknin** [comment]
Hi @Miguel-Henriques ,

>The latest bundled version of the SDK in Lambda NodeJS 18 is 3.188.0 is entirely missing the mapping of these props

The SDK team does not control the version Lambda vends. This is controlled by the lambda team and changes every 6 or so months. You can [bundle your own SDK](https://aws.amazon.com/blogs/compute/optimizing-node-js-dependencies-in-aws-lambda/) and upload it to Lambda to mitigate this.

>The latest version of the SDK (at current time) only includes mapping for the State persistence feature

Which SDK version are you using? 

I used this code and can see that the request body does contain `FeatureConfigurations`:

```js
import { QuickSightClient,GenerateEmbedUrlForRegisteredUserCommand } from "@aws-sdk/client-quicksight";

  const userConfig = {
    namespace: "myNamespace",
    userName: "myUsername",
  };
  const initialDashboardId = "myDashboardID";
  
  const quickSightClient = new QuickSightClient({region:"us-east-1"});
  

  quickSightClient.middlewareStack.add(next => args => {
      console.log('before sign: ' , args.request);
      return next(args);
  }, {step: 'build'})

  try {
    const response = await quickSightClient.send(new GenerateEmbedUrlForRegisteredUserCommand({
      AwsAccountId: "REDACTED",
      UserArn: `arn:aws:quicksight:us-east-1:REDACTED:REDACTED/${userConfig.namespace}/${userConfig.userName}`,
      ExperienceConfiguration: {
        Dashboard: {
          InitialDashboardId: initialDashboardId,
          FeatureConfigurations: {
            StatePersistence: {
              Enabled: true,
            },
            Bookmarks: {
              Enabled: true,
            },
          },
        },
      },
    }))
    console.log(response)
  } catch (err) {
    console.log(err)
  }
```

Will result in `FeatureConfigurations` being serialized correctly:
```
before sign:  HttpRequest {
  method: 'POST',
  hostname: 'quicksight.us-east-1.amazonaws.com',
  port: undefined,
  query: {},
  headers: { 'content-type': 'application/json', 'content-length': '254' },
  body: '{"ExperienceConfiguration":{"Dashboard":{"InitialDashboardId":"myDashboardID","FeatureConfigurations":{"StatePersistence":{"Enabled":true},"Bookmarks":{"Enabled":true}}}},"UserArn":"arn:aws:quicksight:us-east-1:REDACTED:REDACTED/myNamespace/myUsername"}',
  protocol: 'https:',
  path: '/accounts/REDACTED/embed-url/registered-user',
  username: undefined,
  password: undefined,
  fragment: undefined
}
```



My guess is that your application is not using the most up to date version of the SDK.

Let me know if this helps.
Thanks,
Ran~

**Comment by Miguel-Henriques** [comment]
Yup it does help thanks, I'll close the issue.
