### ISSUE TITLE
lib-storage + S3Client: credentials are not refreshed

### ISSUE THREAD

**Issue by bes** [aws/aws-sdk-js-v3#5215]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I have some upload code (TS + webpack, browser target), where large uploads take a long time to finish - more than one hour. The AWS credentials I received from my backend expire after one hour, so I need to refresh them, but I can't figure out how. I tried using the function signature for the configuration field of `credentials` of the S3Client, but it's not called again after the original credentials expire.

### SDK version number

"@aws-sdk/client-s3": "^3.400.0", "@aws-sdk/lib-storage": "^3.400.0",

### Which JavaScript Runtime is this issue in?

Browser

### Details of the browser/Node.js/ReactNative version

Chrome: 116.0.5845.187 Safari: 16.6

### Reproduction Steps

I use macOS Network Link Conditioner to slow down a large upload, and then I wait more than one hour.
After one hour the chunked upload starts failing, but I don't see a new call to `credentials: async (): Promise<AwsCredentialIdentity>`.

```typescript
import { S3Client } from "@aws-sdk/client-s3";
import { Upload } from "@aws-sdk/lib-storage";
import type { AwsCredentialIdentity } from "@aws-sdk/types/dist-types/identity/AwsCredentialIdentity";

// ...

const selectedFile: File = //...
const bucket: string = //...
const region: string = // ...
const key: string = // ...
const multipartUpload = new Upload({
  client: new S3Client({
    maxAttempts: 10,
    region,
    credentials: async (): Promise<AwsCredentialIdentity> => {
      console.log("REFRESHING CREDENTIALS!");
      const session = await getNewSessionFromBackend(); 
      const { accessKeyId, secretAccessKey, sessionToken } = session.uploadCredentials;
      return {
        accessKeyId,
        secretAccessKey,
        sessionToken,
      };
    },
  }),
  params: { Bucket: bucket, Key: key, Body: selectedFile },
});

// Irrelevant, but for completeness:
multipartUpload.on("httpUploadProgress", handleUploadProgress);
multipartUpload.done().then(handleUploadResponse).catch(handleUploadError);
```

### Observed Behavior

Upload keeps failing until retries run out.

### Expected Behavior

I expected the `credentials` function to be called after one hour, when the credentials expired

### Possible Solution

I suggest that the function form of the `credentials` property of the S3Client config be called when the credentials expire.

**Comment by ajredniwja** [comment]
Hi there thanks for opening the issue, how are you accessing the credentials on the blackened?

**Comment by bes** [comment]
Hi @ajredniwja
We have an authenticated API (Google OAuth) that generates an AWS token with a 1 hour timeout.

**Comment by bes** [comment]
I've switched to another library, so I am closing the issue. The issue still remains though, neither lib-storage nor S3Client have any facilities for refreshing credentials once expired.
