### ISSUE TITLE
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by MwSpaceLLC** [aws/aws-sdk-js-v3#5216]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

if i try to use @aws-sdk/s3-request-presigner in nextjs application, on api endpoint in app router configuration, we have a this trask stack errors:

```
- wait compiling...
- warn ./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/load-crt.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

Import trace for requested module:
./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/load-crt.js
./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/SignatureV4MultiRegion.js
./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/index.js
./node_modules/@aws-sdk/s3-request-presigner/dist-cjs/presigner.js
./node_modules/@aws-sdk/s3-request-presigner/dist-cjs/index.js
./helpers/aws/s3.js
./app/api/admin/products/upsert/route.js

```

### SDK version number

@aws-sdk/package-name@version, ...

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.15.0

### Reproduction Steps

create a fresh install on nextjs, and install @aws-sdk/s3-request-presigner for use it

### Observed Behavior

- wait compiling...
- warn ./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/load-crt.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

Import trace for requested module:
./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/load-crt.js
./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/SignatureV4MultiRegion.js
./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/index.js
./node_modules/@aws-sdk/s3-request-presigner/dist-cjs/presigner.js
./node_modules/@aws-sdk/s3-request-presigner/dist-cjs/index.js
./helpers/aws/s3.js
./app/api/admin/products/upsert/route.js

### Expected Behavior

not log warn critical, i think the dynamic module cjs load is no functional on nextjs

**Comment by MwSpaceLLC** [comment]
Possible resolution on livetime on nextjs:

**next.config.js**

```
/** @type {import('next').NextConfig} */
const nextConfig = {

    webpack: (config, {buildId, dev, isServer, defaultLoaders, webpack}) => {
        config.externals.push({
            '@aws-sdk/signature-v4-multi-region': 'commonjs @aws-sdk/signature-v4-multi-region',
        })

        return config
    },
}

module.exports = nextConfig

```

**Comment by ajredniwja** [comment]
I see https://github.com/aws/aws-sdk-js-v3/pull/5225 removes the dynamic imports which should fix this issue.

**Comment by kuhe** [comment]
#5225 is a proposal and not yet decided upon.

Dynamic require is something that we use right now and is needed for checking whether signature-v4-crt is available. 
You should continue using the available workarounds for now.

**Comment by gauthierm** [comment]
You can also work around this issue by adding a dependency and statically importing the required implementation. See the implementation details of:

https://github.com/aws/aws-sdk-js-v3/blob/main/packages/signature-v4-multi-region/src/load-crt.ts#L18-L28

```sh
npm require @aws-sdk/signature-v4-crt
```

```ts
import "@aws-sdk/signature-v4-crt";
```

**Comment by viana-vitor** [comment]
Just importing "@aws-sdk/signature-v4-crt" does not get rid of the warning for me, but adding the following does:

> Possible resolution on livetime on nextjs:
> 
> **next.config.js**
> 
> ```
> /** @type {import('next').NextConfig} */
> const nextConfig = {
> 
>     webpack: (config, {buildId, dev, isServer, defaultLoaders, webpack}) => {
>         config.externals.push({
>             '@aws-sdk/signature-v4-multi-region': 'commonjs @aws-sdk/signature-v4-multi-region',
>         })
> 
>         return config
>     },
> }
> 
> module.exports = nextConfig
> ```

However, when I deploy the app i get the following error:
`Error: AWS CRT binary not present in any of the following locations:
	/var/task/node_modules/aws-crt/dist/bin/linux-x64-glibc/aws-crt-nodejs
    at Object.<anonymous> (/var/task/node_modules/aws-crt/dist/native/binding.js:97:11)`

Am I missing anything? @kuhe

**Comment by kyriacos** [comment]
@viana-vitor I'm actually going through this right now and trying different fixes myself :). Are you seeing that on Vercel also? 

Downgrading the packages to the older ones without CRT seems to not crash:

```js
    "@aws-sdk/client-s3": "3.28.0",
    "@aws-sdk/credential-providers": "3.28.0",
    "@aws-sdk/s3-request-presigner": "3.28.0",
    "aws-sdk": "2.1480.0",
```
And i removed that line from nextConfig as well.

I found a comment on [here]( https://github.com/aws/aws-sdk-js-v3/issues/2753#:~:text=This%20broke%20our%20functions%20in%20production.%20Rolling%20back%20to%203.28.0%20of%20the%20SDK%20fixed%20it)

Let me know if that works for you.

**Comment by viana-vitor** [comment]
Hey @kyriacos, I just rolled back to the 3.28 version and everything works now. 

Kinda sad that this appears to be the most simple solution

Thank you for letting me know!

**Comment by kyriacos** [comment]
@kuhe Is this fixed now as well? I was already importing the module in #5225 and was getting the missing binary.
