### ISSUE TITLE
@aws-sdk/s3-request-presigner getSignedUrl second params wrong type.

### ISSUE THREAD

**Issue by ethyaan** [aws/aws-sdk-js-v3#5217]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

![image](https://github.com/aws/aws-sdk-js-v3/assets/6294823/2c04840a-a1f5-4bc1-8962-d2b6db4b15a3)

Please take a look at this, cause my builds to fail after update.

### SDK version number

@aws-sdk/s3-request-presigner

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.12.1

### Reproduction Steps

Just try the AWS official example of using "getSignedUrl" 

### Observed Behavior

compile fails, because of type miss-match 

### Expected Behavior

it should not cause the build to fail.

**Comment by ethyaan** [comment]
More detail

➜  straim-processor git:(development) ✗ yarn --cwd ./app build     
yarn run v1.22.19
$ tsc && cp package.json ../build
a.ts:8:32 - error TS2345: Argument of type 'GetObjectCommand' is not assignable to parameter of type 'Command<GetObjectCommandInput, GetObjectCommandOutput, any, ServiceInputTypes, MetadataBearer>'.
  Types of property 'resolveMiddleware' are incompatible.
    Type '(clientStack: MiddlewareStack<ServiceInputTypes, ServiceOutputTypes>, configuration: S3ClientResolvedConfig, options?: HttpHandlerOptions | undefined) => Handler<...>' is not assignable to type '(stack: MiddlewareStack<ServiceInputTypes, MetadataBearer>, configuration: any, options: any) => Handler<GetObjectCommandInput, GetObjectCommandOutput>'.
      Types of parameters 'clientStack' and 'stack' are incompatible.
        Type 'MiddlewareStack<ServiceInputTypes, MetadataBearer>' is not assignable to type 'MiddlewareStack<ServiceInputTypes, ServiceOutputTypes>'.
          Types of property 'concat' are incompatible.
            Type '<InputType extends ServiceInputTypes, OutputType extends MetadataBearer>(from: MiddlewareStack<InputType, OutputType>) => MiddlewareStack<InputType, OutputType>' is not assignable to type '<InputType extends ServiceInputTypes, OutputType extends ServiceOutputTypes>(from: MiddlewareStack<InputType, OutputType>) => MiddlewareStack<...>'.
              Types of parameters 'from' and 'from' are incompatible.
                Type 'MiddlewareStack<InputType, OutputType>' is not assignable to type 'MiddlewareStack<InputType, MetadataBearer>'.
                  Types of property 'addRelativeTo' are incompatible.
                    Type '(middleware: MiddlewareType<InputType, OutputType>, options: RelativeMiddlewareOptions) => void' is not assignable to type '(middleware: MiddlewareType<InputType, MetadataBearer>, options: RelativeMiddlewareOptions) => void'.
                      Types of parameters 'middleware' and 'middleware' are incompatible.
                        Type 'MiddlewareType<InputType, MetadataBearer>' is not assignable to type 'MiddlewareType<InputType, OutputType>'.
                          Type 'InitializeMiddleware<InputType, MetadataBearer>' is not assignable to type 'MiddlewareType<InputType, OutputType>'.
                            Type 'InitializeMiddleware<InputType, MetadataBearer>' is not assignable to type 'InitializeMiddleware<InputType, OutputType>'.
                              Call signature return types 'InitializeHandler<InputType, MetadataBearer>' and 'InitializeHandler<InputType, OutputType>' are incompatible.
                                Type 'Promise<InitializeHandlerOutput<MetadataBearer>>' is not assignable to type 'Promise<InitializeHandlerOutput<OutputType>>'.
                                  Type 'InitializeHandlerOutput<MetadataBearer>' is not assignable to type 'InitializeHandlerOutput<OutputType>'.
                                    Types of property 'output' are incompatible.
                                      Type 'MetadataBearer' is not assignable to type 'OutputType'.
                                        'MetadataBearer' is assignable to the constraint of type 'OutputType', but 'OutputType' could be instantiated with a different subtype of constraint 'ServiceOutputTypes'.

8  return await getSignedUrl(s3, command, { expiresIn });
                                 ~~~~~~~

index.ts:34:36 - error TS2345: Argument of type 'GetObjectCommand' is not assignable to parameter of type 'Command<GetObjectCommandInput, GetObjectCommandOutput, any, ServiceInputTypes, MetadataBearer>'.

34  return await getSignedUrl(client, new GetObjectCommand(), { expiresIn });
                                      ~~~~~~~~~~~~~~~~~~~~~~

**Comment by ethyaan** [comment]
@yenfryherrerafeliz can you take look at this?

**Comment by ethyaan** [comment]
Anyone any idea? any update?
@trivikr @AllanZhengYP @kuhe @srchase @jeskew @kstich 
Does this repository has any owner? Why AWS team is always behind in support?
I'm paying to use a service that has many features and yet many of them not working because apparently nobody care about testing and automated test.
Suddenly I have to find out that Oh my build is breaking because someone did some update and the code that was working based on the documentation is not working anymore. 
Write some god damn test before release, put clients bug in priority.

**Comment by justinIs** [comment]
> Anyone any idea? any update? 

I am having the same issue, can you say which version you are currently using? You might need to check your `package/yarn.lock` file to see which version is installed if your package.json has `^` kinda thing

This seems to happen for me on `4.412.0`

It seems like `4.413.0` has been released and the issue is resolved for me.

**Comment by ethyaan** [comment]
Hi, I just ran my build again and it worked, I believe the latest updates fixed this issue.
Thank you for informing and following up. I appreciate .

**Comment by alainfonhof** [comment]
The bug seems to be back in `3.414.0`.
