### ISSUE TITLE
Warning: in ./node_modules/@aws-sdk/util-user-agent-node/dist-es/is-crt-available.js 3:78-96

### ISSUE THREAD

**Issue by jomaora** [aws/aws-sdk-js-v3#5221]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I'm upgrading a project from Node16 to Node18, and also migrating aws-sdk@2 to aws-sdk@3. 

While packaging or lauching `serverless` to run the lambdas, here's the warning that I've got

````
Warning: in ./node_modules/@aws-sdk/util-user-agent-node/dist-es/is-crt-available.js 3:78-96
  Module not found: Error: Can't resolve 'aws-crt' in '/Users/joan/workspace/coorpacademy-lambda/api-review/node_modules/@aws-sdk/util-user-agent-node/dist-es'
````

### SDK version number

@aws-sdk/client-kinesis@3.409.0,@aws-sdk/util-user-agent-node@3.405.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Nodejs v18.17.0 (npm v9.6.7)

### Reproduction Steps

```
➜  npx serverless package
serverless-offline-ssm checking serverless version 3.34.0.

Packaging api-review for stage development (eu-west-1)

Warning: in ./node_modules/aws-crt/dist/native/binding.js 92:18-31
  Critical dependency: the request of a dependency is an expression
  
Creating nested stacks in Cloudformation...
Stack: resources.cfn.yml

✔ Service packaged (16s)
```

### Observed Behavior

Here are the packages that I've changed

![Capture d’écran 2023-09-15 à 16 37 47](https://github.com/aws/aws-sdk-js-v3/assets/7602475/d9320efd-5b8d-4738-856f-b44050dcefe8)
![Capture d’écran 2023-09-15 à 16 38 03](https://github.com/aws/aws-sdk-js-v3/assets/7602475/5c1a5992-adaf-4a92-9196-5ad49373d570)

Using `@aws-sdk/client-kinesis` there's a dependency to `@aws-sdk/util-user-agent-browser`, which uses `aws-crt`.  Here's what I've got on my package-lock.json

```
    "node_modules/@aws-sdk/client-kinesis/node_modules/@aws-sdk/util-user-agent-node": {
      "version": "3.408.0",
      "resolved": "https://registry.npmjs.org/@aws-sdk/util-user-agent-node/-/util-user-agent-node-3.408.0.tgz",
      "integrity": "sha512-BzMFV+cIXrtfcfJk3GpXnkANFkzZisvAtD306TMgIscn5FF26K1jD5DU+h5Q5WMq7gx+oXh9kJ3Lu3hi7hahKQ==",
      "dependencies": {
        "@aws-sdk/types": "3.408.0",
        "@smithy/node-config-provider": "^2.0.6",
        "@smithy/types": "^2.2.2",
        "tslib": "^2.5.0"
      },
      "engines": {
        "node": ">=14.0.0"
      },
      "peerDependencies": {
        "aws-crt": ">=1.0.0"
      },
      "peerDependenciesMeta": {
        "aws-crt": {
          "optional": true
        }
      }
    },
    "node_modules/@aws-sdk/util-user-agent-node": {
      "version": "3.405.0",
      "resolved": "https://registry.npmjs.org/@aws-sdk/util-user-agent-node/-/util-user-agent-node-3.405.0.tgz",
      "integrity": "sha512-6Ssld7aalKCnW6lSGfiiWpqwo2L+AmYq2oV3P9yYAo9ZL+Q78dXquabwj3uq3plJ4l2xE4Gfcf2FJ/1PZpqDvQ==",
      "dependencies": {
        "@aws-sdk/types": "3.398.0",
        "@smithy/node-config-provider": "^2.0.6",
        "@smithy/types": "^2.2.2",
        "tslib": "^2.5.0"
      },
      "engines": {
        "node": ">=14.0.0"
      },
      "peerDependencies": {
        "aws-crt": ">=1.0.0"
      },
      "peerDependenciesMeta": {
        "aws-crt": {
          "optional": true
        }
      }
    },
```
- I've seen that a similar error has been pointed [here](https://github.com/aws/aws-sdk-js-v3/issues/2885) and [here](https://github.com/aws/aws-sdk-js-v3/issues/2750) but in my case I'm not using .@aws-sdk/client-s3.
- I've also updated to the latest version of @aws-sdk/client-kinesis (3.413.0 - today) but the warning remains. 
- I've tried to install this `aws-crt` even if I should not because it's not indicated anywhere. When doing it, I've a new warning appears

```
Warning: in ./node_modules/aws-crt/dist/native/binding.js 92:18-31
  Critical dependency: the request of a dependency is an expression
```

### Expected Behavior

How can I stop this warning?

### Possible Solution

Is there something to do on this `@aws-sdk/util-user-agent-node` to avoid this problem. Maybe.

Thanks.

**Comment by kuhe** [comment]
this warning doesn't appear for me in Node.js 18 without serverless because the `require` call is made in a try/catch block and any thrown error is ignored.

You should ignore the warning, and it is necessary for the SDK to check if the aws-crt package is installed. I will try it with require.resolve instead of require for Node.js and import.meta in dist-es.
