### ISSUE TITLE
Memory leaks in the DynamoDBClient, and DynamoDBDocumentClient

### ISSUE THREAD

**Issue by symbianm** [aws/aws-sdk-js-v3#5230]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

We are experiencing issues with the DynamoDBClient, and DynamoDBDocumentClient. 
Memory usage grows with every request until the application crashes.
It can be reproduced with the basic express app with no dependencies except AWS SDK.

### SDK version number

@aws-sdk/client-dynamodb@3.410.0, @aws-sdk/lib-dynamodb@3.410.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.17.1

### Reproduction Steps

- Set up basic Node.js/Express "Hello World" project with the DynamoDB client.
https://expressjs.com/en/starter/hello-world.html
https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/javascript_dynamodb_code_examples.html
- Run it `npm start`
- Open http://localhost:3000/
- Refresh the page and observe memory leaks

index.js

```
const express = require('express')
const { DynamoDBClient } = require('@aws-sdk/client-dynamodb');
const {
  DynamoDBDocumentClient,
  ScanCommand,
} = require('@aws-sdk/lib-dynamodb');

const app = express()
const port = 3000
const client = new DynamoDBClient({ region: 'us-west-2' });
const docClient = DynamoDBDocumentClient.from(client);

app.get('/', async (req, res) => {
  const command = new ScanCommand({
    TableName: 'company_information',
  });
  const response = await docClient.send(command);
  res.json(response);
})

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
})
```

package.json

```
{
  "name": "test-app",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "AWS_PROFILE=onqpm TZ=UTC NODE_ENV=development node --inspect --trace-gc ./index.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@aws-sdk/client-dynamodb": "^3.410.0",
    "@aws-sdk/lib-dynamodb": "^3.410.0",
    "express": "^4.18.2"
  }
}
```

### Observed Behavior

I refreshed the page 3 times and the memory grew with every request:
<img width="1676" alt="Screenshot 2023-09-19 at 7 20 03" src="https://github.com/aws/aws-sdk-js-v3/assets/3383599/a7bcd8e2-f0b8-493e-932c-7ea614661865">

Almost all those deltas are related to the AWS SDK
<img width="1675" alt="Screenshot 2023-09-19 at 7 26 12" src="https://github.com/aws/aws-sdk-js-v3/assets/3383599/c09487d3-7945-4361-aec2-fc509311f59e">

### Expected Behavior

The memory should be garbage collected

### Additional Information/Context

The same issue happens even with the RAW Node.js setup without an Express.js

**Comment by RanVaknin** [comment]
Hi @symbianm ,

Thanks for the detailed reproduction. A few follow up questions:

1. Which fields in the profiler in specific point you towards a memory leak?
2. What happens when you remove the SDK dependencies and how does it look from a profiler standpoint? 

I ran your code from the browser and using the chrome debug tools Ive noticed the heap size grows regardless if the application uses the SDK  or a different client like axios. 

Thanks!
Ran~

**Comment by symbianm** [comment]
Hi @RanVaknin.
Nice to meet you and thanks for the questions.

1. It is a good question and I was hoping you would help me with that. I see all those deltas and objects in memory that are related to the AWS SDK and they just growing.
2. Probably, you have already tried to do this and know the answer. 
I tried this really simple app.

```
const express = require('express');
const app = express();
const port = 3000;

app.get('/', (req, res) => {
  res.json({ success: true });
});

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`);
});
```

And I have got interesting results after making four requests. All those deltas grow too, but they are related to the Node.js core.

<img width="1678" alt="Screenshot 2023-09-29 at 8 13 11" src="https://github.com/aws/aws-sdk-js-v3/assets/3383599/c57fcb3b-8d6b-47fa-93a4-83921be34df3">
<img width="1677" alt="Screenshot 2023-09-29 at 8 15 24" src="https://github.com/aws/aws-sdk-js-v3/assets/3383599/bc952c30-e4fb-4adf-b99c-38b760d5fc50">

But here is the trick. When I make more requests like this `ab -n 10000 http://localhost:3000/` the memory grows on the beginning but gets garbage collected with time.
<img width="1674" alt="Screenshot 2023-09-29 at 8 23 24" src="https://github.com/aws/aws-sdk-js-v3/assets/3383599/82724c44-c751-4a10-9e4a-a19a30207881">

But when I am using AWS SDK it just grows and is not collected. Am I missing something?
<img width="1671" alt="Screenshot 2023-09-29 at 8 34 21" src="https://github.com/aws/aws-sdk-js-v3/assets/3383599/1f33d90f-b01b-4c38-ab4d-f9cbe6ae3659">

**Comment by kuhe** [comment]
DynamoDBDocumentClient appears memory-stable to me.

```js
import { DynamoDB } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocument, GetCommand, PutCommand } from "@aws-sdk/lib-dynamodb";
import { setFlagsFromString } from "v8";
import { runInNewContext } from "vm";

setFlagsFromString("--expose_gc");
const gc = runInNewContext("gc");

const client = new DynamoDB({});
const doc = DynamoDBDocument.from(client);

setInterval(async () => {
  const mem = process.memoryUsage();
  console.log((((mem.heapUsed / mem.heapTotal) * 100) | 0) + "%", "of", mem.heapTotal.toLocaleString(), "bytes");

  const putCommand = new PutCommand({
    TableName: "test",
    Item: {
      id: "1",
      data: Array.from({
        length: 12,
      }).fill(1),
    },
  });

  putCommand.resolveMiddleware(doc.middlewareStack, doc.config, {});

  await doc.send(putCommand);

  const getCommand = new GetCommand({
    TableName: "test",
    Key: {
      id: "1",
    },
  });

  const get = await doc.send(getCommand);

  gc();
}, 800);

```

No visible movement after stabilizing at 83% of 19mb

```
53% of 33,370,112 bytes
45% of 34,680,832 bytes
45% of 34,942,976 bytes
45% of 34,942,976 bytes
45% of 34,942,976 bytes
46% of 34,942,976 bytes
45% of 35,205,120 bytes
46% of 35,205,120 bytes
45% of 35,467,264 bytes
46% of 35,467,264 bytes
46% of 35,467,264 bytes
46% of 35,467,264 bytes
46% of 35,467,264 bytes
46% of 35,467,264 bytes
46% of 35,467,264 bytes
46% of 35,467,264 bytes
46% of 35,467,264 bytes
46% of 35,467,264 bytes
46% of 35,467,264 bytes
46% of 35,467,264 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
83% of 19,738,624 bytes
```

"Allocation failure" in debug message is not an indication of your application running OOM. Memory usage expands when available to limit GC cycles.

**Comment by kuhe** [comment]
Depending on what the error message is in your production server, it may point to something else.

Also, if you can show reproduction code of the memory leak without Express, please add that here.
