### ISSUE TITLE
Improve SDK examples - use idempotent methods by default

### ISSUE THREAD

**Issue by piotrekwitkowski** [aws/aws-sdk-js-v3#5233]
### Describe the issue

The AWS SDK for JavaScript provides examples for client modules that are often the first methods taken from any given module. As a result, the examples often use non-idempotent methods. This can lead to unexpected changes in AWS resources when developers use these examples. For instance, the [AWS CloudFront client module currently uses the `AssociateAliasCommand` method](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-cloudfront/#usage), which is not idempotent.

![image](https://github.com/aws/aws-sdk-js-v3/assets/17732966/3d864321-9b90-49d4-9e58-5cf8e1598157)

### Proposed Improvement

I propose that we improve the AWS SDK for JavaScript by revising the examples used/provided in client modules. Instead of using just any method, we should prioritise using idempotent methods as examples, wherever possible. Idempotent methods are not only safer but also easier for users to work with since they can be executed multiple times without causing unintended side effects or modifying the system state. Us an example, we couldL
- provide the particular method to use in the example for every client module, like `ListDistributions` for the CloudFront client, `ListInstances` for the EC2 client, etc
- use the first `List*` command available on any client module
- fallback to any (first) method from the module - basically use anything what we have today

### Benefits:

**Better DX**: Using idempotent methods in examples will improve the overall user experience for developers using the SDK. These examples will be more straightforward to use, as users can simply copy and paste them without needing to make adjustments for non-idempotent methods.

**Reduced Risk**: By showcasing idempotent methods, we reduce the risk of users inadvertently making changes to their AWS resources while experimenting with the SDK. This can help prevent costly mistakes and reduce support requests.

### Links

https://github.com/aws/aws-sdk-js-v3/tree/main/clients/client-cloudfront#usage

**Comment by RanVaknin** [comment]
Hi @piotrekwitkowski ,

Thanks for the documentation suggestions. You make a reasonable argument but in the spirit of transparency I'll say that this feature request is unlikely to get implemented in the near future. There is a large list of more precedented enhancements that are needed with our new docs. 

I'll add this to our backlog as a house keeping item.

Thanks again for your feedback.
Ran~
