### ISSUE TITLE
StreamingBlobPayloadInputTypes is effectivly `any` due to empty ReadableStream interface

### ISSUE THREAD

**Issue by everett1992** [aws/aws-sdk-js-v3#5237]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

In a node project StreamingBlobPayloadInputTypes is effectively `any`. I think it's because of the stub definitions of `ReadableStream` included in the union. @aws-sdk/types defines empty interfaces for ReadableStream and Blob

https://github.com/aws/aws-sdk-js-v3/blob/main/packages/types/src/serde.ts#L29

### SDK version number

@aws-sdk/client-s3@3.417.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.16.0

### Reproduction Steps

https://stackblitz.com/edit/stackblitz-starters-rdvp6x?file=index.ts

```js
import { PutObjectCommand, } from '@aws-sdk/client-s3'
import { StreamingBlobPayloadInputTypes } from '@smithy/types'


// none of these would work as a body but this aren't a typescript error.
const typeCheckOkay: StreamingBlobPayloadInputTypes[] = [
  1,
  "what",
  [],
  function foo() {},

  function *foo() { yield "what" },
]

// This is how I noticed the bug, I refactored a Readable into a generator and there wasn't a type error on s3 body. At first I was excited in case the sdk could handle generators as streams, but I realized it was a bug. 
new PutObjectCommand({
  Bucket: "Bucket",
  Key: "Key",
  Body: someGenerator(),
})
```

### Observed Behavior

PutObjectCommand.body and StreamingBlobPayloadInputTypes accept any type

### Expected Behavior

PutObjectCommand.body and StreamingBlobPayloadInputTypes should only accept types that will work at runtime

**Comment by kuhe** [comment]
We could put a token method on ReadableStream stub to prevent matching. The token method should be something stable that exists on the actual ReadableStream interface.

Perhaps:
```ts
interface ReadableStream {
  readonly locked: boolean;
}
```

**Comment by everett1992** [comment]
Are there features TypeScript could add? Something like `ifdef ReadableStream ?? never`
