### ISSUE TITLE
Examples requiring `BLOB` data types should be generated with a concrete example using TextEncoder or Buffer

### ISSUE THREAD

**Issue by RanVaknin** [aws/aws-sdk-js-v3#5240]
### Describe the issue

Currently in our documentation data types defined as "BLOB" are generated as a Uint8Array. Since in v2 most encoding was done implicitly by the SDK, and in v3 we avoid customizations and more closely follow the API models, this can create some confusions for our customers. 
Since this is a question that keeps coming up, I think we should have some concrete examples on how to satisfy the Uint8Array interface. 

### Proposal (example with `Firehose#PutRecordCommand`):

**current:**
```js
const input = { // PutRecordInput
  DeliveryStreamName: "STRING_VALUE", // required
  Record: { // Record
    Data: "BLOB_VALUE", // required
  },
};
```

**proposed:**
```js
const input = { // PutRecordInput
  DeliveryStreamName: "STRING_VALUE", // required
  Record: { // Record
    Data: "BLOB_VALUE", // required, use TextEncoder in browser or Buffer in Node.js environment
  },
};
```

**or more verbose:**
```js
const input = { // PutRecordInput
  DeliveryStreamName: "STRING_VALUE", // required
  Record: { // Record
    Data: "BLOB_VALUE", // required
    // Data: new TextEncoder().encode("STRING_VALUE")  <- Browser
    // Data: Buffer.from("STRING_VALUE", "base64") <- Node.js
  },
};
```

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/firehose/command/PutRecordCommand/

**Comment by trivikr** [comment]
Alternative suggested:

```js
const input = { // PutRecordInput
  DeliveryStreamName: "STRING_VALUE", // required
  Record: { // Record
    Data: new Uint8Array(), // required, you can use TextEncoder in browser or Buffer in Node.js environment
  },
};
```

**Comment by shrkbait-hpe** [comment]
```
    // Data: Buffer.from("STRING_VALUE", "base64") <- Node.js
```
is a bit deceiving for folks coming from SDK 2 still.  STRING_VALUE is a base64 string with the Buffer call.  If you are doing the fairly common stringify + newline you need `utf8` or blank default.  https://nodejs.org/docs/latest-v20.x/api/buffer.html#static-method-bufferfromstring-encoding
```
    Data: Buffer.from(JSON.stringify(firehoseRecord) + '\n')
    // a.k.a. Data: Buffer.from(JSON.stringify(firehoseRecord) + '\n', 'utf8')
```

**Comment by kuhe** [comment]
merged in https://github.com/aws/aws-sdk-js-v3/pull/5864
