### ISSUE TITLE
Unable to use @aws-sdk/client-s3 on React Native

### ISSUE THREAD

**Issue by dpyeates** [aws/aws-sdk-js-v3#5246]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

This has previously been raised as #4631 but this was closed without being resolved.

Currently it is not possible to use @aws-sdk/client-s3 on React Native as the following run-time error is reported:

/node_modules/@smithy/util-stream/dist-cjs/getAwsChunkedEncodingStream.js: stream could not be found

### SDK version number

 "@aws-sdk/client-s3": "^3.414.0",

### Which JavaScript Runtime is this issue in?

React Native

### Details of the browser/Node.js/ReactNative version

 "react-native": "^0.72.4",

### Reproduction Steps

Install and run the app. You will get a red screen.

![Screenshot 2023-09-22 at 12 09 07](https://github.com/aws/aws-sdk-js-v3/assets/944670/1fa94282-ddf2-4e10-a81b-5273875a0208)

### Observed Behavior

See image above

### Expected Behavior

No error

**Comment by dpyeates** [comment]
@RanVaknin

**Comment by cpyle0819** [comment]
Confirmed as still present on `3.417.0`
![Screenshot 2023-09-22 at 10 49 03 AM](https://github.com/aws/aws-sdk-js-v3/assets/2723491/c403feb1-29bb-40ec-bbb0-f6fccaaf7448)

**Comment by JunedBrilworks** [comment]
Facing same issue

**Comment by RanVaknin** [comment]
Hi everyone,

Thanks for the information. Will assign high priority to this for further investigation.

Ran

**Comment by kuhe** [comment]
Please try the bundler configuration explained here: https://github.com/aws/aws-sdk-js-v3/issues/4877#issuecomment-1656007484

**Comment by dpyeates** [comment]
Adding

```
// metro.config.js
module.exports = {
  resolver: {
    resolverMainFields: ['react-native', 'module', 'browser', 'main'],
  }
}
```

Does not resolve the problem for me.

**Comment by dpyeates** [comment]
OK, I have manages to get my app working and resolve the above issue.

I had to edit two package files:

1)  @smithy/util-stream/package.json
2) @aws-sdk/middleware-flexible-checksums/package.json

In each I changed 

"main": "./dist-cjs/index.js"

to

"main": "./dist-es/index.js",

Here are the two patch files that I created after making the changes above.


@smithy+util-stream+2.0.14.patch:

```
diff --git a/node_modules/@smithy/util-stream/package.json b/node_modules/@smithy/util-stream/package.json
index cad3d45..8f566e4 100644
--- a/node_modules/@smithy/util-stream/package.json
+++ b/node_modules/@smithy/util-stream/package.json
@@ -15,7 +15,7 @@
     "test": "yarn g:jest && karma start karma.conf.js",
     "test:integration": "yarn g:jest --config jest.config.integ.js"
   },
-  "main": "./dist-cjs/index.js",
+  "main": "./dist-es/index.js",
   "module": "./dist-es/index.js",
   "types": "./dist-types/index.d.ts",
   "author": {
```

@aws-sdk+middleware-flexible-checksums+3.425.0.patch:

```
diff --git a/node_modules/@aws-sdk/middleware-flexible-checksums/package.json b/node_modules/@aws-sdk/middleware-flexible-checksums/package.json
index 618241c..3e0c17b 100644
--- a/node_modules/@aws-sdk/middleware-flexible-checksums/package.json
+++ b/node_modules/@aws-sdk/middleware-flexible-checksums/package.json
@@ -12,7 +12,7 @@
     "test": "jest --coverage",
     "test:integration": "jest -c jest.config.integ.js"
   },
-  "main": "./dist-cjs/index.js",
+  "main": "./dist-es/index.js",
   "module": "./dist-es/index.js",
   "browser": {
     "./dist-es/streams/create-read-stream-on-buffer": "./dist-es/streams/create-read-stream-on-buffer.browser"
```

**Comment by PrintNifesimi** [comment]
changed 
```
"main": "./dist-cjs/index.js"
to
"main": "./dist-es/index.js",
```

In both files, but issue still persists with "node_modules/@smithy/shared-ini-file-loader/dist-es/getSSOTokenFromFile.js"

**Comment by enisze** [comment]
> OK, I have manages to get my app working and resolve the above issue.
> 
> I had to edit two package files:
> 
> 1. @smithy/util-stream/package.json
> 2. @aws-sdk/middleware-flexible-checksums/package.json
> 
> In each I changed
> 
> "main": "./dist-cjs/index.js"
> 
> to
> 
> "main": "./dist-es/index.js",
> 
> Here are the two patch files that I created after making the changes above.
> 
> @smithy+util-stream+2.0.14.patch:
> 
> ```
> diff --git a/node_modules/@smithy/util-stream/package.json b/node_modules/@smithy/util-stream/package.json
> index cad3d45..8f566e4 100644
> --- a/node_modules/@smithy/util-stream/package.json
> +++ b/node_modules/@smithy/util-stream/package.json
> @@ -15,7 +15,7 @@
>      "test": "yarn g:jest && karma start karma.conf.js",
>      "test:integration": "yarn g:jest --config jest.config.integ.js"
>    },
> -  "main": "./dist-cjs/index.js",
> +  "main": "./dist-es/index.js",
>    "module": "./dist-es/index.js",
>    "types": "./dist-types/index.d.ts",
>    "author": {
> ```
> 
> @aws-sdk+middleware-flexible-checksums+3.425.0.patch:
> 
> ```
> diff --git a/node_modules/@aws-sdk/middleware-flexible-checksums/package.json b/node_modules/@aws-sdk/middleware-flexible-checksums/package.json
> index 618241c..3e0c17b 100644
> --- a/node_modules/@aws-sdk/middleware-flexible-checksums/package.json
> +++ b/node_modules/@aws-sdk/middleware-flexible-checksums/package.json
> @@ -12,7 +12,7 @@
>      "test": "jest --coverage",
>      "test:integration": "jest -c jest.config.integ.js"
>    },
> -  "main": "./dist-cjs/index.js",
> +  "main": "./dist-es/index.js",
>    "module": "./dist-es/index.js",
>    "browser": {
>      "./dist-es/streams/create-read-stream-on-buffer": "./dist-es/streams/create-read-stream-on-buffer.browser"
> ```

When i do this I still get the error for crypto :
<img width="795" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/15271433/aaf905b5-e8a4-4d6b-abc2-88b3d129d5e1">

**Comment by enisze** [comment]
check this [thread](https://github.com/aws/aws-sdk-js-v3/issues/4877) , it helped me to resolve the issue on android.

**Comment by JeanBaptisteBolh** [comment]
I am encountering this problem too.  Tried many different versions of the package.  Will try enisze's solution tomorrow.

**Comment by RanVaknin** [comment]
There are numerous of suggestions on the thread, are folks still not able to solve this issue? If so please comment here / create a separate issue and provide complete repro code including the steps you've taken already.  That will enable us to help you on a case-by-case basis.

Thanks,
Ran~
