### ISSUE TITLE
SimpleDB is not included

### ISSUE THREAD

**Issue by vladaman** [aws/aws-sdk-js-v3#5247]
### Describe the feature

We still use SimpleDB on legacy projects very extensively. I also don't see this being deprecated. Is SimpleDB API included?

### Use Case

Legacy project still depending on SimpleDB

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3

### Environment details (OS name and version, etc.)

AWS Lambda

**Comment by RanVaknin** [comment]
Hi @vladaman ,

SimpleDB is explicitly excluded from newer versions of the AWS SDK and there is no plan to re-add it. It's effectively end of support. DynamoDB offers better performance, availability, and scalability and is the recommended solution. 

If you want to keep using it programmatically, you can use either JS SDK v2 which still supports it (but will be deprecated at some point) or interact with the API directly. 

Thanks for taking the time and raising this request.
All the best,
Ran~
