### ISSUE TITLE
Typescript error with `SecretsManagerClient.send` from `@aws-sdk/client-secrets-manager@3.413.0`

### ISSUE THREAD

**Issue by vietanhtran16** [aws/aws-sdk-js-v3#5252]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When we upgrade from `@aws-sdk/client-secrets-manager@3.410.0` to `@aws-sdk/client-secrets-manager@3.413.0`, we started getting typescript error when using `SecretsManagerClient.send`

Here is our usage and we are getting error when passing the command into `.send`
```
import {
  GetSecretValueCommand,
  SecretsManagerClient,
} from "@aws-sdk/client-secrets-manager"

const client = new SecretsManagerClient({})
const secret = await client.send(
  new GetSecretValueCommand({ SecretId: secretName })
)
```
![image](https://github.com/aws/aws-sdk-js-v3/assets/23372284/4a5e027e-b1b3-40ab-be73-aeadc7693bb2)

Here is the full error messsage
```
Argument of type 'GetSecretValueCommand' is not assignable to parameter of type 'Command<ServiceInputTypes, GetSecretValueCommandInput, ServiceOutputTypes, GetSecretValueCommandOutput, SmithyResolvedConfiguration<...>>'.
  Types of property 'resolveMiddleware' are incompatible.
    Type '(clientStack: MiddlewareStack<ServiceInputTypes, ServiceOutputTypes>, configuration: SecretsManagerClientResolvedConfig, options?: HttpHandlerOptions | undefined) => Handler<...>' is not assignable to type '(stack: MiddlewareStack<ServiceInputTypes, ServiceOutputTypes>, configuration: SmithyResolvedConfiguration<HttpHandlerOptions>, options: any) => Handler<...>'.
      Types of parameters 'clientStack' and 'stack' are incompatible.
        Type 'import("/Users/reproduction/node_modules/@aws-sdk/client-secrets-manager/node_modules/@smithy/middleware-endpoint/node_modules/@smithy/types/dist-types/middleware").MiddlewareStack<import("/Users/reproduction/node_modules/@aws-sdk/client-secrets-manager/dist-...' is not assignable to type 'import("/Users/reproduction/node_modules/@smithy/types/dist-types/middleware").MiddlewareStack<import("/Users/reproduction/node_modules/@aws-sdk/client-secrets-manager/dist-types/SecretsManagerClient").ServiceInputTypes, import("/Users/viet.anhtran/Projects/u...'.
          Types of property 'concat' are incompatible.
            Type '<InputType extends import("/Users/reproduction/node_modules/@aws-sdk/client-secrets-manager/dist-types/SecretsManagerClient").ServiceInputTypes, OutputType extends import("/Users/reproduction/node_modules/@aws-sdk/client-secrets-manager/dist-types/SecretsMana...' is not assignable to type '<InputType extends import("/Users/reproduction/node_modules/@aws-sdk/client-secrets-manager/dist-types/SecretsManagerClient").ServiceInputTypes, OutputType extends import("/Users/reproduction/node_modules/@aws-sdk/client-secrets-manager/dist-types/SecretsMana...'. Two different types with this name exist, but they are unrelated.
              Types of parameters 'from' and 'from' are incompatible.
                Property 'identifyOnResolve' is missing in type 'MiddlewareStack<InputType, OutputType>' but required in type 'MiddlewareStack<InputType, ServiceOutputTypes>'.ts(2345)
middleware.d.ts(422, 5): 'identifyOnResolve' is declared here.
```

We looked at the [documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/secrets-manager/command/GetSecretValueCommand/) and we are using it correctly

### SDK version number

@aws-sdk/client-secrets-manager@3.413.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.16.0

### Reproduction Steps

You should be able to to replicate with a repo in typescript with `@aws-sdk/client-secrets-manager@3.413.0` (or higher) to see the error

### Observed Behavior

```
Argument of type 'GetSecretValueCommand' is not assignable to parameter of type 'Command<ServiceInputTypes, GetSecretValueCommandInput, ServiceOutputTypes, GetSecretValueCommandOutput, SmithyResolvedConfiguration<...>>'.
  Types of property 'resolveMiddleware' are incompatible.
    Type '(clientStack: MiddlewareStack<ServiceInputTypes, ServiceOutputTypes>, configuration: SecretsManagerClientResolvedConfig, options?: HttpHandlerOptions | undefined) => Handler<...>' is not assignable to type '(stack: MiddlewareStack<ServiceInputTypes, ServiceOutputTypes>, configuration: SmithyResolvedConfiguration<HttpHandlerOptions>, options: any) => Handler<...>'.
      Types of parameters 'clientStack' and 'stack' are incompatible.
        Type 'import("/Users/reproduction/node_modules/@aws-sdk/client-secrets-manager/node_modules/@smithy/middleware-endpoint/node_modules/@smithy/types/dist-types/middleware").MiddlewareStack<import("/Users/reproduction/node_modules/@aws-sdk/client-secrets-manager/dist-...' is not assignable to type 'import("/Users/reproduction/node_modules/@smithy/types/dist-types/middleware").MiddlewareStack<import("/Users/reproduction/node_modules/@aws-sdk/client-secrets-manager/dist-types/SecretsManagerClient").ServiceInputTypes, import("/Users/viet.anhtran/Projects/u...'.
          Types of property 'concat' are incompatible.
            Type '<InputType extends import("/Users/reproduction/node_modules/@aws-sdk/client-secrets-manager/dist-types/SecretsManagerClient").ServiceInputTypes, OutputType extends import("/Users/reproduction/node_modules/@aws-sdk/client-secrets-manager/dist-types/SecretsMana...' is not assignable to type '<InputType extends import("/Users/reproduction/node_modules/@aws-sdk/client-secrets-manager/dist-types/SecretsManagerClient").ServiceInputTypes, OutputType extends import("/Users/reproduction/node_modules/@aws-sdk/client-secrets-manager/dist-types/SecretsMana...'. Two different types with this name exist, but they are unrelated.
              Types of parameters 'from' and 'from' are incompatible.
                Property 'identifyOnResolve' is missing in type 'MiddlewareStack<InputType, OutputType>' but required in type 'MiddlewareStack<InputType, ServiceOutputTypes>'.ts(2345)
middleware.d.ts(422, 5): 'identifyOnResolve' is declared here.
```

### Expected Behavior

We shouldn't get the error

**Comment by RanVaknin** [comment]
Hi @vietanhtran16 ,

I'm not sure why you are seeing this I'm not able to reproduce this behavior.
Perhaps your application has multiple copies of the SDK as nested dependencies with different versions. 

You can try deleting your `node_modules` and `package-lock.json`, and then running `npm install` and let npm figure out the correct versioning?

**Comment by vietanhtran16** [comment]
Hey @RanVaknin, I check with `yarn why` and our project only have a single version which is `3.143.0`
![image](https://github.com/aws/aws-sdk-js-v3/assets/23372284/bfeb79a5-4c20-47d7-a523-efa9d893d97f)

I deleted `node_modules` and ran `yarn --frozen-lockfile` again but still seeing the same error. I can reproduce it consistently. It happens with `3.144.0` too

**Comment by RanVaknin** [comment]
Hi @vietanhtran16 ,

Im confused, the version output shows 3.413, but you are mentioning 3.143 and 3.144 which are very old versions. 

What version of Typescript are you using? 

Not sure if this is helpful, but this is my setup:

```js
import {
    GetSecretValueCommand,
    SecretsManagerClient,
  } from "@aws-sdk/client-secrets-manager"
  

  const secretId = "my-secret-REDACTED"
  const client = new SecretsManagerClient({region: "us-east-1"})

  async function run(){
    try {
      const response = await client.send(
        new GetSecretValueCommand({ SecretId: secretId })
      )
      console.log(response)
    } catch (error) {
      console.log(error)

    }
  }

run()
```

```console
$ tsc sample.ts
$ node sample.js

{
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'REDACTED',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  ARN: 'arn:aws:secretsmanager:us-east-1:REDACTED:secret:my-secret-REDACTED-REDACTED',
  CreatedDate: 2022-06-02T22:14:54.561Z,
  Name: 'my-secret-3425',
  SecretString: 'REDACTED',
  VersionId: 'REDACTED',
  VersionStages: [ 'AWSCURRENT' ]
}
```

```console
$ npm list
5252@1.0.0 /Users/rvaknin/test_folder/5252
├── @aws-sdk/client-secrets-manager@3.418.0

$ tsc -v
Version 5.0.4
```

If this doesn't help, can you please create a sample github repo that we can clone and test? 

Thanks,
Ran~

**Comment by vietanhtran16** [comment]
> Hi @vietanhtran16 ,
> 
> Im confused, the version output shows 3.413, but you are mentioning 3.143 and 3.144 which are very old versions.
> 
> What version of Typescript are you using?
> 
> Not sure if this is helpful, but this is my setup:
> 
> ```js
> import {
>     GetSecretValueCommand,
>     SecretsManagerClient,
>   } from "@aws-sdk/client-secrets-manager"
>   
> 
>   const secretId = "my-secret-REDACTED"
>   const client = new SecretsManagerClient({region: "us-east-1"})
> 
>   async function run(){
>     try {
>       const response = await client.send(
>         new GetSecretValueCommand({ SecretId: secretId })
>       )
>       console.log(response)
>     } catch (error) {
>       console.log(error)
> 
>     }
>   }
> 
> run()
> ```
> 
> ```
> $ tsc sample.ts
> $ node sample.js
> 
> {
>   '$metadata': {
>     httpStatusCode: 200,
>     requestId: 'REDACTED',
>     extendedRequestId: undefined,
>     cfId: undefined,
>     attempts: 1,
>     totalRetryDelay: 0
>   },
>   ARN: 'arn:aws:secretsmanager:us-east-1:REDACTED:secret:my-secret-REDACTED-REDACTED',
>   CreatedDate: 2022-06-02T22:14:54.561Z,
>   Name: 'my-secret-3425',
>   SecretString: 'REDACTED',
>   VersionId: 'REDACTED',
>   VersionStages: [ 'AWSCURRENT' ]
> }
> ```
> 
> ```
> $ npm list
> 5252@1.0.0 /Users/rvaknin/test_folder/5252
> ├── @aws-sdk/client-secrets-manager@3.418.0
> 
> $ tsc -v
> Version 5.0.4
> ```
> 
> If this doesn't help, can you please create a sample github repo that we can clone and test?
> 
> Thanks, Ran~

ah sorry I meant I had `3.413.0` and `3.414.0` has the same issues.

Let me check to see if I can create a sample github repo

**Comment by vietanhtran16** [comment]
```
Type 'import("/Users/reproduction/node_modules/@aws-sdk/client-secrets-manager/node_modules/@smithy/middleware-endpoint/node_modules/@smithy/types/dist-types/middleware").MiddlewareStack<import("/Users/reproduction/node_modules/@aws-sdk/client-secrets-manager/dist-...' is not assignable to type 'import("/Users/reproduction/node_modules/@smithy/types/dist-types/middleware").MiddlewareStack<import("/Users/reproduction/node_modules/@aws-sdk/client-secrets-manager/dist-types/SecretsManagerClient").ServiceInputTypes, import("/Users/viet.anhtran/Projects/u...'.
```

I had a closer look at the error message and this one stood out to me.

So this was likely to be caused by one of the packages from `@smithy` probably `@smithy/types`. Our repo is a monorepo so there was multiple version of `@smithy/types` and that caused types mismatch.

Once I deduped dependencies, the errors is now gone so not an issues with `@aws-sdk/client-secrets-manager`

Thanks for your prompt response though
