### ISSUE TITLE
ec2 RunInstances assigning iamInstanceProfile name or arn => InvalidParameterValue

### ISSUE THREAD

**Issue by gurfink** [aws/aws-sdk-js-v3#5253]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When associating an instance profile name or arn on the execution of the RunInstances command after having just created the instance profile prior to executing I receive the following;

`
{    
 "errorType": "InvalidParameterValue",     "errorMessage": "Value (somvalue) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name",     "name": "InvalidParameterValue",     "$fault": "client",     "$metadata": {         "httpStatusCode": 400,         "requestId": "392875ac-536f-4a4c-b1e3-d0660e41b5e5",         "attempts": 1,         "totalRetryDelay": 0     }.....
`

The instance profile name is correct as is arn I attempt to pass in. Funny thing is if I hard-code the value of the instance profile name/arn on the next run that it complains about, no issue. 

I require to create instance profile on the fly so "hard coding" is not valid for my use case. I've attempted pausing, and even calling GetInstanceProfileCommand after creating and using the name/arn returned from that to pass in and same problem.

### SDK version number

@aws-sdk/package-name@version, ...

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

18.x

### Reproduction Steps

1. Create Instance Profile with SDK
2. Immediately follow that with RunInstancesCommand using instance profile name/arn in IamInstanceProfile
3. Errors with invalid name/arn.

### Observed Behavior

2023-09-25T02:34:16.373Z	e35f39be-e1be-4d6e-bbca-ce2f8834d6f8	ERROR	Invoke Error 	
{
    "errorType": "InvalidParameterValue",
    "errorMessage": "Value (gurfinkmac2_instance_1695609254052) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name",
    "name": "InvalidParameterValue",
    "$fault": "client",
    "$metadata": {
        "httpStatusCode": 400,
        "requestId": "392875ac-536f-4a4c-b1e3-d0660e41b5e5",
        "attempts": 1,
        "totalRetryDelay": 0
    },
    "Code": "InvalidParameterValue",
    "message": "Value (gurfinkmac2_instance_1695609254052) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name",
    "stack": [
        "InvalidParameterValue: Value (gurfinkmac2_instance_1695609254052) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name",
        "    at throwDefaultError (/var/runtime/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)",
        "    at deserializeAws_ec2RunInstancesCommandError (/var/runtime/node_modules/@aws-sdk/client-ec2/dist-cjs/protocols/Aws_ec2.js:21579:43)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
        "    at async /var/runtime/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24",
        "    at async /var/runtime/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:13:20",
        "    at async StandardRetryStrategy.retry (/var/runtime/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)",
        "    at async /var/runtime/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22",
        "    at async Runtime.handler (/var/task/index.js:186:25)"
    ]
}

### Expected Behavior

Instance to be started with instance profile role passed in attached.

**Comment by RanVaknin** [comment]
Hi @gurfink ,

What you are describing is [eventual consistency ](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html#eventual-consistency). Even if you are creating a profile, and from an IAM standpoint it has been created, the EC2 service might not "know" that it has been created since there is a propagation delay between the services. 

A possible mitigation strategy is to use a retry strategy with exponential backoff. Something like this:

```js
async function runInstancesWithRetry(instanceProfileName, maxRetries = 3, delay = 5000) {
  let attempts = 0;
  
  while (attempts < maxRetries) {
    try {

      const runInstancesCommand = new RunInstancesCommand({
        IamInstanceProfile: {
          Name: instanceProfileName
        },
      });
      await ec2Client.send(runInstancesCommand);
      
      console.log("success!");
      return;
    } catch (error) {
      if (error.name === "InvalidParameterValue") {
        attempts++;
        await new Promise(resolve => setTimeout(resolve, delay));
      } else {
        console.log(error);
        return;
      }
    }
  }
```

Unfortunately this behavior is not unique to the SDK and also not actionable by the SDK team. Its more about the distributed nature a microservice architecture.

If you have any additional questions, please let me know and I can do my best to help.
Ran~

**Comment by gurfink** [comment]
Thanks, will look into your advice of exponential back off and hope it will work appropriately for my use case.
