### ISSUE TITLE
Kinesis PutRecordCommand using StreamARN property only results in InvalidArgumentException

### ISSUE THREAD

**Issue by astrocreep** [aws/aws-sdk-js-v3#5254]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I'm trying to put some data in an existing Kinesis stream in my Lambda. The ARN is correct.

This fails:
```typescript
...
const data: PutRecordCommandInput = {
          Data: Buffer.from(JSON.stringify(record)),
          PartitionKey: partitionKey,
          StreamARN: arn,
        }
...
await client.send(new PutRecordCommand(data))
```

This works:
```typescript
...
const data: PutRecordCommandInput = {
          Data: Buffer.from(JSON.stringify(record)),
          PartitionKey: partitionKey,
          StreamName: arn.split('/')[1],
        }
...
await client.send(new PutRecordCommand(data))
```

### SDK version number

@aws-sdk/client-kinesis@3.418.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node18 in lambda function

### Reproduction Steps

Try to send a PutRecordCommand and set only the StreamARN property.

### Observed Behavior

Using only the StreamARN as source throws an InvalidArgumentException:
```
InvalidArgumentException: Stream arn and stream name can't be empty at the same time
    at deserializeAws_json1_1InvalidArgumentExceptionResponse (/var/runtime/node_modules/@aws-sdk/client-kinesis/dist-cjs/protocols/Aws_json1_1.js:1562:23)
    at deserializeAws_json1_1PutRecordCommandError (/var/runtime/node_modules/@aws-sdk/client-kinesis/dist-cjs/protocols/Aws_json1_1.js:1097:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/runtime/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /var/runtime/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:13:20
    at async StandardRetryStrategy.retry (/var/runtime/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /var/runtime/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at async Promise.all (index 0)
    at Runtime.nt (/lambda/system/deletedItemLogHandler.ts:55:5) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: '...',
    extendedRequestId: '...',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  __type: 'InvalidArgumentException'
}
```

### Expected Behavior

Should work if a correct stream ARN is provided

**Comment by farski** [comment]
I'm seeing this same behavior, and using a `Streamname` is not a good option for me because I'm trying to write to a Kinesis stream in another account.

**Comment by RanVaknin** [comment]
Hi @farski and @farski ,

You mentioned you are running this from Lambda. Are you sure you are using version `3.418.0` like you mentioned? Lambda does not embed the latest [version of the SDK by default](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html).  Currently Lambda embeds version `3.188.0`. 

By checking out that SDK version I can see that the error you are running into: `InvalidArgumentException: Stream arn and stream name can't be empty at the same time`.
Once I upgraded to the latest version of the SDK both Arn and Name are accepted. This is probably due to this Kinesis feature being released after version 3.188.0 so there was no SDK support back at that time. 

If you want to run the most up to date version of the SDK from lambda, you need to either [bundle your SDK](https://aws.amazon.com/blogs/compute/optimizing-node-js-dependencies-in-aws-lambda/) or upload it as a lambda layer.

Thanks,
Ran

**Comment by farski** [comment]
Thanks for doing that debugging @RanVaknin. I'll give that a shot. If that is the solution, it must be a bug in that particular version, not really a new feature, because this has been supported in the Javascript SDK for a long time, including in the v2 SDK.

**Comment by farski** [comment]
I switched the Lambda function back to `nodejs-16.x` to use the v2 SDK, and it worked as expected, so this does seem like a bug with the v3 SDK version that ships with Nobe.js 18 Lambda functions.

**Comment by RanVaknin** [comment]
Hi @farski ,

Support for StreamArn [was added November 2022](https://github.com/aws/aws-sdk-go-v2/commit/7cd0d9d9b4d7dd972da4aaf8983d6aca8d3f5874), but 3.188.0 [was released October 2022](https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.188.0), 2 months before this feature was implemented.

Since the SDK is code generated from the API model of the service, if the model didnt have that data at the time, the SDK was not generated with support for a feature that didnt exist. 

Example:

```console
$ npm ls
5010@1.0.0 /Users/rvaknin/test_folder/5010
├── @aws-sdk/client-kinesis@3.188.0

$ node producer.js
before sign:  HttpRequest {
  method: 'POST',
  hostname: 'kinesis.us-east-1.amazonaws.com',
  port: undefined,
  query: {},
  headers: {
    'content-type': 'application/x-amz-json-1.1',
    'x-amz-target': 'Kinesis_20131202.PutRecords',
    'content-length': '76'
  },
  body: '{"Records":[{"Data":"eyJrZXkiOiJ2YWx1ZSJ9","PartitionKey":"partitionKey1"}]}',
  protocol: 'https:',
  path: '/'
}
InvalidArgumentException: Stream arn and stream name can't be empty at the same time
    at deserializeAws_json1_1InvalidArgumentExceptionResponse (/Users/rvaknin/test_folder/5010/node_modules/@aws-sdk/client-kinesis/dist-cjs/protocols/Aws_json1_1.js:1562:23)
    at deserializeAws_json1_1PutRecordsCommandError (/Users/rvaknin/test_folder/5010/node_modules/@aws-sdk/client-kinesis/dist-cjs/protocols/Aws_json1_1.js:1155:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/rvaknin/test_folder/5010/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /Users/rvaknin/test_folder/5010/node_modules/@aws-sdk/client-kinesis/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:13:20
    at async StandardRetryStrategy.retry (/Users/rvaknin/test_folder/5010/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /Users/rvaknin/test_folder/5010/node_modules/@aws-sdk/client-kinesis/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at async run (/Users/rvaknin/test_folder/5010/producer.js:55:21) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: 'REDACTED',
    extendedRequestId: 'REDACTED',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  __type: 'InvalidArgumentException'
}

$ npm i @aws-sdk/client-kinesis
$ npm ls
5010@1.0.0 /Users/rvaknin/test_folder/5010
├── @aws-sdk/client-kinesis@3.421.0

$ node producer.js             
before sign:  HttpRequest {
  method: 'POST',
  hostname: 'REDACTED_ACCOUNT_ID.data-kinesis.us-east-1.amazonaws.com',
  port: undefined,
  query: {},
  headers: {
    'content-type': 'application/x-amz-json-1.1',
    'x-amz-target': 'Kinesis_20131202.PutRecords',
    'content-length': '147'
  },
  body: '{"Records":[{"Data":"eyJrZXkiOiJ2YWx1ZSJ9","PartitionKey":"partitionKey1"}],"StreamARN":"arn:aws:kinesis:us-east-1:REDACTED_ACCOUNT_ID:stream/foo-stream"}',
  protocol: 'https:',
  path: '/',
  username: undefined,
  password: undefined,
  fragment: undefined
}
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'REDACTED',
    extendedRequestId: 'REDACTED',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  FailedRecordCount: 0,
  Records: [
    {
      SequenceNumber: 'REDACTED',
      ShardId: 'shardId-000000000005'
    }
  ]
}
```

The solution here is to update the SDK version, not to downgrade the node version.
Thanks,
Ran~
