### ISSUE TITLE
Implement Virtual Hosted Style URLs for S3 Presigned Posts

### ISSUE THREAD

**Issue by RanVaknin** [aws/aws-sdk-js-v3#5257]
### Describe the feature

The new standard for constructing bucket URLs is the Virtual Hosted Style URL. 

Currently generating an S3 presigned post only supports path style URLs that are the old standard. (by default S3 will not even construct path style URLs). 

Proposed solution:
Add logic to the generator: https://github.com/aws/aws-sdk-js-v3/blob/3adb1bacd7e3fc10b3cf0310a015423108b66d76/packages/s3-presigned-post/src/createPresignedPost.ts#L41 to support both path style (for legacy customers and s3 clones that still use it like Digital Ocean Spaces) and Virtual Hosted Style. 

### Use Case

Create a presigned post with virtual hosted style. 

### Proposed Solution

https://github.com/aws/aws-sdk-js-v3/pull/1707

### Other Information

original customer request https://github.com/aws/aws-sdk-js-v3/pull/1707

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.418.0

### Environment details (OS name and version, etc.)

Mac OS

**Comment by p0wl** [comment]
Ran into this as well. Especially because AWS SDK v2 used virtual hosted style urls already, I was surprised that the V3 version of `createPresignedPost` comes with the path style url...

**Comment by RanVaknin** [comment]
This seems to be supported:

```js
import { S3Client } from "@aws-sdk/client-s3";
import { createPresignedPost } from "@aws-sdk/s3-presigned-post";
import fs from "fs";
import FormData from "form-data";

const Conditions = [];

const Bucket = "testbucket";
const Key = "foo10.txt";

const Fields = {};

try {
  const client = new S3Client({ region: "us-east-1", forcePathStyle: false });
  const url = await createPresignedPost(client, {
    Bucket,
    Key,
    Conditions,
    Fields,
    Expires: 600,
  });

  console.log(url);

  const formVirtualHosted = new FormData();
  Object.entries(url.fields).forEach(([field, value]) => {
    formVirtualHosted.append(field, value);
  });
  formVirtualHosted.append("file", fs.createReadStream("./foo10.txt"));

  formVirtualHosted.submit(url.url, (err, res) => {
    if (err) {
      console.error("Error submitting form (Virtual-Hosted):", err);
    } else {
      console.log("Response status code (Virtual-Hosted):", res.statusCode);
    }
  });

} catch (error) {
  console.log("Error:", error);
}
``` 

generates a correct virtual hosted style URL, and also successfully uploads using that URL:

```
{
  url: 'https://testbucket.s3.us-east-1.amazonaws.com/',
  fields: {
    bucket: 'testbucket',
    'X-Amz-Algorithm': 'AWS4-HMAC-SHA256',
    'X-Amz-Credential': 'REDACTED/20240715/us-east-1/s3/aws4_request',
    'X-Amz-Date': '20240715T034108Z',
    key: 'foo10.txt',
    Policy: 'REDACTED',
    'X-Amz-Signature': 'REDACTED'
  }
}
Response status code (Virtual-Hosted): 204
```
