### ISSUE TITLE
The "summary" column looks too complete

### ISSUE THREAD

**Issue by KernelDeimos** [aws/aws-sdk-js-v3#5258]
### Describe the issue

It took me a hot minute to figure out that the information in the `summary` column wasn't in fact the complete API documentation for each command. It really doesn't look like a summary at all; it has most of the documentation, but it doesn't document the return object. A simple "See More..." button would be a fantastic indication that I'm not already seeing all the information.

To highlight a potential danger, I found what I was looking for in the deprecated API documentation before I realized this, which Chat GPT graciously provided me a link to.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/

**Comment by ajredniwja** [comment]
Hi @KernelDeimos thanks for opening this issue, the summary part doesnt document the return object but if you click on a specific command link it will show you the what return object would look like.
