### ISSUE TITLE
Add code examples

### ISSUE THREAD

**Issue by ashley-jisc** [aws/aws-sdk-js-v3#5259]
### Describe the issue

I went to the new docs, as I'm currently having to upgrade v2 to v3, but when going to the lambda page for example, it's not very clear what the new syntax is (if there even is new syntax?). 

I suggest to show basic usage for each service on their respective doc pages.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/client/lambda/

**Comment by ajredniwja** [comment]
Hey @ashley-jisc thanks for opening this issue, the Lambda client has many commands which can be compared to V2 methods for that client. 
If you click on any specific command it will show you how to use it for example here: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/client/lambda/command/CreateFunctionCommand/

You can also find a complete Lambda example here: https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/lambda-examples.html

Please let us know if that doesnt help thanks

**Comment by ashley-jisc** [comment]
Thanks, that helps.

I feel that [adding these accordion sections](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/javascript_lambda_code_examples.html) to the top level of the page would be a welcome addition. 

It's clear, simple and concise. 

Most developers when looking up docs are just looking for basic usage, and then tend to go deeper into the documentation of something specific as of when it's needed.

**Comment by aBurmeseDev** [comment]
Hi @ashley-jisc - I'm glad to see that your question was answered. Since your concern has been addressed, I'll go ahead and close this issue for now. However, please don't hesitate to open a new one if you have any other questions or need further assistance with the SDK. We're always happy to help!
