### ISSUE TITLE
client config object documentation

### ISSUE THREAD

**Issue by darking09** [aws/aws-sdk-js-v3#5260]
### Describe the issue

At any place talks about the config object, or how it should be setup

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/client/comprehend/command/BatchDetectSentimentCommand/

**Comment by ajredniwja** [comment]
hi @darking09 thanks for opening this issue, the JS SDK doesnt have a global configuration object, you would need to pass the config to service client that you instantiate. 
The config object may have information like: region, credentials etc.
You can find that information at any clients page if you look at the configuration section on the bottom. 
For example https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/accessanalyzer/ this link would have what you can add in the configuration object. 

Then you can pass it to your service client constructor with something like this: 

```js
const config = {
  region: "us-west-2", 
  credentials: {
      accessKeyId: "YOUR_ACCESS_KEY_ID",     
      secretAccessKey: "YOUR_SECRET_ACCESS_KEY"
  }
};

const s3 = new S3Client(config);
```

Let us know if that doesnt help, thanks

**Comment by kuhe** [comment]
Now, whenever you are within a client's type documentation, there is a link from the navigation guide back to the client landing page:

example:
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-comprehend/TypeAlias/ComprehendClientConfigType/

Each client landing page, at the bottom, has a description of the config for the client.
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/comprehend/
