### ISSUE TITLE
namespaced shapes 404 in api documentation

### ISSUE THREAD

**Issue by ivoneijr** [aws/aws-sdk-js-v3#5264]
### Describe the issue

```json
{"name":"ResponseStream.PayloadPartMember","pkg":"@aws-sdk/client-sagemaker-runtime","type":"Interface","text":"PayloadPartMember"}
```

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-sagemaker-runtime/TypeAlias/ResponseStream/

**Comment by ajredniwja** [comment]
Hi @ivoneijr thanks for opening this issue, will mark this with a higher priority for team to look at it.

**Comment by Swolebrain** [comment]
Affecting the verified permissions SDK too 

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-verifiedpermissions/TypeAlias/PolicyDefinition/

```json
{"name":"PolicyDefinition.TemplateLinkedMember","pkg":"@aws-sdk/client-verifiedpermissions","type":"Interface","text":"TemplateLinkedMember"}
{"name":"PolicyDefinition.StaticMember","pkg":"@aws-sdk/client-verifiedpermissions","type":"Interface","text":"StaticMember"}
{"name":"PolicyDefinition.StaticMember","pkg":"@aws-sdk/client-verifiedpermissions","type":"Interface","text":"$UnknownMember"}
```

**Comment by kuhe** [comment]
Internal code change has been staged for release, this should be fixed some time after the next SDK release when docs are updated. There can be a few hours delay between SDK releases and docs updates.
