### ISSUE TITLE
Dynamo DB Document Client: Allow Empty Sets

### ISSUE THREAD

**Issue by 0815Hunter** [aws/aws-sdk-js-v3#5266]
### Describe the feature

The Dynamo DB Document Client doesn't allow to persist empty sets, even though it's possible manually in AWS:

![image](https://github.com/aws/aws-sdk-js-v3/assets/26740456/ab41ceaf-fd80-426c-b8b7-f4cb27ded0e8)

### Use Case

To persist an empty set, we have to set the marshall option `convertEmptyValues: true`  which sets every empty string/set/blob to null, else we will get an error.

With this behavior, we have to make a null check before using a string/set/blob from ddb.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3

### Environment details (OS name and version, etc.)

-

**Comment by RanVaknin** [comment]
Hi @0815Hunter ,

Dynamodb Console does not allow to insert empty sets via the console:
<img width="902" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/50976344/678db242-559d-4975-920a-030c197179f9">

I'm not sure I understand the use case of intentionally trying to add empty sets into dynamo?

Thanks,
Ran~

**Comment by RanVaknin** [comment]
Hi, 

After looking at the [Dyanmo service docs](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PutItem.html), the explicitly mention that empty sets are not supported:

>_Empty String and Binary attribute values are allowed. Attribute values of type String and Binary must have a length greater than zero if the attribute is used as a key attribute for a table or index. **Set type attributes cannot be empty.**_

So this feature request is asking for something that doesn't have server side support. Unfortunately we cannot move forward with this request. 

Thanks again for reaching out. 
Ran~
