### ISSUE TITLE
waitUntilTasksRunning throws a TimeoutError instead of returning WaiterResult

### ISSUE THREAD

**Issue by gkorland** [aws/aws-sdk-js-v3#5274]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Using `waitUntilTasksRunning` in `@aws-sdk/client-ec2` throws a TimeoutError instead of returning WaiterResult with state `TIMEOUT`. 

### SDK version number

@aws-sdk/package-name@version, ...

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v17.6.0

### Reproduction Steps

call 
```
let result = await waitUntilTasksRunning(
        { client: ecsClient, maxWaitTime: 2, minDelay: 1},
        { cluster: "mycluster", tasks: [taskArn] }
```
You'll get an exception after 2 secs instead of getting `result.state="TIMEOUT"` 

### Observed Behavior

```
Error [TimeoutError]: {"state":"TIMEOUT","reason":"Waiter has timed out"}
    at checkExceptions (webpack-internal:///(rsc)/./node_modules/@smithy/util-waiter/dist-cjs/waiter.js:27:30)
    at waitUntilTasksRunning (webpack-internal:///(rsc)/./node_modules/@aws-sdk/client-ecs/dist-cjs/waiters/waitForTasksRunning.js:94:46)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async GET (webpack-internal:///(rsc)/./app/api/db/route.tsx:329:9)
    at async eval (webpack-internal:///(rsc)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:254:37)
```

### Expected Behavior

result with state TIMEOUT

**Comment by yenfryherrerafeliz** [comment]
Hi @gkorland, thanks for opening this issue. This behavior is in fact expected. We can confirm this by also checking the implementation [here](https://github.com/awslabs/smithy-typescript/blob/c607f6c2dffbdbf4043a68b9ba98434ec2367d29/packages/util-waiter/src/waiter.ts#L51). If the waiter got a non success result then, an exception will be thrown. This is in fact the behavior for other SDKs, such Java.

I will resolve this issue, but please, if you need anything else that we can help with, feel free in opening a new issue.

Thanks!

**Comment by gkorland** [comment]
If that is the expected result so when will `result.state=="TIMEOUT"`?
