### ISSUE TITLE
npm install error for v3.422.0

### ISSUE THREAD

**Issue by tomleicircle** [aws/aws-sdk-js-v3#5276]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Got error message when running npm install: `npm ERR! 404  '@aws-sdk/credential-provider-http@https://registry.npmjs.org/@aws-sdk/credential-provider-http/-/credential-provider-http-3.422.0.tgz' is not in this registry.`

### SDK version number

@aws-sdk/credential-provider-http

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

18

### Reproduction Steps

npm i @aws-sdk/credential-provider-http@3.422.0

### Observed Behavior

npm ERR! 404  '@aws-sdk/credential-provider-http@https://registry.npmjs.org/@aws-sdk/credential-provider-http/-/credential-provider-http-3.422.0.tgz

### Expected Behavior

No error

### Possible Solution

npm i @aws-sdk/credential-provider-http@3.422.1

**Comment by msrose** [comment]
Seeing the same issue, it appears that @aws-sdk/credential-providers is hard-coded to depend on exactly 3.422.0 of "@aws-sdk/credential-provider-http" (npm view @aws-sdk/credential-providers --json), but npm CLI can't pull this version from the registry, only 3.422.1 can. 

Latest package.json and commit for credential-provider-http shows 3.422.0 https://github.com/aws/aws-sdk-js-v3/blob/main/packages/credential-provider-http/package.json#L3, but npm shows latest version as 3.422.1 - but also list 3.422.0 as a version 🤔 

Even though 3.422.1 exists, this is breaking builds of any dependents because the version number is hard-coded in the package.json of @aws-sdk/credential-providers.

**Comment by martin-vanta** [comment]
Looking at the version history of this package on npm, it definitely looks like something odd happened recently. There is only this and a patch version available and only within the last few hours too. https://www.npmjs.com/package/@aws-sdk/credential-provider-http?activeTab=versions.

**Comment by tomleicircle** [comment]
Looks like this is specific to `@aws-sdk/credential-provider-http`, and other packages such as [@aws-sdk/credential-providers](https://www.npmjs.com/package/@aws-sdk/credential-providers?activeTab=versions) is not affected.

**Comment by Taaqif** [comment]
For anyone wanting a work around until this gets resolved, add this to your package.json as an npm override. 

```json
"overrides": {
  "@aws-sdk/credential-providers": {
   "@aws-sdk/credential-provider-http": "3.422.1"
  }
}
```

**Comment by tomleicircle** [comment]
It seems what's breaking for everyone is @aws-sdk/credential-providers 3.422.0, if the npm owner can just remove the 3.422.0 version from npm, it will fix the issue and all other dependencies should be able install 3.421.0

**Comment by luccasr73** [comment]
same problem here

**Comment by kuhe** [comment]
We encountered a problem with NPM today. While publishing some v3.422.0 packages, NPM publishing failed, but would not let us re-publish that version. The version appeared to be inaccessible.

I'm deprecating v3.422.0 and v3.422.1 of `@aws-sdk/credential-providers` for now until a fix can be made in a higher version.

**Comment by yenfryherrerafeliz** [comment]
Please, as workaround use v3.421

Example:
```
npm install @aws-sdk/credential-providers@3.421
```

Thanks!

**Comment by kuhe** [comment]
In addition to the deprecation on NPM, I moved the `latest` npm tag back to this version: https://www.npmjs.com/package/@aws-sdk/credential-providers/v/3.421.0

**Comment by saptarshi-bose** [comment]
Updating the package.json with overrides will do it. But keep in mind that it requires at least npm v8.3.0 for it to work!

**Comment by yenfryherrerafeliz** [comment]
Hi people, I will close this issue since it has been resolve. Please update to the latest version if this issue still persist on your end.

Thanks!
