### ISSUE TITLE
Concatenate streaming response chunks

### ISSUE THREAD

**Issue by annk-inspify** [aws/aws-sdk-js-v3#5279]
### Describe the feature

I'm trying to use streaming response functions but dont know how to concatenate response payload chunks in to final results.

### Use Case

STREAMING RESPONSE

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3

### Environment details (OS name and version, etc.)

OS, Linux

**Comment by ajredniwja** [comment]
Hi @annk-inspify, thanks for opening this issue, you can use the code like below which I tried with `getObject` and use an async iterator to iterate over the stream and concatenate the chunks. 

```js
const { S3Client, GetObjectCommand } = require("@aws-sdk/client-s3");
const fs = require("fs");

const s3 = new S3Client({ region: 'us-west-2' });

const params = {
    Bucket: 'bucket',
    Key: 'key'
};

const getFile = async(destinationFile) => {
    try {
        const command = new GetObjectCommand(params);
        const response = await s3.send(command);

        const writeStream = fs.createWriteStream(destinationFile);

        for await (const chunk of response.Body) {
            writeStream.write(chunk);
        }

        writeStream.end();
        console.log("Success");

    } catch (error) {
        console.error("Error:", error);
    }
}

getFile('path/to/save/file');
```

For text based content you wont need `fs`. 

Please let us know if that doesnt work and you can specify the functions you are working with and I can try to come up with an example for that.
