### ISSUE TITLE
(lib-dynamodb) leverage tagged templates to write safer condition expressions

### ISSUE THREAD

**Issue by gabrielcipriano** [aws/aws-sdk-js-v3#5300]
### Describe the feature

When writing a `ConditionExpression` in a PutCommandInput, it's a good practice make use of `ExpressionAttributeNames` and `ExpressionAttributeValues` to [avoid reserved words and ambiguity](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ExpressionAttributeNames.html).

[tagged templates](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates) would allow us to build our condition expressions in a more idiomatic and safer way:
```ts
const result = await this.docClient.send(new PutCommand({
    TableName: table,
    Item: item,
    ...condition`${nameAttr("Key")} = ${valueAttr(2)}`
}))
```
is the same as:
```ts
const result = await this.docClient.send(new PutCommand({
    TableName: table,
    Item: item,
    ConditionExpression: '#Key = :value0 ',
    ExpressionAttributeNames: { '#Key': 'Key' },
    ExpressionAttributeValues: { ':value0': 2 }
}))
```

## The problem
Although the use of the `ExpressionAttributeNames` and `ExpressionAttributeNames` properties is useful, this could bring some problems with maintenance:

For instance, if we want to update our `ConditionExpression` below, we also have to remember to update the ExpressionAttribute properties.
```ts
// PutCommandInput
{
  // (...)
  ConditionExpression: '#Key = :value ', // if we change #Key, we also have to remember to update ExpressionAttributeNames dict
  ExpressionAttributeNames: { '#Key': 'Key' },
  ExpressionAttributeValues: { ':value': 2 }
}
```

Other problem is that we don't have any static checking that helps us to spot any inconsistency between our `ConditionExpression` and the ExpressionAttribute properties. So, a small typo in a complex condition expression can lead to a good headache.

## leverage tagged templates to write idiomatic and safer condition expression

Let's say that we have a tag function named `condition` to build our condition-related properties, and two helper functions `nameAttr` and `valueAttr` that marks a value as attributeName or attributeValue. 

We could build our condition expression like that:
```ts
exprProperties = condition`${nameAttr("Key")} = ${valueAttr(2)}`
console.log(exprProperties)
// {
//   ConditionExpression: '#Key = :value0 ',
//   ExpressionAttributeNames: { '#Key': 'Key' },
//   ExpressionAttributeValues: { ':value0': 2 }
// }
```
A more complex expression:
```ts
complexExpr = condition`${nameAttr("Uid")} = ${valueAttr("sKGe7u3")} AND ${nameAttr("Name")} <> ${valueAttr("John")} AND attribute_not_exists(${nameAttr("Metadata.Source")})`
console.log(complexExpr)
// {
//   ConditionExpression: '#Uid = :value0 AND #Name <> :value1 AND attribute_not_exists(#Metadata_Source)',
//   ExpressionAttributeNames: { '#Uid': 'Uid', '#Name': 'Name', '#Metadata_Source': 'Metadata.Source' },
//   ExpressionAttributeValues: { ':value0': 'sKGe7u3', ':value1': 'John' }
// }
// obs: notice that the special character dot (".") in "Metadata.Source" is auto-replaced by a "_"
```

### Other Information

We see that in this proposal, as an expression grows in complexity, more verbose is gets. That's when the `buildCondition` function could come into play:
```ts
const complexExpr = buildCondition((c, n, v) => 
    c`${n("Uid")} = ${v("sKGe7u3")} AND ${n("Name")} <> ${v("John")} AND attribute_not_exists(${n("Metadata.Source")})}`
)
```
`buildCondition` will call the arrow function injecting `condition`, `nameAttr` and `valueAttr` as parameters, allowing you to write the expression in a much less verbose way.

Of course, the definition of the syntax is still open. We could, for example, define that there is no need for the `nameAttr` function, agreeing that **a string would automatically be interpred as an attribute name**:
```ts
console.log( buildCondition((c, v) => c`${"Uid"} = ${v("sKGe7u3")} AND ${"Name"} <> ${v("John")}`) );
// {
//   ConditionExpression: '#Uid = :value0 AND #Name <> :value1',
//   ExpressionAttributeNames: { '#Uid': 'Uid', '#Name': 'Name'},
//   ExpressionAttributeValues: { ':value0': 'sKGe7u3', ':value1': 'John' }
// }
```
Or that there is no need for helper functions at all. Defining that strings in the template are names, and functions are values (that will be evaluated):
```ts
console.log( condition`${"Uid"} = ${() => "sKGe7u3")} AND ${"Name"} <> ${() => "John"}`) );
// {
//   ConditionExpression: '#Uid = :value0 AND #Name <> :value1',
//   ExpressionAttributeNames: { '#Uid': 'Uid', '#Name': 'Name'},
//   ExpressionAttributeValues: { ':value0': 'sKGe7u3', ':value1': 'John' }
// }
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

_edit: typos_

**Comment by kuhe** [comment]
I think it's a good idea. We are unable to accept the additional API surface to support right now, but encourage you to publish these helpers yourself as a library on NPM to be used with AWS DynamoDB and our DynamoDBDocument client.

**Comment by RanVaknin** [comment]
Hi @gabrielcipriano,

Thanks for the feature request. The background for the dynamo document client's implementation was a push from the Dynamodb team to help customers convert native language-specific types into Dynamo types. This is a hand written utility (`@aws-sdk/lib-dyanmodb`) that we are forced to maintain. 

While I can see the value in your example, after discussing this with the team, we have concluded that this high level library is not something we wish to maintain. It is not clear to us if this current implementation of `condition()` only substitutes this structure:
```
ConditionExpression ,ExpressionAttributeNames ,ExpressionAttributeValues
```

As @kuhe mentioned, your best bet would be to self publish this implementation, however if you need anything from the SDK team, we will be happy to chime in. 

Thanks again,
Ran~
