### ISSUE TITLE
Enable the UndoRedoDisabled option on the client

### ISSUE THREAD

**Issue by DorelBarbu** [aws/aws-sdk-js-v3#5302]
### Describe the feature

It would be nice to have the ability to control the `UndoRedoDisabled` through the SDK.

### Use Case

I looked in the docs, and there is no option to control this on the backend request, but it is possible to control it on the frontend side which is a bit annoying because I don't want to integrate the `amazon-quicksight-embedding-sdk` in my frontend app because it doesn't play well with my overall app structure.

If this can be done in any other way besides using the fronted sdk, I would be gladly interested in this.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.395.0

### Environment details (OS name and version, etc.)

Mac OS

**Comment by RanVaknin** [comment]
Hi @DorelBarbu 

I'm not familiar with `https://github.com/awslabs/amazon-quicksight-embedding-sdk` as this is a different product, managed by the Quicksight team, not the AWS SDK team. 

By saying "there is no option to control this on the backend request" you mean the backend code of your application?

You can use the [`GetDashboardEmbedUrlCommand`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/quicksight/command/GetDashboardEmbedUrlCommand/
) and pass in the `UndoRedoDisabled` as an input parameter.

Let me know if this helps.
Thanks,
Ran~

**Comment by DorelBarbu** [comment]
Hi @RanVaknin ,

Thank you very much for your response. I do appreciate it very much. It has indeed helped me to solve my problem, switching to `GetDashboardEmbedUrlCommand` has indeed solved the issue. I was not aware that this command existed, as in the official aws guides that I followed, the `GenerateEmbedUrlForRegisteredUserCommand` was used, and so this is what I have used.

Could you please tell me if there is any other major difference between `GetDashboardEmbedUrlCommand` and `GenerateEmbedUrlForRegisteredUserCommand`? It's not clear to me what is the difference between them.

Thank you very much!

**Comment by RanVaknin** [comment]
Hi @DorelBarbu,

I'm happy to hear it helped. While I'm not a QuickSight expert, the documentation specifies that `GenerateEmbedUrlForRegisteredUserCommand` is intended for any _user registered_ within a QuickSight account.

As for feature differences, it seems like `GenerateEmbedUrlForRegisteredUserCommand` does not offer the `UndoRedoDisable` option that `GetDashboardEmbedUrlCommand` does. For details about why this parameter isn't supported, you may want to consult directly with the QuickSight service team (can be done by filing a support ticket via the AWS console)

It's worth mentioning that AWS SDKs are code-generated based on each AWS service's API model. If a feature or parameter is not in the QuickSight API, it won't be part of the SDK.

Hope this clears things up.
Thanks,
Ran~

**Comment by DorelBarbu** [comment]
Ok, thanks again for your help! All good now.
