### ISSUE TITLE
SearchPromptsCommand is not a constructor

### ISSUE THREAD

**Issue by saulortega** [aws/aws-sdk-js-v3#5315]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Hi.

I'm trying to implement `SearchPromptsCommand` from Amazon Connect. Their types are defined in library, but it seems like the library doesn't contain the actual code.

My typescript code:

```ts
import {
    ConnectClient,
    Prompt,
    SearchPromptsCommand,
    SearchPromptsCommandInput,
} from '@aws-sdk/client-connect'
import { Env, getenv } from '../parameters'

const connectClient = new ConnectClient({
    region: getenv(Env.AWS_REGION),
})

// ...

export async function searchPromptsByName(instanceId: string, name: string): Promise<Prompt[]> {
    const searchPromptsCommandInput: SearchPromptsCommandInput = {
        InstanceId: instanceId,
        SearchCriteria: {
            StringCondition: {
                ComparisonType: 'EXACT',
                FieldName: 'Name',
                Value: name,
            }
        }
    }

    const res = await connectClient.send(new SearchPromptsCommand(searchPromptsCommandInput))
    return res.Prompts || []
}

// ...
```

Transpiled, I added two console.log:

![image](https://github.com/aws/aws-sdk-js-v3/assets/6834676/c7f2e773-6864-4192-9a65-b43bb22d9552)

The logs in CloudWatch:

![image](https://github.com/aws/aws-sdk-js-v3/assets/6834676/de50bfb5-aab7-4b5a-b0fc-aaca90cb5eae)

![image](https://github.com/aws/aws-sdk-js-v3/assets/6834676/67f21191-5989-48f3-bead-c6be03c69304)

I tried both, uploading to AWS Lambda my code with and without the SDK package (Node.js Lambdas includes the official AWS SDK). In both cases I got the same error.

### SDK version number

@aws-sdk/client-connect@3.424.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.15.0

### Reproduction Steps

```ts
import {
    ConnectClient,
    Prompt,
    SearchPromptsCommand,
    SearchPromptsCommandInput,
} from '@aws-sdk/client-connect'

const connectClient = new ConnectClient({
    region: process.env.AWS_REGION,
})

async function searchPromptsByName(instanceId: string, name: string): Promise<Prompt[]> {
    const searchPromptsCommandInput: SearchPromptsCommandInput = {
        InstanceId: instanceId,
        SearchCriteria: {
            StringCondition: {
                ComparisonType: 'EXACT',
                FieldName: 'Name',
                Value: name,
            }
        }
    }

    const res = await connectClient.send(new SearchPromptsCommand(searchPromptsCommandInput))
    return res.Prompts || []
}

export const handler = async(event: any) => {
    await searchPromptsByName('aaaaaaaaaaaaaaa', 'bbbbbbbbbbb')
}

// ...
```

### Observed Behavior

![image](https://github.com/aws/aws-sdk-js-v3/assets/6834676/67f21191-5989-48f3-bead-c6be03c69304)

### Expected Behavior

Not that specific error.

**Comment by RanVaknin** [comment]
Hi @saulortega ,

Since you are using lambda I assume you are using the embedded version of the SDK. 

The SearchPrompts feature was added [4 months ago](https://github.com/aws/aws-sdk-js-v3/commit/37fc985cebce1e06495fed60421ca272f3b6737b#diff-26a4234e622fc546b71a80b685aaa6f8afa3b30601b6ecd17b76390c8b00014bR627)

And the SDK version lambda embeds is 3.188.0 which is from October of last year, so it would not have support for a feature that did not exist at the time. 

If you want to run the most up to date version of the SDK from lambda, you need to either [bundle your SDK](https://aws.amazon.com/blogs/compute/optimizing-node-js-dependencies-in-aws-lambda/) or upload it as a lambda layer.

Let me know if you need anything else.
Ran~

**Comment by saulortega** [comment]
Thank you, Ran.

I bundled the SDK in my code, but for some reason it didn't work. However, I just tried with a Lambda layer and it's working now.
