### ISSUE TITLE
config is not defined

### ISSUE THREAD

**Issue by suhajda3** [aws/aws-sdk-js-v3#5326]
### Describe the issue

Most examples include the config parameter for client creation, but the variable is not defined. As a result, the sample code will not run without modification. It would be great to see the config parameter defined or the parameters included.

```
const config = new LambdaClient({
    region: 'us-east-2'
});
```

or

`const client = new LambdaClient({region: 'us-east-2'});`

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/lambda/command/GetFunctionUrlConfigCommand/

**Comment by RanVaknin** [comment]
Hi @suhajda3 ,

Thanks for reaching out. 

You will find the _client's config_ inputs in the [_client page_](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/lambda/), not the operation page. (scroll all the way to the bottom)

<img width="985" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/50976344/c7608df9-bc53-4680-b99a-b96b9e912b33">


I hope this helps,
Ran~
