### ISSUE TITLE
Cannot create EC-secp384r1 certificate with node 18

### ISSUE THREAD

**Issue by udondan** [aws/aws-sdk-js-v3#5329]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Apparently it is not possible to create an EC-secp384r1 certificate with Node 18. We have a Lambda function which creates certificates. The certificate algorithm is hardcoded in the parameters passed to the `RequestCertificateCommand` and is set to `EC_secp384r1`.

When this code is executed in lambda runtime 16, the certificate is created with the expected algorithm. Simply switching the runtime to Node 18 does **not** cause any error. The certificate is created without any issues but then is of type RSA-2048.

### SDK version number

@aws-sdk/client-acm@3.425.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

18.17.1

### Reproduction Steps

```ts
const input: RequestCertificateCommandInput = {
   DomainName: domainName,
   SubjectAlternativeNames: subjectAlternativeNames,
   CertificateAuthorityArn: certificateAuthorityArn,
   KeyAlgorithm: 'EC_secp384r1'
 };
 const command = new RequestCertificateCommand(input);
 await client.send(command);
```

### Observed Behavior

Run above code once with Node 16 (16.20.2) and you get an `EC-secp384r1` certificate. Run it with Node 18 (18.17.1) and you get an `RSA-2048` certificate.

### Expected Behavior

Irrespective of the used NodeJS version the certificate should be created with the specified `KeyAlgorithm`.

### Additional Information/Context

While we use the Node 18 lambda runtime, which comes with the aws-sdk pre-installed, we bundle the Lambda function ourselves with the latest aws-sdk packages, currently 3.425.0 for `@aws-sdk/client-acm`

Node versions are taken from inside the Lambda function via `process.versions.node`.

**Comment by RanVaknin** [comment]
Hi @udondan,

I'm not able to reproduce your issue. For me running the following code resulted in a request for the right certificate algorithm to be created:

```js
import { ACMClient, KeyAlgorithm, RequestCertificateCommand } from "@aws-sdk/client-acm";

const client = new ACMClient({region: "us-east-1"})

try {
    const response = await client.send(new RequestCertificateCommand({
        DomainName:"REDACTED.aws.dev",
        KeyAlgorithm: KeyAlgorithm.EC_secp384r1
    }))
    console.log(response)
} catch (error) {
    console.log(error)
}
/*
Response:
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'REDACTED',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  CertificateArn: 'arn:aws:acm:us-east-1:REDACTED:certificate/REDACTED'
}
*/
```

<img width="779" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/50976344/4a51e833-71bc-4ae9-8f4a-3de703f709d1">

I'm not sure why you are seeing this behavior, but you might want to create a middleware to log the raw request and response and see if something doesn't add up in the way the request is being sent:

```js
client.middlewareStack.add(next => async(args) => {
    console.log('before sign: ' , args.request);
    const response = await next(args)
    console.log(response)
    return response;
}, {step: 'build'})
```

Let me know what you have found.
Thanks,
Ran~
