### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by siamahnaf** [aws/aws-sdk-js-v3#5334]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Hello, I am getting an type error when I am using this package into nextjs projects.

`TypeError: Failed to fetch`

Here is image of error-

![image](https://github.com/aws/aws-sdk-js-v3/assets/78312010/cdc70f3f-a74e-4622-8b18-01a0f9ada8ff)

In Console I am find this-

`Uncaught (in promise) TypeError: Failed to fetch
    at FetchHttpHandler.handle (fetch-http-handler.js:56:1)
    at async eval (flexibleChecksumsResponseMiddleware.js:17:1)
    at async eval (deserializerMiddleware.js:2:24)`
    
 
 Here is my usage of this package-
 
```
          const params = {
            Bucket: this.config.bucketName,
            Key: key,
            Body: file,
            ACL: "public-read",
            Metadata: {
                uuid: "14365123651274",
                tag: "",
            },
            ContentType: file.type,
            ServerSideEncryption: "AES256",
        };
        const command = new PutObjectCommand(params);
        const data = await client.send(command);
```

What is the main problem.

### SDK version number

@aws-sdk/client-s3@3.427.0 

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

18.17.0

### Reproduction Steps

```
const client = new S3Client({
            region: this.config.region,
            credentials: {
                accessKeyId: this.config.accessKeyId,
                secretAccessKey: this.config.secretAccessKey,
            }
        });
        const params = {
            Bucket: this.config.bucketName,
            Key: key,
            Body: file,
            ACL: "public-read",
            Metadata: {
                uuid: "14365123651274",
                tag: "",
            },
            ContentType: file.type,
            ServerSideEncryption: "AES256",
        };
        const command = new PutObjectCommand(params);
        const data = await client.send(command);
```

### Observed Behavior

It just thawed error.

### Expected Behavior

It should work perfectly!

**Comment by legendsyy** [comment]
Yep i have the exact same problem, works on firefox but not on chrome or edge

**Comment by rakhimovkamran** [comment]
The same error, any ideas how to resolve this kind of issue, maybe need to downgrade ?

**Comment by MrLucio** [comment]
Can confirm that downgrading to `3.370.0` resolved the issue for me.
Either there was a bug in the recent updates or a dependency has been updated and somehow caused some conflict.

**Comment by gusberinger** [comment]
Can also confirm that downgrading to 3.370.0 resolved it for me.

**Comment by MyThunder11** [comment]
Can also confirm that downgrading resolved my problem

**Comment by ajredniwja** [comment]
Running this in node with `3.427.0` does not give me error
```js
import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";
import { createReadStream } from "fs";
import { lookup } from "mime-types";

const client = new S3Client({ region: 'us-west-2' });

(async() => {
    try {
        const filePath = 'path';
        const fileStream = createReadStream(filePath);
        const params = {
            Bucket: 'bucket',
            Key: 'key',
            Body: fileStream,
            ACL: "public-read",
            ContentType: lookup(filePath) || 'application/octet-stream',
            ServerSideEncryption: "AES256",
        };
        const command = new PutObjectCommand(params);
        const data = await client.send(command);
        console.log('Success:', data);
    } catch (error) {
        console.error('Error:', error);
    }
})();
```

Running some more test cases will post updates

**Comment by ajredniwja** [comment]
Running in browser I was able to reproduce the issue using React: 
```js
import './App.css';
import React from 'react';
import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";

function App() {
    const handleFileChange = async(event) => {
        const file = event.target.files[0];
        const reader = new FileReader();

        reader.onload = async(event) => {
            const blob = new Blob([event.target.result], { type: file.type });

            const client = new S3Client({
                region: 'us-west-2',
            });
            const params = {
                Bucket: 'bucket',
                Key: file.name,
                Body: blob,
                ContentType: file.type,
                ACL: "public-read",
                ServerSideEncryption: "AES256",
            };
            const command = new PutObjectCommand(params);

            try {
                const data = await client.send(command);
                console.log('Success:', data);
            } catch (error) {
                console.error('Error:', error);
            }
        };

        reader.readAsArrayBuffer(file);
    };

    return ( <
        div >
        <
        input type = "file"
        onChange = { handleFileChange }
        /> < /
        div >
    );
}

export default App;
```

error: 
```console
App.js:35 Error: TypeError: Failed to fetch
    at FetchHttpHandler.handle (fetch-http-handler.js:55:1)
    at async flexibleChecksumsResponseMiddleware.js:17:1
    at async deserializerMiddleware.js:2:1
```

**Comment by kuhe** [comment]
as a workaround, try setting keepalive to false in browser applications

```js
import { FetchHttpHandler } from "@smithy/fetch-http-handler";
import { S3Client } from "@aws-sdk/client-s3";

new S3Client({
  requestHandler: new FetchHttpHandler({ keepAlive: false })
});
```

We will likely need to patch the fetch-http-handler not to default keepalive to true.

**Comment by ajredniwja** [comment]
I can confirm using the workaround mentioned by @kuhe I dont see the error.

**Comment by ajredniwja** [comment]
`3.377.0` seems to be the latest version working

**Comment by kuhe** [comment]
To resolve this issue, explicitly set keepAlive=false as in my previous example or ensure that your application has `@smithy/fetch-http-handler`@`2.2.3` installed. https://github.com/awslabs/smithy-typescript/blob/main/packages/fetch-http-handler/CHANGELOG.md#223

You may need to update your lockfile for this, since fetch-http-handler is a transitive dependency of the SDK. You do not need to explicitly install it in your package.json.
