### ISSUE TITLE
Error: Can't walk dependency graph: ENOENT: no such file or directory, lstat '/Users/test/Git/UIAutomation/qa-ui-automation/pt/process'

### ISSUE THREAD

**Issue by praveentata** [aws/aws-sdk-js-v3#5349]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I am running UI tests using Cypress 13.3.0

I am using the following AWS SDK libraries:

- @aws-sdk/client-cloudformation@3.142.0
- @aws-sdk/client-ec2@3.142.0

I have a test which imports the following AWS libraries:

```javascript
import {
  CloudFormationClient,
  CreateStackCommand,
  DescribeStacksCommand,
  DeleteStackCommand,
} from '@aws-sdk/client-cloudformation';
```

When I run the command `npx cypress open`, I am getting the following error:

```
Error: Can't walk dependency graph: ENOENT: no such file or directory, lstat '/Users/test/Git/UIAutomation/qa-ui-automation/pt/process'
    required by /Users/test/Git/UIAutomation/qa-ui-automation/pt/node_modules/@aws-sdk/util-user-agent-node/dist-cjs/index.js
```

**package.json**

```json
{
  "name": "my-project",
  "version": "1.0.0",
  "description": "E2E UI automation",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@testing-library/cypress": "^10.0.1",
    "chai": "^4.3.6",
    "chai-as-promised": "^7.1.1",
    "cypress-xpath": "^1.6.2",
    "dayjs": "^1.10.6",
    "pretty-format": "^27.0.6"
  },
  "devDependencies": {
    "@aws-sdk/client-cloudformation": "^3.75.0",
    "@aws-sdk/client-ec2": "^3.75.0",
    "@reportportal/agent-js-cypress": "^5.0.3",
    "cypress": "13.3.0",
    "cypress-audit": "^1.0.0",
    "cypress-downloadfile": "^1.2.1",
    "cypress-iframe": "^1.0.1",
    "cypress-localstorage-commands": "^1.6.1",
    "cypress-multi-reporters": "^1.5.0",
    "cypress-tags": "^1.1.2",
    "cypress-wait-until": "^1.7.2",
    "eslint": "^7.32.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-cypress": "^2.11.3",
    "eslint-plugin-prettier": "^3.4.0",
    "eslint-plugin-react": "^7.24.0",
    "junit-report-merger": "^3.0.2",
    "mocha-junit-reporter": "^2.0.2",
    "mochawesome": "^7.0.1",
    "mochawesome-merge": "^4.2.1",
    "mochawesome-report-generator": "^6.0.1",
    "prettier": "^2.3.2",
    "typescript": "^4.3.5"
  }
}
```

### SDK version number

@aws-sdk/client-cloudformation@3.142.0, @aws-sdk/client-ec2@3.142.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node -v v18.18.0

### Reproduction Steps

Just import any AWS related libraries to any Cypress spec file. For example:

```javascript
import {
  CloudFormationClient,
  CreateStackCommand,
  DescribeStacksCommand,
  DeleteStackCommand,
} from '@aws-sdk/client-cloudformation';
```

### Observed Behavior

When I run the command `npx cypress open`, I am getting the following error:

```
Error: Can't walk dependency graph: ENOENT: no such file or directory, lstat '/Users/test/Git/UIAutomation/qa-ui-automation/pt/process'
    required by /Users/test/Git/UIAutomation/qa-ui-automation/pt/node_modules/@aws-sdk/util-user-agent-node/dist-cjs/index.js
```

I tried changing this:
`const process_1 = require("process");` to `const process_1 = require("process/");` - Added `/` as suggested here: https://github.com/browserify/browserify/issues/1986

After making the change, I got a similar issue for another library `aws-crt`.
I installed that library and made a similar change in its `index.js` file which then landed me to this error: https://github.com/aws/aws-sdk-js-v3/issues/3828

It will be great if someone can provide some pointers on what's going wrong

![image](https://github.com/aws/aws-sdk-js-v3/assets/26746723/af5b1bc6-ccbf-4ecd-9ba4-ea877ec394d5)

### Expected Behavior

Cypress test should be able to identify the import and run the test

**Comment by praveentata** [comment]
So, it seems like the `cypress-tags` library is causing this issue.
After removing the `cypress-tags` library, I was able to successfully run the tests.
This library also intereferred with Report Portal `autoMerge` feature. I was encountering the following error: https://github.com/reportportal/agent-js-cypress/issues/175

**Comment by RanVaknin** [comment]
Seems like you isolated the problem. I suggest you contact the cypress-tags maintainers for support regarding this issue.

Thanks,
Ran~
