### ISSUE TITLE
Add streaming support for QueryCommand in DynamoDBDocumentClient

### ISSUE THREAD

**Issue by jirimoravcik** [aws/aws-sdk-js-v3#5355]
### Describe the feature

Currently, when you want to use `QueryCommand`, you get the response unmarshalled with `Items` as an array. It would be nice to be able to get the raw stream, this would prevent OOM errors, i.e. remove the deserialization and unmarshalling middleware.

### Use Case

In the version 2 of SDK, the following code was possible:
```js
const docClient = new aws.DynamoDB.DocumentClient(...);
const stream = docClient.query(queryParams).createReadStream();
```
This allowed us to pipe the results from the query into our custom transformation streams and avoid OOM errors.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

latest

### Environment details (OS name and version, etc.)

Ubuntu 22.04, but this is irrelevant to the issue

**Comment by kuhe** [comment]
```ts
const queryCommand = new QueryCommand({
    TableName,
    KeyConditionExpression: `id = :id`,
    ExpressionAttributeValues: {
      ":id": "2",
    },
    ConsistentRead: true,
  });

  queryCommand.middlewareStack.add(
    (next) => async (args) => {
      const n = await next(args);
      return {
        ...n,
        output: n.response,
      };
    },
    {
      name: "DocumentUnmarshall",
      relation: "before",
      toMiddleware: "deserializerMiddleware",
      override: true,
    }
  );

  const queryResponse = await doc.send(queryCommand);
```

Using this middleware override of the document unmarshall step will return the HttpResponse object instead of the deserialized output. You can then interact with the response's body stream. 

This is not the intended usage because the Query API is paginated. You should reduce the page size with the `Limit` input parameter if you are running OOM.
