### ISSUE TITLE
HeadBucket Command has no viable output

### ISSUE THREAD

**Issue by Cu7l4ss** [aws/aws-sdk-js-v3#5358]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Hello,

I am currently trying to find out a region for a bucket.
And so, I've came across two options, mainly:
- `GetBucketLocation` this works partially, and at times fails due to other reasons
- `HeadBucket` - the recommended way to get a buckets region (according to the documentation)

And so, I turned to the `HeadBucket` way, problem is response headers which contain the region are unavailable - had been [purposefully removed](https://github.com/aws/aws-sdk-js-v3/issues/1491).

This means that other than the status of the response and the error thrown, the command is completely unusable 
 unlike what the documentation recommended.

Couple of questions:
1. Is this a bug? (it looks like a bug)
2. Is there any other consistent viable way to get the region of a S3 Bucket prior to doing any operations on it?

Thank you

### SDK version number

@aws-sdk/package-name@version, @aws-sdk/s3-client@3.428.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.8.0

### Reproduction Steps

Choose a bucket name

```
await s3Client.send( new HeadBucketCommand({ Bucket: "BucketName"});
```

### Observed Behavior

No Http Response headers available 

### Expected Behavior

Http Response Headers available, or the s3 bucket region as part of the command output

### Possible Solution

s3 bucket region as part of the command output if the command is successful.

**Comment by yenfryherrerafeliz** [comment]
Hi @Cu7l4ss, I can confirm that the response is providing you with the headers. I will mark a needs-review label so we can investigate this further.

Thanks!

Repro Code:
```js
import {HeadBucketCommand, S3Client} from "@aws-sdk/client-s3";

const client = new S3Client({
    region: "us-east-2",
});
const response = await client.send(new HeadBucketCommand({
    Bucket: process.env.TEST_BUCKET,
}));

console.log(response)
```
Response:

```
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'REDACTED',
    extendedRequestId: 'REDACTED',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}

```

**Comment by Cu7l4ss** [comment]
Thank you for the prompt response, anything I can do to pitch in?

**Comment by yenfryherrerafeliz** [comment]
@Cu7l4ss, you could add a middleware and get the headers from there as follow:

```js
import { HeadBucketCommand, S3Client } from "@aws-sdk/client-s3";

const client = new S3Client({
    region: "us-east-2"
});
client.middlewareStack.addRelativeTo(
    (next) => async (args) => {
        const { response } = await next(args);

       console.log(response.headers);

        return {
            response,
        };
    },
    {
        name: "logHeadersMiddleware",
        toMiddleware: "deserializerMiddleware",
        relation: "after",
        step: "deserialize",
        override: true,
    }
);
const response = await client.send(new HeadBucketCommand({
    Bucket: process.env.TEST_BUCKET
}));

console.log(response);
```

Please let me know if that helps!

Thanks!
