### ISSUE TITLE
client-dynamodb/lib-dynamodb v3.428.0: Sending an UpdateCommand fails with TypeError

### ISSUE THREAD

**Issue by maplesteve** [aws/aws-sdk-js-v3#5360]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Since v3.428.0 updates on a DynamoDB table fail with a TypeError. It worked up to v3.427.0. The call of `new UpdateCommand(...)` is ok, but sending the call to DynamoDB fails. The properties of the `UpdateCommand` result are different between v3.428.0 and v3.427.0, which may lead to this error.

### SDK version number

@aws-sdk/lib-dynamodb@3.428.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node.js 18.x

### Reproduction Steps

```ts
let UpdateExpression = "SET autoDeployEnabled = :autoDeployEnabled";
if (args.config.manualDeploymentInfo !== undefined) {
  UpdateExpression += ", manualDeploymentInfo = :manualDeploymentInfo";
}
const cmd = new UpdateCommand({
  ExpressionAttributeValues: {
    ":autoDeployEnabled": args.config.autoDeployEnabled,
    ":manualDeploymentInfo": args.config.manualDeploymentInfo,
  },
  Key: { dataItemType: TestDeploymentDataItemType, repoName: args.repoName },
  ReturnValues: "ALL_NEW",
  TableName: GlobalConstants.DataItemsTableName,
  UpdateExpression,
});
const result = await DynamoDBDocumentClient.send(cmd);
```

### Observed Behavior

The call `await DynamoDBDocumentClient.send(cmd)` fails with a TypeError:
```
TypeError: Cannot read properties of undefined (reading 'S')
    at AttributeValue.visit (node_modules/@aws-sdk/client-dynamodb/dist-cjs/models/models_0.js:620:19)
    at se_AttributeValue (node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:2948:38)
    at [path_redacted]/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3151:20
    at Array.reduce (<anonymous>)
    at se_ExpressionAttributeValueMap (node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3147:34)
    at ExpressionAttributeValues (node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3535:43)
    at applyInstruction (node_modules/@smithy/smithy-client/dist-cjs/object-mapping.js:73:33)
    at take (node_modules/@smithy/smithy-client/dist-cjs/object-mapping.js:44:9)
    at se_UpdateItemInput (node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3529:37)
    at se_UpdateItemCommand (node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:357:27)
```

### Expected Behavior

The call doesn't fail. It didn't fail with prior versions of client-dynamodb/lib-dynamodb.

### Additional Information/Context

The properties `inputKeyNodes` and `outputKeyNodes` of the created `UpdateCommand` (variable `cmd`; see above) differ:

v3.427.0
```json
  "inputKeyNodes": [
    { "key": "Key" },
    {
      "key": "AttributeUpdates",
      "children": { "children": [{ "key": "Value" }] }
    },
    {
      "key": "Expected",
      "children": {
        "children": [{ "key": "Value" }, { "key": "AttributeValueList" }]
      }
    },
    { "key": "ExpressionAttributeValues" }
  ],
  "outputKeyNodes": [
    { "key": "Attributes" },
    {
      "key": "ItemCollectionMetrics",
      "children": [{ "key": "ItemCollectionKey" }]
    }
  ],
```

with v3.428.0
```json
  "inputKeyNodes": {
    "Key": {},
    "AttributeUpdates": { "*": { "Value": null } },
    "Expected": { "*": { "Value": null, "AttributeValueList": [] } },
    "ExpressionAttributeValues": {}
  },
  "outputKeyNodes": {
    "Attributes": {},
    "ItemCollectionMetrics": { "ItemCollectionKey": {} }
  },
```

`inputKeyNodes` and `outputKeyNodes` where changed/touched in this PR https://github.com/aws/aws-sdk-js-v3/pull/5306 (fix(lib-dynamodb): add e2e suite and bug fixes for lib-dynamodb)

**Comment by WtfJoke** [comment]
We experience the same issue with `PutItemCommand`.

```typescript
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read properties of undefined (reading 'S')",
    "stack": [
        "TypeError: Cannot read properties of undefined (reading 'S')",
        "    at AttributeValue2.visit (/var/task/index.js:21363:19)",
        "    at se_AttributeValue (/var/task/index.js:24368:40)",
        "    at /var/task/index.js:24747:20",
        "    at Array.reduce (<anonymous>)",
        "    at se_PutItemInputAttributeMap (/var/task/index.js:24743:36)",
        "    at Item (/var/task/index.js:24734:22)",
        "    at applyInstruction (/var/task/index.js:20552:31)",
        "    at take (/var/task/index.js:20525:9)",
        "    at se_PutItemInput (/var/task/index.js:24728:39)",
        "    at se_PutItemCommand (/var/task/index.js:21686:29)"
    ]
}
```

**Comment by kuhe** [comment]
I will take a look at it since I recently worked on lib-dynamodb.

**Comment by ncino-esselman** [comment]
Running into same issue. Our payload includes {"key":undefined} and now fails with `Cannot read properties of undefined (reading 'S')"` if I take a previous version it works as expected

**Comment by kuhe** [comment]
I wasn't able to reproduce this error with a basic update command. My code is this:

```ts
import { DynamoDB } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocument } from "@aws-sdk/lib-dynamodb";

const dynamodb = new DynamoDB({
  region: "us-west-2",
});

const data = {
  myMap: [
    null,
    "myString",
    [2, 8, [9, 9, 9, [10, 10, 10]]],
    {
      myString: "string",
      myNumber: 1,
    },
  ],
};

const doc = DynamoDBDocument.from(dynamodb, {});

const TableName = "test";

  await doc
    .update({
      TableName,
      ExpressionAttributeValues: {
        ":data": data,
        ":extra": data,
      },
      ExpressionAttributeNames: {
        "#data": "data",
      },
      Key: {
        id: "2",
      },
      ReturnValues: "ALL_NEW",
      UpdateExpression: "SET #data = :data, extra = :extra",
    })
    .catch((e) => {
      console.log(e);
    });

  const get = await doc.get({
    TableName,
    Key: {
      id: "2",
    },
  });

  console.log("GetItemCommand", "actual", get);
```

Please provide the following information:

- Your installed versions of `@aws-sdk/client-dynamodb`, `@aws-sdk/util-dynamodb`, `@aws-sdk/lib-dynamodb`.
- The approximate structure of your data in `args.config.autoDeployEnabled` and `args.config.manualDeploymentInfo`.

**Comment by ncino-esselman** [comment]
```
const item = {
  PK: 'T#tanant#',
  SK: 'OF#org#feature#',
  itemType: 'OrganizationFeatureApp',
  feature: 'feature',
  env: 'Sandbox',
  iss: 'abcdef12345678',
  subj: 'subj',
  aud: 'aud,
  token: undefined,
  tenantId: 'tenant',
  orgId: 'parksAndRec',
  companyName: 'cityOfPawnee'
}
const cmd = new PutCommand({
      TableName: tableName,
      Item: {
        ...item
      }
    });
```
Fails with `Cannot read properties of undefined (reading 'S')"` on version 3.428.0 but works on `3.398.0` which just happens to be the version I was on before will check on 3.427.0 right now

**Comment by kuhe** [comment]
@ncino-esselman your error appears to be caused by the top-level undefined value.

Because of the changes (fixes) in https://github.com/aws/aws-sdk-js-v3/pull/5306, the "removeUndefinedValues" option is only applied to AttributeValue nodes, which are the values of your item, but not the item itself.

For example: 

```js
const Item = {
  PK: '1',
  map: { 
    key: 'value',
    undefinedKey: undefined
  },
  list: [1, 2, undefined],
  undefined_column: undefined // not filtered by marshall options
}
```
would have the undefined values filtered out, but not at the column level.

Although this is a correction of previous unintentional behavior, I will try to make a compatibility fix to support top level undefined AttributeValues.

**Comment by ncino-esselman** [comment]
Oh fascinating. This seems to be a miss on documentation side of things then. The docs are not clear ([here](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/interfaces/_aws_sdk_util_dynamodb.marshalloptions-1.html)). The root level item has to be marshalled and unmarshalled so why would these setting not apply? I can add in the fix but I am trying to understand the behavior of this setting. I would appreciate any insights

**Comment by ncino-esselman** [comment]
Okay last question I really appreciate the explanation
native JS input
```
{
  Item: {
    PK: '...',
    column1: 1,
    column2: 'string',
    column3: undefined
  }
}
```
Is this technically marshalling the value `undefined`? But because it is the value it is unable to remove the Item.entry as a whole?
```
{
  Item: {
    PK: { S: '...' },
    column1: { N: 1 },
    column2: { S: 'string' },
    column3: {S: undefined} //causing an error
  }
}
```

I think that is where my confusion is coming from with the property name and purpose

**Comment by maplesteve** [comment]
> Please provide the following information:
> 
> * Your installed versions of `@aws-sdk/client-dynamodb`, `@aws-sdk/util-dynamodb`, `@aws-sdk/lib-dynamodb`.

As stated above, they're all 3.428.0

> * The approximate structure of your data in `args.config.autoDeployEnabled` and `args.config.manualDeploymentInfo`.

The structure is as follows; it's the representation of how it's stored in DDB. `manualDeploymentInfo ` can be `undefined`/`null`.
```ts
interface TestDeploymentDataItem {
    dataItemType: string
    repoName: string
    autoDeployEnabled: boolean
    manualDeploymentInfo?: {
        deployedBy: string
        deploySource: string
        since: string
        testReason: string
    }
    lastDeployment?: {
        commit: string
        commitMessage: string
        updated: string
    }
}
```

> * Your options given to the Document client on construction.

```ts
marshallOptions: {
  convertClassInstanceToMap: true,
  removeUndefinedValues: true
}
```

**Comment by kuhe** [comment]
@ncino-esselman 

It can't marshal/marshall the column value of `undefined` because it doesn't correspond to any DynamoDB AttributeValue type. The closest is NULL, i.e. `{ NULL: true }` or omitting the column. `{ S: undefined }` is not valid because the S is for string values.

Undefined can be removed from maps and sets by the `removeUndefinedValues` marshallOptions flag, because that does not change the AttributeValue type of the map or set. But when it is the entire value, the column cannot be inserted. Currently the TypeError is based on the SDK being unable to serialize the unexpected undefined column value. 

Previously it worked because the marshall system incorrectly defined the entire Item as an AttributeValue and extracted its `M` value. 

---- 

@maplesteve if manualDeploymentInfo is a column value and can be undefined, you are likely facing the same issue. 

If you performing an insert, there is a patch upcoming in #5365 which will ignore undefined columns as before. However, if you are performing an update and want to set the column's value from something to nothing, you should use a value of `null` instead. Setting an undefined column in an update will, even after the fix, at best be ignored, but will not overwrite the table data as you may intend.

**Comment by ncino-esselman** [comment]
That makes sense! Thank you so much for your time and explanation! Also for the backwards compatibility change!!
