### ISSUE TITLE
Undeclared `@smithy/smithy-client` dependency in `@aws-sdk/credential-provider-http`

### ISSUE THREAD

**Issue by Drarig29** [aws/aws-sdk-js-v3#5362]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Same as https://github.com/aws/aws-sdk-js-v3/issues/5056

The `@smithy/smithy-client` dependency is imported here:
https://github.com/aws/aws-sdk-js-v3/blob/f05d9c6150213ab279fb4afbff16b5c6e5e56bdd/packages/credential-provider-http/src/fromHttp/requestHelpers.ts#L4

But not declared in `@aws-sdk/credential-provider-http`'s dependencies.

### SDK version number

@aws-sdk/credential-providers@3.428.0, @aws-sdk/credential-provider-http@3.428.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.15.0

### Reproduction Steps

- `yarn add @aws-sdk/credential-providers@3.428.0`
- `import {fromIni} from '@aws-sdk/credential-providers'`

### Observed Behavior

At import time, Node.js fails with:
```
Error: @aws-sdk/credential-provider-http tried to access @smithy/smithy-client, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: @smithy/smithy-client
Required by: @aws-sdk/credential-provider-http@npm:3.428.0 (via <redacted>/.yarn/cache/@aws-sdk-credential-provider-http-npm-3.428.0-193a49487e-e0824af9d4.zip/node_modules/@aws-sdk/credential-provider-http/dist-cjs/fromHttp/)
```

### Expected Behavior

The code should run without import time errors.

**Comment by yenfryherrerafeliz** [comment]
Hi @Drarig29, this has been fixed. Please just update to the latest version and you should have not issues. You can confirm the fix [here](https://github.com/aws/aws-sdk-js-v3/blob/main/packages/credential-provider-http/package.json#L34). 

Please feel free of opening a new issue if is there anything that we can help you with.

Thanks!

**Comment by jfirebaugh** [comment]
@yenfryherrerafeliz It isn't fixed in the latest version. The line you linked to is a dependency on `@smithy/types`, not `@smithy/smithy-client`. Could you please reopen the issue?

**Comment by Drarig29** [comment]
@yenfryherrerafeliz I agree with John that the issue is not fixed, and that the line you linked isn't related.

Can you please reopen?

**Comment by Drarig29** [comment]
Pinging @kuhe since you recently fixed a [related issue](https://github.com/aws/aws-sdk-js-v3/issues/5056) 🙂

**Comment by kuhe** [comment]
Added it in #5395 to be included in the next release.

**Comment by Drarig29** [comment]
Thanks a lot!
