### ISSUE TITLE
(lib-dynamodb): DocumentClient should handle i/o of large numbers e.g. BigInt

### ISSUE THREAD

**Issue by alanb-sony** [aws/aws-sdk-js-v3#5363]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The following code:
```
const doc = DynamoDBDocument.from(new DynamoDB());
await doc.put({
  TableName: 'test',
  Item: { num: 1.23e100 },
});
```
Raises the error:
```
Error: Number 1.23e+100 is greater than Number.MAX_SAFE_INTEGER. Use BigInt.
```
We could change `num` to `BigInt` but it is actually a floating point value so we'd have to only convert large numbers, as our numbers are already stored as `Number`, changing them to `BigInt` isn't going to increase their precision

### SDK version number

@aws-sdk/lib-dynamodb@3.428.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.18.0

### Reproduction Steps

```
const doc = DynamoDBDocument.from(new DynamoDB());
await doc.put({
  TableName: 'test',
  Item: { num: 1.23e100 },
});
```

### Observed Behavior

An error is thrown:
```
Error: Number 1.23e+100 is greater than Number.MAX_SAFE_INTEGER. Use BigInt.
```

### Expected Behavior

Large numbers should be stored in the database

**Comment by alanb-sony** [comment]
Even converting a number to a BigInt isn't a trivial task as dynamo wont accept numbers with more than 38 digits of precision

**Comment by kuhe** [comment]
For now, use the base DynamoDB client to `put` with large numbers.

**Comment by kuhe** [comment]
A way to mark large or precise numbers for input and output will be included in the next release.

Instructions are at https://github.com/aws/aws-sdk-js-v3/pull/5427 or https://github.com/aws/aws-sdk-js-v3/blob/main/lib/lib-dynamodb/README.md#large-numbers-and-numbervalue

**Comment by alanb-sony** [comment]
This seems an odd solution to me? We can't construct `NumberValue` from a number so we have to do `NumberValue.from(num.toString())`?

I'm still not sure what the reasoning behind restricting the range of numbers is?
