### ISSUE TITLE
Support AWS_ENDPOINT_URL

### ISSUE THREAD

**Issue by mnapoli** [aws/aws-sdk-js-v3#5364]
### Describe the feature

I would love for the JS SDK to support the new `AWS_ENDPOINT_URL` variable.

See https://aws.amazon.com/fr/blogs/developer/new-improved-flexibility-when-configuring-endpoint-urls-with-the-aws-sdks-and-tools/ and https://docs.aws.amazon.com/sdkref/latest/guide/feature-ss-endpoints.html#ss-endpoints-sdk-compat

### Use Case

Use Localstack locally.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

v3

### Environment details (OS name and version, etc.)

macOS

**Comment by RanVaknin** [comment]
Hi @mnapoli ,

This is already supported. You need to update your SDK version.

```js
import { S3Client, ListObjectsV2Command } from "@aws-sdk/client-s3";

const client = new S3Client({ region: "us-east-1" });

try {
    const response = await client.send(new ListObjectsV2Command({
        Bucket: "testbucket"
    }))
} catch (error) {
    console.log(error)
}
```

```console
$ npm list
4940@1.0.0 /Users/rvaknin/test_folder/4940
└── @aws-sdk/client-s3@3.428.0

$ AWS_ENDPOINT_URL="https://my-subdomain.s3.us-east-1.com" node sample.mjs
Error: getaddrinfo ENOTFOUND testbucket.my-subdomain.s3.us-east-1.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'testbucket.my-subdomain.s3.us-east-1.com',
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
```

Thanks,
Ran~

**Comment by tsibley** [comment]
@RanVaknin Thanks, that's great to know. It's not clear from the changelog what the first version to support this was. I tried grepping a variety of patterns to find where this functionality is implemented in the repo, but found bupkiss. Can you shed any light here? (Is it the version in your example, 3.428.0?)

**Comment by RanVaknin** [comment]
Hi @tsibley ,

The change [was introduced](https://github.com/awslabs/smithy-typescript/pull/1014) on smithy-typescript middleware package which [was made generic recently](https://github.com/aws/aws-sdk-js-v3/issues/5102). 

Thanks,
Ran~

**Comment by mnapoli** [comment]
Oh! I swear the AWS documentation listed the AWS SDK JS v3 as "No", but maybe I was just blind 😅

Sorry about the noise, that is great news!

**Comment by tsibley** [comment]
@mnapoli Yeah, me too...
