### ISSUE TITLE
SageMakerRuntime.invokeEndpointAsync ignoring InvocationTimeoutSeconds option

### ISSUE THREAD

**Issue by atrudeau-vitall** [aws/aws-sdk-js-v3#5372]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I am using @aws-sdk/client-sagemaker-runtime to invoke a sagemaker endpoint deployed with async invocation. The model I have deployed can take a long time to run, so I've set the InvocationTimeoutSeconds parameter to the maximum allowed value of 3600 seconds.

When I invoke the endpoint using `invokeEndpointAsync`, everything seems to work as expected. However after 15 minutes a timeout error is thrown.

Everything works as expected for lightweight inputs to my endpoint (i.e. inputs that take less than 15 minutes to process). Once I provide a heavier input, timeout errors are thrown.

### SDK version number

@aws-sdk/client-sagemaker-runtime@3.429.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

18.15.0

### Reproduction Steps

1. Create a sagemaker endpoint using the async invocation deployment option
  i. Easier way to recreate would be to deploy a script that waits for ~3000 seconds
2. Invoke the endpoint in a **Lambda function** (Node.js 18.x) using the following code
```ts
const sagemaker_runtime = new SageMakerRuntime({});
const response = await sagemaker_runtime.invokeEndpointAsync({
      EndpointName: endpoint_name,
      InputLocation: "s3://some_bucket/some_key",
      ContentType: content_type,
      InvocationTimeoutSeconds: 3600,
    });
```

### Observed Behavior

The invocation times out after 15 minutes, and a timeout error is thrown

### Expected Behavior

I expected the `invokeEndpointAsync` call to respect the value I provided for `InvocationTimeoutSeconds` and to not timeout after 15 minutes.

### Additional Information/Context

Further evidence of this bug is that the default [InvocationTimeoutSeconds](https://github.com/aws/aws-sdk-js-v3/blob/42dd3c5389f0a8fc6c9687499eea72b913aed643/clients/client-sagemaker-runtime/src/models/models_0.ts#L371) value is 15 minutes (or 900 seconds), which is exactly how long my endpoint is timing out after.

**Comment by atrudeau-vitall** [comment]
**Update:** InvocationTimeoutSeconds works as expected locally. When I deploy and invoke through a Lambda function it does not work. I believe this is because the [Lambda runtime](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) for Node.js 18 includes AWS SDK version 3.188.0, which doesn't contain InvocationTimeoutSeconds for invokeEndpointAsync according to the [NPM package](https://www.npmjs.com/package/@aws-sdk/client-sagemaker-runtime/v/3.188.0?activeTab=code) for that version.

For now, my workaround solution is to add @aws-sdk/sagemaker-runtime to dependencies instead of dev dependencies in package.json

**Comment by yenfryherrerafeliz** [comment]
Hi @atrudeau-vitall, you are correct. The version contained in lambda does not have the parameter "InvocationTimeoutSeconds", which can be confirmed [here](https://github.com/aws/aws-sdk-js-v3/blob/v3.188.0/clients/client-sagemaker-runtime/src/models/models_0.ts#L307). As workaround you have two options, either or to use a lambda layer, which documentation can be found [here](https://docs.aws.amazon.com/lambda/latest/dg/chapter-layers.html), or to deploy this dependency along with your code to lambda. 

You could also check the following page [here](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#w917aac19c29), for when lambda updates their runtime with a most updated version of the SDK.

I hope this helps!

Thanks!

**Comment by atrudeau-vitall** [comment]
Thanks @yenfryherrerafeliz 👍
