### ISSUE TITLE
TimestreamWriteClient sample code

### ISSUE THREAD

**Issue by ElijahYao** [aws/aws-sdk-js-v3#5379]
### Describe the issue

I have no idea if the sample code is wrong when using the newest version. 
beacause when I new a TimestreamWriteClient using code here https://github.com/awslabs/amazon-timestream-tools/tree/mainline/sample_apps/js meets a error.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/client/timestream-write/command/WriteRecordsCommand/

**Comment by RanVaknin** [comment]
Hi @ElijahYao ,

Can you tell us what the error is and share the piece of code that raises this issue?

Thanks,
Ran~
