### ISSUE TITLE
In Typescript, SQS.CreateQueueCommand requires all queue attributes due to Attributes having type Record<QueueAttributeName, string>

### ISSUE THREAD

**Issue by suchanpark-koioi** [aws/aws-sdk-js-v3#5387]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

A simple code below:

```typescript
const sqsClient = new SQSClient();
const createCommandOutput = await sqsClient.send(
  new CreateQueueCommand({
    QueueName: queueName,
    Attributes: {
      RedrivePolicy: JSON.stringify({
        maxReceiveCount: '5',
      }),
    },
  }),
);
```

gives TypeScript error as follows:

```
TS2740: Type  { RedrivePolicy: string; }  is missing the following properties from type  Record<QueueAttributeName, string> :
All, ApproximateNumberOfMessages, ApproximateNumberOfMessagesDelayed, ApproximateNumberOfMessagesNotVisible
, and  17  more.
```

### SDK version number

@aws-sdk/client-sqs@3.431.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

18.15.0

### Reproduction Steps

```typescript
import {
  CreateQueueCommand,
  SQSClient,
} from '@aws-sdk/client-sqs';

const sqsClient = new SQSClient();
const createCommandOutput = await sqsClient.send(
  new CreateQueueCommand({
    QueueName: 'anyname',
    Attributes: {
      RedrivePolicy: JSON.stringify({
        maxReceiveCount: '5',
      }),
    },
  }),
);
```

Create a typescript file with the content above and run `tsc`. Use `@aws-sdk/client-sqs` with version >=3.430.0.

### Observed Behavior

Typescript error that says as below:

```
TS2740: Type  { RedrivePolicy: string; }  is missing the following properties from type  Record<QueueAttributeName, string> :
All, ApproximateNumberOfMessages, ApproximateNumberOfMessagesDelayed, ApproximateNumberOfMessagesNotVisible
, and  17  more.
```

### Expected Behavior

This code should compile with Typescript.

Specifiying all the parameters is not required, it can be seen as, for example, here: https://docs.aws.amazon.com/cli/latest/reference/sqs/create-queue.html

This code didn't produce Typescript Error at least until 3.421.0.

### Possible Solution

Maybe change the type of `Attributes` into something like `Partial< Record<QueueAttributeName, string> >`?

### Additional Information/Context

Typescript 5.2.2

**Comment by pfumagalli** [comment]
Introduced in https://github.com/aws/aws-sdk-js-v3/pull/5356 where L1190 of `clients/client-sqs/src/models/models_0.ts` went:

```diff
-  Attributes?: Record<string, string>;
 + Attributes?: Record<QueueAttributeName, string>;
```

Pinging @kuhe who was the author...

**Comment by coderbyheart** [comment]
Similar problem in https://github.com/aws/aws-sdk-js-v3/blob/ba83d46690522a0a18094d7cd72d95724c95177b/clients/client-iot/src/models/models_2.ts#L3595

introduced via 7d312220ce4d75c55a63e8ca1b3320fdb9bf152c

`UpdateEventConfigurationsRequest.eventConfigurations` now requires all properties to be set.

**Comment by kuhe** [comment]
Sorry for the breaking change. We will adopt the suggested fix of using Partial for enum keys, to be included in the next available release day. 

As a workaround, please override the typing of the enum keyed object or use the previous SDK version for now.
