### ISSUE TITLE
New regionRedirectMiddleware does not work for the HeadObjectCommand

### ISSUE THREAD

**Issue by rachelriv** [aws/aws-sdk-js-v3#5388]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The [new middleware for following region redirects](https://github.com/aws/aws-sdk-js-v3/pull/5185) does not work for the `HeadObjectCommand`. 

### SDK version number

@aws-sdk/client-s3@3.427.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.8.0

### Reproduction Steps

```
const s3Client = new S3Client({
    region: <incorrect_region>,
    followRegionRedirects: true,
    ... 
)};
await s3.send(
    new HeadObjectCommand({
        Bucket: <bucket>,
        Key: <key>,
    }),
);
```

### Observed Behavior

A `301: UnknownError` is thrown:
```
301: UnknownError
    at throwDefaultError (.../node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at .../node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:18:39
    at de_HeadObjectCommandError (.../node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:4709:20)
```

### Expected Behavior

I'd expect the middleware to redirect to the correct region.

### Possible Solution

I suspect this is happening because the middleware [expects](https://github.com/aws/aws-sdk-js-v3/blob/ba83d46690522a0a18094d7cd72d95724c95177b/packages/middleware-sdk-s3/src/region-redirect-middleware.ts#L41) the error name to be `PermanentRedirect` *and head operations do not contain error info* [updated]. 
```
        if (
          clientConfig.followRegionRedirects &&
          err.name === "PermanentRedirect" &&
          err.$metadata.httpStatusCode === 301
        ) {
             // redirects to actual region
        }
```

**Comment by kuhe** [comment]
note to maintainers: depends on whether the operation returns the correct bucket in a response header during the error response.

**Comment by RanVaknin** [comment]
Hi @rachelriv @siddsriv ,

The reason why they see Not Found, is because a `headObject` only returns headers and _does not_ return a body. S3 uses the REST-XML wire protocol, which dictates that error messages are sent in the body. This means that head operations (`HeadObject`, `HeadBucket`...) will not contain error info. 

We will look into working around this.

Thanks,
Ran~

**Comment by siddsriv** [comment]
A fix has been posted that should resolve this issue. If something else comes up, feel free to open a new issue.
