### ISSUE TITLE
Shape not found

### ISSUE THREAD

**Issue by Swolebrain** [aws/aws-sdk-js-v3#5393]
### Describe the issue

```json
{"name":"PolicyDefinition.TemplateLinkedMember","pkg":"@aws-sdk/client-verifiedpermissions","type":"Interface","text":"TemplateLinkedMember"}
```

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-verifiedpermissions/TypeAlias/PolicyDefinition/

**Comment by kuhe** [comment]
redirect to https://github.com/aws/aws-sdk-js-v3/issues/5264 as duplicate
