### ISSUE TITLE
[client-mediaconvert] The types of 'AccelerationSettings.Mode' are incompatible between these types

### ISSUE THREAD

**Issue by juffalow** [aws/aws-sdk-js-v3#5398]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I updated to the latest version of `@aws-sdk/client-mediaconvert` (`3.431.0`) and since then I cannot build the project.

The error:

> :warning: The types of 'AccelerationSettings.Mode' are incompatible between these types.
> Type 'string' is not assignable to type 'AccelerationMode'.

The code:

```ts
// ...
const input = {
  Queue: '...',
  Role: '...',
  // ...
  AccelerationSettings: {
    Mode: 'DISABLED'
  },
};

const data = await this.mediaConvert.send(new CreateJobCommand(params));
// ...
```

All examples are using the same code and all of them are using string:
* [CreateJobCommand.ts](https://github.com/aws/aws-sdk-js-v3/blob/36836cf5d28950b49a9c6914a76f5fbb1e9741e6/clients/client-mediaconvert/src/commands/CreateJobCommand.ts#L49)
* [AWS SDK for JavaScript v3](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/mediaconvert/command/CreateJobCommand/)

And it seems that there are more problems with constants like this.

Is there any solution for this?

### SDK version number

@aws-sdk/client-mediaconvert@3.431.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.16.0

### Reproduction Steps

```ts
const input = {
  Queue: '...',
  Role: '...',
  AccelerationSettings: {
    Mode: 'DISABLED'
  },
};

const data = await this.mediaConvert.send(new CreateJobCommand(params));
```

### Observed Behavior

```
Argument of type '{ Queue: string; Role: string; Settings: { TimecodeConfig: { Source: string; }; OutputGroups: { Name: string; Outputs: unknown[]; OutputGroupSettings: { Type: string; FileGroupSettings: { Destination: string; }; }; }[]; Inputs: { ...; }[]; }; AccelerationSettings: { ...; }; StatusUpdateInterval: string; Priority: nu...' is not assignable to parameter of type 'CreateJobCommandInput'.
  The types of 'AccelerationSettings.Mode' are incompatible between these types.
    Type 'string' is not assignable to type 'AccelerationMode'.ts(2345)
```

### Expected Behavior

Should not show any error.

**Comment by juffalow** [comment]
Just found how it works without any error. As I mentioned in the issue description, it is problem with all constants. I don't know if this is intentionally or not. Working example:

```ts
import {
  MediaConvertClient,
  CreateJobCommand,
  AccelerationMode,
  OutputGroupType,
  TimecodeSource,
  AudioDefaultSelection,
  InputTimecodeSource,
  StatusUpdateInterval,
} from '@aws-sdk/client-mediaconvert';

const params = {
  Queue: '....',
  Role: '...',
  Settings: {
    TimecodeConfig: {
      Source: TimecodeSource.ZEROBASED
    },
    OutputGroups: [
      {
        Name: 'File Group',
        Outputs: [
          // ...
        ],
        OutputGroupSettings: {
          Type: OutputGroupType.FILE_GROUP_SETTINGS,
          // ...
        }
      }
    ],
    Inputs: [
      {
        AudioSelectors: {
          "Audio Selector 1": {
            DefaultSelection: AudioDefaultSelection.DEFAULT
          }
        },
        TimecodeSource: InputTimecodeSource.ZEROBASED,
        // ...
      }
    ]
  },
  AccelerationSettings: {
    Mode: AccelerationMode.DISABLED,
  },
  StatusUpdateInterval: StatusUpdateInterval.SECONDS_60,
  // ...
};

const data = await this.mediaConvert.send(new CreateJobCommand(params));
```

**Comment by yenfryherrerafeliz** [comment]
Hi @juffalow, can you please provide more details for how are building your project?, which tools are you using to do so?
In my local environment I am not able to reproduce this issue.
Here is my test code:
```js
import {CreateJobCommand, MediaConvertClient} from "@aws-sdk/client-mediaconvert";

const client = new MediaConvertClient({
    region: "us-east-2"
});
const response = await client.send(new CreateJobCommand({
    Queue: '...',
    Role: '...',
    Settings: {

    },
    AccelerationSettings: {
        Mode: "DISABLED"
    },
}))
```

Could you please also try with a test project from scratch?, because sometimes the dependencies do not get updated correctly and is needed to delete the node_modules folder and the package-lock.json/yarn.lock file, and then run npm install.

I look forward to your response.

Thanks!

**Comment by juffalow** [comment]
Hi @yenfryherrerafeliz ! Thank you for your comment. I tried it but it is still the same. What version of `typescript` do you have?
