### ISSUE TITLE
fromTemporaryCredentials() not working for govcloud?

### ISSUE THREAD

**Issue by mildmojo** [aws/aws-sdk-js-v3#5399]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I have a govcloud temporary access key ID, secret access key, and session token configured in my `~/.aws/credentials`. I'm migrating a script from AWS JS SDK V2 to V3, and I'm having trouble with `fromTemporaryCredentials()`.

In my V2 code, I started with `SharedIniCredentials` to get my on-disk credentials for the starting account, then used them to call the STS `assumeRole()` function, and fed its output into a KMS client. My understanding is that V3's `fromTemporaryCredentials()` can compose creds from an implicit assumeRole, which seems better. And as promised, I'm able to fetch temporary credentials for an assumed role pretty easily for non-govcloud accounts, using code like:

```javascript
import {
  fromIni,
  fromTemporaryCredentials
} from '@aws-sdk/credential-providers';

const creds = fromTemporaryCredentials({
  masterCredentials: fromIni({ profile: 'nongovcloud' }), // first account
  params: {
    RoleArn: 'arn:aws:iam::<second-account>:role/ServiceRole',
    RoleSessionName: 'testing'
  }
});
```

All good, I can `console.dir(await creds())` and see the temporary ID, access key, and token for the assumed role in the second account, assumed using the creds on disk for the `nongovcloud` profile in `~/.aws/credentials`.

However, in govcloud, `fromTemporaryCredentials()` throws an error: `InvalidClientTokenId: The security token included in the request is invalid`. I can separately verify with the STS SDK that an assumeRole works correctly in govcloud, but it seems to fail when it's done inside `fromTemporaryCredentials()`.

### SDK version number

@aws-sdk/credential-providers@3.429.0, @aws-sdk/client-sts@3.431.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.17.1

### Reproduction Steps

This script loads creds for one account from disk, uses them to manually `sts.assumeRole()` into a role in another account to verify that assumption works, then uses the same on-disk creds to call `fromTemporaryCredentials()` to perform the same role assumption and fetch temporary credentials for the assumed role in the second account.

1. `npm install @aws-sdk/credential-providers@3.429.0 @aws-sdk/client-sts@3.431.0`
2. Make sure you have a govcloud IAM session key/secret/token for the source account saved to a profile in `~/.aws/credentials`, as from `aws sts get-session-token`:
  ```
  $ aws configure list --profile govcloud
        Name                    Value             Type    Location
        ----                    -----             ----    --------
     profile                 govcloud           manual    --profile
  access_key     ****************5OMB shared-credentials-file
  secret_key     ****************QAKc shared-credentials-file
      region            us-gov-east-1      config-file    ~/.aws/config
  ```
4. Make sure you have an IAM role created in a second govcloud target account with a policy that allows your IAM user or role in the first account to assume it.
5. Edit the constants in the script below to provide your local govcloud profile name and the role ARN to be assumed in another govcloud account.
6. Run the script below with `node govcloud-temp-creds-test.js`:

```javascript
# govcloud-temp-creds-test.js

const {
  fromIni,
  fromTemporaryCredentials
} = require('@aws-sdk/credential-providers');
const { STS } = require('@aws-sdk/client-sts');

// This profile has ID/secret/token already configured in ~/.aws/credentials.
const STARTING_ACCT_PROFILE = 'govcloud';
// Region. Not sure why it's needed, just make sure the partition's correct.
const REGION = 'us-gov-east-1';
// Starting account will assume this role in another account.
const SERVICE_ROLE_ARN_ACCT_2 = 'arn:aws-us-gov:iam::<acct2>:role/<rolename>';

async function main() {
  const govCreds = await loadIniCredentials();
  await checkAssumeRole(govCreds);
  await loadTemporaryCredentials(govCreds);
}

async function loadIniCredentials() {
  console.log('\n*** fromIni ***\n');

  const creds = fromIni({ profile: STARTING_ACCT_PROFILE });

  console.dir(await creds());

  return creds;
}

async function checkAssumeRole(creds) {
  console.log('\n*** sts.assumeRole confidence check ***\n');

  const sts = new STS({
    apiVersion: '2011-06-15',
    credentials: creds,
    region: REGION,
  });

  // Verify assumeRole succeeds.
  const stsCreds = await sts.assumeRole({
    RoleArn: SERVICE_ROLE_ARN_ACCT_2,
    RoleSessionName: 'testing'
  });

  console.dir(stsCreds);
}

async function loadTemporaryCredentials(creds) {
  console.log('\n*** fromTemporaryCredentials ***\n');

  const tempCreds = fromTemporaryCredentials({
    masterCredentials: creds,
    params: {
      RoleArn: SERVICE_ROLE_ARN_ACCT_2,
      RoleSessionName: 'testing',
    },
  });

  console.dir(await tempCreds());
}

main();
```

### Observed Behavior

Script should output credentials from disk, credentials from `sts.assumeRole()`, and credentials from `fromTemporaryCredentials()` without error. Example running the same script with non-govcloud creds/accounts (actual output values replaced with <> placeholders):

```
$ node govcloud-temp-creds-test.js

*** fromIni ***

{
  accessKeyId: '<key ID from ~/.aws/credentials>',
  secretAccessKey: '<access key from ~/.aws/credentials>',
  sessionToken: '<token from ~/.aws/credentials>'
}

*** sts.assumeRole confidence check ***

{
  '$metadata': {
    httpStatusCode: 200,
    requestId: '<request id>',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Credentials: {
    AccessKeyId: '<temp key ID>',
    SecretAccessKey: '<temp access key>',
    SessionToken: '<temp token>',
    Expiration: 2023-10-20T22:35:44.000Z
  },
  AssumedRoleUser: {
    AssumedRoleId: '<id>:testing',
    Arn: 'arn:aws-us-gov:sts::<assumed acct>:assumed-role/<assumed role name>/testing'
  }
}

*** fromTemporaryCredentials ***

/Users/me/code/cli/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:8
    const response = new exceptionCtor({
                     ^

InvalidClientTokenId: The security token included in the request is invalid
    at throwDefaultError (/Users/me/code/cli/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at /Users/me/code/cli/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:18:39
    at de_AssumeRoleCommandError (/Users/me/code/cli/node_modules/@aws-sdk/client-sts/dist-cjs/protocols/Aws_query.js:132:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/me/code/cli/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /Users/me/code/cli/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20
    at async /Users/me/code/cli/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /Users/me/code/cli/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
    at async /Users/me/code/cli/node_modules/@aws-sdk/credential-providers/dist-cjs/fromTemporaryCredentials.js:24:33
    at async file:///Users/me/code/cli/repro2.mjs:51:13 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 403,
    requestId: '<request id>',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Type: 'Sender',
  Code: 'InvalidClientTokenId'
}

Node.js v18.17.1
```

### Expected Behavior

I expected the `fromTemporaryCredentials()` function to use my on-disk `masterCredentials` to assume the `RoleArn` I provided and return an async function that would produce temporary credentials for that assumed role. Here's an example run for the same situation in non-govcloud:

```
$ node non-govcloud-temp-creds-test.js

*** fromIni ***

{
  accessKeyId: '<key ID from ~/.aws/credentials>',
  secretAccessKey: '<access key from ~/.aws/credentials>',
  sessionToken: '<token from ~/.aws/credentials>'
}

*** sts.assumeRole confidence check***

{
  '$metadata': {
    httpStatusCode: 200,
    requestId: '<request id>',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Credentials: {
    AccessKeyId: '<temp key ID>',
    SecretAccessKey: '<temp access key>',
    SessionToken: '<temp token>',
    Expiration: 2023-10-20T22:35:44.000Z
  },
  AssumedRoleUser: {
    AssumedRoleId: '<id>:testing',
    Arn: 'arn:aws:sts::<assumed acct>:assumed-role/<assumed role name>/testing'
  }
}

*** fromTemporaryCredentials ***

{
  accessKeyId: '<temp key ID for assumed role>',
  secretAccessKey: '<temp access key for assumed role>',
  sessionToken: '<temp token for assumed role>'
  expiration: 2023-10-20T22:36:04.000Z
}
```

### Possible Workaround

I haven't tried it yet, but maybe there's a way to massage the output of `sts.assumeRole()` into the credentials format expected by the rest of the SDK. Maybe my longhand V2 approach would work in V3: load disk credentials with `fromIni()`, use them to `sts.assumeRole()` into the other account and get temp creds, use those creds for e.g. KMS.

### Additional Information/Context

In a back-to-basics attempt using non-govcloud profiles/accounts, I also tried setting env vars `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` to real, non-temporary, non-govcloud IAM user creds and loading them with `fromEnv()`. That made `sts.assumeRole()` fail with the same `InvalidClientTokenId` error. I also tried that `fromEnv()` setup with `sts.getSessionToken()`, and got an`InvalidClientTokenId` error again. That doesn't make any sense to me since the AWS CLI `aws sts get-session-token` correctly fetches a temporary ID/key/token with those env vars set to IAM user creds.

I don't think it matters, but in my case, my normal session credentials in `~/.aws/credentials` are created by `okta-awscli` for SSO authentication.

Related, I'm really struggling with the V3 generated docs, which are missing lots of useful examples. I haven't found a lot of V3 example code online, and it's frequently unclear how to turn the API documentation into actual code.

**Comment by RanVaknin** [comment]
Hi @mildmojo ,

Thanks for the in depth analysis. This is indeed an odd behavior. Unfortunately it's quite difficult for us to test gov cloud related problems as internal employee access for gov cloud requires a long approval process. 

I used the reproduction code you provided only for testing non-govcloud credentials and as expected, it works without any issues. This is really interesting because `fromTemporaryCredentials` uses the same STS client's assume role call under the hood. 

Since you do have a workaround (using the STS client directly) Im going to assign this a stand priority. 
In the meantime, some self check you can do is to add logging middleware to the request and see if the request sent via STS client directly is different from the request sent via `fromTemporaryCredentials`. 

```js
  const sts = new STS({
    apiVersion: '2011-06-15',
    credentials: creds,
    region: REGION,
  });

  sts.middlewareStack.add(next => args => {
      console.log(args.request);
      return next(args);
  }, {step: 'build'})
```

You can put a breakpoint inside of the [fromTemporaryCredentials](https://github.com/aws/aws-sdk-js-v3/blob/8a65e9f080d7490aad5b051ee6ff2c81fb80832b/packages/credential-providers/src/fromTemporaryCredentials.ts#L53) code.

I would have cross checked these two in the way the request is sent out. Im wondering if the session token is not getting piped correctly. 

I will notify you when we are able to setup a reproduction.
Thanks,
Ran~

**Comment by mildmojo** [comment]
Digging in with a debugger, I can see that `@smithy/middleware-endpoint` is returning the wrong STS endpoint when called via `fromTemporaryCredentials`. It's trying to use the non-govcloud STS endpoint, which won't work. The same code returns the correct endpoint for a manual `sts.assumeRole()` call. I also tested the barebones `STSClient` and `AssumeRoleCommand` style of invocation, which worked correctly.

Here's a debugger screenshot showing the **correct** govcloud endpoint returned for an `sts.assumeRole()` call:

![Screenshot 2023-10-25 at 4 44 04 PM](https://github.com/aws/aws-sdk-js-v3/assets/103495/d8230dab-3f5e-4e4f-9fee-887240e2acf2)

...and the **incorrect** non-govcloud endpoint during a `fromTemporaryCredentials()` call:

![Screenshot 2023-10-25 at 4 44 35 PM](https://github.com/aws/aws-sdk-js-v3/assets/103495/827a81c2-7b85-44f9-a64f-d811d04b95ad)

I haven't been able to figure out the difference between the two calls yet.

**Comment by RanVaknin** [comment]
Hi @mildmojo ,

I think what is happening is that your default region is being set from ~./aws/config (expected behavior) rather than the gov cloud region. You can try explicitly setting it on the provider:

```js
  const tempCreds = fromTemporaryCredentials({
    masterCredentials: creds,
    clientConfig:{
        region:"us-gov-east-1"
    },
    params: {
      RoleArn: SERVICE_ROLE_ARN_ACCT_2,
      RoleSessionName: 'testing',
    },
  });
```

Let me know if this solves your issue.

Thanks,
Ran~

**Comment by mildmojo** [comment]
Yup, that did it. It worked by either running the repro script with `AWS_PROFILE=govcloud` (since the `govcloud` profile had the right region) or setting the region in `clientConfig` like you show in your example.

It wasn't clear to me that `fromTemporaryCredentials()` pulls so little from its `masterCredentials`. Given that the `fromIni()` [docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-credential-providers/Variable/fromIni/) reference the `AWS_PROFILE` env var and the `~/.aws/config` file, when I provided a profile name to `fromIni()`, I expected it would load that profile (including region) and `fromTemporaryCredentials()` would inherit profile/region from those credentials rather than re-resolving them.

The `fromTemporaryCredentials()` [docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-credential-providers/Variable/fromTemporaryCredentials/) don't mention that it actually respects `AWS_PROFILE`, and there doesn't seem to be another way to give it a profile from which to extract a region. Which, I guess, follows from its use of the STS client under the hood, which also doesn't accept a profile but respects `AWS_PROFILE`.

Thanks for your help!

**Comment by mildmojo** [comment]
For future readers, it looks like the `loadSharedConfigFiles()` function from `@smithy/shared-ini-file-loader` will read both `~/.aws/credentials` and `~/.aws/config`, so I can do something like this:

```
const { fromIni, fromTemporaryCredentials } = require('@aws-sdk/credential-providers');
const { loadSharedConfigFiles } = require('@smithy/shared-ini-file-loader');

async function credentialsForRole(roleArn, startingProfile, roleSessionName) {
  const awsConfig = await loadSharedConfigFiles();

  return fromTemporaryCredentials({
    masterCredentials: fromIni({ profile: startingProfile }),
    clientConfig: {
      region: awsConfig.configFile[startingProfile].region
    },
    params: {
      RoleArn: roleArn,
      RoleSessionName: roleSessionName
    }
  });
}
```
