### ISSUE TITLE
Occasional Signature Expired errors when fetching secrets from within Lambda

### ISSUE THREAD

**Issue by kimvanrompay** [aws/aws-sdk-js-v3#5408]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

[Occasional Signature Expired errors when fetching secrets from within Lambda · Issue #4429 · aws/aws-sdk-js-v3](https://github.com/aws/aws-sdk-js-v3/issues/4429)

I'm referencing this ticket because we're facing the same problems at the moment.

Although the issue was marked as closed, it hasn't been resolved. 

Has there been a solution since March?

### SDK version number

@aws-sdk/js-v3

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

18

### Reproduction Steps

[Occasional Signature Expired errors when fetching secrets from within Lambda · Issue #4429 · aws/aws-sdk-js-v3](https://github.com/aws/aws-sdk-js-v3/issues/4429)

I'm referencing this ticket because we're facing the same problems at the moment.

Although the issue was marked as closed, it hasn't been resolved. 

Has there been a solution since March?

### Observed Behavior

[Occasional Signature Expired errors when fetching secrets from within Lambda · Issue #4429 · aws/aws-sdk-js-v3](https://github.com/aws/aws-sdk-js-v3/issues/4429)

I'm referencing this ticket because we're facing the same problems at the moment.

Although the issue was marked as closed, it hasn't been resolved. 

Has there been a solution since March?

### Expected Behavior

[Occasional Signature Expired errors when fetching secrets from within Lambda · Issue #4429 · aws/aws-sdk-js-v3](https://github.com/aws/aws-sdk-js-v3/issues/4429)

I'm referencing this ticket because we're facing the same problems at the moment.

Although the issue was marked as closed, it hasn't been resolved. 

Has there been a solution since March?

**Comment by yenfryherrerafeliz** [comment]
Related: https://github.com/aws/aws-sdk-js-v3/issues/5192

**Comment by yenfryherrerafeliz** [comment]
Hi @kimvanrompay, can you please see my comment [here](https://github.com/aws/aws-sdk-js-v3/issues/5192#issuecomment-1786322398), and confirm if you are also using provisioned concurrency with lambda?

Thanks!

**Comment by chrisclayson** [comment]
Also, experiencing this issue, and we were provisioned concurrency, which we've now disabled.

**Comment by yenfryherrerafeliz** [comment]
Hi @chrisclayson, thanks for reaching out. What about lambda runtime, were you using node 18 previously as well?
