### ISSUE TITLE
@aws-sdk/token-providers 3.433.0 depends on undeclared @aws-sdk/region-config-resolver

### ISSUE THREAD

**Issue by ankon** [aws/aws-sdk-js-v3#5409]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

We're seeing build failures in our yarn/pnp setup, because the token-providers package includes a `require("@aws-sdk/region-config-resolver")`.

From CI:
![Screenshot 2023-10-24 at 09 49 10](https://github.com/aws/aws-sdk-js-v3/assets/1210641/f88134f8-3b7b-43eb-91f8-aa4934572574)

Looking the sources I think our CI is correct: https://github.com/aws/aws-sdk-js-v3/blob/7a374640980e86f1ee70527d596b7ccb9de475f1/packages/token-providers/src/bundle/client-sso-oidc-node.ts#L234-L237

@kuhe fixed a similar recently: https://github.com/aws/aws-sdk-js-v3/issues/5362.

### SDK version number

@aws-sdk/token-providers@3.433.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node: v18.18.2   npm: 9.8.1   yarn: 3.4.1

### Reproduction Steps

Yarn pnp setup with a dependency on @aws-sdk/token-providers, try to build using esbuild.

### Observed Behavior

Build fails with message about a dependency that isn't declared (see above)

### Expected Behavior

Build works.

**Comment by kuhe** [comment]
updated to be in next release https://github.com/aws/aws-sdk-js-v3/pull/5412

**Comment by kuhe** [comment]
released in https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.435.0
