### ISSUE TITLE
EventBridge Schedule ActionAfterCompletion isn't set when using Nodejs AWS SDK v3

### ISSUE THREAD

**Issue by roshie548** [aws/aws-sdk-js-v3#5411]
### Describe the bug

EventBridge Schedule ActionAfterCompletion isn't set when using the `CreateScheduleCommand` in Nodejs AWS SDK v3.

### Expected Behavior

Schedules in the console show the "Action after completion" set to `DELETE`

### Current Behavior

Schedules in the console show the "Action after completion" set to `NONE`

### Reproduction Steps

This is the code I'm using

```
        const schedulerClient = new SchedulerClient();

        const input: CreateScheduleInput = {
          Name: newImage.Id,
          ScheduleExpression: `a(2023-12-24T05:19:31)`,
          ScheduleExpressionTimezone: "UTC",
          ActionAfterCompletion: "DELETE",
          Target: {
            Arn: process.env.SEND_SCHEDULED_MESSAGE_LAMBDA_ARN as string,
            RoleArn: process.env
              .EVENTBRIDGE_SEND_SCHEDULED_MESSAGE_ROLE_ARN as string,
            Input: JSON.stringify({
              roomId: "abc",
              scheduleId: "123",
            }),
            RetryPolicy: {
              MaximumRetryAttempts: 5,
            },
            DeadLetterConfig: {
              Arn: process.env.SCHEDULE_MESSAGE_DLQ_ARN as string,
            },
          },
          FlexibleTimeWindow: {
            Mode: FlexibleTimeWindowMode.FLEXIBLE,
            MaximumWindowInMinutes: 60,
          },
        };

        const command = new CreateScheduleCommand(input);
        const response = await schedulerClient.send(command);
```

### SDK version used

"@aws-sdk/client-scheduler": "^3.433.0"

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

x86_64 (Lambda function)

**Comment by KevinToala** [comment]
Same error.
I use the default aws sdk v3 version of aws lambda for nodejs

**Comment by yenfryherrerafeliz** [comment]
Hi @roshie548 and @KevinToala, the client-scheduler was introduced in version [v3.208.0](https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.208.0) but the SDK version embedded in lambda is in v3.188.0, which means this client should not be available there. You would need to either bundle the latest version of the SDK along with your deployment, or install the SDK in your local environment and upload the node_modules folder to lambda along with your code. Also another option would be to create a lambda layer with the latest version of the SDK, and bind it to your lambda function. [Here](https://docs.aws.amazon.com/lambda/latest/dg/chapter-layers.html) is the documentation for how to work with lambda layers.

Please let me know if that helps!

Thanks!

**Comment by roshie548** [comment]
I am bundling it with my lambda code. The client works fine, the issue is the ActionAfterCompletion field in the command doesn't work as expected.

**Comment by KevinToala** [comment]
Perfect. Thanks @yenfryherrerafeliz, including the @aws-sdk/client-scheduler dependency in the lambda code I was able to test and now it creates the scheduler in DELETE mode.
Do you know how often AWS updates the version of the aws sdk for lambda? By including the dependency in the build, the code becomes heavier than normal.

@roshie548 Remember to have the @aws-sdk/client-scheduler dependency installed in your local project and that it is not excluded in the bundling configurations


For the moment we will include it but it would be good to know when they update it in order to exclude the dependency when AWS updates the version of the AWS SDK.

```
    const nodejsFunction = new NodejsFunction(
      this,
      "CreateSchedulerHandler",
      {
        entry: "src/handler/create-scheduler.handler.ts",
        runtime: Runtime.NODEJS_18_X,
        timeout: Duration.minutes(1),
        memorySize: 1536,
        bundling: {
          minify: true,
          target: "ES2021",
          externalModules: [
            "@aws-sdk/client-s3",
            "@aws-sdk/s3-request-presigner",
            "@aws-sdk/client-ssm",
            "@aws-sdk/client-sns",
            // In my case, remove this line from here, so that @aws-sdk/client-scheduler is included in my lambda code. I am currently using version 3.438.0
            "@aws-sdk/client-scheduler",
          ],
        },
      }
    );
```

**Comment by yenfryherrerafeliz** [comment]
Hi @roshie548, please see the comment from @KevinToala. Can you please try that suggestion and confirm if solves your issue as well?

Thanks!

**Comment by yenfryherrerafeliz** [comment]
@KevinToala we do not have an ETA for when lambda will include a most updated version of the SDK, but, we are pushing for having this done as soon as possible. [Here](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#w916aac19c29) is a link that you can use for following up for when lambda updates the version. 

Thanks!

**Comment by dmeehan1968** [comment]
> Hi @roshie548 and @KevinToala, the client-scheduler was introduced in version [v3.208.0](https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.208.0) but the SDK version embedded in lambda is in v3.188.0, which means this client should not be available there. 

I just encountered this and was not needing to include the client-scheduler, it was just 'there'.  However, I too was encountering the problem of the `ActionAfterCompletion` not being set to `DELETE`.  I then included 3.441.0 in the build (I use CDK with Typescript and so specified `bundling.nodeModules` to include the scheduler, and its working as expected.

**Comment by yenfryherrerafeliz** [comment]
I will close this issue now. But please if you need further help in anything that we can help with feel free of opening a new issue.

Thanks!

**Comment by roshie548** [comment]
Sorry for the late reply. I have declared the scheduler module in my package.json:
`"@aws-sdk/client-scheduler": "^3.433.0",`.

I am using the default bundling options for `NodejsFunction` ( I haven't specified the bundling prop ). From my understanding, this should not mark any of the modules as external, which means the code should work. Am I missing anything else?
