### ISSUE TITLE
Documentation Not Complete

### ISSUE THREAD

**Issue by GITOffMuhLawn** [aws/aws-sdk-js-v3#5417]
### Describe the issue

You don't talk about what the config needs to be for CLoudFormationClient at all.  I didn't see it anywhere for the nodejs CloudFormation SDK documentation.  

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/cloudformation/command/ListStacksCommand/

**Comment by RanVaknin** [comment]
Hi @GITOffMuhLawn ,

The config input shape for the client will be in the [client doc page](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/cloudformation/), and not the operation page. 

![image](https://github.com/aws/aws-sdk-js-v3/assets/50976344/4c0e7849-a5ae-4ac7-a855-f104542aee43)

Let me know if this answers your question.

Thanks,
Ran~
