### ISSUE TITLE
DynamoDB: Performance of parallel query execution slower than sequential execution

### ISSUE THREAD

**Issue by adrai** [aws/aws-sdk-js-v3#5430]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

2 normal "GetCommand" executed in parallel much slower than executed sequentially.
Shouldn't that be faster instead of slower?
See the Reproduction Steps below.  ⬇️

### SDK version number

@aws-sdk/client-dynamodb@3.438.0, @aws-sdk/lib-dynamodb@3.438.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.18.2

### Reproduction Steps

```node.js
import { DynamoDBClient } from '@aws-sdk/client-dynamodb'
import { DynamoDBDocumentClient, GetCommand } from '@aws-sdk/lib-dynamodb'

const ddbClient = new DynamoDBClient({ region: 'eu-west-1' })
const ddbDocClient = DynamoDBDocumentClient.from(ddbClient)

const someQuery = () => {
  return ddbDocClient.send(new GetCommand({
    TableName: 'my-table',
    Key: { id: 'my-key' }
  }))
}

console.log('some init query to speed upd lambda execution for warm invokations...')
// can be done during lambda init phase
console.time('firstToInitDynamoDbConnection')
await someQuery()
console.timeEnd('firstToInitDynamoDbConnection')

console.log('normal single execution (after init optimization)...')
// can be done during lambda init phase
console.time('single')
await someQuery()
console.timeEnd('single')

// call sequential
console.log('sequential...')
console.time('sequential')
await someQuery()
await someQuery()
console.timeEnd('sequential')

// call parallel
console.log('parallel...')
console.time('parallel')
await Promise.all([
  someQuery(),
  someQuery()
])
console.timeEnd('parallel')

/* OUTPUT:
some init query to speed upd lambda execution for warm invokations...
firstToInitDynamoDbConnection: 777.097ms
normal single execution (after init optimization)...
single: 52.609ms
sequential...
sequential: 104.581ms
parallel...
parallel: 237.9ms
*/

```

### Observed Behavior

The parallel execution is way slower than the seriell execution.

### Expected Behavior

I expect the parallel execution to be faster.

### Possible Solution

Maybe there is some strange way for queuing the commands?

### Additional Information/Context

I also checked if this is related to how Node.js handles parallel http requests, but that seems to work as expected:

```node.js
import { request } from 'node:https'

const httpsRequest = () => {
  return new Promise((resolve, reject) => {
    const options = {
      host: '1.1.1.1',
      port: 443,
      path: '/',
      method: 'GET'
    }

    const req = request(options, (res) => {
      res.setEncoding('utf8')
      res.on('data', (chunk) => { })
    })

    req.on('error', reject)
    req.on('close', () => resolve())
    req.end()
  })
}

console.time('single')
await httpsRequest()
console.timeEnd('single')

// call sequential
console.log('sequential...')
console.time('sequential')
await httpsRequest()
await httpsRequest()
console.timeEnd('sequential')

// call parallel
console.log('parallel...')
console.time('parallel')
await Promise.all([
  httpsRequest(),
  httpsRequest()
])
console.timeEnd('parallel')

/* OUTPUT:
single: 109.921ms
sequential...
sequential: 148.478ms
parallel...
parallel: 83.005ms
*/
```

**Comment by RanVaknin** [comment]
Hi @adrai ,

I've tested your theory with a larger data sample (20 dynamo items, each one is named `foo0`,`foo1`, `foo2`, etc) and the parallel executions were significantly faster (3-4x faster and will likely be exponentially faster the more items are being read):


```js
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import { DynamoDBDocumentClient, GetCommand } from '@aws-sdk/lib-dynamodb'

const ddbClient = new DynamoDBClient({ region: 'eu-west-1' })
const ddbDocClient = DynamoDBDocumentClient.from(ddbClient)

const someQuery = (i) => {
    return ddbDocClient.send(new GetCommand({
      TableName: 'testGetItemTable',
      Key: { id: `foo${i}` }
    }));
};
  
// Sequential using for loop
console.time('forLoop');
  
(async () => {
    for (let i = 0; i < 20; i++) {
      await someQuery(i);
    }
    console.timeEnd('forLoop');
  })();

// Parallel using Promise.all
console.time('promiseAll');

(async () => {
  await Promise.all(
    Array.from({ length: 20 }, (_, i) => someQuery(i))
  );
  console.timeEnd('promiseAll');
})();
```

Result:

```
promiseAll: 720.417ms
forLoop: 3.530s
```

This behavior is not specific to the AWS SDK. It's a characteristic of asynchronous programming in JavaScript and Node.js. When you execute tasks sequentially using `await` inside a loop, each operation has to complete before the next one starts, resulting in a cumulative delay. On the other hand, Promise.all allows all operations to be performed in parallel, speeding up the overall execution time.

Given these findings, I'm closing this issue as the observed behavior is consistent with how Node.js handles asynchronous operations and is not specific to the SDK.

**Comment by adrai** [comment]
Your argumentation does not answer why this is faster with only 2 parallel actions:

So Node.js and the asynchronous programming in JavaScript (outside of the aws-sdk) is able to be faster, but inside the aws-sdk you can't?
There must be another reason behind this...

```js
import { request } from 'node:https'

const httpsRequest = () => {
  return new Promise((resolve, reject) => {
    const options = {
      host: '1.1.1.1',
      port: 443,
      path: '/',
      method: 'GET'
    }

    const req = request(options, (res) => {
      res.setEncoding('utf8')
      res.on('data', (chunk) => { })
    })

    req.on('error', reject)
    req.on('close', () => resolve())
    req.end()
  })
}

console.time('single')
await httpsRequest()
console.timeEnd('single')

// call sequential
console.log('sequential...')
console.time('sequential')
await httpsRequest()
await httpsRequest()
console.timeEnd('sequential')

// call parallel
console.log('parallel...')
console.time('parallel')
await Promise.all([
  httpsRequest(),
  httpsRequest()
])
console.timeEnd('parallel')

/* OUTPUT:
single: 109.921ms
sequential...
sequential: 148.478ms
parallel...
parallel: 83.005ms
*/
```

maybe @mcollina knows more about that?

**Comment by RanVaknin** [comment]
Hi @adrai ,

I'm confused by your comparison. In your example you are making a raw http request to a mock IP address. 
The AWS SDK does a lot more than just make a basic HTTP request. It handles AWS authentication, serialization/deserialization, endpoint resolution, automatic retries, and more. Each of these operations creates overhead that does not exist in your code sample so that comparison here is not accurate. 

Additionally, I ran the same code just doing two iterations and the results are still conclusive, even with 2 iterations / 2 parallel executions, promise.all is faster:

```
promiseAll: 690.759ms
forLoop: 845.893ms
```

The SDK serves as an abstraction layer, allowing users to construct their requests using a higher-level syntax. It then takes care of building, signing, and forming the HTTP request according to AWS standards. Once prepared, this request is passed to Node.js's native HTTP agent for execution, so the networking behavior you mentioned is not unique to the SDK.

Thanks,
Ran~

**Comment by adrai** [comment]
I know what you mean, but the main question still persists.
If an async action (sdk call or http request) takes a specific amount of time (i.e. 100ms), calling 2 actions in parallel should not take the double of the time (200ms) but much less...

In my example:

single execution: 52.609ms
2 sequential executions: 104.581ms (seems logical: 2x single
2 parallel executions: 237.9ms (should be between 52ms ans 104ms)

You know what I mean?

**Comment by adrai** [comment]
Seems Promise.all is the root problem:

```js
import { DynamoDBClient } from '@aws-sdk/client-dynamodb'
import { DynamoDBDocumentClient, GetCommand } from '@aws-sdk/lib-dynamodb'

const asyncAll = (funcs) => Promise.all(funcs.map((func) => typeof func === 'function' ? func() : func))

const ddbClient = new DynamoDBClient({ region: 'eu-west-1' })
const ddbDocClient = DynamoDBDocumentClient.from(ddbClient)

const someQuery = async (what, i) => {
  console.time(`${what}:${i}`)
  await ddbDocClient.send(new GetCommand({
    TableName: 'locize-dev-jobs',
    Key: { projectId: 'p', jobId: 'j' }
  }))
  console.timeEnd(`${what}:${i}`)
}

console.log('some init query to speed upd lambda execution for warm invokations...')
// can be done during lambda init phase
console.time('firstToInitDynamoDbConnection')
await someQuery('init', 0)
console.timeEnd('firstToInitDynamoDbConnection')

console.log('normal single execution (after init optimization)...')
// can be done during lambda init phase
console.time('single')
await someQuery('single', 0)
console.timeEnd('single')

const executions = 2

// call sequential
console.log(`${executions} sequential...`)
console.time('sequential')
for (let index = 0; index < executions; index++) {
  await someQuery('sequential', index + 1)
}
console.timeEnd('sequential')

// call parallel
console.log(`${executions} parallel...`)
console.time('parallel')
await Promise.all(Array.from({ length: executions }, (_, i) => someQuery('parallel', i + 1)))
console.timeEnd('parallel')

console.log(`${executions} parallel with helper...`)
console.time('parallel2')
await asyncAll(Array.from({ length: executions }, (_, i) => async () => someQuery('parallel2', i + 1)))
console.timeEnd('parallel2')

/* OUTPUT:
some init query to speed upd lambda execution for warm invokations...
init:0: 479.53ms
firstToInitDynamoDbConnection: 480.216ms
normal single execution (after init optimization)...
single:0: 47.475ms
single: 47.622ms
2 sequential...
sequential:1: 49.273ms
sequential:2: 48.216ms
sequential: 97.887ms
2 parallel...
parallel:1: 48.362ms
parallel:2: 157.331ms
parallel: 158.874ms
2 parallel with helper...
parallel2:1: 52.551ms
parallel2:2: 54.609ms
parallel2: 56.784ms
*/
```

so, we can keep this closed, not directly related to aws-sdk
