### ISSUE TITLE
`getSignedUrl` randomly generates expired URLs

### ISSUE THREAD

**Issue by cglacet** [aws/aws-sdk-js-v3#5434]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The `getSignedUrl` function randomly generates link that leads to a `Request has expired` error message page (XML).

### SDK version number

aws-sdk/s3-request-presigner@3.405.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node 20.8.1

### Reproduction Steps

Generate 20 links using this code, most likely one of them will generates an expired link:

```ts
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import checksum from '../utils/checksum';
import { BUCKET_SIGNED_URL_TTL, S3_CONFIG, UPLOAD_CONFIG } from './config';

const CONTENT_TYPE = 'application/zip';
const s3Client = new S3(S3_CONFIG) || new S3Client(S3_CONFIG);

export async function getFileUrl(
    fileName: string | null | undefined,
    expiresIn: number = BUCKET_SIGNED_URL_TTL,
    downloadFileName?: string
) {
    if (!fileName) {
        return null;
    }
    const command = new GetObjectCommand({
        Bucket: process.env.BUCKET_ID,
        Key: fileName,
        ChecksumMode: 'ENABLED',
        ResponseContentDisposition: `attachment; filename=${
            downloadFileName ?? fileName
        }`,
        ResponseContentType: CONTENT_TYPE,
    });
    return await getSignedUrl(s3Client, command, { expiresIn });
}
```

The init is the following: 

```ts
import { Options } from '@aws-sdk/lib-storage';
import { S3ClientConfig } from '@aws-sdk/client-s3';

export const BUCKET_SIGNED_URL_TTL = parseInt(
    process.env.BUCKET_SIGNED_URL_TTL
);

export const UPLOAD_CONFIG: Partial<Options> = {};
export const REGION = process.env.BUCKET_REGION.toLowerCase();
export const S3_CONFIG: S3ClientConfig = {
    credentials: {
        accessKeyId: process.env.BUCKET_ACCESS_KEY_ID,
        secretAccessKey: process.env.BUCKET_SECRET_ACCESS_KEY,
    },
    endpoint: {
        url: new URL(`https://s3.${REGION}.io.cloud.ovh.net`),
    },
    region: REGION,
};
```

### Observed Behavior

I randomly get expired links:

```xml
<Error>
<Code>AccessDenied</Code>
<Message>Request has expired</Message>
<RequestId>xxxxxxxxxx</RequestId>
</Error>
```

### Expected Behavior

All links are generated with the same TTL, they should all expire at the same time.

### Additional Information/Context

All links (including the failing ones) have similar query params, the problem is not obvious to me. The link needs to be clicked to observe the issue, otherwise it seems there is nothing wrong with the link. Only the `X-Amz-Signature` and `X-Amz-Date` differ (I guess that's expected).

**Comment by aBurmeseDev** [comment]
Hi @cglacet - thanks for reaching out. 

I wasn't able to reproduce on my end using the code below. Can you share any other details that might help me investigate further? I would also double check the URL isn't expired when it's consumed and perhaps try running the sample code I used to see if you run into any issues with it?

```ts
import {S3Client, GetObjectCommand} from "@aws-sdk/client-s3"
import {getSignedUrl} from "@aws-sdk/s3-request-presigner"

const client = new S3Client({
    region: "us-west-1" 
})
const generateSignedUrl = async (bucket, key, downloadFileName, expiresIn) => {
    const command = new GetObjectCommand({
        Bucket: bucket,
        Key: key,
        ChecksumMode: 'ENABLED',
        ResponseContentDisposition: `attachment; filename=${
            downloadFileName ?? key
        }`,
        ResponseContentType: "text/plain",
    })
    const signedUrl = await getSignedUrl(client, command, {expiresIn})
    
    return signedUrl;
}
const signedUrls = [];
for (let i = 0; i < 20; i++) {
    const signedUrl = await generateSignedUrl("bucket-name", "key", 300)
    signedUrls.push(signedUrl);
} 
for (const signedUrl of signedUrls) {
    const response = await fetch(signedUrl)
    console.log(response.status)
}
```
Hope it helps,
John

**Comment by cglacet** [comment]
Hello @aBurmeseDev thanks for your help. I was able to figure out what was going on. 

I was using minutes as expiry duration, while they are seconds. Which means all the links probably were expired but some kept working (now I know why).  Chrome is keeping some kind of cache on the download files because links that should have been expired weren't.

To reproduce the issue I had you need to: 

1. generate a signed URL,
2. click the generated link in Chrome before it expires, cancel the download,
3. click the generated link again after expiration

At step 3. you could guess the link should send a `403`, but it doesn't and you can download the file as if the link wasn't expired.

4. If you copy paste the link to another chrome window it still works,
5. if you copy paste the link to a private navigation chrome window it gets a `403` (as expected)

Does that means chrome download a file even if you click cancel? I have no idea, but it seems like it does.

Sorry for the inconvenience, no bug to be reported everything works as expected on your side. 

Cheers
