### ISSUE TITLE
S3Client `CopyObjectCommand` is inconsistent with AWS CLI v2 and AWS Console

### ISSUE THREAD

**Issue by garysassano** [aws/aws-sdk-js-v3#5443]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

1) The `CopyObjectCommand` always sets `MetadataDirective` to `COPY`, even when copying objects within the bucket.
Yet, [AWS CLI documentation](https://docs.aws.amazon.com/cli/latest/reference/s3/cp.html) says:
```
When copying between two s3 locations, the metadata-directive argument will default to 'REPLACE' unless otherwise specified.
```

2) When using `Copy` from the `Object actions` dropdown in the AWS Console, you are able to copy all metadata of an object except the `last-modified` field, which always gets updated.
Yet, the `CopyObjectCommand` copies the `last-modified` field from the source object's metadata instead of updating it.

![s3-copy-objects](https://github.com/aws/aws-sdk-js-v3/assets/10464497/064e39a1-2d01-45b8-a35f-01632d67bcfc)

I'm facing an issue where I cannot copy an object `foo.txt` from `/dir` to `/dir` (copy in-place i.e. overwrite the object) without getting the following error:
```
This copy request is illegal because it is trying to copy an object to itself without changing the object's metadata, storage class, website redirect location or encryption attributes.
```
I could set `MetadataDirective` to `REPLACE` of course, but then I would lose all my object's metadata.

I think this is effectively a bug, since you can copy in-place using the AWS Console and it updates just `last-modified` while retaining all the other metadata fields. Yet you cannot do such operation using the AWS SDK for Javascript v3 because `CopyObjectCommand` works differently.

### SDK version number

@aws-sdk/package-name@version, ...

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.16.0

### Reproduction Steps

See above.

### Observed Behavior

See above.

### Expected Behavior

See above.

### Possible Solution

Align `CopyObjectCommand` behaviour to that of AWS Console so that it copies all metadata from the source object except for the `last-modified` field, which always gets updated on copy.

**Comment by garysassano** [comment]
Alright, looking at [AWS CLI v2 documentation](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3/cp.html), I discovered that a new parameter `--copy-props` was added to address this problem. However, I couldn't find a similar feature in the `CopyObjectCommandInput` interface.

**Comment by garysassano** [comment]
I was able to implement the equivalent of the `--copy-props` parameter:

```ts
// Get properties of the source object
const headResult = await this.s3Client.send(
  new HeadObjectCommand({
    Bucket: this.bucketName,
    Key: srcKey,
  })
);

// Equivalent to `aws s3 cp --copy-props` in AWS CLI v2
const command = new CopyObjectCommand({
  Bucket: this.bucketName,
  CopySource: `${this.bucketName}/${srcKey}`,
  Key: dstKey,
  MetadataDirective: "REPLACE",
  // Properties carried over from the source object
  ContentType: headResult.ContentType,
  ContentLanguage: headResult.ContentLanguage,
  ContentEncoding: headResult.ContentEncoding,
  ContentDisposition: headResult.ContentDisposition,
  CacheControl: headResult.CacheControl,
  Expires: headResult.Expires,
  Metadata: headResult.Metadata,
});

await this.s3Client.send(command);
```

Still, I'd like to see this option added natively to the `CopyObjectCommandInput` interface so that you can use this command instead:

```ts
const command = new CopyObjectCommand({
  Bucket: this.bucketName,
  CopySource: `${this.bucketName}/${srcKey}`,
  Key: dstKey,
  CopyProps: "metadata-directive"
});
```

**Comment by garysassano** [comment]
It should be noted that even this code should work out of the box:

```ts
const command = new CopyObjectCommand({
  Bucket: this.bucketName,
  CopySource: `${this.bucketName}/${srcKey}`,
  Key: dstKey,
});
```

When `CopyProps` isn't specified, it falls back to `default` value, which is equivalent to `metadata-directive`.

However, the current behavior of `CopyObjectCommand` isn't aligned with that of AWS CLI v2 or AWS Console, resulting in the previously mentioned error when copying an object to the same path:
```
This copy request is illegal because it is trying to copy an object to itself without changing the object's metadata, storage class, website redirect location or encryption attributes.
```

**Comment by RanVaknin** [comment]
Hi @garysassano ,

Please note that in the CLI `aws s3 cp` is apart  high level s3 library. There is no equivalent to that in the SDKs. The `CopyObjectCommand` in the SDK is equivalent to the `aws s3api copy-object` command in the CLI.

What you are witnessing is ease of use customization methods provided by the CLI and console. The SDKs are more geared towards fine grained programmatic access. 

There is no plan to add this customization at this time.

Thanks,
Ran~

**Comment by garysassano** [comment]
@RanVaknin What about AWS Console though? Aren't you dogfooding your own SDK when you copy an object through that? The AWS Console retains most properties and always updates the `last-modified` date during a copy within the bucket, but it seems the SDK has taken a different approach. Why is that?

**Comment by RanVaknin** [comment]
Hi @garysassano ,

Thanks for the follow up. Thats a great question! The SDKs are all code generated from the API model of each AWS service. You can look at the internal model that the SDK uses to generate clients and operations [here](https://github.com/aws/aws-sdk-js-v3/blob/main/codegen/sdk-codegen/aws-models/s3.json). This model is owned and maintained by the S3 service team itself, so every operation here represents an upstream service supported operation that will get generated in the SDK with the correct typings. 

There are _some_ customizations introduced like the multipart uploader, but in general the SDKs are supposed to be a mirror of the API model. Since cross SDK feature requests should match in terms of implementation when we build customizations it has to be through an internal review process. The CLI (and console) essentially created a feature parity gap by adding customizations, something we want to avoid exactly for this reason. 

I hope this clears things up. 
All the best,
Ran~
