### ISSUE TITLE
Browserify bundler is not supported

### ISSUE THREAD

**Issue by jeff1evesque** [aws/aws-sdk-js-v3#5445]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

```bash
Now using node v14.21.2 (npm v6.14.17)
Updating is_local.js with desired values
Updating aws-exports.js with desired values
Notice: compiling javascript

> reactjs@1.0.0 build:browserify /path/to/pooPooCodeBase/jsx
> browserify -t [ babelify --presets [ @babel/preset-env ] ] content.jsx > content.js

Error: Can't walk dependency graph: ENOENT: no such file or directory, lstat '/path/to/pooPooCodeBase/jsx/process'
    required by /path/to/pooPooCodeBase/jsx/node_modules/@aws-sdk/client-cognito-identity-provider/node_modules/@aws-sdk/util-user-agent-node/dist-cjs/index.js
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! reactjs@1.0.0 build:browserify: `browserify -t [ babelify --presets [ @babel/preset-env ] ] content.jsx > content.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the reactjs@1.0.0 build:browserify script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jeff1evesque/.npm/_logs/2023-11-01T03_50_45_222Z-debug.log
```

### SDK version number

@aws-sdk/client-cognito-identity-provider@^3.350.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v19.8.0

### Reproduction Steps

I have the following `packages.json`:

```json
{
  "name": "reactjs",
  "version": "1.0.0",
  "description": "packages needed for source files.",
  "main": "index.js",
  "scripts": {
    "prebuild:dos2unix": "find . -type f -print0 | xargs -0 dos2unix",
    "build:browserify": "browserify -t [ babelify --presets [ @babel/preset-env ] ] content.jsx > content.js",
    "watch:jsx": "onchange '**/*.jsx' '**/*.js' -- npm run build:browserify",
    "test": "NODE_ENV=test jest --config jest.config.js",
    "report:coveralls": "cat lcov.info | ./node_modules/coveralls/bin/coveralls.js"
  },
  "author": "Jeff1evesque",
  "license": "BSD",
  "repository": "github:jeff1evesque/pooPooCodeBase",
  "dependencies": {
    "@aws-amplify/auth": "^5.6.5",
    "@aws-sdk/client-cognito-identity-provider": "^3.350.0",
    "@babel/core": "^7.22.11",
    "@babel/plugin-proposal-class-properties": "^7.18.6",
    "@babel/plugin-transform-runtime": "^7.22.10",
    "@babel/preset-env": "^7.22.10",
    "@babel/preset-react": "^7.22.5",
    "@popperjs/core": "^2.8.1",
    "@wojtekmaj/enzyme-adapter-react-17": "^0.4.1",
    "babel-jest": "^26.6.3",
    "babelify": "^10.0.0",
    "browserify": "^17.0.0",
    "coveralls": "^3.1.0",
    "d3": "^6.5.0",
    "dos2unix-cli": "^1.0.1",
    "enzyme": "^3.11.0",
    "framer-motion": "^10.16.2",
    "global": "^4.4.0",
    "history": "^5.0.0",
    "jest-cli": "^26.6.3",
    "recharts": "^2.6.2",
    "onchange": "^7.1.0",
    "promise-polyfill": "^8.2.0",
    "prop-types": "15.7.2",
    "query-string": "^6.14.0",
    "react": "^18.0.0",
    "react-bootstrap": "^2.7.2",
    "react-csv-to-table": "^0.0.4",
    "react-datepicker": "^4.8.0",
    "react-dom": "^18.0.0",
    "react-error-boundary": "^3.1.0",
    "react-gauge-chart": "^0.3.0",
    "react-json-view": "1.21.1",
    "react-papaparse": "^4.1.0",
    "react-redux": "^7.2.2",
    "react-router-dom": "^6.8.0",
    "react-modal-sheet": "^2.0.0",
    "react-tabs": "^4.2.1",
    "react-qr-code": "^2.0.12",
    "rearm": "^0.13.1",
    "redux": "^4.0.5",
    "whatwg-fetch": "^3.4.1",
    "react-device-detect": "^2.2.3",
    "@mui/material": "^5.14.7",
    "@mui/icons-material": "^5.14.9",
    "@emotion/styled": "^11.11.0",
    "@emotion/react": "^11.11.1",
    "react-alice-carousel": "^2.7.1",
    "react-spinners": "^0.13.8"
  }
}
```

### Observed Behavior

I run `npm install` no problem:

```bash
(base) jeff1evesque@computer jsx % npm install

up to date, audited 1584 packages in 3s

124 packages are looking for funding
  run `npm fund` for details

17 vulnerabilities (5 moderate, 11 high, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```

Then, I have a react/jsx template with the following import:

```javascript
import * as AWS from "@aws-sdk/client-cognito-identity-provider";
```

When I run `npm run build:browserify`, I get the following error:

```bash
(base) jeff1evesque@computer pooPooCodeBase % npm run build:browserify
Now using node v14.21.2 (npm v6.14.17)
Updating is_local.js with desired values
Updating aws-exports.js with desired values
Notice: compiling javascript

> reactjs@1.0.0 build:browserify /path/to/pooPooCodeBase/jsx
> browserify -t [ babelify --presets [ @babel/preset-env ] ] content.jsx > content.js

Error: Can't walk dependency graph: ENOENT: no such file or directory, lstat '/path/to/pooPooCodeBase/jsx/process'
    required by /path/to/pooPooCodeBase/jsx/node_modules/@aws-sdk/client-cognito-identity-provider/node_modules/@aws-sdk/util-user-agent-node/dist-cjs/index.js
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! reactjs@1.0.0 build:browserify: `browserify -t [ babelify --presets [ @babel/preset-env ] ] content.jsx > content.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the reactjs@1.0.0 build:browserify script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jeff1evesque/.npm/_logs/2023-11-02T00_56_48_364Z-debug.log
```

### Expected Behavior

I expect being able to `import` the `@aws-sdk/client-cognito-identity-provider` module.  That's my only goal at the moment.

### Additional Information/Context

```bash
(base) jeff1evesque@computer pooPooCodeBase % cat /Users/jeff1evesque/.npm/_logs/2023-11-02T00_56_48_364Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/jeff1evesque/.nvm/versions/node/v14.21.2/bin/node',
1 verbose cli   '/Users/jeff1evesque/.nvm/versions/node/v14.21.2/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:browserify'
1 verbose cli ]
2 info using npm@6.14.17
3 info using node@v14.21.2
4 verbose run-script [ 'prebuild:browserify', 'build:browserify', 'postbuild:browserify' ]
5 info lifecycle reactjs@1.0.0~prebuild:browserify: reactjs@1.0.0
6 info lifecycle reactjs@1.0.0~build:browserify: reactjs@1.0.0
7 verbose lifecycle reactjs@1.0.0~build:browserify: unsafe-perm in lifecycle true
8 verbose lifecycle reactjs@1.0.0~build:browserify: PATH: /Users/jeff1evesque/.nvm/versions/node/v14.21.2/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/jeff1evesque/application/pooPooCodeBase/jsx/node_modules/.bin:/Users/jeff1evesque/.nvm/versions/node/v14.21.2/bin:/Users/jeff1evesque/.pyenv/shims:/Users/jeff1evesque/opt/miniconda3/bin:/Users/jeff1evesque/opt/miniconda3/condabin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
9 verbose lifecycle reactjs@1.0.0~build:browserify: CWD: /Users/jeff1evesque/application/pooPooCodeBase/jsx
10 silly lifecycle reactjs@1.0.0~build:browserify: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'browserify -t [ babelify --presets [ @babel/preset-env ] ] content.jsx > content.js'
10 silly lifecycle ]
11 silly lifecycle reactjs@1.0.0~build:browserify: Returned: code: 1  signal: null
12 info lifecycle reactjs@1.0.0~build:browserify: Failed to exec build:browserify script
13 verbose stack Error: reactjs@1.0.0 build:browserify: `browserify -t [ babelify --presets [ @babel/preset-env ] ] content.jsx > content.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/jeff1evesque/.nvm/versions/node/v14.21.2/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/Users/jeff1evesque/.nvm/versions/node/v14.21.2/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1088:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
14 verbose pkgid reactjs@1.0.0
15 verbose cwd /Users/jeff1evesque/application/pooPooCodeBase/jsx
16 verbose Darwin 22.5.0
17 verbose argv "/Users/jeff1evesque/.nvm/versions/node/v14.21.2/bin/node" "/Users/jeff1evesque/.nvm/versions/node/v14.21.2/bin/npm" "run" "build:browserify"
18 verbose node v14.21.2
19 verbose npm  v6.14.17
20 error code ELIFECYCLE
21 error errno 1
22 error reactjs@1.0.0 build:browserify: `browserify -t [ babelify --presets [ @babel/preset-env ] ] content.jsx > content.js`
22 error Exit status 1
23 error Failed at the reactjs@1.0.0 build:browserify script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by RanVaknin** [comment]
Hi @jeff1evesque ,

Node 14 (and 16) are deprecated. And we have announced the end of support for Node 14.
https://github.com/aws/aws-sdk-js-v3/issues/3641
https://aws.amazon.com/blogs/developer/announcing-the-end-of-support-for-node-js-14-x-in-the-aws-sdk-for-javascript-v3/

You need to upgrade to a newer node version (preferably 18+ since those are still maintained by Node).

Thanks,
Ran~

**Comment by jeff1evesque** [comment]
My apologies. Didn’t mention that I had tried node 18 before creating this issue. Thanks!

**Comment by RanVaknin** [comment]
Hi @jeff1evesque ,

Thank you for your patience. I needed to familiarize myself a bit with the bundling tools to fully reproduce and understand the issue.

It seems like the build issue you are running into is related to how Browserify handles the `process` object, which is a part of Node.js but not naturally available in web browsers. Based on the [Browserify docs](https://github.com/browserify/browserify#compatibility), it usually provides a shim of `process` for the web, but it looks like the SDK needed more functionality than what this shim offers.

To solve this, I added a more specific shim for `process`:

```json
  "scripts": {
    "build": "browserify -r process/browser.js:process ./src/index.jsx -o ./dist/bundle.js -t [ babelify --presets [@babel/preset-env @babel/preset-react] ]"
  },
```
For me this fixed the build error. This Hopefully should let you continue developing without issues. Just keep in mind that this approach mimics Node.js behavior in the browser, so there might be some differences in how certain things work compared to a standard Node.js environment.

Let me know if this helps.
Thanks,
Ran~

**Comment by jeff1evesque** [comment]
@RanVaknin, will test this by this Friday/Saturday. Thank you very much for your assistance.

**Comment by jeff1evesque** [comment]
Just tried, and got the following trace:

```bash
(base) jeff1evesque@computer pooPooCodeBase % ./deploy --js                                              
Now using node v18.18.2 (npm v9.8.1)
Updating aws-exports.js with desired values
Notice: compiling javascript

> reactjs@1.0.0 build:browserify /Users/jeff1evesque/application/pooPooCodeBase/jsx
> browserify -r process/browser.js:process ./src/index.jsx -o ./dist/bundle.js -t [ babelify --presets [@babel/preset-env @babel/preset-react] ] content.jsx > content.js

Error: Can't walk dependency graph: Cannot find module '/Users/jeff1evesque/application/pooPooCodeBase/jsx/src/index.jsx' from '/Users/jeff1evesque/application/pooPooCodeBase/jsx/src/_fake.js'
    required by /Users/jeff1evesque/application/pooPooCodeBase/jsx/src/_fake.js
    at /Users/jeff1evesque/application/pooPooCodeBase/jsx/node_modules/resolve/lib/async.js:167:35
    at load (/Users/jeff1evesque/application/pooPooCodeBase/jsx/node_modules/resolve/lib/async.js:186:43)
    at onex (/Users/jeff1evesque/application/pooPooCodeBase/jsx/node_modules/resolve/lib/async.js:211:17)
    at /Users/jeff1evesque/application/pooPooCodeBase/jsx/node_modules/resolve/lib/async.js:24:69
    at FSReqCallback.oncomplete (fs.js:192:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! reactjs@1.0.0 build:browserify: `browserify -r process/browser.js:process ./src/index.jsx -o ./dist/bundle.js -t [ babelify --presets [@babel/preset-env @babel/preset-react] ] content.jsx > content.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the reactjs@1.0.0 build:browserify script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jeffreylevesque/.npm/_logs/2023-11-16T20_24_59_000Z-debug.log
(base) jeff1evesque@computer pooPooCodeBase % 
```

**Comment by jeff1evesque** [comment]
Just tried, and got the following trace:

```bash
(base) jeff1evesque@computer pooPooCodeBase % ./deploy --js                                                   
Now using node v18.18.2 (npm v9.8.1)
Updating is_local.js with desired values
Updating aws-exports.js with desired values
Notice: compiling javascript

> reactjs@1.0.0 build:browserify
> browserify -r process/browser.js:process -t [ babelify --presets [@babel/preset-env @babel/preset-react] ] content.jsx > content.js

(base) jeff1evesque@computer pooPooCodeBase % 
```

Looks good on that front.  However, I'm getting a new error in the browser console:

>Uncaught TypeError: fs_1.promises is undefined

<img width="1535" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/2907085/802052b8-e48c-4f66-b0c6-0c839f336ef5">

**Comment by kuhe** [comment]
It might be possible to get Browserify to bundle the SDK with a certain set of plugins and configuration hacks, but we do not support it. 

Browserify is designed to parse the CJS module format and we do not offer that format for the browser because CJS is for Node.js.

Our browser distribution is in ESM format. Using a bundler that can understand the ESM syntax of our ES distribution would be much easier. Webpack or ESBuild should work out of the box for bundling the v3 SDK.

**Comment by jeff1evesque** [comment]
How do I compile/replace my browserify command for JSX, to instead use bundler/webpack?

**Comment by kuhe** [comment]
Refer to their documentation at https://webpack.js.org/

**Comment by jeff1evesque** [comment]
@kuhe, thanks I'm not really a frontend developer.  My original objective was to get Cognito integrated with MFA.  I tried amplifyjs and had javascript issues.  Since I have AWS paid support I'll be more than happy to revert to javascript, and open a "Amplify, Javascript" case in the AWS Management Console.

**Comment by RanVaknin** [comment]
Hi @jeff1evesque ,

I think the Cognito offering from Amplify makes setting up logins a lot easier than doing the entire auth flow manually with the SDK. If I were to build a webapp that required Cognito with MFA, Amplify will be my first choice. 

Since our team does not maintain Amplify, it will be hard for us to advise you on Amplify related issues, and indeed the best address for Amplify related questions would be the Amplify team itself.

I see the support ticket you opened and can have your Technical Account manager re-route it to the Amplify team if you have no other questions for the SDK team. 

All the best,
Ran~

**Comment by jeff1evesque** [comment]
@RanVaknin, I previously successfully implemented SMS MFA with some toll-free number.  But, some standardization occurred, and I realized toll-free is limited by the country.  When I refactored to SNS MFA, I wanted to provide the option to end users to choose to select/enable MFA.  Due to some edge case (I forget the exact details), I found an online resource that stated that I could directly make an SDK requests against Cognito client (which wasn't immediately available).  Whatever the case, I did find yesterday something somewhat useful (?).  Specifically, the [aws-sdk](https://www.npmjs.com/package/aws-sdk#how-to-install) module supports browserify:

>The AWS SDK is also compatible with [browserify](http://browserify.org/).

The idea of using downloading/using the entirety of aws-sdk is not ideal, which was why I started down the path of using [aws-sdk/client-cognito-identity-provider](https://www.npmjs.com/package/@aws-sdk/client-cognito-identity-provider), since it was a smaller more focused `import`. That being said, I'm not really a web-developer. Though, I can see my coming appreciation for the frontend AWS-SDK, since I could maybe eliminate 50-90% backend code, with minimal backend asynchronous lambda functions.

**Comment by jeff1evesque** [comment]
Some final conclusions:

1.  Quick to say "code support" is not supported, though support cases has ability to tag the case "Cognito SDK", or "Amplify, Javascript".  If there is no code support then, there should not be an ability to create/open case tickets under SDK or javascript
2. I wasn't under time crunch, since I had other things I'd rather fix, so waiting 18 days in the code support for the case engineer to link me to this github issue was not a big deal.  However, it didn't really add value to the paid support experience
3. Shame support wasn't expert enough in their respective SDK/Javascript fields to be able to feel confident enough to ask exactly what I wanted to do, then make a backup/fallback plan to use [browserify supported](https://github.com/aws/aws-sdk-js-v3/issues/5445#issuecomment-1819957260) AWS-SDK
4. While I'm disappointed for above, I'm grateful for public github (free support)

**Comment by Wisenchild** [comment]
@jeff1evesque, I wonder why you're so critical of AWS Support? I have had some pleasant encounters with them overall even when some of my issues went out side of their technical domain.

And last time I checked, the aws support team is the same people that provide support on these github pages also?

Not everybody is a coder, or has extensive knowledge about packages and setting up SDKs. They're known to always do their best, so I am a bit dissapointed that you would expect perfection from another human being, and when they're not perfect respond to it so harshly.

**Comment by jeff1evesque** [comment]
@Wisenchild, congratulations on a new GitHub account, hope you didn't create it just to respond to this case.  That being said, I think it's a top-down problem. You shouldn't blame me, rather the upper AWS management for misleading AWS support to customers by providing the ability to create cases labelled as "Cognito SDK" or "Amplify, Javascript", then hiring support engineers that don't provide SDK or Javascript support within the management console.  I think some general reassessment can be done for the collective group.

**Comment by jeff1evesque** [comment]
I will be muting this issue, it no longer serves me.  If you work for AWS support, please contact me directly.

**Comment by kellertk** [comment]
> And last time I checked, the aws support team is the same people that provide support on these github pages also?

This is not actually true, but AWS is a large organization with many support teams. We're not part of the same group but we work closely together.

@jeff1evesque. I manage the internal team that provides support on GitHub (of which Ran is a member). If you feel so inclined, you may reach out directly to me at kellertk@amazon.com. I won't be able to fix this particular issue (since this isn't something the JS SDK supports right now), but I would like to hear more about your experience. I have some contacts with other support teams as well as all of the development teams for these services, so if needed I can make sure your feedback reaches the right people. Of course, if you feel that the summary you provided above is enough, that's OK too.

For everyone else, please see [this comment](https://github.com/aws/aws-sdk-js-v3/issues/5445#issuecomment-1816974075) to see why browserify is not supported.
