### ISSUE TITLE
getSignedUrl after migrating to sdk v3 is creating unsigned payload 

### ISSUE THREAD

**Issue by abhirpat** [aws/aws-sdk-js-v3#5465]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

 
 getSignedUrl after migrating to sdk v3 is creating Amz-Content-Sha256=UNSIGNED-PAYLOAD
  
  Is this a bug or by design?

### SDK version number

@aws-sdk/s3-request-presigner": "^3.418.0, @aws-sdk/client-s3": "^3.418.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node -v v18.18.0

### Reproduction Steps

Steps to reproduce 
1. Check the response for SDK V3 which is signed.

````
    const s3 = new AWS.S3();
    const signedUrl= s3.getSignedUrl('getObject', {
        Bucket: params.Bucket,
        Key: params.Key,
        Expires:300,
    });
    console.log(' url: ', signedurl);
  ````
  
  2. Migrate to SDK V3 per guide https://aws.amazon.com/blogs/developer/generate-presigned-url-modular-aws-sdk-javascript/. Check the response and you will notice that the url has "Amz-Content-Sha256=UNSIGNED-PAYLOAD" which is inconsistent with behavior of SDK V2. 
  
  ````
     const s3 = new S3Client({ region });
    const S3Command = new GetObjectCommand({
        Bucket: params.Bucket,
        Key: params.Key
    })
    const signedUrl = await getSignedUrl(s3, S3Command , {
        expiresIn: 300
    });
    console.log('url: ', signedurl)
  
  ````
  

### Observed Behavior

You will see Amz-Content-Sha256=UNSIGNED-PAYLOAD in signed url

### Expected Behavior

You wouldn't see unsigned payload in SDK V2

**Comment by RanVaknin** [comment]
Hi @abhirpat,

The v3 SDK uses [sigv4](https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html) signing scheme by default. Is it possible that you are generating an older version of presigned URL in your v2 app?

This is the intended behavior since you are pre-signing a getObjectCommand which does not have a body.

Thanks,
Ran~
