### ISSUE TITLE
@aws-sdk/client-ses README.md contains link to page without instructions for SendEmailCommand

### ISSUE THREAD

**Issue by projournal** [aws/aws-sdk-js-v3#5467]
### Describe the issue

**Package:** @aws-sdk/client-ses - version 3.445.0 (latest version)
README.md that comes with package contains link to API reference that contains no mention of **SendEmailCommand** and instead gives instructions for **SendEmail**.  This is backwards because the package contains **SendEmailCommand** and not **SendEmail**.  Furthermore **SendEmailCommand** appears to be deprecated and can't be blocked with a User/Group policy on AWS.  There doesn't appear to be any way around this.  **SendEmail** can be blocked with a User/Group policy but isn't in the latest package.

### Links

Link from latest README.md to API reference.
[https://docs.aws.amazon.com/ses/latest/APIReference/API_Operations.html](https://docs.aws.amazon.com/ses/latest/APIReference/API_Operations.html)

Link to deprecated instructions for **SendEmailCommand**.
[https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-ses/classes/sendemailcommand.html](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-ses/classes/sendemailcommand.html)

Link to still active instructions for **SendEmailCommand**.
[https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-ses/Class/SendEmailCommand/](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-ses/Class/SendEmailCommand/)

**Comment by aBurmeseDev** [comment]
Hi @projournal - thanks for reaching out. 

If I understand correctly, you're referring to SES method [SendEmail](https://docs.aws.amazon.com/ses/latest/APIReference/API_SendEmail.html) which is available as [SendEmailCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-ses/classes/sendemailcommand.html) in aws-sdk-js-v3.

>Link to deprecated instructions for SendEmailCommand.
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-ses/classes/sendemailcommand.html

The deprecated instructions banner you see is for the API documentation itself and not for the command. It was a preview API doc before we announced our current docs which is here: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/ses/command/SendEmailCommand/

I totally understand the confusion in those documentations and we're actively listening to our customer feedbacks for improvements.

As far as the confusion between `SendEmail` and `SendEmailCommand`, every client operation name in v3 gets added "Command" as you can see here: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/ses/

However, you can still use non-modular interface like how it was in v2 by importing the service name and call the operation name directly from the client:
```ts
const { SES } = require("@aws-sdk/client-client-ses");

(async () => {
  const client = new SES({ region: "us-west-2" });
  try {
    const response = await client.sendEmail({});
    console.log(response);
  } 
})();
```
and here's the interface in v3:
```ts
const { SESClient, SendEmailCommand } = require("@aws-sdk/client-ses");

(async () => {
  const client = new SESClient({ region: "us-west-2" });
  const command = new SendEmailCommand({input});
  try {
    const response = await client.send(command);
})();
```

Hope that helps,
John
