### ISSUE TITLE
CredentialsProviderError: Could not load credentials from any providers

### ISSUE THREAD

**Issue by tedyu** [aws/aws-sdk-js-v3#5482]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

We are upgrading `client-s3` from v2 to v3.
Previously our unit test stubbing code eludes the need to specify region or credential.

But with v3, we see the following error:
```
     RequestTimeTooSkewed: The difference between the request time and the current time is too large.
      at throwDefaultError (node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:8:22)
      at /opt/app/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:18:39
      at de_PutObjectCommandError (node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:5721:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /opt/app/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
      at async /opt/app/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20
      at async /opt/app/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46
      at async /opt/app/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:63:20
      at async /opt/app/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-endpoint-middleware.js:14:24
      at async /opt/app/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-middleware.js:9:20
      at async /opt/app/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
```
I haven't found out where the `PutObjectCommand` was initiated (maybe from within the middleware).

### SDK version number

@aws-sdk/client-s3@3

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node.js 18

### Reproduction Steps

```
  before(() => {
    sinon.stub(EnvHelper, 'decryptVariable').resolves(true);
  });

  after(() => {
    EnvHelper.decryptVariable.restore();
  }

  beforeEach(() => {
    stubs.get = sinon.stub(InternalRequest, 'get');
    stubs.put = sinon.stub(InternalRequest, 'put');
    stubs.dateString = sinon.stub(Date.prototype, 'toISOString').returns(nowStr);
    stubs.s3 = {
      send: sinon.stub(),
      getSignedUrl: sinon.stub(),
      promise: sinon.stub(),
    };
    stubs.s3.send.returns(stubs.s3);
    stubs.s3.getSignedUrl.returns('foourl');
    stubs.s3.promise.resolves({});
```
Before each test runs, the `RequestTimeTooSkewed` happens.

### Observed Behavior

```
     RequestTimeTooSkewed: The difference between the request time and the current time is too large.
      at throwDefaultError (node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:8:22)
      at /opt/app/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:18:39
```
See description for full stack trace.

### Expected Behavior

aws client v3 should continue to function in similar way to v2 client.

**Comment by cpyle0819** [comment]
The `RequestTimeTooSkewed` error suggests the PutObjectCommand request was created with a timestamp that doesn't match the real time. It looks like you're stubbing the native Date prototype. That could be causing the mismatch.

**Comment by tedyu** [comment]
Here was another error related to credentials:
```
 6) stale bulks
       should handle bulk not found in redrive:
     CredentialsProviderError: Could not load credentials from any providers
      at /opt/app/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js:13:11
      at /opt/app/node_modules/@smithy/property-provider/dist-cjs/chain.js:12:39
```
My question is: what action is needed to avoid providing credential in the tests (seems to be unique to client v3) ?

Thanks

**Comment by cpyle0819** [comment]
What are you trying to mock? If you don’t want to provide credentials, you should be mocking the client in its entirety. V2 to v3 is a major version change, and breaking changes are expected. It’s not meant to be a drop-in replacement. You can find some more info on migrating here:
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/migrating/notable-changes/

https://github.com/awslabs/aws-sdk-js-codemod


From: Zhihong Yu ***@***.***>
Reply-To: aws/aws-sdk-js-v3 ***@***.***>
Date: Monday, November 13, 2023 at 9:43 AM
To: aws/aws-sdk-js-v3 ***@***.***>
Cc: "Pyle, Corey" ***@***.***>, Comment ***@***.***>
Subject: Re: [aws/aws-sdk-js-v3] RequestTimeTooSkewed: The difference between the request time and the current time is too large (Issue #5482)


Here was another error related to credentials:

 6) stale bulks

       should handle bulk not found in redrive:

     CredentialsProviderError: Could not load credentials from any providers

      at ***@***.***/credential-provider-node/dist-cjs/defaultProvider.js:13:11

      at ***@***.***/property-provider/dist-cjs/chain.js:12:39

My question is: what action is needed to avoid providing credential in the tests (seems to be unique to client v3) ?

Thanks
