### ISSUE TITLE
GetImagesCommand does not return Images

### ISSUE THREAD

**Issue by realoldnerd** [aws/aws-sdk-js-v3#5485]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Very basic code that uses the code on the [API documentation page](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/kinesis-video-archived-media/command/GetImagesCommand/) does not return any images, despite validating that the stream contains images in the timeframe specified. It only returns an http 200 in the metadata.
This has been discussed on [StackOverflow](https://stackoverflow.com/questions/72426529/lack-of-images-property-in-response-from-kinesis-video-streams-getimages-retri) without an answer. 

### SDK version number

"@aws-sdk/client-kinesis-video-archived-media": "^3.449.0"

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.17.0

### Reproduction Steps
```js
import { KinesisVideoArchivedMediaClient, 
  GetImagesCommand,
  GetImagesCommandInput,
} from "@aws-sdk/client-kinesis-video-archived-media";

const startTime = new Date(1699882502000);
const endTime = new Date(1699882509000);

 const client = new KinesisVideoArchivedMediaClient({"region": "us-east-1"});
 const input: GetImagesCommandInput = {
   StreamARN: "<my-stream-arn>",
   ImageSelectorType: "SERVER_TIMESTAMP",
   StartTimestamp: startTime, // required
   EndTimestamp: endTime, // required
   SamplingInterval: Number(500),
   Format: "PNG", // required
 };
 const command = new GetImagesCommand(input);

client.send(command).then(
  (data) => {
    console.log(JSON.stringify(data));
  },
  (error) => {
    console.log("Error encountered");
  }
);
```
### Observed Behavior
```
Output: {
  '$metadata': {
    httpStatusCode: 200,
    requestId: '119b4f57-27a3-42f3-b492-3d80b0f42f41',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}
```
### Expected Behavior

Expect Image resources to be attached

### Possible Solution

Use the StockOverflow solution, utilizing V2:
https://stackoverflow.com/questions/72426529/lack-of-images-property-in-response-from-kinesis-video-streams-getimages-retri

**Comment by aBurmeseDev** [comment]
Hi @realoldnerd - thanks for reaching out. I came across this similar [issue](https://github.com/aws/aws-sdk/issues/293) submission and other SDK member [mentioned](https://github.com/aws/aws-sdk/issues/293#issuecomment-1183530707) that you must first call [`GetDataPoint`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/client/kinesis-video/command/GetDataEndpointCommand/) with [@aws-sdk/client-kinesis-video](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/Package/-aws-sdk-client-kinesis-video) client and use that endpoint to call `GetImagesCommand`.

I reached out to service team and was able to confirm that. I understand that the documentation needs to be updated to address these and I'll plan to follow up with them in the near future. 

If the issue persists, please let me know and I'd be happy to investigate further.
Best,
John

**Comment by aBurmeseDev** [comment]
Appreciate you for sharing the working code and I'm happy to know that your workflow is unblocked now.  Please feel free to reach out again if you have any other JavaScript SDK related questions!
