### ISSUE TITLE
Cannot get final name for export 'EndpointURLScheme'

### ISSUE THREAD

**Issue by yannxaver** [aws/aws-sdk-js-v3#5488]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

```shell
next build
   ▲ Next.js 14.0.2
   - Environments: .env
   - Experiments (use at your own risk):
     · typedRoutes

Failed to compile.

./node_modules/@aws-sdk/util-endpoints/node_modules/@smithy/util-endpoints/dist-es/utils/index.js + 72 modules
Cannot get final name for export 'EndpointURLScheme' of ./node_modules/@aws-sdk/util-endpoints/node_modules/@smithy/util-endpoints/node_modules/@smithy/types/dist-es/index.js


> Build failed because of webpack errors
   Creating an optimized production build  .error: script "build" exited with code 1 (SIGHUP)
```

### SDK version number

@aws-sdk/client-s3@3.450.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.16.0

### Reproduction Steps

```shell
npx next build
```

### Observed Behavior

See above

### Expected Behavior

No build error

### Possible Solution

The error disappears when downgrading to `3.445.0`

**Comment by yektas** [comment]
I got a similar type of error with Next `14.0.2`. 
## Using;
```
@aws-sdk/client-s3@3.450.0
@aws-sdk/s3-request-presigner@3.450.0
```

## Error
```
Failed to compile.

../../node_modules/@aws-sdk/s3-request-presigner/dist-es/index.js + 71 modules
Cannot get final name for export 'serializerMiddlewareOption' of ../../node_modules/@smithy/middleware-serde/dist-es/index.js


> Build failed because of webpack errors
```

**Comment by RanVaknin** [comment]
Hi @yektas , @yannxaver ,

Unfortunately Im not able to reproduce this issue. Here is what I've tried:

```console
$ npx create-next-app 5488-b
$ npm i @aws-sdk/client-s3 @aws-sdk/s3-request-presigner
$ touch pages/api/s3.js
```

In my s3.js file I have some sample code using the SDK:

```js
import { S3Client, GetObjectCommand } from "@aws-sdk/client-s3";
import { getSignedUrl } from '@aws-sdk/s3-request-presigner'

const s3Client = new S3Client({ region: "us-east-1" });


export default async function handler(req, res) {
    try {

        const command = new GetObjectCommand({
            Bucket: "foo-bucket",
            Key: "hey.txt"
        });
        const presignedUrl = await getSignedUrl(s3Client, command, { expiresIn: 3600 });
        res.status(200).json({ message: "created presigned URL successfully!", url: presignedUrl});
    } catch (error) {
        console.error(error);
        res.status(500).json({ error: "Error! could not create presigned URL" });
    }
}
```

I can both build and run it successfully:

```console
$ $ npx next build        
 ✓ Linting and checking validity of types    
   ▲ Next.js 14.0.3

 ✓ Creating an optimized production build    
 ✓ Compiled successfully
 ✓ Collecting page data    
 ✓ Generating static pages (3/3) 
 ✓ Collecting build traces    
 ✓ Finalizing page optimization    

Route (pages)                              Size     First Load JS
┌ ○ /                                      4.83 kB        82.8 kB
├   └ css/f7bac67f9d9badbc.css             654 B
├   /_app                                  0 B              78 kB
├ ○ /404                                   182 B          78.2 kB
├ λ /api/foo                               0 B              78 kB
├ λ /api/hello                             0 B              78 kB
└ λ /api/s3                                0 B              78 kB
+ First Load JS shared by all              78.2 kB
  ├ chunks/framework-04b2df298aee5fa5.js   45.2 kB
  ├ chunks/main-bac2f07e2c919777.js        31.7 kB
  ├ chunks/pages/_app-1b08a80b16427f14.js  285 B
  ├ chunks/webpack-8fa1640cc84ba8fe.js     750 B
  └ css/27d177a30947857b.css               194 B

○  (Static)   prerendered as static content
λ  (Dynamic)  server-rendered on demand using Node.js
```

Admittedly I've never used Next before, so I might be overlooking something more obvious. In order to reproduce your specific issue, I would appreciate if one of you either created a minimal github repository that can consistently reproduce the issue / include more in-depth reproduction steps. 

Thanks,
Ran~

**Comment by yannxaver** [comment]
After upgrading to `3.454.0` the error disappeared for me. I'm on next `14.0.3`.

**Comment by RanVaknin** [comment]
glad to hear it. 

Thanks again for reaching out.
All the best,
Ran~

**Comment by RedGlow** [comment]
I'm having the very same problem. A reproduction repo is https://github.com/RedGlow/game-assets-explorer.git at hash 702780038babefb84572fb18258e0ba717789d5a.
Using NodeJS v20.10.0, npm 9.2.0, Next.JS v. 14.0.3, @aws-sdk/client-s3 3.468.0.

```
PS D:\Downloads> git clone https://github.com/RedGlow/game-assets-explorer.git
Cloning into 'game-assets-explorer'...
remote: Enumerating objects: 632, done.
remote: Counting objects: 100% (632/632), done.
remote: Compressing objects: 100% (327/327), done.
Receiving objects:  97% (614/632)used 555 (delta 270), pack-reused 0
Receiving objects: 100% (632/632), 267.14 KiB | 3.34 MiB/s, done.
Resolving deltas: 100% (347/347), done.
PS D:\Downloads> cd .\game-assets-explorer\
PS D:\Downloads\game-assets-explorer> git checkout 702780038babefb84572fb18258e0ba717789d5a
Note: switching to '702780038babefb84572fb18258e0ba717789d5a'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 7027800 chore: s3 update.
PS D:\Downloads\game-assets-explorer> npm install
npm WARN deprecated gulp-header@1.8.12: Removed event-stream from gulp-header
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)

> gameassets@0.1.0 postinstall
> prisma generate

Prisma schema loaded from prisma\schema.prisma

✔ Generated Prisma Client (v5.6.0) to .\node_modules\@prisma\client in 33ms

Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
```
import { PrismaClient } from '@prisma/client/edge'
const prisma = new PrismaClient()
```

See other ways of importing Prisma Client: http://pris.ly/d/importing-client

┌─────────────────────────────────────────────────────────┐
│  Update available 5.6.0 -> 5.7.0                        │
│  Run the following to update                            │
│    npm i --save-dev prisma@latest                       │
│    npm i @prisma/client@latest                          │
└─────────────────────────────────────────────────────────┘

added 881 packages, and audited 882 packages in 3m

275 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS D:\Downloads\game-assets-explorer> npm run build

> gameassets@0.1.0 build
> next build

   ▲ Next.js 14.0.3

Failed to compile.

./node_modules/@aws-sdk/s3-request-presigner/dist-es/index.js + 115 modules
Cannot get final name for export 'serializerMiddlewareOption' of ./node_modules/@smithy/middleware-serde/dist-es/index.js


> Build failed because of webpack errors
   Creating an optimized production build  .
```

**Comment by RedGlow** [comment]
(paging @RanVaknin just to be sure, because I don't know if you get the notification automatically on a closed report)

**Comment by yektas** [comment]
> I got a similar type of error with Next `14.0.2`.
> 
> ## Using;
> ```
> @aws-sdk/client-s3@3.450.0
> @aws-sdk/s3-request-presigner@3.450.0
> ```
> 
> ## Error
> ```
> Failed to compile.
> 
> ../../node_modules/@aws-sdk/s3-request-presigner/dist-es/index.js + 71 modules
> Cannot get final name for export 'serializerMiddlewareOption' of ../../node_modules/@smithy/middleware-serde/dist-es/index.js
> 
> 
> > Build failed because of webpack errors
> ```

I had a custom NODE_ENV variable set to "development"; setting it to "production" fixed the build issue for me.

**Comment by RedGlow** [comment]
> > I got a similar type of error with Next `14.0.2`.
> > ## Using;
> > ```
> > @aws-sdk/client-s3@3.450.0
> > @aws-sdk/s3-request-presigner@3.450.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Error
> > ```
> > Failed to compile.
> > 
> > ../../node_modules/@aws-sdk/s3-request-presigner/dist-es/index.js + 71 modules
> > Cannot get final name for export 'serializerMiddlewareOption' of ../../node_modules/@smithy/middleware-serde/dist-es/index.js
> > 
> > 
> > > Build failed because of webpack errors
> > ```
> 
> I had a custom `NODE_ENV` variable set to `development`; setting it to `production` fixed the build issue for me.

in .env / .env.local? Sadly, this is not my case, no such NODE_ENV variable.

**Comment by matheuschimelli** [comment]
Hello. First, i know the issue is closed.

I know the issue is closed, but I'm getting the same error. I have tried everything, but nothing worked.

**Comment by matheuschimelli** [comment]
I fixed the error.

# TLDR
Just put your functions in separated files. Make sure to do not use more than one different aws service in the same file.

# Possible fix
For everyone who is suffering a lot, trying to find where the error is coming from, here go my tips:

1. As @RedGlow commented, the problem is with webpack. I was getting the error because i was using one file with many exports of many aws functions. Don't do that.

> After some more investigation, it turned out the culprit were _other_, unrelated missing imports that weren't used in my tests on the dev build, but which got used during the final build, and that somehow caused this error to pop up. No idea exactly what the connection between these errors should be, but now I'm thinking it's more of a problem of webpack rather than aws-sdk? maybe?
> 
> For those looking at this in the future, the commit that solved the problem in my case was this one: [RedGlow/game-assets-explorer@5ec427e](https://github.com/RedGlow/game-assets-explorer/commit/5ec427e93faafe112eeab8d433f96b4167868d23)
> 
> BTW, the info that put me in the right direction (getting to check the barrel files) was this one: [webpack/webpack#5095 (comment)](https://github.com/webpack/webpack/issues/5095#issuecomment-317659298)

2. Instead of grouping functions in only one file, divide them in a folder. Example: I'm building a upload system. So this is how my dir looks right now:
```text
lib
- modules (folder)
- - - aws-services (folder)
- - - - s3 (folder)
- - - - - s3-client.ts
- - - - - s3-generate-upload-url.ts
- - - - - s3-get-file.ts
- - - - - s3-service.ts
```

3. Ensure you are not using the `import { getSignedUrl } from "@aws-sdk/s3-request-presigner";` in the same file with other aws functions, neither the `import { getSignedUrl } from "@aws-sdk/s3-request-presigner";`import. For each of them, put the functions in different files.

**Comment by mattinannt** [comment]
I had a slightly different problem:
```
web:build: ../../node_modules/@aws-sdk/s3-request-presigner/dist-es/index.js + 115 modules
web:build: Cannot get final name for export 'serializerMiddlewareOption' of ../../node_modules/@smithy/middleware-serde/dist-es/index.js
```
and for me this advice ( https://github.com/aws/aws-sdk-js-v3/issues/5540#issuecomment-1849103151 ) for the `next.config.js` did the trick:

```
experimental: {
  serverComponentsExternalPackages: ['@aws-sdk'],
},
```
