### ISSUE TITLE
DeleteIntent not working after migrating to SDK V3 

### ISSUE THREAD

**Issue by abhirpat** [aws/aws-sdk-js-v3#5489]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

DeleteIntent not working after migrating to SDK V3. It appears that it cannot take ARN anymore as it used to in SDK V2.
Error 

```
   const exception = new models_0_1.BadRequestException({
                      ^

BadRequestException: RelativeId does not match Lex ARN format: intent:arn:aws:cloudformation:us-west-2:<account>:stack/<stack>-ExamplesStack-RMQBVNLIG5QF/ffdebe80-830f-11ee-a9ad-0a0be9b66dc9/YesNoExitIntent/c8b5977d-87ca-4ff7-8a2e-30cc49b2593d:*
    at de_BadRequestExceptionRes (/Users/abhirpat/Documents/Scripts/Node/node_modules/@aws-sdk/client-lex-model-building-service/dist-cjs/protocols/Aws_restJson1.js:2967:23)
    at de_DeleteIntentCommandError (/Users/abhirpat/Documents/Scripts/Node/node_modules/@aws-sdk/client-lex-model-building-service/dist-cjs/protocols/Aws_restJson1.js:1304:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/abhirpat/Documents/Scripts/Node/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /Users/abhirpat/Documents/Scripts/Node/node_modules/@aws-sdk/client-lex-model-building-service/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20
    at async /Users/abhirpat/Documents/Scripts/Node/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /Users/abhirpat/Documents/Scripts/Node/node_modules/@aws-sdk/client-lex-model-building-service/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
    at async run (/Users/abhirpat/Documents/Scripts/Node/lexmodelservice.js:131:22) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: '942f4d97-4a02-4402-90d4-0cbdf1e420b0',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}
```

### SDK version number

@aws-sdk/client-lex-model-building-service

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node 18.18

### Reproduction Steps

Try to delete Intent, it works always in SDK V2 but fails with SDK V2. The input parameter is name

### Observed Behavior

Fails with SDK V3

params: {
    name: 'arn:aws:cloudformation:us-west-2:<account>:stack/<stack>-ExamplesStack-RMQBVNLIG5QF/ffdebe80-830f-11ee-a9ad-0a0be9b66dc9/YesNoExitIntent/c8b5977d-87ca-4ff7-8a2e-30cc49b2593d'
  }

### Expected Behavior

It should work with SDK V3 since it's working with V2. Also, the error should be easy to understand because here it is not clear what developer needs to do incase RelativeId doesn't match.

### Possible Solution

I have tried to use name of intent but that doesn't work either. It says doesn't exist but exists as I can confirm. Could you improve documentation to include example if this is working?

NotFoundException: The specified resource 'PizzaIntent' does not exist. Choose another resource.
    at de_NotFoundExceptionRes (/Users/abhirpat/Documents/Scripts/Node/node_modules/@aws-sdk/client-lex-model-building-service/dist-cjs/protocols/Aws_restJson1.js:3021:23)
    at de_DeleteIntentCommandError (/Users/abhirpat/Documents/Scripts/Node/node_modules/@aws-sdk/client-lex-model-building-service/dist-cjs/protocols/Aws_restJson1.js:1316:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/abhirpat/Documents/Scripts/Node/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /Users/abhirpat/Documents/Scripts/Node/node_modules/@aws-sdk/client-lex-model-building-service/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20
    at async /Users/abhirpat/Documents/Scripts/Node/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /Users/abhirpat/Documents/Scripts/Node/node_modules/@aws-sdk/client-lex-model-building-service/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
    at async run (/Users/abhirpat/Documents/Scripts/Node/lexmodelservice.js:136:22) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 404,
    requestId: 'd6789cd9-2259-4214-a585-84fd8635e9a7',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }

**Comment by RanVaknin** [comment]
Hi @abhirpat ,

Thanks for opening the issue. Im a bit confused about what worked here. You mentioned `DeleteIntent` used to work with ARN instead of a name? However DeleteIntent takes neither ARN nor name argument it takes the Intent ID. 

Additionally the ARN you are passing is for a Cloudformation construct, and not the intent itself. From what I can tell intents themselves do not have ARNs. This can be visible by describing one of the intents:

```console
$ aws lexv2-models describe-intent --intent-id WU45H0VHU1 --bot-id REDACTED --bot-version 1 --locale-id en_US
{
    "intentId": "WU45H0VHU1",
    "intentName": "BookHotel",
    "description": "Intent to book a hotel on StayBooker",
    "sampleUtterances": [
        {
            "utterance": "Book a hotel"
        },
        {
            "utterance": "I want a make hotel reservations"
        },
        {
            "utterance": "Book a {Nights} night stay in {Location}"
        },
        {
            "utterance": "find a hotel"
        },
        {
            "utterance": "hotel"
        }
    ],
    "slotPriorities": [
        {
            "priority": 1,
            "slotId": "EOYQB5C3WC"
        },
        {
            "priority": 2,
            "slotId": "JBRJPKCLHD"
        },
        {
            "priority": 3,
            "slotId": "DJVFFRZODJ"
        },
        {
            "priority": 4,
            "slotId": "KHBBDSNPCJ"
        }
    ],
    "intentConfirmationSetting": {
        "promptSpecification": {
            "messageGroups": [
                {
                    "message": {
                        "plainTextMessage": {
                            "value": "Okay, I have you down for a {Nights} night stay in {Location} starting {CheckInDate}.  Shall I book the reservation?"
                        }
                    }
                }
            ],
            "maxRetries": 2,
            "allowInterrupt": true,
            "messageSelectionStrategy": "Random",
            "promptAttemptsSpecification": {
                "Initial": {
                    "allowInterrupt": true,
                    "allowedInputTypes": {
                        "allowAudioInput": true,
                        "allowDTMFInput": true
                    },
                    "audioAndDTMFInputSpecification": {
                        "startTimeoutMs": 4000,
                        "audioSpecification": {
                            "maxLengthMs": 15000,
                            "endTimeoutMs": 640
                        },
                        "dtmfSpecification": {
                            "maxLength": 513,
                            "endTimeoutMs": 5000,
                            "deletionCharacter": "*",
                            "endCharacter": "#"
                        }
                    },
                    "textInputSpecification": {
                        "startTimeoutMs": 30000
                    }
                },
                "Retry1": {
                    "allowInterrupt": true,
                    "allowedInputTypes": {
                        "allowAudioInput": true,
                        "allowDTMFInput": true
                    },
                    "audioAndDTMFInputSpecification": {
                        "startTimeoutMs": 4000,
                        "audioSpecification": {
                            "maxLengthMs": 15000,
                            "endTimeoutMs": 640
                        },
                        "dtmfSpecification": {
                            "maxLength": 513,
                            "endTimeoutMs": 5000,
                            "deletionCharacter": "*",
                            "endCharacter": "#"
                        }
                    },
                    "textInputSpecification": {
                        "startTimeoutMs": 30000
                    }
                },
                "Retry2": {
                    "allowInterrupt": true,
                    "allowedInputTypes": {
                        "allowAudioInput": true,
                        "allowDTMFInput": true
                    },
                    "audioAndDTMFInputSpecification": {
                        "startTimeoutMs": 4000,
                        "audioSpecification": {
                            "maxLengthMs": 15000,
                            "endTimeoutMs": 640
                        },
                        "dtmfSpecification": {
                            "maxLength": 513,
                            "endTimeoutMs": 5000,
                            "deletionCharacter": "*",
                            "endCharacter": "#"
                        }
                    },
                    "textInputSpecification": {
                        "startTimeoutMs": 30000
                    }
                }
            }
        },
        "declinationResponse": {
            "messageGroups": [
                {
                    "message": {
                        "plainTextMessage": {
                            "value": "Okay, I have cancelled your reservation in progress."
                        }
                    }
                }
            ],
            "allowInterrupt": true
        },
        "active": true
    },
    "botId": "REDACTED",
    "botVersion": "1",
    "localeId": "en_US",
    "creationDateTime": "2022-08-15T08:58:01.953000-07:00",
    "lastUpdatedDateTime": "2022-08-15T08:59:16.211000-07:00"
}
```

In order to better help you please include the code that is failing. That will give us a better idea of what might be going wrong. 
Additionally if this was working in v2, supplying the v2 sample code that is succeeding will be also helpful.

Thanks again,
Ran~
