### ISSUE TITLE
Invalid https certificate if bucket name contains "." like bucket.example

### ISSUE THREAD

**Issue by pidge-raman** [aws/aws-sdk-js-v3#5490]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

In V2 the url format is 
```
https://s3.{region}.amazonaws.com/{bucket-name}/{file-path}
```
but now in v3 the format is updated to
```
https://{bucket-name}.s3.{region}.amazonaws.com/{file-path}
```
now because bucket-name is as sub-domain the https certificate becomes invalid if bucket-name has. 
for e.g 
https://example.bucket.s3.ap-south-1.amazonaws.com/ but their certificate is valid for domain **.s3.ap-south-1.amazonaws.com/ only allow one level sub-domain before s3

### SDK version number

@aws-sdk/lib-storage@3.451.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.16.0

### Reproduction Steps

- Create bucket name which contains "." in it like example.bucket
- Upload a file using @aws-sdk/lib-storage
- Open the returned Location it give TLS "NET::ERR_CERT_COMMON_NAME_INVALID"

### Observed Behavior

Returned Location it  give TLS "NET::ERR_CERT_COMMON_NAME_INVALID" when try to open the image

### Expected Behavior

Return location endpoint should work

### Possible Solution

Either switch back to older url format or make the *.s3 certificate support multiple sub-domain

**Comment by pidge-raman** [comment]
Thanks @kuhe .

Should i close the issue or keep it open for SSL certificate issue ?

**Comment by kuhe** [comment]
I don't think that's an issue, since I believe you're supposed to use path style for buckets containing `.`.
