### ISSUE TITLE
V3 SDK custom logger should be called with the response duration inside the metadata

### ISSUE THREAD

**Issue by ryan65** [aws/aws-sdk-js-v3#5492]
### Describe the feature

When passing a custom logger to the SDK , and calling an api, we want our logger callback,  to receive the time it took to complete the request together with all the other information .  (clientName, commandName, metadata etc....)
Actually it should be part of the metadata.
In V2 the log contained this information. like the example below.
[AWS ec2 400 **0.528s** 0 retries] deleteSecurityGroup({ GroupId: 'sg-079bfdf0d369d0efe' })

### Use Case

we need this , so that our logs will have this information , when we investigate cases , we can see if a request took longer than expected.

### Proposed Solution

Add the time the request took . to the metadata property. 
In v2 it was calclulated in the  SDK internal buildMessage function of event_listeners.js
        var time = resp.request.service.getSkewCorrectedDate().getTime();
        var delta = (time - req.startTime.getTime()) / 1000;

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.423.0

### Environment details (OS name and version, etc.)

Windows, linux.

**Comment by RanVaknin** [comment]
Hi @ryan65 ,

Thanks for reaching out. I agree that there is no good logging mechanism in the v3 SDK.

You can achieve this by using a middleware hook:

```js
// example using S3
const client = new S3Client({});

client.middlewareStack.add(next => async (args) => {
  const label = 'roundtrip-time'; 
  console.time(label); 
  const response = await next(args);
  console.timeEnd(label); 
  return response; 
}, { step: 'finalizeRequest' });
```

We already have a logger implementation on our backlog which will probably look a bit different than v2, and more look like the Go SDK's logger where it will be a flag in the configuration. 

Thanks,
Ran~

**Comment by ryan65** [comment]
> Hi @ryan65 ,
> 
> Thanks for reaching out. I agree that there is no good logging mechanism in the v3 SDK.
> 
> You can achieve this by using a middleware hook:
> 
> ```js
> // example using S3
> const client = new S3Client({});
> 
> client.middlewareStack.add(next => async (args) => {
>   const label = 'roundtrip-time'; 
>   console.time(label); 
>   const response = await next(args);
>   console.timeEnd(label); 
>   return response; 
> }, { step: 'finalizeRequest' });
> ```
> 
> We already have a logger implementation on our backlog which will probably look a bit different than v2, and more look like the Go SDK's logger where it will be a flag in the configuration.
> 
> Thanks, Ran~

Hi Ran
Thanks for the reply , however it is not quite what I need because we have our own custom logger , that we pass the sdk , and I want to print the time as part of the format that our logger prints for each call , when the sdk calls triggers it .
However , I did find a workaround which is not far from what you mentioned.
We already use a middleware, so what I did is I added the call duration to the response metadata , and that way , when the sdk calls our custom logger with the input , output etc , I will have it on the metadata itself and that way I can format my logs.
That said , I would expect this to be done by the sdk itself  and itself add the duration to the metadata (just like v2 did) since this is something that I think is very important information , and Im sure others would need this , just like the other stuff on the metadata like requestId etc.

sdk.middlewareStack.add(
          (next, context) => async (args) => {
             let result, error;
             let startTime = Date.now();
             try{
                result = await next(args);
                result.output.$metadata._requestDurationSecs = (Date.now() - startTime) /1000;
             }catch(err){
                error = err; .....

**Comment by RanVaknin** [comment]
Hi @ryan65 ,

Thanks for the code snippet. 

In v2 my guess is that this response timing was added into the metadata object as a customization. In v3 we aim to not add customizations to the request /response cycle and instead try to stick to the service response and protocol information only with the exception of logging the retry attempts. 

Since this feature request is aimed at adding the customization to the response itself, this is not something we are planning to support in v3. 

Thanks again for taking the time and providing your own implementation. 

All the best,
Ran~

**Comment by ryan65** [comment]
> Hi @ryan65 ,
> 
> Thanks for the code snippet.
> 
> In v2 my guess is that this response timing was added into the metadata object as a customization. In v3 we aim to not add customizations to the request /response cycle and instead try to stick to the service response and protocol information only with the exception of logging the retry attempts.
> 
> Since this feature request is aimed at adding the customization to the response itself, this is not something we are planning to support in v3.
> 
> Thanks again for taking the time and providing your own implementation.
> 
> All the best, Ran~

Hi Ran
Thanks for the response.
In V2 from looking at the sdk code , the the request stored a field called startTime and used it when building the log message (event_listeners.js , function buildMessage).
I stll dont quite understand why we wouldnt want this information in V3 as well , I would reconsider and find a way to add it to the metadata. This is very usefull information and I dont see any point for each sdk consumer to have to implement this on his own.
