### ISSUE TITLE
@aws-sdk/types has no exported member named "AwsRegionExtensionConfiguration". Did you mean "PaginationConfiguration"

### ISSUE THREAD

**Issue by piotrwalczak1** [aws/aws-sdk-js-v3#5493]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When I install the package and:
import {
  GetSecretValueCommand,
  SecretsManagerClient,
} from "@aws-sdk/client-secrets-manager";

During typescript complilation I am getting the following error:
```
> iot-prototype@0.1.0 typecheck
> npx tsc --noEmit

node_modules/@aws-sdk/client-secrets-manager/dist-types/extensionConfiguration.d.ts:1:10 - error TS2724: '"@aws-sdk/types"' has no exported member named 'AwsRegionExtensionConfiguration'. Did you mean 'PaginationConfiguration'?

1 import { AwsRegionExtensionConfiguration } from "@aws-sdk/types";
```
Installing @aws-sdk/types results in an error:
```
npm ERR! code EOVERRIDE
npm ERR! Override for @aws-sdk/types@* conflicts with direct dependency

npm ERR! A complete log of this run can be found in:
```

### SDK version number

    "@aws-sdk/client-secrets-manager": "^3.451.0",

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v.18.15.0

### Reproduction Steps

Just install the package and import GetSecretValueCommand and SecretsManagerClient.

### Observed Behavior

error

### Expected Behavior

no error

**Comment by kuhe** [comment]
Remove `@smithy/types` from your explicit dependency list. Reinstall without package-lock. 

`@aws-sdk/client-secrets-manager`@3.451.0 will bring in `@smithy/types`@2.5.0 which has the type in question.
