### ISSUE TITLE
client-rds-data ExecuteStatementCommand Parameters Input Syntax

### ISSUE THREAD

**Issue by tahaerden** [aws/aws-sdk-js-v3#5500]
### Describe the issue

I'm using aws-sdk v3 for the first time, and I am trying to use client-rds-data ExecuteStatementCommand function to execute SQL statements from my Lambda NodeJS to Aurora MySQL.

I wasn't able to find a good example of how to use the "parameters" input.

I used a 3rd-party library before in aws-sdk v2. The syntax there would look something like the following:

```

sql: "UPDATE employee SET firstname=:first, lastname=:last WHERE id=:employeeID",
parameters: {
  first: John,
  last: Doe,
  employeeID: 123
}

```

So my questions are:
1. Can I use a colon (:) or something else in sql statement so that it will be replaced by the value in parameters object?
2. Can I simply send a JSON object in parameters or do I have to specify the type (stringValue, longValue, arrayValue etc.) for each value of the object? It sounds like a lot of work for a medium-size object.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/rds-data/command/ExecuteStatementCommand/

**Comment by tahaerden** [comment]
Any updates on this? I'm going to need to use this parameters input soon.

**Comment by aBurmeseDev** [comment]
Hi @tahaerden - apologies for the delay as I was reaching out the service team on the information you're looking for. I'm still waiting on their response but here's what I think the code would look like for your case.

```ts
const { RDSDataServiceClient, ExecuteStatementCommand } = require("@aws-sdk/client-rds-data");

// Set your AWS credentials and region if not already set

// Replace these with your actual values
const databaseArn = "your-database-arn";
const resourceArn = "your-resource-arn";
const secretArn = "your-secret-arn";

const client = new RDSDataServiceClient({ region: "your-region" });

const sql = "UPDATE employee SET firstname=:first, lastname=:last WHERE id=:employeeID";

const parameters = {
  first: { stringValue: "John" },
  last: { stringValue: "Doe" },
  employeeID: { longValue: 123 },
};

const params = {
  resourceArn: resourceArn,
  secretArn: secretArn,
  sql: sql,
  parameters: [parameters],
  database: "your-database-name",
};

const command = new ExecuteStatementCommand(params);

client.send(command)
  .then((response) => {
    console.log("Execution response:", response);
  })
  .catch((error) => {
    console.error("Error executing statement:", error);
  })
  .finally(() => {
    client.destroy();
  });
```
1. Can I use a colon (:) or something else in sql statement so that it will be replaced by the value in parameters object?
_Yes you can_ 
3. Can I simply send a JSON object in parameters or do I have to specify the type (stringValue, longValue, arrayValue etc.) for each value of the object? It sounds like a lot of work for a medium-size object. 
_Yes you do have to specify the type and arrayValue aren't supported by service API as noted [here](https://docs.aws.amazon.com/rdsdataservice/latest/APIReference/API_ExecuteStatement.html#API_ExecuteStatement_RequestBody)_

Hope it helps and please let me know if you run into any issues!
Best,
John

**Comment by aBurmeseDev** [comment]
Please allow me to confirm that with the service team as I wanted to make sure that you get the correct information. I'll circle back once I have the information!

**Comment by aBurmeseDev** [comment]
Checking back in - I still haven't heard back from the service team. However, upon doing some more research, I couldn't find any built-in function that would converts from `{ first: "John" }` to `{ first: { stringValue: "John" } }`. I wanted to share it with you.

**Comment by tahaerden** [comment]
Thank you very much for all the effort @aBurmeseDev . No problem, I'll implement it myself 👍🏻

**Comment by aBurmeseDev** [comment]
Hi @tahaerden - I just heard back from service team member and wanted to share their response with you.

> Can I use a colon (:) or something else in sql statement so that it will be replaced by the value in parameters object?

Yes, you will have to use :<column name> and column name here is from the parameters object.
For example, your sql would be something like this, "insert into mytable values (:id, :val)" and your parameters would be,
"[[{"name": "id", "value": {"longValue": 1}},{"name": "val", "value": {"stringValue": "ValueOne"}}]]"

>Can I simply send a JSON object in parameters or do I have to specify the type (stringValue, longValue, arrayValue etc.) for each value of the object? It sounds like a lot of work for a medium-size object.

Unfortunately yes. For Javascript, we do not yet have a client library that does this for you.
But feel free use exiting ones from our customers.
https://github.com/jeremydaly/data-api-client
