### ISSUE TITLE
Decrypted values differ between KMS client v2 and v3

### ISSUE THREAD

**Issue by tedyu** [aws/aws-sdk-js-v3#5508]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Decrypted values differ between KMS client v2 and v3.

### SDK version number

@aws-sdk/client-kms@3

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node.js 18

### Reproduction Steps

This is the code using kms client v2:
```
    const kms = new AWS.KMS({ apiVersion: '2014-11-01' });
     const encryptedVar = Buffer.from(process.env[encryptedName], 'base64');
     kms.decrypt({ CiphertextBlob: encryptedVar }, (err, data) => {
...
      const decrypted = data.Plaintext;
```
This is the code using kms client v3:
```
    const kms = new KMSClient({ region: 'us-east-1' });
    const encryptedVar = Buffer.from(process.env[encryptedName], 'base64');
    const command = new DecryptCommand({ CiphertextBlob: encryptedVar });
    kms.send(command, (err, data) => {
...
      const decrypted = data.Plaintext;
```
The `data` returned from clients are different.

If certain parameter needs to be specified for client v3, please let me know.

### Observed Behavior

The `data` returned from clients are different.

### Expected Behavior

The `data` returned from clients should be the same.

**Comment by aBurmeseDev** [comment]
Hi @tedyu - thanks for reaching out.

I attempted to reproduce but am not seeing the behavior you described. I have a few questions to clarify:
1. Which key are you using to decrypt data: symmetric, asymmetric encryption KMS or for a Nitro enclave? See [more](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/kms/command/DecryptCommand/).
2. Could you elaborate more on the difference of returned outputs between v2 and v3 as far as which data/field is returned differently? 

The only required parameter is `CiphertextBlob` which you have it in your code. The only difference I see in your code is the region which isn't being specified in v2.

Looking forward to hear back,
John

**Comment by tedyu** [comment]
One line not included in the description is after the decryption call:
```
      const decrypted = data.Plaintext;
```
The `Plaintext` field carries different values between client v2 and v3.
As for which key is used to decrypt data, with or without `KeyEncryptionAlgorithm` parameter, the result is the same (initially I only specified `CiphertextBlob`).

Thanks
