### ISSUE TITLE
lib-storage Upload.done() has wrong return type

### ISSUE THREAD

**Issue by nwalters512** [aws/aws-sdk-js-v3#5513]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

`Upload.done()` from `@aws-sdk/lib-storage` has its return type declared as `Promise<CompleteMultipartUploadCommandOutput | AbortMultipartUploadCommandOutput>`:

https://github.com/aws/aws-sdk-js-v3/blob/27a5b6ca3ed598c68b884eaaf684e928d0abcade/lib/lib-storage/src/Upload.ts#L97

However, this function will only ever return `Promise<CompleteMultipartUploadCommandOutput>`. If the upload is aborted, the promise will reject with an error.

### SDK version number

@aws-sdk/lib-storage@3.456.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.7.0

### Reproduction Steps

N/A; this is a type issue, not a runtime issue.

### Observed Behavior

The function is declared as returning `Promise<CompleteMultipartUploadCommandOutput | AbortMultipartUploadCommandOutput>`.

### Expected Behavior

The return type should be `Promise<CompleteMultipartUploadCommandOutput>`.

### Possible Solution

I've opened a PR to fix this here: https://github.com/aws/aws-sdk-js-v3/pull/5512. I'm opening an issue to ensure that the bug is tracked and that the PR receives attention.

**Comment by RanVaknin** [comment]
Hi @nwalters512 ,

Thanks again for reaching out. I think your are right in your analysis. Will have someone take a look at the PR. 

All the best,
Ran~
