### ISSUE TITLE
Send attachment on email aws-sdk/client-ses

### ISSUE THREAD

**Issue by hygison** [aws/aws-sdk-js-v3#5514]
### Describe the issue

I am trying to send emails with attachment using `aws-sdk/client-ses` But it does not work.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/ses/command/SendEmailCommand/

**Comment by aBurmeseDev** [comment]
Hi @hygison - thanks for reaching out. 

To send email with attachments, [`SendRawEmailCommand`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/ses/command/SendRawEmailCommand/) is probably what you're looking for. 
Here are a few things to note, for you specific use case:
- The maximum message size, including attachments, is 10 MB.
- You'll use `RawMessage` parameter as email message like so:
`
  "RawMessage": {
    "Data": "From: sender@example.com\\nTo: recipient@example.com\\nSubject: Test email (contains an attachment)\\nMIME-Version: 1.0\\nContent-type: Multipart/Mixed; boundary=\"NextPart\"\\n\\n--NextPart\\nContent-Type: text/plain\\n\\nThis is the message body.\\n\\n--NextPart\\nContent-Type: text/plain;\\nContent-Disposition: attachment; filename=\"attachment.txt\"\\n\\nThis is the text in the attachment.\\n\\n--NextPart--"
  },
`
- Attachments must be of a content type that Amazon SES supports. For a list on unsupported content types, see [Unsupported Attachment Types](https://docs.aws.amazon.com/ses/latest/dg/mime-types.html).

Hope that helps!
Best,
John
