### ISSUE TITLE
Parallel getObject leads to timeouts/download hangs

### ISSUE THREAD

**Issue by randomhash** [aws/aws-sdk-js-v3#5517]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

https://github.com/aws/aws-sdk-js-v3/issues/3560
after around 100 items fetched/uploaded connection hangs
concurrency 20-100
S3 client initialized on lambda start
Basically works once every ~20 times correctly

```js
import {NodeHttpHandler} from '@smithy/node-http-handler';
import {Agent} from 'node:https';

const s3download = new S3({
  region: process.env.AWS_REGION,
  logger: console,
  forcePathStyle: true,
  requestHandler: new NodeHttpHandler({
    httpsAgent: new Agent({
      timeout: 5000,
      maxSockets: 1000, // default 50
      // keepAlive is a default from AWS SDK. We want to preserve this for
      // performance reasons.
      keepAlive: true,
      keepAliveMsecs: 1000, // default unset,
    }),
    connectionTimeout: 1000,
    requestTimeout: 5000, // default 0
  }),
});

const s3upload = new S3({
  region: process.env.AWS_REGION,
  logger: console,
  forcePathStyle: true,
  requestHandler: new NodeHttpHandler({
    httpsAgent: new Agent({
      maxSockets: 1000, // default 50
      keepAlive: false,
    }),
    connectionTimeout: 1000,
    requestTimeout: 5000, // default 0
  }),
});
```
This still leads to mass failures within the production environment with lots of files to process

### SDK version number

latest

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

18

### Reproduction Steps

Setup lambda with arm64 with a subscription to sqs queue
Add code to fetch ~1000 items(size varies from 1kb to 5mb) with concurrency of 100
Publish messages into the queue, observe results

### Observed Behavior

Continuous failures of the aws-sdk v3 
Stable work of the aws-sdk v2

### Expected Behavior

Download not hang and files downloaded at the same speeds as aws-sdk v2

**Comment by randomhash** [comment]
Bump

**Comment by kuhe** [comment]
show the code that you use to fetch items

**Comment by aBurmeseDev** [comment]
HI @randomhash!
As kuhe requested, can you please provide a minimal reproducible code that you use to fetch items as that would help us narrow down the root cause?

**Comment by randomhash** [comment]
```
export async function getFile({Bucket, Key}: KeyWithBucket) {
  const {Body} = await getObject({Bucket, Key});

  if (!Body) {
    throw new Error('Object not found.');
  }

  return toBuffer(Body as Readable);
}

export async function toBuffer(stream: Readable): Promise<Buffer> {
  const chunks = [];

  for await (const chunk of stream) {
    chunks.push(Buffer.from(chunk));
  }

  return Buffer.concat(chunks);
}
```

Next place is the actual code that download data, 

```
import pMap from 'p-map';

async function main(s3Keys: string[]) {
 const results = await pMap(s3Keys, async (key) => getFile({Bucket: 'some-bucket', Key: key}), {concurrency: 100})
 console.log('Done')
}

This should be sufficient to reproduce issue on large scale, just pass into main chunks ~400 items multiple times

**Comment by randomhash** [comment]
@aBurmeseDev hey! Maybe you have some updates on the topic?

**Comment by terret** [comment]
Hello, any updates on this?

**Comment by aBurmeseDev** [comment]
Hello, we're still looking into this and will need more time to investigate. I'll post once we have an update. Thanks for your patience!

**Comment by yixiangding** [comment]
Same issue here in our production environment after we upgraded our AWS Lambda Node.js runtime from 14 to 18, which also forces us to upgrade from SDK V2 to V3. After one execution that involves 60+ S3 object downloads, the whole Lambda instance/environment just hung/stuck with no error, and all the following executions on the same environment/instance just silently aborted on the `s3.getObject`, no error and no stack trace from Lambda. 

We can also reproduce on the local environment, which makes us believe it's related to the SDK V3 `getObject`

**Comment by laggage** [comment]
We can reproduce the problem with the following code executed in aws lambda(`objectKeys` need to over than 60 or more)

```js
const {
    S3, GetObjectCommand, PutObjectCommand, HeadObjectCommand
} = require("@aws-sdk/client-s3");

const objectKeys = []

const s3Client = new S3({
    region: 'us-west-2',
});


const getObject2 = (bucket, key) => {
    return (new S3({
        region: 'us-west-2',
    })).send(
        new GetObjectCommand({
            Bucket: bucket,
            Key: key,
            ResponseContentType: "application/octet-stream"
        })
    )
}


const getObject = (bucket, key) => {
    return s3Client.send(
        new GetObjectCommand({
            Bucket: bucket,
            Key: key,
            ResponseContentType: "application/octet-stream"
        })
    )
}

exports.handler = async () => {
   console.log('Objects: ', objectKeys.length)
   await Promise.all(objectKeys.map(k => getObject('test-bucket', k)))
   console.log('finished')
}
```

**Comment by kuhe** [comment]
@laggage increase the number of sockets as shown in the issue description.

```js
import { NodeHttpHandler } from '@smithy/node-http-handler';
import { Agent } from 'node:https';

const s3 = new S3({
  region: "...",
  requestHandler: new NodeHttpHandler({
    httpsAgent: new Agent({
      maxSockets: 200
    }),
  }),
});
```

But also, when you get an object, you should do something with the body. Leaving a socket open with an unconsumed stream also exhausts your sockets even faster. 

If you do consume the stream, using a small number of maxSockets is also fine.

```js
const getObject = (bucket, key) => {
    const response = s3Client.send(
        new GetObjectCommand({
            Bucket: bucket,
            Key: key,
            ResponseContentType: "application/octet-stream"
        })
    );
    return response.Body?.transformToByteArray();
}
```

As to why this isn't an issue in JS SDK v2, I'll double check later but I believe the default behavior is to buffer the response stream before giving it to the user. It's convenient in some cases, but does not provide a consistent modeling of the service. We shouldn't be deciding what to do with your stream, and we used the major version upgrade to take that approach.
