### ISSUE TITLE
retryStrategy.retry is not a function

### ISSUE THREAD

**Issue by tedyu** [aws/aws-sdk-js-v3#5519]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

`TypeError: retryStrategy.retry is not a function` was encountered when retry happens.

### SDK version number

@aws-sdk/client-s3 3.430, @smithy/util-retry 2.0.4

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node.js 18

### Reproduction Steps

For aws-sdk-js-v3, we use the following code:
```
const s3 = new S3Client({
  retryStrategy: Util.retryParams,
```
where retryParams is defined as:
```
const { ConfiguredRetryStrategy } = require('@smithy/util-retry');

const MAX_RETRIES = 3;
const retryParams = () => new ConfiguredRetryStrategy(
  MAX_RETRIES,
  (retryCount) => {
    return 1000;
  }
);
```

### Observed Behavior

at runtime, we see the following stack trace:
```
ERROR   {
  err: TypeError: retryStrategy.retry is not a function
      at /var/task/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:58:30
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /var/task/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:63:20
      at async /var/task/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-endpoint-middleware.js:14:24
      at async /var/task/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-middleware.js:9:20
      at async /var/task/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
```

### Expected Behavior

The retry should proceed.

**Comment by tedyu** [comment]
Since retry parameter is specified when `S3Client` is created, I am not sure which retry function to use since the same `S3Client` instance can be used to send get or put command.

**Comment by tedyu** [comment]
It seems `retry` doesn't need to be a function if `retryStrategy` satisfies:
```
const isRetryStrategyV2 = (retryStrategy) => typeof retryStrategy.acquireInitialRetryToken !== "undefined" &&
    typeof retryStrategy.refreshRetryTokenForRetry !== "undefined" &&
    typeof retryStrategy.recordSuccess !== "undefined";
```

**Comment by kuhe** [comment]
```js
const s3 = new S3Client({
  retryStrategy: Util.retryParams,
```

try changing it to

```js
const s3 = new S3Client({
  retryStrategy: Util.retryParams(),
```

**Comment by tedyu** [comment]
With this (along with above suggestion):
```
const MAX_RETRIES = 3;
const retryParams = (innerStack) =>
  retryMiddleware({
    retryStrategyV2: (error, attempts) => attempts < MAX_RETRIES,
  }).concat(innerStack); // Concatenate the retry middleware with the inner stack;
```
I get:
```
TypeError: retryMiddleware(...).concat is not a function
    at Object.retryParams (/opt/app/lambda/s3/util.js:10:6)
    at Object.<anonymous> (/opt/app/lambda/s3/bulk_put.js:8:23)
```
@kuhe 
Do you have suggestion ?

**Comment by tedyu** [comment]
In private/aws-client-retry-test/src/ClientRetryTest.spec.ts
```
    const s3 = new S3({
      requestHandler: new MockRequestHandler(),
      retryStrategy,
```
@kuhe 
Can you give me a practical `RequestHandler` which I can use ?

Thanks

**Comment by kuhe** [comment]
you have not said what you are trying to do, so I'm not sure why you need to set a requestHandler

You can leave the requestHandler option of the client constructor empty to use the default requestHandler.
