### ISSUE TITLE
S3 HeadObjectCommand throws an error when S3 returns Expires header which doesn't meet http-date format

### ISSUE THREAD

**Issue by Le0Michine** [aws/aws-sdk-js-v3#5520]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

S3 allows non http-date values set to Expires metadata associated with an object (for example user can set 2023-01-01). S3 would return whatever value was set by the user even if it doesn't meet http-date specification. When I try retrieving metadata using HeadObjectCommand SDK throws an error complaining about incorrect format.

It looks like there is a disparity between what API allows and what SDK expects on client side. Since user can set arbitrary value they should be able to retrieve it with no issues, currently SDK prevents user from interacting with such objects.

I was able to find a similar issue which was reported for ruby sdk and it looks like it was addressed by overriding the header type in the model https://github.com/aws/aws-sdk-ruby/issues/1184. It would be great if JS SDK could support that use case as well.

### SDK version number

@aws-sdk/package-name@version, ...

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node v16.18.1

### Reproduction Steps

- create an object in S3
- using S3 Console edit object metadata and set Expires to `2023-01-01`
- try sending HeadObjectCommand for that object

### Observed Behavior

an error thrown

```
Error while heading source key: TypeError: Invalid RFC-7231 date-time value
  Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.
```

### Expected Behavior

sdk should successfully parse the response and return all fields

### Possible Solution

could be addressed in a similar way it was done for ruby sdk before
https://github.com/aws/aws-sdk-ruby/issues/1184

**Comment by RanVaknin** [comment]
Hi @Le0Michine ,

This is related to [this issue](https://github.com/aws/aws-sdk/issues/434) which like you mentioned in your analysis, is an issue with a discrepancy between the Service and the Client.

Since the SDK client is generated from the API model that is defined by the S3 service team, the change needs to happen upstream. In the newer SDKs we are trying to avoid introducing customizations to mitigate API modeling errors. 

I will discuss this again with our team to try and solve this.

All the best,
Ran~

**Comment by niqolay** [comment]
If anyone needs a workaround for this. You can modify 'expires' header before sending it to deserialization with custom middleware:
```
s3Client.middlewareStack.addRelativeTo(
  (next: any) => async (args: any) => {              
    const result = await next(args);
    const response = result.response as HttpResponse;
    response.headers['expires'] = new Date().toUTCString();
    return result;
    },
  {
    relation: 'after',
    toMiddleware: 'deserializerMiddleware',
  }
);
```
This way it works in my case

**Comment by Le0Michine** [comment]
To preserve it though you probably would need another middleware right before deserialization as well. So that the first one would put the value into the context and the second would add it to the parsed model. Would be helpful if deserialization and serialization functions were importable from TS code

**Comment by RanVaknin** [comment]
Fixed in https://github.com/aws/aws-sdk-js-v3/pull/5715
