### ISSUE TITLE
DescribeContact returning undefined disconnectTimestamp

### ISSUE THREAD

**Issue by asiftyro** [aws/aws-sdk-js-v3#5523]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Hi, sometimes we receive an undefined disconnectTimestamp from the API DescribeContact for some ContactID, although other values are returning as expected. We cross-checked with Connect UI. Connect UI shows valid DateTime. Any help will be highly appreciated. Thanks.

Our implementation:

```
const getContactCDR = async (ContactID) => {
  let cmd = new DescribeContactCommand({
    "InstanceId": awsInstance,
    "ContactId": ContactID
  });
  try {
    let res = await connectClient.send(cmd);
    let r = res.Contact;
    let ret = {
      "ContactID": r.Id,
      "describeContactCalled": 1,
      "initiationMethod": r.InitiationMethod,
      "channel": r.Channel,
      "queueId": r.QueueInfo !== undefined ? r.QueueInfo.Id : '',
      "agentId": r.AgentInfo !== undefined ? r.AgentInfo.Id : '',
      "connectedToAgentTimestamp": r.AgentInfo !== undefined ? r.AgentInfo.ConnectedToAgentTimestamp.getTime() / 1000 : 0,
      "enqueueTimestamp": r.QueueInfo !== undefined ? r.QueueInfo.EnqueueTimestamp.getTime() / 1000 : 0,
      "initiationTimestamp": r.InitiationTimestamp.getTime() / 1000,
      "disconnectTimestamp": r.DisconnectTimestamp.getTime() / 1000,
      "lastUpdateTimestamp": r.LastUpdateTimestamp.getTime() / 1000,
      "duration": ((r.DisconnectTimestamp.getTime() / 1000) - (r.InitiationTimestamp.getTime() / 1000))
    }
    return ret;
  } catch (e) {
    console.log(e);
    return;
  }
}
```

### SDK version number

@aws-sdk/client-connect@3.194.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.5.1

### Reproduction Steps

```
const getContactCDR = async (ContactID) => {
  let cmd = new DescribeContactCommand({
    "InstanceId": awsInstance,
    "ContactId": ContactID
  });
  try {
    let res = await connectClient.send(cmd);
    let r = res.Contact;
    let ret = {
      "ContactID": r.Id,
      "describeContactCalled": 1,
      "initiationMethod": r.InitiationMethod,
      "channel": r.Channel,
      "queueId": r.QueueInfo !== undefined ? r.QueueInfo.Id : '',
      "agentId": r.AgentInfo !== undefined ? r.AgentInfo.Id : '',
      "connectedToAgentTimestamp": r.AgentInfo !== undefined ? r.AgentInfo.ConnectedToAgentTimestamp.getTime() / 1000 : 0,
      "enqueueTimestamp": r.QueueInfo !== undefined ? r.QueueInfo.EnqueueTimestamp.getTime() / 1000 : 0,
      "initiationTimestamp": r.InitiationTimestamp.getTime() / 1000,
      "disconnectTimestamp": r.DisconnectTimestamp.getTime() / 1000,
      "lastUpdateTimestamp": r.LastUpdateTimestamp.getTime() / 1000,
      "duration": ((r.DisconnectTimestamp.getTime() / 1000) - (r.InitiationTimestamp.getTime() / 1000))
    }
    return ret;
  } catch (e) {
    console.log(e);
    return;
  }
}
```

### Observed Behavior

Received ```undefined```

### Expected Behavior

Should get a timestamp.

**Comment by RanVaknin** [comment]
Hi @asiftyro ,

Thanks for opening the issue. Im wondering if the in the cases where you see undefined, the service is sending the response in a format that SDK cannot parse. 

We can check if this is an SDK issue by logging the raw response before it gets deserialized. You can do that using a simple middleware:

```js
client.middlewareStack.add(next => async (args) => {
  const response = await next(args);
  console.log(response)
  return response; 
}, { step: 'finalizeRequest' });
```

If you can share the logs of the requests that have the omitted `disconnectTimestamp` value, it might help point us in the right direction. 

Thanks again,
Ran~

**Comment by asiftyro** [comment]
We are facing some issues after implementing the middleware. We will get back with the findings shortly.
