### ISSUE TITLE
Add waitFor to ECSClient

### ISSUE THREAD

**Issue by tedyu** [aws/aws-sdk-js-v3#5525]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Using client v2, we call `ecs.waitFor(type, opts)`.
For client v3, there is no counterpart.

### SDK version number

@aws-sdk/client-ecs@3

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node.js 18

### Reproduction Steps

`waitFor` is missing in `ECSClient`

### Observed Behavior

`waitFor` is missing in `ECSClient`

### Expected Behavior

`waitFor` should be provided in `ECSClient`.

**Comment by RanVaknin** [comment]
Hi @tedyu ,

Waiters already exist in v3. The syntax is a bit different. You can check out this [blogpost](https://aws.amazon.com/blogs/developer/waiters-in-modular-aws-sdk-for-javascript/) for more details on how to use waiters.

Thanks,
Ran~

**Comment by tedyu** [comment]
@RanVaknin 
I think the blog doesn't cover my use case.
```
> const { ECSClient, RunTaskCommand, StopTaskCommand, DescribeTasksCommand } = require('@aws-sdk/client-ecs');
undefined
> ECSClient.waitUntilTasksRunning
undefined
```
Do you know why the ecs client may not have `waitUntilTasksRunning` ?
I wonder if the following call is correct:
```
ecsCVlient.waitUntilTasksRunning({ ...opts, waiterConfiguration: waiterConfig }, taskWaiter);
```
Thanks
