### ISSUE TITLE
presigned post url type definitions not working for conditions

### ISSUE THREAD

**Issue by Sparkdaddy** [aws/aws-sdk-js-v3#5527]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Mostly ripped [the previous issue](https://github.com/aws/aws-sdk-js-v3/issues/3057) since I'm experiencing the same thing today and his sandbox still recreates the example. I cannot use conditions because I have to turn off the linter in the PR which is a poor developer experience and removes the safeguards that Typescript provides.

This is a basic example of creating a presigned post url in the documentations:

  const Conditions = [
    { acl: "public-read" },
    { bucket: "johnsmith" },
    ["starts-with", "$key", "user/eric/"],
  ];

  const Fields = {
    acl: "public-read",
  };
  const { url, fields } = await createPresignedPost(s3Client, {
    Bucket: "bucketname",
    Key: "avatars/1.png",
    Conditions, // Error
    Fields,
    Expires: 600,
  });
I get the following error in "Conditions" field:

### SDK version number

@aws-sdk/package-name@@aws-sdk/client-s3@3.430.0 @aws-sdk/s3-presigned-post@3.461.0version, ...

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

18.18.0

### Reproduction Steps

Steps to reproduce
[codesandbox.io/s/solitary-forest-qvg9t?file=/src/index.ts](https://codesandbox.io/s/solitary-forest-qvg9t?file=/src/index.ts)

### Observed Behavior

[tsserver 2322] [E] Type '(string[] | { acl: string; bucket?: undefined; } | { bucket: string; acl?: undefined; })[]' is not assignable to type 'Conditions[]'.
  Type 'string[] | { acl: string; bucket?: undefined; } | { bucket: string; acl?: undefined; }' is not assignable to type 'Conditions'.
    Type 'string[]' is not assignable to type 'Conditions'.
      Type 'string[]' is not assignable to type 'ContentLengthRangeCondition'.
        Target requires 3 element(s) but source may have fewer.
I didn't expect that error. It's wired. I get a similiar error with this conditions object:

const Conditions = [
  ["starts-with", "$key", "user/eric/"],
];
[tsserver 2322] [E] Type 'string[][]' is not assignable to type 'Conditions[]'.
  Type 'string[]' is not assignable to type 'Conditions'.
    Type 'string[]' is not assignable to type 'ContentLengthRangeCondition'.
      Target requires 3 element(s) but source may have fewer.
The main aws-sdk project mentioned that it required typescript v2.x but I don't know whether the same thing is true about this project. I'm currently using typescript v4.4.4

### Expected Behavior

Typing issues

**Comment by RanVaknin** [comment]
Hi @Sparkdaddy ,

You can just import the Conditions and assert the type the following way:

```js
import { createPresignedPost} from "@aws-sdk/s3-presigned-post";
import { Conditions as PolicyEntry } from '@aws-sdk/s3-presigned-post/dist-types/types';

const Conditions: PolicyEntry[] = [
  { acl: "public-read" },
  { bucket: "johnsmith" },
  ["starts-with", "$key", "user/eric/"],
];

// more code...

    const response = await createPresignedPost(client, {
      Bucket,
      Key,
      Conditions,
      Fields,
      Expires: 600,
    });
  //...
  }
  ```
  
  Thanks,
  Ran~

**Comment by Sparkdaddy** [comment]
So you can - thanks! Strange to me that the type check works at that point and not in the `createPresignedPost` method before...but then again I'm not the best with Typescript.

Appreciate your help!

**Comment by Sparkdaddy** [comment]
Found some relevant articles on Type Annotation to better understand the error of my ways. Thanks again @RanVaknin !
