### ISSUE TITLE
InvalidParameterException  when `TABLES` are not detected on the page and FeatureTypes has `TABLES`

### ISSUE THREAD

**Issue by nivid-eog** [aws/aws-sdk-js-v3#5528]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Analyzing document that has page that doesn't have `TABLES` detected shows no results when using AWS UI. But when using `@aws-sdk/client-textract` `analyzeDocument` function it runs into following error

```
InvalidParameterException: Request has invalid parameters
    at de_InvalidParameterExceptionRes (/*****/node_modules/@aws-sdk/client-textract/dist-cjs/protocols/Aws_json1_1.js:1681:23)
    at de_AnalyzeDocumentCommandError (/*****/node_modules/@aws-sdk/client-textract/dist-cjs/protocols/Aws_json1_1.js:222:25)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /*****/node_modules/@aws-sdk/client-textract/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /*****/node_modules/@aws-sdk/client-textract/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:30:20
    at async /*****/node_modules/@aws-sdk/client-textract/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /*****/node_modules/@aws-sdk/client-textract/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: '*****',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Code: undefined,
  __type: 'InvalidParameterException'
}
```

### SDK version number

@aws-sdk/client-textract@3.461.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node 18

### Reproduction Steps

Can't provide file here. I can provide through email if needed.

### Observed Behavior

Invalid Parameters Exception

### Expected Behavior

no tables found

**Comment by RanVaknin** [comment]
Hi @nivid-eog ,

Can you please share your actual code so we can further look into this?

Thanks,
Ran~

**Comment by nivid-eog** [comment]
I think I know the problem. Sorry for inconvenience.  We split the pdf into multiple pages using python and the split results into pages that are more then 20mb.  I think that is the issue for this exception.

**Comment by nivid-eog** [comment]
Still It would be better if a meaningful exception is thrown rather then invalid parameter exception.

**Comment by RanVaknin** [comment]
Hi @nivid-eog ,

The error `InvalidParameterException: Request has invalid parameters` is a service side error, and not thrown by the SDK.

Without seeing the request logs, its hard to know why this is the error that was returned. Perhaps by you splitting the file up the server was sent something it did not expect. 

You can inspect the raw request and response by including a simple middleware for your client like so:

```js
client.middlewareStack.add(next => async (args) => {
 console.log(args.request)
 const response = await next(args);
 console.log(response);
 return next(args);
}, {step: 'finalizeRequest'})
```

Hopefully by inspecting the request logs you are able to detect why the request is considered invalid.

Since this is an error thrown by the Textract service itself, its not actionable by the SDK team.

All the best,
Ran~
