### ISSUE TITLE
Error with UpdateJobExecutionCommand

### ISSUE THREAD

**Issue by AndresAngel90** [aws/aws-sdk-js-v3#5533]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When I try to use UpdateJobExecutionCommand with the IoTJobsDataPlaneClient, it showed me this error: AccessDeniedException: Access Denied: Invalid endpoint. Use describe-endpoint API to get valid endpoint, I am using the AWS IoT Core credential provider in order to get the credentials. This is the input I am passing:
<img width="230" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/72571690/8048347b-3fe2-49ae-a577-867ca176bce9">

### SDK version number

"@aws-sdk/client-iot-jobs-data-plane": "3.461.0", "@aws-sdk/client-iot-jobs-data-plane": "^3.462.0",

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.18.2

### Reproduction Steps

async updateJobDoneStatus(thingName: string, jobId: string){
    const jsonResponse = await this.getTempCredentials();
    console.log(jsonResponse);
    const iotJobsDataPlaneClient =  new IoTJobsDataPlaneClient({ region: "ap-south-1", credentials: {
      accessKeyId: jsonResponse.credentials.accessKeyId,
      secretAccessKey: jsonResponse.credentials.secretAccessKey,
      sessionToken: jsonResponse.credentials.sessionToken,
    },
  });
    console.log(iotJobsDataPlaneClient.config);
    const input = {
      thingName: thingName,
      jobId:jobId,
      status: JobExecutionStatus.SUCCEEDED
    }
    console.log(input);
    const command = new UpdateJobExecutionCommand(input)
    try {
      const res = await iotJobsDataPlaneClient.send(command)   
      console.log(res);
    } catch (error) {
      console.log(error);
    }
    
  }

### Observed Behavior

AccessDeniedException: Access Denied: Invalid endpoint. Use describe-endpoint API to get valid endpoint

### Expected Behavior

success, chaneg the job status

**Comment by RanVaknin** [comment]
Hi @AndresAngel90 ,

Admittedly, I'm not too familiar with the IOT but from your error it seems like the IOT API expects you to use a specific endpoint.

So following the error message: "Use describe-endpoint API to get valid endpoint":

```console
$ aws iot describe-endpoint --endpoint-type iot:Data-ATS --region ap-south-1

{
    "endpointAddress": "a2e260a5by30ug-ats.iot.ap-south-1.amazonaws.com"
}
```

So in your code:
```js
    const iotJobsDataPlaneClient =  new IoTJobsDataPlaneClient({
        region: "ap-south-1", 
        credentials: {
            accessKeyId: jsonResponse.credentials.accessKeyId,
            secretAccessKey: jsonResponse.credentials.secretAccessKey,
            sessionToken: jsonResponse.credentials.sessionToken,
        },
        endpoint: "a2e260a5by30ug-ats.iot.ap-south-1.amazonaws.com"
  });
```

Let me know if this helps.
Thanks,
Ran~

**Comment by AndresAngel90** [comment]
Good morning @RanVaknin , I already have tried to send the enpoint address and in that specific case response with a 200 howver it does not perform the action that is supposed to execute, and in the cases that I have used the aws-sdk it is not necessary to add the enpoint address due to it has it included into de library

**Comment by RanVaknin** [comment]
Hi @AndresAngel90 ,

>Good morning @RanVaknin , I already have tried to send the enpoint address and in that specific case response with a 200 howver it does not perform the action that is supposed to execute.

Without more details about what is the expected and actual behavior Im not able to point you towards a solution. Can you please let me know what action was supposed to have been made, and what the action that ended up happening?

>and in the cases that I have used the aws-sdk it is not necessary to add the enpoint address due to it has it included into de library

I agree with this sentiment, however this is not something the SDK team can change. The IOT Jobs data plane service team has designed their API in a way that requires you to dynamically obtain the endpoint that you have access to and there has to be a reason why their standard API endpoint (the one that is defined in their API model and that the SDK uses by default) is returning an `AccessDeniedException`.

Thanks,
Ran~
