### ISSUE TITLE
Cannot get final name for export 'serializerMiddlewareOption'

### ISSUE THREAD

**Issue by mattinannt** [aws/aws-sdk-js-v3#5540]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When upgrading from Nextjs `13.5.6` to `14.0.3` I'm facing the following build error:

```
web:build:    Creating an optimized production build ...
web:build: Failed to compile.
web:build: 
web:build: ../../node_modules/@aws-sdk/s3-request-presigner/dist-es/index.js + 115 modules
web:build: Cannot get final name for export 'serializerMiddlewareOption' of ../../node_modules/@smithy/middleware-serde/dist-es/index.js
web:build: 
web:build: 
web:build: > Build failed because of webpack errors
```

Removing the `@aws-sdk/s3-request-presigner` dependency solves the issue but as the package is important for my application I'm stuck on an old next.js version.

These are my `aws-sdk` dependencies:
```
    "@aws-sdk/s3-presigned-post": "3.465.0",
    "@aws-sdk/client-s3": "3.465.0",
    "@aws-sdk/s3-request-presigner": "3.465.0",
```

### SDK version number

"@aws-sdk/s3-request-presigner": "3.465.0"

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.10.0

### Reproduction Steps

I have an open PR in my Next.js monorepo facing this bug as build error:
https://github.com/formbricks/formbricks/pull/1746

### Observed Behavior

Build throws an error

### Expected Behavior

build finishes without erros

**Comment by RanVaknin** [comment]
Hi @mattinannt ,

I'm not able to reproduce the observed behavior. Here is how I attempted to reproduce:

```console
$ npx create-next-app@latest 5540 && cd 5540    
Need to install the following packages:
  create-next-app@14.0.3
Ok to proceed? (y) y
✔ Would you like to use TypeScript? … No / Yes
✔ Would you like to use ESLint? … No / Yes
✔ Would you like to use Tailwind CSS? … No / Yes
✔ Would you like to use `src/` directory? … No / Yes
✔ Would you like to use App Router? (recommended) … No / Yes
✔ Would you like to customize the default import alias (@/*)? … No / Yes
Creating a new Next.js app in /Users/rvaknin/test_folder/5540.

Using npm.

Initializing project with template: app-tw 


Installing dependencies:
- react
- react-dom
- next

Installing devDependencies:
- typescript
- @types/node
- @types/react
- @types/react-dom
- autoprefixer
- postcss
- tailwindcss
- eslint
- eslint-config-next


added 333 packages, and audited 334 packages in 10s

117 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Initialized a git repository.

Success! Created 5540 at /Users/rvaknin/test_folder/5540

$ npm i @aws-sdk/s3-presigned-post @aws-sdk/client-s3 @aws-sdk/s3-request-presigner

added 105 packages, and audited 439 packages in 3s

118 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
$ npm run build


> 5540@0.1.0 build
> next build

   ▲ Next.js 14.0.3

 ✓ Creating an optimized production build    
 ✓ Compiled successfully
 ✓ Linting and checking validity of types    
 ✓ Collecting page data    
 ✓ Generating static pages (5/5) 
 ✓ Collecting build traces    
 ✓ Finalizing page optimization    

Route (app)                              Size     First Load JS
┌ ○ /                                    5.16 kB          89 kB
└ ○ /_not-found                          876 B          84.7 kB
+ First Load JS shared by all            83.9 kB
  ├ chunks/472-b67f79dbdd2c1fe1.js       28.7 kB
  ├ chunks/fd9d1056-7b52db27cfdaff1f.js  53.3 kB
  ├ chunks/main-app-28cb448aac6fb86e.js  218 B
  └ chunks/webpack-327c219bf3d3ad2c.js   1.65 kB


○  (Static)  prerendered as static content

```

Since there are no reproduction steps in your issue description, I'm not sure if our setup is the same, but what I suspect happened here is there might be some dependency in your dependency tree that is out of sync with the rest?
Try to delete `node_modules` and `package-lock.json` and run `npm install` again and rebuild the project.

Thanks,
Ran~

**Comment by jhylmb** [comment]
Same problem here

- yarn workspaces
- next: 13.5.6 to 14.0.4

```
➜  web git:(next14) ✗ yarn build
yarn run v1.22.19
$ next build
   ▲ Next.js 14.0.4
   - Environments: .env

Failed to compile.

../../node_modules/@aws-sdk/s3-request-presigner/dist-es/index.js + 115 modules
Cannot get final name for export 'serializerMiddlewareOption' of ../../node_modules/@smithy/middleware-serde/dist-es/index.js


> Build failed because of webpack errors
```bash

**Comment by RanVaknin** [comment]
Hi @mattinannt ,

Can you check if @jhylmb's comment helped out?

Thanks,
Ran~

**Comment by mattinannt** [comment]
@jhylmb thanks a lot!
```
experimental: {
  serverComponentsExternalPackages: ['@aws-sdk'],
},
```
did the trick 🚀🎉🙏
