### ISSUE TITLE
Possible memory leaks in the SQSClient

### ISSUE THREAD

**Issue by yehor-manzhula** [aws/aws-sdk-js-v3#5541]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Describe the bug
We are experiencing memory issues with the SQSClient.
The issue is similar to one that was reported before [Memory leaks in the DynamoDBClient, and DynamoDBDocumentClient](https://github.com/aws/aws-sdk-js-v3/issues/5230)
but unfortunately it was closed with no solution.
I've read the discussion in the issue and created a [repository](https://github.com/yehor-manzhula/aws-sdk-memory-leak/tree/main) with an example that reproduces the issue we faced.

The repo contains simple polling functionality from test SQS queue in two variations: [with forced garbage collection invocation](https://github.com/yehor-manzhula/aws-sdk-memory-leak/blob/main/src/aws-sdk-gc.js#L43) on each request and [without it.](https://github.com/yehor-manzhula/aws-sdk-memory-leak/blob/main/src/aws-sdk.js)
To be able to compare garbage collector behavior I've added test function that uses [built-in http request wrapped in a promise](https://github.com/yehor-manzhula/aws-sdk-memory-leak/blob/main/src/http-request.js) to reach localstack internal API in same two variations.

I know that V8 has some internal optimizations around garbage collector invocation to archive better throughput performance but I notice a behavior that I found strange:

### SDK version number

@aws-sdk/package-name@3.456.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.10.0

### Reproduction Steps

Clone example [repo](https://github.com/yehor-manzhula/aws-sdk-memory-leak/tree/main)
Make sure you have docker + docker-compose installed

Run `npm install`
Run `./run.sh ./src/aws-sdk-gc.js`

### Observed Behavior

Once you started "http request" function with forced GC invocation it consumes around 5.5 Mb memory slowly growing with some point where memory consumption stays stable for some time till value up to 20.5 Mb and than memory gets cleaned to the startup value. As to me it  looks like the memory got cleaned. (See screenshots)
![http request gc startup](https://github.com/aws/aws-sdk-js-v3/assets/5948294/ef2f63d3-182a-4eaa-9d47-29e7237fcbcf)
![http request gc clean up](https://github.com/aws/aws-sdk-js-v3/assets/5948294/085e1ba4-5adf-4761-8fe2-a3f151f4d277)

But if you run polling from SQS queue with forced GC invocation you'll notice almost the same behavior except memory never returns back to initial values you saw on startup, continues slowly growing up to 44.8Mb and stays on the same level.
![Memory consumption](https://github.com/aws/aws-sdk-js-v3/assets/5948294/e480a4fb-9542-4e89-ad64-32729c1018f9)

### Expected Behavior

Memory should be cleaned at some point.

**Comment by kuhe** [comment]
note to maintainers:

code wrapper for debugging memory leaks

```js
import { setFlagsFromString } from "v8";
import { runInNewContext } from "vm";

setFlagsFromString("--expose_gc");
const gc = runInNewContext("gc");

import { S3 } from "@aws-sdk/client-s3";
const s3 = new S3({
  region: "us-west-2",
});

setInterval(async () => {
  const mem = process.memoryUsage();
  console.log(mem.heapUsed.toLocaleString(), "of", mem.heapTotal.toLocaleString(), "bytes");

  // write code here you suspect causes a memory leak

  Array.from({ length: 250 }).map(async () => {
    //
  });

  gc();
}, 800);
```

**Comment by MajesticMug** [comment]
A possible solution to this was proposed on [an old issue](https://github.com/aws/aws-sdk-js/issues/610#issuecomment-102531679) where limiting the max number of sockets on the HTTP modules prevents the excessive memory growth:
```
var http = require('http');
http.globalAgent.maxSockets = 30;
var https = require('https');
https.globalAgent.maxSockets = 30;
```

**Comment by smoke** [comment]
The very same case (issue) affects ALL of the `@aws-sdk/client-*` packages, so in most cases it is better to do `client.destroy()` as noted here and in other places https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-lambda/src/LambdaClient.ts#L692-L699
```
  /**
   * Destroy underlying resources, like sockets. It's usually not necessary to do this.
   * However in Node.js, it's best to explicitly shut down the client's agent when it is no longer needed.
   * Otherwise, sockets might stay open for quite a long time before the server terminates them.
   */
  destroy(): void
```

**Comment by RanVaknin** [comment]
Hi @yehor-manzhula ,

I have tested SQS polling for about 15 minutes and have observed that the memory does increase from about 9mb to around 11mb but stays steady at around that mark, and occasionally observe reduction in the heap size, indicating garbage collection. I also used the `clinic` memory profiling tool and see that the memory consumption is steady:

<img width="1316" alt="image" src="https://github.com/user-attachments/assets/cabe352d-1f87-4740-8ca1-0f1eb9fdc578">

Also others on the thread have shared good pointers that may help get a more predictable memory usage from the SDK application.

If you have any data points for us to investigate, please let us know.

Thanks,
Ran~
