### ISSUE TITLE
kmsKeyArn is not required

### ISSUE THREAD

**Issue by suzukyz** [aws/aws-sdk-js-v3#5544]
### Describe the issue

```
sessionConfiguration: { // RetrieveAndGenerateSessionConfiguration
    kmsKeyArn: "STRING_VALUE", // required
},
```
When knowledge-base was created with AWS Managed Key, kmsKeyArn is not required.
So, this document make misunderstand.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/bedrock-agent-runtime/command/RetrieveAndGenerateCommand/

**Comment by kuhe** [comment]
sessionConfiguration is not required, but when provided, kmsKeyArn is required

**Comment by suzukyz** [comment]
Thanks. I understood. We need to see `RetrieveAndGenerateCommand Input` table
