### ISSUE TITLE
GetPolicyCommand and GetPolicyVersionCommand not working as expected with @aws-sdk/client-iot

### ISSUE THREAD

**Issue by vivek-doshi-genea** [aws/aws-sdk-js-v3#5549]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

**GetPolicyCommand  - Sample Code :**

```
const { IoTClient, GetPolicyCommand } = require("@aws-sdk/client-iot"); // CommonJS import

const client = new IoTClient({
    region: 'us-east-1',    
    credentials: {
        accessKeyId: 'xxxxxx',
        secretAccessKey : 'xxxxxx',
    },
});

const command = new GetPolicyCommand({
    policyName: "my-policy"
});

const response = await client.send(command);

console.log('response', response);
```

Throwing Error :
```
ResourceNotFoundException: Policy default version not found
    at de_ResourceNotFoundExceptionRes (D:\Projects\SampleProjects\aws-client-iot-sdk\node_modules\@aws-sdk\client-iot\dist-cjs\protocols\Aws_restJson1.js:17419:23)   
    at de_GetPolicyCommandError (D:\Projects\SampleProjects\aws-client-iot-sdk\node_modules\@aws-sdk\client-iot\dist-cjs\protocols\Aws_restJson1.js:11773:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async D:\Projects\SampleProjects\aws-client-iot-sdk\node_modules\@smithy\middleware-serde\dist-cjs\deserializerMiddleware.js:7:24
    at async D:\Projects\SampleProjects\aws-client-iot-sdk\node_modules\@aws-sdk\middleware-signing\dist-cjs\awsAuthMiddleware.js:30:20
    at async D:\Projects\SampleProjects\aws-client-iot-sdk\node_modules\@smithy\middleware-retry\dist-cjs\retryMiddleware.js:31:46
    at async D:\Projects\SampleProjects\aws-client-iot-sdk\node_modules\@aws-sdk\middleware-logger\dist-cjs\loggerMiddleware.js:7:26
    at async D:\Projects\SampleProjects\aws-client-iot-sdk\index.js:21:22 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 404,
    requestId: 'c3cbecea-xxxx-4fd0-ae1f-92b9f3e4ed40',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}
```

And Command doesn't accept any other parameter than `policyName`.

--------

**GetPolicyVersionCommand - Sample Code**

```
const { IoTClient, GetPolicyVersionCommand} = require("@aws-sdk/client-iot"); // CommonJS import

const client = new IoTClient({
    region: 'us-east-1',    
    credentials: {
        accessKeyId: 'xxxxxx',
        secretAccessKey : 'xxxxxx',
    },
});

const command = new GetPolicyVersionCommand({
    policyName: "my-policy",
    policyVersionId: "1"
});

const response = await client.send(command);

console.log('response', response);
```

Throws error :
```
ResourceNotFoundException: Policy not found
    at de_ResourceNotFoundExceptionRes (D:\Projects\SampleProjects\aws-client-iot-sdk\node_modules\@aws-sdk\client-iot\dist-cjs\protocols\Aws_restJson1.js:17419:23)   
    at de_GetPolicyVersionCommandError (D:\Projects\SampleProjects\aws-client-iot-sdk\node_modules\@aws-sdk\client-iot\dist-cjs\protocols\Aws_restJson1.js:11829:25)   
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async D:\Projects\SampleProjects\aws-client-iot-sdk\node_modules\@smithy\middleware-serde\dist-cjs\deserializerMiddleware.js:7:24
    at async D:\Projects\SampleProjects\aws-client-iot-sdk\node_modules\@aws-sdk\middleware-signing\dist-cjs\awsAuthMiddleware.js:30:20
    at async D:\Projects\SampleProjects\aws-client-iot-sdk\node_modules\@smithy\middleware-retry\dist-cjs\retryMiddleware.js:31:46
    at async D:\Projects\SampleProjects\aws-client-iot-sdk\node_modules\@aws-sdk\middleware-logger\dist-cjs\loggerMiddleware.js:7:26
    at async D:\Projects\SampleProjects\aws-client-iot-sdk\index.js:18:22 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 404,
    requestId: 'dbbe1aa4-xxxx-4b91-a528-ddeb47b963ea',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}
```

### SDK version number

@aws-sdk/client-iot@3.465.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node.js v18.12.1

### Reproduction Steps

You can just run above given code with `accessKeyId` and `secretAccessKey` and with existing `policyName`, and make sure we are importing function from `@aws-sdk/client-iot`

### Observed Behavior

Throwing error while fetching policy details.

### Expected Behavior

Should be returning policy details based on `policyName`.

### Additional Information/Context

But it seems working with `@aws-sdk/client-iam`

```
const { IAMClient, GetPolicyCommand } = require("@aws-sdk/client-iam"); // CommonJS import

const client = new IAMClient({
    region: 'us-east-1',    
    credentials: {
        accessKeyId: 'xxxxxx',
        secretAccessKey : 'xxxxxx',
    },
});

const command = new GetPolicyCommand({
    PolicyArn: "arn:aws:iam::xxxxxxxxxx:policy/xyz",
});

const response = await client.send(command);

console.log('response', response);
```

**Comment by aBurmeseDev** [comment]
Hi @vivek-doshi-genea - thanks for reaching out. 

I wasn't able to reproduce the issue and It sounds like you're only running into the error with `client-iot` which get me thinking that might be IAM permission related. [Here](https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsiot.html#awsiot-actions-as-permissions) is the table that shows the actions and policy required to perform the operations. I copied the policies that needs permission to run `AttachPolicy` and `GetPolicyCommand` below if you could confirm that you have those policie granted permissions to perform the commands you ran.


`GetPolicy` needs Read access to Resources type [policy](https://docs.aws.amazon.com/iot/latest/developerguide/iot-policy-actions.html)
`AttachPolicy` needs Permissions management access to Resources 
 types [cert](https://docs.aws.amazon.com/iot/latest/developerguide/x509-client-certs.html) and [thinggroup](https://docs.aws.amazon.com/iot/latest/developerguide/thing-groups.html)

Hope that helps,
John

**Comment by vivek-doshi-genea** [comment]
Hi @aBurmeseDev , thanks for prompt response and looking into it, really appreciated it.

Yes sure, I will double-check, but if it has something to do with permission then why `GetPolicyCommand `  and `GetPolicyVersionCommand` are working when imported from `@aws-sdk/client-iam` and not with `@aws-sdk/client-iot`

With same access key and secret key :

```
//
// Working fine with GetPolicyCommand and GetPolicyVersionCommand  
//
const { IAMClient, GetPolicyCommand, GetPolicyVersionCommand } = require("@aws-sdk/client-iam"); // CommonJS import
```


```
//
// Throwing error for GetPolicyCommand and GetPolicyVersionCommand  
//
const { IoTClient, GetPolicyCommand, GetPolicyVersionCommand  } = require("@aws-sdk/client-iot"); // CommonJS import
```

**Comment by aBurmeseDev** [comment]
Thanks for sharing additional details. @vivek-doshi-genea  A few more things to clarify: 

- Can you please make sure to specify the following actions in the `Action` element of an IAM policy statement when you attach `AWSIoTConfigAccess` policy to your IAM identities. See [here](https://docs.aws.amazon.com/iot/latest/developerguide/security-iam-awsmanpol.html) for reference.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "iot:GetPolicy",
                "iot:GetPolicyVersion",
            ],
            "Resource": "*"
        }
    ]
}
```
- Please make sure you're calling the same region where the policy is created. To double check and confirm, feel free to share screenshot of your policy, IAM policy from your AWS Console (any sensitive info redacted)
>And if it has something to do with permission then why GetPolicyCommand  and GetPolicyVersionCommand are working when imported from @aws-sdk/client-iam and not with @aws-sdk/client-iot

Good question. it's because they're not the same service and IAM is used to manage access to AWS services of which AWS IoT Core is one of them. IAM administrators control who can be authenticated (signed in) and authorized (have permissions) to use AWS IoT resources. In fact, you won't be able to call IoT Policy with `GetPolicyCommand` imported from `@aws-sdk/client-iam` and vice versa. I hope that makes sense.

If you'd like to read more about it, [here](https://docs.aws.amazon.com/iot/latest/developerguide/security-iam.html) is a good resource documentation for it.

Please let me know if you have any other questions.

**Comment by vivek-doshi-genea** [comment]
**_it's because they're not the same service and IAM is used to manage access to AWS services of which AWS IoT Core is one of them. IAM administrators control who can be authenticated (signed in) and authorized (have permissions) to use AWS IoT resources. In fact, you won't be able to call IoT Policy with GetPolicyCommand imported from @aws-sdk/client-iam and vice versa. I hope that makes sense._**

This is the answer!

I was not aware of that the policies created from AWS IAM and AWS IOT Core are different, 
And was trying to fetch the policy that was created via IAM through `@aws-sdk/client-iot`, that's whay it was not working.
Based on your suggestion now I've created a policy from `AWS IoT > Security > Policies`, and now it's working as expected.

Thanks, @aBurmeseDev for such great support!
