### ISSUE TITLE
On migrating from V2 to V3 SDK the S3 list object throws "Region is missing" error, and entering us-east-1 as default throws another error

### ISSUE THREAD

**Issue by himanshu-bhandoh** [aws/aws-sdk-js-v3#5564]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

My v2 list object works without the region being passed, but the same config fails on V3 with "Region is missing" on performing list objects.

When I pass the default s3 region ie us-east-1 as the region (for a bucket hosted on us-east-2), I get the error: “The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.”

So I need to pass the right region which in our case was us-east-2 for V3 SDK to work for us, but V2 works without the region being passed. Our issue is that we allow customers to connect to their S3 bucket via our service so we don't have their regions and V3 migration breaks all our customers unless they fix their region.

How can I make a V3 SDK request without passing the region or having it be resolved on the server?

V2 code looks like this:

export function getS3ClientSession(
  accessKeyId: string | undefined,
  secretAccessKey: string | undefined,
  sessionToken: string | undefined,
  s3ForcePathStyle: boolean | undefined,
  baseUrl: string | undefined,
) {
  const endpoint = baseUrl ? { endpoint: new aws.Endpoint(baseUrl) } : {}
  return new aws.S3({
    accessKeyId,
    secretAccessKey,
    sessionToken,
    s3ForcePathStyle,
    httpOptions: { proxy: getHttpProxy() },
    ...endpoint,
  })
}

V3 code looks like this:

export type S3ClientSessionParams = {
  accessKeyId: string
  secretAccessKey: string
  sessionToken?: string
  s3ForcePathStyle?: boolean
  baseUrl?: string
}

export async function getS3ClientSession(s3ClientSessionParams: S3ClientSessionParams): Promise<S3> {
  const { accessKeyId, secretAccessKey, sessionToken, s3ForcePathStyle, baseUrl } = s3ClientSessionParams
  const proxy = getHttpProxy()
  let agent
  if (proxy) {
    agent = new HttpsProxyAgent({
      proxy,
    })
  }
  const clientConfig: S3ClientConfig = {
    credentials: { accessKeyId, secretAccessKey, sessionToken },
    forcePathStyle: s3ForcePathStyle,
    requestHandler: new NodeHttpHandler({
      httpAgent: agent,
      httpsAgent: agent,
    }),
    endpoint: baseUrl,
  }

return new S3(clientConfig)

### SDK version number

@aws-sdk/client-s3@3.470.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.17.0

### Reproduction Steps

V2 code looks like this:
`
export function getS3ClientSession(
  accessKeyId: string | undefined,
  secretAccessKey: string | undefined,
  sessionToken: string | undefined,
  s3ForcePathStyle: boolean | undefined,
  baseUrl: string | undefined,
) {
  const endpoint = baseUrl ? { endpoint: new aws.Endpoint(baseUrl) } : {}
  return new aws.S3({
    accessKeyId,
    secretAccessKey,
    sessionToken,
    s3ForcePathStyle,
    httpOptions: { proxy: getHttpProxy() },
    ...endpoint,
  })
}
`

V3 code looks like this:
`
export type S3ClientSessionParams = {
  accessKeyId: string
  secretAccessKey: string
  sessionToken?: string
  s3ForcePathStyle?: boolean
  baseUrl?: string
}

export async function getS3ClientSession(s3ClientSessionParams: S3ClientSessionParams): Promise<S3> {
  const { accessKeyId, secretAccessKey, sessionToken, s3ForcePathStyle, baseUrl } = s3ClientSessionParams
  const proxy = getHttpProxy()
  let agent
  if (proxy) {
    agent = new HttpsProxyAgent({
      proxy,
    })
  }
  const clientConfig: S3ClientConfig = {
    credentials: { accessKeyId, secretAccessKey, sessionToken },
    forcePathStyle: s3ForcePathStyle,
    requestHandler: new NodeHttpHandler({
      httpAgent: agent,
      httpsAgent: agent,
    }),
    endpoint: baseUrl,
  }

return new S3(clientConfig)
`

### Observed Behavior

Covered above

### Expected Behavior

V3 SDK should work similar to V2 or allow a workaround?

### Possible Solution

Not sure

**Comment by himanshu-bhandoh** [comment]
Another update here is that I tried passing region as `aws-global` so as to circumvent this, but I got a different error:
"The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-east-2'".

Clearly AWS knows where my bucket is and what it expects (since it is expecting us-east-2)? Why not just use that instead of making a v3 client pass this? 😢

**Comment by himanshu-bhandoh** [comment]
I tried the fetch bucket location command to fetch the region so I can use that to create another client thereafter with the region:

const clientConfig: S3ClientConfig = {
    credentials: { accessKeyId, secretAccessKey, sessionToken },
    forcePathStyle: s3ForcePathStyle,
    requestHandler: new NodeHttpHandler({
      httpAgent: agent,
      httpsAgent: agent,
    }),
    endpoint: baseUrl ? baseUrl: undefined,
  }
  const s3 = new S3Client(clientConfig)
  const result: GetBucketLocationCommandOutput = await s3.send(new GetBucketLocationCommand({ Bucket: bucketName }));
  
  
And the command to fetch the region too fails on not passing the region 😢 

I assume I am missing something fundamental here at this point because this seems a bit too wrong.

**Comment by ryan65** [comment]
Hi Himanshu
see the issue I opened , some days before related also. 
#https://github.com/aws/aws-sdk-js-v3/issues/5554#top
there is a config property added in the recent versions, called followRegionRedirects (3.465.0 has this support).
simply set it to true in the your client configuration.
However it somethings crashes , and not sure how safe it is right. It works most of the time but for some reason fails in our CI environment.

**Comment by RanVaknin** [comment]
Hi @himanshu-bhandoh,

Thanks for reaching out. In v3, you are required to provide a region for any operation. 

>Clearly AWS knows where my bucket is and what it expects (since it is expecting us-east-2)? Why not just use that instead of making a v3 client pass this? 😢

The AWS _server_ does know where your bucket lives, but the SDK _is a client_ and has no knowledge of where your upstream resources live. 

In v2, you'd make the request to the wrong bucket, the server will return a 301 error with information about the correct region, and the SDK will implicitly do a second subsequent request to the region provided by the initial error.
This was introduced to v2 as a form of customization to support 301 redirect and does not exist in all of the SDKs. 

After many user requests, our team very recently added this functionality to v3, but since it was done implicitly in v2 and in fact causes multiple requests to be made in order to be directed at the correct region, it comes at an additional hidden cost. 
In order to make this more intentional, in v3 you have to explicitly enable this by setting `followRegionRedirects: true` in the config of your client, but as @ryan65 pointed out, there are so cases in which this would fail - mainly due to an oversight in how this was implemented.

I'll be closing this in favor of tracking a fix for this feature in #5554. Please check back on that issue in the near future for a fix.

Thanks,
Ran~

**Comment by himanshu-bhandoh** [comment]
@RanVaknin thanks for the context. 

For our business use case, we allow users to connect to their S3 bucket on our platform by saving their creds and bucket info which we store. We've not asked for their region thus far and have relied on the v2 redirect (unbeknownst to us). As such, for the sdk v3 migration, in order to backfill regions to not use the redirect in future, I assume using the [HeadBucket](https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadBucket.html) with followRegionRedirects param set will get the region that we can then store and reuse for any subsequent calls. Hope that sounds right!

**Comment by ryan65** [comment]
> @RanVaknin thanks for the context.
> 
> For our business use case, we allow users to connect to their S3 bucket on our platform by saving their creds and bucket info which we store. We've not asked for their region thus far and have relied on the v2 redirect (unbeknownst to us). As such, for the sdk v3 migration, in order to backfill regions to not use the redirect in future, I assume using the [HeadBucket](https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadBucket.html) with followRegionRedirects param set will get the region that we can then store and reuse for any subsequent calls (with no followRegionRedirects). Hope that sounds right!

@himanshu-bhandoh 
Just note that I would not currently fully rely on the flag  followRegionRedirects right now (at least not for production), since as I mentioned, I found cases where it does not work and even throws an exception, and this is still under investigation by Ran and AWS . 
Note that another issue when not providing the reigon , is that you will get get more latency because actually from what I saw  a request is sent , caught , the context modified to contain the region by extracting it from the response header, and then the request is resent.

**Comment by RanVaknin** [comment]
Hi,

> Note that another issue when not providing the region, is that you will get get more latency because actually from what I saw a request is sent , caught , the context modified to contain the region by extracting it from the response header, and then the request is resent. My personal advice to you if you have no way to pass the bucket region, would be to stay currently with v2 until this issue is fixed.

Again I want to reiterate that those redirects were happening in v2 as well, they were just implicit. Like I mentioned before this is made explicit in v3 because there is a cost associated with redirects and we wanted to make it more intentional.

There is no issue.
