### ISSUE TITLE
Possible memory leak when using getObject or headObject

### ISSUE THREAD

**Issue by Nicu-Ducal** [aws/aws-sdk-js-v3#5570]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Hello!

I've been using in my application the `getObject` and `headObject` functions, and daily i get an increase in memory in my application. After some days, I even get OOM errors.

The concept of my application is serving s3 files through an Express endpoint (GET file behavior).

Every day, my instance is increasing it's used memory. I should mention that a lot of GET requests are made to this instance. In other scenarios, where my instance isn't getting any requests, there is not seen an increase in memory.

### SDK version number

@aws-sdk/client-s3@3.456.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.14.0

### Reproduction Steps

```js
const getEndpoint = async (req, res) => {
  const file = req.params.file
  const params = {
    Bucket: bucketName,
    Key: file
  }

  try {
    await s3.headObject(params)
  } catch (err) {
    res.status(404).json({"message": "not found"})
  }

  const s3file = await s3.getObject(params)
  res.attachment(file);
  res.setHeader("Content-Type", "application/octet-stream");
  s3file.Body.pipe(res)
}
```

### Observed Behavior

The memory is filling up, without being freed

### Expected Behavior

The memory should not increase

**Comment by egoson** [comment]
I'm seeing the same behavior

It partially helps to correct the situation if you explicitly close the socket with `destroyInstance()`, but the memory leak still continues

**Comment by Nicu-Ducal** [comment]
That is awesome, thank you for the tip! Seems to be working bettern now!
