### ISSUE TITLE
S3Client initialization failes for credentials fromEnv()

### ISSUE THREAD

**Issue by skew202** [aws/aws-sdk-js-v3#5574]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When creating an S3Client with the aws-sdk the initialisation failes for **UA_APP_ID_ENV_NAME** in `@smithy/node-config-provider`

### Expected Behavior

A successfully initialized **S3Client** using the variables available in the `process.env`

### SDK version number

3.470.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

 v18.17.0

### Reproduction Steps

.env
```sh
AWS_ACCESS_KEY_ID=ABC1234567890
AWS_SECRET_ACCESS_KEY=Abcd1234567890
AWS_REGION=eu-central-1
```

.index.js
```js
import { S3Client } from "@aws-sdk/client-s3";
import { fromEnv } from "@aws-sdk/credential-providers";

const s3Client = new S3Client({
    credentials: fromEnv()
});
```

### Observed Behavior

```js
Exception has occurred: CredentialsProviderError: Cannot load config from environment variables with getter: (env) => env[exports.UA_APP_ID_ENV_NAME]
  at /node_modules/@smithy/node-config-provider/dist-cjs/fromEnv.js:14:15
    at /node_modules/@smithy/property-provider/dist-cjs/chain.js:12:39
    at coalesceProvider (/node_modules/@smithy/property-provider/dist-cjs/memoize.js:11:23)
    at /node_modules/@smithy/property-provider/dist-cjs/memoize.js:26:34
    at defaultUserAgent (/node_modules/@aws-sdk/util-user-agent-node/dist-cjs/index.js:34:7)
    at getRuntimeConfig (/node_modules/@aws-sdk/client-s3/dist-cjs/runtimeConfig.js:39:57)
    at new S3Client (/node_modules/@aws-sdk/client-s3/dist-cjs/S3Client.js:24:64)
```

### Expected Behavior

A successfully initialized **S3Client** using the variables available in the `process.env`

**Comment by aBurmeseDev** [comment]
Hi @skew202 - thanks for reaching out and apologies for not responding it sooner.

I was able to reproduce it and found out that you'd need to import SignatureV4 and use fromEnv method to provide credentials as shown below. The reason behind, I think, is because JS v3 is opt-in for the use of Sigv4 due to a large optional dependency on the `aws-crt` node bindings package. It doesn't automatically include nor dynamically import this package due to its size negatively affecting customer who don't need it.
```ts
import { S3Client, ListBucketsCommand } from "@aws-sdk/client-s3";
import { SignatureV4 } from "@smithy/signature-v4";
import { fromEnv } from "@aws-sdk/credential-providers";

const signatureV4 = new SignatureV4({
    credentials: fromEnv()
})
const s3Client = new S3Client({
    region: process.env.AWS_REGION
});

const listBuckets = new ListBucketsCommand({});
const response = await s3Client.send(listBuckets)
```
Hope that makes sense and if you have any further questions, please let me know!
Best,
John
