### ISSUE TITLE
Connection reset when uploading to S3 only in chromium

### ISSUE THREAD

**Issue by jakeleventhal** [aws/aws-sdk-js-v3#5589]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When I upload files to S3 in my application via safari, i have no issues. In Chrome and Arc, I get an "ERR_CONNECTION_RESET" error for larger files (~100mb+).

### SDK version number

@aws-sdk/(client-s3|client-sns|s3-presigned-post)@3.450.0

### Which JavaScript Runtime is this issue in?

Browser

### Details of the browser/Node.js/ReactNative version

v18.17.1

### Reproduction Steps

```ts
// my route for createPresignedUrl

  async (req: CreatePresignedUrlRequest, res: NextApiResponse<CreatePresignedUrlResponse>) => {
    const { parentFolderId: parentFolderIdRaw, fileInfo } = req.body;
    const parentFolderId = parentFolderIdRaw || null; // '' is not valid id

    const fileType = UploadUtils.getFileExtensionFromMimeType(fileInfo.fileType) as ImageFileType;

    const fileNameWithoutExtension = fileInfo.name.slice(0, fileInfo.name.lastIndexOf('.'));

    const fileId = crypto.randomUUID();

    const fileKey = UploadUtils.getFileKey(fileId, req.user.id, fileType);
    const url = UploadUtils.getFileUrl(fileId, req.user.id, fileType);
    const postConfig = await AWS.getPresignedUrl(
      UploadUtils.getFileKey(fileId, req.user.id, fileType),
      fileInfo.fileType,
      fileInfo.size
    );

    return res.status(200).send({
      fileConfig: {
        fileKey,
        fileType,
        id: fileId,
        name: fileNameWithoutExtension,
        parentFolderId,
        size: fileInfo.size,
        url,
        userId: req.user.id
      },
      postConfig
    });
  }
```
```ts
// my code that creates a presigned url, then posts it to s3
const uploadFile = async (file: File, parentFolderId: string | null) => {
  const {
    fileConfig,
    postConfig: { url, fields }
  } = await ServerlessAPI.createPresignedUrl({
    fileInfo: {
      fileType: file.type,
      name: file.name,
      size: file.size
    },
    parentFolderId
  });
  const formData = new FormData();
  Object.entries({ ...fields, file }).forEach(([key, value]) => {
    formData.append(key, value as unknown as string);
  });
  await axios.post(url, formData);
};
```

### Observed Behavior

In chrome/arc, i get an error saying "ERR_CONNECTION_RESET", but only for larger files (~100mb+). In safari it works as expected

### Expected Behavior

It works in chromium

**Comment by RanVaknin** [comment]
Hi @jakeleventhal ,

Thank you for reaching out. From your description, it appears that you are only using the SDK for generating a presigned URL, and the actual file uploading process is handled through Axios. Since the SDK's role is limited to creating the URL and the upload issues are occurring specifically in certain browsers (and is succeeding in others), the root cause is either related to the Axios HTTP request or browser-specific behaviors, rather than the SDK itself. 

I would recommend focusing your investigation on Axios and the browser settings for handling large file uploads. 

Thanks,
Ran~

**Comment by jakeleventhal** [comment]
Thanks for the thoughtful response @RanVaknin. I tried with the `fetch` API with no luck, and as mentioned only receive this error in Chromium, so I opened up an issue there: https://bugs.chromium.org/p/chromium/issues/detail?id=1513452
