### ISSUE TITLE
Does lambda still pull in aws-sdk if your only using v3?

### ISSUE THREAD

**Issue by kbradl16** [aws/aws-sdk-js-v3#559]
From my understanding lambdas pull in v2 of the aws-sdk (maybe always?) if you do not define your own version in package.json. 

Does v2 still get pulled in if you are using v3 of the aws-sdk in your lambda project?

**Comment by trivikr** [comment]
Yes, v2 SDK is available by default.

The versions of AWS SDK for JavaScript available in Lambda Node.js runtimes are documented in https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#w463aac27c21

**Comment by kbradl16** [comment]
but why? Does this not cause a problem? And how will this be avoided in future? If I pull in v3 I DO NOT WANT V2!
