### ISSUE TITLE
When adding a middleware to a S3Client instance, commands intercepted by the middleware are instances of object, instead of being instances of the original command

### ISSUE THREAD

**Issue by PChol22** [aws/aws-sdk-js-v3#5593]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When adding a `"initialize"` middleware to a `S3Client` instance, commands intercepted by the middleware are instances of `object`, instead of being instances of the original command.

This is problematic when implementing a cache middleware: 2 different commands (ex: `GetPublicAccessBlockCommand` and `GetBucketLifecycleConfigurationCommand`) with the same input (ex: `{ BucketName: 'abc' }`) will be interpreted as the same command when hashed, and one of them will return incoherent data.

**This problem doesn't happen in other clients like LambdaClient for example.**

### SDK version number

@aws-sdk/client-s3@3.474.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.16.1

### Reproduction Steps

```typescript
import {
  GetBucketLifecycleConfigurationCommand,
  S3Client,
} from '@aws-sdk/client-s3';

const s3Client = new S3Client({});
s3Client.middlewareStack.use({
  applyToStack: stack => {
    stack.add(
      next => async args => {
        console.log(args instanceof GetBucketLifecycleConfigurationCommand);

        return next(args);
      },
      { step: 'initialize' },
    );
  },
});

await s3Client.send(
  new GetBucketLifecycleConfigurationCommand({
    Bucket: 'test',
  }),
);
// Will log false <-- This is the problem
```

### Observed Behavior

In the middleware, args is an instance of `object`, instead of being an instance of `GetBucketLifecycleConfigurationCommand`.

This broken behaviour happens with every S3Client command I tried, but doesn't happen for any other client (Lambda, EventBridge...)

### Expected Behavior

Existing behaviour with clients like LambdaClient:

```typescript
import {
  GetFunctionConfigurationCommand,
  LambdaClient,
} from '@aws-sdk/client-lambda';

const lambdaClient = new LambdaClient({});
lambdaClient.middlewareStack.use({
  applyToStack: stack => {
    stack.add(
      next => async args => {
        console.log(args instanceof GetFunctionConfigurationCommand);

        return next(args);
      },
      { step: 'initialize' },
    );
  },
});

await lambdaClient.send(
  new GetFunctionConfigurationCommand({
    FunctionName: 'test',
  }),
);
// Will log true
```

Args of the middleware are an instance of the command that was intercepted

### Possible Solution

Dirty temporary workaround for those who are stuck:

Add an extra `commandName` parameter to the input of commands sent to the S3Client, that helps the middleware know what command it is intercepting

**Comment by PChol22** [comment]
After some investigation, seems like the usage of next({ ...args }) might be the reason of the issue in files packages/middleware-sdk-s3/src/check-content-length-header.ts
and
packages/middleware-sdk-s3/src/validate-bucket-name.ts

**Comment by kuhe** [comment]
The `async args => {}` part of the middleware has type HandlerArguments e.g. https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-smithy-types/Interface/InitializeHandlerArguments/.

It does not say `args` is the type of the input command, only that `args.input` is the type of the Command's input.
