### ISSUE TITLE
[client-cognito-identity-provider] UserNotFoundException not identifiable by "instanceof"

### ISSUE THREAD

**Issue by tmarcinkowski-logitech** [aws/aws-sdk-js-v3#5595]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Calling the client's `adminGetUser` method and checking thrown errors with `instanceof` doesn't work for the `UserNotFoundException` error in SDK v3. (as opposed to v2)

```
@aws-sdk/client-cognito-identity-provider@3.474.0
```

Consider this example:

```ts
import { CognitoIdentityProvider, UserNotFoundException } from '@aws-sdk/client-cognito-identity-provider';

const cognito = new CognitoIdentityProvider();

async function checkUser(): Promise<boolean> {
	try {
		await cognito.adminGetUser({ UserPoolId, Username });
		return true;
	} catch (e) {
		console.log({
			e,
			constrPrototype: e.constructor.prototype,
			nameMatch: e.name === 'UserNotFoundException',
			instanceMatch: e instanceof UserNotFoundException,
			errorMatch: e instanceof Error,
		});
		if (e instanceof UserNotFoundException) { // doesn't work
			return false;
		}
		throw e;
	}
}
```

The console output is:

```
{
  e: UserNotFoundException: User does not exist.
      at de_UserNotFoundExceptionRes (/Volumes/Work/xxx/node_modules/@aws-sdk/client-cognito-identity-provider/dist-cjs/protocols/Aws_json1_1.js:6581:23)
      at de_AdminGetUserCommandError (/Volumes/Work/xxx/node_modules/@aws-sdk/client-cognito-identity-provider/dist-cjs/protocols/Aws_json1_1.js:1342:25)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /Volumes/Work/xxx/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
      at async /Volumes/Work/xxx/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20
      at async /Volumes/Work/xxx/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46
      at async /Volumes/Work/xxx/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26 {
    '$fault': 'client',
    '$metadata': {
      httpStatusCode: 400,
      requestId: '5dd58674-474f-4bcc-b2b7-2b3a7fb23784',
      extendedRequestId: undefined,
      cfId: undefined,
      attempts: 1,
      totalRetryDelay: 0
    },
    __type: 'UserNotFoundException'
  },
  constrPrototype: [CognitoIdentityProviderServiceException [Error]],
  nameMatch: true,
  instanceMatch: false,
  errorMatch: true
}

```

### SDK version number

@aws-sdk/client-cognito-identity-provider@3.474.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.19.0

### Reproduction Steps

(code included in the description)

### Observed Behavior

(included in the description)

### Expected Behavior

`e instanceof UserNotFoundException` returning true

**Comment by kuhe** [comment]
I wasn't able to reproduce this. 

Your stack trace indicates you have reached the method `de_UserNotFoundExceptionRes`, which instantiates and returns the `UserNotFoundException` class. If you log the constructor itself, it should say

```js
e.constructor: [class UserNotFoundException extends CognitoIdentityProviderServiceException]
```

Prototype mismatch can be caused by nested dependencies or otherwise multiple copies of a dependency existing, or JS transforms like those done by Babel. 

Rather than debugging this issue, I recommend that you use the error name field as the switch for error handling. We have documentation out there that recommends the `instanceof` check, but ultimately the name field is better and we need to work on undoing that recommendation.

**Comment by tmarcinkowski-logitech** [comment]
Thanks for looking into this so quickly. Yeah, that's what I ended up with ultimately; I'm not happy with that solution, though :-) I agree that there's something weird going on and if it's only me, then fine.
