### ISSUE TITLE
waiter function defined without maxDelay behaves strangely.

### ISSUE THREAD

**Issue by ryan65** [aws/aws-sdk-js-v3#5602]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Hi 
In advance saying , not sure if this is a bug or by design.
I migrated my code to V3. 
we use the waitUntilTasksRunning to wait for the task to be running.
I configured the waiter options with minDelay 5 seconds and maxWaitTime 300.
I noticed something very strange with the backoff mechanism. 
In the logs I see, that sdk calls  DescribeTasks  at intervals that grow 5, 10 17 seconds , but after a few requests... suddenly there is a very large interval , can be 70 seconds , can be even 120 seconds.
this is some backoff !!!.
I fixed my code now to set maxDelay also and looks ok , however I wanted to ask , is this by design ? it looks pretty problematic that sudden jump to **120 seconds** from around 17, 20 seconds.
Here is an example of logs I printed to test this,  exponential growth. 5 , 9, 8, 21, and then suddenly 75. (and Ive seen higher numbers as well).

$$$$$$$$$$$$ Last Time Diff 5197  T1702999100926-ryanh_12345-scheduler-69
$$$$$$$$$$$$ Last Time Diff 9158  T1702999100926-ryanh_12345-scheduler-69
$$$$$$$$$$$$ Last Time Diff 8552  T1702999100926-ryanh_12345-scheduler-69
$$$$$$$$$$$$ Last Time Diff 21600  T1702999100926-ryanh_12345-scheduler-69
$$$$$$$$$$$$ Last Time Diff 75302  T1702999100926-ryanh_12345-scheduler-69

Second question.
Would it be possible to add another option to the waiter options , **initalDelay**. this makes sense since in many cases I know that it will take at least 20 30 seconds for the tasks to start running , so why poll unecessarily so early.
I would like the polling to start at a specified delay.
Thanks.

### SDK version number

@aws-sdk"@aws-sdk/client-ecs": "3.474.0"

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

NA

### Reproduction Steps

Nothing special , just call runTasks and wait for state task is running. probably needs tasks that take a little while . minute or two.

### Observed Behavior

backoff algorithm does seem smooth , sudden just to 120 seconds or so between calls.

### Expected Behavior

smoother backoff , or maybe enforce maxDelay because without it , it could confuse users.
add new parameter initialDelay , to wait before the first call. 

### Possible Solution

add initalDelay to the parameters.
enforce parameter maxDelay or limit it to something reasonable.

**Comment by RanVaknin** [comment]
Hi @ryan65,

What you are seeing here is the exponentialBackoffWithJitter function of the waiter's poller.

https://github.com/smithy-lang/smithy-typescript/blob/f0ff3b7cdb93ce607c3873bab9a553566e0aec0b/packages/util-waiter/src/poller.ts#L9-L13.

When the waiter retries it stretches the retry attempt exponentially. Using `maxDelay` is a way to control the upper limit of that delay. Since your max time is 300, it stretches out across that range, and without that max delay, it will basically grow exponentially the bigger that max time will be.

You can read more about it [here](https://smithy.io/2.0/additional-specs/waiters.html).
>Second question.
Would it be possible to add another option to the waiter options , initalDelay. this makes sense since in many cases I know that it will take at least 20 30 seconds for the tasks to start running , so why poll unecessarily so early.

I don't see a use case wide enough for us to introduce this as a customization to the waiter interface as its supposed to be unanimous across all SDKs (per the Smithy doc I linked earlier). Is anything preventing you from just sleeping the application yourself before the waiter call?

So something like:

```js
import { ECSClient, RunTaskCommand } from "@aws-sdk/client-ecs";
import { waitUntilTasksRunning } from "@aws-sdk/client-ecs"; // Ensure this is imported correctly

function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

async function main() {
    const ecsClient = new ECSClient({ region: 'us-east-1' });

    try {
        const response = await ecsClient.send(new RunTaskCommand(runTaskParams));

        await sleep(30000);

        const waiterOptions = {
            client: ecsClient,
            maxWaitTime: 300,
            maxDelay: 15,
            minDelay:5,
        };
        await waitUntilTasksRunning(waiterOptions, your_input);

        console.log("Task is now running");
    } catch (error) {
        console.error(error);
    }
}

main();
```

Thanks,
Ran~

**Comment by ryan65** [comment]
> Hi @ryan65,
> 
> Thanks for reaching out. What you are seeing here is the exponentialBackoffWithJitter function of the waiter's poller.
> 
> https://github.com/smithy-lang/smithy-typescript/blob/f0ff3b7cdb93ce607c3873bab9a553566e0aec0b/packages/util-waiter/src/poller.ts#L9-L13.
> 
> When the waiter retries it stretches the retry attempt exponentially. Using `maxDelay` is a way to control the upper limit of that delay. Since your max time is 300, it stretches out across that range, and without that max delay, it will basically grow exponentially the bigger that max time will be.
> 
> You can read more about it [here](https://smithy.io/2.0/additional-specs/waiters.html).
> 
> > Second question.
> > Would it be possible to add another option to the waiter options , initalDelay. this makes sense since in many cases I know that it will take at least 20 30 seconds for the tasks to start running , so why poll unecessarily so early.
> 
> I don't see a use case wide enough for us to introduce this as a customization to the waiter interface as its supposed to be unanimous across all SDKs (per the Smithy doc I linked earlier). Is anything preventing you from just sleeping the application yourself before the waiter call?
> 
> So something like:
> 
> ```js
> import { ECSClient, RunTaskCommand, waitUntilTasksRunning } from "@aws-sdk/client-ecs";
> 
> function sleep(ms) {
>     return new Promise(resolve => setTimeout(resolve, ms));
> }
> 
> async function main() {
>     const ecsClient = new ECSClient({ region: 'us-east-1' });
> 
>     try {
>         const response = await ecsClient.send(new RunTaskCommand(runTaskParams));
> 
>         await sleep(30000);
> 
>         const waiterOptions = {
>             client: ecsClient,
>             maxWaitTime: 300,
>             maxDelay: 15,
>             minDelay:5,
>         };
>         await waitUntilTasksRunning(waiterOptions, your_input);
> 
>         console.log("Task is now running");
>     } catch (error) {
>         console.error(error);
>     }
> }
> 
> main();
> ```
> 
> Let me know if you need anything else.
> 
> Thanks, Ran~

Hi Ran
Thanks very much for the detailed explaination regarding the backoff algorithm. Anyway with the max delay all seems Ok.
Regarding the initDelay , actually I am asking because I know that 2 other collegues I met from other teams I work with were also wondering why this option didn't exist since to all of us it seemed pretty logical to have . 
However , ofcourse it is no problem to implement this ourselves , just by an initial wait. who know maybe others will also request this here , and you might eventually decide to add it to all waiters :-).
Thanks alot for the great responses you give.
