### ISSUE TITLE
Where are we filling config object

### ISSUE THREAD

**Issue by bharathisunil** [aws/aws-sdk-js-v3#5603]
### Describe the issue

In the document of SignUpCommand for the line "const client = new CognitoIdentityProviderClient(config);" there is no clue on what should be the value for config object.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/cognito-identity-provider/command/SignUpCommand/

**Comment by kuhe** [comment]
The config is on the client, so refer back to the client page https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/cognito-identity-provider/, which has a description of the config on the bottom of the page.

The config can be empty if your region and credentials come from other sources, like a config file profile.

```js
const client = new Client({});
```
