### ISSUE TITLE
`Types of parameters 'event' and 'event' are incompatible.`

### ISSUE THREAD

**Issue by garysassano** [aws/aws-sdk-js-v3#5605]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

![image](https://github.com/aws/aws-sdk-js-v3/assets/10464497/4905a6ef-6182-4cab-a369-93f223f74660)

Full error:
```
Type '(event: S3Event) => Promise<APIGatewayProxyResult>' is not assignable to type 'APIGatewayProxyHandler'.
  Types of parameters 'event' and 'event' are incompatible.
    Property 'Records' is missing in type 'APIGatewayProxyEventBase<APIGatewayEventDefaultAuthorizerContext>' but required in type 'S3Event'.
```

### SDK version number

@aws-sdk/package-name@version, ...

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.18.2

### Reproduction Steps

It's not clear to me what kind of Lambda function handler and return type are accepted when using an `S3Event` event type.

### Observed Behavior

An error is returned.

### Expected Behavior

No error is returned.

**Comment by kuhe** [comment]
These types appear unrelated to the AWS SDK for JavaScript.

**Comment by garysassano** [comment]
@kuhe Where could I support for [this](https://www.npmjs.com/package/@types/aws-lambda)?

**Comment by garysassano** [comment]
@kuhe Where could I ask support for [this](https://www.npmjs.com/package/@types/aws-lambda)?

**Comment by RanVaknin** [comment]
Hi @garysassano 

This is the package https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/aws-lambda

The project name is `DefinitelyTyped` and like @kuhe mentioned, this is unrelated to the JS SDK. 

Thanks,
Ran~
