### ISSUE TITLE
Unable to pass global AbortController to @aws-sdk/lib-storage's Upload

### ISSUE THREAD

**Issue by fcoelho** [aws/aws-sdk-js-v3#5612]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

It's not possible to pass an instance of the global AbortController in nodejs because of a type mismatch in AbortSignal

### SDK version number

@aws-sdk/client-s3@^3.478.0,@aws-sdk/lib-storage@^3.478.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.19.0

### Reproduction Steps

This will show the type mismatch:

```ts
import { S3Client } from "@aws-sdk/client-s3";
import { Upload } from "@aws-sdk/lib-storage";

new Upload({
  client: new S3Client({}),
  params: {
    Bucket: "test",
    Key: "test",
  },
  abortController: new AbortController(),
});
```

And this is a file with package.json/index.ts/tsconfig.json that can be used to test: 
[repro.tar.gz](https://github.com/aws/aws-sdk-js-v3/files/13742634/repro.tar.gz)

### Observed Behavior

```console
root@b542993f081c:/code# yarn tsc --noEmit
yarn run v1.22.19
warning package.json: No license field
$ /code/node_modules/.bin/tsc --noEmit
index.ts:10:3 - error TS2322: Type 'AbortController' is not assignable to type 'import("/code/node_modules/@smithy/abort-controller/dist-types/AbortController").AbortController'.
  Types of property 'signal' are incompatible.
    Type 'AbortSignal' is missing the following properties from type 'AbortSignal': _aborted, abort

10   abortController: new AbortController(),
     ~~~~~~~~~~~~~~~

  node_modules/@aws-sdk/lib-storage/dist-types/types.d.ts:39:5
    39     abortController?: AbortController;
           ~~~~~~~~~~~~~~~
    The expected type comes from property 'abortController' which is declared here on type 'Options'


Found 1 error in index.ts:10

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected Behavior

No type errors

**Comment by RanVaknin** [comment]
Hi @fcoelho ,

Can you give this one a try?

```
import { AbortController } from "@smithy/abort-controller";
```

Thanks,
Ran~

**Comment by fcoelho** [comment]
Hi @RanVaknin, thanks, that does work.

It is a bit inconvenient for me to use that though. I'm creating the actual AbortController a few layers above this use and passing it to other resources along the way, similar to golang's `context.Context`.

For the time being I'll test wrapping the `@smithy/abort-controller` version so I can keep the rest of my code the same, e.g.:

```ts
import { AbortController as AwsAbortController } from "@smithy/abort-controller";

const abortController = new AbortController();
const awsAbortController = new AwsAbortController();

abortController.signal.addEventListener("abort", () => {
	awsAbortController.abort();
});
```

**Comment by RanVaknin** [comment]
Hi @fcoelho ,

Thanks for the follow up. I did check `lib-storage` history, and this is not a change that was introduced recently, AFAIK the`upload`'s options interface never worked with the global AbortController. 

Moving to backlog.

Thanks,
Ran~

**Comment by kuhe** [comment]
A fix is expected later today in the next release. The release notes will include mention of the #5843 pull request "https://github.com/aws/aws-sdk-js-v3/pull/5843".

**Comment by fcoelho** [comment]
The latest version of the SDK fixes this issue, thank you!
