### ISSUE TITLE
Upload blob file in react native ReadableStream doesn't exit

### ISSUE THREAD

**Issue by jkpandianbsetec** [aws/aws-sdk-js-v3#5615]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

 LOG  uploadS3>>>> {"ACL": "public-read", "Body": {"blob": {"_data": [Object]}, "name": 1703332949781, "type": "image/jpeg", "uri": "file:///storage/emulated/0/Android/data/com.upliftapps/files/Pictures/e914b6a7-7802-400a-9eff-24e14b4a150b.jpg"}, "Bucket": "bucket", "ContentType": "image/jpeg", "Key": "photos/1703332949781"}

>> I have picked file and converted file as blob and passed to body params but getting 
 LOG  [ReferenceError: Property 'ReadableStream' doesn't exist] ==error from uploads3
this error 
![image](https://github.com/aws/aws-sdk-js-v3/assets/154676389/e441cb11-f1eb-4185-9bb7-f97de9576481)
![image](https://github.com/aws/aws-sdk-js-v3/assets/154676389/8bbe7bd7-593b-4a5c-ae2c-c5329c0a155f)
![image](https://github.com/aws/aws-sdk-js-v3/assets/154676389/78ce888e-6ae2-4eb7-bb73-06c0db225cba)

### SDK version number

@aws-sdk/lib-storage

### Which JavaScript Runtime is this issue in?

React Native

### Details of the browser/Node.js/ReactNative version

react 18

### Reproduction Steps

- Select the file from android device
- Convert the selected file as blob
- Upload the blob using aws sdk v3 lib storage package

### Observed Behavior

Seems the aws sdk v2 s3.upload working fine but aws sdk v3 not working

### Expected Behavior

Seems the aws sdk v2 s3.upload working fine but aws sdk v3 not working. It should work like the v2 behaviour with progress bar

**Comment by RanVaknin** [comment]
Hi @jkpandianbsetec ,

I'm not a react native user, but Im a bit confused by two things:
1. not sure why you are using `fetch` to read from a local file, after a bit of researching online I found that you can use https://docs.expo.dev/versions/latest/sdk/filesystem/ if you are using Expo. so something like:

```js
    const fileContent = await FileSystem.readAsStringAsync(inputFile.path, { encoding: FileSystem.EncodingType.Base64 });
    const buffer = Buffer.from(fileContent, 'base64');
```

2. Im not sure why you are constructing a `fileObj`? You can just pass in the buffer directly:

```js
    new PutObjectCommand({
      Bucket: bucketName,
      Key: key,
      Body: buffer,
     // rest of params.
    });
```

Can you give this a try?

Thanks,
Ran~

**Comment by Joshandrews43** [comment]
Commenting because I have this issue as well, only in production. I use expo-dev-client in my react native app and even with a polyfill, this is not working on a physical device

**Comment by marcus-menezes** [comment]
I'm having this problem too, got this error: `ReferenceError: Property 'ReadableStream' doesn't exist` when i send a request to Cognito but has a error in the response. Response 200 working normally.

![image](https://github.com/aws/aws-sdk-js-v3/assets/71840100/373c0222-d2c4-45aa-b73a-0b484b50dd1d)
I´m using this libs for aws provider config.

I´m try to install web-streams-polyfill but don´t work.

Does anyone have any ideas?

**Comment by NorseGaud** [comment]
@marcus-menezes , you ever figure this out?

**Comment by abcarlisle** [comment]
Having this issue as well.

**Comment by NorseGaud** [comment]
@abcarlisle here is the fix https://stackoverflow.com/a/77744609/1875932

**Comment by NorseGaud** [comment]
@abcarlisle and how are you importing them in your code?

**Comment by abcarlisle** [comment]
> @abcarlisle and how are you importing them in your code?

My apologies that did fix it, I had another unrelated issue. I appreciate the help!

**Comment by RanVaknin** [comment]
Solution is mentioned [here](https://github.com/aws/aws-sdk-js-v3/issues/6269#issuecomment-2263940705). Closing.
Thanks,
Ran~
