### ISSUE TITLE
DescribeIdentityPoolCommand missing field (IdentityPoolArn)

### ISSUE THREAD

**Issue by thangdoominh** [aws/aws-sdk-js-v3#5619]
### Describe the issue

I used [DescribeIdentityPoolCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/cognito-identity/command/DescribeIdentityPoolCommand) with [@aws-sdk/client-cognito-identity](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-cognito-identity) for discovering the Identity Pool in AWS Cognito Identity. 

Package: `"@aws-sdk/client-cognito-identity": "^3.481.0"`

The document and the interface IdentityPool are missing `IdentityPoolArn`
![image](https://github.com/aws/aws-sdk-js-v3/assets/44288750/b2bd72d5-a5cb-4bc6-8d8a-144c440d4653)

My response when calling SDK:
![image](https://github.com/aws/aws-sdk-js-v3/assets/44288750/da5a7df8-7fde-46cd-a227-2f1c9728fcbd)

I saw the IdentityPoolArn in the response. This issue same problem with https://github.com/aws/aws-sdk/issues/669.

Currently, I am working a lot with AWS SDK (Javascript). So how can I help the AWS SDK or AWS Document , if I find the new one and have the same issue? 

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/cognito-identity/command/DescribeIdentityPoolCommand/

**Comment by RanVaknin** [comment]
Hi @thangdoominh ,

Im not sure why you opened another issue for the same problem.  The reason I moved your original issue opened on this repo to aws/aws-sdk is because this is the cross SDK repo. This issue is with modeling, therefore its a cross SDK problem. 

Closing in favor of tracking this issue there. 

Thanks,
Ran~

**Comment by thangdoominh** [comment]
Hi @RanVaknin, I got it. I didn't know it was a cross-SDK problem before. Thank you
