### ISSUE TITLE
ReferenceError: Property 'e' doesn't exist - @aws-sdk/client-cognito-identity-provider send command after refresh token expiration (expecting NotAuthorizedException: Refresh Token has expired])

### ISSUE THREAD

**Issue by cervebar** [aws/aws-sdk-js-v3#5623]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

We are checking for access token and refreshing - when the refresh token expiration in the "Proxy" AWS Cognito Userpool Client is triggered (for testing we have 1h), the error `Property 'e' doesn't exist ` is thrown instead of any meaningful message.

### SDK version number

`@aws-sdk/client-cognito-identity-provider : 3.481.0`

### Which JavaScript Runtime is this issue in?

React Native (with Hermes enabled)

### Details of the browser/Node.js/ReactNative version

`react-native: 0.72.6`

### Reproduction Steps

- 1) authenticate user with token and login
```js
export const initiateAuth = ({email, password}: InitiateAuthPayload): Promise<InitiateAuthCommandOutput> => {
  const input = getInitiateAuthInput({email, password})
  const command = new InitiateAuthCommand(input)

  const cognitoClient = new CognitoIdentityProviderClient(getCognitoConfig())
  return cognitoClient.send(command)
}

...
const authResult = (await initiateAuth({email, password})).AuthenticationResult
const {AccessToken, RefreshToken} = authResult
await setUserTokens(AccessToken, RefreshToken) // to some persistent storage
```
- 2) set refresh token expiration to shortest period (1h) for testing
<img width="512" alt="Screenshot 2023-12-29 at 11 14 20" src="https://github.com/aws/aws-sdk-js-v3/assets/2403914/c1809288-5f42-4bcc-94e4-f09959ec5787">

- 3) wait that period and do not log out
- 4) go back to app and initiate refresh token, catch exception

```js
import {
  CognitoIdentityProviderClient,
  InitiateAuthCommand,
  InitiateAuthCommandInput,
 ...
} from '@aws-sdk/client-cognito-identity-provider'

...
const refreshAccessToken = async (refreshToken: string): Promise<void> => {
  try {
    const refreshAccessTokenInput: InitiateAuthCommandInput = {
      AuthFlow: 'REFRESH_TOKEN_AUTH',
      AuthParameters: {REFRESH_TOKEN: refreshToken},
      ClientId: 'COGNITO_APP_CLIENT_ID_HERE',
      ClientMetadata: {locale: i18n.language},
    }
    const refreshAccessTokenCommand = new InitiateAuthCommand(refreshAccessTokenInput)

    const cognitoClient = new CognitoIdentityProviderClient({
      region: 'REGION_HERE',
      endpoint: 'COGNITO_ENDPOINT_URL_HERE',
    })
    await cognitoClient.send(refreshAccessTokenCommand)
  } catch (error) {
    console.log('error', error) //error will be logged here
    throw error
  }
}

... 
// get valid token for example from stored value
const token = getToken()
await refreshAccessToken(token)
```

### Observed Behavior

Error with message `Property 'e' doesn't exist ` is raised. This looks like some typescript, missing property or missing `?` issue, or maybe there is code somewhere inside which doesn't expect the refresh token expiration error and passes it to normal code flow.
Unfortunately, I couldn't dig that deep to find the root cause.

### Expected Behavior

Some other informative exception: `InternalErrorException` or `NotAuthorizedException` or own new exception type maybe `RefreshTokenExpirationException`.

In version `3.56.0` it's working and the error response is `[NotAuthorizedException: Refresh Token has expired]`

### Possible Solution

Best will be to throw own exception, something like `RefreshTokenExpirationException`, that we know it is this situation and can handle it properly in our code (typically we logout user).

### Additional Information/Context
Testing is very slow as we need to wait for 1h limit. So at least some info we get so far:
- `3.56.0` - working
- `3.212.0` - working
- `3.256.0` - not working
- `3.332.0` - not working
- `3.481.0` - not working

- not sure if it's relevant, but we are using Hermes in our porject

**Comment by RanVaknin** [comment]
Hi @cervebar ,

Before we jump into replicating the whole auth process can you please add this logging middleware to see if somewhere before the deserialization the service returns an unexpected field that causes this? 

If you can share the output with us that might give us some more insight as to where the issue is happening (Please make sure to redact any sensitive information):

```js
const cognitoClient = new CognitoIdentityProviderClient(getCognitoConfig())

cognitoClient.middlewareStack.add(next => async (args) => {
 console.log(args.request)
 const response = await next(args);
 console.log(response);
 return next(args);
}, {step: 'finalizeRequest'})

// rest of your code. 
```


My first suspicion is that there is a deserialization issue, where the error returned is not correctly deserialized and then `e` is undefined.

Thanks,
Ran~

**Comment by cervebar** [comment]
sure here it is:

request:
```
 LOG
 {
   "body":"{\"ClientId\":\"none\",\"Token\":\"TOKEN1234\",\"ClientMetadata\":{\"locale\":\"en-GB\"}}",
   "fragment":"undefined",
   "headers":{
      "amz-sdk-invocation-id":"12345-1234-1234-1234-12345",
      "amz-sdk-request":"attempt=1; max=3",
      "content-length":"1851",
      "content-type":"application/x-amz-json-1.1",
      "host":"someHASH.cloudfront.net",
      "user-agent":"aws-sdk-js/3.481.0 ua/2.0 os/other lang/js md/rn api/cognito-identity-provider#3.481.0",
      "x-amz-target":"AWSCognitoIdentityProviderService.RevokeToken",
      "x-amz-user-agent":"aws-sdk-js/3.481.0"
   },
   "hostname":"d2svuha93l885h.cloudfront.net",
   "method":"POST",
   "password":"undefined",
   "path":"/",
   "port":"undefined",
   "protocol":"https:",
   "query":{
      
   },
   "username":"undefined"
}
```
response:
```
LOG
{
   "output":{
      "$metadata":{
         "cfId":"someHASH",
         "extendedRequestId":"undefined",
         "httpStatusCode":200,
         "requestId":"someID"
      }
   },
   "response":{
      "body":{
         "_data":[
            "Object"
         ]
      },
      "headers":{
         "content-length":"2",
         "content-type":"application/x-amz-json-1.1",
         "date":"Mon, 08 Jan 2024 09:45:58 GMT",
         "via":"1.1 someHASH.cloudfront.net (CloudFront)",
         "x-amz-cf-id":"someHASH",
         "x-amz-cf-pop":"VIE50-P2",
         "x-amzn-requestid":"someID",
         "x-cache":"Miss from cloudfront"
      },
      "reason":"",
      "statusCode":200
   }
}

```

notes: our current most probable suspect is the Hermes engine

**Comment by RanVaknin** [comment]
Hi @cervebar ,

I apologize for the long wait. It seems like this error `Property 'e' doesn't exist -...` happens when an error is raised. 
The reason I wanted the logs from that middleware is to see what the error looks like before it gets deserialized by the SDK, but looking at the response that you have shared, it's a status 200 successful response and this error is not being raised. 

Since it has been a while, can you please update your SDK version, and see if the error is still being raised? If it is, try to capture the failed response with the middleware I shared. Successful responses are not helpful in this case because it seems to manifest in error parsing so we wont get any info about what is breaking in successful response logs.

Thanks,
Ran~
