### ISSUE TITLE
'ListBucketsCommand' is not assignable to parameter of type 'Command

### ISSUE THREAD

**Issue by rsarosh** [aws/aws-sdk-js-v3#5629]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

using "@aws-sdk/client-s3": "^3.484.0", and keep getting the error at send line

```
 let S3_Config = {
          region: process.env.S3_REGION,
          credentials: {
            accessKeyId:  process.env.S3_ACCESS_KEY_ID,
            secretAccessKey: process.env.S3_ACCESS_SECRET_KEY,
      },
    };
    const s3_client = new S3Client(S3_Config);

    const s3_params = {
      Bucket: process.env.S3_BUCKET_NAME , // required
      MaxKeys: 20,
    };

    const _command = new ListBucketsCommand(s3_params);
    const response = await s3_client.send(_command);
```

> Argument of type 'ListBucketsCommand' is not assignable to parameter of type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration>'. Type 'ListBucketsCommand' is missing the following properties from type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration>': input, middlewareStack, resolveMiddlewarets(2345)

### SDK version number

@aws-sdk/client-s3@3.484.0, ...

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node v20.10.0

### Reproduction Steps

As shown in question 

```
      let S3_Config = {
          region: process.env.S3_REGION,
          credentials: {
            accessKeyId:  process.env.S3_ACCESS_KEY_ID,
            secretAccessKey: process.env.S3_ACCESS_SECRET_KEY,
      },
    };
    const s3_client = new S3Client(S3_Config);

    const s3_params = {
      Bucket: process.env.S3_BUCKET_NAME , // required
      MaxKeys: 20,
    };

    const _command = new ListBucketsCommand(s3_params);
    const response = await s3_client.send(_command);
```

### Observed Behavior

Getting error message:

Argument of type 'ListBucketsCommand' is not assignable to parameter of type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration>'. Type 'ListBucketsCommand' is missing the following properties from type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration>': input, middlewareStack, resolveMiddlewarets(2345)

### Expected Behavior

Should't be getting error

**Comment by rsarosh** [comment]
Any update will be appreciated. This is a major library to read S3 in typescript, how can it have such an issue. It must be me, let me know if you would like me to check something.

**Comment by aBurmeseDev** [comment]
Hi @rsarosh - thanks for reaching out and for your patience. 

`ListBucketsCommand` doesn't require params like `Bucket` or `MaxKeys` because this command is only intended to list all the buckets owned by the authenticated sender of the request. With that said, you can pass in empty object into the command as shown below and it will work. 
```ts
    const _command = new ListBucketsCommand({});
    const response = await s3_client.send(_command);
```
Here's ListBucketsCommand documentation for your reference: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/command/ListBucketsCommand/

If your intention is to list out objects from a bucket, I would use [`ListObjectsV2Command`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/command/ListObjectsV2Command/) operation. 

Hope that helps,
John

**Comment by rsarosh** [comment]
Thanks John. I think, i am falling in some black hole of libraries mis-match.  Here are my libraries:

    "@aws-sdk/client-s3": "^3.485.0",
    "@aws-sdk/smithy-client": "^3.374.0",
    "@smithy/types": "^2.8.0",
    Node: v20.10.0
    tsc: 5.1.6
    
    const input = {};
    const _command = new ListBucketsCommand(input);
    const response = await s3_client.send(_command);  //ERROR!!

Still getting the error :  Argument of type 'ListBucketsCommand' is not assignable to parameter of type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>>'.
  Type 'ListBucketsCommand' is missing the following properties from type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>>': input, middlewareStack, resolveMiddleware

**Comment by aBurmeseDev** [comment]
Hi @rsarosh - thanks for getting back. It looks like you're assigning empty object as `input` where you could simply do this `ListBucketsCommand({})`. Here's full code:
```ts
import { S3Client, ListBucketsCommand } from "@aws-sdk/client-s3";

const S3_Config = {
    region: process.env.S3_REGION,
    credentials: {
    accessKeyId:  process.env.S3_ACCESS_KEY_ID,
    secretAccessKey: process.env.S3_ACCESS_SECRET_KEY,
    },
};
const s3_client = new S3Client(S3_Config);

const _command = new ListBucketsCommand({});
const response = await s3_client.send(_command);
```
Let me know if that works!

**Comment by rsarosh** [comment]
Thanks!! This deletion fixed the issue. I should have thought about it. By the way in your comment, you meant package-lock.json not package.json. Let's update your comment.

**Comment by aBurmeseDev** [comment]
Glad it worked out, closing now. Please do not hesitate to reach out again!
