### ISSUE TITLE
Requesting a signed url from MRAP returns a url where region is 'undefined' 

### ISSUE THREAD

**Issue by Giovanni-Ilacqua** [aws/aws-sdk-js-v3#5639]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The getSignedUrl function from @aws-sdk/s3-request-presigner returns a url with region 'undefined' when pointing to an MRAP ARN.
This bug is related to an already closed issue:
https://github.com/aws/aws-sdk-js-v3/issues/4335#issuecomment-1589863800

A workaround was suggested, but a proper solution has not been released yet.

### SDK version number

@aws-sdk/s3-request-presigner: "3.470.0"

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node v18.18.2

### Reproduction Steps

```
import { everything_relevant } from '@aws-sdk/various-sdks';

const MRAP_ARN = 'arn:aws:s3::0123456789:accesspoint/my_mrap_id.mrap';

const client = new S3Client({
  region: 'us-east-2,
  disableMultiregionAccessPoints: false,
  credentials: {
    accessKeyId: env.ACCESS_KEY_ID as string,
    secretAccessKey: env.SECRET_ACCESS_KEY_ID as string
  }
});

export async function getPreSignedURLToGetFile(key: string): Promise<string> {
  const command = new GetObjectCommand({
    Bucket: MRAP_ARN,
    Key: key,
  });

  const url = await getSignedUrl(client, command);
  return url;
}
```

### Observed Behavior

The generated url has an invalid X-Amz-Credential parameter, because the region is 'undefined'
When the signed url is accessed, the following XML error is returned:

```
<Error>
<Code>AuthorizationQueryParametersError</Code>
<Message>Error parsing the X-Amz-Credential parameter; the region 'undefined' is wrong; expecting 'us-east-2'</Message>
<Region>us-east-2</Region>
<RequestId>GFYNHFPQSME0S905</RequestId>
<HostId>D11bpjcoZl4b7nYJkxxbfuUQT5zQ7rNNq5/8JDDvP00HghqPMAWgtHCo9GzXutooAXCZo8cy/04=</HostId>
</Error>
```

### Expected Behavior

I expect the signed url to have a valid X-Amz-Credential parameter, perhaps with the region being omitted from the url, or alternatively being set to the appropriate region determined by MRAP (aka the region with the closest available bucket).

### Possible Solution

As suggested in the related issue https://github.com/aws/aws-sdk-js-v3/issues/4335#issuecomment-1589863800
The workaround is to explicitly pass the signingRegion 
`const signedUrl = await getSignedUrl(client, getCommand,  {signingRegion: "us-east-1"});`

However I don't understand why this would be a suitable solution. I set up MRAP because I have replicating buckets in multiple regions and want clients to connect to the closest available bucket.
When a client accesses my app and needs to fetch a file on S3, I don't know which bucket is the closest, so how can I specify the appropriate signingRegion?

### Additional Information/Context

I had been using @aws-sdk/s3-request-presigner version 3.145.0 and never had any issues generating signed urls with MRAP.
I believe that version 3.145.0 works because the generated signed url does not include the region in the X-Amz-Credential parameter.

**Comment by RanVaknin** [comment]
Hi @Giovanni-Ilacqua,

Thanks for bringing this to our attention. I've looked a bit into it, and this seems like an issue with how the SDK presigns MRAP requests. Based on the documentation from S3, requests to MRAP need to be [signed with SigV4a](https://docs.aws.amazon.com/AmazonS3/latest/userguide/MultiRegionAccessPointRequests.html#MultiRegionAccessPointHostnames) which we do not do, and as you have pointed out, should be region agnostic. 

The workaround where you pass a signing region works because S3 somehow accepts the request even not in the correct format, kind of a false positive if you will. It might have to do with the buckets served under the MRAP, but I don't have visibility to how they validate signing on the server side.

I have also tested this against the Go v2 SDK and can see that it behaves correctly. For comparison:

**Go v2 SDK presigned MRAP URL:**
```
https://REDACTED.mrap.accesspoint.s3-global.amazonaws.com/key.txt?
X-Amz-Algorithm=AWS4-ECDSA-P256-SHA256&
X-Amz-Credential=REDACTED/20240104/s3/aws4_request&
X-Amz-Date=20240104T183543Z&
X-Amz-Expires=900&
X-Amz-Region-Set=*&
X-Amz-SignedHeaders=host&
x-id=GetObject&
X-Amz-Signature=********************************************************************************************************************************************************************************************
```

**JS SDK v3 presigned MRAP URL:**
```
https://REDACTED.mrap.accesspoint.s3-global.amazonaws.com/key.txt?
X-Amz-Algorithm=AWS4-HMAC-SHA256&
X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&
X-Amz-Credential=REDACTED/20240104/us-east-1/s3/aws4_request&
X-Amz-Date=20240104T184405Z&
X-Amz-Expires=900&
X-Amz-SignedHeaders=host&
x-id=GetObject&
X-Amz-Signature=************************************************************
```

In Go we use the correct signing algorithm (sigv4) and also, the `X-Amz-Region-Set` indicates that we have signed the region as "*" which seems correct.

We are going to further look into in order to root cause the issue.

THanks again,
Ran~

**Comment by Giovanni-Ilacqua** [comment]
Hi Ran, thank you for jumping on this so promptly!

Your comment about the Go SDK setting the signing region as `"*"` made me wonder if could explicitly pass `{signingRegion: "*"}` in the JS SDK V3

Well... it turns out this actually is the true workaround!
`const signedUrl = await getSignedUrl(client, getCommand, {signingRegion: "*"});`

Now the presigned MRAP URL looks correct:
```
https://REDACTED.mrap.accesspoint.s3-global.amazonaws.com/key.pdf?
X-Amz-Algorithm=AWS4-ECDSA-P256-SHA256&
X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&
X-Amz-Credential=REDACTED/20240106/s3/aws4_request&
X-Amz-Date=20240106T052714Z&
X-Amz-Expires=900&
X-Amz-Region-Set=*&
X-Amz-Signature=******************************************************************&
X-Amz-SignedHeaders=host&
x-id=GetObject
```

The `X-Amz-Credential` does not contain any region, and a new header has been added `X-Amz-Region-Set=*&` 
Just like in your Go example.

I am not sure if this is the intended behavior, but per my brief testing it seems to work fine 👍
