### ISSUE TITLE
MIGRATION ISSUE: Upload API stuck when uploading empty file readable stream

### ISSUE THREAD

**Issue by naeemshaikhtw** [aws/aws-sdk-js-v3#5652]
### Pre-Migration Checklist

- [X] I've read the [Migration Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/migrating-to-v3.html).
- [X] I've reviewed the upgrading notes and major version differences mentioned in [`UPGRADING.md`](https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md).
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for similar migration issues.

### Which JavaScript Runtime is this issue in?

Node.js (includes AWS Lambda)

### AWS Lambda Usage

- [ ] Yes, my application is running on AWS Lambda.
- [X] No, my application is not running on AWS Lambda.

### Describe the Migration Issue

The following upload script works fine when the file has some content, but gets stuck and never responds when the file is empty.
```js
const s3 = new S3({
  credentials: {
    accessKeyId: env.accessKeyId,
    secretAccessKey: env.secretAccessKey,
  }
  region: env.region,
  tls: env.sslEnabled,
  params: {
    ServerSideEncryption: env.s3ServerSideEncryption,
  },
  endpoint: env.s3Endpoint,
  forcePathStyle: env.s3ForcePathStyle,
  requestHandler: new NodeHttpHandler({
    socketTimeout: env.timeout,
  }),
});


function uploadFile(key, filePath, bucket){
   const params = {
      Key: key,
      Body: fs.createReadStream(filePath),
      Bucket: bucket
    };

    return new Upload({
      client: s3,
      params,
    }).done();
}
    
 ```
 
 Same thing used to work with v2 `s3.upload()` api. I tried some suggestions on the internet by specifying the contentType, Length, using passThrough streams but no luck so far.
 
 I am using latest versions for both client-s3 and lib-storage.
 
 Additional details I observed while debugging:
 1. the file actually gets uploaded to S3, just that upload function never returns on `done()`.
 2. I was able to find the[ exact line](https://github.com/aws/aws-sdk-js-v3/blob/main/lib/lib-storage/src/Upload.ts#L129) where it gets stuck. Its trying to upload using put command, and never returns.
 3. Not just the readable stream, even if i convert it to a buffer before upload or just pass empty string to the body `""`, even then the upload function hangs.

### Observed Differences/Errors

Upload should work for files with empty content

**Comment by RanVaknin** [comment]
Hi @naeemshaikhtw ,

I'm not able to reproduce the reported behavior.
I have tried both creating an empty file and uploading it, and passing an empty string for the body, and in both cases the upload succeeds:

```js
import { Upload } from "@aws-sdk/lib-storage";
import fs from 'fs';
import { S3Client } from '@aws-sdk/client-s3'

const client = new S3Client({
  region:"us-east-1"
})

try {
  const fileStream = fs.createReadStream("./emptyFile");
  const res = await new Upload({
        client: client,
        params: {
          Key: "emptyFile",
          Body: "",
          Bucket: "testbucket-5652"
        },
    }).done();

    const res2 = await new Upload({
      client: client,
      params: {
        Key: "emptyFile",
        Body: fileStream,
        Bucket: "testbucket-5652"
      },
  }).done();
    console.log(res.$metadata.httpStatusCode)
    console.log(res2.$metadata.httpStatusCode)
} catch (error) {
    console.error(error);
}
// 200
// 200
```

Based on the line you said is "getting stuck" it seems like the issue might be with resolving the custom endpoint you provided. Are you using S3 directly, or using an S3 clone? 

I even looked at the serialized request that the SDK sends when providing a custom endpoint, and both seem valid:

```
// request of sending a body with empty string

before sign:  HttpRequest {
  method: 'PUT',
  hostname: 'testbucket-5652.localhost',
  port: 4566,
  query: { 'x-id': 'PutObject' },
  headers: {
    'content-type': 'application/octet-stream',
    'content-length': '0',
    Expect: '100-continue'
  },
  body: <Buffer >,
  protocol: 'http:',
  path: '/emptyFile',
  username: undefined,
  password: undefined,
  fragment: undefined
}


// request of sending a body with a body of "foo"

before sign:  HttpRequest {
  method: 'PUT',
  hostname: 'testbucket-5652.localhost',
  port: 4566,
  query: { 'x-id': 'PutObject' },
  headers: {
    'content-type': 'application/octet-stream',
    'content-length': '3',
    Expect: '100-continue'
  },
  body: <Buffer 66 6f 6f>,
  protocol: 'http:',
  path: '/emptyFile2',
  username: undefined,
  password: undefined,
  fragment: undefined
}
```

Is there any other information you can provide us with regarding your environment in which you are running this code? If you are using an S3 clone like Digital Ocean Spaces or MinIO, it might be indicative of service side behavior hanging on empty bodies.

Thanks,
Ran~

**Comment by naeemshaikhtw** [comment]
@RanVaknin Thanks for looking into it.

I am using Minio on docker, the problem is that the same instance responds for empty files when using V2 aws sdk with `s3.upload()`, but gets stuck when i upgrade to any version 3.x.x.

I went into debugging the  node-http-handler, and seems like I do get 200 response from the http, but somewhere down the line the response is lost by aws-sdk and not returned to the program

my node version is v18.18.1,
aws-sdk: 3.489.0

**Comment by RanVaknin** [comment]
HI @naeemshaikhtw,

I suggest you add the following middleware hook:

```js
client.middlewareStack.add(next => async (args) => {
 console.log(args.request)
 const response = await next(args);
 console.log(response);
 return next(args);
}, {step: 'finalizeRequest'})
```

This will allow you to inspect the serialized request sent out by the SDK, and the raw http response sent by the server.
If you can see the raw response, but do not see the response resolving, it can mean that MinIO is sending the response in a format the SDK is not expecting. If you cannot see the raw response at all, then it never makes it to the SDK for deserialization and might be blocked on the container level.

At any rate, since this is not reproducible when using the S3 server itself, this is likely an issue with MinIO. We see issues with S3 clones whether it be changes made to S3 that they never implemented or edge cases, and therefore is not actionable by the SDK team. 

This situation of uploading empty files sounds like it can easily be avoided by checking if the file is empty prior to making the call to MinIO. Do you have a use case for uploading empty files?

Thanks,
Ran~

**Comment by naeemshaikhtw** [comment]
@RanVaknin 
makes sene. I added the middleware, and there is no response returned from `next`, so no 2nd console log appears. 
I can share the response from minio here. which i logged in node-http-handler [at this line](https://github.com/smithy-lang/smithy-typescript/blob/main/packages/node-http-handler/src/node-http-handler.ts#L87), I don't think there is anything wrong in minio response, can you please take a look

```
{
      response: HttpResponse {
        statusCode: 200,
        reason: 'OK',
        headers: {
          'accept-ranges': 'bytes',
          'content-length': '0',
          etag: '"d41d8cd98f00b204e9800998ecf8427e"',
          server: 'MinIO',
          'strict-transport-security': 'max-age=31536000; includeSubDomains',
          vary: 'Origin, Accept-Encoding',
          'x-amz-id-2': 'dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8',
          'x-amz-request-id': '17AA7086C4F476B1',
          'x-content-type-options': 'nosniff',
          'x-xss-protection': '1; mode=block',
          date: 'Mon, 15 Jan 2024 06:12:13 GMT'
        },
        body: IncomingMessage {
          _readableState: [ReadableState],
          _events: [Object: null prototype],
          _eventsCount: 1,
          _maxListeners: undefined,
          socket: [Socket],
          httpVersionMajor: 1,
          httpVersionMinor: 1,
          httpVersion: '1.1',
          complete: false,
          rawHeaders: [Array],
          rawTrailers: [],
          joinDuplicateHeaders: undefined,
          aborted: false,
          upgrade: false,
          url: '',
          method: null,
          statusCode: 200,
          statusMessage: 'OK',
          client: [Socket],
          _consuming: false,
          _dumped: false,
          req: [ClientRequest],
          [Symbol(kCapture)]: false,
          [Symbol(kHeaders)]: [Object],
          [Symbol(kHeadersCount)]: 24,
          [Symbol(kTrailers)]: null,
          [Symbol(kTrailersCount)]: 0
        }
      }
    }
