### ISSUE TITLE
[S3][Upload] : Wrong Location in response after multipart upload

### ISSUE THREAD

**Issue by Nicolas-Deleplace** [aws/aws-sdk-js-v3#5656]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I'm using an S3 bucket hosted on Clever Cloud with a default domain name (cellar-c2.services.clever-cloud.com/BUCKET_NAME). I've also set up a custom domain name for this bucket (https://my_custom_domain.com). When I upload an image in a single part, I encounter no issues and the returned URL (Location) is correct : 

**'$metadata': {
    httpStatusCode: 200,
    requestId: 'tx0000000000000083df111-00659d5878-24493169-default',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  ETag: '"b11d056a85bbcaf57285dcc1005d430a"',
  Bucket: 'MY_BUCKET_NAME',
  Key: 'small_2023_12_25_a_18_01_06_e74f207da5.png',
  Location: 'https://my_custom_domain.com/small_2023_12_25_a_18_01_06_e74f207da5.png'**

 However, when I upload a larger file (e.g., an MP3) using multi-part upload, the returned URL points to the original S3 bucket's domain name, not the custom domain, unlike with image uploads.
 
 **'$metadata': {
    httpStatusCode: 200,
    requestId: 'tx000000000000008b13dff-00659d5ce4-24492f23-default',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Bucket: 'MY_BUCKET_NAME',
  ETag: 'f52eccd501a127479b26adf05f95e4d4-10',
  Key: 'EP_2.mp3',
  Location: 'http://cellar-c2.services.clever-cloud.com/MY_BUCKET_NAME/EP_2.mp3)'**

### SDK version number

@aws-sdk/lib-storage@3.485.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.17.0

### Reproduction Steps

I have this code to test: 
```js
const upload = async (file, customParams = {}) => {
      const fileKey = getFileKey(file);
      const uploadObj = new libStorage.Upload({
        client: s3Client,
        params: {
          Bucket: config.params.Bucket,
          Key: fileKey,
          Body: file.stream || Buffer.from(file.buffer, "binary"),
          ACL: config.params.ACL,
          ContentType: file.mime,
          ...customParams
        }
      });
      const upload2 = await uploadObj.done();
      console.log(upload2.Location)
};
```
### Observed Behavior

For single-part file uploads, the function __uploadUsingPut (from the Upload.ts file in the lib-storage library) is used. This function correctly constructs the Location property of the response. However, for multi-part uploads, this function is not utilized. Instead, once all parts are sent, we use this function: result = await this.client.send(new CompleteMultipartUploadCommand(uploadCompleteParams));. However, this function does not construct the response in the same way, which can lead to issues.

### Expected Behavior

Regardless of the file upload method (multi-part or single-part), the returned response is constructed in the same manner to avoid discrepancies.

**Comment by RanVaknin** [comment]
Hi @Nicolas-Deleplace ,

Thanks for reaching out. 

>For single-part file uploads, the function __uploadUsingPut (from the Upload.ts file in the lib-storage library) is used. This function correctly constructs the Location property of the response. However, for multi-part uploads, this function is not utilized. Instead, once all parts are sent, we use this function: result = await this.client.send(new CompleteMultipartUploadCommand(uploadCompleteParams));. However, this function does not construct the response in the same way, which can lead to issues.

The response element `Location` you see is being deserialized directly from the service response, there is no endpoint unpacking logic in the deserializer as Location is just sent as a string. 

This can be one of two things:
1. Clever Cloud returns the wrong location. This is the first time I hear about Clever Cloud but I have seen many odd behaviors in other S3 clones like MinIO / DigitalOceanSpaces / and others, so this totally can be something their service side implementation does not yet support.

2. The SDK doesn't send the request correctly. Either a bug / or you might be missing something in your code.

It would be quite easy to rule out if we can inspect the serialized request going to the server. You can get that by adding this simple middleware hook after your S3 Client creation code:

```
s3Client.middlewareStack.add(next => args => {
    console.log('before sign: ' , args.request);
    return next(args);
}, {step: 'build'})
```

Additionally if you can share your complete code including imports and client creation both for multipart upload or with a single part, that would be really helpful.

Thanks,
Ran~
