### ISSUE TITLE
'AWS CRT binary not present' when using cloudfront-keyvaluestore in Lambda runtime

### ISSUE THREAD

**Issue by luukdobber** [aws/aws-sdk-js-v3#5663]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I am trying to use @aws-sdk/client-cloudfront-keyvaluestore in the NODEJS_20_X lambda runtime. Calling any of the keyvaluestore API's causes the error `AWS CRT binary not present in any of the following locations:\n\t/bin/linux-x64-glibc/aws-crt-nodejs`.

Before running into the error mentioned above, I ran in to the issues described in https://github.com/aws/aws-sdk-js-v3/issues/5576. I worked around that error with the changes mentioned in https://github.com/aws/aws-sdk-js-v3/issues/5576#issuecomment-1854958060. But then I ran into the `AWS CRT binary` error.

### SDK version number

@aws-sdk/client-cloudfront-keyvaluestore@3.485.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

NODEJS_20_X lambda runtime

### Reproduction Steps

Deploy a Lambda function with the following configuration (CDK):
```
const kvLambda = new NodejsFunction(this, 'KvsTestLambda', {
      entry: 'lib/lambdas/kvs-test.ts',
      runtime: lambda.Runtime.NODEJS_20_X,
      environment: {
        KVS_ARN: <insert KVS ARN>
      },
      bundling: {
        externalModules: [] // Force AWS SDK to be bundled, KeyValueStore is not yet available in the Lambda runtime version of @aws-sdk
      }
    })

kvLambda.addToRolePolicy(new cdk.aws_iam.PolicyStatement({
  actions: [
    'cloudfront-keyvaluestore:*',
    'cloudfront:*'
  ],
  resources: ['*']
}))
```

Lambda code:
```
import * as cloudfront from '@aws-sdk/client-cloudfront'
import * as kv from '@aws-sdk/client-cloudfront-keyvaluestore'
// https://github.com/aws/aws-sdk-js-v3/issues/5576
import { SignatureV4MultiRegion } from '@aws-sdk/signature-v4-multi-region'
import '@aws-sdk/signature-v4-crt'

export const handler = async (event) => {
  const kvStoreArn = process.env.KVS_ARN
  if (!kvStoreArn) {
    throw new Error('KVS_ARN is not defined')
  }

  // Test CloudFront API to make sure the problem is isolated to the cloudfront-keyvaluestore
  const cfClient = new cloudfront.CloudFrontClient()
  const distResult = await cfClient.send(new cloudfront.ListDistributionsCommand({}))
  console.log(JSON.stringify(distResult))

  // Call keyvaluestore API
  const kvClient = new kv.CloudFrontKeyValueStoreClient({
    signerConstructor: SignatureV4MultiRegion
  })
  const result = await kvClient.send(new kv.DescribeKeyValueStoreCommand({
    KvsARN: kvStoreArn
  }))

  console.log(JSON.stringify(result))
}
```

### Observed Behavior

The cloudfront.ListDistributionsCommand command works as expected, the kv.DescribeKeyValueStoreCommand results in an error:
```
{
    "errorType": "Error",
    "errorMessage": "AWS CRT binary not present in any of the following locations:\n\t/bin/linux-x64-glibc/aws-crt-nodejs",
    "stack": [
        "Error: AWS CRT binary not present in any of the following locations:",
        "\t/bin/linux-x64-glibc/aws-crt-nodejs",
        "    at node_modules/aws-crt/dist/native/binding.js (/var/task/index.js:42005:13)",
        "    at __require (/var/task/index.js:12:50)",
        "    at node_modules/aws-crt/dist/native/auth.js (/var/task/index.js:42448:38)",
        "    at __require (/var/task/index.js:12:50)",
        "    at node_modules/aws-crt/dist/index.js (/var/task/index.js:46048:30)",
        "    at __require (/var/task/index.js:12:50)",
        "    at node_modules/@aws-sdk/signature-v4-crt/dist-cjs/CrtSignerV4.js (/var/task/index.js:46174:21)",
        "    at __require (/var/task/index.js:12:50)",
        "    at node_modules/@aws-sdk/signature-v4-crt/dist-cjs/index.js (/var/task/index.js:46304:25)",
        "    at __require (/var/task/index.js:12:50)"
    ]
}
```

### Expected Behavior

I expect the kv.DescribeKeyValueStoreCommand to return a result.

**Comment by rr923** [comment]
I have the same issue when trying to use `client-cloudfront-keyvaluestore` with SST.

**Comment by aBurmeseDev** [comment]
Hi @luukdobber @rr923 - thanks for your patience.

I had attempted to reproduce this multiple times but was unable to. It's also strange that you mentioned it works for `cloudfront.ListDistributionsCommand` command and not `kv.DescribeKeyValueStoreCommand`. Were you able to locate the file for `aws-crt` at `locations:\n\t/bin/linux-x64-glibc/aws-crt-nodejs`. Can you check which version of `aws-crt` is installed?

Also to double check if you ran `npm install @aws-sdk/signature-v4-crt` to install the package: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-signature-v4-crt/
