### ISSUE TITLE
InvokeModelCommand does not accept anthropic.claude-v2:1:200k as a model ID

### ISSUE THREAD

**Issue by ataylorme** [aws/aws-sdk-js-v3#5665]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When calling the `InvokeModelCommand` command with `modelId: anthropic.claude-v2:1:200k` a validation error is returned

```
Error invoking the Claude model with AWS Bedrock ValidationException: 1 validation error detected: Value 'anthropic.claude-v2:1:200k' at 'modelId' failed to satisfy constraint: Member must satisfy regular expression pattern: (arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:(([0-9]{12}:custom-model/[a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}/[a-z0-9]{12})|(:foundation-model/[a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}([.:]?[a-z0-9-]{1,63}))|([0-9]{12}:provisioned-model/[a-z0-9]{12})))|([a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}([.:]?[a-z0-9-]{1,63}))|(([0-9a-zA-Z][_-]?)+)
```

`anthropic.claude-v2:1:200k` is in the list of models when calling list foundational models from AWS Bedrock

### SDK version number

@aws-sdk/client-bedrock-runtime@3.489.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.16.1

### Reproduction Steps

```typescript
const params: InvokeModelCommandInputType = {
   body,
   modelId: 'anthropic.claude-v2:1:200k',
   contentType: 'application/json',
  accept: 'application/json',
}
const command = new InvokeModelCommand(params)
const data = await client.send(command)
```

### Observed Behavior

```
Error invoking the Claude model with AWS Bedrock ValidationException: 1 validation error detected: Value 'anthropic.claude-v2:1:200k' at 'modelId' failed to satisfy constraint: Member must satisfy regular expression pattern: (arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:(([0-9]{12}:custom-model/[a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}/[a-z0-9]{12})|(:foundation-model/[a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}([.:]?[a-z0-9-]{1,63}))|([0-9]{12}:provisioned-model/[a-z0-9]{12})))|([a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}([.:]?[a-z0-9-]{1,63}))|(([0-9a-zA-Z][_-]?)+)
```

### Expected Behavior

The command is successful

**Comment by aBurmeseDev** [comment]
Hi @ataylorme - thanks for reaching out!

It looks like you're getting [service exception](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_InvokeModel.html#API_runtime_InvokeModel_Errors) around `modelID` param and according to the [docs](https://docs.aws.amazon.com/bedrock/latest/userguide/model-ids-arns.html) on the list of base model available, you might be using Anthropic Claude v2 model. In that case, you'd use `anthropic.claude-v2` as model ID param, also shown in the [table](https://docs.aws.amazon.com/bedrock/latest/userguide/model-ids-arns.html). 

Please refer to the [docs](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_InvokeModel.html#API_runtime_InvokeModel_Errors) on other type of models.
>The modelId to provide in the header depends on the type of model that you use.
>
>If you use a base model, specify the [model ID](https://docs.aws.amazon.com/bedrock/latest/userguide/model-ids-arns.html) or its ARN.
>
>If you use a provisioned model, specify the provisionedModelName or the provisionedModelArn that was returned from the creation of the Provisioned Throughput.
>
>If you use a custom model, first purchase Provisioned Throughput for it (for more information, see [Provisioned throughput](https://docs.aws.amazon.com/bedrock/latest/userguide/prov-throughput.html) in the Amazon Bedrock User Guide). Then specify the provisionedModelName or the provisionedModelArn that was returned from the creation of the Provisioned Throughput.

Hope it helps,
John

**Comment by ataylorme** [comment]
Thanks for the response John! I didn’t realize [provisioned throughout models](https://docs.aws.amazon.com/bedrock/latest/userguide/prov-throughput-models.html) had to be created and then the ARN sent instead of a model ID.

I will give that a try and re-open this issue if it isn’t working.
