### ISSUE TITLE
QueueAttributeName type and description mismatch

### ISSUE THREAD

**Issue by bfeltman** [aws/aws-sdk-js-v3#5671]
### Describe the issue

The type QueueAttributeName[] does not match the description for AttributeNames on ReceiveMessageCommand Input.  Please fix.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/sqs/command/ReceiveMessageCommand/

**Comment by aBurmeseDev** [comment]
Hi @bfeltman - thanks for reaching out. 

Could you please clarify if you're referring to the type being `List[]` or the values described? If it's the values, please note that the ones described are valid but they're not the full list. Here's the complete list of Valid Values from the [service API docs](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html#API_ReceiveMessage_RequestSyntax):
```
Valid Values: All | Policy | VisibilityTimeout | MaximumMessageSize | MessageRetentionPeriod | ApproximateNumberOfMessages | ApproximateNumberOfMessagesNotVisible | CreatedTimestamp | LastModifiedTimestamp | QueueArn | ApproximateNumberOfMessagesDelayed | DelaySeconds | ReceiveMessageWaitTimeSeconds | RedrivePolicy | FifoQueue | ContentBasedDeduplication | KmsMasterKeyId | KmsDataKeyReusePeriodSeconds | DeduplicationScope | FifoThroughputLimit | RedriveAllowPolicy | SqsManagedSseEnabled
```
Sorry about the confusion on the doc but hope this helps,
John

**Comment by sosafe-anas-bakro** [comment]
@aBurmeseDev this is import, in some cases we need `ApproximateReceiveCount` but we can not include it in `AttributeNames` as `QueueAttributeName` does not have it, we had to stay with an older version where AttributeNames is a string or use `All` but we don't want all attributes we only need `ApproximateReceiveCount`.

This is not just a documentation issue, the library needs to update or we can not use this version!

![image](https://github.com/aws/aws-sdk-js-v3/assets/125665650/86cc91bb-ea25-4d9b-bab9-e9d145c74fcd)
Notice here that the type does not include `ApproximateReceiveCount` which it should or use a string or a different type!
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/sqs/command/ReceiveMessageCommand/

**Comment by rawpixel-vincent** [comment]
<img width="797" alt="Screenshot 2024-01-16 at 16 12 43" src="https://github.com/aws/aws-sdk-js-v3/assets/22284209/c5e8a091-a531-4f62-8499-77bc605e082c">

But it works, receiving a message with
`message.Attributes.ApproximateReceiveCount === '1'`

the type should not be `AttributeNames?: QueueAttributeName[];` but `AttributeNames?: MessageSystemAttributeName[];`

in `@aws-sdk/client-sqs/dist-types/models/models_0.d.ts`

thank you

**Comment by sosafe-anas-bakro** [comment]
@rawpixel-vincent Thanks, the CI pipeline will fail due to having the wrong type, I can add an ignore rule but it still looks ugly.
I believe it is a tiny fix and an important one.

**Comment by kristof-kasa** [comment]
When can we expect a release of this?

**Comment by kuhe** [comment]
We cannot accept a contribution for changes to service models. They are pushed from AWS services and will overwrite any changes made only in this repository. 

If there is a type error it must be fixed by the SQS service. @aBurmeseDev please merge with https://github.com/aws/aws-sdk-js-v3/issues/5403 if this is the same issue.

**Comment by aBurmeseDev** [comment]
thanks @kuhe for pointing to the similar issue. It seems we already have communicated with service team to update their models and waiting for a fix from them. I will check in with the team for updates. 

I'll mark this as duplicate and close in favor of tracking the issue in https://github.com/aws/aws-sdk-js-v3/issues/5403
