### ISSUE TITLE
Helpful error message for validateSsoProfile in case of undefined

### ISSUE THREAD

**Issue by camitz** [aws/aws-sdk-js-v3#5679]
### Describe the feature

Currently `3.485.0`:

   CredentialsProviderError: Profile is configured with invalid SSO credentials. Required parameters "sso_account_id", "sso_region", "sso_role_name", "sso_start_url". Got sso_region, sso_start_url, sso_role_name, aws_access_key_id, aws_secret_access_key
   
...which is unhelpful if say `sso_account_id` is undefined.

### Use Case

In order to debug credential errors.

### Proposed Solution

Display undefined attributes.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.485.0

### Environment details (OS name and version, etc.)

Windows

**Comment by RanVaknin** [comment]
Hi @camitz ,

Thanks for reaching out. The current error message does list both the required parameters and the ones you've provided. 

"Profile is configured with invalid SSO credentials. Required parameters"
"sso_account_id"
 "sso_region"
 "sso_role_name"
 "sso_start_url"
 
 And also clearly shows the parameters you supplied:
"Got
sso_region
sso_start_url
sso_role_name
aws_access_key_id
aws_secret_access_key"

I'll discuss this with the rest of the team, but I want to set your expectation that even if this is approved, it might not get prioritized. Feature request prioritization is based on community engagement.

I see that you marked that you may be able to implement this yourself. If so, please feel free to raise a PR and I'll have someone from the team review it.

Thanks again,
Ran~

**Comment by camitz** [comment]
Hi,

Well, the error message only displays the attributes present in the object. They may still be undefined or similar. Apparently.

I may yet submit a PR.

Thanks,
Martin

Martin Camitz
***@***.*** | +46 702 21 37 49 | www.omegapoint.se
Omegapoint

________________________________
Från: Ran Vaknin ***@***.***>
Skickat: den 12 januari 2024 22:56
Till: aws/aws-sdk-js-v3 ***@***.***>
Kopia: Martin Camitz ***@***.***>; Mention ***@***.***>
Ämne: Re: [aws/aws-sdk-js-v3] Helpful error message for validateSsoProfile in case of undefined (Issue #5679)


Hi @camitz<https://github.com/camitz> ,

Thanks for reaching out. The current error message does list both the required parameters and the ones you've provided.

"Profile is configured with invalid SSO credentials. Required parameters"
"sso_account_id"
"sso_region"
"sso_role_name"
"sso_start_url"

And also clearly shows the parameters you supplied:
"Got
sso_region
sso_start_url
sso_role_name
aws_access_key_id
aws_secret_access_key"

I'll discuss this with the rest of the team, but I want to set your expectation that even if this is approved, it might not get prioritized. Feature request prioritization is based on community engagement.

I see that you marked that you may be able to implement this yourself. If so, please feel free to raise a PR and I'll have someone from the team review it.

Thanks again,
Ran~

**Comment by RanVaknin** [comment]
Hi @camitz ,

I have raised this issue with the team and the consensus was that the existing error is self explanatory as it outlines the expected argument and the actual arguments supplied, therefore we are not inclined to implement this feature at this time.

As I mentioned before, feel free to raise a PR to address this and we will review this.

Thanks again,
Ran~
