### ISSUE TITLE
TITLE FOR BUG REPORT

### ISSUE THREAD

**Issue by enisze** [aws/aws-sdk-js-v3#5680]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

This is my problem (only on vercel):
<img width="1181" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/15271433/d8960b57-b311-4801-802b-7722a1749e7a">

I had this problem locally, but deleting node_modules and reinstalling solved this issue for me. 

This is another post I found to this issue

https://github.com/aws/aws-sdk-js-v3/discussions/5261

### SDK version number

"@aws-sdk/client-cognito-identity-provider": "3.489.0",

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.17.1

### Reproduction Steps

basically trying to build on vercel.

### Observed Behavior

TypeError: (0 , protocol_http_1.getHttpHandlerExtensionConfiguration) is not a function
--
15:12:35.087 | at resolveRuntimeExtensions (/vercel/path0/node_modules/@aws-sdk/client-cognito-identity-provider/dist-cjs/runtimeExtensions.js:12:79)
15:12:35.087 | at new CognitoIdentityProviderClient (/vercel/path0/node_modules/@aws-sdk/client-cognito-identity-provider/dist-cjs/CognitoIdentityProviderClient.js:28:76)
15:12:35.087 | at new CognitoIdentityProvider (/vercel/path0/node_modules/@aws-sdk/client-cognito-identity-provider/dist-cjs/CognitoIdentityProvider.js:214:1)
15:12:35.087 | at 43011 (/vercel/path0/apps/proprate/.next/server/chunks/5101.js:5242:25)
15:12:35.087 | at __webpack_require__ (/vercel/path0/apps/proprate/.next/server/webpack-runtime.js:25:42)
15:12:35.087 | at /vercel/path0/apps/proprate/.next/server/chunks/5101.js:9318:87
15:12:35.087 | at __webpack_require__.a (/vercel/path0/apps/proprate/.next/server/webpack-runtime.js:89:13)
15:12:35.087 | at 5034 (/vercel/path0/apps/proprate/.next/server/chunks/5101.js:9308:21)
15:12:35.087 | at __webpack_require__ (/vercel/path0/apps/proprate/.next/server/webpack-runtime.js:25:42)
15:12:35.087 | at /vercel/path0/apps/proprate/.next/server/chunks/5101.js:6048:71
15:12:35.090 |  
15:12:35.090 | > Build error occurred
15:12:35.091 | Error: Failed to collect page data for /docs/api
15:12:35.092 | at /vercel/path0/node_modules/next/dist/build/utils.js:1156:15
15:12:35.092 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
15:12:35.092 | type: 'Error'
15:12:35.092 | }

### Expected Behavior

the build should go through

### Possible Solution

Somehow fix this type error?

**Comment by RanVaknin** [comment]
Hi @enisze ,

If removing node_moduels and reinstalling solved the issue, this likely means that your project was holding copies of the same dependency but with different versions. 

When you run `npm ls @aws-sdk/client-cognito-identity-provider` you should see a tree of all the dependencies that rely on this one and their version. If there is a mismatch, you'll have to make sure they all using the same version. You can use `npm dedupe` to fix that for you.

I'm not sure how you are using Vercel, and admittedly I'm not super familiar with it, but it seems like you can use it from serverless of front end bundling. Either of which should use a bundled version of your project containing the SDK code.
I would make sure that the local node.js project you have that is working, is the one that you are serving with Vercel.

Additionally, I would also raise this issue in the [Vercel Repos](https://github.com/vercel). I see that they also have a pretty active community, and they might be able to provide some Vercel-targeted advice. 

Let me know how it goes.

Thanks,
Ran~

**Comment by enisze** [comment]
@RanVaknin thank you for your help, it seems like a manual redeploy without using the build cache fixed the error.
