### ISSUE TITLE
MIGRATION ISSUE: v2 to v3 promises on s3 object resolving when there's network error

### ISSUE THREAD

**Issue by niiapa** [aws/aws-sdk-js-v3#5683]
### Pre-Migration Checklist

- [X] I've read the [Migration Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/migrating-to-v3.html).
- [X] I've reviewed the upgrading notes and major version differences mentioned in [`UPGRADING.md`](https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md).
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for similar migration issues.

### Which JavaScript Runtime is this issue in?

Browser

### AWS Lambda Usage

- [ ] Yes, my application is running on AWS Lambda.
- [X] No, my application is not running on AWS Lambda.

### Describe the Migration Issue

In v3, functions on the S3 object have their promises resolve incorrectly on network errors.
Whereas in v2, this behaviour did not happen and a network error would result in the promise rejecting and throwing an error. 
The behaviour was noticed in the `createMultipartUpload` and `uploadPart` functions however, I'm not sure if other functions are affected or the reason for this.

### Code Comparison

v2:
```
// Create s3 object...
s3 = new AWS.S3({
    credentials: awsCredentials,
    region: bucketRegion,
    httpOptions: {
      timeout: 7200000,
    },
    useAccelerateEndpoint: accelerateSupported,
    correctClockSkew: true,
  });
}

// Use s3 object to create multipart upload...
s3.createMultipartUpload(bucketParam).promise()
  .then((s3Data) => {...}
  .catch((e) => {...} // this catches network errors
```

v3:
```
// Create s3 object...
s3 = new S3({
  credentials: credentialsObj,
  region: bucketRegion,
  useAccelerateEndpoint: accelerateSupported,
});

// Use s3 object to create multipart upload...
s3.createMultipartUpload(bucketParam)
  .then((s3Data) => {...} // I'm having to manually check for uploadId existence here to see if the request actually completed
  .catch((e) => {...} // this DOES NOT catch network errors
```

### Observed Differences/Errors

v2 functions catch network errors in the catch block whereas the v3 versions don't appear to throw any errors on network errors. Network error being connection disabled or endpoint blocked so request doesn't make it through to AWS

**Comment by RanVaknin** [comment]
Hi @niiapa,

Can you please give us an example of what a network error might look like?

Thanks,
Ran~

**Comment by adamlis05** [comment]
Encountered this with SNS.publish. The publish command resolves without issue and a network error is thrown afterwards. 



InternalError: Request could not be completed	
node_modules/aws-sdk/lib/protocol/query.js:50:29 Request.extractError	
node_modules/aws-sdk/lib/sequential_executor.js:106:20 Request.callListeners	
node_modules/aws-sdk/lib/sequential_executor.js:78:10 Request.emit	
node_modules/aws-sdk/lib/request.js:686:14 Request.emit	
node_modules/aws-sdk/lib/request.js:22:10 Request.transition	
node_modules/aws-sdk/lib/state_machine.js:14:12 AcceptorStateMachine.runTo	
node_modules/aws-sdk/lib/state_machine.js:26:10 main	
node_modules/aws-sdk/lib/request.js:38:9 Request.<anonymous>	
node_modules/aws-sdk/lib/request.js:688:12 Request.<anonymous>	
node_modules/aws-sdk/lib/sequential_executor.js:116:18 Request.callListeners	
node_modules/aws-sdk/lib/sequential_executor.js:78:10 Request.emit	
node_modules/aws-sdk/lib/request.js:686:14 Request.emit	
node_modules/aws-sdk/lib/request.js:22:10 Request.transition	
node_modules/aws-sdk/lib/state_machine.js:14:12 AcceptorStateMachine.runTo	
node_modules/aws-sdk/lib/state_machine.js:26:10 main	
node_modules/aws-sdk/lib/request.js:38:9 Request.<anonymous>

**Comment by RanVaknin** [comment]
Hi @niiapa ,

I have disconnected my machine's access to the internet mid upload to simulate a network error and the behavior between v2 and v3 is the same. With networking errors, both SDKs will reject the promise and the error can be logged from a `catch` block.

v3 error:
```console
$ node sample.mjs
Multipart upload initiated RAsE.YnaSwdKrFyKIMIEkb5nj48JLpnxEZZMLac1VfDL8OW_EcbgfuEEh2AH7.KAXyY2AxAd.NUkSMF4lwrcCPUXKpw6q47KNo8CCkWLtsxzAeyUFjVeYR28VpLmzWXm
Part 1 uploaded "79b281060d337b9b2b84ccf390adcf74"
Upload failed Error: getaddrinfo ENOTFOUND testbucket-3650.s3.us-east-1.amazonaws.com
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'testbucket-3650.s3.us-east-1.amazonaws.com',
  '$metadata': { attempts: 2, totalRetryDelay: 0 }
}
```

v2 error:
```console
$ node v2sample.js
Multipart upload initiated ohHbEt2.zz022xBNgzuz4SS.3jkNMUbtcE5jEc7kXkpN9C1H093DfrnR0aeDs7gl2zafYJa4aW0hFYgUtW4M0sq.hAa2LGGR8YnXMe0VZuq8ev_YUcLaxdjTySPM.w.v
Part 1 uploaded "79b281060d337b9b2b84ccf390adcf74"
Upload failed UnknownEndpoint: Inaccessible host: `testbucket-3650.s3.amazonaws.com' at port `undefined'. This service may not be available in the `us-east-1' region.
    at Request.ENOTFOUND_ERROR (/Users/rvaknin/test_folder/5683/node_modules/aws-sdk/lib/event_listeners.js:612:46)
    at Request.callListeners (/Users/rvaknin/test_folder/5683/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/rvaknin/test_folder/5683/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/rvaknin/test_folder/5683/node_modules/aws-sdk/lib/request.js:686:14)
    at error (/Users/rvaknin/test_folder/5683/node_modules/aws-sdk/lib/event_listeners.js:443:22)
    at ClientRequest.<anonymous> (/Users/rvaknin/test_folder/5683/node_modules/aws-sdk/lib/http/node.js:100:9)
    at ClientRequest.emit (node:events:520:28)
    at ClientRequest.emit (node:domain:488:12)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:520:28) {
  code: 'UnknownEndpoint',
  region: 'us-east-1',
  hostname: 'testbucket-3650.s3.amazonaws.com',
  retryable: true,
  originalError: Error: getaddrinfo ENOTFOUND testbucket-3650.s3.amazonaws.com
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
    errno: -3008,
    code: 'NetworkingError',
    syscall: 'getaddrinfo',
    hostname: 'testbucket-3650.s3.amazonaws.com',
    region: 'us-east-1',
    retryable: true,
    time: 2024-08-05T21:51:03.545Z
  },
  time: 2024-08-05T21:51:03.545Z
}
```

Perhaps use `try / catch` instead of `.then().catch()` 

Thanks,
Ran~
