### ISSUE TITLE
Cannot import `fromIni` from credential-providers

### ISSUE THREAD

**Issue by jinglongwu** [aws/aws-sdk-js-v3#5685]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Similar to #3806 but it doesn't seem fixed.

Hi I have a react-native app trying to use Pinpoint to send notifications. these are the modules
```
    "@aws-sdk/client-pinpoint": "^3.485.0",
    "@aws-sdk/credential-providers": "^3.490.0",
```
in order to `new PinpointClient(config)`, I am trying to supply it with a credential by `fromIni` but it always appears to be undefined.

### SDK version number

@aws-sdk/credential-providers: 3.490.0

### Which JavaScript Runtime is this issue in?

React Native

### Details of the browser/Node.js/ReactNative version

node -v v20.5.1;  react-native-v 12.3.0

### Reproduction Steps

1. create a react native app
2. `npm install @aws-sdk/credential-providers`
3. do these code
```js
import { fromCognitoIdentity, fromEnv, fromHttp, fromIni, fromProcess } from "@aws-sdk/credential-providers"; 
console.log("fromIni", fromIni);
console.log("fromEnv", fromEnv);
console.log("fromProcess", fromProcess);
console.log("fromHttp", fromHttp);
console.log("fromCognitoIdentity", fromCognitoIdentity);
```

### Observed Behavior

I got output like these
```bash
 LOG  fromIni undefined
 LOG  fromEnv undefined
 LOG  fromProcess undefined
 LOG  fromHttp [Function fromHttp]
 LOG  fromCognitoIdentity [Function fromCognitoIdentity]
 ```

Somehow `fromHttp` and `fromCognitoIdentity` were exported successfully but `fromIni` and `fromEnv` are undefined.

### Expected Behavior

`fromIni` should be a function and providing credentials from `~/.aws/credentials`

**Comment by kuhe** [comment]
React Native does not have process, env, or ini files as valid sources of AWS credentials and profiles.
