### ISSUE TITLE
The requested module '@aws-sdk/client-sts' does not provide an export named 'AssumeRoleCommand'

### ISSUE THREAD

**Issue by jurijzahn8019** [aws/aws-sdk-js-v3#5692]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Since 495 the import from client sts is broken

Due to the fact, that package.json is missing exports field
The library always load cjs code instead of esm

And this cjs code is now somehow broken

### SDK version number

@aws-sdk/client-sts@3.495.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.9.0

### Reproduction Steps

Create file foo.mjs with contents

```js
import { AssumeRoleCommand } from "@aws-sdk/client-sts";
```

node ./foo.mjs

### Observed Behavior

import { Credentials, STSClient, STSClientConfig, AssumeRoleCommand } from "@aws-sdk/client-sts";
                                                  ^

SyntaxError: The requested module '@aws-sdk/client-sts' does not provide an export named 'AssumeRoleCommand'

### Expected Behavior

Should work as <= 3.494.0

### Possible Solution

Ideally add export field to the package.json like

```json
"exports": {
  "types": "./dist-types/index.d.ts",
  "import": "./dist-es/index.js",
  "require": "./dist-cjs/index.js"
}
```

**Comment by kuhe** [comment]
Hi, sorry, this was my mistake. The `dist-cjs` or commonjs exports of our packages are intended to be ESM compatible. 

To ensure this, the commonjs code must have form of annotation, in this case

```js
module.exports = {
  ...,
  AssumeRoleCommand,
  ...
};
```

A recent change to the export format to use esbuild lost some of these annotations, making the ESM loader unable to identify that the package does indeed export `AssumeRoleCommand`.

We will release a fix for this today. If you continue to use this version, the workaround is to use an import object.

```ts
import sts from "@aws-sdk/client-sts";

const { AssumeRoleCommand } = sts;
```

**Comment by kuhe** [comment]
A fix for this was released in https://www.npmjs.com/package/@aws-sdk/client-sts/v/3.496.0.
