### ISSUE TITLE
module does not provide an export named 'fromSSO'

### ISSUE THREAD

**Issue by alenocera** [aws/aws-sdk-js-v3#5693]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Hi, I'm using vite 5.0.11 and I'm trying to use retrieve credentials using fromSSO approach but the following issue appears:
`The requested module '/node_modules/.vite/deps/@aws-sdk_credential-providers.js?v=4d2ccf96' does not provide an export named 'fromSSO'`.

### SDK version number

@aws-sdk/credential-providers@3.495.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

20.10.0

### Reproduction Steps

```
import { fromSSO } from '@aws-sdk/credential-providers';
const credentials = await fromSSO({
  profile: '<my-profile>'
})();
```

```
const client = new S3Client({
  region: 'us-east-1',
  credentials,
});
```

### Observed Behavior

`Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/@aws-sdk_credential-providers.js?v=4d2ccf96' does not provide an export named 'fromSSO' at`

### Expected Behavior

My credentials are retrieved correctly in according with the SDK documentation.

**Comment by kuhe** [comment]
Actually, I'm having trouble reproducing this. What version of the SDK packages do you have?

Can you show your build configuration and build commands?

**Comment by kuhe** [comment]
I didn't reproduce it, but,
this release should address the issue: https://www.npmjs.com/package/@aws-sdk/credential-providers/v/3.496.0

**Comment by alenocera** [comment]
Hi kuhe, thanks for the update.
At the first touch seems that passing through the backend with the 3.496.0 the credentials are correctly retrieved, instead using FE side, nope. Anyway somehow using BE it is not a problem, my side.
So, what do you mean for "build commands"? I mean, I'm using the classical vite build with npm, with no special things.

**Comment by kuhe** [comment]
What are the reproduction steps and error for the front end issue you are referring to?

**Comment by alenocera** [comment]
Some as the first post. I've just updated the package with the last version released and into the console I received the same error:

`Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/@aws-sdk_credential-providers.js?v=4d2ccf96' does not provide an export named 'fromSSO' at`

Just import the lib, then set the configuration like the profile (sso) as defined into my local machine using the CLI tool and that's.

Sounds strange because passing through the BE this issue not appears (my BE developer tell me this).

**Comment by kuhe** [comment]
is this still affecting vite builds as of v3.515.0 or later?

**Comment by jcramb** [comment]
yes it seems like this is still failing on 3.523.0

**Comment by githubb404** [comment]
any update on this? i am experiencing the exact same issue as alenocera@ where the BE calls work but not from a react FE

**Comment by kuhe** [comment]
`fromSSO` is not available in the browser https://www.npmjs.com/package/@aws-sdk/credential-providers#fromsso.

What are you trying to do with the application? Could you create a minimal reproduction example repository?
