### ISSUE TITLE
SQS client not retrying when throttled

### ISSUE THREAD

**Issue by julrich1** [aws/aws-sdk-js-v3#5702]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When sending messages with SQS an encountering a throttling error (Request is throttled code: RequestThrottled) we are not seeing retries as expected. 

### SDK version number

@aws-sdk//client-sqs@3.245.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.17.1

### Reproduction Steps

This is difficult to reproduce because throttling on SQS requires a lot of traffic, but in production we have retries set to 10 via `maxAttempts: 10` in the constructor which should produce a very long retry window. When inspecting the lambdas that showed this issue, their run time was in the milliseconds (396ms in an example case) as opposed to minutes.

### Observed Behavior

Lambda run time should be in the minutes with 10 retries instead of sub 1-second

### Expected Behavior

Lambda run time that was at least a couple minutes (20 seconds is the max cap for retries) or had a successful SQS send operation.

**Comment by RanVaknin** [comment]
Hi @julrich1 ,

You are using a very old version of the SQS client. Are you able to update your SDK and if it solves the issue?
