### ISSUE TITLE
Chime Meeting ended automatically when 2nd attendee joined

### ISSUE THREAD

**Issue by Kick933** [aws/aws-sdk-js-v3#5705]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

ChimeMeetingId -: 8c3d37b4-40a3-49c8-b1a1-6af28fc02954

when the second attendee joined this meeting, it automatically ended for some reason. All following API requests after adding mediacapturepipeline to the meeting resulted in error saying-:
Meeting <a34f1196-935f-46eb-bbbb-ab04a78c2954> not found

This is unexpected. Though, I am using NodeJS 14, but still, this should not happen.
The meeting events also show that the both attendee joined meeting.

### SDK version number

"@aws-sdk/client-chime-sdk-media-pipelines": "^3.468.0",     "@aws-sdk/client-chime-sdk-meetings": "^3.468.0",

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

NodeJS 14

### Reproduction Steps

Only happened for 1 meeting. Unable to reproduce the error.

### Observed Behavior

All calls after the two attendees joined resulted in meeting not found error given by SDK.

### Expected Behavior

The calls should suceed

**Comment by RanVaknin** [comment]
Hi @Kick933 ,

Without seeing any code, logs or errors it's really difficult to advise you. I'm not familiar with the Chime API, but when a user joins the session there should be a log, either in the form of a request / response through the SDK, or a Cloudtrail event. 

Can you please provide a sample code example and articulate where in the code youre seeing the failure? 

Thanks,
Ran~

**Comment by Kick933** [comment]
We are yet to find the root cause for this. It wouldn't help closing this issue. It has not happended again. But we still think that finding the root cause is important for us.

**Comment by aBurmeseDev** [comment]
Hello @Kick933 - checking in here. I understand your previous response from February, indicating that the reported behavior is no longer occurring. However, I would like to inquire if there have been any new developments or reoccurrences of the issue.

If you require further assistance in investigating the root cause, it would be beneficial if you could provide a minimal code snippet or sample that can reproduce the problem. Additionally, any relevant logs or request data you can share would greatly aid our analysis.
