### ISSUE TITLE
progress handler to putObjectCommand

### ISSUE THREAD

**Issue by raykin** [aws/aws-sdk-js-v3#571]
I use @aws-sdk/client-s3-browser to put file to s3 on browser. My code is similar as
```typescript
    const params = {
      ACL: 'public-read',
      Bucket: environment.s3.bucket,
      Key: file_key,
      ContentType: file_obj.type,
      Body: file_obj
    }
    const putObjectCommand = new PutObjectCommand(params);
    putObjectCommand.on('httpUploadProgress', pe => console.log(pe))
    return this.s3_client.send(putObjectCommand).then(data => {
      return  file_key;
    }).catch(err => err)
```
I followed example in https://github.com/aws/aws-sdk-js/commit/084f676927b9cd3da337bd6d0d230680c138d73b 
, but it didn't work.  
I tried several other examples from stackoverflow answers, but none of them works.
I'm not sure if current release 0.1.0-preview.2 support progress handler.

**Comment by alexforsyth** [comment]
We don't support request progress anymore since we use fetchHttpHandler.

Our advice is to use the newly created `@awd-sdk/lib-storage` this is analogous to managed upload in aws sdk v2

**Comment by arturocanalda** [comment]
@alexforsyth 

I've trying to use  @aws-sdk/lib-storage today. It worked, but not for multipart files. 
For some reason uploading a 32MB file was always uploading 2 parts only (5MB each).
That works with `@aws-sdk/client-s3-browser`.

Has anyone reported this issue? (in case it's an issue and not a configuration feature) 

Thanks In advance.
