### ISSUE TITLE
MIGRATION ISSUE: Undocumented change in the behaviour of S3 client region redirects

### ISSUE THREAD

**Issue by andrejleitner** [aws/aws-sdk-js-v3#5712]
### Pre-Migration Checklist

- [X] I've read the [Migration Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/migrating-to-v3.html).
- [X] I've reviewed the upgrading notes and major version differences mentioned in [`UPGRADING.md`](https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md).
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for similar migration issues.

### Which JavaScript Runtime is this issue in?

Node.js (includes AWS Lambda)

### AWS Lambda Usage

- [X] Yes, my application is running on AWS Lambda.
- [X] No, my application is not running on AWS Lambda.

### Describe the Migration Issue

I didn't find the following mentioned in the migration guide or notes:

> So we deliberately removed the follow-the-redirect feature in v3.

Source: https://github.com/aws/aws-sdk-js-v3/issues/1807

### Observed Differences/Errors

`PermanentRedirect` error with v3: `The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.`

**Comment by siddsriv** [comment]
We've added a section for S3 Global Client and the `followRegionRedirects` flag (v3 only) in our `UPGRADING.md`.
