### ISSUE TITLE
MIGRATION ISSUE: When Using AWS SDK JS V3 listObjectsV2 It Does Not Work

### ISSUE THREAD

**Issue by TomerPacific** [aws/aws-sdk-js-v3#5717]
### Pre-Migration Checklist

- [X] I've read the [Migration Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/migrating-to-v3.html).
- [X] I've reviewed the upgrading notes and major version differences mentioned in [`UPGRADING.md`](https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md).
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for similar migration issues.

### Which JavaScript Runtime is this issue in?

Node.js (includes AWS Lambda)

### AWS Lambda Usage

- [ ] Yes, my application is running on AWS Lambda.
- [X] No, my application is not running on AWS Lambda.

### Describe the Migration Issue

I have a project that uses AWS SDK V2 and I am in the process of migrating it to use V3.

Inside of this project, I have a method which uses listObjectsV2 as follows:

```
import {S3} from "aws-sdk";
private readonly _s3:S3 = new S3({apiVersion: "2006-03-01"});

getFolderContentFromS3(folderLocation:string) {
        return this._s3.listObjectsV2({
            Bucket: this._bucketName,
            Prefix: folderLocation,
        }).promise()
            .then((destination:any) => {
                //Success logic
            })
            .catch((error:any) => {
                //Failure logic
            });
    }
```

Following the [documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/command/ListObjectsV2Command/), I have revised this piece of code:

```

import {S3Client, ListObjectsV2Command} from "@aws-sdk/client-s3";
private readonly _s3:S3Client = new S3Client({region: 'us-west-2'});

getFolderContentFromS3(folderLocation:string) {
        const commandConfiguration = {
            Bucket: this._bucketName,
            Prefix: folderLocation,
        }
        const listOfObjectsCommand =  new ListObjectsV2Command(commandConfiguration);

        return this._s3.send(listOfObjectsCommand).then((destination:any) => {
            //Success logic
        }).catch((error:any) => {
            //Failure logic
        })
```

When testing this API, I get:

```
Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read',
  name: 'TimeoutError',
  '$metadata': { attempts: 3, totalRetryDelay: 115 }
}
Failed to read location.
Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read',
  name: 'TimeoutError',
  '$metadata': { attempts: 3, totalRetryDelay: 185 }
}
Failed to read location.
```

**If I run the SDK V2 counterpart, everything works.** 
The arguments hold the same value in both cases.
Other AWS S3 APIs seem to work in V3.

### Observed Differences/Errors

Getting the error posted above when using the V3 counterpart of listObjectsV2.

### Additional Context

The project uses Node 16 and am running it on a M1 Mac machine with OS Ventura 13.5

**Comment by RanVaknin** [comment]
Hi @TomerPacific ,

Thanks for reaching out. Can you please include the entire code sample that includes: SDK import, client creation and your function?

Thanks,
Ran~

**Comment by TomerPacific** [comment]
@RanVaknin - Thanks for your quick reply. I have updated the code above with the import and client creation in V2 and V3.
Let me know if anything else is necessary.

**Comment by TomerPacific** [comment]
@RanVaknin - Wanted to update here, that when using the newer JS SDK for a PutObject command, I am also seeing the same error.

```
Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read',
  name: 'TimeoutError',
  '$metadata': { attempts: 3, totalRetryDelay: 227 }
}
```
And this is the associated logic:

```
import {PutObjectCommand, S3Client} from "@aws-sdk/client-s3";
private readonly _s3:S3Client = new S3Client({region: 'us-west-2'});

uploadFile(file:string | Buffer, destination:string, contentType:ContentType = ContentType.JavaScript) {
		const isFileLocation = typeof file === "string";
		const fileContent = isFileLocation ? fs.readFileSync(file) : file;

		const uploadFileCommand = new PutObjectCommand({
			Bucket: this._bucketName,
			Key: destination,
			ContentType: contentType,
			CacheControl: "max-age=120",
			Body: fileContent
		});

		return this._s3.send(uploadFileCommand).then(() => {
				//Success Logic
			}
		).catch((error: any) => {
			//Failure Logic
		});
	}
```

The arguments and data are the same as the V2 counterpart.
Thanks

**Comment by TomerPacific** [comment]
@RanVaknin  - I figured out what the issue was. The region set for the S3 client was wrong.
Thanks and I am closing this issue.
