### ISSUE TITLE
[s3] Invalid warning when creating empty S3 object

### ISSUE THREAD

**Issue by m-radzikowski** [aws/aws-sdk-js-v3#5722]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

A warning:

> Are you using a Stream of unknown length as the Body of a PutObject request? Consider using Upload instead from @aws-sdk/lib-storage.

is logged when you create an empty S3 object.

### SDK version number

@aws-sdk/client-s3@3.496.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.11.0

### Reproduction Steps

```ts
	await s3.send(
		new PutObjectCommand({
			Bucket: 'my-bucket',
			Key: 'empty-file',
			Body: "",
		}),
	);
```

or:

```ts
	await s3.send(
		new PutObjectCommand({
			Bucket: 'my-bucket',
			Key: 'empty-file',
		}),
	);
```

### Observed Behavior

The warning is logged.

### Expected Behavior

No warning in this case. We are not providing a Stream of unknown length.

**Comment by major-winter** [comment]
Hi @m-radzikowski, it seems that sending a `PutObject` request with an empty `Body` isn't desired. [Here](https://github.com/aws/aws-sdk-js-v3/blob/40442fba7e910ad679be583e83cb375bd51d5b15/packages/middleware-sdk-s3/src/middleware-sdk-s3.integ.spec.ts#L32C1-L59C8)'s the test case for the situation.

Moreover, it doesn't make sense to put something that is empty to S3.

**Comment by m-radzikowski** [comment]
> Moreover, it doesn't make sense to put something that is empty to S3.

It totally makes sense as a "marker" file, which is not an uncommon practice in my experience.

I get why in the test an empty `Body` is used:

```
        Body: "", // use empty body to leave content-length unset.
```

but looking a the test name:

> warns on input streams of unknown length

an empty string isn't really a content with an unknown length. It's length is known, it's 0 bytes.
