### ISSUE TITLE
poor performance presigning requests due to smithy and getEndpointFromInstructions

### ISSUE THREAD

**Issue by mr-feek** [aws/aws-sdk-js-v3#5723]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I've been running into event loop blocks when trying to presign urls for ~20 resources in one of my application's network requests. 

While profiling the presigning code, I've noticed that `getEndpointFromInstructions` is quite cpu intensive, and it's invoked twice for the same get object request when calling `getSignedUrl`.

The process of actually presigning a request is quite fast (~0.003ms), but resolving the endpoint from instructions typically takes anywhere from .5-5ms, two times, means 1-10ms, before we can even get to the presigning stage.

Do this for 20 different resources... yeah the time adds up!

# Use Case
Users have private uploads attached to entities in my system. When they fetch the entity from my system, I want to return image URLs that the authenticated user can load in their browser.

### SDK version number

3.499.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.5.1

### Reproduction Steps

Create a client, and try signing urls for the same resource 20 times

```
const client = new S3Client({
            region: 'auto',
            endpoint: 'https://example.org',
            credentials: {
                accessKeyId: 'redacted',
                secretAccessKey: 'redacted',
            },
        });

        console.time('overall');

        for (let i = 0; i < 20; i++) {
            console.time('gettingSignedUrl');
            await getSignedUrl(
                client,
                new GetObjectCommand({
                    Key: 'foo',
                    Bucket: 'bar',
                }),
            );
            console.timeEnd('gettingSignedUrl');
        }

        console.timeEnd('overall');
```

### Observed Behavior

This process of generating 20 presigned urls takes ~ 30ms.

### Expected Behavior

Since the actual signing process itself only takes .001-.003ms, I would hope we can optimize and get this time down!

### Possible Solution

Is there opportunity to optimize `getSignedUrl` so that we don't need to run so many of the smithy config/request validations? The process of actually generating the signed url itself from the request is quite quick, all of the time is being spent in smithy.

### Additional Information/Context

**How I timed:**

I added 2 timers, one starting at the top of `getEndpointFromInstructions` (and ending right before the return line), and also added a timer in `presigner.presign` method. 

I just used the `console.time` and `console.endTime` helpers for this.

**Where's the time being spent?**
`getEndpointFromInstructions` is invoked twice. 
- https://github.com/aws/aws-sdk-js-v3/blob/main/packages/s3-request-presigner/src/getSignedUrl.ts#L30-L34 
- and then again at the beginning of endpoint middleware... which comes from within smithy: https://github.com/smithy-lang/smithy-typescript/blob/main/packages/middleware-endpoint/src/endpointMiddleware.ts#L42-L51 

This `getEndpointFromInstructions` method is not cheap. It does tons of tree validation, looping through rules that aren't changing on a request by request basis for me. Is there a way to perhaps add memoization or something if this method has to be called for request signing?

**What else I did**
I also generated flame graphs with clinic:

<img width="1081" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/5747667/b884fe16-aad6-432d-ac45-b385f1555891">
(this helped me realize that the expensive method was being called twice)

And I added some event loop blocking tracing into datadog, and it was also indicating that this presigning was blocking the event loop.

**Comment by RanVaknin** [comment]
Hi @mr-feek ,

Thanks for reaching out. Adding to the backlog to see what can be done. 

All the best,
Ran~

**Comment by kuhe** [comment]
Try using the `endpointProvider` field of the S3Client to implement a caching mechanism.

```ts
import { GetObjectCommand, S3Client } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";

const client = new S3Client({
  region: "auto",
  endpoint: "https://example.org",
  credentials: {
    accessKeyId: "redacted",
    secretAccessKey: "redacted",
  },
});

// acquire a reference to the real endpoint provider implementation.
const s3EndpointProvider = client.config.endpointProvider;

// create caching behavior and override the existing function.
const cache = new Map();
const hash = JSON.stringify; // or any unique hasher.

client.config.endpointProvider = function (endpointParams) {
  const key = hash(endpointParams);
  if (!cache.has(key)) {
    const entry = s3EndpointProvider(endpointParams);
    console.log("caching", key.slice(0, 25) + "...");
    console.log("data:", entry.url.toString());
    cache.set(key, entry);
  }
  return cache.get(key);
};

console.time("overall");

for (let i = 0; i < 20; i++) {
  console.time("gettingSignedUrl");
  await getSignedUrl(
    client,
    new GetObjectCommand({
      Key: "foo",
      Bucket: "bar",
    })
  );
  console.timeEnd("gettingSignedUrl");
}
console.timeEnd("overall");
```

**Comment by mr-feek** [comment]
I super appreciate you spending time looking into this and offering a suggestion, @kuhe ! I will try to get around to trying this in the next few days and get back to you 🤝
