### ISSUE TITLE
fromNodeProviderChain does not load credentials for an SSO profile correctly

### ISSUE THREAD

**Issue by gerbenis** [aws/aws-sdk-js-v3#5744]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

With the version 3.502.0 `fromNodeProviderChain` does not use `fromSSO` provider if `init` does not contain SSO session data (related change: https://github.com/aws/aws-sdk-js-v3/commit/d27301d48f3e75fdaccabf58f779f0b33a70664e#diff-353ce2d95d7e528dfc4545a098739086edfdda594eeec31125d6efed8c48de5dR70) . This causes chain to fall back to `fromIni` provider which does not load all SSO configuration correctly if the profile is set up to use `sso_session` data as a separate reusable section.

### SDK version number

@aws-sdk/credential-providers@3.502.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.19.0

### Reproduction Steps

``` javascript
// ~/.aws/config
// [profile test-profile]
// sso_session = test-session
// sso_account_id = 123456789012
// sso_role_name = test-role
// region = us-east-1
// output = json

// [sso-session test-session]
// sso_start_url = https://d-12345d6789.awsapps.com/start#
// sso_region = us-east-1
// sso_registration_scopes = sso:account:access

const { fromNodeProviderChain } = require("@aws-sdk/credential-providers");

const loadCredentials = async () => {
  const provider = fromNodeProviderChain({
    profile: "test-profile",
  });

  try {
    const credentials = await provider();
    console.log(credentials);
  } catch (e) {
    console.error(e);
  }
};

void loadCredentials();
```

### Observed Behavior

An error is thrown that indicates an invalid profile setup:
 
```
CredentialsProviderError: Profile is configured with invalid SSO credentials. Required parameters "sso_account_id", "sso_region", "sso_role_name", "sso_start_url". Got sso_session, sso_account_id, sso_role_name, region, output
Reference: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html
    at validateSsoProfile (/Users/lukas/repos/playground/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/index.js:121:11)
    at resolveSsoCredentials (/Users/lukas/repos/playground/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/index.js:135:85)
    at async resolveProfileData (/Users/lukas/repos/playground/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/index.js:189:12)
    at async /Users/lukas/repos/playground/node_modules/@smithy/property-provider/dist-cjs/index.js:79:27
    at async coalesceProvider (/Users/lukas/repos/playground/node_modules/@smithy/property-provider/dist-cjs/index.js:106:18)
    at async /Users/lukas/repos/playground/node_modules/@smithy/property-provider/dist-cjs/index.js:124:18
    at async loadCredentials (/Users/lukas/repos/playground/aws-credentials.js:9:25) {
  tryNextLink: false
}
```

### Expected Behavior

Credentials are resolved correctly.

### Possible Solution

Either revert `fromNodeProviderChain` behavior to always try `fromSSO` provider or update `fromIni` provider to load configuration from `sso-session` section.

**Comment by RanVaknin** [comment]
Hi @gerbenis ,

Thanks for reaching out. We are looking into this with priority.

All the best,
Ran~

**Comment by kuhe** [comment]
This should be fixed in today's release, expected as v3.503.0.

**Comment by kuhe** [comment]
A patch was released in [v3.503.1](https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.503.1) for SSO credential resolution.

**Comment by gerbenis** [comment]
Thank you! Can confirm that credentials resolution is working well with v3.503.1.

**Comment by RanVaknin** [comment]
Great to hear that this worked out. If anything else comes up please open a new issue.

All the best,
Ran~
