### ISSUE TITLE
CJS build for credential provider references undefined __importStar

### ISSUE THREAD

**Issue by nonken** [aws/aws-sdk-js-v3#5750]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

https://github.com/aws/aws-sdk-js-v3/blob/175169260726c018a5049069ee062f6ef98275d7/packages/credential-providers/src/fromTemporaryCredentials.ts#L69

This line `await import`s a dependency at runtime. Wen the code gets compiled down to CJS, it results in the following code:

```
const { AssumeRoleCommand, STSClient } = await Promise.resolve().then(() => __importStar(require("./loadSts")));
```

In the compiled file `fromTemporaryCredentials.csj` there is no `__importStar` to be found.
When manually adding 

```
const {__importStar} = require('tslib');
```

at the top of the file it will work.

### SDK version number

@aws-sdk/credential-providers@3.503.1

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.11.0

### Reproduction Steps

* Create a nodejs project that uses cjs. 
* Create a build using esbuild.
* Run the service and it will fail.

### Observed Behavior

```
        const { AssumeRoleCommand, STSClient: STSClient2 } = await Promise.resolve().then(() => __importStar(require_loadSts2()));
                                                                                                ^

ReferenceError: __importStar is not defined
```

### Expected Behavior

I expect it to work.

### Possible Solution

```
const {__importStar} = require('tslib');
```

Add this to the file and it works, but this is after it was built.

**Comment by nonken** [comment]
It seems like you can workaround this issue by doing the following when using esbuild:

```
const esbuild = require('esbuild');
const fs = require('fs');

//
// We are injecting __importStar into the credential loader of the aws-sdk.
// This because they have a bug when building their cjs dist.
//
// https://github.com/aws/aws-sdk-js-v3/issues/5750
//
// Once this is resolved we can remove this.
//
const tslibInjectorPlugin = {
  name: 'tslib-injector',
  setup(build) {
    build.onLoad({filter: /fromTemporaryCredentials\.js$/}, async (args) => {
      const contents = await fs.promises.readFile(args.path, 'utf8');

      if (!contents.includes("require('tslib')")) {
        const modifiedContents = `const { __importStar } = require('tslib');\n${contents}`;
        return {contents: modifiedContents, loader: 'js'};
      }

      return null;
    });
  },
};

esbuild
  .build({
    entryPoints: ['src/server.js'], // Adjust as per your entry file
    bundle: true,
    platform: 'node',
    outfile: 'dist/server.js', // Adjust as per your desired output file
    plugins: [tslibInjectorPlugin],
  })
  .catch(() => process.exit(1));
```

**Comment by kuhe** [comment]
We expect to release a fix for this tomorrow. There was a correction needed in an old TSConfig file that was previously undetected.

**Comment by nonken** [comment]
> We expect to include this fix in the next release. There was a correction needed in an old TSConfig file that was previously undetected.

Thank you ser, lightspeed

**Comment by kuhe** [comment]
A patch was released in https://www.npmjs.com/package/@aws-sdk/credential-providers/v/3.504.1
