### ISSUE TITLE
ClientS3 PutObjectCommand fails to upload small PNG files

### ISSUE THREAD

**Issue by Pryanishnik** [aws/aws-sdk-js-v3#5753]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Hey! We are using AWS SDK V3 ClientS3.
And the issue I'm facing is super weird.
PutObjectCommand throws an error `The provided 'x-amz-content-sha256' header does not match what was computed.`
but only for really small PNG images (from experiments less than 5KB size).

### SDK version number

@aws-sdk/client-s3@version, 3.504.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

20.5.1

### Reproduction Steps

Nothing specific is called.

```
await this.s3.send(
                    new PutObjectCommand({
                        Bucket: bucket,
                        Key: name,
                        Body: Buffer.from(file.buffer),
                        ACL: 'public-read',
                        ContentType: mimetype,
                        CacheControl: 'max-age=2592000',
                    }),
                );
```

Example files
![apple-logo](https://github.com/aws/aws-sdk-js-v3/assets/43049295/ee27d0a1-2084-4dae-a573-df9df199a531)
![logo](https://github.com/aws/aws-sdk-js-v3/assets/43049295/6c3f88ba-b843-4156-b66f-375755e064f6)

### Observed Behavior

`The provided 'x-amz-content-sha256' header does not match what was computed.`- is thrown.
ClientCalculatedSHA and S3CalculatedSHA are different

### Expected Behavior

File is successfully uploaded

**Comment by RanVaknin** [comment]
Hi @Pryanishnik ,

I see the `mimetype` is not shown in your snippet, is the mimetype passed in accurate? Can you try removing it and see if it solves your issue?

Thanks,
Ran~

**Comment by Pryanishnik** [comment]
@RanVaknin sure!
Yes, mimeType is "image/png" for both cases. I tried ro remove it from the input, but had the same result

**Comment by RanVaknin** [comment]
Hi @Pryanishnik ,

That is interesting. I'm not able to reproduce the behavior.

I would make sure you are reading your file correctly. Without seeing your complete code sample it will be difficult to speculate.

Here is my implementation:

```js
import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";
import { readFileSync } from "fs";

const client = new S3Client({
    region: "us-east-1", 
}); 

async function uploadImageToS3(filePath) {
  try {
    const fileContent = readFileSync(filePath);
        
    const command = new PutObjectCommand({
      Bucket: 'foo-bucket',
      Key: 'applelogo.png',
      Body: Buffer.from(fileContent),
      CacheControl: 'max-age=2592000',
      
    });
    
    const response = await client.send(command);
    console.log("Success:", response);
  } catch (error) {
    console.error("Error:", error);
  }
}

uploadImageToS3("./applelogo.png");

/*
Success: {
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'REDACTED',
    extendedRequestId: 'REDACTED',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  ETag: '"a07eb8653254d0de3f9f7bd8d37d19ae"',
  ServerSideEncryption: 'AES256',
  VersionId: 'er7rQLjebOtugUszKw4NhRJkb8iCPONL'
}
*/
```

One thing you can do is capture the outgoing request to see what you are actually sending over the wire. This might point you to any unexpected arguments you might be sending over the wire. You can do that by using this middleware hook:

```js
client.middlewareStack.add(next => async (args) => {
 console.log(args.request)
 const response = await next(args);
 console.log(response);
 return next(args);
}, {step: 'finalizeRequest'})
```

Let me know if that helps,
Ran~
