### ISSUE TITLE
Custom header support in AWS ses SDK for sendemailcommand

### ISSUE THREAD

**Issue by cloudcreatr** [aws/aws-sdk-js-v3#5760]
### Describe the feature

If i have to use a custom header in AWS SDK for javascript i have to send a raw email and it's confusing and scary. Idk what to set and mime type and what should be the other things.. i just want to set a custom header and send the email that's it.. i don't want to play with raw email.. 

### Use Case

Being able to include the list unsubscribe header without creating a raw email and playing with it.. also it's a must Gmail policy and it's a very good idea to include this option in send email command not list management 
Being able to set ups custom header without playing with raw email 

### Proposed Solution

Change the sendemailcommand to accept a new property for custom headers and work as normal like doing all the things in background 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3

### Environment details (OS name and version, etc.)

Windows 11

**Comment by Vindexus** [comment]
I think I'm facing the same issue. We upgraded to v3 of the JS SDK because of the notice we were receiving, but also need to add the unsubscribe headers that the Yahoo/Gmail changes come about.

Unfortunately the new version of the API doesn't appear to have the option for list management. The new SDK also doesn't support custom headers for supplying our own unsubscribe links with the SendEmailCommand.

**Comment by cloudcreatr** [comment]
The api before was simple mention the subject, destination and source suddenly to just add customer headers i have to read so many RFC that I don't even know if I am confident after that.. then i have to encode the message and than make sure i hBw formatted the email correctly who is docs doesn't exist on the planet.. idk.. AWS could make a abstraction on top of raw email command. Or create docs on how to properly format a raw email what should be it's header and what should be it's body and what headers is handled by ses

**Comment by cloudcreatr** [comment]
The api before was simple mention the subject, destination and source suddenly to just add customer headers i have to read so many RFC that I don't even know if I am confident after that.. then i have to encode the message and than make sure i hBw formatted the email correctly who is docs doesn't exist on the planet.. idk.. AWS could make a abstraction on top of raw email command. Or create docs on how to properly format a raw email what should be it's header and what should be it's body and what headers is handled by ses

**Comment by RanVaknin** [comment]
Hi @cloudcreatr,

>who is docs doesn't exist on the planet.

SES has a very in-depth [developer guide](https://docs.aws.amazon.com/ses/latest/dg/send-email-raw.html) with code and formatting samples. 

>then i have to encode the message

You don't need to encode the message, the SDK base64 encodes it for you. All you need to do is wrap your string in a Buffer or a similar data type that can hold the raw string binary data - similarly to the code sample I provided.

Regarding an abstraction on top, we don't introduce high level libraries on a per-SDK basis, this would need to be a part of a cross-SDK effort. Right now there is no plan or bandwidth to address customizations of this sort.

If this is something you are interested in, I encourage you to reach out to the SES service team internally via opening a support ticket on the developer console and raise this as a feature request.

Let me know if you have any other questions regarding the current usage and I'd be happy to address them.

Thanks,
Ran~

**Comment by Vindexus** [comment]
@RanVaknin You are correct, I was using the wrong client. @cloudcreatr You might have done the same thing as me.

I got very confused by the different versions of the SDK and the API.

For anyone who gets confused as I did:

- The AWS SDK is moving from V2 to V3. The docs that do not list their version are currently for V3 of the SDK.
- SES itself has V1 and V2 API endpoint. The docs that do not list their version are for V1 of that API
- You should be using @aws-sdk/client-sesv2, which is the SDK V3 client for the SES API V2
- If you wish to add unsubscribe functionality to your emails you can use the `SendEmailCommand` from @aws-sdk/client-sesv2, which has the ListManagementOptions param

I assumed @aws-sdk/client-sesv2 was legacy support for code from the SDK V2.

**Comment by cloudcreatr** [comment]
> You don't need to encode the message, the SDK base64 encodes it for you. All you need to do is wrap your string in a Buffer or a similar data type that can hold the raw string binary data - similarly to the code sample I provided.

What are mandory headers to include when using raw email? What if i don't put the mime type? I am using sendrawemail command because I can put my unsubscribe header!!. Maybe how can I learn about the headers i can use and how to properly format header and body.. there's only RFC available not a proper docs about it

**Comment by RanVaknin** [comment]
Hi @Vindexus glad it worked out for you.

@cloudcreatr as far as I know there are no mandatory headers. If you want to send an unsubscribe header you can use the predefined `List-Unsubscribe` header.

>Maybe how can I learn about the headers i can use and how to properly format header and body..

These are the supported headers: https://docs.aws.amazon.com/ses/latest/dg/header-fields.html
This is the doc on how to format a raw email https://docs.aws.amazon.com/ses/latest/dg/send-email-raw.html

I also provided an example in [this comment](https://github.com/aws/aws-sdk-js-v3/issues/5760#issuecomment-1928660924) which shows how raw emails should be formatted.

Thanks,
Ran~
