### ISSUE TITLE
TypeScript error using Node.js `AbortSignal` when sending SQS commands

### ISSUE THREAD

**Issue by DarylLyonsLF** [aws/aws-sdk-js-v3#5769]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I'm attempting to use the Node.js `AbortController` to configure SQS client commands with an `abortSignal`, however, this results in a TypeScript error (TS2769).

Using the `AbortController` provided by `@smithy/abort-controller` "solves" the issue, but the docs [mark this as deprecated and suggest using the Node native implementation](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-smithy-abort-controller/).

### SDK version number

`@aws-sdk/client-sqs@3.507.0`

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

`v20.11.0`

### Reproduction Steps

```ts
import { SQSClient, ReceiveMessageCommand } from '@aws-sdk/client-sqs';
// note: using deprecated '@smithy/abort-controller' "solves" the problem
// import { AbortController } from '@smithy/abort-controller';

(async () => {
  const abortController = new AbortController(); // Node native abort controller

  const client = new SQSClient();
  const result = await client.send(new ReceiveMessageCommand({ QueueUrl: 'queue-url' }), {
    abortSignal: abortController.signal // <-- error introduced here
  });
})();
```

### Observed Behavior

> Overload 1 of 3, '(command: Command<ServiceInputTypes, ReceiveMessageCommandInput, ServiceOutputTypes, ReceiveMessageCommandOutput, SmithyResolvedConfiguration<...>>, options?: HttpHandlerOptions | undefined): Promise<...>', gave the following error.
    Property 'onabort' is missing in type 'AbortSignal' but required in type 'import("c:/Users/lyonsd/repositories/lf-tech-team/packages/common-eventing/node_modules/@smithy/types/dist-types/abort").AbortSignal'. (ts2769)
_[Redacted 2nd and 3rd overloads as they are irrelevant]_

### Expected Behavior

There is no TS error and I am able to compile the code.

**Comment by kuhe** [comment]
@DarylLyonsLF where is your global type for AbortSignal declared?

Is it `@types/node` or lib.dom.ts? and what version?

**Comment by DarylLyonsLF** [comment]
> @DarylLyonsLF where is your global type for AbortSignal declared?
> 
> Is it `@types/node` or lib.dom.ts? and what version?

@kuhe `@types/node@v18.15.1`. I've just bumped to `v20.11.24` which has resolved the issue! Thanks a lot for the response and apologies for not noticing this myself.
