### ISSUE TITLE
TypeError: import_client_rds2.EnableHttpEndpointCommand is not a constructor

### ISSUE THREAD

**Issue by jlincoln** [aws/aws-sdk-js-v3#5784]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The following results in a "TypeError: import_client_rds2.EnableHttpEndpointCommand is not a constructor".

```ts
import {
  DBCluster,
  EnableHttpEndpointCommand,
  EnableHttpEndpointCommandInput,
  RDSClient,
} from '@aws-sdk/client-rds';

const client = new RDSClient(config); 
const enableDataAPIInput: EnableHttpEndpointCommandInput = {
  ResourceArn: (await dbCluster(client, newClusterId!))?.DBClusterArn,
};
const enableDataAPICommand = new EnableHttpEndpointCommand(enableDataAPIInput);
response = await client.send(enableDataAPICommand);
...

async function dbCluster(rdsClient: RDSClient, dbClusterId: string): Promise<DBCluster | undefined> {
  let response;
  const describeDBClusterInput: DescribeDBClustersCommandInput = {
    DBClusterIdentifier: dbClusterId,
  };
  const describeDBClustersCommand = new DescribeDBClustersCommand(describeDBClusterInput);
  try {
    response = await rdsClient.send(describeDBClustersCommand);
    console.log('response is', response);
  } catch(error) {
    console.error(error);
  }
  let dbClusters: DBCluster[] = [];
  if (response?.DBClusters) dbClusters = response.DBClusters;
  return dbClusters[0];
}
```

### SDK version number

"@aws-sdk/client-rds": "^3.501.0"

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.9.1

### Reproduction Steps

```
import {
  DBCluster,
  EnableHttpEndpointCommand,
  EnableHttpEndpointCommandInput,
  RDSClient,
} from '@aws-sdk/client-rds';

const client = new RDSClient(config); 

const newClusterId = env.DB_CLUSTER_IDENTIFIER;

const enableDataAPIInput: EnableHttpEndpointCommandInput = {
  ResourceArn: (await dbCluster(client, newClusterId!))?.DBClusterArn,
};
const enableDataAPICommand = new EnableHttpEndpointCommand(enableDataAPIInput);
response = await client.send(enableDataAPICommand);
...

async function dbCluster(rdsClient: RDSClient, dbClusterId: string): Promise<DBCluster | undefined> {
  let response;
  const describeDBClusterInput: DescribeDBClustersCommandInput = {
    DBClusterIdentifier: dbClusterId,
  };
  const describeDBClustersCommand = new DescribeDBClustersCommand(describeDBClusterInput);
  try {
    response = await rdsClient.send(describeDBClustersCommand);
    console.log('response is', response);
  } catch(error) {
    console.error(error);
  }
  let dbClusters: DBCluster[] = [];
  if (response?.DBClusters) dbClusters = response.DBClusters;
  return dbClusters[0];
}
```

### Observed Behavior

When executed the following error is encountered.

```
TypeError: import_client_rds2.EnableHttpEndpointCommand is not a constructor
```

### Expected Behavior

Database cluster Data API is enabled.

### Possible Solution

Unknown

### Additional Information/Context

This is being used in a CDK custom resource that also renames the cluster, moves the existing serverless cluster to provisioned, and upgrades the database version.

**Comment by jlincoln** [comment]
I built a standalone Node package to reproduce the issue.  I found the following functions as expected.

package.json:
```
{
  "name": "rdsserverlesstoprovisioned",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "run": "node index.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@aws-sdk/client-rds": "^3.500.0",
    "aws-sdk": "^2.1555.0"
  }
}

```

index.js:
```
const awsSdk = require('aws-sdk');
const {
  DescribeDBClustersCommand,
  RDSClient,
  EnableHttpEndpointCommand,
} = require("@aws-sdk/client-rds");

async function dbCluster(rdsClient, dbClusterId) {
  let response;
  const describeDBClusterInput = {
    DBClusterIdentifier: dbClusterId,
  };
  const describeDBClustersCommand = new DescribeDBClustersCommand(describeDBClusterInput);
  try {
    response = await rdsClient.send(describeDBClustersCommand);
    console.log('response is', response);
  } catch(error) {
    console.error(error);
  }
  let dbClusters = [];
  if (response?.DBClusters) dbClusters = response.DBClusters;
  return dbClusters[0];
}

(async () => {

  const config = {
    region: process.env.AWS_REGION,
    credentials: {
      accessKeyId: awsSdk.config.credentials?.accessKeyId,
      secretAccessKey: awsSdk.config.credentials?.secretAccessKey,
      sessionToken: awsSdk.config.credentials?.sessionToken
    }
  };

  const client = new RDSClient(config);
  const newClusterId = 'forceawakens-lambdaandrds-fatestbetaforceawakensau-o';
  const dbClusterArn = (await dbCluster(client, newClusterId)).DBClusterArn;
  const enableDataAPIInput = {
    ResourceArn: dbClusterArn,
  };
  const enableDataAPICommand = new EnableHttpEndpointCommand(enableDataAPIInput);
  response = await client.send(enableDataAPICommand);
})();
```

**Comment by RanVaknin** [comment]
Hi @jlincoln ,

I see that type error you are getting with other customers who have multiple copies of the same dependency but in different versions. 

From the second command it seems like its working correctly? That would explain why. 

On your first project you can:
- delete `node_modules`
- delete `package-lock.json`
- run `npm install`

This will let npm resolve the dependency tree. You can also look into [npm dedupe](https://docs.npmjs.com/cli/v8/commands/npm-dedupe)

Let us know how it goes.
Thanks,
Ran~

**Comment by jlincoln** [comment]
Thank you @RanVaknin.  I have tried cleaning the Node project to remove node_modules and package-lock.json and then reinstalling them.  I also included dedupe in the postinstall script run when deploying.  I then re-executed as custom CDK resource and received a slightly different error.  The difference is that "import_client_rds2" is now "import_client_rds".

```
TypeError: import_client_rds.EnableHttpEndpointCommand is not a constructor
```

The dedupe did identify duplicate node packages that it removed.

```
> @amzn/force_awakens_cdk@1.0.0 postinstall /workplace/jelinco/ForceAwakens/src/ForceAwakensCDK
> npm dedupe

removed 57 packages and moved 1 package in 2.619s

50 packages are looking for funding
  run `npm fund` for details
```

**Comment by RanVaknin** [comment]
Hi @jlincoln,

I'm not sure why you are running into this. 
I wrote my own little repro code and can successfully transpile:

```ts
import {
  EnableHttpEndpointCommand,
  RDSClient,
} from '@aws-sdk/client-rds';

const rdsClient = new RDSClient({ region: "us-east-1" });

async function enableHttpEndpointForResource() {
  try {
    const response = await rdsClient.send(new EnableHttpEndpointCommand({
      ResourceArn: "arn:aws:rds:us-east-1:REDACTED:cluster:foo"
    }));
    console.log(response);
  } catch (error) {
    console.error(error);
  }
}

enableHttpEndpointForResource();
```

I still think this is a dependency issue where you another copy of this same library just tracking an older version. 
You can try to use `npm ls @aws-sdk/client-rds` to identify if you have multiple versions of the same one.

Additionally, can you tell me how this is used with CDK? Maybe that can help point us to the root cause?

Thanks,
Ran~

**Comment by jlincoln** [comment]
I was trying to use a CDK custom resource to migrate a serverless db cluster to a provisioned db cluster.  There are multiple steps involved but I ended up running into multiple issues including this one with EnableHttpEndpointCommand.  Other issues are the time certain steps take to complete such as modifyDBCluster calls to 1) change to provisioned and 2) upgrade the database version.  Each of these can take more than 15m.  So a custom resource (which is backed by a lambda) will not work.

npm ls @aws-sdk/client-rds@3.509.0 returns the following.
```
└── @aws-sdk/client-rds@3.509.0
```

**Comment by kellertk** [comment]
If you're using the CDK CustomResource framework, you'll be using [Node 18 and AWS JS SDK v3](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.custom_resources-readme.html#using-aws-sdk-for-javascript-v3). Most often, we see the type error you're encountering when you're mixing versions of the JS SDK incorrectly, either among v3 versions or v2 and v3. 

You're right that there's an execution timeout with custom resource Lambdas - the highest they can be set is actually 1 hour. See https://github.com/aws/aws-cdk/issues/24974

If you need to run longer than an hour, we published a blog post with an example of how you might use the custom resource framework in combination with a Step Function, to increase the execution time up to 12 hours, which should be plenty for a database migration. Would something like this work for you? https://aws.amazon.com/blogs/devops/implementing-long-running-deployments-with-aws-cloudformation-custom-resources-using-aws-step-functions/

**Comment by RanVaknin** [comment]
Hi @jlincoln,

Thanks for the information. I had to read your response multiple times to fully understand it. 

I think I know why you were running into this issue. 
Since you mentioned you were using Lambda, my guess is that you were using the [Lambda provided SDK](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) which is pinned at version `3.362.0`
Whereas the operation you are trying to use `EnableHttpEndpoint` was added in [3.520.0](https://github.com/aws/aws-sdk-js-v3/commit/ee4406c0c6bd8aebceb3853ddc98d48b745bafcb)

In order to use it, you'll need to provide the desired SDK version yourself (either with a [Lambda Layer](https://docs.aws.amazon.com/lambda/latest/dg/chapter-layers.html) or with [bundling and minifying](https://aws.amazon.com/blogs/compute/optimizing-node-js-dependencies-in-aws-lambda/) and uploading to Lambda) 

If the Lambda time constraint is something you can't overcome, then @kellertk is right. Step Functions are much more appropriate for multi step, state-dependent workflows, like updating a cluster and checking the cluster state.

Let us know if you need anything else. 
Thanks,
Ran~

**Comment by jlincoln** [comment]
> Hi @jlincoln,
> 
> Thanks for the information. I had to read your response multiple times to fully understand it.
> 
> I think I know why you were running into this issue. Since you mentioned you were using Lambda, my guess is that you were using the [Lambda provided SDK](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) which is pinned at version `3.362.0` Whereas the operation you are trying to use `EnableHttpEndpoint` was added in [3.520.0](https://github.com/aws/aws-sdk-js-v3/commit/ee4406c0c6bd8aebceb3853ddc98d48b745bafcb)
> 
> In order to use it, you'll need to provide the desired SDK version yourself (either with a [Lambda Layer](https://docs.aws.amazon.com/lambda/latest/dg/chapter-layers.html) or with [bundling and minifying](https://aws.amazon.com/blogs/compute/optimizing-node-js-dependencies-in-aws-lambda/) and uploading to Lambda)
> 
> If the Lambda time constraint is something you can't overcome, then @kellertk is right. Step Functions are much more appropriate for multi step, state-dependent workflows, like updating a cluster and checking the cluster state.
> 
> Let us know if you need anything else. Thanks, Ran~

Thank you for the insight.  That makes perfect sense and the thought had occurred to me but didn't see where the Lambda was pulling its SDK and where to identify its version.
