### ISSUE TITLE
Creating LocationClient with API key throws "Could not load credentials from any providers" in version 3.513.0 and forward

### ISSUE THREAD

**Issue by nielscastle** [aws/aws-sdk-js-v3#5808]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

In version 3.513.0 through 3.515.0 an error is throws when creating a `LocationClient` using an API key

    CredentialsProviderError: Could not load credentials from any providers

Up to and including version 3.511.0 the problem does not manifest.

I am using `@aws/amazon-location-utilities-auth-helper` to allow using an API key for authentication

    const authHelper = await withAPIKey(<AWS_API_KEY>);
    const awsClient = new LocationClient({
       region: <AWS_REGION>, 
       ...authHelper.getLocationClientConfig()
    });

### SDK version number

@aws-sdk/client-location@3.513.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node.js v21.2.0

### Reproduction Steps

Using the following code I create a `LocationClient` and verify that it works by geocoding an address. The expected output is

    Subregion: Santa Cruz de Tenerife

The example is as follows:

    "use strict";
    
    // Imports --
    
    require('dotenv').config()
    
    // Constants --
    
    const { withAPIKey } = require( '@aws/amazon-location-utilities-auth-helper');
    const { LocationClient, SearchPlaceIndexForTextCommand } = require("@aws-sdk/client-location");
    
    const params = {
      IndexName: "My-Location-Service-Place-Index",
      Text: "Calle Tomas Zerolo 21, La Orotava, Espania",
      FilterCountries : ["GBR", "IRL", "DNK", "ESP"],
      Language: "en",
      MaxResults: 1,
    }
    
    // Location function --
    
     async function x() {
    
      const authHelper = await withAPIKey(process.env.AWS_API_KEY);
      const awsClient = new LocationClient({
        region: process.env.AWS_REGION, 
        ...authHelper.getLocationClientConfig()
      });
    
      const command = new SearchPlaceIndexForTextCommand(params);
      const response = await awsClient.send(command);
    
      console.log("Subregion: " + response.Results[0].Place.SubRegion)
    }
    
    // Main --
    
    try{
      x()
    } catch(error) {
      console.log(error)
    }

In order to run the code successfully I use the following `package.json` file

    {
        "dependencies":
        {
            "@aws-sdk/client-location": "3.511.0",
            "@aws/amazon-location-utilities-auth-helper": "1.0.3",
            "@aws/amazon-location-utilities-datatypes": "1.0.3",
            "dotenv": "^16.4.1"
        }
    }

In order to make the code fail I change the `@aws-sdk/client-location` version to 3.513.0.

### Observed Behavior

    castle% npm list    
    location-helper-test@ /Repos/location-helper-test
    ├── @aws-sdk/client-location@3.513.0
    ├── @aws/amazon-location-utilities-auth-helper@1.0.3
    ├── @aws/amazon-location-utilities-datatypes@1.0.3
    └── dotenv@16.4.4
    
    castle% node main.js
    /Repos/location-helper-test/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/    credential-provider-node/dist-cjs/index.js:110
          throw new import_property_provider.CredentialsProviderError("Could not load credentials from any     providers", false);
                ^
    
    CredentialsProviderError: Could not load credentials from any providers
        at /Repos/location-helper-test/node_modules/@aws-sdk/client-location/    node_modules/@aws-sdk/credential-provider-node/dist-cjs/index.js:110:13
        at /Repos/location-helper-test/node_modules/@smithy/property-provider/dist-cjs/    index.js:79:33
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async coalesceProvider (/Repos/location-helper-test/node_modules/@smithy/    property-provider/dist-cjs/index.js:106:18)
        at async /Repos/location-helper-test/node_modules/@smithy/property-provider/dist-cjs/    index.js:124:18
        at async /Repos/location-helper-test/node_modules/@smithy/core/dist-cjs/index.js:82:17
        at async /Repos/location-helper-test/node_modules/@aws-sdk/client-location/    node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22
        at async x (/Repos/location-helper-test/main.js:31:20) {
      tryNextLink: false
    }
    
    Node.js v21.2.0
    castle%

### Expected Behavior

My expectation was that the `LocationClient` accepted the API key passed in and run the query against the location API.

    castle% npm list    
    location-helper-test@ /Users/castle/Documents/Repos/location-helper-test
    ├── @aws-sdk/client-location@3.511.0
    ├── @aws/amazon-location-utilities-auth-helper@1.0.3
    ├── @aws/amazon-location-utilities-datatypes@1.0.3
    └── dotenv@16.4.4
    
    castle% node main.js
    Subregion: Santa Cruz de Tenerife
    castle%

### Possible Solution

I do not have a fix or possible reason for the bug.

### Additional Information/Context

Same problem on my machine, when unit testing during build on GitHub and in the docker container where the code is used.

Removed any aws credentials on my machine in project as well as `.aws` in root folder for testing..

**Comment by kuhe** [comment]
what is the output of `authHelper.getLocationClientConfig()`?

**Comment by kuhe** [comment]
I believe we identified the issue and @syall is considering what kind of fix could be made.

As a workaround, could you try passing empty credentials to the initialization?

```ts
const authHelper = await withAPIKey(<AWS_API_KEY>);
const awsClient = new LocationClient({
   region: <AWS_REGION>, 
   credentials: { accessKeyId: "", secretAccessKey: "" }
   ...authHelper.getLocationClientConfig()
});
```

**Comment by nielscastle** [comment]
I can confirm that the workaround is working in 3.513.0:

    castle% node main.js
    Subregion: Santa Cruz de Tenerife (Success)
    castle% npm list
    aws-locationclient-no-providers-bug@ /Users/castle/Documents/Repos/aws-locationclient-no-providers-bug
    ├── @aws-sdk/client-location@3.513.0
    ├── @aws/amazon-location-utilities-auth-helper@1.0.3
    ├── @aws/amazon-location-utilities-datatypes@1.0.3
    └── dotenv@16.4.5
    
    castle% cat main.js | grep -A2 -B2 cred 
      const awsClient = new LocationClient({
        region: process.env.AWS_REGION, 
          credentials: { accessKeyId: "", secretAccessKey: "" },
        ...authHelper.getLocationClientConfig()
      });
    castle%

**Comment by kuhe** [comment]
An update will be released in the other package (https://www.npmjs.com/package/@aws/amazon-location-utilities-auth-helper?activeTab=versions) to also add the stub empty credentials so in the future the user code will not have to change.  

I don't have a timeline for that release, but in the meantime please continue using the workaround.

**Comment by nielscastle** [comment]
Excellent! Thank you very much for the fast turnover 💪
I'll keep an eye on the other package and update it when ready.
All the best!

**Comment by syall** [comment]
[`@aws/amazon-location-utilities-auth-helper@1.0.4`](https://www.npmjs.com/package/@aws/amazon-location-utilities-auth-helper/v/1.0.4) has been published with the fixes from aws-geospatial/amazon-location-utilities-auth-helper-js#31, and is available to consume.
