### ISSUE TITLE
Error TypeError: Failed to fetch When trying to upload

### ISSUE THREAD

**Issue by Sebastp** [aws/aws-sdk-js-v3#5809]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

still getting
"Error TypeError: Failed to fetch
    at FetchHttpHandler.handle (fetch-http-handler.js:53:1)
    at async eval (deserializerMiddleware.js:2:24)"
when trying to upload an object to NON-S3 provider such as Backblaze or digital ocean's spaces.

I tried downgrading like they said in answers in this issue but no success. I'm stuck. What can I do to make it work

https://github.com/aws/aws-sdk-js-v3/issues/5334

### SDK version number

@aws-sdk/package-name@3.370.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

20.10.0

### Reproduction Steps

import { PutObjectCommand, S3Client } from '@aws-sdk/client-s3'
// Step 2: The s3Client function validates your request and directs it to your Space's specified endpoint using the AWS SDK.
const s3Client = new S3Client({
  endpoint: '', // Find your endpoint in the control panel, under Settings. Prepend "https://".
  forcePathStyle: false, // Configures to use subdomain/virtual calling format.
  region: '', // Must be "us-east-1" when creating new Spaces. Otherwise, use the region in your endpoint (e.g. nyc3).
  credentials: {
    accessKeyId: '', // Access key pair. You can create access key pairs using the control panel or API.
    secretAccessKey: '', // Secret access key defined through an environment variable.
  },
})

// Step 3: Define the parameters for the object you want to upload.
const params = {
  Bucket: 'bucket', // The path to the directory you want to upload the object to, starting with your Space name.
  Key: 'hello-world.txt', // Object key, referenced whenever you want to access this file later.
  Body: 'Hello, World!', // The object's contents. This variable is an object, not a string.
  ACL: 'private', // Defines ACL permissions, such as private or public.
  Metadata: {
    // Defines metadata tags.
    'x-amz-meta-my-key': 'your-value',
  },
}

s3Client.send(new PutObjectCommand(params))

### Observed Behavior

Error TypeError: Failed to fetch
    at FetchHttpHandler.handle (fetch-http-handler.js:53:1)
    at async eval (deserializerMiddleware.js:2:24)

### Expected Behavior

it should upload

**Comment by RanVaknin** [comment]
Hi @Sebastp ,

Unfortunately the SDK only officially supports AWS services and cannot guarantee support to any of the S3 clones like Minio, Digital ocean spaces and the many others.

The best advice I can offer you is to see what is the expected request format that the clone you are using expects, and then log the outgoing request to examine any discrepancies:

```
client.middlewareStack.add(next => async (args) => {
 console.log(args.request)
 const response = await next(args);
 console.log(response);
 return next(args);
}, {step: 'finalizeRequest'})
```

This middleware hook will log the raw request and response and might be able to provide some more clues.
Another suggestion is for you to reach to the support ops of the services with which you are interacting:
- https://docs.digitalocean.com/support/
- https://www.backblaze.com/help

Thanks,
Ran~
