### ISSUE TITLE
MIGRATION ISSUE: SQS client send message on mutiple regions

### ISSUE THREAD

**Issue by lepirlouit** [aws/aws-sdk-js-v3#5812]
### Pre-Migration Checklist

- [X] I've read the [Migration Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/migrating-to-v3.html).
- [X] I've reviewed the upgrading notes and major version differences mentioned in [`UPGRADING.md`](https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md).
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for similar migration issues.

### Which JavaScript Runtime is this issue in?

Node.js (includes AWS Lambda)

### AWS Lambda Usage

- [X] Yes, my application is running on AWS Lambda.
- [ ] No, my application is not running on AWS Lambda.

### Describe the Migration Issue

One of my lambda is sending messages on mutiples queues that could be in different regions
with sdk v2 I was able to init the client in one region and queue region was get from the url

### Code Comparison

```
const { SQS } = require("@aws-sdk/client-sqs");
const AWS = require('aws-sdk');
const sqsV2 = new AWS.SQS({region: "eu-central-1"});
const sqsV3 = new SQS({region: "eu-central-1"});


const queuesURLs = [
  'https://sqs.eu-central-1.amazonaws.com/{AWS_ACCOUNT}/oneQueue',
  "https://sqs.eu-west-1.amazonaws.com/{AWS_ACCOUNT}/anotherQueue",
];

(async () => { 
  for (const queueURL of queuesURLs) { 
    const params = {
      "MessageBody": "Dummy Message",
      QueueUrl: queueURL,
    };
    // await sqsV2.sendMessage(params).promise();
    // await sqsV3.sendMessage(params);
  }

})();
```

### Observed Differences/Errors

- `QueueUrl=https://sqs.eu-west-1.amazonaws.com/{aws_account}/anotherQueue differs from SQSClient resolved endpoint=https://sqs.eu-central-1.amazonaws.com/, using QueueUrl host as endpoint.`
- "SignatureDoesNotMatch: Credential should be scoped to a valid region."

with param `useQueueUrlAsEndpoint` I got `The specified queue does not exist or you do not have access to it`

**Comment by lepirlouit** [comment]
in v2 endpoint and region is set from QueueUrl

https://github.com/aws/aws-sdk-js/blob/master/lib/services/sqs.js#L127-L128

**Comment by kuhe** [comment]
You should use one client per region in v3.

```ts
import { SQS } from "@aws-sdk/client-sqs";

const sqsClients = {
  "eu-central-1": new SQS({ region: "eu-central-1" }),
  "eu-west-1": new SQS({ region: "eu-west-1" }),
};

const queues = [
  { region: "eu-central-1", url: "https://sqs.eu-central-1.amazonaws.com/{AWS_ACCOUNT}/oneQueue" },
  { region: "eu-west-1", url: "https://sqs.eu-west-1.amazonaws.com/{AWS_ACCOUNT}/anotherQueue" },
];

for (const { region, url } of queues) {
  const params = {
    MessageBody: "Dummy Message",
    QueueUrl: url,
  };
  await sqsClients[region].sendMessage(params);
}
```

The v2 behavior was a customization that we don't want to keep supporting for consistency among SDK clients and because region is meant to be initialized at the client level and not changed between requests.  

Although it is technically possible to read the region from the standard SQS endpoints, we do not want to attempt to do that because the QueueUrl may deviate from the standard public endpoint.
