### ISSUE TITLE
Shape not found

### ISSUE THREAD

**Issue by fredrickreuben** [aws/aws-sdk-js-v3#5814]
### Describe the issue

```json
{"name":"Origins","pkg":"@aws-sdk/client-cloudfront","type":"Interface","text":"Origins"}
```

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/cloudfront/command/CreateDistributionCommand/

**Comment by aBurmeseDev** [comment]
Hi @fredrickreuben - thank you for reaching out. 

Can you please elaborate on what seems to be an issue whether you're seeing an error or a param is missing? 

Best,
John
