### ISSUE TITLE
UpdateItemCommand not found in package

### ISSUE THREAD

**Issue by ChrisLaforet** [aws/aws-sdk-js-v3#5823]
### Describe the issue

UpdateItemCommand was not found in @aws-sdk/lib-dynamodb.  I had to use UpdateCommand instead.  Is this name valid?

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/dynamodb/command/UpdateItemCommand/

**Comment by kuhe** [comment]
This documentation is for `@aws-sdk/client-dynamodb`. You are using `@aws-sdk/lib-dynamodb`.
