### ISSUE TITLE
DocumentClient incorrectly marshalls binary data types when using `convertClassInstanceToMap: true`

### ISSUE THREAD

**Issue by dabrowne** [aws/aws-sdk-js-v3#5824]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When writing data using `DynamoDBDocumentClient` with `marshallOptions.convertClassInstanceToMap = true`, binary data values are incorrectly written to Dynamo as the `"M"` (map) data type rather than the `"B"` (binary) data type.

### SDK version number

@aws-sdk/lib-dynamodb@3.504.0

### Which JavaScript Runtime is this issue in?

All

### Details of the browser/Node.js/ReactNative version

All

### Reproduction Steps

```ts
const client = DynamoDBDocumentClient.from(new DynamoDBClient(), {
  marshallOptions: {
    convertClassInstanceToMap: true,
  },
});

client.send(new PutCommand({
  TableName: "my-table",
  Item: {
    key: "my-key",
    data: Buffer.from("enchilada"),
  },
}));
```

### Observed Behavior

The marshalled DynamoDB JSON that is written to the database for the `data` attribute contains a Map whose value is equivalent to the result of converting the Buffer to a plain object by iterating over its keys using `Object.entries`:

```json
"data": {
  "M": {
   "0": {
    "N": "101"
   },
   "1": {
    "N": "110"
   },
   "2": {
    "N": "99"
   },
   "3": {
    "N": "104"
   },
   "4": {
    "N": "105"
   },
   "5": {
    "N": "108"
   },
   "6": {
    "N": "97"
   },
   "7": {
    "N": "100"
   },
   "8": {
    "N": "97"
   }
  }
}
```

### Expected Behavior

The marshalled DynamoDB JSON that is written to the database should contain the `data` attribute as a binary value:

```json
"data": {
  "B": "ZW5jaGlsYWRh"
}
```

### Possible Solution

This bug was introduced with https://github.com/aws/aws-sdk-js-v3/pull/5697 which blindly converts anything that has `typeof` of `object` into a plain JS object.

This fails to account for the fact that there are a large number of types that fit this signature but should be left intact, as is accounted for [here](https://github.com/aws/aws-sdk-js-v3/blob/f0fac718c1628216617bad865ee1486793c5b21a/packages/util-dynamodb/src/convertToAttr.ts#L13-L56) and [here](https://github.com/aws/aws-sdk-js-v3/blob/f0fac718c1628216617bad865ee1486793c5b21a/packages/util-dynamodb/src/convertToAttr.ts#L174-L198).

I'd imagine this change has also broken marshalling for other data type such as `Set`.

**Comment by kuhe** [comment]
Thanks for reporting this. A fix was released in https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.523.0.

https://www.npmjs.com/package/@aws-sdk/lib-dynamodb/v/3.523.0

**Comment by dabrowne** [comment]
Great turnaround. Thanks @kuhe!

**Comment by kuhe** [comment]
Related report of the issue affecting AWS Lambda provided SDKs: https://github.com/aws/aws-sdk-js-v3/issues/5868
