### ISSUE TITLE
CredentialsProviderError: Could not load credentials from any providers intermittently

### ISSUE THREAD

**Issue by danielblignaut** [aws/aws-sdk-js-v3#5829]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Hi,

we are receiving the following error: ```CredentialsProviderError: Could not load credentials from any providers``` intermittently from our Fargate ECS task that is trying to connect to DynamoDB. We do have regular healthchecks that create new instances of the DynamoDB client and it seems reasonable to assume that this could be related to https://github.com/aws/aws-sdk-js-v3/issues/4867

It seems reasonable to assume that the SDK should manage credentials in the background, including caching them for subsequent client instantiations, etc.

Are there plans to add support for this? 

### SDK version number

@aws-sdk/credential-provider-node@3.485.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.10.0

### Reproduction Steps

deploy an ECS tasks the creates multiple AWS clients in succession

### Observed Behavior

we are receiving the following error: ```CredentialsProviderError: Could not load credentials from any providers``` intermittently

### Expected Behavior

The AWS client should instantiate itself successfully

### Possible Solution

The AWS SDK should take care to cache credentials

**Comment by kuhe** [comment]
Please add a code example of how you are initializing the client and what environment variables are being passed in.

For example:

```ts
process.env.??? = ???

new DynamoDB({
  credentials: ???
});

```

**Comment by RanVaknin** [comment]
Hi @danielblignaut ,

Credential resolution is happening per SDK call, and not on client creation. 
When the API call fires, the SDK will try to construct the request, it will check the cache that is set on that defaultProvider, if the cache is empty, it will attempt to retrieve new credentials by going through all of the credential providers on the chain until it finds a valid source of credentials (or errors out).

When you deploy your application on ECS, and you use the default provider, the SDK will look through the entire provider list until it reaches the very last one (fromContainerMetadata) which in your case should resolve, if ECS injected the correct env variables, the provider will use those to fetch info from the container metadata service and exchange that info for valid credentials.

The env variable the SDK's provider expects is `ENV_CMDS_AUTH_TOKEN` AND either `AWS_CONTAINER_CREDENTIALS_FULL_URI` OR `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI`.

>On a per request basis, we do instantiate multiple AWS clients. 

Our recommendation is to construct the SDK client once per service, per region. And not per SDK call. That would explain why your credentials are never cached. 

Without seeing a more complete code snippet it's hard to give advise on what went wrong.

Thanks,
Ran~

**Comment by danielblignaut** [comment]
Hi Ran,

I can confirm this is the case and since changing the code and running load
tests we’ve not seen this error re-occur. Thank you for the feedback

**Comment by RanVaknin** [comment]
Happy to hear that this unblocked you.

All the best,
Ran~
