### ISSUE TITLE
Add waiters for DynamoDB S3 exports and imports

### ISSUE THREAD

**Issue by fabsrc** [aws/aws-sdk-js-v3#5831]
### Describe the feature

Currently, DynamoDB offers the functionality to export and import tables to and from Amazon S3, as highlighted in [this AWS blog post](https://aws.amazon.com/blogs/database/amazon-dynamodb-can-now-import-amazon-s3-data-into-a-new-table/). To enhance the usability of this feature, it would be beneficial to incorporate two additional waiters: `waitUntilExportCompleted` and `waitUntilImportCompleted`. These waiters would monitor the progress of export and import jobs respectively, waiting for their completion.

### Use Case

A possible use case for this feature could be a data migration script tasked with exporting a DynamoDB table to an S3 bucket and subsequently importing it into a different AWS account:

1. **Initiate DynamoDB Export to S3**: The script triggers the export process from DynamoDB to an S3 bucket.
2. **Wait for Export Completion**: The script pauses execution, awaiting confirmation of the export's successful completion.
3. **Retrieve S3 Path from Export**: Once the export is finalized, the script retrieves the path to the exported data stored in the designated S3 bucket.
4. **Trigger DynamoDB Import**: With the exported data path secured, the script initiates the import process into the target DynamoDB instance.
5. **Wait for Import Completion**: The script again enters a waiting state, ensuring that the import operation concludes successfully before proceeding.
6. **Cleanup S3 Bucket**: Finally, once the import is verified, the script removes any temporary files or artifacts from the S3 bucket.

### Proposed Solution

The waiters could be added to the `dynamodb.json` model file, which would make them available as TypeScript functions after running the codegen.

<details>
  <summary>Diff for dynamodb.json</summary>

```diff
diff --git a/codegen/sdk-codegen/aws-models/dynamodb.json b/codegen/sdk-codegen/aws-models/dynamodb.json
index 8418bf7ddd7..36206d4dfda 100644
--- a/codegen/sdk-codegen/aws-models/dynamodb.json
+++ b/codegen/sdk-codegen/aws-models/dynamodb.json
@@ -2933,7 +2933,34 @@
         }
       ],
       "traits": {
-        "smithy.api#documentation": "<p>Describes an existing table export.</p>"
+        "smithy.api#documentation": "<p>Describes an existing table export.</p>",
+        "smithy.waiters#waitable": {
+          "ExportCompleted": {
+            "acceptors": [
+              {
+                "state": "success",
+                "matcher": {
+                  "output": {
+                    "path": "ExportDescription.ExportStatus",
+                    "expected": "COMPLETED",
+                    "comparator": "stringEquals"
+                  }
+                }
+              },
+              {
+                "state": "failure",
+                "matcher": {
+                  "output": {
+                    "path": "ExportDescription.ExportStatus",
+                    "expected": "FAILED",
+                    "comparator": "stringEquals"
+                  }
+                }
+              }
+            ],
+            "minDelay": 20
+          }
+        }
       }
     },
     "com.amazonaws.dynamodb#DescribeExportInput": {
@@ -3095,7 +3122,44 @@
         }
       ],
       "traits": {
-        "smithy.api#documentation": "<p> Represents the properties of the import. </p>"
+        "smithy.api#documentation": "<p> Represents the properties of the import. </p>",
+        "smithy.waiters#waitable": {
+          "ImportCompleted": {
+            "acceptors": [
+              {
+                "state": "success",
+                "matcher": {
+                  "output": {
+                    "path": "ImportTableDescription.ImportStatus",
+                    "expected": "COMPLETED",
+                    "comparator": "stringEquals"
+                  }
+                }
+              },
+              {
+                "state": "failure",
+                "matcher": {
+                  "output": {
+                    "path": "ImportTableDescription.ImportStatus",
+                    "expected": "FAILED",
+                    "comparator": "stringEquals"
+                  }
+                }
+              },
+              {
+                "state": "failure",
+                "matcher": {
+                  "output": {
+                    "path": "ImportTableDescription.ImportStatus",
+                    "expected": "CANCELLED",
+                    "comparator": "stringEquals"
+                  }
+                }
+              }
+            ],
+            "minDelay": 20
+          }
+        }
       }
     },
     "com.amazonaws.dynamodb#DescribeImportInput": {
```

</details>

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

v3.521.0

### Environment details (OS name and version, etc.)

macOS 14.2.1, NodeJS 20

**Comment by RanVaknin** [comment]
Hi @fabsrc ,

All of the SDK code including waiters is code generated from the API model of each service team. 
In order for this to be added in the SDK, the S3 team needs to define this as a wait-able operation, meaning the S3 service should add support for and more importantly, model a response member that represents a state that can be listened on.

Because this is a feature request to the S3 service itself, and not the SDK team, I have created this feature request on your behalf (`#P120301656`). We wont be able to actively monitor the progress of this but if you have access to AWS support you can reach out regarding the status of your feature request using the ticket ID I provided.

Thanks again,
Ran~
