### ISSUE TITLE
(@aws-sdk/cloudfront-signer) getSignedCookies does not work with Policy

### ISSUE THREAD

**Issue by nayabatir1** [aws/aws-sdk-js-v3#5836]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

`CloudfrontSignInputWithPolicy` Ts definition is not accurate.

In reference to [issue](https://github.com/aws/aws-sdk-js-v3/issues/4516), [solution](https://github.com/aws/aws-sdk-js-v3/issues/4516) Proposed by Yenfry doesn't work as  when passing policy and not providing url in `getSignedCookies` method I'm getting ts error.

<img width="669" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/91016903/aec7cfe9-f555-45cc-87ab-2bf7614502cb">
<img width="801" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/91016903/b66c4836-5ae9-4490-a7cf-5e3458b775e4">

### SDK version number

@aws-sdk/cloudfront-signer: ^3.521.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.11.0

### Reproduction Steps

```js
  const privateKey = readFileSync('./private_key.pem');
  const keyPairId = 'KEY-PAIR-ID';

  const policy = {
    'Statement': [
      {
        'Resource': cloudfrontDistributionDomain + '/*',
        'Condition': {
          'DateLessThan': {
            'AWS:EpochTime': Date.now(),
          },
        },
      },
    ],
  };

  const policyString = JSON.stringify(policy);

  const signedUrl = getSignedCookies({
    keyPairId,
    privateKey,
    policy: policyString,
  });
```

### Observed Behavior

On implementin same I'm getting ts error
>Argument of type '{ keyPairId: string; privateKey: Buffer; policy: string; }' is not assignable to parameter of type 'CloudfrontSignInput'.
  Type '{ keyPairId: string; privateKey: Buffer; policy: string; }' is not assignable to type 'CloudfrontSignInputWithPolicy'.
    Property 'url' is missing in type '{ keyPairId: string; privateKey: Buffer; policy: string; }' but required in type 'CloudfrontSignInputBase'.ts(2345)
sign.d.ts(6, 5): 'url' is declared here.

### Expected Behavior

If I'm passing policy, url should not be mandatory in Ts definition.

### Possible Solution

On modifying ts definition `getSignedCookies` function works perfectly fine.
I've removed `url` from `CloudfrontSignInputBase` and added it to `CloudfrontSignInputWithParameters`. 
After doing this `getSignedCookies` works like a charm

Here is modified ts definition of `CloudfrontSignInputWithParameters`

```ts
export interface CloudfrontSignInputBase {
    /** The ID of the Cloudfront key pair. */
    keyPairId: string;
    /** The content of the Cloudfront private key. */
    privateKey: string | Buffer;
    /** The passphrase of RSA-SHA1 key*/
    passphrase?: string;
    /** The date string for when the signed URL or cookie can no longer be accessed. */
    dateLessThan?: string;
    /** The IP address string to restrict signed URL access to. */
    ipAddress?: string;
    /** The date string for when the signed URL or cookie can start to be accessed. */
    dateGreaterThan?: string;
}
export type CloudfrontSignInputWithParameters = CloudfrontSignInputBase & {
    /** The date string for when the signed URL or cookie can no longer be accessed */
    dateLessThan: string;
    /** For this type policy should not be provided. */
    policy?: never;
    /** The URL string to sign. */
    url: string;
};
```

**Comment by RanVaknin** [comment]
Hi @nayabatir1 ,

This makes sense. Looking at the Go SDK implementation, I dont see a reference to URL
https://github.com/aws/aws-sdk-go/blob/main/service/cloudfront/sign/sign_cookie.go


Adding to our backlog. 

Thanks,
Ran~

**Comment by nayabatir1** [comment]
@RanVaknin should I create a pull request for the same?
I'm currently working on a project and it would be very much helpful if we can push the changes at the earliest.

**Comment by RanVaknin** [comment]
Hi @nayabatir1 ,

Feel free to submit a PR, I'll have someone take a look. 
Thanks,
Ran~
