### ISSUE TITLE
MIGRATION ISSUE: Invalid or unexpected token ??

### ISSUE THREAD

**Issue by Bharanij27** [aws/aws-sdk-js-v3#5841]
### Pre-Migration Checklist

- [X] I've read the [Migration Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/migrating-to-v3.html).
- [X] I've reviewed the upgrading notes and major version differences mentioned in [`UPGRADING.md`](https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md).
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for similar migration issues.

### Which JavaScript Runtime is this issue in?

Node.js (includes AWS Lambda)

### AWS Lambda Usage

- [X] Yes, my application is running on AWS Lambda.
- [ ] No, my application is not running on AWS Lambda.

### Describe the Migration Issue

In my application, I use one package (Package A) with the dependency of aws-sdk. I have migrated from v2 to v3 in package A and then published it. I got the error below when I executed the npm run test command using Mocha in my application. My application is running as expected but I can't run the unit test cases.

I'm using node v18.17.0 and tried with v16 and v14 as well.

Can someone please help to resolve this issue?
Thanks in advance

### Observed Differences/Errors

```
node_modules/append-transform/index.js:58
                                        module._compile(code, filename);
            ^
node_modules/@aws-sdk/client-dynamodb/dist-cjs/index.js:191
    useDualstackEndpoint: options.useDualstackEndpoint ?? false,
                                                        ^
SyntaxError: Invalid or unexpected token
    at Object.replacementCompile (node_modules/append-transform/index.js:58:13)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10).
    
```

**Comment by RanVaknin** [comment]
Hi @Bharanij27 ,

Without seeing you code and the test we can't say why you are seeing this error. 
This seems like an error with null coalescing "??" operator that your testing library might not support (you might need to update the Mocha, or any other transpilers that you might be using).

Thanks,
Ran~

**Comment by Bharanij27** [comment]
After updating the mocha version this issue was fixed.
Thanks
