### ISSUE TITLE
Lambda can throw SyntaxError with empty $response body

### ISSUE THREAD

**Issue by akeating** [aws/aws-sdk-js-v3#5851]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

In the presence of http errors, the sdk assumes the error body is serialized as json. But this is not always the case. For example a 503 with html body can occur when lambda is unreachable somehow or 404 with plain text body can be thrown when the lambda `endpoint` is defined incorrectly.

When the error body is not json, the deserialization attempt will throw a SyntaxError. Not only does it do that, the attached `$response` body is always empty because it was consumed during the deserialization attempt.

### SDK version number

@aws-sdk/client-lambda@3.525.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.10.0

### Reproduction Steps

```js
test('returns error response body correctly', async () => {
  const config: LambdaClientConfig = {
    region: 'us-east-1',
  };

  config.requestHandler = new (class {
    async handle() {
      return {
        response: new HttpResponse({
          statusCode: 503,
          body: Readable.from(Buffer.from('<html>Some unexpected html</html>')),
        }),
      };
    }
  })();

  const lambdaClient = new LambdaClient(config);

  const params: InvokeCommandInput = {
    FunctionName: 'test',
    InvocationType: 'RequestResponse',
    LogType: 'None',
    Payload: Uint8Array.from(Buffer.from(JSON.stringify({ foo: 'bar' }))),
  };

  const result = await lambdaClient.send(new InvokeCommand(params)).catch((_) => _);
  expect(result).toBeInstanceOf(SyntaxError);
  const syntaxError: SyntaxError = result as SyntaxError;
  expect(syntaxError.message).toEqual(
    'Unexpected token \'<\', "<html>Some"... is not valid JSON\n' +
      '  Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.',
  );
  // The sdk adds a hidden field to the error object
  // https://github.com/aws/aws-sdk-js-v3/pull/4592/files#diff-8700e9d6ea5f0b48b76a520f0138954d8ada56d2abb3692c49b95e0df01ce3c5
  expect(syntaxError['$response']).toBeInstanceOf(HttpResponse);
  const httpResponse: HttpResponse = syntaxError['$response'] as HttpResponse;
  expect(httpResponse.statusCode).toEqual(503);
  const body = await httpResponse.body;
  const text = await consumers.text(body);
  expect(text).toEqual('<html>Some unexpected html</html>');
});
```

### Observed Behavior

A `SyntaxError` was thrown and the attached `$response` body was empty.

### Expected Behavior

I expect the `$response` body to contain the body.

The [deserializerMiddleware](https://github.com/aws/aws-sdk-js-v3/pull/4592/files#diff-8700e9d6ea5f0b48b76a520f0138954d8ada56d2abb3692c49b95e0df01ce3c5) adds the following message:
```
Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.
```

However, it is not possible to see the raw response body which is useful for troubleshooting purposes.

### Possible Solution

I believe as a design, the sdk should not assume the error body is encoded as json. Rather, there could be an attempt to parse the json, but fall-back gracefully.

The `parseBody` function is this:
```js
const parseBody = (streamBody: any, context: __SerdeContext): any =>
collectBodyString(streamBody, context).then((encoded) => {
  if (encoded.length) {
    return JSON.parse(encoded);
  }
  return {};
});
```

It could be something like this:
```js
const parseBody = (streamBody: any, context: __SerdeContext): any =>
collectBodyString(streamBody, context).then((encoded) => {
  if (encoded.length) {
    try {
      return JSON.parse(encoded);
   } catch (err) {
      // The body is not json, just return the raw body
     return encoded;
  }
  return {};
});
```
This means supporting code should not assume an object is returned or this return type could return something such as: 
```
{
  rawBody: encoded
}
```
...and this could be handled gracefully further upstream.

The would result in a different error as well. Certainly `SyntaxError` is not really what's going on here.

### Additional Information/Context

I notice the assumption that the error response body is json is pervasive throughout the sdk. I believe this should also change, not only in `LambdaClient`.

**Comment by RanVaknin** [comment]
Hi @akeating ,

Each AWS service defines a service level protocol that specifies what format the requests and responses it accepts and sends.
In Lambda's case, the Lambda API [is defined](https://github.com/aws/aws-sdk-js-v3/blob/45ea34638870b9313612fd86fcc9ec40ac228890/codegen/sdk-codegen/aws-models/lambda.json#L246) as REST JSON. This means that Lambda must receive requests and send back responses in JSON. 

Because of this "contract" all of the SDKs code generators will generate deserializers and serializer functions that are scoped to that specific format (JSON). 
If a service sends back a response that is not in JSON, the SDK deserialization logic will fail. We cannot make this more lenient because the AWS API standards require adherence to whichever network protocol the service is defined in.

>### Expected Behavior
>
>I expect the $response body to contain the body.

This part I'm not entirely sure about. I don't know why you are returning your body as a stream instead of just a string in the first place. 
I'm not aware of any error response thrown from AWS containing a body that is a stream, therefore I'm not sure if there's built in support for the "hint" component to address that. 

It's not clear what what is the purpose of your reproduction code with the mocked response. Did you run code against Lambda and got a 503 with a stream body representing an HTML string? Are you seeing this issue "in the wild?"

Thanks,
Ran~

**Comment by akeating** [comment]
Thank you for your prompt outreach. 

We both agree that the sdk should 100% support the api contract a service has. However, it should also be resilient to support the fact that the internet (and aws) has many points of failure. Not all responses handled by the sdk are going to 100% conform to a service contract because http responses are not all produced by your internal services. Errors can be produced from many layers between our service and Lambda.

> It's not clear what what is the purpose of your reproduction code with the mocked response.

The purpose of the mock code is to reproduce the condition where the sdk fails to neatly handle the condition specified in the test:

  A 503 response, with html body

> I don't know why you are returning your body as a stream instead of just a string in the first place

If I'm not mistaken, http response bodies are passed around as streams. The `parseBody` function outlined above was lifted directly from your sdk and it indicates that the authors of this deserialization code also expect the body to be streamed in. I would be getting into the weeds here, but the response body at a low-level is an [IncomingMessage](https://nodejs.org/api/http.html#class-httpincomingmessage) which is `Readable`, i.e. it's a stream.

> Are you seeing this issue "in the wild?"

We see this problem several times per month in the logs and we believe it's service outage. It's a [known](https://github.com/aws/aws-sdk-js-v3/issues/4576) pain-point. 

If I could actually see the html body and log it, I might be able to provide more color to this ticket. Still, I think I have enough information and a test to have added value here.

**Comment by kuhe** [comment]
Hi @akeating, if you do a fresh (no lockfile) install and get the following version https://www.npmjs.com/package/@aws-sdk/client-lambda/v/3.529.1, and also transitively pick up https://www.npmjs.com/package/@smithy/middleware-serde/v/2.2.1, you should be able to inspect plain text error response bodies of the wrong format with respect to the service model.

Using your example modified:
```ts
import { Lambda } from "@aws-sdk/client-lambda";
import { HttpResponse } from "@smithy/protocol-http";
import { Readable } from "stream";

const config = {
  region: "us-east-1",
  maxAttempts: 1,
};

config.requestHandler = new (class {
  async handle() {
    return {
      response: new HttpResponse({
        statusCode: 503,
        body: Readable.from(Buffer.from("<html>Some unexpected html</html>")),
      }),
    };
  }
})();

const lambdaClient = new Lambda(config);

const params = {
  FunctionName: "test",
  InvocationType: "RequestResponse",
  LogType: "None",
  Payload: Uint8Array.from(Buffer.from(JSON.stringify({ foo: "bar" }))),
};

try {
  await lambdaClient.invoke(params);
} catch (error) {
  console.log("name:", error.name);
  console.log("message:", error.message);
  console.log(error.$response);
}
```

output:
```
name: SyntaxError
message: Unexpected token < in JSON at position 0
  Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.
HttpResponse {
  statusCode: 503,
  reason: undefined,
  headers: {},
  body: '<html>Some unexpected html</html>'
}
```

I want to note a distinction when handling errors thrown by SDK operations:

- if there is no parsing error, then the thrown error will be an extension of the `ServiceException` class from the SDK. In this case, the HttpResponse body, that is `error.$response.body` is still a consumed stream. The thrown `error` object will contain all parsed information from the stream. This preserves existing behavior. 
- if there _is_ a parsing error, then the thrown error will be a JavaScript language built-in error such as `SyntaxError` from `JSON.parse(string)`. It will not have `$metadata` like HttpStatusCode. Instead, this information stays on the `error.$response` hidden field, to be inspected as a plain HTTP response object. In this case `error.$response.body` may be a string, if any plaintext were in the response body.
