### ISSUE TITLE
AWS SNS Publish Command ignores Message Attributes

### ISSUE THREAD

**Issue by RichardSilveira** [aws/aws-sdk-js-v3#5852]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

🧨💥 Any basic example of an SNS message being sent with a Message Attribute leveraging the `PublishCommand` object must not be working nowadays.

```
const publish = new PublishCommand({
        Message: "sample message",
        MessageAttributes: {
          StaticTraceId: {
            DataType: 'String',
            StringValue: "sample value",
          },
        },
        TopicArn: process.env.MY_TOPIC_ARN,
      })

      const publishOutput = await snsClient.send(publish)
```

🐛 Same as this other one - https://github.com/aws/aws-sdk-js-v3/issues/5666

### SDK version number

@aws-sdk/client-sns@3.525.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.9.0

### Reproduction Steps

Please follow this other closed due to inactivity issue to see the steps - https://github.com/aws/aws-sdk-js-v3/issues/5666

🎯 But as I've said before, I bet that any simple silly example won't work with the described library version.

### Observed Behavior

The `MessageAttributes` is being sent as part of the message body 🤦‍♂️

### Expected Behavior

Have the `MessageAttributes` as part of the message attributes ✌️

**Comment by RichardSilveira** [comment]
I've not noticed that the referenced issue was closed on purpose _(not due to inactivity)_ but still without a proper solution 😭

I hope someone can let me know if I am missing something or if that error is indeed happening and how to overcome it, please 🙏

**Comment by aBurmeseDev** [comment]
HI @RichardSilveira - thanks for reaching out. 

Could you please verify to make sure `raw message delivery` is enabled in your subscription? Service requires it enabled when you're sending a maximum of 10 message attributes and if it's more than 10, it must be disabled as mentioned in the documentation: https://docs.aws.amazon.com/sns/latest/dg/sns-message-attributes.html

> For SQS subscriptions, a maximum of 10 message attributes can be sent when [Raw Message Delivery](https://docs.aws.amazon.com/sns/latest/dg/sns-large-payload-raw-message-delivery.html) is enabled. To send more than 10 message attributes, Raw Message Delivery must be disabled.

I tested and confirmed that message attributes will only pass through when Raw Message Delivery is enabled. Hope it helps but please let me know if the issue persists.

Best,
John

**Comment by RichardSilveira** [comment]
It worked like a charm! 💯

Thanks for your support on this 🙏

Shame on me by not have noticed that in the official docs 🤦‍♂️
