### ISSUE TITLE
client-bedrock-runtime: Fail to send InvokeModel using Message API with Claude v3

### ISSUE THREAD

**Issue by tmokmss** [aws/aws-sdk-js-v3#5853]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When I try to use InvokeModel with [Claude Messages API](https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-anthropic-claude-messages.html), it throws a validation error.

### SDK version number

@aws-sdk/client-bedrock-runtime@3.525.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.10.0

### Reproduction Steps

Run this code:

```js
// index.mjs
import { BedrockRuntimeClient, InvokeModelCommand } from '@aws-sdk/client-bedrock-runtime';

const client = new BedrockRuntimeClient({ region: 'us-west-2' });

const resp = await client.send(
  new InvokeModelCommand({
    modelId: 'anthropic.claude-3-sonnet-20240229-v1:0',
    accept: 'application/json',
    contentType: 'application/json',
    body: JSON.stringify({
      anthropic_version: 'bedrock-2023-05-31',
      max_tokens: 4096,
      temperature: 0,
      system: 'answer in English',
      messages: [
        {
          role: 'user',
          content: {
            type: 'text',
            text: 'What does Claude mean?',
          },
        },
      ],
    }),
  })
);
console.log(resp);
```

### Observed Behavior

Got this error

```
ValidationException: Malformed input request: #: subject must not be valid against schema {"required":["messages"]}#/messages/0/content: expected type: String, found: JSONObject#/messages/0/content: expected type: JSONArray, found: JSONObject, please reformat your input and try again.
    at de_ValidationExceptionRes (/root/node_modules/@aws-sdk/client-bedrock-runtime/dist-cjs/index.js:683:21)
    at de_CommandError (/root/node_modules/@aws-sdk/client-bedrock-runtime/dist-cjs/index.js:541:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /root/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
    at async /root/node_modules/@smithy/core/dist-cjs/index.js:165:18
    at async /root/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
    at async /root/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22
    at async file:///root/index.mjs:5:14 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: '...',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}
```

### Expected Behavior

Request successes.

**Comment by tmokmss** [comment]
Sorry it was my fault. (wrong schema)

**Comment by tmokmss** [comment]
P.S. anyone seeing an error like `ValidationException: Malformed input request: #: required key [prompt] not found#: required key [max_tokens_to_sample] not found#: extraneous key [max_tokens] is not permitted, please reformat your input and try again.` even though you are sure using claude v3, check if `system` or `messages` is not undefined.

**Comment by rock288** [comment]
I'm also using claude v3 but I'm getting an error in the BODY section: in messages 

 ```
messages: [
        {
          role: 'user',
          content: {
            type: 'text',
            text: 'What does Claude mean?',
          },
        },
      ],
```


I have the role system and get the error as below.
`Malformed input request: #: subject must not be valid against schema {\\\"required\\\":[\\\"messages\\\"]}#/messages/0/role: text is not a valid enum value, please reformat your input and try again.\",\"`
Please tell me the types of roles that can be used in messages

**Comment by tmokmss** [comment]
@rock288 You can only use `user` or `assistant` as a role. A system prompt should be set as a `system` property. https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-anthropic-claude-messages.html#model-parameters-anthropic-claude-messages-request-response

**Comment by rock288** [comment]
@tmokmss  That's right, there are only 2 roles, user and assistant. I have another problem:
"text" in content when I upload 21000 characters I receive an error Input is too long for requested model. Can we use 200k tokens in claude v3?
```
messages: [
       {
         role: 'system',
         content: {
           type: 'text',
           text: 'What does Claude mean?',
         },
       },
     ],
```

**Comment by tmokmss** [comment]
@rock288 I heard that if you set `max_token` above 4096, you will get the error. `max_token` sets the limit of output token, which is still limited to 4096 in Claude 3. https://docs.anthropic.com/claude/docs/models-overview#model-comparison
