### ISSUE TITLE
ReferenceError: Property 'e' doesn't exist

### ISSUE THREAD

**Issue by amit-lekhak** [aws/aws-sdk-js-v3#5857]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The existing code with request to textract(previously working) is suddenly failing with react native but works normally with node.js. 

**The send command fails with error: ReferenceError: Property 'e' doesn't exist**

With latest version, ot also throws error: **Cannot read property 'apply ' of undefined**
It was resolved by importing "@aws-sdk/util-endpoints"

### SDK version number

@aws-sdk/client-textract@3.461.0, ...

### Which JavaScript Runtime is this issue in?

React Native

### Details of the browser/Node.js/ReactNative version

0.71.2

### Reproduction Steps

`

    // Configuration for the Textract client
    const textractClient = new TextractClient({
      region: REGION,
      credentials: {
        accessKeyId: ACCESS_KEY,
        secretAccessKey: SECRET_KEY,
      },
    });

    // Convert the image into a base64 string
    const base64Image = await RNFS.readFile(imageUrl, 'base64');

    // Convert the image data into a buffer
    const imageBuffer = toByteArray(base64Image);

    // Parameters for AnalyzeDocumentCommand
    const params = {
      Document: {
        Bytes: imageBuffer,
      },
      FeatureTypes: ['TABLES'],
    };

    // Call the Textract analyze document function
    const command = new AnalyzeDocumentCommand(params);
    const response = await textractClient.send(command);
`

### Observed Behavior

Request failed with error: **ReferenceError: Property 'e' doesn't exist**

### Expected Behavior

It should work normally and return response

**Comment by aBurmeseDev** [comment]
HI @amit-lekhak - thanks for reaching out. 

We've had this similar report [here](https://github.com/aws/aws-sdk-js-v3/issues/5623) previously, and from my [quick research](https://www.google.com/search?q=%22ReferenceError%3A+Property+%27e%27+doesn%27t+exist%22&sca_esv=5029e200667018e0&rlz=1C5GCEM_enUS1007US1007&sxsrf=ACQVn0_cjDxoYbvuhAn1cEOxB2ADOljSPw%3A1709748073273&ei=aa_oZdWtEL3ZkPIPq_CokAw&ved=0ahUKEwiVhsD0m-CEAxW9LEQIHSs4CsIQ4dUDCBA&uact=5&oq=%22ReferenceError%3A+Property+%27e%27+doesn%27t+exist%22&gs_lp=Egxnd3Mtd2l6LXNlcnAiLCJSZWZlcmVuY2VFcnJvcjogUHJvcGVydHkgJ2UnIGRvZXNuJ3QgZXhpc3QiMgQQIxgnMgUQABiABEj8NlDKCFj_NHABeAGQAQCYAVSgAZEBqgEBMrgBA8gBAPgBAZgCA6ACoAHCAgoQABhHGNYEGLADwgIIEAAYgAQYsAOYAwCIBgGQBgmSBwEzoAe4Cw&sclient=gws-wiz-serp) on the error, a lot of resources lead to ReactNative related repos or topics. Do you mind sharing your React code for me to be able to reproduce this?

Best,
John
