### ISSUE TITLE
Update deprectated @aws-crypto version dependencies

### ISSUE THREAD

**Issue by PaulCarlucciStratascale** [aws/aws-sdk-js-v3#5858]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I've observed this using client-s3 but it's present in others as well.   packages.json specifies
```
    "@aws-crypto/sha1-browser": "3.0.0",
    "@aws-crypto/sha256-browser": "3.0.0",
    "@aws-crypto/sha256-js": "3.0.0",
```

...which is fairly old and pulls in deprecated dependencies, specifically @aws-sdk/util-utf8-browser instead of @smithy/util-utf8 which among other issues causes build issues on modern versions of npm.  sha1-browser is only used by client-s3, but sha256-browser and sha256-js are used in 400+ places within aws-sdk-js-v3.

### SDK version number

@aws-sdk/client-s3@v3.527.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.18.0

### Reproduction Steps

Use client-s3 as directed

### Observed Behavior

@aws-crypto 3.0.0 functions are pulled in

### Expected Behavior

@aws-crypto ^5.2.0 should get pulled instead

### Possible Solution

Version bump dependencies

**Comment by RanVaknin** [comment]
Hi @PaulCarlucciStratascale ,

You already created this issue https://github.com/aws/aws-sdk-js-v3/issues/5305 about the same problem with the @aws-crypto dependencies. 

Please refer to that one for tracking.

Thanks,
Ran~
