### ISSUE TITLE
Missing fast-xml-parser dependency in client-s3 v3.529.0

### ISSUE THREAD

**Issue by ddolcimascolo** [aws/aws-sdk-js-v3#5867]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

A module nor found error is thrown when requiring the client. 

### SDK version number

@aws-sdk/client-s3@3.529.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node 20.9.0

### Reproduction Steps

require('@aws-sdk/client-s3')

### Observed Behavior

Error: Cannot find module 'fast-xml-parser'
Require stack:
- /builds/stordata/cmdb/node_modules/@aws-sdk/core/dist-cjs/index.js
- /builds/stordata/cmdb/node_modules/@aws-sdk/client-s3/dist-cjs/index.js
- my code below

### Expected Behavior

No error is thrown, and require succeeds

### Additional Information/Context

Our CI caught this while upgrading the library. Renovate package diff shows the removed dependency fast xml parser 

https://renovatebot.com/diffs/npm/@aws-sdk%2fclient-s3/3.525.0/3.529.0

**Comment by badfun** [comment]
Also occurring with @aws-sdk/client-codecommit 3.529.0

**Comment by mdouglass** [comment]
We're hitting it with @aws-sdk/clinet-sqs 3.529.0

**Comment by aBurmeseDev** [comment]
Related: https://github.com/aws/aws-sdk-js-v3/issues/5866

Plesae use the previous version or add `fast-xml-parser@4.2.5` to your application temporarily.

**Comment by trivikr** [comment]
https://github.com/aws/aws-sdk-js-v3/issues/5866#issuecomment-1984882353
