### ISSUE TITLE
lib-dynamodb does not marshall binary in v3.515.0 when using AWS Lambda provided SDK

### ISSUE THREAD

**Issue by grant-d** [aws/aws-sdk-js-v3#5868]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug
Summary: In recent versions of JS packages, Dynamo marshalls `Uint8Array` as `List` instead of `Binary`

I redeployed a `Node20` lambda today (in `eu-central-1`) that had no changes to the data layer. But as of that deploy, marshalling `Uint8Array` and/or `Buffer` serializes to a `L`ist and not `B`inary. I have rolled back entirely without success, which leads me to believe the latest SDKs are deployed to lambda already.

The problem seems suspiciously timeous with this recent PR, which changes how data is marshalled. Perhaps unrelated, but it does have changed logic around creating `L`ists instead of `B`inary (and also changes re `convertClassInstanceToMap` which would seem related to the symptoms below):
https://github.com/aws/aws-sdk-js-v3/commit/e1ba507fc84d5ae526fe0ee0a26ea4f039b63d03#diff-8853e9557dcc53577bcb4bd057ea592df1aa7d4bddf478a16024fcfac3e7ce85

Here is a basic repro:
```typescript
import { DynamoDBClient } from '@aws-sdk/client-dynamodb'
import { DynamoDBDocumentClient, TranslateConfig } from '@aws-sdk/lib-dynamodb'
import { UpdateCommand, UpdateCommandInput } from '@aws-sdk/lib-dynamodb'

const client = new DynamoDBClient({ apiVersion: 'latest', region: 'eu-central-1` })

const config: TranslateConfig = {
  marshallOptions: { 
    convertClassInstanceToMap: true, // There are relevant changes in PR related to this option
    removeUndefinedValues: true
  }
}

const dbClient = DynamoDBDocumentClient.from(client, config)

const foo = new Uint8Array([1, 2, 3])
await client.send(new UpdateCommand({
   ... "SET #foo = :foo"
   ... // Eliding idiomatic values
  ["#foo] = "foo",
  [":foo"] = foo
})`
```

Here is the previous result (still working on stamps that I have _not_ re-deployed yet)
They were built using `3.513.0`
<img width="409" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/10214147/2c7ce4bb-0f2e-4d54-8a15-49cd70628e71">

Here is the problematic result:
Built using `3.523.0`
<img width="168" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/10214147/94d0cc11-130b-4f26-a134-afb4cc006c26">
Notice how it's a `L`ist of `M`aps
<img width="184" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/10214147/971529ea-1656-410e-98d3-d28768341838">

As a matter of diligence - even though our code has not changed - I logged the type of the value at the last possible moment before calling into DynamoDb, to ensure that we are passing the expected value through:
```
console.debug('type', { name, type: typeof value, length: value?.length, ctor: value?.constructor?.name })
```
<img width="361" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/10214147/ad196e28-f780-4b5b-b794-a3ca853af2b3">

### SDK version number

"@aws-sdk/lib/util/client-dynamodb" "^3.523.0"

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node 20 on AWS Lambda

### Reproduction Steps

See main comments

### Observed Behavior

Binary is serialized as a `L`ist of `M`aps.

### Expected Behavior

Binary is serialized as a `B`inary

**Comment by RanVaknin** [comment]
Hi @grant-d,

Thanks for the in depth analysis.
>which leads me to believe the latest SDKs are deployed to lambda already.

You are correct. We will look into it with priority. 

Thanks,
Ran~

**Comment by kuhe** [comment]
Depending on how you are deploying, there may be a step that removes AWS SDK from your uploaded code under the assumption that it is provided by Lambda. If you could disable this step, or otherwise ensure v3.523.0 or higher is deployed to your Lambda function, it should bring in the fix.

**Comment by kuhe** [comment]
To confirm the desired behavior, this is the test code I'm running:

(using TypeScript with a mix of import/require)

```ts
import { DynamoDB } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocument } from "@aws-sdk/lib-dynamodb";
const client_metadata = require("@aws-sdk/client-dynamodb/package.json");
const util_metadata = require("@aws-sdk/util-dynamodb/package.json");
const lib_metadata = require("@aws-sdk/lib-dynamodb/package.json");

(async () => {
  console.log("versions:", {
    client: client_metadata.version,
    util: util_metadata.version,
    lib: lib_metadata.version,
  });

  const ddb = new DynamoDB({ region: "us-west-2" });
  const doc = DynamoDBDocument.from(ddb, {
    marshallOptions: {
      convertClassInstanceToMap: true,
    },
  });

  await doc.put({
    TableName: "test",
    Item: {
      id: "bits",
      data: new Uint8Array([1, 2, 3, 4]),
    },
  });

  const get = await doc.get({
    TableName: "test",
    Key: {
      id: "bits",
    },
    ConsistentRead: true,
  });

  console.log(get);
  console.log("get.Item.data should be Uint8Array(4) [ 1, 2, 3, 4 ].");
})();

```

**Comment by grant-d** [comment]
Awesome, thanks @kuhe, I will try deploy the specific version of the sdk and let you know

**Comment by kuhe** [comment]
We will work on applying the fix to AWS Lambda provided AWS SDK for JavaScript v3, but I do not have a time estimate for releasing the fix. 

The recommendation remains to supply your own AWS SDK version in uploaded Lambda functions https://docs.aws.amazon.com/lambda/latest/operatorguide/sdks-functions.html.

**Comment by grant-d** [comment]
@kuhe has this been deployed to lambda yet ?

**Comment by kuhe** [comment]
The Lambda deployment is in progress but not completed yet. It can take a few weeks.
