### ISSUE TITLE
removing the `fast-xml-parser` dependency in `client-sts` is a breaking change

### ISSUE THREAD

**Issue by alex-at-cascade** [aws/aws-sdk-js-v3#5870]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

In https://github.com/aws/aws-sdk-js-v3/commit/304ca3eeeea13634ce491e636a86b3e28fcc3d06#diff-c00e767676da286301fe37f850b4c4cdaa0bf86930bcb97a454342605f95938e the removal of the `fast-xml-parser` dependency is a breaking change, because it's apparently still referenced by some things (e.g. client-lambda)

```
Error: Cannot find module 'fast-xml-parser'
--
39 | Require stack:
40 | - [elided...]/node_modules/@aws-sdk/core/dist-cjs/index.js
41 | - [elided...]/node_modules/@aws-sdk/client-lambda/dist-cjs/auth/httpAuthSchemeProvider.js
42 | - [elided...]/node_modules/@aws-sdk/client-lambda/dist-cjs/index.js
[elided...]
```

### SDK version number

@aws-sdk/client-sts@3.529.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node 18 in CodeBuild

### Reproduction Steps

Try to run code that `require`s the `client-lambda` and `client-sts` packages in a CodeBuild environment.

### Observed Behavior

Error: Cannot find module 'fast-xml-parser'

### Expected Behavior

should not fail

### Possible Solution

restore dependency where needed

**Comment by aBurmeseDev** [comment]
Hi @alex-at-cascade, thanks for reporting this! 

We're aware of it and already merged the fix. Please see https://github.com/aws/aws-sdk-js-v3/issues/5866 and refer to the workaround mentioned!

Apologies for the inconvenience!

**Comment by alex-at-cascade** [comment]
Oh, awesome, thanks! (Sorry i missed seeing the existing issue.)

**Comment by trivikr** [comment]
https://github.com/aws/aws-sdk-js-v3/issues/5866#issuecomment-1984882353
