### ISSUE TITLE
resource-explorer-2 TagResource api call throws unauthorized exception despite full permissions on Lambda

### ISSUE THREAD

**Issue by nikhilenmudi** [aws/aws-sdk-js-v3#5874]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I have a Lambda function as below
```

import { ResourceExplorer2Client, TagResourceCommand } from "@aws-sdk/client-resource-explorer-2";
const reClient = new ResourceExplorer2Client();

export const handler = async (event) => {
  const input = { // TagResourceInput
    resourceArn: encodeURIComponent("arn:aws:lambda:us-east-1:********:function:functionUniqueName"),
    Tags: { tagKey: 'ProjectId' }
  };
  const command = new TagResourceCommand(input);
  const res = await reClient.send(command);

  const response = {
    statusCode: 200,
    body: JSON.stringify(res),
  };
  return response;
};
```
The function execution policy already has the TagResource inline permission as below
```

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "resource-explorer-2:TagResource",
            "Resource": "*"
        }
    ]
}
```
When i execute the function it throws error -
```
2024-03-07T23:24:43.011Z fb8a12ae-3004-4810-80c7-80eceb221dcb ERROR Invoke Error

{
    "errorType": "UnauthorizedException",
    "errorMessage": "Unauthorized",
    "name": "UnauthorizedException",
    "$fault": "client",
    "$metadata": {
        "httpStatusCode": 401,
        "requestId": "389d5698-8d50-46a3-adb2-925492bf276b",
        "attempts": 1,
        "totalRetryDelay": 0
    },
    "message": "Unauthorized",
    "stack": [
        "UnauthorizedException: Unauthorized",
        "    at de_UnauthorizedExceptionRes (/var/runtime/node_modules/@aws-sdk/client-resource-explorer-2/dist-cjs/index.js:1245:21)",
        "    at de_CommandError (/var/runtime/node_modules/@aws-sdk/client-resource-explorer-2/dist-cjs/index.js:1141:19)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
        "    at async /var/runtime/node_modules/@aws-sdk/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20",
        "    at async /var/runtime/node_modules/@aws-sdk/node_modules/@smithy/core/dist-cjs/index.js:165:18",
        "    at async /var/runtime/node_modules/@aws-sdk/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38",
        "    at async /var/runtime/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22",
        "    at async Runtime.handler (file:///var/task/index.mjs:16:15)"
    ]
}

```
In the documentation the example provides a POST request with Authorization headers however the sdk does not have this mechanism neither the documentation of the API provides any information.

### SDK version number

@aws-sdk/client-resource-explorer-2

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20

### Reproduction Steps

The lambda code included in the bug report can be used to reproduce the issue. Use Node 20.x as runtime version.

### Observed Behavior

2024-03-07T23:24:43.011Z fb8a12ae-3004-4810-80c7-80eceb221dcb ERROR Invoke Error

{
    "errorType": "UnauthorizedException",
    "errorMessage": "Unauthorized",
    "name": "UnauthorizedException",
    "$fault": "client",
    "$metadata": {
        "httpStatusCode": 401,
        "requestId": "389d5698-8d50-46a3-adb2-925492bf276b",
        "attempts": 1,
        "totalRetryDelay": 0
    },
    "message": "Unauthorized",
    "stack": [
        "UnauthorizedException: Unauthorized",
        "    at de_UnauthorizedExceptionRes (/var/runtime/node_modules/@aws-sdk/client-resource-explorer-2/dist-cjs/index.js:1245:21)",
        "    at de_CommandError (/var/runtime/node_modules/@aws-sdk/client-resource-explorer-2/dist-cjs/index.js:1141:19)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
        "    at async /var/runtime/node_modules/@aws-sdk/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20",
        "    at async /var/runtime/node_modules/@aws-sdk/node_modules/@smithy/core/dist-cjs/index.js:165:18",
        "    at async /var/runtime/node_modules/@aws-sdk/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38",
        "    at async /var/runtime/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22",
        "    at async Runtime.handler (file:///var/task/index.mjs:16:15)"
    ]
}

### Expected Behavior

The lambda function should have been tagged with a success response from API

**Comment by RanVaknin** [comment]
Hi @nikhilenmudi ,

The error you are getting is misleading because you are wrapping your ARN with `encodeURIComponent` which is incorrect.
When you remove that and pass the arn directly, the error you will get will be this:
`BadRequestException: Invalid input resource arn: expected vendor resource-explorer-2`

This is because Resource explorer 2 tagging is meant to tag views which are a RE2 specific construct 
https://docs.aws.amazon.com/resource-explorer/latest/userguide/manage-views-create.html

If you want to tag your lambda function you should use https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/lambda/command/TagResourceCommand/

Let me know if this helps.
Thanks,
Ran~

**Comment by nikhilenmudi** [comment]
Thanks Ran,
Now I get it. Both the error messages were misleading. I should instead use Resource Groups Tagging API
