### ISSUE TITLE
(Lambda) Can't create aws lambda functions in several regions

### ISSUE THREAD

**Issue by 1bye** [aws/aws-sdk-js-v3#5877]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I'm trying to create aws lambda function in several regions as `eu-north-1`, `eu-south-2` and etc... So when I trying set region, for example "eu-south-1" it occurs following error: `InvalidSignatureException: Credential should be scoped to a valid region.` or just creates function using region from global aws config where is `eu-north-1`

If I change aws global config region for example to `eu-south-2`, then it allows to create functions in `eu-south-2`, but in `eu-north-1` it occur error.

### SDK version number

@aws-sdk/client-lambda@3.529.1

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.19.0 (Node.js)

### Reproduction Steps

```js
import { strToU8, zipSync } from "fflate";
import { LambdaClient, CreateFunctionCommand } from "@aws-sdk/client-lambda";

// If I set region like that it, creates function in "eu-north-1" because it set in aws global config
const lambda = new LambdaClient([{
    region: "eu-south-2",
}]);

// If I set like that, It occurs "InvalidSignatureException: Credential should be scoped to a valid region."
lambda.config.region = () => "eu-south-2"

await lambda.send(new CreateFunctionCommand({
    FunctionName: "hello-world",
    Runtime: "nodejs18.x",
    Role: "...",
    Handler: "handler",
    Code: {
        ZipFile: zipSync({
            "index.js": strToU8(`export const handler = () => ({ status: 200, body: "Hello world!" })`)
        })
    }
}))
```

### Observed Behavior

Full error log:
```js
808 | }, "stripLeadingZeroes");
809 | 
810 | // src/exceptions.ts
811 | var _ServiceException = class _ServiceException extends Error {
812 |   constructor(options) {
813 |     super(options.message);
          ^
InvalidSignatureException: Credential should be scoped to a valid region. 
      at new _ServiceException (/home/mrbye/Documents/GitHub/flow-server/node_modules/@smithy/smithy-client/dist-cjs/index.js:813:5)
      at new _LambdaServiceException (/home/mrbye/Documents/GitHub/flow-server/node_modules/@aws-sdk/client-lambda/dist-cjs/index.js:318:5)
      at /home/mrbye/Documents/GitHub/flow-server/node_modules/@smithy/smithy-client/dist-cjs/index.js:838:20
      at /home/mrbye/Documents/GitHub/flow-server/node_modules/@smithy/smithy-client/dist-cjs/index.js:847:5
      at /home/mrbye/Documents/GitHub/flow-server/node_modules/@aws-sdk/client-lambda/dist-cjs/index.js:3773:14

```

### Expected Behavior

Create aws function in several regions by passing it to class, not to change the whole aws global config each time

### Possible Solution

I don't have ideas

### Additional Information/Context

I'm using latest Bun.js (1.0.30), but I've tried also Node.js and the same error.

**Comment by RanVaknin** [comment]
Hi @1bye ,

In v3 there is no global config object and the concept of updating your sdk client is no longer supported in v3. 
Instead, you are expected to create a separate SDK client for each service in each region.

We have examples of how to set the region in many pieces of documentation we maintain: [Readme](https://github.com/aws/aws-sdk-js-v3?tab=readme-ov-file#getting-started) | [developer guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/setting-region.html) | [supplemental docs](https://github.com/aws/aws-sdk-js-v3/blob/main/supplemental-docs/CLIENTS.md#common-client-constructor-parameters) 

Thanks,
Ran~

**Comment by 1bye** [comment]
> Hi @1bye ,
> 
> In v3 there is no global config object and the concept of updating your sdk client is no longer supported in v3. Instead, you are expected to create a separate SDK client for each service in each region.
> 
> We have examples of how to set the region in many pieces of documentation we maintain: [Readme](https://github.com/aws/aws-sdk-js-v3?tab=readme-ov-file#getting-started) | [developer guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/setting-region.html) | [supplemental docs](https://github.com/aws/aws-sdk-js-v3/blob/main/supplemental-docs/CLIENTS.md#common-client-constructor-parameters)
> 
> Thanks, Ran~

Thanks, Ran for reply
I've solved the issue. I've tried to pass config to client as array not as object
