### ISSUE TITLE
MIGRATION ISSUE: SDK v2 Credentials uses `expireTime` and not `expiration`

### ISSUE THREAD

**Issue by matan-mitiga** [aws/aws-sdk-js-v3#5878]
### Pre-Migration Checklist

- [X] I've read the [Migration Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/migrating-to-v3.html).
- [X] I've reviewed the upgrading notes and major version differences mentioned in [`UPGRADING.md`](https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md).
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for similar migration issues.

### Which JavaScript Runtime is this issue in?

Node.js (includes AWS Lambda)

### AWS Lambda Usage

- [ ] Yes, my application is running on AWS Lambda.
- [x] No, my application is not running on AWS Lambda.

### Describe the Migration Issue

Our app has mixed v2 and v3 usages. Our internal authentication library uses v2 to create a `Credentials` object. Sometimes we receive `TokenExpired` errors. When I looked through the V3 code in I noticed that it's expecting that the `Credentials` object will have an `expiration` attribute:

`/packages/middleware-signing/src/awsAuthConfiguration.ts`
line 265
```
const normalizeCredentialProvider = (
  credentials: AwsCredentialIdentity | Provider<AwsCredentialIdentity>
): MemoizedProvider<AwsCredentialIdentity> => {
  if (typeof credentials === "function") {
    return memoize(
      credentials,
      (credentials) =>
        credentials.expiration !== undefined &&
        credentials.expiration.getTime() - Date.now() < CREDENTIAL_EXPIRE_WINDOW,
      (credentials) => credentials.expiration !== undefined
    );
  }
  return normalizeProvider(credentials);
};
```

The V2 Credentials object has a different attribute called `expireTime`. Hence, to my understanding, the token refresh fails.

Will appreciate your advice.

Thank you!

### Observed Differences/Errors

V2 `Credentials` uses `expireTime: Date`
V3 `Identity` uses `expiration: Date`

**Comment by matan-mitiga** [comment]
I noticed another issue was opened in the past to rename and had been closed:
https://github.com/aws/aws-sdk-js-v3/issues/1037

**Comment by RanVaknin** [comment]
HI @matan-mitiga ,

>The V2 Credentials object has a different attribute called expireTime. Hence, to my understanding, the token refresh fails.

Without seeing your code I can't know for sure, but this makes sense.

Mixing v2 and v3 implementation is not recommended. In v3 `expireTime` was renamed to `expiration` to mirror the [credential object returned from STS](https://docs.aws.amazon.com/STS/latest/APIReference/API_Credentials.html) and it is standardized across all newer SDKs. 

You can either migrate the credential fetching logic of your application to use v3. Or if you wish to maintain the functionality you'll need to reconstruct the credential object with the new `expiration` field name. 

Regarding https://github.com/aws/aws-sdk-js-v3/issues/1037, this is not relevant as the credential object has been in use for years, and changing the name would mean a backward incompatible change. 

If you have questions about migrating your existing code to v3 let us know and we will do our best to assist you.

Thanks,
Ran~

**Comment by matan-mitiga** [comment]
Thanks for the response @RanVaknin, we eventually decided to reconstruct the credentials file:

```
  async function getCredentialsV3(): Promise<AwsCredentialIdentity> {
    const credentialsV2 = await this.credentialsProvider.getCredentialsV2() // Our internal credentials provided
    return {
      accessKeyId: credentials.accessKeyId,
      secretAccessKey: credentials.secretAccessKey,
      expiration: credentials.expireTime || undefined,
      sessionToken: credentials.sessionToken,
    }
```

Notice that `credentials.expireTime || undefined` is required since `expireTime` is nullable and it will throw an error since it's expected to be undefined.

Would appreciate for feedback if I missed something with this implementation.

Thanks!

**Comment by RanVaknin** [comment]
Hi @matan-mitiga ,

> I would suggest to update UPGRADING.md, as it is not accurate regarding the credentials

I agree. I'll add that to our docs. 

As I mentioned before, mixing v2 and v3 implementation is not the recommended approach. I understand you want feedback about your implementation of reconstructing the credentials object. On a quick look, it looks correct, however since I don't know how you are obtaining credentials (INI file, EKS token, IMDS role, etc ,etc ) Its not clear if the credential object returned will include `expiration` or not, since not all credentials objects are temporary. INI file parsing returns a credential object only containing `accessKeyId` and `secretAccessKey`. 



Thanks,
Ran~
