### ISSUE TITLE
undefined is not an object (evaluating 'endpointFunctions[fn].apply')]

### ISSUE THREAD

**Issue by JeyShah** [aws/aws-sdk-js-v3#5889]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

We are using @aws-sdk/client-location to get SearchPlaceIndexForPositionCommand of lattitude and longitude and also using @aws/amazon-location-utilities-auth-helper to get credentials from aws through withAPIKey function, but while sending command it returns Error occurred: [TypeError: undefined is not an object (evaluating 'endpointFunctions[fn].apply')].

We are using react native. 
code sample as below 

import { LocationClient, SearchPlaceIndexForPositionCommand } from '@aws-sdk/client-location';
import { withAPIKey } from "@aws/amazon-location-utilities-auth-helper";

const authHelper = await withAPIKey(<API_KEY>);
const client = new LocationClient({
            region: "ap-southeast-1",
            ...authHelper.getLocationClientConfig() // sets up the Location client to use the API Key defined above
 });

const command = new SearchPlaceIndexForPositionCommand({
            IndexName: "<INDEX_NAME>", // Place index resource to use
            Position: [-123.1187, 49.2819], // position to search near
            MaxResults: 10 // number of results to return
        })

 try {
            const result = await client.send(command);
        }
        catch (error) {
    }

### SDK version number

"@aws-sdk/client-location": "^3.529.1", "@aws/amazon-location-utilities-auth-helper": "^1.0.4",

### Which JavaScript Runtime is this issue in?

React Native

### Details of the browser/Node.js/ReactNative version

0.64.1

### Reproduction Steps

Just run the code and it throws error

### Observed Behavior

Error occurred: [TypeError: undefined is not an object (evaluating 'endpointFunctions[fn].apply')]

### Expected Behavior

{
  Categories: [ 'PointOfInterestType' ],
  Country: 'MYS',
  Geometry: { Point: [ 101.71371, 3.15908 ] },
  Interpolated: false,
  Label: 'SEPHORA, Jalan Ampang, KLCC, Bandar Kuala Lumpur, Kuala Lumpur, 50450, Wilayah Persekutuan Kuala Lumpur, MYS',
  Municipality: 'Bandar Kuala Lumpur',
  PostalCode: '50450',
  Region: 'Wilayah Persekutuan Kuala Lumpur',
  SubMunicipality: 'KLCC',
  SubRegion: 'Kuala Lumpur',
  SupplementalCategories: [ 'Specialty Store' ]
}

**Comment by kuhe** [comment]
Try adding a line at the start of your application to import "@aws-sdk/util-endpoints"

```js
import "@aws-sdk/util-endpoints";
// or
require("@aws-sdk/util-endpoints");
```

**Comment by JeyShah** [comment]
> Try adding a line at the start of your application to import "@aws-sdk/util-endpoints"
> 
> ```js
> import "@aws-sdk/util-endpoints";
> // or
> require("@aws-sdk/util-endpoints");
> ```

After this Error changed to [Error: not implemented] on client.send line

**Comment by kuhe** [comment]
What is the actual stack trace?
