### ISSUE TITLE
PutObjectCommand Input is not properly populated in the DOC

### ISSUE THREAD

**Issue by MavGitt** [aws/aws-sdk-js-v3#5891]
### Describe the issue

In the documentation for **PutObjectCommand** 
for the input, the current documentation does not correctly list down all the input required for the API. There are other properties also whose descriptions need to be there inside the input's section.
![image](https://github.com/aws/aws-sdk-js-v3/assets/65035132/df6f5639-dc71-4603-9861-b82622904ee0)

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/command/PutObjectCommand/

**Comment by kuhe** [comment]
Our open source tools for extracting API data from TypeScript source code have limitations inspecting extended types.

In this case, it says
> See [PutObjectCommandInput](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-s3/Interface/PutObjectCommandInput) for more details

On that page, the full signature of the base type will then link to https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-s3/Interface/PutObjectRequest/ containing the rest of the fields.
