### ISSUE TITLE
"Unexpected token export" then add and use aws-sdk/client-s3

### ISSUE THREAD

**Issue by AlekseiHead** [aws/aws-sdk-js-v3#5896]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I'm working on an open source project in OHIF (React, Node.js). After installing the aws-sdk/client-s3 package and initializing it in the project, I receive the following error message in the browser:
"Unexpected token 'export' in "export * from "./EventStreamCodec""

*/***/ "../../../node_modules/@smithy/eventstream-codec/dist-es/index.js":
/*!************************************************************************!*\
  !*** ../../../node_modules/@smithy/eventstream-codec/dist-es/index.js ***!
  \************************************************************************/
/***/ (function(module, exports) {

export * from "./EventStreamCodec";
export * from "./HeaderMarshaller";
export * from "./Int64";
export * from "./Message";
export * from "./MessageDecoderStream";
export * from "./MessageEncoderStream";
export * from "./SmithyMessageDecoderStream";
export * from "./SmithyMessageEncoderStream";*

I tried *type module* and various other solutions, such as * yarn add --dev @babel/plugin-transform-export-namespace-from*, but nothing helps!
How to fix this error?

### SDK version number

"@aws-sdk/client-s3": "^3.533.0"

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node: v20.11.1, chrome 122.0.6261.129

### Reproduction Steps

Using:
import { S3Client, PutObjectCommand } from '@aws-sdk/client-s3';
const s3Client = new S3Client({ params...});
....
try {
const results = await s3Client.send(new PutObjectCommand(params));
} catch (err) {...}
_________________________________

### Observed Behavior

And after run *yarn run dev* i get error in browser:
![123](https://github.com/aws/aws-sdk-js-v3/assets/100319373/efb57432-bc41-46ba-8fcd-b754c2229ed2)

Uncaught SyntaxError: Unexpected token 'export' (at app.js:207575:1)
![123](https://github.com/aws/aws-sdk-js-v3/assets/100319373/45d72da4-811c-48a0-a59f-a94ebef48d56)
![1234](https://github.com/aws/aws-sdk-js-v3/assets/100319373/09f8e226-3c44-46eb-b621-6ae8e579ea4e)

### Expected Behavior

In my old version of OHIF everything ran fine when I installed the package. But in the new version it doesn’t work!

### Possible Solution

I tried *type module* and various other solutions, such as * yarn add --dev @babel/plugin-transform-export-namespace-from*, but nothing helps!

### Additional Information/Context

If you comment out the aws-sdk/client-s3 call, the rest of the application works without problems. But as soon as I divide the call, I immediately get an error in the browser.

**Comment by RanVaknin** [comment]
hi @AlekseiHead ,

The error you are seeing is related to ES6 code that is not supported on a browser you are running. Since you mentioned React, are you using Webpack to bundle your application?

>I tried type module and various other solutions, such as * yarn add --dev @babel/plugin-transform-export-namespace-from*, but nothing helps!

type module would just instruct node to treat this file as a module file but it doesn't mean that the browser that is running this code supports ES6. When you are using react, you typically use it in conjuction with Webpack in order to bundle your application for use in browsers. If you have used `npx create-react-app` (or CRA), then react would come preconfigured with Webpack. 

If you do have a Webpack config file, can you please share it with us?

Thanks,
Ran~

**Comment by AlekseiHead** [comment]
HI @RanVaknin ! I'm glad you responded to my message!

Yes, I'm using Webpack to bundle the application. My application is an [OHIF](https://docs.ohif.org/development/getting-started) fork from the official repository.

I have webpack.config.babel.js here he is:

import fs from 'fs';
import webpack from 'webpack';

let nodeModules = fs.readdirSync('./node_modules')
    .filter((module) => {
        return module !== '.bin';
    })
    .reduce((prev, module) => {
        return Object.assign(prev, {[module]: 'commonjs ' + module});
    }, {});

export default {
    entry: ['./index.js'],
    output: {
        path: './dist',
        filename: 'index.js',
        library: 'electron-machine-id',
        libraryTarget: 'umd'
    },
    target: 'electron',
    module: {
        loaders: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                loader: 'babel',
                query: {
                    cacheDirectory: true
                }
            },
            {
                test: /\.json$/,
                loader: 'json'
            }
        ]
    },
    plugins: [
        new webpack.IgnorePlugin(/node_modules/),
        new webpack.optimize.OccurrenceOrderPlugin(),
        new webpack.optimize.DedupePlugin(),
        new webpack.optimize.UglifyJsPlugin({
            compress: { warnings: false },
            output: { comments: false },
        })
    ],
    node: {
        //do not include polyfills...
        //http://webpack.github.io/docs/configuration.html#node
        console: false,
        process: false,
        child_process: false,
        global: false,
        buffer: false,
        crypto: false,
        __filename: false,
        __dirname: false
    },
    externals: nodeModules
};

**Comment by RanVaknin** [comment]
Hi @AlekseiHead,

I'm not able to see something obvious in your setup that is wrong. The next step would be for you to provide a minimal github repository that I can clone and see if I can debug on my own. 
Ideally the github repository should have the bare minimal amount of code needed to raise this behavior, so that it would be easier for us to investigate and isolate the problem.

Thanks,
Ran~

**Comment by AlekseiHead** [comment]
Hi @RanVaknin,
Thanks for your reply. Sorry for the long reply. It will take me a bit more time to prepare a minimal github repository that will contain a minimal amount of code. This is because I will need to lighten up most of my component (where the error occurs) and the OHIF application too. I will try to do it as soon as possible.
