### ISSUE TITLE
Sagemaker Endpoint Client Runtime returns Incomplete JSON response for Sagemaker Endpoint

### ISSUE THREAD

**Issue by spring1915** [aws/aws-sdk-js-v3#5914]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I ran a NodeJS app that called a Sagemaker Streaming Endpoint deployed with Huggingface TGI. I used `SageMakerEndpoint` (version 3.535.0) with this 
```
import {
SageMakerEndpoint,
SageMakerLLMContentHandler,
} from "@langchain/community/llms/sagemaker_endpoint";
```
I used the same input and parameters as the ones for python langchain and it worked perfectly. But invalidly formatted decoded json was returned (see line 8 below) from the endpoint 

```
1. `{"index": 23, "token": {"id": 851, "text": " This", "logprob": 0.0, "special": false}, "generated_text": null, "details": null}`
2. `{"index": 24, "token": {"id": 7607, "text": " library", "logprob": 0.0, "special": false}, "generated_text": null, "details": null}`
3. `{"index": 25, "token": {"id": 349, "text": " is", "logprob": 0.0, "special": false}, "generated_text": null, "details": null}`
4. `{"index": 26, "token": {"id": 7083, "text": " mentioned", "logprob": 0.0, "special": false}, "generated_text": null, "details": null}`
5. `{"index": 27, "token": {"id": 297, "text": " in", "logprob": -0.12695312, "special": false}, "generated_text": null, "details": null}`
6. `{"index": 28, "token": {"id": 1560, "text": " both", "logprob": 0.0, "special": false}, "generated_text": null, "details": null}`
7. `{"index": 29, "token": {"id": 2389, "text": " job", "logprob": 0.0, "special": false}, "generated_text": null, "details": null}`
8. `{"index": 30, "token": {"id": 25308, "text": " descriptions", "logprob": 0.0, "special": false}, "generated_text": nul`
```
when I switched to langchain JS SagemakerEndpoint, which uses `aws-sdk-client-runtime ``InvokeEndpointWithResponseStreamCommand` under the hood. LangchainJS uses `@aws-sdk/client-sagemaker-runtime `"^4.414.0" but that should not the problem because in my package.json, I specified the package with "3.535.0".

### SDK version number

@aws-sdk/client-sagemaker-runtime 3.535.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node JS 21.0.0

### Reproduction Steps

Deploy a model with TGI on Sagemaker.
Call the endpoint with parameters for streaming using Langchain JS's Sagemakerendpoint.

### Observed Behavior

Cut-off json from model.

### Expected Behavior

Validly formatted json streaming output.

**Comment by RanVaknin** [comment]
Hi @spring1915 ,

Thanks for reaching out.

>but that should not the problem because in my package.json, I specified the package with "3.535.0".

The fact that you imported a newer version of the SDK will not cause the 3rd party library that you are using to use the newer SDK version. 

When `@langchain/community/llms/sagemaker_endpoint` executes, it uses the version of `@aws-sdk/client-sagemaker-runtime` that it has in its own `node_modules` directory, not the version installed in the project's root `node_modules` directory.

The solution here is to get `@langchain/community/llms/sagemaker_endpoint` to update their own dependency. You can [open an issue](https://github.com/langchain-ai/langchainjs/issues/new/choose) on their github repo.

Since this is not something the SDK team can change, I'm going to close this.

Thanks again,
Ran~
