### ISSUE TITLE
Clock skew correction is not working on AppSyncData

### ISSUE THREAD

**Issue by simonmeyerrr** [aws/aws-sdk-js-v3#5920]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When using `AppConfigData.startConfigurationSession` with invalid time (on purpose) in the past or future, it throw this errors without retrying with clock skew correction as it should do:
- `Signature not yet current: 20240319T145952Z is still later than 20240319T130506Z (20240319T130006Z + 5 min.)`
- `Signature expired: 20240319T110034Z is now earlier than 20240319T125554Z (20240319T130054Z - 5 min.)`

The response from AWS contains this headers which should make the clock skew correction possible:
```
Date: Tue, 19 Mar 2024 13:01:21 GMT
X-Amzn-Errortype: InvalidSignatureException:http://internal.amazon.com/coral/com.amazon.coral.service/
```

### SDK version number

@aws-sdk/client-appconfigdata@3.535.0

### Which JavaScript Runtime is this issue in?

Browser

### Details of the browser/Node.js/ReactNative version

Google Chrome 122.0.6261.129

### Reproduction Steps

Change manually your computer time in the past or future (more than 5 minutes) and run this in the browser

```javascript
import { AppConfigData } from '@aws-sdk/client-appconfigdata';

const client = new AppConfigData({
  region: process.env.REACT_APP_AWS_REGION,
  credentials: {
    accessKeyId: process.env.REACT_APP_AWS_ACCESS_KEY_ID!,
    secretAccessKey: process.env.REACT_APP_AWS_SECRET_ACCESS_KEY!,
    sessionToken: process.env.REACT_APP_AWS_SESSION_TOKEN,
  },
});

console.log('before', client.config.systemClockOffset);
// -> 0

client.startConfigurationSession({
  ApplicationIdentifier: process.env.REACT_APP_APP_CONFIG_APP,
  ConfigurationProfileIdentifier: process.env.REACT_APP_APP_CONFIG_CONFIG_PROFILE,
  EnvironmentIdentifier: process.env.REACT_APP_APP_CONFIG_ENVIRONMENT,
})
  .then((res) => {
    console.log('success', res);
  })
  .catch((err) => {
    console.error('fail', err);
    // -> 403: Signature expired: 20240319T110603Z is now earlier than 20240319T130122Z (20240319T130622Z - 5 min.)
    // + stack trace
    
    console.log('after', client.config.systemClockOffset);
    // -> still 0
  });
```

### Observed Behavior

`console.log(err)` depending on if the time is in the future or the past:
- `403: Signature not yet current: 20240319T145952Z is still later than 20240319T130506Z (20240319T130006Z + 5 min.)`
- `403: Signature expired: 20240319T110034Z is now earlier than 20240319T125554Z (20240319T130054Z - 5 min.)`

`console.log(err.$metadata)`:
```
{
  attempts: 1,
  cfId: undefined,
  extendedRequestId: undefined,
  httpStatusCode: 403,
  requestId: undefined,
  totalRetryDelay: 0
}
```

Response headers:
```
Date: Tue, 19 Mar 2024 13:00:06 GMT
X-Amzn-Errortype: InvalidSignatureException:http://internal.amazon.com/coral/com.amazon.coral.service/
```

### Expected Behavior

`client.config.systemClockOffset` should be updated based on server time in the response and the request should be retried.

### Additional Information/Context

A fix has recently be merged about clock skew, but it doesn't seem to fix my issue: https://github.com/aws/aws-sdk-js-v3/pull/5835

**Comment by RanVaknin** [comment]
Hi @simonmeyerrr ,

Thanks for letting us know. I can confirm that the error is not being retried.  

We will look into this.
Ran~

**Comment by RanVaknin** [comment]
Hi,

I reproduced this again with appconfig data client:

```js

import { AppConfigDataClient, StartConfigurationSessionCommand } from "@aws-sdk/client-appconfigdata"; 

    const client = new AppConfigDataClient({ region: "us-east-1", systemClockOffset: -30 * 60 * 1000});

    try {
      const response = await client.send(new StartConfigurationSessionCommand({
        ApplicationIdentifier:"REDACTED",
        ConfigurationProfileIdentifier:"REDACTED",
        EnvironmentIdentifier:"REDACTED"
      }))
      console.log(response)
    } catch (error) {
      console.log(error)
    }
```

We can see that the request actually gets retried and then successful:

```
{
  '$metadata': {
    httpStatusCode: 201,
    requestId: '15449feb-REDACTED',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 2,  <---- being retried
    totalRetryDelay: 94
  },
  InitialConfigurationToken: 'REDACTED'
}
```

Can you run your code from node and not from the browser? Im trying to see if we can narrow down the issue.

Thanks,
Ran~
