### ISSUE TITLE
Missing Headers parameter

### ISSUE THREAD

**Issue by maxgurewitz** [aws/aws-sdk-js-v3#5924]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The send email API now supports adding headers.

https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_SendEmail.html

However the client currently does not.

https://github.com/aws/aws-sdk-js-v3/blob/0559eadb7da1fb3e098b20b743f11e4a4411e493/clients/client-ses/src/commands/SendEmailCommand.ts

This addition was made as of 3/08/24

https://aws.amazon.com/about-aws/whats-new/2024/03/amazon-ses-headers-sending-email/

### SDK version number

@aws-sdk/client-ses@3.535.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.11.0

### Reproduction Steps

Read the API documentation, and the client code, see that the feature is available from the API and not the client.

### Observed Behavior

The Headers parameter is not available.

### Expected Behavior

The Headers parameter should be available.

**Comment by RanVaknin** [comment]
Hi @maxgurewitz ,

SES has two APIs, SES, and SESv2, therefore there would be 2 SDK clients, one for each.

You need to use @aws-sdk/client-sesv2
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/sesv2/command/SendEmailCommand/

Thanks,
Ran~

**Comment by maxgurewitz** [comment]
@RanVaknin great thanks!
