### ISSUE TITLE
aws-sdk/client-fsx 

### ISSUE THREAD

**Issue by ilia373** [aws/aws-sdk-js-v3#5936]
### Describe the bug

according to aws documentation, in order to disable filesystem automatic backup need to set 
OntapConfiguration.AutomaticBackupRetentionDays = 0, however when set the value to 0, filesystem being configured with 30 days 

### Expected Behavior

AutomaticBackupRetentionDays to be 0 and automatic backup disabled 

### Current Behavior

AutomaticBackupRetentionDays returned with value 30 although set to 0

### Reproduction Steps

1. define filesystem creation command with AutomaticBackupRetentionDays = 0: 

`const input: CreateFileSystemCommandInput = {
      FileSystemType: 'ONTAP',
      OntapConfiguration: {
        AutomaticBackupRetentionDays:0,
      },
}`

2. create command 
const command = new CreateFileSystemCommand(input)

3. send command 
clinet.send(command)

4. describe filesystem
5. AutomaticBackupRetentionDays is 30 instead of 0

### SDK version used

"@aws-sdk/client-fsx": "^3.525.0"

### Environment details (OS name and version, etc.)

macos Sonoma 14.4 (23E214)

**Comment by RanVaknin** [comment]
Hi @ilia373 ,

Thanks for reaching out. I think I might have an idea what the issue may be, but before that, are you able to add this middleware hook to your code:

```js
// some more code
const client = new FSXClient({region: "some-region"});

client.middlewareStack.add(next => async (args) => {
 console.log(args.request)
 const response = await next(args);
 console.log(response);
 return next(args);
}, {step: 'finalizeRequest'})

const input: CreateFileSystemCommandInput = { FileSystemType: 'ONTAP', OntapConfiguration: { AutomaticBackupRetentionDays:0, }, }
// more code
```

This would log the raw request and response and tell us if this is a serialization issue with the SDK, or a service related modeling issue, or a bug in the service itself.

Thanks,
Ran~

**Comment by ilia373** [comment]
hi @RanVaknin , 
here is the middleware output:

`HttpRequest {
  method: 'POST',
  hostname: 'fsx.us-east-1.amazonaws.com',
  port: undefined,
  query: {},
  headers: {
    'content-type': 'application/x-amz-json-1.1',
    'x-amz-target': 'AWSSimbaAPIService_v20180301.CreateFileSystem',
    'content-length': '488',
    host: 'fsx.us-east-1.amazonaws.com',
    'x-amz-user-agent': 'aws-sdk-js/3.540.0',
    'user-agent': 'aws-sdk-js/3.540.0 ua/2.0 os/darwin#23.4.0 lang/js md/nodejs#21.2.0 api/fsx#3.540.0',
    'amz-sdk-invocation-id': 'e612fd11-2d3a-4e12-93db-329c3caeba4e',
    'amz-sdk-request': 'attempt=1; max=3',
    'x-amz-date': '20240331T063028Z',
    'x-amz-content-sha256': '513afc98b0c376e7c316fef1faa69a1ec72e73e9deaf89f65a967c28d8cce1e9',
    authorization: 'auth'
  },
  **body: '{"ClientRequestToken":"aaadf83f-1e45-4a67-ae5b-6304cb280540","FileSystemType":"ONTAP","OntapConfiguration":{"DeploymentType":"SINGLE_AZ_1","PreferredSubnetId":"subnet-c1d99699","FsxAdminPassword":"Netapp234","DiskIopsConfiguration":{"Mode":"AUTOMATIC"},"RouteTableIds":[],"AutomaticBackupRetentionDays":0,"ThroughputCapacity":128},"SecurityGroupIds":["sg-0c50915a4ae396910"],"StorageCapacity":1024,"SubnetIds":["subnet-c1d99699"],"Tags":[{"Key":"Name","Value":"fsx_autobackup_disabled"}]}',**
  protocol: 'https:',
  path: '/',
  username: undefined,
  password: undefined,
  fragment: undefined
}
{
  response: HttpResponse {
    statusCode: 200,
    reason: 'OK',
    headers: {
      date: 'Sun, 31 Mar 2024 06:30:30 GMT',
      'content-type': 'application/x-amz-json-1.1',
      'content-length': '939',
      connection: 'keep-alive',
      'x-amzn-requestid': 'dfbfd79a-e8e4-4f5f-80b2-23c7569f02be'
    },
    body: IncomingMessage {
      _events: [Object],
      _readableState: [ReadableState],
      _maxListeners: undefined,
      socket: null,
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 200,
      statusMessage: 'OK',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [ClientRequest],
      _eventsCount: 2,
      [Symbol(shapeMode)]: true,
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 10,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    }
  },
  output: {
    '$metadata': {
      httpStatusCode: 200,
      requestId: 'dfbfd79a-e8e4-4f5f-80b2-23c7569f02be',
      extendedRequestId: undefined,
      cfId: undefined
    },
    FileSystem: {
      CreationTime: 2024-03-31T06:30:30.393Z,
      FileSystemId: '**fs-0486c4c25aae95022**',
      FileSystemType: 'ONTAP',
      KmsKeyId: 'arn',
      Lifecycle: 'CREATING',
      OntapConfiguration: [Object],
      OwnerId: '733004784675',
      ResourceARN: 'arn:aws:fsx:us-east-1:733004784675:file-system/fs-0486c4c25aae95022',
      StorageCapacity: 1024,
      StorageType: 'SSD',
      SubnetIds: [Array],
      Tags: [Array],
      VpcId: 'vpc-b16c90d4'
    }
  }
}
`

**Comment by ilia373** [comment]
Hi again @RanVaknin ,
seems like the issue was resolved, not sure by which side backend or client lib,  i see that when sending AutomaticBackupRetentionDays:0 upon creation, the AutomaticBackup is disabled, which means it works as expected 

thanks!

**Comment by RanVaknin** [comment]
HI @ilia373 ,

I'm not aware of any client side changes that were made, and if you did not update your SDK it is likely related to a change in the backend. 

Happy to hear it has worked itself out.
Thanks again,
Ran~
