### ISSUE TITLE
SQS has become much slower

### ISSUE THREAD

**Issue by zryenz5w** [aws/aws-sdk-js-v3#5938]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The SQS service has become slower in the recent releases. Maybe since [v3.507.0](https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.507.0) because of the middleware-sdk-sqs update.

This is a breaking change for us, we ran in multiple Lambda timeouts because of this.

The middleware-sdk-sqs update also causes a new warning because we use the `queueName` instead of the `queueUrl`:

```
2024-03-20T12:36:21.945Z	868dee7b-147c-415b-9a7d-1bc86d2f9b04	WARN	TypeError [ERR_INVALID_URL]: Invalid URL
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at new NodeError (node:internal/errors:405:5)
    at new URL (node:internal/url:676:13)
    at /var/runtime/node_modules/@aws-sdk/middleware-sdk-sqs/dist-cjs/index.js:56:28
    at /var/runtime/node_modules/@aws-sdk/node_modules/@smithy/middleware-endpoint/dist-cjs/index.js:199:12
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/runtime/node_modules/@aws-sdk/middleware-sdk-sqs/dist-cjs/index.js:127:16
    at async /var/runtime/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22
    ...
}
```

When switching from `queueName` to `queueUrl` the warning disappears and it is still working like before; but the performance issue remains.

### SDK version number

@aws-sdk/client-sqs@^3.507.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node 18

### Reproduction Steps

We have a class function that logs before and after the `send` command:

```typescript
import { SendMessageCommand, SendMessageCommandInput, SQSClient } from '@aws-sdk/client-sqs';
// ...
private readonly _sqsClient = new SQSClient({});
// ...
async sendEmail(emailSendRequest: EmailSendRequest): Promise<void> {
    logger.info(`Received email send request ${emailSendRequest.subject}`);
    const input: SendMessageCommandInput = {
      QueueUrl: this._sendEmailQueueUrl,
      MessageBody: JSON.stringify(emailSendRequest),
    };

    const output = await this._sqsClient.send(new SendMessageCommand(input));

    logger.info(
      `Published email send request ${emailSendRequest.subject} to topic (message id is ${output.MessageId}).`
    );
  }
```

### Observed Behavior

**220 ms** for the send command:
![image](https://github.com/aws/aws-sdk-js-v3/assets/164998208/6d244e63-bae7-4dbe-939f-46233ca79504)

**559 ms** for the send command:
![image](https://github.com/aws/aws-sdk-js-v3/assets/164998208/53eb4580-14c7-42a5-8dfa-9453e5949046)

Note: the log between these info logs is the TypeError warning described above

### Expected Behavior

Setting the sdk version back to [v3.504.0](https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.504.0) and it seems to work as expected.

**11 ms** for the send command:
![image](https://github.com/aws/aws-sdk-js-v3/assets/164998208/9d1518b8-d924-42e6-84bc-8acc4accd3d7)

![image](https://github.com/aws/aws-sdk-js-v3/assets/164998208/10478ae5-fe2c-4bc6-837b-6294cf8a352c)

**Comment by kuhe** [comment]
Try setting `useQueueUrlAsEndpoint`=`false` on the client. It will be possible to use just the queue name in the `QueueUrl` field, but I recommend using the full URL.

```js
new SQSClient({
  useQueueUrlAsEndpoint: false,
});
```

**Comment by zryenz5w** [comment]
Thanks, setting `useQueueUrlAsEndpoint: false` seems to help if we continue using `queueName`. I also tested `queueUrl` again without this setting and it seems to end up with similar times.

Only the case `queueName` without `useQueueUrlAsEndpoint: false` leads to the TypeError and slows the request down. Maybe considering setting `useQueueUrlAsEndpoint` to `true` by default (for now) to avoid the breaking change for other users that still uses the `queueName`.
