### ISSUE TITLE
Introduce s3-request-presigner once client-s3 is available

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#594]
**Is your feature request related to a problem? Please describe.**
While we release limited clients based on smithy, the package `s3-request-presigner` might need to be removed as it depends on `client-s3-node@0.1.0-preview`
https://github.com/aws/aws-sdk-js-v3/blob/fdca49c86596ec282e3dffa2a8a6646bd11b2c4a/packages/s3-request-presigner/package.json#L24

**Describe the solution you'd like**
Reintroduce `s3-request-presigner` once `client-s3@0.1.0-beta.1` is available

**Comment by trivikr** [comment]
Closing as changes were reverted using force-push 
Details https://github.com/aws/aws-sdk-js-v3/issues/584#issuecomment-570368315

**Comment by trivikr** [comment]
Re-opening, as we removed s3-request-presigner in `smithy-codegen` in https://github.com/aws/aws-sdk-js-v3/pull/653

**Comment by AllanFly120** [comment]
The package is added back in https://github.com/aws/aws-sdk-js-v3/pull/660
