### ISSUE TITLE
PutKeyCommandOutput not found with Cloudfront KVS

### ISSUE THREAD

**Issue by trobert2** [aws/aws-sdk-js-v3#5940]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When trying to import `*CommandOutput` interfaces to use as return types from `@aws-sdk/client-cloudfront-keyvaluestore` a linting error occurs. Example:
> PutKeyCommandOutput not found in '@aws-sdk/client-cloudfront-keyvaluestore'eslint[import/named](https://github.com/import-js/eslint-plugin-import/blob/v2.29.1/docs/rules/named.md)

This rule:
> Verifies that all named imports are part of the set of named exports in the referenced module.

So given this function implementation:
```
export const setKVValue = async (
  kvsArn: string,
  key: string,
  value: string,
  etag: string,
): Promise<PutKeyCommandOutput> => {
  return await getKVClient().send(
    new PutKeyCommand({ Key: key, KvsARN: kvsArn, Value: value, IfMatch: etag }),
  );
};
```

I cannot import `PutKeyCommandOutput` to declare the type of the returned value.

Library version: `"@aws-sdk/client-cloudfront-keyvaluestore": "3.540.0",`

### SDK version number

@aws-sdk/client-cloudfront-keyvaluestore@3.540.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v21

### Reproduction Steps

```
import {
  PutKeyCommandOutput,
} from '@aws-sdk/client-cloudfront-keyvaluestore';
```

### Observed Behavior

PutKeyCommandOutput not found in '@aws-sdk/client-cloudfront-keyvaluestore'eslint[import/named](https://github.com/import-js/eslint-plugin-import/blob/v2.29.1/docs/rules/named.md)

### Expected Behavior

The interfaces should be exported (use named exports)

### Possible Solution

Improve named exports

**Comment by kuhe** [comment]
Does this work?

use `import type` instead of `import`
```ts
import type {
  PutKeyCommandOutput,
} from '@aws-sdk/client-cloudfront-keyvaluestore';
```

**Comment by aBurmeseDev** [comment]
Hi @trobert2 - sorry to hear you're running into this error.

I have just tried to reproduce it but was unable to. Can you please try `import type` as suggested and share a minimal reproducible code if you have it?

Here's our API reference doc on [`PutKeyCommand`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/cloudfront-keyvaluestore/command/PutKeyCommand/) and as you can see client exports `PutKeyCommandOutput` as Type. 

Best,
John
