### ISSUE TITLE
config is not defined

### ISSUE THREAD

**Issue by davidskingsley** [aws/aws-sdk-js-v3#5944]
### Describe the issue

Because the variable config on line 3 (const client = new CognitoIdentityProviderClient(config);) has no associated reference it is difficult to fully grasp the example.  I appreciate it is most likely defined elsewhere but a link to the full code needs to be included with the example.  AWS documentation is littered with examples that do not provide enough detail to be overly useful!

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/cognito-identity-provider/command/GetUserCommand/

**Comment by aBurmeseDev** [comment]
HI @davidskingsley - thanks for reaching out and sharing the feedback.

As every feedback is essential to our improvement process, I'll take note of your feedback to be considered in future updates. 

I would like to share [this doc](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/global-config-object.html) around configuring the service that you might find it helpful. 

There's also [this page](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/javascript_code_examples_categorized.html) with code examples for different services but I understand that they might not be very specific. 

If you have further questions around implementation, please let us know.

Best,
John
