### ISSUE TITLE
@aws-sdk/types version

### ISSUE THREAD

**Issue by patrick-geyer-21** [aws/aws-sdk-js-v3#5955]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Shouldn't there also be version  3.540.0 available like there is for 
client-sns": "^3.540.0",
    "@aws-sdk/client-sqs": "^3.540.0",
    "@aws-sdk/client-ssm": "^3.540.0",
    "@aws-sdk/client-sts": "^3.540.0",
    "@aws-sdk/cloudfront-signer": "^3.540.0",
    "@aws-sdk/lib-dynamodb": "^3.540.0",
...

### SDK version number

@aws-sdk/types@3.535.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.13.0

### Reproduction Steps

--

### Observed Behavior

--

### Expected Behavior

--

**Comment by kuhe** [comment]
check the tag corresponding to the desired version of the codebase, and then check the package in question. It will have a version less than or equal to the target version. We don't publish incremental versions when no changes are contained.

You can also check the matching version by running `npm view @aws-sdk/types@"<=3.540.0" version`
