### ISSUE TITLE
can't upload file to s3 in react-native

### ISSUE THREAD

**Issue by lukerlv** [aws/aws-sdk-js-v3#5978]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Previously, it was possible to upload, but now it is no longer possible. The upload interface returned {"data": ""}, and the error message from react-native is as follows:
```
// node_modules\whatwg-fetch\dist\fetch.umd.js
xhr.onerror = function(e) {
  setTimeout(function() {
    reject(new TypeError('Network request failed'));
  }, 0);
};
```

### SDK version number

@aws-sdk/client-s3@3.550.0, @aws-sdk/lib-storage@3.550.0

### Which JavaScript Runtime is this issue in?

React Native

### Details of the browser/Node.js/ReactNative version

0.72.7

### Reproduction Steps

Previously, it was possible to upload, but now it is no longer possible. The upload interface returned {"data": ""}, and the error message from react-native is as follows:
```
// node_modules\whatwg-fetch\dist\fetch.umd.js
xhr.onerror = function(e) {
  setTimeout(function() {
    reject(new TypeError('Network request failed'));
  }, 0);
};
```
my upload code is as follows: 
```
import 'react-native-get-random-values';
import 'react-native-url-polyfill/auto';
import {S3Client, PutObjectCommand} from '@aws-sdk/client-s3';
import {Upload} from '@aws-sdk/lib-storage';

const upload = async (videoRes: IImage) => {
    const res: any = await tokenInfoApi({});
    const {accessKeyId, accessKeySecret, expireTime, token, bucketName} = res.model;

    const createParams = {
      Bucket: bucketName,
      Key: filePath.current,
    };

    const credentials = {
      accessKeyId: accessKeyId,
      secretAccessKey: accessKeySecret,
      sessionToken: token,
    };

    const client = new S3Client({
      region: regionCode,
      credentials: credentials,
    });

    const _source = Platform.OS === 'android' ? videoRes.path : 'file://' + videoRes.path;
    const response = await fetch(_source);
    const blob = await response.blob();

    const parallelUploads3 = new Upload({
        client: client,
        params: {
          Bucket: createParams.Bucket,
          Key: createParams.Key,
          Body: blob,
        },
        tags: [
          /*...*/
        ], // optional tags
        queueSize: 4, // optional concurrency configuration
        partSize: 1024 * 1024 * 10,// optional size of each part, in bytes, at least 5MB
        leavePartsOnError: true, // optional manually handle dropped parts
      });

      parallelUploads3.on('httpUploadProgress', (progress: any) => {

      });

      await parallelUploads3.done();

      uploadSuccess && uploadSuccess(filePath.current, coverUrl)
  };
  ```

### Observed Behavior

Previously, it was possible to upload, but now it is no longer possible. The upload interface returned {"data": ""}, and the error message from react-native is as follows:
```
// node_modules\whatwg-fetch\dist\fetch.umd.js
xhr.onerror = function(e) {
  setTimeout(function() {
    reject(new TypeError('Network request failed'));
  }, 0);
};
```

### Expected Behavior

upload success

**Comment by RanVaknin** [comment]
Hi @lukerlv ,

Thanks for reaching out.
Can you please provide the stack trace of the full error?

Additionally you mentioned 
>Previously, it was possible to upload, but now it is no longer possible.

Did you update the SDK to a version that stopped working? You didn't mention if this was after updating your SDK, what was the previous state, and the current one. 

Thanks,
Ran~

**Comment by lukerlv** [comment]
Hi @RanVaknin ,

Thanks for your help.

My previous version is 3.490.0，but it also has this problem: (Previously, it was possible to upload, but now it is no longer possible.)
Sorry, I don't know how to provide the full error, but the error occured is as follows:
![image](https://github.com/aws/aws-sdk-js-v3/assets/73922910/65ba2bbd-803a-46c3-b39f-cc80cdfd0a89)
My upload request is as follows:
![image](https://github.com/aws/aws-sdk-js-v3/assets/73922910/7b92bf80-d6c0-4481-873c-f7585f7ae150)
![image](https://github.com/aws/aws-sdk-js-v3/assets/73922910/6a60a46f-ad92-440c-bf8e-6b0aa1bd9046)

Thanks,
luker~

**Comment by lukerlv** [comment]
Hi @RanVaknin,
I have discovered the reason for this issue, which is due to the issue with my office's WiFi. I cannot upload using WiFi, but I can upload using my phone's mobile network. I'm sorry for causing you trouble, but I can't figure out why my office's WiFi cannot upload files to S3. Is there anywhere to configure it?

Thanks for your help.
luker~

**Comment by RanVaknin** [comment]
Hi @lukerlv ,

Happy to hear that you were able to diagnose the issue. There are no SDK configurations for network. Establishing a network connection is a lower level networking event that happens on the OS level. My only thought is if you have a firewall setup you might want to check its configuration to see if you can allow more traffic out. 

Thanks,
Ran~

**Comment by lukerlv** [comment]
Hi @RanVaknin ,

The network issue may require my colleagues to assist in handling it. If the reason is found, I will update here. Thank you for your help!

Thanks,
luker~
