### ISSUE TITLE
Slow video loading on accelerated s3

### ISSUE THREAD

**Issue by Rossella-Mascia-Neosyn** [aws/aws-sdk-js-v3#5989]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The slow part is when I make the first CreateMultipartUpload request and send the first chunk
![Screenshot 2024-04-10 at 12 59 26](https://github.com/aws/aws-sdk-js-v3/assets/79088170/dfb76cf4-824b-4379-b5ab-90070b1c5fb1)

### SDK version number

@aws-sdk/client-s3@^3.549.0

### Which JavaScript Runtime is this issue in?

React Native

### Details of the browser/Node.js/ReactNative version

^0.73.5

### Reproduction Steps

1. create file mp4
2. save file on device
3. upload video in multipart

### Observed Behavior

I have no mistake from aws

### Expected Behavior

what I expect is that the time from the CreateMultipartUpload to the first chunk is faster

**Comment by aBurmeseDev** [comment]
Hi @Rossella-Mascia-Neosyn - thanks for reaching out. 

While I look more into it, will you be able to share your code snippet for me to reproduce? If you can also elaborate more on the performance that you're expecting and whether this happens intermittently or repeatedly, that would give us more insight. I would also check if you're running any VPN or anything that would slow down your connection.

Best,
John
