### ISSUE TITLE
Typo in tag name

### ISSUE THREAD

**Issue by tenbradley** [aws/aws-sdk-js-v3#6004]
### Describe the issue

In the given example, the tags are listed as
`
"Tags": [
    {
      "Key": "Acount",
      "Value": "143327655"
    }
  ]
`
"Acount" should be "Account"

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/database-migration-service/command/CreateReplicationTaskCommand/

**Comment by RanVaknin** [comment]
Hi @tenbradley ,

The code examples for our docs are defined upstream with the service team itself. This is not something that the SDK team can change.

Also, you can name your key anything, so while `Acount` is not a word, you can define any tag name you want.

Thanks for taking the time and submitting this.
Ran~
