### ISSUE TITLE
TypeError: fromEnv is not a function

### ISSUE THREAD

**Issue by vs223** [aws/aws-sdk-js-v3#6006]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

```log
code: undefined, TypeError: fromEnv is not a function TypeError: fromEnv is not a function
        at _a (****/node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/credential-provider-node/dist-cjs/index.js:71:16)
        at ****/node_modules/@smithy/property-provider/dist-cjs/index.js:79:27
        at coalesceProvider (****/node_modules/@smithy/property-provider/dist-cjs/index.js:106:18)
        at _SignatureV4S3Express.credentialProvider (****/node_modules/@smithy/property-provider/dist-cjs/index.js:124:18)
        at _SignatureV4S3Express.signRequest (****/node_modules/@smithy/signature-v4/dist-cjs/index.js:486:25)
        at ****/node_modules/@aws-sdk/middleware-signing/dist-cjs/index.js:223:21
        at ****/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
        at ****/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/index.js:173:18
        at ****/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:97:20
        at ****/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:120:14
        at ****/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22
```

```
// package.json
{
  "dependencies": {
    "@aws-sdk/client-s3": "^3.554.0",
    "@aws-sdk/credential-providers": "^3.554.0",
    ...
  },
  ...
}
```

node version: v20.12.0

#### additional
after add `yarn add @aws-sdk/credential-provider-env`
```
`ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From test/app.e2e-spec.ts.`
```

### SDK version number

@aws-sdk/package-name@version, ...

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.12.0

### Reproduction Steps

```
this.s3 = new S3(s3ClientConfig);
...
this.s3.getObject({ Bucket: this.bucket, Key: keys });
```

### Observed Behavior

.

### Expected Behavior

.

### Possible Solution

x

**Comment by RanVaknin** [comment]
Hi @vs223 ,

>code: undefined, TypeError: fromEnv is not a function TypeError: fromEnv is not a function

this suggest that the module was not installed. after you installed the dependency it seems like you are importing it after your jest E2E test has already been torn down. 

The code snippet you shared is incomplete, and does not give us enough info to go off of.
Can you please better articulate the problem and include a more complete and concise code snippet? 

Thanks,
Ran~
