### ISSUE TITLE
React Native peer dependency for Vue project using aws-sdk

### ISSUE THREAD

**Issue by JPVan** [aws/aws-sdk-js-v3#6017]
### Describe the bug

Using aws-sdk-js with Vue Amplify Authenticator gives an error about missing peer dependency react-native. https://ui.docs.amplify.aws/vue/connected-components/authenticator

### Expected Behavior

Expected not to have to install react-native into a Vue project. 

### Current Behavior

Copy of output following installation of aws-sdk-js as part of aws-amplify: 

 WARN  Issues with peer dependencies found
.
└─┬ aws-amplify 5.0.8
  └─┬ @aws-amplify/analytics 6.0.8
    └─┬ @aws-amplify/cache 5.0.8
      └─┬ @aws-amplify/core 5.0.8
        └─┬ @aws-sdk/client-cloudwatch-logs 3.6.1
          └─┬ @aws-sdk/middleware-retry 3.6.1
            └─┬ react-native-get-random-values 1.8.0
              └── ✕ missing peer react-native@>=0.56
Peer dependencies that should be installed:
  react-native@>=0.56

### Reproduction Steps

Steps to reproduce: 
npm create vue@latest 
amplify init
amplify add auth
pnpm install
pnpm i @aws-amplify/ui-vue aws-amplify

### Possible Solution

Perhaps use something other than react-native-get-random-values to get random values in @aws-sdk/middleware-retry 3.6.1. 

### Additional Information/Context

https://github.com/LinusU/react-native-get-random-values/issues/27

### SDK version used

@aws-sdk/client-cloudwatch-logs 3.6.1

### Environment details (OS name and version, etc.)

Windows 10, VS Code 1.74.2

**Comment by RanVaknin** [comment]
Hi there,

This seems to be a pretty old issue. Is this still a problem? I know we had a few other react native related tickets that we addressed in the recent past. 

Thanks,
Ran~

**Comment by JPVan** [comment]
I haven’t tried recently since I’ve switched to SvelteKit from Vue.

**Comment by aBurmeseDev** [comment]
It doesn't sound like this's an issue anymore. If anyone comes across this, feel free to create a new issue. Closing this now.
