### ISSUE TITLE
Support the pagination on list things of AWS IOT

### ISSUE THREAD

**Issue by smnodame** [aws/aws-sdk-js-v3#6018]
right now, it can do pagination by the next token but I want to to have ability to skip to the last page. How can we do it? 

```js
import { SearchIndexCommand } from '@aws-sdk/client-iot';

const command = new SearchIndexCommand({
  indexName: 'AWS_Things',
  queryString: `attributes.deleted:true`,
  nextToken: '<next_token>'
});
```

**Comment by aBurmeseDev** [comment]
Hi there, thanks for reaching out and apologies for the long wait.

Unfortunately, `SearchIndexCommand` operation can't be paginated as design by service API models which is something SDK doesn't have control over as SDK is generated upstream by service models. 

What you're doing with nextToken seems like a good way to achieve that but I can't think of a way to skip to the last page by using nextToken as it's an unique pagination token just to get to next page. 

I can reach out to service team with a request to make this operation paginatable but can't guarantee the outcome.
