### ISSUE TITLE
SESClient

### ISSUE THREAD

**Issue by akshaydodiya** [aws/aws-sdk-js-v3#6020]
### Describe the issue

Can't find the parameters for SESClient constructor

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/ses/

**Comment by aBurmeseDev** [comment]
Hi @akshaydodiya - thanks for reaching out. 

Client constructor should be linked at the bottom of the page. Let me know if you're looking for specific information.

**Comment by akshaydodiya** [comment]
Thanks, it is done now
