### ISSUE TITLE
@aws-sdk/lib-storage doesn't upload and freezes program

### ISSUE THREAD

**Issue by Calemy** [aws/aws-sdk-js-v3#6030]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I try to upload a stream.passThrough() object via the lib-storage.
when i run the code it just freezes the entire code

### SDK version number

@aws-sdk/package-name@version, ...

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Bun 1.1.4

### Reproduction Steps

```js
import { Upload } from "@aws-sdk/lib-storage"
import { S3 } from "@aws-sdk/client-s3"
import stream from "stream"
import fetch from "node-fetch"
const storage = new S3({
    endpoint: "https://s3.eu-central-2.wasabisys.com",
    region: "eu-central-2",
    credentials: {
        accessKeyId: process.env.storageID,
        secretAccessKey: process.env.storageKey
    }
})

const request = await fetch("https://catboy.best/d/1")
request.body.pipe(await uploadToStorage("maps/1.osz"))

async function uploadToStorage(path, retries = 0){
    const data = new stream.PassThrough()
    try {
        const upload = new Upload({
            client: storage,
            params: {
                Bucket: "mino",
                Key: path,
                Body: data
            }
        })
        upload.on("httpUploadProgress", (progress) => { console.log(progress) })
        console.log(await upload.done())
    } catch(e){
        console.error(e)
    } finally {
        return data;
    }
}
```

### Observed Behavior

progress never starts, function never gets finished and is stuck.

### Expected Behavior

to upload the file

**Comment by RanVaknin** [comment]
Hi @Calemy ,

The AWS SDK S3 client only officially guarantees compatibility with the AWS S3 service. We do not guarantee support for S3 clones like Wasabi / MinIO / digital ocean spaces or any other non AWS products.

Since this is not actionable by the SDK team I'm going to go ahead and close this.

Thanks,
Ran~
