### ISSUE TITLE
SignatureDoesNotMatch Error in S3 PUT Object in React Native

### ISSUE THREAD

**Issue by waleedshkt** [aws/aws-sdk-js-v3#6033]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The issue is stemming when I upload an base64-encoded JPEG image to S3 in React Native. I possible reasons were checked but to no avail. There is no issue with credentials (they aren't expired or mistyped as they work successfully in putting record to Aurora) nor with the request headers. In fact, the same logic works okay in web app.

I also tested different versions of the S3 client. Initially installed v3.556.0 and v.503.1 (installed in web app). But the same error is popping repeatedly. 

### SDK version number

@aws-sdk/client-s3@3.556.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

`node v20.10.0` and `react-native v0.69.10`

### Reproduction Steps

```js
import "react-native-get-random-values";
import "react-native-url-polyfill/auto";
import { ReadableStream } from "web-streams-polyfill";
globalThis.ReadableStream = ReadableStream;

import "@aws-sdk/util-endpoints";
import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";
const Buffer = require("buffer").Buffer;

const uploadImage = async (creds, imgUri) => {
  try {
    const client = new S3Client({
      region: AWS_REGION,
      credentials: {
        accessKeyId: creds.AccessKeyId,
        secretAccessKey: creds.SecretKey,
        sessionToken: creds.SessionToken,
      },
    });

    const respose = await client.send(
      new PutObjectCommand({
        Bucket: BUCKET_NAME,
        Key: TARGET_KEY,
        Body: new Buffer.from(
          imgUri.replace(/^data:image\/\w+;base64,/, ""),
          "base64",
        ),
        ContentType: `image/jpeg`,
        ContentEncoding: "base64",
        ServerSideEncryption: "AES256",
      }),
    );

    return response;
  } catch (error) {
    console.error(error);
    return -1;
  }
};
```

### Observed Behavior

The above mentioned comes up as been mentioned earlier

### Expected Behavior

Image should be uploading successfully

### Possible Solution

Workaround for now is to use Amplify Storage to upload image

**Comment by aBurmeseDev** [comment]
Hi @waleedshkt - thanks for reaching out. 

Here are a couple things I'd like to point out before further debugging:
- ContentType should be string, as I've seen this can cause Signature Mismatch in some cases. See [docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/command/PutObjectCommand/)
- React-native version you're on seems to be archived, I'm not sure if this's the culprit but wanted to point it out.

A few questions:
- Are you able to run other S3 operations? For example, try getObjectCommand.
- Can you paste the the logs/error here?

Let me know if issue persists and I'll be happy to further investigate.
Best,
John

**Comment by waleedshkt** [comment]
Thanks for the response.

Yes, I double checked the content type. This property is a string. I also made it lowercase as there was a similar mismatch issue raised earlier. But that didn't work either. Error kept popping up

I'm deliberately clinging to RN v0.69 owing to compatibility issues in newer versions with many node packages

Yes, other s3 commands are successfully executing

**Comment by aBurmeseDev** [comment]
Thank you for your response and apology for the wait. Are you still running into the issue? If so, can you please add this middleware stack to your code and share the output with us?
```ts
s3Client.middlewareStack.add(next => async (args) => {
 console.log(args.request)
 const response = await next(args);
 console.log(response);
 return next(args);
}, {step: 'finalizeRequest'})
```
