### ISSUE TITLE
MetadataService ignoring timeout config

### ISSUE THREAD

**Issue by morwoen** [aws/aws-sdk-js-v3#6042]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The MetadataService from @aws-sdk/ec2-metadata-service package ignores timeout config. The config is [initialised in the constructor](https://github.com/aws/aws-sdk-js-v3/blob/main/packages/ec2-metadata-service/src/MetadataService.ts#L25) but is never retrieved from the object [here](https://github.com/aws/aws-sdk-js-v3/blob/main/packages/ec2-metadata-service/src/MetadataService.ts#L35) or [here](https://github.com/aws/aws-sdk-js-v3/blob/main/packages/ec2-metadata-service/src/MetadataService.ts#L85).

### SDK version number

@aws-sdk/ec2-metadata-service@3.565.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.18.2

### Reproduction Steps

```
const metaData = new MetadataService({
    httpOptions: {
      timeout: 2000
    },
  });

return metaData.request('/latest/meta-data/placement/region', {})
```

The above has to be run locally where there is no metadata service access.

### Observed Behavior

Code hangs for over 30 seconds

### Expected Behavior

After 2 seconds the code should return a rejected promise

### Possible Solution

The config needs to be passed down to the HttpRequest.

**Comment by RanVaknin** [comment]
Hi @morwoen ,

Thanks for letting us know. This seems like an oversight. @siddsriv is taking a look.

All the best,
Ran~

**Comment by siddsriv** [comment]
thanks for reporting this, timeout config option been added for requests. closing this issue, feel free to create a new one if you encounter any other issues.

**Comment by morwoen** [comment]
Thanks @siddsriv , could you confirm which version the fix is in?

**Comment by morwoen** [comment]
Found it :) https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.574.0
