### ISSUE TITLE
Volumes of FSx for NetApp ONTAP missing AdministrativeActions prop

### ISSUE THREAD

**Issue by RonyLevAri** [aws/aws-sdk-js-v3#6048]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

According to the docs a volume entity should have an array of AdministrativeActions yet no such property is ever returned.  
For example in [UpdateVolumeCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/fsx/command/UpdateVolumeCommand/) the volume entity is returned without such prop. 

### SDK version number

@aws-sdk/package-name@version, ...

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node v21.2.0

### Reproduction Steps

1. create FSx ONTAP 
2. create volume
3. update volume's tiering policy using the UpdateVolume command

### Observed Behavior

returned volume response from update command missing AdministrativeActions 

### Expected Behavior

returned volume response from update command should have AdministrativeActions

**Comment by aBurmeseDev** [comment]
Hi @RonyLevAri - thanks for reaching out. I was able to reproduce this and confirm that `AdministrativeActions` is missing in the response. However, I can't say whether service API enforces it in the backend which is why I reached out to service team for further insights.

I'll circle back here once I hear back from service team. _P128943399_

**Comment by aBurmeseDev** [comment]
Service team responded: 
>AdministrativeActions is an optional field.  Currently update-volume actions on FSx ONTAP volumes do not return any AdministrativeActions.  But in the future they may be there.  The update-volume action is shared across the various FSx engine types, so some of the other engines may return it.

Let me know if you have further question to service team.
