### ISSUE TITLE
Cannot find package '@aws-sdk/client-s3' in Lambda function with a Layer

### ISSUE THREAD

**Issue by keithwhor** [aws/aws-sdk-js-v3#6057]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When creating a Lambda Function with a Layer containing `nodejs/node_modules`, I can no longer access the `@aws-sdk` v3 inside of my `nodejs-20.x` functions.

### SDK version number

Latest in Lambda

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

20.x

### Reproduction Steps

- Create a Lambda function that imports `@aws-sdk/client-s3` with a layer containing `nodejs/node_modules/` and any number of modules
- Publish it via `createFunction` or `updateFunctionCode` call in Node.js SDK
- Execute via `invoke` -- should encounter `Cannot find package '@aws-sdk/client-s3'`

### Observed Behavior

Lambda Function throws error; `Cannot find package '@aws-sdk/client-s3'`

### Expected Behavior

Lambda function executes as normal

### Possible Solution

Unsure; it seems that mounting a layer unmounts the AWS SDK.

**Comment by keithwhor** [comment]
I've found that directly importing `/var/runtime/node_modules/@aws-sdk/client-s3/dist-cjs/index.js` seems to work, but I'm not sure why `import` resolution doesn't work properly after a layer with node modules is attached?

**Comment by aBurmeseDev** [comment]
Hi @keithwhor - thanks for reaching out. 

I'm going to verify a few things:
- Can you check your SDK version and NodeJS runtime for your Lambda function? Ref: https://docs.aws.amazon.com/lambda/latest/dg/lambda-nodejs.html
- Did you also npm install `npm install @aws-sdk/client-s3`? Ref: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/
- What does your Lambda function and SDK code look like?
