### ISSUE TITLE
`DescribeSnapshotsCommand` mishandles empty array of filters

### ISSUE THREAD

**Issue by wuhkuh** [aws/aws-sdk-js-v3#6063]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When I configure an empty array of filters for `DescribeSnapshotsCommand`,
I get the response `InvalidParameterValue: The filter 'null' is invalid` from the backend.

### SDK version number

@aws-sdk/client-ec2@3.569.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.12.2

### Reproduction Steps

```typescript
import { DescribeSnapshotsCommand, EC2Client } from "@aws-sdk/client-ec2";

const client = new EC2Client();
const describeResponse = await client.send(
  new DescribeSnapshotsCommand({
    Filters: []
  })
);

console.log(describeResponse);
```

### Observed Behavior

I got the following response:

```
const response = new exceptionCtor({
                 ^

InvalidParameterValue: The filter 'null' is invalid
  at throwDefaultError$4
  at de_CommandError$3
  <truncated for brevity, the remainder is mangled>
  
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: '8a591f88-4042-40c4-9ab2-974fcc3c4aa9',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Code: 'InvalidParameterValue'
}
```

### Expected Behavior

No filters should be applied, when the array of filters to be applied is empty.
I expected to receive all snapshots (an unfiltered response) for the request.

### Possible Solution

- The backend should ignore an empty array of filters, assuming that these are sent over the wire as an array.
- The client could automatically transform an empty filter array to `undefined`, so I don't have to do this everywhere myself, when I'm dynamically building the list of filters.

**Comment by aBurmeseDev** [comment]
Hi @wuhkuh - thanks for reaching out.

>No filters should be applied, when the array of filters to be applied is empty.
I expected to receive all snapshots (an unfiltered response) for the request.

That's current behavior that it returns unfiltered response without param `Filters` and that’s the same behavior for across SDKs. Can you help me understand your specific use case that you'd like to keep `Filters` param with empty array there?

This code example will return all snapshots (unfiltered)
```ts
import { EC2Client, DescribeSnapshotsCommand } from "@aws-sdk/client-ec2"; // ES Modules import
const client = new EC2Client({
    region: "us-west-1"
});
const command = new DescribeSnapshotsCommand({});
const response = await client.send(command);

```

Hope it helps,
John

**Comment by syall** [comment]
@wuhkuh - For more context, did you encounter this issue when updating the SDK dependency version, or is this a new code path?
