### ISSUE TITLE
`@smithy/types` clients mistype `CloudFormation.describeStacks`

### ISSUE THREAD

**Issue by wuhkuh** [aws/aws-sdk-js-v3#6065]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When I'm casting a `CloudFormation` instance as one (or more) Smithy types (`NodeJsClient`, `AssertiveClient`, ...), it loses the type information.

_Update:_
Apparently this has a wider scope than just the method I'm interested in.

### SDK version number

@aws-sdk/client-cloudformation@3.569.0
@smithy/types@2.12.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.12.2

### Reproduction Steps

```typescript
import { type AssertiveClient } from "@smithy/types";
import { CloudFormation } from "@aws-sdk/client-cloudformation";

const client = new CloudFormation({}) as AssertiveClient<CloudFormation>;
const describeStacksResponse = await client.describeStacks({
  StackName: STACK_NAME
});
```

### Observed Behavior

You will see the following TypeScript error:

```
No overload matches this call.
  Overload 1 of 4, '(command: Command<object, object, { $metadata: { httpStatusCode?: number | undefined; requestId?: string | undefined; extendedRequestId?: string | undefined; cfId?: string | undefined; attempts?: number | undefined; totalRetryDelay?: number | undefined; }; }, { ...; }, unknown>, options?: any): Promise<...>', gave the following error.
    Object literal may only specify known properties, and 'StackName' does not exist in type 'Command<object, object, { $metadata: { httpStatusCode?: number | undefined; requestId?: string | undefined; extendedRequestId?: string | undefined; cfId?: string | undefined; attempts?: number | undefined; totalRetryDelay?: number | undefined; }; }, { ...; }, unknown>'.
  Overload 2 of 4, '(command: Command<object, object, { $metadata: { httpStatusCode?: number | undefined; requestId?: string | undefined; extendedRequestId?: string | undefined; cfId?: string | undefined; attempts?: number | undefined; totalRetryDelay?: number | undefined; }; }, { ...; }, unknown>, options?: any, cb?: ((err: any, data?: { ...; } | undefined) => void) | undefined): void | Promise<...>', gave the following error.
    Object literal may only specify known properties, and 'StackName' does not exist in type 'Command<object, object, { $metadata: { httpStatusCode?: number | undefined; requestId?: string | undefined; extendedRequestId?: string | undefined; cfId?: string | undefined; attempts?: number | undefined; totalRetryDelay?: number | undefined; }; }, { ...; }, unknown>'.
ts(2769)
```

### Expected Behavior

No type errors, like other method calls for the constructed client. 

### Additional Information/Context

It's incredibly hard to step through the generated types. It's definitely a problem related to Smithy code generation.

**Comment by kuhe** [comment]
dev note: likely due to interaction between the all-optional args generating an additional no-arg method signature and the type transform only seeing the first available signature

**Comment by kuhe** [comment]
a fix has been applied as of this version: https://www.npmjs.com/package/@aws-sdk/client-cloudformation/v/3.575.0, using `^3.0.0` of `@smithy/types`.
