### ISSUE TITLE
docs: use `pnpm add <pkg>` instead of `pnpm install <pkg>`

### ISSUE THREAD

**Issue by jferrettiboke** [aws/aws-sdk-js-v3#6066]
### Describe the issue

It should be `pnpm add @aws-sdk/client-s3` instead of `pnpm install @aws-sdk/client-s3`.

`pnpm install` is used to install all dependencies for a project while `pnpm add <pkg>` is used to install a package and any packages that it depends on.

More info (official source):

- https://pnpm.io/cli/add
- https://pnpm.io/cli/install

<img width="398" alt="Screenshot 2024-05-05 at 20 01 36" src="https://github.com/aws/aws-sdk-js-v3/assets/11066224/dea4e0b5-47db-4fbe-90b0-3555365d9237">

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/

**Comment by jferrettiboke** [comment]
@aBurmeseDev `pnpm install <pkg>` does the same as `pnpm add <pkg>` today, but it might stop functioning that way in future versions since the official docs clarify the difference between the two. It might be that `pnpm install <pkg>` was used in past versions, and the PNPM team didn't want to remove support for it right away after introducing `pnpm add <pkg>`.

**Comment by trivikr** [comment]
Internal fix is in CR-126891228 for API Reference.
This issue will be updated once the fix is merged, with expected time of doc deployment.

**Comment by trivikr** [comment]
> Internal fix is in CR-126891228 for API Reference.
Internal fix is merged.

The change is expected to go live around 6:30 PM Pacific on Tue May 14th.
