### ISSUE TITLE
(short issue description)

### ISSUE THREAD

**Issue by TyagiiUjjawal** [aws/aws-sdk-js-v3#6070]
### Describe the issue

what is the config in this?

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/rekognition/command/DetectFacesCommand/

**Comment by kuhe** [comment]
described at the bottom of https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/rekognition/
