### ISSUE TITLE
The request must contain the parameter MessageHandle

### ISSUE THREAD

**Issue by jeremy-brooks** [aws/aws-sdk-js-v3#6092]
### Describe the issue

The docs are missing a 3rd parameter which seems to be requried for a delete message command to work: "MessageHandle"

This needs to be the message ID of the message being deleted I think.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/sqs/command/DeleteMessageCommand/

**Comment by aBurmeseDev** [comment]
Hi @jeremy-brooks - thanks for reaching out. 

I've come across a similar post in the past and my colleague [mentioned](https://github.com/aws/aws-sdk-js-v3/issues/5478#issuecomment-1808787727) in a comment that it might be when null value gets passed into `receiptHandle`. Let me know if that's the same behavior you're seeing or should I look further into it.

Best,
John
