### ISSUE TITLE
Support for Header in SendEmail

### ISSUE THREAD

**Issue by eaoliver** [aws/aws-sdk-js-v3#6093]
### Describe the feature

Amazed released support for Headers in SendMail and SendRawMail in March 2024.  It would be nice if SendEmail supported headers: 
https://aws.amazon.com/about-aws/whats-new/2024/03/amazon-ses-headers-sending-email/

### Use Case

For adding headers to simple emails. 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.575.0

### Environment details (OS name and version, etc.)

Node: v20.8.0

**Comment by RanVaknin** [comment]
Hi @eaoliver ,

This seems to already [be supported](https://github.com/aws/aws-sdk-js-v3/commit/4b858e0ae26c867e2b079b75620ed5dfd24b4bfc). You need to use SESv2 Client to use this.

Thanks,
Ran~

**Comment by eaoliver** [comment]
Thank you @RanVaknin .  I did not see the second v2 client.
