### ISSUE TITLE
Add possibility to retrieve savings plans inventory for the whole organization

### ISSUE THREAD

**Issue by henriklewander** [aws/aws-sdk-js-v3#6095]
### Describe the feature

In AWS Management Console, for an organization management account it is possible to show savings plans inventory for either the management account itself or for the complete organization.
Listing the account inventory is supported in the SDK but not listing the organization inventory.

### Use Case

When you do not have access to the member accounts in an organization but to the management account, it is currently impossible to show the organization inventory. This is important as the management account is responsible for the billing + it is possible to see in the management console so no new security issues.

### Proposed Solution

Add an option to the input of DescribeSavingsPlansCommand to select "Organization Inventory" or "Account Inventory" (the default).

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.575.0

### Environment details (OS name and version, etc.)

Windows 11

**Comment by aBurmeseDev** [comment]
Hi @henriklewander - thanks for reaching out.

This sounds like a feature request for service API team rather than AWS SDK as we do not have control to the upstream API. I'd recommend reaching out via [AWS Support](https://aws.amazon.com/contact-us/) or I can submit an internal request on your behalf if you'd like.

**Comment by henriklewander** [comment]
Hi @aBurmeseDev , thanks for the reply. If you could submit an internal request on my behalf, that would be great. Thanks!

**Comment by aBurmeseDev** [comment]
Submitted internal ticket (ref: _P130409175_) for you. As we want to keep this repo for SDK related only, I'm going to close this. Please look out for new feature announcement in the future. 
Best,
John
