### ISSUE TITLE
what to put as a config?

### ISSUE THREAD

**Issue by dhavalpacewisdom** [aws/aws-sdk-js-v3#6097]
### Describe the issue

const client = new PersonalizeEventsClient(config);
In the above line, could you mention what to put as a config?

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/personalize-events/command/PutEventsCommand/

**Comment by aBurmeseDev** [comment]
Hi @dhavalpacewisdom - thanks for reaching out.

For service-level configuration, you can pass in objects like region or credentials which you'll have significant control over your default local configuration. If those configurations aren't defined, SDK will use your local config.

For example:
`const client = new PersonalizeEventsClient({ region: 'us-east-1', credentials: {...} });`
or if you have credentials configured locally, you can run it like 
`const client = new PersonalizeEventsClient();`

You can read more about it here: https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/global-config-object.html

Hope it helps,
John
