### ISSUE TITLE
SES Interface change is not compatible

### ISSUE THREAD

**Issue by 291devoss** [aws/aws-sdk-js-v3#6102]
### Pre-Migration Checklist

- [X] I've read the [Migration Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/migrating-to-v3.html).
- [X] I've reviewed the upgrading notes and major version differences mentioned in [`UPGRADING.md`](https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md).
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for similar migration issues.

### Which JavaScript Runtime is this issue in?

Node.js (includes AWS Lambda)

### AWS Lambda Usage

- [X] Yes, my application is running on AWS Lambda.
- [ ] No, my application is not running on AWS Lambda.

### Describe the Migration Issue

SES SendEmailResponse Interface change in v2 to v3 is not compatible because "MessageId" property can be undefined in v3.
Is there any case that  "MessageId" will be undefined without throwing any Exception?
If it is yes I need to know when the property will be undefined.
If it is no I think "MessageId" property should be string.
This difference is not written in any document I saw.

### Observed Differences/Errors

aws-sdk v2 interface definition
```
...
  export interface SendEmailResponse {
    /**
     * The unique message identifier returned from the SendEmail action. 
     */
    MessageId: MessageId;
  }
...
  export type MessageId = string;
```

aws-sdk v3 interface definition
```
/**
 * <p>Represents a unique message ID.</p>
 * @public
 */
export interface SendEmailResponse {
    /**
     * <p>The unique message identifier returned from the <code>SendEmail</code> action. </p>
     * @public
     */
    MessageId: string | undefined;
}
```

**Comment by 291devoss** [comment]
@RanVaknin
Thanks, I read https://github.com/aws/aws-sdk-js-v3/issues/5992#issuecomment-2052253822, but we cannot easily apply with the solution, [UncheckedClient or AssertiveClient](https://github.com/smithy-lang/smithy-typescript/tree/main/packages/types#scenario-removing--undefined-from-input-and-output-structures) .
We have to handle the process when "MessageId" property was undefined. 
So far, is it right that an unexpected  error had happened when required property in aws-sdk-v2, like the "MessageId" property  was undefined.

**Comment by RanVaknin** [comment]
Hi @291devoss ,

>So far, is it right that an unexpected error had happened when required property in aws-sdk-v2, like the "MessageId" property was undefined.

If I understand what you are asking correctly, the change in interface in v3 only represent a change in SDK behavior. From an SES API perspective there is no change you can safely assert no null for this parameter as you were using it in v2. I'm not an SES expert, but AFAIK when a valid response (not an Exception) is returned by the SES for `SendEmail`, there is always going to be a `messageID` returned with it. 

This change in response interface is not unique to SES, it would be across the board for all v3 response interfaces for the reasons mentioned in #5992.

Thanks,
Ran~
