### ISSUE TITLE
client use http protocol failed 

### ISSUE THREAD

**Issue by uzengo** [aws/aws-sdk-js-v3#6106]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

our client code
```
        s3Client = new S3({
          region: 'xx',
          endpoint: 'http://abc.com:',
          disableHostPrefix: true,
          tls: false,
          credentials: {
            accessKeyId: accessKey,
            secretAccessKey: accessSecret,
            sessionToken: accessToken,
          },
        });
   
 const uploadParams = {
        Bucket: bucket,
        Key: halfPath,
        Body: file, // file from <input type="file">
      };
      const upload = new Upload({
        client: s3Client,
        params: uploadParams,
        queueSize: 4, // optional concurrency configuration
        partSize: 1024 * 1024 * 5, // optional size of each part
        leavePartsOnError: false, // optional manually handle dropped parts
      });
      console.log('==>zzzz11');

      upload.on('httpUploadProgress', (progress) => {
        console.log('==>progress', progress);
      });
      try {
        await upload.done();
      } catch (err) {
        console.log('==>444', err);
      }

```

when we use this code, our endpoint change to `https`, the config is no work!!!

![image](https://github.com/aws/aws-sdk-js-v3/assets/21187455/1578ad00-c3ec-47e5-8625-c541742473c9)

### SDK version number

"@aws-sdk/client-s3": "3.577.0" "@aws-sdk/lib-storage": "3.578.0"

### Which JavaScript Runtime is this issue in?

React Native

### Details of the browser/Node.js/ReactNative version

v16.18.0

### Reproduction Steps

see code

### Observed Behavior

change url protocol from http to https

### Expected Behavior

use http endpoint

**Comment by kairiruutel** [comment]
I have a similar problem, the need for turning TLS off is for the functional tests, is there any workaround for this issue?

**Comment by aBurmeseDev** [comment]
Hi @uzengo - I'm sorry this fell off my radar. 

The ERR_SSL_PROTOCOL_ERROR is an error that occurs when there is a problem with the SSL/TLS protocol negotiation during the connection establishment phase. This error typically occurs when the client and server cannot agree on a common SSL/TLS protocol version or cipher suite.

In your case, when you specify `http://abc.com` as the endpoint, you're attempting to make an unencrypted HTTP connection to the S3 service. However, AWS S3 requires secure connections over HTTPS, and it seems that the combination of your endpoint configuration and the use of the `tls: false` option causes the SSL/TLS protocol negotiation to fail.

By changing the endpoint to `https://abc.com`, you're explicitly specifying that the connection should be made over HTTPS, which resolves the SSL/TLS protocol negotiation issue.

If you need to use a custom endpoint for your S3 service, you should use the https protocol scheme and remove the `tls: false` option, as TLS (Transport Layer Security) is required for secure communication with AWS services. The correct configuration would be:
```ts
s3Client = new S3({
  region: 'xx',
  endpoint: 'https://abc.com',
  disableHostPrefix: true,
  credentials: {
    accessKeyId: accessKey,
    secretAccessKey: accessSecret,
    sessionToken: accessToken,
  },
});
```
Hope it helps,
John
