### ISSUE TITLE
error TS2339: Property 'send' does not exist on type 'SecretsManagerClient'

### ISSUE THREAD

**Issue by BowgartField** [aws/aws-sdk-js-v3#6135]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I'm trying to bundle `@aws-sdk/client-secrets-manager` into my nodeJs package with rollup.
Bundling is going good but when I'm generating the type file I got this error.
I'm using pnpm to manage my project.

### SDK version number

@aws-sdk/client-secrets-manager@^3.583.0 

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.9.0

### Reproduction Steps

This is the code I'm trying to bundle:
```ts
import { GetSecretValueCommand, SecretsManagerClient } from "@aws-sdk/client-secrets-manager";
export const getAwsSecrets = async (region: string, secretName: string) => {
    const client = new SecretsManagerClient({ region });
    const response = await client.send(new GetSecretValueCommand({ SecretId: secretName }));
}
```

### Observed Behavior

TypeScript compilation fails with
Property 'send' does not exist on type 'SecretsManagerClient'.

### Expected Behavior

TypeScript compilation succeeds

**Comment by aBurmeseDev** [comment]
Hi @BowgartField - thanks for reaching out.

Can you try deleting your `node_modules` and `package-lock.json` and try running pnpm add/install again to see if it resolves the error?
Best,
John

**Comment by BowgartField** [comment]
> Hi @BowgartField - thanks for reaching out.
> 
> Can you try deleting your `node_modules` and `package-lock.json` and try running pnpm add/install again to see if it resolves the error? Best, John

Hi,
I tried deleting my package node_modules + my monorepo node_modules and deleting pnpm-lock.json but it's still not working.

**Comment by macstr1k3r** [comment]
+1

**Comment by aBurmeseDev** [comment]
@BowgartField Can you try the suggestion by @macstr1k3r and confirm if it resolves your issue as well?
