### ISSUE TITLE
@aws-sdk/client-lambda: ListFunctionsCommand 

### ISSUE THREAD

**Issue by eiglesia4** [aws/aws-sdk-js-v3#6136]
### Describe the issue

The doc does not indicate that input parameter MasterRegion is mandatory, but indeed the function fails if not present. Also when set, but not set FunctionVersion, the call fails (as has to be) but the message indicates MasterArn instead MasterRegion. Says something like "FunctionVersion cannot be NULL when MasterArn is set".

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/lambda/command/ListFunctionsCommand/

**Comment by aBurmeseDev** [comment]
Hi @eiglesia4 -  thanks for reaching out.

I was able to run it successfully without any params which indicates `MasterRegion` is optional. Can you share your code (without any sensitive info) and the error you're getting that would give me some insight into the behavior?

```ts
import { LambdaClient, ListFunctionsCommand } from "@aws-sdk/client-lambda"; 
const client = new LambdaClient();
const input = {};
const command = new ListFunctionsCommand(input);
const response = await client.send(command);
console.log(response)
```
Best,
John
