### ISSUE TITLE
SSMClient unable to fetch secrets while running in Next.js middleware

### ISSUE THREAD

**Issue by fs24-chrter** [aws/aws-sdk-js-v3#6146]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I experienced an issue that AWS credentials could not be resolved by code that is running in a Next.js middleware.
The same code is running fine if it is executed in a normal Next.js page. 

### SDK version number

@aws-sdk/client-ssm@3.583.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Nextjs 14.2.3

### Reproduction Steps

See reproducible isolated issue here: https://github.com/fs24-chrter/AWS-ssmclient-nextjs-issue

### Observed Behavior

Middleware code is not able to fetch AWS credentials and its config resolves to a `Browser` config. Error message shown: `Credential is missing`.

Normal page code is able to fetch AWS credentials and its config resolves to `Node` config.

### Expected Behavior

I would expect that also the code running in the middleware is able to fetch AWS credentials. Since this code is executed on the server side and should have the same privileges as a normal Next.js page.

### Possible Solution

It looks like the constructor of `SSMClient` resolves to a runtimeConfig that is of type `Browser` in the middleware and therefore is not able to fetch policies from ECS task role. 
The same code resolves to runtimeConfig of type `Node` if running in normal Next.js page. Here the code is able to fetch the policies from ECS task role.

It do not understand yet why code in the middleware thinks it's running in a Browser.

**Comment by aBurmeseDev** [comment]
Hi @fs24-chrter - thanks for reaching out and sorry to hear you're running into an error.

Before I attempt to reproduce it, can you share repro steps specific to SDK as far as how you configured the [credentials](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-credentials-node.html) and share the error logs as well? I want you to rule out everything else and simply make SDK SSMClient call with `GetParametersByPathCommand` and we can further investigate.

**Comment by fs24-chrter** [comment]
> Hi @fs24-chrter - thanks for reaching out and sorry to hear you're running into an error.
> 
> Before I attempt to reproduce it, can you share repro steps specific to SDK as far as how you configured the [credentials](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-credentials-node.html) and share the error logs as well? I want you to rule out everything else and simply make SDK SSMClient call with `GetParametersByPathCommand` and we can further investigate.

Hi @aBurmeseDev,

sure, the most simple way to reproduce is to follow the link to the Github Repo that I've provided in the description. You will find a Docker image there. If you build this and push to ECR, you can run this as is in ECS. I've documented everything in the repository but happy to replicate it also directly here.

**Reproduction**

Reproducable code that shows the issue:
```
async function getParametersWithTryCatch(uuid: string, source: string) {
  let ssmClient: SSMClient;

  try {
    ssmClient = new SSMClient({ region: 'eu-central-1' });

    // This should NOT resolve to browser config since we're running on the server side
    console.log(`${uuid} [${source}] Resolved config in client: ${ssmClient.config.runtime}`)
  }
  catch(error) {
    console.log(`${uuid} [${source}] Could not create SSMClient. ${JSON.stringify(error)}`);
    return;
  }

  try {
    const credentials = await ssmClient.config.credentials();
    console.log(`${uuid} [${source}] Config credentials. Credentials: ${JSON.stringify(credentials)}`);
  }
  catch(error) {
    console.log(`${uuid} [${source}] Could not log config credentials. ${JSON.stringify(error)}`);
    return;
  }

  try {
    const cmd = new GetParametersByPathCommand({
      Path: '/INT/common',
      Recursive: true,
      WithDecryption: true,
    });
  
    const resp = await ssmClient.send(cmd);
    console.log(`${uuid} [${source}] Got response. Response: ${JSON.stringify(resp)}`);
  }
  catch(error) {
    console.log(`${uuid} [${source}] Could not get parameters by path. ${JSON.stringify(error)}`)
  }
}
```
The code above fails only if it runs in the middleware. Then the error message is `Credential is missing`.

If the code runs anywhere else, it runs just fine.

**Credentials configuration**

Credentials should be fetched via task role. For this to work, you need to configure task role e.g. with this inline policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "secretsmanager:DescribeSecret",
                "secretsmanager:GetSecretValue"
            ],
            "Resource": "arn:aws:secretsmanager:eu-central-1:<redacted>:secret:<redacted>",
            "Effect": "Allow"
        },
        {
            "Action": "ssm:GetParametersByPath",
            "Resource": "*",
            "Effect": "Allow"
        }
    ]
}
```

Let me know if you need something else.

**Comment by kunalhexus** [comment]
Seeing the same issue for dynamodb client.

**Comment by cowsandmilk** [comment]
See the note at https://nextjs.org/docs/app/api-reference/file-conventions/middleware#runtime that middleware only runs on the Edge runtime.

Then, see https://nextjs.org/docs/app/api-reference/edge that mentions the Edge runtime is based on web apis.

Next intentionally makes it so your middleware looks at the environment around it and thinks it is in a browser because there are no Node.js apis available and all the apis are based on the Web version.

https://github.com/vercel/next.js/discussions/46722 is an effort at making this configurable so that middleware can be run in the Node.js environment.

**Comment by kuhe** [comment]
The AWS SDK's browser vs Node.js differentiation is done at compile time using package.json metadata for bundlers. The SDK does not attempt to recognize what environment it is in at runtime.

You should build (i.e. at the bundler or build configuration level) the application in a way that targets Node.js if you want to run Node.js credential resolvers. It sounds like Next may be building the application in a way that signals it is targeting a browser environment. If that is intentional, then you need to obtain credentials manually to pass to the AWS SDK client just as you would in a browser.
