### ISSUE TITLE
No matching version found for `@aws-sdk/middleware-flexible-checksums@3.587.0`

### ISSUE THREAD

**Issue by TenviLi** [aws/aws-sdk-js-v3#6152]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Install `latest`(`@aws-sdk/client-s3@3.587.0`) failed
No matching version found for @aws-sdk/middleware-flexible-checksums@3.587.0

### SDK version number

@aws-sdk/client-s3@3.587.0, @aws-sdk/middleware-flexible-checksums@3.587.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.12.0

### Reproduction Steps

Just run `pnpm install @aws-sdk/client-s3`

### Observed Behavior

```log
No matching version found for @aws-sdk/middleware-flexible-checksums@3.587.0

This error happened while installing the dependencies of @aws-sdk/client-s3@3.587.0

The latest release of @aws-sdk/middleware-flexible-checksums is "3.577.0".

If you need the full list of all 97 published versions run "$ pnpm view @aws-sdk/middleware-flexible-checksums versions".
```

### Expected Behavior

Check @aws-sdk/middleware-flexible-checksums@3.587.0

**Comment by RanVaknin** [comment]
Hi @TenviLi,

I'm not seeing this issue when installing client-s3:

```console
$ pnpm init
Wrote to /Users/rvaknin/test_folder/6152/package.json

{
  "name": "6152",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
$ pnpm install @aws-sdk/client-s3
Packages: +98
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 98, reused 98, downloaded 0, added 98, done

dependencies:
+ @aws-sdk/client-s3 3.590.0

Done in 1.5s
$ pnpm ls
Legend: production dependency, optional only, dev only

6152@1.0.0 /Users/rvaknin/test_folder/6152

dependencies:
@aws-sdk/client-s3 3.590.0
```

This also works perfectly when I'm explicitly installing `@aws-sdk/client-s3@3.587.0`

My guess is that somewhere in your lock file you have multiple versions of the S3 installed and it creates a conflict.

You should run `pnpm dedupe`, and see if it solves your issue.

Thanks,
Ran~
