### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by calabr93** [aws/aws-sdk-js-v3#6154]
### Describe the issue

_"For **synchronous** function invocation, use Invoke."_
instead of
_"For **asynchronous** function invocation, use Invoke."_

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/lambda/command/InvokeAsyncCommand/

**Comment by aBurmeseDev** [comment]
Hi @calabr93 - thanks for reporting this. 

First, I wanted to mention that `InvokeAsync` has been deprecated (please refer to [Lambda docs](https://docs.aws.amazon.com/lambda/latest/api/API_InvokeAsync.html)). 

With [`Invoke`](https://docs.aws.amazon.com/lambda/latest/api/API_Invoke.html), it functions both synchronously and asynchronously. Here's what the doc say:

>You can invoke a function synchronously (and wait for the response), or asynchronously. By default, Lambda invokes your function synchronously (i.e. theInvocationType is RequestResponse). To invoke a function asynchronously, set InvocationType to Event. Lambda passes the ClientContext object to your function for synchronous invocations only.

Also for reference, our SDK documentations are upstream generated by service API docs and in this case, JavaScript SDK documentation reflects the Lambda doc. The only thing that's missing is the deprecation banner which I'll get it added to. 

Hope it makes sense and let me know if there's any further questions. 
Best,
John
