### ISSUE TITLE
StartDate, EndDate and ScheduleExpressionTimeZone fields on PutRulesCommand

### ISSUE THREAD

**Issue by LuccaRebelloToledo** [aws/aws-sdk-js-v3#6158]
### Describe the feature

Add the StartDate, EndDate, ScheduleExpressionTimeZone and FlexibleTimeWindow fields on PutRulesCommand

![19094c64-9bdf-4fcf-809d-07722d82bb30](https://github.com/aws/aws-sdk-js-v3/assets/99377036/e06b57d8-5912-4385-87cc-08b958da90d3)

### Use Case

I have a use case like others of recursion in scheduling notifications and the impact that when this notification starts and in the desired time zone. This would bring a lot of dynamism to the client event bridge

### Proposed Solution

[](url)

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.588.0

### Environment details (OS name and version, etc.)

Windows Version 10.0.19045 Build 19045

**Comment by aBurmeseDev** [comment]
Hi @LuccaRebelloToledo - thanks for reaching out. 

I see that you also created a PR. These models are generated by upstream service API and SDK team doesn't modify any generated models. What you're asking needs to reviewed and updated by service team (EventBridge) in this case. Once it's updated on service model, you'll be able to see it across SDK languages. 

You can either submit a request via [AWS Support](https://aws.amazon.com/contact-us/) or I can submit one on your behalf if you'd like. 
Hope that makes sense and let me know if you have any further questions.

**Comment by LuccaRebelloToledo** [comment]
Hi @aBurmeseDev

Thank you very much for your contact and for your explanation. Could you make the request on my behalf? I would be very grateful, if you need more information, I'm at your disposal! Thank you again very much and have a great day :)

**Comment by aBurmeseDev** [comment]
Submitted internal request to EventBridge (ref: _P134937654_)

**Comment by embano1** [comment]
Just to check, are you requesting to have these EventBridge Scheduler features available in EventBridge `PutRules` to create schedules? If so, is there any reason why you can't use Scheduler? Scheduler is purpose-built for managing schedules, is the successor to EventBridge schedules on rules, and therefore we don't have plans to add new features to the scheduling capabilities in `PutRule`.

**Comment by LuccaRebelloToledo** [comment]
Hey Michael, how are you? I hope everything is fine :)

Based on what you said, I did my research and found client-scheduler and this library perfectly meets what I was requesting. I apologize for the lack of attention previously, but, as a user, when using the tool in the CLI, the first thing that comes to mind when downloading the SDK is to look for the event-bridge client and not the scheduler. At first, it seemed like it was a new event-bridge feature and not a new client/SDK. Anyway, thank you very much Michael, congratulations on the product!

**Comment by embano1** [comment]
@LuccaRebelloToledo thx a ton, you rock!
