### ISSUE TITLE
Incorrect interface types in Amazon CloudFront clients

### ISSUE THREAD

**Issue by piotrekwitkowski** [aws/aws-sdk-js-v3#6165]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Many of the required strings in the client's models are incorrectly typed as `string | undefined`, but required in practice. They should be typed as `string` instead.

![image](https://github.com/aws/aws-sdk-js-v3/assets/17732966/dc497777-e0af-43c7-b8b6-9dbc93090bfa)

This applies for all commands of the client:

- [DeleteKeyCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/cloudfront-keyvaluestore/command/DeleteKeyCommand)
- [DescribeKeyValueStoreCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/cloudfront-keyvaluestore/command/DescribeKeyValueStoreCommand)
- [GetKeyCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/cloudfront-keyvaluestore/command/GetKeyCommand)
- [ListKeysCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/cloudfront-keyvaluestore/command/ListKeysCommand)
- [PutKeyCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/cloudfront-keyvaluestore/command/PutKeyCommand)
- [UpdateKeysCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/cloudfront-keyvaluestore/command/UpdateKeysCommand)

There are 13 occurrences of such bug across these 6 methods.

### SDK version number
@aws-sdk/client-cloudfront@3.590.0
@aws-sdk/client-cloudfront-keyvaluestore@3.590.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node v18.19.0

### Reproduction Steps
In the `@aws-sdk/client-cloudfront`:
```typescript
import { CloudFrontClient, DescribeKeyValueStoreCommand } from "@aws-sdk/client-cloudfront"; 
const client = new CloudFrontClient({ region: "us-east-1" });
const input = { Name: undefined }; // <-- this field should be required, `string` only, not `string | undefined`
const command = new DescribeKeyValueStoreCommand(input); <- I expect linting error here, because the `Name` field is actually required by the API
```

Similar for the other client, from `@aws-sdk/client-cloudfront-keyvaluestore`
```typescript
import { CloudFrontKeyValueStoreClient, DescribeKeyValueStoreCommand } from "@aws-sdk/client-cloudfront-keyvaluestore"; 
const client = new CloudFrontKeyValueStoreClient({ region: "us-east-1" });
const input = { Name: undefined }; // <-- this field should be required, `string` only, not `string | undefined`
const command = new DescribeKeyValueStoreCommand(input); <- I expect linting error here, because the `Name` field is actually required by the API
```

### Observed Behavior

These types should be `string`s - these fields are required by the API, and there is a runtime error if the value is not set:
```
    "ValidationException: 1 validation error detected: Value null at 'ifMatch' failed to satisfy constraint: Member must not be null",
    "    at de_ValidationExceptionRes (/var/runtime/node_modules/@aws-sdk/client-cloudfront-keyvaluestore/dist-cjs/index.js:585:21)",
    "    at de_CommandError (/var/runtime/node_modules/@aws-sdk/client-cloudfront-keyvaluestore/dist-cjs/index.js:502:19)",
...
```

### Expected Behavior

1/ SDK type mentioning `string` only, 
2/ my IDE / TypeScript able to detect this behavior at lint/compile time.

### Possible Solution

Fix autogenerated types

### Additional Information/Context

I may be able to fix the bug, please just tell me where to start.

**Comment by aBurmeseDev** [comment]
Hi @piotrekwitkowski - thanks for reaching out. 

I'm not able to reproduce with the code below. Can you share reproducible code for the error? 
```ts
import { CloudFrontClient, DescribeKeyValueStoreCommand } from "@aws-sdk/client-cloudfront"; 
const client = new CloudFrontClient({region: "us-west-1"});
const input = { 
  Name: "STRING_VALUE", 
};
const command = new DescribeKeyValueStoreCommand(input);
const response = await client.send(command);
```

**Comment by piotrekwitkowski** [comment]
Hi, updated Node and SDK version above. The issue is not about the good case, when you provide the Name value. It is about the case where I don't provide the value, which is a problem that should be caught way earlier.

**Comment by aBurmeseDev** [comment]
Thanks for your response. A few things to address here:
- Name value is a param required by service API (CloudFront) and it throws error when not provided, which is correct behavior.
- Which param required in every client call is defined in service models that are generated upstream by service teams and SDK doesn't have control over it.
-  As far as why we display type as `string | undefined` vs only `string`, it's for forward-compatibility with service models and has been addressed a few times on this repo (https://github.com/aws/aws-sdk-js-v3/issues/5992). 

Hope it clears things up, let me know if there's any further questions!
