### ISSUE TITLE
Bedrock Converse API missing exports for commonjs

### ISSUE THREAD

**Issue by mtliendo** [aws/aws-sdk-js-v3#6188]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When using ES Modules, the docs state that I should be able to import the methods like so:

```ts
import { BedrockRuntimeClient, ConverseCommand } from "@aws-sdk/client-bedrock-runtime"; // ES Modules import
```

However that results in the following runtime error:

```txt
"SyntaxError: Named export 'ConverseCommand' not found. The requested module '@aws-sdk/client-bedrock-runtime' is a CommonJS module, which may not support all module.exports as named exports.\nCommonJS modules can always be imported via the default export, for example using:\n\nimport pkg from '@aws-sdk/client-bedrock-runtime';\nconst { ConverseCommand } = pkg;\n"
```

The solution is to do something like `import * from '@aws-sdk/client-bedrock-runtime'`. Though this is not mentioned in the docs.

---
The other issue is that it doesn't seem possible to call the `ConverseCommand(input)`. If I prefix it with `new`, then I get a runtime error saying that it is not a constructor. If I omit the `new` keyword, I get an error saying it is not a function. Logging out `bedrock.ConverseCommand` returns `undefined`. 

For reference, this is my sample code:

```ts
import bedrock from '@aws-sdk/client-bedrock-runtime'

const client = new bedrock.BedrockRuntimeClient({
	region: 'us-east-1',
})

export const handler = async () => {
	const input = {
		modelId: 'anthropic.claude-3-haiku-20240307-v1:0',
		messages: [
			{
				role: 'assistant' as bedrock.ConversationRole,
				content: [
					{
						text: 'You are a sassy intern. You reply with the letter "B" as the first item in your sentence.',
					},
				],
			},
			{
				role: 'user' as bedrock.ConversationRole,
				content: [
					{
						text: 'What is a good type of taco?',
					},
				],
			},
		],
	}

	const command = new bedrock.ConverseCommand(input)
	const response = await client.send(command)

	console.log('the response', response)
	return 'Hello, World!'
}
```

### SDK version number

@aws-sdk/client-bedrock-runtime@^3.592.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node 20

### Reproduction Steps

Create a lambda function with version 20 and paste in the provided code. make sure the lambdas package.json type is set to `module`.

### Observed Behavior

pasted in details section. 

### Expected Behavior

bedrock output.

**Comment by mtliendo** [comment]
ah. I had to check my build settings in esbuild. all good :)

**Comment by mtliendo** [comment]
To help in troubleshooting, I created the following repo: https://github.com/mtliendo/sample-converse

The `converse.cjs` file works and can be ran with `node converse.mjs` so long as the shell environment has the proper AWS credentials configured.

I also created a Lambda function with AWS Amplify located in `amplify/functions/testConverse/resource.ts`. This file uses the adjacent `main.ts` as the handler code. This code is written in TypeScript and transpiled with `esbuild`. When deployed, I get the following error:

```txt
Named export 'ConverseCommand' not found. The requested module '@aws-sdk/client-bedrock-runtime' is a CommonJS module, which may not support all module.exports as named exports.\nCommonJS modules can always be imported via the default export, for example using:\n\nimport pkg from '@aws-sdk/client-bedrock-runtime';\n",
```

To further debug, I created a standard `NodeJSFunction` Lambda using the L2 construct in the CDK. This is located in the `amplify/backend.ts` file (unaffiliated with Amplify). When deployed and tested, I get a related but slightly different error message:

```txt
  "errorMessage": "import_client_bedrock_runtime.ConverseCommand is not a constructor",
```

As shown in the above screenshot, it appears the `commands` folder that is visible in `dist-es`, is not available in `dist-cjs`.

**Comment by DennisTraub** [comment]
I'm not sure why the issue occurs. It looks like your deployment is missing the dependencies.

Check out this repo that manually deploys your example via the AWS CLI: https://github.com/DennisTraub/bedrock-converse-lambda-ts

**Comment by aBurmeseDev** [comment]
Hi everyone - thanks for checking in. 

Based off your comments, it sounds like this reported behavior only occurs in [Lambda provided SDK ](https://docs.aws.amazon.com/lambda/latest/operatorguide/sdks-functions.html)via Amplify since I'm not able to reproduce it with [JavaScript SDK](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/bedrock-runtime/command/ConverseCommand/) itself. 

@mtliendo - do you mind checking if you can run it [with SDK](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/bedrock-runtime/command/ConverseCommand/) but not in Lambda? 

@DennisTraub - I believe the repo you shared isn't reachable, may be private. I'd appreciate if you can share it with us.

**Comment by RanVaknin** [comment]
Hi,

I see that the Converse API operation was only introduced [2 weeks ago](https://github.com/aws/aws-sdk-js-v3/commit/512d901499b7bc31fdddc8372a18339dc9909b15). The Lambda provided SDK is not the latest released SDK (Lambda only updates it roughly twice a year) therefore it would not contain the latest features released via the SDK. 

In order to use the latest features, you'll need to provide the desired SDK version yourself (either with a [Lambda Layer](https://docs.aws.amazon.com/lambda/latest/dg/chapter-layers.html) or with [bundling and minifying](https://aws.amazon.com/blogs/compute/optimizing-node-js-dependencies-in-aws-lambda/) and uploading to Lambda) 

The SDK team does not control which SDK version is vended through lambda, and therefore this is not actionable by our team so I'm going to close this issue.

Thanks for reaching out.
Ran~

**Comment by DennisTraub** [comment]
@aBurmeseDev Oh, my bad. I made it public now. It basically confirms what @RanVaknin already said: It works if you bundle the dependencies into the package.

**Comment by SumiyaE** [comment]
I am encountering the same issue and seeking assistance. I created a Lambda function using the aws-lambda-nodejs module in CDK. In this case, the modules are bundled by default with esbuild, so I understand that the version of the SDK specified in my package.json is used on Lambda. However, like @mtliendo  previously posted, I am encountering the error 
`import_client_bedrock_runtime.ConverseCommand is not a constructor.`

lambda handler code is here 

```ts
import { Handler } from 'aws-lambda';
import {
    BedrockRuntimeClient,
    ConverseCommand, Message,
} from "@aws-sdk/client-bedrock-runtime";

export const handler: Handler = async (event, context) => {
    console.log('EVENT: \n' + JSON.stringify(event, null, 2));
    console.log('hello this is lambda message')
    const client = new BedrockRuntimeClient();
    const modelId = "anthropic.claude-v2:1";
    const userMessage = "please tell me how to use bedrock";

    const conversation:Message[] = [
        {
            role: "user",
            content: [{ text: userMessage }],
        },
    ];
    
    // ------------- here is the problem area. ------------- 
    const command : ConverseCommand = new ConverseCommand({
        modelId,
        messages: conversation,
        inferenceConfig: { maxTokens: 512, temperature: 0.5, topP: 0.9 },
    });

    try {
        // Send the command to the model and wait for the response
        const response = await client.send(command);

        // Extract and print the streamed response text in real-time.
        const responseText = response.output?.message?.content?.[0].text ?? 'No response text available';
    } catch (err) {
        console.log(`ERROR: Can't invoke '${modelId}'. Reason: ${err}`);
    }

};
```


cdk stack code is here 

```ts
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import {NodejsFunction} from "aws-cdk-lib/aws-lambda-nodejs";
import {Architecture, Runtime} from "aws-cdk-lib/aws-lambda";
// import * as sqs from 'aws-cdk-lib/aws-sqs';

export class BedrockTrainStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const lambda =  new NodejsFunction(this, 'BedrockTrainLambda', {
        entry: 'lambda/index.ts',
        handler: 'handler',
        runtime: Runtime.NODEJS_18_X,
        architecture:Architecture.ARM_64,
    })
  }
}

```



How can I resolve this issue?

**Comment by SumiyaE** [comment]
Hi! I wanted to share how I resolved
`import_client_bedrock_runtime.ConverseCommand is not a constructor`  error I posted about earlier.

When creating a Lambda function using the `aws-lambda-nodejs` module with CDK, it indeed seems that esbuild automatically bundles the node_modules.  However, if you specify a runtime other than `NODEJS_LATEST`, esbuild appears to exclude the aws-sdk from the bundle. 

You can refer to the official documentation for more details 
(the relevant section in the README is [here](https://github.com/aws/aws-cdk/tree/main/packages/aws-cdk-lib/aws-lambda-nodejs#working-with-modules), and the related tests are mentioned [here](https://github.com/aws/aws-cdk/blob/3b95777ee5dae32fd41481d81922d07c804a2c6b/packages/aws-cdk-lib/aws-lambda-nodejs/test/bundling.test.ts#L920-L943)).



To address this issue, if you're specifying a runtime other than NODEJS_LATEST, you need to explicitly indicate that there are no modules to exclude from the bundle, like this:

```ts
const lambda = new NodejsFunction(this, 'BedrockTrainLambda', {
    entry: 'lambda/index.ts',
    handler: 'handler',
    runtime: Runtime.NODEJS_20_X,
    architecture: Architecture.ARM_64,
    bundling: {
        externalModules: [], // here
    }
});
```

Alternatively, as I mentioned earlier, specifying NODEJS_LATEST for the runtime also resolves this issue:

```ts
const lambda = new NodejsFunction(this, 'BedrockTrainLambda', {
    entry: 'lambda/index.ts',
    handler: 'handler',
    runtime: Runtime.NODEJS_LATEST,
    architecture: Architecture.ARM_64,
});
```

 believe this solution will also work for @mtliendo's issue.

**Comment by richardvaldivieso** [comment]
I am getting the same error: 

"errorType": "Runtime.UserCodeSyntaxError",
"errorMessage": "SyntaxError: Named export 'ConverseCommand' not found. The requested module '@aws-sdk/client-bedrock-runtime' is a CommonJS module, which may not support all module exports as named exports. CommonJS modules can always be imported via the default export, for example, using import pkg from '@aws-sdk/client-bedrock-runtime'"
If I use require, it will tell me to use import. Do you know why this is happening?

**Comment by aBurmeseDev** [comment]
@richardvaldivieso - are you using Lambda provided SDK? If so, you'll have to provide desired SDK version (either with a [Lambda Layer](https://docs.aws.amazon.com/lambda/latest/dg/chapter-layers.html) or with [bundling and minifying](https://aws.amazon.com/blogs/compute/optimizing-node-js-dependencies-in-aws-lambda/) and uploading to Lambda), as previously mentioned. 

You can also specify your NodeJS runtime as mentioned [in this comment](https://github.com/aws/aws-sdk-js-v3/issues/6188#issuecomment-2184914816). If issue persists, please create a new issue and provide your use case along with minimal steps to reproduce your issue. Thank you!
