### ISSUE TITLE
Error: URL.hostname is not implemented in React Native AWS Textract integration

### ISSUE THREAD

**Issue by ketan-pcs** [aws/aws-sdk-js-v3#6191]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I'm encountering an error while integrating AWS Textract with a React Native application. When attempting to analyze an ID document using the AnalyzeIDCommand from the @aws-sdk/client-textract package, I'm receiving the following error message:
[Error: URL.hostname is not implemented]

### SDK version number

3.592.0

### Which JavaScript Runtime is this issue in?

React Native

### Details of the browser/Node.js/ReactNative version

0.74.1

### Reproduction Steps

[Error: URL.hostname is not implemented]

### Observed Behavior
```ts
 const textRactFunction = async () => {
    if (imageData?.data) {
      const client = new TextractClient({
        region: 'us-east-1',
        credentials: {
          accessKeyId: 'YOUR_ACCESS_KEY_ID',
          secretAccessKey: 'YOUR_SECRET_ACCESS_KEY',
        },
      });

      const blob = Buffer.from(imageData?.data, 'base64');

      const params = {
        DocumentPages: [
          {
            Bytes: blob,
          },
        ],
      };

      const command = new AnalyzeIDCommand(params);

      try {
        const textRactData = await client.send(command);

        // process data.

         console.log(textRactData.IdentityDocuments[0].IdentityDocumentFields);
      } catch (error) {
        console.log('TextractClient err', error);
        // error handling.
      }
    }
  };
```
### Expected Behavior

give a response

**Comment by RanVaknin** [comment]
Hi @ketan-pcs ,

Did you add any polyfills? 

>If you are consuming modular AWS SDK for JavaScript on react-native environments, you will need to add and import following polyfills in your react-native application:
>
>[react-native-get-random-values](https://www.npmjs.com/package/react-native-get-random-values)
[react-native-url-polyfill](https://www.npmjs.com/package/react-native-url-polyfill)
>
>import "react-native-get-random-values";
import "react-native-url-polyfill/auto";

Thanks,
Ran~
