### ISSUE TITLE
RequestTimeTooSkewed due to cached responses.

### ISSUE THREAD

**Issue by lromor** [aws/aws-sdk-js-v3#6202]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

From the browser the s3 client changes the X-Amz-Date based on the Date header.
https://github.com/aws/aws-sdk-js-v3/blob/main/packages/middleware-signing/src/awsAuthMiddleware.ts#L105

Sometimes the responses are cached, and so their Date header. This introduces a drift in the systemClockOffset which eventually turns into the server returning time skew too large errors in successive requests.

### SDK version number

@aws-sdk/client-s3@^3.433.0

### Which JavaScript Runtime is this issue in?

Browser

### Details of the browser/Node.js/ReactNative version

  Browsers:     Chrome: 125.0.6422.142     Safari: 17.5

### Reproduction Steps

Request cacheable content using the "Cache-Control" headers. After a while, the server will return errors as the date of the sever and the client is too skewed.

### Observed Behavior

After a while, X-Amz-Date used during requests is calculated with an offset that is very large. The server then responds with an error RequestTimeTooSkewed.

### Expected Behavior

The client shouldn't try to compute an offset over cached responses.

### Possible Solution

Either adjust the offset on requests that the client is certain are not cached.

**Comment by aBurmeseDev** [comment]
Hi @lromor - thanks for reaching out.

As you're probably aware, this `RequestTimeTooSkewed` error is due to the mismatch between the server time and current time. In order for us to understand your use case better, can you share a minimal repro code?
