### ISSUE TITLE
Example email should be in "Example Name <example@example.com>"

### ISSUE THREAD

**Issue by satyaprakashpatel** [aws/aws-sdk-js-v3#6213]
### Describe the issue

If I am using only email then it is throwing error "InvalidParameterValue" with the message "Invalid email address"

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/ses/command/SendEmailCommand/

**Comment by aBurmeseDev** [comment]
Hi @satyaprakashpatel - can you share your code that would give us more insight into the reported behavior? Can you also elaborate on your title as which part of documentation you're referring to?
>"Example email should be in "Example Name <example@example.com>"
