### ISSUE TITLE
Expose HTTP response headers in websocket upgrade request 

### ISSUE THREAD

**Issue by esauerbo** [aws/aws-sdk-js-v3#6221]
### Describe the feature

It would be helpful to have access to the response headers in the initial http upgrade request for a websocket connection. We are specifically looking to access the date. From the below screenshots you can see the headers in the network tab but not when logging the response. 

![Screenshot 2024-06-13 at 10 04 49 AM](https://github.com/aws/aws-sdk-js-v3/assets/70536670/18979361-c5b6-4d5b-bbb5-9e9cd10179ec)
![Screenshot 2024-06-13 at 10 05 01 AM](https://github.com/aws/aws-sdk-js-v3/assets/70536670/b210fc08-adb1-4eb8-b1df-314eb6710179)

### Use Case

The Amplify UI Face Liveness Detector provides a UI component for Amazon Rekognition Face Liveness using the `client-rekognitionstreaming` package. Some customers are getting Invalid Signature Exceptions due to clock skew issues. 

We want to fix this by catching these exceptions and attempting to restart the session with a systemClockOffset that's the difference between device and server time. This has been [implemented](https://github.com/aws-amplify/amplify-android/pull/2615) on the android liveness component, but currently isn't possible in web because we cannot access the http upgrade headers. 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

V3

### Environment details (OS name and version, etc.)

any

**Comment by kuhe** [comment]
there doesn't seem to be a way to retrieve upgrade response headers in a browser using the `WebSocket` class.
