### ISSUE TITLE
Extend compatibility with `readable-stream` module in `@aws-sdk/lib-storage`

### ISSUE THREAD

**Issue by giovanni-bertoncelli** [aws/aws-sdk-js-v3#6229]
### Describe the feature

As described in [this issue](https://github.com/mcollina/cloneable-readable/issues/46) I'm using this library to clone a stream. Considering the popularity of `readable-stream` is there any chance to support compatibility with that library?

### Use Case

Every time a user is using `readable-stream`.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.554.0

### Environment details (OS name and version, etc.)

MacOS Sonoma 14.5

**Comment by jedwards1211** [comment]
I brought this kind of thing up in https://github.com/aws/aws-sdk-js-v3/issues/6153

**Comment by aBurmeseDev** [comment]
Hi @giovanni-bertoncelli - this has been queued for the team to take a further look at and potentially add the support as mentioned by @jedwards1211. We cannot, however, provide definite timeline on that. Meanwhile, I understand that there's a workaround provided in other issue you linked, I'll leave it here for reference for anyone that comes across this.

```
const stream = pipeline(clone, new PassThrough(), () => {})
```

Closing this in favor of https://github.com/aws/aws-sdk-js-v3/issues/6153.
