### ISSUE TITLE
Cannot convert object to primitive value

### ISSUE THREAD

**Issue by cosbgn** [aws/aws-sdk-js-v3#6248]
### Checkboxes for prior research

- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Can't initialize the SDK in cloudflare workers. Locally it works.

### SDK version number

"@aws-sdk/client-s3": "^3.608.0"

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

cloudflare workers

### Reproduction Steps

```
import { S3Client } from "@aws-sdk/client-s3";

const s3Client = new S3Client({
        region: "auto",
        endpoint: `https://${process.env.CLOUDFLARE_ACCOUNT_ID}.r2.cloudflarestorage.com`,
        credentials: {
            accessKeyId: process.env.CLOUDFLARE_R2_BUCKET_ACCESS_KEY_ID,
            secretAccessKey: process.env.CLOUDFLARE_R2_BUCKET_SECRET_KEY_ID,
        },
})

```
This fails with: `Cannot convert object to primitive value`.

### Observed Behavior

This works on localhost but fails when deployed (cloudflare workers)

### Expected Behavior

it works

**Comment by aBurmeseDev** [comment]
Hi @cosbgn - thanks for reaching out.

Can you share the full error and your SDK that would give us some insight into this behavior? Based on the report, my guess on the culprit is the endpoint value. 

Since you mentioned this works on localhost and fails when deployed with Cloudflare workers, please note AWS does not guarantee support for 3rd party offerings like Cloudflare Workers. AWS supports Lambda as a serverless offering.

**Comment by rahulkumarsingh73690** [comment]
@cosbgn You got any solution?

**Comment by cosbgn** [comment]
Yes, the issue is caused by unenv here I made a small reproduction: https://github.com/unjs/unenv/issues/279 
I guess this falls out of scope for S3 so I'll close this issue and leave the one on unenv open

**Comment by pi0** [comment]
Update: https://github.com/unjs/unenv/issues/279#issuecomment-2231505068
