### ISSUE TITLE
client-transcribe-streaming StartStreamTranscriptionCommand got ERR_HTTP2_HEADER_SINGLE_VALUE error

### ISSUE THREAD

**Issue by MirandaDora** [aws/aws-sdk-js-v3#6254]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Hi, I have copy pasted the streaming code from https://docs.aws.amazon.com/transcribe/latest/dg/getting-started-sdk.html 
And when executing the code, I've got the following error:
```
An error was encountered in a non-retryable streaming request.
node:internal/http2/util:633
        throw new ERR_HTTP2_HEADER_SINGLE_VALUE(key);
              ^

TypeError [ERR_HTTP2_HEADER_SINGLE_VALUE]: Header field "content-type" must only have a single value
    at mapToHeaders (node:internal/http2/util:633:15)
    at ClientHttp2Session.request (node:internal/http2/core:1813:25)
    at /Users/miranli/Projects/jam/simultaneous-interpretation-jam/node_modules/@smithy/node-http-handler/dist-cjs/index.js:588:27
    at new Promise (<anonymous>)
    at _NodeHttp2Handler.handle (/Users/miranli/Projects/jam/simultaneous-interpretation-jam/node_modules/@smithy/node-http-handler/dist-cjs/index.js:541:12)
    at async /Users/miranli/Projects/jam/simultaneous-interpretation-jam/node_modules/@smithy/middleware-serde/dist-cjs/index.js:33:24
    at async _EventStreamPayloadHandler.handle (/Users/miranli/Projects/jam/simultaneous-interpretation-jam/node_modules/@aws-sdk/eventstream-handler-node/dist-cjs/index.js:110:16) {
  code: 'ERR_HTTP2_HEADER_SINGLE_VALUE'
}

Node.js v20.15.0
```
I have tried to execute the batch code, it's working. Only this one got issue.
"@aws-sdk/client-transcribe": "^3.609.0",
"@aws-sdk/client-transcribe-streaming": "^3.609.0",

### SDK version number

@aws-sdk/package-name@version, ...

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node.js v20.15.0

### Reproduction Steps

Create a clean nodejs project, put the code from "streaming" section for javascript in this document: https://docs.aws.amazon.com/transcribe/latest/dg/getting-started-sdk.html 
And execute

### Observed Behavior

As described

### Expected Behavior

It should start to stream the audio file

**Comment by haochunchang** [comment]
I have encountered the same issue yesterday.
For my use case, I commented out the following line (in dist-cjs/index.js) and my request starts working:

https://github.com/aws/aws-sdk-js-v3/blob/0b87b64a0290d3aaa4dd9753eab8be66c2598c97/clients/client-transcribe-streaming/src/protocols/Aws_restJson1.ts#L147

Hopefully this workaround can help. 

Another clue is that the request headers, I found out it already has: `'Content-Type': 'application/vnd.amazon.eventstream’`.
But I do not know how to fix this yet.

**Comment by MirandaDora** [comment]
Hi @haochunchang -- thanks sooo much for this. Your workaround is working for me.
However, I would still prefer to get this fixed as this is in node_modules and ideally we won't need to change code in the library itself. Let's keep this one open and make sure it catches AWS folks' eyes.

Again, thanks heaps!!

**Comment by aBurmeseDev** [comment]
HI @MirandaDora - thanks for reaching out and apology for the inconvenience.

I was able to reproduce the reported behavior and also confirm the workaround mentioned by @haochunchang . I'll bring it up to the team to further discuss and investigate the issue.

**Comment by kuhe** [comment]
The release of this PR's changeset later today should fix this issue: https://github.com/aws/aws-sdk-js-v3/pull/6259

**Comment by aBurmeseDev** [comment]
Hi everyone - this was addressed in PR https://github.com/aws/aws-sdk-js-v3/pull/6259 which has now been merged and released. Please update to the version [`v3.613.0`](https://github.com/aws/aws-sdk-js-v3/blob/main/CHANGELOG.md#36130-2024-07-09) and let us know if you have any other concerns. Thank you again for reporting.

cc: @MirandaDora, @haochunchang, @kimmoeklund
