### ISSUE TITLE
S3/DDB Connection timing out / Socket timing out

### ISSUE THREAD

**Issue by randomhash** [aws/aws-sdk-js-v3#6263]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

TimeoutError: Connection timed out after 5000 ms
    at ClientRequest.<anonymous> (path/to/handler:142541:26)
    at Object.onceWrapper (node:events:633:28)
    at ClientRequest.emit (node:events:519:28)
    at TLSSocket.emitRequestTimeout (node:_http_client:845:9)
    at Object.onceWrapper (node:events:633:28)
    at TLSSocket.emit (node:events:531:35)
    at Socket._onTimeout (node:net:590:8)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
    
    
   ```
const httpHandlerWithRetry = (options) => {
    const handler = new NodeHttpHandler(options);
    const retryHandler = async (request, options) => {
        for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
            try {
                return await handler.handle(request, options);
            }
            catch (error) {
                if ((error.name === 'TimeoutError' || error.code === 'ECONNRESET') &&
                    attempt < MAX_RETRIES) {
                    continue;
                }
                logger.error(`Failed to make request after ${MAX_RETRIES} attempts`, error);
                throw error;
            }
        }
        throw new Error('Impossible case reached');
    };
    return {
        ...handler,
        handle: retryHandler,
        destroy: handler.destroy,
        updateHttpClientConfig: handler.updateHttpClientConfig,
    };
};
const s3download = new S3({
    region: process.env.AWS_REGION,
    logger,
    forcePathStyle: true,
    requestHandler: httpHandlerWithRetry({
        httpsAgent: new Agent({
            timeout: Number(process.env.DW_S3_TM ?? 5000),
            maxSockets: 1000,
            // keepAlive is a default from AWS SDK. We want to preserve this for
            // performance reasons.
            keepAlive: process.env.DW_S3_KA_DISABLE ? false : true,
            keepAliveMsecs: Number(process.env.DW_S3_KA ?? 1000), // default unset,
        }),
        connectionTimeout: Number(process.env.DW_S3_CN_TM ?? 1000),
        requestTimeout: Number(process.env.DW_S3_RQ_TM ?? 5000), // default 0
    }),
    retryStrategy,
});
```
Alot of s3 requests to s3 in  lambda

Tried to set requestTimeout back to 0
Tried to set keepAlive to false
Nothing seems to help

  

### SDK version number

latest

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

20x 

### Reproduction Steps

```
await pMap(
    itemKeys,
    async itemS3Key => {
        const {Body} = await s3download.getObject({Bucket, Key});
        const bytes = await Body!.transformToByteArray();
        return Buffer.from(bytes);
    },
    {concurrency: 10}
  );


### Observed Behavior

Socket timing out /  Connection timeout

### Expected Behavior

Should be able to download an unlimited amount of files 

### Possible Solution

_No response_

### Additional Information/Context

_No response_

**Comment by randomhash** [comment]
Same errors are happening with usage of the native smithy handler

**Comment by randomhash** [comment]
same error happening as of now also with dynamodb client

**Comment by aBurmeseDev** [comment]
Hi @randomhash - thanks for reaching out. Can you please provide a minimal reproducible code? Does it occur repeatedly or intermittently? We've checked to see if there's any known bug reports with s3 GetObject and attempted to reproduce but was unable to. Any detailed steps to replicate your workflow would help us understand the issue better.
