### ISSUE TITLE
Allow customizable credential provider chain

### ISSUE THREAD

**Issue by mxxk** [aws/aws-sdk-js-v3#6272]
### Describe the feature

Provide a construct to allow users of the AWS SDK for JavaScript v3 to express a chain of credential providers. An example of this is the [`@aws-sdk/credential-provider-node`](https://github.com/aws/aws-sdk-js-v3/tree/v3.614.0/packages/credential-provider-node) provider, but its chain of credentials is not customizable. This was possible in v2 using [`CredentialProviderChain`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CredentialProviderChain.html), but there is no equivalent v3.

### Use Case

Here are some example use cases which are not currently supported due to lack of custom composition of credential providers:

- **Credential provider exclusion.** There is no way to remove specific credential providers from the chain for security purposes. For example, if credentials should only be sourced from ECS container metadata or a file, but not from environment variables, there is no way to chain only those two credential providers.
- **Custom credential providers.** If there is a custom credential providers, there is no way to compose it into a chain of other credential providers.

### Proposed Solution

Since `@aws-sdk/credential-provider-node` relies on `chain` to compose multiple credential providers,

https://github.com/aws/aws-sdk-js-v3/blob/794a37e9795f390d15c9530209e465d099716c86/packages/credential-provider-node/src/defaultProvider.ts#L58-L60

one possible way forward might be to expose [`chain`](https://github.com/smithy-lang/smithy-typescript/blob/%40smithy/property-provider%403.1.3/packages/property-provider/src/chain.ts) (and possibly [`memoize`](https://github.com/smithy-lang/smithy-typescript/blob/%40smithy/property-provider%403.1.3/packages/property-provider/src/memoize.ts)) for public consumption. Both currently belong to `@smithy/property-provider`, an internal package.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.614.0

### Environment details (OS name and version, etc.)

macOS 14.5

**Comment by kuhe** [comment]
You can use promises to create a credential chain.

```ts
import { fromEnv, fromSSO, fromIni, fromHttp } from "@aws-sdk/credential-providers";

const myCredentialProvider = async () => ({ secretAccessKey, ... })

new AWSSDKClient({
  credentials: () => 
    fromEnv()()
      .catch(fromSSO())
      .catch(fromHttp())
      .catch(fromIni())
      .catch(myCredentialProvider)
});
```

**Comment by mxxk** [comment]
Thanks @kuhe, if this is the best way, I can explore it further. One discrepancy I noticed right off the bat is that the `.catch()` in your example will catch _all_ promise rejections, but [`chain` only proceeds to the next provider if `err?.tryNextLink` property is set](https://github.com/smithy-lang/smithy-typescript/blob/d952a6a9d6a436b79f6174fcee9e4fbed82ca841/packages/property-provider/src/chain.ts#L30-L32):

> ```js
> try {
>   const credentials = await provider();
>   return credentials;
> } catch (err) {
>   lastProviderError = err;
>   if (err?.tryNextLink) {
>     continue;
>   }
>   throw err;
> }
> ```

Of course, this consideration can be rolled into a similar helper to `chain`, but wanted to call it out.

**Comment by zshzbh** [comment]
Hey @mxxk, 

This `tryNextLink` is specifically for the error handling. Please refer to [this part of code/comment](https://github.com/smithy-lang/smithy-typescript/blob/86862eab5e8b26520a2a3e9914d24a9ab5a98270/packages/property-provider/src/ProviderError.ts#L12)

If a provider in the chain is rejected with an error, the chain will only proceed to the next provider if the value of the `tryNextLink` property on the error is truthy. This allows individual providers to halt the chain and also ensures the chain will stop if an entirely unexpected error is encountered.

It seems that you want us to export it, this was discussed by the team and the feature won’t be considered at this time unfortunately. I'd suggest to try the solution that @kuhe posted. And please don't hesitate to let us know if you have any questions!

Thanks!
Maggie

**Comment by mxxk** [comment]
@zshzbh yep, that makes sense. Let me summarize your recommendation for this issue...

In order to create a custom credential provider chain, developers using AWS SDK for JavaScript v3 can implement a helper like the following:

```js
function chainCredentialProviders(providers) {
  return async function getCredentials() {
    for (const provider of providers) {
      try {
        return await provider();
      } catch (error) {
        if (!error?.tryNextLink) {
          throw error;
        }
      }
    }
  };
}
```

This helper can be used as follows:

```js
const myCustomCredentialProvider = async () => ({ secretAccessKey, ... });

const s3Client = new S3Client({
  region: "us-west-2",
  credentials: chainCredentialProviders([
    fromSSO(),
    fromHttp(),
    fromIni(),
    myCustomCredentialProvider,
  ]),
});
```

Since there is no additional action here, I can close this issue as "not planned", and hope the workaround documented here can help future readers.
