### ISSUE TITLE
marshallInput and unmarshallOutput are missing from the CJS distribution of lib-dynamodb

### ISSUE THREAD

**Issue by sawilde** [aws/aws-sdk-js-v3#6276]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

`marshallInput` and `unmarshallOutput` are missing from the `CJS` distribution of `lib-dynamodb`

These functions are described in `types` and are exported in the `ES` distribution but are not exported in the `CJS` distribution.

Walking the packages this seems to have happened starting with build `3.495.0` when the generated utils.js started to only export from its local `index.js` file but the above functions were not included in that file.

I number of Open Source packages depend on this function e.g. [electrodb](https://github.com/tywalch/electrodb)

### SDK version number

@aws-sdk/lib-dynamodb@3.395.0, ...

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.18.2 and others

### Reproduction Steps

1. install @aws-sdk/lib-dynamodb@3.394.0 (see exports in `dist-cjs/commands/utils.js` compare with `dist-es\...`)
2. install @aws-sdk/lib-dynamodb@3.395.0 (see exports in `dist-cjs/commands/utils.js` compare with `dist-es\...`)

### Observed Behavior

Cannot import `marshallInput` or `unmarshallOutput`

### Expected Behavior

Should be able to import `marshallInput` or `unmarshallOutput`

### Possible Solution

Export the two functions in the CJS distribution

**Comment by kuhe** [comment]
This is a private API of the AWS SDK.

Based on the usage observed in electrodb, it can be replaced like this:

```ts
// unmarshallOutput is internal/private

if (reason.Item) {
  return unmarshallOutput(reason, [{ key: "Item" }]);
}
```

to:

```ts
import { unmarshall } from "@aws-sdk/util-dynamodb";

if (reason.Item) {
  return unmarshall(reason.Item);
}
```

**Comment by sawilde** [comment]
@kuhe if that is the case should we hide these internal methods from the `types` and `es` distributions?

**Comment by kuhe** [comment]
No. 

> @kuhe if that is the case should we hide these internal methods from the `types` and `es` distributions?

No, due to the modularity of npm packages and the nature of JavaScript, 'twas almost futile to control the accessible interface until the advent of package.json export metadata, which didn't exist at initial authoring. 

These functions were not exported at the top level of the package, marked with the `@internal` tsdoc annotation, and don't appear in API reference documentation. That is how we generally indicate things as private.

We have a PR open to export the private API. But it will not be supported in the future. The correct usage is in the previous comment example.

**Comment by RanVaknin** [comment]
Hi @sawilde ,

After further discussions with the team we have decided not to expose these.
Please use the workaround provided in https://github.com/aws/aws-sdk-js-v3/issues/6276#issuecomment-2229346158.

Thanks,
Ran~

**Comment by sawilde** [comment]
The proposed fix doesn't work - to make the tests continue working I needed to make a copy `unmarshallOutput`. 

`unmarshallOutput` does more than call `unmashall` it seems.
