### ISSUE TITLE
aws-sdk/client-kinesis consuming too much memory under load

### ISSUE THREAD

**Issue by Guru3101** [aws/aws-sdk-js-v3#6292]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

In one of our app we are using kinesis to push our platform feeds to Kinesis , under some load (3000 to 3500 requests/min max) the heap consumption spikes gradually  heavily and app is getting crashed . we took the heapdump when memory is spiking and looks like the kinesis sdk is not flushing the ClientRequest Object and holding it in the memory at least when big volume comes in, attaching the heap screenshot for reference 

![HEAP](https://github.com/user-attachments/assets/3aa876c8-d33d-45f6-bdef-8c4d3d010223)

13K such ClientRequest Object are sitting in the memory when we took heap dump and here is one such memory spike of our container

![MEMEORYUSAGE](https://github.com/user-attachments/assets/f8bf002c-d758-45df-9917-4aaab4131d9d)

Here is quick snippets of our script
```js
const { KinesisClient, PutRecordCommand} = require(@aws-sdk/client-kinesis);
const { NodeHttpHandler } = require("@smithy/node-http-handler");
const https = require('https');

//Initialization
let kinesis = new KinesisClient({
    region: 'us-east-1',
    retryMode: 'standard',
    requestHandler: new NodeHttpHandler({
        httpsAgent: new https.Agent({
            keepAlive:true,
            maxSockets: 200
        })
    })
})

//pushing to kinesis
await kinesis.send(new PutRecordCommand(params));
```
 this app consumes the feeds at the rate of ~100req/sec from Kafka and pushes to kinesis so to match that i added a http agent with max socket value as 200 and keepalive as true to reuse connection.

### SDK version number

@aws-sdk/client-kinesis@3.606.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node v18.20.4

### Reproduction Steps
```js
const { KinesisClient, PutRecordCommand} = require(@aws-sdk/client-kinesis);
const { NodeHttpHandler } = require("@smithy/node-http-handler");
const https = require('https');

//Initialization
let kinesis = new KinesisClient({
    region: 'us-east-1',
    retryMode: 'standard',
    requestHandler: new NodeHttpHandler({
        httpsAgent: new https.Agent({
            keepAlive:true,
            maxSockets: 200
        })
    })
})

//pushing to kinesis
await kinesis.send(new PutRecordCommand(params));
```
### Observed Behavior

App crashes due to heavy heap usage

under some load (3000 to 3500 requests/min max) the heap consumption spikes gradually  heavily and app is getting crashed . we took the heapdump when memory is spiking and looks like the kinesis sdk is not flushing the ClientRequest Object and holding it in the memory at least when big volume comes in, attaching the heap screenshot for reference 

![HEAP](https://github.com/user-attachments/assets/3aa876c8-d33d-45f6-bdef-8c4d3d010223)

13K such ClientRequest Object are sitting in the memory when we took heap dump and here is one such memory spike of our container

![MEMEORYUSAGE](https://github.com/user-attachments/assets/f8bf002c-d758-45df-9917-4aaab4131d9d)

Here is quick snippets of our script
```js
const { KinesisClient, PutRecordCommand} = require(@aws-sdk/client-kinesis);
const { NodeHttpHandler } = require("@smithy/node-http-handler");
const https = require('https');

//Initialization
let kinesis = new KinesisClient({
    region: 'us-east-1',
    retryMode: 'standard',
    requestHandler: new NodeHttpHandler({
        httpsAgent: new https.Agent({
            keepAlive:true,
            maxSockets: 200
        })
    })
})

//pushing to kinesis
await kinesis.send(new PutRecordCommand(params));
```
 this app consumes the feeds at the rate of ~100req/sec from Kafka and pushes to kinesis so to match that i added a http agent with max socket value as 200 and keepalive as true to reuse connection.

### Expected Behavior

Memory consumption to be stable

**Comment by aBurmeseDev** [comment]
Hi @Guru3101 - thanks for reaching out. I apologize for the inconvenience you're experiencing.

To better understand and troubleshoot the problem, it would be helpful if you could provide us with more details about your environment and workflow. Specifically, please share the following information:

- Are you running your application on AWS Lambda?
- Could you describe your workflow involving Apache Kafka?
- Is this issue occurring continuously, or does it happen intermittently?

Having a clear understanding of your setup and the frequency of the issue will greatly assist us in diagnosing the root cause and providing an effective solution. Please provide as much relevant information as possible to help us investigate further.
