### ISSUE TITLE
Error: NodejsNpmBuilder:CopySource - [Errno 2] No such file or directory: DescribeLocalGatewayRouteTableVirtualInterfaceGroupAssociationsPaginator.js

### ISSUE THREAD

**Issue by iDcodes** [aws/aws-sdk-js-v3#6320]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I am getting this error during sam build executed.

> sam build
Starting Build use cache
Building codeuri: \src runtime: nodejs20.x metadata: {}
architecture: x86_64 functions: lambdafunction
package.json file not found. Continuing the build without dependencies.
 Running NodejsNpmBuilder:CopySource

> Build Failed
Error: NodejsNpmBuilder:CopySource - [Errno 2] No such file or directory: 'C:\\lambdafunction\\.aws-sam\\build\\lambdafunction\\node_modules\\@aws-sdk\\client-ec2\\dist-es\\pagination\\DescribeLocalGatewayRouteTableVirtualInterfaceGroupAssociationsPaginator.js'

But I can locate the file directory of the said error. Tried to research and look for other issue that the same as mine but couldn't found. I even tried to exclude modules by follow the steps here: https://stackoverflow.com/questions/55199370/how-to-exclude-modules-using-aws-sam-build-for-nodejs but the error still persists.

### SDK version number

@aws-sdk/client-ec2

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v14.21.3

### Reproduction Steps

In my app.mjs:

```
import { EC2Client, DescribeInstancesCommand } from "@aws-sdk/client-ec2";
export const handler = async (event) => { 
  const client = new EC2Client({ region: 'ap-southeast-2'})
  const command = new DescribeInstancesCommand(params);
  ...my code goes here
})
```

### Observed Behavior

Error: NodejsNpmBuilder:CopySource - [Errno 2] No such file or directory: 'C:\\lambdafunction\\.aws-sam\\build\\lambdafunction\\node_modules\\@aws-sdk\\client-ec2\\dist-es\\pagination\\DescribeLocalGatewayRouteTableVirtualInterfaceGroupAssociationsPaginator.js'

### Expected Behavior

sam build should complete without an error.

**Comment by zshzbh** [comment]
Hey @iDcodes ,

We announced the [end of support for Node.js 14.x in the AWS SDK for JavaScript (v3)](https://aws.amazon.com/blogs/developer/announcing-the-end-of-support-for-node-js-14-x-in-the-aws-sdk-for-javascript-v3/). Starting May 1, 2024, the [AWS SDK for JavaScript (v3)](https://github.com/aws/aws-sdk-js-v3/) will no longer actively support Node.js 14.x, which reached [end-of-life](https://github.com/nodejs/Release/pull/859) on April 30, 2023. It seems that you used Node v14.21.3 , I'd recommend to upgrade to a newer version of Node and try again.  

If the issue persists, please let us know! 

Thanks! 
Maggie
