### ISSUE TITLE
fast-xml-parser dependency has a vulnerability

### ISSUE THREAD

**Issue by Jish2** [aws/aws-sdk-js-v3#6327]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

```sh
$ yarn audit --groups dependencies
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ fast-xml-parser vulnerable to ReDOS at currency parsing      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ fast-xml-parser                                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.4.1                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @aws-sdk/client-lambda                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @aws-sdk/client-lambda > @aws-sdk/core > fast-xml-parser     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1098305                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

### SDK version number

@aws-sdk/core@3.620.1

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

all

### Reproduction Steps

Run `npm audit`

### Observed Behavior

vulnerability present

### Expected Behavior

no vulnerability present

### Possible Solution

bump `fast-xml-parser` to patched version `4.4.1`

### Additional Information/Context

https://www.npmjs.com/advisories/1098305

**Comment by knixeur** [comment]
Fixed by https://github.com/aws/aws-sdk-js-v3/pull/6326

**Comment by trivikr** [comment]
The new version https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.621.0 with updated version of fast-xml-parser is expected to release around 12:30 PM Pacific today (Tue, July 30th)
