### ISSUE TITLE
Recent fast-xml-parser vulnerability now shows dozens of high severity vulnerabilities during `npm install`

### ISSUE THREAD

**Issue by purplepenguin42** [aws/aws-sdk-js-v3#6331]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Related:
* https://github.com/advisories/GHSA-mpg4-rc92-vx8v
* https://github.com/aws/aws-sdk-js-v3/issues/6327

When running an `npm install` with latest versions of things like `@aws-sdk/client-dynamodb`, `@aws-sdk/client-kms`, `@aws-sdk/client-lambda`, etc. you are now greeted with a bold red text about 18 high severity vulnerabilities.  I'm using the latest (i.e. published a few hours ago versions), and npm is still showing the warnings.

Is there a timeline when the rest of the ecosystem will be updated? Previously (e.g. yesterday), the same install resulted in 0 warnings.

### SDK version number

@aws-sdk/client-dynamodb@3.620.1

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v22.5.1

### Reproduction Steps

Run `npm install` with any of the modular SDK packages on the latest version.

### Observed Behavior

A bunch of high severity vulnerability warnings.

### Expected Behavior

No warnings.

**Comment by purplepenguin42** [comment]
Ignore the exact number (18), it'll vary depending on which modules you're installing.

```sh
$ npm install @aws-sdk/client-kms@3.620.1

added 90 packages, and audited 91 packages in 1s

2 packages are looking for funding
  run `npm fund` for details

13 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

**Comment by kiarash-malekzadeh** [comment]
Having the same issue with our: 
- **@aws-sdk/client-s3**
- **@aws-sdk/client-sts**
Updating to latest versions did not help since the **fast-xml-parser** version is still **4.2.5** which needs to be upgraded to **4.4.1**

**Comment by seriousme** [comment]
See https://github.com/aws/aws-sdk-js-v3/pull/6330

**Comment by rlsf** [comment]
@seriousme is there a timeline for a release of fixed version?

**Comment by seriousme** [comment]
I don't know, I don't work for Amazon.
I only found the PR and I thought it might help linking it here.

**Comment by rlsf** [comment]
@trivikr is there a timeline for a release of fixed version?

**Comment by FarhanHossain00** [comment]
I'm also having a dozen of vulnerabilities'
Will install @aws-sdk/client-s3@3.529.0, which is a breaking change
node_modules/fast-xml-parser
  @aws-sdk/core  >=3.529.1
  Depends on vulnerable versions of fast-xml-parser
  node_modules/@aws-sdk/core
    @aws-sdk/client-s3  >=3.529.1
    Depends on vulnerable versions of @aws-sdk/client-sso-oidc
    Depends on vulnerable versions of @aws-sdk/client-sts
    Depends on vulnerable versions of @aws-sdk/core
    Depends on vulnerable versions of @aws-sdk/credential-provider-node
    node_modules/@aws-sdk/client-s3
    @aws-sdk/client-sso  >=3.529.1
    Depends on vulnerable versions of @aws-sdk/core
    node_modules/@aws-sdk/client-sso
      @aws-sdk/credential-provider-sso  >=3.529.1
      Depends on vulnerable versions of @aws-sdk/client-sso
      Depends on vulnerable versions of @aws-sdk/token-providers
      node_modules/@aws-sdk/credential-provider-sso
        @aws-sdk/credential-provider-node  >=3.529.1
        Depends on vulnerable versions of @aws-sdk/credential-provider-ini
        Depends on vulnerable versions of @aws-sdk/credential-provider-sso
        Depends on vulnerable versions of @aws-sdk/credential-provider-web-identity
        node_modules/@aws-sdk/credential-provider-node
    @aws-sdk/client-sso-oidc  >=3.529.1
    Depends on vulnerable versions of @aws-sdk/client-sts
    Depends on vulnerable versions of @aws-sdk/core
    Depends on vulnerable versions of @aws-sdk/credential-provider-node
    node_modules/@aws-sdk/client-sso-oidc
      @aws-sdk/client-sts  >=3.529.1
      Depends on vulnerable versions of @aws-sdk/client-sso-oidc
      Depends on vulnerable versions of @aws-sdk/core
      Depends on vulnerable versions of @aws-sdk/credential-provider-node
      node_modules/@aws-sdk/client-sts
        @aws-sdk/credential-provider-ini  >=3.529.1
        Depends on vulnerable versions of @aws-sdk/client-sts
        Depends on vulnerable versions of @aws-sdk/credential-provider-sso
        Depends on vulnerable versions of @aws-sdk/credential-provider-web-identity
        node_modules/@aws-sdk/credential-provider-ini
        @aws-sdk/credential-provider-web-identity  >=3.529.1
        Depends on vulnerable versions of @aws-sdk/client-sts
        node_modules/@aws-sdk/credential-provider-web-identity
      @aws-sdk/token-providers  >=3.529.1
      Depends on vulnerable versions of @aws-sdk/client-sso-oidc
      node_modules/@aws-sdk/token-providers

**Comment by trivikr** [comment]
> is there a timeline for a release of fixed version?

The new version https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.621.0 with updated version of fast-xml-parser is expected to release around 12:30 PM Pacific today (Tue, July 30th)

**Comment by xfournet** [comment]
@trivikr thanks! Quick question, why do you pin the dependencies version in @aws-sdk packages ? It prevent to fix the issue by ourself.

**Comment by surecloud-Awalia** [comment]
Do you know if this fix also be released simultaneously for sdk v2 ?

**Comment by trivikr** [comment]
> Do you know if this fix also be released simultaneously for sdk v2 ?

The AWS SDK for JavaScript (v2) does NOT have a direct/transient dependency on fast-xml-parser

It can be verified by installing the SDK in a new folder as follows:
```console
$ test-deps> npm init -y

$ test-deps> npm install aws-sdk

$ test-deps> npm why aws-sdk
aws-sdk@2.1664.0
node_modules/aws-sdk
  aws-sdk@"^2.1664.0" from the root project

$ test-deps> npm why fast-xml-parser
```

**Comment by Ardakilic** [comment]
We encountered this on our project today.

Somehow 3.620.1 did not fix for us, so we had to use `overrides` section temporarily on our `package.json`:

```json
"overrides": {
    "@aws-sdk/client-s3": {
        "fast-xml-parser": "4.4.1",
        "@aws-sdk/client-sts": {
            "fast-xml-parser": "4.4.1"
        }
    }
},
```

**Comment by trivikr** [comment]
> Somehow 3.620.1 did not fix for us

The fix is going to be published in `v3.621.0`

Details in prior comment https://github.com/aws/aws-sdk-js-v3/issues/6331#issuecomment-2258351666

**Comment by purplepenguin42** [comment]
@trivikr 

> We pin third-party dependencies in `@aws-sdk` packages, so that your AWS applications do not break by some bad version update in a package that we don't maintain.

This isn't how pinning works, mainly because you can't actually pin a dependency tree. You're pinning the top-level dependencies, but all of the transitive dependencies still freely update based on semver ranges.  The reality is the current design is basically the worst of both worlds, you still aren't pinning most of the SDK's actual dependencies but you are pinning a handful, which makes it impossible for these issues to simply be non-issues by letting consumers run a fresh install.

**Comment by trivikr** [comment]
> mainly because you can't actually pin a dependency tree

@purplepenguin42 I tried my best to explain the issue in a concise way in the comment https://github.com/aws/aws-sdk-js-v3/issues/6331#issuecomment-2258446110 providing specific examples on how failures can happen in both cases, and the cost of fixing them. I also didn't use some any analogy to put it in another way.

Can you create a [feature request](https://github.com/aws/aws-sdk-js-v3/issues/new?assignees=&labels=feature-request%2Cneeds-triage&projects=&template=feature-request.yml&title=%28short+issue+description%29) and provide a minimal repro on how a bad update in third-party dependency, like `fast-xml-parser` will not instantly break applications without lockfiles as soon as they run new install step. I can go through your example, and provide a counter example, if needed.

That way, we keep this issue specific to fast-xml-parser@4.4.1 update, and not digress.

**Comment by purplepenguin42** [comment]
@trivikr 

What I'm trying to get across is you aren't doing what you actually think you are doing. Yes, you can pin `fast-xml-parser` to a specific version, but that does absolutely nothing for all the rest of the SDK's dependencies that aren't top-level dependencies.

For example, `fast-xml-parser` has a dependency on `strnum`.  Despite you pinning `fast-xml-parser`, `strnum` will still pull in the latest updates regardless.  If `strnum` releases a bad update, guess what? You're still in the exact same boat.

The point I'm trying to make is pinning `fast-xml-parser` only affects bad updates specifically in `fast-xml-parser` (or whatever other top-level dependencies), it has no effect whatsoever on transitive dependencies, which make up the bulk of the SDK's total footprint.  You can only pin an individual package declared in your own `package.json`, all dependencies under that still freely float and pull whatever version satisfies semver.  You fundamentally cannot pin a full dependency tree, but you seem to believe the current design is doing just that, which is simply incorrect and potentially dangerous.

tl;dr - you pinning a handful of dependencies does more harm than good; you are only preventing "bad updates" to a tiny percentage of the SDK's overall dependencies, while at the same time preventing people from easily using the latest versions, and instead forcing users to rely on manual releases from the SDK in situations like this.

Regardless, I won't comment any further on this thread.  Feel free to make another tracking issue, but it doesn't appear the SDK team actually understands how their own system currently works, which is a bit scary.

**Comment by NabilFurmoli** [comment]
@trivikr Any updates, the new version @3.621.0 still has not been released yet. Its 1:03 PM PST.

**Comment by trivikr** [comment]
The [@aws-sdk/client-s3@3.621.0](https://www.npmjs.com/package/@aws-sdk/client-s3/v/3.621.0) was published at 12:19 PM Pacific

```console
$ npm view @aws-sdk/client-s3 time --json | grep 3.621.0
  "3.621.0": "2024-07-30T19:19:32.730Z"
```

I verified that it includes `fast-xml-parser@4.4.1` as follows:
```console
$ test-deps> npm init -y

$ test-deps> npm install @aws-sdk/client-s3@3.621.0 --save-exact

$ test-deps> npm why fast-xml-parser | grep fast-xml-parser
fast-xml-parser@4.4.1
node_modules/fast-xml-parser
  fast-xml-parser@"4.4.1" from @aws-sdk/core@3.621.0
```

**Comment by Ardakilic** [comment]
Hello, can confirm 3.621.0 fixes the vulnerability on my dependency tree. Thank you!

**Comment by kiarash-malekzadeh** [comment]
@trivikr Still having the 4.2.5 dependency under this in package-lock.json:
 ```
"node_modules/@aws-sdk/client-sts": {
            "version": "3.454.0",
            "dependencies": {
                "fast-xml-parser": "4.2.5",
            },
        } 
```
Is there anything else that should be updated besides @aws-sdk/client-s3 and aws-sdk? Please note that we have not installed the @aws-sdk/client-s3 and it does not exist in package.json.

**Comment by trivikr** [comment]
> Is there anything else that should be updated besides @aws-sdk/client-s3

Update all your `@aws-sdk/*` clients to `v3.621.0`.

You've only provided a subset of your lockfile contains `@aws-sdk/client-sts@3.454.0`, which is likely added as a transitive dependency from some other `v3.454.0` client.

**Comment by kiarash-malekzadeh** [comment]
@trivikr We have only the following installed:

- "@aws-sdk/client-s3": "^3.621.0",
- "aws-sdk": "^2.1665.0",

I think the dependencies of "aws-sdk" have not been updated.

**Comment by kiarash-malekzadeh** [comment]
@trivikr This is what I get from npm audit:
```
fast-xml-parser  <4.4.1
Severity: high
fast-xml-parser vulnerable to ReDOS at currency parsing - https://github.com/advisories/GHSA-mpg4-rc92-vx8v
fix available via `npm audit fix`
node_modules/fast-xml-parser
  @aws-sdk/client-sts  <=3.525.0
  Depends on vulnerable versions of fast-xml-parser
  node_modules/@aws-sdk/client-sts
    @aws-sdk/client-cognito-identity  3.12.0 - 3.525.0
    Depends on vulnerable versions of @aws-sdk/client-sts
    node_modules/@aws-sdk/client-cognito-identity
      @aws-sdk/credential-provider-cognito-identity  3.12.0 - 3.525.0
      Depends on vulnerable versions of @aws-sdk/client-cognito-identity
      node_modules/@aws-sdk/credential-provider-cognito-identity
    @aws-sdk/credential-providers  <=3.525.0
    Depends on vulnerable versions of @aws-sdk/client-cognito-identity
    Depends on vulnerable versions of @aws-sdk/client-sts
    Depends on vulnerable versions of @aws-sdk/credential-provider-cognito-identity
    node_modules/@aws-sdk/credential-providers

ip  *
Severity: high
```

**Comment by trivikr** [comment]
@kiarash-malekzadeh You can examine your lockfile by running `npm why @aws-sdk/client-sts`, which will provide information on why the dependency is imported. And update the direct dependency accordingly.

**Comment by kiarash-malekzadeh** [comment]
@trivikr Thanks for the help. Fixed the issue.

**Comment by bhaveshj459** [comment]
@trivikr  this is showing in my audit files;

**Comment by trivikr** [comment]
@bhaveshj459 The answer is similar to one given in previous comment, and your console also shows `@aws-sdk/client-sts  <=3.525.0`

https://github.com/aws/aws-sdk-js-v3/issues/6331#issuecomment-2259379014

**Comment by bhaveshj459** [comment]
@trivikr I have tried it but its not working for me also I have made an new angular application to make sure other deps are not causing this issue but found no difference.

**Comment by jlove-dev** [comment]
I'm getting the same thing. `npm audit`:

```
# npm audit report

fast-xml-parser  <4.4.1
Severity: high
fast-xml-parser vulnerable to ReDOS at currency parsing - https://github.com/advisories/GHSA-mpg4-rc92-vx8v
fix available via `npm audit fix --force`
Will install aws-amplify@5.3.19, which is a breaking change
node_modules/fast-xml-parser
  @aws-sdk/client-sts  <=3.525.0 || 3.529.1 - 3.620.1
  Depends on vulnerable versions of @aws-sdk/client-sso-oidc
  Depends on vulnerable versions of @aws-sdk/core
  Depends on vulnerable versions of @aws-sdk/credential-provider-node
  Depends on vulnerable versions of fast-xml-parser
  node_modules/@aws-sdk/client-cognito-identity-provider/node_modules/@aws-sdk/client-sts
  node_modules/@aws-sdk/client-firehose/node_modules/@aws-sdk/client-sts
  node_modules/@aws-sdk/client-kinesis/node_modules/@aws-sdk/client-sts
  node_modules/@aws-sdk/client-personalize-events/node_modules/@aws-sdk/client-sts
  node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/client-sts
  node_modules/@aws-sdk/client-sso-oidc/node_modules/@aws-sdk/client-sts
  node_modules/@aws-sdk/client-sts
    @aws-sdk/client-cognito-identity  3.529.1 - 3.620.1
    Depends on vulnerable versions of @aws-sdk/client-sso-oidc
    Depends on vulnerable versions of @aws-sdk/client-sts
    Depends on vulnerable versions of @aws-sdk/core
    Depends on vulnerable versions of @aws-sdk/credential-provider-node
    node_modules/@aws-sdk/client-cognito-identity
      @aws-sdk/credential-provider-cognito-identity  3.529.1 - 3.620.1
      Depends on vulnerable versions of @aws-sdk/client-cognito-identity
```

`npm why`:

```
npm why @aws-sdk/client-sts
@aws-sdk/client-sts@3.398.0
node_modules/@aws-amplify/analytics/node_modules/@aws-sdk/client-sts
  @aws-sdk/client-sts@"3.398.0" from @aws-sdk/client-firehose@3.398.0
  node_modules/@aws-amplify/analytics/node_modules/@aws-sdk/client-firehose
    @aws-sdk/client-firehose@"3.398.0" from @aws-amplify/analytics@7.0.40
    node_modules/@aws-amplify/analytics
      @aws-amplify/analytics@"7.0.40" from aws-amplify@6.4.3
      node_modules/aws-amplify
        aws-amplify@"^6.3.8" from the root project
  @aws-sdk/client-sts@"3.398.0" from @aws-sdk/client-kinesis@3.398.0
  node_modules/@aws-amplify/analytics/node_modules/@aws-sdk/client-kinesis
    @aws-sdk/client-kinesis@"3.398.0" from @aws-amplify/analytics@7.0.40
    node_modules/@aws-amplify/analytics
      @aws-amplify/analytics@"7.0.40" from aws-amplify@6.4.3
      node_modules/aws-amplify
        aws-amplify@"^6.3.8" from the root project
  @aws-sdk/client-sts@"3.398.0" from @aws-sdk/client-personalize-events@3.398.0
  node_modules/@aws-amplify/analytics/node_modules/@aws-sdk/client-personalize-events
    @aws-sdk/client-personalize-events@"3.398.0" from @aws-amplify/analytics@7.0.40
    node_modules/@aws-amplify/analytics
      @aws-amplify/analytics@"7.0.40" from aws-amplify@6.4.3
      node_modules/aws-amplify
        aws-amplify@"^6.3.8" from the root project
```

I've tried resolving this but my dependencies show:

`"@aws-sdk/client-sts": "^3.606.0"`
`"aws-amplify": "^6.3.8"`

**Comment by trivikr** [comment]
@jlove-dev The AWS SDK in your application is imported from Amplify.

Please refer to https://github.com/aws-amplify/amplify-js/issues/13670, for updates in `@aws-amplify/*`

**Comment by jlove-dev** [comment]
Thank you @trivikr that really clears things up!
