### ISSUE TITLE
httpOptions docs need updating in "Client Constructors" section of "Notable Changes [since v2]" 

### ISSUE THREAD

**Issue by RichardBradley** [aws/aws-sdk-js-v3#6370]
### Describe the issue

The page at https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/migrating/notable-changes/ describes how to translate various v2 options to v3

One section describes the old "httpOptions" and references ""@aws-sdk/node-http-handler""

This needs updating to "smithy", but also quite a few of the options have also changed recently, and I'm struggling to find good docs for them. 

I think the latest style is now to pass POJO rather than classes here.
"socketTimeout" is also deprecated.

Perhaps the example should now look like this?

```
const dynamodbClient = new DynamoDBClient({
  requestHandler: {
    httpsAgent: {
      /*params*/
    },
    connectionTimeout: /*number in milliseconds*/
    requestTimeout: /*number in milliseconds*/
  }),
});
```

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/migrating/notable-changes/

**Comment by aBurmeseDev** [comment]
Hi @RichardBradley - appreciate you for reaching out and reporting documentation update.

>One section describes the old "httpOptions" and references ""@aws-sdk/node-http-handler"
>This needs updating to "smithy", but also quite a few of the options have also changed recently, and I'm struggling to find good docs for them.

Good catch, we'll get it updated. I'd recommend you [this docs page](https://github.com/aws/aws-sdk-js-v3/blob/main/supplemental-docs/CLIENTS.md#request-handler-requesthandler) for NodeHttpHandler. 

>I think the latest style is now to pass POJO rather than classes here.
"socketTimeout" is also deprecated.
>
> Perhaps the example should now look like this?

The `socketTimeout` configuration is available as an option in the [NodeHttpHandler](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-smithy-node-http-handler/Interface/NodeHttpHandlerOptions/) from the `@smithy/node-http-handler` package in JavaScript SDK v3.

To clarify, the `socketTimeout` config determines the time after which an idle socket will be closed. This means that the socket will be closed if there are no active requests using it after the specified timeout duration. On the other hand, the `connectionTimeout` config sets the time limit for establishing a connection before throwing an error.

Here's code example with @smithy/node-http-handler
```js
import { NodeHttpHandler } from "@smithy/node-http-handler";
import https from "https";

new S3Client({
  requestHandler: new NodeHttpHandler({
    httpsAgent: new https.Agent({
      keepAlive: true,
      maxSockets: 200, // default is 50 per client.
    }),

    // time limit (ms) for receiving response.
    requestTimeout: 15_000,

    // time limit (ms) for establishing connection.
    connectionTimeout: 6_000,
  }),
});
```
Hope this helps and please let me know if there's any other question I can help clarify.
Best,
John

**Comment by aBurmeseDev** [comment]
We've updated the docs for code examples on [Notable Changes](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/migrating/notable-changes/) that addresses your feedback. Thank you again for providing feedback and please let us know if there're any other questions!

**Comment by RichardBradley** [comment]
Thanks!
