### ISSUE TITLE
@aws-sdk/client-bedrock-runtime In the Nextjs environment build, ./dist-es/runtimeConfig.browser will be loaded.

### ISSUE THREAD

**Issue by Xavieru718** [aws/aws-sdk-js-v3#6378]
### Describe the bug

Hello,

In my Nextjs project, I use @aws-sdk/client-bedrock-runtime to request Bedrock. I must manually declare AccessKey & SecretAccessKey in the code. I cannot use aws configure or EC2's IAM Role. If AK&SK is not set, an error will be reported: **Error: Credential is missing** .

I think it is the request handled by ./dist-es/runtimeConfig.browser

My code is:
```Typescript
    import { BedrockRuntimeClient, InvokeModelWithResponseStreamCommand } from "@aws-sdk/client-bedrock-runtime";
    const accessKey = 'myAK';
    const secretAccessKey = 'mySK';
    const AWS_PARAM = accessKey && secretAccessKey
    ? {
        region: 'us-west-2',
        credentials: {
          accessKeyId: accessKey,
          secretAccessKey: secretAccessKey,
        },
      }
    : {
        region: 'us-west-2',
      };
     const bedrockruntime = new BedrockRuntimeClient(AWS_PARAM);
     const command = new InvokeModelWithResponseStreamCommand({
      body: ...,
      modelId: 'anthropic.claude-3-sonnet-20240229-v1:0',
      contentType: "application/json",
      accept: "application/json",
    });
    // error reported from here
    const response = await bedrockruntime.send(command);
```

My next.config.mjs is:
```javascript
const mode = process.env.BUILD_MODE ?? "standalone";
const nextConfig = {
  reactStrictMode: true,
  webpack(config, { isServer }) {
    config.module.rules.push({
      test: /\.svg$/,
      use: ["@svgr/webpack"],
    });

    if (isServer) {
      config.resolve.fallback = {
        child_process: false,
        canvas: false,
        fs: false,
        http: false,
        https: false,
        http2: false,
      };

      config.resolve.alias = {
        ...config.resolve.alias,
        "./runtimeConfig": path.resolve(
          process.cwd(),
          "node_modules/@aws-sdk/client-bedrock-runtime/dist-es/runtimeConfig"
        ),
        "./dist-es/runtimeConfig": path.resolve(
          process.cwd(),
          "node_modules/@aws-sdk/client-bedrock-runtime/dist-es/runtimeConfig"
        ),
      };
    }

    return config;
  },
  output: mode,
};
```

If I don't set AK and SK, an error will be reported here, even though I have given AdminAccess to my EC2.

Thanks for your help.

### Expected Behavior

I can access BedrockRuntimeClient through IAM Role without explicitly setting ak and sk.

### Current Behavior

Please see the code above.

### Reproduction Steps

Please see the code above.

### SDK version used

"@aws-sdk/client-bedrock-runtime": "^3.624.0"

### Environment details (OS name and version, etc.)

mac & amazon linux 2023 & nodejs v20.15.1

**Comment by aBurmeseDev** [comment]
Hi @Xavieru718 - thanks for reaching out. 

The AWS SDK for JavaScript V3 provides a [default credential provider](https://docs.aws.amazon.com/sdkref/latest/guide/standardized-credentials.html#credentialProviderChain) chain in Node.js, which attempts to resolve credentials from [various sources in a specific order](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/setting-credentials-node.html#credchain). When credentials are not found from any of these sources, you encounter the "Missing credential" error.

The simplest way to provide credentials is by configuring the [shared AWS config and credentials files](https://docs.aws.amazon.com/sdkref/latest/guide/file-format.html#file-format-creds), which contain a set of profiles with the necessary configuration settings. Have you configured these files on your machine?

You mentioned that you cannot use `aws configure` or an `EC2 IAM Role`. If that's the case, you may need to explore alternative methods to provide credentials, such as environment variables or programmatic credential management.

It's worth noting that hardcoding credentials in your application code is generally not recommended for security reasons. Instead, you should consider using a secure and centralized credential management system or leverage AWS services like AWS Amplify or Cognito for authentication and authorization.

If you provide more details about your specific constraints or requirements, I can suggest more tailored solutions to address the credential management issue in your Next.js project.

Best,
John

**Comment by Xavieru718** [comment]
Hi John, 
Thanks for looking at my issue.

I tried to use the **fromInstanceMetadata** and **fromNodeProviderChain** methods of @aws-sdk/credential-providers in Next.js code in **API service**, but both of them reported errors 
(0, _aws_sdk_credential_providers__WEBPACK_IMPORTED_MODULE_3__.fromInstanceMetadata) is not a function

(0, _aws_sdk_credential_providers__WEBPACK_IMPORTED_MODULE_3__.fromNodeProviderChain) is not a function

I have installed the dependencies using the npm command. (`npm i  @aws-sdk/credential-providers --save`)

I have configured AK and SK on my computer/EC2 through the `aws configure` command. At the same time, I have given the EC2 AdminAccess IAM Role. I can list all Buckets using the `aws s3 ls` command on my computer/EC2.

I think in Nextjs server code, the SDK considers itself a browser environment instead of a node environment.

My code is as follows:
```Typescript
// An API file 
import { fromNodeProviderChain } from "@aws-sdk/credential-providers"; 
const credentialProvider = fromNodeProviderChain({
  clientConfig: { region: 'us-west-2'},
});
const credential = await credentialProvider();
const bedrockruntime = new BedrockRuntimeClient({
    region: 'us-west-2',
    credential: credential,
  });

// or

// An API file 
import { fromInstanceMetadata } from "@aws-sdk/credential-providers"; 
const credentials = fromInstanceMetadata({
  timeout: 1000,
  maxRetries: 0,
});
const bedrockruntime = new BedrockRuntimeClient({
    region: 'us-west-2',
    credential: credential,
  });

```

**Comment by kuhe** [comment]
If `./dist-es/runtimeConfig.browser` is loaded then your bundler is operating with a browser target environment. In such cases, the node.js default credential chain will not be used, and most file-system or environment/process based credential providers from `@aws-sdk/credential-providers` will not be available.

If you are indeed creating a browser bundle, you need to provide credentials explicitly. If you are bundling server-side code, then you should set the platform target to `node` so that the SDK's browser runtimeConfig is not used.

**Comment by Xavieru718** [comment]
Hi all,
Thanks for your help on my issue.

I have solved this problem. Since Nextjs requires "edge" or "nodejs" as the runtime at the API entry, I specified edge, so webpack uses the browser environment by default. Changing the runtime to nodejs solves the problem.

```Typescript
// API entry
export const runtime = "nodejs"; // Not "edge"!
export async function handle(req: NextRequest,  { params }: { params: { path: string[] } }) {
    // My code......
}
```

Thanks.
