### ISSUE TITLE
Async invocation is not covered in the javascript example for V3 SDK

### ISSUE THREAD

**Issue by matthewvcarey1** [aws/aws-sdk-js-v3#6388]
### Describe the issue

There is a very clear example for synchronous invocation  but asynchronous invocation is not covered in the javascript example for V3 SDK. As the way of doing it has changed from V2 of the SDK this is an omission.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/lambda/command/InvokeCommand/

**Comment by zshzbh** [comment]
Hey @matthewvcarey1 , 

The v2 code sample is similar with V3 code sample: 
V2 - 
<img width="1115" alt="Screenshot 2024-08-15 at 1 14 46 PM" src="https://github.com/user-attachments/assets/63b0be3d-ac4e-4a1d-9b38-075d91cdd223">
 

V3 - 
<img width="984" alt="Screenshot 2024-08-15 at 1 15 49 PM" src="https://github.com/user-attachments/assets/39a41d7b-7a59-47ff-ab72-3e260e217bb7">

Could you please provide the link of the v2 example you mentioned? 

Thanks! 
Maggie
