### ISSUE TITLE
Dead link in S3-control CreateJob description

### ISSUE THREAD

**Issue by modelbitjason** [aws/aws-sdk-js-v3#6412]
### Describe the issue

The link 'Operations' goes to :
https://docs.aws.amazon.com/AmazonS3/latest/dev/batch-ops-actions.html, but that link is dead and just redirects to the main S3 page.

![image](https://github.com/user-attachments/assets/3960127f-19ca-4b8d-91cd-ebdba685be90)

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3-control/command/CreateJobCommand/

**Comment by zshzbh** [comment]
Hey @modelbitjason ,

Thanks for the feedback! I do think we need to update the link of the `Operations`. I have brought this request to our internal tech writer, I will post the reference once I get the ticket ID.

Thanks! 
Maggie

**Comment by zshzbh** [comment]
ref: V1501129765

**Comment by aws-docs-suej** [comment]
Thank you. Here's the correct doc, for your reference: https://docs.aws.amazon.com/AmazonS3/latest/userguide/batch-ops-operations.html

**Comment by kuhe** [comment]
fixed at https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3-control/command/CreateJobCommand/
