### ISSUE TITLE
Need Signed URL without Async await like we have in V2

### ISSUE THREAD

**Issue by nikhilmisra63** [aws/aws-sdk-js-v3#6425]
### Describe the feature

Need to generate S3 Signed URL without async await as after updating to v3 it is breaking my code.

### Use Case

Need this feature because in mongo db serialization I'm generating signed url before sending response to frontend and there in toJSON method we can not call a method using await.

```
schema.methods.toJSON = async function () {
  const story = this.toObject();
  story.contentUrl = story.content
    ? await generateSignedUrl(story.content)
    : undefined;
  return story;
};
```

this is what I was doing in v2 and it is not working after v3 update.

### Proposed Solution

support v2 method of generating signed url

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

v3

### Environment details (OS name and version, etc.)

Mac, ubuntu

**Comment by aBurmeseDev** [comment]
HI @nikhilmisra63 - thanks for reaching out.

Here's code example of v3 to generate pre-signed URL without using async/await:
```js
const { S3Client, GetObjectCommand } = require("@aws-sdk/client-s3");
const { getSignedUrl } = require("@aws-sdk/s3-request-presigner");

// Create an S3 client
const s3Client = new S3Client({ region: "your-aws-region" });

// Function to generate a pre-signed URL
function generateSignedUrl(key) {
  const command = new GetObjectCommand({
    Bucket: "your-bucket-name",
    Key: key,
  });

  // Generate the pre-signed URL
  return getSignedUrl(s3Client, command, { expiresIn: 3600 });
}

// Usage example
const objectKey = "path/to/your/object.jpg";
const signedUrl = generateSignedUrl(objectKey);
console.log(signedUrl);
``` 
Since the getSignedUrl function returns a Promise, you can directly assign the result to a variable without using async/await. 
```js
schema.methods.toJSON = function () {
  const story = this.toObject();
  story.contentUrl = story.content
    ? generateSignedUrl(story.content)
    : undefined;
  return story;
};
```

Hope it helps!
Best,
John
