### ISSUE TITLE
QueryCommand:  failed to query index

### ISSUE THREAD

**Issue by Luan10017** [aws/aws-sdk-js-v3#6429]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

QueryCommand receiving timeout when trying to query index (GSI), however when observing the index reading data in the table console there is no reading processing.
Furthermore, the same logic and data work perfectly with the dynamodb SDK V2 and nodejs 14 lambda runtime.

### SDK version number

@aws-sdk/lib-dynamodb

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Nodejs 20

### Reproduction Steps

```js
import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, QueryCommand } from "@aws-sdk/lib-dynamodb";

const client = new DynamoDBClient({});
const dynamo = DynamoDBDocumentClient.from(client);

export const handler = async (event, context) => {
    if (process.env.DEBUG) {
      console.log({
        message: "Received event",
        data: JSON.stringify(event, null, 2),
      });
      console.log({
        message: "Received contex",
        data: JSON.stringify(context, null, 2),
      });
    }
  
    const firstDate = event?.firstDate;
    const secondDate = event?.secondDate;
    const emailToResponsible = event?.emailToResponsible;
    const ExclusiveStartKey = event?.ExclusiveStartKey;
  
    try {

          const emailData = await getDataByEmail(
            emailToResponsible,
            firstDate,
            secondDate,
            ExclusiveStartKey
          );
          return response(200, emailData);
       
    } catch (error) {
      console.error(JSON.stringify(error, null, 2));
      return response(500, error);
    }
  };

async function getDataByEmail(
    emailToResponsible,
    firstDate,
    secondDate,
    ExclusiveStartKey
  ) {
    const params = {
      TableName: tableName,
      IndexName: "emailToResponsible",
      KeyConditionExpression:
        "emailToResponsible = :emailToResponsible_prefix AND #dateField BETWEEN :date1 and :date2",
      ExpressionAttributeValues: {
        ":emailToResponsible_prefix": emailToResponsible,
        ":date1": firstDate,
        ":date2": secondDate,
      },
      ExpressionAttributeNames: {
        "#dateField": "createdAt",
      },
    };
  
    if (ExclusiveStartKey) {
      params.ExclusiveStartKey = ExclusiveStartKey;
    }
  
    const items = await dynamo.send(new QueryCommand(params));
  
    return items;
  }

  function response(status, body) {
    return {
      statusCode: status,
      body: body,
      headers: {
        "Content-Type": "application/json",
      },
    };
  }
```
### Observed Behavior

QueryCommad receives a timeout error after 30 seconds, but no read attempts are recorded in the table index reading metrics.
Furthermore, using the AWS SDK V2, the query returns in 400 ms.

### Expected Behavior

Data return in time compared to SDK V2 400 ms.

**Comment by aBurmeseDev** [comment]
Hi @Luan10017 - thanks for reaching out.  

>Furthermore, the same logic and data work perfectly with the dynamodb SDK V2 and nodejs 14 lambda runtime.

Node.js 14 runtime for Lambda was [deprecated](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtime-deprecation-levels) on Dec 4, 2023, and AWS SDK for Javascript v2 is [entering Maintenance mode](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-javascript-v2/) on Sept 8, 2025. 

Can you confirm if you're running this on supported Lambda runtime?

Here are a few steps you can take to further investigate:
- Check/Increase Timeout Settings: If you're not currently setting timeout, you can increase default settings
```js
const client = new DynamoDBClient({ requestTimeout: 60000 }); // Increase timeout to 60 seconds
```
- Retrieve request logs: Gather logs using [mIddlewareStack](https://github.com/aws/aws-sdk-js-v3?tab=readme-ov-file#middleware) and share it with us (redact any sensitive information)
```js
client.middlewareStack.add(
  (next, context) => async (args) => {
    console.log("AWS SDK context", context.clientName, context.commandName);
    console.log("AWS SDK request input", args.input);
    const result = await next(args);
    console.log("AWS SDK request output:", result.output);
    return result;
  },
  {
    name: "MyMiddleware",
    step: "build",
    override: true,
  }
);
```
Looking forward to hear back!
Best,
John
