### ISSUE TITLE
Incomplete list of Lambda runtimes

### ISSUE THREAD

**Issue by skyzyx** [aws/aws-sdk-js-v3#6441]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The deprecated Lambda runtimes `dotnet5.0` and `dotnet7` are missing from the code, as well as [the models](https://github.com/aws/aws-sdk-js-v3/blob/v3.646.0/codegen/sdk-codegen/aws-models/lambda.json).

https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

### SDK version number

v3.646.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

N/A

### Reproduction Steps

Using GitHub search in this repository for the terms `dotnet5.0` or `dotnet7` return 0 results. The terms `dotnet6`, `dotnet8`, and every other runtime listed on the official [Lambda runtimes](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) page returns expected results.

### Observed Behavior

The `dotnet5.0` and `dotnet7` identifiers appear to be missing from the list of Lambda runtimes understood by this SDK.

### Expected Behavior

I expected `dotnet5.0` and `dotnet7` to be supported.

### Possible Solution

* Perhaps the identifiers are missing from the source models.
* Perhaps these get sorted out of the list when performing code generation.

### Additional Information/Context

I worked at AWS on the SDK team from 2010-2014. At the time, "Coral" was used for modeling services. Nowadays, I see "Smithy" used everywhere. Not sure how they are/aren't related.

My real use-case is not in using the SDK, but rather in using the model files for code generation in a different programming language, and allowing me to programmatically keep certain patterns up-to-date. During my time at AWS, I was a champion for making the models available to end-users for precisely this purpose, so I'm glad it has come to fruition (some years ago at this point).

The JS SDK is the first one I've found that exposes JSON to work with (although I may have missed other SDKs).

**Comment by kuhe** [comment]
They would only be in the models if there was an enum of the runtimes that was involved in an SDK API operation to the AWS Lambda service. If no such operation exists, then there's no reason they would be in the models.

**Comment by kuhe** [comment]
On second glance, there could be a modeling error. We receive these from the service teams rather than maintaining them ourselves. The maintainer(s) who triage the ticket may be able to inquire with the Lambda team about the discrepancy.

**Comment by kuhe** [comment]
The two enum values share the suffix "container only", that probably has something to do with it.

**Comment by aBurmeseDev** [comment]
Hi @skyzyx - appreciate you for reporting it. 

As mentioned above, service models are generated and managed by the upstream service teams which in this case is the Lambda team. If this issue requires an update to the service model itself, the Lambda team needs to address it as the SDK team does not have direct control over the service models.

I will reach out to the Lambda team on your behalf to gather more insights and have them investigate this issue further. I will keep you updated on any progress or response from the Lambda team. (ref: _P153373156_)

Best,
John

**Comment by aBurmeseDev** [comment]
Lambda team member responded: 
>The two specified runtimes in the issue are container image functions only, no managed runtime exists and as such when creating the function using the SDK you do not specify the runtime when creating a function which uses container images.

Let us know if you have further question before closing the issue.

**Comment by skyzyx** [comment]
Understood. This wasn't clear to me from the [Lambda Runtimes documentation](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html).
