### ISSUE TITLE
SSM GetParameterCommand never return undefined

### ISSUE THREAD

**Issue by cm-iwata** [aws/aws-sdk-js-v3#6443]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The return value Parameter.Value of the `GetParameterCommand` is defined as `string | undefined`, but undefined will never return.
This is because if the parameter is not found, a `ParameterNotFound` exception will be thrown instead.

### SDK version number

@aws-sdk/client-ssm@3.637.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.11.1

### Reproduction Steps

```ts
import { SSMClient, GetParameterCommand } from "@aws-sdk/client-ssm";
const client = new SSMClient();
const input = {
  Name: "STRING_VALUE",
};
const command = new GetParameterCommand(input);
const response = await client.send(command);

let value: string;
value = response.Parameter?.Value
```

### Observed Behavior

Type error will occur.

![image](https://github.com/user-attachments/assets/16cf852a-65e7-4389-9e57-eb17c4ec0ecc)

### Expected Behavior

The code I mentioned earlier should not be raise a type error.
Because If the GetParameterCommand is not rejected, the `Value` will always returned.

**Comment by RanVaknin** [comment]
Hi @cm-iwata ,

The reason why we generate " | undefined" for our types, is intentionally designed for forward compatibility reasons. This allows AWS services to change their APIs by making previously required parameters optional, ensuring that existing client applications will not break when the API becomes less strict.

To improve the typescript experience, you can cast your client to be an [UncheckedClient or AssertiveClient](https://github.com/smithy-lang/smithy-typescript/tree/main/packages/types?rgh-link-date=2024-04-12T18%3A22%3A53Z#scenario-removing--undefined-from-input-and-output-structures) from Smithy-Typescript package. Just be mindful that using UncheckedClient eliminates compiler-generated nullability warnings for output fields by treating them as non-nullable. You should still perform manual type checks as necessary for your application's specific needs.

Thanks,
Ran~

**Comment by cm-iwata** [comment]
@RanVaknin 

Thank you for your reply, I understand!
