### ISSUE TITLE
How to apply guardrails in RetrieveCommandInput?

### ISSUE THREAD

**Issue by ivipinmishra** [aws/aws-sdk-js-v3#6452]
### Describe the issue

How to apply guardrails in RetrieveCommandInput? 

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/bedrock-agent-runtime/command/RetrieveCommand/

**Comment by zshzbh** [comment]
Hey @ivipinmishra ,

Could you please elaborate on this? May I know what you want to achieve?

Thanks!
Maggie
