### ISSUE TITLE
Check Headers of S3 Response and Error 

### ISSUE THREAD

**Issue by shirady** [aws/aws-sdk-js-v3#6476]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

How can I check the headers of the response - in case of regular response and error response?
In the AWS CLI tool I can see all the response headers using the `--debug` flag (regardless if it throws and error).

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### SDK version number

aws-sdk/client-s3: 3.637.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.11.0

### Reproduction Steps

An example of error check headers:
1. Create S3 bucket with versioning.
2. Put object.
3. Delete the object.
4. Head/Get the object with version-id (from step 3, which is the delete marker)
How can we save the headers for validation later?

Note: this is an example, but the question is general.

### Observed Behavior

Can't see all the headers on the thrown error.

### Expected Behavior

To have the ability to see all the headers as we can in AWS CLI with the `debug` flag.

### Additional Information/Context

From the docs [AWS docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html#API_GetObject_ResponseElements):
`If the specified version in the request is a delete marker, the response returns a 405 Method Not Allowed error and the Last-Modified: timestamp response header.`

**Comment by kuhe** [comment]
For a non-error response, to check the headers, use a custom middleware function. One example is here: https://github.com/aws/aws-sdk-js-v3/blob/main/supplemental-docs/CLIENTS.md#logger-logger, and I give an example below.

```js
import { S3 } from "@aws-sdk/client-s3";

const s3 = new S3();

s3.middlewareStack.add(
  (next) => async (args) => {
    const result = await next(args);
    result.output.$metadata.headers = result.response.headers;
    return result;
  }
);

const buckets = await s3.listBuckets();

console.log(buckets.$metadata.headers);
```

For a server error response, refer to https://github.com/aws/aws-sdk-js-v3/blob/main/supplemental-docs/ERROR_HANDLING.md#handling-service-returned-errors.

**Comment by shirady** [comment]
@kuhe thank you.

I want to make sure I understand - in case of an error, we can check `err.$response.headers`, right? (no need for `middlewareStack`).

I find writing the `middlewareStack` hard, can you add more explanations or links? (how can I know the structure to refer to? for example: `result.output.$metadata.headers = result.response.headers`)

**Comment by aBurmeseDev** [comment]
>I want to make sure I understand - in case of an error, we can check err.$response.headers, right? (no need for middlewareStack).

You're correct. For error responses, you can directly access `err.$response.headers` without needing to use the middlewareStack.


Regarding your question about understanding the structure to refer to when writing middleware, here's [link](https://github.com/aws/aws-sdk-js-v3?tab=readme-ov-file#middleware-stack) to middleware session in README which provides a clear example and explanation of how to write middleware and access different parts of the request or response data, including headers. 

Hope it helps,
John
