### ISSUE TITLE
Ipv6 address treated as hostnamem getaddrinfo ENOTFOUND [fd00:ec2::23]

### ISSUE THREAD

**Issue by Defman** [aws/aws-sdk-js-v3#6495]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When using podidentity with eks the ip [fd00:ec2::23] is treated as a hostname.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### SDK version number

@aws-sdk/client-s3@3.654.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

22.9.0

### Reproduction Steps

1. EKS Cluster running ipv6
2. Use podidentity
3. Use the s3-client lib to access s3 authenticated via podidentity

### Observed Behavior

Tries to resolve [fd00:ec2::23] via dns

### Expected Behavior

Should not try to resolve the ip via dns.

### Additional Information/Context

EKS ipv6

**Comment by Defman** [comment]
Fixed in https://github.com/smithy-lang/smithy-typescript/pull/1408

**Comment by Defman** [comment]
Actually I’ll leave this issue open until smithy is bumped.

**Comment by kuhe** [comment]
Workaround until the minimum version is bumped is to update your lockfile or make a fresh install.

**Comment by kuhe** [comment]
The minimum node-http-handler dependency version in the current version of the SDK is high enough to guarantee including the fix, so I'm closing this now.
