### ISSUE TITLE
DynamoDB client url changed after 3.656.0 release

### ISSUE THREAD

**Issue by Steuls** [aws/aws-sdk-js-v3#6503]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

With the latest version of the SDK the URL the dynamo requests go to has changed, this has caused us issues since all our applications live in a whitelisted networking space and so suddenly went down. This change to use the accountId URL should be a separate flag as otherwise this is a breaking change

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### SDK version number

3.656.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

18

### Reproduction Steps

Load previous version and the output URL is the generic one
Load current version and the output URL is the AccountId specific one

### Observed Behavior

The URL requests are now being sent to the new URL

### Expected Behavior

The URL requests are being sent to should not be changed from the original default behaviour

### Possible Solution

Set this new setting as a flag

**Comment by Steuls** [comment]
Thanks for that information. It should be noted though that the page you linked says support for the V3 SDK is not supported so does have conflicting information. Also doesn't change the fact this is more of a breaking change since it is directly changing the functionality from the version before?

**Comment by aBurmeseDev** [comment]
Thanks for your patience @Steuls. Please refer to this [announcement](https://github.com/aws/aws-sdk-js-v3/issues/6520) here:

>In AWS SDK for JavaScript v3.656.0, we released changes to the DynamoDB client that adopt a new AWS account-based endpoints feature. For more information on account based endpoints, please refer to the official [SDK documentation](https://docs.aws.amazon.com/sdkref/latest/guide/feature-account-endpoints.html). In SDK releases from this version on, clients will connect to a DynamoDB endpoint in the form of (account-id).ddb.(region).amazonaws.com instead of dynamodb.(region).amazonaws.com.
>
>If your network configuration blocks outgoing traffic to DynamoDB based on DNS names or endpoint URLs, you must adjust your configuration, because the service's DNS name will change. You may also choose to switch to an IP-based configuration. The IP address ranges for DynamoDB, as well as other AWS services, can be found in the [AWS documentation](https://docs.aws.amazon.com/vpc/latest/userguide/aws-ip-ranges.html).
>
>You may instead disable account-based endpoints for DynamoDB by setting the [config flag](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/dynamodb/) accountIdEndpointMode to disabled. We recommend against this because the DynamoDB service uses account-based endpoints to ensure performance and scalability.

Here's updated docs for reference: https://docs.aws.amazon.com/sdkref/latest/guide/feature-account-endpoints.html

Apologies for the inconvenience and feel free to let us know if there are any further questions.
