### ISSUE TITLE
No iso-f and iso-e

### ISSUE THREAD

**Issue by dutingda** [aws/aws-sdk-js-v3#6513]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

https://github.com/aws/aws-sdk-js-v3/blob/main/codegen/sdk-codegen/aws-models/sts.json
where is iso-f and iso-e

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### SDK version number

@aws-sdk/client-sts

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

18.18.2

### Reproduction Steps

No need to reproduce see the description

### Observed Behavior

No iso-f and iso-e partition

### Expected Behavior

should be inside

**Comment by aBurmeseDev** [comment]
Hi @dutingda - thanks for reaching out.

The service model you're referring to is created by the respective service teams. The SDK team does not modify these models directly. Could you provide more details about your specific concern? With additional context, I can better understand your inquiry and reach out to the appropriate service team internally for clarification.

Best,
John

**Comment by dutingda** [comment]
There is no sts url for partition iso-f and iso-e you can check the link doc I provided, there is url for iso and iso-b but not the partition I mentioned

**Comment by dutingda** [comment]
This is error we got, Error: getaddrinfo ENOTFOUND sts.us-isof-south-1.amazonaws.com

**Comment by dutingda** [comment]
can I have this issue deleted thank you.
