### ISSUE TITLE
[client-kms] Setting AWS_SDK_LOAD_CONFIG does not enable region loading from config file

### ISSUE THREAD

**Issue by ProjectFrank** [aws/aws-sdk-js-v3#6518]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Setting AWS_SDK_LOAD_CONFIG=true does not allow the `KMSClient` constructor (called with no arguments) to use the region specified in `~/.aws/config`.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### SDK version number

@aws-sdk/client-kms@npm:^3.658.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.9.0

### Reproduction Steps

Contents of `~/.aws/config`:
[default]
region = us-east-1

Snippet:

```typescript
import { KMSClient, GenerateMacCommand } from '@aws-sdk/client-kms';

const client = new KMSClient();
const keyArn = 'your-key-arn';
const command = new GenerateMacCommand({
  Message: Buffer.from('abc'),
  KeyId: keyArn,
  MacAlgorithm: 'HMAC_SHA_512',
});
await client.send(command);
```

### Observed Behavior

When using the above snippet to make a request, I encounter the following error:
```
Unhandled error Error: getaddrinfo ENOTFOUND kms.undefined.amazonaws.com
```

### Expected Behavior

I expect the command to work (e.g. by sending a request to `kms.us-east-1.amazonaws.com`).

### Additional Information/Context

smithy-codegen

**Comment by aBurmeseDev** [comment]
Hi @ProjectFrank - thanks for reaching out. 

Before I further look into the issue, there are a couple of things I'd like to confirm:
- Are you able to successfully execute the code when you explicitly specify the region in the client constructor? For example, `new KMSClient({region: 'us-east-1'})`.
- If possible, could you try running a different AWS client with the environment variable `AWS_SDK_LOAD_CONFIG="true"`? This may provide additional insights into the problem.
---

I'll share these docs for your reference:
- Use a shared config file - https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/setting-region.html#setting-region-config-file
- Shared config and credentials files - https://docs.aws.amazon.com/sdkref/latest/guide/file-format.html

**Comment by ProjectFrank** [comment]
Yes, the code works correctly when the region is explicitly specified. 

Strangely enough, the client also doesn't seem to be picking up the region when specifying the region by running `export AWS_REGION=us-east-1`.

I can try to find time and put together a snippet using a different sdk.

**Comment by ProjectFrank** [comment]
This may be a problem having to do with running the code via https://github.com/dherault/serverless-offline . I will close this issue for now.
