### ISSUE TITLE
Enable an option for executing read queries against the reader instances in rds-data

### ISSUE THREAD

**Issue by alejandromendeza** [aws/aws-sdk-js-v3#6531]
### Describe the feature

It would be great to execute Data API queries not only to the writer instances, but pointing to the reader ones in a DB cluster. 

### Use Case

Gradually replace any third-party library (such as mysql2 in javascript) for handling RDS queries in a Serverless environment. 

### Proposed Solution

The secret's JSON already contains the host, so, it should be easy for the service to honor such a value (if present). In that way the secretArn passed to the commands would determine whether the client hits the reader or writer endpoints of the clusters.

### Other Information

The lack of this ability make much of us stay using third-party libs hora handling connections to the RDS (including managing connections pools, which is a little bit more complex in serverless scenarios)

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

V3.660.0

### Environment details (OS name and version, etc.)

Any

**Comment by aBurmeseDev** [comment]
Hi @alejandromendeza - thanks for reaching out.

Could you please provide more details about your workflow process and specify what you need from the AWS SDK for JavaScript team? This will help us better understand your feature request.
