### ISSUE TITLE
Unable to call fromCognitoIdentityPool on iOS (browser) - crashes

### ISSUE THREAD

**Issue by raRaRa** [aws/aws-sdk-js-v3#6542]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I just noticed that Chrome on iOS devices fails when calling `fromCognitoIdentityPool`. But it works on my desktop machine just fine with Chrome and Safari.

Example code:

```
  this.cachedCredentials = await fromCognitoIdentityPool({
      // Required. The unique identifier for the identity pool from which an identity should be
      // retrieved or generated.
      identityPoolId: this.options.IdentityPoolId,
      clientConfig: { region: this.options.Region },
  })();
```

The error I get:
```
DEBUG endpoints Resolving endpoint from template: {
  "url": "https://cognito-identity.{Region}.{PartitionResult#dnsSuffix}",
  "properties": {},
  "headers": {}
}

ERROR TypeError: JSON.stringify cannot serialize cyclic structures
```

### Expected Behavior

I expect it to run through the last step where it errors out, which should log:

```
endpoints Resolved endpoint: {
  "headers": {},
  "properties": {},
  "url": "https://cognito-identity.eu-west-1.amazonaws.com/"
}
```

### Current Behavior

Currently it errors on 
```
DEBUG endpoints Resolving endpoint from template: {
  "url": "https://cognito-identity.{Region}.{PartitionResult#dnsSuffix}",
  "properties": {},
  "headers": {}
}
```

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### SDK version number

@aws-sdk/credential-providers 3.664.0

### Which JavaScript Runtime is this issue in?

Browser

### Details of the browser/Node.js/ReactNative version

Latest Chrome on iOS - Chrome: 129.0.6668.90

### Reproduction Steps

Call `fromCognitoIdentityPool` from Chrome in iOS 

### Observed Behavior

This error comes: `ERROR TypeError: JSON.stringify cannot serialize cyclic structures`

### Expected Behavior

I expect this to log out:

```
endpoints Resolved endpoint: {
  "headers": {},
  "properties": {},
  "url": "https://cognito-identity.eu-west-1.amazonaws.com/"
}
```

### Possible Solution

N/A

### Additional Information/Context

N/A

**Comment by zshzbh** [comment]
Hey @raRaRa ,

Thanks for the feedback! Could you please add the following code so that we can see the request headers?

```js

client.middlewareStack.add(next => async (args) => {
    console.log(args.request)
    const response = await next(args);
    console.log(response);
    return response;
   }, {step: 'finalizeRequest'}) 

```

Thanks! 
Maggie
