### ISSUE TITLE
DynamoDBDocumentClients override other DynamoDBDocumentClients' marshalling options

### ISSUE THREAD

**Issue by misterjoshua** [aws/aws-sdk-js-v3#6545]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When you're sharing one DynamoDBClient between multiple DynamoDBDocumentClients, the marshalling options from the most recently created document client overwrites all the other document clients' marshalling options.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### SDK version number

@aws-sdk/lib-dynamodb@3.664.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node 20.13.1

### Reproduction Steps

```
test('error', async () => {
  const sharedClient = new DynamoDBClient();

  const doc1 = DynamoDBDocumentClient.from(sharedClient, {
    marshallOptions: {
      convertEmptyValues: true,
      removeUndefinedValues: true,
    },
  });

  const doc2 = DynamoDBDocumentClient.from(sharedClient, {
    marshallOptions: {
      convertEmptyValues: false,
      removeUndefinedValues: false,
    },
  });

  expect(doc1.config.translateConfig?.marshallOptions?.removeUndefinedValues).toBe(true);
  expect(doc1.config.translateConfig?.marshallOptions?.convertEmptyValues).toBe(true);
});
```

### Observed Behavior

The first document client's marshallOptions were overwritten by the second's marshallOptions.

### Expected Behavior

Each document client's options should be distinct and should not affect each other even if they're sharing a DynamoDBClient.

### Possible Solution

https://github.com/aws/aws-sdk-js-v3/blob/de4dc495455a47cd718c635209cd7aef9167797c/lib/lib-dynamodb/src/DynamoDBDocumentClient.ts#L144-L145

DynamoDBDocumentClient is sharing and mutating the underlying DynamoDBClient's config object when it should be keeping a private copy of the translate config.

**Comment by kuhe** [comment]
We don't plan to change this behavior currently. Please create two DynamoDB client instances. 

If you want them to share credentials and socket pools, refer to the documentation here: https://github.com/aws/aws-sdk-js-v3/blob/main/supplemental-docs/performance/parallel-workloads-node-js.md#client-instances. 

Excerpt (replace S3 with DynamoDB):
```ts
// example: credential and socket pool sharing from user instantiated objects.
import { S3 } from "@aws-sdk/client-s3";
import { fromNodeProviderChain } from "@aws-sdk/credential-providers";
import { NodeHttpHandler } from "@smithy/node-http-handler";

const credentials = fromNodeProviderChain();
const requestHandler = new NodeHttpHandler({
  httpsAgent: {
    maxSockets: 100,
  },
});

const s3_east = new S3({ region: "us-east-1", credentials, requestHandler });
const s3_west = new S3({ region: "us-west-2", credentials, requestHandler });
```
