### ISSUE TITLE
"You can't create a hosted zone for a top-level domain (TLD) such as .com." for Route53

### ISSUE THREAD

**Issue by itsfaraaz** [aws/aws-sdk-js-v3#6547]
### Describe the issue

The documentation states for the CreateHostedZoneCommand:

> You can't create a hosted zone for a top-level domain (TLD) such as .com.

This is misleading or incorrect. Because the name parameter takes in exactly a TLD (such as example.com). Could this be clarified?

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/route-53/command/CreateHostedZoneCommand/

**Comment by aBurmeseDev** [comment]
Hi @itsfaraaz - thanks for reaching out. 

When the documentation states "You can't create a hosted zone for a top-level domain (TLD) such as .com," it means that you cannot create a hosted zone that contains only a top-level domain like .com, .org, or .edu. A hosted zone needs to be associated with a fully qualified domain name (FQDN), such as www.example.com or example.org. The hosted zone cannot be created for just the TLD portion alone.

The documentation explains that under the "Name" [description](https://docs.aws.amazon.com/Route53/latest/APIReference/API_CreateHostedZone.html#API_CreateHostedZone_RequestBody), it states you must "Specify a fully qualified domain name, for example, www.example.com." This clarifies that the hosted zone needs to include the complete domain name, not just the TLD.

Hope that answers your question.
Best,
John

**Comment by itsfaraaz** [comment]
Awesome, thanks. I feel though that this documentation language can be updated to be clearer else it may be confusing. Thanks
