### ISSUE TITLE
Multiple credential sources warning: How to suppress warning message?

### ISSUE THREAD

**Issue by tfrancois** [aws/aws-sdk-js-v3#6548]
This warning is emitted here in the default provider chain rather than in the `fromEnv` provider function.

The reason for this is because when using the `fromEnv` provider in isolation, it doesn't matter if the `AWS_PROFILE` is set or not.

_Originally posted by @kuhe in https://github.com/aws/aws-sdk-js-v3/pull/6277#discussion_r1678171599_

**Comment by tfrancois** [comment]
Is there a way to suppress this message when using the `createCredentialChain` method with the `fromEnv` and the default profile configured on a workstation/server?

**Comment by kuhe** [comment]
You should unset the credentials that you aren't using to avoid the warning.

There is also a manual way:
```ts
new Client({
  logger: {
	trace() {},
	debug() {},
    info() {}, 
    warn(arg) {
      if (arg.includes("Multiple credential sources detected")) {
      } else {
        console.warn(arg);
      }
    },
    error: console.error,
  }
});
```
