### ISSUE TITLE
Headers are ignored for Pinpoint CreateEmailTemplateCommand and UpdateEmailTemplateCommand

### ISSUE THREAD

**Issue by Sin-** [aws/aws-sdk-js-v3#6550]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I wrote a script that is going to create 250 email templates in Pinpoint.
Here is the input for the CreateEmailTemplateCommand that returns a "200 - Created" : 
```
const input = {
        EmailTemplateRequest: {
          HtmlPart: '<p>Lorem Ipsum</p>',
          Subject: templateName,
          Headers: [
            {
              Name: 'List-Unsubscribe',
              Value:
                '<mailto:*****@***.***>,<https://**********/pinpoint/unsubscribe/{{Address}}>',
            },
            {
              Name: 'List-Unsubscribe-Post',
              Value: 'List-Unsubscribe=One-Click',
            },
          ],
        },
        TemplateName: templateName,
      };      
```

But when I go check in the console, everything is good with the templates, except they have no headers set.
I also tried to add them with an UpdateEmailTemplateCommand, with no success.

Am I missing something?

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### SDK version number

@aws-sdk/client-pinpoint@3.540.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node v20.17.0

### Reproduction Steps

```
import { PinpointClient, CreateEmailTemplateCommand } from "@aws-sdk/client-pinpoint"; // ES Modules import
const client = new PinpointClient(config);
const input = {
        EmailTemplateRequest: {
          HtmlPart: '<p>Lorem Ipsum</p>',
          Subject: 'templateName',
          Headers: [
            {
              Name: 'List-Unsubscribe',
              Value:
                '<mailto:*****@***.***>,<https://*******.***/pinpoint/unsubscribe/{{Address}}>',
            },
            {
              Name: 'List-Unsubscribe-Post',
              Value: 'List-Unsubscribe=One-Click',
            },
          ],
        },
        TemplateName: 'templateName',
      };      
const command = new CreateEmailTemplateCommand(input);
const response = await client.send(command);
```

### Observed Behavior

CreateEmailTemplate command worked and returned the Created message, but the Headers part of the query was ignored and no headers were set

### Expected Behavior

Headers to be taken into account and set on the template

**Comment by aBurmeseDev** [comment]
Hi @Sin- thanks for reaching out. 

I tried your code on my end and the headers were correctly set and visible in the AWS Console. I suggest upgrading to the latest version and attempting again to see if that resolves the issue.

Additionally, you mentioned a script that creates 250 templates. Could you confirm if the headers are also missing when creating a single template? This might help narrow down the root cause of the problem.
>I wrote a script that is going to create 250 email templates in Pinpoint.

Best,
John

**Comment by Sin-** [comment]
Hello, I updated the client-pinpoint to 3.668.0 but it didn't change anything.
I did not run the script that creates all the templates yet, I tested my script with only one template and this is when I noticed the issue
