### ISSUE TITLE
DynamoDB PutItemCommand returning a @smithy/base64 failure

### ISSUE THREAD

**Issue by hbjydev** [aws/aws-sdk-js-v3#6559]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

For some reason, when attempting to insert the following record into a DynamoDB table:
```ts
{
  id: { S: '51e60555-823a-4a3d-850d-0c4812d8b882' },
  site_id: { S: '9ba4ad29-e0d3-4a41-b1f0-313106c1df46' },
  product_id: { N: '12747' },
  ignored: { B: false },
  pushed: { B: false }
}
```
I get an error back from `@smithy/base64`: `@smithy/util-base64: toBase64 encoder function only accepts string | Uint8Array.`

I'm aware that the two `B` vals are booleans, not strings, but seemingly those are what the types for `AttributeValue` accept?

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### SDK version number

@aws-sdk/client-dynamodb@^3.654.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node.js 20 Lambda Runtime

### Reproduction Steps

```ts
const record = {
  id: { S: '51e60555-823a-4a3d-850d-0c4812d8b882' },
  site_id: { S: '9ba4ad29-e0d3-4a41-b1f0-313106c1df46' },
  product_id: { N: '12747' },
  ignored: { B: false },
  pushed: { B: false }
};

const cmd = new dynamodb.PutItemCommand({
  TableName: 'my-table',
  Item: record,
});

await client.send(cmd); // this errors out
```

### Observed Behavior

```
{
    "errorType": "Error",
    "errorMessage": "@smithy/util-base64: toBase64 encoder function only accepts string | Uint8Array.",
    "stack": [
        "Error: @smithy/util-base64: toBase64 encoder function only accepts string | Uint8Array.",
        "    at Object.toBase64 [as base64Encoder] (/var/runtime/node_modules/@aws-sdk/node_modules/@smithy/util-base64/dist-cjs/toBase64.js:15:15)",
        "    at Object.B (/var/runtime/node_modules/@aws-sdk/client-dynamodb/dist-cjs/index.js:2545:33)",
        "    at Object.visit (/var/runtime/node_modules/@aws-sdk/client-dynamodb/dist-cjs/index.js:988:22)",
        "    at se_AttributeValue (/var/runtime/node_modules/@aws-sdk/client-dynamodb/dist-cjs/index.js:2544:25)",
        "    at /var/runtime/node_modules/@aws-sdk/client-dynamodb/dist-cjs/index.js:2923:16",
        "    at Array.reduce (<anonymous>)",
        "    at se_PutItemInputAttributeMap (/var/runtime/node_modules/@aws-sdk/client-dynamodb/dist-cjs/index.js:2919:32)",
        "    at Item (/var/runtime/node_modules/@aws-sdk/client-dynamodb/dist-cjs/index.js:2910:18)",
        "    at applyInstruction (/var/runtime/node_modules/@aws-sdk/node_modules/@smithy/smithy-client/dist-cjs/index.js:1090:27)",
        "    at take (/var/runtime/node_modules/@aws-sdk/node_modules/@smithy/smithy-client/dist-cjs/index.js:1058:5)"
    ]
}
```

### Expected Behavior

I expected the record to be inserted normally

**Comment by hbjydev** [comment]
@aBurmeseDev don't suppose there are any updates on this?

**Comment by aBurmeseDev** [comment]
Hi @hbjydev - thanks for reaching out and apologies for the delay.

For Boolean, please use `BOOL`. You can refer to this docs page from DynamoDB on Data Type Descriptors: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html#HowItWorks.DataTypeDescriptors


```js
   ignored: { BOOL: false },
   pushed: { BOOL: false } 
```

Hope that helps!
Best,
John

**Comment by hbjydev** [comment]
Hi, thanks John, that worked perfectly! Bit of oversight on my part that's had me scratching my head for days on end! 😅 

Appreciate the eyes on, have a good day :)
