### ISSUE TITLE
client-b2bi - Support Outbound Transformers through the StartTransformationJob request

### ISSUE THREAD

**Issue by ncalarco** [aws/aws-sdk-js-v3#6570]
### Describe the feature

Support for Outbound transformers when using the `StartTransformationJob` API in the SDK (or CLI):

### Use Case

In the client-b2bi documentation it states:

> If you only want to transform EDI (electronic data interchange) documents, you don't need to create profiles, partnerships or capabilities. Just create and configure a transformer, and then run the StartTransformerJob API to process your files.

This is the exact functionality we need and want to use.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.670.0

### Environment details (OS name and version, etc.)

Windows, NodeJS 18x, cdk/cdk-lib 2.162.1

**Comment by aBurmeseDev** [comment]
Hi @ncalarco - thanks for reaching out.

Could you please provide more details about the feature request you have regarding the `StartTransformerJob` API? I noticed that this API is currently available in the SDKs and CLI (code example for JavaScript below). However, I'm not entirely clear on what specific aspect or enhancement you're looking for. 

```js
import { B2biClient, StartTransformerJobCommand } from "@aws-sdk/client-b2bi"; // ES Modules import
const client = new B2biClient(config);
const input = { // StartTransformerJobRequest
  inputFile: { // S3Location
    bucketName: "STRING_VALUE",
    key: "STRING_VALUE",
  },
  outputLocation: {
    bucketName: "STRING_VALUE",
    key: "STRING_VALUE",
  },
  transformerId: "STRING_VALUE", 
};
```
JavaScript API Reference Docs: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/b2bi/command/StartTransformerJobCommand/

Looking forward to hear back!
