### ISSUE TITLE
Missing Events from SES

### ISSUE THREAD

**Issue by n-for-all** [aws/aws-sdk-js-v3#6617]
### Describe the issue

The docs shows that i can subscribe to 10 events
https://docs.aws.amazon.com/ses/latest/dg/event-publishing-retrieving-sns-examples.html

But in the code it show that notificationType is limited to 3 only
https://github.com/aws/aws-sdk-js-v3/blob/e5a04d0396396a84074ea330073bcf06f8fa1f82/clients/client-
ses/src/models/models_0.ts#L3949

Can i subscribe to the other events?

### Links

https://docs.aws.amazon.com/ses/latest/dg/event-publishing-retrieving-sns-examples.html

**Comment by mbayucot** [comment]
Hi, could you assign this issue to me?

**Comment by zshzbh** [comment]
Hey @mbayucot,

I can assign it to you once you open a PR or come up with a solution to fix this issue. If you want to contribute and create a pr to fix it, you can mention this issue so it will auto link to this issue. 

Thanks!
Maggie

**Comment by mbayucot** [comment]
Hi @zshzbh,

Got it, thanks. I’ll take a look and work on a fix.

**Comment by zshzbh** [comment]
@mbayucot Thanks!
