### ISSUE TITLE
Expo - TypeError: 0, import_protocols.resolvedPath is not a function 

### ISSUE THREAD

**Issue by princekurt** [aws/aws-sdk-js-v3#6626]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

This bug has been happening with a brand new expo build. I have seen the issue on Expo 50 and Expo 51. Anytime you try to use the LocationClient from `@aws-sdk/client-location@6.682` it gives off the error of `[TypeError: 0, import_protocols.resolvedPath is not a function (it is undefined)]`

I have tried to work through the issue by moving the @aws-sdk library all the way back to 6.427 with no luck. I have attempted different versions of Expo, and have turned hermes off and on with no difference. 

```{
  "name": "aws-expo-text",
  "main": "expo-router/entry",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start",
    "reset-project": "node ./scripts/reset-project.js",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "test": "jest --watchAll",
    "lint": "expo lint"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@aws-sdk/client-cognito-identity": "^3.685.0",
    "@aws-sdk/client-location": "^3.682.0",
    "@aws-sdk/credential-provider-cognito-identity": "^3.685.0",
    "@expo/vector-icons": "^14.0.2",
    "@react-navigation/native": "^6.0.2",
    "expo": "~51.0.28",
    "expo-constants": "~16.0.2",
    "expo-font": "~12.0.9",
    "expo-linking": "~6.3.1",
    "expo-location": "^17.0.1",
    "expo-router": "~3.5.23",
    "expo-splash-screen": "~0.27.5",
    "expo-status-bar": "~1.12.1",
    "expo-system-ui": "~3.0.7",
    "expo-web-browser": "~13.0.3",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.74.5",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-get-random-values": "^1.11.0",
    "react-native-reanimated": "~3.10.1",
    "react-native-safe-area-context": "4.10.5",
    "react-native-screens": "3.31.1",
    "react-native-web": "~0.19.10"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/jest": "^29.5.12",
    "@types/react": "~18.2.45",
    "@types/react-test-renderer": "^18.0.7",
    "jest": "^29.2.1",
    "jest-expo": "~51.0.3",
    "react-test-renderer": "18.2.0",
    "typescript": "~5.3.3"
  },
  "private": true
}
```

### SDK version number

@aws-sdk/package-name@version, ...

### Which JavaScript Runtime is this issue in?

React Native

### Details of the browser/Node.js/ReactNative version

react-native-cli: 2.0.1 react-native: 0.74.5

### Reproduction Steps

1. Create a brand new project
2. Install @aws-sdk/client-location @aws-sdk/client-cognito-identity @aws-sdk/credential-provider-cognito-identity
3. Create a LocationClient and send a SearchPlaceIndexForPositionCommand() 
4. Run the project on web, android, or iOS. 

#### Install Project
1. Run `npx create-expo-app@latest aws-expo-test` to create the project. 
2. `cd aws-expo-test`
3. `npm install @aws-sdk/client-location @aws-sdk/client-cognito-identity @aws-sdk/credential-provider-cognito-identity`

#### Update _Layout.tsx File
```js
try {
    const AWS_REGION = 'region-name';
    const IDENTITY_POOL_ID = 'cognito-idenity-pool';
    
    const LOCATION_PLACE_INDEX = 'index-name';
    
    const locationClient = new LocationClient({
            region: AWS_REGION,
            credentials: fromCognitoIdentityPool({
              client: new CognitoIdentityClient({ region: AWS_REGION }),
              identityPoolId: IDENTITY_POOL_ID,
            }),
          });
    
    const params: SearchPlaceIndexForPositionCommandInput = {
      IndexName: LOCATION_PLACE_INDEX,
      Position: [-96.80667, 32.78306],
      MaxResults: 10,
    };
    
    const command = new SearchPlaceIndexForPositionCommand(params);
    
    const response = await locationClient.send(command);
} catch (err) {
      console.log(err);
}

```

Put this code into the _layout.tsx file on the useEffect there and it will attempt to run this on the start of the app. 

Run `npm run ios` or `npm run android` or `npm run web` and all will fail with the same error. 

### Observed Behavior

The `locationClient.send(command)` call returns the error `TypeError: 0, import_protocols.resolvedPath is not a function`

### Expected Behavior

It should return a list of locations from the AWS Location Service. 

### Additional Information/Context

Attempted Fixes: 
- Turn off Hermes 
- Downgrade Expo to 50
- Run React 0.70.2
- Downgrade @aws-sdk/client-location all the way down to 6.427

**Comment by mbencomo** [comment]
Also seeing this issue when using @aws-sdk/lambda-client `InvokeCommand`

**Comment by JuanDArdilaG** [comment]
Same here using `@aws-sdk/client-s3` v3.687.0 in a react native expo app

**Comment by aleksnied** [comment]
Seeing it with @aws-sdk/s3-request-presigner getSignedUrl 3.685.0

**Comment by sab5449** [comment]
Seeing this issue when using @aws-sdk/lambda-client when calling lambdaClient.send

**Comment by hokagedemehin** [comment]
This issue is still showing up in was s3 client of version 3.688.0.

For context, this happens at this command

await s3Client.send(...);

**Comment by fazrimo** [comment]
same issue when using `@aws-sdk/client-workmailmessageflow`

**Comment by zshzbh** [comment]
Hey,

Could you please confirm that you have already added [additional packages](https://github.com/aws/aws-sdk-js-v3?tab=readme-ov-file#getting-started) for react native project? 


If you are consuming modular AWS SDK for JavaScript on react-native environments, you will need to add and import following polyfills in your react-native application:

[react-native-get-random-values](https://www.npmjs.com/package/react-native-get-random-values)
[react-native-url-polyfill](https://www.npmjs.com/package/react-native-url-polyfill)
[web-streams-polyfill](https://www.npmjs.com/package/web-streams-polyfill)
```js
import "react-native-get-random-values";
import "react-native-url-polyfill/auto";
import "web-streams-polyfill/dist/polyfill";

import { DynamoDB } from "@aws-sdk/client-dynamodb";
```
Specifically Metro bundler used by react-native, enable Package Exports Support:

https://metrobundler.dev/docs/package-exports/
https://reactnative.dev/blog/2023/06/21/package-exports-support

**Comment by JuanDArdilaG** [comment]
Hi @zshzbh
I've installed and add the import for the polyfills just before the import of my library
```javascript
import "react-native-get-random-values";
import "react-native-url-polyfill/auto";
import "web-streams-polyfill/dist/polyfill";

import { S3Client, ListObjectsV2Command } from "@aws-sdk/client-s3";
```
The error remains the same.
Not sure if there are any configuration missing related to metro and Package Exports, that part isn't clear to me.

**Comment by mikeholloway-kaluza** [comment]
Hey 👋 I wanted to jump in here and say that I've observed the exact same problem as this but I'm not using Expo or RN. It seems to be an issue introduced sometime after `v3.574.0` of `@aws-sdk/client-s3` and potentially related to https://github.com/aws/aws-sdk-js-v3/pull/6088

**Comment by JulianHillworth** [comment]
Ok team, after spending about 5 hours on this and scowling through multiple package-lock.json files on multiple git histories I uncovered root cause.  @smithy/core (sub dependency) an internal library for the AWS SDK updated itself to 2.5.1. from 2.4.8

In your package.json dependencies just put "@smithy/core": "2.4.8" to enforce the last known working version.  Error disappears and uploading to s3 recommenced!

**Comment by kuhe** [comment]
v2.5.2 of `@smithy/core` was released https://www.npmjs.com/package/@smithy/core/v/2.5.2 with the above PR.

This should fix the issue. To get this version, reinstall the latest AWS SDK client version(s) without a lockfile limiting the version of `@smithy/core`.

**Comment by zshzbh** [comment]
Hey @aashishshrestha5532 

Could you please try @smithy/core@2.5.2 as @kuhe  mentioned in this [comment](https://github.com/aws/aws-sdk-js-v3/issues/6626#issuecomment-2476980175)?

**Comment by aashishshrestha5532** [comment]
@zshzbh @kuhe i tried updating @smith/core and aws client sdk to the latest version but it also didn't help.
<img width="396" alt="Screenshot 2024-12-02 at 09 56 03" src="https://github.com/user-attachments/assets/243f9428-7a0c-450d-beff-5dc34e1ef08c">

**Comment by aashishshrestha5532** [comment]
@zshzbh i even tried updating to @smithy/core to 2.5.2 with aws-sdk of version 3.693.0.

**Comment by zshzbh** [comment]
@aashishshrestha5532 

Could you please share your minimal code reproduction and error msg?
