### ISSUE TITLE
Cognito ListUsersCommand Filter doesn’t return results when using prefix with special character (@)

### ISSUE THREAD

**Issue by julianCast** [aws/aws-sdk-js-v3#6645]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When using AWS Cognito’s `ListUsersCommand` with a filter on the email attribute, attempting to search with a prefix ending in @ (e.g., "email ^= \"julian@\""), no results are returned even if there are users with email addresses starting with julian@ark.com. However, appending an additional character after @ (e.g., "email ^= \"julian@a\""), does return results for users with email addresses that match this prefix.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### SDK version number

@aws-sdk/client-cognito-identity-provider": "3.651.1

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

20

### Reproduction Steps

	1.	Use AWS Cognito’s ListUsersCommand to search for users by email prefix in a specific User Pool.
	2.	Set the filter to match email addresses with a prefix ending in @, as shown below:
	
```tsx
		const response = await cognito.send(
		  new ListUsersCommand({
		    UserPoolId: "pool-id",
		    Filter: 'email ^= "julian@"'
		  })
		);
```

3. Observe the results of the command.

### Observed Behavior

When executing the above code:
- No users are returned for the filter email ^= "julian@", even if users with matching email addresses exist in the User Pool.
- Adding a single character after the @ symbol in the filter (e.g., email ^= "julian@a") correctly returns users whose emails match the specified prefix.

### Expected Behavior

The filter email ^= "julian@" should return all users with email addresses that start with julian@, regardless of what characters come after the @ symbol.

### Possible Solution

The `ListUsersCommand `filter logic in AWS Cognito should recognize and handle special characters such as @ in a prefix context, even if they appear at the end of the filter string. This would enable searching for email prefixes with special characters without requiring additional characters afterward.

### Additional Information/Context

If we have a list of users like:
`julian@ark.com`, `julian-the-best@ark.com`, `julian-the-worst@ark.com`

We may want to just look for `julian@` to exclude the rest.

**Comment by zshzbh** [comment]
Hey @julianCast 

Thanks for the feedback!  However I can't reproduce this issue

The code I have - 

```js
import {
  CognitoIdentityProviderClient,
  ListUsersCommand,
} from "@aws-sdk/client-cognito-identity-provider"; // ES Modules import

const client = new CognitoIdentityProviderClient({ region: "us-east-1" });
const input = {
  // ListUsersRequest
  UserPoolId: "us-east-1_XXXXXX", // required
  // AttributesToGet: ["email"],
  "Filter": `email ^= "zshzbh"`, //I tried "zshzbh", "zshzbh@", both are returning the correct result
};
const command = new ListUsersCommand(input);
const response = await client.send(command);

console.log(response.Users);

```
The result I got  - 

```log
[
  {
    Attributes: [ [Object], [Object], [Object] ],
    Enabled: true,
    UserCreateDate: 2024-11-12T20:57:44.113Z,
    UserLastModifiedDate: 2024-11-12T20:57:44.113Z,
    UserStatus: 'FORCE_CHANGE_PASSWORD',
    Username: 'c4489418-60b1-70cb-f9ab-XXXXXX'
  }
]
```
This is my user attribute - 
<img width="1307" alt="Screenshot 2024-11-12 at 1 14 49 PM" src="https://github.com/user-attachments/assets/2fc0a735-20fb-4349-9443-2f6dfb0a0065">

The version I have         "@aws-sdk/client-cognito-identity-provider": "3.651",, I also tried on latest version and both are working as expected.

**Comment by zshzbh** [comment]
I would like to suggest to upgrade the sdk version, close and reopen the project and try again.

**Comment by julianCast** [comment]
Actually, it's reproducible even in AWS console
![image](https://github.com/user-attachments/assets/89bd787a-f940-4c7f-9c71-e3d8a9f77cc6)

**Comment by zshzbh** [comment]
Hey @julianCast ,

<img width="1102" alt="Screenshot 2024-11-13 at 9 45 13 AM" src="https://github.com/user-attachments/assets/6be9377f-10a7-4904-b026-435feace7f87">


I can't reproduce this issue in console. I used verified and unverified email addresses. This issue doesn't come from SDK and I think this issue might be related to the region. Which region are you using?

**Comment by julianCast** [comment]
M3MzVkNTkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bkh5fiEu571B8Ht4kYzPvhI172wzdmWaQJGkBx8fRRM">
> I can't reproduce this issue in console. I used verified and unverified email addresses. It seems that this issue doesn't come from SDK. I think this issue might be related to the region. Which region are you using?

That's very interesting, we are in Ireland `eu-west-1`, how about you?

**Comment by zshzbh** [comment]
I created an internal ticket,  ref - V1587958012.

I will keep you posted if I have any updates. 

Thanks!

**Comment by zshzbh** [comment]
Hey @julianCast ,

I just got back from service team. They can't reproduce this issue in eu-west-1 region either. 

This is the cli and response they provided: 
``` cli
pashikal@bcd074638dd6 ~ % aws cognito-idp list-users --user-pool-id eu-west-1_u2jGHEOz3 --filter "email ^= \"mark.mercurio10@\""  
```
response: 
``` json
{
    "Users": [
        {
            "Username": "markmerc",
            "Attributes": [
                {
                    "Name": "email",
                    "Value": "mark.mercurio10@gmail.com"
                },
                {
                    "Name": "sub",
                    "Value": "429574a4-a081-7006-093f-94b7d6ede76b"
                }
            ],
            "UserCreateDate": "2024-11-21T13:01:54.500000-08:00",
            "UserLastModifiedDate": "2024-11-21T13:01:54.500000-08:00",
            "Enabled": true,
            "UserStatus": "FORCE_CHANGE_PASSWORD"
        }
    ]
}
```

**Comment by zshzbh** [comment]
I don't think the error is from AWS SDK or Cognito service. 

I'm wondering if this behavior only happens in this user pool because some configs or settings?  Could you please try to create a new test user pool and try to reproduce this issue?

**Comment by julianCast** [comment]
Thank you for all the tests. I've discovered something I can't understand the reason:

The only search that causes this issue is `julian@`, I have tried with other searches, ending with `@`, and I successfully got the results.

I've literally copied the email to avoid manual mistakes, but same thing. 

For context, I have `julian@ark.com`, and a few with `julian+123456@ark.com`. Same test with different names work so I'm at a loss here, but at least it's not happening for all users somehow.

**Comment by zshzbh** [comment]
I tried this email address and still I can't see any issues. I don't have any other suggestions now as I can't reproduce this issue. 

 As long as we found the workaround, I think we are good to use fully copied email addresses.
<img width="1350" alt="Screenshot 2024-11-25 at 4 47 46 PM" src="https://github.com/user-attachments/assets/3100da07-3356-471e-8ce8-a770bf09d5ec">

**Comment by julianCast** [comment]
What a mistery! But yep, thank you so much for your help!
