### ISSUE TITLE
DAX support missing in dynamodb-client v3

### ISSUE THREAD

**Issue by arthurshir** [aws/aws-sdk-js-v3#6650]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Title is self explanatory. Its been two years since this has since been reported https://github.com/aws/aws-sdk-js-v3/issues/4263

This does not pertain to https://www.npmjs.com/package/@aws-sdk/client-dax, which is a low-level SDK for managing clusters

This breaks 3 of the Amazon Leadership Principles:
* Customer Obsession & Earn Trust: This decision to not support DAX in V3 breaks trust with developers that follow your team's recommendations to upgrade to the latest version, especially when taking the timeframe into account
* Insist on the Highest Standards: Abstracting team politics away from your developers is an obvious standard to follow. Which makes @kellertk 's comments a clear miss in this LP regarding this matter https://github.com/aws/aws-sdk-js-v3/issues/4263#issuecomment-2035584918

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### SDK version number

@aws-sdk/client-dynamodb@3.687.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v22.10.0

### Reproduction Steps

DAX support missing in dynamodb-client v3

### Observed Behavior

DAX support missing in dynamodb-client v3

### Expected Behavior

DAX support within dynamodb-client v3

**Comment by kuhe** [comment]
The DynamoDB DAX team is working on a new version of a JavaScript DAX client, and will announce it when they are ready. We do not have an estimated release date for this feature.
