### ISSUE TITLE
SESv2 SendBulkEmailCommand: Template contains unsupported operations

### ISSUE THREAD

**Issue by BabyDino** [aws/aws-sdk-js-v3#6657]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When using the `SendBulkEmailCommand` with in-line templates, Handlebars conditional statements are not accepted by the SDK.

`{{#if var}}{{var}}{{/if}}` throws a BadRequestException:

```
{
  "status": 400,
  "name": "BadRequestException",
  "message": "Template contains unsupported operations.",
  "details": {}
}
```

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### SDK version number

@aws-sdk/client-sesv2@latest

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.17.0

### Reproduction Steps

```
new SendBulkEmailCommand({
        FromEmailAddress: 'Me <me@me.com>,
        DefaultContent: {
          Template: {
            TemplateContent: {
              Subject: 'Hello world!',
              Text: 'Dear {{#if firstName}} {{firstName}}{{/if}}',
              Html: '<html>Dear {{#if firstName}} {{firstName}}{{/if}}</html>',
            },
            TemplateData: JSON.stringify({ firstName: 'John' }),
          },
        },
        BulkEmailEntries: ...
      });
```

throws the following exception:

```
{
  "status": 400,
  "name": "BadRequestException",
  "message": "Template contains unsupported operations.",
  "details": {}
}
```

Using `#if` conditional statements is supported, according to the official [docs](https://docs.aws.amazon.com/ses/latest/dg/send-personalized-email-advanced.html).

### Observed Behavior

```
BadRequestException: Template contains unsupported operations.
    at de_BadRequestExceptionRes (/home/me/dev/project/node_modules/@aws-sdk/client-sesv2/dist-cjs/index.js:3438:21)
    at de_CommandError (/home/me/dev/project/node_modules/@aws-sdk/client-sesv2/dist-cjs/index.js:3358:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/me/dev/project/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
    at async /home/me/dev/project/node_modules/@smithy/core/dist-cjs/index.js:168:18
    at async /home/me/dev/project/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
    at async /home/me/dev/project/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:34:22
    at async Object.email (/home/me/dev/project/dist/src/api/template/controllers/test.js:107:30)
```

### Expected Behavior

Expect the template to send. In case of renderfailures, this is by the configuration set.

**Comment by RanVaknin** [comment]
Hi @BabyDino ,

You are using the wrong API. the docs you linked was for the legacy SES client and not the newer SESv2 client which you are attempting to use in your repro code. 

AFAIK SESv2 does not support conditional statements using handlebars. You can use SES's (v1) `SendBulkTemplatedEmail` API to create a template with a conditional statement and then use it in your emails:

```js

import { SESClient, CreateTemplateCommand, SendBulkTemplatedEmailCommand } from "@aws-sdk/client-ses";

const sesClient = new SESClient({ region: "us-east-1" });

try {
    await sesClient.send(new CreateTemplateCommand({
        Template: {
            TemplateName: "MyTemplate",
            SubjectPart: "Hello world!",
            TextPart: "Dear {{#if firstName}} {{firstName}}{{/if}}",
            HtmlPart: "<html>Dear {{#if firstName}} {{firstName}}{{/if}}</html>"
        }
    }));

    const response = await sesClient.send(new SendBulkTemplatedEmailCommand({
        Source: "rvaknin@amazon.com",
        Template: "MyTemplate",
        Destinations: [{
            Destination: {
                ToAddresses: ["foo@bar.com"],
            },
            ReplacementTemplateData: JSON.stringify({ firstName: "Joe" })
        }],
        DefaultTemplateData: JSON.stringify({ firstName: "" })
    }));

    console.log("Email sent successfully:", response);
} catch (error) {
    console.error("Error:", error);
}
```

Thanks,
Ran~

**Comment by RanVaknin** [comment]
Hi @BabyDino ,

Thanks for the clarification. I agree, this seems like a bug with the service itself.

I have created an internal ticket with the SES service team (ticket ID `#P170912725`). We will update you when we hear back.
Thanks,
Ran~

**Comment by RanVaknin** [comment]
Hi @BabyDino ,

I heard back from the service team:

>Inline template – The Template resource is not used, but rather, the subject and body of the email containing variables (placeholders) inline with the written content along with the values for those placeholder variables are provided when calling either the SendEmail or SendBulkEmail v2 API operations.

https://docs.aws.amazon.com/ses/latest/dg/send-personalized-email-api.html

>Amazon SES supports only simple substitions when you send email using the SendEmail or SendBulkEmail operations and you provide the full template content in the request.

https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_Template.html#SES-Type-Template-TemplateContent

Inline templates do not support conditional statements.  I have requested that the service team add some clarifications to their docs about it for future use. 

Thanks,
Ran~

**Comment by diego-sepulveda-lavin** [comment]
I encountered the same problem, even though I wasn't using conditional statements. After extensive debugging, I discovered that the issue was caused by using snake_case variables in the inline template.

Initially, I had `{{no_reply}}`, but after changing it to `{{noReply}}`, the error disappeared. I also found out that nested properties are not supported either. The documentation should provide a clearer explanation of this limitation.

**Comment by RanVaknin** [comment]
Feel free to leave documentation feedback directly with the SES service team [here](https://docs-feedback.aws.amazon.com/feedback.jsp?hidden_service_name=SES&topic_url=https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_SendBulkEmail.html).
