### ISSUE TITLE
Can not delete EventBridge rule target & EventBridge rule

### ISSUE THREAD

**Issue by lampvux** [aws/aws-sdk-js-v3#6671]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I used AWS sdk v3 to delete eventbridge Rule Target & Rule, the response returned with both httpStatusCode 200. But the rule does not removed.

I used this aws lambda function to invoke :
```js
    import {
      RemoveTargetsCommand,
      EventBridgeClient,
      DeleteRuleCommand
    } from "@aws-sdk/client-eventbridge";

    export const handler = async (event, context) => {
      try {
        // after delete an webhook, delete the rule target in event bridge
        const eventbridgeConfig = {};
        const client = new EventBridgeClient(eventbridgeConfig);
        const removeTargetsParams = {
          EventBusName: "lam",
          Force: true,
          Ids: [`my-id`], // required
          Rule: "my-rule", // required
        };
    
        const command = new RemoveTargetsCommand(removeTargetsParams);
        const response = await client.send(command);
    
        if (response.$metadata.httpStatusCode === 200) {
          // after the api destination is deleted, delete the rule in event bridge
          const deleteRuleParams = {
            EventBusName: process.env.EVENTBUS_NAME || 'default',
            Force: true,
            Name: "my-rule", // required
          };
          
          const deleterulecommand = new DeleteRuleCommand(deleteRuleParams);
          const response = await client.send(deleterulecommand);      
        }
      } catch (err) {
        console.error(err);
      }
    };
```

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### SDK version number

"@aws-sdk/client-eventbridge@3.637.0"

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

20.16.0

### Reproduction Steps

use the lambda function above and test it with the id target rule & rule name 

### Observed Behavior

returned both success with delete target & rule : 

    {
      '$metadata': {
        httpStatusCode: 200,
        requestId: '20ab194e-93ae-4db9-b08b-80ca7195f59e',
        extendedRequestId: undefined,
        cfId: undefined,
        attempts: 1,
        totalRetryDelay: 0
      },
      FailedEntries: [],
      FailedEntryCount: 0
    }
    
  But no rule was deleted. I checked in the AWS Dashboard Console

### Expected Behavior

EventBridge Rule deleted

**Comment by RanVaknin** [comment]
Hi @lampvux ,

Thanks for reaching out. This sounds like an API limitation, and not something related to the SDK. 

From the Eventbridge docs:

>When you delete a rule, incoming events might continue to match to the deleted rule. Allow a short period of time for changes to take effect.

Are you able to see the rule deleted if you wait a bit?

Thanks,
Ran~
