### ISSUE TITLE
High License and Operational Issues in Transitive Dependencies

### ISSUE THREAD

**Issue by Pavan1925** [aws/aws-sdk-js-v3#6680]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Hi team,

There are couple of Transitive Dependency which has License issues and Operational issues.
I have attached file with related issues.

Please take a look and upgrade accordingly.

[Black Duck _ trellix-products_xdr-alert-management-api _ v6.0.8.pdf](https://github.com/user-attachments/files/17825987/Black.Duck._.trellix-products_xdr-alert-management-api._.v6.0.8.pdf)

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### SDK version number

@aws-sdk/client-cloudwatch@3.632.0, @aws-sdk/client-secrets-manager@3.491.0, @aws-sdk/client-sts@3.490.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v22.2.0

### Reproduction Steps

NA

### Observed Behavior

There are multiple High License and Operational Issues in Transitive Dependencies

### Expected Behavior

There Shouldn't be any High License and Operational Issues in Transitive Dependencies

**Comment by zshzbh** [comment]
Hey @Pavan1925  

This is the license - https://github.com/smithy-lang/smithy-typescript/blob/main/packages/core/package.json#L55
And this is the license file - https://github.com/smithy-lang/smithy-typescript/blob/main/packages/core/LICENSE

There's a recognized SPDX identifier in all packages - https://spdx.org/licenses/Apache-2.0.html
