### ISSUE TITLE
Missing VoiceId for Patrick

### ISSUE THREAD

**Issue by anujgawde** [aws/aws-sdk-js-v3#6685]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I am trying to build a text-to-speech feature which will be able to read long articles. I found voice name 'Patrick, Male' suitable for my use case (tested on the console). When I try to pass the VoiceId from my Node.js application, the IDE prompts me that the VoiceId does not exist in the model.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### SDK version number

@aws-sdk/package-name@version^3.693.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.10.0

### Reproduction Steps

```
      const params = {
        OutputS3BucketName: process.env.AWS_TTS_BUCKET_NAME,
        OutputS3KeyPrefix: keyPrefix,
        OutputFormat: OutputFormat.MP3,
        Text: textContent,
        Engine: Engine.LONG_FORM,
        
        // Voice Id for Patrick is missing from the model (This will result in an error):
        VoiceId: VoiceId.Patrick,
      };

      // Start speech synthesis task
      const command = new StartSpeechSynthesisTaskCommand(params);
      const response = await this.pollyClient.send(command);
```

### Observed Behavior

The IDE does not let me pass my desired VoiceId

<img width="578" alt="Screenshot 2024-11-21 at 3 15 59 PM" src="https://github.com/user-attachments/assets/f92b3764-0317-4f62-aac3-4a820c5e8b3f">

### Expected Behavior

I should be able to use my desired VoiceId

### Possible Solution

Update the VoiceId model to include a value for 'Patrick'

**Comment by zshzbh** [comment]
Hey @anujgawde ,

It seems that you are using this [StartSpeechSynthesisTaskCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/polly/command/StartSpeechSynthesisTaskCommand/) from [@aws-sdk/client-polly](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-polly). 


I just checked [VoiceId](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-polly/Variable/VoiceId/) page in AWS JS SDK doc, it seems that AWS JS SDK doesn't support  `Patrick`. 

Please choose other preferred VoiceId.

Thanks!
Maggie

**Comment by anujgawde** [comment]
Hey @zshzbh ,

Thanks for sharing the info! I’ll update the implementation and choose an alternate VoiceId from the supported options. Appreciate the heads-up!

Best regards,
Anuj
