### ISSUE TITLE
SSO requests ignore proxy configuration

### ISSUE THREAD

**Issue by otaviomacedo** [aws/aws-sdk-js-v3#6687]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The SDK gets credentials via SSO directly (ignoring proxy configuration) provided in the `fromIni()` method.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### SDK version number

@aws-sdk/credential-providers@3.696.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node version: v22.9.0

### Reproduction Steps

0. Precondition: the SSO set-up has been done (creating user, `aws sso login` etc).
1. Start a proxy on port 8080. I'm using [mitmproxy](https://mitmproxy.org/).
2. [Install](https://docs.mitmproxy.org/stable/concepts-certificates/) the CA certificate.
3. Run the following code:

```ts
    const agent = new ProxyAgent({
      ca: fs.readFileSync('/path/to/pem', { encoding: 'utf-8' }),
      getProxyForUrl: () => Promise.resolve('http://localhost:8080'),
    });

    const provider = fromIni({
      profile: 'test',
      ignoreCache: true,
      clientConfig: {
        requestHandler: {
          connectionTimeout: 30000,
          requestTimeout: 10000,
          httpsAgent: agent,
          httpAgent: agent,
        },
      },
    });

    console.log(await provider());
```

4. Watch the proxy logs.

### Observed Behavior

The TypeScript program will print the AWS credentials, but the proxy won't show any activity. To further confirm, if I shut down the proxy, the credentials are still retrieved.

### Expected Behavior

Proxy show activity when up and request fail when proxy is down.

### Additional Information/Context

Related issue: https://github.com/aws/aws-cdk/issues/32208

**Comment by kuhe** [comment]
a fix for this was released in https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.699.0
