### ISSUE TITLE
Amazon Connect Client break between version 3.696.0 and 3.699.0

### ISSUE THREAD

**Issue by zyrorl** [aws/aws-sdk-js-v3#6695]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The interface for ListRoutingProfilesCommandOutput has broken, and is now missing the RoutingProfileSummaryList attribute in the api.

### Regression Issue

- [x] Select this option if this issue appears to be a regression.

### SDK version number

@aws-sdk/client-connect@3.699.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v22.10.0

### Reproduction Steps

-

### Observed Behavior

-

### Expected Behavior

-

### Possible Solution

downgrade to version 3.696.0

**Comment by RanVaknin** [comment]
Hi @zyrorl ,

I'm not sure why you are seeing a breaking change. I dont see a change in interface:

```js
import {ListRoutingProfilesCommandOutput, ListRoutingProfilesCommand, ConnectClient} from '@aws-sdk/client-connect'

const client = new ConnectClient({
  region: "us-east-1"
})

async function run(){
  try {
    const command = new ListRoutingProfilesCommand({
      InstanceId: "REDACTED",
    });
  
    const response: ListRoutingProfilesCommandOutput = await client.send(command);
  
    console.log(response.RoutingProfileSummaryList);
  
    if (response.RoutingProfileSummaryList) {
      response.RoutingProfileSummaryList.forEach(profile => {
        console.log(profile.Name);
        console.log(profile.Arn);
      });
    }
  
  } catch (error) {
    console.error(error);
  }
}

run()
  

```

results in:

```console
$ npm ls
connect-try@1.0.0 /Users/rvaknin/test_folder/connect-try
└── @aws-sdk/client-connect@3.699.0

$ tsc sample.ts 
$ node sample.js
[
  {
    Arn: 'arn:aws:connect:us-east-1:REDACTED:instance/REDACTED/routing-profile/REDACTED',
    Id: 'REDACTED',
    LastModifiedRegion: 'us-east-1',
    LastModifiedTime: 2024-05-17T04:48:07.110Z,
    Name: 'Basic Routing Profile'
  }
]
Basic Routing Profile
arn:aws:connect:us-east-1:REDACTED:instance/REDACTED/routing-profile/REDACTED
```

The only change I see is this https://github.com/aws/aws-sdk-js-v3/commit/a83926c90ed8eb4608f987faa9803e805f5ea5ff#diff-164fa22f7a2439af11297a84706a2efd3c0be36a3d5f92ab06e16c9436646e00L3

Which changed the imports to [new model file](https://github.com/aws/aws-sdk-js-v3/blob/a83926c90ed8eb4608f987faa9803e805f5ea5ff/clients/client-connect/src/models/models_2.ts#L549) which has the `RoutingProfileSummaryList` in question. 

If I had to guess what happened is that your project has multiple versions of the same `@aws-sdk/client-connect` dependency.  You can check that by running:

```console
$ npm ls -a @aws-sdk/client-connect
```

and then see the dependency tree to make sure all of them point to the latest 3.699.0 by using `npm dedupe`, or by deleting your node_modules and pacakge-lock.json and running `npm install` again. 

Let me know if this helped.
All the best,
Ran~
