### ISSUE TITLE
(short issue description)

### ISSUE THREAD

**Issue by GeorgeBrn** [aws/aws-sdk-js-v3#6707]
### Describe the issue

This documentation is absolutely deplorable, without chatGPT I would've been unable to use S3. Literally not one word about 'getObjectCommand' returning data in streams and you having to handle the chunks with a promise. All I wanted to do was to upload an image from a nodeJs server and then read it from S3. Of course, this simple task took me several hours because getting the body from an S3 file is apparently a herculean task

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/command/GetObjectCommand/

**Comment by kuhe** [comment]
The linked page states the return type of the body in S3 GetObject is a stream in the section "Example Syntax" and in the section "GetObjectCommand Output".

Also take a look at https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/javascript_s3_code_examples.html#basics.

As part of https://github.com/aws/aws-sdk-js-v3/issues/6691, we will be creating additional documentation for streaming operations.

**Comment by kuhe** [comment]
Using the example from https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/javascript_s3_code_examples.html#basics, you do not need to concatenate into a buffer yourself.

```js
import {
  GetObjectCommand,
  S3Client,
} from "@aws-sdk/client-s3";

const response = await client.send(
  new GetObjectCommand({
    Bucket: bucketName,
    Key: key,
  }),
);

const str = await response.Body.transformToString();
console.log(str); // a string.
```

Alternatively, a byte array

```js
// Uint8Array, which can be converted to Buffer.
const bytes = await response.Body.transformToByteArray();
```

**Comment by kuhe** [comment]
Currently, the developer guide linked above contains more practical examples than the auto-generated API shape documentation you have seen.

We plan to integrate this example into the API docs in a future update.

**Comment by GeorgeBrn** [comment]
Hello, thank you and sorry for my previous comments, the "const str = await
response.Body.transformToString();" works very well and I'm able to get the
body of my s3 files.

Thank you once again!

**Comment by GeorgeBrn** [comment]
Hello, thank you and sorry for my previous comments, the "const byteArray =
await response.Body.transformToString();" works very well and I'm able to
get the body of my s3 files.

Thank you once again!
