### ISSUE TITLE
yarn test:all doesn't run tests written in karma

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#671]
**Describe the bug**
* yarn test:all doesn't run tests written in karma https://github.com/aws/aws-sdk-js-v3/blob/176ec93b9db2dd8a59b196b3c9d80049bc3b8e81/package.json#L17
* Since we've planned to use Jest for future integration tests (example PR https://github.com/aws/aws-sdk-js-v3/pull/580), we should move karma tests to jest

**To Reproduce (observed behavior)**
* Run `yarn test:all`
* Notice that tests are not run for packages which use karma (like hash-blob-browser)

**Expected behavior**
Tests are run for packages which use karma - recommendation is to move them to Jest instead

**Comment by trivikr** [comment]
Documentation on using Jest with Puppeteer https://jestjs.io/docs/en/puppeteer

**Comment by trivikr** [comment]
QAWolf for writing browser tests faster https://www.qawolf.com/

**Comment by AllanFly120** [comment]
Currently we test packages with karma test explicitly like:

https://github.com/aws/aws-sdk-js-v3/blob/15a66c720f49884087126d6d573c64b6a4a16dc5/package.json#L17

We will investigate jest-puppeteer solution. Label this as a feature request.
