### ISSUE TITLE
Missing Installation code for bun

### ISSUE THREAD

**Issue by MohammedAbidNafi** [aws/aws-sdk-js-v3#6734]
### Describe the issue

**Missing Installation Code for Bun**

**Description**
The installation instructions currently lack guidance for setting up the project using the Bun package manager. As Bun is gaining popularity due to its speed and developer-friendly features, including specific installation instructions will enhance the usability of the project for developers who prefer Bun.

**Steps to Reproduce**
Attempt to set up the project using Bun instead of npm/yarn.
Notice the absence of instructions specific to Bun in the documentation.

**Expected Behavior**
Comprehensive installation instructions should be provided for Bun, alongside npm and yarn, to ensure compatibility and accessibility for all developers.

**Proposed Solution**
Add a section in the installation guide detailing how to set up the project using Bun, including commands for installing dependencies and running the project.

**Additional Context**
Providing Bun support could make the project more inclusive and appealing to a broader developer audience.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/sesv2/

**Comment by aBurmeseDev** [comment]
Hi @MohammedAbidNafi - thank you for bringing this up. 

We can confirm that bun functions similarly to other package managers when working with the AWS JavaScript SDK. While the team does not currently have plans to include it in our official documentation, this decision may be reconsidered in the future. Thanks again for reaching out!
