### ISSUE TITLE
Release scripts publish redundant data in CHANGELOG

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#691]
**Describe the bug**
Release scripts publish redundant data in CHANGELOG

Publish [v0.6.0](https://github.com/aws/aws-sdk-js-v3/releases/tag/v0.6.0)
* Commit https://github.com/aws/aws-sdk-js-v3/commit/2af97025b4fb46cab7e7cebbd7b763b9d494594f
* It added the following content in CHANGELOG (minimized)
  ```console
  # 0.1.0-preview.5 (2019-10-30)
  # 0.4.0 (2019-09-19)
  # 0.3.0 (2019-09-09)
  ```

Publish [v0.7.0](https://github.com/aws/aws-sdk-js-v3/releases/tag/v0.7.0)
* Commit https://github.com/aws/aws-sdk-js-v3/commit/45338abda5de396fac9378cfc5089f9ba454d418
* It added the following content in CHANGELOG (minimized)
  ```console
  # 0.1.0-preview.6 (2019-11-19)
  # 0.6.0 (2019-10-30)
  # 0.4.0 (2019-09-19)
  # 0.3.0 (2019-09-09)
  ```

**To Reproduce (observed behavior)**
Can be reproduced by following private release scripts, and creating v0.9.0 - but not recommended. Analyze release script code, logs from the past and documentation for dependencies used.

**Expected behavior**
The CHANGELOG contains changes specific to that particular release which includes new version number of the package and changes in the new version

**Comment by trivikr** [comment]
This work needs to be prioritized as CHANGELOG.md file size is increasing everyday with lot of redundant data.

Refs: https://github.com/aws/aws-sdk-js-v3/pull/1111

**Comment by trivikr** [comment]
This issue would be fixed once we move to fixed versioning in https://github.com/aws/aws-sdk-js-v3/pull/1577

The cleanup of previous changelog would still be required.

**Comment by alexforsyth** [comment]
fixed
