### ISSUE TITLE
GitHub shows already released packages in release note

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#731]
**Describe the bug**
GitHub shows already released packages in release note
* Example releases:
  * [v1.0.0-alpha.5](https://github.com/aws/aws-sdk-js-v3/releases/tag/v1.0.0-alpha.5)
  * [v1.0.0-alpha.4](https://github.com/aws/aws-sdk-js-v3/releases/tag/v1.0.0-alpha.4)
* Note that following packages are repeated:
  * @aws-sdk/signature-v4@v1.0.0-alpha.4
  * @aws-sdk/config-resolver@v1.0.0-alpha.4
  * @aws-sdk/middleware-signing@v1.0.0-alpha.4
  * and so one

**To Reproduce (observed behavior)**
Examine releases mentioned above. Examine repeated packages in future releases

**Expected behavior**
If a new version of package is not released, it shouldn't be documented in "Updated packages" list

Refs: https://github.com/aws/aws-sdk-js-v3/issues/692

**Comment by trivikr** [comment]
In internal release scripts, we run the following command to get list of updated packages:
```console
node node_modules/lerna/cli.js changed --toposort --all --long --loglevel silent
```

**Comment by alexforsyth** [comment]
Fixed
