### ISSUE TITLE
fix pixl-xml to avoid importing 'fs' and 'util' module

### ISSUE THREAD

**Issue by AllanFly120** [aws/aws-sdk-js-v3#735]
**Describe the bug**
Our dependency pixl-xml [has dependency over node module `fs` and `util`](https://github.com/jhuckaby/pixl-xml/blob/67a470dad7319c88b6ab086562d0ba48a866d722/xml.js#L27-L28). We need this dependency work in browser without pollyfill. And we are not using these 2 dependencies. But these 2 node module makes all our xml clients hard to be bundled for browser.

**Is the issue in the browser/Node.js?**
All XML/Query/EC2 clients

**Additional context**
We should vendor or fork this dependency to make it compatible with browser without excessive bundling config

**Comment by trivikr** [comment]
Can be repro'd in commit https://github.com/trivikr/aws-sdk-js-tests/commit/6f03fca07d7245c745a4eff390431c807773f62e of private branch [`s3-signer-test`](https://github.com/trivikr/aws-sdk-js-tests/commits/s3-signer-test)
Steps to test in browser: https://github.com/trivikr/aws-sdk-js-tests/tree/s3-signer-test#browser

Error by webpack on running `yarn watch`:
```console
ERROR in ./node_modules/pixl-xml/xml.js
Module not found: Error: Can't resolve 'fs' in '/Users/trivikr/workspace/aws-sdk-js-tests/node_modules/pixl-xml'
 @ ./node_modules/pixl-xml/xml.js 27:9-22
 @ ./node_modules/@aws-sdk/client-s3/dist/cjs/protocols/Aws_restXml.js
 @ ./node_modules/@aws-sdk/client-s3/dist/cjs/commands/UploadPartCopyCommand.js
 @ ./node_modules/@aws-sdk/client-s3/dist/cjs/index.js
 @ ./src/index.js
```

**Comment by Amplifiyer** [comment]
This is causing failures in react native as well (both expo and CLI)

```
error: bundling failed: Error: Unable to resolve module `fs` from 
`node_modules/pixl-xml/xml.js`: fs could not be found within the project
```

```
The package at "node_modules/pixl-xml/xml.js" attempted to import the 
Node standard library module "fs". It failed because React Native does 
not include the Node standard library. Read more at 
https://docs.expo.io/versions/latest/introduction/faq/#can-i-use-nodejs-packages-with-expo
Failed building JavaScript bundle.
```

**Comment by trivikr** [comment]
There's an existing open request from 2017 to make pixl-xml work in browsers at https://github.com/jhuckaby/pixl-xml/issues/14, but there's no update

**Comment by trivikr** [comment]
fast-xml-parser works in both Node.js and browsers and appears to be a good alternative https://github.com/NaturalIntelligence/fast-xml-parser

Comparison on npmtrends https://www.npmtrends.com/pixl-xml-vs-fast-xml-parser
![Screen Shot 2020-01-29 at 3 20 37 PM](https://user-images.githubusercontent.com/16024985/73406338-0f320a80-42ab-11ea-9361-333409a94c19.png)

**Comment by AllanFly120** [comment]
I did a quick look at the `fast-xml-parser`, looks awesome. I think it wasn't this popular when I chose `pixl-xml` late 2017. Its JSON to XML ability can potentially replace our `@aws-sdk/xml-builder` package, but for now we can only focus on parsing the xml side. I'm totally go for it if it won't bring significant change to our xml protocol codegen.

**Comment by trivikr** [comment]
Parsing comparison with default options between `pixl-xml` and `fast-xml-parser`
https://github.com/trivikr/xml-parser-comparison#compare-parsing-of-xml

**Comment by trivikr** [comment]
fast-xml-parser parses values as string, int, boolean, float, hexadecimal
Unit test code https://github.com/NaturalIntelligence/fast-xml-parser/blob/cbdd45bfa3b8685de25ca93497fe04bf873c8108/spec/xmlParser_spec.js#L8-L29

It can be disabled in fast-xml-parser by setting `parseNodeValue` to `false` in options
https://github.com/NaturalIntelligence/fast-xml-parser/blob/cbdd45bfa3b8685de25ca93497fe04bf873c8108/spec/xmlParser_spec.js#L57-L72

pixl-xml returns all values as strings

**Comment by trivikr** [comment]
Verified that the issue is not reproducible with:
```
    "@aws-sdk/client-cognito-identity": "^1.0.0-alpha.16",
    "@aws-sdk/client-s3": "^1.0.0-alpha.11",
    "@aws-sdk/credential-provider-cognito-identity": "^1.0.0-alpha.14",
```

Commit which verified it https://github.com/trivikr/aws-sdk-js-tests/commit/e7750587790faba1ab02c26e921832d37fd027b2
Repro repo https://github.com/trivikr/aws-sdk-js-tests/commits/s3-signer-test
