### ISSUE TITLE
CI didn't fail for missing dependency of client-s3-control

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#738]
**Describe the bug**
CI didn't fail for missing dependency of client-s3-control

**To Reproduce (observed behavior)**
* client-s3-control was added in https://github.com/aws/aws-sdk-js-v3/pull/729
* The CodeGen commit didn't add dependency `"@aws-sdk/middleware-sdk-s3-control"` https://github.com/aws/aws-sdk-js-v3/pull/729/commits/d0b5d0d8c16a0cbc1f87f5a13336337a6e06b64f
* The CI didn't fail https://github.com/aws/aws-sdk-js-v3/pull/729#issuecomment-574419062
* This issue was caught during release, and was fixed in https://github.com/aws/aws-sdk-js-v3/pull/736

**Expected behavior**
CI should fail if dependency is missing

**Comment by alexforsyth** [comment]
https://github.com/aws/aws-sdk-js-v3/issues/817

**Comment by AllanZhengYP** [comment]
Close this because of duplication. We will provide more updates on #817 .
