### ISSUE TITLE
S3 dependencies version is not up-to-date

### ISSUE THREAD

**Issue by AllanFly120** [aws/aws-sdk-js-v3#739]
**Describe the bug**
https://github.com/aws/aws-sdk-js-v3/blob/ab2f5a724e45ebf21d4326fe572360a942391a07/clients/client-s3/package.json#L28-L67

Although dependencies are marked with `^`, some package manager(e.g. yarn) doesn't use the newest alpha dependencies. Possibly because these packages' `latest` npm tag is marked on earlier alpha version. In the installed `node_modules`, these packages' version `1.0.0-alpha.1` were installed and they were not hoisted.

**Fix**
Update the dependency manually for now to unblock the alpha test users. In the future we need to update the code gen to generated clients with newest dependencies.

**Comment by trivikr** [comment]
Fixed by #745
