### ISSUE TITLE
Misspelled word in readme.md used 367 times

### ISSUE THREAD

**Issue by ajredniwja** [aws/aws-sdk-js-v3#743]
**Describe the issue with documentation**
The word 'modulized' should be 'modularized'

**To Reproduce (observed behavior)**
367 results for misspelled word
Type: modulized in search bar for the repository 

**Expected behavior**
modulized should be changed to modularized since modulized is no word

**Comment by trivikr** [comment]
Closing as the typo was fixed, and no longer appears in the repo https://github.com/aws/aws-sdk-js-v3/search?q=modulized
