### ISSUE TITLE
Runtime issue 'signer.sign is not a function'

### ISSUE THREAD

**Issue by Amplifiyer** [aws/aws-sdk-js-v3#761]
**Describe the bug**
Getting a run time error when calling any AWS service in browser. Below is the full stack trace
```
signer.sign is not a function
    at middleware.js:55
    at step (tslib.es6.js:196)
    at Object.next (tslib.es6.js:127)
    at fulfilled (tslib.es6.js:80)
```

**SDK version number**
 Latest alpha version of aws-sdk-v3

**Is the issue in the browser/Node.js?**
Browser

**Details of the browser/Node.js version**
  Browsers:
    Chrome: 79.0.3945.117
    Safari: 13.0.4

**To Reproduce (observed behavior)**
Calling any AWS service in browser using aws-sdk-v3 causes this run time error.

**Expected behavior**
Error should not be thrown

**Screenshots**

**Additional context**

**Comment by trivikr** [comment]
This happens because of the hack given in https://github.com/aws/aws-sdk-js-v3/issues/185#issuecomment-457030792

**Comment by trivikr** [comment]
Verified that signer.sign() is not required to be passed in our test repo:
* Code: https://github.com/aws-samples/aws-sdk-js-tests/blob/9809dfcb58ab42949bec976aeb9c056d30c039a8/src/index.js#L44-L50
* Steps to test: https://github.com/aws-samples/aws-sdk-js-tests/blob/master/README.md

@Amplifiyer Is this still an issue?

**Comment by Amplifiyer** [comment]
@trivikr the issue was resolved by reverting the hack in https://github.com/aws/aws-sdk-js-v3/issues/185#issuecomment-457030792. Is the correct and recommended way to initialize cognito client is

```js
const cognitoClient = new CognitoIdentityClient({
	region,
	credentials: () => Promise.resolve({} as any),
});
```

**Comment by trivikr** [comment]
Yup, this is the recommended way right now
```javascript
const cognitoClient = new CognitoIdentityClient({
  region,
  credentials: () => Promise.resolve({} as any)
});
```

We'll follow up in #185, and update README.md for `credential-provider-cognito-identity` if this changes.
