### ISSUE TITLE
[feature request] Share VERSION of the package in client

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#795]
**Is your feature request related to a problem? Please describe.**
* In v2, the version of the package can be viewed by printing VERSION as follows:
```javascript
const AWS = require("aws-sdk");
console.log(AWS.VERSION);
```
* As v3 is modular, there's no equivalent global package as per design, and the client package doesn't have key storing it's version number

**Describe the solution you'd like**
* The client object prints it's version in `VERSION` as follows:
```javascript
const { S3 } = require("@aws-sdk/client-s3");
console.log(S3.VERSION);
```
* This applies to the barebones client too:
```javascript
const { S3Client } = require("@aws-sdk/client-s3");
console.log(S3Client.VERSION);
```

**Describe alternatives you've considered**
Running `npm list <PACKAGE_NAME>` to get the version number in the minimal repro repository as follows:
```
$ npm list @aws-sdk/client-s3
└─ @aws-sdk/client-s3@1.0.0-alpha.3
```

**Comment by trivikr** [comment]
Alternatives is requesting importing package.json directly.

CJS
```js
const { version } = require("@aws-sdk/client-s3/package.json");
console.log(version);
```

**Comment by trivikr** [comment]
MJS

```js
import packageJson from "@aws-sdk/client-s3/package.json" assert { type: "json" };

console.log(packageJson.version);
```

**Comment by trivikr** [comment]
Verified that:
* createRequire was added in v12.x: https://nodejs.org/docs/latest-v12.x/api/module.html#module_module_createrequire_filename
* `import.meta.url` is present in v14.x: https://nodejs.org/docs/latest-v14.x/api/esm.html#esm_import_meta_url

**Comment by aBurmeseDev** [comment]
For anyone who comes across this, Lambda team recommended to import version from `@aws-sdk/client-s3/package.json` as mentioned in [this docs](https://docs.aws.amazon.com/lambda/latest/dg/lambda-nodejs.html#nodejs-sdk-included).
```ts
const { version } = require("@aws-sdk/client-s3/package.json");

exports.handler = async () => ({ version });
```
Closing the issue.
