### ISSUE TITLE
Expiration value is incorrect in the return object of fromCognitoIdentity

### ISSUE THREAD

**Issue by Amplifiyer** [aws/aws-sdk-js-v3#809]
**Describe the bug**
Expiration value that is returned from https://github.com/aws/aws-sdk-js-v3/blob/v1.0.0-alpha.14/packages/credential-provider-cognito-identity/src/fromCognitoIdentity.ts#L39 seems to be epoch value divided by 1000

**SDK version number**
@aws-sdk/credential-provider-cognito-identity@1.0.0-alpha.10

**Is the issue in the browser/Node.js?**
Browser

**Details of the browser/Node.js version**
  Browsers:
    Chrome: 79.0.3945.117
    Safari: 13.0.4

**To Reproduce (observed behavior)**
Make a call to fromCognitoIdentity.ts and check the returned expiration value, in my last attempt it was 1580266

**Expected behavior**
Correct epoch timestamp should be returned.

**Screenshots**

**Additional context**

**Comment by trivikr** [comment]
CodeGen for the fix https://github.com/aws/aws-sdk-js-v3/pull/822

**Comment by trivikr** [comment]
Fix released with [v1.0.0-alpha.15](https://github.com/aws/aws-sdk-js-v3/releases/tag/v1.0.0-alpha.15)

@Amplifiyer Can you verify the fix with `@aws-sdk/credential-provider-cognito-identity@1.0.0-alpha.11`?

**Comment by Amplifiyer** [comment]
yes I verified that the fix is working! Thank you!
