### ISSUE TITLE
All commands for a client are getting included in the bundle

### ISSUE THREAD

**Issue by Amplifiyer** [aws/aws-sdk-js-v3#823]
**Describe the bug**
When importing an aws client using below import syntax
```js
import {
	PinpointClient,
	PutEventsCommand,
	PutEventsCommandInput,
	UpdateEndpointCommand,
	GetUserEndpointsCommand,
} from '@aws-sdk/client-pinpoint';
```

we are seeing all commands for pinpoint included in the bundle

**SDK version number**

**Is the issue in the browser/Node.js?**
Browser

**Details of the browser/Node.js version**
  Browsers:
    Chrome: 79.0.3945.117
    Safari: 13.0.4

**To Reproduce (observed behavior)**
* Create a react app
* Import aws-sdk/client-pinpoint and few commands. 
* Build the production app by running `npm run build --prod`
* Check the bundle using webpack analyzer or source-map-explorer.

**Expected behavior**
Only commands imported should be part of the bundle.

**Screenshots**

**Additional context**

**Comment by Amplifiyer** [comment]
<img width="701" alt="Screen Shot 2020-01-30 at 2 35 54 PM" src="https://user-images.githubusercontent.com/51211245/73497014-a8762500-436e-11ea-9d1a-2e0f8d039453.png">

**Comment by AllanFly120** [comment]
This is related to #734 Webpack doesn't strip out unused commands because they are imported from a CJS module.

**Comment by AllanFly120** [comment]
Fixed here: https://github.com/aws/aws-sdk-js-v3/issues/734#issuecomment-581712169

**Comment by trivikr** [comment]
Verified as follows:

```console
$ npx create-react-app verify-823 
$ cd verify-823 
$ yarn build --prod
...
File sizes after gzip:

  39.85 KB  build/static/js/2.b7e05ea9.chunk.js
  779 B     build/static/js/runtime-main.125eb46c.js
  614 B     build/static/js/main.194a24c2.chunk.js
  556 B     build/static/css/main.d1b05096.chunk.css
...

$ yarn add @aws-sdk/client-pinpoint@1.0.0-alpha.11

$ # add the following code to src/App.js
$ # import {Pinpoint, PutEventsCommand} from '@aws-sdk/client-pinpoint';
$ # const client = new Pinpoint({});
$ # client.send(new PutEventsCommand({}));

$ yarn build --prod
...
File sizes after gzip:

  86.18 KB (+46.33 KB)  build/static/js/2.3bd1fbe9.chunk.js
  779 B                 build/static/js/runtime-main.125eb46c.js
  664 B (+50 B)         build/static/js/main.bd2da39a.chunk.js
  556 B                 build/static/css/main.d1b05096.chunk.css
...

$ yarn add @aws-sdk/client-pinpoint@1.0.0-alpha.12
$ yarn build --prod
...
File sizes after gzip:

  79.21 KB (-6.98 KB)  build/static/js/2.ce048a13.chunk.js
  779 B                build/static/js/runtime-main.125eb46c.js
  649 B (-15 B)        build/static/js/main.cceeb303.chunk.js
  556 B                build/static/css/main.d1b05096.chunk.css
...
```

**Comment by trivikr** [comment]
source-map-explorer output with `source-map-explorer "build/static/js/*.js" --only-mapped`

`@aws-sdk/client-pinpoint@1.0.0-alpha.11`
  
<img width="712" alt="result-1 0 0-alpha 11" src="https://user-images.githubusercontent.com/16024985/73877148-01c9d280-480d-11ea-87f7-0bb99669e5c4.png">

`@aws-sdk/client-pinpoint@1.0.0-alpha.12`

<img width="713" alt="result-1 0 0-alpha 12" src="https://user-images.githubusercontent.com/16024985/73877163-07bfb380-480d-11ea-9b96-c82992a9ca2b.png">

Some mapping is missed because of issue with CRA https://github.com/facebook/create-react-app/issues/8430
