### ISSUE TITLE
Bundlephobia shows size of individual Command exports as 18kB

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#840]
**Describe the bug**
Bundlephobia shows size of individual Command exports as ~18kB

**SDK version number**
```console
@aws-sdk/client-dynamodb@1.0.0-alpha.14
```

**To Reproduce (observed behavior)**
* https://bundlephobia.com/result?p=@aws-sdk/client-dynamodb@1.0.0-alpha.14
* As per the analysis, DynamoDBClient (16.0kB) and PutItemCommand (17.8kB) adds to more than DynamoDB (30.9kB)

**Expected behavior**
The export size of individual commands must be smaller

**Screenshots**
![Screen Shot 2020-02-03 at 8 25 54 PM](https://user-images.githubusercontent.com/16024985/73713774-709b1480-46c3-11ea-8fbd-1e4cb1560826.png)

**Comment by AllanFly120** [comment]
IMO client and commands have the same dependencies, I don't think you can add up their size simply. I tried the S3 bundle manually, the exports analysis doesn't tally with my bundler results

**Comment by trivikr** [comment]
ToDo: verification of the bundle sizes when several commands are imported.
If the bug is with BundlePhobia, we need to create an issue there
