### ISSUE TITLE
Rekognition/Textract APIs that require images as input are not working

### ISSUE THREAD

**Issue by Amplifiyer** [aws/aws-sdk-js-v3#854]
**Describe the bug**
Passing the same input as V2 in V3 request object, results in empty request payload sent to the service.
Repro repo: https://github.com/Amplifiyer/aws-sdk-js-tests/tree/rekognitionClient

**SDK version number**
`"@aws-sdk/client-rekognition": "^1.0.0-alpha.14",`

**Is the issue in the browser/Node.js?**
Browser

**Details of the browser/Node.js version**
  Browsers:
    Chrome: 79.0.3945.117
    Safari: 13.0.4

**To Reproduce (observed behavior)**
* Clone the repro repo and run.
* Upload a small image file having some text in it.
* See the results of V2 and V3.

Observe that request payload is empty
![Screen Shot 2020-02-04 at 7 42 34 PM](https://user-images.githubusercontent.com/51211245/73808974-858cac00-4786-11ea-8a3d-428a83984819.png)

and the response from the server is
```
{"__type":"ValidationException","message":"1 validation error detected: Value 
'java.nio.HeapByteBuffer[pos=0 lim=0 cap=0]' at 'image.bytes' failed to 
satisfy constraint: Member must have length greater than or equal to 1"}
```

**Expected behavior**
There shouldn't be any failures.

**Screenshots**

**Additional context**

**Comment by AllanFly120** [comment]
Not strictly an issue, you need to convert the image binaries to `Uint8Array` before sending the request. See https://github.com/Amplifiyer/aws-sdk-js-tests/pull/1 for more information.

**Comment by trivikr** [comment]
Related: https://github.com/aws/aws-sdk-js-v3/issues/771#issuecomment-579053290
