### ISSUE TITLE
Update Jest dependency in all packages to ^21

### ISSUE THREAD

**Issue by jeskew** [aws/aws-sdk-js-v3#87]

**Comment by trivikr** [comment]
I tried to update jest in [`trivikr:update-jest`](https://github.com/trivikr/aws-sdk-js-v3/commits/update-jest)
The test failures are documented in the commit https://github.com/trivikr/aws-sdk-js-v3/commit/1ad0705940dcd35325ccf892d45471051975c533

As of now, I've fixed couple of them:
* Expected value mismatch in `"Unable to locate secure random source"` in https://github.com/trivikr/aws-sdk-js-v3/commit/cb81ff62b44e49e8faf76e4a2cfac41e91dc88b2
* Change JSON to Error Object in https://github.com/trivikr/aws-sdk-js-v3/commit/0066bf456ae26c367c3a2fa788a8814e8455f4af

Pending:
* `ReferenceError: defaultRegion is not defined`
* `TypeError: Cannot read property 'byteLength' of undefined`
* `No file coverage available`
* `Your test suite must contain at least one test.`

I'll find sometime next weekend to revisit fixing these tests.
If you do take a look at the commits - do comment on this issue on how to fix the remaining, or even better - push the fixes to `trivikr:update-jest`

**Comment by trivikr** [comment]
Closing as we updated jest to v24 in #243
