### ISSUE TITLE
[React Native] Error: FileReader.readAsArrayBuffer is not implemented

### ISSUE THREAD

**Issue by Amplifiyer** [aws/aws-sdk-js-v3#881]
**Describe the bug**
React Native uses https://www.npmjs.com/package/whatwg-fetch for fetch which calls FileReader.readAsArrayBuffer() and it's not implemented in React Native libraries https://github.com/facebook/react-native/blob/master/Libraries/Blob/FileReader.js#L84-L86
```
[Error: FileReader.readAsArrayBuffer is not implemented]
 WARN  Possible Unhandled Promise Rejection (id: 0):
Error: FileReader.readAsArrayBuffer is not implemented
readAsArrayBuffer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:33230:24
readBlobAsArrayBuffer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30062:31
```

**SDK version number**
Latest alpha versions

**Is the issue in the browser/Node.js?**
React Native

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`

**To Reproduce (observed behavior)**
Run a react native app and see the error.

**Expected behavior**
No errors.

** Hacky workaround **
Putting [this](https://gitmemory.com/issue/facebook/react-native/21209/495294672) in the client app (Not the amplify library) solved it in meantime so I can continue testing

**Screenshots**

**Additional context**

**Comment by AllanFly120** [comment]
Fixed in: https://github.com/aws/aws-sdk-js-v3/releases/tag/v1.0.0-alpha.22
