### ISSUE TITLE
[DynamoDB] Support for Transactions?

### ISSUE THREAD

**Issue by maxgr0** [aws/aws-sdk-js-v3#884]
**Is your feature request related to a problem? Please describe.**
Transactions like `TransactWriteItems` are supported in the current official version of the DynamoDB-Client for JS. Could not find any matching commands in the source of the `@aws-sdk/client-dynamodb-node`.

**Describe the solution you'd like**
A similar command to execute transactional writes, updates or deletes would be nice.

**Describe alternatives you've considered**
Considered implementing the functionality myself and open a PR. 

Is it worth it to take on the problem myself and open a PR or will this feature be released in sooner versions?

**Comment by srchase** [comment]
@maxgr0 

Transaction operations are supported on the alpha tagged version of @aws-sdk/client-dynamodb.

Once #901 is resolved, you can do ```npm i @aws-sdk/client-dynamodb@alpha``` to install that version of the client.

**Comment by maxgr0** [comment]
> @maxgr0
> 
> Transaction operations are supported on the alpha tagged version of @aws-sdk/client-dynamodb.
> 
> Once #901 is resolved, you can do `npm i @aws-sdk/client-dynamodb@alpha` to install that version of the client.

Thanks mate! But using yarn it should be possible to install the alpha without #901  being solved, right?

**Comment by srchase** [comment]
Yes, @trivikr posted an example of a workaround using yarn.
