### ISSUE TITLE
LEX api is failing at runtime with "TypeError: Cannot read property 'contentType' of null"

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#892]
**Describe the bug**
LEX api is failing at runtime with "TypeError: Cannot read property 'contentType' of null"

**SDK version number**
@aws-sdk/client-lex-runtime-service@1.0.0-alpha.15

**Is the issue in the browser/Node.js?**
Browser

**To Reproduce (observed behavior)**
* Code: https://github.com/trivikr/aws-sdk-js-tests/blob/d0aa4eed077efaab3ce0e6e7e9bb4baf526f474b/src/index.js
* Branch: https://github.com/trivikr/aws-sdk-js-tests/tree/lex-signature-error

**Expected behavior**
There should be no runtime error

**Comment by trivikr** [comment]
Refs: https://github.com/aws/aws-sdk-js-v3/issues/810#issuecomment-583672972

**Comment by Amplifiyer** [comment]
After the fix in #810 I'm getting this error as well.

**Comment by srchase** [comment]
This issue was fixed in https://github.com/aws/aws-sdk-js-v3/pull/872 with the corresponding codegen in https://github.com/aws/aws-sdk-js-v3/pull/879

Can you confirm if this is an issue in v1.0.0-alpha.20 or later?

**Comment by srchase** [comment]
See also: https://github.com/aws/aws-sdk-js-v3/issues/871

**Comment by Amplifiyer** [comment]
This is fixed for me in the recent release.

**Comment by srchase** [comment]
👍 

Confirmed as working with last release.

**Comment by trivikr** [comment]
Verified that the issue is fixed in `@aws-sdk/client-lex-runtime-service@1.0.0-alpha.16`
* Code: https://github.com/trivikr/aws-sdk-js-tests/blob/d0aa4eed077efaab3ce0e6e7e9bb4baf526f474b/src/index.js
* Branch: https://github.com/trivikr/aws-sdk-js-tests/tree/lex-signature-error
* Upgrade commit: https://github.com/trivikr/aws-sdk-js-tests/commit/ee5ce92560a4a344353b5c971d3a4dd05c054795
