### ISSUE TITLE
Access Analyzer client has invalid enpdoints

### ISSUE THREAD

**Issue by srchase** [aws/aws-sdk-js-v3#923]
**Describe the bug**
Invalid endpoints for Access Analyzer client:

https://github.com/aws/aws-sdk-js-v3/blob/debed62c47656377be305b1e0b9412adcb22b578/clients/client-accessanalyzer/endpoints.ts#L4-L8

**SDK version number**
`@aws-sdk/client-accessanalyzer@1.0.0-alpha.6`

**Is the issue in the browser/Node.js?**
N/A

**To Reproduce (observed behavior)**
Attempt to make any requests with Access Analyzer

Receive `Error: getaddrinfo ENOTFOUND replace-for-service-name.us-west-2.amazonaws.com`

**Expected behavior**
Request succeeds

**Comment by AllanFly120** [comment]
Fixed in https://github.com/aws/aws-sdk-js-v3/pull/945
