### ISSUE TITLE
S3:ListObjects doesn't work with new alpha clients

### ISSUE THREAD

**Issue by Amplifiyer** [aws/aws-sdk-js-v3#930]
**Describe the bug**
Listing from public/ directory causes the request URL to be https://analytics3d5167b766084a44803d0ccb49a6eb66-devoa.s3.us-west-2.amazonaws.com/?prefix=public%252F
which then fails with AccessDenied Error

**SDK version number**
Latest versions of alpha clients

**Is the issue in the browser/Node.js?**
Browser

**Details of the browser/Node.js version**
  Browsers:
    Chrome: 79.0.3945.117
    Safari: 13.0.4

**Comment by srchase** [comment]
Requires additional fix from https://github.com/aws/aws-sdk-js-v3/pull/935

**Comment by srchase** [comment]
Confirmed that each of the following work with [@aws-sdk/client-s3@1.0.0-alpha.17](https://www.npmjs.com/package/@aws-sdk/client-s3/v/1.0.0-alpha.17):

```
(async () => {
    const client = new S3({region: "us-west-2"})
    await client.listObjects({
        Bucket: "fooBucket",
        Prefix: "foo(",
    }).then((res) => {
        console.log(res);
    }).catch((err) => {
        console.log(err);
    });
})();
```

```
(async () => {
    const client = new S3({region: "us-west-2"})
    await client.listObjects({
        Bucket: "fooBucket",
        Prefix: "foo/",
    }).then((res) => {
        console.log(res);
    }).catch((err) => {
        console.log(err);
    });
})();
```
