### ISSUE TITLE
[secretsmanager]: when can Name be undefined?

### ISSUE THREAD

**Issue by G-Rath** [aws/aws-sdk-js-v3#932]
The `Name` property is typed as being optional in a number of places, such as `DescribeSecretResponse`, and `string | undefined` for `CreateSecretRequest`.

I've also noticed the `SecretId` is apparently optional for commands like `GetSecretValueRequest` - is this correct?

I've attempted to confirm this, but no matter what I do I can't create a secret without a name: 

![image](https://user-images.githubusercontent.com/3151613/74625127-16fd1480-51b0-11ea-86bf-521d0f58c022.png)

```
~/c/tr/portal WOR-2126-add-missing-alert-types *5 ❯ aws secretsmanager create-secret                                    Ruby 2.5.1 17:52:02
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:
  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: the following arguments are required: --name
```

**Comment by AllanFly120** [comment]
Looks like you are using AWS CLI instead of JS SDK. Can you open the issue on their side? https://github.com/aws/aws-cli. 
I will close this ticket for now. Let me know if you want it reopened

**Comment by G-Rath** [comment]
@AllanFly120 you've misunderstood: im referring to the type definitions of this library.

I used the cli test if it was possible for `Name` to be null, as I assume it uses the same underlying endpoint.

Ill link to the types directly in a few minutes once I'm at my laptop.

**Comment by G-Rath** [comment]
Here is an example:

https://github.com/aws/aws-sdk-js-v3/blob/3c06325c4425756dcda2bb2bc6f6424cf902db20/clients/node/client-secrets-manager-node/types/DeleteSecretOutput.ts#L15

**Comment by bhowell2** [comment]
I second this issue. I'm currently only doing something with the S3 client, but I imagine optionals have been used in this codebase to short-circuit some typescript . This has almost defeated the purpose of typescript (the type completion is nice at least, but the safety is lacking).

E.g., When listing the objects of an S3 bucket the returned `_Object` type has an optional `Key`? Is this ever the case? Is it ever the case that `Size`, `Etag`, etc. are also not returned?

https://github.com/aws/aws-sdk-js-v3/blob/88a823e09bb274f851f86dadc851eefff671cc94/clients/client-s3/models/index.ts#L6945

Now I'm having to write code to check if the `Key` exists for an object?
```javascript 
if (s3Obj.Key) {
  // now do something with the key...
}
// or have to do s3Obj.Key!, which feels dirty and antithetical to typescript...
```

**Comment by trivikr** [comment]
Using `| undefined` is a thought out decision explained in https://github.com/aws/aws-sdk-js-v3/issues/1124#issuecomment-622004875

**Comment by trivikr** [comment]
The Name is optional in DescribeSecretResponse, as it's not marked as `required` in model

* Code https://github.com/aws/aws-sdk-js-v3/blob/master/clients/client-secrets-manager/models/index.ts#L501-L504
* Model https://github.com/aws/aws-sdk-js-v3/blob/e19fc4feea5268442370af97e266c982beef4210/codegen/sdk-codegen/aws-models/secrets-manager.2017-10-17.json#L1594-L1602

required trait in Smithy https://awslabs.github.io/smithy/1.0/spec/core/constraint-traits.html?highlight=required#required-trait

The name is optional is AWS JavaScript v2 too
Code: https://github.com/aws/aws-sdk-js/blob/5b51b4e3297f0f1f13d66eaff0c2e8ad5473de49/clients/secretsmanager.d.ts#L285-L288

**Comment by alexforsyth** [comment]
Closing as last comment was July 9
