### ISSUE TITLE
Lambda StatusCode missing in V3 Smithy code gen

### ISSUE THREAD

**Issue by mullermp** [aws/aws-sdk-js-v3#942]
**Describe the bug**
Lambda's StatusCode is missing in v3 Smithy codegen but exists in master.

**Additional context**
Status code exists here: https://github.com/aws/aws-sdk-js-v3/blob/master/models/lambda/2015-03-31/service-2.json#L1869

Status code is not a member here: https://github.com/aws/aws-sdk-js-v3/blob/smithy-codegen/models/lambda.2015-03-31.json#L2881

Official docs (https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html#API_Invoke_ResponseSyntax)

"StatusCode
The HTTP status code is in the 200 range for a successful request. For the RequestResponse invocation type, this status code is 200. For the Event invocation type, this status code is 202. For the DryRun invocation type, the status code is 204."

**Comment by ajredniwja** [comment]
Should not be an issue anymore as a model was shipped after the issue was opened:

https://github.com/aws/aws-sdk-js-v3/blob/master/codegen/sdk-codegen/aws-models/lambda.2015-03-31.json#L3750

Closing this issue now.
