### ISSUE TITLE
Credentials not reset between commands

### ISSUE THREAD

**Issue by GrahamFord** [aws/aws-sdk-js-v3#943]
**Describe the bug**
Send an Iam command with credentials containing a correct key but incorrect secret. An error is thrown as expected.
Subsequently send a command with the correct key and secret. The updated credentials are not recognised as being correct.

**SDK version number**
"@aws-sdk/client-iam-node": "0.1.0-preview.2"

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
v12.12.0

**To Reproduce (observed behavior)**
https://repl.it/@GrahamFord/AWS-IAM-demo

Replace the values of the credentials as appropriate for testing. 

**Expected behavior**
When passed valid credentials, the users details should be returned

**Screenshots**

**Additional context**

**Comment by AllanFly120** [comment]
Thank you for bringing this up! I'm closing this issue because we recently moved to alpha clients. See [here](https://github.com/aws/aws-sdk-js-v3/issues/944) for more information. Please post a new issue if the bug persists.
