### ISSUE TITLE
👉 New Gamma Clients Are Available!

### ISSUE THREAD

**Issue by AllanZhengYP** [aws/aws-sdk-js-v3#944]
**UPDATE 06/05/20**: *Gamma* version is available now. You can install the beta clients by:
```
npm install @aws-sdk/client-s3@gamma
```
or 
```
yarn add @aws-sdk/client-s3@gamma
```
====================================================================

**UPDATE**: *Beta* version is available now. You can install the beta clients by:
```
npm install @aws-sdk/client-s3@beta
```
or 
```
yarn add @aws-sdk/client-s3@beta
```
====================================================================

We recently released alpha version of our the V2 clients. It's the next incremental release of the existing preview clients. You can install them by specifying the `alpha` tag, like below:

```
npm install @aws-sdk/client-s3@alpha
```
or if you are using Yarn:

```
yarn add @aws-sdk/client-s3@alpha
```

(**Note**: alpha clients doesn't distinguish `-node` or `-browser` packages. You can remove them from all the package names)

You can adopt the new version as an experiment and see if they fix the issues from previous version. If you adopt the alpha version, you **should** uninstall all the `preview` packages from `@aws-sdk` organization and reinstall them with `alpha` tag.

A lot of new features and bugfixings are introduced. Here are some highlights:
1. No breaking change since preview version except for a few exceptions:
    * remove runtime from package name.
    * middleware stack uses `low|normal|high` instead of number to represent priority
1. Each client comes with NodeJS, browsers, and ReactNative support, you don't need to change anything to bundle your code targeting at above runtimes.
1. Each client comes with additional ESM that achieve smaller code footprint. 
1. SDK can resolve all public AWS partitions(e.g. US gov, ISO, China) from the `region` config.

We appriciate your time and feedbacks since V3 launched preview and we hope you can keep it coming. We will be more actively working on this project in coming months, especially the higher level features like S3 multipart upload, DynamoDB document client.

**Comment by roborourke** [comment]
Thanks for this, and your continued work on improving the JS SDK.

I tried out the difference between `0.1.0-preview.2` and `1.0.0-alpha.23` in my application which includes the following imports but unfortunately the alpha seems to give me a bundle about 25Kb larger.

Preview version:

```js
import { CognitoIdentityClient } from "@aws-sdk/client-cognito-identity-browser/CognitoIdentityClient";
import { GetCredentialsForIdentityCommand } from "@aws-sdk/client-cognito-identity-browser/commands/GetCredentialsForIdentityCommand";
import { GetIdCommand } from "@aws-sdk/client-cognito-identity-browser/commands/GetIdCommand";
import { PinpointClient } from "@aws-sdk/client-pinpoint-browser/PinpointClient";
import { PutEventsCommand } from "@aws-sdk/client-pinpoint-browser/commands/PutEventsCommand";
```

Alpha version:

```
import {
 	CognitoIdentityClient,
 	GetCredentialsForIdentityCommand,
 	GetIdCommand
} from "@aws-sdk/client-cognito-identity";
import { 
 	PinpointClient, 
 	PutEventsCommand 
} from "@aws-sdk/client-pinpoint";
```

I ran CPD against the bundle output for both eg:

```
pmd cpd --files build.js --minimum-tokens 100 --language javascript
```

With the alpha version it seems there's a lot of duplicated code in the client objects, each with its own copy of the crypto & signing libraries etc from what I could gather.

This is still a huge improvement over v2 either way but wanted to flag this with you incase it helps.

**Comment by trivikr** [comment]
Thank you @roborourke for reporting increase in bundle size.
It's documented at https://github.com/aws/aws-sdk-js-v3/issues/693, and will be prioritized at some point.

**Comment by zsid** [comment]
There have been issues with the sdk not being able to get the appropriate scopes i.e. `openid`, `custom scopes` etc. This is still persisting in the current stable version and I am wondering whether it will be addressed in this new version.

There is a feature [request](https://github.com/aws/aws-sdk-js-v3/issues/1090)  which I am not sure if that is a feature or a bug.

What is your view on that?

**Comment by zedsinn** [comment]
> There have been issues with the sdk not being able to get the appropriate scopes i.e. `openid`, `custom scopes` etc. This is still persisting in the current stable version and I am wondering whether it will be addressed in this new version.
> 
> There is a feature [request](https://github.com/aws/aws-sdk-js-v3/issues/1090) which I am not sure if that is a feature or a bug.
> 
> What is your view on that?

I am also eager to hear if this will be implemented or not.

**Comment by zsid** [comment]
@AllanFly120, @trivikr  what are your thoughts on my question above about scopes?

**Comment by matej-prokop** [comment]
Is there any public roadmap for this project? I would like to know when we can expect:
1. `DynamoDB document client` to arrive
1. public (stable) release of Dynamo DB client

**Comment by Syy0n** [comment]
Any updates on when a stable release will be published?

**Comment by trivikr** [comment]
We've published Release Candidate versions, and written a blog post at https://aws.amazon.com/blogs/developer/modular-aws-sdk-for-javascript-release-candidate/

Closing this issue in favor of blog post.
