### ISSUE TITLE
AutoScaling member deser returns too early

### ISSUE THREAD

**Issue by AllanZhengYP** [aws/aws-sdk-js-v3#948]
**Describe the bug**
See #947 

**Is the issue in the browser/Node.js?**
Browser/Node.js

**Expected behavior**
We shouldn't return here:
https://github.com/aws/aws-sdk-js-v3/blob/3049f3dc78aa8be8775de0440c73041db3f4f130/clients/client-auto-scaling/protocols/Aws_query.ts#L8152-L8155

It results all other members are always `undefined` when this array is empty

**Comment by AllanFly120** [comment]
Close this this it's duplicated with #947
