### ISSUE TITLE
Backwards compatibility of error codes from v2 to v3

### ISSUE THREAD

**Issue by seebees** [aws/aws-sdk-js-v3#978]
**Is your feature request related to a problem? Please describe.**

When migrating from v2 to v3
I do not want to have to completely change my error handling.
I _can_ do string matches on error messages,
but this is brittle and easy to get wrong.
In SDK v2 errors have a `code`  https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Response.html#error-property
but in v3 this "information" is moved to `name`.
How do I easily us v3 into my existing code?

**Describe the solution you'd like**

Map the error values in v2 `code` onto the v3 Error object.

**Describe alternatives you've considered**

Do nothing. It may be that the direction of the v3 SDK is to not deal with backwards compatibility.
_Some_ change to the code seems likely.
If _full_ backwards compatibility is not an issue,
perhaps this not as important.

**Additional context**

**Comment by AllanFly120** [comment]
After discussion with the team, we believe this is a feature that we don't want to be compatible with V2. Firstly, `Error.name` is more idiomatic the JavaScript language, so it is more familiar to new users not migrating from V2. Moreover, using syntax like `InvalidArnException.isa(err)` encapsulates the details of the `InvalidArnException` interface. This may makes the code more robust to breaking change in errors. The `isa(a)` function is a [type prediction statement](https://www.typescriptlang.org/docs/handbook/advanced-types.html#using-type-predicates), it's a more elegant way to cast catched error(`any`) to individual types, compare the type casting.
