### ISSUE TITLE
Rename `.rn.ts` files to `.native.ts` files

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#990]
**Is your feature request related to a problem? Please describe.**
Rename `.rn.ts` files to `.native.ts` files
* React Native target was added in https://github.com/awslabs/smithy-typescript/pull/125
* CodeGen for adding RN target https://github.com/aws/aws-sdk-js-v3/pull/903

**Describe the solution you'd like**
Use `.native.js` extension instead
* it's recommended in react-native docs https://reactnative.dev/docs/platform-specific-code#native-specific-extensions-ie-sharing-code-with-nodejs-and-web
* it's used elsewhere on GitHub https://github.com/search?q=filename%3A*.native.js

**Describe alternatives you've considered**
Stick with using `.rn.js` as we do it now

**Comment by AllanFly120** [comment]
Just to add more information. This change won't bring structural change other than better naming convention. Because we are using `react-native` key word in `package.json`, the files with `.native` extension won't be effective in bundling.
