### ISSUE TITLE
`DnsName` isn't a field in GameLift describe-player-sessions' output

### ISSUE THREAD

**Issue by therealsamf** [aws/aws-sdk-js-v3#991]
**Describe the bug**
`DnsName` is a valid & necessary field to include in the [`_PlayerSession`](https://github.com/aws/aws-sdk-js-v3/blob/master/clients/node/client-gamelift-node/types/_PlayerSession.ts) type and it appears it is missing.

**SDK version number**
0.1.0-preview.2

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
v10.16.0

**To Reproduce (observed behavior)**
Stand up AWS GameLift fleet
Create AWS GameLift game session
Reserve a player session

```node
const { GameLiftClient, DescribePlayerSessionsCommand } = require('@aws-sdk/client-gamelift-node')
const gamelift = new GameLiftClient({ region: 'us-east-1' })
const command = new DescribePlayerSessionsCommand({ PlayerSessionId: '***' })
gamelift.send(command).then((data) => { console.dir(data); });
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events:
      [Object: null prototype] {
        removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function: debugDomainError] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [],
     [Symbol(kWeak)]: WeakReference {} } }
{ PlayerSessions:
   [ { PlayerSessionId: '***',
       PlayerId: '***',
       GameSessionId: '***',
       FleetId: '***',
       CreationTime: 2020-03-10T05:04:03.888Z,
       TerminationTime: 2020-03-10T05:05:03.916Z,
       Status: 'TIMEDOUT',
       IpAddress: '***',
       Port: ***,
       PlayerData: '{}' } ],
  '$metadata':
   { httpHeaders:
      { 'x-amzn-requestid': '65333717-c8c0-47fa-90df-fcd7b4c2bbbe',
        'content-type': 'application/x-amz-json-1.1',
        'content-length': '720',
        date: 'Tue, 10 Mar 2020 05:29:09 GMT' },
     httpStatusCode: 200,
     requestId: '65333717-c8c0-47fa-90df-fcd7b4c2bbbe',
     extendedRequestId: undefined,
     cfId: undefined,
     retries: 0,
     totalRetryDelay: 0 } }
```

**Expected behavior**
`DnsName` field should be included to the response in addition to `IpAddress`, which already exists.

**Screenshots**

**Additional context**

**Comment by AllanFly120** [comment]
Thank you for bringing this up! I'm closing this issue because we recently moved to alpha clients. See [here](https://github.com/aws/aws-sdk-js-v3/issues/944) for more information. Please post a new issue if the bug persists.
